{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"backgroundImage","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"barMetrics","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","text":"UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The background image to use for "},{"type":"codeVoice","code":"barMetrics"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"backgroundImage"},{"content":[{"inlineContent":[{"type":"text","text":"A bar metrics constant."}],"type":"paragraph"}],"name":"barMetrics"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Equivalent to using ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)","isActive":true,"type":"reference"},{"text":" with a position of ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/any","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Sets the background image for given bar metrics."}],"sections":[],"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)"],"anchor":"Changing-the-background","title":"Changing the background"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:)"]}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setBackgroundImage(_:for:)","navigatorTitle":[{"text":"setBackgroundImage:forBarMetrics:","kind":"identifier"}],"modules":[{"name":"UIKit"}],"symbolKind":"method","externalID":"c:objc(cs)UINavigationBar(im)setBackgroundImage:forBarMetrics:","platforms":[{"deprecated":false,"name":"iOS","introducedAt":"5.0","unavailable":false,"beta":false},{"deprecated":false,"name":"iPadOS","introducedAt":"5.0","unavailable":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"beta":false}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor":{"type":"topic","title":"barTintColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barTintColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uinavigationbar/bartintcolor","navigatorTitle":[{"text":"barTintColor","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The tint color to apply to the navigation bar background."}]},"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/any":{"kind":"symbol","title":"UIBarPosition.any","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"any"}],"url":"/documentation/uikit/uibarposition/any","abstract":[{"type":"text","text":"Specifies that the position is unspecified."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/any","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIBarPositionAny"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)","kind":"symbol","title":"backgroundImage(for:barMetrics:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundImageForBarPosition:barMetrics:"}],"abstract":[{"text":"Returns the background image to use for a given bar position and set of metrics.","type":"text"}],"url":"/documentation/uikit/uinavigationbar/backgroundimage(for:barmetrics:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier","text":"UIBarPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barMetrics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)":{"role":"symbol","url":"/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:barmetrics:)","navigatorTitle":[{"text":"setBackgroundImage:forBarPosition:barMetrics:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barMetrics","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)","abstract":[{"type":"text","text":"Sets the background image to use for a given bar position and set of metrics."}],"kind":"symbol","title":"setBackgroundImage(_:for:barMetrics:)","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)":{"kind":"symbol","title":"backgroundImage(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"url":"/documentation/uikit/uinavigationbar/backgroundimage(for:)","abstract":[{"type":"text","text":"Returns the background image for given bar metrics."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"backgroundImageForBarMetrics:"}]},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics":{"navigatorTitle":[{"text":"UIBarMetrics","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIBarMetrics","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uibarmetrics","title":"UIBarMetrics","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Constants to specify metrics to use for appearance."}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)":{"kind":"symbol","title":"setBackgroundImage(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:)","abstract":[{"type":"text","text":"Sets the background image for given bar metrics."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setBackgroundImage:forBarMetrics:"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","beta":false,"introducedAt":"5.0","unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"introducedAt":"5.0","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"setBackgroundImage:forBarMetrics:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBackgroundImage:forBarMetrics:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Changing-the-background","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)"],"generated":true,"title":"Changing the background"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setBackgroundImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"backgroundImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forBarMetrics:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","text":"UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"barMetrics","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The background image to use for "},{"code":"barMetrics","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"backgroundImage"},{"content":[{"inlineContent":[{"type":"text","text":"A bar metrics constant."}],"type":"paragraph"}],"name":"barMetrics"}]},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","value":"barTintColor","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barTintColor/title"},{"op":"replace","value":[{"text":"barTintColor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barTintColor/fragments"},{"op":"replace","value":"UIBarPositionAny","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition~1any/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIBarPositionAny"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition~1any/fragments"},{"op":"replace","value":"UIImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title"},{"op":"replace","value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIImage"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle"},{"op":"replace","value":"backgroundImageForBarPosition:barMetrics:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:barMetrics:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backgroundImageForBarPosition:barMetrics:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:barMetrics:)/fragments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:barMetrics:)/title","op":"replace","value":"setBackgroundImage:forBarPosition:barMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:barMetrics:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackgroundImage:forBarPosition:barMetrics:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title","op":"replace","value":"UINavigationBar"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments","op":"replace","value":[{"kind":"identifier","text":"UINavigationBar"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UINavigationBar"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:)/title","op":"replace","value":"backgroundImageForBarMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backgroundImageForBarMetrics:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/title","op":"replace","value":"UIBarMetrics"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/fragments","op":"replace","value":[{"kind":"identifier","text":"UIBarMetrics"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIBarMetrics"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:)/title","op":"replace","value":"setBackgroundImage:forBarMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackgroundImage:forBarMetrics:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}