{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"backgroundImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"barPosition","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition","text":"UIBarPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarPosition"},{"text":", ","kind":"text"},{"text":"barMetrics","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","text":"UIBarMetrics","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The image to use for the specified location and metrics.","type":"text"}],"type":"paragraph"}],"name":"backgroundImage"},{"content":[{"inlineContent":[{"type":"text","text":"The location of the navigation bar."}],"type":"paragraph"}],"name":"barPosition"},{"content":[{"inlineContent":[{"type":"text","text":"The metrics of the navigation bar."}],"type":"paragraph"}],"name":"barMetrics"}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Resizable images will be stretched vertically, if necessary, for a position of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/topAttached","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"sections":[],"abstract":[{"text":"Sets the background image to use for a given bar position and set of metrics.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","platforms":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"7.0","deprecated":false},{"beta":false,"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS"},{"beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS"}],"modules":[{"name":"UIKit"}],"role":"symbol","externalID":"c:objc(cs)UINavigationBar(im)setBackgroundImage:forBarPosition:barMetrics:","title":"setBackgroundImage(_:for:barMetrics:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarPosition","text":"UIBarPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barMetrics"},{"text":": ","kind":"text"},{"text":"UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setBackgroundImage:forBarPosition:barMetrics:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:barmetrics:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:barmetrics:)"]}],"kind":"symbol","seeAlsoSections":[{"anchor":"Changing-the-background","title":"Changing the background","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)","kind":"symbol","title":"backgroundImage(for:barMetrics:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundImageForBarPosition:barMetrics:"}],"abstract":[{"text":"Returns the background image to use for a given bar position and set of metrics.","type":"text"}],"url":"/documentation/uikit/uinavigationbar/backgroundimage(for:barmetrics:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier","text":"UIBarPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barMetrics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)":{"kind":"symbol","title":"backgroundImage(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"url":"/documentation/uikit/uinavigationbar/backgroundimage(for:)","abstract":[{"type":"text","text":"Returns the background image for given bar metrics."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"backgroundImageForBarMetrics:"}]},"doc://com.apple.uikit/documentation/UIKit/UIBarPosition":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIBarPosition"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIBarPosition"}],"title":"UIBarPosition","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition","type":"topic","url":"/documentation/uikit/uibarposition","abstract":[{"type":"text","text":"Constants to identify the position of a bar."}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)":{"kind":"symbol","title":"setBackgroundImage(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:)","abstract":[{"type":"text","text":"Sets the background image for given bar metrics."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setBackgroundImage:forBarMetrics:"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics":{"navigatorTitle":[{"text":"UIBarMetrics","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIBarMetrics","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uibarmetrics","title":"UIBarMetrics","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Constants to specify metrics to use for appearance."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)":{"role":"symbol","url":"/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:barmetrics:)","navigatorTitle":[{"text":"setBackgroundImage:forBarPosition:barMetrics:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barMetrics","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)","abstract":[{"type":"text","text":"Sets the background image to use for a given bar position and set of metrics."}],"kind":"symbol","title":"setBackgroundImage(_:for:barMetrics:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/topAttached":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topAttached","kind":"identifier"}],"role":"symbol","title":"UIBarPosition.topAttached","url":"/documentation/uikit/uibarposition/topattached","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/topAttached","navigatorTitle":[{"text":"UIBarPositionTopAttached","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Specifies that the bar is at the top of the screen, as well as its containing view."}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor":{"type":"topic","title":"barTintColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barTintColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uinavigationbar/bartintcolor","navigatorTitle":[{"text":"barTintColor","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The tint color to apply to the navigation bar background."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"7.0","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"7.0","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"setBackgroundImage:forBarPosition:barMetrics:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setBackgroundImage:forBarPosition:barMetrics:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"path":"/hierarchy","op":"replace"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)"],"anchor":"Changing-the-background","title":"Changing the background","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setBackgroundImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage"},{"text":" *) ","kind":"text"},{"text":"backgroundImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forBarPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UIBarPosition","text":"UIBarPosition","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition"},{"text":") ","kind":"text"},{"text":"barPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barMetrics:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","text":"UIBarMetrics","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics"},{"text":") ","kind":"text"},{"text":"barMetrics","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The image to use for the specified location and metrics."}],"type":"paragraph"}],"name":"backgroundImage"},{"content":[{"inlineContent":[{"text":"The location of the navigation bar.","type":"text"}],"type":"paragraph"}],"name":"barPosition"},{"content":[{"inlineContent":[{"type":"text","text":"The metrics of the navigation bar."}],"type":"paragraph"}],"name":"barMetrics"}]}},{"op":"replace","value":"backgroundImageForBarPosition:barMetrics:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:barMetrics:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"backgroundImageForBarPosition:barMetrics:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:barMetrics:)/fragments"},{"op":"replace","value":"backgroundImageForBarMetrics:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"backgroundImageForBarMetrics:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:)/fragments"},{"op":"replace","value":"UIBarPosition","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition/title"},{"op":"replace","value":[{"text":"UIBarPosition","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition/fragments"},{"op":"replace","value":[{"text":"UIBarPosition","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition/navigatorTitle"},{"op":"replace","value":"setBackgroundImage:forBarMetrics:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackgroundImage:forBarMetrics:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:)/fragments"},{"op":"replace","value":"UINavigationBar","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title"},{"op":"replace","value":[{"text":"UINavigationBar","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments"},{"op":"replace","value":[{"text":"UINavigationBar","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle"},{"op":"replace","value":"UIBarMetrics","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIBarMetrics"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIBarMetrics"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/navigatorTitle"},{"op":"replace","value":"UIImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIImage"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments"},{"op":"replace","value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle"},{"op":"replace","value":"setBackgroundImage:forBarPosition:barMetrics:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:barMetrics:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBackgroundImage:forBarPosition:barMetrics:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:barMetrics:)/fragments"},{"op":"replace","value":"UIBarPositionTopAttached","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition~1topAttached/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIBarPositionTopAttached"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition~1topAttached/fragments"},{"op":"replace","value":"barTintColor","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barTintColor/title"},{"op":"replace","value":[{"kind":"identifier","text":"barTintColor"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barTintColor/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}