{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setItems"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)UINavigationBar(im)setItems:animated:","modules":[{"name":"UIKit"}],"navigatorTitle":[{"text":"setItems:animated:","kind":"identifier"}],"role":"symbol","platforms":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false,"introducedAt":"2.0"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"2.0"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0"}],"symbolKind":"method","title":"setItems(_:animated:)"},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/pushItem(_:animated:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/popItem(animated:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/items","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/topItem","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backItem"],"generated":true,"title":"Pushing and popping items","anchor":"Pushing-and-popping-items"}],"kind":"symbol","variants":[{"paths":["/documentation/uikit/uinavigationbar/setitems(_:animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uinavigationbar/setitems(_:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setItems(_:animated:)"},"abstract":[{"type":"text","text":"Replaces the navigation items currently managed by the navigation bar with the specified items."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"parameters":[{"name":"items","content":[{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem","type":"reference"},{"type":"text","text":" objects to place in the stack. The front-to-back order of the items in this array represents the new bottom-to-top order of the items in the navigation stack. Thus, the last item added to the array becomes the top item of the navigation stack."}],"type":"paragraph"}]},{"name":"animated","content":[{"inlineContent":[{"type":"text","text":"If "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":", animate the pushing or popping of the top stack item. If "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":", replace the stack items without any animations."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"You can use this method to update or replace the navigation items in the stack without pushing or popping each item explicitly. In addition, this method lets you update the stack without animating the changes, which might be appropriate at launch time when you want to restore the state of the navigation stack to some previous state.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"If animations are enabled, this method decides which type of transition to perform based on whether the last item in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/items"},{"text":" array is already on the current navigation stack. If the item is currently on the stack, but is not the topmost item, this method uses a pop transition; if it is the topmost item, no transition is performed. If the item is not on the stack, this method uses a push transition. Only one transition is performed, but when that transition finishes, the entire contents of the stack are replaced with the new items. For example, if items A, B, and C are on the stack and you set items D, A, and B, this method uses a pop transition and the resulting stack contains the items D, A, and B.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setItems(_:animated:)":{"role":"symbol","url":"/documentation/uikit/uinavigationbar/setitems(_:animated:)","abstract":[{"type":"text","text":"Replaces the navigation items currently managed by the navigation bar with the specified items."}],"type":"topic","title":"setItems(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setItems"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setItems:animated:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setItems(_:animated:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/popItem(animated:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"popItem"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/popItem(animated:)","type":"topic","abstract":[{"type":"text","text":"Pops the top item from the navigation bar’s stack and updates the UI."}],"url":"/documentation/uikit/uinavigationbar/popitem(animated:)","navigatorTitle":[{"text":"popNavigationItemAnimated:","kind":"identifier"}],"title":"popItem(animated:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/topItem":{"type":"topic","abstract":[{"text":"The navigation item at the top of the navigation bar’s stack.","type":"text"}],"kind":"symbol","url":"/documentation/uikit/uinavigationbar/topitem","navigatorTitle":[{"kind":"identifier","text":"topItem"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/topItem","role":"symbol","title":"topItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"topItem","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationItem","kind":"typeIdentifier","text":"UINavigationItem"},{"kind":"text","text":"?"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/items":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"items","kind":"identifier"}],"title":"items","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/items","type":"topic","url":"/documentation/uikit/uinavigationbar/items","abstract":[{"type":"text","text":"An array of navigation items managed by the navigation bar."}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/pushItem(_:animated:)":{"abstract":[{"type":"text","text":"Pushes the given navigation item onto the navigation bar’s stack and updates the UI."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushItem"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UINavigationItem","kind":"typeIdentifier","text":"UINavigationItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushNavigationItem:animated:"}],"title":"pushItem(_:animated:)","url":"/documentation/uikit/uinavigationbar/pushitem(_:animated:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/pushItem(_:animated:)"},"doc://com.apple.uikit/documentation/UIKit/UINavigationItem":{"title":"UINavigationItem","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem","abstract":[{"text":"The items that a navigation bar displays when the associated view controller is visible.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UINavigationItem","kind":"identifier"}],"url":"/documentation/uikit/uinavigationitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UINavigationItem","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backItem":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"backItem","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationItem","kind":"typeIdentifier","text":"UINavigationItem"},{"kind":"text","text":"?"}],"type":"topic","title":"backItem","url":"/documentation/uikit/uinavigationbar/backitem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backItem","navigatorTitle":[{"kind":"identifier","text":"backItem"}],"abstract":[{"text":"The navigation item that is immediately below the topmost item on a navigation bar’s stack.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"2.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"2.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","path":"/metadata/title","value":"setItems:animated:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setItems:animated:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Pushing-and-popping-items","title":"Pushing and popping items","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/pushItem(_:animated:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/popItem(animated:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/items","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/topItem","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backItem"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setItems:"},{"kind":"text","text":"("},{"text":"NSArray<UINavigationItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"items","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem","isActive":true},{"type":"text","text":" objects to place in the stack. The front-to-back order of the items in this array represents the new bottom-to-top order of the items in the navigation stack. Thus, the last item added to the array becomes the top item of the navigation stack."}]}],"name":"items"},{"content":[{"inlineContent":[{"type":"text","text":"If "},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":", animate the pushing or popping of the top stack item. If "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":", replace the stack items without any animations."}],"type":"paragraph"}],"name":"animated"}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setItems(_:animated:)/title","op":"replace","value":"setItems:animated:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setItems(_:animated:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setItems:animated:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1popItem(animated:)/title","op":"replace","value":"popNavigationItemAnimated:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1popItem(animated:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"popNavigationItemAnimated:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1topItem/title","op":"replace","value":"topItem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1topItem/fragments","op":"replace","value":[{"kind":"identifier","text":"topItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1items/title","op":"replace","value":"items"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1items/fragments","op":"replace","value":[{"text":"items","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1pushItem(_:animated:)/title","op":"replace","value":"pushNavigationItem:animated:"},{"value":[{"text":"- ","kind":"text"},{"text":"pushNavigationItem:animated:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1pushItem(_:animated:)/fragments","op":"replace"},{"value":"UINavigationItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/title","op":"replace"},{"value":[{"text":"UINavigationItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UINavigationItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/navigatorTitle","op":"replace"},{"value":"UINavigationBar","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title","op":"replace"},{"value":[{"text":"UINavigationBar","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UINavigationBar"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle","op":"replace"},{"value":"backItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backItem/title","op":"replace"},{"value":[{"kind":"identifier","text":"backItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backItem/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}