{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context","type":"reference"},{"text":" object initializes the value of","type":"text"},{"text":" ","type":"text"},{"text":"this property at creation time. Use this value to identify the","type":"text"},{"text":" ","type":"text"},{"text":"context object within your app.","type":"text"}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/identifier"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context"]]},"metadata":{"modules":[{"name":"AppKit"}],"platforms":[{"beta":false,"deprecated":false,"introducedAt":"15.2","name":"macOS","unavailable":false}],"externalID":"c:objc(cs)NSWritingToolsCoordinatorContext(py)identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"identifier","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"}]},"variants":[{"paths":["/documentation/appkit/nswritingtoolscoordinator/context/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswritingtoolscoordinator/context/identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The unique identifier of the context object.","type":"text"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator":{"abstract":[{"text":"An object that manages interactions between Writing Tools and","type":"text"},{"text":" ","type":"text"},{"text":"your custom text view.","type":"text"}],"type":"topic","title":"NSWritingToolsCoordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSWritingToolsCoordinator","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator","role":"symbol","url":"/documentation/appkit/nswritingtoolscoordinator","navigatorTitle":[{"text":"NSWritingToolsCoordinator","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/identifier":{"title":"identifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"url":"/documentation/appkit/nswritingtoolscoordinator/context/identifier","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"}],"abstract":[{"type":"text","text":"The unique identifier of the context object."}]},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Context"}],"abstract":[{"type":"text","text":"A data object that you use to share your custom view’s text with Writing Tools."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Context"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context","url":"/documentation/appkit/nswritingtoolscoordinator/context","title":"NSWritingToolsCoordinator.Context","kind":"symbol"},"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV":{"role":"symbol","title":"UUID","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV","type":"topic","fragments":[{"kind":"text","text":"struct "},{"text":"UUID","kind":"identifier"}],"kind":"symbol","url":"/documentation/foundation/uuid","abstract":[{"text":"A universally unique value to identify types, interfaces, and other items.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"18.2","name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"15.2","name":"macOS","beta":false,"unavailable":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"identifier"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"identifier","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSUUID","kind":"typeIdentifier","text":"NSUUID"},{"kind":"text","text":" * "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"NSWritingToolsCoordinator","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSWritingToolsCoordinator"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWritingToolsCoordinator"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/navigatorTitle","op":"replace"},{"value":"identifier","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1identifier/title","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1identifier/fragments","op":"replace"},{"value":"NSWritingToolsCoordinatorContext","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/title","op":"replace"},{"value":[{"text":"NSWritingToolsCoordinatorContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWritingToolsCoordinatorContext"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}