{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"range"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"mentions":["doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview"],"kind":"mentions"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context","type":"reference","isActive":true},{"type":"text","text":" object initializes the value of this property"},{"type":"text","text":" "},{"type":"text","text":"at creation time. Use this value to identify the context object within your app."}],"type":"paragraph"}]}],"metadata":{"modules":[{"name":"AppKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"range","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"}],"title":"range","navigatorTitle":[{"text":"range","kind":"identifier"}],"role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"15.2"}],"externalID":"c:objc(cs)NSWritingToolsCoordinatorContext(py)range","symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/range","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context"]]},"variants":[{"paths":["/documentation/appkit/nswritingtoolscoordinator/context/range"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswritingtoolscoordinator/context/range"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/attributedString"],"title":"Getting the source text details","generated":true,"anchor":"Getting-the-source-text-details"}],"abstract":[{"type":"text","text":"The unique identifier of the context object."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/range":{"role":"symbol","title":"range","type":"topic","navigatorTitle":[{"text":"range","kind":"identifier"}],"url":"/documentation/appkit/nswritingtoolscoordinator/context/range","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/range","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"range","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The unique identifier of the context object."}]},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator":{"abstract":[{"text":"An object that manages interactions between Writing Tools and","type":"text"},{"text":" ","type":"text"},{"text":"your custom text view.","type":"text"}],"type":"topic","title":"NSWritingToolsCoordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSWritingToolsCoordinator","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator","role":"symbol","url":"/documentation/appkit/nswritingtoolscoordinator","navigatorTitle":[{"text":"NSWritingToolsCoordinator","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview":{"role":"article","abstract":[{"text":"Integrate Writing Tools support, including support for inline replacement","type":"text"},{"text":" ","type":"text"},{"text":"animations, to your custom text views on macOS.","type":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview","url":"/documentation/appkit/adding-writing-tools-support-to-a-custom-nsview","title":"Adding Writing Tools support to a custom AppKit view","kind":"article"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Context"}],"abstract":[{"type":"text","text":"A data object that you use to share your custom view’s text with Writing Tools."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Context"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context","url":"/documentation/appkit/nswritingtoolscoordinator/context","title":"NSWritingToolsCoordinator.Context","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/attributedString":{"role":"symbol","title":"attributedString","type":"topic","navigatorTitle":[{"text":"attributedString","kind":"identifier"}],"url":"/documentation/appkit/nswritingtoolscoordinator/context/attributedstring","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/attributedString","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"attributedString","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"}],"abstract":[{"type":"text","text":"The portion of your view’s text to evaluate."}]},"doc://com.externally.resolved.symbol/c:@S@_NSRange":{"role":"symbol","type":"topic","abstract":[{"text":"A Swift-only concrete structure that backs the range type alias.","type":"text"}],"url":"/documentation/foundation/nsrange-jio","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"_NSRange"}],"identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","title":"_NSRange"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"introducedAt":"18.2","unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"introducedAt":"15.2","unavailable":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"range","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"range","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Getting-the-source-text-details","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/attributedString"],"title":"Getting the source text details","generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSRange","identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSRange"},{"text":" ","kind":"text"},{"text":"range","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1range/title","value":"range","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1range/fragments","value":[{"text":"range","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/title","value":"NSWritingToolsCoordinator","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/fragments","value":[{"kind":"identifier","text":"NSWritingToolsCoordinator"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/navigatorTitle","value":[{"text":"NSWritingToolsCoordinator","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/title","value":"NSWritingToolsCoordinatorContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/fragments","value":[{"kind":"identifier","text":"NSWritingToolsCoordinatorContext"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/navigatorTitle","value":[{"text":"NSWritingToolsCoordinatorContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1attributedString/title","value":"attributedString","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1attributedString/fragments","value":[{"kind":"identifier","text":"attributedString"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}