{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context"]]},"abstract":[{"type":"text","text":"The actual range of text that Writing Tools might change, which can"},{"type":"text","text":" "},{"type":"text","text":"be different than the range of text you supplied."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolvedRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"After analyzing the text in your context object, Writing Tools sets","type":"text"},{"text":" ","type":"text"},{"text":"this property to the portion of ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/attributedString","isActive":true},{"text":" it might modify.","type":"text"},{"text":" ","type":"text"},{"text":"Initially, this property has a location of","type":"text"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsnotfound","isActive":true},{"text":" and a length","type":"text"},{"text":" ","type":"text"},{"text":"of ","type":"text"},{"code":"0","type":"codeVoice"},{"text":", but Writing Tools updates those values before making any changes","type":"text"},{"text":" ","type":"text"},{"text":"to the text.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"While the Writing Tools operation is active, make sure Writing Tools has"},{"type":"text","text":" "},{"type":"text","text":"exclusive access to the text in this range. Your "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Delegate-swift.protocol","isActive":true},{"type":"text","text":" "},{"type":"text","text":"object can make changes to the text as part of incorporating Writing Tools"},{"type":"text","text":" "},{"text":"results, but don’t allow changes to come from other sources. For example,","type":"text"},{"text":" ","type":"text"},{"text":"don’t let someone edit the text in this range directly until Writing Tools finishes.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/appkit/nswritingtoolscoordinator/context/resolvedrange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswritingtoolscoordinator/context/resolvedrange"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/resolvedRange","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolvedRange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"resolvedRange","kind":"identifier"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"15.2","beta":false}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)NSWritingToolsCoordinatorContext(py)resolvedRange","title":"resolvedRange","role":"symbol"},"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/resolvedRange":{"url":"/documentation/appkit/nswritingtoolscoordinator/context/resolvedrange","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolvedRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The actual range of text that Writing Tools might change, which can","type":"text"},{"text":" ","type":"text"},{"text":"be different than the range of text you supplied.","type":"text"}],"navigatorTitle":[{"text":"resolvedRange","kind":"identifier"}],"title":"resolvedRange","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/resolvedRange"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/attributedString":{"role":"symbol","title":"attributedString","type":"topic","navigatorTitle":[{"text":"attributedString","kind":"identifier"}],"url":"/documentation/appkit/nswritingtoolscoordinator/context/attributedstring","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context/attributedString","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"attributedString","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"}],"abstract":[{"type":"text","text":"The portion of your view’s text to evaluate."}]},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Delegate-swift.protocol":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Delegate-swift.protocol","kind":"symbol","navigatorTitle":[{"text":"Delegate","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSWritingToolsCoordinator.Delegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Delegate","kind":"identifier"}],"abstract":[{"text":"An interface that you use to manage interactions between Writing Tools","type":"text"},{"text":" ","type":"text"},{"text":"and your custom text view.","type":"text"}],"url":"/documentation/appkit/nswritingtoolscoordinator/delegate-swift.protocol"},"doc://com.externally.resolved.symbol/c:@S@_NSRange":{"role":"symbol","type":"topic","abstract":[{"text":"A Swift-only concrete structure that backs the range type alias.","type":"text"}],"url":"/documentation/foundation/nsrange-jio","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"_NSRange"}],"identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","title":"_NSRange"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Context"}],"abstract":[{"type":"text","text":"A data object that you use to share your custom view’s text with Writing Tools."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Context"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context","url":"/documentation/appkit/nswritingtoolscoordinator/context","title":"NSWritingToolsCoordinator.Context","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator":{"abstract":[{"text":"An object that manages interactions between Writing Tools and","type":"text"},{"text":" ","type":"text"},{"text":"your custom text view.","type":"text"}],"type":"topic","title":"NSWritingToolsCoordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSWritingToolsCoordinator","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator","role":"symbol","url":"/documentation/appkit/nswritingtoolscoordinator","navigatorTitle":[{"text":"NSWritingToolsCoordinator","kind":"identifier"}]},"doc://com.apple.documentation/documentation/foundation/nsnotfound":{"title":"NSNotFound","identifier":"doc://com.apple.documentation/documentation/foundation/nsnotfound","url":"/documentation/foundation/nsnotfound","role":"symbol","abstract":[{"type":"text","text":"A value indicating that a requested item couldn’t be found or doesn’t exist."}],"type":"topic","fragments":[{"kind":"text","text":"let "},{"kind":"identifier","text":"NSNotFound"},{"kind":"text","text":": Int"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"18.2","name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"15.2","name":"macOS","deprecated":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","op":"replace","value":"resolvedRange"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"resolvedRange","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@_NSRange","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@S@_NSRange","text":"NSRange"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolvedRange"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1resolvedRange/title","op":"replace","value":"resolvedRange"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1resolvedRange/fragments","op":"replace","value":[{"kind":"identifier","text":"resolvedRange"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1attributedString/title","op":"replace","value":"attributedString"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context~1attributedString/fragments","op":"replace","value":[{"text":"attributedString","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Delegate-swift.protocol/title","op":"replace","value":"NSWritingToolsCoordinatorDelegate"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Delegate-swift.protocol/fragments","op":"replace","value":[{"text":"NSWritingToolsCoordinatorDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Delegate-swift.protocol/navigatorTitle","op":"replace","value":[{"text":"NSWritingToolsCoordinatorDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/title","op":"replace","value":"NSWritingToolsCoordinatorContext"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/fragments","op":"replace","value":[{"text":"NSWritingToolsCoordinatorContext","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/navigatorTitle","op":"replace","value":[{"text":"NSWritingToolsCoordinatorContext","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/title","op":"replace","value":"NSWritingToolsCoordinator"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/fragments","op":"replace","value":[{"text":"NSWritingToolsCoordinator","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/navigatorTitle","op":"replace","value":[{"text":"NSWritingToolsCoordinator","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}