{
  "abstract": [
    {
      "text": "A prefix that multiplies the base unit by 1e6.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/mega"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKMetricPrefix@HKMetricPrefixMega",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mega"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKMetricPrefixMega"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKMetricPrefix.mega"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mega"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix": {
      "abstract": [
        {
          "text": "Prefixes that can be added to SI units to change the order of magnitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetricPrefix"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefix"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/centi": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 0.01.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centi"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/centi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixCenti"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.centi",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/centi"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/deca": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 10.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deca"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/deca",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixDeca"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.deca",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/deca"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/deci": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 0.1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deci"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/deci",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixDeci"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.deci",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/deci"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/femto": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 1e-15.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "femto"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/femto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixFemto"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.femto",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/femto"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/giga": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 1e9.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "giga"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/giga",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixGiga"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.giga",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/giga"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/hecto": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 100.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hecto"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/hecto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixHecto"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.hecto",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/hecto"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/kilo": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 1000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kilo"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/kilo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixKilo"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.kilo",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/kilo"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/mega": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 1e6.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mega"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/mega",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixMega"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.mega",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/mega"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/micro": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 1e-6.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "micro"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/micro",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixMicro"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.micro",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/micro"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/milli": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 0.001.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "milli"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/milli",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixMilli"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.milli",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/milli"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/nano": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 1e-9.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nano"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/nano",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixNano"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.nano",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/nano"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/none": {
      "abstract": [
        {
          "text": "A prefix that does not modify the base unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixNone"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.none",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/none"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/pico": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 1e-12.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pico"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/pico",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixPico"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.pico",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/pico"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/tera": {
      "abstract": [
        {
          "text": "A prefix that multiplies the base unit by 1e12.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tera"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/tera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetricPrefixTera"
        }
      ],
      "role": "symbol",
      "title": "HKMetricPrefix.tera",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetricprefix/tera"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Prefixes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/none",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/femto",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/pico",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/nano",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/micro",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/milli",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/centi",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/deci",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/deca",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/hecto",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/kilo",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/giga",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/tera"
      ],
      "title": "Prefixes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKMetricPrefixMega"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixMega"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Prefixes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/none",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/femto",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/pico",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/nano",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/micro",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/milli",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/centi",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/deci",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/deca",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/hecto",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/kilo",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/giga",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetricPrefix/tera"
              ],
              "title": "Prefixes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKMetricPrefixMega"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1nano/title",
          "value": "HKMetricPrefixNano"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1nano/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixNano"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1centi/title",
          "value": "HKMetricPrefixCenti"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1centi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixCenti"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1kilo/title",
          "value": "HKMetricPrefixKilo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1kilo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixKilo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix/title",
          "value": "HKMetricPrefix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1tera/title",
          "value": "HKMetricPrefixTera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1tera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixTera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1femto/title",
          "value": "HKMetricPrefixFemto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1femto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixFemto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1giga/title",
          "value": "HKMetricPrefixGiga"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1giga/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixGiga"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1hecto/title",
          "value": "HKMetricPrefixHecto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1hecto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixHecto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1milli/title",
          "value": "HKMetricPrefixMilli"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1milli/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixMilli"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1none/title",
          "value": "HKMetricPrefixNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1deca/title",
          "value": "HKMetricPrefixDeca"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1deca/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixDeca"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1deci/title",
          "value": "HKMetricPrefixDeci"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1deci/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixDeci"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1mega/title",
          "value": "HKMetricPrefixMega"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1mega/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixMega"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1pico/title",
          "value": "HKMetricPrefixPico"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1pico/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixPico"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1micro/title",
          "value": "HKMetricPrefixMicro"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetricPrefix~1micro/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetricPrefixMicro"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkmetricprefix/mega"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkmetricprefix/mega"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
