{
  "abstract": [
    {
      "text": "Changes the value of a directional pad element in the virtual controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/setPosition(_:forDirectionPadElement:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCVirtualController(im)setPosition:forDirectionPadElement:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setPosition"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGPoint",
        "text": "CGPoint"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "forDirectionPadElement"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setPosition:forDirectionPadElement:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setPosition(_:forDirectionPadElement:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setPosition"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "position"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGPoint",
              "text": "CGPoint"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "forDirectionPadElement"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "element"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A point with ",
                  "type": "text"
                },
                {
                  "code": "x",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "y",
                  "type": "codeVoice"
                },
                {
                  "text": " values in the range ",
                  "type": "text"
                },
                {
                  "code": "[0.0, 1.0]",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "position"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the directional pad element to update.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "element"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to update the value of a directional pad in the virtual controller when you set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/Configuration/isHidden",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and present your own virtual controller interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController": {
      "abstract": [
        {
          "text": "A software emulation of a real controller that you configure specifically for your game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCVirtualController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCVirtualController"
        }
      ],
      "role": "symbol",
      "title": "GCVirtualController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcvirtualcontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/Configuration/isHidden": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system or the app presents the virtual interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/Configuration/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcvirtualcontroller/configuration/ishidden"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/setPosition(_:forDirectionPadElement:)": {
      "abstract": [
        {
          "text": "Changes the value of a directional pad element in the virtual controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forDirectionPadElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/setPosition(_:forDirectionPadElement:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPosition:forDirectionPadElement:"
        }
      ],
      "role": "symbol",
      "title": "setPosition(_:forDirectionPadElement:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcvirtualcontroller/setposition(_:fordirectionpadelement:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/setValue(_:forButtonElement:)": {
      "abstract": [
        {
          "text": "Changes the value of a button element in the virtual controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forButtonElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/setValue(_:forButtonElement:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValue:forButtonElement:"
        }
      ],
      "role": "symbol",
      "title": "setValue(_:forButtonElement:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcvirtualcontroller/setvalue(_:forbuttonelement:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGPoint": {
      "abstract": [
        {
          "text": "A structure that contains a point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPoint",
      "type": "topic",
      "url": "/documentation/corefoundation/cgpoint"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-a-custom-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/setValue(_:forButtonElement:)"
      ],
      "title": "Presenting a custom interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setPosition:forDirectionPadElement:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPosition:forDirectionPadElement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-a-custom-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCVirtualController/setValue(_:forButtonElement:)"
              ],
              "title": "Presenting a custom interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setPosition:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGPoint",
                    "text": "CGPoint"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "position"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forDirectionPadElement:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "element"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A point with ",
                        "type": "text"
                      },
                      {
                        "code": "x",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "code": "y",
                        "type": "codeVoice"
                      },
                      {
                        "text": " values in the range ",
                        "type": "text"
                      },
                      {
                        "code": "[0.0, 1.0]",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "position"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the directional pad element to update.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "element"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController~1Configuration~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController~1Configuration~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController~1setPosition(_:forDirectionPadElement:)/title",
          "value": "setPosition:forDirectionPadElement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController~1setPosition(_:forDirectionPadElement:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPosition:forDirectionPadElement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController/title",
          "value": "GCVirtualController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCVirtualController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCVirtualController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController~1setValue(_:forButtonElement:)/title",
          "value": "setValue:forButtonElement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCVirtualController~1setValue(_:forButtonElement:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setValue:forButtonElement:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcvirtualcontroller/setposition(_:fordirectionpadelement:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcvirtualcontroller/setposition(_:fordirectionpadelement:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
