{"sections":[],"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(pl)UIAccessibilityContainerDataTable(im)accessibilityDataTableCellElementForRow:column:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDataTableCellElement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forRow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"column","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> (any ","kind":"text"},{"text":"UIAccessibilityContainerDataTableCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIAccessibilityContainerDataTableCell"},{"text":")?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"accessibilityDataTableCellElementForRow:column:","kind":"identifier"}],"modules":[{"name":"UIKit"}],"platforms":[{"name":"iOS","introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","unavailable":false,"introducedAt":"11.0","deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false}],"required":true,"symbolKind":"method","title":"accessibilityDataTableCellElement(forRow:column:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDataTableCellElement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forRow","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"row","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":", ","kind":"text"},{"text":"column","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":") -> (any ","kind":"text"},{"text":"UIAccessibilityContainerDataTableCell","preciseIdentifier":"c:objc(pl)UIAccessibilityContainerDataTableCell","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTableCell"},{"text":")?","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"row","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The row of the cell."}]}]},{"name":"column","content":[{"type":"paragraph","inlineContent":[{"text":"The column of the cell.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The accessibility element for the cell.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Returns the accessibility element for the specified cell.","type":"text"}],"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTable/accessibilityDataTableCellElement(forRow:column:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTable"]]},"variants":[{"paths":["/documentation/uikit/uiaccessibilitycontainerdatatable/accessibilitydatatablecellelement(forrow:column:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiaccessibilitycontainerdatatable/accessibilitydatatablecellelement(forrow:column:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTable/accessibilityDataTableCellElement(forRow:column:)":{"required":true,"type":"topic","url":"/documentation/uikit/uiaccessibilitycontainerdatatable/accessibilitydatatablecellelement(forrow:column:)","role":"symbol","title":"accessibilityDataTableCellElement(forRow:column:)","abstract":[{"type":"text","text":"Returns the accessibility element for the specified cell."}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTable/accessibilityDataTableCellElement(forRow:column:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDataTableCellElement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forRow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"column","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> (any ","kind":"text"},{"text":"UIAccessibilityContainerDataTableCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIAccessibilityContainerDataTableCell"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"accessibilityDataTableCellElementForRow:column:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTable":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTable","role":"symbol","title":"UIAccessibilityContainerDataTable","url":"/documentation/uikit/uiaccessibilitycontainerdatatable","abstract":[{"type":"text","text":"Methods that convey information about the contents of a table."}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIAccessibilityContainerDataTable"}],"navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityContainerDataTable"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTableCell":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTableCell","title":"UIAccessibilityContainerDataTableCell","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIAccessibilityContainerDataTableCell","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityContainerDataTableCell"}],"abstract":[{"type":"text","text":"Methods that provide the location of a cell in a table."}],"role":"symbol","type":"topic","url":"/documentation/uikit/uiaccessibilitycontainerdatatablecell"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger","kind":"symbol","type":"topic","title":"NSUInteger"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false,"name":"iOS"},{"unavailable":false,"beta":false,"introducedAt":"11.0","name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"11.0","name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"accessibilityDataTableCellElementForRow:column:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"accessibilityDataTableCellElementForRow:column:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerDataTable"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIAccessibilityContainerDataTableCell","text":"id<UIAccessibilityContainerDataTableCell>"},{"kind":"text","text":") "},{"text":"accessibilityDataTableCellElementForRow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"row","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"column:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"column","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace"},{"value":{"parameters":[{"name":"row","content":[{"type":"paragraph","inlineContent":[{"text":"The row of the cell.","type":"text"}]}]},{"name":"column","content":[{"type":"paragraph","inlineContent":[{"text":"The column of the cell.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The accessibility element for the cell."}]}]},"op":"replace"},{"value":"accessibilityDataTableCellElementForRow:column:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerDataTable~1accessibilityDataTableCellElement(forRow:column:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityDataTableCellElementForRow:column:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerDataTable~1accessibilityDataTableCellElement(forRow:column:)/fragments"},{"value":"UIAccessibilityContainerDataTable","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerDataTable/title"},{"value":[{"text":"UIAccessibilityContainerDataTable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerDataTable/fragments"},{"value":[{"text":"UIAccessibilityContainerDataTable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerDataTable/navigatorTitle"},{"value":"UIAccessibilityContainerDataTableCell","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerDataTableCell/title"},{"value":[{"text":"UIAccessibilityContainerDataTableCell","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerDataTableCell/fragments"},{"value":[{"text":"UIAccessibilityContainerDataTableCell","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerDataTableCell/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}