{
  "abstract": [
    {
      "text": "A reactive-mask texture input you set for a temporal scaler that supports the",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "correct usage options.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalfx/documentation/MetalFX",
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveMaskTexture"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLFXTemporalScaler(py)reactiveMaskTexture",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "reactiveMaskTexture"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLTexture",
        "text": "MTLTexture"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "MetalFX"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "reactiveMaskTexture"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "reactiveMaskTexture"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reactiveMaskTexture"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLTexture",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This texture helps when objects move quickly in a scene with inaccurate motion information,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "such as when they involve alpha blending.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In these situations, you can get better results by guiding MetalFX whether to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "favor the current frame on a per-pixel basis with a reactive mask texture.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Each pixel needs to be in the range ",
              "type": "text"
            },
            {
              "code": "[0.0, 1.0]",
              "type": "codeVoice"
            },
            {
              "text": ", where a value:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Equal to ",
                      "type": "text"
                    },
                    {
                      "code": "0.0",
                      "type": "codeVoice"
                    },
                    {
                      "text": " tells MetalFX to follow its normal behavior for the corresponding pixel",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Equal to ",
                      "type": "text"
                    },
                    {
                      "code": "1.0",
                      "type": "codeVoice"
                    },
                    {
                      "text": " tells MetalFX to ignore temporal history for the corresponding pixel",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the range ",
                      "type": "text"
                    },
                    {
                      "code": "(0.0, 1.0)",
                      "type": "codeVoice"
                    },
                    {
                      "text": " proportionally blends the effect for the corresponding pixel",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTexture/usage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property of the texture you set to this property needs to be the same as, or a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "superset of, the temporal scaling effect’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Metal/MTLTexture/usage": {
      "abstract": [
        {
          "text": "Options that determine how you can use the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTexture/usage",
      "kind": "symbol",
      "role": "symbol",
      "title": "usage",
      "type": "topic",
      "url": "/documentation/Metal/MTLTexture/usage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalfx/documentation/MetalFX": {
      "abstract": [
        {
          "text": "Boost your Metal app’s performance by upscaling lower-resolution content to save GPU time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalFX",
      "type": "topic",
      "url": "/documentation/metalfx"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler": {
      "abstract": [
        {
          "text": "An upscaling effect that generates a higher resolution texture in a render pass by analyzing multiple input textures over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFXTemporalScaler"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFXTemporalScaler"
        }
      ],
      "role": "symbol",
      "title": "MTLFXTemporalScaler",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveMaskTexture": {
      "abstract": [
        {
          "text": "A reactive-mask texture input you set for a temporal scaler that supports the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "correct usage options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactiveMaskTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveMaskTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reactiveMaskTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reactiveMaskTexture",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/reactivemasktexture"
    },
    "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage": {
      "abstract": [
        {
          "text": "The minimal texture-usage options that your app’s reactive-mask texture",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "input needs to have for the temporal scaler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactiveTextureUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reactiveTextureUsage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reactiveTextureUsage",
      "type": "topic",
      "url": "/documentation/metalfx/mtlfxtemporalscaler/reactivetextureusage"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture": {
      "abstract": [
        {
          "text": "A resource that holds formatted image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLResource",
          "text": "MTLResource"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLTexture",
      "type": "topic",
      "url": "/documentation/Metal/MTLTexture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-reactive-mask-input",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage"
      ],
      "title": "Configuring the reactive mask input"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "reactiveMaskTexture"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reactiveMaskTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalfx/documentation/MetalFX",
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-reactive-mask-input",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalfx/documentation/MetalFX/MTLFXTemporalScaler/reactiveTextureUsage"
              ],
              "title": "Configuring the reactive mask input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)MTLTexture",
                    "text": "id<MTLTexture>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "reactiveMaskTexture"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MTLTexture/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLResource",
              "text": "MTLResource"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLTexture~1usage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLTextureUsage",
              "text": "MTLTextureUsage"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "usage"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reactiveTextureUsage/title",
          "value": "reactiveTextureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reactiveTextureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reactiveTextureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler/title",
          "value": "MTLFXTemporalScaler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFXTemporalScaler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reactiveMaskTexture/title",
          "value": "reactiveMaskTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalfx~1documentation~1MetalFX~1MTLFXTemporalScaler~1reactiveMaskTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reactiveMaskTexture"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalfx/mtlfxtemporalscaler/reactivemasktexture"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalfx/mtlfxtemporalscaler/reactivemasktexture"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
