{
  "abstract": [
    {
      "text": "Create declarative animations that move elements of a scene in predetermined ways, or manage animations imported with external authoring tools.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/animation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Animation"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAction": {
      "abstract": [
        {
          "text": "A simple, reusable animation that changes attributes of any node you attach it to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAction"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAction"
        }
      ],
      "role": "symbol",
      "title": "SCNAction",
      "type": "topic",
      "url": "/documentation/scenekit/scnaction"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNActionable": {
      "abstract": [
        {
          "text": "Methods for running actions on nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNActionable"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNActionable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNActionable"
        }
      ],
      "role": "symbol",
      "title": "SCNActionable",
      "type": "topic",
      "url": "/documentation/scenekit/scnactionable"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimatable": {
      "abstract": [
        {
          "text": "The common interface for attaching animations to nodes, geometries, materials, and other SceneKit objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAnimatable"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimatable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAnimatable"
        }
      ],
      "role": "symbol",
      "title": "SCNAnimatable",
      "type": "topic",
      "url": "/documentation/scenekit/scnanimatable"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimation-swift.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAnimation"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimation-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAnimation"
        }
      ],
      "role": "symbol",
      "title": "SCNAnimation",
      "type": "topic",
      "url": "/documentation/scenekit/scnanimation-swift.class"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationEvent": {
      "abstract": [
        {
          "text": "A container for a closure, a block in Objective-C, to be executed at a specific time during playback of an animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAnimationEvent"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAnimationEvent"
        }
      ],
      "role": "symbol",
      "title": "SCNAnimationEvent",
      "type": "topic",
      "url": "/documentation/scenekit/scnanimationevent"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationPlayer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAnimationPlayer"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAnimationPlayer"
        }
      ],
      "role": "symbol",
      "title": "SCNAnimationPlayer",
      "type": "topic",
      "url": "/documentation/scenekit/scnanimationplayer"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAnimationProtocol"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAnimationProtocol"
        }
      ],
      "role": "symbol",
      "title": "SCNAnimationProtocol",
      "type": "topic",
      "url": "/documentation/scenekit/scnanimationprotocol"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher": {
      "abstract": [
        {
          "text": "An object that manages smooth transitions between a node’s base geometry and one or more target geometries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMorpher"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMorpher"
        }
      ],
      "role": "symbol",
      "title": "SCNMorpher",
      "type": "topic",
      "url": "/documentation/scenekit/scnmorpher"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner": {
      "abstract": [
        {
          "text": "An object that manages the relationship between skeletal animations and the nodes and geometries they animate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSkinner"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSkinner"
        }
      ],
      "role": "symbol",
      "title": "SCNSkinner",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTimingFunction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTimingFunction"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTimingFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTimingFunction"
        }
      ],
      "role": "symbol",
      "title": "SCNTimingFunction",
      "type": "topic",
      "url": "/documentation/scenekit/scntimingfunction"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction": {
      "abstract": [
        {
          "text": "A mechanism for creating implicit animations and combining scene graph changes into atomic updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTransaction"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTransaction"
        }
      ],
      "role": "symbol",
      "title": "SCNTransaction",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content": {
      "abstract": [
        {
          "text": "Learn about implicit animations, explicit animations, and actions, and when to choose each in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content",
      "kind": "article",
      "role": "article",
      "title": "Animating SceneKit Content",
      "type": "topic",
      "url": "/documentation/scenekit/animating-scenekit-content"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/constraints": {
      "abstract": [
        {
          "text": "Automatically adjust the position or orientation of a node based on specified rules.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/constraints",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Constraints",
      "type": "topic",
      "url": "/documentation/scenekit/constraints"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animation-and-Constraints",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/constraints",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher"
      ],
      "title": "Animation and Constraints"
    }
  ],
  "topicSections": [
    {
      "anchor": "First-Steps",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content"
      ],
      "title": "First Steps"
    },
    {
      "anchor": "Actions",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAction",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNActionable"
      ],
      "title": "Actions"
    },
    {
      "anchor": "Implicit-Animation",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction"
      ],
      "title": "Implicit Animation"
    },
    {
      "anchor": "Explicit-Animation",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimatable",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationEvent",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimation-swift.class",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationPlayer",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTimingFunction",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationProtocol",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimation-swift.class"
      ],
      "title": "Explicit Animation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "First-Steps",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content"
              ],
              "title": "First Steps"
            },
            {
              "anchor": "Actions",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAction",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNActionable"
              ],
              "title": "Actions"
            },
            {
              "anchor": "Implicit-Animation",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction"
              ],
              "title": "Implicit Animation"
            },
            {
              "anchor": "Explicit-Animation",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimatable",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationEvent",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimation-swift.class",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationPlayer",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTimingFunction",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimationProtocol",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAnimation-swift.class"
              ],
              "title": "Explicit Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animation-and-Constraints",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/constraints",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher"
              ],
              "title": "Animation and Constraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationProtocol/title",
          "value": "SCNAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/title",
          "value": "SCNTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimatable/title",
          "value": "SCNAnimatable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimatable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimatable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimatable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimatable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTimingFunction/title",
          "value": "SCNTimingFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTimingFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTimingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTimingFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTimingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationPlayer/title",
          "value": "SCNAnimationPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimationPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimationPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/title",
          "value": "SCNMorpher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMorpher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMorpher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimation-swift.class/title",
          "value": "SCNAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimation-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimation-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationEvent/title",
          "value": "SCNAnimationEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimationEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAnimationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNActionable/title",
          "value": "SCNActionable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNActionable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNActionable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNActionable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNActionable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/title",
          "value": "SCNSkinner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSkinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSkinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAction/title",
          "value": "SCNAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/animation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/animation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
