{
  "abstract": [
    {
      "text": "Basic shapes—such as spheres, boxes, and planes—and features for generating 3D objects from 2D text and Bézier curves.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/built-in-geometry-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Built-in Geometry Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBox": {
      "abstract": [
        {
          "text": "A six-sided polyhedron geometry whose faces are all rectangles, optionally with rounded edges and corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNBox"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNBox"
        }
      ],
      "role": "symbol",
      "title": "SCNBox",
      "type": "topic",
      "url": "/documentation/scenekit/scnbox"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule": {
      "abstract": [
        {
          "text": "A right circular cylinder geometry whose ends are capped with hemispheres.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCapsule"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCapsule"
        }
      ],
      "role": "symbol",
      "title": "SCNCapsule",
      "type": "topic",
      "url": "/documentation/scenekit/scncapsule"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCone": {
      "abstract": [
        {
          "text": "A right circular cone or frustum geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCone"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCone"
        }
      ],
      "role": "symbol",
      "title": "SCNCone",
      "type": "topic",
      "url": "/documentation/scenekit/scncone"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder": {
      "abstract": [
        {
          "text": "A right circular cylinder geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCylinder"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCylinder"
        }
      ],
      "role": "symbol",
      "title": "SCNCylinder",
      "type": "topic",
      "url": "/documentation/scenekit/scncylinder"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNFloor": {
      "abstract": [
        {
          "text": "A plane that can optionally display a reflection of the scene above it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNFloor"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNFloor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNFloor"
        }
      ],
      "role": "symbol",
      "title": "SCNFloor",
      "type": "topic",
      "url": "/documentation/scenekit/scnfloor"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry": {
      "abstract": [
        {
          "text": "A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometry",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement": {
      "abstract": [
        {
          "text": "A container for index data describing how vertices connect to define a three-dimensional object, or geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometryElement"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometryElement"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometryElement",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometryelement"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource": {
      "abstract": [
        {
          "text": "A container for vertex data forming part of the definition for a three-dimensional object, or geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometrySource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometrySource"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometrySource",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometrysource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPlane": {
      "abstract": [
        {
          "text": "A rectangular, one-sided plane geometry of specified width and height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPlane"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPlane",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPlane"
        }
      ],
      "role": "symbol",
      "title": "SCNPlane",
      "type": "topic",
      "url": "/documentation/scenekit/scnplane"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid": {
      "abstract": [
        {
          "text": "A right rectangular pyramid geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPyramid"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPyramid"
        }
      ],
      "role": "symbol",
      "title": "SCNPyramid",
      "type": "topic",
      "url": "/documentation/scenekit/scnpyramid"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNShape": {
      "abstract": [
        {
          "text": "A geometry based on a two-dimensional path, optionally extruded to create a three-dimensional object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNShape"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNShape"
        }
      ],
      "role": "symbol",
      "title": "SCNShape",
      "type": "topic",
      "url": "/documentation/scenekit/scnshape"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere": {
      "abstract": [
        {
          "text": "A sphere (or ball or globe) geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSphere"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSphere"
        }
      ],
      "role": "symbol",
      "title": "SCNSphere",
      "type": "topic",
      "url": "/documentation/scenekit/scnsphere"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNText": {
      "abstract": [
        {
          "text": "A geometry based on a string of text, optionally extruded to create a three-dimensional object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNText"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNText"
        }
      ],
      "role": "symbol",
      "title": "SCNText",
      "type": "topic",
      "url": "/documentation/scenekit/scntext"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTorus": {
      "abstract": [
        {
          "text": "A torus, or ring-shaped geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTorus"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTorus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTorus"
        }
      ],
      "role": "symbol",
      "title": "SCNTorus",
      "type": "topic",
      "url": "/documentation/scenekit/scntorus"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTube": {
      "abstract": [
        {
          "text": "A tube or pipe geometry—a right circular cylinder with a circular hole along its central axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTube"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTube",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTube"
        }
      ],
      "role": "symbol",
      "title": "SCNTube",
      "type": "topic",
      "url": "/documentation/scenekit/scntube"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Geometry",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement"
      ],
      "title": "Geometry"
    }
  ],
  "topicSections": [
    {
      "anchor": "Parametric-Geometry",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNText",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNShape"
      ],
      "title": "Parametric Geometry"
    },
    {
      "anchor": "Basic-Shapes",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNFloor",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNBox",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCone",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPlane",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTorus",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTube"
      ],
      "title": "Basic Shapes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Parametric-Geometry",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNText",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNShape"
              ],
              "title": "Parametric Geometry"
            },
            {
              "anchor": "Basic-Shapes",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNFloor",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNBox",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCone",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPlane",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTorus",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTube"
              ],
              "title": "Basic Shapes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Geometry",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement"
              ],
              "title": "Geometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/title",
          "value": "SCNPyramid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPyramid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPyramid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/title",
          "value": "SCNBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/title",
          "value": "SCNGeometrySource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometrySource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometrySource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title",
          "value": "SCNGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/title",
          "value": "SCNFloor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/title",
          "value": "SCNCone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/title",
          "value": "SCNPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShape/title",
          "value": "SCNShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/title",
          "value": "SCNSphere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSphere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSphere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/title",
          "value": "SCNCapsule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCapsule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCapsule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNText/title",
          "value": "SCNText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/title",
          "value": "SCNTube"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTube"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTube"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/title",
          "value": "SCNCylinder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCylinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCylinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/title",
          "value": "SCNGeometryElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/title",
          "value": "SCNTorus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTorus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTorus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/built-in-geometry-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/built-in-geometry-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
