{
  "abstract": [
    {
      "text": "Automatically adjust the position or orientation of a node based on specified rules.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/constraints"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Constraints"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By modifying the results of animation, physics, and other scene graph changes, constraints make it easier manage dynamic behaviors and relationships between elements of your scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, when developing a game, you might want a camera node to always point at the player character, even as that character moves around the scene. Instead of directly reorienting the camera node each time you move the character, you can add a look-at constraint to the camera node to make SceneKit reorient the camera automatically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAccelerationConstraint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAccelerationConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAccelerationConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAccelerationConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNAccelerationConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scnaccelerationconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNAvoidOccluderConstraint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNAvoidOccluderConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNAvoidOccluderConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNAvoidOccluderConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNAvoidOccluderConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scnavoidoccluderconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBillboardConstraint": {
      "abstract": [
        {
          "text": "A constraint that orients a node to always point toward the current camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNBillboardConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBillboardConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNBillboardConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNBillboardConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scnbillboardconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNConstraint": {
      "abstract": [
        {
          "text": "The abstract superclass for objects that automatically adjust the position, rotation, or scale of a node based on specified rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scnconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDistanceConstraint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNDistanceConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDistanceConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDistanceConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNDistanceConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scndistanceconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNIKConstraint": {
      "abstract": [
        {
          "text": "A constraint that applies inverse kinematics to make a chain of nodes “reach” toward a target point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNIKConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNIKConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNIKConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNIKConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scnikconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNLookAtConstraint": {
      "abstract": [
        {
          "text": "A constraint that orients a node to always point toward a specified other node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNLookAtConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLookAtConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLookAtConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNLookAtConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scnlookatconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher": {
      "abstract": [
        {
          "text": "An object that manages smooth transitions between a node’s base geometry and one or more target geometries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMorpher"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMorpher"
        }
      ],
      "role": "symbol",
      "title": "SCNMorpher",
      "type": "topic",
      "url": "/documentation/scenekit/scnmorpher"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNReplicatorConstraint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNReplicatorConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNReplicatorConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNReplicatorConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNReplicatorConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scnreplicatorconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner": {
      "abstract": [
        {
          "text": "An object that manages the relationship between skeletal animations and the nodes and geometries they animate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSkinner"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSkinner"
        }
      ],
      "role": "symbol",
      "title": "SCNSkinner",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSliderConstraint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSliderConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSliderConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSliderConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNSliderConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scnsliderconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransformConstraint": {
      "abstract": [
        {
          "text": "A constraint that runs a specified closure, block in Objective-C, to compute a new transform (position, rotation, and scale) for each node that the constraint affects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTransformConstraint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransformConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTransformConstraint"
        }
      ],
      "role": "symbol",
      "title": "SCNTransformConstraint",
      "type": "topic",
      "url": "/documentation/scenekit/scntransformconstraint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/animation": {
      "abstract": [
        {
          "text": "Create declarative animations that move elements of a scene in predetermined ways, or manage animations imported with external authoring tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/animation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation",
      "type": "topic",
      "url": "/documentation/scenekit/animation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animation-and-Constraints",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/animation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher"
      ],
      "title": "Animation and Constraints"
    }
  ],
  "topicSections": [
    {
      "anchor": "First-Steps",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNConstraint"
      ],
      "title": "First Steps"
    },
    {
      "anchor": "Orientation-Constraints",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNBillboardConstraint",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNLookAtConstraint"
      ],
      "title": "Orientation Constraints"
    },
    {
      "anchor": "Position-Constraints",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDistanceConstraint",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAvoidOccluderConstraint"
      ],
      "title": "Position Constraints"
    },
    {
      "anchor": "Motion-Constraints",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNAccelerationConstraint",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSliderConstraint"
      ],
      "title": "Motion Constraints"
    },
    {
      "anchor": "Synchronization",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNReplicatorConstraint"
      ],
      "title": "Synchronization"
    },
    {
      "anchor": "Inverse-Kinematics",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNIKConstraint"
      ],
      "title": "Inverse Kinematics"
    },
    {
      "anchor": "Customization",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransformConstraint"
      ],
      "title": "Customization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "First-Steps",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNConstraint"
              ],
              "title": "First Steps"
            },
            {
              "anchor": "Orientation-Constraints",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNBillboardConstraint",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNLookAtConstraint"
              ],
              "title": "Orientation Constraints"
            },
            {
              "anchor": "Position-Constraints",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDistanceConstraint",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAvoidOccluderConstraint"
              ],
              "title": "Position Constraints"
            },
            {
              "anchor": "Motion-Constraints",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNAccelerationConstraint",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSliderConstraint"
              ],
              "title": "Motion Constraints"
            },
            {
              "anchor": "Synchronization",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNReplicatorConstraint"
              ],
              "title": "Synchronization"
            },
            {
              "anchor": "Inverse-Kinematics",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNIKConstraint"
              ],
              "title": "Inverse Kinematics"
            },
            {
              "anchor": "Customization",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransformConstraint"
              ],
              "title": "Customization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animation-and-Constraints",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/animation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMorpher"
              ],
              "title": "Animation and Constraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/title",
          "value": "SCNSkinner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSkinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSkinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAvoidOccluderConstraint/title",
          "value": "SCNAvoidOccluderConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAvoidOccluderConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAvoidOccluderConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAvoidOccluderConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAvoidOccluderConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSliderConstraint/title",
          "value": "SCNSliderConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSliderConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSliderConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSliderConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSliderConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBillboardConstraint/title",
          "value": "SCNBillboardConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBillboardConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBillboardConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBillboardConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBillboardConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransformConstraint/title",
          "value": "SCNTransformConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransformConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTransformConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransformConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTransformConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDistanceConstraint/title",
          "value": "SCNDistanceConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDistanceConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDistanceConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDistanceConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDistanceConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAccelerationConstraint/title",
          "value": "SCNAccelerationConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAccelerationConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAccelerationConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAccelerationConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNAccelerationConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNIKConstraint/title",
          "value": "SCNIKConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNIKConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNIKConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNIKConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNIKConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNConstraint/title",
          "value": "SCNConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/title",
          "value": "SCNMorpher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMorpher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMorpher/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMorpher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLookAtConstraint/title",
          "value": "SCNLookAtConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLookAtConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLookAtConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLookAtConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLookAtConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReplicatorConstraint/title",
          "value": "SCNReplicatorConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReplicatorConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNReplicatorConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReplicatorConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNReplicatorConstraint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/constraints"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/constraints"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
