{
  "abstract": [
    {
      "text": "SceneKit-specific vectors, matrices, and related functions and operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/scenekit-3d-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SceneKit 3D Data Types"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In macOS 10.13, iOS 11, tvOS 11, and watchOS 4 (or later), use data types provided by the system SIMD library (such as ",
                  "type": "text"
                },
                {
                  "code": "float3",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "float4x4",
                  "type": "codeVoice"
                },
                {
                  "text": ") and the corresponding SceneKit methods (such as ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ") instead. These types provide faster performance, offer more concise C, C++, and Swift syntax (such as ",
                  "type": "text"
                },
                {
                  "code": "+",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "*",
                  "type": "codeVoice"
                },
                {
                  "text": " operators instead of functions), and interoperate better with other technologies (such as Model I/O, GameplayKit, and the Metal Shading Language).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNFloat": {
      "abstract": [
        {
          "text": "The element type for SceneKit vectors and matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNFloat"
        }
      ],
      "role": "symbol",
      "title": "SCNFloat",
      "type": "topic",
      "url": "/documentation/scenekit/scnfloat"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct": {
      "abstract": [
        {
          "text": "A representation of a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias": {
      "abstract": [
        {
          "text": "A representation of a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.typealias"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition": {
      "abstract": [
        {
          "text": "The translation applied to the node. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simdPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simdPosition"
        }
      ],
      "role": "symbol",
      "title": "simdPosition",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode/simdposition"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform": {
      "abstract": [
        {
          "text": "The transform applied to the node relative to its parent. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simdTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/simdTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simdTransform"
        }
      ],
      "role": "symbol",
      "title": "simdTransform",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode/simdtransform"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion": {
      "abstract": [
        {
          "text": "A representation of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNQuaternion"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNQuaternion"
        }
      ],
      "role": "symbol",
      "title": "SCNQuaternion",
      "type": "topic",
      "url": "/documentation/scenekit/scnquaternion"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3": {
      "abstract": [
        {
          "text": "A representation of a three-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNVector3"
        }
      ],
      "role": "symbol",
      "title": "SCNVector3",
      "type": "topic",
      "url": "/documentation/scenekit/scnvector3"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNVector4": {
      "abstract": [
        {
          "text": "A representation of a four-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNVector4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNVector4"
        }
      ],
      "role": "symbol",
      "title": "SCNVector4",
      "type": "topic",
      "url": "/documentation/scenekit/scnvector4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Vectors",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNVector4"
      ],
      "title": "Vectors"
    },
    {
      "anchor": "Transforms-and-Rotations",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion"
      ],
      "title": "Transforms and Rotations"
    },
    {
      "anchor": "Scalars",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNFloat"
      ],
      "title": "Scalars"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Vectors",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNVector4"
              ],
              "title": "Vectors"
            },
            {
              "anchor": "Transforms-and-Rotations",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion"
              ],
              "title": "Transforms and Rotations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdTransform/title",
          "value": "simdTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simdTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/title",
          "value": "SCNMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector4/title",
          "value": "SCNVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/title",
          "value": "SCNQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/title",
          "value": "SCNMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPosition/title",
          "value": "simdPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1simdPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simdPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/title",
          "value": "SCNVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNVector3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scenekit-3d-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scenekit-3d-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
