{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/scenekit-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SceneKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNLightAreaType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNLightAreaType"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLightAreaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLightAreaType"
        }
      ],
      "role": "symbol",
      "title": "SCNLightAreaType",
      "type": "topic",
      "url": "/documentation/scenekit/scnlightareatype"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNLightProbeType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNLightProbeType"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLightProbeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLightProbeType"
        }
      ],
      "role": "symbol",
      "title": "SCNLightProbeType",
      "type": "topic",
      "url": "/documentation/scenekit/scnlightprobetype"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNLightProbeUpdateType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNLightProbeUpdateType"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLightProbeUpdateType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLightProbeUpdateType"
        }
      ],
      "role": "symbol",
      "title": "SCNLightProbeUpdateType",
      "type": "topic",
      "url": "/documentation/scenekit/scnlightprobeupdatetype"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/scenekit-constants": {
      "abstract": [
        {
          "text": "Constants used throughout the SceneKit framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/scenekit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SceneKit Constants",
      "type": "topic",
      "url": "/documentation/scenekit/scenekit-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/scenekit-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNLightAreaType",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNLightProbeType",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNLightProbeUpdateType"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNLightAreaType",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNLightProbeType",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNLightProbeUpdateType"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/scenekit-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightProbeUpdateType/title",
          "value": "SCNLightProbeUpdateType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightProbeUpdateType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLightProbeUpdateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightProbeUpdateType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLightProbeUpdateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightAreaType/title",
          "value": "SCNLightAreaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightAreaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLightAreaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightAreaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLightAreaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightProbeType/title",
          "value": "SCNLightProbeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightProbeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLightProbeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLightProbeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLightProbeType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scenekit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scenekit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
