{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SceneKit-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Macros"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4FromCATransform3D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4FromCATransform3D"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4FromCATransform3D",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLKMatrix4FromCATransform3D",
      "type": "topic",
      "url": "/documentation/scenekit/glkmatrix4fromcatransform3d"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4ToCATransform3D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4ToCATransform3D"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4ToCATransform3D",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLKMatrix4ToCATransform3D",
      "type": "topic",
      "url": "/documentation/scenekit/glkmatrix4tocatransform3d"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNColor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNColor"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNColor",
      "type": "topic",
      "url": "/documentation/scenekit/scncolor"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBackFaceCulling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionBackFaceCulling"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBackFaceCulling",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionBackFaceCulling",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionbackfaceculling"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBoundingBoxOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionBoundingBoxOnly"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBoundingBoxOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionBoundingBoxOnly",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionboundingboxonly"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionClipToZRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionClipToZRange"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionClipToZRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionClipToZRange",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptioncliptozrange"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionFirstFoundOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionFirstFoundOnly"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionFirstFoundOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionFirstFoundOnly",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionfirstfoundonly"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreChildNodes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionIgnoreChildNodes"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreChildNodes",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionIgnoreChildNodes",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionignorechildnodes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreHiddenNodes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionIgnoreHiddenNodes"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreHiddenNodes",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionIgnoreHiddenNodes",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionignorehiddennodes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionRootNode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionRootNode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionRootNode",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionRootNode",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionrootnode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionSortResults": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionSortResults"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionSortResults",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionSortResults",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionsortresults"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionKeepAsCompound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsShapeOptionKeepAsCompound"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionKeepAsCompound",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsShapeOptionKeepAsCompound",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsshapeoptionkeepascompound"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionScale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsShapeOptionScale"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsShapeOptionScale",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsshapeoptionscale"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsShapeOptionType"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionType",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsShapeOptionType",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsshapeoptiontype"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionBackfaceCulling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsTestOptionBackfaceCulling"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionBackfaceCulling",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsTestOptionBackfaceCulling",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicstestoptionbackfaceculling"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionCollisionBitMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsTestOptionCollisionBitMask"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionCollisionBitMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsTestOptionCollisionBitMask",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicstestoptioncollisionbitmask"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionSearchMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsTestOptionSearchMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionSearchMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsTestOptionSearchMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicstestoptionsearchmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeEndTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneAttributeEndTime"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeEndTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneAttributeEndTime",
      "type": "topic",
      "url": "/documentation/scenekit/scnsceneattributeendtime"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeFrameRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneAttributeFrameRate"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeFrameRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneAttributeFrameRate",
      "type": "topic",
      "url": "/documentation/scenekit/scnsceneattributeframerate"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeStartTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneAttributeStartTime"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeStartTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneAttributeStartTime",
      "type": "topic",
      "url": "/documentation/scenekit/scnsceneattributestarttime"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeUpAxis": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneAttributeUpAxis"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeUpAxis",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneAttributeUpAxis",
      "type": "topic",
      "url": "/documentation/scenekit/scnsceneattributeupaxis"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionAnimationImportPolicy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionAnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionAnimationImportPolicy",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionAnimationImportPolicy",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptionanimationimportpolicy"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionAssetDirectoryURLs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionAssetDirectoryURLs"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionAssetDirectoryURLs",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionAssetDirectoryURLs",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptionassetdirectoryurls"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionCheckConsistency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionCheckConsistency"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionCheckConsistency",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionCheckConsistency",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptioncheckconsistency"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionConvertToYUp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionConvertToYUp"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionConvertToYUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionConvertToYUp",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptionconverttoyup"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionConvertUnitsToMeters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionConvertUnitsToMeters"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionConvertUnitsToMeters",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionConvertUnitsToMeters",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptionconvertunitstometers"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionCreateNormalsIfAbsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionCreateNormalsIfAbsent"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionCreateNormalsIfAbsent",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionCreateNormalsIfAbsent",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptioncreatenormalsifabsent"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionFlattenScene": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionFlattenScene"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionFlattenScene",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionFlattenScene",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptionflattenscene"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionOverrideAssetURLs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionOverrideAssetURLs"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionOverrideAssetURLs",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionOverrideAssetURLs",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptionoverrideasseturls"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionStrictConformance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionStrictConformance"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionStrictConformance",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionStrictConformance",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptionstrictconformance"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionUseSafeMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceLoadingOptionUseSafeMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionUseSafeMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNSceneSourceLoadingOptionUseSafeMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceloadingoptionusesafemode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferLowPowerDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNViewOptionPreferLowPowerDevice"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferLowPowerDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNViewOptionPreferLowPowerDevice",
      "type": "topic",
      "url": "/documentation/scenekit/scnviewoptionpreferlowpowerdevice"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferredDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNViewOptionPreferredDevice"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferredDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNViewOptionPreferredDevice",
      "type": "topic",
      "url": "/documentation/scenekit/scnviewoptionpreferreddevice"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferredRenderingAPI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNViewOptionPreferredRenderingAPI"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferredRenderingAPI",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNViewOptionPreferredRenderingAPI",
      "type": "topic",
      "url": "/documentation/scenekit/scnviewoptionpreferredrenderingapi"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_METAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCN_ENABLE_METAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_METAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCN_ENABLE_METAL"
        }
      ],
      "role": "symbol",
      "title": "SCN_ENABLE_METAL",
      "type": "topic",
      "url": "/documentation/scenekit/scn_enable_metal"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_OPENGL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCN_ENABLE_OPENGL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_OPENGL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCN_ENABLE_OPENGL"
        }
      ],
      "role": "symbol",
      "title": "SCN_ENABLE_OPENGL",
      "type": "topic",
      "url": "/documentation/scenekit/scn_enable_opengl"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCN_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCN_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCN_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCN_EXPORT",
      "type": "topic",
      "url": "/documentation/scenekit/scn_export"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCN_GL_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCN_GL_DEPRECATED",
      "type": "topic",
      "url": "/documentation/scenekit/scn_gl_deprecated"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCN_GL_DEPRECATED_IOS"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCN_GL_DEPRECATED_IOS",
      "type": "topic",
      "url": "/documentation/scenekit/scn_gl_deprecated_ios"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED_MAC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCN_GL_DEPRECATED_MAC"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED_MAC",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCN_GL_DEPRECATED_MAC",
      "type": "topic",
      "url": "/documentation/scenekit/scn_gl_deprecated_mac"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_METAL",
        "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_OPENGL"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4FromCATransform3D",
                "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4ToCATransform3D",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNColor",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBackFaceCulling",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBoundingBoxOnly",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionClipToZRange",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionFirstFoundOnly",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreChildNodes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreHiddenNodes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionRootNode",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionSortResults",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionKeepAsCompound",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionScale",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionType",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionBackfaceCulling",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionCollisionBitMask",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionSearchMode",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeEndTime",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeFrameRate",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeStartTime",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneAttributeUpAxis",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionAnimationImportPolicy",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionAssetDirectoryURLs",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionCheckConsistency",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionConvertToYUp",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionConvertUnitsToMeters",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionCreateNormalsIfAbsent",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionFlattenScene",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionOverrideAssetURLs",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionStrictConformance",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceLoadingOptionUseSafeMode",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferLowPowerDevice",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferredDevice",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNViewOptionPreferredRenderingAPI",
                "doc://com.apple.scenekit/documentation/SceneKit/SCN_EXPORT",
                "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_METAL",
                "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_OPENGL",
                "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED",
                "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED_IOS",
                "doc://com.apple.scenekit/documentation/SceneKit/SCN_GL_DEPRECATED_MAC"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCN_ENABLE_METAL/title",
          "value": "SCN_ENABLE_METAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCN_ENABLE_METAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCN_ENABLE_METAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCN_ENABLE_OPENGL/title",
          "value": "SCN_ENABLE_OPENGL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCN_ENABLE_OPENGL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCN_ENABLE_OPENGL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scenekit-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scenekit-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
