{
  "abstract": [
    {
      "text": "The metadata properties associated with a scene file, used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/property(forKey:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/scene-source-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Scene Source Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/1573761-scene-file-consistency-check-err": {
      "abstract": [
        {
          "text": "Error codes that identify errors found during a scene-file-format consistency check.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/1573761-scene-file-consistency-check-err",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scene File Consistency Check Error Codes",
      "type": "topic",
      "url": "/documentation/scenekit/1573761-scene-file-consistency-check-err"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource": {
      "abstract": [
        {
          "text": "An object that manages the data-reading tasks associated with loading scene contents from a file or data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSource"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSource",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption": {
      "abstract": [
        {
          "text": "Options for creating scene sources and loading the scenes they contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LoadingOption"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSource.LoadingOption",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/property(forKey:)": {
      "abstract": [
        {
          "text": "Returns metadata about the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "property"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/property(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyForKey:"
        }
      ],
      "role": "symbol",
      "title": "property(forKey:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/property(forkey:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetContributorsKey": {
      "abstract": [
        {
          "text": "The file contributors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetContributorsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetContributorsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetContributorsKey"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSourceAssetContributorsKey",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceassetcontributorskey"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetCreatedDateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetCreatedDateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetCreatedDateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetCreatedDateKey"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSourceAssetCreatedDateKey",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceassetcreateddatekey"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetModifiedDateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetModifiedDateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetModifiedDateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetModifiedDateKey"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSourceAssetModifiedDateKey",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceassetmodifieddatekey"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUnitKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetUnitKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUnitKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetUnitKey"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSourceAssetUnitKey",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceassetunitkey"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUpAxisKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetUpAxisKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUpAxisKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAssetUpAxisKey"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSourceAssetUpAxisKey",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourceassetupaxiskey"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatus": {
      "abstract": [
        {
          "text": "Constants identifying phases of SceneKit’s scene loading process, used in a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatusHandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSourceStatus"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceStatus"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSourceStatus",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourcestatus"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatusHandler": {
      "abstract": [
        {
          "text": "The signature for the block that SceneKit calls periodically to report progress while loading a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSourceStatusHandler"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatusHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceStatusHandler"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSourceStatusHandler",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesourcestatushandler"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/contributor-keys": {
      "abstract": [
        {
          "text": "Metadata identifying the user and authoring tool that created a scene file, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetContributorsKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/contributor-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Contributor Keys",
      "type": "topic",
      "url": "/documentation/scenekit/contributor-keys"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/scene-file-consistency-error-keys": {
      "abstract": [
        {
          "text": "Keys identifying errors found during a scene-file-format consistency check.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/scene-file-consistency-error-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scene File Consistency Error Keys",
      "type": "topic",
      "url": "/documentation/scenekit/scene-file-consistency-error-keys"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/scene-loading-error-keys": {
      "abstract": [],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/scene-loading-error-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scene Loading Error Keys",
      "type": "topic",
      "url": "/documentation/scenekit/scene-loading-error-keys"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/unit-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata describing the unit of measurement used in a scene file, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUnitKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/unit-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Unit Dictionary Keys",
      "type": "topic",
      "url": "/documentation/scenekit/unit-dictionary-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption",
        "doc://com.apple.scenekit/documentation/SceneKit/contributor-keys",
        "doc://com.apple.scenekit/documentation/SceneKit/unit-dictionary-keys",
        "doc://com.apple.scenekit/documentation/SceneKit/scene-loading-error-keys",
        "doc://com.apple.scenekit/documentation/SceneKit/scene-file-consistency-error-keys",
        "doc://com.apple.scenekit/documentation/SceneKit/1573761-scene-file-consistency-check-err",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatusHandler",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatus"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetContributorsKey",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetCreatedDateKey",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetModifiedDateKey",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUpAxisKey",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUnitKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetContributorsKey",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetCreatedDateKey",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetModifiedDateKey",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUpAxisKey",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceAssetUnitKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption",
                "doc://com.apple.scenekit/documentation/SceneKit/contributor-keys",
                "doc://com.apple.scenekit/documentation/SceneKit/unit-dictionary-keys",
                "doc://com.apple.scenekit/documentation/SceneKit/scene-loading-error-keys",
                "doc://com.apple.scenekit/documentation/SceneKit/scene-file-consistency-error-keys",
                "doc://com.apple.scenekit/documentation/SceneKit/1573761-scene-file-consistency-check-err",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatusHandler",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSourceStatus"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetModifiedDateKey/title",
          "value": "SCNSceneSourceAssetModifiedDateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetModifiedDateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAssetModifiedDateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1property(forKey:)/title",
          "value": "propertyForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1property(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "propertyForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceStatusHandler/title",
          "value": "SCNSceneSourceStatusHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceStatusHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceStatusHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceStatusHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceStatusHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetUnitKey/title",
          "value": "SCNSceneSourceAssetUnitKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetUnitKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAssetUnitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/title",
          "value": "SCNSceneSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetCreatedDateKey/title",
          "value": "SCNSceneSourceAssetCreatedDateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetCreatedDateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAssetCreatedDateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetContributorsKey/title",
          "value": "SCNSceneSourceAssetContributorsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetContributorsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAssetContributorsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption/title",
          "value": "SCNSceneSourceLoadingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceLoadingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceLoadingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetUpAxisKey/title",
          "value": "SCNSceneSourceAssetUpAxisKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceAssetUpAxisKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAssetUpAxisKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceStatus/title",
          "value": "SCNSceneSourceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSourceStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scene-source-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scene-source-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
