{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_METAL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@SCN_ENABLE_METAL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCN_ENABLE_METAL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCN_ENABLE_METAL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "SCN_ENABLE_METAL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCN_ENABLE_METAL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4FromCATransform3D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4FromCATransform3D"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4FromCATransform3D",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLKMatrix4FromCATransform3D",
      "type": "topic",
      "url": "/documentation/scenekit/glkmatrix4fromcatransform3d"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4ToCATransform3D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GLKMatrix4ToCATransform3D"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4ToCATransform3D",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLKMatrix4ToCATransform3D",
      "type": "topic",
      "url": "/documentation/scenekit/glkmatrix4tocatransform3d"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNColor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNColor"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNColor",
      "type": "topic",
      "url": "/documentation/scenekit/scncolor"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBackFaceCulling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionBackFaceCulling"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBackFaceCulling",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionBackFaceCulling",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionbackfaceculling"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBoundingBoxOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionBoundingBoxOnly"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBoundingBoxOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionBoundingBoxOnly",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionboundingboxonly"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionClipToZRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionClipToZRange"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionClipToZRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionClipToZRange",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptioncliptozrange"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionFirstFoundOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionFirstFoundOnly"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionFirstFoundOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionFirstFoundOnly",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionfirstfoundonly"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreChildNodes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionIgnoreChildNodes"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreChildNodes",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionIgnoreChildNodes",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionignorechildnodes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreHiddenNodes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionIgnoreHiddenNodes"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreHiddenNodes",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionIgnoreHiddenNodes",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionignorehiddennodes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionRootNode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionRootNode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionRootNode",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionRootNode",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionrootnode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionSortResults": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOptionSortResults"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionSortResults",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNHitTestOptionSortResults",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoptionsortresults"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionKeepAsCompound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsShapeOptionKeepAsCompound"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionKeepAsCompound",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsShapeOptionKeepAsCompound",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsshapeoptionkeepascompound"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionScale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsShapeOptionScale"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsShapeOptionScale",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsshapeoptionscale"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsShapeOptionType"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionType",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsShapeOptionType",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsshapeoptiontype"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionBackfaceCulling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsTestOptionBackfaceCulling"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionBackfaceCulling",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNPhysicsTestOptionBackfaceCulling",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicstestoptionbackfaceculling"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_METAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCN_ENABLE_METAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_METAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCN_ENABLE_METAL"
        }
      ],
      "role": "symbol",
      "title": "SCN_ENABLE_METAL",
      "type": "topic",
      "url": "/documentation/scenekit/scn_enable_metal"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_OPENGL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCN_ENABLE_OPENGL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_OPENGL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCN_ENABLE_OPENGL"
        }
      ],
      "role": "symbol",
      "title": "SCN_ENABLE_OPENGL",
      "type": "topic",
      "url": "/documentation/scenekit/scn_enable_opengl"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCN_ENABLE_OPENGL"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCN_ENABLE_METAL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCN_ENABLE_METAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4FromCATransform3D",
                "doc://com.apple.scenekit/documentation/SceneKit/GLKMatrix4ToCATransform3D",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNColor",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBackFaceCulling",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionBoundingBoxOnly",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionClipToZRange",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionFirstFoundOnly",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreChildNodes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionIgnoreHiddenNodes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionRootNode",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOptionSortResults",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionKeepAsCompound",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionScale",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShapeOptionType",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsTestOptionBackfaceCulling"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCN_ENABLE_METAL"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCN_ENABLE_OPENGL/title",
          "value": "SCN_ENABLE_OPENGL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCN_ENABLE_OPENGL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCN_ENABLE_OPENGL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCN_ENABLE_METAL/title",
          "value": "SCN_ENABLE_METAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCN_ENABLE_METAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCN_ENABLE_METAL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scn_enable_metal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scn_enable_metal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
