{
  "abstract": [
    {
      "text": "Methods common to the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " classes for measuring location and size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SCNBoundingVolume",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNBoundingVolume"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNBoundingVolume"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "SCNBoundingVolume"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNBoundingVolume"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This protocol defines features adopted by both the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A bounding box is the smallest volume, in the shape of a rectangle aligned to the axes of the local coordinate space, that entirely contains an object. Scene Kit defines a bounding box using two points: a minimum and maximum corner. Similarly, a bounding sphere is the smallest sphere containing an object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By default, Scene Kit automatically determines the minimal bounding volumes for geometries based on their vertex positions in model space. The bounding volume of a node with an attached geometry is the bounding volume of the geometry, expressed in the node’s local space. The bounding volume of a node containing child nodes is the minimal volume that encloses the bounding volumes of the node’s children.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Scene Kit uses the bounding volume of an object when determining how to render a scene. For example, an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCamera",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object uses the bounding boxes of visible elements in a scene to determine the its depth limits. You can override a bounding volume to change this behavior. For example, if a building model has a long, narrow antenna, the default bounding box includes that feature, so the default camera view for that model will be off-center with respect to the building itself. If you set a new bounding box that includes only the main part of the building, the default camera view will center on the building and ignore the antenna.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Getting-and-Setting-Bounding-Volumes",
          "level": 3,
          "text": "Getting and Setting Bounding Volumes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Read the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingBox",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingSphere",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/getBoundingBoxMin:max:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/getBoundingSphereCenter:radius:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods in Objective-C, to retrieve information about an object’s bounding box or sphere. To override the automatically determined bounding volume of an object, set a new value for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingBox",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/setBoundingBoxMin:max:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in Objective-C.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume": {
      "abstract": [
        {
          "text": "Methods common to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " classes for measuring location and size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNBoundingVolume"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNBoundingVolume"
        }
      ],
      "role": "symbol",
      "title": "SCNBoundingVolume",
      "type": "topic",
      "url": "/documentation/scenekit/scnboundingvolume"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingBox": {
      "abstract": [
        {
          "text": "The minimum and maximum corner points of the object’s bounding box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundingBox"
        },
        {
          "kind": "text",
          "text": ": (min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingBox",
      "kind": "symbol",
      "role": "symbol",
      "title": "boundingBox",
      "type": "topic",
      "url": "/documentation/scenekit/scnboundingvolume/boundingbox"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingSphere": {
      "abstract": [
        {
          "text": "The center point and radius of the object’s bounding sphere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundingSphere"
        },
        {
          "kind": "text",
          "text": ": (center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", radius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingSphere",
      "kind": "symbol",
      "role": "symbol",
      "title": "boundingSphere",
      "type": "topic",
      "url": "/documentation/scenekit/scnboundingvolume/boundingsphere"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/getBoundingBoxMin:max:": {
      "abstract": [
        {
          "text": "Gets the minimum and maximum corner points of the object’s bounding box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "getBoundingBoxMin:max:"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/getBoundingBoxMin:max:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getBoundingBoxMin:max:"
        }
      ],
      "role": "symbol",
      "title": "getBoundingBoxMin:max:",
      "type": "topic",
      "url": "/documentation/scenekit/scnboundingvolume/getboundingboxmin:max:"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/getBoundingSphereCenter:radius:": {
      "abstract": [
        {
          "text": "Gets the center point and radius of the object’s bounding sphere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "getBoundingSphereCenter:radius:"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/getBoundingSphereCenter:radius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getBoundingSphereCenter:radius:"
        }
      ],
      "role": "symbol",
      "title": "getBoundingSphereCenter:radius:",
      "type": "topic",
      "url": "/documentation/scenekit/scnboundingvolume/getboundingspherecenter:radius:"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/setBoundingBoxMin:max:": {
      "abstract": [
        {
          "text": "Sets a custom bounding box for the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setBoundingBoxMin:max:"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/setBoundingBoxMin:max:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBoundingBoxMin:max:"
        }
      ],
      "role": "symbol",
      "title": "setBoundingBoxMin:max:",
      "type": "topic",
      "url": "/documentation/scenekit/scnboundingvolume/setboundingboxmin:max:"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBox": {
      "abstract": [
        {
          "text": "A six-sided polyhedron geometry whose faces are all rectangles, optionally with rounded edges and corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNBox"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNBox"
        }
      ],
      "role": "symbol",
      "title": "SCNBox",
      "type": "topic",
      "url": "/documentation/scenekit/scnbox"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCamera": {
      "abstract": [
        {
          "text": "A set of camera attributes that can be attached to a node to provide a point of view for displaying the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCamera"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCamera"
        }
      ],
      "role": "symbol",
      "title": "SCNCamera",
      "type": "topic",
      "url": "/documentation/scenekit/scncamera"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule": {
      "abstract": [
        {
          "text": "A right circular cylinder geometry whose ends are capped with hemispheres.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCapsule"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCapsule"
        }
      ],
      "role": "symbol",
      "title": "SCNCapsule",
      "type": "topic",
      "url": "/documentation/scenekit/scncapsule"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCone": {
      "abstract": [
        {
          "text": "A right circular cone or frustum geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCone"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCone"
        }
      ],
      "role": "symbol",
      "title": "SCNCone",
      "type": "topic",
      "url": "/documentation/scenekit/scncone"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder": {
      "abstract": [
        {
          "text": "A right circular cylinder geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCylinder"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCylinder"
        }
      ],
      "role": "symbol",
      "title": "SCNCylinder",
      "type": "topic",
      "url": "/documentation/scenekit/scncylinder"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNFloor": {
      "abstract": [
        {
          "text": "A plane that can optionally display a reflection of the scene above it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNFloor"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNFloor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNFloor"
        }
      ],
      "role": "symbol",
      "title": "SCNFloor",
      "type": "topic",
      "url": "/documentation/scenekit/scnfloor"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry": {
      "abstract": [
        {
          "text": "A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometry",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/name": {
      "abstract": [
        {
          "text": "A name associated with the geometry object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry/name"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode": {
      "abstract": [
        {
          "text": "A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNNode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNNode"
        }
      ],
      "role": "symbol",
      "title": "SCNNode",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPlane": {
      "abstract": [
        {
          "text": "A rectangular, one-sided plane geometry of specified width and height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPlane"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPlane",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPlane"
        }
      ],
      "role": "symbol",
      "title": "SCNPlane",
      "type": "topic",
      "url": "/documentation/scenekit/scnplane"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid": {
      "abstract": [
        {
          "text": "A right rectangular pyramid geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPyramid"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPyramid"
        }
      ],
      "role": "symbol",
      "title": "SCNPyramid",
      "type": "topic",
      "url": "/documentation/scenekit/scnpyramid"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNReferenceNode": {
      "abstract": [
        {
          "text": "A scene graph node that serves as a placeholder for content to be loaded from a separate scene file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNReferenceNode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNReferenceNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNReferenceNode"
        }
      ],
      "role": "symbol",
      "title": "SCNReferenceNode",
      "type": "topic",
      "url": "/documentation/scenekit/scnreferencenode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNShape": {
      "abstract": [
        {
          "text": "A geometry based on a two-dimensional path, optionally extruded to create a three-dimensional object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNShape"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNShape"
        }
      ],
      "role": "symbol",
      "title": "SCNShape",
      "type": "topic",
      "url": "/documentation/scenekit/scnshape"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere": {
      "abstract": [
        {
          "text": "A sphere (or ball or globe) geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSphere"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSphere"
        }
      ],
      "role": "symbol",
      "title": "SCNSphere",
      "type": "topic",
      "url": "/documentation/scenekit/scnsphere"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNText": {
      "abstract": [
        {
          "text": "A geometry based on a string of text, optionally extruded to create a three-dimensional object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNText"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNText"
        }
      ],
      "role": "symbol",
      "title": "SCNText",
      "type": "topic",
      "url": "/documentation/scenekit/scntext"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTorus": {
      "abstract": [
        {
          "text": "A torus, or ring-shaped geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTorus"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTorus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTorus"
        }
      ],
      "role": "symbol",
      "title": "SCNTorus",
      "type": "topic",
      "url": "/documentation/scenekit/scntorus"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTube": {
      "abstract": [
        {
          "text": "A tube or pipe geometry—a right circular cylinder with a circular hole along its central axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTube"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTube",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTube"
        }
      ],
      "role": "symbol",
      "title": "SCNTube",
      "type": "topic",
      "url": "/documentation/scenekit/scntube"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNBox",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCone",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNFloor",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPlane",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNReferenceNode",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNShape",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNText",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTorus",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTube"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Geometry-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/name"
      ],
      "title": "Managing Geometry Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Measuring-an-Objects-Bounding-Volume",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingBox",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/boundingSphere"
      ],
      "title": "Measuring an Object’s Bounding Volume"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNBoundingVolume"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBoundingVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBoundingVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Measuring-an-Objects-Bounding-Volume",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/getBoundingBoxMin:max:",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/getBoundingSphereCenter:radius:"
              ],
              "title": "Measuring an Object’s Bounding Volume"
            },
            {
              "anchor": "Overriding-an-Objects-Default-Bounding-Volume",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume/setBoundingBoxMin:max:"
              ],
              "title": "Overriding an Object’s Default Bounding Volume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNNode"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Geometry-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/name"
              ],
              "title": "Managing Geometry Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNBoundingVolume"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/title",
          "value": "SCNPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/title",
          "value": "SCNCapsule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCapsule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCapsule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/title",
          "value": "SCNTube"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTube"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTube"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNText/title",
          "value": "SCNText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title",
          "value": "SCNNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/title",
          "value": "SCNTorus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTorus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTorus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/title",
          "value": "SCNBoundingVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBoundingVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBoundingVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/title",
          "value": "SCNFloor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReferenceNode/title",
          "value": "SCNReferenceNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReferenceNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNReferenceNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNReferenceNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNReferenceNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShape/title",
          "value": "SCNShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/title",
          "value": "SCNPyramid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPyramid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPyramid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/title",
          "value": "SCNSphere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSphere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSphere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/title",
          "value": "SCNCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/title",
          "value": "SCNBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/title",
          "value": "SCNCone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title",
          "value": "SCNGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/title",
          "value": "SCNCylinder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCylinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCylinder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnboundingvolume"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnboundingvolume"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
