{"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"SCNCone","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNCone","kind":"identifier"}],"modules":[{"name":"SceneKit"}],"platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false},{"name":"watchOS","beta":false,"unavailable":false,"deprecated":false}],"title":"SCNCone","symbolKind":"class","externalID":"c:objc(cs)SCNCone","role":"symbol"},"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","doc://com.apple.scenekit/documentation/SceneKit/SCNAnimatable","doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume","doc://com.apple.scenekit/documentation/SceneKit/SCNShadable"],"type":"conformsTo"}],"variants":[{"paths":["/documentation/scenekit/scncone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/scenekit/scncone"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A right circular cone or frustum geometry."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNCone","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"identifier":"media-2929809","type":"image"}]},{"type":"paragraph","inlineContent":[{"text":"A cone defines the surface of a solid whose base is a circle and whose side surface tapers to a point centered above its base. A frustum also has a circular base and tapered sides but has a circular top, similar to a cone cut off below its apex.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Define the size of the cone’s base in the x- and z-axis dimensions of its local coordinate space with its "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/bottomRadius","type":"reference","isActive":true},{"type":"text","text":" property, and its extent in the y-axis dimension with its "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/height","type":"reference","isActive":true},{"type":"text","text":" property. Create a cone that tapers to a point by setting its "},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/topRadius","type":"reference"},{"type":"text","text":" property to zero, or a frustum that tapers (or expands) to a circular top by setting the "},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/topRadius","type":"reference"},{"type":"text","text":" property to a different value."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To position and orient a cone in a scene, attach it to the "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry","type":"reference","isActive":true},{"type":"text","text":" property of an "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode","type":"reference","isActive":true},{"type":"text","text":" object."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Control the level of detail with the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/radialSegmentCount"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/heightSegmentCount"},{"type":"text","text":" properties. A higher radial segment count creates a smoother curve for the cone’s circular sides. A higher segment count in either direction produces more vertices, which can improve rendering quality for certain lighting models or custom shader effects, but at a cost to rendering performance."}]},{"type":"paragraph","inlineContent":[{"text":"A cone geometry may contain two or three ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement","type":"reference","isActive":true},{"text":" objects, corresponding to its outer surface, its base and its top (or base only or top only, if the ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/topRadius","type":"reference","isActive":true},{"text":" or ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/bottomRadius","type":"reference","isActive":true},{"text":" property is zero). SceneKit can render each element using a different material. For details, see the ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/materials","type":"reference","isActive":true},{"text":" property in ","type":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry","type":"reference","isActive":true},{"text":".","type":"text"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone"},"topicSections":[{"title":"Creating a Cone","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNCone/init(topRadius:bottomRadius:height:)"],"anchor":"Creating-a-Cone"},{"title":"Adjusting a Cone’s Dimensions","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNCone/topRadius","doc://com.apple.scenekit/documentation/SceneKit/SCNCone/bottomRadius","doc://com.apple.scenekit/documentation/SceneKit/SCNCone/height"],"anchor":"Adjusting-a-Cones-Dimensions"},{"title":"Adjusting Geometric Detail","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNCone/radialSegmentCount","doc://com.apple.scenekit/documentation/SceneKit/SCNCone/heightSegmentCount"],"anchor":"Adjusting-Geometric-Detail"}],"seeAlsoSections":[{"title":"Basic Shapes","generated":true,"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNFloor","doc://com.apple.scenekit/documentation/SceneKit/SCNBox","doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule","doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder","doc://com.apple.scenekit/documentation/SceneKit/SCNPlane","doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid","doc://com.apple.scenekit/documentation/SceneKit/SCNSphere","doc://com.apple.scenekit/documentation/SceneKit/SCNTorus","doc://com.apple.scenekit/documentation/SceneKit/SCNTube"],"anchor":"Basic-Shapes"}],"references":{"doc://com.externally.resolved.symbol/s:SQ":{"title":"Equatable","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SQ","url":"/documentation/Swift/Equatable","abstract":[{"type":"text","text":"A type that can be compared for value equality."}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry":{"role":"symbol","kind":"symbol","title":"SCNGeometry","navigatorTitle":[{"text":"SCNGeometry","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNGeometry","kind":"identifier"}],"url":"/documentation/scenekit/scngeometry","abstract":[{"text":"A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"},"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/init(topRadius:bottomRadius:height:)":{"url":"/documentation/scenekit/scncone/init(topradius:bottomradius:height:)","role":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"title":"init(topRadius:bottomRadius:height:)","navigatorTitle":[{"kind":"identifier","text":"coneWithTopRadius:bottomRadius:height:"}],"abstract":[{"text":"Creates a cone geometry with the given top radius, bottom radius, and height.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/init(topRadius:bottomRadius:height:)"},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement":{"url":"/documentation/scenekit/scngeometryelement","title":"SCNGeometryElement","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SCNGeometryElement","kind":"identifier"}],"abstract":[{"type":"text","text":"A container for index data describing how vertices connect to define a three-dimensional object, or geometry."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometryElement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNGeometryElement","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"kind":"symbol","type":"topic","url":"/documentation/Swift/CustomStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNTube":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNTube","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/scenekit/scntube","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTube","abstract":[{"type":"text","text":"A tube or pipe geometry—a right circular cylinder with a circular hole along its central axis."}],"title":"SCNTube","navigatorTitle":[{"text":"SCNTube","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"kind":"symbol","url":"/documentation/foundation/nscoding","type":"topic","title":"NSCoding","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode":{"role":"symbol","kind":"symbol","title":"SCNNode","navigatorTitle":[{"kind":"identifier","text":"SCNNode"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNNode"}],"url":"/documentation/scenekit/scnnode","abstract":[{"text":"A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},"doc://com.apple.scenekit/documentation/SceneKit/SCNBox":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNBox"}],"url":"/documentation/scenekit/scnbox","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNBox","abstract":[{"text":"A six-sided polyhedron geometry whose faces are all rectangles, optionally with rounded edges and corners.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SCNBox"}],"kind":"symbol","title":"SCNBox","role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/heightSegmentCount":{"title":"heightSegmentCount","abstract":[{"text":"The number of subdivisions in the sides of the cone along its y-axis. Animatable.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/heightSegmentCount","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightSegmentCount"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"heightSegmentCount","kind":"identifier"}],"url":"/documentation/scenekit/scncone/heightsegmentcount"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"type":"topic","kind":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","url":"/documentation/foundation/nscopying","role":"symbol","title":"NSCopying","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}]},"media-2929809":{"type":"image","variants":[{"url":"https://docs-assets.developer.apple.com/published/c98604b0c5b0a6a33ac4e0c4c7d4e68a/media-2929809@2x.png","traits":["2x","light"]}],"identifier":"media-2929809","alt":null},"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/radialSegmentCount":{"title":"radialSegmentCount","abstract":[{"text":"The number of subdivisions around the circumference of the cone. Animatable.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/radialSegmentCount","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"radialSegmentCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"radialSegmentCount"}],"url":"/documentation/scenekit/scncone/radialsegmentcount"},"doc://com.apple.scenekit/documentation/SceneKit/SCNCone":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone","abstract":[{"text":"A right circular cone or frustum geometry.","type":"text"}],"url":"/documentation/scenekit/scncone","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNCone"}],"title":"SCNCone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNCone"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","type":"topic","url":"/documentation/objectivec/nsobjectprotocol","role":"symbol"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"title":"CustomDebugStringConvertible","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","kind":"symbol","type":"topic","url":"/documentation/Swift/CustomDebugStringConvertible","role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/bottomRadius":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomRadius"}],"kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/bottomRadius","url":"/documentation/scenekit/scncone/bottomradius","role":"symbol","title":"bottomRadius","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRadius","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"text":"The radius of the cone’s circular base. Animatable.","type":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNCapsule"}],"title":"SCNCapsule","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule","abstract":[{"text":"A right circular cylinder geometry whose ends are capped with hemispheres.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SCNCapsule"}],"url":"/documentation/scenekit/scncapsule","type":"topic","role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNSphere":{"title":"SCNSphere","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNSphere","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNSphere","url":"/documentation/scenekit/scnsphere","abstract":[{"text":"A sphere (or ball or globe) geometry.","type":"text"}],"navigatorTitle":[{"text":"SCNSphere","kind":"identifier"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/materials":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"materials","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SCNMaterial","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNMaterial"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"materials","kind":"identifier"}],"type":"topic","url":"/documentation/scenekit/scngeometry/materials","title":"materials","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry/materials","abstract":[{"type":"text","text":"An array of "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial"},{"text":" objects that determine the geometry’s appearance when rendered.","type":"text"}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder":{"role":"symbol","kind":"symbol","title":"SCNCylinder","navigatorTitle":[{"kind":"identifier","text":"SCNCylinder"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNCylinder"}],"url":"/documentation/scenekit/scncylinder","abstract":[{"text":"A right circular cylinder geometry.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/height":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"height"}],"kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/height","url":"/documentation/scenekit/scncone/height","role":"symbol","title":"height","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"text":"The extent of the cylinder along its y-axis. Animatable.","type":"text"}]},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"kind":"symbol","url":"/documentation/Swift/CVarArg","type":"topic","title":"CVarArg","role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial":{"navigatorTitle":[{"kind":"identifier","text":"SCNMaterial"}],"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial","abstract":[{"type":"text","text":"A set of shading attributes that define the appearance of a geometry’s surface when rendered."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNMaterial"}],"kind":"symbol","title":"SCNMaterial","url":"/documentation/scenekit/scnmaterial"},"doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume":{"url":"/documentation/scenekit/scnboundingvolume","role":"symbol","title":"SCNBoundingVolume","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCNBoundingVolume"}],"navigatorTitle":[{"kind":"identifier","text":"SCNBoundingVolume"}],"type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNBoundingVolume","abstract":[{"text":"Methods common to the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode"},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry","isActive":true},{"type":"text","text":" classes for measuring location and size."}],"kind":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry":{"type":"topic","url":"/documentation/scenekit/scnnode/geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNGeometry","preciseIdentifier":"c:objc(cs)SCNGeometry"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"geometry"}],"abstract":[{"type":"text","text":"The geometry attached to the node."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry","kind":"symbol","role":"symbol","title":"geometry"},"doc://com.apple.scenekit/documentation/SceneKit/SCNFloor":{"navigatorTitle":[{"text":"SCNFloor","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNFloor","abstract":[{"text":"A plane that can optionally display a reflection of the scene above it.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNFloor","kind":"identifier"}],"kind":"symbol","title":"SCNFloor","url":"/documentation/scenekit/scnfloor"},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"kind":"symbol","url":"/documentation/foundation/nssecurecoding","type":"topic","title":"NSSecureCoding","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSSecureCoding"}],"abstract":[{"type":"text","text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid":{"navigatorTitle":[{"kind":"identifier","text":"SCNPyramid"}],"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid","abstract":[{"text":"A right rectangular pyramid geometry.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNPyramid"}],"kind":"symbol","title":"SCNPyramid","url":"/documentation/scenekit/scnpyramid"},"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Equatable","preciseIdentifier":"s:SQ"}],"identifier":"doc://com.externally.resolved.symbol/s:SH","title":"Hashable","url":"/documentation/Swift/Hashable"},"doc://com.apple.scenekit/documentation/SceneKit/SCNPlane":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNPlane","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/scenekit/scnplane","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPlane","abstract":[{"type":"text","text":"A rectangular, one-sided plane geometry of specified width and height."}],"title":"SCNPlane","navigatorTitle":[{"text":"SCNPlane","kind":"identifier"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNTorus":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNTorus","abstract":[{"text":"A torus, or ring-shaped geometry.","type":"text"}],"url":"/documentation/scenekit/scntorus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNTorus"}],"title":"SCNTorus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNTorus"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNAnimatable":{"abstract":[{"text":"The common interface for attaching animations to nodes, geometries, materials, and other SceneKit objects.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNAnimatable","kind":"identifier"}],"navigatorTitle":[{"text":"SCNAnimatable","kind":"identifier"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNAnimatable","title":"SCNAnimatable","url":"/documentation/scenekit/scnanimatable","type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/topRadius":{"type":"topic","url":"/documentation/scenekit/scncone/topradius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"type":"text","text":"The radius of the cone’s circular top. Animatable."}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/topRadius","role":"symbol","title":"topRadius","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"topRadius"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNShadable":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNShadable","kind":"identifier"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNShadable","url":"/documentation/scenekit/scnshadable","role":"symbol","title":"SCNShadable","kind":"symbol","navigatorTitle":[{"text":"SCNShadable","kind":"identifier"}],"type":"topic","abstract":[{"text":"Methods for customizing SceneKit’s rendering of geometry and materials using Metal or OpenGL shader programs.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"SCNCone"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"SCNCone"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"SCNCone"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit"]]}},{"op":"replace","path":"/topicSections","value":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNCone/init(topRadius:bottomRadius:height:)"],"anchor":"Creating-a-Cone","title":"Creating a Cone"},{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNCone/topRadius","doc://com.apple.scenekit/documentation/SceneKit/SCNCone/bottomRadius","doc://com.apple.scenekit/documentation/SceneKit/SCNCone/height"],"anchor":"Adjusting-a-Cones-Dimensions","title":"Adjusting a Cone’s Dimensions"},{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNCone/radialSegmentCount","doc://com.apple.scenekit/documentation/SceneKit/SCNCone/heightSegmentCount"],"anchor":"Adjusting-Geometric-Detail","title":"Adjusting Geometric Detail"}]},{"op":"replace","path":"/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry"],"title":"Inherits From"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNFloor","doc://com.apple.scenekit/documentation/SceneKit/SCNBox","doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule","doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder","doc://com.apple.scenekit/documentation/SceneKit/SCNPlane","doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid","doc://com.apple.scenekit/documentation/SceneKit/SCNSphere","doc://com.apple.scenekit/documentation/SceneKit/SCNTorus","doc://com.apple.scenekit/documentation/SceneKit/SCNTube"],"anchor":"Basic-Shapes","title":"Basic Shapes","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNCone","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry","text":"SCNGeometry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SCNGeometry"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}},{"value":"SCNGeometry","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title"},{"value":[{"text":"SCNGeometry","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments"},{"value":[{"kind":"identifier","text":"SCNGeometry"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle"},{"value":"coneWithTopRadius:bottomRadius:height:","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1init(topRadius:bottomRadius:height:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"coneWithTopRadius:bottomRadius:height:"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1init(topRadius:bottomRadius:height:)/fragments"},{"value":"SCNGeometryElement","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/title"},{"value":[{"kind":"identifier","text":"SCNGeometryElement"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/fragments"},{"value":[{"kind":"identifier","text":"SCNGeometryElement"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometryElement/navigatorTitle"},{"value":"SCNTube","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/title"},{"value":[{"kind":"identifier","text":"SCNTube"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/fragments"},{"value":[{"text":"SCNTube","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTube/navigatorTitle"},{"value":"SCNNode","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title"},{"value":[{"kind":"identifier","text":"SCNNode"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments"},{"value":[{"text":"SCNNode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle"},{"value":"SCNBox","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/title"},{"value":[{"text":"SCNBox","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/fragments"},{"value":[{"text":"SCNBox","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/navigatorTitle"},{"value":"heightSegmentCount","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1heightSegmentCount/title"},{"value":[{"kind":"identifier","text":"heightSegmentCount"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1heightSegmentCount/fragments"},{"value":"radialSegmentCount","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1radialSegmentCount/title"},{"value":[{"text":"radialSegmentCount","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1radialSegmentCount/fragments"},{"value":"SCNCone","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/title"},{"value":[{"text":"SCNCone","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/fragments"},{"value":[{"kind":"identifier","text":"SCNCone"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/navigatorTitle"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"value":"bottomRadius","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1bottomRadius/title"},{"value":[{"kind":"identifier","text":"bottomRadius"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1bottomRadius/fragments"},{"value":"SCNCapsule","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/title"},{"value":[{"kind":"identifier","text":"SCNCapsule"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/fragments"},{"value":[{"text":"SCNCapsule","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/navigatorTitle"},{"value":"SCNSphere","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/title"},{"value":[{"text":"SCNSphere","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/fragments"},{"value":[{"kind":"identifier","text":"SCNSphere"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/navigatorTitle"},{"value":"materials","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1materials/title"},{"value":[{"text":"materials","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry~1materials/fragments"},{"value":"SCNCylinder","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/title"},{"value":[{"text":"SCNCylinder","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/fragments"},{"value":[{"text":"SCNCylinder","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/navigatorTitle"},{"value":"height","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1height/title"},{"value":[{"kind":"identifier","text":"height"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1height/fragments"},{"value":"SCNMaterial","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/title"},{"value":[{"kind":"identifier","text":"SCNMaterial"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/fragments"},{"value":[{"kind":"identifier","text":"SCNMaterial"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/navigatorTitle"},{"value":"SCNBoundingVolume","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/title"},{"value":[{"text":"SCNBoundingVolume","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/fragments"},{"value":[{"text":"SCNBoundingVolume","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBoundingVolume/navigatorTitle"},{"value":"geometry","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/title"},{"value":[{"kind":"identifier","text":"geometry"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/fragments"},{"value":"SCNFloor","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/title"},{"value":[{"text":"SCNFloor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/fragments"},{"value":[{"text":"SCNFloor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFloor/navigatorTitle"},{"value":"SCNPyramid","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/title"},{"value":[{"kind":"identifier","text":"SCNPyramid"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/fragments"},{"value":[{"text":"SCNPyramid","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/navigatorTitle"},{"value":"SCNPlane","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/title"},{"value":[{"kind":"identifier","text":"SCNPlane"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/fragments"},{"value":[{"kind":"identifier","text":"SCNPlane"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPlane/navigatorTitle"},{"value":"SCNTorus","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/title"},{"value":[{"kind":"identifier","text":"SCNTorus"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/fragments"},{"value":[{"text":"SCNTorus","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTorus/navigatorTitle"},{"value":"SCNAnimatable","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimatable/title"},{"value":[{"text":"SCNAnimatable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimatable/fragments"},{"value":[{"text":"SCNAnimatable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNAnimatable/navigatorTitle"},{"value":"topRadius","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1topRadius/title"},{"value":[{"text":"topRadius","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1topRadius/fragments"},{"value":"SCNShadable","op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShadable/title"},{"value":[{"text":"SCNShadable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShadable/fragments"},{"value":[{"kind":"identifier","text":"SCNShadable"}],"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNShadable/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}