{
  "abstract": [
    {
      "text": "Properties affecting the behavior of a camera controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SCNCameraControlConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNCameraControlConfiguration"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNCameraControlConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "SCNCameraControlConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNCameraControlConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration": {
      "abstract": [
        {
          "text": "Properties affecting the behavior of a camera controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCameraControlConfiguration"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCameraControlConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SCNCameraControlConfiguration",
      "type": "topic",
      "url": "/documentation/scenekit/scncameracontrolconfiguration"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/allowsTranslation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/allowsTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsTranslation"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "allowsTranslation",
      "type": "topic",
      "url": "/documentation/scenekit/scncameracontrolconfiguration/allowstranslation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/autoSwitchToFreeCamera": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoSwitchToFreeCamera"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/autoSwitchToFreeCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoSwitchToFreeCamera"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "autoSwitchToFreeCamera",
      "type": "topic",
      "url": "/documentation/scenekit/scncameracontrolconfiguration/autoswitchtofreecamera"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/flyModeVelocity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flyModeVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/flyModeVelocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flyModeVelocity"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "flyModeVelocity",
      "type": "topic",
      "url": "/documentation/scenekit/scncameracontrolconfiguration/flymodevelocity"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/panSensitivity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panSensitivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/panSensitivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panSensitivity"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "panSensitivity",
      "type": "topic",
      "url": "/documentation/scenekit/scncameracontrolconfiguration/pansensitivity"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/rotationSensitivity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotationSensitivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/rotationSensitivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotationSensitivity"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "rotationSensitivity",
      "type": "topic",
      "url": "/documentation/scenekit/scncameracontrolconfiguration/rotationsensitivity"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/truckSensitivity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "truckSensitivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/truckSensitivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "truckSensitivity"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "truckSensitivity",
      "type": "topic",
      "url": "/documentation/scenekit/scncameracontrolconfiguration/trucksensitivity"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCameraController"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCameraController"
        }
      ],
      "role": "symbol",
      "title": "SCNCameraController",
      "type": "topic",
      "url": "/documentation/scenekit/scncameracontroller"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView/allowsCameraControl": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the user can manipulate the current point of view that is used to render the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsCameraControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView/allowsCameraControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsCameraControl"
        }
      ],
      "role": "symbol",
      "title": "allowsCameraControl",
      "type": "topic",
      "url": "/documentation/scenekit/scnview/allowscameracontrol"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView/cameraControlConfiguration": {
      "abstract": [
        {
          "text": "The current configuration for the camera controller’s event-handling behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraControlConfiguration"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SCNCameraControlConfiguration",
          "text": "SCNCameraControlConfiguration"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView/cameraControlConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraControlConfiguration"
        }
      ],
      "role": "symbol",
      "title": "cameraControlConfiguration",
      "type": "topic",
      "url": "/documentation/scenekit/scnview/cameracontrolconfiguration"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView/defaultCameraController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultCameraController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNCameraController",
          "text": "SCNCameraController"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView/defaultCameraController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultCameraController"
        }
      ],
      "role": "symbol",
      "title": "defaultCameraController",
      "type": "topic",
      "url": "/documentation/scenekit/scnview/defaultcameracontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Camera-Controls",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNView/allowsCameraControl",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNView/cameraControlConfiguration",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNView/defaultCameraController",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraController"
      ],
      "title": "Managing Camera Controls"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/allowsTranslation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/autoSwitchToFreeCamera",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/flyModeVelocity",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/panSensitivity",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/rotationSensitivity",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/truckSensitivity"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNCameraControlConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCameraControlConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCameraControlConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/allowsTranslation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/autoSwitchToFreeCamera",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/flyModeVelocity",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/panSensitivity",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/rotationSensitivity",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraControlConfiguration/truckSensitivity"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Camera-Controls",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNView/allowsCameraControl",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNView/cameraControlConfiguration",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNView/defaultCameraController",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNCameraController"
              ],
              "title": "Managing Camera Controls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNCameraControlConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1defaultCameraController/title",
          "value": "defaultCameraController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1defaultCameraController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultCameraController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1cameraControlConfiguration/title",
          "value": "cameraControlConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1cameraControlConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cameraControlConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1panSensitivity/title",
          "value": "panSensitivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1panSensitivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "panSensitivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1truckSensitivity/title",
          "value": "truckSensitivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1truckSensitivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "truckSensitivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1rotationSensitivity/title",
          "value": "rotationSensitivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1rotationSensitivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotationSensitivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1flyModeVelocity/title",
          "value": "flyModeVelocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1flyModeVelocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flyModeVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1allowsTranslation/title",
          "value": "allowsTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1allowsTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration/title",
          "value": "SCNCameraControlConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCameraControlConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCameraControlConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1autoSwitchToFreeCamera/title",
          "value": "autoSwitchToFreeCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraControlConfiguration~1autoSwitchToFreeCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoSwitchToFreeCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraController/title",
          "value": "SCNCameraController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCameraController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCameraController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCameraController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1allowsCameraControl/title",
          "value": "allowsCameraControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1allowsCameraControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsCameraControl"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scncameracontrolconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scncameracontrolconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
