{
  "abstract": [
    {
      "text": "Options for drawing overlays with SceneKit content that can aid in debugging, used with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNDebugOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNDebugOptions"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNDebugOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SCNDebugOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNDebugOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Debug options are bit mask patterns. To display multiple debugging overlays, combine options using the bitwise OR operator.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions": {
      "abstract": [
        {
          "text": "Options for drawing overlays with SceneKit content that can aid in debugging, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptions"
        }
      ],
      "role": "symbol",
      "title": "SCNDebugOptions",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/SCNDebugOptionNone": {
      "abstract": [
        {
          "text": "Disable all debugging overlays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionNone"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/SCNDebugOptionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNDebugOptionNone",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/scndebugoptionnone"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/init(rawvalue:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/renderAsWireframe": {
      "abstract": [
        {
          "text": "Display only wireframe placeholders for geometries in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderAsWireframe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/renderAsWireframe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionRenderAsWireframe"
        }
      ],
      "role": "symbol",
      "title": "renderAsWireframe",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/renderaswireframe"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showBoundingBoxes": {
      "abstract": [
        {
          "text": "Display the bounding boxes for any nodes with content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showBoundingBoxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showBoundingBoxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowBoundingBoxes"
        }
      ],
      "role": "symbol",
      "title": "showBoundingBoxes",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showboundingboxes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCameras": {
      "abstract": [
        {
          "text": "Display visualizations for nodes in the scene with attached cameras and their fields of view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showCameras"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCameras",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowCameras"
        }
      ],
      "role": "symbol",
      "title": "showCameras",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showcameras"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showConstraints": {
      "abstract": [
        {
          "text": "Display visualizations of the constraint objects acting on nodes in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showConstraints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showConstraints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowConstraints"
        }
      ],
      "role": "symbol",
      "title": "showConstraints",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showconstraints"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCreases": {
      "abstract": [
        {
          "text": "Display nonsmoothed crease regions for geometries affected by surface subdivision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showCreases"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCreases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowCreases"
        }
      ],
      "role": "symbol",
      "title": "showCreases",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showcreases"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showFeaturePoints": {
      "abstract": [
        {
          "text": "Display a point cloud showing intermediate results of the scene analysis that ARKit uses to track device position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showFeaturePoints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showFeaturePoints",
      "kind": "symbol",
      "role": "symbol",
      "title": "showFeaturePoints",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showfeaturepoints"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showLightExtents": {
      "abstract": [
        {
          "text": "Display the regions affected by each ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLight",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showLightExtents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showLightExtents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowLightExtents"
        }
      ],
      "role": "symbol",
      "title": "showLightExtents",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showlightextents"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showLightInfluences": {
      "abstract": [
        {
          "text": "Display the locations of each ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLight",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showLightInfluences"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showLightInfluences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowLightInfluences"
        }
      ],
      "role": "symbol",
      "title": "showLightInfluences",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showlightinfluences"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showPhysicsFields": {
      "abstract": [
        {
          "text": "Display the regions affected by each ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsField",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showPhysicsFields"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showPhysicsFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowPhysicsFields"
        }
      ],
      "role": "symbol",
      "title": "showPhysicsFields",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showphysicsfields"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showPhysicsShapes": {
      "abstract": [
        {
          "text": "Display the physics shapes for any nodes with attached ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showPhysicsShapes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showPhysicsShapes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowPhysicsShapes"
        }
      ],
      "role": "symbol",
      "title": "showPhysicsShapes",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showphysicsshapes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showSkeletons": {
      "abstract": [
        {
          "text": "Display visualizations of the skeletal animation parameters for relevant geometries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showSkeletons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showSkeletons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowSkeletons"
        }
      ],
      "role": "symbol",
      "title": "showSkeletons",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showskeletons"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWireframe": {
      "abstract": [
        {
          "text": "Display geometries in the scene with wireframe rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showWireframe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWireframe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowWireframe"
        }
      ],
      "role": "symbol",
      "title": "showWireframe",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showwireframe"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWorldOrigin": {
      "abstract": [
        {
          "text": "Display a coordinate axis visualization indicating the position and orientation of the AR world coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showWorldOrigin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWorldOrigin",
      "kind": "symbol",
      "role": "symbol",
      "title": "showWorldOrigin",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showworldorigin"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNLight": {
      "abstract": [
        {
          "text": "A light source that can be attached to a node to illuminate the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNLight"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLight"
        }
      ],
      "role": "symbol",
      "title": "SCNLight",
      "type": "topic",
      "url": "/documentation/scenekit/scnlight"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody": {
      "abstract": [
        {
          "text": "The physics simulation attributes attached to a scene graph node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsBody"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsBody"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsBody",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsField": {
      "abstract": [
        {
          "text": "An object that applies forces, such as gravitation, electromagnetism, and turbulence, to physics bodies within a certain area of effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsField"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsField"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsField",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsfield"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI": {
      "abstract": [
        {
          "text": "Options for choosing the graphics technology for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object (or other SceneKit renderer) to use for drawing its contents. Used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/renderingAPI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView/Option/preferredRenderingAPI",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " option when initializing an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNRenderingAPI"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderingAPI"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderingAPI",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderingapi"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/autoenablesDefaultLighting": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether SceneKit automatically adds lights to a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoenablesDefaultLighting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/autoenablesDefaultLighting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoenablesDefaultLighting"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "autoenablesDefaultLighting",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/autoenablesdefaultlighting"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions": {
      "abstract": [
        {
          "text": "Options for drawing overlay content in a scene that can aid debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "debugOptions"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "debugOptions",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/debugoptions"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/isJitteringEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether SceneKit applies jittering to reduce aliasing artifacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isJitteringEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/isJitteringEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jitteringEnabled"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isJitteringEnabled",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/isjitteringenabled"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/pointOfView": {
      "abstract": [
        {
          "text": "The node from which the scene’s contents are viewed for rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/pointOfView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointOfView"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pointOfView",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/pointofview"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/renderingAPI": {
      "abstract": [
        {
          "text": "The graphics technology SceneKit uses to render the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderingAPI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNRenderingAPI",
          "text": "SCNRenderingAPI"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/renderingAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderingAPI"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "renderingAPI",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/renderingapi"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/showsStatistics": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether SceneKit displays rendering performance statistics in an accessory view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsStatistics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/showsStatistics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsStatistics"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "showsStatistics",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/showsstatistics"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView": {
      "abstract": [
        {
          "text": "A view for displaying 3D SceneKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "role": "symbol",
      "title": "SCNView",
      "type": "topic",
      "url": "/documentation/scenekit/scnview"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView/Option/preferredRenderingAPI": {
      "abstract": [
        {
          "text": "The rendering API to use for rendering the view (for example, Metal or OpenGL).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredRenderingAPI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNView",
          "text": "SCNView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNViewOption",
          "text": "Option"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView/Option/preferredRenderingAPI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPreferredRenderingAPIKey"
        }
      ],
      "role": "symbol",
      "title": "preferredRenderingAPI",
      "type": "topic",
      "url": "/documentation/scenekit/scnview/option/preferredrenderingapi"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Scene-Display",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/pointOfView",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/autoenablesDefaultLighting",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/isJitteringEnabled",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/showsStatistics",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/renderingAPI",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI"
      ],
      "title": "Managing Scene Display"
    }
  ],
  "topicSections": [
    {
      "anchor": "Debugging-Geometry-and-Animation",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showBoundingBoxes",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWireframe",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/renderAsWireframe",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showSkeletons",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCreases",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showConstraints"
      ],
      "title": "Debugging Geometry and Animation"
    },
    {
      "anchor": "Debugging-Cameras-and-Lighting",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCameras",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showLightInfluences",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showLightExtents"
      ],
      "title": "Debugging Cameras and Lighting"
    },
    {
      "anchor": "Debugging-Physics",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showPhysicsShapes",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showPhysicsFields"
      ],
      "title": "Debugging Physics"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showFeaturePoints",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWorldOrigin"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNDebugOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Debugging-Geometry-and-Animation",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showBoundingBoxes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWireframe",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/renderAsWireframe",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showSkeletons",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCreases",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showConstraints"
              ],
              "title": "Debugging Geometry and Animation"
            },
            {
              "anchor": "Debugging-Cameras-and-Lighting",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCameras",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showLightInfluences",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showLightExtents"
              ],
              "title": "Debugging Cameras and Lighting"
            },
            {
              "anchor": "Debugging-Physics",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showPhysicsShapes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showPhysicsFields"
              ],
              "title": "Debugging Physics"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/SCNDebugOptionNone"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Scene-Display",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/pointOfView",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/autoenablesDefaultLighting",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/isJitteringEnabled",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/showsStatistics",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/renderingAPI",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderingAPI"
              ],
              "title": "Managing Scene Display"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNDebugOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showSkeletons/title",
          "value": "SCNDebugOptionShowSkeletons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showSkeletons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowSkeletons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showCameras/title",
          "value": "SCNDebugOptionShowCameras"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showCameras/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowCameras"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI/title",
          "value": "SCNRenderingAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderingAPI/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderingAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1showsStatistics/title",
          "value": "showsStatistics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1showsStatistics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsStatistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showPhysicsFields/title",
          "value": "SCNDebugOptionShowPhysicsFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showPhysicsFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowPhysicsFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/title",
          "value": "SCNPhysicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/title",
          "value": "SCNLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsField/title",
          "value": "SCNPhysicsField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showWireframe/title",
          "value": "SCNDebugOptionShowWireframe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showWireframe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowWireframe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1renderingAPI/title",
          "value": "renderingAPI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1renderingAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "renderingAPI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1renderAsWireframe/title",
          "value": "SCNDebugOptionRenderAsWireframe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1renderAsWireframe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionRenderAsWireframe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showCreases/title",
          "value": "SCNDebugOptionShowCreases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showCreases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowCreases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showConstraints/title",
          "value": "SCNDebugOptionShowConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showConstraints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showLightExtents/title",
          "value": "SCNDebugOptionShowLightExtents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showLightExtents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowLightExtents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions/title",
          "value": "SCNDebugOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1isJitteringEnabled/title",
          "value": "jitteringEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1isJitteringEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jitteringEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showPhysicsShapes/title",
          "value": "SCNDebugOptionShowPhysicsShapes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showPhysicsShapes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowPhysicsShapes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1debugOptions/title",
          "value": "debugOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1debugOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "debugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/title",
          "value": "SCNView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1autoenablesDefaultLighting/title",
          "value": "autoenablesDefaultLighting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1autoenablesDefaultLighting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoenablesDefaultLighting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showBoundingBoxes/title",
          "value": "SCNDebugOptionShowBoundingBoxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showBoundingBoxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowBoundingBoxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showLightInfluences/title",
          "value": "SCNDebugOptionShowLightInfluences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showLightInfluences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowLightInfluences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1Option~1preferredRenderingAPI/title",
          "value": "SCNPreferredRenderingAPIKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView~1Option~1preferredRenderingAPI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPreferredRenderingAPIKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1pointOfView/title",
          "value": "pointOfView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1pointOfView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointOfView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scndebugoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scndebugoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
