{"metadata":{"title":"SCNMatrix4Identity","roleHeading":"Global Variable","symbolKind":"var","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNMatrix4Identity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SCNMatrix4","preciseIdentifier":"c:@S@SCNMatrix4"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.10","deprecated":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"beta":false}],"externalID":"c:@SCNMatrix4Identity","modules":[{"name":"SceneKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNMatrix4Identity"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNMatrix4Identity"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct","kind":"typeIdentifier","text":"SCNMatrix4","preciseIdentifier":"c:@S@SCNMatrix4"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]},{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNMatrix4Identity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@SCNMatrix4","text":"SCNMatrix4","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Elements on the diagonal of this matrix are ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":"; all other elements are ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":". Multiplying another matrix by the identity matrix or multiplying the identity matrix by another matrix yields the other matrix.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"The 4 x 4 identity matrix."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Identity"},"variants":[{"paths":["/documentation/scenekit/scnmatrix4identity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/scenekit/scnmatrix4identity"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit"]]},"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias":{"role":"symbol","kind":"symbol","title":"SCNMatrix4","navigatorTitle":[{"text":"SCNMatrix4","kind":"identifier"}],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNMatrix4","kind":"identifier"}],"url":"/documentation/scenekit/scnmatrix4-swift.typealias","abstract":[{"text":"A representation of a 4 x 4 matrix.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias"},"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Identity":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNMatrix4Identity"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNMatrix4Identity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@SCNMatrix4","text":"SCNMatrix4"}],"url":"/documentation/scenekit/scnmatrix4identity","title":"SCNMatrix4Identity","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Identity","kind":"symbol","abstract":[{"text":"The 4 x 4 identity matrix.","type":"text"}]},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct":{"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCNMatrix4"}],"type":"topic","title":"SCNMatrix4","abstract":[{"text":"A representation of a 4 x 4 matrix.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNMatrix4"}],"url":"/documentation/scenekit/scnmatrix4-swift.struct"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.10","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Global Variable"},{"op":"replace","path":"/metadata/title","value":"SCNMatrix4Identity"},{"op":"replace","path":"/metadata/symbolKind","value":"var"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"SCNMatrix4Identity"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNMatrix4","preciseIdentifier":"c:@S@SCNMatrix4","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SCNMatrix4Identity","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]},{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNMatrix4","preciseIdentifier":"c:@T@SCNMatrix4","kind":"typeIdentifier","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias"},{"text":" ","kind":"text"},{"text":"SCNMatrix4Identity","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"SCNMatrix4","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/title","op":"replace"},{"value":[{"kind":"identifier","text":"SCNMatrix4"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SCNMatrix4"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/navigatorTitle","op":"replace"},{"value":"SCNMatrix4Identity","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Identity/title","op":"replace"},{"value":[{"text":"SCNMatrix4Identity","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Identity/fragments","op":"replace"},{"value":"SCNMatrix4","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/title","op":"replace"},{"value":[{"kind":"identifier","text":"SCNMatrix4"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/fragments","op":"replace"},{"value":[{"text":"SCNMatrix4","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}