{
  "abstract": [
    {
      "text": "A representation of a 4 x 4 matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@SCNMatrix4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNMatrix4"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNMatrix4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SCNMatrix4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SceneKit uses matrices to represent coordinate space transformations, which in turn can represent the combined position, rotation or orientation, and scale of an object in three-dimensional space.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In macOS, the fields in this structure are ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgfloat",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " values. In iOS, tvOS, and watchOS, these fields are ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/Float",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/QuartzCore/CATransform3D/init(_:)-6awvy": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "m"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float4x4a",
          "text": "float4x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CATransform3D/init(_:)-6awvy",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/QuartzCore/CATransform3D/init(_:)-6awvy"
    },
    "doc://com.apple.documentation/documentation/QuartzCore/CATransform3D/init(_:)-6euzs": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "m"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x4a",
          "text": "double4x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CATransform3D/init(_:)-6euzs",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/QuartzCore/CATransform3D/init(_:)-6euzs"
    },
    "doc://com.apple.documentation/documentation/Swift/Float": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Float",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cgfloat": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cgfloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct": {
      "abstract": [
        {
          "text": "A representation of a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/init()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(_:)-98ce8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float4x4a",
          "text": "float4x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(_:)-98ce8",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/init(_:)-98ce8"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(_:)-bqz6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x4a",
          "text": "double4x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(_:)-bqz6",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/init(_:)-bqz6"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(m11:m12:m13:m14:m21:m22:m23:m24:m31:m32:m33:m34:m41:m42:m43:m44:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "m11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m21"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m22"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m23"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m31"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m33"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m34"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m41"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m42"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m43"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "m44"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(m11:m12:m13:m14:m21:m22:m23:m24:m31:m32:m33:m34:m41:m42:m43:m44:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(m11:m12:m13:m14:m21:m22:m23:m24:m31:m32:m33:m34:m41:m42:m43:m44:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/init(m11:m12:m13:m14:m21:m22:m23:m24:m31:m32:m33:m34:m41:m42:m43:m44:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m11": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m11"
        }
      ],
      "role": "symbol",
      "title": "m11",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m11"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m12": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m12"
        }
      ],
      "role": "symbol",
      "title": "m12",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m12"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m13": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m13",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m13"
        }
      ],
      "role": "symbol",
      "title": "m13",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m13"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m14": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m14",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m14"
        }
      ],
      "role": "symbol",
      "title": "m14",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m14"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m21": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m21"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m21",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m21"
        }
      ],
      "role": "symbol",
      "title": "m21",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m21"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m22": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m22"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m22",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m22"
        }
      ],
      "role": "symbol",
      "title": "m22",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m22"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m23": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m23"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m23",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m23"
        }
      ],
      "role": "symbol",
      "title": "m23",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m23"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m24"
        }
      ],
      "role": "symbol",
      "title": "m24",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m24"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m31": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m31"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m31",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m31"
        }
      ],
      "role": "symbol",
      "title": "m31",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m31"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m32"
        }
      ],
      "role": "symbol",
      "title": "m32",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m32"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m33": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m33"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m33",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m33"
        }
      ],
      "role": "symbol",
      "title": "m33",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m33"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m34": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m34"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m34",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m34"
        }
      ],
      "role": "symbol",
      "title": "m34",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m34"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m41": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m41"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m41",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m41"
        }
      ],
      "role": "symbol",
      "title": "m41",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m41"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m42": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m42"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m42",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m42"
        }
      ],
      "role": "symbol",
      "title": "m42",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m42"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m43": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m43"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m43",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m43"
        }
      ],
      "role": "symbol",
      "title": "m43",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m43"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m44": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m44"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m44",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "m44"
        }
      ],
      "role": "symbol",
      "title": "m44",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct/m44"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias": {
      "abstract": [
        {
          "text": "A representation of a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.typealias"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4EqualToMatrix4(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the corresponding elements of two matrices are equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4EqualToMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4EqualToMatrix4(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4EqualToMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4EqualToMatrix4(_:_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4equaltomatrix4(_:_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4FromGLKMatrix4(_:)": {
      "abstract": [
        {
          "text": "Returns a SceneKit matrix corresponding to a GLKit matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4FromGLKMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4FromGLKMatrix4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4FromGLKMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4FromGLKMatrix4(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4fromglkmatrix4(_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Identity": {
      "abstract": [
        {
          "text": "The 4 x 4 identity matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4Identity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Identity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4Identity"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4Identity",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4identity"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Invert(_:)": {
      "abstract": [
        {
          "text": "Returns the inverse of the specified matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4Invert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Invert(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4Invert"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4Invert(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4invert(_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4IsIdentity(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the specified matrix is equal to the identity matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4IsIdentity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4IsIdentity(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4IsIdentity"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4IsIdentity(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4isidentity(_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeRotation(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a matrix describing a rotation transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4MakeRotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeRotation(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4MakeRotation"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4MakeRotation(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4makerotation(_:_:_:_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeScale(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a matrix describing a scale transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4MakeScale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeScale(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4MakeScale"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4MakeScale(_:_:_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4makescale(_:_:_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeTranslation(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a matrix describing a translation transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4MakeTranslation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeTranslation(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4MakeTranslation"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4MakeTranslation(_:_:_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4maketranslation(_:_:_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Mult(_:_:)": {
      "abstract": [
        {
          "text": "Returns the product of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4Mult"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Mult(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4Mult"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4Mult(_:_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4mult(_:_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Rotate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new matrix created by concatenating the specified matrix with a rotation transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4Rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Rotate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4Rotate"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4Rotate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4rotate(_:_:_:_:_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Scale(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new matrix created by concatenating the specified matrix with a scale transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4Scale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Scale(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4Scale"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4Scale(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4scale(_:_:_:_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4ToGLKMatrix4(_:)": {
      "abstract": [
        {
          "text": "Returns a GLKit matrix corresponding to a SceneKit matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4ToGLKMatrix4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "GLKMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4ToGLKMatrix4(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4ToGLKMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4ToGLKMatrix4(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4toglkmatrix4(_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Translate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new matrix created by concatenating the specified matrix with a translation transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4Translate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Translate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4Translate"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4Translate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4translate(_:_:_:_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion": {
      "abstract": [
        {
          "text": "A representation of a quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNQuaternion"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNQuaternion"
        }
      ],
      "role": "symbol",
      "title": "SCNQuaternion",
      "type": "topic",
      "url": "/documentation/scenekit/scnquaternion"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transforms-and-Rotations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion"
      ],
      "title": "Transforms and Rotations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Transform-Matrices",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeTranslation(_:_:_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeRotation(_:_:_:_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeScale(_:_:_:)"
      ],
      "title": "Creating Transform Matrices"
    },
    {
      "anchor": "Creating-Matrices-from-Elements",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init()",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(_:)-bqz6",
        "doc://com.apple.documentation/documentation/QuartzCore/CATransform3D/init(_:)-6euzs",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(_:)-98ce8",
        "doc://com.apple.documentation/documentation/QuartzCore/CATransform3D/init(_:)-6awvy",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/init(m11:m12:m13:m14:m21:m22:m23:m24:m31:m32:m33:m34:m41:m42:m43:m44:)"
      ],
      "title": "Creating Matrices from Elements"
    },
    {
      "anchor": "Performing-Matrix-Operations",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Translate(_:_:_:_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Rotate(_:_:_:_:_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Scale(_:_:_:_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Invert(_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Mult(_:_:)"
      ],
      "title": "Performing Matrix Operations"
    },
    {
      "anchor": "Converting-Matrix-Types",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4FromGLKMatrix4(_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4ToGLKMatrix4(_:)"
      ],
      "title": "Converting Matrix Types"
    },
    {
      "anchor": "Comparing-Matrices",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4EqualToMatrix4(_:_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4IsIdentity(_:)"
      ],
      "title": "Comparing Matrices"
    },
    {
      "anchor": "Identity-Constant",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Identity"
      ],
      "title": "Identity Constant"
    },
    {
      "anchor": "Matrix-Elements",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m11",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m12",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m13",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m14",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m21",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m22",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m23",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m24",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m31",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m32",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m33",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m34",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m41",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m42",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m43",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m44"
      ],
      "title": "Matrix Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNMatrix4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Transform-Matrices",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeTranslation(_:_:_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeRotation(_:_:_:_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4MakeScale(_:_:_:)"
              ],
              "title": "Creating Transform Matrices"
            },
            {
              "anchor": "Performing-Matrix-Operations",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Translate(_:_:_:_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Rotate(_:_:_:_:_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Scale(_:_:_:_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Invert(_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Mult(_:_:)"
              ],
              "title": "Performing Matrix Operations"
            },
            {
              "anchor": "Converting-Matrix-Types",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4FromGLKMatrix4(_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4ToGLKMatrix4(_:)"
              ],
              "title": "Converting Matrix Types"
            },
            {
              "anchor": "Comparing-Matrices",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4EqualToMatrix4(_:_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4IsIdentity(_:)"
              ],
              "title": "Comparing Matrices"
            },
            {
              "anchor": "Identity-Constant",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4Identity"
              ],
              "title": "Identity Constant"
            },
            {
              "anchor": "Matrix-Elements",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m11",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m12",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m13",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m14",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m21",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m22",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m23",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m24",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m31",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m32",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m33",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m34",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m41",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m42",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m43",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct/m44"
              ],
              "title": "Matrix Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transforms-and-Rotations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion"
              ],
              "title": "Transforms and Rotations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNMatrix4"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNMatrix4"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m21/title",
          "value": "m21"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m21/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m21"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Translate(_:_:_:_:)/title",
          "value": "SCNMatrix4Translate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Translate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4Translate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Identity/title",
          "value": "SCNMatrix4Identity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Identity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4Identity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m13/title",
          "value": "m13"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m13/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m13"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m11/title",
          "value": "m11"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m11/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m11"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m31/title",
          "value": "m31"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m31/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m31"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m33/title",
          "value": "m33"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m33/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m33"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m44/title",
          "value": "m44"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m44/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m44"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4MakeScale(_:_:_:)/title",
          "value": "SCNMatrix4MakeScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4MakeScale(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4MakeScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Mult(_:_:)/title",
          "value": "SCNMatrix4Mult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Mult(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4Mult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4IsIdentity(_:)/title",
          "value": "SCNMatrix4IsIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4IsIdentity(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4IsIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/title",
          "value": "SCNMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m42/title",
          "value": "m42"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m42/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m42"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4ToGLKMatrix4(_:)/title",
          "value": "SCNMatrix4ToGLKMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4ToGLKMatrix4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4ToGLKMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Scale(_:_:_:_:)/title",
          "value": "SCNMatrix4Scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Scale(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4Scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Invert(_:)/title",
          "value": "SCNMatrix4Invert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Invert(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4Invert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m14/title",
          "value": "m14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m14/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m43/title",
          "value": "m43"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m43/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m43"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m12/title",
          "value": "m12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4MakeTranslation(_:_:_:)/title",
          "value": "SCNMatrix4MakeTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4MakeTranslation(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4MakeTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Rotate(_:_:_:_:_:)/title",
          "value": "SCNMatrix4Rotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4Rotate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4Rotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4MakeRotation(_:_:_:_:)/title",
          "value": "SCNMatrix4MakeRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4MakeRotation(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4MakeRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m22/title",
          "value": "m22"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m22/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m22"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4FromGLKMatrix4(_:)/title",
          "value": "SCNMatrix4FromGLKMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4FromGLKMatrix4(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4FromGLKMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m34/title",
          "value": "m34"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m34/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m34"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/title",
          "value": "SCNMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4EqualToMatrix4(_:_:)/title",
          "value": "SCNMatrix4EqualToMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4EqualToMatrix4(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4EqualToMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m23/title",
          "value": "m23"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m23/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m23"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m41/title",
          "value": "m41"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m41/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m41"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m24/title",
          "value": "m24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/title",
          "value": "SCNQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m32/title",
          "value": "m32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct~1m32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "m32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnmatrix4-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnmatrix4-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
