{
  "abstract": [
    {
      "text": "Default values for a physics body’s ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/collisionBitMask",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNPhysicsCollisionCategory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNPhysicsCollisionCategory"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNPhysicsCollisionCategory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SCNPhysicsCollisionCategory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNPhysicsCollisionCategory"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You specify contact and collision behaviors by defining your own categories for the kinds of bodies your app simulates and setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/collisionBitMask",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties for each body to determine which kinds of bodies it collides with. Additionally, you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld/contactDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the physics world to be notified of collisions between bodies.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more details and example usage, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody#Defining-a-Bodys-Category-and-Collisions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the class overview.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody#Defining-a-Bodys-Category-and-Collisions": {
      "abstract": [],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody#Defining-a-Bodys-Category-and-Collisions",
      "kind": "section",
      "title": "Defining a Body’s Category and Collisions",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody#Defining-a-Bodys-Category-and-Collisions"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask": {
      "abstract": [
        {
          "text": "A mask that defines which categories this physics body belongs to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoryBitMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "categoryBitMask"
        }
      ],
      "role": "symbol",
      "title": "categoryBitMask",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/categorybitmask"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/collisionBitMask": {
      "abstract": [
        {
          "text": "A mask that defines which categories of physics bodies can collide with this physics body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionBitMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/collisionBitMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionBitMask"
        }
      ],
      "role": "symbol",
      "title": "collisionBitMask",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/collisionbitmask"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/contactTestBitMask": {
      "abstract": [
        {
          "text": "A mask that defines which categories of bodies cause intersection notifications with this physics body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactTestBitMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/contactTestBitMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contactTestBitMask"
        }
      ],
      "role": "symbol",
      "title": "contactTestBitMask",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/contacttestbitmask"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/continuousCollisionDetectionThreshold": {
      "abstract": [
        {
          "text": "The minimum distance the body must travel for SceneKit to apply a more precise (but more costly) algorithm to detect contacts with other bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuousCollisionDetectionThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/continuousCollisionDetectionThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continuousCollisionDetectionThreshold"
        }
      ],
      "role": "symbol",
      "title": "continuousCollisionDetectionThreshold",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/continuouscollisiondetectionthreshold"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory": {
      "abstract": [
        {
          "text": "Default values for a physics body’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/collisionBitMask",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsCollisionCategory"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsCollisionCategory"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsCollisionCategory",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicscollisioncategory"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/all": {
      "abstract": [
        {
          "text": "This is the default value for a physics body’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/collisionBitMask",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNPhysicsCollisionCategory",
          "text": "SCNPhysicsCollisionCategory"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsCollisionCategoryAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicscollisioncategory/all"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/default": {
      "abstract": [
        {
          "text": "The default ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value for dynamic and kinematic bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNPhysicsCollisionCategory",
          "text": "SCNPhysicsCollisionCategory"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsCollisionCategoryDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicscollisioncategory/default"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicscollisioncategory/init(rawvalue:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/static": {
      "abstract": [
        {
          "text": "The default ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value for static bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`static`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNPhysicsCollisionCategory",
          "text": "SCNPhysicsCollisionCategory"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/static",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsCollisionCategoryStatic"
        }
      ],
      "role": "symbol",
      "title": "static",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicscollisioncategory/static"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld/contactDelegate": {
      "abstract": [
        {
          "text": "A delegate that is called when two physics bodies come in contact with each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SCNPhysicsContactDelegate",
          "text": "SCNPhysicsContactDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld/contactDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contactDelegate"
        }
      ],
      "role": "symbol",
      "title": "contactDelegate",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsworld/contactdelegate"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Contacts-and-Collisions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/contactTestBitMask",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/collisionBitMask",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/continuousCollisionDetectionThreshold"
      ],
      "title": "Working with Contacts and Collisions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/default",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/static",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/all"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNPhysicsCollisionCategory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsCollisionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsCollisionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/default",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/static",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsCollisionCategory/all"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Contacts-and-Collisions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/categoryBitMask",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/contactTestBitMask",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/collisionBitMask",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/continuousCollisionDetectionThreshold"
              ],
              "title": "Working with Contacts and Collisions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNPhysicsCollisionCategory"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld~1contactDelegate/title",
          "value": "contactDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld~1contactDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contactDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1categoryBitMask/title",
          "value": "categoryBitMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1categoryBitMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "categoryBitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory/title",
          "value": "SCNPhysicsCollisionCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsCollisionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsCollisionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory~1all/title",
          "value": "SCNPhysicsCollisionCategoryAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsCollisionCategoryAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1contactTestBitMask/title",
          "value": "contactTestBitMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1contactTestBitMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contactTestBitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1continuousCollisionDetectionThreshold/title",
          "value": "continuousCollisionDetectionThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1continuousCollisionDetectionThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "continuousCollisionDetectionThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory~1static/title",
          "value": "SCNPhysicsCollisionCategoryStatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory~1static/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsCollisionCategoryStatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory~1default/title",
          "value": "SCNPhysicsCollisionCategoryDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsCollisionCategory~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsCollisionCategoryDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1collisionBitMask/title",
          "value": "collisionBitMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1collisionBitMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collisionBitMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnphysicscollisioncategory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnphysicscollisioncategory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
