{
  "abstract": [
    {
      "text": "A physics behavior that connects two bodies and allows them to pivot around each other on a single axis.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNPhysicsHingeJoint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNPhysicsHingeJoint"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNPhysicsHingeJoint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SCNPhysicsHingeJoint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNPhysicsHingeJoint"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A hinge has a single degree of freedom (rotation). You can also use a hinge joint to pin a body so that it can only move by rotating around a specific axis in the coordinate space of the node containing it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBallSocketJoint": {
      "abstract": [
        {
          "text": "A physics behavior that connects two physics bodies and allows them to pivot around each other in any direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsBallSocketJoint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBallSocketJoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsBallSocketJoint"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsBallSocketJoint",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsballsocketjoint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBehavior": {
      "abstract": [
        {
          "text": "The abstract superclass for joints, vehicle simulations, and other high-level behaviors that incorporate multiple physics bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsBehavior"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsBehavior"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsBehavior",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbehavior"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsConeTwistJoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsConeTwistJoint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsConeTwistJoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsConeTwistJoint"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsConeTwistJoint",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsconetwistjoint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint": {
      "abstract": [
        {
          "text": "A physics behavior that connects two bodies and allows them to pivot around each other on a single axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsHingeJoint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsHingeJoint"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsHingeJoint",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/anchorA": {
      "abstract": [
        {
          "text": "The point at which the hinge connects, relative to the node containing the first body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anchorA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/anchorA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anchorA"
        }
      ],
      "role": "symbol",
      "title": "anchorA",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/anchora"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/anchorB": {
      "abstract": [
        {
          "text": "The point at which the hinge connects, relative to the node containing the second body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anchorB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/anchorB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anchorB"
        }
      ],
      "role": "symbol",
      "title": "anchorB",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/anchorb"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/axisA": {
      "abstract": [
        {
          "text": "The axis that the hinge pivots around, relative to the node containing the first body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "axisA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/axisA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "axisA"
        }
      ],
      "role": "symbol",
      "title": "axisA",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/axisa"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/axisB": {
      "abstract": [
        {
          "text": "The axis that the hinge pivots around, relative to the node containing the second body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "axisB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/axisB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "axisB"
        }
      ],
      "role": "symbol",
      "title": "axisB",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/axisb"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/bodyA": {
      "abstract": [
        {
          "text": "The first physics body connected by the joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/bodyA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bodyA"
        }
      ],
      "role": "symbol",
      "title": "bodyA",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/bodya"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/bodyB": {
      "abstract": [
        {
          "text": "The second physics body connected by the joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/bodyB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bodyB"
        }
      ],
      "role": "symbol",
      "title": "bodyB",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/bodyb"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(body:axis:anchor:)": {
      "abstract": [
        {
          "text": "Creates a hinge joint that anchors a single physics body in space and lets it rotate around a specific axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "axis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(body:axis:anchor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jointWithBody:axis:anchor:"
        }
      ],
      "role": "symbol",
      "title": "init(body:axis:anchor:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/init(body:axis:anchor:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)": {
      "abstract": [
        {
          "text": "Creates a hinge joint connecting two physics bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bodyA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "axisA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchorA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bodyB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "axisB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchorB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
        }
      ],
      "role": "symbol",
      "title": "init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/init(bodya:axisa:anchora:bodyb:axisb:anchorb:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsSliderJoint": {
      "abstract": [
        {
          "text": "A physics behavior that connects two bodies and allows them to slide against each other and rotate around their connecting points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsSliderJoint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsSliderJoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsSliderJoint"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsSliderJoint",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicssliderjoint"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBehavior"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Joints",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsSliderJoint",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBallSocketJoint",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsConeTwistJoint"
      ],
      "title": "Joints"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Hinge-Joint",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(body:axis:anchor:)"
      ],
      "title": "Creating a Hinge Joint"
    },
    {
      "anchor": "Managing-the-Characteristics-of-a-Hinge-Joint",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/bodyA",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/axisA",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/anchorA",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/bodyB",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/axisB",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/anchorB"
      ],
      "title": "Managing the Characteristics of a Hinge Joint"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNPhysicsHingeJoint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsHingeJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsHingeJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Hinge-Joint",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(body:axis:anchor:)"
              ],
              "title": "Creating a Hinge Joint"
            },
            {
              "anchor": "Managing-the-Characteristics-of-a-Hinge-Joint",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/bodyA",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/axisA",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/anchorA",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/bodyB",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/axisB",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/anchorB"
              ],
              "title": "Managing the Characteristics of a Hinge Joint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBehavior"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Joints",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsSliderJoint",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBallSocketJoint",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsConeTwistJoint"
              ],
              "title": "Joints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNPhysicsHingeJoint"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBehavior",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SCNPhysicsBehavior",
                    "text": "SCNPhysicsBehavior"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1axisB/title",
          "value": "axisB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1axisB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "axisB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1anchorB/title",
          "value": "anchorB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1anchorB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anchorB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint/title",
          "value": "SCNPhysicsHingeJoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsHingeJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsHingeJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1axisA/title",
          "value": "axisA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1axisA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "axisA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1anchorA/title",
          "value": "anchorA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1anchorA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anchorA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1bodyB/title",
          "value": "bodyB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1bodyB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bodyB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsSliderJoint/title",
          "value": "SCNPhysicsSliderJoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsSliderJoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsSliderJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsSliderJoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsSliderJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBallSocketJoint/title",
          "value": "SCNPhysicsBallSocketJoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBallSocketJoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBallSocketJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBallSocketJoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBallSocketJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1bodyA/title",
          "value": "bodyA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1bodyA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bodyA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1init(body:axis:anchor:)/title",
          "value": "jointWithBody:axis:anchor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1init(body:axis:anchor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "jointWithBody:axis:anchor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBehavior/title",
          "value": "SCNPhysicsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)/title",
          "value": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsConeTwistJoint/title",
          "value": "SCNPhysicsConeTwistJoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsConeTwistJoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsConeTwistJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsConeTwistJoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsConeTwistJoint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnphysicshingejoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnphysicshingejoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
