{
  "abstract": [
    {
      "text": "Options for animating each particle with a sequence of images, used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNParticleImageSequenceAnimationMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNParticleImageSequenceAnimationMode"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNParticleImageSequenceAnimationMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SCNParticleImageSequenceAnimationMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode": {
      "abstract": [
        {
          "text": "Options for animating each particle with a sequence of images, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticleImageSequenceAnimationMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleImageSequenceAnimationMode"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleImageSequenceAnimationMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleimagesequenceanimationmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/autoReverse": {
      "abstract": [
        {
          "text": "After the animation displays all of its images, it plays again in reverse order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoReverse"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/autoReverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleImageSequenceAnimationModeAutoReverse"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleImageSequenceAnimationMode.autoReverse",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleimagesequenceanimationmode/autoreverse"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/clamp": {
      "abstract": [
        {
          "text": "The animation stops after displaying all of its images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clamp"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/clamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleImageSequenceAnimationModeClamp"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleImageSequenceAnimationMode.clamp",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleimagesequenceanimationmode/clamp"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleimagesequenceanimationmode/init(rawvalue:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/repeat": {
      "abstract": [
        {
          "text": "The animation loops after displaying all of its images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleImageSequenceAnimationModeRepeat"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleImageSequenceAnimationMode.repeat",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleimagesequenceanimationmode/repeat"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode": {
      "abstract": [
        {
          "text": "The animation mode for particle image animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceAnimationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNParticleImageSequenceAnimationMode",
          "text": "SCNParticleImageSequenceAnimationMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceAnimationMode"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceAnimationMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceanimationmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount": {
      "abstract": [
        {
          "text": "The number of columns for treating the particle image as a grid of animation frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceColumnCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceColumnCount"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceColumnCount",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequencecolumncount"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate": {
      "abstract": [
        {
          "text": "The rate, in frames per second, of particle image animation. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceFrameRate"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceFrameRate",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceframerate"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRateVariation": {
      "abstract": [
        {
          "text": "The range, in frames per second, of randomized frame rates for particle image animation. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceFrameRateVariation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRateVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceFrameRateVariation"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceFrameRateVariation",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceframeratevariation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame": {
      "abstract": [
        {
          "text": "The index of the first frame in a particle image animation. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceInitialFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceInitialFrame"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceInitialFrame",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceinitialframe"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrameVariation": {
      "abstract": [
        {
          "text": "The range of randomized initial frames for particle image animation. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceInitialFrameVariation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrameVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceInitialFrameVariation"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceInitialFrameVariation",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequenceinitialframevariation"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceRowCount": {
      "abstract": [
        {
          "text": "The number of rows for treating the particle image as a grid of animation frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSequenceRowCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceRowCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSequenceRowCount"
        }
      ],
      "role": "symbol",
      "title": "imageSequenceRowCount",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/imagesequencerowcount"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animating-Particle-Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceRowCount",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrameVariation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRateVariation",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode"
      ],
      "title": "Animating Particle Images"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/repeat",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/clamp",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/autoReverse"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNParticleImageSequenceAnimationMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/repeat",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/clamp",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleImageSequenceAnimationMode/autoReverse"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animating-Particle-Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceRowCount",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceColumnCount",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrame",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceInitialFrameVariation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRate",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceFrameRateVariation",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/imageSequenceAnimationMode"
              ],
              "title": "Animating Particle Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNParticleImageSequenceAnimationMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceInitialFrame/title",
          "value": "imageSequenceInitialFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceInitialFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceInitialFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceFrameRate/title",
          "value": "imageSequenceFrameRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceFrameRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceFrameRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode~1autoReverse/title",
          "value": "SCNParticleImageSequenceAnimationModeAutoReverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode~1autoReverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationModeAutoReverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode~1repeat/title",
          "value": "SCNParticleImageSequenceAnimationModeRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationModeRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode/title",
          "value": "SCNParticleImageSequenceAnimationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceColumnCount/title",
          "value": "imageSequenceColumnCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceColumnCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceColumnCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode~1clamp/title",
          "value": "SCNParticleImageSequenceAnimationModeClamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleImageSequenceAnimationMode~1clamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleImageSequenceAnimationModeClamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceFrameRateVariation/title",
          "value": "imageSequenceFrameRateVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceFrameRateVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceFrameRateVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceInitialFrameVariation/title",
          "value": "imageSequenceInitialFrameVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceInitialFrameVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceInitialFrameVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceRowCount/title",
          "value": "imageSequenceRowCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceRowCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceRowCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceAnimationMode/title",
          "value": "imageSequenceAnimationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1imageSequenceAnimationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSequenceAnimationMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnparticleimagesequenceanimationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnparticleimagesequenceanimationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
