{"metadata":{"navigatorTitle":[{"text":"SCNQuaternion","kind":"identifier"}],"title":"SCNQuaternion","modules":[{"name":"SceneKit"}],"roleHeading":"Type Alias","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false},{"unavailable":false,"beta":false,"name":"watchOS","deprecated":false}],"symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNQuaternion","kind":"identifier"}],"role":"symbol","externalID":"c:@T@SCNQuaternion"},"sections":[],"kind":"symbol","abstract":[{"text":"A representation of a quaternion.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCNQuaternion"},{"kind":"text","text":" = "},{"preciseIdentifier":"c:@S@SCNVector4","kind":"typeIdentifier","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector4","text":"SCNVector4"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"A quaternion is a mathematical construct useful for describing rotations in three-dimensional space. Although its implementation differs from that of a 4-component vector, you specify a quaternion value using the same fields as an "},{"code":"SCNVector4","type":"codeVoice"},{"type":"text","text":" structure."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"SceneKit uses unit quaternions (those whose components satisfy the equation "},{"type":"codeVoice","code":"x*x + y*y + z*z + w*w == 1"},{"type":"text","text":") for the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation"},{"type":"text","text":" property of nodes."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["/documentation/scenekit/scnquaternion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/scenekit/scnquaternion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion"},"seeAlsoSections":[{"title":"Transforms and Rotations","generated":true,"anchor":"Transforms-and-Rotations","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct","doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit"]]},"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias":{"role":"symbol","kind":"symbol","title":"SCNMatrix4","navigatorTitle":[{"text":"SCNMatrix4","kind":"identifier"}],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNMatrix4","kind":"identifier"}],"url":"/documentation/scenekit/scnmatrix4-swift.typealias","abstract":[{"text":"A representation of a 4 x 4 matrix.","type":"text"}],"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias"},"doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNQuaternion"}],"url":"/documentation/scenekit/scnquaternion","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNQuaternion","title":"SCNQuaternion","kind":"symbol","abstract":[{"type":"text","text":"A representation of a quaternion."}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNQuaternion"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNVector4":{"kind":"symbol","type":"topic","title":"SCNVector4","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector4","url":"/documentation/scenekit/scnvector4","navigatorTitle":[{"text":"SCNVector4","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCNVector4","kind":"identifier"}],"abstract":[{"type":"text","text":"A representation of a four-component vector."}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation":{"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNNode/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"role":"symbol","title":"orientation","url":"/documentation/scenekit/scnnode/orientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@SCNQuaternion","text":"SCNQuaternion"}],"abstract":[{"type":"text","text":"The node’s orientation, expressed as a quaternion. Animatable."}],"kind":"symbol","type":"topic"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct":{"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCNMatrix4"}],"type":"topic","title":"SCNMatrix4","abstract":[{"text":"A representation of a 4 x 4 matrix.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNMatrix4"}],"url":"/documentation/scenekit/scnmatrix4-swift.struct"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false},{"name":"watchOS","unavailable":false,"beta":false,"deprecated":false}],"op":"replace"},{"value":"Type Alias","op":"replace","path":"/metadata/roleHeading"},{"value":"SCNQuaternion","op":"replace","path":"/metadata/title"},{"value":"typealias","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"SCNQuaternion"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"SCNQuaternion","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct","doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.typealias"],"generated":true,"anchor":"Transforms-and-Rotations","title":"Transforms and Rotations"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@SCNVector4","kind":"typeIdentifier","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNVector4","text":"SCNVector4"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNQuaternion"},{"kind":"text","text":";"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/title","op":"replace","value":"SCNMatrix4"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/fragments","op":"replace","value":[{"text":"SCNMatrix4","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.typealias/navigatorTitle","op":"replace","value":[{"text":"SCNMatrix4","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/title","op":"replace","value":"SCNQuaternion"},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/fragments","value":[{"text":"SCNQuaternion","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNQuaternion/navigatorTitle","value":[{"text":"SCNQuaternion","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector4/title","value":"SCNVector4"},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector4/fragments","value":[{"text":"SCNVector4","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector4/navigatorTitle","value":[{"text":"SCNVector4","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1orientation/title","op":"replace","value":"orientation"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1orientation/fragments","op":"replace","value":[{"text":"orientation","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/title","op":"replace","value":"SCNMatrix4"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/fragments","op":"replace","value":[{"text":"SCNMatrix4","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/navigatorTitle","op":"replace","value":[{"text":"SCNMatrix4","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}