{
  "abstract": [
    {
      "text": "A mechanism for creating implicit animations and combining scene graph changes into atomic updates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNTransaction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNTransaction"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNTransaction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SCNTransaction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNTransaction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class methods to control the animation that results from changing animatable properties in the scene graph and to combine sets of changes into nested transactions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Adding-Animation-with-Automatic-Transaction",
          "level": 3,
          "text": "Adding Animation with Automatic Transaction",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SceneKit creates a transaction automatically whenever you modify the objects in a scene graph. This transaction groups any additional changes you make from the same thread during the current iteration of that thread’s run loop. When the run loop next iterates, SceneKit automatically commits the transaction, atomically applying all changes made during the transaction to the presentation scene graph (that is, the, version of the scene graph currently being displayed).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because an automatic transaction has a default duration of zero, any changes it contains appear instantly when SceneKit automatically commits the transaction. By using the ",
              "type": "text"
            },
            {
              "code": "setAnimationDuration(_:)",
              "type": "codeVoice"
            },
            {
              "text": " method in Swift, ",
              "type": "text"
            },
            {
              "code": "setAnimationDuration:",
              "type": "codeVoice"
            },
            {
              "text": " in Objective-C, to change the duration, you ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "implicitly animate",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " all changes made to animatable properties during the transaction. You can use implicit animation to add animation to a scene quickly and easily. For example, the code in Listing 1 fades out and moves one node, fades in another, moves and zooms the point of view camera, and focuses a spotlight, all in a single one-second animation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Implicitly animating several property changes",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "[SCNTransaction setAnimationDuration:1.0];    ",
            "_textNode.position = SCNVector3Make(0.0, -10.0, 0.0);",
            "_textNode.opacity = 0.0;",
            "_heroNode.opacity = 1.0;",
            "view.pointOfView = _heroCamera;",
            "_heroCamera.camera.yFov = 20.0;",
            "_lightNode.light.spotInnerAngle = 30.0;"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "anchor": "Creating-Advanced-Animations-with-Custom-Transactions",
          "level": 3,
          "text": "Creating Advanced Animations with Custom Transactions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class methods to create and manage a hierarchy of your own transactions. By nesting custom transactions, you can group sets of scene graph changes, applying different animation parameters to each group. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/begin()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to create a custom transaction, nested within the current transaction if one exists. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/commit()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to end a transaction, applying all scene graph changes made within.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction": {
      "abstract": [
        {
          "text": "A mechanism for creating implicit animations and combining scene graph changes into atomic updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNTransaction"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNTransaction"
        }
      ],
      "role": "symbol",
      "title": "SCNTransaction",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/animationDuration": {
      "abstract": [
        {
          "text": "Returns the duration, in seconds, of all animations within the current transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/animationDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animationDuration"
        }
      ],
      "role": "symbol",
      "title": "animationDuration",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/animationduration"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/animationTimingFunction": {
      "abstract": [
        {
          "text": "Returns the timing function that SceneKit uses for all animations within this transaction group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationTimingFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CAMediaTimingFunction",
          "text": "CAMediaTimingFunction"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/animationTimingFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animationTimingFunction"
        }
      ],
      "role": "symbol",
      "title": "animationTimingFunction",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/animationtimingfunction"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/begin()": {
      "abstract": [
        {
          "text": "Begins a new transaction for the current thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "begin"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/begin()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "begin"
        }
      ],
      "role": "symbol",
      "title": "begin()",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/begin()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/commit()": {
      "abstract": [
        {
          "text": "Commits all changes made during the current transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commit"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/commit()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commit"
        }
      ],
      "role": "symbol",
      "title": "commit()",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/commit()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/completionBlock": {
      "abstract": [
        {
          "text": "Returns the block previously associated with the current transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionBlock"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/completionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionBlock"
        }
      ],
      "role": "symbol",
      "title": "completionBlock",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/completionblock"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/disableActions": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether changes to animatable properties during the transaction are implicitly animated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableActions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/disableActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableActions"
        }
      ],
      "role": "symbol",
      "title": "disableActions",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/disableactions"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/flush()": {
      "abstract": [
        {
          "text": "Applies all changes from the current automatic transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flush"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/flush()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flush"
        }
      ],
      "role": "symbol",
      "title": "flush()",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/flush()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/lock()": {
      "abstract": [
        {
          "text": "Attempts to acquire a recursive spinlock to ensure the validity of values you retrieve during the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lock"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/lock()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lock"
        }
      ],
      "role": "symbol",
      "title": "lock()",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/lock()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/setValue(_:forKey:)": {
      "abstract": [
        {
          "text": "Associates an arbitrary object with the current transaction using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/setValue(_:forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValue:forKey:"
        }
      ],
      "role": "symbol",
      "title": "setValue(_:forKey:)",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/setvalue(_:forkey:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/unlock()": {
      "abstract": [
        {
          "text": "Relinquishes a previously acquired transaction lock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlock"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/unlock()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlock"
        }
      ],
      "role": "symbol",
      "title": "unlock()",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/unlock()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/value(forKey:)": {
      "abstract": [
        {
          "text": "Returns the object previously associated with the current transaction using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/value(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForKey:"
        }
      ],
      "role": "symbol",
      "title": "value(forKey:)",
      "type": "topic",
      "url": "/documentation/scenekit/scntransaction/value(forkey:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content": {
      "abstract": [
        {
          "text": "Learn about implicit animations, explicit animations, and actions, and when to choose each in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content",
      "kind": "article",
      "role": "article",
      "title": "Animating SceneKit Content",
      "type": "topic",
      "url": "/documentation/scenekit/animating-scenekit-content"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-and-Committing-Transactions",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/begin()",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/commit()",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/flush()"
      ],
      "title": "Creating and Committing Transactions"
    },
    {
      "anchor": "Overriding-Animation-Duration-and-Timing",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/animationDuration",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/animationTimingFunction"
      ],
      "title": "Overriding Animation Duration and Timing"
    },
    {
      "anchor": "Temporarily-Disabling-Property-Animations",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/disableActions"
      ],
      "title": "Temporarily Disabling Property Animations"
    },
    {
      "anchor": "Getting-and-Setting-Completion-Block-Objects",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/completionBlock"
      ],
      "title": "Getting and Setting Completion Block Objects"
    },
    {
      "anchor": "Managing-Concurrency",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/lock()",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/unlock()"
      ],
      "title": "Managing Concurrency"
    },
    {
      "anchor": "Getting-and-Setting-Transaction-Properties",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/setValue(_:forKey:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/value(forKey:)"
      ],
      "title": "Getting and Setting Transaction Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNTransaction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-and-Committing-Transactions",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/begin()",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/commit()",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/flush()"
              ],
              "title": "Creating and Committing Transactions"
            },
            {
              "anchor": "Overriding-Animation-Duration-and-Timing",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/animationDuration",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/animationTimingFunction"
              ],
              "title": "Overriding Animation Duration and Timing"
            },
            {
              "anchor": "Temporarily-Disabling-Property-Animations",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/disableActions"
              ],
              "title": "Temporarily Disabling Property Animations"
            },
            {
              "anchor": "Getting-and-Setting-Completion-Block-Objects",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/completionBlock"
              ],
              "title": "Getting and Setting Completion Block Objects"
            },
            {
              "anchor": "Managing-Concurrency",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/lock()",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/unlock()"
              ],
              "title": "Managing Concurrency"
            },
            {
              "anchor": "Getting-and-Setting-Transaction-Properties",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/setValue(_:forKey:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNTransaction/value(forKey:)"
              ],
              "title": "Getting and Setting Transaction Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNTransaction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1flush()/title",
          "value": "flush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1flush()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "flush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1unlock()/title",
          "value": "unlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1unlock()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "unlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1value(forKey:)/title",
          "value": "valueForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1value(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "valueForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/title",
          "value": "SCNTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1setValue(_:forKey:)/title",
          "value": "setValue:forKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1setValue(_:forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setValue:forKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1animationDuration/title",
          "value": "animationDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1animationDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "animationDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1completionBlock/title",
          "value": "completionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1completionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1begin()/title",
          "value": "begin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1begin()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "begin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1lock()/title",
          "value": "lock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1lock()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "lock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1disableActions/title",
          "value": "disableActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1disableActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disableActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1animationTimingFunction/title",
          "value": "animationTimingFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1animationTimingFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "animationTimingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1commit()/title",
          "value": "commit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNTransaction~1commit()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "commit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scntransaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scntransaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
