{
  "abstract": [
    {
      "text": "Error codes for the GameKit error domain.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "GKError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError": {
      "abstract": [
        {
          "text": "The error structure used by this framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "role": "symbol",
      "title": "GKError",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code": {
      "abstract": [
        {
          "text": "Error codes for the GameKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiNotAvailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the API isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorAPINotAvailable"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.apiNotAvailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/apinotavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiObsolete": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because Apple deprecated the API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiObsolete"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiObsolete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorAPIObsolete"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.apiObsolete",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/apiobsolete"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/appUnlisted": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the game isn’t available on the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appUnlisted"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/appUnlisted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorAppUnlisted"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.appUnlisted",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/appunlisted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/authenticationInProgress": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the local player is already authenticating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationInProgress"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/authenticationInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorAuthenticationInProgress"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.authenticationInProgress",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/authenticationinprogress"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/cancelled": {
      "abstract": [
        {
          "text": "The system canceled the requested operation or the user disabled it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorCancelled"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.cancelled",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/cancelled"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/challengeInvalid": {
      "abstract": [
        {
          "text": "The challenge request failed due to invalid challenge data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "challengeInvalid"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/challengeInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorChallengeInvalid"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.challengeInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/challengeinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/communicationsFailure": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation due to an error communicating with the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationsFailure"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/communicationsFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorCommunicationsFailure"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.communicationsFailure",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/communicationsfailure"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/connectionTimeout": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the connection timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionTimeout"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/connectionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorConnectionTimeout"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.connectionTimeout",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/connectiontimeout"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/debugMode": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugMode"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/debugMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorDebugMode"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.debugMode",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/debugmode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListDenied": {
      "abstract": [
        {
          "text": "Access to the local player’s list of friends denied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friendListDenied"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorFriendListDenied"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.friendListDenied",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/friendlistdenied"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListDescriptionMissing": {
      "abstract": [
        {
          "text": "Access to the local player’s list of friends denied for lack of a reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friendListDescriptionMissing"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListDescriptionMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorFriendListDescriptionMissing"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.friendListDescriptionMissing",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/friendlistdescriptionmissing"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListRestricted": {
      "abstract": [
        {
          "text": "Access to the local player’s list of friends restricted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friendListRestricted"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListRestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorFriendListRestricted"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.friendListRestricted",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/friendlistrestricted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendRequestNotAvailable": {
      "abstract": [
        {
          "text": "The player can’t send a friend request at this time from this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friendRequestNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendRequestNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorFriendRequestNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.friendRequestNotAvailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/friendrequestnotavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameSessionRequestInvalid": {
      "abstract": [
        {
          "text": "The properties of the game session request are impossible to fulfill.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gameSessionRequestInvalid"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameSessionRequestInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorGameSessionRequestInvalid"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.gameSessionRequestInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/gamesessionrequestinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameUnrecognized": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because Game Center doesn’t recognize the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gameUnrecognized"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameUnrecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorGameUnrecognized"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.gameUnrecognized",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/gameunrecognized"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/iCloudUnavailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because it can’t access the player’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iCloudUnavailable"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/iCloudUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorICloudUnavailable"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.iCloudUnavailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/icloudunavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/init(rawvalue:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidCredentials": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user name or password are incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCredentials"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorInvalidCredentials"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.invalidCredentials",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/invalidcredentials"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidParameter": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because one or more parameters are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.invalidParameter",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/invalidparameter"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidPlayer": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPlayer"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorInvalidPlayer"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.invalidPlayer",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/invalidplayer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invitationsDisabled": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the receiving player has disabled invitations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitationsDisabled"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invitationsDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorInvitationsDisabled"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.invitationsDisabled",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/invitationsdisabled"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/lockdownMode": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player enabled Lockdown Mode on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockdownMode"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/lockdownMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorLockdownMode"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.lockdownMode",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/lockdownmode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchNotConnected": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the match isn’t connected to other players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchNotConnected"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchNotConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorMatchNotConnected"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.matchNotConnected",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/matchnotconnected"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchRequestInvalid": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the match request is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchRequestInvalid"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchRequestInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorMatchRequestInvalid"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.matchRequestInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/matchrequestinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthenticated": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the system hasn’t authorized the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthenticated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorNotAuthenticated"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.notAuthenticated",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/notauthenticated"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthorized": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the system hasn’t authorized the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorized"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.notAuthorized",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/notauthorized"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notSupported": {
      "abstract": [
        {
          "text": "The app doesn’t have Game Center enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorNotSupported"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.notSupported",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/notsupported"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/parentalControlsBlocked": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user disabled this feature in Restrictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentalControlsBlocked"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/parentalControlsBlocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorParentalControlsBlocked"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.parentalControlsBlocked",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/parentalcontrolsblocked"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerPhotoFailure": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation to retrieve a player’s photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerPhotoFailure"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerPhotoFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorPlayerPhotoFailure"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.playerPhotoFailure",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/playerphotofailure"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusExceedsMaximumLength": {
      "abstract": [
        {
          "text": "The player’s status exceeds the maximum length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerStatusExceedsMaximumLength"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusExceedsMaximumLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorPlayerStatusExceedsMaximumLength"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.playerStatusExceedsMaximumLength",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/playerstatusexceedsmaximumlength"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusInvalid": {
      "abstract": [
        {
          "text": "The player’s status is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerStatusInvalid"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorPlayerStatusInvalid"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.playerStatusInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/playerstatusinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/restrictedToAutomatch": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player is using automatch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedToAutomatch"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/restrictedToAutomatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorRestrictedToAutomatch"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.restrictedToAutomatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/restrictedtoautomatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/scoreNotSet": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the system hasn’t set the score.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scoreNotSet"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/scoreNotSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorScoreNotSet"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.scoreNotSet",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/scorenotset"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidParticipant": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the specified participant is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedInvalidParticipant"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidParticipant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorTurnBasedInvalidParticipant"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.turnBasedInvalidParticipant",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/turnbasedinvalidparticipant"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidState": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the session is in an invalid state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedInvalidState"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorTurnBasedInvalidState"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.turnBasedInvalidState",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/turnbasedinvalidstate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidTurn": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the participant doesn’t have the required turn state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedInvalidTurn"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidTurn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorTurnBasedInvalidTurn"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.turnBasedInvalidTurn",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/turnbasedinvalidturn"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedMatchDataTooLarge": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the match data is too large.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedMatchDataTooLarge"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedMatchDataTooLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorTurnBasedMatchDataTooLarge"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.turnBasedMatchDataTooLarge",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/turnbasedmatchdatatoolarge"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedTooManySessions": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because it exceeds the maximum number of sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedTooManySessions"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedTooManySessions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorTurnBasedTooManySessions"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.turnBasedTooManySessions",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/turnbasedtoomanysessions"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/ubiquityContainerUnavailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user hasn’t signed in to iCloud or hasn’t enabled iCloud Drive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ubiquityContainerUnavailable"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/ubiquityContainerUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUbiquityContainerUnavailable"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.ubiquityContainerUnavailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/ubiquitycontainerunavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/underage": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because this feature isn’t available to underage players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underage"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/underage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUnderage"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.underage",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/underage"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unexpectedConnection": {
      "abstract": [
        {
          "text": "An unexpected player has connected to a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedConnection"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unexpectedConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUnexpectedConnection"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.unexpectedConnection",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/unexpectedconnection"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unknown": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation due to an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.unknown",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/unknown"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/userDenied": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user denied it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDenied"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/userDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUserDenied"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.userDenied",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/userdenied"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for general game errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GKErrorDomain",
      "type": "topic",
      "url": "/documentation/gamekit/gkerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError",
        "doc://com.apple.gamekit/documentation/GameKit/GKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuration-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameUnrecognized",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notSupported",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/appUnlisted"
      ],
      "title": "Configuration Errors"
    },
    {
      "anchor": "Communication-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unknown",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/cancelled",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/communicationsFailure",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidPlayer",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidParameter",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameSessionRequestInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiNotAvailable",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/connectionTimeout",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiObsolete"
      ],
      "title": "Communication Errors"
    },
    {
      "anchor": "Player-Related-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/userDenied",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidCredentials",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthenticated",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/authenticationInProgress",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/parentalControlsBlocked",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusExceedsMaximumLength",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/underage",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerPhotoFailure",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/ubiquityContainerUnavailable",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthorized",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/iCloudUnavailable",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/lockdownMode"
      ],
      "title": "Player-Related Errors"
    },
    {
      "anchor": "Friend-List-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListDescriptionMissing",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListRestricted",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListDenied",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendRequestNotAvailable"
      ],
      "title": "Friend List Errors"
    },
    {
      "anchor": "Matchmaking-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchRequestInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unexpectedConnection",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invitationsDisabled",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchNotConnected",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/restrictedToAutomatch"
      ],
      "title": "Matchmaking Errors"
    },
    {
      "anchor": "Turn-Based-Game-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedMatchDataTooLarge",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedTooManySessions",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidParticipant",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidTurn",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidState"
      ],
      "title": "Turn-Based Game Errors"
    },
    {
      "anchor": "Leaderboard-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/scoreNotSet"
      ],
      "title": "Leaderboard Errors"
    },
    {
      "anchor": "Challenges-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/challengeInvalid"
      ],
      "title": "Challenges Errors"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/debugMode"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuration-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameUnrecognized",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notSupported",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/appUnlisted"
              ],
              "title": "Configuration Errors"
            },
            {
              "anchor": "Communication-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unknown",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/cancelled",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/communicationsFailure",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidPlayer",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidParameter",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameSessionRequestInvalid",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiNotAvailable",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/connectionTimeout",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiObsolete"
              ],
              "title": "Communication Errors"
            },
            {
              "anchor": "Player-Related-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/userDenied",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidCredentials",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthenticated",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/authenticationInProgress",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/parentalControlsBlocked",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusExceedsMaximumLength",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusInvalid",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/underage",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerPhotoFailure",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/ubiquityContainerUnavailable",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthorized",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/iCloudUnavailable",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/lockdownMode"
              ],
              "title": "Player-Related Errors"
            },
            {
              "anchor": "Friend-List-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListDescriptionMissing",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListRestricted",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendListDenied",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/friendRequestNotAvailable"
              ],
              "title": "Friend List Errors"
            },
            {
              "anchor": "Matchmaking-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchRequestInvalid",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unexpectedConnection",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invitationsDisabled",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchNotConnected",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/restrictedToAutomatch"
              ],
              "title": "Matchmaking Errors"
            },
            {
              "anchor": "Turn-Based-Game-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedMatchDataTooLarge",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedTooManySessions",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidParticipant",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidTurn",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/turnBasedInvalidState"
              ],
              "title": "Turn-Based Game Errors"
            },
            {
              "anchor": "Leaderboard-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/scoreNotSet"
              ],
              "title": "Leaderboard Errors"
            },
            {
              "anchor": "Challenges-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/challengeInvalid"
              ],
              "title": "Challenges Errors"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/debugMode"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedInvalidParticipant/title",
          "value": "GKErrorTurnBasedInvalidParticipant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedInvalidParticipant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorTurnBasedInvalidParticipant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invitationsDisabled/title",
          "value": "GKErrorInvitationsDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invitationsDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorInvitationsDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1matchNotConnected/title",
          "value": "GKErrorMatchNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1matchNotConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorMatchNotConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1apiObsolete/title",
          "value": "GKErrorAPIObsolete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1apiObsolete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorAPIObsolete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedTooManySessions/title",
          "value": "GKErrorTurnBasedTooManySessions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedTooManySessions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorTurnBasedTooManySessions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1unknown/title",
          "value": "GKErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1iCloudUnavailable/title",
          "value": "GKErrorICloudUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1iCloudUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorICloudUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1unexpectedConnection/title",
          "value": "GKErrorUnexpectedConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1unexpectedConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUnexpectedConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerStatusExceedsMaximumLength/title",
          "value": "GKErrorPlayerStatusExceedsMaximumLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerStatusExceedsMaximumLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorPlayerStatusExceedsMaximumLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1restrictedToAutomatch/title",
          "value": "GKErrorRestrictedToAutomatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1restrictedToAutomatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorRestrictedToAutomatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedInvalidState/title",
          "value": "GKErrorTurnBasedInvalidState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedInvalidState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorTurnBasedInvalidState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1gameSessionRequestInvalid/title",
          "value": "GKErrorGameSessionRequestInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1gameSessionRequestInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorGameSessionRequestInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1friendListDenied/title",
          "value": "GKErrorFriendListDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1friendListDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorFriendListDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedInvalidTurn/title",
          "value": "GKErrorTurnBasedInvalidTurn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedInvalidTurn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorTurnBasedInvalidTurn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1cancelled/title",
          "value": "GKErrorCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1ubiquityContainerUnavailable/title",
          "value": "GKErrorUbiquityContainerUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1ubiquityContainerUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUbiquityContainerUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1authenticationInProgress/title",
          "value": "GKErrorAuthenticationInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1authenticationInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorAuthenticationInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKErrorDomain/title",
          "value": "GKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1gameUnrecognized/title",
          "value": "GKErrorGameUnrecognized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1gameUnrecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorGameUnrecognized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1debugMode/title",
          "value": "GKErrorDebugMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1debugMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorDebugMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1friendListDescriptionMissing/title",
          "value": "GKErrorFriendListDescriptionMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1friendListDescriptionMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorFriendListDescriptionMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1scoreNotSet/title",
          "value": "GKErrorScoreNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1scoreNotSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorScoreNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1friendRequestNotAvailable/title",
          "value": "GKErrorFriendRequestNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1friendRequestNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorFriendRequestNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1lockdownMode/title",
          "value": "GKErrorLockdownMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1lockdownMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorLockdownMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1challengeInvalid/title",
          "value": "GKErrorChallengeInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1challengeInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorChallengeInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1matchRequestInvalid/title",
          "value": "GKErrorMatchRequestInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1matchRequestInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorMatchRequestInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1apiNotAvailable/title",
          "value": "GKErrorAPINotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1apiNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorAPINotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1communicationsFailure/title",
          "value": "GKErrorCommunicationsFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1communicationsFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCommunicationsFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidParameter/title",
          "value": "GKErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1parentalControlsBlocked/title",
          "value": "GKErrorParentalControlsBlocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1parentalControlsBlocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorParentalControlsBlocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notAuthorized/title",
          "value": "GKErrorNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidPlayer/title",
          "value": "GKErrorInvalidPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorInvalidPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/title",
          "value": "GKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidCredentials/title",
          "value": "GKErrorInvalidCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorInvalidCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notAuthenticated/title",
          "value": "GKErrorNotAuthenticated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notAuthenticated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorNotAuthenticated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notSupported/title",
          "value": "GKErrorNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1friendListRestricted/title",
          "value": "GKErrorFriendListRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1friendListRestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorFriendListRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1underage/title",
          "value": "GKErrorUnderage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1underage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUnderage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerStatusInvalid/title",
          "value": "GKErrorPlayerStatusInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerStatusInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorPlayerStatusInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerPhotoFailure/title",
          "value": "GKErrorPlayerPhotoFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerPhotoFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorPlayerPhotoFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1connectionTimeout/title",
          "value": "GKErrorConnectionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1connectionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorConnectionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1appUnlisted/title",
          "value": "GKErrorAppUnlisted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1appUnlisted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorAppUnlisted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedMatchDataTooLarge/title",
          "value": "GKErrorTurnBasedMatchDataTooLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1turnBasedMatchDataTooLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorTurnBasedMatchDataTooLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1userDenied/title",
          "value": "GKErrorUserDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1userDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUserDenied"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
