{"kind":"symbol","metadata":{"symbolKind":"init","modules":[{"name":"Core Audio"}],"externalID":"s:9CoreAudio0B13HardwareClockC2idACs6UInt32V_tcfc","roleHeading":"Initializer","role":"symbol","title":"init(id:)","platforms":[{"unavailable":false,"introducedAt":"15.0","beta":false,"name":"macOS","deprecated":false}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AudioObjectID","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID"},{"text":")","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/audiohardwareclock/init(id:)"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier","text":"AudioObjectID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock/init(id:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID":{"navigatorTitle":[{"kind":"identifier","text":"AudioObjectID"}],"url":"/documentation/coreaudio/audioobjectid","title":"AudioObjectID","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioObjectID"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"AudioHardwareClock","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock","navigatorTitle":[{"text":"AudioHardwareClock","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioHardwareClock","kind":"identifier"}],"url":"/documentation/coreaudio/audiohardwareclock"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock/init(id:)":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"init(id:)","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareClock/init(id:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AudioObjectID","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID"},{"text":")","kind":"text"}],"url":"/documentation/coreaudio/audiohardwareclock/init(id:)"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/title","value":"AudioObjectID","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/fragments","value":[{"kind":"identifier","text":"AudioObjectID"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/navigatorTitle","value":[{"kind":"identifier","text":"AudioObjectID"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}