{
  "abstract": [
    {
      "text": "Provides an unaltered version of its video asset.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBaseVideo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHAssetResourceType@PHAssetResourceTypeAdjustmentBaseVideo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "adjustmentBaseVideo"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHAssetResourceTypeAdjustmentBaseVideo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHAssetResourceType.adjustmentBaseVideo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "adjustmentBaseVideo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType": {
      "abstract": [
        {
          "text": "Describes the relationship of an asset resource to its owning asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetResourceType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceType"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePairedVideo": {
      "abstract": [
        {
          "text": "Provides an unaltered version of the video data for a Live Photo asset for use in reconstructing recent edits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentBasePairedVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePairedVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAdjustmentBasePairedVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.adjustmentBasePairedVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/adjustmentbasepairedvideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePhoto": {
      "abstract": [
        {
          "text": "Provides an unaltered version of its photo asset for use in for use in reconstructing recent edits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentBasePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAdjustmentBasePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.adjustmentBasePhoto",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/adjustmentbasephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBaseVideo": {
      "abstract": [
        {
          "text": "Provides an unaltered version of its video asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentBaseVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBaseVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAdjustmentBaseVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.adjustmentBaseVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/adjustmentbasevideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentData": {
      "abstract": [
        {
          "text": "Provides data for use in reconstructing recent edits to its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustmentData"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAdjustmentData"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.adjustmentData",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/adjustmentdata"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/alternatePhoto": {
      "abstract": [
        {
          "text": "Provides photo data that isn’t the primary form of its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternatePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/alternatePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAlternatePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.alternatePhoto",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/alternatephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/audio": {
      "abstract": [
        {
          "text": "Provides the original audio data for its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.audio",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/audio"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePairedVideo": {
      "abstract": [
        {
          "text": "Provides the current video data component of a Live Photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullSizePairedVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePairedVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeFullSizePairedVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.fullSizePairedVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/fullsizepairedvideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePhoto": {
      "abstract": [
        {
          "text": "Provides a modified version of the original photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullSizePhoto"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeFullSizePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.fullSizePhoto",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/fullsizephoto"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizeVideo": {
      "abstract": [
        {
          "text": "Provides a modified version of the original video asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullSizeVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeFullSizeVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.fullSizeVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/fullsizevideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/pairedVideo": {
      "abstract": [
        {
          "text": "Provides the original video data component of a Live Photo asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pairedVideo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/pairedVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypePairedVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.pairedVideo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/pairedvideo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photo": {
      "abstract": [
        {
          "text": "Provides the original photo data for its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypePhoto"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.photo",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/photo"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/video": {
      "abstract": [
        {
          "text": "Provides the original video data for its asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "video"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetResourceTypeVideo"
        }
      ],
      "role": "symbol",
      "title": "PHAssetResourceType.video",
      "type": "topic",
      "url": "/documentation/photos/phassetresourcetype/video"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resource-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/video",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/audio",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/alternatePhoto",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePhoto",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizeVideo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentData",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePhoto",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/pairedVideo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePairedVideo",
        "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePairedVideo"
      ],
      "title": "Resource Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHAssetResourceTypeAdjustmentBaseVideo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentBaseVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resource-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/photo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/video",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/audio",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/alternatePhoto",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePhoto",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizeVideo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentData",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePhoto",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/pairedVideo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/fullSizePairedVideo",
                "doc://com.apple.photokit/documentation/Photos/PHAssetResourceType/adjustmentBasePairedVideo"
              ],
              "title": "Resource Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHAssetResourceTypeAdjustmentBaseVideo"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizeVideo/title",
          "value": "PHAssetResourceTypeFullSizeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeFullSizeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1alternatePhoto/title",
          "value": "PHAssetResourceTypeAlternatePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1alternatePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAlternatePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBasePairedVideo/title",
          "value": "PHAssetResourceTypeAdjustmentBasePairedVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBasePairedVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentBasePairedVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1photo/title",
          "value": "PHAssetResourceTypePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1photo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1pairedVideo/title",
          "value": "PHAssetResourceTypePairedVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1pairedVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypePairedVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBaseVideo/title",
          "value": "PHAssetResourceTypeAdjustmentBaseVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBaseVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentBaseVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1video/title",
          "value": "PHAssetResourceTypeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType/title",
          "value": "PHAssetResourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBasePhoto/title",
          "value": "PHAssetResourceTypeAdjustmentBasePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentBasePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentBasePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizePhoto/title",
          "value": "PHAssetResourceTypeFullSizePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeFullSizePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentData/title",
          "value": "PHAssetResourceTypeAdjustmentData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1adjustmentData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAdjustmentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizePairedVideo/title",
          "value": "PHAssetResourceTypeFullSizePairedVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1fullSizePairedVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeFullSizePairedVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1audio/title",
          "value": "PHAssetResourceTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResourceType~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetResourceTypeAudio"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phassetresourcetype/adjustmentbasevideo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phassetresourcetype/adjustmentbasevideo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
