{
  "abstract": [
    {
      "text": "Audio quality suitable for higher fidelity speech recording. This preset records audio with a 16 kHz sampling rate using either the LPCM 256 kbps or AAC 32 kbps format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/wideBandSpeech"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKAudioRecorderPreset@WKAudioRecorderPresetWideBandSpeech",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "wideBandSpeech"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKAudioRecorderPresetWideBandSpeech"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKAudioRecorderPreset.wideBandSpeech"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "wideBandSpeech"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset": {
      "abstract": [
        {
          "text": "Constants indicating the quality of audio recordings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudioRecorderPreset"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioRecorderPreset"
        }
      ],
      "role": "symbol",
      "title": "WKAudioRecorderPreset",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiorecorderpreset"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/highQualityAudio": {
      "abstract": [
        {
          "text": "A high-quality audio recording. This preset records audio with a 44.1 kHz sampling rate using either the LPCM 705.6 kbps or AAC 96 kbps format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highQualityAudio"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/highQualityAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioRecorderPresetHighQualityAudio"
        }
      ],
      "role": "symbol",
      "title": "WKAudioRecorderPreset.highQualityAudio",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiorecorderpreset/highqualityaudio"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/narrowBandSpeech": {
      "abstract": [
        {
          "text": "Audio quality suitable for basic speech recording. This preset records audio with an 8 kHz sampling rate using either the LPCM 128 kbps or AAC 24 kbps format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "narrowBandSpeech"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/narrowBandSpeech",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioRecorderPresetNarrowBandSpeech"
        }
      ],
      "role": "symbol",
      "title": "WKAudioRecorderPreset.narrowBandSpeech",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiorecorderpreset/narrowbandspeech"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/wideBandSpeech": {
      "abstract": [
        {
          "text": "Audio quality suitable for higher fidelity speech recording. This preset records audio with a 16 kHz sampling rate using either the LPCM 256 kbps or AAC 32 kbps format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wideBandSpeech"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/wideBandSpeech",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioRecorderPresetWideBandSpeech"
        }
      ],
      "role": "symbol",
      "title": "WKAudioRecorderPreset.wideBandSpeech",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiorecorderpreset/widebandspeech"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/narrowBandSpeech",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/highQualityAudio"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKAudioRecorderPresetWideBandSpeech"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioRecorderPresetWideBandSpeech"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/narrowBandSpeech",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioRecorderPreset/highQualityAudio"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKAudioRecorderPresetWideBandSpeech"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset~1highQualityAudio/title",
          "value": "WKAudioRecorderPresetHighQualityAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset~1highQualityAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioRecorderPresetHighQualityAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset/title",
          "value": "WKAudioRecorderPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioRecorderPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioRecorderPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset~1wideBandSpeech/title",
          "value": "WKAudioRecorderPresetWideBandSpeech"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset~1wideBandSpeech/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioRecorderPresetWideBandSpeech"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset~1narrowBandSpeech/title",
          "value": "WKAudioRecorderPresetNarrowBandSpeech"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioRecorderPreset~1narrowBandSpeech/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioRecorderPresetNarrowBandSpeech"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkaudiorecorderpreset/widebandspeech"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkaudiorecorderpreset/widebandspeech"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
