{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO",
        "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback/init(mGetSMPTETimeProc:mRefCon:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So27CMIODeviceSMPTETimeCallbackV04mGetB4Proc7mRefConABs5Int32VSvSg_Spys6UInt64VGSgSpy6Darwin0J7BooleanVGSgSpys6UInt32VGSgtXCSg_AGtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "mGetSMPTETimeProc"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMIODeviceGetSMPTETimeProc",
        "text": "CMIODeviceGetSMPTETimeProc"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "mRefCon"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "Core Media I/O"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(mGetSMPTETimeProc:mRefCon:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "mGetSMPTETimeProc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceGetSMPTETimeProc",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMIODeviceGetSMPTETimeProc",
              "text": "CMIODeviceGetSMPTETimeProc"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "mRefCon"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremediaio/documentation/CoreMediaIO": {
      "abstract": [
        {
          "text": "Securely support custom camera devices in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media I/O",
      "type": "topic",
      "url": "/documentation/coremediaio"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceGetSMPTETimeProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceGetSMPTETimeProc"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceGetSMPTETimeProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceGetSMPTETimeProc"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceGetSMPTETimeProc",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicegetsmptetimeproc"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMIODeviceSMPTETimeCallback"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMIODeviceSMPTETimeCallback"
        }
      ],
      "role": "symbol",
      "title": "CMIODeviceSMPTETimeCallback",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicesmptetimecallback"
    },
    "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback/init(mGetSMPTETimeProc:mRefCon:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mGetSMPTETimeProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMIODeviceGetSMPTETimeProc",
          "text": "CMIODeviceGetSMPTETimeProc"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "mRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.coremediaio/documentation/CoreMediaIO/CMIODeviceSMPTETimeCallback/init(mGetSMPTETimeProc:mRefCon:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mGetSMPTETimeProc:mRefCon:)",
      "type": "topic",
      "url": "/documentation/coremediaio/cmiodevicesmptetimecallback/init(mgetsmptetimeproc:mrefcon:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/title",
          "value": "CMIODeviceSMPTETimeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceSMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceSMPTETimeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceSMPTETimeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceGetSMPTETimeProc/title",
          "value": "CMIODeviceGetSMPTETimeProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceGetSMPTETimeProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceGetSMPTETimeProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremediaio~1documentation~1CoreMediaIO~1CMIODeviceGetSMPTETimeProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMIODeviceGetSMPTETimeProc"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremediaio/cmiodevicesmptetimecallback/init(mgetsmptetimeproc:mrefcon:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
