{"sections":[],"metadata":{"navigatorTitle":[{"text":"AVCaptureVideoStabilizationModeCinematicExtendedEnhanced","kind":"identifier"}],"modules":[{"name":"AVFoundation"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cinematicExtendedEnhanced","kind":"identifier"}],"externalID":"c:@E@AVCaptureVideoStabilizationMode@AVCaptureVideoStabilizationModeCinematicExtendedEnhanced","title":"AVCaptureVideoStabilizationMode.cinematicExtendedEnhanced","roleHeading":"Case","platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"18.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"18.0"},{"deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false,"name":"tvOS"}],"symbolKind":"case","role":"symbol"},"kind":"symbol","variants":[{"paths":["/documentation/avfoundation/avcapturevideostabilizationmode/cinematicextendedenhanced"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avcapturevideostabilizationmode/cinematicextendedenhanced"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"anchor":"Stabilization-Modes","title":"Stabilization Modes","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/off","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/standard","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematic","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtended","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/previewOptimized","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/auto"],"generated":true}],"abstract":[{"type":"text","text":"A mode that stabilizes video using the enhanced extended cinematic stabilization algorithm."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cinematicExtendedEnhanced"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Enhanced extended cinematic has a reduced field of view compared to extended cinematic, without any noticeable increase in latency, and it yields improved stability."}],"type":"paragraph"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"It’s recommended to use identical or similar minimum and maximum frame durations in conjunction with this mode."}],"type":"paragraph"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtended":{"title":"AVCaptureVideoStabilizationMode.cinematicExtended","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtended","type":"topic","url":"/documentation/avfoundation/avcapturevideostabilizationmode/cinematicextended","navigatorTitle":[{"text":"AVCaptureVideoStabilizationModeCinematicExtended","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cinematicExtended","kind":"identifier"}],"abstract":[{"type":"text","text":"A mode that uses the extended cinematic stabilization algorithm."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/auto":{"role":"symbol","abstract":[{"type":"text","text":"A mode that indicates the system chooses the most appropriate video stabilization mode for the device and format."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"auto"}],"navigatorTitle":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeAuto"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/auto","url":"/documentation/avfoundation/avcapturevideostabilizationmode/auto","type":"topic","title":"AVCaptureVideoStabilizationMode.auto","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/standard":{"title":"AVCaptureVideoStabilizationMode.standard","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/standard","type":"topic","url":"/documentation/avfoundation/avcapturevideostabilizationmode/standard","navigatorTitle":[{"text":"AVCaptureVideoStabilizationModeStandard","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"standard","kind":"identifier"}],"abstract":[{"text":"A mode that uses the standard algorithm.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced":{"role":"symbol","abstract":[{"text":"A mode that stabilizes video using the enhanced extended cinematic stabilization algorithm.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cinematicExtendedEnhanced"}],"navigatorTitle":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced","url":"/documentation/avfoundation/avcapturevideostabilizationmode/cinematicextendedenhanced","type":"topic","title":"AVCaptureVideoStabilizationMode.cinematicExtendedEnhanced","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode":{"url":"/documentation/avfoundation/avcapturevideostabilizationmode","navigatorTitle":[{"text":"AVCaptureVideoStabilizationMode","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode","title":"AVCaptureVideoStabilizationMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AVCaptureVideoStabilizationMode","kind":"identifier"}],"type":"topic","abstract":[{"text":"An enumeration of video stabilization modes that capture devices and formats support.","type":"text"}],"role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematic":{"title":"AVCaptureVideoStabilizationMode.cinematic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cinematic"}],"abstract":[{"text":"A mode that uses the cinematic stabilization algorithm.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematic","type":"topic","role":"symbol","url":"/documentation/avfoundation/avcapturevideostabilizationmode/cinematic","navigatorTitle":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeCinematic"}]},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/off":{"navigatorTitle":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeOff"}],"type":"topic","title":"AVCaptureVideoStabilizationMode.off","abstract":[{"text":"A mode that doesn’t stabilize video capture.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/off","url":"/documentation/avfoundation/avcapturevideostabilizationmode/off","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"off"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/previewOptimized":{"role":"symbol","abstract":[{"text":"A mode that uses the preview optimized stabilization algorithm.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previewOptimized"}],"navigatorTitle":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModePreviewOptimized"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/previewOptimized","url":"/documentation/avfoundation/avcapturevideostabilizationmode/previewoptimized","type":"topic","title":"AVCaptureVideoStabilizationMode.previewOptimized","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"unavailable":false,"introducedAt":"18.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"18.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"18.0","name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"18.0","name":"tvOS","deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"/metadata/title","value":"AVCaptureVideoStabilizationModeCinematicExtendedEnhanced","op":"replace"},{"path":"/metadata/symbolKind","value":"case","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"}],"op":"replace"},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Stabilization-Modes","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/off","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/standard","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematic","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtended","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/previewOptimized","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/auto"],"title":"Stabilization Modes"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"}]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtended/title","value":"AVCaptureVideoStabilizationModeCinematicExtended"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtended/fragments","value":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeCinematicExtended"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1auto/title","value":"AVCaptureVideoStabilizationModeAuto"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1auto/fragments","value":[{"text":"AVCaptureVideoStabilizationModeAuto","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1standard/title","value":"AVCaptureVideoStabilizationModeStandard"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1standard/fragments","value":[{"text":"AVCaptureVideoStabilizationModeStandard","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtendedEnhanced/title","value":"AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtendedEnhanced/fragments","value":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode/title","value":"AVCaptureVideoStabilizationMode"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode/fragments","value":[{"kind":"identifier","text":"AVCaptureVideoStabilizationMode"}]},{"value":[{"kind":"identifier","text":"AVCaptureVideoStabilizationMode"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode/navigatorTitle"},{"value":"AVCaptureVideoStabilizationModeCinematic","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematic/title"},{"value":[{"text":"AVCaptureVideoStabilizationModeCinematic","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematic/fragments"},{"value":"AVCaptureVideoStabilizationModeOff","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1off/title"},{"value":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModeOff"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1off/fragments"},{"value":"AVCaptureVideoStabilizationModePreviewOptimized","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1previewOptimized/title"},{"value":[{"kind":"identifier","text":"AVCaptureVideoStabilizationModePreviewOptimized"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1previewOptimized/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}