{
  "abstract": [
    {
      "text": "A mode that uses the standard algorithm.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/standard"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVCaptureVideoStabilizationMode@AVCaptureVideoStabilizationModeStandard",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "standard"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptureVideoStabilizationModeStandard"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVCaptureVideoStabilizationMode.standard"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "standard"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Standard video stabilization has a reduced field of view. Enabling video stabilization may introduce additional latency into the video capture pipeline.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode": {
      "abstract": [
        {
          "text": "An enumeration of video stabilization modes that capture devices and formats support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationMode"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturevideostabilizationmode"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/auto": {
      "abstract": [
        {
          "text": "A mode that indicates the system chooses the most appropriate video stabilization mode for the device and format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationModeAuto"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode.auto",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturevideostabilizationmode/auto"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematic": {
      "abstract": [
        {
          "text": "A mode that uses the cinematic stabilization algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cinematic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationModeCinematic"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode.cinematic",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturevideostabilizationmode/cinematic"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtended": {
      "abstract": [
        {
          "text": "A mode that uses the extended cinematic stabilization algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cinematicExtended"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationModeCinematicExtended"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode.cinematicExtended",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturevideostabilizationmode/cinematicextended"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced": {
      "abstract": [
        {
          "text": "A mode that stabilizes video using the enhanced extended cinematic stabilization algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cinematicExtendedEnhanced"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode.cinematicExtendedEnhanced",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturevideostabilizationmode/cinematicextendedenhanced"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/off": {
      "abstract": [
        {
          "text": "A mode that doesn’t stabilize video capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "off"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/off",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationModeOff"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode.off",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturevideostabilizationmode/off"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/previewOptimized": {
      "abstract": [
        {
          "text": "A mode that uses the preview optimized stabilization algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewOptimized"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/previewOptimized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationModePreviewOptimized"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode.previewOptimized",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturevideostabilizationmode/previewoptimized"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/standard": {
      "abstract": [
        {
          "text": "A mode that uses the standard algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureVideoStabilizationModeStandard"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode.standard",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturevideostabilizationmode/standard"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stabilization-Modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/off",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematic",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtended",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/previewOptimized",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/auto"
      ],
      "title": "Stabilization Modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptureVideoStabilizationModeStandard"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModeStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stabilization-Modes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/off",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematic",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtended",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/previewOptimized",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/auto"
              ],
              "title": "Stabilization Modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVCaptureVideoStabilizationModeStandard"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtendedEnhanced/title",
          "value": "AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtendedEnhanced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1off/title",
          "value": "AVCaptureVideoStabilizationModeOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1off/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModeOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematic/title",
          "value": "AVCaptureVideoStabilizationModeCinematic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModeCinematic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1previewOptimized/title",
          "value": "AVCaptureVideoStabilizationModePreviewOptimized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1previewOptimized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModePreviewOptimized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode/title",
          "value": "AVCaptureVideoStabilizationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1auto/title",
          "value": "AVCaptureVideoStabilizationModeAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModeAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtended/title",
          "value": "AVCaptureVideoStabilizationModeCinematicExtended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModeCinematicExtended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1standard/title",
          "value": "AVCaptureVideoStabilizationModeStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModeStandard"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturevideostabilizationmode/standard"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturevideostabilizationmode/standard"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
