{
  "abstract": [
    {
      "text": "A string that identifies the key used to generate the signature.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount/keyIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKPaymentDiscount(py)keyIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "keyIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "keyIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.2",
        "message": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.2",
        "message": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.14.4",
        "message": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.2",
        "message": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "6.2",
        "message": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "keyIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "keyIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You generate and download keys from App Store Connect. See the “KEY ID” column in App Store Connect to use as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount/keyIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount": {
      "abstract": [
        {
          "text": "The signed discount to apply to a payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPaymentDiscount"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentDiscount"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentDiscount",
      "type": "topic",
      "url": "/documentation/storekit/skpaymentdiscount"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount/identifier": {
      "abstract": [
        {
          "text": "A string used to uniquely identify a discount offer for a product.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/storekit/skpaymentdiscount/identifier"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount/keyIdentifier": {
      "abstract": [
        {
          "text": "A string that identifies the key used to generate the signature.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount/keyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "keyIdentifier",
      "type": "topic",
      "url": "/documentation/storekit/skpaymentdiscount/keyidentifier"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-the-Discount",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount/identifier"
      ],
      "title": "Identifying the Discount"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "keyIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit",
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-the-Discount",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentDiscount/identifier"
              ],
              "title": "Identifying the Discount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "keyIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Create a Product.PurchaseOption.promotionalOffer to use in Product.purchase(confirmIn:options:)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount~1keyIdentifier/title",
          "value": "keyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount~1keyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount/title",
          "value": "SKPaymentDiscount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentDiscount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentDiscount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skpaymentdiscount/keyidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skpaymentdiscount/keyidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
