{"abstract":[{"text":"Creates a new picker view controller with the configuration you specify.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/photosui/phpickerviewcontroller/initwithconfiguration:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHPickerConfiguration","text":"PHPickerConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}],"languages":["occ"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The configuration with which to initialize the view controller.","type":"text"}],"type":"paragraph"}],"name":"configuration"}]}],"kind":"symbol","metadata":{"modules":[{"name":"PhotosUI"}],"role":"symbol","title":"initWithConfiguration:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"introducedAt":"13.0","beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)PHPickerViewController(im)initWithConfiguration:","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}]},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/PhotosUI","doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController"]]},"identifier":{"url":"doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/initWithConfiguration:","interfaceLanguage":"occ"},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class"],"title":"Creating a picker","anchor":"Creating-a-picker"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class":{"fragments":[{"kind":"identifier","text":"PHPickerConfiguration"}],"url":"/documentation/photosui/phpickerconfiguration-c.class","role":"symbol","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class","kind":"symbol","title":"PHPickerConfiguration","abstract":[{"text":"An object that contains information about how to configure a picker view controller.","type":"text"}],"type":"topic"},"doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHPickerViewController"}],"url":"/documentation/photosui/phpickerviewcontroller","role":"symbol","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController","navigatorTitle":[{"text":"PHPickerViewController","kind":"identifier"}],"kind":"symbol","title":"PHPickerViewController","abstract":[{"text":"A view controller that provides the user interface for choosing assets from the photo library.","type":"text"}],"type":"topic"},"doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/initWithConfiguration:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}],"role":"symbol","abstract":[{"text":"Creates a new picker view controller with the configuration you specify.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}],"kind":"symbol","type":"topic","title":"initWithConfiguration:","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/initWithConfiguration:","url":"/documentation/photosui/phpickerviewcontroller/initwithconfiguration:"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.photokit/documentation/PhotosUI":{"type":"topic","identifier":"doc://com.apple.photokit/documentation/PhotosUI","title":"PhotosUI","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality."}],"url":"/documentation/photosui"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/title","value":"PHPickerViewController","op":"replace"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/fragments","value":[{"kind":"identifier","text":"PHPickerViewController"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/navigatorTitle","value":[{"kind":"identifier","text":"PHPickerViewController"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}