{"abstract":[{"text":"Copies the selected content to the pasteboard.","type":"text"}],"metadata":{"platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"3.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"3.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UIResponderStandardEditActions(im)copy:","title":"copy(_:)","navigatorTitle":[{"text":"copy:","kind":"identifier"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/cut(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/paste(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndGo(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndMatchStyle(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndSearch(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/delete(_:)"],"anchor":"Handling-copy-cut-paste-and-delete-commands","title":"Handling copy, cut, paste, and delete commands"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object calling this method."}]}]}],"kind":"parameters"},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/using-responders-and-the-responder-chain-to-handle-events"]},{"content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"UIKit calls this method when the user selects the Copy command from an editing menu. Your implementation should write the selected content to the pasteboard without removing the selection from your interface."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/copy(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiresponderstandardeditactions/copy(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiresponderstandardeditactions/copy(_:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/delete(_:)":{"type":"topic","role":"symbol","url":"/documentation/uikit/uiresponderstandardeditactions/delete(_:)","title":"delete(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/delete(_:)","navigatorTitle":[{"text":"delete:","kind":"identifier"}],"abstract":[{"text":"Removes the selected content from your interface.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions":{"navigatorTitle":[{"kind":"identifier","text":"UIResponderStandardEditActions"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIResponderStandardEditActions"}],"type":"topic","abstract":[{"type":"text","text":"A set of standard methods that apps can adopt to support editing."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions","title":"UIResponderStandardEditActions","url":"/documentation/uikit/uiresponderstandardeditactions","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/cut(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cut","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"cut(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/cut(_:)","url":"/documentation/uikit/uiresponderstandardeditactions/cut(_:)","role":"symbol","navigatorTitle":[{"text":"cut:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Removes the selected content and writes the data for it to the pasteboard."}]},"doc://com.apple.uikit/documentation/UIKit/using-responders-and-the-responder-chain-to-handle-events":{"abstract":[{"text":"Learn how to handle events that propagate through your app.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/using-responders-and-the-responder-chain-to-handle-events","role":"article","type":"topic","title":"Using responders and the responder chain to handle events","kind":"article","url":"/documentation/uikit/using-responders-and-the-responder-chain-to-handle-events"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/copy(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"copy(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/copy(_:)","url":"/documentation/uikit/uiresponderstandardeditactions/copy(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copy:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Copies the selected content to the pasteboard."}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/paste(_:)":{"type":"topic","role":"symbol","url":"/documentation/uikit/uiresponderstandardeditactions/paste(_:)","title":"paste(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/paste(_:)","navigatorTitle":[{"text":"paste:","kind":"identifier"}],"abstract":[{"text":"Pastes the current contents of the pasteboard into your app’s interface.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paste","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndGo(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pasteAndGo"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"pasteAndGo(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndGo(_:)","url":"/documentation/uikit/uiresponderstandardeditactions/pasteandgo(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pasteAndGo:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Pastes the current contents of the pasteboard into your app’s interface and navigates to the entity it references."}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndMatchStyle(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pasteAndMatchStyle"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"pasteAndMatchStyle(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndMatchStyle(_:)","url":"/documentation/uikit/uiresponderstandardeditactions/pasteandmatchstyle(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pasteAndMatchStyle:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Pastes the current contents of the pasteboard into your app’s interface using the text style of the target."}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndSearch(_:)":{"type":"topic","role":"symbol","url":"/documentation/uikit/uiresponderstandardeditactions/pasteandsearch(_:)","title":"pasteAndSearch(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndSearch(_:)","navigatorTitle":[{"text":"pasteAndSearch:","kind":"identifier"}],"abstract":[{"text":"Pastes the current contents of the pasteboard into your app’s interface and performs a search.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pasteAndSearch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"3.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"3.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"value":"copy:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"copy:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Handling-copy-cut-paste-and-delete-commands","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/cut(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/paste(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndGo(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndMatchStyle(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndSearch(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/delete(_:)"],"generated":true,"title":"Handling copy, cut, paste, and delete commands"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"copy:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The object calling this method.","type":"text"}],"type":"paragraph"}],"name":"sender"}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"value":"delete:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1delete(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"delete:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1delete(_:)/fragments"},{"value":"UIResponderStandardEditActions","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/title"},{"value":[{"text":"UIResponderStandardEditActions","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/fragments"},{"value":[{"text":"UIResponderStandardEditActions","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/navigatorTitle"},{"value":"cut:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1cut(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"cut:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1cut(_:)/fragments"},{"value":"copy:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1copy(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"copy:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1copy(_:)/fragments"},{"value":"paste:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1paste(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paste:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1paste(_:)/fragments"},{"value":"pasteAndGo:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndGo(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pasteAndGo:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndGo(_:)/fragments"},{"value":"pasteAndMatchStyle:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndMatchStyle(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"pasteAndMatchStyle:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndMatchStyle(_:)/fragments"},{"value":"pasteAndSearch:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndSearch(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pasteAndSearch:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndSearch(_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}