{"variants":[{"paths":["/documentation/uikit/uiresponderstandardeditactions/cut(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiresponderstandardeditactions/cut(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(pl)UIResponderStandardEditActions(im)cut:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cut"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"cut:","kind":"identifier"}],"role":"symbol","modules":[{"name":"UIKit"}],"title":"cut(_:)","symbolKind":"method","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"3.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"3.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1","unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cut","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The object calling this method.","type":"text"}]}],"name":"sender"}],"kind":"parameters"},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/using-responders-and-the-responder-chain-to-handle-events"]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"UIKit calls this method when the user selects the Cut command from an editing menu. Your implementation should write the selected content to the pasteboard and then remove it from your interface.","type":"text"}]}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/copy(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/paste(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndGo(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndMatchStyle(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndSearch(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/delete(_:)"],"anchor":"Handling-copy-cut-paste-and-delete-commands","title":"Handling copy, cut, paste, and delete commands"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/cut(_:)"},"abstract":[{"type":"text","text":"Removes the selected content and writes the data for it to the pasteboard."}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndGo(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pasteAndGo"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"pasteAndGo(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndGo(_:)","url":"/documentation/uikit/uiresponderstandardeditactions/pasteandgo(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pasteAndGo:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Pastes the current contents of the pasteboard into your app’s interface and navigates to the entity it references."}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndSearch(_:)":{"type":"topic","role":"symbol","url":"/documentation/uikit/uiresponderstandardeditactions/pasteandsearch(_:)","title":"pasteAndSearch(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndSearch(_:)","navigatorTitle":[{"text":"pasteAndSearch:","kind":"identifier"}],"abstract":[{"text":"Pastes the current contents of the pasteboard into your app’s interface and performs a search.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pasteAndSearch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndMatchStyle(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pasteAndMatchStyle"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"pasteAndMatchStyle(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndMatchStyle(_:)","url":"/documentation/uikit/uiresponderstandardeditactions/pasteandmatchstyle(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pasteAndMatchStyle:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Pastes the current contents of the pasteboard into your app’s interface using the text style of the target."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/delete(_:)":{"type":"topic","role":"symbol","url":"/documentation/uikit/uiresponderstandardeditactions/delete(_:)","title":"delete(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/delete(_:)","navigatorTitle":[{"text":"delete:","kind":"identifier"}],"abstract":[{"text":"Removes the selected content from your interface.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/cut(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cut","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"cut(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/cut(_:)","url":"/documentation/uikit/uiresponderstandardeditactions/cut(_:)","role":"symbol","navigatorTitle":[{"text":"cut:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Removes the selected content and writes the data for it to the pasteboard."}]},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/paste(_:)":{"type":"topic","role":"symbol","url":"/documentation/uikit/uiresponderstandardeditactions/paste(_:)","title":"paste(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/paste(_:)","navigatorTitle":[{"text":"paste:","kind":"identifier"}],"abstract":[{"text":"Pastes the current contents of the pasteboard into your app’s interface.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paste","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/using-responders-and-the-responder-chain-to-handle-events":{"abstract":[{"text":"Learn how to handle events that propagate through your app.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/using-responders-and-the-responder-chain-to-handle-events","role":"article","type":"topic","title":"Using responders and the responder chain to handle events","kind":"article","url":"/documentation/uikit/using-responders-and-the-responder-chain-to-handle-events"},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/copy(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"copy(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/copy(_:)","url":"/documentation/uikit/uiresponderstandardeditactions/copy(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copy:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Copies the selected content to the pasteboard."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions":{"navigatorTitle":[{"kind":"identifier","text":"UIResponderStandardEditActions"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIResponderStandardEditActions"}],"type":"topic","abstract":[{"type":"text","text":"A set of standard methods that apps can adopt to support editing."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions","title":"UIResponderStandardEditActions","url":"/documentation/uikit/uiresponderstandardeditactions","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"3.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"3.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1","unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"cut:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"cut:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/copy(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/paste(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndGo(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndMatchStyle(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/pasteAndSearch(_:)","doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions/delete(_:)"],"anchor":"Handling-copy-cut-paste-and-delete-commands","title":"Handling copy, cut, paste, and delete commands","generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"cut:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"name":"sender","content":[{"inlineContent":[{"text":"The object calling this method.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndGo(_:)/title","value":"pasteAndGo:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndGo(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"pasteAndGo:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndSearch(_:)/title","value":"pasteAndSearch:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndSearch(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pasteAndSearch:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndMatchStyle(_:)/title","value":"pasteAndMatchStyle:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1pasteAndMatchStyle(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"pasteAndMatchStyle:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1delete(_:)/title","value":"delete:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1delete(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"delete:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1cut(_:)/title","value":"cut:","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1cut(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cut:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1paste(_:)/title","value":"paste:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1paste(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"paste:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1copy(_:)/title","value":"copy:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions~1copy(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copy:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/title","value":"UIResponderStandardEditActions"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/fragments","value":[{"text":"UIResponderStandardEditActions","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/navigatorTitle","value":[{"text":"UIResponderStandardEditActions","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}