{
  "abstract": [
    {
      "text": "The attribute type of the expression’s result.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/resultType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreData",
    "externalID": "s:So23NSExpressionDescriptionC8CoreDataE10resultTypeSo011NSAttributeB0CACE09AttributeF0Vvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resultType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
        "text": "NSAttributeDescription"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
        "text": "AttributeType"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "resultType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resultType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
              "text": "NSAttributeDescription"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
              "text": "AttributeType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription": {
      "abstract": [
        {
          "text": "A description of a single attribute belonging to an entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAttributeDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAttributeDescription"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct": {
      "abstract": [
        {
          "text": "The types of attributes that Core Data supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription/AttributeType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeDescription.AttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription/attributetype-swift.struct"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription": {
      "abstract": [
        {
          "text": "An object that describes an expression to include with a fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExpressionDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExpressionDescription"
        }
      ],
      "role": "symbol",
      "title": "NSExpressionDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsexpressiondescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/expression": {
      "abstract": [
        {
          "text": "The expression to evaluate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSExpression",
          "text": "NSExpression"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/expression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expression"
        }
      ],
      "role": "symbol",
      "title": "expression",
      "type": "topic",
      "url": "/documentation/coredata/nsexpressiondescription/expression"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/expressionResultType": {
      "abstract": [
        {
          "text": "The attribute type of the expression’s result.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expressionResultType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAttributeType",
          "text": "NSAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/expressionResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expressionResultType"
        }
      ],
      "role": "symbol",
      "title": "expressionResultType",
      "type": "topic",
      "url": "/documentation/coredata/nsexpressiondescription/expressionresulttype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/resultType": {
      "abstract": [
        {
          "text": "The attribute type of the expression’s result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributeDescription",
          "text": "NSAttributeDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22NSAttributeDescriptionC8CoreDataE13AttributeTypeV",
          "text": "AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/resultType",
      "kind": "symbol",
      "role": "symbol",
      "title": "resultType",
      "type": "topic",
      "url": "/documentation/coredata/nsexpressiondescription/resulttype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Expression-Description",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/expression",
        "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription/expressionResultType"
      ],
      "title": "Configuring the Expression Description"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription~1expressionResultType/title",
          "value": "expressionResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription~1expressionResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expressionResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription/title",
          "value": "NSExpressionDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExpressionDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExpressionDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/title",
          "value": "NSAttributeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription~1expression/title",
          "value": "expression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription~1expression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expression"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsexpressiondescription/resulttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
