{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataServiceIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The identifier of the service that’s currently providing data."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coretelephony/documentation/CoreTelephony","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"]]},"seeAlsoSections":[{"anchor":"Getting-Information-About-the-Cellular-Service-Provider","identifiers":["doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology","doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants"],"generated":true,"title":"Getting Information About the Cellular Service Provider"}],"identifier":{"url":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)CTTelephonyNetworkInfo(py)dataServiceIdentifier","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataServiceIdentifier"}],"platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false}],"roleHeading":"Instance Property","symbolKind":"property","title":"dataServiceIdentifier","modules":[{"name":"Core Telephony"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataServiceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coretelephony/cttelephonynetworkinfo/dataserviceidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coretelephony/cttelephonynetworkinfo/dataserviceidentifier"]}],"sections":[],"kind":"symbol","references":{"doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants":{"url":"/documentation/coretelephony/radio-access-technology-constants","role":"collectionGroup","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants","abstract":[{"text":"Constants that describe the current radio access technology.","type":"text"}],"kind":"article","title":"Radio Access Technology Constants","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","url":"/documentation/foundation/nsstring","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"title":"NSString","role":"symbol","type":"topic"},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier":{"url":"/documentation/coretelephony/cttelephonynetworkinfo/dataserviceidentifier","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataServiceIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier","abstract":[{"text":"The identifier of the service that’s currently providing data.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"dataServiceIdentifier","kind":"identifier"}],"title":"dataServiceIdentifier","type":"topic"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","title":"String","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony":{"kind":"symbol","url":"/documentation/coretelephony","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony","abstract":[{"type":"text","text":"Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP."}],"title":"Core Telephony","type":"topic","role":"collection"},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceCurrentRadioAccessTechnology","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology","url":"/documentation/coretelephony/cttelephonynetworkinfo/servicecurrentradioaccesstechnology","abstract":[{"text":"A dictionary containing the current radio access technology registered to each service.","type":"text"}],"title":"serviceCurrentRadioAccessTechnology","navigatorTitle":[{"kind":"identifier","text":"serviceCurrentRadioAccessTechnology"}],"role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","type":"topic","role":"overview"},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo":{"kind":"symbol","url":"/documentation/coretelephony/cttelephonynetworkinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CTTelephonyNetworkInfo","kind":"identifier"}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo","title":"CTTelephonyNetworkInfo","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object that provides notifications of changes to the user’s cellular service provider."}],"navigatorTitle":[{"text":"CTTelephonyNetworkInfo","kind":"identifier"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate":{"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"CTTelephonyNetworkInfoDelegate","preciseIdentifier":"c:objc(pl)CTTelephonyNetworkInfoDelegate"},{"kind":"text","text":")?"}],"url":"/documentation/coretelephony/cttelephonynetworkinfo/delegate","abstract":[{"type":"text","text":"An object that the system notifies when the data service identifier changes."}],"kind":"symbol","title":"delegate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CTTelephonyNetworkInfoDelegate"}],"kind":"symbol","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate","url":"/documentation/coretelephony/cttelephonynetworkinfodelegate","abstract":[{"type":"text","text":"The methods that the system invokes when data service changes occur."}],"title":"CTTelephonyNetworkInfoDelegate","navigatorTitle":[{"kind":"identifier","text":"CTTelephonyNetworkInfoDelegate"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"13.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"13.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"dataServiceIdentifier"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"dataServiceIdentifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coretelephony/documentation/CoreTelephony","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Getting Information About the Cellular Service Provider","anchor":"Getting-Information-About-the-Cellular-Service-Provider","identifiers":["doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology","doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"dataServiceIdentifier","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"type":"text","text":"A static, plain-text Unicode string object."}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1dataServiceIdentifier/title","value":"dataServiceIdentifier"},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1dataServiceIdentifier/fragments","value":[{"text":"dataServiceIdentifier","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/title","value":"serviceCurrentRadioAccessTechnology"},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/fragments","value":[{"kind":"identifier","text":"serviceCurrentRadioAccessTechnology"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/title","value":"CTTelephonyNetworkInfo"},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/fragments","value":[{"kind":"identifier","text":"CTTelephonyNetworkInfo"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/navigatorTitle","value":[{"text":"CTTelephonyNetworkInfo","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1delegate/title","value":"delegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1delegate/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"value":"CTTelephonyNetworkInfoDelegate","op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/title"},{"value":[{"kind":"identifier","text":"CTTelephonyNetworkInfoDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/fragments"},{"value":[{"text":"CTTelephonyNetworkInfoDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}