{"seeAlsoSections":[{"identifiers":["doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology","doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants"],"generated":true,"title":"Getting Information About the Cellular Service Provider","anchor":"Getting-Information-About-the-Cellular-Service-Provider"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate","preciseIdentifier":"c:objc(pl)CTTelephonyNetworkInfoDelegate","text":"CTTelephonyNetworkInfoDelegate"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coretelephony/cttelephonynetworkinfo/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coretelephony/cttelephonynetworkinfo/delegate"]}],"kind":"symbol","abstract":[{"type":"text","text":"An object that the system notifies when the data service identifier changes."}],"identifier":{"url":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coretelephony/documentation/CoreTelephony","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"]]},"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"Core Telephony"}],"role":"symbol","platforms":[{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"externalID":"c:objc(cs)CTTelephonyNetworkInfo(py)delegate","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)CTTelephonyNetworkInfoDelegate","kind":"typeIdentifier","text":"CTTelephonyNetworkInfoDelegate"},{"text":")?","kind":"text"}]},"references":{"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier":{"url":"/documentation/coretelephony/cttelephonynetworkinfo/dataserviceidentifier","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataServiceIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier","abstract":[{"text":"The identifier of the service that’s currently providing data.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"dataServiceIdentifier","kind":"identifier"}],"title":"dataServiceIdentifier","type":"topic"},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CTTelephonyNetworkInfoDelegate"}],"kind":"symbol","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate","url":"/documentation/coretelephony/cttelephonynetworkinfodelegate","abstract":[{"type":"text","text":"The methods that the system invokes when data service changes occur."}],"title":"CTTelephonyNetworkInfoDelegate","navigatorTitle":[{"kind":"identifier","text":"CTTelephonyNetworkInfoDelegate"}],"role":"symbol","type":"topic"},"doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants":{"url":"/documentation/coretelephony/radio-access-technology-constants","role":"collectionGroup","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants","abstract":[{"text":"Constants that describe the current radio access technology.","type":"text"}],"kind":"article","title":"Radio Access Technology Constants","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","type":"topic","role":"overview"},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo":{"kind":"symbol","url":"/documentation/coretelephony/cttelephonynetworkinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CTTelephonyNetworkInfo","kind":"identifier"}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo","title":"CTTelephonyNetworkInfo","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object that provides notifications of changes to the user’s cellular service provider."}],"navigatorTitle":[{"text":"CTTelephonyNetworkInfo","kind":"identifier"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate":{"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"CTTelephonyNetworkInfoDelegate","preciseIdentifier":"c:objc(pl)CTTelephonyNetworkInfoDelegate"},{"kind":"text","text":")?"}],"url":"/documentation/coretelephony/cttelephonynetworkinfo/delegate","abstract":[{"type":"text","text":"An object that the system notifies when the data service identifier changes."}],"kind":"symbol","title":"delegate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceCurrentRadioAccessTechnology","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology","url":"/documentation/coretelephony/cttelephonynetworkinfo/servicecurrentradioaccesstechnology","abstract":[{"text":"A dictionary containing the current radio access technology registered to each service.","type":"text"}],"title":"serviceCurrentRadioAccessTechnology","navigatorTitle":[{"kind":"identifier","text":"serviceCurrentRadioAccessTechnology"}],"role":"symbol","type":"topic"},"doc://com.apple.coretelephony/documentation/CoreTelephony":{"kind":"symbol","url":"/documentation/coretelephony","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony","abstract":[{"type":"text","text":"Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP."}],"title":"Core Telephony","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"13.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"13.0","name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","value":"delegate","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coretelephony/documentation/CoreTelephony","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Getting-Information-About-the-Cellular-Service-Provider","identifiers":["doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology","doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants"],"title":"Getting Information About the Cellular Service Provider","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)CTTelephonyNetworkInfoDelegate","text":"id<CTTelephonyNetworkInfoDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1dataServiceIdentifier/title","op":"replace","value":"dataServiceIdentifier"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1dataServiceIdentifier/fragments","op":"replace","value":[{"text":"dataServiceIdentifier","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/title","op":"replace","value":"CTTelephonyNetworkInfoDelegate"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/fragments","op":"replace","value":[{"text":"CTTelephonyNetworkInfoDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CTTelephonyNetworkInfoDelegate"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/title","op":"replace","value":"CTTelephonyNetworkInfo"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/fragments","op":"replace","value":[{"kind":"identifier","text":"CTTelephonyNetworkInfo"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CTTelephonyNetworkInfo"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1delegate/title","op":"replace","value":"delegate"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1delegate/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/title","op":"replace","value":"serviceCurrentRadioAccessTechnology"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/fragments","op":"replace","value":[{"text":"serviceCurrentRadioAccessTechnology","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}