{"identifier":{"url":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coretelephony/documentation/CoreTelephony","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"]]},"abstract":[{"type":"text","text":"A dictionary that contains carrier information about each service."}],"metadata":{"role":"symbol","externalID":"c:objc(cs)CTTelephonyNetworkInfo(py)serviceSubscriberCellularProviders","symbolKind":"property","modules":[{"name":"Core Telephony"}],"navigatorTitle":[{"kind":"identifier","text":"serviceSubscriberCellularProviders"}],"roleHeading":"Instance Property","title":"serviceSubscriberCellularProviders","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceSubscriberCellularProviders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CTCarrier","text":"CTCarrier"},{"kind":"text","text":"]?"}],"platforms":[{"deprecatedAt":"16.0","name":"iOS","introducedAt":"12.0","deprecated":false,"unavailable":false,"message":"Deprecated with no replacement","beta":false},{"deprecatedAt":"16.0","name":"iPadOS","introducedAt":"12.0","deprecated":false,"unavailable":false,"message":"Deprecated with no replacement","beta":false},{"deprecatedAt":"16.0","name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false,"message":"Deprecated with no replacement","beta":false}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceSubscriberCellularProviders","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":" : ","kind":"text"},{"text":"CTCarrier","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CTCarrier","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"The keys for the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders"},{"text":" dictionary are ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsstring"},{"text":" objects, each of which represents a service. Each entry in the dictionary is a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier"},{"text":" object, which contains information about the subscriber’s home cellular service provider.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"In this context, the “home” provider is the one with which the user has a cellular plan, as opposed to a roaming provider.","type":"text"}],"type":"paragraph"}],"name":"Note","style":"note","type":"aside"},{"inlineContent":[{"text":"Although the actual value of a key isn’t important, you can also use it to get the current radio access technology associated with the service. To do so, pass the key to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology"},{"text":" dictionary.","type":"text"}],"type":"paragraph"}]}],"seeAlsoSections":[{"title":"Deprecated","identifiers":["doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier","doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange"],"anchor":"Deprecated","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularproviders"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularproviders"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Deprecated with no replacement","type":"text"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","type":"topic","role":"overview"},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier":{"title":"CTCarrier","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CTCarrier"}],"url":"/documentation/coretelephony/ctcarrier","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CTCarrier"}],"deprecated":true,"abstract":[{"type":"text","text":"Information about the user’s cellular service provider, such as its unique identifier and whether it allows VoIP calls on its network."}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier","kind":"symbol"},"doc://com.apple.coretelephony/documentation/CoreTelephony":{"kind":"symbol","url":"/documentation/coretelephony","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony","abstract":[{"type":"text","text":"Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP."}],"title":"Core Telephony","type":"topic","role":"collection"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","title":"String","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider":{"type":"topic","url":"/documentation/coretelephony/cttelephonynetworkinfo/subscribercellularprovider","abstract":[{"type":"text","text":"Information about the user’s cellular service provider."}],"title":"subscriberCellularProvider","kind":"symbol","role":"symbol","deprecated":true,"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscriberCellularProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CTCarrier","kind":"typeIdentifier","text":"CTCarrier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"subscriberCellularProvider"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceCurrentRadioAccessTechnology","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology","url":"/documentation/coretelephony/cttelephonynetworkinfo/servicecurrentradioaccesstechnology","abstract":[{"text":"A dictionary containing the current radio access technology registered to each service.","type":"text"}],"title":"serviceCurrentRadioAccessTechnology","navigatorTitle":[{"kind":"identifier","text":"serviceCurrentRadioAccessTechnology"}],"role":"symbol","type":"topic"},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentRadioAccessTechnology"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology","title":"currentRadioAccessTechnology","abstract":[{"text":"The current radio access technology registered with the device.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"currentRadioAccessTechnology"}],"kind":"symbol","type":"topic","url":"/documentation/coretelephony/cttelephonynetworkinfo/currentradioaccesstechnology","deprecated":true},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceSubscriberCellularProviders","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CTCarrier","text":"CTCarrier","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders","title":"serviceSubscriberCellularProviders","abstract":[{"type":"text","text":"A dictionary that contains carrier information about each service."}],"navigatorTitle":[{"text":"serviceSubscriberCellularProviders","kind":"identifier"}],"kind":"symbol","type":"topic","url":"/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularproviders","deprecated":true},"doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange":{"title":"CTRadioAccessTechnologyDidChange","fragments":[{"kind":"text","text":"static let "},{"kind":"identifier","text":"CTRadioAccessTechnologyDidChange"},{"kind":"text","text":": NSNotification.Name"}],"url":"/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange","type":"topic","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"The name of the notification indicating that the radio access technology changed for one of the services."}],"identifier":"doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/nsstring":{"type":"topic","url":"/documentation/foundation/nsstring","role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"identifier":"doc://com.apple.documentation/documentation/foundation/nsstring","title":"NSString","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier":{"kind":"symbol","url":"/documentation/coretelephony/cttelephonynetworkinfo/subscribercellularproviderdidupdatenotifier","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscriberCellularProviderDidUpdateNotifier","kind":"identifier"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:objc(cs)CTCarrier","kind":"typeIdentifier","text":"CTCarrier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier","title":"subscriberCellularProviderDidUpdateNotifier","deprecated":true,"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A block dispatched when the user’s cellular service provider information changes."}],"navigatorTitle":[{"text":"subscriberCellularProviderDidUpdateNotifier","kind":"identifier"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification":{"type":"topic","url":"/documentation/coretelephony/ctserviceradioaccesstechnologydidchangenotification","abstract":[],"title":"CTServiceRadioAccessTechnologyDidChangeNotification","kind":"symbol","role":"symbol","identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification","fragments":[{"text":"CTServiceRadioAccessTechnologyDidChangeNotification","kind":"identifier"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo":{"kind":"symbol","url":"/documentation/coretelephony/cttelephonynetworkinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CTTelephonyNetworkInfo","kind":"identifier"}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo","title":"CTTelephonyNetworkInfo","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object that provides notifications of changes to the user’s cellular service provider."}],"navigatorTitle":[{"text":"CTTelephonyNetworkInfo","kind":"identifier"}]},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification":{"role":"symbol","fragments":[{"text":"CTRadioAccessTechnologyDidChangeNotification","kind":"identifier"}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification","title":"CTRadioAccessTechnologyDidChangeNotification","abstract":[{"text":"The name of the notification indicating that the radio access technology changed for one of the services.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/coretelephony/ctradioaccesstechnologydidchangenotification"},"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier":{"title":"serviceSubscriberCellularProvidersDidUpdateNotifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceSubscriberCellularProvidersDidUpdateNotifier"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"url":"/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularprovidersdidupdatenotifier","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"serviceSubscriberCellularProvidersDidUpdateNotifier"}],"deprecated":true,"abstract":[{"type":"text","text":"A block dispatched when there are updates to the user’s cellular provider information for any service."}],"identifier":"doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"12.0","deprecated":false,"name":"iOS","unavailable":false,"deprecatedAt":"16.0","beta":false},{"introducedAt":"12.0","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"16.0","name":"iPadOS"},{"introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"16.0","name":"Mac Catalyst"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"serviceSubscriberCellularProviders"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"serviceSubscriberCellularProviders","kind":"identifier"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coretelephony/documentation/CoreTelephony","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Deprecated","title":"Deprecated","identifiers":["doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier","doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier","doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification","doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange","doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"retain","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDictionary<NSString *,CTCarrier *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"serviceSubscriberCellularProviders","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":[{"inlineContent":[{"type":"text","text":"Deprecated with no replacement"}],"type":"paragraph"}],"path":"/deprecationSummary","op":"replace"},{"value":"CTCarrier","path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/title","op":"replace"},{"value":[{"text":"CTCarrier","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CTCarrier"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProvider/title","op":"replace","value":"subscriberCellularProvider"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProvider/fragments","op":"replace","value":[{"text":"subscriberCellularProvider","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/title","op":"replace","value":"serviceCurrentRadioAccessTechnology"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/fragments","op":"replace","value":[{"kind":"identifier","text":"serviceCurrentRadioAccessTechnology"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1currentRadioAccessTechnology/title","op":"replace","value":"currentRadioAccessTechnology"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1currentRadioAccessTechnology/fragments","op":"replace","value":[{"text":"currentRadioAccessTechnology","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProviders/title","op":"replace","value":"serviceSubscriberCellularProviders"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProviders/fragments","op":"replace","value":[{"kind":"identifier","text":"serviceSubscriberCellularProviders"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract","op":"replace","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProviderDidUpdateNotifier/title","op":"replace","value":"subscriberCellularProviderDidUpdateNotifier"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProviderDidUpdateNotifier/fragments","op":"replace","value":[{"kind":"identifier","text":"subscriberCellularProviderDidUpdateNotifier"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/title","op":"replace","value":"CTTelephonyNetworkInfo"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/fragments","op":"replace","value":[{"text":"CTTelephonyNetworkInfo","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CTTelephonyNetworkInfo"}]},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProvidersDidUpdateNotifier/title","op":"replace","value":"serviceSubscriberCellularProvidersDidUpdateNotifier"},{"path":"/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProvidersDidUpdateNotifier/fragments","op":"replace","value":[{"kind":"identifier","text":"serviceSubscriberCellularProvidersDidUpdateNotifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}