{
  "abstract": [
    {
      "text": "A dictionary containing the current radio access technology registered to each service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CTTelephonyNetworkInfo(py)serviceCurrentRadioAccessTechnology",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "serviceCurrentRadioAccessTechnology"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "serviceCurrentRadioAccessTechnology"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "serviceCurrentRadioAccessTechnology"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "serviceCurrentRadioAccessTechnology"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The keys for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " dictionary are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, each of which represents a service. The entry associated with a key is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the service is not registered on any network.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Although the actual value of a key isn’t important, you can also use it to get the carrier information associated with the service. To do so, pass the key to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo": {
      "abstract": [
        {
          "text": "An object that provides notifications of changes to the user’s cellular service provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfo"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfo"
        }
      ],
      "role": "symbol",
      "title": "CTTelephonyNetworkInfo",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the service that’s currently providing data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataServiceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataServiceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "dataServiceIdentifier",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/dataserviceidentifier"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate": {
      "abstract": [
        {
          "text": "An object that the system notifies when the data service identifier changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CTTelephonyNetworkInfoDelegate",
          "text": "CTTelephonyNetworkInfoDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/delegate"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology": {
      "abstract": [
        {
          "text": "A dictionary containing the current radio access technology registered to each service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceCurrentRadioAccessTechnology"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceCurrentRadioAccessTechnology"
        }
      ],
      "role": "symbol",
      "title": "serviceCurrentRadioAccessTechnology",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/servicecurrentradioaccesstechnology"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders": {
      "abstract": [
        {
          "text": "A dictionary that contains carrier information about each service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProviders"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCarrier",
          "text": "CTCarrier"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProviders"
        }
      ],
      "role": "symbol",
      "title": "serviceSubscriberCellularProviders",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularproviders"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate": {
      "abstract": [
        {
          "text": "The methods that the system invokes when data service changes occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfoDelegate"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfoDelegate"
        }
      ],
      "role": "symbol",
      "title": "CTTelephonyNetworkInfoDelegate",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfodelegate"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants": {
      "abstract": [
        {
          "text": "Constants that describe the current radio access technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Radio Access Technology Constants",
      "type": "topic",
      "url": "/documentation/coretelephony/radio-access-technology-constants"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Information-About-the-Cellular-Service-Provider",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants"
      ],
      "title": "Getting Information About the Cellular Service Provider"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "serviceCurrentRadioAccessTechnology"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceCurrentRadioAccessTechnology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretelephony/documentation/CoreTelephony",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Information-About-the-Cellular-Service-Provider",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants"
              ],
              "title": "Getting Information About the Cellular Service Provider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "serviceCurrentRadioAccessTechnology"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/title",
          "value": "CTTelephonyNetworkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProviders/title",
          "value": "serviceSubscriberCellularProviders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProviders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceSubscriberCellularProviders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1dataServiceIdentifier/title",
          "value": "dataServiceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1dataServiceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataServiceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/title",
          "value": "serviceCurrentRadioAccessTechnology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceCurrentRadioAccessTechnology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/title",
          "value": "CTTelephonyNetworkInfoDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfoDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfoDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/cttelephonynetworkinfo/servicecurrentradioaccesstechnology"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/cttelephonynetworkinfo/servicecurrentradioaccesstechnology"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
