{
  "abstract": [
    {
      "text": "A cover section.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/cover"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHProjectSectionType@PHProjectSectionTypeCover",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cover"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHProjectSectionTypeCover"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHProjectSection.SectionType.cover"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cover"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection": {
      "abstract": [
        {
          "text": "A collection of content representing curated asset and text elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectSection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectSection"
        }
      ],
      "role": "symbol",
      "title": "PHProjectSection",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsection"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum": {
      "abstract": [
        {
          "text": "The intended usage of the section: cover, content, or auxiliary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SectionType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SectionType"
        }
      ],
      "role": "symbol",
      "title": "PHProjectSection.SectionType",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsection/sectiontype-swift.enum"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/auxiliary": {
      "abstract": [
        {
          "text": "An auxiliary section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auxiliary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/auxiliary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectSectionTypeAuxiliary"
        }
      ],
      "role": "symbol",
      "title": "PHProjectSection.SectionType.auxiliary",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsection/sectiontype-swift.enum/auxiliary"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/content": {
      "abstract": [
        {
          "text": "A content section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "content"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/content",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectSectionTypeContent"
        }
      ],
      "role": "symbol",
      "title": "PHProjectSection.SectionType.content",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsection/sectiontype-swift.enum/content"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/cover": {
      "abstract": [
        {
          "text": "A cover section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cover"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/cover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectSectionTypeCover"
        }
      ],
      "role": "symbol",
      "title": "PHProjectSection.SectionType.cover",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsection/sectiontype-swift.enum/cover"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/undefined": {
      "abstract": [
        {
          "text": "A blank or undefined section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectSectionTypeUndefined"
        }
      ],
      "role": "symbol",
      "title": "PHProjectSection.SectionType.undefined",
      "type": "topic",
      "url": "/documentation/photosui/phprojectsection/sectiontype-swift.enum/undefined"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Section-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/undefined",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/content",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/auxiliary"
      ],
      "title": "Section Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHProjectSectionTypeCover"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSectionTypeCover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Section-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/undefined",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/content",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectSection/SectionType-swift.enum/auxiliary"
              ],
              "title": "Section Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHProjectSectionTypeCover"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum~1auxiliary/title",
          "value": "PHProjectSectionTypeAuxiliary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum~1auxiliary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSectionTypeAuxiliary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum~1content/title",
          "value": "PHProjectSectionTypeContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum~1content/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSectionTypeContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum~1undefined/title",
          "value": "PHProjectSectionTypeUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSectionTypeUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum/title",
          "value": "PHProjectSectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/title",
          "value": "PHProjectSection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum~1cover/title",
          "value": "PHProjectSectionTypeCover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectSection~1SectionType-swift.enum~1cover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectSectionTypeCover"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojectsection/sectiontype-swift.enum/cover"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojectsection/sectiontype-swift.enum/cover"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
