{
  "abstract": [
    {
      "text": "Requests an array of precision estimates for each landmark point.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D/precisionEstimatesPerPoint-5jl22"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "s:So22VNFaceLandmarkRegion2DC6VisionE26precisionEstimatesPerPointSaySfGSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "precisionEstimatesPerPoint"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "precisionEstimatesPerPoint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "precisionEstimatesPerPoint"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property is only populated when you configure your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For other constellation types, this array is set to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest": {
      "abstract": [
        {
          "text": "An image-analysis request that finds facial features like eyes and mouth in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectFaceLandmarksRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectFaceLandmarksRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectFaceLandmarksRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectFaceLandmarksRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetectfacelandmarksrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D": {
      "abstract": [
        {
          "text": "2D geometry information for a specific facial feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNFaceLandmarkRegion2D"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNFaceLandmarkRegion2D"
        }
      ],
      "role": "symbol",
      "title": "VNFaceLandmarkRegion2D",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarkregion2d"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D/normalizedPoints-7s7im": {
      "abstract": [
        {
          "text": "The array of normalized landmark points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalizedPoints"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D/normalizedPoints-7s7im",
      "kind": "symbol",
      "role": "symbol",
      "title": "normalizedPoints",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarkregion2d/normalizedpoints-7s7im"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D/precisionEstimatesPerPoint-5jl22": {
      "abstract": [
        {
          "text": "Requests an array of precision estimates for each landmark point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "precisionEstimatesPerPoint"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D/precisionEstimatesPerPoint-5jl22",
      "kind": "symbol",
      "role": "symbol",
      "title": "precisionEstimatesPerPoint",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarkregion2d/precisionestimatesperpoint-5jl22"
    },
    "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points": {
      "abstract": [
        {
          "text": "A constellation with 76 points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constellation76Points"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNRequestFaceLandmarksConstellation/constellation76Points",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNRequestFaceLandmarksConstellation76Points"
        }
      ],
      "role": "symbol",
      "title": "VNRequestFaceLandmarksConstellation.constellation76Points",
      "type": "topic",
      "url": "/documentation/vision/vnrequestfacelandmarksconstellation/constellation76points"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Region-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D/normalizedPoints-7s7im"
      ],
      "title": "Specifying Region Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation76Points/title",
          "value": "VNRequestFaceLandmarksConstellation76Points"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNRequestFaceLandmarksConstellation~1constellation76Points/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNRequestFaceLandmarksConstellation76Points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarkRegion2D/title",
          "value": "VNFaceLandmarkRegion2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarkRegion2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceLandmarkRegion2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarkRegion2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceLandmarkRegion2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/title",
          "value": "VNDetectFaceLandmarksRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceLandmarksRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectFaceLandmarksRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectFaceLandmarksRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnfacelandmarkregion2d/precisionestimatesperpoint-5jl22"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
