{
  "abstract": [
    {
      "text": "You successfully scheduled the transaction.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/success"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPayBillIntentResponseCode@INPayBillIntentResponseCodeSuccess",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "success"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPayBillIntentResponseCodeSuccess"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.3",
        "message": "INPayBillIntentResponseCode is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.3",
        "message": "INPayBillIntentResponseCode is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INPayBillIntentResponseCode is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INPayBillIntentResponseCode is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.2",
        "message": "INPayBillIntentResponseCode is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INPayBillIntentResponseCode.success"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "success"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this code after scheduling the transaction successfully. Returning this code doesn’t requirea transfer of funds. It only means that you’ve recorded the transaction are making the payment on the date specified in the intent object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to schedule the transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureCredentialsUnverified": {
      "abstract": [
        {
          "text": "The transaction failed because you were unable to verify the credentials of the user or the payee.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCredentialsUnverified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureCredentialsUnverified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCodeFailureCredentialsUnverified"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode.failureCredentialsUnverified",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode/failurecredentialsunverified"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureInsufficientFunds": {
      "abstract": [
        {
          "text": "The transaction failed because the user’s account didn’t contain sufficient funds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureInsufficientFunds"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureInsufficientFunds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCodeFailureInsufficientFunds"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode.failureInsufficientFunds",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode/failureinsufficientfunds"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to schedule the transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "You’ve received the payment details and are in the process of scheduling the transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You’re ready to handle the intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/success": {
      "abstract": [
        {
          "text": "You successfully scheduled the transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "The response didn’t specify a response code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPayBillIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INPayBillIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inpaybillintentresponsecode/unspecified"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureCredentialsUnverified",
        "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureInsufficientFunds"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPayBillIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureCredentialsUnverified",
                "doc://com.apple.sirikit/documentation/Intents/INPayBillIntentResponseCode/failureInsufficientFunds"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INPayBillIntentResponseCodeSuccess"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1failureInsufficientFunds/title",
          "value": "INPayBillIntentResponseCodeFailureInsufficientFunds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1failureInsufficientFunds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeFailureInsufficientFunds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INPayBillIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1unspecified/title",
          "value": "INPayBillIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1success/title",
          "value": "INPayBillIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode/title",
          "value": "INPayBillIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1inProgress/title",
          "value": "INPayBillIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1failureCredentialsUnverified/title",
          "value": "INPayBillIntentResponseCodeFailureCredentialsUnverified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1failureCredentialsUnverified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeFailureCredentialsUnverified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1failure/title",
          "value": "INPayBillIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1ready/title",
          "value": "INPayBillIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPayBillIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPayBillIntentResponseCodeReady"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inpaybillintentresponsecode/success"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inpaybillintentresponsecode/success"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
