{
  "abstract": [
    {
      "text": "A mask for detecting a device shared by another Mac host.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/shared"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICDeviceLocationTypeMask@ICDeviceLocationTypeMaskShared",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shared"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICDeviceLocationTypeMaskShared"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICDeviceLocationTypeMask.shared"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shared"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask": {
      "abstract": [
        {
          "text": "Masks for detecting different device locations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMask"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMask"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationTypeMask",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationtypemask"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/bluetooth": {
      "abstract": [
        {
          "text": "A mask for detecting a paired Bluetooth device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetooth"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/bluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMaskBluetooth"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationTypeMask.bluetooth",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationtypemask/bluetooth"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/bonjour": {
      "abstract": [
        {
          "text": "A mask for detecting a network device that publishes a Bonjour service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bonjour"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/bonjour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMaskBonjour"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationTypeMask.bonjour",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationtypemask/bonjour"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/local": {
      "abstract": [
        {
          "text": "A mask for detecting a local device, such as USB or FireWire.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "local"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/local",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMaskLocal"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationTypeMask.local",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationtypemask/local"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/remote": {
      "abstract": [
        {
          "text": "A mask for detecting a remote device, such as a shared, Bonjour, or Bluetooth device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remote"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/remote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMaskRemote"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationTypeMask.remote",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationtypemask/remote"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/shared": {
      "abstract": [
        {
          "text": "A mask for detecting a device shared by another Mac host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMaskShared"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationTypeMask.shared",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationtypemask/shared"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/bluetooth",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/bonjour",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/local",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/remote"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICDeviceLocationTypeMaskShared"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMaskShared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/bluetooth",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/bonjour",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/local",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask/remote"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICDeviceLocationTypeMaskShared"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask/title",
          "value": "ICDeviceLocationTypeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1bluetooth/title",
          "value": "ICDeviceLocationTypeMaskBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1bluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMaskBluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1bonjour/title",
          "value": "ICDeviceLocationTypeMaskBonjour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1bonjour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMaskBonjour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1local/title",
          "value": "ICDeviceLocationTypeMaskLocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1local/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMaskLocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1shared/title",
          "value": "ICDeviceLocationTypeMaskShared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMaskShared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1remote/title",
          "value": "ICDeviceLocationTypeMaskRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask~1remote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMaskRemote"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icdevicelocationtypemask/shared"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icdevicelocationtypemask/shared"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
