{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/failed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioComponentValidationResult@kAudioComponentValidationResult_Failed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failed"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioComponentValidationResult_Failed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AudioComponentValidationResult.failed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioComponentValidationResult"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioComponentValidationResult"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentValidationResult",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentvalidationresult"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/failed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentValidationResult_Failed"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentValidationResult.failed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentvalidationresult/failed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/passed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passed"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/passed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentValidationResult_Passed"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentValidationResult.passed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentvalidationresult/passed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/timedOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOut"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/timedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentValidationResult_TimedOut"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentValidationResult.timedOut",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentvalidationresult/timedout"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unauthorizedError_Init": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unauthorizedError_Init"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unauthorizedError_Init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentValidationResult_UnauthorizedError_Init"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentValidationResult.unauthorizedError_Init",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentvalidationresult/unauthorizederror_init"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unauthorizedError_Open": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unauthorizedError_Open"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unauthorizedError_Open",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentValidationResult_UnauthorizedError_Open"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentValidationResult.unauthorizedError_Open",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentvalidationresult/unauthorizederror_open"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioComponentValidationResult_Unknown"
        }
      ],
      "role": "symbol",
      "title": "AudioComponentValidationResult.unknown",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiocomponentvalidationresult/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/passed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/timedOut",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unauthorizedError_Init",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unauthorizedError_Open",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioComponentValidationResult_Failed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentValidationResult_Failed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/passed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/timedOut",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unauthorizedError_Init",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unauthorizedError_Open",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioComponentValidationResult/unknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioComponentValidationResult_Failed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1failed/title",
          "value": "kAudioComponentValidationResult_Failed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentValidationResult_Failed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1timedOut/title",
          "value": "kAudioComponentValidationResult_TimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1timedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentValidationResult_TimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult/title",
          "value": "AudioComponentValidationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentValidationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioComponentValidationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1unauthorizedError_Open/title",
          "value": "kAudioComponentValidationResult_UnauthorizedError_Open"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1unauthorizedError_Open/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentValidationResult_UnauthorizedError_Open"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1passed/title",
          "value": "kAudioComponentValidationResult_Passed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1passed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentValidationResult_Passed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1unknown/title",
          "value": "kAudioComponentValidationResult_Unknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentValidationResult_Unknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1unauthorizedError_Init/title",
          "value": "kAudioComponentValidationResult_UnauthorizedError_Init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioComponentValidationResult~1unauthorizedError_Init/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentValidationResult_UnauthorizedError_Init"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiocomponentvalidationresult/failed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiocomponentvalidationresult/failed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
