{
  "abstract": [
    {
      "text": "The document has been initialized with the contents of a file or file package other than the one whose location is in the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileURL",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property, and therefore can’t possibly be synchronized with its persistent representation. For example, ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/init(for:withContentsOf:ofType:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " passes this value when the two passed-in URLs are not equal to indicate that an autosaved document is being reopened.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeReadOtherContents"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSDocumentChangeType@NSChangeReadOtherContents",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "changeReadOtherContents"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSChangeReadOtherContents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSDocument.ChangeType.changeReadOtherContents"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "changeReadOtherContents"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType": {
      "abstract": [
        {
          "text": "Values that indicate a document’s edit status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ChangeType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ChangeType"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.ChangeType",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/changetype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeAutosaved": {
      "abstract": [
        {
          "text": "The document’s contents have been autosaved. For example, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " passes this value for a successful ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSaveOperationType/NSAutosaveOperation",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeAutosaved"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeAutosaved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSChangeAutosaved"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.ChangeType.changeAutosaved",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/changetype/changeautosaved"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeCleared": {
      "abstract": [
        {
          "text": "Set change count to 0. The document has been synchronized with its file or file package. For example, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " passes this value for a successful ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType/saveOperation",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType/saveAsOperation",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method does too.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeCleared"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeCleared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSChangeCleared"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.ChangeType.changeCleared",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/changetype/changecleared"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeDiscardable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeDiscardable"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeDiscardable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSChangeDiscardable"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.ChangeType.changeDiscardable",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/changetype/changediscardable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeDone": {
      "abstract": [
        {
          "text": "Increment change count. Pass this value to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method to indicate that a single change has been done. For example, the built-in undo support in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class passes this value whenever a document receives an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1408817-nsundomanagerdidcloseundogroup",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " notification from its own undo manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeDone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeDone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSChangeDone"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.ChangeType.changeDone",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/changetype/changedone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeReadOtherContents": {
      "abstract": [
        {
          "text": "The document has been initialized with the contents of a file or file package other than the one whose location is in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileURL",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property, and therefore can’t possibly be synchronized with its persistent representation. For example, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/init(for:withContentsOf:ofType:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " passes this value when the two passed-in URLs are not equal to indicate that an autosaved document is being reopened.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeReadOtherContents"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeReadOtherContents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSChangeReadOtherContents"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.ChangeType.changeReadOtherContents",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/changetype/changereadothercontents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeRedone": {
      "abstract": [
        {
          "text": "A single change has been redone. For example, the built-in undo support of ",
          "type": "text"
        },
        {
          "code": "NSDocument",
          "type": "codeVoice"
        },
        {
          "text": " passes this value whenever a document receives an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1413579-nsundomanagerdidredochange",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " from its own undo manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeRedone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeRedone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSChangeRedone"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.ChangeType.changeRedone",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/changetype/changeredone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeUndone": {
      "abstract": [
        {
          "text": "Decrement change count. A single change has been undone. For example, the built-in undo support of ",
          "type": "text"
        },
        {
          "code": "NSDocument",
          "type": "codeVoice"
        },
        {
          "text": " passes this value whenever a document receives an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1410142-nsundomanagerdidundochange",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " from its own undo manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeUndone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeUndone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSChangeUndone"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.ChangeType.changeUndone",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/changetype/changeundone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType/saveAsOperation": {
      "abstract": [
        {
          "text": "An operation that writes the document’s contents to a new location and updates the document to point to that location",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveAsOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType/saveAsOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSaveAsOperation"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.SaveOperationType.saveAsOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/saveoperationtype/saveasoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType/saveOperation": {
      "abstract": [
        {
          "text": "An operation that overwrites a document’s file or file package with the document’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType/saveOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSaveOperation"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.SaveOperationType.saveOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/saveoperationtype/saveoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileURL": {
      "abstract": [
        {
          "text": "The location of the document’s on-disk representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileURL"
        }
      ],
      "role": "symbol",
      "title": "fileURL",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/fileurl"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/init(for:withContentsOf:ofType:)": {
      "abstract": [
        {
          "text": "Initializes a document with the specified contents, and places the resulting document’s file at the designated location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/init(for:withContentsOf:ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initForURL:withContentsOfURL:ofType:error:"
        }
      ],
      "role": "symbol",
      "title": "init(for:withContentsOf:ofType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/init(for:withcontentsof:oftype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)": {
      "abstract": [
        {
          "text": "The action of the File menu item Revert in a document-based app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revertToSaved"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertDocumentToSaved:"
        }
      ],
      "role": "symbol",
      "title": "revertToSaved(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/reverttosaved(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:": {
      "abstract": [
        {
          "text": "Saves the contents of the document to a file or file package located by a URL, formatted to a specified type, for a particular kind of save operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "saveToURL:ofType:forSaveOperation:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToURL:ofType:forSaveOperation:error:"
        }
      ],
      "role": "symbol",
      "title": "saveToURL:ofType:forSaveOperation:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/savetourl:oftype:forsaveoperation:error:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)": {
      "abstract": [
        {
          "text": "Updates the receiver’s change count according to the given change type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateChangeCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDocumentChangeType",
          "text": "ChangeType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateChangeCount:"
        }
      ],
      "role": "symbol",
      "title": "updateChangeCount(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/updatechangecount(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSaveOperationType/NSAutosaveOperation": {
      "abstract": [
        {
          "text": "Old name for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType/autosaveElsewhereOperation",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " operation type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAutosaveOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSaveOperationType/NSAutosaveOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAutosaveOperation",
      "type": "topic",
      "url": "/documentation/appkit/nssaveoperationtype/nsautosaveoperation"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1408817-nsundomanagerdidcloseundogroup": {
      "abstract": [
        {
          "text": "Posted after an undo manager closes an undo group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSUndoManagerDidCloseUndoGroup"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1408817-nsundomanagerdidcloseundogroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUndoManagerDidCloseUndoGroup",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1408817-nsundomanagerdidcloseundogroup"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1410142-nsundomanagerdidundochange": {
      "abstract": [
        {
          "text": "Posted just after an undo manager performs an undo operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSUndoManagerDidUndoChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1410142-nsundomanagerdidundochange",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUndoManagerDidUndoChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1410142-nsundomanagerdidundochange"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1413579-nsundomanagerdidredochange": {
      "abstract": [
        {
          "text": "Posted just after an undo manager performs a redo operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSUndoManagerDidRedoChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1413579-nsundomanagerdidredochange",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUndoManagerDidRedoChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1413579-nsundomanagerdidredochange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeDone",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeUndone",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeCleared",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeAutosaved",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeRedone",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeDiscardable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSChangeReadOtherContents"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSChangeReadOtherContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeDone",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeUndone",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeCleared",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeAutosaved",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeRedone",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/ChangeType/changeDiscardable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSChangeReadOtherContents"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1fileURL/title",
          "value": "fileURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1fileURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fileURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeUndone/title",
          "value": "NSChangeUndone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeUndone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSChangeUndone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsnotification~1name~11408817-nsundomanagerdidcloseundogroup/title",
          "value": "NSUndoManagerDidCloseUndoGroupNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1revertToSaved(_:)/title",
          "value": "revertDocumentToSaved:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1revertToSaved(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "revertDocumentToSaved:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsnotification~1name~11410142-nsundomanagerdidundochange/title",
          "value": "NSUndoManagerDidUndoChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType~1saveOperation/title",
          "value": "NSSaveOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType~1saveOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSaveOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1updateChangeCount(_:)/title",
          "value": "updateChangeCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1updateChangeCount(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateChangeCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsnotification~1name~11413579-nsundomanagerdidredochange/title",
          "value": "NSUndoManagerDidRedoChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeReadOtherContents/title",
          "value": "NSChangeReadOtherContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeReadOtherContents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSChangeReadOtherContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeDiscardable/title",
          "value": "NSChangeDiscardable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeDiscardable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSChangeDiscardable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeDone/title",
          "value": "NSChangeDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeDone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSChangeDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType~1saveAsOperation/title",
          "value": "NSSaveAsOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType~1saveAsOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSaveAsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1init(for:withContentsOf:ofType:)/title",
          "value": "initForURL:withContentsOfURL:ofType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1init(for:withContentsOf:ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initForURL:withContentsOfURL:ofType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType/title",
          "value": "NSDocumentChangeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeCleared/title",
          "value": "NSChangeCleared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeCleared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSChangeCleared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeRedone/title",
          "value": "NSChangeRedone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeRedone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSChangeRedone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title",
          "value": "NSDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeAutosaved/title",
          "value": "NSChangeAutosaved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1ChangeType~1changeAutosaved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSChangeAutosaved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocument/changetype/changereadothercontents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdocument/changetype/changereadothercontents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
