{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the VM can overwrite an existing auxiliary storage file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions/allowOverwrite"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VZMacAuxiliaryStorageInitializationOptions@VZMacAuxiliaryStorageInitializationOptionAllowOverwrite",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allowOverwrite"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VZMacAuxiliaryStorage",
        "text": "VZMacAuxiliaryStorage"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@VZMacAuxiliaryStorageInitializationOptions",
        "text": "InitializationOptions"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZMacAuxiliaryStorageInitializationOptionAllowOverwrite"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "allowOverwrite"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allowOverwrite"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VZMacAuxiliaryStorage",
              "text": "VZMacAuxiliaryStorage"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VZMacAuxiliaryStorageInitializationOptions",
              "text": "InitializationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage": {
      "abstract": [
        {
          "text": "An object that contains information the boot loader needs for booting macOS as a guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacAuxiliaryStorage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacAuxiliaryStorage"
        }
      ],
      "role": "symbol",
      "title": "VZMacAuxiliaryStorage",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacauxiliarystorage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions": {
      "abstract": [
        {
          "text": "Options you can set when creating new auxiliary storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InitializationOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InitializationOptions"
        }
      ],
      "role": "symbol",
      "title": "VZMacAuxiliaryStorage.InitializationOptions",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacauxiliarystorage/initializationoptions"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions/allowOverwrite": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the VM can overwrite an existing auxiliary storage file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowOverwrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZMacAuxiliaryStorage",
          "text": "VZMacAuxiliaryStorage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZMacAuxiliaryStorageInitializationOptions",
          "text": "InitializationOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions/allowOverwrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacAuxiliaryStorageInitializationOptionAllowOverwrite"
        }
      ],
      "role": "symbol",
      "title": "allowOverwrite",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacauxiliarystorage/initializationoptions/allowoverwrite"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZMacAuxiliaryStorageInitializationOptionAllowOverwrite"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorageInitializationOptionAllowOverwrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VZMacAuxiliaryStorageInitializationOptionAllowOverwrite"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage~1InitializationOptions/title",
          "value": "VZMacAuxiliaryStorageInitializationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage~1InitializationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorageInitializationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage~1InitializationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorageInitializationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage~1InitializationOptions~1allowOverwrite/title",
          "value": "VZMacAuxiliaryStorageInitializationOptionAllowOverwrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage~1InitializationOptions~1allowOverwrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorageInitializationOptionAllowOverwrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/title",
          "value": "VZMacAuxiliaryStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzmacauxiliarystorage/initializationoptions/allowoverwrite"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzmacauxiliarystorage/initializationoptions/allowoverwrite"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
