{
  "abstract": [
    {
      "text": "Network EAPTLS version 1.1.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationEAPTLSVersion/NEHotspotConfigurationEAPTLSVersion_1_1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEHotspotConfigurationEAPTLSVersion@NEHotspotConfigurationEAPTLSVersion_1_1",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NEHotspotConfigurationEAPTLSVersion_1_1"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEHotspotConfigurationEAPTLSVersion_1_1"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NEHotspotConfigurationEAPTLSVersion_1_1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTLSVersion_1_1"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationEAPTLSVersion/NEHotspotConfigurationEAPTLSVersion_1_1": {
      "abstract": [
        {
          "text": "Network EAPTLS version 1.1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTLSVersion_1_1"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotConfigurationEAPTLSVersion/NEHotspotConfigurationEAPTLSVersion_1_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEHotspotConfigurationEAPTLSVersion_1_1",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspotconfigurationeaptlsversion/nehotspotconfigurationeaptlsversion_1_1"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion": {
      "abstract": [
        {
          "text": "The EAPTLS Version identifiers that may be specified by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/preferredTLSVersion",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TLSVersion"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TLSVersion"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TLSVersion",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/tlsversion"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/preferredTLSVersion": {
      "abstract": [
        {
          "text": "The Transport Layer Security (TLS) version to use during a TLS authentication handshake.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTLSVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEHotspotEAPSettings",
          "text": "NEHotspotEAPSettings"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEHotspotConfigurationEAPTLSVersion",
          "text": "TLSVersion"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/preferredTLSVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredTLSVersion"
        }
      ],
      "role": "symbol",
      "title": "preferredTLSVersion",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/preferredtlsversion"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TLSVersion/title",
          "value": "NEHotspotConfigurationEAPTLSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TLSVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TLSVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1preferredTLSVersion/title",
          "value": "preferredTLSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1preferredTLSVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredTLSVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspotconfigurationeaptlsversion/nehotspotconfigurationeaptlsversion_1_1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
