{
  "abstract": [
    {
      "text": "An error that indicates developer signature for this action is corrupted.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionSignatureCorruptError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AMErrorCode@AMActionSignatureCorruptError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "actionSignatureCorruptError"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AMActionSignatureCorruptError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AMError.Code.actionSignatureCorruptError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "actionSignatureCorruptError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMError": {
      "abstract": [
        {
          "text": "An Automator error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "role": "symbol",
      "title": "AMError",
      "type": "topic",
      "url": "/documentation/automator/amerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code": {
      "abstract": [
        {
          "text": "Automator error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code",
      "type": "topic",
      "url": "/documentation/automator/amerror/code"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an app required by the action is not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionApplicationResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionApplicationResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionApplicationResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionapplicationresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationVersionResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an app required by the action is the wrong version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionApplicationVersionResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationVersionResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionApplicationVersionResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionApplicationVersionResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionapplicationversionresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionArchitectureMismatchError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s binary is not compatible with the current processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionArchitectureMismatchError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionArchitectureMismatchError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionArchitectureMismatchError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionArchitectureMismatchError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionarchitecturemismatcherror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExceptionError": {
      "abstract": [
        {
          "text": "An error that indicates an action encounters an exception while running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionExceptionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExceptionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionExceptionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionExceptionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionexceptionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExecutionError": {
      "abstract": [
        {
          "text": "An error that indicates an action encounters an error while running (reason unknown).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionExecutionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExecutionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionExecutionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionExecutionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionexecutionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFailedGatekeeperError": {
      "abstract": [
        {
          "text": "An error that indicates the action doesn’t meet the Gatekeeper security policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionFailedGatekeeperError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFailedGatekeeperError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionFailedGatekeeperError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionFailedGatekeeperError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionfailedgatekeepererror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFileResourceError": {
      "abstract": [
        {
          "text": "An error that indicates a file required by the action is not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionFileResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFileResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionFileResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionFileResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionfileresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInitializationError": {
      "abstract": [
        {
          "text": "An error that indicates Automator is unable to initialize an action (reason unknown).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionInitializationError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInitializationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionInitializationError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionInitializationError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actioninitializationerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInsufficientDataError": {
      "abstract": [
        {
          "text": "An error that indicates the action requires input data to run, but none was supplied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionInsufficientDataError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInsufficientDataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionInsufficientDataError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionInsufficientDataError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actioninsufficientdataerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionIsDeprecatedError": {
      "abstract": [
        {
          "text": "An error that indicates the action has been deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionIsDeprecatedError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionIsDeprecatedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionIsDeprecatedError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionIsDeprecatedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionisdeprecatederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLicenseResourceError": {
      "abstract": [
        {
          "text": "An error that indicates a license required by the action was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLicenseResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLicenseResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionLicenseResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionLicenseResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionlicenseresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLinkError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable failed to load due to linking issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLinkError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLinkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionLinkError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionLinkError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionlinkerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLoadError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLoadError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLoadError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionLoadError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionLoadError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionloaderror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionMalwareError": {
      "abstract": [
        {
          "text": "An error that indicates the action has been identified as malware by XProtect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionMalwareError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionMalwareError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionMalwareError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionMalwareError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionmalwareerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionNotLoadableError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable is of a type that is not loadable in the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionNotLoadableError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionNotLoadableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionNotLoadableError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionNotLoadableError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionnotloadableerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionSignatureCorruptError": {
      "abstract": [
        {
          "text": "An error that indicates developer signature for this action is corrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionSignatureCorruptError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionSignatureCorruptError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionSignatureCorruptError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionSignatureCorruptError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionsignaturecorrupterror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Action-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationVersionResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionArchitectureMismatchError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExceptionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExecutionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFailedGatekeeperError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFileResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInitializationError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInsufficientDataError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionIsDeprecatedError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLicenseResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLinkError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLoadError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionMalwareError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionNotLoadableError"
      ],
      "title": "Action Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AMActionSignatureCorruptError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionSignatureCorruptError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator",
                "doc://com.apple.automator/documentation/Automator/AMError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Action-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationVersionResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionArchitectureMismatchError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExceptionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExecutionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFailedGatekeeperError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFileResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInitializationError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInsufficientDataError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionIsDeprecatedError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLicenseResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLinkError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLoadError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionMalwareError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionNotLoadableError"
              ],
              "title": "Action Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AMActionSignatureCorruptError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionFailedGatekeeperError/title",
          "value": "AMActionFailedGatekeeperError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionFailedGatekeeperError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionFailedGatekeeperError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionExecutionError/title",
          "value": "AMActionExecutionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionExecutionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionExecutionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/title",
          "value": "AMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionSignatureCorruptError/title",
          "value": "AMActionSignatureCorruptError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionSignatureCorruptError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionSignatureCorruptError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionExceptionError/title",
          "value": "AMActionExceptionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionExceptionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionExceptionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionMalwareError/title",
          "value": "AMActionMalwareError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionMalwareError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionMalwareError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLinkError/title",
          "value": "AMActionLinkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLinkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionLinkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionArchitectureMismatchError/title",
          "value": "AMActionArchitectureMismatchError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionArchitectureMismatchError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionArchitectureMismatchError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionFileResourceError/title",
          "value": "AMActionFileResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionFileResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionFileResourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionInsufficientDataError/title",
          "value": "AMActionInsufficientDataError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionInsufficientDataError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionInsufficientDataError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionIsDeprecatedError/title",
          "value": "AMActionIsDeprecatedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionIsDeprecatedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionIsDeprecatedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionInitializationError/title",
          "value": "AMActionInitializationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionInitializationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionInitializationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionApplicationVersionResourceError/title",
          "value": "AMActionApplicationVersionResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionApplicationVersionResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionApplicationVersionResourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLoadError/title",
          "value": "AMActionLoadError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLoadError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionLoadError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLicenseResourceError/title",
          "value": "AMActionLicenseResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLicenseResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionLicenseResourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionNotLoadableError/title",
          "value": "AMActionNotLoadableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionNotLoadableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionNotLoadableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionApplicationResourceError/title",
          "value": "AMActionApplicationResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionApplicationResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionApplicationResourceError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amerror/code/actionsignaturecorrupterror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amerror/code/actionsignaturecorrupterror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
