{
  "abstract": [
    {
      "text": "An error that indicates an action in a workflow is older than the installed action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowOlderActionVersionError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AMErrorCode@AMWorkflowOlderActionVersionError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "workflowOlderActionVersionError"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AMWorkflowOlderActionVersionError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AMError.Code.workflowOlderActionVersionError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "workflowOlderActionVersionError"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error is presented to the user as a warning.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMError": {
      "abstract": [
        {
          "text": "An Automator error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "role": "symbol",
      "title": "AMError",
      "type": "topic",
      "url": "/documentation/automator/amerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code": {
      "abstract": [
        {
          "text": "Automator error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code",
      "type": "topic",
      "url": "/documentation/automator/amerror/code"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowActionsNotLoadedError": {
      "abstract": [
        {
          "text": "An error that indicates one of the actions of the workflow couldn’t be loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowActionsNotLoadedError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowActionsNotLoadedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowActionsNotLoadedError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowActionsNotLoadedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflowactionsnotloadederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerActionVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an action in a workflow is newer than the installed action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNewerActionVersionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerActionVersionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowNewerActionVersionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowNewerActionVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflowneweractionversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt to open a workflow document that was saved with a newer version of Automator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNewerVersionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerVersionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowNewerVersionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowNewerVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflownewerversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNoEnabledActionsError": {
      "abstract": [
        {
          "text": "An error that indicates there are no enabled actions in the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNoEnabledActionsError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNoEnabledActionsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowNoEnabledActionsError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowNoEnabledActionsError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflownoenabledactionserror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowOlderActionVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an action in a workflow is older than the installed action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowOlderActionVersionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowOlderActionVersionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowOlderActionVersionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowOlderActionVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflowolderactionversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowPropertyListInvalidError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt to open a workflow document whose property list couldn’t be read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowPropertyListInvalidError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowPropertyListInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowPropertyListInvalidError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowPropertyListInvalidError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflowpropertylistinvaliderror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Workflow-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowActionsNotLoadedError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerActionVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNoEnabledActionsError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowPropertyListInvalidError"
      ],
      "title": "Workflow Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AMWorkflowOlderActionVersionError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowOlderActionVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator",
                "doc://com.apple.automator/documentation/Automator/AMError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Workflow-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowActionsNotLoadedError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerActionVersionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerVersionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNoEnabledActionsError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowPropertyListInvalidError"
              ],
              "title": "Workflow Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AMWorkflowOlderActionVersionError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNewerActionVersionError/title",
          "value": "AMWorkflowNewerActionVersionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNewerActionVersionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowNewerActionVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowActionsNotLoadedError/title",
          "value": "AMWorkflowActionsNotLoadedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowActionsNotLoadedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowActionsNotLoadedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNoEnabledActionsError/title",
          "value": "AMWorkflowNoEnabledActionsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNoEnabledActionsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowNoEnabledActionsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowPropertyListInvalidError/title",
          "value": "AMWorkflowPropertyListInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowPropertyListInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowPropertyListInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowOlderActionVersionError/title",
          "value": "AMWorkflowOlderActionVersionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowOlderActionVersionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowOlderActionVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNewerVersionError/title",
          "value": "AMWorkflowNewerVersionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNewerVersionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowNewerVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/title",
          "value": "AMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amerror/code/workflowolderactionversionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amerror/code/workflowolderactionversionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
