{"abstract":[{"type":"text","text":"An error indicating that the metadata fetch was canceled by the client."}],"seeAlsoSections":[{"title":"Error cases","identifiers":["doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown"],"anchor":"Error-cases","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Link-Presentation/documentation/LinkPresentation","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code"]]},"identifier":{"url":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled","interfaceLanguage":"swift"},"metadata":{"platforms":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.1","deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"introducedAt":"10.15","deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0","deprecated":false}],"role":"symbol","externalID":"c:@E@LPErrorCode@LPErrorMetadataFetchCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchCancelled"}],"navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchCancelled"}],"symbolKind":"case","roleHeading":"Case","title":"LPError.Code.metadataFetchCancelled","modules":[{"name":"Link Presentation"}]},"sections":[],"kind":"symbol","variants":[{"paths":["/documentation/linkpresentation/lperror/code/metadatafetchcancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/linkpresentation/lperror/code/metadatafetchcancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metadataFetchCancelled","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError":{"type":"topic","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LPError"}],"abstract":[{"type":"text","text":"An error returned by the LinkPresentation framework."}],"kind":"symbol","title":"LPError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LPError"}],"url":"/documentation/linkpresentation/lperror"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown":{"type":"topic","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LPErrorUnknown"}],"abstract":[{"type":"text","text":"An unknown error."}],"kind":"symbol","title":"LPError.Code.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"url":"/documentation/linkpresentation/lperror/code/unknown"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed":{"navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchFailed"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An error indicating that a metadata fetch failed."}],"title":"LPError.Code.metadataFetchFailed","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchFailed"}],"kind":"symbol","url":"/documentation/linkpresentation/lperror/code/metadatafetchfailed"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation":{"title":"Link Presentation","type":"topic","kind":"symbol","role":"collection","url":"/documentation/linkpresentation","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation","abstract":[{"type":"text","text":"Fetch, provide, and present rich links in your app."}]},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut":{"navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchTimedOut"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An error indicating that the metadata fetch took longer than allowed."}],"title":"LPError.Code.metadataFetchTimedOut","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchTimedOut"}],"kind":"symbol","url":"/documentation/linkpresentation/lperror/code/metadatafetchtimedout"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","role":"overview","type":"topic","title":"Technologies"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code":{"role":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Possible error values that can be returned from LinkPresentation APIs."}],"identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code","url":"/documentation/linkpresentation/lperror/code","title":"LPError.Code","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled":{"abstract":[{"type":"text","text":"An error indicating that the metadata fetch was canceled by the client."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchCancelled"}],"identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled","title":"LPError.Code.metadataFetchCancelled","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchCancelled"}],"url":"/documentation/linkpresentation/lperror/code/metadatafetchcancelled","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"13.1"},{"beta":false,"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"10.15"},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"LPErrorMetadataFetchCancelled"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"LPErrorMetadataFetchCancelled","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Link-Presentation/documentation/LinkPresentation","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown"],"generated":true,"anchor":"Error-cases","title":"Error cases"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"LPErrorMetadataFetchCancelled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"LPErrorUnknown","op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1unknown/title"},{"value":[{"text":"LPErrorUnknown","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1unknown/fragments"},{"value":"LPErrorMetadataFetchFailed","op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchFailed/title"},{"value":[{"text":"LPErrorMetadataFetchFailed","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchFailed/fragments"},{"value":"LPErrorMetadataFetchTimedOut","op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchTimedOut/title"},{"value":[{"kind":"identifier","text":"LPErrorMetadataFetchTimedOut"}],"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchTimedOut/fragments"},{"value":"LPErrorCode","op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/title"},{"value":[{"text":"LPErrorCode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/fragments"},{"value":[{"kind":"identifier","text":"LPErrorCode"}],"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/navigatorTitle"},{"value":"LPErrorMetadataFetchCancelled","op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchCancelled/title"},{"value":[{"text":"LPErrorMetadataFetchCancelled","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchCancelled/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}