{"abstract":[{"text":"An error indicating that the metadata fetch took longer than allowed.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Link-Presentation/documentation/LinkPresentation","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metadataFetchTimedOut","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["/documentation/linkpresentation/lperror/code/metadatafetchtimedout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/linkpresentation/lperror/code/metadatafetchtimedout"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown"],"title":"Error cases","anchor":"Error-cases"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchTimedOut"}],"platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"13.0","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"introducedAt":"10.15","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"role":"symbol","roleHeading":"Case","title":"LPError.Code.metadataFetchTimedOut","externalID":"c:@E@LPErrorCode@LPErrorMetadataFetchTimedOut","symbolKind":"case","modules":[{"name":"Link Presentation"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchTimedOut"}]},"sections":[],"references":{"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown":{"type":"topic","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LPErrorUnknown"}],"abstract":[{"type":"text","text":"An unknown error."}],"kind":"symbol","title":"LPError.Code.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"url":"/documentation/linkpresentation/lperror/code/unknown"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code":{"role":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Possible error values that can be returned from LinkPresentation APIs."}],"identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code","url":"/documentation/linkpresentation/lperror/code","title":"LPError.Code","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed":{"navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchFailed"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An error indicating that a metadata fetch failed."}],"title":"LPError.Code.metadataFetchFailed","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchFailed"}],"kind":"symbol","url":"/documentation/linkpresentation/lperror/code/metadatafetchfailed"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled":{"abstract":[{"type":"text","text":"An error indicating that the metadata fetch was canceled by the client."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchCancelled"}],"identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled","title":"LPError.Code.metadataFetchCancelled","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchCancelled"}],"url":"/documentation/linkpresentation/lperror/code/metadatafetchcancelled","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","role":"overview","type":"topic","title":"Technologies"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError":{"type":"topic","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LPError"}],"abstract":[{"type":"text","text":"An error returned by the LinkPresentation framework."}],"kind":"symbol","title":"LPError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LPError"}],"url":"/documentation/linkpresentation/lperror"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut":{"navigatorTitle":[{"kind":"identifier","text":"LPErrorMetadataFetchTimedOut"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An error indicating that the metadata fetch took longer than allowed."}],"title":"LPError.Code.metadataFetchTimedOut","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataFetchTimedOut"}],"kind":"symbol","url":"/documentation/linkpresentation/lperror/code/metadatafetchtimedout"},"doc://com.apple.Link-Presentation/documentation/LinkPresentation":{"title":"Link Presentation","type":"topic","kind":"symbol","role":"collection","url":"/documentation/linkpresentation","identifier":"doc://com.apple.Link-Presentation/documentation/LinkPresentation","abstract":[{"type":"text","text":"Fetch, provide, and present rich links in your app."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"introducedAt":"10.15","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"LPErrorMetadataFetchTimedOut"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"LPErrorMetadataFetchTimedOut","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Link-Presentation/documentation/LinkPresentation","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Error-cases","title":"Error cases","generated":true,"identifiers":["doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed","doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"LPErrorMetadataFetchTimedOut","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}]}},{"value":"LPErrorUnknown","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1unknown/title","op":"replace"},{"value":[{"text":"LPErrorUnknown","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1unknown/fragments","op":"replace"},{"value":"LPErrorCode","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/title","op":"replace"},{"value":[{"kind":"identifier","text":"LPErrorCode"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"LPErrorCode"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/navigatorTitle","op":"replace"},{"value":"LPErrorMetadataFetchFailed","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchFailed/title","op":"replace"},{"value":[{"text":"LPErrorMetadataFetchFailed","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchFailed/fragments","op":"replace"},{"value":"LPErrorMetadataFetchCancelled","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchCancelled/title","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchCancelled/fragments","value":[{"kind":"identifier","text":"LPErrorMetadataFetchCancelled"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchTimedOut/title","value":"LPErrorMetadataFetchTimedOut"},{"op":"replace","path":"/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchTimedOut/fragments","value":[{"text":"LPErrorMetadataFetchTimedOut","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}