{
  "abstract": [
    {
      "text": "Tells the delegate when the route picker view finishes presenting routes to the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate/routePickerViewDidEndPresentingRoutes(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVRoutePickerViewDelegate(im)routePickerViewDidEndPresentingRoutes:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "routePickerViewDidEndPresentingRoutes"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
        "text": "AVRoutePickerView"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "routePickerViewDidEndPresentingRoutes:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "routePickerViewDidEndPresentingRoutes(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "routePickerViewDidEndPresentingRoutes"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "routePickerView"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
              "text": "AVRoutePickerView"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The route picker view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "routePickerView"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView": {
      "abstract": [
        {
          "text": "A view that presents a list of nearby media receivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to adopt to respond to route picker view presentation events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerViewDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate/routePickerViewDidEndPresentingRoutes(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the route picker view finishes presenting routes to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routePickerViewDidEndPresentingRoutes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
          "text": "AVRoutePickerView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate/routePickerViewDidEndPresentingRoutes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routePickerViewDidEndPresentingRoutes:"
        }
      ],
      "role": "symbol",
      "title": "routePickerViewDidEndPresentingRoutes(_:)",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewdelegate/routepickerviewdidendpresentingroutes(_:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate/routePickerViewWillBeginPresentingRoutes(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the route picker view is about to begin presenting routes to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routePickerViewWillBeginPresentingRoutes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
          "text": "AVRoutePickerView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate/routePickerViewWillBeginPresentingRoutes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routePickerViewWillBeginPresentingRoutes:"
        }
      ],
      "role": "symbol",
      "title": "routePickerViewWillBeginPresentingRoutes(_:)",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewdelegate/routepickerviewwillbeginpresentingroutes(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-Routes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate/routePickerViewWillBeginPresentingRoutes(_:)"
      ],
      "title": "Presenting Routes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "routePickerViewDidEndPresentingRoutes:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "routePickerViewDidEndPresentingRoutes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-Routes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewDelegate/routePickerViewWillBeginPresentingRoutes(_:)"
              ],
              "title": "Presenting Routes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "routePickerViewDidEndPresentingRoutes:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
                    "text": "AVRoutePickerView"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "routePickerView"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The route picker view.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "routePickerView"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewDelegate/title",
          "value": "AVRoutePickerViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewDelegate~1routePickerViewDidEndPresentingRoutes(_:)/title",
          "value": "routePickerViewDidEndPresentingRoutes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewDelegate~1routePickerViewDidEndPresentingRoutes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "routePickerViewDidEndPresentingRoutes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/title",
          "value": "AVRoutePickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewDelegate~1routePickerViewWillBeginPresentingRoutes(_:)/title",
          "value": "routePickerViewWillBeginPresentingRoutes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewDelegate~1routePickerViewWillBeginPresentingRoutes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "routePickerViewWillBeginPresentingRoutes:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avroutepickerviewdelegate/routepickerviewdidendpresentingroutes(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avroutepickerviewdelegate/routepickerviewdidendpresentingroutes(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
