{"identifier":{"url":"doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping/renderTargetArrayIndexOffset","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"renderTargetArrayIndexOffset","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"mentions","mentions":["doc://com.apple.metal/documentation/Metal/improving-rendering-performance-with-vertex-amplification"]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"To specify a list of offsets, call the ","type":"text"},{"identifier":"doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setVertexAmplificationCount(_:viewMappings:)","isActive":true,"type":"reference"},{"text":" method.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"When your app renders to different render targets, you specify the render target index to render to in your vertex shader by adding the ","type":"text"},{"type":"codeVoice","code":"render_target_array_index"},{"text":" attribute to one of the vertex shader’s outputs. If you are using vertex amplification, Metal calculates the index for each amplified vertex by adding the index offset for the vertex to the value returned from your shader.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping"]]},"variants":[{"paths":["/documentation/metal/mtlvertexamplificationviewmapping/rendertargetarrayindexoffset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metal/mtlvertexamplificationviewmapping/rendertargetarrayindexoffset"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping/viewportArrayIndexOffset"],"generated":true,"title":"Specifying Mapping Offsets","anchor":"Specifying-Mapping-Offsets"}],"metadata":{"symbolKind":"property","externalID":"c:@SA@MTLVertexAmplificationViewMapping@FI@renderTargetArrayIndexOffset","modules":[{"name":"Metal"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderTargetArrayIndexOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"}],"navigatorTitle":[{"kind":"identifier","text":"renderTargetArrayIndexOffset"}],"title":"renderTargetArrayIndexOffset","platforms":[{"introducedAt":"13.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"13.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.4"},{"deprecated":false,"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.15.4"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"16.0"},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0"}],"role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"type":"text","text":"An offset into the list of render targets."}],"references":{"doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping/renderTargetArrayIndexOffset":{"url":"/documentation/metal/mtlvertexamplificationviewmapping/rendertargetarrayindexoffset","abstract":[{"type":"text","text":"An offset into the list of render targets."}],"title":"renderTargetArrayIndexOffset","identifier":"doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping/renderTargetArrayIndexOffset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"renderTargetArrayIndexOffset"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderTargetArrayIndexOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}]},"doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping":{"kind":"symbol","title":"MTLVertexAmplificationViewMapping","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MTLVertexAmplificationViewMapping","kind":"identifier"}],"abstract":[{"text":"An offset applied to a render target index and viewport index.","type":"text"}],"navigatorTitle":[{"text":"MTLVertexAmplificationViewMapping","kind":"identifier"}],"role":"symbol","type":"topic","url":"/documentation/metal/mtlvertexamplificationviewmapping","identifier":"doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping"},"doc://com.apple.metal/documentation/Metal":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal","title":"Metal","abstract":[{"text":"Render advanced 3D graphics and compute data in parallel with graphics processors.","type":"text"}],"url":"/documentation/metal"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setVertexAmplificationCount(_:viewMappings:)":{"role":"symbol","url":"/documentation/metal/mtlrendercommandencoder/setvertexamplificationcount(_:viewmappings:)","identifier":"doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setVertexAmplificationCount(_:viewMappings:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVertexAmplificationCount","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"viewMappings","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MTLVertexAmplificationViewMapping","kind":"typeIdentifier","preciseIdentifier":"c:@SA@MTLVertexAmplificationViewMapping"},{"text":">?)","kind":"text"}],"navigatorTitle":[{"text":"setVertexAmplificationCount:viewMappings:","kind":"identifier"}],"abstract":[{"type":"text","text":"Configures the number of output vertices the render pipeline produces for each input vertex, optionally with render target and viewport offsets."}],"required":true,"type":"topic","title":"setVertexAmplificationCount(_:viewMappings:)","kind":"symbol"},"doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping/viewportArrayIndexOffset":{"url":"/documentation/metal/mtlvertexamplificationviewmapping/viewportarrayindexoffset","abstract":[{"type":"text","text":"An offset into the list of viewports."}],"title":"viewportArrayIndexOffset","identifier":"doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping/viewportArrayIndexOffset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewportArrayIndexOffset"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewportArrayIndexOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}]},"doc://com.externally.resolved.symbol/s:s6UInt32V":{"type":"topic","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"UInt32","kind":"identifier"}],"title":"UInt32","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V","role":"symbol","abstract":[{"type":"text","text":"A 32-bit unsigned integer value type."}],"url":"/documentation/Swift/UInt32"},"doc://com.apple.metal/documentation/Metal/improving-rendering-performance-with-vertex-amplification":{"kind":"article","identifier":"doc://com.apple.metal/documentation/Metal/improving-rendering-performance-with-vertex-amplification","title":"Improving Rendering Performance with Vertex Amplification","url":"/documentation/metal/improving-rendering-performance-with-vertex-amplification","abstract":[{"type":"text","text":"Run draw commands that render to different outputs using the same vertex data multiple times."}],"role":"article","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"name":"macOS","unavailable":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"renderTargetArrayIndexOffset","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"renderTargetArrayIndexOffset"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Specifying Mapping Offsets","anchor":"Specifying-Mapping-Offsets","identifiers":["doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping/viewportArrayIndexOffset"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint32_t","text":"uint32_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderTargetArrayIndexOffset"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},"op":"replace"},{"value":"renderTargetArrayIndexOffset","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping~1renderTargetArrayIndexOffset/title","op":"replace"},{"value":[{"text":"renderTargetArrayIndexOffset","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping~1renderTargetArrayIndexOffset/fragments","op":"replace"},{"value":"MTLVertexAmplificationViewMapping","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping/title","op":"replace"},{"value":[{"text":"MTLVertexAmplificationViewMapping","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MTLVertexAmplificationViewMapping"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping/navigatorTitle","op":"replace"},{"value":"setVertexAmplificationCount:viewMappings:","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setVertexAmplificationCount(_:viewMappings:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVertexAmplificationCount:viewMappings:"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setVertexAmplificationCount(_:viewMappings:)/fragments","op":"replace"},{"value":"viewportArrayIndexOffset","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping~1viewportArrayIndexOffset/title","op":"replace"},{"value":[{"text":"viewportArrayIndexOffset","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping~1viewportArrayIndexOffset/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}