{
  "abstract": [
    {
      "text": "Medium image quality, represented as a high quality lossy JPEG image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/medium"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCTImageQuality@XCTImageQualityMedium",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "medium"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTImageQualityMedium"
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "XCTAttachment.ImageQuality.medium"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "medium"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment": {
      "abstract": [
        {
          "text": "Data from a test method’s execution, such as a file, image, screenshot, data blob, or ZIP file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTAttachment"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTAttachment"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality": {
      "abstract": [
        {
          "text": "Compression quality options for image-based attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageQuality"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageQuality"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment.ImageQuality",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/imagequality"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/low": {
      "abstract": [
        {
          "text": "Low image quality, represented as a highly compressed lossy JPEG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTImageQualityLow"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment.ImageQuality.low",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/imagequality/low"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/medium": {
      "abstract": [
        {
          "text": "Medium image quality, represented as a high quality lossy JPEG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTImageQualityMedium"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment.ImageQuality.medium",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/imagequality/medium"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/original": {
      "abstract": [
        {
          "text": "Original image quality, represented as a lossless PNG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "original"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/original",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTImageQualityOriginal"
        }
      ],
      "role": "symbol",
      "title": "XCTAttachment.ImageQuality.original",
      "type": "topic",
      "url": "/documentation/xctest/xctattachment/imagequality/original"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Quality-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/original",
        "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/low"
      ],
      "title": "Quality Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTImageQualityMedium"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTImageQualityMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Quality-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/original",
                "doc://com.apple.xctest/documentation/XCTest/XCTAttachment/ImageQuality/low"
              ],
              "title": "Quality Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCTImageQualityMedium"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality~1medium/title",
          "value": "XCTImageQualityMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTImageQualityMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/title",
          "value": "XCTAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality/title",
          "value": "XCTImageQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTImageQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTImageQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality~1original/title",
          "value": "XCTImageQualityOriginal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality~1original/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTImageQualityOriginal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality~1low/title",
          "value": "XCTImageQualityLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTAttachment~1ImageQuality~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTImageQualityLow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctattachment/imagequality/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctattachment/imagequality/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
