{
  "abstract": [
    {
      "text": "The section allows users to page its content orthogonally one group at a time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSCollectionLayoutSectionOrthogonalScrollingBehavior@NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "groupPaging"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.groupPaging"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "groupPaging"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior": {
      "abstract": [
        {
          "text": "The scrolling behavior of the layout’s sections in relation to the main layout axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuous": {
      "abstract": [
        {
          "text": "The section allows users to scroll its content orthogonally with continuous scrolling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuous"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.continuous",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/continuous"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary": {
      "abstract": [
        {
          "text": "The section allows users to scroll its content orthogonally, coming to a natural stop at the leading boundary of the visible group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuousGroupLeadingBoundary"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.continuousGroupLeadingBoundary",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/continuousgroupleadingboundary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally one group at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupPaging"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.groupPaging",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/grouppaging"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally one group at a time, centering each group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupPagingCentered"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.groupPagingCentered",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/grouppagingcentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none": {
      "abstract": [
        {
          "text": "The section does not allow users to scroll its content orthogonally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorNone"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.none",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/paging": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paging"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/paging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.paging",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/paging"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/paging",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/paging",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1groupPaging/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1groupPaging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1paging/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1paging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1none/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1continuous/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1continuous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1continuousGroupLeadingBoundary/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1continuousGroupLeadingBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1groupPagingCentered/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1groupPagingCentered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/grouppaging"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/grouppaging"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
