{
  "abstract": [
    {
      "text": "Describes an event that occurs during a sync operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "s:8CloudKit12CKSyncEngineC5EventO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Event"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Event"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CKSyncEngine.Event"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Event"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You don’t create instances of this type manually. Instead, the sync engine provides them to your app’s delegate during sync operations.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5": {
      "abstract": [
        {
          "text": "An object that manages the synchronization of local and remote record data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEngine"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngine"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event": {
      "abstract": [
        {
          "text": "Describes an event that occurs during a sync operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/AccountChange": {
      "abstract": [
        {
          "text": "A type that provides information about a change to the device’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccountChange"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/AccountChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccountChange"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.AccountChange",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/accountchange"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidFetchChanges": {
      "abstract": [
        {
          "text": "A type that provides information about a finished database fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DidFetchChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidFetchChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DidFetchChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.DidFetchChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/didfetchchanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidFetchRecordZoneChanges": {
      "abstract": [
        {
          "text": "A type that provides information about a finished record zone fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DidFetchRecordZoneChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidFetchRecordZoneChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DidFetchRecordZoneChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.DidFetchRecordZoneChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/didfetchrecordzonechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidSendChanges": {
      "abstract": [
        {
          "text": "A type that provides information about a finished send operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DidSendChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidSendChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DidSendChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.DidSendChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/didsendchanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/FetchedDatabaseChanges": {
      "abstract": [
        {
          "text": "A type that provides information about fetched database changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FetchedDatabaseChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/FetchedDatabaseChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FetchedDatabaseChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.FetchedDatabaseChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/fetcheddatabasechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/FetchedRecordZoneChanges": {
      "abstract": [
        {
          "text": "A type that provides information about fetched record zone changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FetchedRecordZoneChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/FetchedRecordZoneChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FetchedRecordZoneChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.FetchedRecordZoneChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/fetchedrecordzonechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/SentDatabaseChanges": {
      "abstract": [
        {
          "text": "A type that provides information about a sent batch of database changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SentDatabaseChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/SentDatabaseChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SentDatabaseChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.SentDatabaseChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/sentdatabasechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/SentRecordZoneChanges": {
      "abstract": [
        {
          "text": "A type that provides information about a sent batch of record zone changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SentRecordZoneChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/SentRecordZoneChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SentRecordZoneChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.SentRecordZoneChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/sentrecordzonechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/StateUpdate": {
      "abstract": [
        {
          "text": "A type that provides information about an update to the sync engine’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StateUpdate"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/StateUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StateUpdate"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.StateUpdate",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/stateupdate"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillFetchChanges": {
      "abstract": [
        {
          "text": "A type that provides information about an imminent database fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WillFetchChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillFetchChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WillFetchChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.WillFetchChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/willfetchchanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillFetchRecordZoneChanges": {
      "abstract": [
        {
          "text": "A type that provides information about an imminent fetch of changes in a record zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WillFetchRecordZoneChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillFetchRecordZoneChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WillFetchRecordZoneChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.WillFetchRecordZoneChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/willfetchrecordzonechanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillSendChanges": {
      "abstract": [
        {
          "text": "A type that provides information about an imminent send of local changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WillSendChanges"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillSendChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WillSendChanges"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.Event.WillSendChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/willsendchanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/accountChange(_:)": {
      "abstract": [
        {
          "text": "An event indicating a change to the device’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO13AccountChangeV",
          "text": "AccountChange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/accountChange(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.accountChange(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/accountchange(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didFetchChanges(_:)": {
      "abstract": [
        {
          "text": "An event that indicates the database fetch is done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFetchChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO15DidFetchChangesV",
          "text": "DidFetchChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didFetchChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.didFetchChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/didfetchchanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didFetchRecordZoneChanges(_:)": {
      "abstract": [
        {
          "text": "An event that indicates the record zone fetch is done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFetchRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO25DidFetchRecordZoneChangesV",
          "text": "DidFetchRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didFetchRecordZoneChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.didFetchRecordZoneChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/didfetchrecordzonechanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didSendChanges(_:)": {
      "abstract": [
        {
          "text": "An event that indicates a finished send operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didSendChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO14DidSendChangesV",
          "text": "DidSendChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didSendChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.didSendChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/didsendchanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/fetchedDatabaseChanges(_:)": {
      "abstract": [
        {
          "text": "An event indicating there are fetched database changes to process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchedDatabaseChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO22FetchedDatabaseChangesV",
          "text": "FetchedDatabaseChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/fetchedDatabaseChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.fetchedDatabaseChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/fetcheddatabasechanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/fetchedRecordZoneChanges(_:)": {
      "abstract": [
        {
          "text": "An event indicating there are fetched record zone changes to process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchedRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO24FetchedRecordZoneChangesV",
          "text": "FetchedRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/fetchedRecordZoneChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.fetchedRecordZoneChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/fetchedrecordzonechanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/sentDatabaseChanges(_:)": {
      "abstract": [
        {
          "text": "An event indicating a sent batch of database changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentDatabaseChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO19SentDatabaseChangesV",
          "text": "SentDatabaseChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/sentDatabaseChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.sentDatabaseChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/sentdatabasechanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/sentRecordZoneChanges(_:)": {
      "abstract": [
        {
          "text": "An event indicating a sent batch of record zone changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO21SentRecordZoneChangesV",
          "text": "SentRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/sentRecordZoneChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.sentRecordZoneChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/sentrecordzonechanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/stateUpdate(_:)": {
      "abstract": [
        {
          "text": "An event indicating an update to the sync engine’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO11StateUpdateV",
          "text": "StateUpdate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/stateUpdate(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.stateUpdate(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/stateupdate(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willFetchChanges(_:)": {
      "abstract": [
        {
          "text": "An event indicating an imminent database fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willFetchChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO16WillFetchChangesV",
          "text": "WillFetchChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willFetchChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.willFetchChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/willfetchchanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willFetchRecordZoneChanges(_:)": {
      "abstract": [
        {
          "text": "An event indicating an imminent fetch of changes in a record zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willFetchRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO26WillFetchRecordZoneChangesV",
          "text": "WillFetchRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willFetchRecordZoneChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.willFetchRecordZoneChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/willfetchrecordzonechanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willSendChanges(_:)": {
      "abstract": [
        {
          "text": "An event indicating an imminent send of local changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willSendChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO15WillSendChangesV",
          "text": "WillSendChanges"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willSendChanges(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.Event.willSendChanges(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/event/willsendchanges(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineDelegate-1q7g8/handleEvent(_:syncEngine:)": {
      "abstract": [
        {
          "text": "Tells the delegate to handle the specified sync event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC5EventO",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "syncEngine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineDelegate-1q7g8/handleEvent(_:syncEngine:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "handleEvent(_:syncEngine:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginedelegate-1q7g8/handleevent(_:syncengine:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType": {
      "abstract": [
        {
          "text": "Describes an event that occurs during a sync operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineEventType"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineEventType",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineeventtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-sync-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineDelegate-1q7g8/handleEvent(_:syncEngine:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineEventType"
      ],
      "title": "Handling sync events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Account-changes",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/accountChange(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/AccountChange"
      ],
      "title": "Account changes"
    },
    {
      "anchor": "Remote-database-changes",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willFetchChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillFetchChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/fetchedDatabaseChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/FetchedDatabaseChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didFetchChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidFetchChanges"
      ],
      "title": "Remote database changes"
    },
    {
      "anchor": "Remote-record-zone-changes",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willFetchRecordZoneChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillFetchRecordZoneChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/fetchedRecordZoneChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/FetchedRecordZoneChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didFetchRecordZoneChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidFetchRecordZoneChanges"
      ],
      "title": "Remote record zone changes"
    },
    {
      "anchor": "Pending-local-changes",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/willSendChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/WillSendChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/sentDatabaseChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/SentDatabaseChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/sentRecordZoneChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/SentRecordZoneChanges",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/didSendChanges(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/DidSendChanges"
      ],
      "title": "Pending local changes"
    },
    {
      "anchor": "State-updates",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/stateUpdate(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/Event/StateUpdate"
      ],
      "title": "State updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType/title",
          "value": "CKSyncEngineEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineEventType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksyncengine-5sie5/event"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
