{
  "abstract": [
    {
      "text": "Describes an unsent database modification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "s:8CloudKit12CKSyncEngineC21PendingDatabaseChangeO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PendingDatabaseChange"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PendingDatabaseChange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CKSyncEngine.PendingDatabaseChange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PendingDatabaseChange"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5": {
      "abstract": [
        {
          "text": "An object that manages the synchronization of local and remote record data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEngine"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngine"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange": {
      "abstract": [
        {
          "text": "Describes an unsent database modification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PendingDatabaseChange"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PendingDatabaseChange"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.PendingDatabaseChange",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/pendingdatabasechange"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange/deleteZone(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteZone"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordZone",
          "text": "CKRecordZone"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordZoneID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange/deleteZone(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.PendingDatabaseChange.deleteZone(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/pendingdatabasechange/deletezone(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange/saveZone(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveZone"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordZone",
          "text": "CKRecordZone"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange/saveZone(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngine.PendingDatabaseChange.saveZone(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/pendingdatabasechange/savezone(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingRecordZoneChange": {
      "abstract": [
        {
          "text": "Describes an unsent record modification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PendingRecordZoneChange"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingRecordZoneChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PendingRecordZoneChange"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.PendingRecordZoneChange",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/pendingrecordzonechange"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/add(pendingDatabaseChanges:)": {
      "abstract": [
        {
          "text": "Adds the specified database changes to the state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "pendingDatabaseChanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC21PendingDatabaseChangeO",
          "text": "PendingDatabaseChange"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/add(pendingDatabaseChanges:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "add(pendingDatabaseChanges:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/state-swift.class/add(pendingdatabasechanges:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/add(pendingRecordZoneChanges:)": {
      "abstract": [
        {
          "text": "Adds the specified record zone changes to the state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "pendingRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC23PendingRecordZoneChangeO",
          "text": "PendingRecordZoneChange"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/add(pendingRecordZoneChanges:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "add(pendingRecordZoneChanges:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/state-swift.class/add(pendingrecordzonechanges:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/remove(pendingDatabaseChanges:)": {
      "abstract": [
        {
          "text": "Removes the specified database changes from the state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "pendingDatabaseChanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC21PendingDatabaseChangeO",
          "text": "PendingDatabaseChange"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/remove(pendingDatabaseChanges:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "remove(pendingDatabaseChanges:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/state-swift.class/remove(pendingdatabasechanges:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/remove(pendingRecordZoneChanges:)": {
      "abstract": [
        {
          "text": "Removes the specified record zone changes from the state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "pendingRecordZoneChanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC23PendingRecordZoneChangeO",
          "text": "PendingRecordZoneChange"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/remove(pendingRecordZoneChanges:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "remove(pendingRecordZoneChanges:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/state-swift.class/remove(pendingrecordzonechanges:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChangeType": {
      "abstract": [
        {
          "text": "Describes the type of a pending database change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEnginePendingDatabaseChangeType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChangeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEnginePendingDatabaseChangeType"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEnginePendingDatabaseChangeType",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginependingdatabasechangetype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Manipulating-pending-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/add(pendingDatabaseChanges:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/remove(pendingDatabaseChanges:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/add(pendingRecordZoneChanges:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/State-swift.class/remove(pendingRecordZoneChanges:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingRecordZoneChange"
      ],
      "title": "Manipulating pending changes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Database-change-types",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChangeType"
      ],
      "title": "Database change types"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange/deleteZone(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/PendingDatabaseChange/saveZone(_:)"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEnginePendingDatabaseChangeType/title",
          "value": "CKSyncEnginePendingDatabaseChangeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEnginePendingDatabaseChangeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEnginePendingDatabaseChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEnginePendingDatabaseChangeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEnginePendingDatabaseChangeType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksyncengine-5sie5/pendingdatabasechange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
