{
  "abstract": [
    {
      "text": "Read series data from condensed workouts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Accessing condensed workout samples"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To reduce the size of workout data, HealthKit can condense samples associated with workouts created on Apple Watch. HealthKit enumerates the data associated with a workout and adds that data to one or more quantity series samples. After saving all the data to series objects, HealthKit deletes the originals. In addition, it converts older ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCumulativeQuantitySample",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "HealthKit only condenses high-frequency data recorded by the Workout app on Apple Watch. This includes the following data types:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceWalkingRunning",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceCycling",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/basalEnergyBurned",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/activeEnergyBurned",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRate",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For these data types, HealthKit condenses samples that are more than 90 days old and associated with a workout that’s at least 5 minutes long.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "HealthKit may condense samples for a given workout more than once. For example, if the system syncs new samples associated with the workout to the device, or if the condenser algorithm changes, HealthKit may condense the workout again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "HealthKit also batches the data into multiple quantity series to optimize how the system lays out the data in memory. For many data types, HealthKit creates a separate quantity series for each 5-minute interval in the workout. The condensation process preserves all the data from the original workout — but it greatly reduces the overhead needed to save that data to disk. However, your app may need to perform additional steps to read the condensed data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Query-high-frequency-data-from-a-condensed-workout",
          "level": 3,
          "text": "Query high-frequency data from a condensed workout",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Because HealthKit condenses older workout data, any samples associated with a workout may actually represent a series of higher-frequency data. In many cases, you can just use these samples, without having to access the underlying data. For example, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " transparently operate on the underlying data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "However, if your app needs to access the underlying data directly, start by querying for all the samples associated with a workout:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create the workout predicate.",
            "let forWorkout = HKQuery.predicateForObjects(from: workout)",
            "",
            "// Create the heart-rate descriptor.",
            "let heartRateDescriptor = HKQueryDescriptor(sampleType: myHeartRateType,",
            "                                            predicate: forWorkout)",
            "",
            "// Create the query.",
            "let heartRateQuery = HKSampleQuery(queryDescriptors: [heartRateDescriptor],",
            "                                   limit: HKObjectQueryNoLimit)",
            "{ query, samples, error in",
            "    // Process the samples.",
            "}",
            "",
            "// Run  the query.",
            "myStore.execute(heartRateQuery)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then, in the query’s results handler, if a sample has a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample/count",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " greater than 1, it contains series data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create the query.",
            "let heartRateQuery = HKSampleQuery(queryDescriptors: [heartRateDescriptor],",
            "                                   limit: HKObjectQueryNoLimit)",
            "{ query, samples, error in",
            "",
            "    // Start by checking for errors.",
            "    guard let samples = samples else {",
            "        // Handle the error.",
            "        fatalError(\"*** An error occurred: \\(error!.localizedDescription) ***\")",
            "    }",
            "    ",
            "    // Iterate over all the samples.",
            "    for sample in samples {",
            "        ",
            "        guard let sample = sample as? HKDiscreteQuantitySample else {",
            "            fatalError(\"*** Unexpected Sample Type ***\")",
            "        }",
            "        ",
            "        // Check to see if the sample is a series.",
            "        if sample.count == 1 {",
            "            // This is a single sample.",
            "            // Use the sample.",
            "            myOutput.append(\"\\(sample)\\n\")",
            "        }",
            "        else {",
            "            // This is a series.",
            "            // Get the detailed items for the series.",
            "            myGetDetailedItems(for: sample)",
            "        }",
            "    }",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to access the detailed data from the series.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create the predicate.",
            "let inSeriesSample = HKQuery.predicateForObject(with: series.uuid)",
            "",
            "// Create the query.",
            "let detailQuery = HKQuantitySeriesSampleQuery(quantityType: myHeartRateType,",
            "                                              predicate: inSeriesSample)",
            "{ query, quantity, dateInterval, HKSample, done, error in",
            "    ",
            "    guard let quantity = quantity, let dateInterval = dateInterval else {",
            "        fatalError(\"*** An error occurred: \\(error!.localizedDescription) ***\")",
            "    }",
            "    ",
            "    // Use the data.",
            "    myOutput.append(\"\\(quantity.doubleValue(for: HKUnit(from: \"count/min\"))): \\(dateInterval)\")",
            "}",
            "",
            "// Run the query.",
            "myStore.execute(detailQuery)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCumulativeQuantitySample": {
      "abstract": [
        {
          "text": "A sample that represents a cumulative quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCumulativeQuantitySample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCumulativeQuantitySample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCumulativeQuantitySample"
        }
      ],
      "role": "symbol",
      "title": "HKCumulativeQuantitySample",
      "type": "topic",
      "url": "/documentation/healthkit/hkcumulativequantitysample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample": {
      "abstract": [
        {
          "text": "A sample that represents a discrete quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDiscreteQuantitySample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDiscreteQuantitySample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDiscreteQuantitySample"
        }
      ],
      "role": "symbol",
      "title": "HKDiscreteQuantitySample",
      "type": "topic",
      "url": "/documentation/healthkit/hkdiscretequantitysample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample": {
      "abstract": [
        {
          "text": "A sample that represents a quantity, including the value and the units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantitySample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantitySample"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySample",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitysample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample/count": {
      "abstract": [
        {
          "text": "The number of quantities contained in this sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitysample/count"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQuery": {
      "abstract": [
        {
          "text": "A query that accesses the series data associated with a quantity sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantitySeriesSampleQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantitySeriesSampleQuery"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySeriesSampleQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityseriessamplequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/activeEnergyBurned": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of active energy the user has burned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeEnergyBurned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/activeEnergyBurned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierActiveEnergyBurned"
        }
      ],
      "role": "symbol",
      "title": "activeEnergyBurned",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/activeenergyburned"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/basalEnergyBurned": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the resting energy burned by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "basalEnergyBurned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/basalEnergyBurned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierBasalEnergyBurned"
        }
      ],
      "role": "symbol",
      "title": "basalEnergyBurned",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/basalenergyburned"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceCycling": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the distance the user has moved by cycling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceCycling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceCycling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistanceCycling"
        }
      ],
      "role": "symbol",
      "title": "distanceCycling",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distancecycling"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceWalkingRunning": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the distance the user has moved by walking or running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceWalkingRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceWalkingRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistanceWalkingRunning"
        }
      ],
      "role": "symbol",
      "title": "distanceWalkingRunning",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distancewalkingrunning"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRate": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the user’s heart rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heartRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/heartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierHeartRate"
        }
      ],
      "role": "symbol",
      "title": "heartRate",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/heartrate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQuery": {
      "abstract": [
        {
          "text": "A query that performs multiple statistics queries over a series of fixed-length time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQuery"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsCollectionQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQuery": {
      "abstract": [
        {
          "text": "A query that performs statistical calculations over a set of matching quantity samples, and returns the results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsQuery"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticsquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout": {
      "abstract": [
        {
          "text": "A workout sample that stores information about a single physical activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "role": "symbol",
      "title": "HKWorkout",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity": {
      "abstract": [
        {
          "text": "An object that describes an activity within a longer workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivity"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivity",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder": {
      "abstract": [
        {
          "text": "A builder object that incrementally constructs a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutBuilder"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutBuilder"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutBuilder",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent": {
      "abstract": [
        {
          "text": "An object representing an important event during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEvent"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType": {
      "abstract": [
        {
          "text": "The type of session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType": {
      "abstract": [
        {
          "text": "A type that identifies samples that store information about a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier": {
      "abstract": [
        {
          "text": "The workout type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout": {
      "abstract": [
        {
          "text": "Create associated samples that add details to a workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout",
      "kind": "article",
      "role": "article",
      "title": "Adding samples to a workout",
      "type": "topic",
      "url": "/documentation/healthkit/adding-samples-to-a-workout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities": {
      "abstract": [
        {
          "text": "Partition multisport and interval workouts into activities that represent the different parts of the workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities",
      "kind": "article",
      "role": "article",
      "title": "Dividing a HealthKit workout into activities",
      "type": "topic",
      "url": "/documentation/healthkit/dividing-a-healthkit-workout-into-activities"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings": {
      "abstract": [
        {
          "text": "Manage workouts, workout sessions, and activity summaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workouts and activity rings",
      "type": "topic",
      "url": "/documentation/healthkit/workouts-and-activity-rings"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Samples",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout",
        "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent"
      ],
      "title": "Samples"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySeriesSampleQuery/title",
          "value": "HKQuantitySeriesSampleQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySeriesSampleQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySeriesSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySeriesSampleQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySeriesSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample/title",
          "value": "HKDiscreteQuantitySample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDiscreteQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDiscreteQuantitySample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDiscreteQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceCycling/title",
          "value": "HKQuantityTypeIdentifierDistanceCycling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceCycling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistanceCycling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/title",
          "value": "HKWorkoutSessionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceWalkingRunning/title",
          "value": "HKQuantityTypeIdentifierDistanceWalkingRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceWalkingRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistanceWalkingRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample~1count/title",
          "value": "count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1basalEnergyBurned/title",
          "value": "HKQuantityTypeIdentifierBasalEnergyBurned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1basalEnergyBurned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierBasalEnergyBurned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/title",
          "value": "HKWorkoutEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutTypeIdentifier/title",
          "value": "HKWorkoutTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/title",
          "value": "HKWorkoutActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1activeEnergyBurned/title",
          "value": "HKQuantityTypeIdentifierActiveEnergyBurned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1activeEnergyBurned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierActiveEnergyBurned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/title",
          "value": "HKWorkoutBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/title",
          "value": "HKQuantitySample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/title",
          "value": "HKWorkoutType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollectionQuery/title",
          "value": "HKStatisticsCollectionQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollectionQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsCollectionQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollectionQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsCollectionQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/title",
          "value": "HKWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCumulativeQuantitySample/title",
          "value": "HKCumulativeQuantitySample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCumulativeQuantitySample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCumulativeQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCumulativeQuantitySample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCumulativeQuantitySample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title",
          "value": "HKWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsQuery/title",
          "value": "HKStatisticsQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1heartRate/title",
          "value": "HKQuantityTypeIdentifierHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1heartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierHeartRate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
