{
  "abstract": [
    {
      "text": "Partition multisport and interval workouts into activities that represent the different parts of the workout.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Dividing a HealthKit workout into activities"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some workouts benefit from having the workout’s duration broken into a set of discrete activities. For example, a multisport event, like a triathlon, has separate swim, bike, and run portions. Similarly, you can divide interval training into active and rest periods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4083470",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To model these activities in HealthKit, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to specify the different parts of a workout. You can then query for workouts that have matching activities, and analyze those activities independently from the rest of the workout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances have two main use cases:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "For workouts with an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/swimBikeRun",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " activity type, you can use ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instances to represent the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/swimming",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cycling",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " portions of the workout. You can also use activities to mark the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/transition",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " between these activities.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Multisport workouts",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instances to represent the active portions of the workout. You can create an interval workout for any ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": "; however, all workout activities must use the same activity type as the containing workout. You can’t mix activities within a single workout.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Interval training",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "All ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects have at least one associated ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". If you don’t explicitly add an activity to a workout, HealthKit adds an activity that matches the workout’s activity type. This means you can use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkoutActivities(workoutActivityType:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to filter for all the workouts that track an activity type. For example, filtering for workout activities that use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " includes regular running workouts, running interval training, and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/swimBikeRun",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " workouts that include a running activity.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Mark-transitions",
          "level": 3,
          "text": "Mark transitions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Activities can’t overlap, but they also don’t need to cover the entire ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sample’s duration. You can leave the time between the active portions of the workout blank, or you can explicitly create workout activities for these intervals. For example, explicitly creating activities for the time between active portions of the workout helps you track statistics during those intervals.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For multisport workouts, you can explicitly mark the transitions between activities using an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/transition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type. For interval training, you can use the same activity type as the workout for the rest periods; however, you may want to add custom metadata to indicate whether the activity is an active or resting interval.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "How you choose to model the data depends on the needs of your app and the types of intervals you’re tracking. If you’re tracking a workout that alternates between a fast and a slow pace, using workout activities to explicitly track all intervals makes sense. If, however, the intervals alternate between exercising and resting (for example, during many high-intensity interval training exercises), you may want to leave the rest intervals blank.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-workout-activities-to-a-workout-session",
          "level": 3,
          "text": "Add workout activities to a workout session",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To add workout activities to a workout session, start by creating the session and start collecting data using the workout builder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create the workout configuration for a multisport workout.",
            "let configuration = HKWorkoutConfiguration()",
            "configuration.activityType = .swimBikeRun",
            "configuration.locationType = .outdoor",
            "",
            "// Create the workout session.",
            "session = try HKWorkoutSession(healthStore: store,",
            "                               configuration: configuration)",
            "",
            "// Start the session and the workout builder.",
            "let startDate = Date()",
            "session.startActivity(with: startDate)",
            "workoutBuilder = session.associatedWorkoutBuilder()",
            "",
            "// Set the workout builder's data source.",
            "workoutBuilder.dataSource =",
            "HKLiveWorkoutDataSource(healthStore: store,",
            "                        workoutConfiguration: configuration)",
            "",
            "// Start collecting data.",
            "try await workoutBuilder.beginCollection(at: startDate)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, when an activity begins, create a new configuration for the activity, and start the activity using the session’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/beginNewActivity(configuration:date:metadata:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. The data source automatically begins collecting the default data types for the activity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Start the swimming activity.",
            "let swimmingConfiguration = HKWorkoutConfiguration()",
            "swimmingConfiguration.activityType = .swimming",
            "swimmingConfiguration.locationType = .outdoor",
            "swimmingConfiguration.swimmingLocationType = .openWater",
            "",
            "session.beginNewActivity(configuration: swimmingConfiguration,",
            "                         date: Date(),",
            "                         metadata: nil)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the activity ends, call the session’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/endCurrentActivity(on:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. HealthKit also ends the current activity when you begin a new activity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// End the activity.",
            "session.endCurrentActivity(on: Date())"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To explicitly track the intervals between activities, start a new activity using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/transition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". End this transition when the next activity begins.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Explicitly track the transition between activities.",
            "let transitionConfiguration = HKWorkoutConfiguration()",
            "transitionConfiguration.activityType = .transition",
            "transitionConfiguration.locationType = .outdoor",
            "",
            "session.beginNewActivity(configuration: transitionConfiguration,",
            "                         date: Date(),",
            "                         metadata: nil)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, when the entire workout session ends, call the session’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/end()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. This also ends the current activity. Then call the workout builder’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/finishWorkout(completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to save the workout to the HealthKit store. This method also returns an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, which you can use to display summary information about the workout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Ending the session also ends the current activity.",
            "session.end()",
            "",
            "// Finishing the workout saves the workout",
            "// and returns an HKWorkout object that you can use to display summary data.",
            "let workout = try await workoutBuilder.finishWorkout()",
            "",
            "// Do something with the workout here.",
            "print(workout as Any)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Enable-and-disable-the-collection-of-data",
          "level": 3,
          "text": "Enable and disable the collection of data",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you start a new workout activity, your data source automatically begins collecting relevant data from Apple Watch. To see the data types that the data source collects, check the data source’s ",
              "type": "text"
            },
            {
              "code": "typesToCollect",
              "type": "codeVoice"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When running an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/swimBikeRun",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " workout session, HealthKit automatically changes the collected data types based on the current workout activity. For example, the data source collects data like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/activeEnergyBurned",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceSwimming",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/swimmingStrokeCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you start an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " activity, the system automatically updates the data source’s ",
              "type": "text"
            },
            {
              "code": "typesToCollect",
              "type": "codeVoice"
            },
            {
              "text": " property based on the new activity. For example, the data source automatically stops collecting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceSwimming",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/swimmingStrokeCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and starts collecting relevant data like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceWalkingRunning",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/runningStrideLength",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Most of the time, you can use the default collected data types. However, if your app calculates and saves its own ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSample",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects during the workout, you may want to manually enable and disable the collection of that data type, letting the data source automatically associate your samples with the workout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To start collecting a data type, call the data source’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource/enableCollection(for:predicate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Enable the collection of respiratory rate.",
            "guard let dataSource = session.associatedWorkoutBuilder().dataSource else {",
            "    print(\"*** No data source found! ***\")",
            "    return }",
            "",
            "let respiratoryRate = HKQuantityType(.respiratoryRate)",
            "dataSource.enableCollection(for: respiratoryRate, predicate: nil)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "HealthKit then associates any matching samples from your app with the workout activity. You can also disable the collection of a data type by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource/disableCollection(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Disable the collection of respiratory rate.",
            "guard let dataSource = session.associatedWorkoutBuilder().dataSource else {",
            "    print(\"*** No data source found! ***\")",
            "    return }",
            "",
            "let respiratoryRate = HKQuantityType(.respiratoryRate)",
            "dataSource.disableCollection(for: respiratoryRate)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Query-for-workout-activities",
          "level": 3,
          "text": "Query for workout activities",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To query for workouts with activities that match a specific predicate, start by creating a workout activity predicate using one of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class’s ",
              "type": "text"
            },
            {
              "code": "predicateForWorkoutActivities",
              "type": "codeVoice"
            },
            {
              "text": " methods. Next, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to wrap the activity predicate inside a workout predicate. You can then use the workout predicate in your query.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create a predicate for an average heart rate of greater than 150 bpm.",
            "let highHeartRate = HKQuantity(unit: .count(), doubleValue: 150.0)",
            "let heartRateType = HKQuantityType(.heartRate)",
            "",
            "let heartRatePredicate =",
            "HKQuery.predicateForWorkoutActivities(operatorType: .greaterThan,",
            "                                      quantityType: heartRateType,",
            "                                      averageQuantity: highHeartRate)",
            "",
            "// Wrap the workout activity predicate inside a workout predicate.",
            "let workoutPredicate = HKQuery.predicateForWorkouts(activityPredicate: heartRatePredicate)",
            "",
            "let query = HKSampleQueryDescriptor(predicates: [.workout(workoutPredicate)],",
            "                                    sortDescriptors: [])",
            "",
            "let matchingWorkouts = try await query.result(for: store)",
            "",
            "// Do something with the samples here.",
            "print(matchingWorkouts)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This example returns all the workouts that have an activity with an average heart rate over 150 bpm. Use the workout’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout/workoutActivities",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to access the activities associated with a workout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource/disableCollection(for:)": {
      "abstract": [
        {
          "text": "Stops automatically calculating statistics for the quantity type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantityType",
          "text": "HKQuantityType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource/disableCollection(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableCollectionForType:"
        }
      ],
      "role": "symbol",
      "title": "disableCollection(for:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkliveworkoutdatasource/disablecollection(for:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource/enableCollection(for:predicate:)": {
      "abstract": [
        {
          "text": "Begins automatically calculating statistics for samples that match the quantity type and predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantityType",
          "text": "HKQuantityType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource/enableCollection(for:predicate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableCollectionForType:predicate:"
        }
      ],
      "role": "symbol",
      "title": "enableCollection(for:predicate:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkliveworkoutdatasource/enablecollection(for:predicate:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/activeEnergyBurned": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the amount of active energy the user has burned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeEnergyBurned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/activeEnergyBurned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierActiveEnergyBurned"
        }
      ],
      "role": "symbol",
      "title": "activeEnergyBurned",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/activeenergyburned"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceSwimming": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the distance the user has moved while swimming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceSwimming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceSwimming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistanceSwimming"
        }
      ],
      "role": "symbol",
      "title": "distanceSwimming",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distanceswimming"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceWalkingRunning": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the distance the user has moved by walking or running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceWalkingRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceWalkingRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistanceWalkingRunning"
        }
      ],
      "role": "symbol",
      "title": "distanceWalkingRunning",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distancewalkingrunning"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/runningStrideLength": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the distance covered by a single step while running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runningStrideLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/runningStrideLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierRunningStrideLength"
        }
      ],
      "role": "symbol",
      "title": "runningStrideLength",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/runningstridelength"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/swimmingStrokeCount": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the number of strokes performed while swimming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swimmingStrokeCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/swimmingStrokeCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierSwimmingStrokeCount"
        }
      ],
      "role": "symbol",
      "title": "swimmingStrokeCount",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/swimmingstrokecount"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery": {
      "abstract": [
        {
          "text": "An abstract class for all the query classes in HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuery"
        }
      ],
      "role": "symbol",
      "title": "HKQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkoutActivities(workoutActivityType:)": {
      "abstract": [
        {
          "text": "Returns a predicate for workout activities based on the type of activity performed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForWorkoutActivities"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "workoutActivityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKWorkoutActivityType",
          "text": "HKWorkoutActivityType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkoutActivities(workoutActivityType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForWorkoutActivitiesWithWorkoutActivityType:"
        }
      ],
      "role": "symbol",
      "title": "predicateForWorkoutActivities(workoutActivityType:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery/predicateforworkoutactivities(workoutactivitytype:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)": {
      "abstract": [
        {
          "text": "Returns a predicate for matching workouts based on the associated workout activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForWorkouts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "activityPredicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForWorkoutsWithActivityPredicate:"
        }
      ],
      "role": "symbol",
      "title": "predicateForWorkouts(activityPredicate:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery/predicateforworkouts(activitypredicate:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSample": {
      "abstract": [
        {
          "text": "A HealthKit sample represents a piece of data associated with a start and end time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSample"
        }
      ],
      "role": "symbol",
      "title": "HKSample",
      "type": "topic",
      "url": "/documentation/healthkit/hksample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout": {
      "abstract": [
        {
          "text": "A workout sample that stores information about a single physical activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "role": "symbol",
      "title": "HKWorkout",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout/workoutActivities": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutActivities"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutActivity",
          "text": "HKWorkoutActivity"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout/workoutActivities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workoutActivities"
        }
      ],
      "role": "symbol",
      "title": "workoutActivities",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkout/workoutactivities"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity": {
      "abstract": [
        {
          "text": "An object that describes an activity within a longer workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivity"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivity",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cycling": {
      "abstract": [
        {
          "text": "The constant for cycling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cycling"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/cycling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeCycling"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.cycling",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/cycling"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running": {
      "abstract": [
        {
          "text": "The constant for running and jogging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeRunning"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.running",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/running"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/swimBikeRun": {
      "abstract": [
        {
          "text": "The constant for multisport activities like triathlons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swimBikeRun"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/swimBikeRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeSwimBikeRun"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.swimBikeRun",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/swimbikerun"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/swimming": {
      "abstract": [
        {
          "text": "The constant for swimming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swimming"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/swimming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeSwimming"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.swimming",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/swimming"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/transition": {
      "abstract": [
        {
          "text": "A constant for the transition time between activities in a multisport workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transition"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/transition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeTransition"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.transition",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/transition"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder": {
      "abstract": [
        {
          "text": "A builder object that incrementally constructs a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutBuilder"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutBuilder"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutBuilder",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/finishWorkout(completion:)": {
      "abstract": [
        {
          "text": "Creates the workout, using the samples and events added to the builder, and saves it to the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishWorkout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkout",
          "text": "HKWorkout"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/finishWorkout(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishWorkoutWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "finishWorkout(completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/finishworkout(completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent": {
      "abstract": [
        {
          "text": "An object representing an important event during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEvent"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/beginNewActivity(configuration:date:metadata:)": {
      "abstract": [
        {
          "text": "Begins a new workout activity in the workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginNewActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutConfiguration",
          "text": "HKWorkoutConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/beginNewActivity(configuration:date:metadata:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginNewActivityWithConfiguration:date:metadata:"
        }
      ],
      "role": "symbol",
      "title": "beginNewActivity(configuration:date:metadata:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsession/beginnewactivity(configuration:date:metadata:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/end()": {
      "abstract": [
        {
          "text": "Ends the workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/end()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "end"
        }
      ],
      "role": "symbol",
      "title": "end()",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsession/end()"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/endCurrentActivity(on:)": {
      "abstract": [
        {
          "text": "Ends the current workout activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endCurrentActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession/endCurrentActivity(on:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endCurrentActivityOnDate:"
        }
      ],
      "role": "symbol",
      "title": "endCurrentActivity(on:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsession/endcurrentactivity(on:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType": {
      "abstract": [
        {
          "text": "The type of session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType": {
      "abstract": [
        {
          "text": "A type that identifies samples that store information about a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier": {
      "abstract": [
        {
          "text": "The workout type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples": {
      "abstract": [
        {
          "text": "Read series data from condensed workouts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples",
      "kind": "article",
      "role": "article",
      "title": "Accessing condensed workout samples",
      "type": "topic",
      "url": "/documentation/healthkit/accessing-condensed-workout-samples"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout": {
      "abstract": [
        {
          "text": "Create associated samples that add details to a workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout",
      "kind": "article",
      "role": "article",
      "title": "Adding samples to a workout",
      "type": "topic",
      "url": "/documentation/healthkit/adding-samples-to-a-workout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings": {
      "abstract": [
        {
          "text": "Manage workouts, workout sessions, and activity summaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workouts and activity rings",
      "type": "topic",
      "url": "/documentation/healthkit/workouts-and-activity-rings"
    },
    "media-4083470": {
      "alt": "An illustration showing a .swimBikeRun workout and its corresponding .swimming, .biking, .running, and .transition activities. The activities fill the entire time covered by the workout, but none of the activities overlap.",
      "identifier": "media-4083470",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/74a2190228254300b6b8371b87c2ec31/media-4083470@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/48b931541c113cc565de5cc35c82f60a/media-4083470~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Samples",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout",
        "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent"
      ],
      "title": "Samples"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/title",
          "value": "HKSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceSwimming/title",
          "value": "HKQuantityTypeIdentifierDistanceSwimming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceSwimming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistanceSwimming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1swimming/title",
          "value": "HKWorkoutActivityTypeSwimming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1swimming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSwimming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/title",
          "value": "HKWorkoutActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/title",
          "value": "HKWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1end()/title",
          "value": "end"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1end()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "end"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title",
          "value": "HKWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(activityPredicate:)/title",
          "value": "predicateForWorkoutsWithActivityPredicate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(activityPredicate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForWorkoutsWithActivityPredicate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/title",
          "value": "HKWorkoutBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutDataSource~1disableCollection(for:)/title",
          "value": "disableCollectionForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutDataSource~1disableCollection(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "disableCollectionForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1swimBikeRun/title",
          "value": "HKWorkoutActivityTypeSwimBikeRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1swimBikeRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSwimBikeRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/title",
          "value": "HKWorkoutEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1transition/title",
          "value": "HKWorkoutActivityTypeTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1transition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutTypeIdentifier/title",
          "value": "HKWorkoutTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1activeEnergyBurned/title",
          "value": "HKQuantityTypeIdentifierActiveEnergyBurned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1activeEnergyBurned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierActiveEnergyBurned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkoutActivities(workoutActivityType:)/title",
          "value": "predicateForWorkoutActivitiesWithWorkoutActivityType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkoutActivities(workoutActivityType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForWorkoutActivitiesWithWorkoutActivityType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1beginNewActivity(configuration:date:metadata:)/title",
          "value": "beginNewActivityWithConfiguration:date:metadata:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1beginNewActivity(configuration:date:metadata:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginNewActivityWithConfiguration:date:metadata:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutDataSource~1enableCollection(for:predicate:)/title",
          "value": "enableCollectionForType:predicate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutDataSource~1enableCollection(for:predicate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enableCollectionForType:predicate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1runningStrideLength/title",
          "value": "HKQuantityTypeIdentifierRunningStrideLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1runningStrideLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierRunningStrideLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1endCurrentActivity(on:)/title",
          "value": "endCurrentActivityOnDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession~1endCurrentActivity(on:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endCurrentActivityOnDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceWalkingRunning/title",
          "value": "HKQuantityTypeIdentifierDistanceWalkingRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceWalkingRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistanceWalkingRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1swimmingStrokeCount/title",
          "value": "HKQuantityTypeIdentifierSwimmingStrokeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1swimmingStrokeCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierSwimmingStrokeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/title",
          "value": "HKWorkoutSessionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1running/title",
          "value": "HKWorkoutActivityTypeRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1finishWorkout(completion:)/title",
          "value": "finishWorkoutWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1finishWorkout(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishWorkoutWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout~1workoutActivities/title",
          "value": "workoutActivities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout~1workoutActivities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "workoutActivities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1cycling/title",
          "value": "HKWorkoutActivityTypeCycling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1cycling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeCycling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/title",
          "value": "HKWorkoutType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title",
          "value": "HKQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuery"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
