{
  "abstract": [
    {
      "text": "Create and run observer queries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/queries",
        "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/executing-observer-queries"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Executing Observer Queries"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Observer queries are long-running queries that monitor the HealthKit store on a background thread, and update your app when the HealthKit store saves or deletes a matching sample. By default, observer queries only return results while your app is in the foreground; however, you can configure your app to also receive update notifications in the background.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-Observer-Queries",
          "level": 3,
          "text": "Create Observer Queries",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To create an observer query, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery/init(sampleType:predicate:updateHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " initializer. Start by creating a type object for the samples you want to observe. The following example creates a type object for step counts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "guard let stepCountType = HKObjectType.quantityType(forIdentifier: .stepCount) else {",
            "    // This should never fail when using a defined constant.",
            "    fatalError(\"*** Unable to get the step count type ***\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, create the observer query.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let query = HKObserverQuery(sampleType: stepCountType, predicate: nil) { (query, completionHandler, errorOrNil) in",
            "    ",
            "    if let error = errorOrNil {",
            "        // Properly handle the error.",
            "        return",
            "    }",
            "        ",
            "    // Take whatever steps are necessary to update your app.",
            "    // This often involves executing other queries to access the new data.",
            "    ",
            "    // If you have subscribed for background updates you must call the completion handler here.",
            "    // completionHandler()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After the query is instantiated, call the HealthKit store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "store.execute(query)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This runs the query on an anonymous background queue. Whenever a matching sample is added to or deleted from the HealthKit store, the system calls the query’s update handler on the same background queue (but not necessarily the same thread).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The observer query’s update handler does not receive any information about the change—just that a change occurred. You must execute another query, for example an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", to access the changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To stop the query, call the HealthKit store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/stop(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Receive-Background-Deliveries",
          "level": 3,
          "text": "Receive Background Deliveries",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps can also register to receive updates while in the background by calling the HealthKit store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/enableBackgroundDelivery(for:frequency:withCompletion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. This method registers your app for background notifications. HealthKit wakes your app when the store receives new samples of the specified type. HealthKit notifies your app at most once per time period defined by the frequency you specified when registering.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As soon as your app launches, HealthKit calls the update handler for any observer queries that match the newly saved data. If you plan on supporting background delivery, set up all your observer queries in your app delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. By setting up the queries in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you ensure that the queries are instantiated and ready to use before HealthKit delivers the updates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After your observer queries have finished processing the new data, you must call the update’s completion handler to notify HealthKit that you have successfully received the background delivery.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Background server queries aren’t supported on the Simulator. Be sure to test your background queries on a device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on managing background deliveries, see Managing Background Deliveries in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information on the background delivery completion handler, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQueryCompletionHandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process is almost done and the app is almost ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishLaunchingWithOptions"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationLaunchOptionsKey",
          "text": "LaunchOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]? = nil) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:didFinishLaunchingWithOptions:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery": {
      "abstract": [
        {
          "text": "A query that returns changes to the HealthKit store, including a snapshot of new changes and continuous monitoring as a long-running query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQuery"
        }
      ],
      "role": "symbol",
      "title": "HKAnchoredObjectQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkanchoredobjectquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore": {
      "abstract": [
        {
          "text": "The access point for all data managed by HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "role": "symbol",
      "title": "HKHealthStore",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/enableBackgroundDelivery(for:frequency:withCompletion:)": {
      "abstract": [
        {
          "text": "Enables the delivery of updates to an app running in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableBackgroundDelivery"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKObjectType",
          "text": "HKObjectType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKUpdateFrequency",
          "text": "HKUpdateFrequency"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCompletion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/enableBackgroundDelivery(for:frequency:withCompletion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableBackgroundDeliveryForType:frequency:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "enableBackgroundDelivery(for:frequency:withCompletion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/enablebackgrounddelivery(for:frequency:withcompletion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)": {
      "abstract": [
        {
          "text": "Starts executing the provided query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuery",
          "text": "HKQuery"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executeQuery:"
        }
      ],
      "role": "symbol",
      "title": "execute(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/execute(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/stop(_:)": {
      "abstract": [
        {
          "text": "Stops a long-running query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuery",
          "text": "HKQuery"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/stop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopQuery:"
        }
      ],
      "role": "symbol",
      "title": "stop(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/stop(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery": {
      "abstract": [
        {
          "text": "A long-running query that monitors the HealthKit store and updates your app when the HealthKit store saves or deletes a matching sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKObserverQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKObserverQuery"
        }
      ],
      "role": "symbol",
      "title": "HKObserverQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkobserverquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery/init(queryDescriptors:updateHandler:)": {
      "abstract": [
        {
          "text": "Creates a query that monitors the HealthKit store and responds to any changes matching any of the query descriptors you provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "queryDescriptors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQueryDescriptor",
          "text": "HKQueryDescriptor"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "updateHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKObserverQuery",
          "text": "HKObserverQuery"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSampleType",
          "text": "HKSampleType"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKObserverQueryCompletionHandler",
          "text": "HKObserverQueryCompletionHandler"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery/init(queryDescriptors:updateHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithQueryDescriptors:updateHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(queryDescriptors:updateHandler:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkobserverquery/init(querydescriptors:updatehandler:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery/init(sampleType:predicate:updateHandler:)": {
      "abstract": [
        {
          "text": "Instantiates and returns a query that monitors the HealthKit store and responds to changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sampleType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSampleType",
          "text": "HKSampleType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "updateHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKObserverQuery",
          "text": "HKObserverQuery"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKObserverQueryCompletionHandler",
          "text": "HKObserverQueryCompletionHandler"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery/init(sampleType:predicate:updateHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSampleType:predicate:updateHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(sampleType:predicate:updateHandler:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkobserverquery/init(sampletype:predicate:updatehandler:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQueryCompletionHandler": {
      "abstract": [
        {
          "text": "The completion handler for background deliveries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKObserverQueryCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQueryCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKObserverQueryCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "HKObserverQueryCompletionHandler",
      "type": "topic",
      "url": "/documentation/healthkit/hkobserverquerycompletionhandler"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery": {
      "abstract": [
        {
          "text": "A general query that returns a snapshot of all the matching samples currently saved in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSampleQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSampleQuery"
        }
      ],
      "role": "symbol",
      "title": "HKSampleQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/queries": {
      "abstract": [
        {
          "text": "Query health and fitness data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/queries",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Queries",
      "type": "topic",
      "url": "/documentation/healthkit/queries"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Observer-Queries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery/init(sampleType:predicate:updateHandler:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery/init(queryDescriptors:updateHandler:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQueryCompletionHandler"
      ],
      "title": "Creating Observer Queries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1stop(_:)/title",
          "value": "stopQuery:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1stop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopQuery:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1execute(_:)/title",
          "value": "executeQuery:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1execute(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "executeQuery:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/title",
          "value": "application:didFinishLaunchingWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didFinishLaunchingWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "launchOptions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/title",
          "value": "HKSampleQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1enableBackgroundDelivery(for:frequency:withCompletion:)/title",
          "value": "enableBackgroundDeliveryForType:frequency:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1enableBackgroundDelivery(for:frequency:withCompletion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enableBackgroundDeliveryForType:frequency:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery~1init(queryDescriptors:updateHandler:)/title",
          "value": "initWithQueryDescriptors:updateHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery~1init(queryDescriptors:updateHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithQueryDescriptors:updateHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/title",
          "value": "HKHealthStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery/title",
          "value": "HKObserverQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKObserverQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKObserverQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/title",
          "value": "HKAnchoredObjectQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAnchoredObjectQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAnchoredObjectQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery~1init(sampleType:predicate:updateHandler:)/title",
          "value": "initWithSampleType:predicate:updateHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery~1init(sampleType:predicate:updateHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSampleType:predicate:updateHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQueryCompletionHandler/title",
          "value": "HKObserverQueryCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQueryCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKObserverQueryCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQueryCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKObserverQueryCompletionHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
