{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "HealthKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramConductionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramConductionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramConductionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramConductionType"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramConductionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramconductiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTestSide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityTestSide"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTestSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityTestSide"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramSensitivityTestSide",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramsensitivitytestside"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex": {
      "abstract": [
        {
          "text": "Constants indicating the user’s sex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBiologicalSex"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBiologicalSex"
        }
      ],
      "role": "symbol",
      "title": "HKBiologicalSex",
      "type": "topic",
      "url": "/documentation/healthkit/hkbiologicalsex"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType": {
      "abstract": [
        {
          "text": "Constants indicating the user’s blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueVaginalBleeding"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueVaginalBleeding"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueVaginalBleeding",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluevaginalbleeding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType": {
      "abstract": [
        {
          "text": "Categories representing the user’s skin type based on the Fitzpatrick scale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Answer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Answer"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Answer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Answer"
        }
      ],
      "role": "symbol",
      "title": "HKGAD7Assessment.Answer",
      "type": "topic",
      "url": "/documentation/healthkit/hkgad7assessment/answer"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Risk-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Risk"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Risk-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Risk"
        }
      ],
      "role": "symbol",
      "title": "HKGAD7Assessment.Risk",
      "type": "topic",
      "url": "/documentation/healthkit/hkgad7assessment/risk-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMCPregnancyDatesConstants": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMCPregnancyDatesConstants"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMCPregnancyDatesConstants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMCPregnancyDatesConstants"
        }
      ],
      "role": "symbol",
      "title": "HKMCPregnancyDatesConstants",
      "type": "topic",
      "url": "/documentation/healthkit/hkmcpregnancydatesconstants"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Answer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Answer"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Answer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Answer"
        }
      ],
      "role": "symbol",
      "title": "HKPHQ9Assessment.Answer",
      "type": "topic",
      "url": "/documentation/healthkit/hkphq9assessment/answer"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Risk-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Risk"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Risk-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Risk"
        }
      ],
      "role": "symbol",
      "title": "HKPHQ9Assessment.Risk",
      "type": "topic",
      "url": "/documentation/healthkit/hkphq9assessment/risk-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Association"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Association"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Kind-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Kind"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Kind-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Kind"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Kind",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/kind-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Label": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Label"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Label"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Label",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/label"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/ValenceClassification-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ValenceClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/ValenceClassification-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ValenceClassification"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.ValenceClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/valenceclassification-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUse": {
      "abstract": [
        {
          "text": "Constants indicating the user’s wheelchair use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWheelchairUse"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWheelchairUse"
        }
      ],
      "role": "symbol",
      "title": "HKWheelchairUse",
      "type": "topic",
      "url": "/documentation/healthkit/hkwheelchairuse"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQueryOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQueryOptions"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQueryOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQueryOptions"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEffortRelationshipQueryOptions",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteffortrelationshipqueryoptions"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-macros"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Classes",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-classes"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Constants",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-constants"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Data Types",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-data-types"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Functions",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-functions"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Variables",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
        "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramConductionType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTestSide",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Answer",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Risk-swift.enum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Answer",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Risk-swift.enum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Kind-swift.enum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Label",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/ValenceClassification-swift.enum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQueryOptions",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUse",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMCPregnancyDatesConstants"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1ValenceClassification-swift.enum/title",
          "value": "HKStateOfMindValenceClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1ValenceClassification-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindValenceClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1ValenceClassification-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindValenceClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association/title",
          "value": "HKStateOfMindAssociation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/title",
          "value": "HKCategoryValueVaginalBleeding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueVaginalBleeding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueVaginalBleeding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUse/title",
          "value": "HKWheelchairUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Answer/title",
          "value": "HKGAD7AssessmentAnswer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Answer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7AssessmentAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Answer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7AssessmentAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Answer/title",
          "value": "HKPHQ9AssessmentAnswer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Answer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9AssessmentAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Answer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9AssessmentAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Label/title",
          "value": "HKStateOfMindLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Label/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramConductionType/title",
          "value": "HKAudiogramConductionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramConductionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramConductionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramConductionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramConductionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTestSide/title",
          "value": "HKAudiogramSensitivityTestSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTestSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityTestSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTestSide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityTestSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/title",
          "value": "HKFitzpatrickSkinType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQueryOptions/title",
          "value": "HKWorkoutEffortRelationshipQueryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQueryOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQueryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQueryOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQueryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Kind-swift.enum/title",
          "value": "HKStateOfMindKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Kind-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Kind-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/title",
          "value": "HKBiologicalSex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/title",
          "value": "HKBloodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Risk-swift.enum/title",
          "value": "HKGAD7AssessmentRisk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Risk-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7AssessmentRisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Risk-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7AssessmentRisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Risk-swift.enum/title",
          "value": "HKPHQ9AssessmentRisk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Risk-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9AssessmentRisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Risk-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9AssessmentRisk"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
