{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "HealthKit Variables"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/bleedingAfterPregnancy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bleedingAfterPregnancy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/bleedingAfterPregnancy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierBleedingAfterPregnancy"
        }
      ],
      "role": "symbol",
      "title": "bleedingAfterPregnancy",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/bleedingafterpregnancy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/bleedingDuringPregnancy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bleedingDuringPregnancy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/bleedingDuringPregnancy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierBleedingDuringPregnancy"
        }
      ],
      "role": "symbol",
      "title": "bleedingDuringPregnancy",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/bleedingduringpregnancy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepApneaEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepApneaEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepApneaEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierSleepApneaEvent"
        }
      ],
      "role": "symbol",
      "title": "sleepApneaEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/sleepapneaevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevice/localIdentifier": {
      "abstract": [
        {
          "text": "An identifier that uniquely identifies the device object on the hardware running this code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevice/localIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localIdentifier"
        }
      ],
      "role": "symbol",
      "title": "localIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevice/localidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyFirmwareVersion": {
      "abstract": [
        {
          "text": "The device’s firmware version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyFirmwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyFirmwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyFirmwareVersion"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePropertyKeyFirmwareVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevicepropertykeyfirmwareversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyHardwareVersion": {
      "abstract": [
        {
          "text": "The device’s hardware version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyHardwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyHardwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyHardwareVersion"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePropertyKeyHardwareVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevicepropertykeyhardwareversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyLocalIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for the device on the hardware running the app. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevice/localIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyLocalIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyLocalIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyLocalIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePropertyKeyLocalIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevicepropertykeylocalidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyManufacturer": {
      "abstract": [
        {
          "text": "The device’s manufacturer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyManufacturer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyManufacturer"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePropertyKeyManufacturer",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevicepropertykeymanufacturer"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyModel": {
      "abstract": [
        {
          "text": "The device’s model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyModel"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePropertyKeyModel",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevicepropertykeymodel"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyName": {
      "abstract": [
        {
          "text": "The device’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyName"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePropertyKeyName",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevicepropertykeyname"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeySoftwareVersion": {
      "abstract": [
        {
          "text": "The device’s software version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeySoftwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeySoftwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeySoftwareVersion"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePropertyKeySoftwareVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevicepropertykeysoftwareversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyUDIDeviceIdentifier": {
      "abstract": [
        {
          "text": "The device’s UDI Device Identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyUDIDeviceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyUDIDeviceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePropertyKeyUDIDeviceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePropertyKeyUDIDeviceIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevicepropertykeyudideviceidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCount": {
      "abstract": [
        {
          "text": "A key path for the sample’s count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathCount"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathCount",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathcount"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/appleSleepingBreathingDisturbances": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleSleepingBreathingDisturbances"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/appleSleepingBreathingDisturbances",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances"
        }
      ],
      "role": "symbol",
      "title": "appleSleepingBreathingDisturbances",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/applesleepingbreathingdisturbances"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/crossCountrySkiingSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crossCountrySkiingSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/crossCountrySkiingSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierCrossCountrySkiingSpeed"
        }
      ],
      "role": "symbol",
      "title": "crossCountrySkiingSpeed",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/crosscountryskiingspeed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingCadence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cyclingCadence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingCadence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierCyclingCadence"
        }
      ],
      "role": "symbol",
      "title": "cyclingCadence",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/cyclingcadence"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingFunctionalThresholdPower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cyclingFunctionalThresholdPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingFunctionalThresholdPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower"
        }
      ],
      "role": "symbol",
      "title": "cyclingFunctionalThresholdPower",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/cyclingfunctionalthresholdpower"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingPower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cyclingPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierCyclingPower"
        }
      ],
      "role": "symbol",
      "title": "cyclingPower",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/cyclingpower"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cyclingSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierCyclingSpeed"
        }
      ],
      "role": "symbol",
      "title": "cyclingSpeed",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/cyclingspeed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceCrossCountrySkiing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceCrossCountrySkiing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceCrossCountrySkiing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistanceCrossCountrySkiing"
        }
      ],
      "role": "symbol",
      "title": "distanceCrossCountrySkiing",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distancecrosscountryskiing"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distancePaddleSports": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distancePaddleSports"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distancePaddleSports",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistancePaddleSports"
        }
      ],
      "role": "symbol",
      "title": "distancePaddleSports",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distancepaddlesports"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceRowing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceRowing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceRowing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistanceRowing"
        }
      ],
      "role": "symbol",
      "title": "distanceRowing",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distancerowing"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceSkatingSports": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceSkatingSports"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceSkatingSports",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistanceSkatingSports"
        }
      ],
      "role": "symbol",
      "title": "distanceSkatingSports",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distanceskatingsports"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/environmentalSoundReduction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "environmentalSoundReduction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/environmentalSoundReduction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierEnvironmentalSoundReduction"
        }
      ],
      "role": "symbol",
      "title": "environmentalSoundReduction",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/environmentalsoundreduction"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/estimatedWorkoutEffortScore": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "estimatedWorkoutEffortScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/estimatedWorkoutEffortScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore"
        }
      ],
      "role": "symbol",
      "title": "estimatedWorkoutEffortScore",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/estimatedworkouteffortscore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/paddleSportsSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paddleSportsSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/paddleSportsSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierPaddleSportsSpeed"
        }
      ],
      "role": "symbol",
      "title": "paddleSportsSpeed",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/paddlesportsspeed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/physicalEffort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicalEffort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/physicalEffort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierPhysicalEffort"
        }
      ],
      "role": "symbol",
      "title": "physicalEffort",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/physicaleffort"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/rowingSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowingSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/rowingSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierRowingSpeed"
        }
      ],
      "role": "symbol",
      "title": "rowingSpeed",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/rowingspeed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/timeInDaylight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeInDaylight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/timeInDaylight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierTimeInDaylight"
        }
      ],
      "role": "symbol",
      "title": "timeInDaylight",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/timeindaylight"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/workoutEffortScore": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutEffortScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/workoutEffortScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierWorkoutEffortScore"
        }
      ],
      "role": "symbol",
      "title": "workoutEffortScore",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/workouteffortscore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentTypeIdentifier/GAD7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GAD7"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKScoredAssessmentTypeIdentifier",
          "text": "HKScoredAssessmentTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentTypeIdentifier/GAD7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKScoredAssessmentTypeIdentifierGAD7"
        }
      ],
      "role": "symbol",
      "title": "GAD7",
      "type": "topic",
      "url": "/documentation/healthkit/hkscoredassessmenttypeidentifier/gad7"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentTypeIdentifier/PHQ9": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHQ9"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKScoredAssessmentTypeIdentifier",
          "text": "HKScoredAssessmentTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentTypeIdentifier/PHQ9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKScoredAssessmentTypeIdentifierPHQ9"
        }
      ],
      "role": "symbol",
      "title": "PHQ9",
      "type": "topic",
      "url": "/documentation/healthkit/hkscoredassessmenttypeidentifier/phq9"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyOperatingSystem": {
      "abstract": [
        {
          "text": "A constant that matches any operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSourceRevisionAnyOperatingSystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@NSOperatingSystemVersion",
          "text": "OperatingSystemVersion"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyOperatingSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSourceRevisionAnyOperatingSystem"
        }
      ],
      "role": "symbol",
      "title": "HKSourceRevisionAnyOperatingSystem",
      "type": "topic",
      "url": "/documentation/healthkit/hksourcerevisionanyoperatingsystem"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyProductType": {
      "abstract": [
        {
          "text": "A constant that matches any product type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSourceRevisionAnyProductType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyProductType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSourceRevisionAnyProductType"
        }
      ],
      "role": "symbol",
      "title": "HKSourceRevisionAnyProductType",
      "type": "topic",
      "url": "/documentation/healthkit/hksourcerevisionanyproducttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyVersion": {
      "abstract": [
        {
          "text": "A constant that matches any version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSourceRevisionAnyVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSourceRevisionAnyVersion"
        }
      ],
      "role": "symbol",
      "title": "HKSourceRevisionAnyVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hksourcerevisionanyversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-macros"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Classes",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-classes"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Constants",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-constants"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Data Types",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-data-types"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Enumerations",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-enumerations"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Functions",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
        "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Variables",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/bleedingAfterPregnancy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/bleedingDuringPregnancy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepApneaEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyFirmwareVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyHardwareVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyLocalIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyManufacturer",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyModel",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyName",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeySoftwareVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePropertyKeyUDIDeviceIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCount",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/appleSleepingBreathingDisturbances",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/crossCountrySkiingSpeed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingCadence",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingFunctionalThresholdPower",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingPower",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/cyclingSpeed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceCrossCountrySkiing",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distancePaddleSports",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceRowing",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceSkatingSports",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/environmentalSoundReduction",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/estimatedWorkoutEffortScore",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/paddleSportsSpeed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/physicalEffort",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/rowingSpeed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/timeInDaylight",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/workoutEffortScore",
        "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentTypeIdentifier/GAD7",
        "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentTypeIdentifier/PHQ9",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyOperatingSystem",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyProductType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevisionAnyVersion"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceCrossCountrySkiing/title",
          "value": "HKQuantityTypeIdentifierDistanceCrossCountrySkiing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceCrossCountrySkiing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistanceCrossCountrySkiing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeySoftwareVersion/title",
          "value": "HKDevicePropertyKeySoftwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeySoftwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePropertyKeySoftwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1cyclingSpeed/title",
          "value": "HKQuantityTypeIdentifierCyclingSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1cyclingSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierCyclingSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1timeInDaylight/title",
          "value": "HKQuantityTypeIdentifierTimeInDaylight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1timeInDaylight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierTimeInDaylight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevisionAnyProductType/title",
          "value": "HKSourceRevisionAnyProductType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevisionAnyProductType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSourceRevisionAnyProductType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyModel/title",
          "value": "HKDevicePropertyKeyModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePropertyKeyModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyFirmwareVersion/title",
          "value": "HKDevicePropertyKeyFirmwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyFirmwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePropertyKeyFirmwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyManufacturer/title",
          "value": "HKDevicePropertyKeyManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePropertyKeyManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice~1localIdentifier/title",
          "value": "localIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice~1localIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1sleepApneaEvent/title",
          "value": "HKCategoryTypeIdentifierSleepApneaEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1sleepApneaEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierSleepApneaEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1cyclingFunctionalThresholdPower/title",
          "value": "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1cyclingFunctionalThresholdPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1paddleSportsSpeed/title",
          "value": "HKQuantityTypeIdentifierPaddleSportsSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1paddleSportsSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierPaddleSportsSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevisionAnyVersion/title",
          "value": "HKSourceRevisionAnyVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevisionAnyVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSourceRevisionAnyVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1workoutEffortScore/title",
          "value": "HKQuantityTypeIdentifierWorkoutEffortScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1workoutEffortScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierWorkoutEffortScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceRowing/title",
          "value": "HKQuantityTypeIdentifierDistanceRowing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceRowing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistanceRowing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyLocalIdentifier/title",
          "value": "HKDevicePropertyKeyLocalIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyLocalIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePropertyKeyLocalIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1crossCountrySkiingSpeed/title",
          "value": "HKQuantityTypeIdentifierCrossCountrySkiingSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1crossCountrySkiingSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierCrossCountrySkiingSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceSkatingSports/title",
          "value": "HKQuantityTypeIdentifierDistanceSkatingSports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceSkatingSports/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistanceSkatingSports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyName/title",
          "value": "HKDevicePropertyKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePropertyKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1environmentalSoundReduction/title",
          "value": "HKQuantityTypeIdentifierEnvironmentalSoundReduction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1environmentalSoundReduction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierEnvironmentalSoundReduction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distancePaddleSports/title",
          "value": "HKQuantityTypeIdentifierDistancePaddleSports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distancePaddleSports/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistancePaddleSports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentTypeIdentifier~1GAD7/title",
          "value": "HKScoredAssessmentTypeIdentifierGAD7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentTypeIdentifier~1GAD7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessmentTypeIdentifierGAD7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyHardwareVersion/title",
          "value": "HKDevicePropertyKeyHardwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyHardwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePropertyKeyHardwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyUDIDeviceIdentifier/title",
          "value": "HKDevicePropertyKeyUDIDeviceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePropertyKeyUDIDeviceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePropertyKeyUDIDeviceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1bleedingDuringPregnancy/title",
          "value": "HKCategoryTypeIdentifierBleedingDuringPregnancy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1bleedingDuringPregnancy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierBleedingDuringPregnancy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1cyclingPower/title",
          "value": "HKQuantityTypeIdentifierCyclingPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1cyclingPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierCyclingPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCount/title",
          "value": "HKPredicateKeyPathCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1physicalEffort/title",
          "value": "HKQuantityTypeIdentifierPhysicalEffort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1physicalEffort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierPhysicalEffort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1rowingSpeed/title",
          "value": "HKQuantityTypeIdentifierRowingSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1rowingSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierRowingSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1appleSleepingBreathingDisturbances/title",
          "value": "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1appleSleepingBreathingDisturbances/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1bleedingAfterPregnancy/title",
          "value": "HKCategoryTypeIdentifierBleedingAfterPregnancy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1bleedingAfterPregnancy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierBleedingAfterPregnancy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1estimatedWorkoutEffortScore/title",
          "value": "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1estimatedWorkoutEffortScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1cyclingCadence/title",
          "value": "HKQuantityTypeIdentifierCyclingCadence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1cyclingCadence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierCyclingCadence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevisionAnyOperatingSystem/title",
          "value": "HKSourceRevisionAnyOperatingSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevisionAnyOperatingSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSourceRevisionAnyOperatingSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentTypeIdentifier~1PHQ9/title",
          "value": "HKScoredAssessmentTypeIdentifierPHQ9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentTypeIdentifier~1PHQ9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessmentTypeIdentifierPHQ9"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
