{"abstract":[{"text":"Identifiers for sorting results.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"HealthKit sort descriptors","modules":[{"name":"HealthKit"}]},"sections":[],"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/healthkit-sort-descriptors","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/queries","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"],["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/queries","doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery"]]},"topicSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKSampleSortIdentifierStartDate","doc://com.apple.healthkit/documentation/HealthKit/HKSampleSortIdentifierEndDate"],"anchor":"Sample-sort-identifiers","title":"Sample sort identifiers"},{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierDuration","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalDistance","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalFlightsClimbed","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalEnergyBurned","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalSwimmingStrokeCount"],"anchor":"Workout-sort-identifiers","title":"Workout sort identifiers"}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalDistance":{"title":"HKWorkoutSortIdentifierTotalDistance","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HKWorkoutSortIdentifierTotalDistance","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierTotalDistance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"/documentation/healthkit/hkworkoutsortidentifiertotaldistance","abstract":[{"text":"A constant for sorting workouts based on their total distance.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalDistance"},"doc://com.apple.healthkit/documentation/HealthKit/HKSampleSortIdentifierEndDate":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKSampleSortIdentifierEndDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKSampleSortIdentifierEndDate"}],"url":"/documentation/healthkit/hksamplesortidentifierenddate","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKSampleSortIdentifierEndDate","abstract":[{"type":"text","text":"A constant for sorting samples based on their end date."}],"title":"HKSampleSortIdentifierEndDate"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalEnergyBurned":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalEnergyBurned","url":"/documentation/healthkit/hkworkoutsortidentifiertotalenergyburned","title":"HKWorkoutSortIdentifierTotalEnergyBurned","abstract":[{"type":"text","text":"A constant for sorting workouts based on the total energy burned."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalEnergyBurned"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalEnergyBurned"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery":{"role":"symbol","url":"/documentation/healthkit/hksamplequery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKSampleQuery","kind":"identifier"}],"title":"HKSampleQuery","kind":"symbol","navigatorTitle":[{"text":"HKSampleQuery","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery","abstract":[{"type":"text","text":"A general query that returns a snapshot of all the matching samples currently saved in the HealthKit store."}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKSampleSortIdentifierStartDate":{"abstract":[{"text":"A constant for sorting samples based on their start date.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKSampleSortIdentifierStartDate","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKSampleSortIdentifierStartDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"HKSampleSortIdentifierStartDate","kind":"identifier"}],"type":"topic","url":"/documentation/healthkit/hksamplesortidentifierstartdate","title":"HKSampleSortIdentifierStartDate"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierDuration":{"url":"/documentation/healthkit/hkworkoutsortidentifierduration","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"HKWorkoutSortIdentifierDuration","type":"topic","abstract":[{"text":"A constant for sorting workouts based on their duration.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HKWorkoutSortIdentifierDuration","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierDuration"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalFlightsClimbed":{"type":"topic","url":"/documentation/healthkit/hkworkoutsortidentifiertotalflightsclimbed","title":"HKWorkoutSortIdentifierTotalFlightsClimbed","role":"symbol","kind":"symbol","abstract":[{"text":"A constant for sorting workouts based on the number of flights of steps climbed.","type":"text"}],"navigatorTitle":[{"text":"HKWorkoutSortIdentifierTotalFlightsClimbed","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierTotalFlightsClimbed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalFlightsClimbed"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery":{"title":"HKQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQuery"}],"url":"/documentation/healthkit/hkquery","abstract":[{"type":"text","text":"An abstract class for all the query classes in HealthKit."}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQuery"}]},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/queries":{"title":"Queries","abstract":[{"type":"text","text":"Query health and fitness data."}],"url":"/documentation/healthkit/queries","identifier":"doc://com.apple.healthkit/documentation/HealthKit/queries","role":"collectionGroup","type":"topic","kind":"article"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalSwimmingStrokeCount":{"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkworkoutsortidentifiertotalswimmingstrokecount","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalSwimmingStrokeCount","navigatorTitle":[{"text":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","kind":"identifier"}],"title":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","abstract":[{"type":"text","text":"A constant for sorting workouts based on the number of swimming strokes."}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalDistance/title","op":"replace","value":"HKWorkoutSortIdentifierTotalDistance"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalDistance/fragments","op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalDistance"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleSortIdentifierEndDate/title","op":"replace","value":"HKSampleSortIdentifierEndDate"},{"op":"replace","value":[{"text":"HKSampleSortIdentifierEndDate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleSortIdentifierEndDate/fragments"},{"op":"replace","value":"HKWorkoutSortIdentifierTotalEnergyBurned","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalEnergyBurned/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalEnergyBurned"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalEnergyBurned/fragments"},{"op":"replace","value":"HKSampleQuery","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKSampleQuery"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HKSampleQuery"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/navigatorTitle"},{"op":"replace","value":"HKSampleSortIdentifierStartDate","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleSortIdentifierStartDate/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKSampleSortIdentifierStartDate"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleSortIdentifierStartDate/fragments"},{"op":"replace","value":"HKWorkoutSortIdentifierDuration","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierDuration/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSortIdentifierDuration"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierDuration/fragments"},{"op":"replace","value":"HKWorkoutSortIdentifierTotalFlightsClimbed","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalFlightsClimbed/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalFlightsClimbed"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalFlightsClimbed/fragments"},{"op":"replace","value":"HKQuery","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKQuery"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HKQuery"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle"},{"op":"replace","value":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalSwimmingStrokeCount/title"},{"op":"replace","value":[{"text":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalSwimmingStrokeCount/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}