{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "HealthKit Classes"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityPointClampingRange": {
      "abstract": [
        {
          "text": "Defines the range within which an ear’s sensitivity point may have been clamped, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityPointClampingRange"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityPointClampingRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityPointClampingRange"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramSensitivityPointClampingRange",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramsensitivitypointclampingrange"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityTest"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityTest"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramSensitivityTest",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramsensitivitytest"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex": {
      "abstract": [
        {
          "text": "Constants indicating the user’s sex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBiologicalSex"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBiologicalSex"
        }
      ],
      "role": "symbol",
      "title": "HKBiologicalSex",
      "type": "topic",
      "url": "/documentation/healthkit/hkbiologicalsex"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSexObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBiologicalSexObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSexObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBiologicalSexObject"
        }
      ],
      "role": "symbol",
      "title": "HKBiologicalSexObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkbiologicalsexobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType": {
      "abstract": [
        {
          "text": "Constants indicating the user’s blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodTypeObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeObject"
        }
      ],
      "role": "symbol",
      "title": "HKBloodTypeObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtypeobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType": {
      "abstract": [
        {
          "text": "Categories representing the user’s skin type based on the Fitzpatrick scale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinTypeObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinTypeObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeObject"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinTypeObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintypeobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKGAD7Assessment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKGAD7Assessment"
        }
      ],
      "role": "symbol",
      "title": "HKGAD7Assessment",
      "type": "topic",
      "url": "/documentation/healthkit/hkgad7assessment"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPHQ9Assessment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPHQ9Assessment"
        }
      ],
      "role": "symbol",
      "title": "HKPHQ9Assessment",
      "type": "topic",
      "url": "/documentation/healthkit/hkphq9assessment"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKScoredAssessment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKScoredAssessment"
        }
      ],
      "role": "symbol",
      "title": "HKScoredAssessment",
      "type": "topic",
      "url": "/documentation/healthkit/hkscoredassessment"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKScoredAssessmentType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKScoredAssessmentType"
        }
      ],
      "role": "symbol",
      "title": "HKScoredAssessmentType",
      "type": "topic",
      "url": "/documentation/healthkit/hkscoredassessmenttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMindType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStateOfMindType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMindType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindType"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMindType",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmindtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the wheelchair use enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWheelchairUseObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWheelchairUseObject"
        }
      ],
      "role": "symbol",
      "title": "HKWheelchairUseObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkwheelchairuseobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationship": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationship"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationship",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationship"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEffortRelationship",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteffortrelationship"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQuery": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQuery"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEffortRelationshipQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteffortrelationshipquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-macros"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Constants",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-constants"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Data Types",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-data-types"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Enumerations",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-enumerations"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Functions",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-functions"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Variables",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
        "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityPointClampingRange",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTest",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSexObject",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinTypeObject",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment",
        "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessment",
        "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMindType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationship",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQuery"
      ],
      "title": "Classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTest/title",
          "value": "HKAudiogramSensitivityTest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityPointClampingRange/title",
          "value": "HKAudiogramSensitivityPointClampingRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityPointClampingRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityPointClampingRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityPointClampingRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityPointClampingRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/title",
          "value": "HKBloodTypeObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQuery/title",
          "value": "HKWorkoutEffortRelationshipQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/title",
          "value": "HKBloodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment/title",
          "value": "HKPHQ9Assessment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9Assessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9Assessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/title",
          "value": "HKFitzpatrickSkinType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessment/title",
          "value": "HKScoredAssessment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSexObject/title",
          "value": "HKBiologicalSexObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSexObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSexObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSexObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSexObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinTypeObject/title",
          "value": "HKFitzpatrickSkinTypeObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinTypeObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinTypeObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMindType/title",
          "value": "HKStateOfMindType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMindType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMindType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationship/title",
          "value": "HKWorkoutEffortRelationship"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationship/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationship/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUseObject/title",
          "value": "HKWheelchairUseObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUseObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUseObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUseObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUseObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/title",
          "value": "HKStateOfMind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/title",
          "value": "HKBiologicalSex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentType/title",
          "value": "HKScoredAssessmentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessmentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessmentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment/title",
          "value": "HKGAD7Assessment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7Assessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7Assessment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
