{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "HealthKit Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDataTypeIdentifierStateOfMind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDataTypeIdentifierStateOfMind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDataTypeIdentifierStateOfMind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDataTypeIdentifierStateOfMind"
        }
      ],
      "role": "symbol",
      "title": "HKDataTypeIdentifierStateOfMind",
      "type": "topic",
      "url": "/documentation/healthkit/hkdatatypeidentifierstateofmind"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleFitnessPlusCatalogIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAppleFitnessPlusCatalogIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleFitnessPlusCatalogIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAppleFitnessPlusCatalogIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyAppleFitnessPlusCatalogIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyapplefitnesspluscatalogidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumLightIntensity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyMaximumLightIntensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumLightIntensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyMaximumLightIntensity"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyMaximumLightIntensity",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeymaximumlightintensity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutEffortRelationship": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutEffortRelationship"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutEffortRelationship",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutEffortRelationship"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutEffortRelationship",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkouteffortrelationship"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-macros"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Classes",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-classes"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Data Types",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-data-types"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Enumerations",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-enumerations"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Functions",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-functions"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HealthKit Variables",
      "type": "topic",
      "url": "/documentation/healthkit/healthkit-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-enumerations",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-classes",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-data-types",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-functions",
        "doc://com.apple.healthkit/documentation/HealthKit/HealthKit-macros",
        "doc://com.apple.healthkit/documentation/HealthKit/healthkit-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKDataTypeIdentifierStateOfMind",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleFitnessPlusCatalogIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumLightIntensity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutEffortRelationship"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDataTypeIdentifierStateOfMind/title",
          "value": "HKDataTypeIdentifierStateOfMind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDataTypeIdentifierStateOfMind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDataTypeIdentifierStateOfMind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleFitnessPlusCatalogIdentifier/title",
          "value": "HKMetadataKeyAppleFitnessPlusCatalogIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleFitnessPlusCatalogIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyAppleFitnessPlusCatalogIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyMaximumLightIntensity/title",
          "value": "HKMetadataKeyMaximumLightIntensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyMaximumLightIntensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyMaximumLightIntensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutEffortRelationship/title",
          "value": "HKPredicateKeyPathWorkoutEffortRelationship"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutEffortRelationship/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutEffortRelationship"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
