{
  "abstract": [
    {
      "text": "A type that identifies activity summary objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKActivitySummaryType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKActivitySummaryType"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKActivitySummaryType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HKActivitySummaryType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKActivitySummaryType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the activity summary type to request permission to read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects from the HealthKit store. To create an activity summary type, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType/activitySummaryType()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " convenience method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Although you can request permission to read ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects, you can’t request permission to share them. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/requestAuthorization(toShare:read:completion:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class is a concrete subclass of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class. Like many HealthKit classes, activity summary types aren’t extensible and you shouldn’t subclass them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Access-and-Modify-Activity-Summaries",
          "level": 3,
          "text": "Access and Modify Activity Summaries",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Any workouts that you save to the HealthKit store may affect that day’s summary. For more information, see ",
              "type": "text"
            },
            {
              "code": "Using Workout Samples",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To query for activity summary objects, use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can also create your own ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects (for example, to display in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKitUI/HKActivityRingView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), but you can’t save them to the HealthKit store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary": {
      "abstract": [
        {
          "text": "An object that contains the move, exercise, and stand data for a given day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummary"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummary"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummary",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery": {
      "abstract": [
        {
          "text": "A query for reading activity summary objects from the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQuery"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummaryQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummaryquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryType": {
      "abstract": [
        {
          "text": "A type that identifies activity summary objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummaryType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummaryType"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummaryType",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummarytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSampleType": {
      "abstract": [
        {
          "text": "A type that identifies samples that contain audiogram data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramSampleType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSampleType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramSampleType"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramSampleType",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramsampletype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType": {
      "abstract": [
        {
          "text": "A type that identifies samples that contain a value from a small set of possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryType"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicType": {
      "abstract": [
        {
          "text": "A type that represents data that doesn’t typically change over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCharacteristicType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicType"
        }
      ],
      "role": "symbol",
      "title": "HKCharacteristicType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalType": {
      "abstract": [
        {
          "text": "A type that identifies samples that contain clinical record data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKClinicalType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKClinicalType"
        }
      ],
      "role": "symbol",
      "title": "HKClinicalType",
      "type": "topic",
      "url": "/documentation/healthkit/hkclinicaltype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationType": {
      "abstract": [
        {
          "text": "A type that identifies samples that group multiple subsamples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCorrelationType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCorrelationType"
        }
      ],
      "role": "symbol",
      "title": "HKCorrelationType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcorrelationtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramType": {
      "abstract": [
        {
          "text": "A type that identifies samples containing electrocardiogram data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramType"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogramType",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogramtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/requestAuthorization(toShare:read:completion:)": {
      "abstract": [
        {
          "text": "Requests permission to save and read the specified data types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toShare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSampleType",
          "text": "HKSampleType"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "read"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKObjectType",
          "text": "HKObjectType"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/requestAuthorization(toShare:read:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAuthorizationToShareTypes:readTypes:completion:"
        }
      ],
      "role": "symbol",
      "title": "requestAuthorization(toShare:read:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/requestauthorization(toshare:read:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType": {
      "abstract": [
        {
          "text": "An abstract superclass with subclasses that identify a specific type of data for the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKObjectType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKObjectType"
        }
      ],
      "role": "symbol",
      "title": "HKObjectType",
      "type": "topic",
      "url": "/documentation/healthkit/hkobjecttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType/activitySummaryType()": {
      "abstract": [
        {
          "text": "Returns the shared activity summary type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activitySummaryType"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKActivitySummaryType",
          "text": "HKActivitySummaryType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType/activitySummaryType()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activitySummaryType"
        }
      ],
      "role": "symbol",
      "title": "activitySummaryType()",
      "type": "topic",
      "url": "/documentation/healthkit/hkobjecttype/activitysummarytype()"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityType": {
      "abstract": [
        {
          "text": "A type that identifies samples that store numerical values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityType"
        }
      ],
      "role": "symbol",
      "title": "HKQuantityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSampleType": {
      "abstract": [
        {
          "text": "An abstract superclass for all classes that identify a specific type of sample when working with the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSampleType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSampleType"
        }
      ],
      "role": "symbol",
      "title": "HKSampleType",
      "type": "topic",
      "url": "/documentation/healthkit/hksampletype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesType": {
      "abstract": [
        {
          "text": "A type that indicates the data stored in a series sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSeriesType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSeriesType"
        }
      ],
      "role": "symbol",
      "title": "HKSeriesType",
      "type": "topic",
      "url": "/documentation/healthkit/hkseriestype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType": {
      "abstract": [
        {
          "text": "A type that identifies samples that store information about a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKitUI/HKActivityRingView": {
      "abstract": [
        {
          "text": "A view that uses the Move, Exercise, and Stand activity rings to display data from a HealthKit activity summary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivityRingView"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKitUI/HKActivityRingView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivityRingView"
        }
      ],
      "role": "symbol",
      "title": "HKActivityRingView",
      "type": "topic",
      "url": "/documentation/healthkitui/hkactivityringview"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery",
        "doc://com.apple.healthkit/documentation/HealthKitUI/HKActivityRingView"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Object-type-subclasses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSampleType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSampleType"
      ],
      "title": "Object type subclasses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKActivitySummaryType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
                "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery",
                "doc://com.apple.healthkit/documentation/HealthKitUI/HKActivityRingView"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Object-type-subclasses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSampleType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKClinicalType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSampleType"
              ],
              "title": "Object type subclasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKActivitySummaryType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HKObjectType",
                    "text": "HKObjectType"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1requestAuthorization(toShare:read:completion:)/title",
          "value": "requestAuthorizationToShareTypes:readTypes:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1requestAuthorization(toShare:read:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorizationToShareTypes:readTypes:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/title",
          "value": "HKActivitySummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/title",
          "value": "HKActivitySummaryQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramType/title",
          "value": "HKElectrocardiogramType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKitUI~1HKActivityRingView/title",
          "value": "HKActivityRingView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKitUI~1HKActivityRingView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivityRingView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKitUI~1HKActivityRingView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivityRingView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSampleType/title",
          "value": "HKAudiogramSampleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSampleType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSampleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSampleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSampleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/title",
          "value": "HKCategoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObjectType~1activitySummaryType()/title",
          "value": "activitySummaryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObjectType~1activitySummaryType()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "activitySummaryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObjectType/title",
          "value": "HKObjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesType/title",
          "value": "HKSeriesType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSeriesType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSeriesType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalType/title",
          "value": "HKClinicalType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKClinicalType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKClinicalType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityType/title",
          "value": "HKQuantityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryType/title",
          "value": "HKActivitySummaryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationType/title",
          "value": "HKCorrelationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/title",
          "value": "HKWorkoutType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicType/title",
          "value": "HKCharacteristicType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleType/title",
          "value": "HKSampleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkactivitysummarytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkactivitysummarytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
