{
  "abstract": [
    {
      "text": "Returns the maximum score for the steadiness of the user’s gait based on the provided classification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMaximumQuantityForClassification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@HKAppleWalkingSteadinessMaximumQuantityForClassification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "HKAppleWalkingSteadinessMaximumQuantityForClassification"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKAppleWalkingSteadinessMaximumQuantityForClassification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "HKAppleWalkingSteadinessMaximumQuantityForClassification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKQuantity",
              "text": "HKQuantity"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessMaximumQuantityForClassification"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@HKAppleWalkingSteadinessClassification",
              "text": "HKAppleWalkingSteadinessClassification"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "classification"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The classification to look up.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "classification"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method to look up the maximum Walking Steadiness value for a given classification. It returns an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance that contains a percentage value between ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification": {
      "abstract": [
        {
          "text": "A classification of a score based on the steadiness of the user’s gait.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassification"
        }
      ],
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassificationForQuantity": {
      "abstract": [
        {
          "text": "Provides a classification for a score that measures the steadiness of the user’s gait.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassificationForQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassificationForQuantity",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessClassificationForQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassificationforquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMaximumQuantityForClassification": {
      "abstract": [
        {
          "text": "Returns the maximum score for the steadiness of the user’s gait based on the provided classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessMaximumQuantityForClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMaximumQuantityForClassification",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessMaximumQuantityForClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessmaximumquantityforclassification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMinimumQuantityForClassification": {
      "abstract": [
        {
          "text": "Returns the minimum score for the steadiness of the user’s gait based on the provided classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessMinimumQuantityForClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMinimumQuantityForClassification",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessMinimumQuantityForClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessminimumquantityforclassification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity": {
      "abstract": [
        {
          "text": "An object that stores a value for a given unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantity"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Walking-steadiness-classifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassificationForQuantity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMinimumQuantityForClassification"
      ],
      "title": "Walking steadiness classifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/title",
          "value": "HKQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification/title",
          "value": "HKAppleWalkingSteadinessClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkapplewalkingsteadinessmaximumquantityforclassification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
