{
  "abstract": [
    {
      "text": "A classification of a score based on the steadiness of the user’s gait.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKAppleWalkingSteadinessClassification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKAppleWalkingSteadinessClassification"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKAppleWalkingSteadinessClassification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "HKAppleWalkingSteadinessClassification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassification"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Walking Steadiness classifications measures the ability of the user to move with a steady, even gait. You can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassificationForQuantity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMaximumQuantityForClassification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMinimumQuantityForClassification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods to convert between Walking Steadiness scores and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/low",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/veryLow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/ok",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification": {
      "abstract": [
        {
          "text": "A classification of a score based on the steadiness of the user’s gait.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassification"
        }
      ],
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/CaseIterable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/CaseIterable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CaseIterable Implementations",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification/caseiterable-implementations"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/init(for:)": {
      "abstract": [
        {
          "text": "Creates a new classification for the provided percentage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/init(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(for:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification/init(for:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification/init(rawvalue:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/low": {
      "abstract": [
        {
          "text": "A classification indicating that the stability of the user’s gate is below normal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassificationLow"
        }
      ],
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessClassification.low",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification/low"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/maximum": {
      "abstract": [
        {
          "text": "The minimum walking steadiness percentage for the classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/maximum",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximum",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification/maximum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/minimum": {
      "abstract": [
        {
          "text": "The maximum walking steadiness percentage for the classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantity",
          "text": "HKQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/minimum",
      "kind": "symbol",
      "role": "symbol",
      "title": "minimum",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification/minimum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/ok": {
      "abstract": [
        {
          "text": "A classification indicating that the stability of the user’s gait is within the normal range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ok"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/ok",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassificationOK"
        }
      ],
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessClassification.ok",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification/ok"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/veryLow": {
      "abstract": [
        {
          "text": "A classification indicating that the stability of the user’s gate is considerably below normal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "veryLow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/veryLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassificationVeryLow"
        }
      ],
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessClassification.veryLow",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassification/verylow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassificationForQuantity": {
      "abstract": [
        {
          "text": "Provides a classification for a score that measures the steadiness of the user’s gait.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessClassificationForQuantity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassificationForQuantity",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessClassificationForQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessclassificationforquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMaximumQuantityForClassification": {
      "abstract": [
        {
          "text": "Returns the maximum score for the steadiness of the user’s gait based on the provided classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessMaximumQuantityForClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMaximumQuantityForClassification",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessMaximumQuantityForClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessmaximumquantityforclassification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMinimumQuantityForClassification": {
      "abstract": [
        {
          "text": "Returns the minimum score for the steadiness of the user’s gait based on the provided classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKAppleWalkingSteadinessMinimumQuantityForClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMinimumQuantityForClassification",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKAppleWalkingSteadinessMinimumQuantityForClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkapplewalkingsteadinessminimumquantityforclassification"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s12CaseIterableP": {
      "abstract": [
        {
          "text": "A type that provides a collection of all of its values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CaseIterable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s12CaseIterableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CaseIterable",
      "type": "topic",
      "url": "/documentation/Swift/CaseIterable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s12CaseIterableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Accessing-Classifications",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/ok",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/low",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/veryLow"
      ],
      "title": "Accessing Classifications"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/init(for:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/maximum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/minimum"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/CaseIterable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKAppleWalkingSteadinessClassification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Classifications",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/ok",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/low",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassification/veryLow"
              ],
              "title": "Accessing Classifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Walking-steadiness-classifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessClassificationForQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMaximumQuantityForClassification",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAppleWalkingSteadinessMinimumQuantityForClassification"
              ],
              "title": "Walking steadiness classifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKAppleWalkingSteadinessClassification"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification~1low/title",
          "value": "HKAppleWalkingSteadinessClassificationLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassificationLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification~1ok/title",
          "value": "HKAppleWalkingSteadinessClassificationOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification~1ok/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassificationOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification~1veryLow/title",
          "value": "HKAppleWalkingSteadinessClassificationVeryLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification~1veryLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassificationVeryLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification/title",
          "value": "HKAppleWalkingSteadinessClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAppleWalkingSteadinessClassification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAppleWalkingSteadinessClassification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkapplewalkingsteadinessclassification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkapplewalkingsteadinessclassification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
