{"abstract":[{"type":"text","text":"Constants that indicate where on the body a temperature reading was taken."}],"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"]}],"metadata":{"externalID":"c:@E@HKBodyTemperatureSensorLocation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"symbolKind":"enum","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"roleHeading":"Enumeration","platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"8.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"8.0"},{"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"macOS","beta":false},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS","beta":false},{"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"watchOS","beta":false}],"role":"symbol","modules":[{"name":"HealthKit"}],"title":"HKBodyTemperatureSensorLocation"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKBodyTemperatureSensorLocation"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"sections":[],"variants":[{"paths":["/documentation/healthkit/hkbodytemperaturesensorlocation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkbodytemperaturesensorlocation"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead"],"title":"Locations","anchor":"Locations"},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/init(rawValue:)"]}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/finger","kind":"symbol","abstract":[{"text":"The temperature was taken at the finger.","type":"text"}],"title":"HKBodyTemperatureSensorLocation.finger","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"finger","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationFinger","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"role":"symbol","url":"/documentation/Swift/BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"abstract":[{"text":"","type":"text"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body":{"type":"topic","title":"HKBodyTemperatureSensorLocation.body","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationBody","kind":"identifier"}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/body","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"body","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The temperature was taken on the body.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","title":"Equatable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"armpit"}],"title":"HKBodyTemperatureSensorLocation.armpit","abstract":[{"text":"The temperature was taken in the armpit.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationArmpit"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/armpit"},"doc://com.externally.resolved.symbol/s:SH":{"title":"Hashable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","preciseIdentifier":"s:SQ","kind":"typeIdentifier"}],"url":"/documentation/Swift/Hashable","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:SY":{"title":"RawRepresentable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"url":"/documentation/Swift/RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY","type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"temporalArtery","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.temporalArtery","abstract":[{"text":"The temperature was taken at the temporal artery.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationTemporalArtery","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/temporalartery"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forehead","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.forehead","abstract":[{"text":"The temperature was taken on the forehead.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationForehead","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/forehead"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe":{"abstract":[{"type":"text","text":"The temperature was taken at the toe."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/toe","role":"symbol","title":"HKBodyTemperatureSensorLocation.toe","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toe","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationToe","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth":{"type":"topic","abstract":[{"text":"The temperature was taken in the mouth.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mouth","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationMouth","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.mouth","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/mouth"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gastroIntestinal","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.gastroIntestinal","abstract":[{"text":"The temperature was taken inside the gastrointestinal tract.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationGastroIntestinal","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/gastrointestinal"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other":{"title":"HKBodyTemperatureSensorLocation.other","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The temperature was taken at a location that is not otherwise in this list."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/other","role":"symbol","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationOther","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"type":"topic","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"title":"NSInteger","kind":"symbol","abstract":[{"text":"Describes an integer.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","url":"/documentation/objectivec/nsinteger"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/init(rawValue:)":{"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/init(rawValue:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/init(rawvalue:)","title":"init(rawValue:)","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"earDrum"}],"title":"HKBodyTemperatureSensorLocation.earDrum","abstract":[{"text":"The temperature was taken on the eardrum.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationEarDrum"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/eardrum"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation":{"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation","kind":"symbol","abstract":[{"type":"text","text":"Constants that indicate where on the body a temperature reading was taken."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation","title":"HKBodyTemperatureSensorLocation","role":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","url":"/documentation/Swift/Sendable"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ear"}],"title":"HKBodyTemperatureSensorLocation.ear","abstract":[{"text":"The temperature was taken in the ear.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationEar"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/ear"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum":{"abstract":[{"type":"text","text":"The temperature was taken in the rectum."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/rectum","role":"symbol","title":"HKBodyTemperatureSensorLocation.rectum","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rectum","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationRectum","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false,"name":"macOS"},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS","beta":false},{"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"watchOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration"},{"op":"replace","path":"/metadata/title","value":"HKBodyTemperatureSensorLocation"},{"op":"replace","path":"/metadata/symbolKind","value":"enum"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]}},{"path":"/topicSections","op":"replace","value":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead"],"title":"Locations","anchor":"Locations"}]},{"path":"/relationshipsSections","op":"replace","value":null},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1finger/title","value":"HKBodyTemperatureSensorLocationFinger"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1finger/fragments","value":[{"text":"HKBodyTemperatureSensorLocationFinger","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1body/title","value":"HKBodyTemperatureSensorLocationBody"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1body/fragments","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationBody"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1armpit/title","value":"HKBodyTemperatureSensorLocationArmpit"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1armpit/fragments","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationArmpit"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1temporalArtery/title","value":"HKBodyTemperatureSensorLocationTemporalArtery"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1temporalArtery/fragments","value":[{"text":"HKBodyTemperatureSensorLocationTemporalArtery","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1forehead/title","value":"HKBodyTemperatureSensorLocationForehead"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1forehead/fragments","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationForehead"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1toe/title","value":"HKBodyTemperatureSensorLocationToe","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1toe/fragments","value":[{"text":"HKBodyTemperatureSensorLocationToe","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1mouth/title","value":"HKBodyTemperatureSensorLocationMouth","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1mouth/fragments","value":[{"text":"HKBodyTemperatureSensorLocationMouth","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1gastroIntestinal/title","value":"HKBodyTemperatureSensorLocationGastroIntestinal","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1gastroIntestinal/fragments","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationGastroIntestinal"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1other/title","value":"HKBodyTemperatureSensorLocationOther","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1other/fragments","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationOther"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1earDrum/title","value":"HKBodyTemperatureSensorLocationEarDrum","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1earDrum/fragments","value":[{"text":"HKBodyTemperatureSensorLocationEarDrum","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/title","value":"HKBodyTemperatureSensorLocation","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/fragments","value":[{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/navigatorTitle","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocation"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1ear/title","value":"HKBodyTemperatureSensorLocationEar","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1ear/fragments","value":[{"text":"HKBodyTemperatureSensorLocationEar","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1rectum/title","value":"HKBodyTemperatureSensorLocationRectum","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1rectum/fragments","value":[{"text":"HKBodyTemperatureSensorLocationRectum","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}