{
  "abstract": [
    {
      "text": "Identifiers for creating category types.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@HKCategoryTypeIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKCategoryTypeIdentifier"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryTypeIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "HKCategoryTypeIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance, pass an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType/categoryType(forIdentifier:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For the complete list of quantity type identifiers, see Activity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType": {
      "abstract": [
        {
          "text": "A type that identifies samples that contain a value from a small set of possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryType"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier": {
      "abstract": [
        {
          "text": "Identifiers for creating category types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/appleStandHour": {
      "abstract": [
        {
          "text": "A category sample type that counts the number of hours in the day during which the user has stood and moved for at least one minute per hour.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleStandHour"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/appleStandHour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierAppleStandHour"
        }
      ],
      "role": "symbol",
      "title": "appleStandHour",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/applestandhour"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/appleWalkingSteadinessEvent": {
      "abstract": [
        {
          "text": "A category sample type that records an incident where the user showed a reduced score for their gait’s steadiness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleWalkingSteadinessEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/appleWalkingSteadinessEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierAppleWalkingSteadinessEvent"
        }
      ],
      "role": "symbol",
      "title": "appleWalkingSteadinessEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/applewalkingsteadinessevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/audioExposureEvent": {
      "abstract": [
        {
          "text": "A category sample type for audio exposure events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioExposureEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/audioExposureEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierAudioExposureEvent"
        }
      ],
      "role": "symbol",
      "title": "audioExposureEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/audioexposureevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/cervicalMucusQuality": {
      "abstract": [
        {
          "text": "A category sample type that records the quality of the user’s cervical mucus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cervicalMucusQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/cervicalMucusQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierCervicalMucusQuality"
        }
      ],
      "role": "symbol",
      "title": "cervicalMucusQuality",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/cervicalmucusquality"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/contraceptive": {
      "abstract": [
        {
          "text": "A category sample type that records the use of contraceptives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contraceptive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/contraceptive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierContraceptive"
        }
      ],
      "role": "symbol",
      "title": "contraceptive",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/contraceptive"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/environmentalAudioExposureEvent": {
      "abstract": [
        {
          "text": "A category sample type that records exposure to potentially damaging sounds from the environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "environmentalAudioExposureEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/environmentalAudioExposureEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent"
        }
      ],
      "role": "symbol",
      "title": "environmentalAudioExposureEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/environmentalaudioexposureevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/handwashingEvent": {
      "abstract": [
        {
          "text": "A category sample type for handwashing events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handwashingEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/handwashingEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierHandwashingEvent"
        }
      ],
      "role": "symbol",
      "title": "handwashingEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/handwashingevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/headphoneAudioExposureEvent": {
      "abstract": [
        {
          "text": "A category sample type that records exposure to potentially damaging sounds from headphones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headphoneAudioExposureEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/headphoneAudioExposureEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierHeadphoneAudioExposureEvent"
        }
      ],
      "role": "symbol",
      "title": "headphoneAudioExposureEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/headphoneaudioexposureevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/highHeartRateEvent": {
      "abstract": [
        {
          "text": "A category sample type for high heart rate events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highHeartRateEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/highHeartRateEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierHighHeartRateEvent"
        }
      ],
      "role": "symbol",
      "title": "highHeartRateEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/highheartrateevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/infrequentMenstrualCycles": {
      "abstract": [
        {
          "text": "A category sample that indicates an infrequent menstrual cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "infrequentMenstrualCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/infrequentMenstrualCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierInfrequentMenstrualCycles"
        }
      ],
      "role": "symbol",
      "title": "infrequentMenstrualCycles",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/infrequentmenstrualcycles"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/init(rawValue:)": {
      "abstract": [
        {
          "text": "Returns a newly initialized category type identifier using the provided string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/init(rawvalue:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/intermenstrualBleeding": {
      "abstract": [
        {
          "text": "A category sample type that records spotting outside the normal menstruation period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intermenstrualBleeding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/intermenstrualBleeding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierIntermenstrualBleeding"
        }
      ],
      "role": "symbol",
      "title": "intermenstrualBleeding",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/intermenstrualbleeding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularHeartRhythmEvent": {
      "abstract": [
        {
          "text": "A category sample type for irregular heart rhythm events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "irregularHeartRhythmEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularHeartRhythmEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierIrregularHeartRhythmEvent"
        }
      ],
      "role": "symbol",
      "title": "irregularHeartRhythmEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/irregularheartrhythmevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularMenstrualCycles": {
      "abstract": [
        {
          "text": "A category sample that indicates an irregular menstrual cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "irregularMenstrualCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularMenstrualCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierIrregularMenstrualCycles"
        }
      ],
      "role": "symbol",
      "title": "irregularMenstrualCycles",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/irregularmenstrualcycles"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lactation": {
      "abstract": [
        {
          "text": "A category type that records lactation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lactation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lactation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierLactation"
        }
      ],
      "role": "symbol",
      "title": "lactation",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/lactation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowCardioFitnessEvent": {
      "abstract": [
        {
          "text": "An event that indicates the user’s VO2 max values consistently fall below a particular aerobic fitness threshold.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowCardioFitnessEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowCardioFitnessEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierLowCardioFitnessEvent"
        }
      ],
      "role": "symbol",
      "title": "lowCardioFitnessEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/lowcardiofitnessevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowHeartRateEvent": {
      "abstract": [
        {
          "text": "A category sample type for low heart rate events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowHeartRateEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowHeartRateEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierLowHeartRateEvent"
        }
      ],
      "role": "symbol",
      "title": "lowHeartRateEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/lowheartrateevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/menstrualFlow": {
      "abstract": [
        {
          "text": "A category sample type that records menstrual cycles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menstrualFlow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/menstrualFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierMenstrualFlow"
        }
      ],
      "role": "symbol",
      "title": "menstrualFlow",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/menstrualflow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/mindfulSession": {
      "abstract": [
        {
          "text": "A category sample type for recording a mindful session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mindfulSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/mindfulSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierMindfulSession"
        }
      ],
      "role": "symbol",
      "title": "mindfulSession",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/mindfulsession"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/ovulationTestResult": {
      "abstract": [
        {
          "text": "A category sample type that records the result of an ovulation home test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ovulationTestResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/ovulationTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierOvulationTestResult"
        }
      ],
      "role": "symbol",
      "title": "ovulationTestResult",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/ovulationtestresult"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/persistentIntermenstrualBleeding": {
      "abstract": [
        {
          "text": "A category sample that indicates persistent intermenstrual bleeding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentIntermenstrualBleeding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/persistentIntermenstrualBleeding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierPersistentIntermenstrualBleeding"
        }
      ],
      "role": "symbol",
      "title": "persistentIntermenstrualBleeding",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/persistentintermenstrualbleeding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/pregnancy": {
      "abstract": [
        {
          "text": "A category type that records pregnancy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pregnancy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/pregnancy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierPregnancy"
        }
      ],
      "role": "symbol",
      "title": "pregnancy",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/pregnancy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/pregnancyTestResult": {
      "abstract": [
        {
          "text": "A category type that represents the results from a home pregnancy test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pregnancyTestResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/pregnancyTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierPregnancyTestResult"
        }
      ],
      "role": "symbol",
      "title": "pregnancyTestResult",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/pregnancytestresult"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/progesteroneTestResult": {
      "abstract": [
        {
          "text": "A category type that represents the results from a home progesterone test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progesteroneTestResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/progesteroneTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierProgesteroneTestResult"
        }
      ],
      "role": "symbol",
      "title": "progesteroneTestResult",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/progesteronetestresult"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/prolongedMenstrualPeriods": {
      "abstract": [
        {
          "text": "A category sample that indicates a prolonged menstrual cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prolongedMenstrualPeriods"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/prolongedMenstrualPeriods",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierProlongedMenstrualPeriods"
        }
      ],
      "role": "symbol",
      "title": "prolongedMenstrualPeriods",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/prolongedmenstrualperiods"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sexualActivity": {
      "abstract": [
        {
          "text": "A category sample type that records sexual activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sexualActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sexualActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierSexualActivity"
        }
      ],
      "role": "symbol",
      "title": "sexualActivity",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/sexualactivity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepAnalysis": {
      "abstract": [
        {
          "text": "A category sample type for sleep analysis information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepAnalysis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepAnalysis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierSleepAnalysis"
        }
      ],
      "role": "symbol",
      "title": "sleepAnalysis",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/sleepanalysis"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/toothbrushingEvent": {
      "abstract": [
        {
          "text": "A category sample type for toothbrushing events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toothbrushingEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/toothbrushingEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryTypeIdentifierToothbrushingEvent"
        }
      ],
      "role": "symbol",
      "title": "toothbrushingEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/toothbrushingevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueEnvironmentalAudioExposureEvent": {
      "abstract": [
        {
          "text": "Exposure events for environmental audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueEnvironmentalAudioExposureEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueEnvironmentalAudioExposureEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueEnvironmentalAudioExposureEvent"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueEnvironmentalAudioExposureEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueenvironmentalaudioexposureevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueHeadphoneAudioExposureEvent": {
      "abstract": [
        {
          "text": "Exposure events for headphone audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueHeadphoneAudioExposureEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueHeadphoneAudioExposureEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueHeadphoneAudioExposureEvent"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueHeadphoneAudioExposureEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueheadphoneaudioexposureevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType/categoryType(forIdentifier:)": {
      "abstract": [
        {
          "text": "Returns the shared category type for the provided identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoryType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCategoryTypeIdentifier",
          "text": "HKCategoryTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCategoryType",
          "text": "HKCategoryType"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType/categoryType(forIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "categoryTypeForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "categoryType(forIdentifier:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkobjecttype/categorytype(foridentifier:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/symptom-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for medical symptoms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/symptom-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Symptom Type Identifiers",
      "type": "topic",
      "url": "/documentation/healthkit/symptom-type-identifiers"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-category-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType/categoryType(forIdentifier:)"
      ],
      "title": "Creating category types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Activity",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/appleStandHour",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowCardioFitnessEvent"
      ],
      "title": "Activity"
    },
    {
      "anchor": "Reproductive-Health",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/menstrualFlow",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/intermenstrualBleeding",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/infrequentMenstrualCycles",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularMenstrualCycles",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/persistentIntermenstrualBleeding",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/prolongedMenstrualPeriods",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/cervicalMucusQuality",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/ovulationTestResult",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/progesteroneTestResult",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sexualActivity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/contraceptive",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/pregnancy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/pregnancyTestResult",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lactation"
      ],
      "title": "Reproductive Health"
    },
    {
      "anchor": "Hearing",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/environmentalAudioExposureEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueEnvironmentalAudioExposureEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/headphoneAudioExposureEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueHeadphoneAudioExposureEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/audioExposureEvent"
      ],
      "title": "Hearing"
    },
    {
      "anchor": "Vital-Signs",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowHeartRateEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/highHeartRateEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularHeartRhythmEvent"
      ],
      "title": "Vital Signs"
    },
    {
      "anchor": "Mobility",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/appleWalkingSteadinessEvent"
      ],
      "title": "Mobility"
    },
    {
      "anchor": "Symptoms",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/symptom-type-identifiers"
      ],
      "title": "Symptoms"
    },
    {
      "anchor": "Mindfulness-and-Sleep",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/mindfulSession",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepAnalysis"
      ],
      "title": "Mindfulness and Sleep"
    },
    {
      "anchor": "Self-Care",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/toothbrushingEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/handwashingEvent"
      ],
      "title": "Self Care"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCategoryTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Activity",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/appleStandHour",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowCardioFitnessEvent"
              ],
              "title": "Activity"
            },
            {
              "anchor": "Reproductive-Health",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/menstrualFlow",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/intermenstrualBleeding",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/infrequentMenstrualCycles",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularMenstrualCycles",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/persistentIntermenstrualBleeding",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/prolongedMenstrualPeriods",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/cervicalMucusQuality",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/ovulationTestResult",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/progesteroneTestResult",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sexualActivity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/contraceptive",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/pregnancy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/pregnancyTestResult",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lactation"
              ],
              "title": "Reproductive Health"
            },
            {
              "anchor": "Hearing",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/environmentalAudioExposureEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueEnvironmentalAudioExposureEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/headphoneAudioExposureEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueHeadphoneAudioExposureEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/audioExposureEvent"
              ],
              "title": "Hearing"
            },
            {
              "anchor": "Vital-Signs",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/lowHeartRateEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/highHeartRateEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/irregularHeartRhythmEvent"
              ],
              "title": "Vital Signs"
            },
            {
              "anchor": "Mobility",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/appleWalkingSteadinessEvent"
              ],
              "title": "Mobility"
            },
            {
              "anchor": "Symptoms",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/symptom-type-identifiers"
              ],
              "title": "Symptoms"
            },
            {
              "anchor": "Mindfulness-and-Sleep",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/mindfulSession",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/sleepAnalysis"
              ],
              "title": "Mindfulness and Sleep"
            },
            {
              "anchor": "Self-Care",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/toothbrushingEvent",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryTypeIdentifier/handwashingEvent"
              ],
              "title": "Self Care"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-category-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKObjectType/categoryType(forIdentifier:)"
              ],
              "title": "Creating category types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKCategoryTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1appleWalkingSteadinessEvent/title",
          "value": "HKCategoryTypeIdentifierAppleWalkingSteadinessEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1appleWalkingSteadinessEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierAppleWalkingSteadinessEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1sleepAnalysis/title",
          "value": "HKCategoryTypeIdentifierSleepAnalysis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1sleepAnalysis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierSleepAnalysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueHeadphoneAudioExposureEvent/title",
          "value": "HKCategoryValueHeadphoneAudioExposureEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueHeadphoneAudioExposureEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueHeadphoneAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueHeadphoneAudioExposureEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueHeadphoneAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1headphoneAudioExposureEvent/title",
          "value": "HKCategoryTypeIdentifierHeadphoneAudioExposureEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1headphoneAudioExposureEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierHeadphoneAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObjectType~1categoryType(forIdentifier:)/title",
          "value": "categoryTypeForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObjectType~1categoryType(forIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "categoryTypeForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1cervicalMucusQuality/title",
          "value": "HKCategoryTypeIdentifierCervicalMucusQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1cervicalMucusQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierCervicalMucusQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1toothbrushingEvent/title",
          "value": "HKCategoryTypeIdentifierToothbrushingEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1toothbrushingEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierToothbrushingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1intermenstrualBleeding/title",
          "value": "HKCategoryTypeIdentifierIntermenstrualBleeding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1intermenstrualBleeding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierIntermenstrualBleeding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1menstrualFlow/title",
          "value": "HKCategoryTypeIdentifierMenstrualFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1menstrualFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierMenstrualFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1prolongedMenstrualPeriods/title",
          "value": "HKCategoryTypeIdentifierProlongedMenstrualPeriods"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1prolongedMenstrualPeriods/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierProlongedMenstrualPeriods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1environmentalAudioExposureEvent/title",
          "value": "HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1environmentalAudioExposureEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1audioExposureEvent/title",
          "value": "HKCategoryTypeIdentifierAudioExposureEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1audioExposureEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueEnvironmentalAudioExposureEvent/title",
          "value": "HKCategoryValueEnvironmentalAudioExposureEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueEnvironmentalAudioExposureEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueEnvironmentalAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueEnvironmentalAudioExposureEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueEnvironmentalAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier/title",
          "value": "HKCategoryTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1pregnancy/title",
          "value": "HKCategoryTypeIdentifierPregnancy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1pregnancy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierPregnancy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1persistentIntermenstrualBleeding/title",
          "value": "HKCategoryTypeIdentifierPersistentIntermenstrualBleeding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1persistentIntermenstrualBleeding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierPersistentIntermenstrualBleeding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1lactation/title",
          "value": "HKCategoryTypeIdentifierLactation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1lactation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierLactation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1sexualActivity/title",
          "value": "HKCategoryTypeIdentifierSexualActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1sexualActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierSexualActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1progesteroneTestResult/title",
          "value": "HKCategoryTypeIdentifierProgesteroneTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1progesteroneTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierProgesteroneTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1handwashingEvent/title",
          "value": "HKCategoryTypeIdentifierHandwashingEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1handwashingEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierHandwashingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1lowCardioFitnessEvent/title",
          "value": "HKCategoryTypeIdentifierLowCardioFitnessEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1lowCardioFitnessEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierLowCardioFitnessEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/title",
          "value": "HKCategoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1ovulationTestResult/title",
          "value": "HKCategoryTypeIdentifierOvulationTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1ovulationTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierOvulationTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1highHeartRateEvent/title",
          "value": "HKCategoryTypeIdentifierHighHeartRateEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1highHeartRateEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierHighHeartRateEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1irregularHeartRhythmEvent/title",
          "value": "HKCategoryTypeIdentifierIrregularHeartRhythmEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1irregularHeartRhythmEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierIrregularHeartRhythmEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1lowHeartRateEvent/title",
          "value": "HKCategoryTypeIdentifierLowHeartRateEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1lowHeartRateEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierLowHeartRateEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1contraceptive/title",
          "value": "HKCategoryTypeIdentifierContraceptive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1contraceptive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierContraceptive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1infrequentMenstrualCycles/title",
          "value": "HKCategoryTypeIdentifierInfrequentMenstrualCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1infrequentMenstrualCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierInfrequentMenstrualCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1irregularMenstrualCycles/title",
          "value": "HKCategoryTypeIdentifierIrregularMenstrualCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1irregularMenstrualCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierIrregularMenstrualCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1mindfulSession/title",
          "value": "HKCategoryTypeIdentifierMindfulSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1mindfulSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierMindfulSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1appleStandHour/title",
          "value": "HKCategoryTypeIdentifierAppleStandHour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1appleStandHour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierAppleStandHour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1pregnancyTestResult/title",
          "value": "HKCategoryTypeIdentifierPregnancyTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryTypeIdentifier~1pregnancyTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryTypeIdentifierPregnancyTestResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategorytypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcategorytypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
