{
  "abstract": [
    {
      "text": "A protocol for objects that produce predicates that match category value samples.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9HealthKit33HKCategoryValuePredicateProvidingP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKCategoryValuePredicateProviding"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryValuePredicateProviding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "HKCategoryValuePredicateProviding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKCategoryValuePredicateProviding"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SH",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SH",
              "text": "Hashable"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SY",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SY",
              "text": "RawRepresentable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue": {
      "abstract": [
        {
          "text": "Categories that are undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValue"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValue"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValue",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalue"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppetiteChanges": {
      "abstract": [
        {
          "text": "Categories that represent change in appetite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppetiteChanges"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppetiteChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppetiteChanges"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppetiteChanges",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueappetitechanges"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleStandHour": {
      "abstract": [
        {
          "text": "Categories that the system used to indicate whether the user stood during the sample’s duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleStandHour"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleStandHour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleStandHour"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppleStandHour",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueapplestandhour"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent": {
      "abstract": [
        {
          "text": "The value of an event triggered by a reduced score for the steadiness of the user’s gait.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleWalkingSteadinessEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueAppleWalkingSteadinessEvent"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueAppleWalkingSteadinessEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueapplewalkingsteadinessevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality": {
      "abstract": [
        {
          "text": "Categories that represent the user’s cervical mucus quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQuality"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQuality"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueCervicalMucusQuality",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecervicalmucusquality"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive": {
      "abstract": [
        {
          "text": "The type of contraceptive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptive"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueContraceptive"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueContraceptive",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecontraceptive"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueEnvironmentalAudioExposureEvent": {
      "abstract": [
        {
          "text": "Exposure events for environmental audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueEnvironmentalAudioExposureEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueEnvironmentalAudioExposureEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueEnvironmentalAudioExposureEvent"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueEnvironmentalAudioExposureEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueenvironmentalaudioexposureevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueHeadphoneAudioExposureEvent": {
      "abstract": [
        {
          "text": "Exposure events for headphone audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueHeadphoneAudioExposureEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueHeadphoneAudioExposureEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueHeadphoneAudioExposureEvent"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueHeadphoneAudioExposureEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueheadphoneaudioexposureevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueLowCardioFitnessEvent": {
      "abstract": [
        {
          "text": "A value that indicates a low-level cardio fitness event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueLowCardioFitnessEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueLowCardioFitnessEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueLowCardioFitnessEvent"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueLowCardioFitnessEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluelowcardiofitnessevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow": {
      "abstract": [
        {
          "text": "Categories that indicate the amount of menstrual flow for a given sample.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueMenstrualFlow"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueMenstrualFlow",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluemenstrualflow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult": {
      "abstract": [
        {
          "text": "Categories that represent the result of an ovulation home test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResult"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResult"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueOvulationTestResult",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueovulationtestresult"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding": {
      "abstract": [
        {
          "text": "A protocol for objects that produce predicates that match category value samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValuePredicateProviding"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValuePredicateProviding"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValuePredicateProviding",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluepredicateproviding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(_:value:)": {
      "abstract": [
        {
          "text": "Returns a predicate that checks a category sample’s value.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Int",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForSamples"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSComparisonPredicate",
          "text": "NSComparisonPredicate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPredicateOperatorType",
          "text": "Operator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(_:value:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "predicateForSamples(_:value:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluepredicateproviding/predicateforsamples(_:value:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(equalTo:)": {
      "abstract": [
        {
          "text": "Returns a predicate that checks whether a category sample is equal to the provided set of values.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Int",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForSamples"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "equalTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(equalTo:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "predicateForSamples(equalTo:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluepredicateproviding/predicateforsamples(equalto:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePregnancyTestResult": {
      "abstract": [
        {
          "text": "Category values that indicate the results of a home pregnancy test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValuePregnancyTestResult"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePregnancyTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValuePregnancyTestResult"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValuePregnancyTestResult",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluepregnancytestresult"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePresence": {
      "abstract": [
        {
          "text": "Categories that indicate whether a symptom is present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValuePresence"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePresence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValuePresence"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValuePresence",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluepresence"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueProgesteroneTestResult": {
      "abstract": [
        {
          "text": "A category value that indicates the result from a home progesterone test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueProgesteroneTestResult"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueProgesteroneTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueProgesteroneTestResult"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueProgesteroneTestResult",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueprogesteronetestresult"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSeverity": {
      "abstract": [
        {
          "text": "Categories that represent the severity of a symptom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueSeverity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSeverity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSeverity"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSeverity",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueseverity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis": {
      "abstract": [
        {
          "text": "Categories that represent the result of a sleep analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysis"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysis"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysis",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysis"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueVaginalBleeding"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueVaginalBleeding"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueVaginalBleeding",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluevaginalbleeding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamples(with:value:)": {
      "abstract": [
        {
          "text": "Returns a predicate that checks a category sample’s value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForCategorySamples"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSComparisonPredicate",
          "text": "NSComparisonPredicate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPredicateOperatorType",
          "text": "Operator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamples(with:value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForCategorySamplesWithOperatorType:value:"
        }
      ],
      "role": "symbol",
      "title": "predicateForCategorySamples(with:value:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery/predicateforcategorysamples(with:value:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValue",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppetiteChanges",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleStandHour",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueAppleWalkingSteadinessEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueContraceptive",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueEnvironmentalAudioExposureEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueHeadphoneAudioExposureEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueLowCardioFitnessEvent",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueMenstrualFlow",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePregnancyTestResult",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePresence",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueProgesteroneTestResult",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSeverity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-category-sample-predicates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamples(with:value:)"
      ],
      "title": "Creating category sample predicates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-predicates",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(_:value:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(equalTo:)"
      ],
      "title": "Creating predicates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValue/title",
          "value": "HKCategoryValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppetiteChanges/title",
          "value": "HKCategoryValueAppetiteChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppetiteChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppetiteChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppetiteChanges/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppetiteChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow/title",
          "value": "HKCategoryValueMenstrualFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueMenstrualFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueMenstrualFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult/title",
          "value": "HKCategoryValueOvulationTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/title",
          "value": "HKCategoryValueVaginalBleeding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueVaginalBleeding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueVaginalBleeding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleStandHour/title",
          "value": "HKCategoryValueAppleStandHour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleStandHour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleStandHour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleStandHour/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleStandHour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent/title",
          "value": "HKCategoryValueAppleWalkingSteadinessEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueAppleWalkingSteadinessEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueAppleWalkingSteadinessEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueHeadphoneAudioExposureEvent/title",
          "value": "HKCategoryValueHeadphoneAudioExposureEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueHeadphoneAudioExposureEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueHeadphoneAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueHeadphoneAudioExposureEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueHeadphoneAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueEnvironmentalAudioExposureEvent/title",
          "value": "HKCategoryValueEnvironmentalAudioExposureEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueEnvironmentalAudioExposureEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueEnvironmentalAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueEnvironmentalAudioExposureEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueEnvironmentalAudioExposureEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueProgesteroneTestResult/title",
          "value": "HKCategoryValueProgesteroneTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueProgesteroneTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueProgesteroneTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueProgesteroneTestResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueProgesteroneTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueLowCardioFitnessEvent/title",
          "value": "HKCategoryValueLowCardioFitnessEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueLowCardioFitnessEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueLowCardioFitnessEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueLowCardioFitnessEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueLowCardioFitnessEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValuePregnancyTestResult/title",
          "value": "HKCategoryValuePregnancyTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValuePregnancyTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValuePregnancyTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValuePregnancyTestResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValuePregnancyTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSeverity/title",
          "value": "HKCategoryValueSeverity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSeverity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSeverity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSeverity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSeverity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality/title",
          "value": "HKCategoryValueCervicalMucusQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/title",
          "value": "HKCategoryValueSleepAnalysis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForCategorySamples(with:value:)/title",
          "value": "predicateForCategorySamplesWithOperatorType:value:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForCategorySamples(with:value:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForCategorySamplesWithOperatorType:value:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive/title",
          "value": "HKCategoryValueContraceptive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueContraceptive/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueContraceptive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValuePresence/title",
          "value": "HKCategoryValuePresence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValuePresence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValuePresence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValuePresence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValuePresence"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluepredicateproviding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
