{
  "abstract": [
    {
      "text": "A query that performs complex searches based on the correlation’s contents, and returns a snapshot of all matching samples.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKCorrelationQuery",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKCorrelationQuery"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCorrelationQuery"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HKCorrelationQuery"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKCorrelationQuery"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Correlation samples act as a container, grouping multiple quantity or category samples. While you can use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSample",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects to search for correlations, correlation queries allow more complex filtering based on the contained samples. Specifically, correlation queries let you provide a separate predicate for each of the sample types stored in the correlation. A correlation is  returned only if the correlation’s predicate and all of the sample predicates match.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Requesting-Permission-to-Share-and-Read",
          "level": 3,
          "text": "Requesting Permission to Share and Read",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Unlike other sample types, you do not request permission to share and read correlation types directly. Instead, you request permission to share and read each of the sample types contained within the correlation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When saving a correlation, the app must have permission to share all of the contained objects. If the app does not have permission to share one or more of the contained objects, the operation fails.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When your app queries for correlation data, HealthKit only returns samples that contain objects you have permission to read. If the app has permission to read only some of the contained objects, HealthKit still returns the correlation; however, the correlation appears to only contain those objects that your app has permission to read. HealthKit hides all of the other contained objects from your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Executing-Queries",
          "level": 3,
          "text": "Executing Queries",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You create a correlation query by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/init(type:predicate:samplePredicates:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " initializer. After the query is instantiated, you run it by calling the HealthKit store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. This method runs the query on an anonymous background queue. When the query is complete, it executes the results handler on the same background queue (though not necessarily the same thread). Typically, you dispatch these results back to the main thread to update your user interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example builds a correlation query that searches for food samples with more than 800 calories.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "var highCalorieFoods: [HKCorrelationQuery] = []",
                    " ",
                    "let highCalorie = HKQuantity(unit: HKUnit.kilocalorieUnit(),",
                    "                             doubleValue: 800.0);",
                    " ",
                    "let greaterThanHighCalorie = HKQuery.predicateForQuantitySamplesWithOperatorType(",
                    "    .GreaterThanOrEqualToPredicateOperatorType, quantity: highCalorie)",
                    " ",
                    "let energyConsumed = HKObjectType.quantityTypeForIdentifier(",
                    "    HKQuantityTypeIdentifierDietaryEnergyConsumed)",
                    " ",
                    "let samplePredicates = [energyConsumed: greaterThanHighCalorie]",
                    " ",
                    "let foodType = HKCorrelationType.correlationTypeForIdentifier(",
                    "    HKCorrelationTypeIdentifierFood)",
                    " ",
                    "let query = HKCorrelationQuery(type: foodType, predicate: nil, samplePredicates: samplePredicates)",
                    "{",
                    "    query, results, error in",
                    "    ",
                    "    if let correlations = results as? [HKCorrelationQuery] {",
                    "        for correlation in correlations {",
                    "            highCalorieFoods.append(correlation)",
                    "        }",
                    "    }",
                    "    else {",
                    "        // Provide proper error handling here...",
                    "        println(\"An error occurred while searching for high calorie food: \\(error.localizedDescription)\")",
                    "        abort()",
                    "    }",
                    "    ",
                    "    println(\"Found \\(highCalorieFoods.count) foods: \\(highCalorieFoods)\")",
                    "}",
                    " ",
                    "healthStore.executeQuery(query)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSMutableArray *highCalorieFoods = [NSMutableArray array];",
                    "HKQuantity *highCalorie = [HKQuantity quantityWithUnit:[HKUnit kilocalorieUnit]",
                    "                                           doubleValue:800.0];",
                    " ",
                    "NSPredicate *greaterThanHighCalorie =",
                    "[HKQuery predicateForQuantitySamplesWithOperatorType:",
                    " NSGreaterThanOrEqualToPredicateOperatorType quantity:highCalorie];",
                    " ",
                    "HKQuantityType *energyConsumed =",
                    "[HKObjectType quantityTypeForIdentifier:",
                    " HKQuantityTypeIdentifierDietaryEnergyConsumed];",
                    " ",
                    "NSDictionary *samplePredicates = @{energyConsumed : greaterThanHighCalorie};",
                    " ",
                    "HKCorrelationType *foodType =",
                    "[HKCorrelationType correlationTypeForIdentifier:HKCorrelationTypeIdentifierFood];",
                    " ",
                    "HKCorrelationQuery *query =",
                    "[[HKCorrelationQuery alloc]",
                    " initWithType:foodType predicate:nil",
                    " samplePredicates:samplePredicates",
                    " completion:^(HKCorrelationQuery *query, NSArray *correlations, NSError *error) {",
                    "     if (correlations == nil) {",
                    "         // Provide proper error handling here...",
                    "         NSLog(@\"An error occurred while searching for high calorie food: %@\",",
                    "              error.localizedDescription);",
                    "         abort();",
                    "     }",
                    "     for (HKCorrelation *correlation in correlations) {",
                    "         [highCalorieFoods addObject:correlation];",
                    "     }",
                    "     NSLog(@\"Found %lu foods: %@\", (unsigned long)[highCalorieFoods count], highCalorieFoods);",
                    " ",
                    " }];",
                    " ",
                    "[self.healthStore executeQuery:query];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "It begins by setting up an array to store our high calorie foods. Next, the sample code creates a predicate that matches quantities greater than or equal to 800 kcal. It then creates a dictionary using a quantity type object for dietary energy consumed as the key and the newly-created predicate as the value. It uses this dictionary as the sample predicates for a correlation query.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the query’s completion handler, the sample code first checks to see if an error occurred. If no errors occurred, it adds the results to the array of high calorie foods. Then it logs the number of matching samples found, and the contents of the high calorie foods array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Once the sample code finishes declaring the completion handler, the query is ready to use. The sample code simply executes the query on the HeathKit store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Subclassing-Correlation-Queries",
          "level": 3,
          "text": "Subclassing Correlation Queries",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Like many HealthKit classes, the ",
              "type": "text"
            },
            {
              "code": "HKCorrelationQuery",
              "type": "codeVoice"
            },
            {
              "text": " class should not be subclassed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nspredicate": {
      "abstract": [
        {
          "text": "A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nspredicate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPredicate",
      "type": "topic",
      "url": "/documentation/foundation/nspredicate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery": {
      "abstract": [
        {
          "text": "A query that performs complex searches based on the correlation’s contents, and returns a snapshot of all matching samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCorrelationQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCorrelationQuery"
        }
      ],
      "role": "symbol",
      "title": "HKCorrelationQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkcorrelationquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/correlationType": {
      "abstract": [
        {
          "text": "The type of correlation to search for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "correlationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCorrelationType",
          "text": "HKCorrelationType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/correlationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "correlationType"
        }
      ],
      "role": "symbol",
      "title": "correlationType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcorrelationquery/correlationtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/init(type:predicate:samplePredicates:completion:)": {
      "abstract": [
        {
          "text": "Instantiates and returns a correlation query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCorrelationType",
          "text": "HKCorrelationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "samplePredicates"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSampleType",
          "text": "HKSampleType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCorrelationQuery",
          "text": "HKCorrelationQuery"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKCorrelation",
          "text": "HKCorrelation"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/init(type:predicate:samplePredicates:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithType:predicate:samplePredicates:completion:"
        }
      ],
      "role": "symbol",
      "title": "init(type:predicate:samplePredicates:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkcorrelationquery/init(type:predicate:samplepredicates:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/samplePredicates": {
      "abstract": [
        {
          "text": "A dictionary whose keys are ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instances and whose values are ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nspredicate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "samplePredicates"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSampleType",
          "text": "HKSampleType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/samplePredicates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "samplePredicates"
        }
      ],
      "role": "symbol",
      "title": "samplePredicates",
      "type": "topic",
      "url": "/documentation/healthkit/hkcorrelationquery/samplepredicates"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)": {
      "abstract": [
        {
          "text": "Starts executing the provided query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuery",
          "text": "HKQuery"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executeQuery:"
        }
      ],
      "role": "symbol",
      "title": "execute(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/execute(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery": {
      "abstract": [
        {
          "text": "An abstract class for all the query classes in HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuery"
        }
      ],
      "role": "symbol",
      "title": "HKQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQueryDescriptor": {
      "abstract": [
        {
          "text": "A descriptor that specifies a set of samples based on the data type and a predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSample": {
      "abstract": [
        {
          "text": "A HealthKit sample represents a piece of data associated with a start and end time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSample"
        }
      ],
      "role": "symbol",
      "title": "HKSample",
      "type": "topic",
      "url": "/documentation/healthkit/hksample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery": {
      "abstract": [
        {
          "text": "A general query that returns a snapshot of all the matching samples currently saved in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSampleQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSampleQuery"
        }
      ],
      "role": "symbol",
      "title": "HKSampleQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads samples using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSampleQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSampleQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKSampleQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplequerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSampleType": {
      "abstract": [
        {
          "text": "An abstract superclass for all classes that identify a specific type of sample when working with the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSampleType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSampleType"
        }
      ],
      "role": "symbol",
      "title": "HKSampleType",
      "type": "topic",
      "url": "/documentation/healthkit/hksampletype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit": {
      "abstract": [
        {
          "text": "Use queries to request sample data from HealthKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit",
      "kind": "article",
      "role": "article",
      "title": "Reading data from HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit/reading-data-from-healthkit"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuery"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Basic-queries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuery"
      ],
      "title": "Basic queries"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Correlation-Queries",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/init(type:predicate:samplePredicates:completion:)"
      ],
      "title": "Creating Correlation Queries"
    },
    {
      "anchor": "Getting-Property-Data",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/correlationType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/samplePredicates"
      ],
      "title": "Getting Property Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCorrelationQuery"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Correlation-Queries",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/init(type:predicate:samplePredicates:completion:)"
              ],
              "title": "Creating Correlation Queries"
            },
            {
              "anchor": "Getting-Property-Data",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/correlationType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery/samplePredicates"
              ],
              "title": "Getting Property Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuery"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Basic-queries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQueryDescriptor",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuery"
              ],
              "title": "Basic queries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKCorrelationQuery"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HKQuery",
                    "text": "HKQuery"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1execute(_:)/title",
          "value": "executeQuery:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1execute(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "executeQuery:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/title",
          "value": "HKSampleQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleType/title",
          "value": "HKSampleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery~1correlationType/title",
          "value": "correlationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery~1correlationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "correlationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery/title",
          "value": "HKCorrelationQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/title",
          "value": "HKSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title",
          "value": "HKQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery~1init(type:predicate:samplePredicates:completion:)/title",
          "value": "initWithType:predicate:samplePredicates:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery~1init(type:predicate:samplePredicates:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithType:predicate:samplePredicates:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryDescriptor/title",
          "value": "HKQueryDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQueryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQueryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery~1samplePredicates/title",
          "value": "samplePredicates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery~1samplePredicates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "samplePredicates"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcorrelationquery"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcorrelationquery"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
