{
  "abstract": [
    {
      "text": "Values that indicate the placement of the device that measured a sample.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKDevicePlacementSide",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKDevicePlacementSide"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKDevicePlacementSide"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "HKDevicePlacementSide"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSide"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide": {
      "abstract": [
        {
          "text": "Values that indicate the placement of the device that measured a sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSide"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSide"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/central": {
      "abstract": [
        {
          "text": "A device predominately located near the center of the body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "central"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/central",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSideCentral"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide.central",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/central"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/init(rawvalue:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/left": {
      "abstract": [
        {
          "text": "A device predominately located on the left side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSideLeft"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide.left",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/left"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/right": {
      "abstract": [
        {
          "text": "A device predominately located on the right side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSideRight"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide.right",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/right"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/unknown": {
      "abstract": [
        {
          "text": "The system couldn’t determine the device’s placement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSideUnknown"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide.unknown",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/unknown"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated": {
      "abstract": [
        {
          "text": "The key for metadata indicating whether the system had data from a sufficient amount of calibrated sensors when recording the sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAppleDeviceCalibrated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAppleDeviceCalibrated"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyAppleDeviceCalibrated",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyappledevicecalibrated"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName": {
      "abstract": [
        {
          "text": "The name of the manufacturer of the device that took this reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDeviceManufacturerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDeviceManufacturerName"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyDeviceManufacturerName",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeydevicemanufacturername"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName": {
      "abstract": [
        {
          "text": "The name of the device that took this reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDeviceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDeviceName"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyDeviceName",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeydevicename"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide": {
      "abstract": [
        {
          "text": "The key for metadata indicating the placement of the device that measured a sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDevicePlacementSide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDevicePlacementSide"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyDevicePlacementSide",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeydeviceplacementside"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber": {
      "abstract": [
        {
          "text": "The key for the serial number of the device that generated the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDeviceSerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDeviceSerialNumber"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyDeviceSerialNumber",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeydeviceserialnumber"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature": {
      "abstract": [
        {
          "text": "A digital signature that can be used to validate the origin of the HealthKit object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDigitalSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyDigitalSignature"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyDigitalSignature",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeydigitalsignature"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier": {
      "abstract": [
        {
          "text": "The device identifier portion of a device’s UDI (unique device identifier).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyUDIDeviceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyUDIDeviceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyUDIDeviceIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyudideviceidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier": {
      "abstract": [
        {
          "text": "The production identifier portion of a device’s UDI (unique device identifier).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyUDIProductionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyUDIProductionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyUDIProductionIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyudiproductionidentifier"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Device-Information-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated"
      ],
      "title": "Device Information Keys"
    }
  ],
  "topicSections": [
    {
      "anchor": "Placements",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/central",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/left",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/right",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/unknown"
      ],
      "title": "Placements"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKDevicePlacementSide"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Placements",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/central",
                "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/left",
                "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/right",
                "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/unknown"
              ],
              "title": "Placements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Device-Information-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated"
              ],
              "title": "Device Information Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKDevicePlacementSide"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1left/title",
          "value": "HKDevicePlacementSideLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceManufacturerName/title",
          "value": "HKMetadataKeyDeviceManufacturerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceManufacturerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyDeviceManufacturerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDigitalSignature/title",
          "value": "HKMetadataKeyDigitalSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDigitalSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyDigitalSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceName/title",
          "value": "HKMetadataKeyDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDevicePlacementSide/title",
          "value": "HKMetadataKeyDevicePlacementSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDevicePlacementSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyDevicePlacementSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceSerialNumber/title",
          "value": "HKMetadataKeyDeviceSerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceSerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyDeviceSerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleDeviceCalibrated/title",
          "value": "HKMetadataKeyAppleDeviceCalibrated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleDeviceCalibrated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyAppleDeviceCalibrated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIDeviceIdentifier/title",
          "value": "HKMetadataKeyUDIDeviceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIDeviceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyUDIDeviceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1right/title",
          "value": "HKDevicePlacementSideRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIProductionIdentifier/title",
          "value": "HKMetadataKeyUDIProductionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIProductionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyUDIProductionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1unknown/title",
          "value": "HKDevicePlacementSideUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1central/title",
          "value": "HKDevicePlacementSideCentral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1central/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideCentral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/title",
          "value": "HKDevicePlacementSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSide"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkdeviceplacementside"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkdeviceplacementside"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
