{
  "abstract": [
    {
      "text": "The FHIR version.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKFHIRVersion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKFHIRVersion"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKFHIRVersion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HKFHIRVersion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKFHIRVersion"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to represent the version of the Fast Healthcare Interoperability Resources (FHIR) standard used to create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sample.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRRelease": {
      "abstract": [
        {
          "text": "Official releases of the FHIR specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFHIRRelease"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRRelease",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRRelease"
        }
      ],
      "role": "symbol",
      "title": "HKFHIRRelease",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirrelease"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource": {
      "abstract": [
        {
          "text": "An object containing Fast Healthcare Interoperability Resources (FHIR) data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFHIRResource"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResource"
        }
      ],
      "role": "symbol",
      "title": "HKFHIRResource",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/data": {
      "abstract": [
        {
          "text": "The JSON representation of the FHIR resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/data"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/fhirVersion": {
      "abstract": [
        {
          "text": "The FHIR version used by this resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fhirVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKFHIRVersion",
          "text": "HKFHIRVersion"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/fhirVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FHIRVersion"
        }
      ],
      "role": "symbol",
      "title": "fhirVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/fhirversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/identifier": {
      "abstract": [
        {
          "text": "The value from the FHIR resource’s ",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/identifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/resourceType": {
      "abstract": [
        {
          "text": "The value from the FHIR resource’s ",
          "type": "text"
        },
        {
          "code": "resourceType",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/resourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resourceType"
        }
      ],
      "role": "symbol",
      "title": "resourceType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/resourcetype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/sourceURL": {
      "abstract": [
        {
          "text": "The full URL for the source of the FHIR resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/sourceURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceURL"
        }
      ],
      "role": "symbol",
      "title": "sourceURL",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/sourceurl"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType": {
      "abstract": [
        {
          "text": "The FHIR resource types supported in HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceType"
        }
      ],
      "role": "symbol",
      "title": "HKFHIRResourceType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion": {
      "abstract": [
        {
          "text": "The FHIR version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFHIRVersion"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRVersion"
        }
      ],
      "role": "symbol",
      "title": "HKFHIRVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/fhirRelease": {
      "abstract": [
        {
          "text": "An official release of the FHIR specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fhirRelease"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRRelease",
          "text": "HKFHIRRelease"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/fhirRelease",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FHIRRelease"
        }
      ],
      "role": "symbol",
      "title": "fhirRelease",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion/fhirrelease"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/init(fromVersionString:)": {
      "abstract": [
        {
          "text": "Creates an FHIR version object from a string representation of the version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromVersionString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/init(fromVersionString:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "versionFromVersionString:error:"
        }
      ],
      "role": "symbol",
      "title": "init(fromVersionString:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion/init(fromversionstring:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/majorVersion": {
      "abstract": [
        {
          "text": "The standard’s major version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "majorVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/majorVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "majorVersion"
        }
      ],
      "role": "symbol",
      "title": "majorVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion/majorversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/minorVersion": {
      "abstract": [
        {
          "text": "The standard’s minor version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minorVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/minorVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minorVersion"
        }
      ],
      "role": "symbol",
      "title": "minorVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion/minorversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/patchVersion": {
      "abstract": [
        {
          "text": "The standard’s patch version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patchVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/patchVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "patchVersion"
        }
      ],
      "role": "symbol",
      "title": "patchVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion/patchversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/primaryDSTU2()": {
      "abstract": [
        {
          "text": "Returns the primary Second Draft Standard for Trial Use (DSTU2) version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryDSTU2"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/primaryDSTU2()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryDSTU2Version"
        }
      ],
      "role": "symbol",
      "title": "primaryDSTU2()",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion/primarydstu2()"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/primaryR4()": {
      "abstract": [
        {
          "text": "Returns the primary Release 4 (R4) version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryR4"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/primaryR4()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryR4Version"
        }
      ],
      "role": "symbol",
      "title": "primaryR4()",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion/primaryr4()"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/stringRepresentation": {
      "abstract": [
        {
          "text": "A string representation of the version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringRepresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/stringRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringRepresentation"
        }
      ],
      "role": "symbol",
      "title": "stringRepresentation",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion/stringrepresentation"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-FHIR-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/identifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/fhirVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/resourceType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/sourceURL",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/data"
      ],
      "title": "Accessing FHIR Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Version-Objects",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/init(fromVersionString:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/primaryDSTU2()",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/primaryR4()"
      ],
      "title": "Creating Version Objects"
    },
    {
      "anchor": "Accessing-Version-Data",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/majorVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/minorVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/patchVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/stringRepresentation"
      ],
      "title": "Accessing Version Data"
    },
    {
      "anchor": "Accessing-the-Release",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/fhirRelease",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRRelease"
      ],
      "title": "Accessing the Release"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKFHIRVersion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Version-Objects",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/init(fromVersionString:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/primaryDSTU2()",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/primaryR4()"
              ],
              "title": "Creating Version Objects"
            },
            {
              "anchor": "Accessing-Version-Data",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/majorVersion",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/minorVersion",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/patchVersion",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/stringRepresentation"
              ],
              "title": "Accessing Version Data"
            },
            {
              "anchor": "Accessing-the-Release",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion/fhirRelease",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRRelease"
              ],
              "title": "Accessing the Release"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-FHIR-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/identifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/fhirVersion",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/resourceType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/sourceURL",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/data"
              ],
              "title": "Accessing FHIR Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKFHIRVersion"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1resourceType/title",
          "value": "resourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1resourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource/title",
          "value": "HKFHIRResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1minorVersion/title",
          "value": "minorVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1minorVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minorVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1primaryDSTU2()/title",
          "value": "primaryDSTU2Version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1primaryDSTU2()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "primaryDSTU2Version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1stringRepresentation/title",
          "value": "stringRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1stringRepresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stringRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion/title",
          "value": "HKFHIRVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRRelease/title",
          "value": "HKFHIRRelease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRRelease/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRRelease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRRelease/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRRelease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1init(fromVersionString:)/title",
          "value": "versionFromVersionString:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1init(fromVersionString:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "versionFromVersionString:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/title",
          "value": "HKFHIRResourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1fhirRelease/title",
          "value": "FHIRRelease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1fhirRelease/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FHIRRelease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1majorVersion/title",
          "value": "majorVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1majorVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "majorVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1patchVersion/title",
          "value": "patchVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1patchVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "patchVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1sourceURL/title",
          "value": "sourceURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1sourceURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1primaryR4()/title",
          "value": "primaryR4Version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion~1primaryR4()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "primaryR4Version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1fhirVersion/title",
          "value": "FHIRVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1fhirVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FHIRVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkfhirversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkfhirversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
