{
  "abstract": [
    {
      "text": "The FHIR resource types supported in HealthKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@HKFHIRResourceType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKFHIRResourceType"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKFHIRResourceType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "HKFHIRResourceType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.healthkit/documentation/HealthKit/accessing-health-records"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/data": {
      "abstract": [
        {
          "text": "The JSON representation of the FHIR resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/data"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/fhirVersion": {
      "abstract": [
        {
          "text": "The FHIR version used by this resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fhirVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKFHIRVersion",
          "text": "HKFHIRVersion"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/fhirVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FHIRVersion"
        }
      ],
      "role": "symbol",
      "title": "fhirVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/fhirversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/identifier": {
      "abstract": [
        {
          "text": "The value from the FHIR resource’s ",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/identifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/resourceType": {
      "abstract": [
        {
          "text": "The value from the FHIR resource’s ",
          "type": "text"
        },
        {
          "code": "resourceType",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/resourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resourceType"
        }
      ],
      "role": "symbol",
      "title": "resourceType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/resourcetype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/sourceURL": {
      "abstract": [
        {
          "text": "The full URL for the source of the FHIR resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/sourceURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceURL"
        }
      ],
      "role": "symbol",
      "title": "sourceURL",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresource/sourceurl"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType": {
      "abstract": [
        {
          "text": "The FHIR resource types supported in HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceType"
        }
      ],
      "role": "symbol",
      "title": "HKFHIRResourceType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/allergyIntolerance": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for allergies and intolerances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allergyIntolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/allergyIntolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeAllergyIntolerance"
        }
      ],
      "role": "symbol",
      "title": "allergyIntolerance",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/allergyintolerance"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/condition": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for a condition, problem, diagnosis, or other event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "condition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/condition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeCondition"
        }
      ],
      "role": "symbol",
      "title": "condition",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/condition"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/coverage": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources containing information about the user’s insurance coverage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coverage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/coverage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeCoverage"
        }
      ],
      "role": "symbol",
      "title": "coverage",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/coverage"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for findings and interpretation of diagnostic tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diagnosticReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeDiagnosticReport"
        }
      ],
      "role": "symbol",
      "title": "diagnosticReport",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/diagnosticreport"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for document references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentReference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeDocumentReference"
        }
      ],
      "role": "symbol",
      "title": "documentReference",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/documentreference"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/immunization": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for the administration of vaccines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "immunization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/immunization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeImmunization"
        }
      ],
      "role": "symbol",
      "title": "immunization",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/immunization"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Returns a new resource type for the provided string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/init(rawvalue:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationDispense": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for the delivery of medication (usually in response to a prescription).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationDispense"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationDispense",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeMedicationDispense"
        }
      ],
      "role": "symbol",
      "title": "medicationDispense",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/medicationdispense"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationOrder": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for prescriptions or other orders for medication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeMedicationOrder"
        }
      ],
      "role": "symbol",
      "title": "medicationOrder",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/medicationorder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationRequest": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for prescriptions or other orders or requests for medication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeMedicationRequest"
        }
      ],
      "role": "symbol",
      "title": "medicationRequest",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/medicationrequest"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationStatement": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for statements about medication taken by the patient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medicationStatement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationStatement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeMedicationStatement"
        }
      ],
      "role": "symbol",
      "title": "medicationStatement",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/medicationstatement"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/observation": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for medical observations, including lab results and vital signs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/observation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeObservation"
        }
      ],
      "role": "symbol",
      "title": "observation",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/observation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/procedure": {
      "abstract": [
        {
          "text": "A type that identifies FHIR resources for procedures performed on the patient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "procedure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKFHIRResourceType",
          "text": "HKFHIRResourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/procedure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRResourceTypeProcedure"
        }
      ],
      "role": "symbol",
      "title": "procedure",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirresourcetype/procedure"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion": {
      "abstract": [
        {
          "text": "The FHIR version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFHIRVersion"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFHIRVersion"
        }
      ],
      "role": "symbol",
      "title": "HKFHIRVersion",
      "type": "topic",
      "url": "/documentation/healthkit/hkfhirversion"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/accessing-health-records": {
      "abstract": [
        {
          "text": "Read clinical record data from the HealthKit store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/accessing-health-records",
      "kind": "article",
      "role": "article",
      "title": "Accessing Health Records",
      "type": "topic",
      "url": "/documentation/healthkit/accessing-health-records"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-FHIR-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/identifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/fhirVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/resourceType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/sourceURL",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/data"
      ],
      "title": "Accessing FHIR Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resource-Types",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/allergyIntolerance",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/condition",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/immunization",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationOrder",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationDispense",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationStatement",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationRequest",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/observation",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/procedure",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/coverage"
      ],
      "title": "Resource Types"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKFHIRResourceType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resource-Types",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/allergyIntolerance",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/condition",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/diagnosticReport",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/documentReference",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/immunization",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationOrder",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationDispense",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationStatement",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/medicationRequest",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/observation",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/procedure",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResourceType/coverage"
              ],
              "title": "Resource Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-FHIR-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/identifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/fhirVersion",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRVersion",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/resourceType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/sourceURL",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFHIRResource/data"
              ],
              "title": "Accessing FHIR Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKFHIRResourceType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationRequest/title",
          "value": "HKFHIRResourceTypeMedicationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeMedicationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1resourceType/title",
          "value": "resourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1resourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationOrder/title",
          "value": "HKFHIRResourceTypeMedicationOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeMedicationOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationStatement/title",
          "value": "HKFHIRResourceTypeMedicationStatement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationStatement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeMedicationStatement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1allergyIntolerance/title",
          "value": "HKFHIRResourceTypeAllergyIntolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1allergyIntolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeAllergyIntolerance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1fhirVersion/title",
          "value": "FHIRVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1fhirVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FHIRVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1coverage/title",
          "value": "HKFHIRResourceTypeCoverage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1coverage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeCoverage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1procedure/title",
          "value": "HKFHIRResourceTypeProcedure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1procedure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeProcedure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationDispense/title",
          "value": "HKFHIRResourceTypeMedicationDispense"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1medicationDispense/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeMedicationDispense"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1diagnosticReport/title",
          "value": "HKFHIRResourceTypeDiagnosticReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1diagnosticReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeDiagnosticReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1condition/title",
          "value": "HKFHIRResourceTypeCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1condition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1sourceURL/title",
          "value": "sourceURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1sourceURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/title",
          "value": "HKFHIRResourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1observation/title",
          "value": "HKFHIRResourceTypeObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1observation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResource~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1documentReference/title",
          "value": "HKFHIRResourceTypeDocumentReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1documentReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeDocumentReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1immunization/title",
          "value": "HKFHIRResourceTypeImmunization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRResourceType~1immunization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRResourceTypeImmunization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion/title",
          "value": "HKFHIRVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFHIRVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFHIRVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkfhirresourcetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkfhirresourcetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
