{"metadata":{"roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":[{"introducedAt":"8.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"8.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"unavailable":false,"introducedAt":"13.0","name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"13.0","name":"macOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"2.0","name":"watchOS","beta":false,"deprecated":false}],"title":"HKMetadataKeyUDIDeviceIdentifier","externalID":"c:@HKMetadataKeyUDIDeviceIdentifier","modules":[{"name":"HealthKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"}],"symbolKind":"var"},"seeAlsoSections":[{"anchor":"Device-Information-Keys","title":"Device Information Keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated"],"generated":true}],"variants":[{"paths":["/documentation/healthkit/hkmetadatakeyudideviceidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkmetadatakeyudideviceidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"The device identifier can be used to reference the GUDID (Globally Unique Device Identification Database)."}],"type":"paragraph"},{"inlineContent":[{"text":"This key takes a string value.","type":"text"}],"type":"paragraph"},{"style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"In iOS 9.0 and later, the use of this key is discouraged. Use the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDevice","type":"reference"},{"text":" class instead.","type":"text"}],"type":"paragraph"}],"name":"Note","type":"aside"}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier","interfaceLanguage":"swift"},"abstract":[{"text":"The device identifier portion of a device’s UDI (unique device identifier).","type":"text"}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","role":"symbol","abstract":[{"text":"The key for metadata indicating the placement of the device that measured a sample.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDevicePlacementSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"HKMetadataKeyDevicePlacementSide","type":"topic","url":"/documentation/healthkit/hkmetadatakeydeviceplacementside","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDevicePlacementSide"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier":{"title":"HKMetadataKeyUDIDeviceIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"}],"abstract":[{"type":"text","text":"The device identifier portion of a device’s UDI (unique device identifier)."}],"url":"/documentation/healthkit/hkmetadatakeyudideviceidentifier","type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKDevice":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDevice","url":"/documentation/healthkit/hkdevice","title":"HKDevice","abstract":[{"type":"text","text":"A device that generates data for HealthKit."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKDevice"}],"navigatorTitle":[{"kind":"identifier","text":"HKDevice"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated","abstract":[{"text":"The key for metadata indicating whether the system had data from a sufficient amount of calibrated sensors when recording the sample.","type":"text"}],"title":"HKMetadataKeyAppleDeviceCalibrated","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyAppleDeviceCalibrated"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"HKMetadataKeyAppleDeviceCalibrated","kind":"identifier"}],"kind":"symbol","url":"/documentation/healthkit/hkmetadatakeyappledevicecalibrated"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName":{"abstract":[{"text":"The name of the manufacturer of the device that took this reading.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKMetadataKeyDeviceManufacturerName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName","title":"HKMetadataKeyDeviceManufacturerName","url":"/documentation/healthkit/hkmetadatakeydevicemanufacturername","navigatorTitle":[{"text":"HKMetadataKeyDeviceManufacturerName","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","title":"NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","url":"/documentation/foundation/nsstring","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber":{"url":"/documentation/healthkit/hkmetadatakeydeviceserialnumber","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyDeviceSerialNumber","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber","type":"topic","abstract":[{"type":"text","text":"The key for the serial number of the device that generated the data."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide":{"url":"/documentation/healthkit/hkdeviceplacementside","title":"HKDevicePlacementSide","type":"topic","role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","navigatorTitle":[{"kind":"identifier","text":"HKDevicePlacementSide"}],"abstract":[{"text":"Values that indicate the placement of the device that measured a sample.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKDevicePlacementSide"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature":{"type":"topic","url":"/documentation/healthkit/hkmetadatakeydigitalsignature","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKMetadataKeyDigitalSignature","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"A digital signature that can be used to validate the origin of the HealthKit object.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDigitalSignature"}],"title":"HKMetadataKeyDigitalSignature"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","title":"String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName":{"url":"/documentation/healthkit/hkmetadatakeydevicename","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyDeviceName","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","type":"topic","abstract":[{"type":"text","text":"The name of the device that took this reading."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDeviceName"}]},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier":{"url":"/documentation/healthkit/hkmetadatakeyudiproductionidentifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyUDIProductionIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","type":"topic","abstract":[{"type":"text","text":"The production identifier portion of a device’s UDI (unique device identifier)."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"8.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"8.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.0","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"13.0","beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false,"unavailable":false},{"introducedAt":"2.0","beta":false,"name":"watchOS","deprecated":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"value":"HKMetadataKeyUDIDeviceIdentifier","op":"replace","path":"/metadata/title"},{"value":"var","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"HKMetadataKeyUDIDeviceIdentifier","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Device Information Keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated"],"generated":true,"anchor":"Device-Information-Keys"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"HKMetadataKeyDevicePlacementSide","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDevicePlacementSide/title"},{"value":[{"text":"HKMetadataKeyDevicePlacementSide","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDevicePlacementSide/fragments"},{"value":"HKMetadataKeyUDIDeviceIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIDeviceIdentifier/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIDeviceIdentifier/fragments"},{"value":"HKDevice","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/title"},{"value":[{"text":"HKDevice","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/fragments"},{"value":[{"text":"HKDevice","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/navigatorTitle"},{"value":"HKMetadataKeyAppleDeviceCalibrated","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleDeviceCalibrated/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyAppleDeviceCalibrated"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleDeviceCalibrated/fragments"},{"value":"HKMetadataKeyDeviceManufacturerName","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceManufacturerName/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyDeviceManufacturerName"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceManufacturerName/fragments"},{"value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"value":"HKMetadataKeyDeviceSerialNumber","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceSerialNumber/title"},{"value":[{"text":"HKMetadataKeyDeviceSerialNumber","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceSerialNumber/fragments"},{"value":"HKDevicePlacementSide","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/title"},{"value":[{"kind":"identifier","text":"HKDevicePlacementSide"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/fragments"},{"value":[{"text":"HKDevicePlacementSide","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/navigatorTitle"},{"value":"HKMetadataKeyDigitalSignature","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDigitalSignature/title"},{"value":[{"text":"HKMetadataKeyDigitalSignature","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDigitalSignature/fragments"},{"value":"HKMetadataKeyDeviceName","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceName/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyDeviceName"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceName/fragments"},{"value":"HKMetadataKeyUDIProductionIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIProductionIdentifier/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIProductionIdentifier/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}