{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyBodyTemperatureSensorLocation": {
      "abstract": [
        {
          "text": "The location where a specific body temperature reading was taken.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyBodyTemperatureSensorLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyBodyTemperatureSensorLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyBodyTemperatureSensorLocation"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyBodyTemperatureSensorLocation",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeybodytemperaturesensorlocation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext": {
      "abstract": [
        {
          "text": "The user’s activity level when the heart rate sample was measured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateMotionContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateMotionContext"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyHeartRateMotionContext",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyheartratemotioncontext"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryActivityDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateRecoveryActivityDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryActivityDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateRecoveryActivityDuration"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyHeartRateRecoveryActivityDuration",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyheartraterecoveryactivityduration"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryActivityType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateRecoveryActivityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateRecoveryActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyHeartRateRecoveryActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyheartraterecoveryactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyheartraterecoverymaxobservedrecoveryheartrate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryTestType": {
      "abstract": [
        {
          "text": "The type of test that the source used to calculate a person’s heart-rate recovery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateRecoveryTestType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryTestType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateRecoveryTestType"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyHeartRateRecoveryTestType",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyheartraterecoverytesttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateSensorLocation": {
      "abstract": [
        {
          "text": "The location where a specific heart rate reading was taken.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateSensorLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateSensorLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyHeartRateSensorLocation"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyHeartRateSensorLocation",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyheartratesensorlocation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyVO2MaxTestType": {
      "abstract": [
        {
          "text": "The method used to calculate the user’s VO2 max rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyVO2MaxTestType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyVO2MaxTestType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyVO2MaxTestType"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyVO2MaxTestType",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyvo2maxtesttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathAverageHeartRate": {
      "abstract": [
        {
          "text": "The key path for the sample’s average heart rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathAverageHeartRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathAverageHeartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathAverageHeartRate"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathAverageHeartRate",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathaverageheartrate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vitals-Sensors-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyBodyTemperatureSensorLocation",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateSensorLocation",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathAverageHeartRate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryActivityDuration",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryTestType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyVO2MaxTestType"
      ],
      "title": "Vitals Sensors Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vitals-Sensors-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyBodyTemperatureSensorLocation",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateSensorLocation",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateMotionContext",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathAverageHeartRate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryActivityDuration",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryActivityType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyHeartRateRecoveryTestType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyVO2MaxTestType"
              ],
              "title": "Vitals Sensors Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateMotionContext/title",
          "value": "HKMetadataKeyHeartRateMotionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateMotionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateMotionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateRecoveryActivityType/title",
          "value": "HKMetadataKeyHeartRateRecoveryActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateRecoveryActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateRecoveryActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateSensorLocation/title",
          "value": "HKMetadataKeyHeartRateSensorLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateSensorLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateSensorLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateRecoveryActivityDuration/title",
          "value": "HKMetadataKeyHeartRateRecoveryActivityDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateRecoveryActivityDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateRecoveryActivityDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyVO2MaxTestType/title",
          "value": "HKMetadataKeyVO2MaxTestType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyVO2MaxTestType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyVO2MaxTestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathAverageHeartRate/title",
          "value": "HKPredicateKeyPathAverageHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathAverageHeartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathAverageHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateRecoveryTestType/title",
          "value": "HKMetadataKeyHeartRateRecoveryTestType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateRecoveryTestType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateRecoveryTestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyBodyTemperatureSensorLocation/title",
          "value": "HKMetadataKeyBodyTemperatureSensorLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyBodyTemperatureSensorLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyBodyTemperatureSensorLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate/title",
          "value": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyHeartRateRecoveryMaxObservedRecoveryHeartRate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkmetadatakeyheartraterecoverymaxobservedrecoveryheartrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkmetadatakeyheartraterecoverymaxobservedrecoveryheartrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
