{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceManufacturerName"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This key takes a string value."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"In iOS 9.0 and later, the use of this key is discouraged. Use the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDevice","type":"reference"},{"text":" class instead.","type":"text"}]}],"name":"Note","type":"aside"}],"kind":"content"}],"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkmetadatakeydevicemanufacturername"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkmetadatakeydevicemanufacturername"]}],"abstract":[{"type":"text","text":"The name of the manufacturer of the device that took this reading."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated"],"anchor":"Device-Information-Keys","generated":true,"title":"Device Information Keys"}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceManufacturerName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDeviceManufacturerName"}],"modules":[{"name":"HealthKit"}],"symbolKind":"var","externalID":"c:@HKMetadataKeyDeviceManufacturerName","platforms":[{"unavailable":false,"introducedAt":"8.0","deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"introducedAt":"8.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false},{"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"watchOS","beta":false}],"roleHeading":"Global Variable","title":"HKMetadataKeyDeviceManufacturerName","role":"symbol"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"references":{"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","title":"String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName":{"url":"/documentation/healthkit/hkmetadatakeydevicename","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyDeviceName","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","type":"topic","abstract":[{"type":"text","text":"The name of the device that took this reading."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDeviceName"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKDevice":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDevice","url":"/documentation/healthkit/hkdevice","title":"HKDevice","abstract":[{"type":"text","text":"A device that generates data for HealthKit."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKDevice"}],"navigatorTitle":[{"kind":"identifier","text":"HKDevice"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier":{"url":"/documentation/healthkit/hkmetadatakeyudiproductionidentifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyUDIProductionIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","type":"topic","abstract":[{"type":"text","text":"The production identifier portion of a device’s UDI (unique device identifier)."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated","abstract":[{"text":"The key for metadata indicating whether the system had data from a sufficient amount of calibrated sensors when recording the sample.","type":"text"}],"title":"HKMetadataKeyAppleDeviceCalibrated","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyAppleDeviceCalibrated"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"HKMetadataKeyAppleDeviceCalibrated","kind":"identifier"}],"kind":"symbol","url":"/documentation/healthkit/hkmetadatakeyappledevicecalibrated"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber":{"url":"/documentation/healthkit/hkmetadatakeydeviceserialnumber","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyDeviceSerialNumber","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber","type":"topic","abstract":[{"type":"text","text":"The key for the serial number of the device that generated the data."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide":{"url":"/documentation/healthkit/hkdeviceplacementside","title":"HKDevicePlacementSide","type":"topic","role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","navigatorTitle":[{"kind":"identifier","text":"HKDevicePlacementSide"}],"abstract":[{"text":"Values that indicate the placement of the device that measured a sample.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKDevicePlacementSide"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","title":"NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","url":"/documentation/foundation/nsstring","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName":{"abstract":[{"text":"The name of the manufacturer of the device that took this reading.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKMetadataKeyDeviceManufacturerName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName","title":"HKMetadataKeyDeviceManufacturerName","url":"/documentation/healthkit/hkmetadatakeydevicemanufacturername","navigatorTitle":[{"text":"HKMetadataKeyDeviceManufacturerName","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier":{"title":"HKMetadataKeyUDIDeviceIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"}],"abstract":[{"type":"text","text":"The device identifier portion of a device’s UDI (unique device identifier)."}],"url":"/documentation/healthkit/hkmetadatakeyudideviceidentifier","type":"topic","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","role":"symbol","abstract":[{"text":"The key for metadata indicating the placement of the device that measured a sample.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDevicePlacementSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"HKMetadataKeyDevicePlacementSide","type":"topic","url":"/documentation/healthkit/hkmetadatakeydeviceplacementside","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDevicePlacementSide"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature":{"type":"topic","url":"/documentation/healthkit/hkmetadatakeydigitalsignature","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKMetadataKeyDigitalSignature","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"A digital signature that can be used to validate the origin of the HealthKit object.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDigitalSignature"}],"title":"HKMetadataKeyDigitalSignature"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"8.0","deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"introducedAt":"8.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.0","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"13.0","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Global Variable","op":"replace","path":"/metadata/roleHeading"},{"value":"HKMetadataKeyDeviceManufacturerName","op":"replace","path":"/metadata/title"},{"value":"var","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"HKMetadataKeyDeviceManufacturerName","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Device-Information-Keys","title":"Device Information Keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceManufacturerName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"HKMetadataKeyDeviceName","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceName/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyDeviceName"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceName/fragments"},{"value":"HKDevice","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/title"},{"value":[{"kind":"identifier","text":"HKDevice"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/fragments"},{"value":[{"kind":"identifier","text":"HKDevice"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/navigatorTitle"},{"value":"HKMetadataKeyUDIProductionIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIProductionIdentifier/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIProductionIdentifier/fragments"},{"value":"HKMetadataKeyAppleDeviceCalibrated","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleDeviceCalibrated/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyAppleDeviceCalibrated"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleDeviceCalibrated/fragments"},{"value":"HKMetadataKeyDeviceSerialNumber","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceSerialNumber/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceSerialNumber/fragments"},{"value":"HKDevicePlacementSide","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/title"},{"value":[{"kind":"identifier","text":"HKDevicePlacementSide"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/fragments"},{"value":[{"text":"HKDevicePlacementSide","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/navigatorTitle"},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"value":"HKMetadataKeyDeviceManufacturerName","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceManufacturerName/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyDeviceManufacturerName"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceManufacturerName/fragments"},{"value":"HKMetadataKeyUDIDeviceIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIDeviceIdentifier/title"},{"value":[{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIDeviceIdentifier/fragments"},{"value":"HKMetadataKeyDevicePlacementSide","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDevicePlacementSide/title"},{"value":[{"text":"HKMetadataKeyDevicePlacementSide","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDevicePlacementSide/fragments"},{"value":"HKMetadataKeyDigitalSignature","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDigitalSignature/title"},{"value":[{"text":"HKMetadataKeyDigitalSignature","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDigitalSignature/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}