{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"HealthKit"}],"platforms":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"8.0","unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"8.0","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.0","unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"introducedAt":"13.0","unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false},{"deprecated":false,"name":"watchOS","beta":false,"introducedAt":"2.0","unavailable":false}],"roleHeading":"Global Variable","title":"HKMetadataKeyDeviceSerialNumber","symbolKind":"var","externalID":"c:@HKMetadataKeyDeviceSerialNumber","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKMetadataKeyDeviceSerialNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"This key takes a string value."}],"type":"paragraph"}]}],"abstract":[{"text":"The key for the serial number of the device that generated the data.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated"],"title":"Device Information Keys","anchor":"Device-Information-Keys","generated":true}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkmetadatakeydeviceserialnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkmetadatakeydeviceserialnumber"]}],"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","title":"NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","url":"/documentation/foundation/nsstring","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","title":"String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","role":"symbol","abstract":[{"text":"The key for metadata indicating the placement of the device that measured a sample.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDevicePlacementSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"HKMetadataKeyDevicePlacementSide","type":"topic","url":"/documentation/healthkit/hkmetadatakeydeviceplacementside","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDevicePlacementSide"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber":{"url":"/documentation/healthkit/hkmetadatakeydeviceserialnumber","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyDeviceSerialNumber","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceSerialNumber","type":"topic","abstract":[{"type":"text","text":"The key for the serial number of the device that generated the data."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide":{"url":"/documentation/healthkit/hkdeviceplacementside","title":"HKDevicePlacementSide","type":"topic","role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","navigatorTitle":[{"kind":"identifier","text":"HKDevicePlacementSide"}],"abstract":[{"text":"Values that indicate the placement of the device that measured a sample.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKDevicePlacementSide"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName":{"url":"/documentation/healthkit/hkmetadatakeydevicename","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyDeviceName","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","type":"topic","abstract":[{"type":"text","text":"The name of the device that took this reading."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDeviceName"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier":{"title":"HKMetadataKeyUDIDeviceIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"}],"abstract":[{"type":"text","text":"The device identifier portion of a device’s UDI (unique device identifier)."}],"url":"/documentation/healthkit/hkmetadatakeyudideviceidentifier","type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature":{"type":"topic","url":"/documentation/healthkit/hkmetadatakeydigitalsignature","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKMetadataKeyDigitalSignature","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"A digital signature that can be used to validate the origin of the HealthKit object.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyDigitalSignature"}],"title":"HKMetadataKeyDigitalSignature"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated","abstract":[{"text":"The key for metadata indicating whether the system had data from a sufficient amount of calibrated sensors when recording the sample.","type":"text"}],"title":"HKMetadataKeyAppleDeviceCalibrated","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyAppleDeviceCalibrated"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"HKMetadataKeyAppleDeviceCalibrated","kind":"identifier"}],"kind":"symbol","url":"/documentation/healthkit/hkmetadatakeyappledevicecalibrated"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName":{"abstract":[{"text":"The name of the manufacturer of the device that took this reading.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKMetadataKeyDeviceManufacturerName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName","title":"HKMetadataKeyDeviceManufacturerName","url":"/documentation/healthkit/hkmetadatakeydevicemanufacturername","navigatorTitle":[{"text":"HKMetadataKeyDeviceManufacturerName","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier":{"url":"/documentation/healthkit/hkmetadatakeyudiproductionidentifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"HKMetadataKeyUDIProductionIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","type":"topic","abstract":[{"type":"text","text":"The production identifier portion of a device’s UDI (unique device identifier)."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"beta":false,"introducedAt":"8.0","unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"introducedAt":"8.0","unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"introducedAt":"13.0","unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"introducedAt":"13.0","unavailable":false,"name":"macOS"},{"deprecated":false,"beta":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS"},{"deprecated":false,"beta":false,"introducedAt":"2.0","unavailable":false,"name":"watchOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"HKMetadataKeyDeviceSerialNumber","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Device-Information-Keys","generated":true,"title":"Device Information Keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIDeviceIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyUDIProductionIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDigitalSignature","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDeviceManufacturerName","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide","doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleDeviceCalibrated"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDevicePlacementSide/title","value":"HKMetadataKeyDevicePlacementSide"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDevicePlacementSide/fragments","value":[{"kind":"identifier","text":"HKMetadataKeyDevicePlacementSide"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceSerialNumber/title","value":"HKMetadataKeyDeviceSerialNumber"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceSerialNumber/fragments","value":[{"kind":"identifier","text":"HKMetadataKeyDeviceSerialNumber"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/title","value":"HKDevicePlacementSide"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/fragments","value":[{"text":"HKDevicePlacementSide","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/navigatorTitle","value":[{"kind":"identifier","text":"HKDevicePlacementSide"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceName/title","value":"HKMetadataKeyDeviceName"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceName/fragments","value":[{"kind":"identifier","text":"HKMetadataKeyDeviceName"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIDeviceIdentifier/title","value":"HKMetadataKeyUDIDeviceIdentifier"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIDeviceIdentifier/fragments","value":[{"kind":"identifier","text":"HKMetadataKeyUDIDeviceIdentifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDigitalSignature/title","value":"HKMetadataKeyDigitalSignature"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDigitalSignature/fragments","value":[{"text":"HKMetadataKeyDigitalSignature","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleDeviceCalibrated/title","value":"HKMetadataKeyAppleDeviceCalibrated"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleDeviceCalibrated/fragments","value":[{"text":"HKMetadataKeyAppleDeviceCalibrated","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceManufacturerName/title","value":"HKMetadataKeyDeviceManufacturerName"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyDeviceManufacturerName/fragments","value":[{"kind":"identifier","text":"HKMetadataKeyDeviceManufacturerName"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIProductionIdentifier/title","value":"HKMetadataKeyUDIProductionIdentifier"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyUDIProductionIdentifier/fragments","value":[{"kind":"identifier","text":"HKMetadataKeyUDIProductionIdentifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}