{
  "abstract": [
    {
      "text": "The key path for accessing the total number of flights of stairs climbed during the workout.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use predicateForWorkoutActivitiesWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HKPredicateKeyPathWorkoutTotalFlightsClimbed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.0",
        "message": "Use predicateForWorkoutActivitiesWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.0",
        "message": "Use predicateForWorkoutActivitiesWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "message": "Use predicateForWorkoutActivitiesWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.0",
        "message": "Use predicateForWorkoutActivitiesWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use predicateForWorkoutActivitiesWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "4.0",
        "message": "Use predicateForWorkoutActivitiesWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkout": {
      "abstract": [
        {
          "text": "The key path for accessing the object’s workout inside a predicate format string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkout"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkout",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutAverageQuantity": {
      "abstract": [
        {
          "text": "The key path for accessing workouts with a matching average quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutAverageQuantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutAverageQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutAverageQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutAverageQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutaveragequantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutDuration": {
      "abstract": [
        {
          "text": "The key path for accessing the workout’s duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutDuration"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutDuration",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutduration"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMaximumQuantity": {
      "abstract": [
        {
          "text": "The key path for accessing workouts with a matching maximum quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutMaximumQuantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMaximumQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutMaximumQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutMaximumQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutmaximumquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMinimumQuantity": {
      "abstract": [
        {
          "text": "The key path for accessing workouts with a matching minimum quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutMinimumQuantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMinimumQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutMinimumQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutMinimumQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutminimumquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutSumQuantity": {
      "abstract": [
        {
          "text": "The key path for accessing workouts with a matching sum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutSumQuantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutSumQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutSumQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutSumQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutsumquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalDistance": {
      "abstract": [
        {
          "text": "The key path for accessing the workout’s total distance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutTotalDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutTotalDistance"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutTotalDistance",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkouttotaldistance"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalEnergyBurned": {
      "abstract": [
        {
          "text": "The key path for accessing the workout’s total energy burned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutTotalEnergyBurned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalEnergyBurned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutTotalEnergyBurned"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutTotalEnergyBurned",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkouttotalenergyburned"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed": {
      "abstract": [
        {
          "text": "The key path for accessing the total number of flights of stairs climbed during the workout.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutTotalFlightsClimbed",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkouttotalflightsclimbed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount": {
      "abstract": [
        {
          "text": "The key path for accessing the number of strokes during a swimming workout.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkouttotalswimmingstrokecount"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType": {
      "abstract": [
        {
          "text": "The key path for accessing the workout’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutType"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutType",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkouttype"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Workout-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkout",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutDuration",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutAverageQuantity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMaximumQuantity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMinimumQuantity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutSumQuantity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalDistance",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalEnergyBurned",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount"
      ],
      "title": "Workout keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Workout-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkout",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutDuration",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutAverageQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMaximumQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMinimumQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutSumQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalDistance",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalEnergyBurned",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount"
              ],
              "title": "Workout keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use predicateForWorkoutActivitiesWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalEnergyBurned/title",
          "value": "HKPredicateKeyPathWorkoutTotalEnergyBurned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalEnergyBurned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutTotalEnergyBurned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutAverageQuantity/title",
          "value": "HKPredicateKeyPathWorkoutAverageQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutAverageQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutAverageQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkout/title",
          "value": "HKPredicateKeyPathWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalFlightsClimbed/title",
          "value": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalFlightsClimbed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutTotalFlightsClimbed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutMinimumQuantity/title",
          "value": "HKPredicateKeyPathWorkoutMinimumQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutMinimumQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutMinimumQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutDuration/title",
          "value": "HKPredicateKeyPathWorkoutDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalDistance/title",
          "value": "HKPredicateKeyPathWorkoutTotalDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutTotalDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutSumQuantity/title",
          "value": "HKPredicateKeyPathWorkoutSumQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutSumQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutSumQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount/title",
          "value": "HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutMaximumQuantity/title",
          "value": "HKPredicateKeyPathWorkoutMaximumQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutMaximumQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutMaximumQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutType/title",
          "value": "HKPredicateKeyPathWorkoutType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkpredicatekeypathworkouttotalflightsclimbed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkpredicatekeypathworkouttotalflightsclimbed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
