{
  "abstract": [
    {
      "text": "The key path for accessing activities with a matching start date.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityStartDate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HKPredicateKeyPathWorkoutActivityStartDate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKPredicateKeyPathWorkoutActivityStartDate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKPredicateKeyPathWorkoutActivityStartDate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HKPredicateKeyPathWorkoutActivityStartDate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityStartDate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivity": {
      "abstract": [
        {
          "text": "The key path for accessing a specific workout activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityAverageQuantity": {
      "abstract": [
        {
          "text": "The key path for accessing activities with a matching average quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityAverageQuantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityAverageQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityAverageQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivityAverageQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivityaveragequantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityDuration": {
      "abstract": [
        {
          "text": "The key path for accessing activities with a matching duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityDuration"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivityDuration",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivityduration"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityEndDate": {
      "abstract": [
        {
          "text": "The key path for accessing activities with a matching end date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityEndDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityEndDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityEndDate"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivityEndDate",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivityenddate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMaximumQuantity": {
      "abstract": [
        {
          "text": "The key path for accessing activities with a matching maximum quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityMaximumQuantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMaximumQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityMaximumQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivityMaximumQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivitymaximumquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMinimumQuantity": {
      "abstract": [
        {
          "text": "The key path for accessing activities with a matching minimum quantity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityMinimumQuantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMinimumQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityMinimumQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivityMinimumQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivityminimumquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityStartDate": {
      "abstract": [
        {
          "text": "The key path for accessing activities with a matching start date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityStartDate"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivityStartDate",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivitystartdate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivitySumQuantity": {
      "abstract": [
        {
          "text": "The key path for accessing activities with a matching sum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivitySumQuantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivitySumQuantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivitySumQuantity"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivitySumQuantity",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivitysumquantity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityType": {
      "abstract": [
        {
          "text": "The key path for accessing activities that match a workout activity type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathworkoutactivitytype"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-predicate-key-paths",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityEndDate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityDuration",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityAverageQuantity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMaximumQuantity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMinimumQuantity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivitySumQuantity"
      ],
      "title": "Specifying predicate key paths"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKPredicateKeyPathWorkoutActivityStartDate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-predicate-key-paths",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityEndDate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityDuration",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityAverageQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMaximumQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMinimumQuantity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivitySumQuantity"
              ],
              "title": "Specifying predicate key paths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKPredicateKeyPathWorkoutActivityStartDate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityStartDate/title",
          "value": "HKPredicateKeyPathWorkoutActivityStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityType/title",
          "value": "HKPredicateKeyPathWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityEndDate/title",
          "value": "HKPredicateKeyPathWorkoutActivityEndDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityEndDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityEndDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivity/title",
          "value": "HKPredicateKeyPathWorkoutActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityMinimumQuantity/title",
          "value": "HKPredicateKeyPathWorkoutActivityMinimumQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityMinimumQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityMinimumQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivitySumQuantity/title",
          "value": "HKPredicateKeyPathWorkoutActivitySumQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivitySumQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivitySumQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityMaximumQuantity/title",
          "value": "HKPredicateKeyPathWorkoutActivityMaximumQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityMaximumQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityMaximumQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityDuration/title",
          "value": "HKPredicateKeyPathWorkoutActivityDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityAverageQuantity/title",
          "value": "HKPredicateKeyPathWorkoutActivityAverageQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityAverageQuantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathWorkoutActivityAverageQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkpredicatekeypathworkoutactivitystartdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkpredicatekeypathworkoutactivitystartdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
