{"seeAlsoSections":[{"title":"Specifying Predicate Key Paths","generated":true,"anchor":"Specifying-Predicate-Key-Paths","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathMetadata","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkpredicatekeypathmetadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkpredicatekeypathmetadata"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"HKPredicateKeyPathMetadata","kind":"identifier"}],"modules":[{"name":"HealthKit"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"HKPredicateKeyPathMetadata","platforms":[{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"macOS","beta":false},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS","beta":false},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"watchOS","beta":false}],"roleHeading":"Global Variable","externalID":"c:@HKPredicateKeyPathMetadata","symbolKind":"var","role":"symbol"},"kind":"symbol","abstract":[{"text":"The key path for accessing the object’s metadata dictionary inside a predicate format string.","type":"text"}],"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","title":"NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","url":"/documentation/foundation/nsstring","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID":{"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID","url":"/documentation/healthkit/hkpredicatekeypathuuid","title":"HKPredicateKeyPathUUID","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathUUID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathUUID"}],"abstract":[{"type":"text","text":"The key path for accessing the object’s UUID inside a predicate format string."}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","title":"String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathMetadata":{"kind":"symbol","url":"/documentation/healthkit/hkpredicatekeypathmetadata","abstract":[{"text":"The key path for accessing the object’s metadata dictionary inside a predicate format string.","type":"text"}],"title":"HKPredicateKeyPathMetadata","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"HKPredicateKeyPathMetadata","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathMetadata","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"macOS","beta":false},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS","beta":false},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"watchOS","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"HKPredicateKeyPathMetadata","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"HKPredicateKeyPathMetadata","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Specifying Predicate Key Paths","anchor":"Specifying-Predicate-Key-Paths","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathMetadata","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"]}]}},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathUUID/title","value":"HKPredicateKeyPathUUID"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathUUID/fragments","value":[{"text":"HKPredicateKeyPathUUID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathMetadata/title","value":"HKPredicateKeyPathMetadata"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathMetadata/fragments","value":[{"text":"HKPredicateKeyPathMetadata","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}