{
  "abstract": [
    {
      "text": "The style of stroke while swimming.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKSwimmingStrokeStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKSwimmingStrokeStyle"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKSwimmingStrokeStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "HKSwimmingStrokeStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle": {
      "abstract": [
        {
          "text": "The style of stroke while swimming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyle"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyle"
        }
      ],
      "role": "symbol",
      "title": "HKSwimmingStrokeStyle",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/backstroke": {
      "abstract": [
        {
          "text": "The user swam the backstroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backstroke"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/backstroke",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyleBackstroke"
        }
      ],
      "role": "symbol",
      "title": "HKSwimmingStrokeStyle.backstroke",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle/backstroke"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/breaststroke": {
      "abstract": [
        {
          "text": "The user swam the breaststroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breaststroke"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/breaststroke",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyleBreaststroke"
        }
      ],
      "role": "symbol",
      "title": "HKSwimmingStrokeStyle.breaststroke",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle/breaststroke"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/butterfly": {
      "abstract": [
        {
          "text": "The user swam the butterfly stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "butterfly"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/butterfly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyleButterfly"
        }
      ],
      "role": "symbol",
      "title": "HKSwimmingStrokeStyle.butterfly",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle/butterfly"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/freestyle": {
      "abstract": [
        {
          "text": "The user swam the freestyle stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freestyle"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/freestyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyleFreestyle"
        }
      ],
      "role": "symbol",
      "title": "HKSwimmingStrokeStyle.freestyle",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle/freestyle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle/init(rawvalue:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/kickboard": {
      "abstract": [
        {
          "text": "The user swam using a kickboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kickboard"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/kickboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyleKickboard"
        }
      ],
      "role": "symbol",
      "title": "HKSwimmingStrokeStyle.kickboard",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle/kickboard"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/mixed": {
      "abstract": [
        {
          "text": "The user swam a mixture of strokes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixed"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/mixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyleMixed"
        }
      ],
      "role": "symbol",
      "title": "HKSwimmingStrokeStyle.mixed",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle/mixed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/unknown": {
      "abstract": [
        {
          "text": "The user’s stroke could not be determined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSwimmingStrokeStyleUnknown"
        }
      ],
      "role": "symbol",
      "title": "HKSwimmingStrokeStyle.unknown",
      "type": "topic",
      "url": "/documentation/healthkit/hkswimmingstrokestyle/unknown"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Strokes",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/backstroke",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/breaststroke",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/butterfly",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/freestyle",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/mixed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/kickboard",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/unknown"
      ],
      "title": "Strokes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKSwimmingStrokeStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Strokes",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/backstroke",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/breaststroke",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/butterfly",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/freestyle",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/mixed",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/kickboard",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSwimmingStrokeStyle/unknown"
              ],
              "title": "Strokes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKSwimmingStrokeStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1freestyle/title",
          "value": "HKSwimmingStrokeStyleFreestyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1freestyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyleFreestyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1mixed/title",
          "value": "HKSwimmingStrokeStyleMixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1mixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyleMixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle/title",
          "value": "HKSwimmingStrokeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1kickboard/title",
          "value": "HKSwimmingStrokeStyleKickboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1kickboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyleKickboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1backstroke/title",
          "value": "HKSwimmingStrokeStyleBackstroke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1backstroke/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyleBackstroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1unknown/title",
          "value": "HKSwimmingStrokeStyleUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyleUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1butterfly/title",
          "value": "HKSwimmingStrokeStyleButterfly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1butterfly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyleButterfly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1breaststroke/title",
          "value": "HKSwimmingStrokeStyleBreaststroke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSwimmingStrokeStyle~1breaststroke/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSwimmingStrokeStyleBreaststroke"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkswimmingstrokestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkswimmingstrokestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
