{
  "abstract": [
    {
      "text": "A sample that stores a vision prescription.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKVisionPrescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKVisionPrescription"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKVisionPrescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HKVisionPrescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKVisionPrescription"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to create an image-only prescription. Here, you attach the prescription as an image or PDF to a simple sample. The sample contains only basic information about the prescription, such as the issue and expiration dates. To see the prescription data, people must view the attached image or PDF.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Some regions may require an image of the original prescription to validate the prescription record.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To create an image-only prescription, start by creating an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sample object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create a minimal prescription sample that just holds an image attachment.",
            "let prescription = HKVisionPrescription(type: .glasses,",
            "                                        dateIssued: Date(),",
            "                                        expirationDate: nil,",
            "                                        device: HKDevice.local(),",
            "                                        metadata: nil)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, save the sample to the HealthKit store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Save the sample to the HealthKit store.",
            "do {",
            "    try await store.save(prescription)",
            "} catch {",
            "    // Handle the error here.",
            "    fatalError(\"*** An error occurred while saving the prescription sample to the HealthKit store \\(error.localizedDescription) ***\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then, you can attach the image or PDF to the sample.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Get the attachment store.",
            "let attachmentStore = HKAttachmentStore(healthStore: store)",
            "",
            "// Attach the image to the sample.",
            "do {",
            "    _ = try await attachmentStore.addAttachment(to: prescription,",
            "                                                name: \"Glasses Prescription\",",
            "                                                contentType: type,",
            "                                                url: url)",
            "} catch {",
            "    // Handle the error.",
            "    fatalError(\"*** An error occurred while attaching the image: \\(error.localizedDescription) ***\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about adding images or pdfs as attachments, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To create a vision prescription sample that contains the full data for the prescription, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKContactsPrescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentStore": {
      "abstract": [
        {
          "text": "The access point for attachments associated with samples in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAttachmentStore"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAttachmentStore"
        }
      ],
      "role": "symbol",
      "title": "HKAttachmentStore",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachmentstore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKContactsLensSpecification": {
      "abstract": [
        {
          "text": "An object that contains the contacts prescription data for one eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKContactsLensSpecification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKContactsLensSpecification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKContactsLensSpecification"
        }
      ],
      "role": "symbol",
      "title": "HKContactsLensSpecification",
      "type": "topic",
      "url": "/documentation/healthkit/hkcontactslensspecification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKContactsPrescription": {
      "abstract": [
        {
          "text": "A sample that store a prescription for contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKContactsPrescription"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKContactsPrescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKContactsPrescription"
        }
      ],
      "role": "symbol",
      "title": "HKContactsPrescription",
      "type": "topic",
      "url": "/documentation/healthkit/hkcontactsprescription"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesLensSpecification": {
      "abstract": [
        {
          "text": "An object that contains the glasses prescription data for one eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKGlassesLensSpecification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesLensSpecification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKGlassesLensSpecification"
        }
      ],
      "role": "symbol",
      "title": "HKGlassesLensSpecification",
      "type": "topic",
      "url": "/documentation/healthkit/hkglasseslensspecification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription": {
      "abstract": [
        {
          "text": "A sample that stores a prescription for glasses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKGlassesPrescription"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKGlassesPrescription"
        }
      ],
      "role": "symbol",
      "title": "HKGlassesPrescription",
      "type": "topic",
      "url": "/documentation/healthkit/hkglassesprescription"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKLensSpecification": {
      "abstract": [
        {
          "text": "An abstract superclass for lens specifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKLensSpecification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLensSpecification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKLensSpecification"
        }
      ],
      "role": "symbol",
      "title": "HKLensSpecification",
      "type": "topic",
      "url": "/documentation/healthkit/hklensspecification"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPrescriptionType": {
      "abstract": [
        {
          "text": "A type that identifies samples that store a prescription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPrescriptionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPrescriptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPrescriptionType"
        }
      ],
      "role": "symbol",
      "title": "HKPrescriptionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkprescriptiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSample": {
      "abstract": [
        {
          "text": "A HealthKit sample represents a piece of data associated with a start and end time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSample"
        }
      ],
      "role": "symbol",
      "title": "HKSample",
      "type": "topic",
      "url": "/documentation/healthkit/hksample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription": {
      "abstract": [
        {
          "text": "A sample that stores a vision prescription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVisionPrescription"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVisionPrescription"
        }
      ],
      "role": "symbol",
      "title": "HKVisionPrescription",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprescription"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/dateIssued": {
      "abstract": [
        {
          "text": "The date when the doctor issued the prescription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateIssued"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/dateIssued",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateIssued"
        }
      ],
      "role": "symbol",
      "title": "dateIssued",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprescription/dateissued"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/expirationDate": {
      "abstract": [
        {
          "text": "The date when the prescription expires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/expirationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expirationDate"
        }
      ],
      "role": "symbol",
      "title": "expirationDate",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprescription/expirationdate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/init(type:dateIssued:expirationDate:device:metadata:)": {
      "abstract": [
        {
          "text": "Creates a new vision prescription sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKVisionPrescriptionType",
          "text": "HKVisionPrescriptionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dateIssued"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "expirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKDevice",
          "text": "HKDevice"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/init(type:dateIssued:expirationDate:device:metadata:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prescriptionWithType:dateIssued:expirationDate:device:metadata:"
        }
      ],
      "role": "symbol",
      "title": "init(type:dateIssued:expirationDate:device:metadata:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprescription/init(type:dateissued:expirationdate:device:metadata:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/prescriptionType": {
      "abstract": [
        {
          "text": "The type of vision prescription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prescriptionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKVisionPrescriptionType",
          "text": "HKVisionPrescriptionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/prescriptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prescriptionType"
        }
      ],
      "role": "symbol",
      "title": "prescriptionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprescription/prescriptiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescriptionType": {
      "abstract": [
        {
          "text": "The type of vision prescription, for example a prescription for glasses or for contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVisionPrescriptionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescriptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVisionPrescriptionType"
        }
      ],
      "role": "symbol",
      "title": "HKVisionPrescriptionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprescriptiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism": {
      "abstract": [
        {
          "text": "Prescription data for eye alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVisionPrism"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVisionPrism"
        }
      ],
      "role": "symbol",
      "title": "HKVisionPrism",
      "type": "topic",
      "url": "/documentation/healthkit/hkvisionprism"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKSample"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKContactsPrescription",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vision-prescriptions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription",
        "doc://com.apple.healthkit/documentation/HealthKit/HKContactsPrescription",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesLensSpecification",
        "doc://com.apple.healthkit/documentation/HealthKit/HKContactsLensSpecification",
        "doc://com.apple.healthkit/documentation/HealthKit/HKLensSpecification",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPrescriptionType"
      ],
      "title": "Vision prescriptions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-vision-prescription-samples",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/init(type:dateIssued:expirationDate:device:metadata:)"
      ],
      "title": "Creating vision prescription samples"
    },
    {
      "anchor": "Accessing-the-prescription-data",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/prescriptionType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescriptionType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/dateIssued",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/expirationDate"
      ],
      "title": "Accessing the prescription data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKVisionPrescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-vision-prescription-samples",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/init(type:dateIssued:expirationDate:device:metadata:)"
              ],
              "title": "Creating vision prescription samples"
            },
            {
              "anchor": "Accessing-the-prescription-data",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/prescriptionType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescriptionType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/dateIssued",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrescription/expirationDate"
              ],
              "title": "Accessing the prescription data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKSample"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKContactsPrescription",
                "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vision-prescriptions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesPrescription",
                "doc://com.apple.healthkit/documentation/HealthKit/HKContactsPrescription",
                "doc://com.apple.healthkit/documentation/HealthKit/HKGlassesLensSpecification",
                "doc://com.apple.healthkit/documentation/HealthKit/HKContactsLensSpecification",
                "doc://com.apple.healthkit/documentation/HealthKit/HKLensSpecification",
                "doc://com.apple.healthkit/documentation/HealthKit/HKVisionPrism",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPrescriptionType"
              ],
              "title": "Vision prescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKVisionPrescription"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSample",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HKSample",
                    "text": "HKSample"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription~1init(type:dateIssued:expirationDate:device:metadata:)/title",
          "value": "prescriptionWithType:dateIssued:expirationDate:device:metadata:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription~1init(type:dateIssued:expirationDate:device:metadata:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "prescriptionWithType:dateIssued:expirationDate:device:metadata:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKContactsLensSpecification/title",
          "value": "HKContactsLensSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKContactsLensSpecification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKContactsLensSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKContactsLensSpecification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKContactsLensSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLensSpecification/title",
          "value": "HKLensSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLensSpecification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKLensSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLensSpecification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKLensSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription~1expirationDate/title",
          "value": "expirationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription~1expirationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expirationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription~1prescriptionType/title",
          "value": "prescriptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription~1prescriptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prescriptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription/title",
          "value": "HKVisionPrescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachmentStore/title",
          "value": "HKAttachmentStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachmentStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAttachmentStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachmentStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAttachmentStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKContactsPrescription/title",
          "value": "HKContactsPrescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKContactsPrescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKContactsPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKContactsPrescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKContactsPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription/title",
          "value": "HKGlassesPrescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGlassesPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesPrescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGlassesPrescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescriptionType/title",
          "value": "HKVisionPrescriptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescriptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrescriptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescriptionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrescriptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesLensSpecification/title",
          "value": "HKGlassesLensSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesLensSpecification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGlassesLensSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGlassesLensSpecification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGlassesLensSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism/title",
          "value": "HKVisionPrism"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrism"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrism/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVisionPrism"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPrescriptionType/title",
          "value": "HKPrescriptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPrescriptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPrescriptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPrescriptionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPrescriptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/title",
          "value": "HKSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription~1dateIssued/title",
          "value": "dateIssued"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVisionPrescription~1dateIssued/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateIssued"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkvisionprescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkvisionprescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
