{
  "abstract": [
    {
      "text": "Constants that indicate a type of weather.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKWeatherCondition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKWeatherCondition"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWeatherCondition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "HKWeatherCondition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKWeatherCondition"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition": {
      "abstract": [
        {
          "text": "Constants that indicate a type of weather.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWeatherCondition"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherCondition"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/blustery": {
      "abstract": [
        {
          "text": "The weather condition is blustery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blustery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/blustery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionBlustery"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.blustery",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/blustery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/clear": {
      "abstract": [
        {
          "text": "The weather condition is clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clear"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/clear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionClear"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.clear",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/clear"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/cloudy": {
      "abstract": [
        {
          "text": "The weather condition is cloudy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/cloudy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionCloudy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.cloudy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/cloudy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/drizzle": {
      "abstract": [
        {
          "text": "The weather condition is drizzle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drizzle"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/drizzle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionDrizzle"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.drizzle",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/drizzle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/dust": {
      "abstract": [
        {
          "text": "The weather condition is dust.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dust"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/dust",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionDust"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.dust",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/dust"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/fair": {
      "abstract": [
        {
          "text": "The weather condition is fair.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fair"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/fair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionFair"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.fair",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/fair"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/foggy": {
      "abstract": [
        {
          "text": "The weather condition is foggy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foggy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/foggy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionFoggy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.foggy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/foggy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingDrizzle": {
      "abstract": [
        {
          "text": "The weather condition is freezing drizzle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freezingDrizzle"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingDrizzle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionFreezingDrizzle"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.freezingDrizzle",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/freezingdrizzle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingRain": {
      "abstract": [
        {
          "text": "The weather condition is freezing rain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freezingRain"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingRain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionFreezingRain"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.freezingRain",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/freezingrain"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hail": {
      "abstract": [
        {
          "text": "The weather condition is hail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hail"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionHail"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.hail",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/hail"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/haze": {
      "abstract": [
        {
          "text": "The weather condition is hazy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "haze"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/haze",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionHaze"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.haze",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/haze"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hurricane": {
      "abstract": [
        {
          "text": "The weather condition is hurricane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hurricane"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hurricane",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionHurricane"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.hurricane",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/hurricane"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/init(rawvalue:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndHail": {
      "abstract": [
        {
          "text": "The weather condition is mixed rain and hail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedRainAndHail"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndHail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionMixedRainAndHail"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.mixedRainAndHail",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/mixedrainandhail"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndSleet": {
      "abstract": [
        {
          "text": "The weather condition is mixed rain and sleet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedRainAndSleet"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndSleet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionMixedRainAndSleet"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.mixedRainAndSleet",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/mixedrainandsleet"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndSnow": {
      "abstract": [
        {
          "text": "The weather condition is mixed rain and snow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedRainAndSnow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndSnow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionMixedRainAndSnow"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.mixedRainAndSnow",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/mixedrainandsnow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedSnowAndSleet": {
      "abstract": [
        {
          "text": "The weather condition is mixed snow and sleet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixedSnowAndSleet"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedSnowAndSleet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionMixedSnowAndSleet"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.mixedSnowAndSleet",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/mixedsnowandsleet"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mostlyCloudy": {
      "abstract": [
        {
          "text": "The weather condition is mostly cloudy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostlyCloudy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mostlyCloudy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionMostlyCloudy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.mostlyCloudy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/mostlycloudy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/none": {
      "abstract": [
        {
          "text": "The weather condition is unknown or irrelevant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionNone"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.none",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/none"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/partlyCloudy": {
      "abstract": [
        {
          "text": "The weather condition is partly cloudy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partlyCloudy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/partlyCloudy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionPartlyCloudy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.partlyCloudy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/partlycloudy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/scatteredShowers": {
      "abstract": [
        {
          "text": "The weather condition is scattered showers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scatteredShowers"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/scatteredShowers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionScatteredShowers"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.scatteredShowers",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/scatteredshowers"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/showers": {
      "abstract": [
        {
          "text": "The weather condition is showers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showers"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/showers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionShowers"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.showers",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/showers"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/sleet": {
      "abstract": [
        {
          "text": "The weather condition is sleet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleet"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/sleet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionSleet"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.sleet",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/sleet"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/smoky": {
      "abstract": [
        {
          "text": "The weather condition is smoky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smoky"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/smoky",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionSmoky"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.smoky",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/smoky"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/snow": {
      "abstract": [
        {
          "text": "The weather condition is snow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snow"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/snow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionSnow"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.snow",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/snow"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/thunderstorms": {
      "abstract": [
        {
          "text": "The weather condition is thunderstorms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thunderstorms"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/thunderstorms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionThunderstorms"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.thunderstorms",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/thunderstorms"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/tornado": {
      "abstract": [
        {
          "text": "The weather condition is tornado.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tornado"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/tornado",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionTornado"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.tornado",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/tornado"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/tropicalStorm": {
      "abstract": [
        {
          "text": "The weather condition is tropical storm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tropicalStorm"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/tropicalStorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionTropicalStorm"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.tropicalStorm",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/tropicalstorm"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/windy": {
      "abstract": [
        {
          "text": "The weather condition is windy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/windy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWeatherConditionWindy"
        }
      ],
      "role": "symbol",
      "title": "HKWeatherCondition.windy",
      "type": "topic",
      "url": "/documentation/healthkit/hkweathercondition/windy"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Weather-Conditions",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/none",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/clear",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/fair",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/partlyCloudy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mostlyCloudy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/cloudy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/foggy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/haze",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/windy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/blustery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/smoky",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/dust",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/snow",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hail",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/sleet",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingDrizzle",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingRain",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndHail",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndSnow",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndSleet",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedSnowAndSleet",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/drizzle",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/scatteredShowers",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/showers",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/thunderstorms",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/tropicalStorm",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hurricane",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/tornado"
      ],
      "title": "Weather Conditions"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWeatherCondition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Weather-Conditions",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/none",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/clear",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/fair",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/partlyCloudy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mostlyCloudy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/cloudy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/foggy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/haze",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/windy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/blustery",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/smoky",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/dust",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/snow",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hail",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/sleet",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingDrizzle",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/freezingRain",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndHail",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndSnow",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedRainAndSleet",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/mixedSnowAndSleet",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/drizzle",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/scatteredShowers",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/showers",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/thunderstorms",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/tropicalStorm",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/hurricane",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWeatherCondition/tornado"
              ],
              "title": "Weather Conditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKWeatherCondition"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1dust/title",
          "value": "HKWeatherConditionDust"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1dust/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionDust"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1snow/title",
          "value": "HKWeatherConditionSnow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1snow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionSnow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1fair/title",
          "value": "HKWeatherConditionFair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1fair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionFair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mixedRainAndSleet/title",
          "value": "HKWeatherConditionMixedRainAndSleet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mixedRainAndSleet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionMixedRainAndSleet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1freezingDrizzle/title",
          "value": "HKWeatherConditionFreezingDrizzle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1freezingDrizzle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionFreezingDrizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1smoky/title",
          "value": "HKWeatherConditionSmoky"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1smoky/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionSmoky"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1hurricane/title",
          "value": "HKWeatherConditionHurricane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1hurricane/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionHurricane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1partlyCloudy/title",
          "value": "HKWeatherConditionPartlyCloudy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1partlyCloudy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionPartlyCloudy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1drizzle/title",
          "value": "HKWeatherConditionDrizzle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1drizzle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionDrizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1none/title",
          "value": "HKWeatherConditionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1clear/title",
          "value": "HKWeatherConditionClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1clear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1blustery/title",
          "value": "HKWeatherConditionBlustery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1blustery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionBlustery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1hail/title",
          "value": "HKWeatherConditionHail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1hail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionHail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1freezingRain/title",
          "value": "HKWeatherConditionFreezingRain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1freezingRain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionFreezingRain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1sleet/title",
          "value": "HKWeatherConditionSleet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1sleet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionSleet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1thunderstorms/title",
          "value": "HKWeatherConditionThunderstorms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1thunderstorms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionThunderstorms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1tropicalStorm/title",
          "value": "HKWeatherConditionTropicalStorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1tropicalStorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionTropicalStorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1foggy/title",
          "value": "HKWeatherConditionFoggy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1foggy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionFoggy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mixedRainAndHail/title",
          "value": "HKWeatherConditionMixedRainAndHail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mixedRainAndHail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionMixedRainAndHail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1haze/title",
          "value": "HKWeatherConditionHaze"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1haze/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionHaze"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1tornado/title",
          "value": "HKWeatherConditionTornado"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1tornado/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionTornado"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mixedRainAndSnow/title",
          "value": "HKWeatherConditionMixedRainAndSnow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mixedRainAndSnow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionMixedRainAndSnow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mostlyCloudy/title",
          "value": "HKWeatherConditionMostlyCloudy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mostlyCloudy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionMostlyCloudy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1cloudy/title",
          "value": "HKWeatherConditionCloudy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1cloudy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionCloudy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mixedSnowAndSleet/title",
          "value": "HKWeatherConditionMixedSnowAndSleet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1mixedSnowAndSleet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionMixedSnowAndSleet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1windy/title",
          "value": "HKWeatherConditionWindy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1windy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionWindy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition/title",
          "value": "HKWeatherCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1scatteredShowers/title",
          "value": "HKWeatherConditionScatteredShowers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1scatteredShowers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionScatteredShowers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1showers/title",
          "value": "HKWeatherConditionShowers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWeatherCondition~1showers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWeatherConditionShowers"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkweathercondition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkweathercondition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
