{
  "abstract": [
    {
      "text": "This class acts as a wrapper for the wheelchair use enumeration.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKWheelchairUseObject",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKWheelchairUseObject"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWheelchairUseObject"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HKWheelchairUseObject"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKWheelchairUseObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityPointClampingRange": {
      "abstract": [
        {
          "text": "Defines the range within which an ear’s sensitivity point may have been clamped, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityPointClampingRange"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityPointClampingRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityPointClampingRange"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramSensitivityPointClampingRange",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramsensitivitypointclampingrange"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityTest"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityTest"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramSensitivityTest",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramsensitivitytest"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex": {
      "abstract": [
        {
          "text": "Constants indicating the user’s sex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBiologicalSex"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBiologicalSex"
        }
      ],
      "role": "symbol",
      "title": "HKBiologicalSex",
      "type": "topic",
      "url": "/documentation/healthkit/hkbiologicalsex"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSexObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBiologicalSexObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSexObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBiologicalSexObject"
        }
      ],
      "role": "symbol",
      "title": "HKBiologicalSexObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkbiologicalsexobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType": {
      "abstract": [
        {
          "text": "Constants indicating the user’s blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodTypeObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeObject"
        }
      ],
      "role": "symbol",
      "title": "HKBloodTypeObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtypeobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType": {
      "abstract": [
        {
          "text": "Categories representing the user’s skin type based on the Fitzpatrick scale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinTypeObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinTypeObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinTypeObject"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinTypeObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintypeobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKGAD7Assessment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKGAD7Assessment"
        }
      ],
      "role": "symbol",
      "title": "HKGAD7Assessment",
      "type": "topic",
      "url": "/documentation/healthkit/hkgad7assessment"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPHQ9Assessment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPHQ9Assessment"
        }
      ],
      "role": "symbol",
      "title": "HKPHQ9Assessment",
      "type": "topic",
      "url": "/documentation/healthkit/hkphq9assessment"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKScoredAssessment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKScoredAssessment"
        }
      ],
      "role": "symbol",
      "title": "HKScoredAssessment",
      "type": "topic",
      "url": "/documentation/healthkit/hkscoredassessment"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKScoredAssessmentType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKScoredAssessmentType"
        }
      ],
      "role": "symbol",
      "title": "HKScoredAssessmentType",
      "type": "topic",
      "url": "/documentation/healthkit/hkscoredassessmenttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMindType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStateOfMindType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMindType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindType"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMindType",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmindtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the wheelchair use enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWheelchairUseObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWheelchairUseObject"
        }
      ],
      "role": "symbol",
      "title": "HKWheelchairUseObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkwheelchairuseobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject/wheelchairUse": {
      "abstract": [
        {
          "text": "A value indicating the user’s wheelchair use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wheelchairUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKWheelchairUse",
          "text": "HKWheelchairUse"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject/wheelchairUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wheelchairUse"
        }
      ],
      "role": "symbol",
      "title": "wheelchairUse",
      "type": "topic",
      "url": "/documentation/healthkit/hkwheelchairuseobject/wheelchairuse"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationship": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationship"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationship",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationship"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEffortRelationship",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteffortrelationship"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQuery": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQuery"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEffortRelationshipQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteffortrelationshipquery"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityPointClampingRange",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTest",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSexObject",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinTypeObject",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment",
        "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessment",
        "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMindType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationship",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQuery"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Wheelchair-Use-Data",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject/wheelchairUse"
      ],
      "title": "Accessing Wheelchair Use Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWheelchairUseObject"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUseObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUseObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Wheelchair-Use-Data",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUseObject/wheelchairUse"
              ],
              "title": "Accessing Wheelchair Use Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityPointClampingRange",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTest",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSexObject",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinTypeObject",
                "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment",
                "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessment",
                "doc://com.apple.healthkit/documentation/HealthKit/HKScoredAssessmentType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMindType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationship",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQuery"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKWheelchairUseObject"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/title",
          "value": "HKStateOfMind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQuery/title",
          "value": "HKWorkoutEffortRelationshipQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/title",
          "value": "HKBiologicalSex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinTypeObject/title",
          "value": "HKFitzpatrickSkinTypeObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinTypeObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinTypeObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessment/title",
          "value": "HKScoredAssessment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMindType/title",
          "value": "HKStateOfMindType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMindType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMindType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUseObject/title",
          "value": "HKWheelchairUseObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUseObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUseObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUseObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUseObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUseObject~1wheelchairUse/title",
          "value": "wheelchairUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUseObject~1wheelchairUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wheelchairUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationship/title",
          "value": "HKWorkoutEffortRelationship"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationship/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationship/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentType/title",
          "value": "HKScoredAssessmentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessmentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKScoredAssessmentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKScoredAssessmentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/title",
          "value": "HKBloodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSexObject/title",
          "value": "HKBiologicalSexObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSexObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSexObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSexObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSexObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityPointClampingRange/title",
          "value": "HKAudiogramSensitivityPointClampingRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityPointClampingRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityPointClampingRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityPointClampingRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityPointClampingRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/title",
          "value": "HKFitzpatrickSkinType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment/title",
          "value": "HKGAD7Assessment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7Assessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7Assessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTest/title",
          "value": "HKAudiogramSensitivityTest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment/title",
          "value": "HKPHQ9Assessment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9Assessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9Assessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/title",
          "value": "HKBloodTypeObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkwheelchairuseobject"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkwheelchairuseobject"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
