{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalFlightsClimbed"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"seeAlsoSections":[{"anchor":"Workout-sort-identifiers","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierDuration","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalDistance","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalEnergyBurned","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalSwimmingStrokeCount"],"title":"Workout sort identifiers","generated":true}],"metadata":{"platforms":[{"unavailable":false,"introducedAt":"11.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"11.0","deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"name":"macOS"},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false,"name":"visionOS"},{"unavailable":false,"introducedAt":"4.0","deprecated":false,"beta":false,"name":"watchOS"}],"title":"HKWorkoutSortIdentifierTotalFlightsClimbed","externalID":"c:@HKWorkoutSortIdentifierTotalFlightsClimbed","role":"symbol","navigatorTitle":[{"text":"HKWorkoutSortIdentifierTotalFlightsClimbed","kind":"identifier"}],"modules":[{"name":"HealthKit"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierTotalFlightsClimbed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Global Variable","symbolKind":"var"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkworkoutsortidentifiertotalflightsclimbed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkworkoutsortidentifiertotalflightsclimbed"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A constant for sorting workouts based on the number of flights of steps climbed."}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"kind":"symbol","identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalFlightsClimbed","interfaceLanguage":"swift"},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalSwimmingStrokeCount":{"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkworkoutsortidentifiertotalswimmingstrokecount","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalSwimmingStrokeCount","navigatorTitle":[{"text":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","kind":"identifier"}],"title":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","abstract":[{"type":"text","text":"A constant for sorting workouts based on the number of swimming strokes."}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalDistance":{"title":"HKWorkoutSortIdentifierTotalDistance","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HKWorkoutSortIdentifierTotalDistance","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierTotalDistance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"/documentation/healthkit/hkworkoutsortidentifiertotaldistance","abstract":[{"text":"A constant for sorting workouts based on their total distance.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalDistance"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalFlightsClimbed":{"type":"topic","url":"/documentation/healthkit/hkworkoutsortidentifiertotalflightsclimbed","title":"HKWorkoutSortIdentifierTotalFlightsClimbed","role":"symbol","kind":"symbol","abstract":[{"text":"A constant for sorting workouts based on the number of flights of steps climbed.","type":"text"}],"navigatorTitle":[{"text":"HKWorkoutSortIdentifierTotalFlightsClimbed","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierTotalFlightsClimbed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalFlightsClimbed"},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","title":"String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalEnergyBurned":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalEnergyBurned","url":"/documentation/healthkit/hkworkoutsortidentifiertotalenergyburned","title":"HKWorkoutSortIdentifierTotalEnergyBurned","abstract":[{"type":"text","text":"A constant for sorting workouts based on the total energy burned."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalEnergyBurned"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalEnergyBurned"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","title":"NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","url":"/documentation/foundation/nsstring","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierDuration":{"url":"/documentation/healthkit/hkworkoutsortidentifierduration","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"HKWorkoutSortIdentifierDuration","type":"topic","abstract":[{"text":"A constant for sorting workouts based on their duration.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HKWorkoutSortIdentifierDuration","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierDuration"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"11.0","name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"11.0","name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"13.0","name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"13.0","name":"macOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"4.0","name":"watchOS","beta":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Global Variable","op":"replace","path":"/metadata/roleHeading"},{"value":"HKWorkoutSortIdentifierTotalFlightsClimbed","op":"replace","path":"/metadata/title"},{"value":"var","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalFlightsClimbed"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit"]]},"op":"replace","path":"/hierarchy"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierDuration","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalDistance","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalEnergyBurned","doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSortIdentifierTotalSwimmingStrokeCount"],"title":"Workout sort identifiers","generated":true,"anchor":"Workout-sort-identifiers"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutSortIdentifierTotalFlightsClimbed","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalSwimmingStrokeCount/title","op":"replace","value":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalSwimmingStrokeCount/fragments","op":"replace","value":[{"text":"HKWorkoutSortIdentifierTotalSwimmingStrokeCount","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalDistance/title","op":"replace","value":"HKWorkoutSortIdentifierTotalDistance"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalDistance/fragments","op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalDistance"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalFlightsClimbed/title","op":"replace","value":"HKWorkoutSortIdentifierTotalFlightsClimbed"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalFlightsClimbed/fragments","op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSortIdentifierTotalFlightsClimbed"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalEnergyBurned/title","op":"replace","value":"HKWorkoutSortIdentifierTotalEnergyBurned"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierTotalEnergyBurned/fragments","op":"replace","value":[{"text":"HKWorkoutSortIdentifierTotalEnergyBurned","kind":"identifier"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierDuration/title","op":"replace","value":"HKWorkoutSortIdentifierDuration"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSortIdentifierDuration/fragments","op":"replace","value":[{"kind":"identifier","text":"HKWorkoutSortIdentifierDuration"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}