{
  "abstract": [
    {
      "text": "A builder object that incrementally constructs a workout.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKWorkoutBuilder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HKWorkoutBuilder"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWorkoutBuilder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HKWorkoutBuilder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Incrementally collect samples and events associated with a workout. When the workout ends, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/finishWorkout(completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sample and save it to the HealthKit store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For watchOS, use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder": {
      "abstract": [
        {
          "text": "A builder object that constructs a workout incrementally based on live data from an active workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKLiveWorkoutBuilder"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKLiveWorkoutBuilder"
        }
      ],
      "role": "symbol",
      "title": "HKLiveWorkoutBuilder",
      "type": "topic",
      "url": "/documentation/healthkit/hkliveworkoutbuilder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout": {
      "abstract": [
        {
          "text": "A workout sample that stores information about a single physical activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "role": "symbol",
      "title": "HKWorkout",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity": {
      "abstract": [
        {
          "text": "An object that describes an activity within a longer workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivity"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivity",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder": {
      "abstract": [
        {
          "text": "A builder object that incrementally constructs a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutBuilder"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutBuilder"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutBuilder",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/add(_:completion:)": {
      "abstract": [
        {
          "text": "Adds a sample to be associated with the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSample",
          "text": "HKSample"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/add(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSamples:completion:"
        }
      ],
      "role": "symbol",
      "title": "add(_:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/add(_:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addMetadata(_:completion:)": {
      "abstract": [
        {
          "text": "Adds metadata to be saved with the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMetadata"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addMetadata(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addMetadata:completion:"
        }
      ],
      "role": "symbol",
      "title": "addMetadata(_:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/addmetadata(_:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutActivity(_:completion:)": {
      "abstract": [
        {
          "text": "Adds a workout activity to the workout builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addWorkoutActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutActivity",
          "text": "HKWorkoutActivity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutActivity(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addWorkoutActivity:completion:"
        }
      ],
      "role": "symbol",
      "title": "addWorkoutActivity(_:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/addworkoutactivity(_:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutEvents(_:completion:)": {
      "abstract": [
        {
          "text": "Adds a workout event to the builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addWorkoutEvents"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutEvent",
          "text": "HKWorkoutEvent"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutEvents(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addWorkoutEvents:completion:"
        }
      ],
      "role": "symbol",
      "title": "addWorkoutEvents(_:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/addworkoutevents(_:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/allStatistics": {
      "abstract": [
        {
          "text": "A dictionary that contains all the statistics for the workout builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allStatistics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantityType",
          "text": "HKQuantityType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKStatistics",
          "text": "HKStatistics"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/allStatistics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allStatistics"
        }
      ],
      "role": "symbol",
      "title": "allStatistics",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/allstatistics"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/beginCollection(withStart:completion:)": {
      "abstract": [
        {
          "text": "Sets the workout’s start date and begins building the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/beginCollection(withStart:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginCollectionWithStartDate:completion:"
        }
      ],
      "role": "symbol",
      "title": "beginCollection(withStart:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/begincollection(withstart:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/device": {
      "abstract": [
        {
          "text": "The device associated with the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKDevice",
          "text": "HKDevice"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/device",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "device"
        }
      ],
      "role": "symbol",
      "title": "device",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/device"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/discardWorkout()": {
      "abstract": [
        {
          "text": "Stops the collection of data and discards the current results without saving the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discardWorkout"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/discardWorkout()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discardWorkout"
        }
      ],
      "role": "symbol",
      "title": "discardWorkout()",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/discardworkout()"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/elapsedTime(at:)": {
      "abstract": [
        {
          "text": "Calculates the duration of the workout at the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elapsedTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/elapsedTime(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elapsedTimeAtDate:"
        }
      ],
      "role": "symbol",
      "title": "elapsedTime(at:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/elapsedtime(at:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/endCollection(withEnd:completion:)": {
      "abstract": [
        {
          "text": "Stops the collection of data, sets the workout’s end date, and deactivates the workout builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/endCollection(withEnd:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endCollectionWithEndDate:completion:"
        }
      ],
      "role": "symbol",
      "title": "endCollection(withEnd:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/endcollection(withend:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/endDate": {
      "abstract": [
        {
          "text": "The workout’s end date and time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/endDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endDate"
        }
      ],
      "role": "symbol",
      "title": "endDate",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/enddate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/finishWorkout(completion:)": {
      "abstract": [
        {
          "text": "Creates the workout, using the samples and events added to the builder, and saves it to the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishWorkout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkout",
          "text": "HKWorkout"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/finishWorkout(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishWorkoutWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "finishWorkout(completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/finishworkout(completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/init(healthStore:configuration:device:)": {
      "abstract": [
        {
          "text": "Returns a new workout builder object that is not connected to a workout session or other data source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "healthStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKHealthStore",
          "text": "HKHealthStore"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutConfiguration",
          "text": "HKWorkoutConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKDevice",
          "text": "HKDevice"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/init(healthStore:configuration:device:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHealthStore:configuration:device:"
        }
      ],
      "role": "symbol",
      "title": "init(healthStore:configuration:device:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/init(healthstore:configuration:device:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/metadata": {
      "abstract": [
        {
          "text": "The metadata the builder saves with the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/metadata"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/seriesBuilder(for:)": {
      "abstract": [
        {
          "text": "Returns the series builder for the specified type, creating a new builder, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seriesBuilder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSeriesType",
          "text": "HKSeriesType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKSeriesBuilder",
          "text": "HKSeriesBuilder"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/seriesBuilder(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "seriesBuilderForType:"
        }
      ],
      "role": "symbol",
      "title": "seriesBuilder(for:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/seriesbuilder(for:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/startDate": {
      "abstract": [
        {
          "text": "The workout’s start date and time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/startdate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/statistics(for:)": {
      "abstract": [
        {
          "text": "Returns the statistics calculated for matching samples added to the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statistics"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuantityType",
          "text": "HKQuantityType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKStatistics",
          "text": "HKStatistics"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/statistics(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statisticsForType:"
        }
      ],
      "role": "symbol",
      "title": "statistics(for:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/statistics(for:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:adding:completion:)": {
      "abstract": [
        {
          "text": "Adds metadata to a workout activity that you’ve already added to the workout builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "uuid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adding"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:adding:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateActivityWithUUID:addMedatata:completion:"
        }
      ],
      "role": "symbol",
      "title": "updateActivity(uuid:adding:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/updateactivity(uuid:adding:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:end:completion:)": {
      "abstract": [
        {
          "text": "Sets the end date for a workout activity that you’ve already added to the workout builder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "uuid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "end"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:end:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateActivityWithUUID:endDate:completion:"
        }
      ],
      "role": "symbol",
      "title": "updateActivity(uuid:end:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/updateactivity(uuid:end:completion:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutActivities": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutActivities"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutActivity",
          "text": "HKWorkoutActivity"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutActivities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workoutActivities"
        }
      ],
      "role": "symbol",
      "title": "workoutActivities",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/workoutactivities"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutConfiguration": {
      "abstract": [
        {
          "text": "The configuration information for the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutConfiguration",
          "text": "HKWorkoutConfiguration"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workoutConfiguration"
        }
      ],
      "role": "symbol",
      "title": "workoutConfiguration",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/workoutconfiguration"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutEvents": {
      "abstract": [
        {
          "text": "The list of events added to the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutEvents"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutEvent",
          "text": "HKWorkoutEvent"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workoutEvents"
        }
      ],
      "role": "symbol",
      "title": "workoutEvents",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder/workoutevents"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent": {
      "abstract": [
        {
          "text": "An object representing an important event during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEvent"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession": {
      "abstract": [
        {
          "text": "A session that tracks the user’s workout on Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSession"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSession"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSession",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsession"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType": {
      "abstract": [
        {
          "text": "The type of session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType": {
      "abstract": [
        {
          "text": "A type that identifies samples that store information about a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier": {
      "abstract": [
        {
          "text": "The workout type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples": {
      "abstract": [
        {
          "text": "Read series data from condensed workouts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples",
      "kind": "article",
      "role": "article",
      "title": "Accessing condensed workout samples",
      "type": "topic",
      "url": "/documentation/healthkit/accessing-condensed-workout-samples"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout": {
      "abstract": [
        {
          "text": "Create associated samples that add details to a workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout",
      "kind": "article",
      "role": "article",
      "title": "Adding samples to a workout",
      "type": "topic",
      "url": "/documentation/healthkit/adding-samples-to-a-workout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities": {
      "abstract": [
        {
          "text": "Partition multisport and interval workouts into activities that represent the different parts of the workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities",
      "kind": "article",
      "role": "article",
      "title": "Dividing a HealthKit workout into activities",
      "type": "topic",
      "url": "/documentation/healthkit/dividing-a-healthkit-workout-into-activities"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Samples",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout",
        "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples",
        "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent"
      ],
      "title": "Samples"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-builder",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/init(healthStore:configuration:device:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/device",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutConfiguration"
      ],
      "title": "Creating the builder"
    },
    {
      "anchor": "Starting-the-workout",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/beginCollection(withStart:completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/startDate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/elapsedTime(at:)"
      ],
      "title": "Starting the workout"
    },
    {
      "anchor": "Associating-samples-with-the-workout",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/add(_:completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/seriesBuilder(for:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/statistics(for:)"
      ],
      "title": "Associating samples with the workout"
    },
    {
      "anchor": "Adding-metadata-to-the-workout",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addMetadata(_:completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/metadata"
      ],
      "title": "Adding metadata to the workout"
    },
    {
      "anchor": "Adding-events-to-the-workout",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutEvents(_:completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutEvents"
      ],
      "title": "Adding events to the workout"
    },
    {
      "anchor": "Managing-workout-activities",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutActivity(_:completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:adding:completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:end:completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutActivities"
      ],
      "title": "Managing workout activities"
    },
    {
      "anchor": "Ending-the-workout",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/endCollection(withEnd:completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/endDate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/finishWorkout(completion:)",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/discardWorkout()"
      ],
      "title": "Ending the workout"
    },
    {
      "anchor": "Accessing-workout-statistics",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/allStatistics"
      ],
      "title": "Accessing workout statistics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWorkoutBuilder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-builder",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/init(healthStore:configuration:device:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/device",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutConfiguration"
              ],
              "title": "Creating the builder"
            },
            {
              "anchor": "Starting-the-workout",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/beginCollection(withStart:completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/startDate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/elapsedTime(at:)"
              ],
              "title": "Starting the workout"
            },
            {
              "anchor": "Associating-samples-with-the-workout",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/add(_:completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/seriesBuilder(for:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/statistics(for:)"
              ],
              "title": "Associating samples with the workout"
            },
            {
              "anchor": "Adding-metadata-to-the-workout",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addMetadata(_:completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/metadata"
              ],
              "title": "Adding metadata to the workout"
            },
            {
              "anchor": "Adding-events-to-the-workout",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutEvents(_:completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutEvents"
              ],
              "title": "Adding events to the workout"
            },
            {
              "anchor": "Managing-workout-activities",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/addWorkoutActivity(_:completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:adding:completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/updateActivity(uuid:end:completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/workoutActivities"
              ],
              "title": "Managing workout activities"
            },
            {
              "anchor": "Ending-the-workout",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/endCollection(withEnd:completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/endDate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/finishWorkout(completion:)",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/discardWorkout()"
              ],
              "title": "Ending the workout"
            },
            {
              "anchor": "Accessing-workout-statistics",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder/allStatistics"
              ],
              "title": "Accessing workout statistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Samples",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent"
              ],
              "title": "Samples"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKWorkoutBuilder"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1addWorkoutEvents(_:completion:)/title",
          "value": "addWorkoutEvents:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1addWorkoutEvents(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addWorkoutEvents:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/title",
          "value": "HKLiveWorkoutBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKLiveWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKLiveWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1statistics(for:)/title",
          "value": "statisticsForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1statistics(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "statisticsForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/title",
          "value": "HKWorkoutEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1endDate/title",
          "value": "endDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1endDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/title",
          "value": "HKWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1discardWorkout()/title",
          "value": "discardWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1discardWorkout()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "discardWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1beginCollection(withStart:completion:)/title",
          "value": "beginCollectionWithStartDate:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1beginCollection(withStart:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginCollectionWithStartDate:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1device/title",
          "value": "device"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1device/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1add(_:completion:)/title",
          "value": "addSamples:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1add(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addSamples:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1workoutActivities/title",
          "value": "workoutActivities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1workoutActivities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "workoutActivities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1workoutConfiguration/title",
          "value": "workoutConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1workoutConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "workoutConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1updateActivity(uuid:end:completion:)/title",
          "value": "updateActivityWithUUID:endDate:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1updateActivity(uuid:end:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateActivityWithUUID:endDate:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title",
          "value": "HKWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1seriesBuilder(for:)/title",
          "value": "seriesBuilderForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1seriesBuilder(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "seriesBuilderForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1addMetadata(_:completion:)/title",
          "value": "addMetadata:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1addMetadata(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addMetadata:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutTypeIdentifier/title",
          "value": "HKWorkoutTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1updateActivity(uuid:adding:completion:)/title",
          "value": "updateActivityWithUUID:addMedatata:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1updateActivity(uuid:adding:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateActivityWithUUID:addMedatata:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/title",
          "value": "HKWorkoutType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/title",
          "value": "HKWorkoutActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1allStatistics/title",
          "value": "allStatistics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1allStatistics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allStatistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1elapsedTime(at:)/title",
          "value": "elapsedTimeAtDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1elapsedTime(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "elapsedTimeAtDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1init(healthStore:configuration:device:)/title",
          "value": "initWithHealthStore:configuration:device:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1init(healthStore:configuration:device:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHealthStore:configuration:device:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/title",
          "value": "HKWorkoutSessionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/title",
          "value": "HKWorkoutSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1addWorkoutActivity(_:completion:)/title",
          "value": "addWorkoutActivity:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1addWorkoutActivity(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addWorkoutActivity:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1finishWorkout(completion:)/title",
          "value": "finishWorkoutWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1finishWorkout(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishWorkoutWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/title",
          "value": "HKWorkoutBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1endCollection(withEnd:completion:)/title",
          "value": "endCollectionWithEndDate:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1endCollection(withEnd:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endCollectionWithEndDate:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1workoutEvents/title",
          "value": "workoutEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder~1workoutEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "workoutEvents"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkworkoutbuilder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkworkoutbuilder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
