{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/queries","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/predicate-format-strings"},"abstract":[{"type":"text","text":"Formatting strings for creating predicates."}],"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"HealthKit"}],"title":"Predicate format strings"},"topicSections":[{"anchor":"Object-keys","title":"Object keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathMetadata","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSum"]},{"anchor":"Quantity-sample-keys","title":"Quantity sample keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathQuantity"]},{"anchor":"Category-sample-keys","title":"Category sample keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCategoryValue"]},{"anchor":"Correlation-sample-keys","title":"Correlation sample keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCorrelation"]},{"anchor":"Device-and-source-keys","title":"Device and source keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathDevice","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSource","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSourceRevision"]},{"anchor":"Start-and-end-date-keys","title":"Start and end date keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathStartDate","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathEndDate"]},{"anchor":"Activity-summary-keys","title":"Activity summary keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathDateComponents"]},{"anchor":"Document-keys","title":"Document keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDAAuthorName","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDACustodianName","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDAPatientName","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDATitle"]},{"anchor":"Clinical-record-keys","title":"Clinical record keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathClinicalRecordFHIRResourceType"]},{"anchor":"Workout-keys","title":"Workout keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkout","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutDuration","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutAverageQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMaximumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMinimumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutSumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalDistance","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalEnergyBurned","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount"]},{"anchor":"Workout-activity-keys","title":"Workout activity keys","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivity","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityType","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityStartDate","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityEndDate","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityDuration","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityAverageQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMaximumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMinimumQuantity","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivitySumQuantity"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutSumQuantity":{"url":"/documentation/healthkit/hkpredicatekeypathworkoutsumquantity","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutSumQuantity","title":"HKPredicateKeyPathWorkoutSumQuantity","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutSumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"text":"The key path for accessing workouts with a matching sum.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutSumQuantity"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathQuantity":{"type":"topic","abstract":[{"type":"text","text":"The key path for accessing the sample’s quantity."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathQuantity"}],"title":"HKPredicateKeyPathQuantity","role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathQuantity","url":"/documentation/healthkit/hkpredicatekeypathquantity"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDATitle":{"title":"HKPredicateKeyPathCDATitle","role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathcdatitle","abstract":[{"type":"text","text":"The key path for accessing the document’s title inside a predicate format string."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathCDATitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathCDATitle"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDATitle"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMinimumQuantity":{"kind":"symbol","type":"topic","title":"HKPredicateKeyPathWorkoutMinimumQuantity","abstract":[{"text":"The key path for accessing workouts with a matching minimum quantity.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMinimumQuantity","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutMinimumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutMinimumQuantity"}],"role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkoutminimumquantity"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID":{"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID","url":"/documentation/healthkit/hkpredicatekeypathuuid","title":"HKPredicateKeyPathUUID","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathUUID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathUUID"}],"abstract":[{"type":"text","text":"The key path for accessing the object’s UUID inside a predicate format string."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityType":{"title":"HKPredicateKeyPathWorkoutActivityType","role":"symbol","navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutActivityType","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityType","url":"/documentation/healthkit/hkpredicatekeypathworkoutactivitytype","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[{"type":"text","text":"The key path for accessing activities that match a workout activity type."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathDateComponents":{"type":"topic","title":"HKPredicateKeyPathDateComponents","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathDateComponents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"/documentation/healthkit/hkpredicatekeypathdatecomponents","abstract":[{"text":"The key path for accessing an activity summary’s date components.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathDateComponents","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathDateComponents"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSource":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSource","url":"/documentation/healthkit/hkpredicatekeypathsource","kind":"symbol","abstract":[{"text":"The key path for accessing the object’s source inside a predicate format string.","type":"text"}],"type":"topic","title":"HKPredicateKeyPathSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathSource"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkout":{"title":"HKPredicateKeyPathWorkout","role":"symbol","kind":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkout","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkout","navigatorTitle":[{"text":"HKPredicateKeyPathWorkout","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The key path for accessing the object’s workout inside a predicate format string."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathDevice":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathDevice","url":"/documentation/healthkit/hkpredicatekeypathdevice","kind":"symbol","abstract":[{"text":"The key path for accessing the object’s device inside a predicate format string.","type":"text"}],"type":"topic","title":"HKPredicateKeyPathDevice","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathDevice"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalDistance":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkoutTotalDistance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","title":"HKPredicateKeyPathWorkoutTotalDistance","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalDistance","type":"topic","navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutTotalDistance","kind":"identifier"}],"abstract":[{"text":"The key path for accessing the workout’s total distance.","type":"text"}],"deprecated":true,"url":"/documentation/healthkit/hkpredicatekeypathworkouttotaldistance","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount":{"title":"HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount","role":"symbol","kind":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkouttotalswimmingstrokecount","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount","deprecated":true,"navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The key path for accessing the number of strokes during a swimming workout."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathClinicalRecordFHIRResourceType":{"abstract":[{"text":"The key path for accessing the resource type of a Fast Healthcare Interoperability Resources (FHIR) record.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathclinicalrecordfhirresourcetype","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathClinicalRecordFHIRResourceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"HKPredicateKeyPathClinicalRecordFHIRResourceType","kind":"identifier"}],"title":"HKPredicateKeyPathClinicalRecordFHIRResourceType","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathClinicalRecordFHIRResourceType"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathStartDate":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathStartDate","title":"HKPredicateKeyPathStartDate","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathStartDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"/documentation/healthkit/hkpredicatekeypathstartdate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathStartDate"}],"abstract":[{"text":"The key path for accessing the sample’s start date.","type":"text"}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDAAuthorName":{"title":"HKPredicateKeyPathCDAAuthorName","role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathcdaauthorname","abstract":[{"type":"text","text":"The key path for accessing the author’s name inside a predicate format string."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathCDAAuthorName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathCDAAuthorName"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDAAuthorName"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityEndDate":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityEndDate"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityEndDate","title":"HKPredicateKeyPathWorkoutActivityEndDate","url":"/documentation/healthkit/hkpredicatekeypathworkoutactivityenddate","navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutActivityEndDate","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The key path for accessing activities with a matching end date."}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDAPatientName":{"title":"HKPredicateKeyPathCDAPatientName","role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathcdapatientname","abstract":[{"type":"text","text":"The key path for accessing the patient’s name inside a predicate format string."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathCDAPatientName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathCDAPatientName"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDAPatientName"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivity":{"navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutActivity","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivity","url":"/documentation/healthkit/hkpredicatekeypathworkoutactivity","abstract":[{"type":"text","text":"The key path for accessing a specific workout activity."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivity"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"HKPredicateKeyPathWorkoutActivity"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathMetadata":{"kind":"symbol","url":"/documentation/healthkit/hkpredicatekeypathmetadata","abstract":[{"text":"The key path for accessing the object’s metadata dictionary inside a predicate format string.","type":"text"}],"title":"HKPredicateKeyPathMetadata","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"HKPredicateKeyPathMetadata","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathMetadata","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCategoryValue":{"role":"symbol","abstract":[{"text":"The key path for accessing the category sample’s value.","type":"text"}],"navigatorTitle":[{"text":"HKPredicateKeyPathCategoryValue","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCategoryValue","kind":"symbol","url":"/documentation/healthkit/hkpredicatekeypathcategoryvalue","type":"topic","title":"HKPredicateKeyPathCategoryValue","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathCategoryValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDACustodianName":{"title":"HKPredicateKeyPathCDACustodianName","role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathcdacustodianname","abstract":[{"type":"text","text":"The key path for accessing the custodian’s name inside a predicate format string."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathCDACustodianName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathCDACustodianName"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCDACustodianName"},"doc://com.apple.healthkit/documentation/HealthKit/queries":{"title":"Queries","abstract":[{"type":"text","text":"Query health and fitness data."}],"url":"/documentation/healthkit/queries","identifier":"doc://com.apple.healthkit/documentation/HealthKit/queries","role":"collectionGroup","type":"topic","kind":"article"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathEndDate":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathEndDate","title":"HKPredicateKeyPathEndDate","url":"/documentation/healthkit/hkpredicatekeypathenddate","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathEndDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathEndDate"}],"abstract":[{"type":"text","text":"The key path for accessing the sample’s end date."}],"role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier":{"title":"HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier","abstract":[{"type":"text","text":"The key path for accessing the clinical record’s Fast Healthcare Interoperability Resources (FHIR) identifier."}],"kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathclinicalrecordfhirresourceidentifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier","type":"topic","navigatorTitle":[{"text":"HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery":{"title":"HKQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQuery"}],"url":"/documentation/healthkit/hkquery","abstract":[{"type":"text","text":"An abstract class for all the query classes in HealthKit."}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQuery"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMaximumQuantity":{"kind":"symbol","navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutActivityMaximumQuantity","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMaximumQuantity","title":"HKPredicateKeyPathWorkoutActivityMaximumQuantity","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"HKPredicateKeyPathWorkoutActivityMaximumQuantity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[{"type":"text","text":"The key path for accessing activities with a matching maximum quantity."}],"url":"/documentation/healthkit/hkpredicatekeypathworkoutactivitymaximumquantity"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityDuration":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"HKPredicateKeyPathWorkoutActivityDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityDuration","title":"HKPredicateKeyPathWorkoutActivityDuration","url":"/documentation/healthkit/hkpredicatekeypathworkoutactivityduration","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityDuration"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The key path for accessing activities with a matching duration."}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutDuration":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkoutDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"HKPredicateKeyPathWorkoutDuration","url":"/documentation/healthkit/hkpredicatekeypathworkoutduration","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutDuration","navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutDuration","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The key path for accessing the workout’s duration.","type":"text"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivitySumQuantity":{"navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivitySumQuantity"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivitySumQuantity","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivitySumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkoutactivitysumquantity","title":"HKPredicateKeyPathWorkoutActivitySumQuantity","abstract":[{"type":"text","text":"The key path for accessing activities with a matching sum."}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalEnergyBurned":{"role":"symbol","navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutTotalEnergyBurned","kind":"identifier"}],"deprecated":true,"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalEnergyBurned","kind":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkouttotalenergyburned","title":"HKPredicateKeyPathWorkoutTotalEnergyBurned","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkoutTotalEnergyBurned","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"The key path for accessing the workout’s total energy burned.","type":"text"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSourceRevision":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathSourceRevision"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathSourceRevision"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSourceRevision","abstract":[{"text":"The key path for accessing the object’s source revision inside a predicate format string.","type":"text"}],"url":"/documentation/healthkit/hkpredicatekeypathsourcerevision","title":"HKPredicateKeyPathSourceRevision","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMaximumQuantity":{"kind":"symbol","type":"topic","title":"HKPredicateKeyPathWorkoutMaximumQuantity","abstract":[{"text":"The key path for accessing workouts with a matching maximum quantity.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutMaximumQuantity","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutMaximumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutMaximumQuantity"}],"role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkoutmaximumquantity"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCorrelation":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathCorrelation"}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCorrelation","title":"HKPredicateKeyPathCorrelation","url":"/documentation/healthkit/hkpredicatekeypathcorrelation","abstract":[{"text":"The key path for accessing the object’s correlation inside a predicate format string.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HKPredicateKeyPathCorrelation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityStartDate":{"navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityStartDate"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityStartDate","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkoutActivityStartDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkoutactivitystartdate","title":"HKPredicateKeyPathWorkoutActivityStartDate","abstract":[{"type":"text","text":"The key path for accessing activities with a matching start date."}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutAverageQuantity":{"role":"symbol","navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutAverageQuantity","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutAverageQuantity","kind":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkoutaveragequantity","title":"HKPredicateKeyPathWorkoutAverageQuantity","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkoutAverageQuantity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"The key path for accessing workouts with a matching average quantity.","type":"text"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType":{"abstract":[{"text":"The key path for accessing the workout’s type.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutType"}],"role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkouttype","title":"HKPredicateKeyPathWorkoutType"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed":{"role":"symbol","abstract":[{"type":"text","text":"The key path for accessing the total number of flights of stairs climbed during the workout."}],"navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutTotalFlightsClimbed","kind":"identifier"}],"deprecated":true,"title":"HKPredicateKeyPathWorkoutTotalFlightsClimbed","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed","type":"topic","url":"/documentation/healthkit/hkpredicatekeypathworkouttotalflightsclimbed","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkoutTotalFlightsClimbed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMinimumQuantity":{"url":"/documentation/healthkit/hkpredicatekeypathworkoutactivityminimumquantity","kind":"symbol","title":"HKPredicateKeyPathWorkoutActivityMinimumQuantity","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityMinimumQuantity"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityMinimumQuantity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityMinimumQuantity","type":"topic","role":"symbol","abstract":[{"text":"The key path for accessing activities with a matching minimum quantity.","type":"text"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSum":{"abstract":[{"type":"text","text":"The key path for accessing the sum of a quantity series inside a predicate format string."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathSum"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","url":"/documentation/healthkit/hkpredicatekeypathsum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathSum"}],"title":"HKPredicateKeyPathSum","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathSum","type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityAverageQuantity":{"url":"/documentation/healthkit/hkpredicatekeypathworkoutactivityaveragequantity","kind":"symbol","title":"HKPredicateKeyPathWorkoutActivityAverageQuantity","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityAverageQuantity"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityAverageQuantity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutActivityAverageQuantity","type":"topic","role":"symbol","abstract":[{"text":"The key path for accessing activities with a matching average quantity.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutSumQuantity/title","value":"HKPredicateKeyPathWorkoutSumQuantity"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutSumQuantity/fragments","value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutSumQuantity"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathQuantity/title","value":"HKPredicateKeyPathQuantity"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathQuantity/fragments","value":[{"text":"HKPredicateKeyPathQuantity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCDATitle/title","value":"HKPredicateKeyPathCDATitle"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCDATitle/fragments","value":[{"text":"HKPredicateKeyPathCDATitle","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutMinimumQuantity/title","value":"HKPredicateKeyPathWorkoutMinimumQuantity"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutMinimumQuantity/fragments","value":[{"text":"HKPredicateKeyPathWorkoutMinimumQuantity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathUUID/title","value":"HKPredicateKeyPathUUID"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathUUID/fragments","value":[{"kind":"identifier","text":"HKPredicateKeyPathUUID"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityType/title","value":"HKPredicateKeyPathWorkoutActivityType"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityType/fragments","value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathDateComponents/title","value":"HKPredicateKeyPathDateComponents"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathDateComponents/fragments","value":[{"text":"HKPredicateKeyPathDateComponents","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathSource/title","value":"HKPredicateKeyPathSource"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathSource/fragments","value":[{"text":"HKPredicateKeyPathSource","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkout/title","value":"HKPredicateKeyPathWorkout"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkout/fragments","value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkout"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathDevice/title","value":"HKPredicateKeyPathDevice"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathDevice/fragments","value":[{"kind":"identifier","text":"HKPredicateKeyPathDevice"}]},{"value":"HKPredicateKeyPathWorkoutTotalDistance","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalDistance/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutTotalDistance"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalDistance/fragments"},{"value":"HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalSwimmingStrokeCount/fragments"},{"value":"HKPredicateKeyPathClinicalRecordFHIRResourceType","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathClinicalRecordFHIRResourceType/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathClinicalRecordFHIRResourceType"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathClinicalRecordFHIRResourceType/fragments"},{"value":"HKPredicateKeyPathStartDate","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathStartDate/title"},{"value":[{"text":"HKPredicateKeyPathStartDate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathStartDate/fragments"},{"value":"HKPredicateKeyPathCDAAuthorName","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCDAAuthorName/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathCDAAuthorName"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCDAAuthorName/fragments"},{"value":"HKPredicateKeyPathWorkoutActivityEndDate","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityEndDate/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutActivityEndDate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityEndDate/fragments"},{"value":"HKPredicateKeyPathCDAPatientName","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCDAPatientName/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathCDAPatientName"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCDAPatientName/fragments"},{"value":"HKPredicateKeyPathWorkoutActivity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivity/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivity/fragments"},{"value":"HKPredicateKeyPathMetadata","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathMetadata/title"},{"value":[{"text":"HKPredicateKeyPathMetadata","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathMetadata/fragments"},{"value":"HKPredicateKeyPathCategoryValue","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCategoryValue/title"},{"value":[{"text":"HKPredicateKeyPathCategoryValue","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCategoryValue/fragments"},{"value":"HKPredicateKeyPathCDACustodianName","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCDACustodianName/title"},{"value":[{"text":"HKPredicateKeyPathCDACustodianName","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCDACustodianName/fragments"},{"value":"HKPredicateKeyPathEndDate","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathEndDate/title"},{"value":[{"text":"HKPredicateKeyPathEndDate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathEndDate/fragments"},{"value":"HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathClinicalRecordFHIRResourceIdentifier/fragments"},{"value":"HKQuery","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title"},{"value":[{"kind":"identifier","text":"HKQuery"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments"},{"value":[{"text":"HKQuery","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle"},{"value":"HKPredicateKeyPathWorkoutActivityMaximumQuantity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityMaximumQuantity/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutActivityMaximumQuantity","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityMaximumQuantity/fragments"},{"value":"HKPredicateKeyPathWorkoutActivityDuration","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityDuration/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutActivityDuration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityDuration/fragments"},{"value":"HKPredicateKeyPathWorkoutDuration","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutDuration/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutDuration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutDuration/fragments"},{"value":"HKPredicateKeyPathWorkoutActivitySumQuantity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivitySumQuantity/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivitySumQuantity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivitySumQuantity/fragments"},{"value":"HKPredicateKeyPathWorkoutTotalEnergyBurned","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalEnergyBurned/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutTotalEnergyBurned","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalEnergyBurned/fragments"},{"value":"HKPredicateKeyPathSourceRevision","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathSourceRevision/title"},{"value":[{"text":"HKPredicateKeyPathSourceRevision","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathSourceRevision/fragments"},{"value":"HKPredicateKeyPathWorkoutMaximumQuantity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutMaximumQuantity/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutMaximumQuantity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutMaximumQuantity/fragments"},{"value":"HKPredicateKeyPathCorrelation","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCorrelation/title"},{"value":[{"text":"HKPredicateKeyPathCorrelation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCorrelation/fragments"},{"value":"HKPredicateKeyPathWorkoutActivityStartDate","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityStartDate/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutActivityStartDate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityStartDate/fragments"},{"value":"HKPredicateKeyPathWorkoutAverageQuantity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutAverageQuantity/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutAverageQuantity","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutAverageQuantity/fragments"},{"value":"HKPredicateKeyPathWorkoutType","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutType/title"},{"value":[{"text":"HKPredicateKeyPathWorkoutType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutType/fragments"},{"value":"HKPredicateKeyPathWorkoutTotalFlightsClimbed","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalFlightsClimbed/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutTotalFlightsClimbed"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalFlightsClimbed/fragments"},{"value":"HKPredicateKeyPathWorkoutActivityMinimumQuantity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityMinimumQuantity/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityMinimumQuantity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityMinimumQuantity/fragments"},{"value":"HKPredicateKeyPathSum","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathSum/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathSum"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathSum/fragments"},{"value":"HKPredicateKeyPathWorkoutActivityAverageQuantity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityAverageQuantity/title"},{"value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutActivityAverageQuantity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutActivityAverageQuantity/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}