{
  "abstract": [
    {
      "text": "Query health and fitness data.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/queries"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Queries"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use queries to read sample data from the HealthKit store. You can also use queries to list all the sources for a particular data type, or to perform statistical calculations for a data type. For example, statistical queries can calculate the minimum and maximum heart rate for a given week, or the total step count for a given day.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You run a query by calling the HealthKit store’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. HealthKit returns a snapshot of the current results to the query’s results handler. Long-running queries continue to monitor the HealthKit store, and return any relevant changes to the query’s update handler. To return sorted or filtered results, give the query a sort descriptor or predicate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery": {
      "abstract": [
        {
          "text": "A query for reading activity summary objects from the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQuery"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummaryQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummaryquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads activity summaries using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummaryQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummaryquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery": {
      "abstract": [
        {
          "text": "A query that returns changes to the HealthKit store, including a snapshot of new changes and continuous monitoring as a long-running query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQuery"
        }
      ],
      "role": "symbol",
      "title": "HKAnchoredObjectQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkanchoredobjectquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that runs anchored object queries using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKAnchoredObjectQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkanchoredobjectquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAsyncQuery": {
      "abstract": [
        {
          "text": "A protocol that defines an asynchronous method for running queries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAsyncQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAsyncQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAsyncQuery"
        }
      ],
      "role": "symbol",
      "title": "HKAsyncQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkasyncquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAsyncSequenceQuery": {
      "abstract": [
        {
          "text": "A protocol that defines a method for running queries that returns results using an asynchronous sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAsyncSequenceQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAsyncSequenceQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAsyncSequenceQuery"
        }
      ],
      "role": "symbol",
      "title": "HKAsyncSequenceQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkasyncsequencequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery": {
      "abstract": [
        {
          "text": "A query that performs complex searches based on the correlation’s contents, and returns a snapshot of all matching samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCorrelationQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCorrelationQuery"
        }
      ],
      "role": "symbol",
      "title": "HKCorrelationQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkcorrelationquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevice": {
      "abstract": [
        {
          "text": "A device that generates data for HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevice"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevice"
        }
      ],
      "role": "symbol",
      "title": "HKDevice",
      "type": "topic",
      "url": "/documentation/healthkit/hkdevice"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDocumentQuery": {
      "abstract": [
        {
          "text": "A query that returns a snapshot of all matching documents currently saved in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDocumentQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDocumentQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDocumentQuery"
        }
      ],
      "role": "symbol",
      "title": "HKDocumentQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkdocumentquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramQuery": {
      "abstract": [
        {
          "text": "A query that returns the underlying voltage measurements for an electrocardiogram sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramQuery"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogramQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogramquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads the underlying voltage measurements for an electrocardiogram sample using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogramQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogramquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore": {
      "abstract": [
        {
          "text": "The access point for all data managed by HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "role": "symbol",
      "title": "HKHealthStore",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)": {
      "abstract": [
        {
          "text": "Starts executing the provided query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKQuery",
          "text": "HKQuery"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore/execute(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executeQuery:"
        }
      ],
      "role": "symbol",
      "title": "execute(_:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/execute(_:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartbeatSeriesQuery": {
      "abstract": [
        {
          "text": "A query that returns the heartbeat data contained in a heartbeat series sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHeartbeatSeriesQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartbeatSeriesQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartbeatSeriesQuery"
        }
      ],
      "role": "symbol",
      "title": "HKHeartbeatSeriesQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartbeatseriesquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHeartbeatSeriesQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads the heartbeat series data stored in a heartbeat sample using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHeartbeatSeriesQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHeartbeatSeriesQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHeartbeatSeriesQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKHeartbeatSeriesQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkheartbeatseriesquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery": {
      "abstract": [
        {
          "text": "A long-running query that monitors the HealthKit store and updates your app when the HealthKit store saves or deletes a matching sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKObserverQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKObserverQuery"
        }
      ],
      "role": "symbol",
      "title": "HKObserverQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkobserverquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQuery": {
      "abstract": [
        {
          "text": "A query that accesses the series data associated with a quantity sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantitySeriesSampleQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantitySeriesSampleQuery"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySeriesSampleQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityseriessamplequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads the series data associated with quantity samples using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantitySeriesSampleQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantitySeriesSampleQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySeriesSampleQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityseriessamplequerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery": {
      "abstract": [
        {
          "text": "An abstract class for all the query classes in HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuery"
        }
      ],
      "role": "symbol",
      "title": "HKQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQueryDescriptor": {
      "abstract": [
        {
          "text": "A descriptor that specifies a set of samples based on the data type and a predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate": {
      "abstract": [
        {
          "text": "A predicate for queries that return a collection of matching sample objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSamplePredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSamplePredicate"
        }
      ],
      "role": "symbol",
      "title": "HKSamplePredicate",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplepredicate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery": {
      "abstract": [
        {
          "text": "A general query that returns a snapshot of all the matching samples currently saved in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSampleQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSampleQuery"
        }
      ],
      "role": "symbol",
      "title": "HKSampleQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads samples using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSampleQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSampleQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKSampleQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hksamplequerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSource": {
      "abstract": [
        {
          "text": "An object indicating the app or device that created a HealthKit sample",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSource"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSource"
        }
      ],
      "role": "symbol",
      "title": "HKSource",
      "type": "topic",
      "url": "/documentation/healthkit/hksource"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSourceQuery": {
      "abstract": [
        {
          "text": "A query that returns a list of sources, such as apps and devices, that have saved matching queries to the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSourceQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSourceQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSourceQuery"
        }
      ],
      "role": "symbol",
      "title": "HKSourceQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hksourcequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSourceQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that uses Swift concurrency to read the apps and devices that produced the matching samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSourceQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSourceQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSourceQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKSourceQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hksourcequerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevision": {
      "abstract": [
        {
          "text": "An object indicating the source of a HealthKit sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSourceRevision"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSourceRevision"
        }
      ],
      "role": "symbol",
      "title": "HKSourceRevision",
      "type": "topic",
      "url": "/documentation/healthkit/hksourcerevision"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatistics": {
      "abstract": [
        {
          "text": "An object that represents the result of calculating the minimum, maximum, average, or sum over a set of samples from the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatistics"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatistics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatistics"
        }
      ],
      "role": "symbol",
      "title": "HKStatistics",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatistics"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollection": {
      "abstract": [
        {
          "text": "An object that manages a collection of statistics, representing the results calculated over separate time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsCollection"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsCollection"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsCollection",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollection"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQuery": {
      "abstract": [
        {
          "text": "A query that performs multiple statistics queries over a series of fixed-length time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQuery"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsCollectionQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor": {
      "abstract": [
        {
          "text": "A query descriptor that gathers a collection of statistics calculated over a series of fixed-length time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsCollectionQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsCollectionQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticscollectionquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions": {
      "abstract": [
        {
          "text": "Options for specifying the statistic to calculate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsOptions"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsOptions"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsOptions",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticsoptions"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQuery": {
      "abstract": [
        {
          "text": "A query that performs statistical calculations over a set of matching quantity samples, and returns the results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsQuery"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticsquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor": {
      "abstract": [
        {
          "text": "A query descriptor that calculates the minimum, maximum, average, or sum over a set of samples from the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStatisticsQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStatisticsQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKStatisticsQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkstatisticsquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType": {
      "abstract": [
        {
          "text": "The type of record returned by a verifiable clinical record query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVerifiableClinicalRecordCredentialType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVerifiableClinicalRecordCredentialType"
        }
      ],
      "role": "symbol",
      "title": "HKVerifiableClinicalRecordCredentialType",
      "type": "topic",
      "url": "/documentation/healthkit/hkverifiableclinicalrecordcredentialtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQuery": {
      "abstract": [
        {
          "text": "A query for one-time access to a SMART Health Card or EU Digital COVID Certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVerifiableClinicalRecordQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVerifiableClinicalRecordQuery"
        }
      ],
      "role": "symbol",
      "title": "HKVerifiableClinicalRecordQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkverifiableclinicalrecordquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that provides one-time access to a SMART Health Card or EU Digital COVID Certificate using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVerifiableClinicalRecordQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVerifiableClinicalRecordQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKVerifiableClinicalRecordQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkverifiableclinicalrecordquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordSourceType": {
      "abstract": [
        {
          "text": "The source type for the verifiable clinical record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKVerifiableClinicalRecordSourceType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKVerifiableClinicalRecordSourceType"
        }
      ],
      "role": "symbol",
      "title": "HKVerifiableClinicalRecordSourceType",
      "type": "topic",
      "url": "/documentation/healthkit/hkverifiableclinicalrecordsourcetype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery": {
      "abstract": [
        {
          "text": "A query to access the location data stored in a workout route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQuery"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutRouteQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutroutequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads the location data stored in a workout route using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutRouteQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutroutequerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/creating-a-mobility-health-app": {
      "abstract": [
        {
          "text": "Create a health app that allows a clinical care team to send and receive mobility data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/creating-a-mobility-health-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a Mobility Health App",
      "type": "topic",
      "url": "/documentation/healthkit/creating-a-mobility-health-app"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/data-types": {
      "abstract": [
        {
          "text": "Specify the kind of data used in HealthKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data types",
      "type": "topic",
      "url": "/documentation/healthkit/data-types"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/executing-statistical-queries": {
      "abstract": [
        {
          "text": "Create and run statistical queries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/executing-statistical-queries",
      "kind": "article",
      "role": "article",
      "title": "Executing Statistical Queries",
      "type": "topic",
      "url": "/documentation/healthkit/executing-statistical-queries"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries": {
      "abstract": [
        {
          "text": "Calculate statistical data for graphs and charts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries",
      "kind": "article",
      "role": "article",
      "title": "Executing Statistics Collection Queries",
      "type": "topic",
      "url": "/documentation/healthkit/executing-statistics-collection-queries"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit": {
      "abstract": [
        {
          "text": "Use queries to request sample data from HealthKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit",
      "kind": "article",
      "role": "article",
      "title": "Reading data from HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit/reading-data-from-healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/running-queries-with-swift-concurrency": {
      "abstract": [
        {
          "text": "Use Swift concurrency to manage one-shot and long-running queries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/running-queries-with-swift-concurrency",
      "kind": "article",
      "role": "article",
      "title": "Running Queries with Swift Concurrency",
      "type": "topic",
      "url": "/documentation/healthkit/running-queries-with-swift-concurrency"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/samples": {
      "abstract": [
        {
          "text": "Create and save health and fitness samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/samples",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Samples",
      "type": "topic",
      "url": "/documentation/healthkit/samples"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/saving-data-to-healthkit": {
      "abstract": [
        {
          "text": "Create and share HealthKit samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/saving-data-to-healthkit",
      "kind": "article",
      "role": "article",
      "title": "Saving data to HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit/saving-data-to-healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/visualizing-healthkit-state-of-mind-in-visionos": {
      "abstract": [
        {
          "text": "Incorporate HealthKit State of Mind into your app and visualize the data in visionOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/visualizing-healthkit-state-of-mind-in-visionos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Visualizing HealthKit State of Mind in visionOS",
      "type": "topic",
      "url": "/documentation/healthkit/visualizing-healthkit-state-of-mind-in-visionos"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Health-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/saving-data-to-healthkit",
        "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
        "doc://com.apple.healthkit/documentation/HealthKit/creating-a-mobility-health-app",
        "doc://com.apple.healthkit/documentation/HealthKit/data-types",
        "doc://com.apple.healthkit/documentation/HealthKit/samples",
        "doc://com.apple.healthkit/documentation/HealthKit/visualizing-healthkit-state-of-mind-in-visionos"
      ],
      "title": "Health data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/reading-data-from-healthkit"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Swift-concurrency-support",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/running-queries-with-swift-concurrency",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAsyncQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAsyncSequenceQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate"
      ],
      "title": "Swift concurrency support"
    },
    {
      "anchor": "Basic-queries",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSampleQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCorrelationQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuery"
      ],
      "title": "Basic queries"
    },
    {
      "anchor": "Series-queries",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartbeatSeriesQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKHeartbeatSeriesQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogramQuery"
      ],
      "title": "Series queries"
    },
    {
      "anchor": "Long-running-queries",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKObserverQuery"
      ],
      "title": "Long-running queries"
    },
    {
      "anchor": "Sources-and-devices",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKSourceQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSourceRevision",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSource",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevice",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSourceQuery"
      ],
      "title": "Sources and devices"
    },
    {
      "anchor": "Statistics",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/executing-statistical-queries",
        "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollectionQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatistics",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsCollection",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions"
      ],
      "title": "Statistics"
    },
    {
      "anchor": "Clinical-record-queries",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordSourceType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDocumentQuery"
      ],
      "title": "Clinical record queries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramQuery/title",
          "value": "HKElectrocardiogramQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogramQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsQuery/title",
          "value": "HKStatisticsQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatistics/title",
          "value": "HKStatistics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatistics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatistics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollection/title",
          "value": "HKStatisticsCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollectionQuery/title",
          "value": "HKStatisticsCollectionQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollectionQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsCollectionQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsCollectionQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsCollectionQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySeriesSampleQuery/title",
          "value": "HKQuantitySeriesSampleQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySeriesSampleQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySeriesSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySeriesSampleQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantitySeriesSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery/title",
          "value": "HKCorrelationQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCorrelationQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCorrelationQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryDescriptor/title",
          "value": "HKQueryDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQueryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQueryDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQueryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordQuery/title",
          "value": "HKVerifiableClinicalRecordQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVerifiableClinicalRecordQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVerifiableClinicalRecordQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartbeatSeriesQuery/title",
          "value": "HKHeartbeatSeriesQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartbeatSeriesQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartbeatSeriesQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHeartbeatSeriesQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHeartbeatSeriesQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceQuery/title",
          "value": "HKSourceQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSourceQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSourceQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/title",
          "value": "HKWorkoutRouteQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSource/title",
          "value": "HKSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1execute(_:)/title",
          "value": "executeQuery:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore~1execute(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "executeQuery:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordSourceType/title",
          "value": "HKVerifiableClinicalRecordSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVerifiableClinicalRecordSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVerifiableClinicalRecordSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title",
          "value": "HKQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/title",
          "value": "HKStatisticsOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStatisticsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevision/title",
          "value": "HKSourceRevision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSourceRevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceRevision/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSourceRevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery/title",
          "value": "HKObserverQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKObserverQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObserverQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKObserverQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/title",
          "value": "HKVerifiableClinicalRecordCredentialType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVerifiableClinicalRecordCredentialType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKVerifiableClinicalRecordCredentialType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/title",
          "value": "HKActivitySummaryQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/title",
          "value": "HKAnchoredObjectQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAnchoredObjectQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAnchoredObjectQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/title",
          "value": "HKDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDocumentQuery/title",
          "value": "HKDocumentQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDocumentQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDocumentQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDocumentQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDocumentQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/title",
          "value": "HKSampleQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSampleQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSampleQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/title",
          "value": "HKHealthStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
