{
  "abstract": [
    {
      "text": "Receive segments and distance samples during downhill skiing and snowboarding workout sessions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/receiving-downhill-skiing-and-snowboarding-data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Receiving Downhill Skiing and Snowboarding Data"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On Apple Watch Series 3, the system automatically generates distance samples, segments, and pause and resume events during ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " workout sessions. Monitor these samples to receive additional information about individual runs. You can then display this information on the watch during the session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Receiving-Distance-Samples",
          "level": 3,
          "text": "Receiving Distance Samples",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system generates a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceDownhillSnowSports",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sample at the end of each run. Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " query to receive and process these samples.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let updateHandler: ((HKAnchoredObjectQuery, [HKSample]?, [HKDeletedObject]?, HKQueryAnchor?, Error?) -> Void) = { [unowned self] (query, samplesOrNil, deletedObjectsOrNil, newAnchorOrNil, errorOrNil) in",
            "    ",
            "    // Check for errors.",
            "    if let error = errorOrNil {",
            "        // Handle the error here.",
            "        print(\"*** An error occurred: \\(error.localizedDescription) ***\")",
            "        return",
            "    }",
            "    ",
            "    // Process the samples.",
            "    if let samples = samplesOrNil  {",
            "        // Do something with the distance samples here.",
            "        print(\"Samples: \\(samples)\")",
            "    }",
            "    ",
            "    // Update the anchor.",
            "    if let newAnchor = newAnchorOrNil {",
            "        self.myCurrentAnchor = newAnchor",
            "    }",
            "}",
            "// Get the downhill skiing type.",
            "guard let downhillSnowSport = HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier.distanceDownhillSnowSports) else {",
            "    fatalError(\"*** Unable to get the downhill snow sport type ***\")",
            "}",
            "// Only find samples that start after the workout began.",
            "let datePredicate = NSPredicate(format: \"%K > %@\", HKPredicateKeyPathStartDate, workoutStartDate as NSDate)",
            "let distanceQuery = HKAnchoredObjectQuery(type: downhillSnowSport,",
            "                                          predicate: datePredicate,",
            "                                          anchor: myCurrentAnchor,",
            "                                          limit: HKObjectQueryNoLimit,",
            "                                          resultsHandler: updateHandler)",
            "distanceQuery.updateHandler = updateHandler",
            "// Run the query.",
            "store.execute(distanceQuery)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Receiving-Segments",
          "level": 3,
          "text": "Receiving Segments",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system generates a segment event for each run. This event is passed to your app using the session delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didGenerate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func workoutSession(_ workoutSession: HKWorkoutSession, didGenerate event: HKWorkoutEvent) {",
            "    ",
            "    // Check to see if the event is a segment.",
            "    if event.type == .segment {",
            "        ",
            "        // Get the segment's start and end times.",
            "        let startTime = event.dateInterval.start",
            "        let endTime = event.dateInterval.end",
            "        ",
            "        // Get the segment's metadata.",
            "        let averageSpeed = event.metadata?[HKMetadataKeyAverageSpeed]",
            "        let maxSpeed = event.metadata?[HKMetadataKeyMaximumSpeed]",
            "        let alpineSlope = event.metadata?[HKMetadataKeyAlpineSlopeGrade]",
            "        let elevationAscended = event.metadata?[HKMetadataKeyElevationAscended]",
            "        let elevationDescended = event.metadata?[HKMetadataKeyElevationDescended]",
            "        ",
            "        // Do something with the segment data here...",
            "        ",
            "    }",
            "    ",
            "    // Also handle any other event types...",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Each autogenerated segment has a metadata dictionary with the following keys and values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageSpeed",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumSpeed",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAlpineSlopeGrade",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationDescended",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationAscended",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Handling-Pause-and-Resume-Events",
          "level": 3,
          "text": "Handling Pause and Resume Events",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system automatically generates ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionPaused",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionResumed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " events for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sessions:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionPaused",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " events are generated at the end of each run.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionResumed",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " events are generated at the beginning of the next run.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "These events are similar to the motion events generated for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " workout sessions; however, unlike ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sessions, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sessions do not continue to run in the background while paused. As a result, you should use these events to pause and resume any other long-running tasks your app is performing (for example, location tracking).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery": {
      "abstract": [
        {
          "text": "A query that returns changes to the HealthKit store, including a snapshot of new changes and continuous monitoring as a long-running query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAnchoredObjectQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAnchoredObjectQuery"
        }
      ],
      "role": "symbol",
      "title": "HKAnchoredObjectQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkanchoredobjectquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAlpineSlopeGrade": {
      "abstract": [
        {
          "text": "A key that indicates the percent slope of a ski run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAlpineSlopeGrade"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAlpineSlopeGrade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAlpineSlopeGrade"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyAlpineSlopeGrade",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyalpineslopegrade"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageSpeed": {
      "abstract": [
        {
          "text": "A key that indicates the average speed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAverageSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAverageSpeed"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyAverageSpeed",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyaveragespeed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationAscended": {
      "abstract": [
        {
          "text": "A key that indicates the cumulative elevation ascended during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyElevationAscended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationAscended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyElevationAscended"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyElevationAscended",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyelevationascended"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationDescended": {
      "abstract": [
        {
          "text": "A key that indicates the cumulative elevation descended during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyElevationDescended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationDescended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyElevationDescended"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyElevationDescended",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyelevationdescended"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumSpeed": {
      "abstract": [
        {
          "text": "A key that indicates the maximum speed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyMaximumSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyMaximumSpeed"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyMaximumSpeed",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeymaximumspeed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceDownhillSnowSports": {
      "abstract": [
        {
          "text": "A quantity sample type that measures the distance the user has traveled while skiing or snowboarding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceDownhillSnowSports"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKQuantityTypeIdentifier",
          "text": "HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantityTypeIdentifier/distanceDownhillSnowSports",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantityTypeIdentifierDistanceDownhillSnowSports"
        }
      ],
      "role": "symbol",
      "title": "distanceDownhillSnowSports",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/distancedownhillsnowsports"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing": {
      "abstract": [
        {
          "text": "The constant for downhill skiing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downhillSkiing"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/downhillSkiing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeDownhillSkiing"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.downhillSkiing",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/downhillskiing"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running": {
      "abstract": [
        {
          "text": "The constant for running and jogging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeRunning"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.running",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/running"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding": {
      "abstract": [
        {
          "text": "The constant for snowboarding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snowboarding"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType/snowboarding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityTypeSnowboarding"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType.snowboarding",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype/snowboarding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionPaused": {
      "abstract": [
        {
          "text": "A constant indicating that the system has automatically paused a workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionPaused"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionPaused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypeMotionPaused"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.motionPaused",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/motionpaused"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionResumed": {
      "abstract": [
        {
          "text": "A constant indicating that the system has automatically resumed a workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionResumed"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionResumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypeMotionResumed"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.motionResumed",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/motionresumed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didGenerate:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system generated a workout event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutSession",
          "text": "HKWorkoutSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didGenerate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKWorkoutEvent",
          "text": "HKWorkoutEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionDelegate/workoutSession(_:didGenerate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workoutSession:didGenerateEvent:"
        }
      ],
      "role": "symbol",
      "title": "workoutSession(_:didGenerate:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiondelegate/workoutsession(_:didgenerate:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings": {
      "abstract": [
        {
          "text": "Manage workouts, workout sessions, and activity summaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workouts and activity rings",
      "type": "topic",
      "url": "/documentation/healthkit/workouts-and-activity-rings"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyElevationAscended/title",
          "value": "HKMetadataKeyElevationAscended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyElevationAscended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyElevationAscended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyElevationDescended/title",
          "value": "HKMetadataKeyElevationDescended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyElevationDescended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyElevationDescended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceDownhillSnowSports/title",
          "value": "HKQuantityTypeIdentifierDistanceDownhillSnowSports"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantityTypeIdentifier~1distanceDownhillSnowSports/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuantityTypeIdentifierDistanceDownhillSnowSports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1motionResumed/title",
          "value": "HKWorkoutEventTypeMotionResumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1motionResumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeMotionResumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyMaximumSpeed/title",
          "value": "HKMetadataKeyMaximumSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyMaximumSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyMaximumSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1snowboarding/title",
          "value": "HKWorkoutActivityTypeSnowboarding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1snowboarding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSnowboarding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1motionPaused/title",
          "value": "HKWorkoutEventTypeMotionPaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1motionPaused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeMotionPaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAverageSpeed/title",
          "value": "HKMetadataKeyAverageSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAverageSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyAverageSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAlpineSlopeGrade/title",
          "value": "HKMetadataKeyAlpineSlopeGrade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAlpineSlopeGrade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyAlpineSlopeGrade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/title",
          "value": "HKAnchoredObjectQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAnchoredObjectQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAnchoredObjectQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAnchoredObjectQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didGenerate:)/title",
          "value": "workoutSession:didGenerateEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionDelegate~1workoutSession(_:didGenerate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workoutSession:didGenerateEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1downhillSkiing/title",
          "value": "HKWorkoutActivityTypeDownhillSkiing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1downhillSkiing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeDownhillSkiing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title",
          "value": "HKWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1running/title",
          "value": "HKWorkoutActivityTypeRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeRunning"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
