{
  "abstract": [
    {
      "text": "Manage workouts, workout sessions, and activity summaries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Workouts and activity rings"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A workout is a sample that contains data about an exercise or fitness activity. You save workout data using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class. In many ways, workouts are identical to any other HealthKit sample—the same advice and APIs apply to both workouts and samples. However, workouts do have a number of unique features, described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Workout sessions let you track the user’s activity on Apple Watch. While  a workout session is active, your app can continue to run in the background. This lets your app monitor the user and gather data throughout the activity. Additionally, it ensures that your app appears whenever the user checks their watch. After the session ends, your app saves the activity’s data as a workout sample. For more information on setting up and running workout sessions, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Activity Rings display a summary of the user’s daily activity on Apple Watch and in the Activity app. Activity summaries provide access to the data displayed in the user’s Move, Exercise, and Stand rings. To see how your workout samples contribute to these rings, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout#Fill-the-Activity-rings",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To learn more about accessing and displaying activity data in your app, see Activity rings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, workout routes record the user’s path during an outdoor activity (for example, while walking, running, or cycling). Routes can be associated with a workout sample. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/creating-a-workout-route",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/reading-route-data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivityMoveModeObject": {
      "abstract": [
        {
          "text": "An object that contains a movement mode value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivityMoveModeObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivityMoveModeObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivityMoveModeObject"
        }
      ],
      "role": "symbol",
      "title": "HKActivityMoveModeObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitymovemodeobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary": {
      "abstract": [
        {
          "text": "An object that contains the move, exercise, and stand data for a given day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummary"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummary"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummary",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummary"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery": {
      "abstract": [
        {
          "text": "A query for reading activity summary objects from the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQuery"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummaryQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummaryquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads activity summaries using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivitySummaryQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKActivitySummaryQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkactivitysummaryquerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder": {
      "abstract": [
        {
          "text": "A builder object that constructs a workout incrementally based on live data from an active workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKLiveWorkoutBuilder"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKLiveWorkoutBuilder"
        }
      ],
      "role": "symbol",
      "title": "HKLiveWorkoutBuilder",
      "type": "topic",
      "url": "/documentation/healthkit/hkliveworkoutbuilder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource": {
      "abstract": [
        {
          "text": "A data source that automatically provides live data from an active workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKLiveWorkoutDataSource"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKLiveWorkoutDataSource"
        }
      ],
      "role": "symbol",
      "title": "HKLiveWorkoutDataSource",
      "type": "topic",
      "url": "/documentation/healthkit/hkliveworkoutdatasource"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesBuilder": {
      "abstract": [
        {
          "text": "An abstract base class for building series samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSeriesBuilder"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSeriesBuilder"
        }
      ],
      "role": "symbol",
      "title": "HKSeriesBuilder",
      "type": "topic",
      "url": "/documentation/healthkit/hkseriesbuilder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample": {
      "abstract": [
        {
          "text": "An abstract base class that defines samples that contain a series of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSeriesSample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSeriesSample"
        }
      ],
      "role": "symbol",
      "title": "HKSeriesSample",
      "type": "topic",
      "url": "/documentation/healthkit/hkseriessample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout": {
      "abstract": [
        {
          "text": "A workout sample that stores information about a single physical activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "role": "symbol",
      "title": "HKWorkout",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout#Fill-the-Activity-rings": {
      "abstract": [],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout#Fill-the-Activity-rings",
      "kind": "section",
      "title": "Fill the Activity rings",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkout#Fill-the-Activity-rings"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity": {
      "abstract": [
        {
          "text": "An object that describes an activity within a longer workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivity"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivity",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType": {
      "abstract": [
        {
          "text": "The type of activity performed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder": {
      "abstract": [
        {
          "text": "A builder object that incrementally constructs a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutBuilder"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutBuilder"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutBuilder",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutbuilder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutConfiguration": {
      "abstract": [
        {
          "text": "An object that contains configuration information about a workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutConfiguration"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutConfiguration"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutConfiguration",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutconfiguration"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent": {
      "abstract": [
        {
          "text": "An object representing an important event during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEvent"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEvent"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEvent",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutevent"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRoute": {
      "abstract": [
        {
          "text": "A sample that contains a workout’s route data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutRoute"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRoute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutRoute"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutRoute",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutroute"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteBuilder": {
      "abstract": [
        {
          "text": "A builder object that incrementally constructs a workout route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteBuilder"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteBuilder"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutRouteBuilder",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutroutebuilder"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery": {
      "abstract": [
        {
          "text": "A query to access the location data stored in a workout route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQuery"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutRouteQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutroutequery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads the location data stored in a workout route using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutRouteQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutroutequerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteTypeIdentifier": {
      "abstract": [
        {
          "text": "A series sample containing location data that defines the route the user took during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutRouteTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutroutetypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession": {
      "abstract": [
        {
          "text": "A session that tracks the user’s workout on Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSession"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSession"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSession",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsession"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState": {
      "abstract": [
        {
          "text": "A workout session’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionState"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionState"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionState",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessionstate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType": {
      "abstract": [
        {
          "text": "The type of session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutSessionType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutSessionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutsessiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType": {
      "abstract": [
        {
          "text": "A type that identifies samples that store information about a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier": {
      "abstract": [
        {
          "text": "The workout type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouttypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples": {
      "abstract": [
        {
          "text": "Read series data from condensed workouts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples",
      "kind": "article",
      "role": "article",
      "title": "Accessing condensed workout samples",
      "type": "topic",
      "url": "/documentation/healthkit/accessing-condensed-workout-samples"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout": {
      "abstract": [
        {
          "text": "Create associated samples that add details to a workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout",
      "kind": "article",
      "role": "article",
      "title": "Adding samples to a workout",
      "type": "topic",
      "url": "/documentation/healthkit/adding-samples-to-a-workout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/build-a-workout-app-for-apple-watch": {
      "abstract": [
        {
          "text": "Create your own workout app, quickly and easily, with HealthKit and SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/build-a-workout-app-for-apple-watch",
      "kind": "article",
      "role": "sampleCode",
      "title": "Build a workout app for Apple Watch",
      "type": "topic",
      "url": "/documentation/healthkit/build-a-workout-app-for-apple-watch"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/building-a-multidevice-workout-app": {
      "abstract": [
        {
          "text": "Mirror a workout from a watchOS app to its companion iOS app, and perform bidirectional communication between them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/building-a-multidevice-workout-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building a multidevice workout app",
      "type": "topic",
      "url": "/documentation/healthkit/building-a-multidevice-workout-app"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/creating-a-workout-route": {
      "abstract": [
        {
          "text": "Record the user’s route during a workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/creating-a-workout-route",
      "kind": "article",
      "role": "article",
      "title": "Creating a workout route",
      "type": "topic",
      "url": "/documentation/healthkit/creating-a-workout-route"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities": {
      "abstract": [
        {
          "text": "Partition multisport and interval workouts into activities that represent the different parts of the workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities",
      "kind": "article",
      "role": "article",
      "title": "Dividing a HealthKit workout into activities",
      "type": "topic",
      "url": "/documentation/healthkit/dividing-a-healthkit-workout-into-activities"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/reading-route-data": {
      "abstract": [
        {
          "text": "Access the user’s route for a workout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/reading-route-data",
      "kind": "article",
      "role": "article",
      "title": "Reading route data",
      "type": "topic",
      "url": "/documentation/healthkit/reading-route-data"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions": {
      "abstract": [
        {
          "text": "Track a workout on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions",
      "kind": "article",
      "role": "article",
      "title": "Running workout sessions",
      "type": "topic",
      "url": "/documentation/healthkit/running-workout-sessions"
    },
    "doc://com.apple.healthkit/documentation/HealthKitUI/HKActivityRingView": {
      "abstract": [
        {
          "text": "A view that uses the Move, Exercise, and Stand activity rings to display data from a HealthKit activity summary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKActivityRingView"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKitUI/HKActivityRingView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKActivityRingView"
        }
      ],
      "role": "symbol",
      "title": "HKActivityRingView",
      "type": "topic",
      "url": "/documentation/healthkitui/hkactivityringview"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Samples",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/adding-samples-to-a-workout",
        "doc://com.apple.healthkit/documentation/HealthKit/accessing-condensed-workout-samples",
        "doc://com.apple.healthkit/documentation/HealthKit/dividing-a-healthkit-workout-into-activities",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutBuilder",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEvent"
      ],
      "title": "Samples"
    },
    {
      "anchor": "Sessions",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/running-workout-sessions",
        "doc://com.apple.healthkit/documentation/HealthKit/build-a-workout-app-for-apple-watch",
        "doc://com.apple.healthkit/documentation/HealthKit/building-a-multidevice-workout-app",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSession",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutConfiguration",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutSessionState",
        "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutBuilder",
        "doc://com.apple.healthkit/documentation/HealthKit/HKLiveWorkoutDataSource"
      ],
      "title": "Sessions"
    },
    {
      "anchor": "Activity-rings",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummary",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivitySummaryQuery",
        "doc://com.apple.healthkit/documentation/HealthKitUI/HKActivityRingView",
        "doc://com.apple.healthkit/documentation/HealthKit/HKActivityMoveModeObject"
      ],
      "title": "Activity rings"
    },
    {
      "anchor": "Route-data",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/creating-a-workout-route",
        "doc://com.apple.healthkit/documentation/HealthKit/reading-route-data",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteBuilder",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRoute",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQueryDescriptor",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesBuilder",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample"
      ],
      "title": "Route data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutDataSource/title",
          "value": "HKLiveWorkoutDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKLiveWorkoutDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKLiveWorkoutDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/title",
          "value": "HKWorkoutRouteQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesBuilder/title",
          "value": "HKSeriesBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSeriesBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSeriesBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/title",
          "value": "HKWorkoutActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/title",
          "value": "HKLiveWorkoutBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKLiveWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKLiveWorkoutBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKLiveWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/title",
          "value": "HKWorkoutSessionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/title",
          "value": "HKWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/title",
          "value": "HKWorkoutSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRoute/title",
          "value": "HKWorkoutRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRoute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRoute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/title",
          "value": "HKWorkoutBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivityMoveModeObject/title",
          "value": "HKActivityMoveModeObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivityMoveModeObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivityMoveModeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivityMoveModeObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivityMoveModeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutTypeIdentifier/title",
          "value": "HKWorkoutTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesSample/title",
          "value": "HKSeriesSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSeriesSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSeriesSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteTypeIdentifier/title",
          "value": "HKWorkoutRouteTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteBuilder/title",
          "value": "HKWorkoutRouteBuilder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteBuilder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteBuilder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteBuilder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title",
          "value": "HKWorkoutActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/title",
          "value": "HKActivitySummaryQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummaryQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummaryQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutConfiguration/title",
          "value": "HKWorkoutConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/title",
          "value": "HKWorkoutEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKitUI~1HKActivityRingView/title",
          "value": "HKActivityRingView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKitUI~1HKActivityRingView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivityRingView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKitUI~1HKActivityRingView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivityRingView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/title",
          "value": "HKActivitySummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKActivitySummary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKActivitySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/title",
          "value": "HKWorkoutSessionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutSessionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutSessionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/title",
          "value": "HKWorkoutType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
