{
  "abstract": [
    {
      "text": "Constants that can be used to add metadata to workouts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/samples",
        "doc://com.apple.healthkit/documentation/HealthKit/metadata-keys"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/workout-metadata-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Workout Metadata Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyActivityType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyActivityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyActivityType"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyActivityType",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyactivitytype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAlpineSlopeGrade": {
      "abstract": [
        {
          "text": "A key that indicates the percent slope of a ski run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAlpineSlopeGrade"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAlpineSlopeGrade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAlpineSlopeGrade"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyAlpineSlopeGrade",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyalpineslopegrade"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleFitnessPlusSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAppleFitnessPlusSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleFitnessPlusSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAppleFitnessPlusSession"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyAppleFitnessPlusSession",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyapplefitnessplussession"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageMETs": {
      "abstract": [
        {
          "text": "A key that indicates the average Metabolic Equivalent of Task (METs) during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAverageMETs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageMETs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAverageMETs"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyAverageMETs",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyaveragemets"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageSpeed": {
      "abstract": [
        {
          "text": "A key that indicates the average speed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAverageSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyAverageSpeed"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyAverageSpeed",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyaveragespeed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCoachedWorkout": {
      "abstract": [
        {
          "text": "A key that indicates whether the workout was performed with a coach or personal trainer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyCoachedWorkout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCoachedWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyCoachedWorkout"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyCoachedWorkout",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeycoachedworkout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCrossTrainerDistance": {
      "abstract": [
        {
          "text": "The workout distance displayed by a connected GymKit cross-trainer machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyCrossTrainerDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCrossTrainerDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyCrossTrainerDistance"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyCrossTrainerDistance",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeycrosstrainerdistance"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCyclingFunctionalThresholdPowerTestType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyCyclingFunctionalThresholdPowerTestType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCyclingFunctionalThresholdPowerTestType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyCyclingFunctionalThresholdPowerTestType"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyCyclingFunctionalThresholdPowerTestType",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeycyclingfunctionalthresholdpowertesttype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationAscended": {
      "abstract": [
        {
          "text": "A key that indicates the cumulative elevation ascended during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyElevationAscended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationAscended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyElevationAscended"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyElevationAscended",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyelevationascended"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationDescended": {
      "abstract": [
        {
          "text": "A key that indicates the cumulative elevation descended during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyElevationDescended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationDescended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyElevationDescended"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyElevationDescended",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyelevationdescended"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyFitnessMachineDuration": {
      "abstract": [
        {
          "text": "The workout duration displayed by a connected GymKit fitness machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyFitnessMachineDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyFitnessMachineDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyFitnessMachineDuration"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyFitnessMachineDuration",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyfitnessmachineduration"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyGroupFitness": {
      "abstract": [
        {
          "text": "A key that indicates whether the workout was performed as part of a group fitness class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyGroupFitness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyGroupFitness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyGroupFitness"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyGroupFitness",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeygroupfitness"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyIndoorBikeDistance": {
      "abstract": [
        {
          "text": "The workout distance displayed by a connected GymKit exercise bike.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyIndoorBikeDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyIndoorBikeDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyIndoorBikeDistance"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyIndoorBikeDistance",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyindoorbikedistance"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyIndoorWorkout": {
      "abstract": [
        {
          "text": "A key that indicates whether the workout was performed indoors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyIndoorWorkout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyIndoorWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyIndoorWorkout"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyIndoorWorkout",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyindoorworkout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyLapLength": {
      "abstract": [
        {
          "text": "A key that indicates the length of a lap during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyLapLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyLapLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyLapLength"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyLapLength",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeylaplength"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumSpeed": {
      "abstract": [
        {
          "text": "A key that indicates the maximum speed during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyMaximumSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyMaximumSpeed"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyMaximumSpeed",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeymaximumspeed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyPhysicalEffortEstimationType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyPhysicalEffortEstimationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyPhysicalEffortEstimationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyPhysicalEffortEstimationType"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyPhysicalEffortEstimationType",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyphysicaleffortestimationtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySWOLFScore": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeySWOLFScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySWOLFScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeySWOLFScore"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeySWOLFScore",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyswolfscore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySwimmingLocationType": {
      "abstract": [
        {
          "text": "A key that indicates the location for a swimming workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeySwimmingLocationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySwimmingLocationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeySwimmingLocationType"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeySwimmingLocationType",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyswimminglocationtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySwimmingStrokeStyle": {
      "abstract": [
        {
          "text": "A key that indicates the predominant stroke style for a lap of swimming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeySwimmingStrokeStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySwimmingStrokeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeySwimmingStrokeStyle"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeySwimmingStrokeStyle",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyswimmingstrokestyle"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyWaterSalinity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyWaterSalinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyWaterSalinity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyWaterSalinity"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyWaterSalinity",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeywatersalinity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyWorkoutBrandName": {
      "abstract": [
        {
          "text": "The brand name of a particular workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKMetadataKeyWorkoutBrandName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyWorkoutBrandName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKMetadataKeyWorkoutBrandName"
        }
      ],
      "role": "symbol",
      "title": "HKMetadataKeyWorkoutBrandName",
      "type": "topic",
      "url": "/documentation/healthkit/hkmetadatakeyworkoutbrandname"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout": {
      "abstract": [
        {
          "text": "A workout sample that stores information about a single physical activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkout"
        }
      ],
      "role": "symbol",
      "title": "HKWorkout",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkout"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/metadata-keys": {
      "abstract": [
        {
          "text": "Constants used to add metadata to objects stored in HealthKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/metadata-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Keys",
      "type": "topic",
      "url": "/documentation/healthkit/metadata-keys"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/samples": {
      "abstract": [
        {
          "text": "Create and save health and fitness samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/samples",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Samples",
      "type": "topic",
      "url": "/documentation/healthkit/samples"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings": {
      "abstract": [
        {
          "text": "Manage workouts, workout sessions, and activity summaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/workouts-and-activity-rings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workouts and activity rings",
      "type": "topic",
      "url": "/documentation/healthkit/workouts-and-activity-rings"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Workout-Type",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyActivityType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAppleFitnessPlusSession",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCoachedWorkout",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyGroupFitness",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyIndoorWorkout",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyWorkoutBrandName"
      ],
      "title": "Workout Type"
    },
    {
      "anchor": "Cycling",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCyclingFunctionalThresholdPowerTestType"
      ],
      "title": "Cycling"
    },
    {
      "anchor": "GymKit-Fitness-Equipment",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyFitnessMachineDuration",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyCrossTrainerDistance",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyIndoorBikeDistance"
      ],
      "title": "GymKit Fitness Equipment"
    },
    {
      "anchor": "Intensity",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageMETs",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyPhysicalEffortEstimationType"
      ],
      "title": "Intensity"
    },
    {
      "anchor": "Skiing-and-Snowboarding",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAlpineSlopeGrade",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationAscended",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyElevationDescended"
      ],
      "title": "Skiing and Snowboarding"
    },
    {
      "anchor": "Speed",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyAverageSpeed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyMaximumSpeed"
      ],
      "title": "Speed"
    },
    {
      "anchor": "Swimming",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySwimmingLocationType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySwimmingStrokeStyle",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyLapLength",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeySWOLFScore",
        "doc://com.apple.healthkit/documentation/HealthKit/HKMetadataKeyWaterSalinity"
      ],
      "title": "Swimming"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeySWOLFScore/title",
          "value": "HKMetadataKeySWOLFScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeySWOLFScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeySWOLFScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyIndoorBikeDistance/title",
          "value": "HKMetadataKeyIndoorBikeDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyIndoorBikeDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyIndoorBikeDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleFitnessPlusSession/title",
          "value": "HKMetadataKeyAppleFitnessPlusSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAppleFitnessPlusSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyAppleFitnessPlusSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyElevationDescended/title",
          "value": "HKMetadataKeyElevationDescended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyElevationDescended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyElevationDescended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/title",
          "value": "HKWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyCrossTrainerDistance/title",
          "value": "HKMetadataKeyCrossTrainerDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyCrossTrainerDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyCrossTrainerDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyWaterSalinity/title",
          "value": "HKMetadataKeyWaterSalinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyWaterSalinity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyWaterSalinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyCyclingFunctionalThresholdPowerTestType/title",
          "value": "HKMetadataKeyCyclingFunctionalThresholdPowerTestType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyCyclingFunctionalThresholdPowerTestType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyCyclingFunctionalThresholdPowerTestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAverageMETs/title",
          "value": "HKMetadataKeyAverageMETs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAverageMETs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyAverageMETs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAlpineSlopeGrade/title",
          "value": "HKMetadataKeyAlpineSlopeGrade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAlpineSlopeGrade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyAlpineSlopeGrade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyMaximumSpeed/title",
          "value": "HKMetadataKeyMaximumSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyMaximumSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyMaximumSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyFitnessMachineDuration/title",
          "value": "HKMetadataKeyFitnessMachineDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyFitnessMachineDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyFitnessMachineDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeySwimmingLocationType/title",
          "value": "HKMetadataKeySwimmingLocationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeySwimmingLocationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeySwimmingLocationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyIndoorWorkout/title",
          "value": "HKMetadataKeyIndoorWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyIndoorWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyIndoorWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyCoachedWorkout/title",
          "value": "HKMetadataKeyCoachedWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyCoachedWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyCoachedWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyActivityType/title",
          "value": "HKMetadataKeyActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyLapLength/title",
          "value": "HKMetadataKeyLapLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyLapLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyLapLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyGroupFitness/title",
          "value": "HKMetadataKeyGroupFitness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyGroupFitness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyGroupFitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyPhysicalEffortEstimationType/title",
          "value": "HKMetadataKeyPhysicalEffortEstimationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyPhysicalEffortEstimationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyPhysicalEffortEstimationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyElevationAscended/title",
          "value": "HKMetadataKeyElevationAscended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyElevationAscended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyElevationAscended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAverageSpeed/title",
          "value": "HKMetadataKeyAverageSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyAverageSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyAverageSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyWorkoutBrandName/title",
          "value": "HKMetadataKeyWorkoutBrandName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeyWorkoutBrandName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeyWorkoutBrandName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeySwimmingStrokeStyle/title",
          "value": "HKMetadataKeySwimmingStrokeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKMetadataKeySwimmingStrokeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKMetadataKeySwimmingStrokeStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
