{
  "abstract": [
    {
      "text": "Creates a pointer accessory at the specified position.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/arrowAccessoryWithPosition:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIPointerAccessory(cm)arrowAccessoryWithPosition:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "arrowAccessoryWithPosition:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "arrowAccessoryWithPosition:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "arrowAccessoryWithPosition:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "arrowAccessoryWithPosition:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessoryPosition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@UIPointerAccessoryPosition",
              "text": "UIPointerAccessoryPosition"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "position"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "One of the available ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " positions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "position"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory": {
      "abstract": [
        {
          "text": "Constants that describe accessories to display alongside the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerAccessory"
        }
      ],
      "role": "symbol",
      "title": "UIPointerAccessory",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct": {
      "abstract": [
        {
          "text": "A structure that specifies the position of the accessory relative to the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/Position-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "role": "symbol",
      "title": "UIPointerAccessory.Position",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/position-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/accessoryWithShape:position:": {
      "abstract": [
        {
          "text": "Creates a pointer accessory with the specified shape and position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "accessoryWithShape:position:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/accessoryWithShape:position:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryWithShape:position:"
        }
      ],
      "role": "symbol",
      "title": "accessoryWithShape:position:",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/accessorywithshape:position:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/arrowAccessoryWithPosition:": {
      "abstract": [
        {
          "text": "Creates a pointer accessory at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "arrowAccessoryWithPosition:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/arrowAccessoryWithPosition:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrowAccessoryWithPosition:"
        }
      ],
      "role": "symbol",
      "title": "arrowAccessoryWithPosition:",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory/arrowaccessorywithposition:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessoryPosition": {
      "abstract": [
        {
          "text": "A structure that specifies the position of the accessory relative to the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPointerAccessoryPosition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessoryPosition",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPointerAccessoryPosition",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessoryposition"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-pointer-accessory",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory/accessoryWithShape:position:"
      ],
      "title": "Creating a pointer accessory"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/title",
          "value": "UIPointerAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerAccessory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipointeraccessory/arrowaccessorywithposition:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
