{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragDelegate","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"textDragDelegate"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)UITextDraggable(py)textDragDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDragDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)UITextDragDelegate","kind":"typeIdentifier","text":"UITextDragDelegate"},{"kind":"text","text":")?"}],"title":"textDragDelegate","platforms":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false,"introducedAt":"11.0"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"11.0"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.1"},{"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false}],"modules":[{"name":"UIKit"}],"required":true,"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textDragDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","preciseIdentifier":"c:objc(pl)UITextDragDelegate","text":"UITextDragDelegate","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["/documentation/uikit/uitextdraggable/textdragdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitextdraggable/textdragdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"A text drag delegate object for customizing the drag source behavior of a text view.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextDraggable"]]},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate":{"url":"/documentation/uikit/uitextdragdelegate","abstract":[{"type":"text","text":"The interface for customizing the behavior of a drag activity for a text view."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","kind":"symbol","title":"UITextDragDelegate","navigatorTitle":[{"kind":"identifier","text":"UITextDragDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDragDelegate"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDraggable":{"role":"symbol","type":"topic","title":"UITextDraggable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDraggable"}],"url":"/documentation/uikit/uitextdraggable","abstract":[{"type":"text","text":"The interface that determines if a text view is a drag source."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDraggable"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable"},"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragDelegate":{"type":"topic","url":"/documentation/uikit/uitextdraggable/textdragdelegate","navigatorTitle":[{"text":"textDragDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragDelegate","abstract":[{"text":"A text drag delegate object for customizing the drag source behavior of a text view.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textDragDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UITextDragDelegate","preciseIdentifier":"c:objc(pl)UITextDragDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"required":true,"title":"textDragDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"11.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"11.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1"},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"textDragDelegate","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"textDragDelegate","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextDraggable"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)UITextDragDelegate","kind":"typeIdentifier","text":"id<UITextDragDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDragDelegate"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"UITextDragDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/title","op":"replace"},{"value":[{"kind":"identifier","text":"UITextDragDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UITextDragDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/navigatorTitle","op":"replace"},{"value":"UITextDraggable","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/title","op":"replace"},{"value":[{"kind":"identifier","text":"UITextDraggable"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/fragments","op":"replace"},{"value":[{"text":"UITextDraggable","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/navigatorTitle","op":"replace"},{"value":"textDragDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1textDragDelegate/title","op":"replace"},{"value":[{"kind":"identifier","text":"textDragDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1textDragDelegate/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}