{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkitui/documentation/EventKitUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_IOS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@EKUI_IS_IOS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EKUI_IS_IOS"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "EventKit UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKUI_IS_IOS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "EKUI_IS_IOS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EKUI_IS_IOS"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/eventkitui"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_EXTENSION_AVAILABLE_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EKUI_EXTENSION_AVAILABLE_IOS"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_EXTENSION_AVAILABLE_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "EKUI_EXTENSION_AVAILABLE_IOS",
      "type": "topic",
      "url": "/documentation/eventkitui/ekui_extension_available_ios"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_HAS_HEADER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EKUI_HAS_HEADER"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_HAS_HEADER",
      "kind": "symbol",
      "role": "symbol",
      "title": "EKUI_HAS_HEADER",
      "type": "topic",
      "url": "/documentation/eventkitui/ekui_has_header"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKUI_IS_IOS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_IOS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKUI_IS_IOS"
        }
      ],
      "role": "symbol",
      "title": "EKUI_IS_IOS",
      "type": "topic",
      "url": "/documentation/eventkitui/ekui_is_ios"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_SIMULATOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKUI_IS_SIMULATOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_SIMULATOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKUI_IS_SIMULATOR"
        }
      ],
      "role": "symbol",
      "title": "EKUI_IS_SIMULATOR",
      "type": "topic",
      "url": "/documentation/eventkitui/ekui_is_simulator"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EVENTKITUI_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "EVENTKITUI_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/eventkitui/eventkitui_class_available"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EVENTKITUI_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "EVENTKITUI_EXTERN",
      "type": "topic",
      "url": "/documentation/eventkitui/eventkitui_extern"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_SIMULATOR"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKUI_IS_IOS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKUI_IS_IOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkitui/documentation/EventKitUI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_EXTENSION_AVAILABLE_IOS",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_HAS_HEADER",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_SIMULATOR",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_CLASS_AVAILABLE",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_EXTERN"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EKUI_IS_IOS"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKUI_IS_IOS/title",
          "value": "EKUI_IS_IOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKUI_IS_IOS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKUI_IS_IOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKUI_IS_SIMULATOR/title",
          "value": "EKUI_IS_SIMULATOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKUI_IS_SIMULATOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKUI_IS_SIMULATOR"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkitui/ekui_is_ios"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkitui/ekui_is_ios"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
