{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkitui/documentation/EventKitUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_EXTERN"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@EVENTKITUI_EXTERN",
    "fragments": [
      {
        "kind": "identifier",
        "text": "EVENTKITUI_EXTERN"
      }
    ],
    "modules": [
      {
        "name": "EventKit UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EVENTKITUI_EXTERN"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "EVENTKITUI_EXTERN"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EVENTKITUI_EXTERN"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/eventkitui"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_EXTENSION_AVAILABLE_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EKUI_EXTENSION_AVAILABLE_IOS"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_EXTENSION_AVAILABLE_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "EKUI_EXTENSION_AVAILABLE_IOS",
      "type": "topic",
      "url": "/documentation/eventkitui/ekui_extension_available_ios"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_HAS_HEADER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EKUI_HAS_HEADER"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_HAS_HEADER",
      "kind": "symbol",
      "role": "symbol",
      "title": "EKUI_HAS_HEADER",
      "type": "topic",
      "url": "/documentation/eventkitui/ekui_has_header"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKUI_IS_IOS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_IOS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKUI_IS_IOS"
        }
      ],
      "role": "symbol",
      "title": "EKUI_IS_IOS",
      "type": "topic",
      "url": "/documentation/eventkitui/ekui_is_ios"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_SIMULATOR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKUI_IS_SIMULATOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_SIMULATOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKUI_IS_SIMULATOR"
        }
      ],
      "role": "symbol",
      "title": "EKUI_IS_SIMULATOR",
      "type": "topic",
      "url": "/documentation/eventkitui/ekui_is_simulator"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EVENTKITUI_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "EVENTKITUI_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/eventkitui/eventkitui_class_available"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EVENTKITUI_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "EVENTKITUI_EXTERN",
      "type": "topic",
      "url": "/documentation/eventkitui/eventkitui_extern"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_EXTENSION_AVAILABLE_IOS",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_HAS_HEADER",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_IOS",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKUI_IS_SIMULATOR",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EVENTKITUI_CLASS_AVAILABLE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKUI_IS_SIMULATOR/title",
          "value": "EKUI_IS_SIMULATOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKUI_IS_SIMULATOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKUI_IS_SIMULATOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKUI_IS_IOS/title",
          "value": "EKUI_IS_IOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKUI_IS_IOS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKUI_IS_IOS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkitui/eventkitui_extern"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
