{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2"]]},"sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"Model I/O"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"11.0"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"11.0"},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.13"},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false,"introducedAt":"11.0"},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0"}],"externalID":"c:objc(cs)MDLAnimatedVector2(im)float2AtTime:","navigatorTitle":[{"kind":"identifier","text":"float2AtTime:"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"float2Value"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float2","text":"vector_float2"}],"title":"float2Value(atTime:)"},"identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2/float2Value(atTime:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"float2Value"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atTime"},{"kind":"text","text":" "},{"kind":"internalParam","text":"time"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval"},{"text":") -> ","kind":"text"},{"text":"vector_float2","preciseIdentifier":"c:@T@vector_float2","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float2"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlanimatedvector2/float2value(attime:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlanimatedvector2/float2value(attime:)"]}],"references":{"doc://com.externally.resolved.symbol/c:@T@vector_float2":{"abstract":[{"text":"","type":"text"}],"url":"/documentation/simd/vector_float2","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vector_float2"},{"kind":"text","text":" = "},{"preciseIdentifier":"c:@T@simd_float2","kind":"typeIdentifier","text":"simd_float2"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float2","title":"vector_float2"},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2/float2Value(atTime:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"float2Value","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float2","text":"vector_float2","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"float2AtTime:","kind":"identifier"}],"url":"/documentation/modelio/mdlanimatedvector2/float2value(attime:)","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2/float2Value(atTime:)","kind":"symbol","role":"symbol","title":"float2Value(atTime:)","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval":{"role":"symbol","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"TimeInterval"}],"type":"topic","title":"TimeInterval","abstract":[{"type":"text","text":"A number of seconds."}],"url":"/documentation/foundation/timeinterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","kind":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2":{"type":"topic","role":"symbol","url":"/documentation/modelio/mdlanimatedvector2","abstract":[],"navigatorTitle":[{"text":"MDLAnimatedVector2","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAnimatedVector2","kind":"identifier"}],"title":"MDLAnimatedVector2"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"introducedAt":"11.0","beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"introducedAt":"11.0","beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"10.13","beta":false,"deprecated":false,"name":"macOS"},{"unavailable":false,"introducedAt":"11.0","beta":false,"deprecated":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"float2AtTime:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"float2AtTime:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"vector_float2","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float2","identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float2"},{"text":") ","kind":"text"},{"text":"float2AtTime:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"time"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@vector_float2/fragments","op":"replace","value":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"simd_float2","kind":"typeIdentifier","preciseIdentifier":"c:@T@simd_float2"},{"text":" ","kind":"text"},{"text":"vector_float2","kind":"identifier"},{"text":";","kind":"text"}]},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedVector2~1float2Value(atTime:)/title","op":"replace","value":"float2AtTime:"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedVector2~1float2Value(atTime:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"float2AtTime:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title","value":"NSTimeInterval"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedVector2/title","value":"MDLAnimatedVector2"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedVector2/fragments","value":[{"text":"MDLAnimatedVector2","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedVector2/navigatorTitle","value":[{"kind":"identifier","text":"MDLAnimatedVector2"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}