{"identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2/getFloat2Array:maxCount:","interfaceLanguage":"occ"},"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getFloat2Array:maxCount:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFloat2Array:maxCount:"}],"title":"getFloat2Array:maxCount:","externalID":"c:objc(cs)MDLAnimatedVector2(im)getFloat2Array:maxCount:","platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"11.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"11.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.1"},{"name":"macOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.13"},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"11.0"},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"1.0"}],"modules":[{"name":"Model I/O"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlanimatedvector2/getfloat2array:maxcount:"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"getFloat2Array:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float2","text":"vector_float2","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float2"},{"text":" *) ","kind":"text"},{"text":"valuesArray","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxCount:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"text":"maxCount","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","url":"/documentation/objectivec/nsuinteger","abstract":[{"type":"text","text":"Describes an unsigned integer."}],"type":"topic","role":"symbol","kind":"symbol","title":"NSUInteger"},"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2/getFloat2Array:maxCount:":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2/getFloat2Array:maxCount:","url":"/documentation/modelio/mdlanimatedvector2/getfloat2array:maxcount:","abstract":[],"title":"getFloat2Array:maxCount:","navigatorTitle":[{"kind":"identifier","text":"getFloat2Array:maxCount:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFloat2Array:maxCount:"}]},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2":{"type":"topic","role":"symbol","url":"/documentation/modelio/mdlanimatedvector2","abstract":[],"navigatorTitle":[{"text":"MDLAnimatedVector2","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedVector2","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAnimatedVector2","kind":"identifier"}],"title":"MDLAnimatedVector2"},"doc://com.externally.resolved.symbol/c:@T@vector_float2":{"abstract":[{"text":"","type":"text"}],"url":"/documentation/simd/vector_float2","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vector_float2"},{"kind":"text","text":" = "},{"preciseIdentifier":"c:@T@simd_float2","kind":"typeIdentifier","text":"simd_float2"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float2","title":"vector_float2"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MDLAnimatedVector2","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedVector2/title"},{"op":"replace","value":[{"text":"MDLAnimatedVector2","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedVector2/fragments"},{"op":"replace","value":[{"text":"MDLAnimatedVector2","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedVector2/navigatorTitle"},{"op":"replace","value":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simd_float2","preciseIdentifier":"c:@T@simd_float2","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"vector_float2","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@vector_float2/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}