{
  "abstract": [
    {
      "text": "A reading taken by the system in the background.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/backgroundSystem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:@SRPhotoplethysmogramSampleUsageBackgroundSystem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "backgroundSystem"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
        "text": "SRPhotoplethysmogramSample"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
        "text": "Usage"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRPhotoplethysmogramSampleUsageBackgroundSystem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "backgroundSystem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "backgroundSystem"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
              "text": "SRPhotoplethysmogramSample"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
              "text": "Usage"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system takes this reading while performing various heart features on watchOS — such as background blood oxygen, atrial fibrillation (AFib), and low-cardio notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample": {
      "abstract": [
        {
          "text": "The sample photoplethysmogram (PPG) sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSample"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct": {
      "abstract": [
        {
          "text": "The possible ways that a person or the system may take a photoplethysmogram (PPG) reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Usage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Usage"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramSample.Usage",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.struct"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/backgroundSystem": {
      "abstract": [
        {
          "text": "A reading taken by the system in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundSystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
          "text": "SRPhotoplethysmogramSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
          "text": "Usage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/backgroundSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSampleUsageBackgroundSystem"
        }
      ],
      "role": "symbol",
      "title": "backgroundSystem",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.struct/backgroundsystem"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/deepBreathing": {
      "abstract": [
        {
          "text": "A deep breathing sensor reading that a person takes while using an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deepBreathing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
          "text": "SRPhotoplethysmogramSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
          "text": "Usage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/deepBreathing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSampleUsageDeepBreathing"
        }
      ],
      "role": "symbol",
      "title": "deepBreathing",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.struct/deepbreathing"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/foregroundBloodOxygen": {
      "abstract": [
        {
          "text": "A blood oxygen reading that a person takes while using an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foregroundBloodOxygen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
          "text": "SRPhotoplethysmogramSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
          "text": "Usage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/foregroundBloodOxygen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSampleUsageForegroundBloodOxygen"
        }
      ],
      "role": "symbol",
      "title": "foregroundBloodOxygen",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.struct/foregroundbloodoxygen"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/foregroundHeartRate": {
      "abstract": [
        {
          "text": "A heart rate reading that a person takes while using an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foregroundHeartRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramSample",
          "text": "SRPhotoplethysmogramSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
          "text": "Usage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/foregroundHeartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSampleUsageForegroundHeartRate"
        }
      ],
      "role": "symbol",
      "title": "foregroundHeartRate",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.struct/foregroundheartrate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-reading-method",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/foregroundHeartRate",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/deepBreathing",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/foregroundBloodOxygen"
      ],
      "title": "Getting the reading method"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRPhotoplethysmogramSampleUsageBackgroundSystem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsageBackgroundSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-reading-method",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/foregroundHeartRate",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/deepBreathing",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct/foregroundBloodOxygen"
              ],
              "title": "Getting the reading method"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramSample/Usage-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SRPhotoplethysmogramSampleUsage",
                    "text": "SRPhotoplethysmogramSampleUsage"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRPhotoplethysmogramSampleUsageBackgroundSystem"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct~1backgroundSystem/title",
          "value": "SRPhotoplethysmogramSampleUsageBackgroundSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct~1backgroundSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsageBackgroundSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct/title",
          "value": "SRPhotoplethysmogramSampleUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct~1deepBreathing/title",
          "value": "SRPhotoplethysmogramSampleUsageDeepBreathing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct~1deepBreathing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsageDeepBreathing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct~1foregroundHeartRate/title",
          "value": "SRPhotoplethysmogramSampleUsageForegroundHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct~1foregroundHeartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsageForegroundHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/title",
          "value": "SRPhotoplethysmogramSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct~1foregroundBloodOxygen/title",
          "value": "SRPhotoplethysmogramSampleUsageForegroundBloodOxygen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramSample~1Usage-swift.struct~1foregroundBloodOxygen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSampleUsageForegroundBloodOxygen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.struct/backgroundsystem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srphotoplethysmogramsample/usage-swift.struct/backgroundsystem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
