{
  "abstract": [
    {
      "text": "Enumerates through each dragging item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession/enumerateDraggingItems(options:for:classes:searchOptions:using:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDraggingSession(im)enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "enumerateDraggingItems"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSDraggingItemEnumerationOptions",
        "text": "NSDraggingItemEnumerationOptions"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSView",
        "text": "NSView"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "classes"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s8AnyClassa",
        "text": "AnyClass"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "searchOptions"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPasteboard",
        "text": "NSPasteboard"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
        "text": "ReadingOptionKey"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "using"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSDraggingItem",
        "text": "NSDraggingItem"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
        "text": "ObjCBool"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "enumerateDraggingItems(options:for:classes:searchOptions:using:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "enumerateDraggingItems"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "enumOpts"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSDraggingItemEnumerationOptions",
              "text": "NSDraggingItemEnumerationOptions"
            },
            {
              "kind": "text",
              "text": " = [], "
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "view"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSView",
              "text": "NSView"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "classes"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "classArray"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s8AnyClassa",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s8AnyClassa",
              "text": "AnyClass"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "searchOptions"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPasteboard",
              "text": "NSPasteboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
              "text": "ReadingOptionKey"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "] = [:], "
            },
            {
              "kind": "externalParam",
              "text": "using"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ": ("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDraggingItem",
              "text": "NSDraggingItem"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8ObjCBoolV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
              "text": "ObjCBool"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The enumeration options. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for the supported values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "enumOpts"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The view to use as the base coordinate system for the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instances.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "view"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of class objects.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Arrange classes in the array in the preferred order of representation. Classes in the array must conform to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " protocol.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "classArray"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dictionary that specifies options to refine the search for pasteboard items, such as restricting the search to file URLs with particular content types. For valid dictionary keys, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "searchOptions"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block to execute for the enumeration. The block takes three arguments:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "A reference to the dragging item. The ",
                            "type": "text"
                          },
                          {
                            "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/draggingFrame",
                            "isActive": true,
                            "type": "reference"
                          },
                          {
                            "text": " of the dragging item is in the coordinate space of the view that ",
                            "type": "text"
                          },
                          {
                            "code": "view",
                            "type": "codeVoice"
                          },
                          {
                            "text": " specifies. A ",
                            "type": "text"
                          },
                          {
                            "code": "view",
                            "type": "codeVoice"
                          },
                          {
                            "text": " value of ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " means the screen coordinate space.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "draggingItem",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The index of the element in the classes.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "idx",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "A reference to a Boolean value that the block can use to stop the enumeration by setting ",
                            "type": "text"
                          },
                          {
                            "code": "*stop",
                            "type": "codeVoice"
                          },
                          {
                            "text": " to ",
                            "type": "text"
                          },
                          {
                            "identifier": "doc://com.apple.documentation/documentation/swift/true",
                            "isActive": true,
                            "type": "reference"
                          },
                          {
                            "text": ".",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "stop",
                        "type": "codeVoice"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "block"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Enumerate through dragging items to modify their properties, such as the drag image or size, while the user is dragging. When the dragging items are over the destination, changes that the destination’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods make may override changes you make during the drag session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To get dragging items in a data type that you expect while enumerating, specify classes in the ",
              "type": "text"
            },
            {
              "code": "classesArray",
              "type": "codeVoice"
            },
            {
              "text": " parameter that implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol, such as ",
              "type": "text"
            },
            {
              "code": "NSImage",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "NSString",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "NSURL",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "NSColor",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "NSAttributedString",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "NSPasteboardItem",
              "type": "codeVoice"
            },
            {
              "text": ". For each item in the dragging pasteboard, the system performs the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The systems calls ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " on the item to determine the types of data the item conforms to.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "It attempts to create an instance of a matching class from the dragging pasteboard data, using the class order you specify in the ",
                      "type": "text"
                    },
                    {
                      "code": "classesArray",
                      "type": "codeVoice"
                    },
                    {
                      "text": " parameter.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If it can create an instance of a matching class, the system creates an instance of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with the class instance and the dragging properties of that item.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system passes the ",
                      "type": "text"
                    },
                    {
                      "code": "NSDraggingItem",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to the block you provide as the ",
                      "type": "text"
                    },
                    {
                      "code": "draggingItem",
                      "type": "codeVoice"
                    },
                    {
                      "text": " parameter.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If the system can’t create an instance of one of the classes you specify in ",
              "type": "text"
            },
            {
              "code": "classesArray",
              "type": "codeVoice"
            },
            {
              "text": " with an item, the system skips the item without calling ",
              "type": "text"
            },
            {
              "code": "block",
              "type": "codeVoice"
            },
            {
              "text": " and proceeds to the next item.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Ensure you receive one object per item on the pasteboard by including the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardItem",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class in the array of classes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "When the system provides a ",
              "type": "text"
            },
            {
              "code": "draggingItem",
              "type": "codeVoice"
            },
            {
              "text": " to your block, modify the item’s properties to change how the user sees the item while dragging. Provide a ",
              "type": "text"
            },
            {
              "code": "view",
              "type": "codeVoice"
            },
            {
              "text": " to this method if you want to express each dragging item’s ",
              "type": "text"
            },
            {
              "code": "draggingFrame",
              "type": "codeVoice"
            },
            {
              "text": " relative to that ",
              "type": "text"
            },
            {
              "code": "view",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "code": "draggingItem",
                  "type": "codeVoice"
                },
                {
                  "text": " object is only valid for the current iteration of the enumeration block. Never store the ",
                  "type": "text"
                },
                {
                  "code": "draggingItem",
                  "type": "codeVoice"
                },
                {
                  "text": " or change it outside of the block iteration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Don’t reference ",
                  "type": "text"
                },
                {
                  "code": "draggingItem",
                  "type": "codeVoice"
                },
                {
                  "text": " inside an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/imageComponentsProvider",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " block for the following reasons:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "・When the system calls the ",
                  "type": "text"
                },
                {
                  "code": "imageComponentsProvider",
                  "type": "codeVoice"
                },
                {
                  "text": " block, the enumeration block is out of scope and the ",
                  "type": "text"
                },
                {
                  "code": "draggingItem",
                  "type": "codeVoice"
                },
                {
                  "text": " is no longer valid.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "・Referencing ",
                  "type": "text"
                },
                {
                  "code": "draggingItem",
                  "type": "codeVoice"
                },
                {
                  "text": " in an ",
                  "type": "text"
                },
                {
                  "code": "imageComponentsProvider",
                  "type": "codeVoice"
                },
                {
                  "text": " block creates a retain cycle because ",
                  "type": "text"
                },
                {
                  "code": "draggingItem",
                  "type": "codeVoice"
                },
                {
                  "text": " retains ",
                  "type": "text"
                },
                {
                  "code": "imageComponentsProvider",
                  "type": "codeVoice"
                },
                {
                  "text": ", and ",
                  "type": "text"
                },
                {
                  "code": "imageComponentsProvider",
                  "type": "codeVoice"
                },
                {
                  "text": " retains ",
                  "type": "text"
                },
                {
                  "code": "draggingItem",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Assign ",
                  "type": "text"
                },
                {
                  "code": "draggingItem.item",
                  "type": "codeVoice"
                },
                {
                  "text": " to an object pointer or variable outside of the ",
                  "type": "text"
                },
                {
                  "code": "imageComponentsProvider",
                  "type": "codeVoice"
                },
                {
                  "text": " block definition instead, and use that object pointer or variable inside the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/imageComponentsProvider",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " block definition.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To refine the list of dragging items that this method provides, specify ",
              "type": "text"
            },
            {
              "code": "enumOpts",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "searchOptions",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo": {
      "abstract": [
        {
          "text": "A set of methods that supply information about a dragging session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingInfo"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem": {
      "abstract": [
        {
          "text": "A single dragged item within a dragging session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingItem"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingItem",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/draggingFrame": {
      "abstract": [
        {
          "text": "The frame of the dragging item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/draggingFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingFrame"
        }
      ],
      "role": "symbol",
      "title": "draggingFrame",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingitem/draggingframe"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/imageComponentsProvider": {
      "abstract": [
        {
          "text": "An array of blocks that provide the dragging image components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageComponentsProvider"
        },
        {
          "kind": "text",
          "text": ": (() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingImageComponent",
          "text": "NSDraggingImageComponent"
        },
        {
          "kind": "text",
          "text": "])?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/imageComponentsProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageComponentsProvider"
        }
      ],
      "role": "symbol",
      "title": "imageComponentsProvider",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingitem/imagecomponentsprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions": {
      "abstract": [
        {
          "text": "A group of constants that specify options to use when enumerating dragging items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingItemEnumerationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingItemEnumerationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingItemEnumerationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingitemenumerationoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession": {
      "abstract": [
        {
          "text": "The encapsulation of a drag-and-drop action that supports modification of the drag while in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingSession"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingSession"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingSession",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsession"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession/enumerateDraggingItems(options:for:classes:searchOptions:using:)": {
      "abstract": [
        {
          "text": "Enumerates through each dragging item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateDraggingItems"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDraggingItemEnumerationOptions",
          "text": "NSDraggingItemEnumerationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "classes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "searchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
          "text": "ReadingOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingItem",
          "text": "NSDraggingItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession/enumerateDraggingItems(options:for:classes:searchOptions:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateDraggingItems(options:for:classes:searchOptions:using:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsession/enumeratedraggingitems(options:for:classes:searchoptions:using:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard": {
      "abstract": [
        {
          "text": "An object that transfers data to and from the pasteboard server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey": {
      "abstract": [
        {
          "text": "Options for reading pasteboard data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadingOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadingOptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard.ReadingOptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/readingoptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)": {
      "abstract": [
        {
          "text": "Reads from the receiver objects that best match the specified array of classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readObjects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forClasses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
          "text": "ReadingOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readObjectsForClasses:options:"
        }
      ],
      "role": "symbol",
      "title": "readObjects(forClasses:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/readobjects(forclasses:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardItem": {
      "abstract": [
        {
          "text": "An item on a pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboardItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardItem"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboardItem",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboarditem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading": {
      "abstract": [
        {
          "text": "A set of methods that defines the interface for initializing an object from a pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboardReading"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardReading"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboardReading",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboardreading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)": {
      "abstract": [
        {
          "text": "Returns an array of uniform type identifier strings of data types the receiver can read from the pasteboard and initialize from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readableTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading/readableTypes(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readableTypesForPasteboard:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "readableTypes(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboardreading/readabletypes(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:10ObjectiveC8ObjCBoolV": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "ObjCBool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8ObjCBoolV",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObjCBool",
      "type": "topic",
      "url": "/documentation/objectivec/objcbool"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s8AnyClassa": {
      "abstract": [
        {
          "text": "The protocol to which all class types implicitly conform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": " = any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9AnyObjecta",
          "text": "AnyObject"
        },
        {
          "kind": "text",
          "text": ".Type"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8AnyClassa",
      "kind": "symbol",
      "role": "symbol",
      "title": "AnyClass",
      "type": "topic",
      "url": "/documentation/Swift/AnyClass"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "enumerateDraggingItemsWithOptions:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSDraggingItemEnumerationOptions",
                    "text": "NSDraggingItemEnumerationOptions"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "enumOpts"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forView:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSView",
                    "text": "NSView"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "view"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "classes:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<Class>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "classArray"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "searchOptions:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,id>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "searchOptions"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "usingBlock:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDraggingItem",
                    "text": "NSDraggingItem"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "draggingItem"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "idx"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "stop"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "block"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The enumeration options. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for the supported values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "enumOpts"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The view to use as the base coordinate system for the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instances.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "view"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of class objects.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Arrange classes in the array in the preferred order of representation. Classes in the array must conform to the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboardReading",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " protocol.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "classArray"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary that specifies options to refine the search for pasteboard items, such as restricting the search to file URLs with particular content types. For valid dictionary keys, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "searchOptions"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block to execute for the enumeration. The block takes three arguments:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "A reference to the dragging item. The ",
                                  "type": "text"
                                },
                                {
                                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/draggingFrame",
                                  "isActive": true,
                                  "type": "reference"
                                },
                                {
                                  "text": " of the dragging item is in the coordinate space of the view that ",
                                  "type": "text"
                                },
                                {
                                  "code": "view",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " specifies. A ",
                                  "type": "text"
                                },
                                {
                                  "code": "view",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " value of ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " means the screen coordinate space.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "draggingItem",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The index of the element in the classes.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "idx",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "A reference to a Boolean value that the block can use to stop the enumeration by setting ",
                                  "type": "text"
                                },
                                {
                                  "code": "*stop",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " to ",
                                  "type": "text"
                                },
                                {
                                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                                  "isActive": true,
                                  "type": "reference"
                                },
                                {
                                  "text": ".",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "stop",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "block"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardItem/title",
          "value": "NSPasteboardItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/title",
          "value": "NSDraggingItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading/title",
          "value": "NSPasteboardReading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/title",
          "value": "NSDraggingInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession~1enumerateDraggingItems(options:for:classes:searchOptions:using:)/title",
          "value": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession~1enumerateDraggingItems(options:for:classes:searchOptions:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1draggingFrame/title",
          "value": "draggingFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1draggingFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggingFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title",
          "value": "NSPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/title",
          "value": "NSDraggingSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey/title",
          "value": "NSPasteboardReadingOptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReadingOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReadingOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading~1readableTypes(for:)/title",
          "value": "readableTypesForPasteboard:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardReading~1readableTypes(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "readableTypesForPasteboard:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1readObjects(forClasses:options:)/title",
          "value": "readObjectsForClasses:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1readObjects(forClasses:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readObjectsForClasses:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItemEnumerationOptions/title",
          "value": "NSDraggingItemEnumerationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItemEnumerationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingItemEnumerationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItemEnumerationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingItemEnumerationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1imageComponentsProvider/title",
          "value": "imageComponentsProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1imageComponentsProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageComponentsProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdraggingsession/enumeratedraggingitems(options:for:classes:searchoptions:using:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdraggingsession/enumeratedraggingitems(options:for:classes:searchoptions:using:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
