{
  "abstract": [
    {
      "text": "Yes or no.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit",
        "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/yesNo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLSBinaryValueType@CLSBinaryValueTypeYesNo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "yesNo"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSBinaryValueTypeYesNo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLSBinaryValueType.yesNo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "yesNo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType": {
      "abstract": [
        {
          "text": "The kinds of outcomes that a binary activity item can represent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSBinaryValueType"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSBinaryValueType"
        }
      ],
      "role": "symbol",
      "title": "CLSBinaryValueType",
      "type": "topic",
      "url": "/documentation/classkit/clsbinaryvaluetype"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/correctIncorrect": {
      "abstract": [
        {
          "text": "Correct or incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "correctIncorrect"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/correctIncorrect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSBinaryValueTypeCorrectIncorrect"
        }
      ],
      "role": "symbol",
      "title": "CLSBinaryValueType.correctIncorrect",
      "type": "topic",
      "url": "/documentation/classkit/clsbinaryvaluetype/correctincorrect"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/passFail": {
      "abstract": [
        {
          "text": "Pass or fail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passFail"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/passFail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSBinaryValueTypePassFail"
        }
      ],
      "role": "symbol",
      "title": "CLSBinaryValueType.passFail",
      "type": "topic",
      "url": "/documentation/classkit/clsbinaryvaluetype/passfail"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/trueFalse": {
      "abstract": [
        {
          "text": "True or false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trueFalse"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/trueFalse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSBinaryValueTypeTrueFalse"
        }
      ],
      "role": "symbol",
      "title": "CLSBinaryValueType.trueFalse",
      "type": "topic",
      "url": "/documentation/classkit/clsbinaryvaluetype/truefalse"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/yesNo": {
      "abstract": [
        {
          "text": "Yes or no.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yesNo"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/yesNo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSBinaryValueTypeYesNo"
        }
      ],
      "role": "symbol",
      "title": "CLSBinaryValueType.yesNo",
      "type": "topic",
      "url": "/documentation/classkit/clsbinaryvaluetype/yesno"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Value-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/passFail",
        "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/trueFalse",
        "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/correctIncorrect"
      ],
      "title": "Value Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLSBinaryValueTypeYesNo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryValueTypeYesNo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit",
                "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Value-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/passFail",
                "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/trueFalse",
                "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryValueType/correctIncorrect"
              ],
              "title": "Value Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLSBinaryValueTypeYesNo"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType~1correctIncorrect/title",
          "value": "CLSBinaryValueTypeCorrectIncorrect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType~1correctIncorrect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryValueTypeCorrectIncorrect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType~1passFail/title",
          "value": "CLSBinaryValueTypePassFail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType~1passFail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryValueTypePassFail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType/title",
          "value": "CLSBinaryValueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryValueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryValueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType~1yesNo/title",
          "value": "CLSBinaryValueTypeYesNo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType~1yesNo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryValueTypeYesNo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType~1trueFalse/title",
          "value": "CLSBinaryValueTypeTrueFalse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryValueType~1trueFalse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryValueTypeTrueFalse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clsbinaryvaluetype/yesno"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clsbinaryvaluetype/yesno"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
