{
  "abstract": [
    {
      "text": "Creates a graph with the specified list of obstacles, using the specified node class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/graphWithObstacles:bufferRadius:nodeClass:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKObstacleGraph(cm)graphWithObstacles:bufferRadius:nodeClass:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "graphWithObstacles:bufferRadius:nodeClass:"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "graphWithObstacles:bufferRadius:nodeClass:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "graphWithObstacles:bufferRadius:nodeClass:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "graphWithObstacles:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<GKPolygonObstacle *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "obstacles"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bufferRadius:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "bufferRadius"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nodeClass:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@Class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@Class",
              "text": "Class"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "nodeClass"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of obstacle objects, each of which describes a polygon-shaped impassable area.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "obstacles"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The distance from obstacle edges that should also be considered impassable.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bufferRadius"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraphNode2D",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " subclass to use for nodes in the graph.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "nodeClass"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new obstacle graph.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method generates a graph that can be traversed in all directions, except into the areas occupied by obstacles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "bufferRadius",
              "type": "codeVoice"
            },
            {
              "text": " parameter to take the size of potential travelers into account when determining navigability. For example, if a game character that will use pathfinding has a radius of 20 units (in the same coordinate space you use to define obstacles), specify a buffer radius of 20. As a result, the graph will consider any points within 20 units of an obstacle non-navigable—that is, pathfinding in the graph will not result in any positions that lie inside this buffer region, so you can safely set the character’s center point to the location of a node returned from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraph/findPath(from:to:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method without the character overlapping any obstacles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "nodeClass",
              "type": "codeVoice"
            },
            {
              "text": " parameter to create a graph using a custom subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraphNode2D",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For example, your custom node class might override the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraphNode/cost(to:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method so that some nodes are more costly than others to travel through. Pathfinding in such a graph would favor indirect routes when a direct route has a higher cost.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraph/findPath(from:to:)": {
      "abstract": [
        {
          "text": "Computes and returns a sequence of nodes that represents the shortest traversal of the graph between the specified nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGraphNode",
          "text": "GKGraphNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGraphNode",
          "text": "GKGraphNode"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGraphNode",
          "text": "GKGraphNode"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraph/findPath(from:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findPathFromNode:toNode:"
        }
      ],
      "role": "symbol",
      "title": "findPath(from:to:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgraph/findpath(from:to:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraphNode/cost(to:)": {
      "abstract": [
        {
          "text": "Returns the cost to travel from this node to the specified, directly connected, node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cost"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGraphNode",
          "text": "GKGraphNode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraphNode/cost(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "costToNode:"
        }
      ],
      "role": "symbol",
      "title": "cost(to:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgraphnode/cost(to:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraphNode2D": {
      "abstract": [
        {
          "text": "A node in a navigation graph, associated with a point in continuous 2D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGraphNode2D"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGraphNode2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGraphNode2D"
        }
      ],
      "role": "symbol",
      "title": "GKGraphNode2D",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgraphnode2d"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph": {
      "abstract": [
        {
          "text": "A navigation graph for 2D game worlds that creates a minimal network for precise pathfinding around obstacles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKObstacleGraph"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKObstacleGraph"
        }
      ],
      "role": "symbol",
      "title": "GKObstacleGraph",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkobstaclegraph"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/graphWithObstacles:bufferRadius:": {
      "abstract": [
        {
          "text": "Creates a graph with the specified list of obstacles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "graphWithObstacles:bufferRadius:"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/graphWithObstacles:bufferRadius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "graphWithObstacles:bufferRadius:"
        }
      ],
      "role": "symbol",
      "title": "graphWithObstacles:bufferRadius:",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkobstaclegraph/graphwithobstacles:bufferradius:"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/graphWithObstacles:bufferRadius:nodeClass:": {
      "abstract": [
        {
          "text": "Creates a graph with the specified list of obstacles, using the specified node class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "graphWithObstacles:bufferRadius:nodeClass:"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/graphWithObstacles:bufferRadius:nodeClass:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "graphWithObstacles:bufferRadius:nodeClass:"
        }
      ],
      "role": "symbol",
      "title": "graphWithObstacles:bufferRadius:nodeClass:",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkobstaclegraph/graphwithobstacles:bufferradius:nodeclass:"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/init(obstacles:bufferRadius:)": {
      "abstract": [
        {
          "text": "Initializes a graph with the specified list of obstacles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "obstacles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPolygonObstacle",
          "text": "GKPolygonObstacle"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "bufferRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/init(obstacles:bufferRadius:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithObstacles:bufferRadius:"
        }
      ],
      "role": "symbol",
      "title": "init(obstacles:bufferRadius:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkobstaclegraph/init(obstacles:bufferradius:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/init(obstacles:bufferRadius:nodeClass:)": {
      "abstract": [
        {
          "text": "Initializes a graph with the specified list of obstacles, using the specified node class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "obstacles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPolygonObstacle",
          "text": "GKPolygonObstacle"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "bufferRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nodeClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/init(obstacles:bufferRadius:nodeClass:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithObstacles:bufferRadius:nodeClass:"
        }
      ],
      "role": "symbol",
      "title": "init(obstacles:bufferRadius:nodeClass:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkobstaclegraph/init(obstacles:bufferradius:nodeclass:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@Class": {
      "abstract": [
        {
          "text": "An opaque type that represents an Objective-C class.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@Class",
      "kind": "symbol",
      "role": "symbol",
      "title": "Class",
      "type": "topic",
      "url": "/documentation/objectivec/class"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Graph",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/init(obstacles:bufferRadius:nodeClass:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/init(obstacles:bufferRadius:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKObstacleGraph/graphWithObstacles:bufferRadius:"
      ],
      "title": "Creating a Graph"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGraphNode2D/title",
          "value": "GKGraphNode2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGraphNode2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGraphNode2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGraphNode2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGraphNode2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGraphNode~1cost(to:)/title",
          "value": "costToNode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGraphNode~1cost(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "costToNode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKObstacleGraph~1init(obstacles:bufferRadius:nodeClass:)/title",
          "value": "initWithObstacles:bufferRadius:nodeClass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKObstacleGraph~1init(obstacles:bufferRadius:nodeClass:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithObstacles:bufferRadius:nodeClass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKObstacleGraph/title",
          "value": "GKObstacleGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKObstacleGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKObstacleGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKObstacleGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKObstacleGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGraph~1findPath(from:to:)/title",
          "value": "findPathFromNode:toNode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGraph~1findPath(from:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findPathFromNode:toNode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKObstacleGraph~1init(obstacles:bufferRadius:)/title",
          "value": "initWithObstacles:bufferRadius:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKObstacleGraph~1init(obstacles:bufferRadius:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithObstacles:bufferRadius:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gkobstaclegraph/graphwithobstacles:bufferradius:nodeclass:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
