{
  "abstract": [
    {
      "text": "An error that occurs when PassKit cancels the addition of a Secure Element pass due to an unknown failure.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use PKAddSecureElementPassGeneralError instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unknownError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC31PKAddSecureElementPassErrorCodeLeV07unknownE0SoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknownError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
        "text": "PKAddSecureElementPassError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.4",
        "message": "Use PKAddSecureElementPassGeneralError instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.4",
        "message": "Use PKAddSecureElementPassGeneralError instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.4",
        "message": "Use PKAddSecureElementPassGeneralError instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use PKAddSecureElementPassGeneralError instead.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "6.2",
        "message": "Use PKAddSecureElementPassGeneralError instead.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "unknownError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknownError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
              "text": "PKAddSecureElementPassError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError": {
      "abstract": [
        {
          "text": "An error object that PassKit uses when it adds Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassError"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code": {
      "abstract": [
        {
          "text": "Error codes for problems that occur when you add a secure element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotReadyError": {
      "abstract": [
        {
          "text": "The device isn’t ready to add Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotReadyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotReadyError",
      "kind": "symbol",
      "role": "symbol",
      "title": "deviceNotReadyError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/devicenotreadyerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotSupportedError": {
      "abstract": [
        {
          "text": "The device doesn’t support adding Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotSupportedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotSupportedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "deviceNotSupportedError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/devicenotsupportederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/invalidConfigurationError": {
      "abstract": [
        {
          "text": "An error that occurs when they system attempts to add a Secure Element pass using an invalid configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConfigurationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/invalidConfigurationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidConfigurationError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/invalidconfigurationerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unavailableError": {
      "abstract": [
        {
          "text": "PassKit is temporarily unable to add Secure Element passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unavailableError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unavailableError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/unavailableerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unknownError": {
      "abstract": [
        {
          "text": "An error that occurs when PassKit cancels the addition of a Secure Element pass due to an unknown failure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/unknownerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/userCanceledError": {
      "abstract": [
        {
          "text": "An error that occurs when the user cancels the addition of a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCanceledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC31PKAddSecureElementPassErrorCodeLeV",
          "text": "PKAddSecureElementPassError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddSecureElementPassErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/userCanceledError",
      "kind": "symbol",
      "role": "symbol",
      "title": "userCanceledError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpasserror/usercancelederror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotReadyError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/deviceNotSupportedError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/invalidConfigurationError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/unavailableError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/userCanceledError",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassError/Code"
      ],
      "title": "Identifying errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/title",
          "value": "PKAddSecureElementPassErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkaddsecureelementpasserror/unknownerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
