{
  "abstract": [
    {
      "text": "The media container has no unplayed content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureNoUnplayedContent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPlayMediaIntentResponseCode@INPlayMediaIntentResponseCodeFailureNoUnplayedContent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failureNoUnplayedContent"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INPlayMediaIntentResponseCode.failureNoUnplayedContent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failureNoUnplayedContent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Respond with this code when a media container such as a playlist has no unplayed media items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode": {
      "abstract": [
        {
          "text": "Codes returned by an app or Intents app extension when handling or confirming a play media intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "A failure occurred while confirming or handling the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureNoUnplayedContent": {
      "abstract": [
        {
          "text": "The media container has no unplayed content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureNoUnplayedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureNoUnplayedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureNoUnplayedContent",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failurenounplayedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch the app before media playback can begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRestrictedContent": {
      "abstract": [
        {
          "text": "The app cannot play the media because of content restrictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRestrictedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRestrictedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureRestrictedContent"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureRestrictedContent",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failurerestrictedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureUnknownMediaType": {
      "abstract": [
        {
          "text": "The app cannot play the media because the type is unknown or not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureUnknownMediaType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureUnknownMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureUnknownMediaType"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureUnknownMediaType",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failureunknownmediatype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Failures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRestrictedContent",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureUnknownMediaType"
      ],
      "title": "Failures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Failures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRestrictedContent",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureUnknownMediaType"
              ],
              "title": "Failures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureNoUnplayedContent/title",
          "value": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureNoUnplayedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failure/title",
          "value": "INPlayMediaIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode/title",
          "value": "INPlayMediaIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureUnknownMediaType/title",
          "value": "INPlayMediaIntentResponseCodeFailureUnknownMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureUnknownMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureUnknownMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureRestrictedContent/title",
          "value": "INPlayMediaIntentResponseCodeFailureRestrictedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureRestrictedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureRestrictedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INPlayMediaIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inplaymediaintentresponsecode/failurenounplayedcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inplaymediaintentresponsecode/failurenounplayedcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
