{
  "abstract": [
    {
      "text": "The point in the scrolling lifecycle represented by the scroll update.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/phase-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)BEScrollViewScrollUpdate(py)phase",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "phase"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)BEScrollViewScrollUpdate",
        "text": "BEScrollViewScrollUpdate"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BEScrollViewScrollUpdatePhase",
        "text": "Phase"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "phase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "phase"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "phase"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)BEScrollViewScrollUpdate",
              "text": "BEScrollViewScrollUpdate"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BEScrollViewScrollUpdatePhase",
              "text": "Phase"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The phases of a scroll update represent a state machine:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A scroll gesture is initially in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/began",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " phase, when the person puts their finger down in the scroll view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "As the person interacts with the scroll view, the system generates zero or more ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/changed",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " updates for the scroll gesture.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Finally, the scroll gesture either enters the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/ended",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " phase when the person stops interacting with the scroll view; or it becomes ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/cancelled",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " when the operating system receives another event that means it stops tracking the scroll gesture.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate": {
      "abstract": [
        {
          "text": "An object that represents a change in a scroll view’s scroll state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BEScrollViewScrollUpdate"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEScrollViewScrollUpdate"
        }
      ],
      "role": "symbol",
      "title": "BEScrollViewScrollUpdate",
      "type": "topic",
      "url": "/documentation/browserenginekit/bescrollviewscrollupdate"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum": {
      "abstract": [
        {
          "text": "The phase of a scroll update in a scroll gesture’s lifecycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "role": "symbol",
      "title": "BEScrollViewScrollUpdate.Phase",
      "type": "topic",
      "url": "/documentation/browserenginekit/bescrollviewscrollupdate/phase-swift.enum"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/began": {
      "abstract": [
        {
          "text": "The scroll gesture began.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "began"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/began",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEScrollViewScrollUpdatePhaseBegan"
        }
      ],
      "role": "symbol",
      "title": "BEScrollViewScrollUpdate.Phase.began",
      "type": "topic",
      "url": "/documentation/browserenginekit/bescrollviewscrollupdate/phase-swift.enum/began"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/cancelled": {
      "abstract": [
        {
          "text": "The operating system detected an event that caused it to stop tracking the scroll gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEScrollViewScrollUpdatePhaseCancelled"
        }
      ],
      "role": "symbol",
      "title": "BEScrollViewScrollUpdate.Phase.cancelled",
      "type": "topic",
      "url": "/documentation/browserenginekit/bescrollviewscrollupdate/phase-swift.enum/cancelled"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/changed": {
      "abstract": [
        {
          "text": "The scroll gesture changed the scroll location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changed"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/changed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEScrollViewScrollUpdatePhaseChanged"
        }
      ],
      "role": "symbol",
      "title": "BEScrollViewScrollUpdate.Phase.changed",
      "type": "topic",
      "url": "/documentation/browserenginekit/bescrollviewscrollupdate/phase-swift.enum/changed"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/ended": {
      "abstract": [
        {
          "text": "The scroll gesture came to an end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BEScrollViewScrollUpdatePhaseEnded"
        }
      ],
      "role": "symbol",
      "title": "BEScrollViewScrollUpdate.Phase.ended",
      "type": "topic",
      "url": "/documentation/browserenginekit/bescrollviewscrollupdate/phase-swift.enum/ended"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/phase-swift.property": {
      "abstract": [
        {
          "text": "The point in the scrolling lifecycle represented by the scroll update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)BEScrollViewScrollUpdate",
          "text": "BEScrollViewScrollUpdate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BEScrollViewScrollUpdatePhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/phase-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "phase"
        }
      ],
      "role": "symbol",
      "title": "phase",
      "type": "topic",
      "url": "/documentation/browserenginekit/bescrollviewscrollupdate/phase-swift.property"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/timestamp": {
      "abstract": [
        {
          "text": "The time at which the scroll update occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/timestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timestamp"
        }
      ],
      "role": "symbol",
      "title": "timestamp",
      "type": "topic",
      "url": "/documentation/browserenginekit/bescrollviewscrollupdate/timestamp"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-scroll-state-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/timestamp",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum"
      ],
      "title": "Retrieving scroll state information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "phase"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "phase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Retrieving-scroll-state-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/timestamp",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum"
              ],
              "title": "Retrieving scroll state information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BEScrollViewScrollUpdate/Phase-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@BEScrollViewScrollUpdatePhase",
                    "text": "BEScrollViewScrollUpdatePhase"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "phase"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1phase-swift.property/title",
          "value": "phase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1phase-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "phase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1timestamp/title",
          "value": "timestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1timestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate/title",
          "value": "BEScrollViewScrollUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEScrollViewScrollUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEScrollViewScrollUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum/title",
          "value": "BEScrollViewScrollUpdatePhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEScrollViewScrollUpdatePhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BEScrollViewScrollUpdatePhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum~1cancelled/title",
          "value": "BEScrollViewScrollUpdatePhaseCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEScrollViewScrollUpdatePhaseCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum~1began/title",
          "value": "BEScrollViewScrollUpdatePhaseBegan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum~1began/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEScrollViewScrollUpdatePhaseBegan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum~1changed/title",
          "value": "BEScrollViewScrollUpdatePhaseChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum~1changed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEScrollViewScrollUpdatePhaseChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum~1ended/title",
          "value": "BEScrollViewScrollUpdatePhaseEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BEScrollViewScrollUpdate~1Phase-swift.enum~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BEScrollViewScrollUpdatePhaseEnded"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/bescrollviewscrollupdate/phase-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/bescrollviewscrollupdate/phase-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
