{
  "abstract": [
    {
      "text": "Creates an intent that describes media content such as a song, podcast episode, or movie.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/init(mediaItems:mediaContainer:playShuffled:playbackRepeatMode:resumePlayback:playbackQueueLocation:playbackSpeed:mediaSearch:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Intents",
    "externalID": "s:So17INPlayMediaIntentC7IntentsE10mediaItems0E9Container12playShuffled18playbackRepeatMode14resumePlayback0J13QueueLocation0J5Speed0E6SearchABSaySo11INMediaItemCGSg_AMSgSbSgSo010INPlaybackkL0VAQSo0uoP0VSdSgSo0sR0CSgtcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "mediaItems"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INMediaItem",
        "text": "INMediaItem"
      },
      {
        "kind": "text",
        "text": "]?, "
      },
      {
        "kind": "externalParam",
        "text": "mediaContainer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INMediaItem",
        "text": "INMediaItem"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "playShuffled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "playbackRepeatMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INPlaybackRepeatMode",
        "text": "INPlaybackRepeatMode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "resumePlayback"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "playbackQueueLocation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INPlaybackQueueLocation",
        "text": "INPlaybackQueueLocation"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "playbackSpeed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "mediaSearch"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INMediaSearch",
        "text": "INMediaSearch"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(mediaItems:mediaContainer:playShuffled:playbackRepeatMode:resumePlayback:playbackQueueLocation:playbackSpeed:mediaSearch:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "mediaItems"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INMediaItem",
              "text": "INMediaItem"
            },
            {
              "kind": "text",
              "text": "]? = nil, "
            },
            {
              "kind": "externalParam",
              "text": "mediaContainer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INMediaItem",
              "text": "INMediaItem"
            },
            {
              "kind": "text",
              "text": "? = nil, "
            },
            {
              "kind": "externalParam",
              "text": "playShuffled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": "? = nil, "
            },
            {
              "kind": "externalParam",
              "text": "playbackRepeatMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INPlaybackRepeatMode",
              "text": "INPlaybackRepeatMode"
            },
            {
              "kind": "text",
              "text": " = .unknown, "
            },
            {
              "kind": "externalParam",
              "text": "resumePlayback"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": "? = nil, "
            },
            {
              "kind": "externalParam",
              "text": "playbackQueueLocation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INPlaybackQueueLocation",
              "text": "INPlaybackQueueLocation"
            },
            {
              "kind": "text",
              "text": " = .unknown, "
            },
            {
              "kind": "externalParam",
              "text": "playbackSpeed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": "? = nil, "
            },
            {
              "kind": "externalParam",
              "text": "mediaSearch"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INMediaSearch",
              "text": "INMediaSearch"
            },
            {
              "kind": "text",
              "text": "? = nil)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The media content, such as a song or episode of TV show, that the user is playing. When donating the intent, the system uses only the first item in the array, ignoring the other media items in the array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mediaItems"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The container of the media item. For example, when the user plays a song from the playlist, the playlist is the container. A television show with multiple episodes is another example. However, some media items, like movies, may have no container.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mediaContainer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that indicates whether the media plays in a shuffled order.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "playShuffled"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The repeat mode setting at the time the user plays the media item.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "playbackRepeatMode"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The resume playback setting at the time the user plays the media item. Set to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " when the user hasn’t finished listening to or watching the media item.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "resumePlayback"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The location in the queue to play the media item.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "playbackQueueLocation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The speed to play the media item.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "playbackSpeed"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The search parameters for a media item.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mediaSearch"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object should include information about the media that accurately represents the content. For example, if the user plays a song from a particular album, include both pieces of information in the intent. Provide the song in ",
              "type": "text"
            },
            {
              "code": "mediaItems",
              "type": "codeVoice"
            },
            {
              "text": " and the album in ",
              "type": "text"
            },
            {
              "code": "mediaContainer",
              "type": "codeVoice"
            },
            {
              "text": ". If your app supports options for shuffle play, repeat modes, and resuming playback, include the current settings for those options when creating the intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItem": {
      "abstract": [
        {
          "text": "An object that describes a piece of media content, such as a song, TV show, artist, or podcast playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaItem"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItem"
        }
      ],
      "role": "symbol",
      "title": "INMediaItem",
      "type": "topic",
      "url": "/documentation/intents/inmediaitem"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch": {
      "abstract": [
        {
          "text": "An object that describes a media type to search for, such as a station name, song name, or album name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaSearch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSearch"
        }
      ],
      "role": "symbol",
      "title": "INMediaSearch",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent": {
      "abstract": [
        {
          "text": "An intent that contains information about media playable from your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntent"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntent",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/init(mediaItems:mediaContainer:playShuffled:playbackRepeatMode:resumePlayback:playbackQueueLocation:playbackSpeed:mediaSearch:)": {
      "abstract": [
        {
          "text": "Creates an intent that describes media content such as a song, podcast episode, or movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mediaItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INMediaItem",
          "text": "INMediaItem"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "mediaContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INMediaItem",
          "text": "INMediaItem"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "playShuffled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "playbackRepeatMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPlaybackRepeatMode",
          "text": "INPlaybackRepeatMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resumePlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "playbackQueueLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPlaybackQueueLocation",
          "text": "INPlaybackQueueLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "playbackSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "mediaSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INMediaSearch",
          "text": "INMediaSearch"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/init(mediaItems:mediaContainer:playShuffled:playbackRepeatMode:resumePlayback:playbackQueueLocation:playbackSpeed:mediaSearch:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mediaItems:mediaContainer:playShuffled:playbackRepeatMode:resumePlayback:playbackQueueLocation:playbackSpeed:mediaSearch:)",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/init(mediaitems:mediacontainer:playshuffled:playbackrepeatmode:resumeplayback:playbackqueuelocation:playbackspeed:mediasearch:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation": {
      "abstract": [
        {
          "text": "Constants that describe the playback queue location for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocation",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode": {
      "abstract": [
        {
          "text": "The possible repeat modes at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackRepeatMode",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmode"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/title",
          "value": "INPlaybackQueueLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/title",
          "value": "INPlaybackRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/title",
          "value": "INPlayMediaIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem/title",
          "value": "INMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/title",
          "value": "INMediaSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSearch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inplaymediaintent/init(mediaitems:mediacontainer:playshuffled:playbackrepeatmode:resumeplayback:playbackqueuelocation:playbackspeed:mediasearch:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
