{
  "abstract": [
    {
      "text": "An object that contains the search parameters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/mediaSearch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INPlayMediaIntent(py)mediaSearch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mediaSearch"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INMediaSearch",
        "text": "INMediaSearch"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mediaSearch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mediaSearch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mediaSearch"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INMediaSearch",
              "text": "INMediaSearch"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch": {
      "abstract": [
        {
          "text": "An object that describes a media type to search for, such as a station name, song name, or album name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaSearch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSearch"
        }
      ],
      "role": "symbol",
      "title": "INMediaSearch",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent": {
      "abstract": [
        {
          "text": "An intent that contains information about media playable from your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntent"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntent",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/mediaSearch": {
      "abstract": [
        {
          "text": "An object that contains the search parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INMediaSearch",
          "text": "INMediaSearch"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/mediaSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaSearch"
        }
      ],
      "role": "symbol",
      "title": "mediaSearch",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/mediasearch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-2btex": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media plays in a shuffled order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playShuffled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-2btex",
      "kind": "symbol",
      "role": "symbol",
      "title": "playShuffled",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playshuffled-2btex"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-93hn1": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media plays in a shuffled order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "playShuffled"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-93hn1",
      "kind": "symbol",
      "role": "symbol",
      "title": "playShuffled",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playshuffled-93hn1"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackQueueLocation": {
      "abstract": [
        {
          "text": "The queue location for a media item during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackQueueLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPlaybackQueueLocation",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackQueueLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackQueueLocation"
        }
      ],
      "role": "symbol",
      "title": "playbackQueueLocation",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playbackqueuelocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackRepeatMode": {
      "abstract": [
        {
          "text": "The repeat mode setting at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackRepeatMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPlaybackRepeatMode",
          "text": "INPlaybackRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "playbackRepeatMode",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playbackrepeatmode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-17r2t": {
      "abstract": [
        {
          "text": "The playback speed for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-17r2t",
      "kind": "symbol",
      "role": "symbol",
      "title": "playbackSpeed",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playbackspeed-17r2t"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-6ngbq": {
      "abstract": [
        {
          "text": "The playback speed for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "playbackSpeed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-6ngbq",
      "kind": "symbol",
      "role": "symbol",
      "title": "playbackSpeed",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playbackspeed-6ngbq"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-1xw6r": {
      "abstract": [
        {
          "text": "The resume playback setting at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumePlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-1xw6r",
      "kind": "symbol",
      "role": "symbol",
      "title": "resumePlayback",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/resumeplayback-1xw6r"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-9zfyp": {
      "abstract": [
        {
          "text": "The resume playback setting at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "resumePlayback"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-9zfyp",
      "kind": "symbol",
      "role": "symbol",
      "title": "resumePlayback",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/resumeplayback-9zfyp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation": {
      "abstract": [
        {
          "text": "Constants that describe the playback queue location for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocation",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode": {
      "abstract": [
        {
          "text": "The possible repeat modes at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackRepeatMode",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Playback-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-2btex",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-1xw6r",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackRepeatMode",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-17r2t",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackQueueLocation",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation"
      ],
      "title": "Accessing Playback Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mediaSearch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Playback-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-93hn1",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-9zfyp",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackRepeatMode",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-6ngbq",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackQueueLocation",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation"
              ],
              "title": "Accessing Playback Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INMediaSearch",
                    "text": "INMediaSearch"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "mediaSearch"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INMediaSearch",
                    "text": "INMediaSearch"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "mediaSearch"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1playbackQueueLocation/title",
          "value": "playbackQueueLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1playbackQueueLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1mediaSearch/title",
          "value": "mediaSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1mediaSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/title",
          "value": "INPlaybackRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/title",
          "value": "INPlaybackQueueLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/title",
          "value": "INMediaSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1playbackRepeatMode/title",
          "value": "playbackRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1playbackRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/title",
          "value": "INPlayMediaIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inplaymediaintent/mediasearch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inplaymediaintent/mediasearch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
