{
  "abstract": [
    {
      "text": "The watch face is not available on this device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLKWatchFaceLibraryErrorCode@CLKWatchFaceLibraryErrorCodeFaceNotAvailable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "faceNotAvailable"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLKWatchFaceLibrary.ErrorCode.faceNotAvailable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "faceNotAvailable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary": {
      "abstract": [
        {
          "text": "An object for importing watch faces that the app provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibrary"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibrary"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode": {
      "abstract": [
        {
          "text": "Error codes that the watch face library returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable": {
      "abstract": [
        {
          "text": "The watch face is not available on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode.faceNotAvailable",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/facenotavailable"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile": {
      "abstract": [
        {
          "text": "The specified file wasn’t a valid watch face file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFile"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorCodeInvalidFile"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode.invalidFile",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/invalidfile"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL": {
      "abstract": [
        {
          "text": "No file was found at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFileURL"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorCodeNotFileURL"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode.notFileURL",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/notfileurl"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied": {
      "abstract": [
        {
          "text": "The app does not have permission to read the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorCodePermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode.permissionDenied",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/permissiondenied"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode/title",
          "value": "CLKWatchFaceLibraryErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary/title",
          "value": "CLKWatchFaceLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1faceNotAvailable/title",
          "value": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1faceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1permissionDenied/title",
          "value": "CLKWatchFaceLibraryErrorCodePermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1permissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodePermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1invalidFile/title",
          "value": "CLKWatchFaceLibraryErrorCodeInvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1invalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodeInvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1notFileURL/title",
          "value": "CLKWatchFaceLibraryErrorCodeNotFileURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1notFileURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodeNotFileURL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkwatchfacelibrary/errorcode/facenotavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkwatchfacelibrary/errorcode/facenotavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
