{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSVolume"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "FSKit",
    "externalID": "c:@E@FSAccessMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AccessMask"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AccessMask"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "FSVolume.AccessMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AccessMask"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSBlockmapFlags": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSBlockmapFlags"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockmapFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSBlockmapFlags"
        }
      ],
      "role": "symbol",
      "title": "FSBlockmapFlags",
      "type": "topic",
      "url": "/documentation/fskit/fsblockmapflags"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSCompleteIOFlags"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSCompleteIOFlags"
        }
      ],
      "role": "symbol",
      "title": "FSCompleteIOFlags",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags"
    },
    "doc://FSKit/documentation/FSKit/FSDeactivateOptions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSDeactivateOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDeactivateOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDeactivateOptions"
        }
      ],
      "role": "symbol",
      "title": "FSDeactivateOptions",
      "type": "topic",
      "url": "/documentation/fskit/fsdeactivateoptions"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryCookie": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSDirectoryCookie"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryCookie"
        }
      ],
      "role": "symbol",
      "title": "FSDirectoryCookie",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectorycookie"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryCookie/initial": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FSDirectoryCookie",
          "text": "FSDirectoryCookie"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryCookie/initial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryCookieInitial"
        }
      ],
      "role": "symbol",
      "title": "initial",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectorycookie/initial"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryEntryPacker": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSDirectoryEntryPacker"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryEntryPacker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryEntryPacker"
        }
      ],
      "role": "symbol",
      "title": "FSDirectoryEntryPacker",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectoryentrypacker"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryVerifier": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSDirectoryVerifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryVerifier"
        }
      ],
      "role": "symbol",
      "title": "FSDirectoryVerifier",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectoryverifier"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryVerifier/initial": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FSDirectoryVerifier",
          "text": "FSDirectoryVerifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryVerifier/initial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryVerifierInitial"
        }
      ],
      "role": "symbol",
      "title": "initial",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectoryverifier/initial"
    },
    "doc://FSKit/documentation/FSKit/FSEntityIdentifier": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSEntityIdentifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSEntityIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSEntityIdentifier"
        }
      ],
      "role": "symbol",
      "title": "FSEntityIdentifier",
      "type": "topic",
      "url": "/documentation/fskit/fsentityidentifier"
    },
    "doc://FSKit/documentation/FSKit/FSExtentPacker": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSExtentPacker"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSExtentPacker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSExtentPacker"
        }
      ],
      "role": "symbol",
      "title": "FSExtentPacker",
      "type": "topic",
      "url": "/documentation/fskit/fsextentpacker"
    },
    "doc://FSKit/documentation/FSKit/FSExtentType": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSExtentType"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSExtentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSExtentType"
        }
      ],
      "role": "symbol",
      "title": "FSExtentType",
      "type": "topic",
      "url": "/documentation/fskit/fsextenttype"
    },
    "doc://FSKit/documentation/FSKit/FSMatchResult": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSMatchResult"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSMatchResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSMatchResult"
        }
      ],
      "role": "symbol",
      "title": "FSMatchResult",
      "type": "topic",
      "url": "/documentation/fskit/fsmatchresult"
    },
    "doc://FSKit/documentation/FSKit/FSMetadataRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSMetadataRange"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSMetadataRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSMetadataRange"
        }
      ],
      "role": "symbol",
      "title": "FSMetadataRange",
      "type": "topic",
      "url": "/documentation/fskit/fsmetadatarange"
    },
    "doc://FSKit/documentation/FSKit/FSVolume": {
      "abstract": [
        {
          "text": "A directory structure for files and folders.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "role": "symbol",
      "title": "FSVolume",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessMask"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.AccessMask",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/equatable-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/OptionSet-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/OptionSet-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OptionSet Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/optionset-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/SetAlgebra-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/SetAlgebra-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SetAlgebra Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/setalgebra-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/addFile": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/addFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessAddFile"
        }
      ],
      "role": "symbol",
      "title": "addFile",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/addfile"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/addSubdirectory": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSubdirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/addSubdirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessAddSubdirectory"
        }
      ],
      "role": "symbol",
      "title": "addSubdirectory",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/addsubdirectory"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/appendData": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/appendData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessAppendData"
        }
      ],
      "role": "symbol",
      "title": "appendData",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/appenddata"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/delete": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/delete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessDelete"
        }
      ],
      "role": "symbol",
      "title": "delete",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/delete"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/deleteChild": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/deleteChild",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessDeleteChild"
        }
      ],
      "role": "symbol",
      "title": "deleteChild",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/deletechild"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/execute": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/execute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessExecute"
        }
      ],
      "role": "symbol",
      "title": "execute",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/execute"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/init(rawvalue:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/listDirectory": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/listDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessListDirectory"
        }
      ],
      "role": "symbol",
      "title": "listDirectory",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/listdirectory"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readAttributes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessReadAttributes"
        }
      ],
      "role": "symbol",
      "title": "readAttributes",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/readattributes"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readData": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessReadData"
        }
      ],
      "role": "symbol",
      "title": "readData",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/readdata"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readSecurity": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readSecurity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessReadSecurity"
        }
      ],
      "role": "symbol",
      "title": "readSecurity",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/readsecurity"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readXattr": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readXattr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readXattr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessReadXattr"
        }
      ],
      "role": "symbol",
      "title": "readXattr",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/readxattr"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/search": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessSearch"
        }
      ],
      "role": "symbol",
      "title": "search",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/search"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/takeOwnership": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "takeOwnership"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/takeOwnership",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessTakeOwnership"
        }
      ],
      "role": "symbol",
      "title": "takeOwnership",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/takeownership"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeAttributes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessWriteAttributes"
        }
      ],
      "role": "symbol",
      "title": "writeAttributes",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/writeattributes"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeData": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessWriteData"
        }
      ],
      "role": "symbol",
      "title": "writeData",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/writedata"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeSecurity": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeSecurity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeSecurity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessWriteSecurity"
        }
      ],
      "role": "symbol",
      "title": "writeSecurity",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/writesecurity"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeXattr": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeXattr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSAccessMask",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeXattr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSAccessWriteXattr"
        }
      ],
      "role": "symbol",
      "title": "writeXattr",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/writexattr"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-types",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSBlockmapFlags",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags",
        "doc://FSKit/documentation/FSKit/FSDeactivateOptions",
        "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
        "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
        "doc://FSKit/documentation/FSKit/FSDirectoryCookie/initial",
        "doc://FSKit/documentation/FSKit/FSDirectoryEntryPacker",
        "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
        "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
        "doc://FSKit/documentation/FSKit/FSDirectoryVerifier/initial",
        "doc://FSKit/documentation/FSKit/FSEntityIdentifier",
        "doc://FSKit/documentation/FSKit/FSExtentPacker",
        "doc://FSKit/documentation/FSKit/FSExtentType",
        "doc://FSKit/documentation/FSKit/FSMatchResult",
        "doc://FSKit/documentation/FSKit/FSMetadataRange"
      ],
      "title": "Supporting types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/addFile",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/addSubdirectory",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/appendData",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/delete",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/deleteChild",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/execute",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/listDirectory",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readAttributes",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readData",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readSecurity",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readXattr",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/search",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/takeOwnership",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeAttributes",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeData",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeSecurity",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeXattr"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/Equatable-Implementations",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/OptionSet-Implementations",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/SetAlgebra-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSAccessMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/addFile",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/addSubdirectory",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/appendData",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/delete",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/deleteChild",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/execute",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/listDirectory",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readAttributes",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readData",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readSecurity",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/readXattr",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/search",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/takeOwnership",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeAttributes",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeData",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeSecurity",
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/writeXattr"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-types",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSBlockmapFlags",
                "doc://FSKit/documentation/FSKit/FSCompleteIOFlags",
                "doc://FSKit/documentation/FSKit/FSDeactivateOptions",
                "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
                "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
                "doc://FSKit/documentation/FSKit/FSDirectoryCookie/initial",
                "doc://FSKit/documentation/FSKit/FSDirectoryEntryPacker",
                "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
                "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
                "doc://FSKit/documentation/FSKit/FSDirectoryVerifier/initial",
                "doc://FSKit/documentation/FSKit/FSEntityIdentifier",
                "doc://FSKit/documentation/FSKit/FSExtentPacker",
                "doc://FSKit/documentation/FSKit/FSExtentType",
                "doc://FSKit/documentation/FSKit/FSMatchResult",
                "doc://FSKit/documentation/FSKit/FSMetadataRange"
              ],
              "title": "Supporting types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSAccessMask"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1execute/title",
          "value": "FSAccessExecute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1execute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessExecute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1readXattr/title",
          "value": "FSAccessReadXattr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1readXattr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessReadXattr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1takeOwnership/title",
          "value": "FSAccessTakeOwnership"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1takeOwnership/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessTakeOwnership"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1readAttributes/title",
          "value": "FSAccessReadAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1readAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessReadAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/title",
          "value": "FSVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/title",
          "value": "FSAccessMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1addFile/title",
          "value": "FSAccessAddFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1addFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessAddFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1readData/title",
          "value": "FSAccessReadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1readData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessReadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentType/title",
          "value": "FSExtentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSExtentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSExtentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryEntryPacker/title",
          "value": "FSDirectoryEntryPacker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryEntryPacker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryEntryPacker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryEntryPacker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryEntryPacker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDeactivateOptions/title",
          "value": "FSDeactivateOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDeactivateOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDeactivateOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDeactivateOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDeactivateOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1addSubdirectory/title",
          "value": "FSAccessAddSubdirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1addSubdirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessAddSubdirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1listDirectory/title",
          "value": "FSAccessListDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1listDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessListDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1appendData/title",
          "value": "FSAccessAppendData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1appendData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessAppendData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentPacker/title",
          "value": "FSExtentPacker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentPacker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSExtentPacker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentPacker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSExtentPacker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier~1initial/title",
          "value": "FSDirectoryVerifierInitial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier~1initial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryVerifierInitial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1readSecurity/title",
          "value": "FSAccessReadSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1readSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessReadSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie/title",
          "value": "FSDirectoryCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockmapFlags/title",
          "value": "FSBlockmapFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockmapFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSBlockmapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockmapFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSBlockmapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1writeData/title",
          "value": "FSAccessWriteData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1writeData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessWriteData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMetadataRange/title",
          "value": "FSMetadataRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMetadataRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSMetadataRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMetadataRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSMetadataRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1writeAttributes/title",
          "value": "FSAccessWriteAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1writeAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessWriteAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1delete/title",
          "value": "FSAccessDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1delete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1search/title",
          "value": "FSAccessSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1deleteChild/title",
          "value": "FSAccessDeleteChild"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1deleteChild/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessDeleteChild"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie~1initial/title",
          "value": "FSDirectoryCookieInitial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie~1initial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryCookieInitial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1writeSecurity/title",
          "value": "FSAccessWriteSecurity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1writeSecurity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessWriteSecurity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMatchResult/title",
          "value": "FSMatchResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMatchResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSMatchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMatchResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSMatchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSEntityIdentifier/title",
          "value": "FSEntityIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSEntityIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSEntityIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSEntityIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSEntityIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier/title",
          "value": "FSDirectoryVerifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryVerifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryVerifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1writeXattr/title",
          "value": "FSAccessWriteXattr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask~1writeXattr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessWriteXattr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/title",
          "value": "FSCompleteIOFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSCompleteIOFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSCompleteIOFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsvolume/accessmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsvolume/accessmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
