{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSVolume"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "FSKit",
    "externalID": "c:@E@FSVolumeCaseFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CaseFormat"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CaseFormat"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "FSVolume.CaseFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CaseFormat"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSVolume": {
      "abstract": [
        {
          "text": "A directory structure for files and folders.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "role": "symbol",
      "title": "FSVolume",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CaseFormat"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CaseFormat"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.CaseFormat",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat/equatable-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat/rawrepresentable-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat/init(rawvalue:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/insensitive": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insensitive"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/insensitive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolumeCaseFormatInsensitive"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.CaseFormat.insensitive",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat/insensitive"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/insensitiveCasePreserving": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insensitiveCasePreserving"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/insensitiveCasePreserving",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolumeCaseFormatInsensitiveCasePreserving"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.CaseFormat.insensitiveCasePreserving",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat/insensitivecasepreserving"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/sensitive": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensitive"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/sensitive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolumeCaseFormatSensitive"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.CaseFormat.sensitive",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat/sensitive"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ItemDeactivation"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ItemDeactivation"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ItemDeactivation",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivation"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ItemDeactivationOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ItemDeactivationOptions"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ItemDeactivationOptions",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/OpenModes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpenModes"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OpenModes"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.OpenModes",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/openmodes"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SupportedCapabilities"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SupportedCapabilities"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.SupportedCapabilities",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-types",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities"
      ],
      "title": "Supporting types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/insensitive",
        "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/insensitiveCasePreserving",
        "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/sensitive"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/Equatable-Implementations",
        "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSVolumeCaseFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/insensitive",
                "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/insensitiveCasePreserving",
                "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat/sensitive"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-types",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
                "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
                "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities"
              ],
              "title": "Supporting types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSVolumeCaseFormat"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/title",
          "value": "FSVolumeOpenModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/title",
          "value": "FSVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/title",
          "value": "FSVolumeItemDeactivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeItemDeactivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeItemDeactivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat~1insensitive/title",
          "value": "FSVolumeCaseFormatInsensitive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat~1insensitive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormatInsensitive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat~1insensitiveCasePreserving/title",
          "value": "FSVolumeCaseFormatInsensitiveCasePreserving"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat~1insensitiveCasePreserving/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormatInsensitiveCasePreserving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat~1sensitive/title",
          "value": "FSVolumeCaseFormatSensitive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat~1sensitive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormatSensitive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/title",
          "value": "FSVolumeCaseFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/title",
          "value": "FSItemDeactivationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/title",
          "value": "FSVolumeSupportedCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeSupportedCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeSupportedCapabilities"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsvolume/caseformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsvolume/caseformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
