{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSVolume"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "FSKit",
    "externalID": "c:@E@FSItemDeactivationOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ItemDeactivationOptions"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ItemDeactivationOptions"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "FSVolume.ItemDeactivationOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ItemDeactivationOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSItemDeactivationOptions/FSItemDeactivationNever": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FSItemDeactivationNever"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItemDeactivationOptions/FSItemDeactivationNever",
      "kind": "symbol",
      "role": "symbol",
      "title": "FSItemDeactivationNever",
      "type": "topic",
      "url": "/documentation/fskit/fsitemdeactivationoptions/fsitemdeactivationnever"
    },
    "doc://FSKit/documentation/FSKit/FSVolume": {
      "abstract": [
        {
          "text": "A directory structure for files and folders.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "role": "symbol",
      "title": "FSVolume",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CaseFormat"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CaseFormat"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.CaseFormat",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ItemDeactivation"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ItemDeactivation"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ItemDeactivation",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivation"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ItemDeactivationOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ItemDeactivationOptions"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ItemDeactivationOptions",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions/equatable-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/OptionSet-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/OptionSet-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OptionSet Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions/optionset-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/SetAlgebra-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/SetAlgebra-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SetAlgebra Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions/setalgebra-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/always": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "always"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSItemDeactivationOptions",
          "text": "ItemDeactivationOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/always",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSItemDeactivationAlways"
        }
      ],
      "role": "symbol",
      "title": "always",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions/always"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/forPreallocatedItems": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forPreallocatedItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSItemDeactivationOptions",
          "text": "ItemDeactivationOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/forPreallocatedItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSItemDeactivationForPreallocatedItems"
        }
      ],
      "role": "symbol",
      "title": "forPreallocatedItems",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions/forpreallocateditems"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/forRemovedItems": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forRemovedItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSItemDeactivationOptions",
          "text": "ItemDeactivationOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/forRemovedItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSItemDeactivationForRemovedItems"
        }
      ],
      "role": "symbol",
      "title": "forRemovedItems",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions/forremoveditems"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions/init(rawvalue:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/OpenModes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpenModes"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OpenModes"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.OpenModes",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/openmodes"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SupportedCapabilities"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SupportedCapabilities"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.SupportedCapabilities",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-types",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat",
        "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities"
      ],
      "title": "Supporting types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/always",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/forPreallocatedItems",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/forRemovedItems"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/Equatable-Implementations",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/OptionSet-Implementations",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/SetAlgebra-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSItemDeactivationOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSItemDeactivationOptions/FSItemDeactivationNever",
                "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/always",
                "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/forPreallocatedItems",
                "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions/forRemovedItems"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-types",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat",
                "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
                "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities"
              ],
              "title": "Supporting types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSItemDeactivationOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/title",
          "value": "FSVolumeSupportedCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeSupportedCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeSupportedCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/title",
          "value": "FSItemDeactivationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions~1forRemovedItems/title",
          "value": "FSItemDeactivationForRemovedItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions~1forRemovedItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationForRemovedItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/title",
          "value": "FSVolumeItemDeactivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeItemDeactivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeItemDeactivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/title",
          "value": "FSVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions~1forPreallocatedItems/title",
          "value": "FSItemDeactivationForPreallocatedItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions~1forPreallocatedItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationForPreallocatedItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/title",
          "value": "FSVolumeCaseFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/title",
          "value": "FSVolumeOpenModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions~1always/title",
          "value": "FSItemDeactivationAlways"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions~1always/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationAlways"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsvolume/itemdeactivationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsvolume/itemdeactivationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
