{
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSVolume"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSVolume/Operations"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "FSKit",
    "externalID": "c:objc(pl)FSVolumeOperations",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Operations"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Operations"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FSVolume.Operations"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Operations"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSVolume",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)FSVolume",
              "text": "FSVolume"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)FSVolumePathConfOperations",
              "text": "PathConfOperations"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSVolume": {
      "abstract": [
        {
          "text": "A directory structure for files and folders.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "role": "symbol",
      "title": "FSVolume",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessCheckOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessCheckOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessCheckOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessCheckOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.AccessCheckOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accesscheckoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/OpenCloseOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpenCloseOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/OpenCloseOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OpenCloseOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.OpenCloseOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/opencloseoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Operations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Operations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.Operations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/activate(options:replyHandler:)": {
      "abstract": [
        {
          "text": "activateWithOptions:replyHandler:",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSTaskOptions",
          "text": "FSTaskOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/activate(options:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activateWithOptions:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "activate(options:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/activate(options:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/createItem(named:type:inDirectory:attributes:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSItemType",
          "text": "ItemType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItemSetAttributesRequest",
          "text": "SetAttributesRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/createItem(named:type:inDirectory:attributes:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createItemNamed:type:inDirectory:attributes:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "createItem(named:type:inDirectory:attributes:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/createitem(named:type:indirectory:attributes:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/createLink(to:named:inDirectory:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createLink"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/createLink(to:named:inDirectory:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createLinkToItem:named:inDirectory:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "createLink(to:named:inDirectory:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/createlink(to:named:indirectory:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/createSymbolicLink(named:inDirectory:attributes:linkContents:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createSymbolicLink"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItemSetAttributesRequest",
          "text": "SetAttributesRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "linkContents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/createSymbolicLink(named:inDirectory:attributes:linkContents:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createSymbolicLinkNamed:inDirectory:attributes:linkContents:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "createSymbolicLink(named:inDirectory:attributes:linkContents:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/createsymboliclink(named:indirectory:attributes:linkcontents:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/deactivate(options:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deactivate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSDeactivateOptions",
          "text": "FSDeactivateOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/deactivate(options:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deactivateWithOptions:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "deactivate(options:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/deactivate(options:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/enumerateDirectory(_:startingAt:verifier:attributes:packer:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateDirectory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startingAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FSDirectoryCookie",
          "text": "FSDirectoryCookie"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "verifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FSDirectoryVerifier",
          "text": "FSDirectoryVerifier"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItemGetAttributesRequest",
          "text": "GetAttributesRequest"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "packer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSDirectoryEntryPacker",
          "text": "FSDirectoryEntryPacker"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FSDirectoryVerifier",
          "text": "FSDirectoryVerifier"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/enumerateDirectory(_:startingAt:verifier:attributes:packer:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateDirectory:startingAtCookie:verifier:providingAttributes:usingPacker:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "enumerateDirectory(_:startingAt:verifier:attributes:packer:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/enumeratedirectory(_:startingat:verifier:attributes:packer:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/getAttributes(_:of:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItemGetAttributesRequest",
          "text": "GetAttributesRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItemAttributes",
          "text": "Attributes"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/getAttributes(_:of:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getAttributes:ofItem:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "getAttributes(_:of:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/getattributes(_:of:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/lookupItem(named:inDirectory:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookupItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/lookupItem(named:inDirectory:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookupItemNamed:inDirectory:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lookupItem(named:inDirectory:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/lookupitem(named:indirectory:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/mount(options:replyHandler:)": {
      "abstract": [
        {
          "text": "mountWithOptions:replyHandler:",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSTaskOptions",
          "text": "FSTaskOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/mount(options:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mountWithOptions:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "mount(options:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/mount(options:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/readSymbolicLink(_:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readSymbolicLink"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/readSymbolicLink(_:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readSymbolicLink:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "readSymbolicLink(_:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/readsymboliclink(_:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/reclaimItem(_:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reclaimItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/reclaimItem(_:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reclaimItem:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reclaimItem(_:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/reclaimitem(_:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/removeItem(_:named:fromDirectory:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fromDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/removeItem(_:named:fromDirectory:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeItem:named:fromDirectory:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "removeItem(_:named:fromDirectory:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/removeitem(_:named:fromdirectory:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/renameItem(_:inDirectory:named:to:inDirectory:overItem:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renameItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "overItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSFileName",
          "text": "FSFileName"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/renameItem(_:inDirectory:named:to:inDirectory:overItem:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renameItem:inDirectory:named:toNewName:inDirectory:overItem:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "renameItem(_:inDirectory:named:to:inDirectory:overItem:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/renameitem(_:indirectory:named:to:indirectory:overitem:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/setAttributes(_:on:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItemSetAttributesRequest",
          "text": "SetAttributesRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItemAttributes",
          "text": "Attributes"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/setAttributes(_:on:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAttributes:onItem:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setAttributes(_:on:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/setattributes(_:on:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/supportedVolumeCapabilities": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedVolumeCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolumeSupportedCapabilities",
          "text": "SupportedCapabilities"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/supportedVolumeCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedVolumeCapabilities"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportedVolumeCapabilities",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/supportedvolumecapabilities"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/synchronize(flags:replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "synchronize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSSyncFlags",
          "text": "FSSyncFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/synchronize(flags:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "synchronizeWithFlags:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "synchronize(flags:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/synchronize(flags:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/unmount(replyHandler:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unmount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/unmount(replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unmountWithReplyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "unmount(replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/unmount(replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations/volumeStatistics": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volumeStatistics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSStatFSResult",
          "text": "FSStatFSResult"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations/volumeStatistics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "volumeStatistics"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "volumeStatistics",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations/volumestatistics"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PathConfOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PathConfOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.PathConfOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PreallocateOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PreallocateOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PreallocateOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PreallocateOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.PreallocateOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/preallocateoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ReadWriteOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadWriteOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ReadWriteOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadWriteOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ReadWriteOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/readwriteoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/RenameOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RenameOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/RenameOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RenameOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.RenameOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/renameoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/XattrOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XattrOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/XattrOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XattrOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.XattrOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/xattroperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolumeKernelOffloadedIOOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSVolumeKernelOffloadedIOOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolumeKernelOffloadedIOOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolumeKernelOffloadedIOOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolumeKernelOffloadedIOOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolumekerneloffloadediooperations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Volume-operations",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/AccessCheckOperations",
        "doc://FSKit/documentation/FSKit/FSVolumeKernelOffloadedIOOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/OpenCloseOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/PreallocateOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/ReadWriteOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/RenameOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/XattrOperations"
      ],
      "title": "Volume operations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/supportedVolumeCapabilities",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/volumeStatistics"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/activate(options:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/createItem(named:type:inDirectory:attributes:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/createLink(to:named:inDirectory:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/createSymbolicLink(named:inDirectory:attributes:linkContents:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/deactivate(options:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/enumerateDirectory(_:startingAt:verifier:attributes:packer:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/getAttributes(_:of:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/lookupItem(named:inDirectory:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/mount(options:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/readSymbolicLink(_:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/reclaimItem(_:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/removeItem(_:named:fromDirectory:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/renameItem(_:inDirectory:named:to:inDirectory:overItem:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/setAttributes(_:on:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/synchronize(flags:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations/unmount(replyHandler:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSVolumeOperations"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/supportedVolumeCapabilities",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/volumeStatistics"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/activate(options:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/createItem(named:type:inDirectory:attributes:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/createLink(to:named:inDirectory:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/createSymbolicLink(named:inDirectory:attributes:linkContents:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/deactivate(options:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/enumerateDirectory(_:startingAt:verifier:attributes:packer:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/getAttributes(_:of:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/lookupItem(named:inDirectory:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/mount(options:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/readSymbolicLink(_:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/reclaimItem(_:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/removeItem(_:named:fromDirectory:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/renameItem(_:inDirectory:named:to:inDirectory:overItem:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/setAttributes(_:on:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/synchronize(flags:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations/unmount(replyHandler:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Volume-operations",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/AccessCheckOperations",
                "doc://FSKit/documentation/FSKit/FSVolumeKernelOffloadedIOOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/OpenCloseOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/PreallocateOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/ReadWriteOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/RenameOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/XattrOperations"
              ],
              "title": "Volume operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSVolumeOperations"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)FSVolumePathConfOperations",
                    "text": "FSVolumePathConfOperations"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1RenameOperations/title",
          "value": "FSVolumeRenameOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1RenameOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeRenameOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1RenameOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeRenameOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1renameItem(_:inDirectory:named:to:inDirectory:overItem:replyHandler:)/title",
          "value": "renameItem:inDirectory:named:toNewName:inDirectory:overItem:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1renameItem(_:inDirectory:named:to:inDirectory:overItem:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "renameItem:inDirectory:named:toNewName:inDirectory:overItem:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1readSymbolicLink(_:replyHandler:)/title",
          "value": "readSymbolicLink:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1readSymbolicLink(_:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readSymbolicLink:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1lookupItem(named:inDirectory:replyHandler:)/title",
          "value": "lookupItemNamed:inDirectory:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1lookupItem(named:inDirectory:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookupItemNamed:inDirectory:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1mount(options:replyHandler:)/title",
          "value": "mountWithOptions:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1mount(options:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mountWithOptions:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1deactivate(options:replyHandler:)/title",
          "value": "deactivateWithOptions:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1deactivate(options:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deactivateWithOptions:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1unmount(replyHandler:)/title",
          "value": "unmountWithReplyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1unmount(replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unmountWithReplyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PreallocateOperations/title",
          "value": "FSVolumePreallocateOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PreallocateOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePreallocateOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PreallocateOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePreallocateOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1reclaimItem(_:replyHandler:)/title",
          "value": "reclaimItem:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1reclaimItem(_:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reclaimItem:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1createSymbolicLink(named:inDirectory:attributes:linkContents:replyHandler:)/title",
          "value": "createSymbolicLinkNamed:inDirectory:attributes:linkContents:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1createSymbolicLink(named:inDirectory:attributes:linkContents:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createSymbolicLinkNamed:inDirectory:attributes:linkContents:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1enumerateDirectory(_:startingAt:verifier:attributes:packer:replyHandler:)/title",
          "value": "enumerateDirectory:startingAtCookie:verifier:providingAttributes:usingPacker:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1enumerateDirectory(_:startingAt:verifier:attributes:packer:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateDirectory:startingAtCookie:verifier:providingAttributes:usingPacker:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1activate(options:replyHandler:)/title",
          "value": "activateWithOptions:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1activate(options:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activateWithOptions:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenCloseOperations/title",
          "value": "FSVolumeOpenCloseOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenCloseOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenCloseOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenCloseOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenCloseOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1setAttributes(_:on:replyHandler:)/title",
          "value": "setAttributes:onItem:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1setAttributes(_:on:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAttributes:onItem:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1createLink(to:named:inDirectory:replyHandler:)/title",
          "value": "createLinkToItem:named:inDirectory:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1createLink(to:named:inDirectory:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createLinkToItem:named:inDirectory:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations/title",
          "value": "FSVolumeOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/title",
          "value": "FSVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1removeItem(_:named:fromDirectory:replyHandler:)/title",
          "value": "removeItem:named:fromDirectory:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1removeItem(_:named:fromDirectory:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeItem:named:fromDirectory:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1XattrOperations/title",
          "value": "FSVolumeXattrOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1XattrOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeXattrOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1XattrOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeXattrOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessCheckOperations/title",
          "value": "FSVolumeAccessCheckOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessCheckOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeAccessCheckOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessCheckOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeAccessCheckOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations/title",
          "value": "FSVolumePathConfOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePathConfOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePathConfOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1getAttributes(_:of:replyHandler:)/title",
          "value": "getAttributes:ofItem:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1getAttributes(_:of:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getAttributes:ofItem:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolumeKernelOffloadedIOOperations/title",
          "value": "FSVolumeKernelOffloadedIOOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolumeKernelOffloadedIOOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeKernelOffloadedIOOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolumeKernelOffloadedIOOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeKernelOffloadedIOOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1volumeStatistics/title",
          "value": "volumeStatistics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1volumeStatistics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "volumeStatistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1supportedVolumeCapabilities/title",
          "value": "supportedVolumeCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1supportedVolumeCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedVolumeCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1synchronize(flags:replyHandler:)/title",
          "value": "synchronizeWithFlags:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1synchronize(flags:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "synchronizeWithFlags:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ReadWriteOperations/title",
          "value": "FSVolumeReadWriteOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ReadWriteOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeReadWriteOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ReadWriteOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeReadWriteOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1createItem(named:type:inDirectory:attributes:replyHandler:)/title",
          "value": "createItemNamed:type:inDirectory:attributes:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations~1createItem(named:type:inDirectory:attributes:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createItemNamed:type:inDirectory:attributes:replyHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsvolume/operations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsvolume/operations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
