{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSVolume"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "FSKit",
    "externalID": "c:objc(pl)FSVolumePathConfOperations",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PathConfOperations"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PathConfOperations"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FSVolume.PathConfOperations"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PathConfOperations"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSVolume": {
      "abstract": [
        {
          "text": "A directory structure for files and folders.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "role": "symbol",
      "title": "FSVolume",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessCheckOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessCheckOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessCheckOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessCheckOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.AccessCheckOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accesscheckoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/OpenCloseOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpenCloseOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/OpenCloseOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OpenCloseOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.OpenCloseOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/opencloseoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/Operations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Operations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/Operations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Operations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.Operations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/operations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PathConfOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PathConfOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.PathConfOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumFileSize": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumFileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumFileSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumFileSize"
        }
      ],
      "role": "symbol",
      "title": "maximumFileSize",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations/maximumfilesize"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumFileSizeInBits": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumFileSizeInBits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumFileSizeInBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumFileSizeInBits"
        }
      ],
      "role": "symbol",
      "title": "maximumFileSizeInBits",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations/maximumfilesizeinbits"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumLinkCount": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumLinkCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumLinkCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumLinkCount"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "maximumLinkCount",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations/maximumlinkcount"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumNameLength": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumNameLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumNameLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumNameLength"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "maximumNameLength",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations/maximumnamelength"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumXattrSize": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumXattrSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumXattrSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumXattrSize"
        }
      ],
      "role": "symbol",
      "title": "maximumXattrSize",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations/maximumxattrsize"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumXattrSizeInBits": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumXattrSizeInBits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumXattrSizeInBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumXattrSizeInBits"
        }
      ],
      "role": "symbol",
      "title": "maximumXattrSizeInBits",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations/maximumxattrsizeinbits"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/restrictsOwnershipChanges": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictsOwnershipChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/restrictsOwnershipChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "restrictsOwnershipChanges"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "restrictsOwnershipChanges",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations/restrictsownershipchanges"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/truncatesLongNames": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "truncatesLongNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/truncatesLongNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "truncatesLongNames"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "truncatesLongNames",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/pathconfoperations/truncateslongnames"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/PreallocateOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PreallocateOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/PreallocateOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PreallocateOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.PreallocateOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/preallocateoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ReadWriteOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadWriteOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ReadWriteOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadWriteOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ReadWriteOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/readwriteoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/RenameOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RenameOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/RenameOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RenameOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.RenameOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/renameoperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/XattrOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XattrOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/XattrOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XattrOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.XattrOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/xattroperations"
    },
    "doc://FSKit/documentation/FSKit/FSVolumeKernelOffloadedIOOperations": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSVolumeKernelOffloadedIOOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolumeKernelOffloadedIOOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolumeKernelOffloadedIOOperations"
        }
      ],
      "role": "symbol",
      "title": "FSVolumeKernelOffloadedIOOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsvolumekerneloffloadediooperations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/Operations"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Volume-operations",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/AccessCheckOperations",
        "doc://FSKit/documentation/FSKit/FSVolumeKernelOffloadedIOOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/OpenCloseOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/Operations",
        "doc://FSKit/documentation/FSKit/FSVolume/PreallocateOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/ReadWriteOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/RenameOperations",
        "doc://FSKit/documentation/FSKit/FSVolume/XattrOperations"
      ],
      "title": "Volume operations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumFileSize",
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumFileSizeInBits",
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumLinkCount",
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumNameLength",
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumXattrSize",
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumXattrSizeInBits",
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/restrictsOwnershipChanges",
        "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/truncatesLongNames"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSVolumePathConfOperations"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePathConfOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePathConfOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumFileSize",
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumFileSizeInBits",
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumLinkCount",
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumNameLength",
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumXattrSize",
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/maximumXattrSizeInBits",
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/restrictsOwnershipChanges",
                "doc://FSKit/documentation/FSKit/FSVolume/PathConfOperations/truncatesLongNames"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/Operations"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Volume-operations",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/AccessCheckOperations",
                "doc://FSKit/documentation/FSKit/FSVolumeKernelOffloadedIOOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/OpenCloseOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/Operations",
                "doc://FSKit/documentation/FSKit/FSVolume/PreallocateOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/ReadWriteOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/RenameOperations",
                "doc://FSKit/documentation/FSKit/FSVolume/XattrOperations"
              ],
              "title": "Volume operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSVolumePathConfOperations"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/title",
          "value": "FSVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumFileSize/title",
          "value": "maximumFileSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumFileSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumFileSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1RenameOperations/title",
          "value": "FSVolumeRenameOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1RenameOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeRenameOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1RenameOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeRenameOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1truncatesLongNames/title",
          "value": "truncatesLongNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1truncatesLongNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "truncatesLongNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumFileSizeInBits/title",
          "value": "maximumFileSizeInBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumFileSizeInBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumFileSizeInBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1XattrOperations/title",
          "value": "FSVolumeXattrOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1XattrOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeXattrOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1XattrOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeXattrOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumNameLength/title",
          "value": "maximumNameLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumNameLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumNameLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumXattrSize/title",
          "value": "maximumXattrSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumXattrSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumXattrSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessCheckOperations/title",
          "value": "FSVolumeAccessCheckOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessCheckOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeAccessCheckOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessCheckOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeAccessCheckOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PreallocateOperations/title",
          "value": "FSVolumePreallocateOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PreallocateOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePreallocateOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PreallocateOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePreallocateOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ReadWriteOperations/title",
          "value": "FSVolumeReadWriteOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ReadWriteOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeReadWriteOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ReadWriteOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeReadWriteOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumLinkCount/title",
          "value": "maximumLinkCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumLinkCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumLinkCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations/title",
          "value": "FSVolumePathConfOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePathConfOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumePathConfOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1restrictsOwnershipChanges/title",
          "value": "restrictsOwnershipChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1restrictsOwnershipChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "restrictsOwnershipChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations/title",
          "value": "FSVolumeOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1Operations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumXattrSizeInBits/title",
          "value": "maximumXattrSizeInBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1PathConfOperations~1maximumXattrSizeInBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumXattrSizeInBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolumeKernelOffloadedIOOperations/title",
          "value": "FSVolumeKernelOffloadedIOOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolumeKernelOffloadedIOOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeKernelOffloadedIOOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolumeKernelOffloadedIOOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeKernelOffloadedIOOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenCloseOperations/title",
          "value": "FSVolumeOpenCloseOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenCloseOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenCloseOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenCloseOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenCloseOperations"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsvolume/pathconfoperations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsvolume/pathconfoperations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
