{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSVolume"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "FSKit",
    "externalID": "c:objc(cs)FSVolumeSupportedCapabilities",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SupportedCapabilities"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SupportedCapabilities"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "FSVolume.SupportedCapabilities"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SupportedCapabilities"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSVolume": {
      "abstract": [
        {
          "text": "A directory structure for files and folders.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSVolume"
        }
      ],
      "role": "symbol",
      "title": "FSVolume",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CaseFormat"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CaseFormat"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.CaseFormat",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/caseformat"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ItemDeactivation"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ItemDeactivation"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ItemDeactivation",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivation"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ItemDeactivationOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ItemDeactivationOptions"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.ItemDeactivationOptions",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/itemdeactivationoptions"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/OpenModes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpenModes"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OpenModes"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.OpenModes",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/openmodes"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SupportedCapabilities"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SupportedCapabilities"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.SupportedCapabilities",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/caseFormat": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caseFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSVolumeCaseFormat",
          "text": "CaseFormat"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/caseFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "caseFormat"
        }
      ],
      "role": "symbol",
      "title": "caseFormat",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/caseformat"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportImmutableFiles": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doesNotSupportImmutableFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportImmutableFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doesNotSupportImmutableFiles"
        }
      ],
      "role": "symbol",
      "title": "doesNotSupportImmutableFiles",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/doesnotsupportimmutablefiles"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportRootTimes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doesNotSupportRootTimes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportRootTimes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doesNotSupportRootTimes"
        }
      ],
      "role": "symbol",
      "title": "doesNotSupportRootTimes",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/doesnotsupportroottimes"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportSettingFilePermissions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doesNotSupportSettingFilePermissions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportSettingFilePermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doesNotSupportSettingFilePermissions"
        }
      ],
      "role": "symbol",
      "title": "doesNotSupportSettingFilePermissions",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/doesnotsupportsettingfilepermissions"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportVolumeSizes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doesNotSupportVolumeSizes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportVolumeSizes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doesNotSupportVolumeSizes"
        }
      ],
      "role": "symbol",
      "title": "doesNotSupportVolumeSizes",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/doesnotsupportvolumesizes"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supports2TBFiles": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supports2TBFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supports2TBFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supports2TBFiles"
        }
      ],
      "role": "symbol",
      "title": "supports2TBFiles",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supports2tbfiles"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supports64BitObjectIDs": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supports64BitObjectIDs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supports64BitObjectIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supports64BitObjectIDs"
        }
      ],
      "role": "symbol",
      "title": "supports64BitObjectIDs",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supports64bitobjectids"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsActiveJournal": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsActiveJournal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsActiveJournal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsActiveJournal"
        }
      ],
      "role": "symbol",
      "title": "supportsActiveJournal",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportsactivejournal"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsDocumentID": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsDocumentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsDocumentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsDocumentID"
        }
      ],
      "role": "symbol",
      "title": "supportsDocumentID",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportsdocumentid"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsFastStatFS": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFastStatFS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsFastStatFS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFastStatFS"
        }
      ],
      "role": "symbol",
      "title": "supportsFastStatFS",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportsfaststatfs"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsHardLinks": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsHardLinks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsHardLinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsHardLinks"
        }
      ],
      "role": "symbol",
      "title": "supportsHardLinks",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportshardlinks"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsHiddenFiles": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsHiddenFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsHiddenFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsHiddenFiles"
        }
      ],
      "role": "symbol",
      "title": "supportsHiddenFiles",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportshiddenfiles"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsJournal": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsJournal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsJournal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsJournal"
        }
      ],
      "role": "symbol",
      "title": "supportsJournal",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportsjournal"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsOpenDenyModes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsOpenDenyModes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsOpenDenyModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsOpenDenyModes"
        }
      ],
      "role": "symbol",
      "title": "supportsOpenDenyModes",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportsopendenymodes"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsPersistentObjectIDs": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsPersistentObjectIDs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsPersistentObjectIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsPersistentObjectIDs"
        }
      ],
      "role": "symbol",
      "title": "supportsPersistentObjectIDs",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportspersistentobjectids"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSharedSpace": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsSharedSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSharedSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsSharedSpace"
        }
      ],
      "role": "symbol",
      "title": "supportsSharedSpace",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportssharedspace"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSparseFiles": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsSparseFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSparseFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsSparseFiles"
        }
      ],
      "role": "symbol",
      "title": "supportsSparseFiles",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportssparsefiles"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSymbolicLinks": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsSymbolicLinks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSymbolicLinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsSymbolicLinks"
        }
      ],
      "role": "symbol",
      "title": "supportsSymbolicLinks",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportssymboliclinks"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsVolumeGroups": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsVolumeGroups"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsVolumeGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsVolumeGroups"
        }
      ],
      "role": "symbol",
      "title": "supportsVolumeGroups",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportsvolumegroups"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsZeroRuns": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsZeroRuns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsZeroRuns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsZeroRuns"
        }
      ],
      "role": "symbol",
      "title": "supportsZeroRuns",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/supportedcapabilities/supportszeroruns"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-types",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat",
        "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
        "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions"
      ],
      "title": "Supporting types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/caseFormat",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportImmutableFiles",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportRootTimes",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportSettingFilePermissions",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportVolumeSizes",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supports2TBFiles",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supports64BitObjectIDs",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsActiveJournal",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsDocumentID",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsFastStatFS",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsHardLinks",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsHiddenFiles",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsJournal",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsOpenDenyModes",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsPersistentObjectIDs",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSharedSpace",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSparseFiles",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSymbolicLinks",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsVolumeGroups",
        "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsZeroRuns"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSVolumeSupportedCapabilities"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeSupportedCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeSupportedCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/caseFormat",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportImmutableFiles",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportRootTimes",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportSettingFilePermissions",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/doesNotSupportVolumeSizes",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supports2TBFiles",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supports64BitObjectIDs",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsActiveJournal",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsDocumentID",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsFastStatFS",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsHardLinks",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsHiddenFiles",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsJournal",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsOpenDenyModes",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsPersistentObjectIDs",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSharedSpace",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSparseFiles",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsSymbolicLinks",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsVolumeGroups",
                "doc://FSKit/documentation/FSKit/FSVolume/SupportedCapabilities/supportsZeroRuns"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-types",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/CaseFormat",
                "doc://FSKit/documentation/FSKit/FSVolume/OpenModes",
                "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivation",
                "doc://FSKit/documentation/FSKit/FSVolume/ItemDeactivationOptions"
              ],
              "title": "Supporting types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSVolumeSupportedCapabilities"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/title",
          "value": "FSVolumeCaseFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1CaseFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeCaseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsHardLinks/title",
          "value": "supportsHardLinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsHardLinks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsHardLinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/title",
          "value": "FSVolumeOpenModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1OpenModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeOpenModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsVolumeGroups/title",
          "value": "supportsVolumeGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsVolumeGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsVolumeGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/title",
          "value": "FSVolumeItemDeactivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeItemDeactivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeItemDeactivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsSharedSpace/title",
          "value": "supportsSharedSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsSharedSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsSharedSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsActiveJournal/title",
          "value": "supportsActiveJournal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsActiveJournal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsActiveJournal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsSparseFiles/title",
          "value": "supportsSparseFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsSparseFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsSparseFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supports64BitObjectIDs/title",
          "value": "supports64BitObjectIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supports64BitObjectIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supports64BitObjectIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsJournal/title",
          "value": "supportsJournal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsJournal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsJournal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1doesNotSupportSettingFilePermissions/title",
          "value": "doesNotSupportSettingFilePermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1doesNotSupportSettingFilePermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doesNotSupportSettingFilePermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsFastStatFS/title",
          "value": "supportsFastStatFS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsFastStatFS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsFastStatFS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1doesNotSupportRootTimes/title",
          "value": "doesNotSupportRootTimes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1doesNotSupportRootTimes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doesNotSupportRootTimes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsSymbolicLinks/title",
          "value": "supportsSymbolicLinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsSymbolicLinks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsSymbolicLinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1caseFormat/title",
          "value": "caseFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1caseFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "caseFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/title",
          "value": "FSItemDeactivationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1ItemDeactivationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemDeactivationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1doesNotSupportVolumeSizes/title",
          "value": "doesNotSupportVolumeSizes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1doesNotSupportVolumeSizes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doesNotSupportVolumeSizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsOpenDenyModes/title",
          "value": "supportsOpenDenyModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsOpenDenyModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsOpenDenyModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/title",
          "value": "FSVolumeSupportedCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeSupportedCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolumeSupportedCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsZeroRuns/title",
          "value": "supportsZeroRuns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsZeroRuns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsZeroRuns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsHiddenFiles/title",
          "value": "supportsHiddenFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsHiddenFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsHiddenFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsDocumentID/title",
          "value": "supportsDocumentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsDocumentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsDocumentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1doesNotSupportImmutableFiles/title",
          "value": "doesNotSupportImmutableFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1doesNotSupportImmutableFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doesNotSupportImmutableFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supports2TBFiles/title",
          "value": "supports2TBFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supports2TBFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supports2TBFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsPersistentObjectIDs/title",
          "value": "supportsPersistentObjectIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1SupportedCapabilities~1supportsPersistentObjectIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsPersistentObjectIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/title",
          "value": "FSVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSVolume"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsvolume/supportedcapabilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsvolume/supportedcapabilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
