{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor"]]},"metadata":{"title":"init(predicate:options:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"predicate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9HealthKit17HKSamplePredicateV","text":"HKSamplePredicate","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"HKQuantitySample","preciseIdentifier":"c:objc(cs)HKQuantitySample"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HKStatisticsOptions","preciseIdentifier":"c:@E@HKStatisticsOptions"},{"kind":"text","text":")"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.4","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.4","name":"iPadOS"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"15.4"},{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"13.0"},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false},{"beta":false,"name":"watchOS","deprecated":false,"unavailable":false,"introducedAt":"8.5"}],"role":"symbol","symbolKind":"init","modules":[{"name":"HealthKit"}],"externalID":"s:9HealthKit27HKStatisticsQueryDescriptorV9predicate7optionsAcA17HKSamplePredicateVySo16HKQuantitySampleCG_So0C7OptionsVtcfc","roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkstatisticsquerydescriptor/init(predicate:options:)"]}],"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor/init(predicate:options:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"predicate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKSamplePredicate","kind":"typeIdentifier","preciseIdentifier":"s:9HealthKit17HKSamplePredicateV","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate"},{"text":"<","kind":"text"},{"text":"HKQuantitySample","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantitySample","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample"},{"text":">, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKStatisticsOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@HKStatisticsOptions","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A predicate that defines the set of data that the query uses to calculate the statistics."}],"type":"paragraph"}],"name":"predicate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of options that define the type of statistical calculations performed and the way in which HealthKit merges data from multiple sources. For a list of valid options, see "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions"},{"type":"text","text":"."}]}],"name":"options"}]}],"sections":[],"abstract":[{"text":"Creates a statistics query descriptor.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKStatisticsOptions"}],"type":"topic","title":"HKStatisticsOptions","navigatorTitle":[{"kind":"identifier","text":"HKStatisticsOptions"}],"kind":"symbol","abstract":[{"type":"text","text":"Options for specifying the statistic to calculate."}],"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsOptions","url":"/documentation/healthkit/hkstatisticsoptions"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKSamplePredicate"}],"title":"HKSamplePredicate","navigatorTitle":[{"kind":"identifier","text":"HKSamplePredicate"}],"kind":"symbol","abstract":[{"text":"A predicate for queries that return a collection of matching sample objects.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKSamplePredicate","role":"symbol","url":"/documentation/healthkit/hksamplepredicate"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor/init(predicate:options:)":{"url":"/documentation/healthkit/hkstatisticsquerydescriptor/init(predicate:options:)","type":"topic","title":"init(predicate:options:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor/init(predicate:options:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"predicate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9HealthKit17HKSamplePredicateV","text":"HKSamplePredicate","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKQuantitySample","text":"HKQuantitySample","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@HKStatisticsOptions","text":"HKStatisticsOptions","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates a statistics query descriptor."}],"role":"symbol","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor":{"title":"HKStatisticsQueryDescriptor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"HKStatisticsQueryDescriptor","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKStatisticsQueryDescriptor","type":"topic","abstract":[{"type":"text","text":"A query descriptor that calculates the minimum, maximum, average, or sum over a set of samples from the HealthKit store."}],"url":"/documentation/healthkit/hkstatisticsquerydescriptor","role":"symbol","navigatorTitle":[{"text":"HKStatisticsQueryDescriptor","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKQuantitySample","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySample","url":"/documentation/healthkit/hkquantitysample","title":"HKQuantitySample","kind":"symbol","abstract":[{"type":"text","text":"A sample that represents a quantity, including the value and the units."}],"role":"symbol","navigatorTitle":[{"text":"HKQuantitySample","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/title","value":"HKStatisticsOptions"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/fragments","value":[{"kind":"identifier","text":"HKStatisticsOptions"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStatisticsOptions/navigatorTitle","value":[{"text":"HKStatisticsOptions","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/title","value":"HKQuantitySample"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/fragments","value":[{"kind":"identifier","text":"HKQuantitySample"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantitySample/navigatorTitle","value":[{"kind":"identifier","text":"HKQuantitySample"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}