{
  "abstract": [
    {
      "text": "Removes the specified assets from the project.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/removeAssets:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHProjectChangeRequest(im)removeAssets:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "removeAssets:"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "removeAssets:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "removeAssets:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "removeAssets:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)NSFastEnumeration",
              "text": "id<NSFastEnumeration>"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "assets"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A collection of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": "s to be removed from the project.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "assets"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest": {
      "abstract": [
        {
          "text": "A request to change asset data in a Photos project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHProjectChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phprojectchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/removeAssets:": {
      "abstract": [
        {
          "text": "Removes the specified assets from the project.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAssets:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/removeAssets:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAssets:"
        }
      ],
      "role": "symbol",
      "title": "removeAssets:",
      "type": "topic",
      "url": "/documentation/photos/phprojectchangerequest/removeassets:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/title",
          "value": "PHProjectChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phprojectchangerequest/removeassets:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
