{
  "abstract": [
    {
      "text": "Updates the project preview in Photos.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/setProjectPreviewImage(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHProjectChangeRequest(im)setProjectPreviewImage:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setProjectPreviewImage"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSImage",
        "text": "NSImage"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setProjectPreviewImage:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setProjectPreviewImage(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setProjectPreviewImage"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "previewImage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSImage",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A rendered project preview with dimensions of 1024 x 1024.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "previewImage"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "PhotoKit requires that you set a project preview in the following situations:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Whenever the project changes in a way that requires a new preview.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "During or after execution of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController/beginProject(with:projectInfo:completion:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "During or after execution of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController/resumeProject(with:completion:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest": {
      "abstract": [
        {
          "text": "A request to change asset data in a Photos project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHProjectChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phprojectchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/setKeyAsset(_:)": {
      "abstract": [
        {
          "text": "Sets the key asset representing the project.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKeyAsset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/setKeyAsset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKeyAsset:"
        }
      ],
      "role": "symbol",
      "title": "setKeyAsset(_:)",
      "type": "topic",
      "url": "/documentation/photos/phprojectchangerequest/setkeyasset(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/setProjectPreviewImage(_:)": {
      "abstract": [
        {
          "text": "Updates the project preview in Photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setProjectPreviewImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/setProjectPreviewImage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setProjectPreviewImage:"
        }
      ],
      "role": "symbol",
      "title": "setProjectPreviewImage(_:)",
      "type": "topic",
      "url": "/documentation/photos/phprojectchangerequest/setprojectpreviewimage(_:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController/beginProject(with:projectInfo:completion:)": {
      "abstract": [
        {
          "text": "Provides an opportunity to customize the initial state when the user creates a project using the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginProject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectExtensionContext",
          "text": "PHProjectExtensionContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "projectInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectInfo",
          "text": "PHProjectInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController/beginProject(with:projectInfo:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginProjectWithExtensionContext:projectInfo:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "beginProject(with:projectInfo:completion:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontroller/beginproject(with:projectinfo:completion:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController/resumeProject(with:completion:)": {
      "abstract": [
        {
          "text": "Provides an opportunity to restore or refresh the user interface when the user returns to a previously created project.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeProject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectExtensionContext",
          "text": "PHProjectExtensionContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectExtensionController/resumeProject(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeProjectWithExtensionContext:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "resumeProject(with:completion:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojectextensioncontroller/resumeproject(with:completion:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/AppKit/NSImage"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/UIKit/UIImage"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Change-Requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/setKeyAsset(_:)"
      ],
      "title": "Responding to Change Requests"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setProjectPreviewImage:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setProjectPreviewImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Change-Requests",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHProjectChangeRequest/setKeyAsset(_:)"
              ],
              "title": "Responding to Change Requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setProjectPreviewImage:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSImage",
                    "text": "NSImage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "previewImage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setProjectPreviewImage:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIImage",
                    "text": "UIImage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "previewImage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A rendered project preview with dimensions of 1024 x 1024.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "previewImage"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/title",
          "value": "PHProjectChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController~1resumeProject(with:completion:)/title",
          "value": "resumeProjectWithExtensionContext:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController~1resumeProject(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resumeProjectWithExtensionContext:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController~1beginProject(with:projectInfo:completion:)/title",
          "value": "beginProjectWithExtensionContext:projectInfo:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectExtensionController~1beginProject(with:projectInfo:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginProjectWithExtensionContext:projectInfo:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest~1setKeyAsset(_:)/title",
          "value": "setKeyAsset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest~1setKeyAsset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKeyAsset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest~1setProjectPreviewImage(_:)/title",
          "value": "setProjectPreviewImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHProjectChangeRequest~1setProjectPreviewImage(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setProjectPreviewImage:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phprojectchangerequest/setprojectpreviewimage(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phprojectchangerequest/setprojectpreviewimage(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
