{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether there is a valid forward item in the back-forward list.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebView/canGoForward"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKWebView(py)canGoForward",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "canGoForward"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "canGoForward"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "canGoForward"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "canGoForward"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/allowsBackForwardNavigationGestures": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether horizontal swipe gestures trigger backward and forward page navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsBackForwardNavigationGestures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/allowsBackForwardNavigationGestures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsBackForwardNavigationGestures"
        }
      ],
      "role": "symbol",
      "title": "allowsBackForwardNavigationGestures",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/allowsbackforwardnavigationgestures"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/allowsLinkPreview": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether pressing a link displays a preview of the destination for the link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsLinkPreview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/allowsLinkPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsLinkPreview"
        }
      ],
      "role": "symbol",
      "title": "allowsLinkPreview",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/allowslinkpreview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/backForwardList": {
      "abstract": [
        {
          "text": "The web view’s back-forward list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backForwardList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKBackForwardList",
          "text": "WKBackForwardList"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/backForwardList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backForwardList"
        }
      ],
      "role": "symbol",
      "title": "backForwardList",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/backforwardlist"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/canGoBack": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether there is a valid back item in the back-forward list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canGoBack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/canGoBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canGoBack"
        }
      ],
      "role": "symbol",
      "title": "canGoBack",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/cangoback"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/canGoForward": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether there is a valid forward item in the back-forward list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canGoForward"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/canGoForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canGoForward"
        }
      ],
      "role": "symbol",
      "title": "canGoForward",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/cangoforward"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/go(to:)": {
      "abstract": [
        {
          "text": "Navigates to an item from the back-forward list and sets it as the current item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "go"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKBackForwardListItem",
          "text": "WKBackForwardListItem"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKNavigation",
          "text": "WKNavigation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/go(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goToBackForwardListItem:"
        }
      ],
      "role": "symbol",
      "title": "go(to:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/go(to:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/goBack()": {
      "abstract": [
        {
          "text": "Navigates to the back item in the back-forward list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goBack"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKNavigation",
          "text": "WKNavigation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/goBack()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goBack"
        }
      ],
      "role": "symbol",
      "title": "goBack()",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/goback()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/goBack(_:)": {
      "abstract": [
        {
          "text": "Navigates to the back item in the back-forward list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goBack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/goBack(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goBack:"
        }
      ],
      "role": "symbol",
      "title": "goBack(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/goback(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/goForward()": {
      "abstract": [
        {
          "text": "Navigates to the forward item in the back-forward list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goForward"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKNavigation",
          "text": "WKNavigation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/goForward()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goForward"
        }
      ],
      "role": "symbol",
      "title": "goForward()",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/goforward()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/goForward(_:)": {
      "abstract": [
        {
          "text": "Navigates to the forward item in the back-forward list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goForward"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/goForward(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goForward:"
        }
      ],
      "role": "symbol",
      "title": "goForward(_:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/goforward(_:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/interactionState": {
      "abstract": [
        {
          "text": "An object you use to capture the current state of interaction in a web view so that you can restore that state later to another web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactionState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/interactionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interactionState"
        }
      ],
      "role": "symbol",
      "title": "interactionState",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/interactionstate"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigating-between-webpages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/allowsBackForwardNavigationGestures",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/backForwardList",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/goBack(_:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/goBack()",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/goForward(_:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/goForward()",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/go(to:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/canGoBack",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/allowsLinkPreview",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/interactionState"
      ],
      "title": "Navigating between webpages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "canGoForward"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigating-between-webpages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/allowsBackForwardNavigationGestures",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/backForwardList",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/goBack(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/goBack()",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/goForward(_:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/goForward()",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/go(to:)",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/canGoBack",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/allowsLinkPreview",
                "doc://com.apple.webkit/documentation/WebKit/WKWebView/interactionState"
              ],
              "title": "Navigating between webpages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "canGoForward"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1goBack(_:)/title",
          "value": "goBack:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1goBack(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goBack:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1backForwardList/title",
          "value": "backForwardList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1backForwardList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backForwardList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1canGoBack/title",
          "value": "canGoBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1canGoBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1allowsBackForwardNavigationGestures/title",
          "value": "allowsBackForwardNavigationGestures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1allowsBackForwardNavigationGestures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsBackForwardNavigationGestures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/title",
          "value": "WKWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1canGoForward/title",
          "value": "canGoForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1canGoForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canGoForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1goForward(_:)/title",
          "value": "goForward:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1goForward(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goForward:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1go(to:)/title",
          "value": "goToBackForwardListItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1go(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goToBackForwardListItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1allowsLinkPreview/title",
          "value": "allowsLinkPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1allowsLinkPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsLinkPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1interactionState/title",
          "value": "interactionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1interactionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interactionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1goBack()/title",
          "value": "goBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1goBack()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1goForward()/title",
          "value": "goForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1goForward()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "goForward"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebview/cangoforward"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebview/cangoforward"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
