{
  "abstract": [
    {
      "text": "Changes whether the webpage is suspending playback of all media in the page.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebView/suspendAllMediaPlayback:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKWebView(im)suspendAllMediaPlayback:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "suspendAllMediaPlayback:"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "suspendAllMediaPlayback:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "14.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "suspendAllMediaPlayback:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "suspendAllMediaPlayback:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:BFv()",
              "text": "void (^)(void)"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Pass ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " to pause all media the web view is playing. Neither the user or web page can resume playback until you call this method again with ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState": {
      "abstract": [
        {
          "text": "An enumeration that describes whether an audio or video presentation is playing, paused, or suspended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackState"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackState"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations(completionHandler:)": {
      "abstract": [
        {
          "text": "Closes all media the web view is presenting, including picture-in-picture video and fullscreen video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closeAllMediaPresentations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "closeAllMediaPresentationsWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "closeAllMediaPresentations(completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/closeallmediapresentations(completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback(completionHandler:)": {
      "abstract": [
        {
          "text": "Pauses playback of all media in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseAllMediaPlayback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseAllMediaPlaybackWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "pauseAllMediaPlayback(completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/pauseallmediaplayback(completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback:": {
      "abstract": [
        {
          "text": "Pauses playback of all media in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "pauseAllMediaPlayback:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseAllMediaPlayback:"
        }
      ],
      "role": "symbol",
      "title": "pauseAllMediaPlayback:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/pauseallmediaplayback:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState(completionHandler:)": {
      "abstract": [
        {
          "text": "Requests the playback status of media in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestMediaPlaybackState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKMediaPlaybackState",
          "text": "WKMediaPlaybackState"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestMediaPlaybackStateWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestMediaPlaybackState(completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/requestmediaplaybackstate(completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState:": {
      "abstract": [
        {
          "text": "Requests the playback status of media in the web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "requestMediaPlaybackState:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestMediaPlaybackState:"
        }
      ],
      "role": "symbol",
      "title": "requestMediaPlaybackState:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/requestmediaplaybackstate:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/resumeAllMediaPlayback:": {
      "abstract": [
        {
          "text": "Resumes playback of all media in a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "resumeAllMediaPlayback:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/resumeAllMediaPlayback:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeAllMediaPlayback:"
        }
      ],
      "role": "symbol",
      "title": "resumeAllMediaPlayback:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/resumeallmediaplayback:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/setAllMediaPlaybackSuspended(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Changes whether the webpage is suspending playback of all media in the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAllMediaPlaybackSuspended"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/setAllMediaPlaybackSuspended(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAllMediaPlaybackSuspended:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "setAllMediaPlaybackSuspended(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/setallmediaplaybacksuspended(_:completionhandler:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView/suspendAllMediaPlayback:": {
      "abstract": [
        {
          "text": "Changes whether the webpage is suspending playback of all media in the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "suspendAllMediaPlayback:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView/suspendAllMediaPlayback:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suspendAllMediaPlayback:"
        }
      ],
      "role": "symbol",
      "title": "suspendAllMediaPlayback:",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview/suspendallmediaplayback:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interacting-with-media",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback(completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/pauseAllMediaPlayback:",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState(completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/requestMediaPlaybackState:",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/setAllMediaPlaybackSuspended(_:completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/resumeAllMediaPlayback:",
        "doc://com.apple.webkit/documentation/WebKit/WKWebView/closeAllMediaPresentations(completionHandler:)",
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState"
      ],
      "title": "Interacting with media"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/title",
          "value": "WKWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/title",
          "value": "WKMediaPlaybackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1requestMediaPlaybackState(completionHandler:)/title",
          "value": "requestMediaPlaybackStateWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1requestMediaPlaybackState(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestMediaPlaybackStateWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1setAllMediaPlaybackSuspended(_:completionHandler:)/title",
          "value": "setAllMediaPlaybackSuspended:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1setAllMediaPlaybackSuspended(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAllMediaPlaybackSuspended:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1pauseAllMediaPlayback(completionHandler:)/title",
          "value": "pauseAllMediaPlaybackWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1pauseAllMediaPlayback(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pauseAllMediaPlaybackWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1closeAllMediaPresentations(completionHandler:)/title",
          "value": "closeAllMediaPresentationsWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView~1closeAllMediaPresentations(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "closeAllMediaPresentationsWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebview/suspendallmediaplayback:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
