{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageRetrievalFailed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INIntentErrorCode@INIntentErrorImageRetrievalFailed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "imageRetrievalFailed"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INIntentErrorImageRetrievalFailed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INIntentError.Code.imageRetrievalFailed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imageRetrievalFailed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError": {
      "abstract": [
        {
          "text": "Errors returned by SiriKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentError"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentError"
        }
      ],
      "role": "symbol",
      "title": "INIntentError",
      "type": "topic",
      "url": "/documentation/intents/inintenterror"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code": {
      "abstract": [
        {
          "text": "Constants for error codes returned by the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageGeneric"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageGeneric"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageGeneric",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imagegeneric"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageLoadingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageLoadingFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageLoadingFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageLoadingFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageLoadingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageloadingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageNoServiceAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageNoServiceAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageNoServiceAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageNoServiceAvailable"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageNoServiceAvailable",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imagenoserviceavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyInvalid"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageProxyInvalid"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageProxyInvalid",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageproxyinvalid"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyLoop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyLoop"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyLoop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageProxyLoop"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageProxyLoop",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageproxyloop"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyTimeout"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageProxyTimeout"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageProxyTimeout",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageproxytimeout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageRetrievalFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageRetrievalFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageRetrievalFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageRetrievalFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageRetrievalFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageretrievalfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageScalingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageScalingFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageScalingFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageScalingFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageScalingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imagescalingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageServiceFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageServiceFailure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageServiceFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageServiceFailure"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageServiceFailure",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imageservicefailure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageStorageFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageStorageFailed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageStorageFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorImageStorageFailed"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.imageStorageFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/imagestoragefailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/permissionDenied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/permissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorPermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code.permissionDenied",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code/permissiondenied"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageGeneric",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageLoadingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageNoServiceAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageServiceFailure",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyInvalid",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyLoop",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyTimeout",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageStorageFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageScalingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/permissionDenied"
      ],
      "title": "Image Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INIntentErrorImageRetrievalFailed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageRetrievalFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageGeneric",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageLoadingFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageNoServiceAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageServiceFailure",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyInvalid",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyLoop",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageProxyTimeout",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageStorageFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/imageScalingFailed",
                "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code/permissionDenied"
              ],
              "title": "Image Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INIntentErrorImageRetrievalFailed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageScalingFailed/title",
          "value": "INIntentErrorImageScalingFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageScalingFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageScalingFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageGeneric/title",
          "value": "INIntentErrorImageGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyLoop/title",
          "value": "INIntentErrorImageProxyLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyLoop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageProxyLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyTimeout/title",
          "value": "INIntentErrorImageProxyTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageProxyTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageLoadingFailed/title",
          "value": "INIntentErrorImageLoadingFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageLoadingFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageLoadingFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/title",
          "value": "INIntentErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageRetrievalFailed/title",
          "value": "INIntentErrorImageRetrievalFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageRetrievalFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageRetrievalFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageServiceFailure/title",
          "value": "INIntentErrorImageServiceFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageServiceFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageServiceFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageNoServiceAvailable/title",
          "value": "INIntentErrorImageNoServiceAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageNoServiceAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageNoServiceAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageStorageFailed/title",
          "value": "INIntentErrorImageStorageFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageStorageFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageStorageFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1permissionDenied/title",
          "value": "INIntentErrorPermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1permissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorPermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyInvalid/title",
          "value": "INIntentErrorImageProxyInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code~1imageProxyInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorImageProxyInvalid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inintenterror/code/imageretrievalfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inintenterror/code/imageretrievalfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
