{
  "abstract": [
    {
      "text": "The unique identifier string for the Khmer script.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/khmer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "NaturalLanguage",
    "externalID": "c:@NLScriptKhmer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "khmer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NLScript",
        "text": "NLScript"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NLScriptKhmer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "khmer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "khmer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLScript",
              "text": "NLScript"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript": {
      "abstract": [
        {
          "text": "The writing scripts that the Natural Language framework supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScript"
        }
      ],
      "role": "symbol",
      "title": "NLScript",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/arabic": {
      "abstract": [
        {
          "text": "The unique identifier string for the Arabic script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arabic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/arabic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptArabic"
        }
      ],
      "role": "symbol",
      "title": "arabic",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/arabic"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/armenian": {
      "abstract": [
        {
          "text": "The unique identifier string for the Armenian script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "armenian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/armenian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptArmenian"
        }
      ],
      "role": "symbol",
      "title": "armenian",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/armenian"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/bengali": {
      "abstract": [
        {
          "text": "The unique identifier string for the Bengali script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bengali"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/bengali",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptBengali"
        }
      ],
      "role": "symbol",
      "title": "bengali",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/bengali"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/canadianAboriginalSyllabics": {
      "abstract": [
        {
          "text": "The unique identifier string for the Canadian Aboriginal Syllabics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canadianAboriginalSyllabics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/canadianAboriginalSyllabics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptCanadianAboriginalSyllabics"
        }
      ],
      "role": "symbol",
      "title": "canadianAboriginalSyllabics",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/canadianaboriginalsyllabics"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cherokee": {
      "abstract": [
        {
          "text": "The unique identifier string for the Cherokee script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cherokee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cherokee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptCherokee"
        }
      ],
      "role": "symbol",
      "title": "cherokee",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/cherokee"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cyrillic": {
      "abstract": [
        {
          "text": "The unique identifier string for the Cyrillic script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cyrillic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cyrillic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptCyrillic"
        }
      ],
      "role": "symbol",
      "title": "cyrillic",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/cyrillic"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/devanagari": {
      "abstract": [
        {
          "text": "The unique identifier string for the Devanagari script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devanagari"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/devanagari",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptDevanagari"
        }
      ],
      "role": "symbol",
      "title": "devanagari",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/devanagari"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/ethiopic": {
      "abstract": [
        {
          "text": "The unique identifier string for the Ethiopic script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ethiopic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/ethiopic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptEthiopic"
        }
      ],
      "role": "symbol",
      "title": "ethiopic",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/ethiopic"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/georgian": {
      "abstract": [
        {
          "text": "The unique identifier string for the Georgian script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "georgian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/georgian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptGeorgian"
        }
      ],
      "role": "symbol",
      "title": "georgian",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/georgian"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/greek": {
      "abstract": [
        {
          "text": "The unique identifier string for the Greek script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greek"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/greek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptGreek"
        }
      ],
      "role": "symbol",
      "title": "greek",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/greek"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gujarati": {
      "abstract": [
        {
          "text": "The unique identifier string for the Gujarati script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gujarati"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gujarati",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptGujarati"
        }
      ],
      "role": "symbol",
      "title": "gujarati",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/gujarati"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gurmukhi": {
      "abstract": [
        {
          "text": "The unique identifier string for the Gurmukhi script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gurmukhi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gurmukhi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptGurmukhi"
        }
      ],
      "role": "symbol",
      "title": "gurmukhi",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/gurmukhi"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/hebrew": {
      "abstract": [
        {
          "text": "The unique identifier string for the Hebrew script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hebrew"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/hebrew",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptHebrew"
        }
      ],
      "role": "symbol",
      "title": "hebrew",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/hebrew"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/japanese": {
      "abstract": [
        {
          "text": "The unique identifier string for the Japanese script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "japanese"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/japanese",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptJapanese"
        }
      ],
      "role": "symbol",
      "title": "japanese",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/japanese"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/kannada": {
      "abstract": [
        {
          "text": "The unique identifier string for the Kannada script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kannada"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/kannada",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptKannada"
        }
      ],
      "role": "symbol",
      "title": "kannada",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/kannada"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/khmer": {
      "abstract": [
        {
          "text": "The unique identifier string for the Khmer script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "khmer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/khmer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptKhmer"
        }
      ],
      "role": "symbol",
      "title": "khmer",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/khmer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-standard-scripts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/arabic",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/armenian",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/bengali",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/canadianAboriginalSyllabics",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cherokee",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cyrillic",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/devanagari",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/ethiopic",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/georgian",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/greek",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gujarati",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gurmukhi",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/hebrew",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/japanese",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/kannada"
      ],
      "title": "Getting standard scripts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NLScriptKhmer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptKhmer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-standard-scripts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/arabic",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/armenian",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/bengali",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/canadianAboriginalSyllabics",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cherokee",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cyrillic",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/devanagari",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/ethiopic",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/georgian",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/greek",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gujarati",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gurmukhi",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/hebrew",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/japanese",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/kannada"
              ],
              "title": "Getting standard scripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NLScript",
                    "text": "NLScript"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NLScriptKhmer"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1ethiopic/title",
          "value": "NLScriptEthiopic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1ethiopic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptEthiopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1arabic/title",
          "value": "NLScriptArabic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1arabic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptArabic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1cyrillic/title",
          "value": "NLScriptCyrillic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1cyrillic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptCyrillic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1gujarati/title",
          "value": "NLScriptGujarati"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1gujarati/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptGujarati"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1armenian/title",
          "value": "NLScriptArmenian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1armenian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptArmenian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1hebrew/title",
          "value": "NLScriptHebrew"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1hebrew/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptHebrew"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1kannada/title",
          "value": "NLScriptKannada"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1kannada/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptKannada"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1japanese/title",
          "value": "NLScriptJapanese"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1japanese/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptJapanese"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1georgian/title",
          "value": "NLScriptGeorgian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1georgian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptGeorgian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1devanagari/title",
          "value": "NLScriptDevanagari"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1devanagari/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptDevanagari"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1khmer/title",
          "value": "NLScriptKhmer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1khmer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptKhmer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1canadianAboriginalSyllabics/title",
          "value": "NLScriptCanadianAboriginalSyllabics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1canadianAboriginalSyllabics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptCanadianAboriginalSyllabics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1cherokee/title",
          "value": "NLScriptCherokee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1cherokee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptCherokee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1bengali/title",
          "value": "NLScriptBengali"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1bengali/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptBengali"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1greek/title",
          "value": "NLScriptGreek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1greek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptGreek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1gurmukhi/title",
          "value": "NLScriptGurmukhi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1gurmukhi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptGurmukhi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/title",
          "value": "NLScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nlscript/khmer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage/nlscript/khmer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
