{
  "abstract": [
    {
      "text": "The media item contains an iTunes U video.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/videoITunesU"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPMediaType@MPMediaTypeVideoITunesU",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "videoITunesU"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MPMediaType",
        "text": "MPMediaType"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMediaTypeVideoITunesU"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "videoITunesU"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "videoITunesU"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MPMediaType",
              "text": "MPMediaType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType": {
      "abstract": [
        {
          "text": "The properties for defining the type for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaType"
        }
      ],
      "role": "symbol",
      "title": "MPMediaType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/any": {
      "abstract": [
        {
          "text": "The media item contains an unspecified type of media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeAny"
        }
      ],
      "role": "symbol",
      "title": "any",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/any"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/anyAudio": {
      "abstract": [
        {
          "text": "The media item contains an unspecified type of audio content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anyAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/anyAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeAnyAudio"
        }
      ],
      "role": "symbol",
      "title": "anyAudio",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/anyaudio"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/anyVideo": {
      "abstract": [
        {
          "text": "The media item contains an unspecified type of video content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anyVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/anyVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeAnyVideo"
        }
      ],
      "role": "symbol",
      "title": "anyVideo",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/anyvideo"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/audioBook": {
      "abstract": [
        {
          "text": "The media item contains an audio book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioBook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/audioBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeAudioBook"
        }
      ],
      "role": "symbol",
      "title": "audioBook",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/audiobook"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/audioITunesU": {
      "abstract": [
        {
          "text": "The media item contains an iTunes U audio lesson.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioITunesU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/audioITunesU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeAudioITunesU"
        }
      ],
      "role": "symbol",
      "title": "audioITunesU",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/audioitunesu"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/homeVideo": {
      "abstract": [
        {
          "text": "The media item contains a home video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/homeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeHomeVideo"
        }
      ],
      "role": "symbol",
      "title": "homeVideo",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/homevideo"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/movie": {
      "abstract": [
        {
          "text": "The media item contains a movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/movie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeMovie"
        }
      ],
      "role": "symbol",
      "title": "movie",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/movie"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/music": {
      "abstract": [
        {
          "text": "The media item contains music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "music"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/music",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeMusic"
        }
      ],
      "role": "symbol",
      "title": "music",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/music"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/musicVideo": {
      "abstract": [
        {
          "text": "The media item contains a music video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/musicVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeMusicVideo"
        }
      ],
      "role": "symbol",
      "title": "musicVideo",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/musicvideo"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/podcast": {
      "abstract": [
        {
          "text": "The media item contains a podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "podcast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/podcast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypePodcast"
        }
      ],
      "role": "symbol",
      "title": "podcast",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/podcast"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/tvShow": {
      "abstract": [
        {
          "text": "The media item contains a TV show.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvShow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/tvShow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeTVShow"
        }
      ],
      "role": "symbol",
      "title": "tvShow",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/tvshow"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/videoITunesU": {
      "abstract": [
        {
          "text": "The media item contains an iTunes U video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoITunesU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/videoITunesU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeVideoITunesU"
        }
      ],
      "role": "symbol",
      "title": "videoITunesU",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/videoitunesu"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/videoPodcast": {
      "abstract": [
        {
          "text": "The media item contains a video podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoPodcast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMediaType",
          "text": "MPMediaType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/videoPodcast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaTypeVideoPodcast"
        }
      ],
      "role": "symbol",
      "title": "videoPodcast",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediatype/videopodcast"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/music",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/podcast",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/audioBook",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/audioITunesU",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/anyAudio",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/movie",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/tvShow",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/videoPodcast",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/musicVideo",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/homeVideo",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/anyVideo",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/any"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPMediaTypeVideoITunesU"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeVideoITunesU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/music",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/podcast",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/audioBook",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/audioITunesU",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/anyAudio",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/movie",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/tvShow",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/videoPodcast",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/musicVideo",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/homeVideo",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/anyVideo",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaType/any"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MPMediaTypeVideoITunesU"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1videoITunesU/title",
          "value": "MPMediaTypeVideoITunesU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1videoITunesU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeVideoITunesU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1podcast/title",
          "value": "MPMediaTypePodcast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1podcast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypePodcast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1homeVideo/title",
          "value": "MPMediaTypeHomeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1homeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeHomeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1anyAudio/title",
          "value": "MPMediaTypeAnyAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1anyAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeAnyAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1any/title",
          "value": "MPMediaTypeAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1videoPodcast/title",
          "value": "MPMediaTypeVideoPodcast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1videoPodcast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeVideoPodcast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1audioITunesU/title",
          "value": "MPMediaTypeAudioITunesU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1audioITunesU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeAudioITunesU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1musicVideo/title",
          "value": "MPMediaTypeMusicVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1musicVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeMusicVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1anyVideo/title",
          "value": "MPMediaTypeAnyVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1anyVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeAnyVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/title",
          "value": "MPMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1audioBook/title",
          "value": "MPMediaTypeAudioBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1audioBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeAudioBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1music/title",
          "value": "MPMediaTypeMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1music/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1tvShow/title",
          "value": "MPMediaTypeTVShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1tvShow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeTVShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1movie/title",
          "value": "MPMediaTypeMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaType~1movie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaTypeMovie"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmediatype/videoitunesu"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmediatype/videoitunesu"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
