{
  "abstract": [
    {
      "text": "The URL of the link that launched the App Clip.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appclip/documentation/AppClip",
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayload"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appclip/documentation/AppClip/APActivationPayload/url"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)APActivationPayload(py)URL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "url"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "App Clips"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "URL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "url"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "url"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "code": "url",
              "type": "codeVoice"
            },
            {
              "text": " to retrieve data that’s passed to an App Clip on launch, and use the data to update the user interface of the App Clip.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value of ",
              "type": "text"
            },
            {
              "code": "url",
              "type": "codeVoice"
            },
            {
              "text": " is the same as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity/1418086-webpageurl",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. If you don’t need to verify the user’s location when they launch your App Clip, use ",
              "type": "text"
            },
            {
              "code": "webpageURL",
              "type": "codeVoice"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appclip/documentation/AppClip/responding-to-invocations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appclip/documentation/AppClip": {
      "abstract": [
        {
          "text": "Provide people a shortcut to selected content and features of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip",
      "kind": "symbol",
      "role": "collection",
      "title": "App Clips",
      "type": "topic",
      "url": "/documentation/appclip"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayload": {
      "abstract": [
        {
          "text": "Information that’s passed to an App Clip on launch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "APActivationPayload"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APActivationPayload"
        }
      ],
      "role": "symbol",
      "title": "APActivationPayload",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayload"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayload/url": {
      "abstract": [
        {
          "text": "The URL of the link that launched the App Clip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayload/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayload/url"
    },
    "doc://com.apple.appclip/documentation/AppClip/responding-to-invocations": {
      "abstract": [
        {
          "text": "Add code to respond to invocations and offer a focused launch experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/responding-to-invocations",
      "kind": "article",
      "role": "article",
      "title": "Responding to invocations",
      "type": "topic",
      "url": "/documentation/appclip/responding-to-invocations"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity": {
      "abstract": [
        {
          "text": "A representation of the state of your app at a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivity",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity/1418086-webpageurl": {
      "abstract": [
        {
          "text": "The URL of the webpage to load in a browser to continue the activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "webpageURL"
        },
        {
          "kind": "text",
          "text": ": URL?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity/1418086-webpageurl",
      "kind": "symbol",
      "role": "symbol",
      "title": "webpageURL",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity/1418086-webpageurl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appclip/documentation/AppClip",
                "doc://com.apple.appclip/documentation/AppClip/APActivationPayload"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "URL"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayload/title",
          "value": "APActivationPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayload~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayload~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appclip/apactivationpayload/url"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appclip/apactivationpayload/url"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
