{
  "abstract": [
    {
      "text": "A value for classifying an issue that occurs during testing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/type"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTIssue(py)type",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCTIssue",
        "text": "XCTIssueReference"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@XCTIssueType",
        "text": "IssueType"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "type"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "type"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTIssue",
              "text": "XCTIssueReference"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/IssueType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@XCTIssueType",
              "text": "IssueType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference": {
      "abstract": [
        {
          "text": "An object that represents a test failure, and includes source code call stacks for test reporting and investigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTIssueReference"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTIssueReference"
        }
      ],
      "role": "symbol",
      "title": "XCTIssueReference",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/IssueType": {
      "abstract": [
        {
          "text": "Constants that indicate types of test failures, such as assertion failures, performance regressions, or thrown errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IssueType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/IssueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IssueType"
        }
      ],
      "role": "symbol",
      "title": "XCTIssueReference.IssueType",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference/issuetype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/associatedError": {
      "abstract": [
        {
          "text": "An optional error to associate with a test issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "associatedError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/associatedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "associatedError"
        }
      ],
      "role": "symbol",
      "title": "associatedError",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference/associatederror"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/attachments": {
      "abstract": [
        {
          "text": "An array of data that augments a test issue, such as files, images, screenshots, data blobs, or ZIP files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTAttachment",
          "text": "XCTAttachment"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/attachments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachments"
        }
      ],
      "role": "symbol",
      "title": "attachments",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference/attachments"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/compactDescription": {
      "abstract": [
        {
          "text": "A concise description of the issue with no transient data, suitable for use in test run summaries and results aggregation across multiple test runs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compactDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/compactDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compactDescription"
        }
      ],
      "role": "symbol",
      "title": "compactDescription",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference/compactdescription"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/detailedDescription": {
      "abstract": [
        {
          "text": "A detailed description of the issue that may include transient data, such as numbers, object identifiers, and timestamps, to help diagnose the issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detailedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/detailedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detailedDescription"
        }
      ],
      "role": "symbol",
      "title": "detailedDescription",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference/detaileddescription"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/sourceCodeContext": {
      "abstract": [
        {
          "text": "The source code location for the issue, including the filename, line number, and call stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceCodeContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeContext",
          "text": "XCTSourceCodeContext"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/sourceCodeContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceCodeContext"
        }
      ],
      "role": "symbol",
      "title": "sourceCodeContext",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference/sourcecodecontext"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/type": {
      "abstract": [
        {
          "text": "A value for classifying an issue that occurs during testing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTIssue",
          "text": "XCTIssueReference"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTIssueType",
          "text": "IssueType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/xctest/xctissuereference/type"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Issue-Details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/compactDescription",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/detailedDescription",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/sourceCodeContext",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/associatedError",
        "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/attachments"
      ],
      "title": "Issue Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Issue-Details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/compactDescription",
                "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/detailedDescription",
                "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/sourceCodeContext",
                "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/associatedError",
                "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/attachments"
              ],
              "title": "Issue Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTIssueReference/IssueType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@XCTIssueType",
                    "text": "XCTIssueType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "type"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1sourceCodeContext/title",
          "value": "sourceCodeContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1sourceCodeContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceCodeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1associatedError/title",
          "value": "associatedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1associatedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "associatedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1IssueType/title",
          "value": "XCTIssueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1IssueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTIssueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1IssueType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTIssueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1detailedDescription/title",
          "value": "detailedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1detailedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "detailedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1compactDescription/title",
          "value": "compactDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1compactDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compactDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/title",
          "value": "XCTIssue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTIssue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1attachments/title",
          "value": "attachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1attachments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTIssueReference~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctissuereference/type"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctissuereference/type"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
