{
  "diffAvailability": {
    "beta": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor/process(with:parameters:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VTFrameProcessor(im)processWithCommandBuffer:parameters:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "process"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLCommandBuffer",
        "text": "MTLCommandBuffer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "parameters"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)VTFrameProcessorParameters",
        "text": "VTFrameProcessorParameters"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "processWithCommandBuffer:parameters:"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "process(with:parameters:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "process"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "commandBuffer"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLCommandBuffer",
              "text": "MTLCommandBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "parameters"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorParameters",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)VTFrameProcessorParameters",
              "text": "VTFrameProcessorParameters"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "code": [
            "@method\t\tprocessWithCommandBuffer:parameters",
            "@abstract\tThis API provides a Metal API friendly version of processWithParameters.",
            "@discussion\tThis function allows clients to add the effect to an existing Metal command buffer. This can be used by clients that have an existing Metal pipeline and want to add this effect to it. Note: this function will wait until all previously inserted tasks in the command buffer finished before running. Tasks inserted after the processWithCommandBuffer will run after the effect is applied.  Processing does not happen until the commandBuffer is executed.",
            "@param\t\tcommandBuffer",
            "\tAn existing Metal command buffer where the frame processing will be inserted.",
            "@param\t\tparameters",
            "\tA VTFrameProcessorParameters based object to specify additional frame based parameters to be used during processing. it needs to match the configuration type used during start session."
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessor"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessor"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessor",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessor"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor/process(with:parameters:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "process"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCommandBuffer",
          "text": "MTLCommandBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)VTFrameProcessorParameters",
          "text": "VTFrameProcessorParameters"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor/process(with:parameters:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processWithCommandBuffer:parameters:"
        }
      ],
      "role": "symbol",
      "title": "process(with:parameters:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessor/process(with:parameters:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorParameters": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorParameters"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorparameters"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandBuffer": {
      "abstract": [
        {
          "text": "A container that stores a sequence of GPU commands that you encode into it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBuffer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCommandBuffer",
      "type": "topic",
      "url": "/documentation/Metal/MTLCommandBuffer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "processWithCommandBuffer:parameters:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "processWithCommandBuffer:parameters:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "processWithCommandBuffer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)MTLCommandBuffer",
                    "text": "id<MTLCommandBuffer>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "commandBuffer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "parameters:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)VTFrameProcessorParameters",
                    "text": "id<VTFrameProcessorParameters>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "parameters"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MTLCommandBuffer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLCommandBuffer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessor~1process(with:parameters:)/title",
          "value": "processWithCommandBuffer:parameters:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessor~1process(with:parameters:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "processWithCommandBuffer:parameters:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessor/title",
          "value": "VTFrameProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorParameters/title",
          "value": "VTFrameProcessorParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtframeprocessor/process(with:parameters:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtframeprocessor/process(with:parameters:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
