{
  "abstract": [
    {
      "text": "The default types of analysis to perform.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit",
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVVideoFrameAnalysisType@AVVideoFrameAnalysisTypeDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
        "text": "AVVideoFrameAnalysisType"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVVideoFrameAnalysisTypeDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
              "text": "AVVideoFrameAnalysisType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType": {
      "abstract": [
        {
          "text": "Constants that define the types of analysis a player view controller may perform on a paused video frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "role": "symbol",
      "title": "AVVideoFrameAnalysisType",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/AVVideoFrameAnalysisTypeNone": {
      "abstract": [
        {
          "text": "A type that performs no analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeNone"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/AVVideoFrameAnalysisTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVVideoFrameAnalysisTypeNone",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/avvideoframeanalysistypenone"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/default": {
      "abstract": [
        {
          "text": "The default types of analysis to perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/default"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/machineReadableCode": {
      "abstract": [
        {
          "text": "A type that recognizes machine-readable codes, such as QR codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "machineReadableCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/machineReadableCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeMachineReadableCode"
        }
      ],
      "role": "symbol",
      "title": "machineReadableCode",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/machinereadablecode"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/subject": {
      "abstract": [
        {
          "text": "A type that finds a subject that a user can copy out of frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/subject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeSubject"
        }
      ],
      "role": "symbol",
      "title": "subject",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/subject"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/text": {
      "abstract": [
        {
          "text": "A type that finds text in a paused video frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeText"
        }
      ],
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/text"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/visualSearch": {
      "abstract": [
        {
          "text": "A type that identifies objects, landmarks, art, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visualSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/visualSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeVisualSearch"
        }
      ],
      "role": "symbol",
      "title": "visualSearch",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/visualsearch"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Analysis-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/text",
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/subject",
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/visualSearch",
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/machineReadableCode"
      ],
      "title": "Analysis types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVVideoFrameAnalysisTypeDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Analysis-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/text",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/subject",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/visualSearch",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/machineReadableCode",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/AVVideoFrameAnalysisTypeNone"
              ],
              "title": "Analysis types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVVideoFrameAnalysisTypeDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1default/title",
          "value": "AVVideoFrameAnalysisTypeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1machineReadableCode/title",
          "value": "AVVideoFrameAnalysisTypeMachineReadableCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1machineReadableCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeMachineReadableCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1visualSearch/title",
          "value": "AVVideoFrameAnalysisTypeVisualSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1visualSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeVisualSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType/title",
          "value": "AVVideoFrameAnalysisType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1subject/title",
          "value": "AVVideoFrameAnalysisTypeSubject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1subject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeSubject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1text/title",
          "value": "AVVideoFrameAnalysisTypeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeText"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avvideoframeanalysistype/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avvideoframeanalysistype/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
