{
  "abstract": [
    {
      "text": "The states in the process of decoding an App Clip code URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "c:@E@ARAppClipCodeURLDecodingState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "URLDecodingState"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "URLDecodingState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ARAppClipCodeAnchor.URLDecodingState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "URLDecodingState"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The possible states of decoding the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/url",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of an App Clip Code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor": {
      "abstract": [
        {
          "text": "An anchor that tracks the position and orientation of an App Clip Code in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARAppClipCodeAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAppClipCodeAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARAppClipCodeAnchor",
      "type": "topic",
      "url": "/documentation/arkit/arappclipcodeanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum": {
      "abstract": [
        {
          "text": "The states in the process of decoding an App Clip code URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "URLDecodingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URLDecodingState"
        }
      ],
      "role": "symbol",
      "title": "ARAppClipCodeAnchor.URLDecodingState",
      "type": "topic",
      "url": "/documentation/arkit/arappclipcodeanchor/urldecodingstate-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/decoded": {
      "abstract": [
        {
          "text": "A state that indicates the completed decoding of an App Clip Code URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decoded"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/decoded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAppClipCodeURLDecodingStateDecoded"
        }
      ],
      "role": "symbol",
      "title": "ARAppClipCodeAnchor.URLDecodingState.decoded",
      "type": "topic",
      "url": "/documentation/arkit/arappclipcodeanchor/urldecodingstate-swift.enum/decoded"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/decoding": {
      "abstract": [
        {
          "text": "A state that indicates the continuing process of decoding an App Clip Code’s URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decoding"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/decoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAppClipCodeURLDecodingStateDecoding"
        }
      ],
      "role": "symbol",
      "title": "ARAppClipCodeAnchor.URLDecodingState.decoding",
      "type": "topic",
      "url": "/documentation/arkit/arappclipcodeanchor/urldecodingstate-swift.enum/decoding"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/failed": {
      "abstract": [
        {
          "text": "A state that indicates the failure to decode an App Clip Code’s URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAppClipCodeURLDecodingStateFailed"
        }
      ],
      "role": "symbol",
      "title": "ARAppClipCodeAnchor.URLDecodingState.failed",
      "type": "topic",
      "url": "/documentation/arkit/arappclipcodeanchor/urldecodingstate-swift.enum/failed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/arkit/arappclipcodeanchor/urldecodingstate-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/url": {
      "abstract": [
        {
          "text": "The URL encoded in an App Clip Code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "url"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/arkit/arappclipcodeanchor/url"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/urlDecodingState-swift.property": {
      "abstract": [
        {
          "text": "A state that indicates the process of decoding an App Clip Code URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "urlDecodingState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARAppClipCodeAnchor",
          "text": "ARAppClipCodeAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARAppClipCodeURLDecodingState",
          "text": "URLDecodingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/urlDecodingState-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "urlDecodingState"
        }
      ],
      "role": "symbol",
      "title": "urlDecodingState",
      "type": "topic",
      "url": "/documentation/arkit/arappclipcodeanchor/urldecodingstate-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Decoding-the-URL",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/url",
        "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/urlDecodingState-swift.property"
      ],
      "title": "Decoding the URL"
    }
  ],
  "topicSections": [
    {
      "anchor": "States",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/decoded",
        "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/decoding",
        "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/failed"
      ],
      "title": "States"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARAppClipCodeURLDecodingState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeURLDecodingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeURLDecodingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "States",
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/decoded",
                "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/decoding",
                "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/URLDecodingState-swift.enum/failed"
              ],
              "title": "States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Decoding-the-URL",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/url",
                "doc://com.apple.arkit/documentation/ARKit/ARAppClipCodeAnchor/urlDecodingState-swift.property"
              ],
              "title": "Decoding the URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ARAppClipCodeURLDecodingState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum/title",
          "value": "ARAppClipCodeURLDecodingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeURLDecodingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeURLDecodingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1url/title",
          "value": "url"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "url"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum~1decoded/title",
          "value": "ARAppClipCodeURLDecodingStateDecoded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum~1decoded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeURLDecodingStateDecoded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor/title",
          "value": "ARAppClipCodeAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1urlDecodingState-swift.property/title",
          "value": "urlDecodingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1urlDecodingState-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "urlDecodingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum~1decoding/title",
          "value": "ARAppClipCodeURLDecodingStateDecoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum~1decoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeURLDecodingStateDecoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum~1failed/title",
          "value": "ARAppClipCodeURLDecodingStateFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAppClipCodeAnchor~1URLDecodingState-swift.enum~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAppClipCodeURLDecodingStateFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arappclipcodeanchor/urldecodingstate-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arappclipcodeanchor/urldecodingstate-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
