{
  "abstract": [
    {
      "text": "The item appears in the tab bar, but people can move or remove it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITab",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITabPlacement@UITabPlacementDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITabPlacementDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITab.Placement.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab": {
      "abstract": [
        {
          "text": "An object that manages a tab in a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITab"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITab"
        }
      ],
      "role": "symbol",
      "title": "UITab",
      "type": "topic",
      "url": "/documentation/uikit/uitab"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement": {
      "abstract": [
        {
          "text": "A tab’s placement when displayed in contexts that allow different placement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/automatic": {
      "abstract": [
        {
          "text": "The system adds only top-level items to the tab bar, but people can add, remove, or move this item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/default": {
      "abstract": [
        {
          "text": "The item appears in the tab bar, but people can move or remove it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementDefault"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.default",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/fixed": {
      "abstract": [
        {
          "text": "The item appears in the tab bar’s leading edge, and people can’t move or remove it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/fixed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementFixed"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.fixed",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/fixed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/movable": {
      "abstract": [
        {
          "text": "The item appears in the tab bar, people can move it but can’t remove it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/movable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementMovable"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.movable",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/movable"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/optional": {
      "abstract": [
        {
          "text": "The item doesn’t appear in the tab bar, but people can add it and move it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optional"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/optional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementOptional"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.optional",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/optional"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/pinned": {
      "abstract": [
        {
          "text": "The item appears as a pinned tab, on the trailing edge of the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinned"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/pinned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementPinned"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.pinned",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/pinned"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/sidebarOnly": {
      "abstract": [
        {
          "text": "The item only appears in the sidebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidebarOnly"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/sidebarOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabPlacementSidebarOnly"
        }
      ],
      "role": "symbol",
      "title": "UITab.Placement.sidebarOnly",
      "type": "topic",
      "url": "/documentation/uikit/uitab/placement/sidebaronly"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Placement-values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/fixed",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/movable",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/optional",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/pinned",
        "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/sidebarOnly"
      ],
      "title": "Placement values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITabPlacementDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Placement-values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/fixed",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/movable",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/optional",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/pinned",
                "doc://com.apple.uikit/documentation/UIKit/UITab/Placement/sidebarOnly"
              ],
              "title": "Placement values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITabPlacementDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/title",
          "value": "UITab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1optional/title",
          "value": "UITabPlacementOptional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1optional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementOptional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1sidebarOnly/title",
          "value": "UITabPlacementSidebarOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1sidebarOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementSidebarOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1automatic/title",
          "value": "UITabPlacementAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1movable/title",
          "value": "UITabPlacementMovable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1movable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementMovable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement/title",
          "value": "UITabPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1default/title",
          "value": "UITabPlacementDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1fixed/title",
          "value": "UITabPlacementFixed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1fixed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementFixed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1pinned/title",
          "value": "UITabPlacementPinned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab~1Placement~1pinned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabPlacementPinned"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitab/placement/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitab/placement/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
