{"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance","doc://com.apple.uikit/documentation/UIKit/UITabBar/leadingAccessoryView","doc://com.apple.uikit/documentation/UIKit/UITabBar/trailingAccessoryView","doc://com.apple.uikit/documentation/UIKit/UITabBar/isTranslucent","doc://com.apple.uikit/documentation/UIKit/uitabbar-legacy-customizations"],"title":"Customizing tab bar appearance","anchor":"Customizing-tab-bar-appearance"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBar"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITabBar/scrollEdgeAppearance"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitabbar/scrolledgeappearance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitabbar/scrolledgeappearance"]}],"abstract":[{"type":"text","text":"The appearance settings for the tab bar when the edge of scrollable content aligns with the edge of the tab bar."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollEdgeAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITabBarAppearance","preciseIdentifier":"c:objc(cs)UITabBarAppearance","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"When a tab bar controller contains a tab bar and a scroll view, part of the scroll view’s content appears underneath the tab bar. If the edge of the scrolled content reaches that bar, UIKit applies the appearance settings in this property."}],"type":"paragraph"},{"inlineContent":[{"text":"If the value of this property is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", UIKit uses the value of the tab bar’s ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance"},{"text":" property, modified to have a transparent background. If no tab bar controller manages your tab bar, UIKit ignores this property and uses the tab bar’s standard appearance.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You can customize the appearance for specific tab bar items with the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance","type":"reference","isActive":true},{"text":" property of ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"UIKit"}],"symbolKind":"property","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"15.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"15.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"15.0","beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"15.0","beta":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false}],"roleHeading":"Instance Property","externalID":"c:objc(cs)UITabBar(py)scrollEdgeAppearance","title":"scrollEdgeAppearance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollEdgeAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITabBarAppearance","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"scrollEdgeAppearance","kind":"identifier"}]},"references":{"doc://com.apple.uikit/documentation/UIKit/uitabbar-legacy-customizations":{"identifier":"doc://com.apple.uikit/documentation/UIKit/uitabbar-legacy-customizations","title":"Legacy customizations","url":"/documentation/uikit/uitabbar-legacy-customizations","kind":"article","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Customize appearance information directly on the tab bar object."}]},"doc://com.apple.uikit/documentation/UIKit/UITabBar/trailingAccessoryView":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/trailingAccessoryView","title":"trailingAccessoryView","navigatorTitle":[{"kind":"identifier","text":"trailingAccessoryView"}],"url":"/documentation/uikit/uitabbar/trailingaccessoryview","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trailingAccessoryView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"role":"symbol","abstract":[{"type":"text","text":"The view at the trailing edge of a tab bar on tvOS."}]},"doc://com.apple.uikit/documentation/UIKit/UITabBar":{"kind":"symbol","role":"symbol","title":"UITabBar","navigatorTitle":[{"kind":"identifier","text":"UITabBar"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITabBar"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar","url":"/documentation/uikit/uitabbar","abstract":[{"type":"text","text":"A control that displays one or more buttons in a tab bar for selecting between different subtasks, views, or modes in an app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance","kind":"symbol","url":"/documentation/uikit/uitabbar/standardappearance","navigatorTitle":[{"kind":"identifier","text":"standardAppearance"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"}],"abstract":[{"text":"The appearance settings for a standard-height tab bar.","type":"text"}],"title":"standardAppearance"},"doc://com.apple.uikit/documentation/UIKit/UITabBar/leadingAccessoryView":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/leadingAccessoryView","kind":"symbol","url":"/documentation/uikit/uitabbar/leadingaccessoryview","navigatorTitle":[{"kind":"identifier","text":"leadingAccessoryView"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingAccessoryView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"text":"The view at the leading edge of a tab bar on tvOS.","type":"text"}],"title":"leadingAccessoryView"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem":{"navigatorTitle":[{"text":"UITabBarItem","kind":"identifier"}],"role":"symbol","type":"topic","title":"UITabBarItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITabBarItem","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that describes an item in a tab bar."}],"url":"/documentation/uikit/uitabbaritem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem"},"doc://com.apple.uikit/documentation/UIKit/UITabBar/isTranslucent":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTranslucent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","title":"isTranslucent","url":"/documentation/uikit/uitabbar/istranslucent","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/isTranslucent","navigatorTitle":[{"kind":"identifier","text":"translucent"}],"type":"topic","kind":"symbol","abstract":[{"text":"A Boolean value that indicates whether the tab bar is translucent.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance","kind":"symbol","url":"/documentation/uikit/uitabbarappearance","navigatorTitle":[{"kind":"identifier","text":"UITabBarAppearance"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITabBarAppearance"}],"abstract":[{"text":"An object for customizing the appearance of a tab bar.","type":"text"}],"title":"UITabBarAppearance"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance":{"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarItem/scrollEdgeAppearance","kind":"symbol","url":"/documentation/uikit/uitabbaritem/scrolledgeappearance","navigatorTitle":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"},{"kind":"text","text":"?"}],"abstract":[{"text":"The appearance settings for the tab bar when the edge of scrollable content aligns with the edge of the tab bar.","type":"text"}],"title":"scrollEdgeAppearance"},"doc://com.apple.uikit/documentation/UIKit/UITabBar/scrollEdgeAppearance":{"abstract":[{"type":"text","text":"The appearance settings for the tab bar when the edge of scrollable content aligns with the edge of the tab bar."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITabBarAppearance","text":"UITabBarAppearance"},{"kind":"text","text":"?"}],"title":"scrollEdgeAppearance","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBar/scrollEdgeAppearance","url":"/documentation/uikit/uitabbar/scrolledgeappearance","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"scrollEdgeAppearance"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"scrollEdgeAppearance"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITabBar"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance","doc://com.apple.uikit/documentation/UIKit/UITabBar/leadingAccessoryView","doc://com.apple.uikit/documentation/UIKit/UITabBar/trailingAccessoryView","doc://com.apple.uikit/documentation/UIKit/UITabBar/isTranslucent","doc://com.apple.uikit/documentation/UIKit/uitabbar-legacy-customizations"],"title":"Customizing tab bar appearance","anchor":"Customizing-tab-bar-appearance","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UITabBarAppearance","preciseIdentifier":"c:objc(cs)UITabBarAppearance","identifier":"doc://com.apple.uikit/documentation/UIKit/UITabBarAppearance","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"scrollEdgeAppearance","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1trailingAccessoryView/title","value":"trailingAccessoryView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1trailingAccessoryView/fragments","value":[{"kind":"identifier","text":"trailingAccessoryView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/title","value":"UITabBar"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/fragments","value":[{"text":"UITabBar","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/navigatorTitle","value":[{"text":"UITabBar","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1standardAppearance/title","value":"standardAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1standardAppearance/fragments","value":[{"text":"standardAppearance","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1leadingAccessoryView/title","value":"leadingAccessoryView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1leadingAccessoryView/fragments","value":[{"kind":"identifier","text":"leadingAccessoryView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title","value":"UITabBarItem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments","value":[{"kind":"identifier","text":"UITabBarItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle","value":[{"text":"UITabBarItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1isTranslucent/title","value":"translucent","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1isTranslucent/fragments","value":[{"text":"translucent","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/title","value":"UITabBarAppearance","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/fragments","value":[{"text":"UITabBarAppearance","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarAppearance/navigatorTitle","value":[{"text":"UITabBarAppearance","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1scrollEdgeAppearance/title","value":"scrollEdgeAppearance","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem~1scrollEdgeAppearance/fragments","value":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1scrollEdgeAppearance/title","value":"scrollEdgeAppearance","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1scrollEdgeAppearance/fragments","value":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}