{
  "abstract": [
    {
      "text": "A finger touched the device. Or, a resting touch transitioned to an active touch and resting touches are not wanted by the view hierarchy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTouch",
        "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/began"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTouchPhase@NSTouchPhaseBegan",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "began"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTouch",
        "text": "NSTouch"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTouchPhase",
        "text": "Phase"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTouchPhaseBegan"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "began"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "began"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTouch",
              "text": "NSTouch"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTouchPhase",
              "text": "Phase"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch": {
      "abstract": [
        {
          "text": "A snapshot of a particular touch at an instant in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouch"
        }
      ],
      "role": "symbol",
      "title": "NSTouch",
      "type": "topic",
      "url": "/documentation/appkit/nstouch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct": {
      "abstract": [
        {
          "text": "The possible phases of a touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "role": "symbol",
      "title": "NSTouch.Phase",
      "type": "topic",
      "url": "/documentation/appkit/nstouch/phase-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/any": {
      "abstract": [
        {
          "text": "Matches any phase of a touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTouchPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchPhaseAny"
        }
      ],
      "role": "symbol",
      "title": "any",
      "type": "topic",
      "url": "/documentation/appkit/nstouch/phase-swift.struct/any"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/began": {
      "abstract": [
        {
          "text": "A finger touched the device. Or, a resting touch transitioned to an active touch and resting touches are not wanted by the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "began"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTouchPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/began",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchPhaseBegan"
        }
      ],
      "role": "symbol",
      "title": "began",
      "type": "topic",
      "url": "/documentation/appkit/nstouch/phase-swift.struct/began"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/cancelled": {
      "abstract": [
        {
          "text": "The system cancelled tracking for the touch, as when (for example) the window associated with the touch resigns key or is deactivated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTouchPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchPhaseCancelled"
        }
      ],
      "role": "symbol",
      "title": "cancelled",
      "type": "topic",
      "url": "/documentation/appkit/nstouch/phase-swift.struct/cancelled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/ended": {
      "abstract": [
        {
          "text": "A finger was lifted from the screen. Or, an active touch transitioned to a resting touch and resting touches are not wanted by the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTouchPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchPhaseEnded"
        }
      ],
      "role": "symbol",
      "title": "ended",
      "type": "topic",
      "url": "/documentation/appkit/nstouch/phase-swift.struct/ended"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/moved": {
      "abstract": [
        {
          "text": "A finger moved on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTouchPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/moved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchPhaseMoved"
        }
      ],
      "role": "symbol",
      "title": "moved",
      "type": "topic",
      "url": "/documentation/appkit/nstouch/phase-swift.struct/moved"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/stationary": {
      "abstract": [
        {
          "text": "A finger is touching the device, but hasn’t moved since the previous event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stationary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTouchPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/stationary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchPhaseStationary"
        }
      ],
      "role": "symbol",
      "title": "stationary",
      "type": "topic",
      "url": "/documentation/appkit/nstouch/phase-swift.struct/stationary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/touching": {
      "abstract": [
        {
          "text": "Matches the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/began",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/moved",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/stationary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " phases of a touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouch",
          "text": "NSTouch"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTouchPhase",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/touching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchPhaseTouching"
        }
      ],
      "role": "symbol",
      "title": "touching",
      "type": "topic",
      "url": "/documentation/appkit/nstouch/phase-swift.struct/touching"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/moved",
        "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/stationary",
        "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/ended",
        "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/cancelled",
        "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/touching",
        "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/any"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTouchPhaseBegan"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhaseBegan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/moved",
                "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/stationary",
                "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/ended",
                "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/cancelled",
                "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/touching",
                "doc://com.apple.appkit/documentation/AppKit/NSTouch/Phase-swift.struct/any"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTouchPhaseBegan"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1cancelled/title",
          "value": "NSTouchPhaseCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhaseCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1ended/title",
          "value": "NSTouchPhaseEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhaseEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1touching/title",
          "value": "NSTouchPhaseTouching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1touching/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhaseTouching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1began/title",
          "value": "NSTouchPhaseBegan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1began/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhaseBegan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1any/title",
          "value": "NSTouchPhaseAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhaseAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct/title",
          "value": "NSTouchPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1stationary/title",
          "value": "NSTouchPhaseStationary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1stationary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhaseStationary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch/title",
          "value": "NSTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1moved/title",
          "value": "NSTouchPhaseMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouch~1Phase-swift.struct~1moved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchPhaseMoved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstouch/phase-swift.struct/began"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstouch/phase-swift.struct/began"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
