{
  "abstract": [
    {
      "text": "A plain table view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITableView",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/plain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITableViewStyle@UITableViewStylePlain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "plain"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITableViewStylePlain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITableView.Style.plain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "plain"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Section headers and footers are displayed as inline separators and float when the table view is scrolled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView": {
      "abstract": [
        {
          "text": "A view that presents data using rows in a single column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "role": "symbol",
      "title": "UITableView",
      "type": "topic",
      "url": "/documentation/uikit/uitableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum": {
      "abstract": [
        {
          "text": "Constants for the table view styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "UITableView.Style",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/style-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/grouped": {
      "abstract": [
        {
          "text": "A table view where sections have distinct groups of rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grouped"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/grouped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewStyleGrouped"
        }
      ],
      "role": "symbol",
      "title": "UITableView.Style.grouped",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/style-swift.enum/grouped"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/insetGrouped": {
      "abstract": [
        {
          "text": "A table view where the grouped sections are inset with rounded corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insetGrouped"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/insetGrouped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewStyleInsetGrouped"
        }
      ],
      "role": "symbol",
      "title": "UITableView.Style.insetGrouped",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/style-swift.enum/insetgrouped"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/plain": {
      "abstract": [
        {
          "text": "A plain table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plain"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/plain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewStylePlain"
        }
      ],
      "role": "symbol",
      "title": "UITableView.Style.plain",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/style-swift.enum/plain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/grouped",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/insetGrouped"
      ],
      "title": "Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITableViewStylePlain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewStylePlain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/grouped",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/Style-swift.enum/insetGrouped"
              ],
              "title": "Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITableViewStylePlain"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1insetGrouped/title",
          "value": "UITableViewStyleInsetGrouped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1insetGrouped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewStyleInsetGrouped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/title",
          "value": "UITableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum/title",
          "value": "UITableViewStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1grouped/title",
          "value": "UITableViewStyleGrouped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1grouped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewStyleGrouped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1plain/title",
          "value": "UITableViewStylePlain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1Style-swift.enum~1plain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewStylePlain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableview/style-swift.enum/plain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitableview/style-swift.enum/plain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
