{
  "abstract": [
    {
      "text": "The error codes that the Messages framework generates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MSMessageErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MSMessageErrorCode"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MSMessageErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MSMessageErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError": {
      "abstract": [
        {
          "text": "Values that describe errors the Critical Messaging API returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSCriticalMessagingError"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSCriticalMessagingError"
        }
      ],
      "role": "symbol",
      "title": "MSCriticalMessagingError",
      "type": "topic",
      "url": "/documentation/messages/mscriticalmessagingerror"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessage": {
      "abstract": [
        {
          "text": "A custom message object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessage"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessage"
        }
      ],
      "role": "symbol",
      "title": "MSMessage",
      "type": "topic",
      "url": "/documentation/messages/msmessage"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessage/url": {
      "abstract": [
        {
          "text": "A URL that encodes data to be transmitted with the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/messages/msmessage/url"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode": {
      "abstract": [
        {
          "text": "The error codes that the Messages framework generates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageErrorCode"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCode"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/apiUnavailableInPresentationContext": {
      "abstract": [
        {
          "text": "The API is unavailable in the current context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiUnavailableInPresentationContext"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/apiUnavailableInPresentationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeAPIUnavailableInPresentationContext"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.apiUnavailableInPresentationContext",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/apiunavailableinpresentationcontext"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/fileNotFound": {
      "abstract": [
        {
          "text": "The file could not be found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNotFound"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/fileNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeFileNotFound"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.fileNotFound",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/filenotfound"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/fileUnreadable": {
      "abstract": [
        {
          "text": "The file could not be read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileUnreadable"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/fileUnreadable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeFileUnreadable"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.fileUnreadable",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/fileunreadable"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/improperFileType": {
      "abstract": [
        {
          "text": "The file is not a supported file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "improperFileType"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/improperFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeImproperFileType"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.improperFileType",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/improperfiletype"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/improperFileURL": {
      "abstract": [
        {
          "text": "The URL does not refer to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "improperFileURL"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/improperFileURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeImproperFileURL"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.improperFileURL",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/improperfileurl"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/init(rawvalue:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWhileNotVisible": {
      "abstract": [
        {
          "text": "A message was sent while the app was not visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendWhileNotVisible"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWhileNotVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeSendWhileNotVisible"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.sendWhileNotVisible",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/sendwhilenotvisible"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWithoutRecentInteraction": {
      "abstract": [
        {
          "text": "A message was sent, but the app has not registered a recent touch interaction from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendWithoutRecentInteraction"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWithoutRecentInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeSendWithoutRecentInteraction"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.sendWithoutRecentInteraction",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/sendwithoutrecentinteraction"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileAttributes": {
      "abstract": [
        {
          "text": "The system cannot read one or more of the file’s attributes (for example, the file size).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stickerFileImproperFileAttributes"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeStickerFileImproperFileAttributes"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.stickerFileImproperFileAttributes",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/stickerfileimproperfileattributes"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileFormat": {
      "abstract": [
        {
          "text": "The image used to create an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.messages/documentation/Messages/MSSticker",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object is not one of the supported file types (PNG, APNG, GIF, or JPEG).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stickerFileImproperFileFormat"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeStickerFileImproperFileFormat"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.stickerFileImproperFileFormat",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/stickerfileimproperfileformat"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileSize": {
      "abstract": [
        {
          "text": "The image used to create an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.messages/documentation/Messages/MSSticker",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object is larger than 500 KB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stickerFileImproperFileSize"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeStickerFileImproperFileSize"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.stickerFileImproperFileSize",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/stickerfileimproperfilesize"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/unknown": {
      "abstract": [
        {
          "text": "An unexpected or unknown error has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeUnknown"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.unknown",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/unknown"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/urlExceedsMaxSize": {
      "abstract": [
        {
          "text": "The URL in an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/url",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property is longer than the maximum allowed length (5,000 characters).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "urlExceedsMaxSize"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/urlExceedsMaxSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeURLExceedsMaxSize"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.urlExceedsMaxSize",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/urlexceedsmaxsize"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for iMessage apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesErrorDomain",
      "type": "topic",
      "url": "/documentation/messages/msmessageserrordomain"
    },
    "doc://com.apple.messages/documentation/Messages/MSSticker": {
      "abstract": [
        {
          "text": "A sticker that can be sent as a new message or attached to an existing balloon in the Messages app’s  transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSSticker"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSSticker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSSticker"
        }
      ],
      "role": "symbol",
      "title": "MSSticker",
      "type": "topic",
      "url": "/documentation/messages/mssticker"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for stickers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSStickersErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSStickersErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MSStickersErrorDomain",
      "type": "topic",
      "url": "/documentation/messages/msstickerserrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
        "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain",
        "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/fileNotFound",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/fileUnreadable",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/improperFileType",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/improperFileURL",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileAttributes",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileSize",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileFormat",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/urlExceedsMaxSize",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWhileNotVisible",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWithoutRecentInteraction",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/apiUnavailableInPresentationContext",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/unknown"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MSMessageErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/fileNotFound",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/fileUnreadable",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/improperFileType",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/improperFileURL",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileAttributes",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileSize",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/stickerFileImproperFileFormat",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/urlExceedsMaxSize",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWhileNotVisible",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWithoutRecentInteraction",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/apiUnavailableInPresentationContext",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/unknown"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
                "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MSMessageErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/title",
          "value": "MSMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1improperFileURL/title",
          "value": "MSMessageErrorCodeImproperFileURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1improperFileURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeImproperFileURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1urlExceedsMaxSize/title",
          "value": "MSMessageErrorCodeURLExceedsMaxSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1urlExceedsMaxSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeURLExceedsMaxSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/title",
          "value": "MSMessageErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickersErrorDomain/title",
          "value": "MSStickersErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickersErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickersErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1unknown/title",
          "value": "MSMessageErrorCodeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1improperFileType/title",
          "value": "MSMessageErrorCodeImproperFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1improperFileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeImproperFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1sendWithoutRecentInteraction/title",
          "value": "MSMessageErrorCodeSendWithoutRecentInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1sendWithoutRecentInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeSendWithoutRecentInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/title",
          "value": "MSSticker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSticker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1sendWhileNotVisible/title",
          "value": "MSMessageErrorCodeSendWhileNotVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1sendWhileNotVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeSendWhileNotVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1stickerFileImproperFileFormat/title",
          "value": "MSMessageErrorCodeStickerFileImproperFileFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1stickerFileImproperFileFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeStickerFileImproperFileFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1stickerFileImproperFileSize/title",
          "value": "MSMessageErrorCodeStickerFileImproperFileSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1stickerFileImproperFileSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeStickerFileImproperFileSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesErrorDomain/title",
          "value": "MSMessagesErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1stickerFileImproperFileAttributes/title",
          "value": "MSMessageErrorCodeStickerFileImproperFileAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1stickerFileImproperFileAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeStickerFileImproperFileAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1fileNotFound/title",
          "value": "MSMessageErrorCodeFileNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1fileNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeFileNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1apiUnavailableInPresentationContext/title",
          "value": "MSMessageErrorCodeAPIUnavailableInPresentationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1apiUnavailableInPresentationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeAPIUnavailableInPresentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1fileUnreadable/title",
          "value": "MSMessageErrorCodeFileUnreadable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1fileUnreadable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeFileUnreadable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/msmessageerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/msmessageerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
