{
  "abstract": [
    {
      "text": "The error domain for iMessage apps.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MSMessagesErrorDomain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MSMessagesErrorDomain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MSMessagesErrorDomain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MSMessagesErrorDomain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MSMessagesErrorDomain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError": {
      "abstract": [
        {
          "text": "Values that describe errors the Critical Messaging API returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSCriticalMessagingError"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSCriticalMessagingError"
        }
      ],
      "role": "symbol",
      "title": "MSCriticalMessagingError",
      "type": "topic",
      "url": "/documentation/messages/mscriticalmessagingerror"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode": {
      "abstract": [
        {
          "text": "The error codes that the Messages framework generates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageErrorCode"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCode"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for iMessage apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesErrorDomain",
      "type": "topic",
      "url": "/documentation/messages/msmessageserrordomain"
    },
    "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for stickers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSStickersErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSStickersErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MSStickersErrorDomain",
      "type": "topic",
      "url": "/documentation/messages/msstickerserrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
        "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode",
        "doc://com.apple.messages/documentation/Messages/MSCriticalMessagingError"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MSMessagesErrorDomain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSStickersErrorDomain",
                "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MSMessagesErrorDomain"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickersErrorDomain/title",
          "value": "MSStickersErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSStickersErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSStickersErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesErrorDomain/title",
          "value": "MSMessagesErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/title",
          "value": "MSMessageErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/msmessageserrordomain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/msmessageserrordomain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
