{
  "abstract": [
    {
      "text": "A protocol that provides support for displaying live messages in the transcript of the Messages app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MSMessagesAppTranscriptPresentation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MSMessagesAppTranscriptPresentation"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MSMessagesAppTranscriptPresentation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MSMessagesAppTranscriptPresentation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These methods are called when a view controller is presented using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle/transcript",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " presentation style.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle": {
      "abstract": [
        {
          "text": "Presentation styles that describe your iMessage app’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationStyle",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationstyle"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle/transcript": {
      "abstract": [
        {
          "text": "The iMessage app is displayed in the Messages app’s transcript or input field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transcript"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle/transcript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationStyleTranscript"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationStyle.transcript",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationstyle/transcript"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation": {
      "abstract": [
        {
          "text": "A protocol that provides support for displaying live messages in the transcript of the Messages app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppTranscriptPresentation"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppTranscriptPresentation"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppTranscriptPresentation",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapptranscriptpresentation"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation/contentSizeThatFits(_:)": {
      "abstract": [
        {
          "text": "The size of your messages view, given the provided maximum size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentSizeThatFits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation/contentSizeThatFits(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentSizeThatFits:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "contentSizeThatFits(_:)",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapptranscriptpresentation/contentsizethatfits(_:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController": {
      "abstract": [
        {
          "text": "The principal view controller for iMessage apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessagesAppViewController"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppViewController"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppViewController",
      "type": "topic",
      "url": "/documentation/messages/msmessagesappviewcontroller"
    },
    "doc://com.apple.messages/documentation/Messages/creating-a-sticker-app-with-a-custom-layout": {
      "abstract": [
        {
          "text": "Expand on the Messages sticker app template to create an app with a customized user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/creating-a-sticker-app-with-a-custom-layout",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a Sticker App with a Custom Layout",
      "type": "topic",
      "url": "/documentation/messages/creating-a-sticker-app-with-a-custom-layout"
    },
    "doc://com.apple.messages/documentation/Messages/icecreambuilder-building-an-imessage-extension": {
      "abstract": [
        {
          "text": "Allow users to collaborate on the design of ice cream sundae stickers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/icecreambuilder-building-an-imessage-extension",
      "kind": "article",
      "role": "sampleCode",
      "title": "IceCreamBuilder: Building an iMessage Extension",
      "type": "topic",
      "url": "/documentation/messages/icecreambuilder-building-an-imessage-extension"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-iMessage-app-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/icecreambuilder-building-an-imessage-extension",
        "doc://com.apple.messages/documentation/Messages/creating-a-sticker-app-with-a-custom-layout",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle"
      ],
      "title": "Custom iMessage app interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-the-Contents-Size",
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation/contentSizeThatFits(_:)"
      ],
      "title": "Providing the Content’s Size"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MSMessagesAppTranscriptPresentation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-the-Contents-Size",
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppTranscriptPresentation/contentSizeThatFits(_:)"
              ],
              "title": "Providing the Content’s Size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Custom-iMessage-app-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/icecreambuilder-building-an-imessage-extension",
                "doc://com.apple.messages/documentation/Messages/creating-a-sticker-app-with-a-custom-layout",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppViewController",
                "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationStyle"
              ],
              "title": "Custom iMessage app interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MSMessagesAppTranscriptPresentation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/title",
          "value": "MSMessagesAppPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/title",
          "value": "MSMessagesAppTranscriptPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppTranscriptPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/title",
          "value": "MSMessagesAppViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation~1contentSizeThatFits(_:)/title",
          "value": "contentSizeThatFits:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppTranscriptPresentation~1contentSizeThatFits(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentSizeThatFits:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle~1transcript/title",
          "value": "MSMessagesAppPresentationStyleTranscript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationStyle~1transcript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationStyleTranscript"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/msmessagesapptranscriptpresentation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/msmessagesapptranscriptpresentation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
