{
  "abstract": [
    {
      "text": "A session object used to create and update messages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSSession"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSSession",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MSSession"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MSSession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MSSession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MSSession"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.messages/documentation/Messages/MSSession",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class does not declare any instance methods or properties. iMessage apps use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.messages/documentation/Messages/MSSession",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects to identify and track updatable messages.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects associated with a session receive the following treatment in the transcript:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The first time a session is used, the message appears normally in the transcript.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If a later message is sent using the same session, the previous message is removed from the transcript. The new message, with the updated content, is added to the bottom of the transcript, as normal.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the previous message has a non-",
                      "type": "text"
                    },
                    {
                      "code": "nil",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/summaryText",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property, the Messages app creates a summary message from the text and inserts it in the message’s previous location.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Create-New-Updatable-Messages",
          "level": 3,
          "text": "Create New, Updatable Messages",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the following workflow to create a new, updatable message.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create the following:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A new URL that encodes the message’s initial state. For example, you could encode data as key-value pairs in the URL’s query string. For more information, see the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/url",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A new layout object that describes the initial message’s appearance. For more information, see the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/layout",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A string that describes the message’s current state. For more information, see the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/summaryText",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instantiate a new ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object by calling its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1418641-init",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instantiate a new ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object by calling its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/init(session:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method and passing the session object. Set the message’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/url",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/layout",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/summaryText",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Send the message by calling the conversation’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/insert(_:completionHandler:)-3g248",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method. Pass ",
                      "type": "text"
                    },
                    {
                      "code": "nil",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for the change description.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "start": 2,
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The Messages app adds the message to the transcript as soon as the user taps the send button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Update-Messages",
          "level": 3,
          "text": "Update Messages",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the following workflow to receive and update a message.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When the user taps on one of your ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " entries, the conversation’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/selectedMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property is changed to the tapped message. Use key-value observing to respond to these changes. Extract the current state from the message’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/url",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property, and present it to the user.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "For more information on receiving messages, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "After the user responds, create the following:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A new URL that encodes the updated message state. For example, you could encode the data as key-value pairs in the URL’s query string. For more information, see the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/url",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A new layout object that describes the updated message’s appearance. For more information, see the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/layout",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A string that describes the message’s current state. For more information, see the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/summaryText",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instantiate a new ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object by calling its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/init(session:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method and passing the currently selected message’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object. Set the message’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/url",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/layout",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/summaryText",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Send the updated message by calling the conversation’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/insert(_:completionHandler:)-3g248",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "start": 3,
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The Messages app updates the message in the transcript as soon as the user taps the send button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1418641-init": {
      "abstract": [
        {
          "text": "Implemented by subclasses to initialize a new object (the receiver) immediately after memory for it has been allocated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1418641-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1418641-init"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSConversation/insert(_:completionHandler:)-3g248": {
      "abstract": [
        {
          "text": "Inserts a message object into the Messages app’s input field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSMessage",
          "text": "MSMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/insert(_:completionHandler:)-3g248",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertMessage:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "insert(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/messages/msconversation/insert(_:completionhandler:)-3g248"
    },
    "doc://com.apple.messages/documentation/Messages/MSConversation/selectedMessage": {
      "abstract": [
        {
          "text": "The message that the user selected in the conversation transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSMessage",
          "text": "MSMessage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/selectedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedMessage"
        }
      ],
      "role": "symbol",
      "title": "selectedMessage",
      "type": "topic",
      "url": "/documentation/messages/msconversation/selectedmessage"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessage": {
      "abstract": [
        {
          "text": "A custom message object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessage"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessage"
        }
      ],
      "role": "symbol",
      "title": "MSMessage",
      "type": "topic",
      "url": "/documentation/messages/msmessage"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessage/init(session:)": {
      "abstract": [
        {
          "text": "Initializes a new message that is part of the provided session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSSession",
          "text": "MSSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/init(session:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSession:"
        }
      ],
      "role": "symbol",
      "title": "init(session:)",
      "type": "topic",
      "url": "/documentation/messages/msmessage/init(session:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessage/layout": {
      "abstract": [
        {
          "text": "A layout object that defines the message’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSMessageLayout",
          "text": "MSMessageLayout"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/layout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layout"
        }
      ],
      "role": "symbol",
      "title": "layout",
      "type": "topic",
      "url": "/documentation/messages/msmessage/layout"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessage/summaryText": {
      "abstract": [
        {
          "text": "A succinct description of the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "summaryText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/summaryText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "summaryText"
        }
      ],
      "role": "symbol",
      "title": "summaryText",
      "type": "topic",
      "url": "/documentation/messages/msmessage/summarytext"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessage/url": {
      "abstract": [
        {
          "text": "A URL that encodes data to be transmitted with the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/messages/msmessage/url"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageLayout": {
      "abstract": [
        {
          "text": "An abstract base class that defines the appearance of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.messages/documentation/Messages/MSMessage",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects in the conversation transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageLayout"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageLayout"
        }
      ],
      "role": "symbol",
      "title": "MSMessageLayout",
      "type": "topic",
      "url": "/documentation/messages/msmessagelayout"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageLiveLayout": {
      "abstract": [
        {
          "text": "A layout that provides a custom, interactive view inside the transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageLiveLayout"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageLiveLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageLiveLayout"
        }
      ],
      "role": "symbol",
      "title": "MSMessageLiveLayout",
      "type": "topic",
      "url": "/documentation/messages/msmessagelivelayout"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout": {
      "abstract": [
        {
          "text": "A template-based layout for custom messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageTemplateLayout"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageTemplateLayout"
        }
      ],
      "role": "symbol",
      "title": "MSMessageTemplateLayout",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout"
    },
    "doc://com.apple.messages/documentation/Messages/MSSession": {
      "abstract": [
        {
          "text": "A session object used to create and update messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSSession"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSSession"
        }
      ],
      "role": "symbol",
      "title": "MSSession",
      "type": "topic",
      "url": "/documentation/messages/mssession"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interactive-messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSMessage",
        "doc://com.apple.messages/documentation/Messages/MSMessageLayout",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout",
        "doc://com.apple.messages/documentation/Messages/MSMessageLiveLayout"
      ],
      "title": "Interactive messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MSSession"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interactive-messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSMessage",
                "doc://com.apple.messages/documentation/Messages/MSMessageLayout",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout",
                "doc://com.apple.messages/documentation/Messages/MSMessageLiveLayout"
              ],
              "title": "Interactive messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MSSession"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1init(session:)/title",
          "value": "initWithSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1init(session:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/title",
          "value": "MSMessageTemplateLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageTemplateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageTemplateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSession/title",
          "value": "MSSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLayout/title",
          "value": "MSMessageLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1layout/title",
          "value": "layout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1layout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1selectedMessage/title",
          "value": "selectedMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1selectedMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11418641-init/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLiveLayout/title",
          "value": "MSMessageLiveLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLiveLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageLiveLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageLiveLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageLiveLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1summaryText/title",
          "value": "summaryText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage~1summaryText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "summaryText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/title",
          "value": "MSMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1insert(_:completionHandler:)-3g248/title",
          "value": "insertMessage:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1insert(_:completionHandler:)-3g248/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertMessage:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/mssession"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/mssession"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
