{
  "abstract": [
    {
      "text": "The standard small system font used for informative text in alerts, column headings in lists, help tags, and small controls.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallSystem",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSmallSystemFontType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontUIFontType@kCTFontSmallSystemFontType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTFontSmallSystemFontType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTFontUIFontType",
        "text": "CTFontUIFontType"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontSmallSystemFontType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Deprecated",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Deprecated",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Deprecated",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.11",
        "introducedAt": "10.5",
        "message": "Deprecated",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Deprecated",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "kCTFontSmallSystemFontType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTFontSmallSystemFontType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTFontUIFontType",
              "text": "CTFontUIFontType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType": {
      "abstract": [
        {
          "text": "Constants that represent the specific user-interface purpose to specify for font creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontUIFontType"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontApplicationFontType": {
      "abstract": [
        {
          "text": "The default font for text documents.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontApplicationFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontApplicationFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontApplicationFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontApplicationFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontapplicationfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontEmphasizedSystemFontType": {
      "abstract": [
        {
          "text": "The system font used for emphasis in alerts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontEmphasizedSystemFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontEmphasizedSystemFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontEmphasizedSystemFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontEmphasizedSystemFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontemphasizedsystemfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontLabelFontType": {
      "abstract": [
        {
          "text": "The font used for labels and tick marks on full-size sliders.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontLabelFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontLabelFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontLabelFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontLabelFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontlabelfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemCmdKeyFontType": {
      "abstract": [
        {
          "text": "The font used for menu-item command-key equivalents.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMenuItemCmdKeyFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemCmdKeyFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMenuItemCmdKeyFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMenuItemCmdKeyFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontmenuitemcmdkeyfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemFontType": {
      "abstract": [
        {
          "text": "The font used for menu items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMenuItemFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMenuItemFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMenuItemFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontmenuitemfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemMarkFontType": {
      "abstract": [
        {
          "text": "The font used to draw menu-item marks.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMenuItemMarkFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemMarkFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMenuItemMarkFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMenuItemMarkFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontmenuitemmarkfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuTitleFontType": {
      "abstract": [
        {
          "text": "The font used for menu titles.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMenuTitleFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuTitleFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMenuTitleFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMenuTitleFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontmenutitlefonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMiniEmphasizedSystemFontType": {
      "abstract": [
        {
          "text": "The miniature system font used for emphasis.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMiniEmphasizedSystemFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMiniEmphasizedSystemFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMiniEmphasizedSystemFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMiniEmphasizedSystemFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontminiemphasizedsystemfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMiniSystemFontType": {
      "abstract": [
        {
          "text": "The standard miniature system font used for mini controls and utility window labels and text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMiniSystemFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMiniSystemFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMiniSystemFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMiniSystemFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontminisystemfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontNoFontType": {
      "abstract": [
        {
          "text": "The user-interface font type isn’t specified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontNoFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontNoFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontNoFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontNoFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontnofonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSmallEmphasizedSystemFontType": {
      "abstract": [
        {
          "text": "The small system font used for emphasis.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontSmallEmphasizedSystemFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSmallEmphasizedSystemFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSmallEmphasizedSystemFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontSmallEmphasizedSystemFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontsmallemphasizedsystemfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSmallSystemFontType": {
      "abstract": [
        {
          "text": "The standard small system font used for informative text in alerts, column headings in lists, help tags, and small controls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontSmallSystemFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSmallSystemFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSmallSystemFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontSmallSystemFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontsmallsystemfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSystemFontType": {
      "abstract": [
        {
          "text": "The system font used for standard user-interface items, such as button labels and menu items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontSystemFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSystemFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSystemFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontSystemFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontsystemfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontUserFixedPitchFontType": {
      "abstract": [
        {
          "text": "The font used by default for documents and other text under the user’s control when that font is fixed-pitch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontUserFixedPitchFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontUserFixedPitchFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUserFixedPitchFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontUserFixedPitchFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontuserfixedpitchfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontUserFontType": {
      "abstract": [
        {
          "text": "The font used by default for documents and other text under the user’s control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontUserFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontUserFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUserFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontUserFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontuserfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontViewsFontType": {
      "abstract": [
        {
          "text": "The view font used as the default font of text in lists and tables.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontViewsFontType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontViewsFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontViewsFontType"
        }
      ],
      "role": "symbol",
      "title": "kCTFontViewsFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/kctfontviewsfonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallSystem": {
      "abstract": [
        {
          "text": "The standard small system font for informative text in alerts, column headings in lists, help tags, and small controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallSystem"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontSmallSystem"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.smallSystem",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/smallsystem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontNoFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontUserFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontUserFixedPitchFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSystemFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontEmphasizedSystemFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSmallEmphasizedSystemFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMiniSystemFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMiniEmphasizedSystemFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontViewsFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontApplicationFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontLabelFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuTitleFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemMarkFontType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemCmdKeyFontType"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.11",
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontSmallSystemFontType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSmallSystemFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontNoFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontUserFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontUserFixedPitchFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSystemFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontEmphasizedSystemFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontSmallEmphasizedSystemFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMiniSystemFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMiniEmphasizedSystemFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontViewsFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontApplicationFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontLabelFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuTitleFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemMarkFontType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/kCTFontMenuItemCmdKeyFontType"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontSmallSystemFontType"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallSystem",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMiniEmphasizedSystemFontType/title",
          "value": "kCTFontMiniEmphasizedSystemFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMiniEmphasizedSystemFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMiniEmphasizedSystemFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType/title",
          "value": "CTFontUIFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontUIFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontUIFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontEmphasizedSystemFontType/title",
          "value": "kCTFontEmphasizedSystemFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontEmphasizedSystemFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontEmphasizedSystemFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMiniSystemFontType/title",
          "value": "kCTFontMiniSystemFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMiniSystemFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMiniSystemFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMenuItemMarkFontType/title",
          "value": "kCTFontMenuItemMarkFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMenuItemMarkFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMenuItemMarkFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontUserFontType/title",
          "value": "kCTFontUserFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontUserFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUserFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontUserFixedPitchFontType/title",
          "value": "kCTFontUserFixedPitchFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontUserFixedPitchFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUserFixedPitchFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMenuItemCmdKeyFontType/title",
          "value": "kCTFontMenuItemCmdKeyFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMenuItemCmdKeyFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMenuItemCmdKeyFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontSmallEmphasizedSystemFontType/title",
          "value": "kCTFontSmallEmphasizedSystemFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontSmallEmphasizedSystemFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSmallEmphasizedSystemFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMenuItemFontType/title",
          "value": "kCTFontMenuItemFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMenuItemFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMenuItemFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontSystemFontType/title",
          "value": "kCTFontSystemFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontSystemFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSystemFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontSmallSystemFontType/title",
          "value": "kCTFontSmallSystemFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontSmallSystemFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSmallSystemFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMenuTitleFontType/title",
          "value": "kCTFontMenuTitleFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontMenuTitleFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMenuTitleFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontViewsFontType/title",
          "value": "kCTFontViewsFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontViewsFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontViewsFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontLabelFontType/title",
          "value": "kCTFontLabelFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontLabelFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontLabelFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1smallSystem/title",
          "value": "kCTFontUIFontSmallSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1smallSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontSmallSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontNoFontType/title",
          "value": "kCTFontNoFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontNoFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontNoFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontApplicationFontType/title",
          "value": "kCTFontApplicationFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1kCTFontApplicationFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontApplicationFontType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontuifonttype/kctfontsmallsystemfonttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontuifonttype/kctfontsmallsystemfonttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
