{
  "abstract": [
    {
      "text": "The small system font for emphasis.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallEmphasizedSystem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontUIFontType@kCTFontUIFontSmallEmphasizedSystem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "smallEmphasizedSystem"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontUIFontSmallEmphasizedSystem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTFontUIFontType.smallEmphasizedSystem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "smallEmphasizedSystem"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType": {
      "abstract": [
        {
          "text": "Constants that represent the specific user-interface purpose to specify for font creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontUIFontType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontUIFontType"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/application": {
      "abstract": [
        {
          "text": "The default font for text documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/application",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontApplication"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.application",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/application"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/emphasizedSystem": {
      "abstract": [
        {
          "text": "The system font for emphasis in alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emphasizedSystem"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/emphasizedSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontEmphasizedSystem"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.emphasizedSystem",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/emphasizedsystem"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/label": {
      "abstract": [
        {
          "text": "The font for labels and tick marks on full-size sliders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontLabel"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.label",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/label"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItem": {
      "abstract": [
        {
          "text": "The font for menu items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuItem"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontMenuItem"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.menuItem",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/menuitem"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItemCmdKey": {
      "abstract": [
        {
          "text": "The font for menu-item command-key equivalents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuItemCmdKey"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItemCmdKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontMenuItemCmdKey"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.menuItemCmdKey",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/menuitemcmdkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItemMark": {
      "abstract": [
        {
          "text": "The font to draw menu-item marks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuItemMark"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItemMark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontMenuItemMark"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.menuItemMark",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/menuitemmark"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuTitle": {
      "abstract": [
        {
          "text": "The font for menu titles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuTitle"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontMenuTitle"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.menuTitle",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/menutitle"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/miniEmphasizedSystem": {
      "abstract": [
        {
          "text": "The miniature system font for emphasis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miniEmphasizedSystem"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/miniEmphasizedSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontMiniEmphasizedSystem"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.miniEmphasizedSystem",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/miniemphasizedsystem"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/miniSystem": {
      "abstract": [
        {
          "text": "The standard miniature system font for mini controls and utility window labels and text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miniSystem"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/miniSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontMiniSystem"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.miniSystem",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/minisystem"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/none": {
      "abstract": [
        {
          "text": "The user-interface font type isn’t specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontNone"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.none",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/none"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallEmphasizedSystem": {
      "abstract": [
        {
          "text": "The small system font for emphasis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallEmphasizedSystem"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallEmphasizedSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontSmallEmphasizedSystem"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.smallEmphasizedSystem",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/smallemphasizedsystem"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallSystem": {
      "abstract": [
        {
          "text": "The standard small system font for informative text in alerts, column headings in lists, help tags, and small controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallSystem"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontSmallSystem"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.smallSystem",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/smallsystem"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/system": {
      "abstract": [
        {
          "text": "The system font for standard user-interface items, such as button labels and menu items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "system"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/system",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontSystem"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.system",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/system"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/user": {
      "abstract": [
        {
          "text": "The default font for documents and other text whose font the user can typically change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "user"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/user",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontUser"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.user",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/user"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/userFixedPitch": {
      "abstract": [
        {
          "text": "The default font for documents and other text under the user’s control when that font is fixed-pitch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userFixedPitch"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/userFixedPitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontUserFixedPitch"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.userFixedPitch",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/userfixedpitch"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/views": {
      "abstract": [
        {
          "text": "The default view font for text in lists and tables.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "views"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/views",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIFontViews"
        }
      ],
      "role": "symbol",
      "title": "CTFontUIFontType.views",
      "type": "topic",
      "url": "/documentation/coretext/ctfontuifonttype/views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/none",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/user",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/userFixedPitch",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/system",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/emphasizedSystem",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallSystem",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/miniSystem",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/miniEmphasizedSystem",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/views",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/application",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/label",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuTitle",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItem",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItemMark",
        "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItemCmdKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontUIFontSmallEmphasizedSystem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontSmallEmphasizedSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/none",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/user",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/userFixedPitch",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/system",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/emphasizedSystem",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/smallSystem",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/miniSystem",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/miniEmphasizedSystem",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/views",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/application",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/label",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuTitle",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItem",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItemMark",
                "doc://com.apple.coretext/documentation/CoreText/CTFontUIFontType/menuItemCmdKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontUIFontSmallEmphasizedSystem"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1views/title",
          "value": "kCTFontUIFontViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1views/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1application/title",
          "value": "kCTFontUIFontApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1application/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType/title",
          "value": "CTFontUIFontType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontUIFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontUIFontType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1none/title",
          "value": "kCTFontUIFontNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1menuItemMark/title",
          "value": "kCTFontUIFontMenuItemMark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1menuItemMark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontMenuItemMark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1smallEmphasizedSystem/title",
          "value": "kCTFontUIFontSmallEmphasizedSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1smallEmphasizedSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontSmallEmphasizedSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1miniSystem/title",
          "value": "kCTFontUIFontMiniSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1miniSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontMiniSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1label/title",
          "value": "kCTFontUIFontLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1menuItemCmdKey/title",
          "value": "kCTFontUIFontMenuItemCmdKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1menuItemCmdKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontMenuItemCmdKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1miniEmphasizedSystem/title",
          "value": "kCTFontUIFontMiniEmphasizedSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1miniEmphasizedSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontMiniEmphasizedSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1emphasizedSystem/title",
          "value": "kCTFontUIFontEmphasizedSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1emphasizedSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontEmphasizedSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1menuItem/title",
          "value": "kCTFontUIFontMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1menuItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1smallSystem/title",
          "value": "kCTFontUIFontSmallSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1smallSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontSmallSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1userFixedPitch/title",
          "value": "kCTFontUIFontUserFixedPitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1userFixedPitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontUserFixedPitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1system/title",
          "value": "kCTFontUIFontSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1system/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1user/title",
          "value": "kCTFontUIFontUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1user/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1menuTitle/title",
          "value": "kCTFontUIFontMenuTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontUIFontType~1menuTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIFontMenuTitle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontuifonttype/smallemphasizedsystem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontuifonttype/smallemphasizedsystem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
