{
  "abstract": [
    {
      "text": "A constant that represents an element type for ruler views.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/ruler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCUIElementType@XCUIElementTypeRuler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ruler"
      }
    ],
    "modules": [
      {
        "name": "XCUIAutomation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIElementTypeRuler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.3",
        "name": "Xcode",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "XCUIElement.ElementType.ruler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ruler"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation": {
      "abstract": [
        {
          "text": "Replicate sequences of interactions and make sure that your app’s user interface behaves as intended.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
      "kind": "symbol",
      "role": "collection",
      "title": "XCUIAutomation",
      "type": "topic",
      "url": "/documentation/xcuiautomation"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType": {
      "abstract": [
        {
          "text": "The types of UI elements that you find, inspect, and interact with in a UI test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/activityIndicator": {
      "abstract": [
        {
          "text": "A constant that represents an element type for activity indicator views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityIndicator"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/activityIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeActivityIndicator"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.activityIndicator",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/activityindicator"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/alert": {
      "abstract": [
        {
          "text": "A constant that represents an element type for alert views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alert"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/alert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeAlert"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.alert",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/alert"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/any": {
      "abstract": [
        {
          "text": "A constant that represents an element type for any view or control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeAny"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.any",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/any"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/application": {
      "abstract": [
        {
          "text": "A constant that represents an element type for an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/application",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeApplication"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.application",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/application"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/browser": {
      "abstract": [
        {
          "text": "A constant that represents an element type for a browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browser"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/browser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeBrowser"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.browser",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/browser"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/button": {
      "abstract": [
        {
          "text": "A constant that represents an element type for button controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeButton"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.button",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/button"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/cell": {
      "abstract": [
        {
          "text": "A constant that represents an element type for cells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cell"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/cell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeCell"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.cell",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/cell"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/checkBox": {
      "abstract": [
        {
          "text": "A constant that represents an element type for checkbox controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkBox"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/checkBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeCheckBox"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.checkBox",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/checkbox"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/collectionView": {
      "abstract": [
        {
          "text": "A constant that represents an element type for collection views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/collectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeCollectionView"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.collectionView",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/collectionview"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/colorWell": {
      "abstract": [
        {
          "text": "A constant that represents an element type for color-well controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorWell"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/colorWell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeColorWell"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.colorWell",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/colorwell"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/comboBox": {
      "abstract": [
        {
          "text": "A constant that represents an element type for combo-box controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comboBox"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/comboBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeComboBox"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.comboBox",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/combobox"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/datePicker": {
      "abstract": [
        {
          "text": "A constant that represents an element type for date-picker controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datePicker"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/datePicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeDatePicker"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.datePicker",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/datepicker"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/decrementArrow": {
      "abstract": [
        {
          "text": "A constant that represents an element type for decrement arrow controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementArrow"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/decrementArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeDecrementArrow"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.decrementArrow",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/decrementarrow"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/dialog": {
      "abstract": [
        {
          "text": "A constant that represents an element type for dialog views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialog"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/dialog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeDialog"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.dialog",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/dialog"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/disclosureTriangle": {
      "abstract": [
        {
          "text": "A constant that represents an element type for disclosure-triangle controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disclosureTriangle"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/disclosureTriangle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeDisclosureTriangle"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.disclosureTriangle",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/disclosuretriangle"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/ruler": {
      "abstract": [
        {
          "text": "A constant that represents an element type for ruler views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ruler"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/ruler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeRuler"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType.ruler",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/elementtype/ruler"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/activityIndicator",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/alert",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/any",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/application",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/browser",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/button",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/cell",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/checkBox",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/collectionView",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/colorWell",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/comboBox",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/datePicker",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/decrementArrow",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/dialog",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/disclosureTriangle"
      ],
      "title": "Enumeration cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.3",
              "name": "Xcode",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIElementTypeRuler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeRuler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/activityIndicator",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/alert",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/any",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/application",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/browser",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/button",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/cell",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/checkBox",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/collectionView",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/colorWell",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/comboBox",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/datePicker",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/decrementArrow",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/dialog",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/ElementType/disclosureTriangle"
              ],
              "title": "Enumeration cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCUIElementTypeRuler"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1activityIndicator/title",
          "value": "XCUIElementTypeActivityIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1activityIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeActivityIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1disclosureTriangle/title",
          "value": "XCUIElementTypeDisclosureTriangle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1disclosureTriangle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeDisclosureTriangle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1datePicker/title",
          "value": "XCUIElementTypeDatePicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1datePicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeDatePicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1browser/title",
          "value": "XCUIElementTypeBrowser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1browser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1button/title",
          "value": "XCUIElementTypeButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1button/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1dialog/title",
          "value": "XCUIElementTypeDialog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1dialog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeDialog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1cell/title",
          "value": "XCUIElementTypeCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1cell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1alert/title",
          "value": "XCUIElementTypeAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1alert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1application/title",
          "value": "XCUIElementTypeApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1application/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1ruler/title",
          "value": "XCUIElementTypeRuler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1ruler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeRuler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType/title",
          "value": "XCUIElementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1comboBox/title",
          "value": "XCUIElementTypeComboBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1comboBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeComboBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1checkBox/title",
          "value": "XCUIElementTypeCheckBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1checkBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeCheckBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1colorWell/title",
          "value": "XCUIElementTypeColorWell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1colorWell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeColorWell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1collectionView/title",
          "value": "XCUIElementTypeCollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1collectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeCollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1decrementArrow/title",
          "value": "XCUIElementTypeDecrementArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1decrementArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeDecrementArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1any/title",
          "value": "XCUIElementTypeAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1ElementType~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeAny"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcuiautomation/xcuielement/elementtype/ruler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcuiautomation/xcuielement/elementtype/ruler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
