{
  "abstract": [
    {
      "text": "A value that describes the display mode of an indicator.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/displayMode-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextInsertionIndicator(py)displayMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "displayMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTextInsertionIndicator",
        "text": "NSTextInsertionIndicator"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTextInsertionIndicatorDisplayMode",
        "text": "DisplayMode"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "displayMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "displayMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "displayMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextInsertionIndicator",
              "text": "NSTextInsertionIndicator"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTextInsertionIndicatorDisplayMode",
              "text": "DisplayMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/displayMode-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/automatic",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when your custom view becomes the first responder. When your custom view resigns first responder, set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/displayMode-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/hidden",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to indicate that key events aren’t sent to your view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator": {
      "abstract": [
        {
          "text": "A view that represents the insertion indicator in text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicator"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct": {
      "abstract": [
        {
          "text": "Options that affect the automatic display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutomaticModeOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutomaticModeOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.AutomaticModeOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/automaticmodeoptions-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that determine how to display the system text cursor in a custom text UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/automatic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicatorDisplayModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode.automatic",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum/automatic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/hidden": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/hidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicatorDisplayModeHidden"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode.hidden",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum/hidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/automaticModeOptions-swift.property": {
      "abstract": [
        {
          "text": "Options that affect the automatic display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticModeOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextInsertionIndicator",
          "text": "NSTextInsertionIndicator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInsertionIndicatorAutomaticModeOptions",
          "text": "AutomaticModeOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/automaticModeOptions-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticModeOptions"
        }
      ],
      "role": "symbol",
      "title": "automaticModeOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/automaticmodeoptions-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/displayMode-swift.property": {
      "abstract": [
        {
          "text": "A value that describes the display mode of an indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextInsertionIndicator",
          "text": "NSTextInsertionIndicator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInsertionIndicatorDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/displayMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayMode"
        }
      ],
      "role": "symbol",
      "title": "displayMode",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-display-mode",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/automaticModeOptions-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum"
      ],
      "title": "Setting the display mode"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-the-display-mode",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/automaticModeOptions-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum"
              ],
              "title": "Setting the display mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSTextInsertionIndicatorDisplayMode",
                    "text": "NSTextInsertionIndicatorDisplayMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "displayMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1automatic/title",
          "value": "NSTextInsertionIndicatorDisplayModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/title",
          "value": "NSTextInsertionIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1hidden/title",
          "value": "NSTextInsertionIndicatorDisplayModeHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1hidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayModeHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1automaticModeOptions-swift.property/title",
          "value": "automaticModeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1automaticModeOptions-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1displayMode-swift.property/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1displayMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/title",
          "value": "NSTextInsertionIndicatorAutomaticModeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/title",
          "value": "NSTextInsertionIndicatorDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextinsertionindicator/displaymode-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextinsertionindicator/displaymode-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
