{
  "abstract": [
    {
      "text": "Error codes that Metal can generate when creating dynamic libraries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLDynamicLibraryError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLDynamicLibraryError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when compiling dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that Metal can generate when creating dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure": {
      "abstract": [
        {
          "text": "An error code that indicates Metal couldn’t compile a dynamic library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compilationFailure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorCompilationFailure"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.compilationFailure",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/compilationfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure": {
      "abstract": [
        {
          "text": "An error code that indicates a dynamic library couldn’t link to other dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dependencyLoadFailure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorDependencyLoadFailure"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.dependencyLoadFailure",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/dependencyloadfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile": {
      "abstract": [
        {
          "text": "An error code that indicates an app is using an invalid reference to a library file, typically related to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFile"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorInvalidFile"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.invalidFile",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/invalidfile"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none": {
      "abstract": [
        {
          "text": "An error code that represents the absence of any problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorNone"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.none",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/none"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName": {
      "abstract": [
        {
          "text": "An error code that indicates Metal couldn’t resolve the installation name for a new dynamic library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unresolvedInstallName"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorUnresolvedInstallName"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.unresolvedInstallName",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/unresolvedinstallname"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU device doesn’t support dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryErrorUnsupported"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code/unsupported"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/compilationFailure": {
      "abstract": [
        {
          "text": "An error code that indicates Metal couldn’t compile a dynamic library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compilationFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/compilationFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "compilationFailure",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/compilationfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/dependencyLoadFailure": {
      "abstract": [
        {
          "text": "An error code that indicates a dynamic library couldn’t link to other dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dependencyLoadFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/dependencyLoadFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "dependencyLoadFailure",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/dependencyloadfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/invalidFile": {
      "abstract": [
        {
          "text": "An error code that indicates an app is using an invalid reference to a library file, typically related to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/invalidFile",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidFile",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/invalidfile"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/none": {
      "abstract": [
        {
          "text": "An error code that represents the absence of any problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/none",
      "kind": "symbol",
      "role": "symbol",
      "title": "none",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/none"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unresolvedInstallName": {
      "abstract": [
        {
          "text": "An error code that indicates Metal couldn’t resolve the installation name for a new dynamic library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unresolvedInstallName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unresolvedInstallName",
      "kind": "symbol",
      "role": "symbol",
      "title": "unresolvedInstallName",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/unresolvedinstallname"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unsupported": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU device doesn’t support dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unsupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupported",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/unsupported"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/none",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/invalidFile",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/compilationFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unresolvedInstallName",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/dependencyLoadFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unsupported"
      ],
      "title": "Error Codes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLDynamicLibraryError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/none",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/invalidFile",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/compilationFailure",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unresolvedInstallName",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/dependencyLoadFailure",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code/unsupported"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLDynamicLibraryError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1unresolvedInstallName/title",
          "value": "MTLDynamicLibraryErrorUnresolvedInstallName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1unresolvedInstallName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorUnresolvedInstallName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1compilationFailure/title",
          "value": "MTLDynamicLibraryErrorCompilationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1compilationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorCompilationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1invalidFile/title",
          "value": "MTLDynamicLibraryErrorInvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1invalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorInvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1dependencyLoadFailure/title",
          "value": "MTLDynamicLibraryErrorDependencyLoadFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1dependencyLoadFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorDependencyLoadFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1none/title",
          "value": "MTLDynamicLibraryErrorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/title",
          "value": "MTLDynamicLibraryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1unsupported/title",
          "value": "MTLDynamicLibraryErrorUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryErrorUnsupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldynamiclibraryerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldynamiclibraryerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
