{
  "abstract": [
    {
      "text": "An error code that indicates an app is using an invalid reference to a library file, typically related to a URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/invalidFile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC22MTLDynamicLibraryErrorLeV11invalidFileSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidFile"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
        "text": "MTLDynamicLibraryError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "invalidFile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidFile"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
              "text": "MTLDynamicLibraryError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when compiling dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that Metal can generate when creating dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/compilationFailure": {
      "abstract": [
        {
          "text": "An error code that indicates Metal couldn’t compile a dynamic library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compilationFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/compilationFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "compilationFailure",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/compilationfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/dependencyLoadFailure": {
      "abstract": [
        {
          "text": "An error code that indicates a dynamic library couldn’t link to other dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dependencyLoadFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/dependencyLoadFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "dependencyLoadFailure",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/dependencyloadfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/invalidFile": {
      "abstract": [
        {
          "text": "An error code that indicates an app is using an invalid reference to a library file, typically related to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/invalidFile",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidFile",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/invalidfile"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/none": {
      "abstract": [
        {
          "text": "An error code that represents the absence of any problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/none",
      "kind": "symbol",
      "role": "symbol",
      "title": "none",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/none"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unresolvedInstallName": {
      "abstract": [
        {
          "text": "An error code that indicates Metal couldn’t resolve the installation name for a new dynamic library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unresolvedInstallName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unresolvedInstallName",
      "kind": "symbol",
      "role": "symbol",
      "title": "unresolvedInstallName",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/unresolvedinstallname"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unsupported": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU device doesn’t support dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22MTLDynamicLibraryErrorLeV",
          "text": "MTLDynamicLibraryError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDynamicLibraryError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unsupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupported",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/unsupported"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/none",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/compilationFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unresolvedInstallName",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/dependencyLoadFailure",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/unsupported",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/title",
          "value": "MTLDynamicLibraryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldynamiclibraryerror-swift.struct/invalidfile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
