{
  "abstract": [
    {
      "text": "Scroll so that the bounding box of the selected items is centered vertically in the collection view’s bounds. This option must not be combined with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/top",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/bottom",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", or ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestHorizontalEdge",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " options, but may be combined with other options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredVertically"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSCollectionViewScrollPosition@NSCollectionViewScrollPositionCenteredVertically",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "centeredVertically"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSCollectionView",
        "text": "NSCollectionView"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
        "text": "ScrollPosition"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCollectionViewScrollPositionCenteredVertically"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "centeredVertically"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "centeredVertically"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCollectionView",
              "text": "NSCollectionView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
              "text": "ScrollPosition"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView": {
      "abstract": [
        {
          "text": "An ordered collection of data items displayed in a customizable layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionView"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionView",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition": {
      "abstract": [
        {
          "text": "Constants indicating the options for scrolling the collection view’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScrollPosition"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionView.ScrollPosition",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/bottom": {
      "abstract": [
        {
          "text": "Scroll so that the bottom edge of the bounding box is adjacent to the bottom of the collection view’s bounds. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/top",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredVertically",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestHorizontalEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionBottom"
        }
      ],
      "role": "symbol",
      "title": "bottom",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/bottom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally": {
      "abstract": [
        {
          "text": "Scroll so that the selected items’ bounding box is centered horizontally in the collection view’s bounds. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ",  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centeredHorizontally"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionCenteredHorizontally"
        }
      ],
      "role": "symbol",
      "title": "centeredHorizontally",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/centeredhorizontally"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredVertically": {
      "abstract": [
        {
          "text": "Scroll so that the bounding box of the selected items is centered vertically in the collection view’s bounds. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/top",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/bottom",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestHorizontalEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centeredVertically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredVertically",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionCenteredVertically"
        }
      ],
      "role": "symbol",
      "title": "centeredVertically",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/centeredvertically"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge": {
      "abstract": [
        {
          "text": "Scroll so that the leading edge of the selected items’ bounding box is adjacent to the leading edge of the collection view’s bounds. Use this option to support both left-to-right and right-to-left layouts appropriately. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leadingEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionLeadingEdge"
        }
      ],
      "role": "symbol",
      "title": "leadingEdge",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/leadingedge"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left": {
      "abstract": [
        {
          "text": "Scroll so that the left edge of the selected items’ bounding box is adjacent to the left edge of the collection view’s bounds. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionLeft"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/left"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestHorizontalEdge": {
      "abstract": [
        {
          "text": "Scroll so that the bounding box is adjacent to the nearest edge (top or bottom) of the collection view. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/top",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredVertically",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/bottom",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nearestHorizontalEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestHorizontalEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionNearestHorizontalEdge"
        }
      ],
      "role": "symbol",
      "title": "nearestHorizontalEdge",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/nearesthorizontaledge"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge": {
      "abstract": [
        {
          "text": "Scroll so that the bounding box is adjacent to the nearest edge (leading or trailing) of the collection view. Use this option to support both left-to-right and right-to-left layouts appropriately. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nearestVerticalEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionNearestVerticalEdge"
        }
      ],
      "role": "symbol",
      "title": "nearestVerticalEdge",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/nearestverticaledge"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right": {
      "abstract": [
        {
          "text": "Scroll so that the right edge of the selected items’ bounding box is adjacent to the right edge of the collection view’s bounds. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionRight"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/right"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/top": {
      "abstract": [
        {
          "text": "Scroll so that the top edge of the selected items’ bounding box is adjacent to the top edge of the collection view’s bounds. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredVertically",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/bottom",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestHorizontalEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionTop"
        }
      ],
      "role": "symbol",
      "title": "top",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/top"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge": {
      "abstract": [
        {
          "text": "Scroll so that the trailing edge of the selected items’ bounding box is adjacent to the trailing edge of the collection view’s bounds. Use this option to support both left-to-right and right-to-left layouts appropriately. This option must not be combined with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options, but may be combined with other options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollPosition",
          "text": "ScrollPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionTrailingEdge"
        }
      ],
      "role": "symbol",
      "title": "trailingEdge",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview/scrollposition/trailingedge"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewScrollPosition/NSCollectionViewScrollPositionNone": {
      "abstract": [
        {
          "text": "Do not scroll.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewScrollPositionNone"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewScrollPosition/NSCollectionViewScrollPositionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCollectionViewScrollPositionNone",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewscrollposition/nscollectionviewscrollpositionnone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/top",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/bottom",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestHorizontalEdge",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCollectionViewScrollPositionCenteredVertically"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionCenteredVertically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/top",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/bottom",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestHorizontalEdge",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/left",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/centeredHorizontally",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/right",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/leadingEdge",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/trailingEdge",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView/ScrollPosition/nearestVerticalEdge",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewScrollPosition/NSCollectionViewScrollPositionNone"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSCollectionViewScrollPositionCenteredVertically"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition/title",
          "value": "NSCollectionViewScrollPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1trailingEdge/title",
          "value": "NSCollectionViewScrollPositionTrailingEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1trailingEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionTrailingEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1bottom/title",
          "value": "NSCollectionViewScrollPositionBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1centeredHorizontally/title",
          "value": "NSCollectionViewScrollPositionCenteredHorizontally"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1centeredHorizontally/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionCenteredHorizontally"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1left/title",
          "value": "NSCollectionViewScrollPositionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1nearestVerticalEdge/title",
          "value": "NSCollectionViewScrollPositionNearestVerticalEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1nearestVerticalEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionNearestVerticalEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/title",
          "value": "NSCollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1centeredVertically/title",
          "value": "NSCollectionViewScrollPositionCenteredVertically"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1centeredVertically/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionCenteredVertically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1top/title",
          "value": "NSCollectionViewScrollPositionTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1right/title",
          "value": "NSCollectionViewScrollPositionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1nearestHorizontalEdge/title",
          "value": "NSCollectionViewScrollPositionNearestHorizontalEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1nearestHorizontalEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionNearestHorizontalEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1leadingEdge/title",
          "value": "NSCollectionViewScrollPositionLeadingEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1ScrollPosition~1leadingEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewScrollPositionLeadingEdge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscollectionview/scrollposition/centeredvertically"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscollectionview/scrollposition/centeredvertically"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
