{
  "abstract": [
    {
      "text": "Sets a limit on the number of partipants that a group may contain before the coordinator stops waiting on suspensions that occur for a particular reason.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/setParticipantLimit(_:forWaitingOutSuspensionsWithReason:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVPlaybackCoordinator(im)setParticipantLimit:forWaitingOutSuspensionsWithReason:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setParticipantLimit"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "forWaitingOutSuspensionsWithReason"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
        "text": "AVCoordinatedPlaybackSuspension"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
        "text": "Reason"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setParticipantLimit:forWaitingOutSuspensionsWithReason:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setParticipantLimit(_:forWaitingOutSuspensionsWithReason:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setParticipantLimit"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "participantLimit"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "forWaitingOutSuspensionsWithReason"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "reason"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
              "text": "AVCoordinatedPlaybackSuspension"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
              "text": "Reason"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of participants.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "participantLimit"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The suspension reason to set a limit for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "reason"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method provides additional configuration of the values your app sets for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/suspensionReasonsThatTriggerWaiting",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. When a coordinator decides whether one participant’s suspensions cause others to wait, it also considers any participant limits that you set on the group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension": {
      "abstract": [
        {
          "text": "An object that represents a temporary suspension of coordinated playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspension"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspension"
        }
      ],
      "role": "symbol",
      "title": "AVCoordinatedPlaybackSuspension",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct": {
      "abstract": [
        {
          "text": "Constants that identify playback suspension reasons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "role": "symbol",
      "title": "AVCoordinatedPlaybackSuspension.Reason",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator": {
      "abstract": [
        {
          "text": "An object that coordinates the playback of players in a connected group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlaybackCoordinator"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlaybackCoordinator"
        }
      ],
      "role": "symbol",
      "title": "AVPlaybackCoordinator",
      "type": "topic",
      "url": "/documentation/avfoundation/avplaybackcoordinator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/participantLimitForWaitingOutSuspensions(withReason:)": {
      "abstract": [
        {
          "text": "Returns the limit on the number of partipants that a group may contain before the coordinator stops waiting on suspensions that occur for a particular reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "participantLimitForWaitingOutSuspensions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/participantLimitForWaitingOutSuspensions(withReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "participantLimitForWaitingOutSuspensionsWithReason:"
        }
      ],
      "role": "symbol",
      "title": "participantLimitForWaitingOutSuspensions(withReason:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplaybackcoordinator/participantlimitforwaitingoutsuspensions(withreason:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/pauseSnapsToMediaTimeOfOriginator": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether participants mirror the originator’s stop time when they pause.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseSnapsToMediaTimeOfOriginator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/pauseSnapsToMediaTimeOfOriginator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseSnapsToMediaTimeOfOriginator"
        }
      ],
      "role": "symbol",
      "title": "pauseSnapsToMediaTimeOfOriginator",
      "type": "topic",
      "url": "/documentation/avfoundation/avplaybackcoordinator/pausesnapstomediatimeoforiginator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/setParticipantLimit(_:forWaitingOutSuspensionsWithReason:)": {
      "abstract": [
        {
          "text": "Sets a limit on the number of partipants that a group may contain before the coordinator stops waiting on suspensions that occur for a particular reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setParticipantLimit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forWaitingOutSuspensionsWithReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/setParticipantLimit(_:forWaitingOutSuspensionsWithReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setParticipantLimit:forWaitingOutSuspensionsWithReason:"
        }
      ],
      "role": "symbol",
      "title": "setParticipantLimit(_:forWaitingOutSuspensionsWithReason:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplaybackcoordinator/setparticipantlimit(_:forwaitingoutsuspensionswithreason:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/suspensionReasonsThatTriggerWaiting": {
      "abstract": [
        {
          "text": "The reasons that cause a coordinator to suspend playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspensionReasonsThatTriggerWaiting"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/suspensionReasonsThatTriggerWaiting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suspensionReasonsThatTriggerWaiting"
        }
      ],
      "role": "symbol",
      "title": "suspensionReasonsThatTriggerWaiting",
      "type": "topic",
      "url": "/documentation/avfoundation/avplaybackcoordinator/suspensionreasonsthattriggerwaiting"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Playback-Policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/participantLimitForWaitingOutSuspensions(withReason:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/suspensionReasonsThatTriggerWaiting",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/pauseSnapsToMediaTimeOfOriginator"
      ],
      "title": "Configuring Playback Policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setParticipantLimit:forWaitingOutSuspensionsWithReason:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setParticipantLimit:forWaitingOutSuspensionsWithReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Playback-Policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/participantLimitForWaitingOutSuspensions(withReason:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/suspensionReasonsThatTriggerWaiting",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/pauseSnapsToMediaTimeOfOriginator"
              ],
              "title": "Configuring Playback Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setParticipantLimit:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "participantLimit"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forWaitingOutSuspensionsWithReason:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
                    "text": "AVCoordinatedPlaybackSuspensionReason"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "reason"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of participants.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "participantLimit"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The suspension reason to set a limit for.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "reason"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension/title",
          "value": "AVCoordinatedPlaybackSuspension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator~1pauseSnapsToMediaTimeOfOriginator/title",
          "value": "pauseSnapsToMediaTimeOfOriginator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator~1pauseSnapsToMediaTimeOfOriginator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pauseSnapsToMediaTimeOfOriginator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator/title",
          "value": "AVPlaybackCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlaybackCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlaybackCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator~1setParticipantLimit(_:forWaitingOutSuspensionsWithReason:)/title",
          "value": "setParticipantLimit:forWaitingOutSuspensionsWithReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator~1setParticipantLimit(_:forWaitingOutSuspensionsWithReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setParticipantLimit:forWaitingOutSuspensionsWithReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator~1participantLimitForWaitingOutSuspensions(withReason:)/title",
          "value": "participantLimitForWaitingOutSuspensionsWithReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator~1participantLimitForWaitingOutSuspensions(withReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "participantLimitForWaitingOutSuspensionsWithReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator~1suspensionReasonsThatTriggerWaiting/title",
          "value": "suspensionReasonsThatTriggerWaiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator~1suspensionReasonsThatTriggerWaiting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "suspensionReasonsThatTriggerWaiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/title",
          "value": "AVCoordinatedPlaybackSuspensionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avplaybackcoordinator/setparticipantlimit(_:forwaitingoutsuspensionswithreason:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avplaybackcoordinator/setparticipantlimit(_:forwaitingoutsuspensionswithreason:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
