{
  "abstract": [
    {
      "text": "A state that indicates the current interaction ended.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/ended"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIBandSelectionInteractionState@UIBandSelectionInteractionStateEnded",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ended"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIBandSelectionInteractionStateEnded"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIBandSelectionInteraction.State.ended"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ended"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this state to finalize the interaction. For example, you might finalize the selection of items in your view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction": {
      "abstract": [
        {
          "text": "An object that tracks the selection of multiple items using pointer-based input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBandSelectionInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBandSelectionInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIBandSelectionInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate whether a band selection interaction object is inactive or currently tracking an interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "UIBandSelectionInteraction.State",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/state-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/began": {
      "abstract": [
        {
          "text": "A state that indicates the interaction object began a new interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "began"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/began",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBandSelectionInteractionStateBegan"
        }
      ],
      "role": "symbol",
      "title": "UIBandSelectionInteraction.State.began",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/state-swift.enum/began"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/ended": {
      "abstract": [
        {
          "text": "A state that indicates the current interaction ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBandSelectionInteractionStateEnded"
        }
      ],
      "role": "symbol",
      "title": "UIBandSelectionInteraction.State.ended",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/state-swift.enum/ended"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/possible": {
      "abstract": [
        {
          "text": "A state that indicates the interaction object is ready to start a new interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "possible"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/possible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBandSelectionInteractionStatePossible"
        }
      ],
      "role": "symbol",
      "title": "UIBandSelectionInteraction.State.possible",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/state-swift.enum/possible"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/selecting": {
      "abstract": [
        {
          "text": "A state that indicates the interaction object is tracking changes to the selection rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selecting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/selecting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBandSelectionInteractionStateSelecting"
        }
      ],
      "role": "symbol",
      "title": "UIBandSelectionInteraction.State.selecting",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/state-swift.enum/selecting"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-selection-state",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/possible",
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/began",
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/selecting"
      ],
      "title": "Getting the selection state"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIBandSelectionInteractionStateEnded"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionStateEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-selection-state",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/possible",
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/began",
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum/selecting"
              ],
              "title": "Getting the selection state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIBandSelectionInteractionStateEnded"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum~1ended/title",
          "value": "UIBandSelectionInteractionStateEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionStateEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum~1began/title",
          "value": "UIBandSelectionInteractionStateBegan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum~1began/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionStateBegan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction/title",
          "value": "UIBandSelectionInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum~1selecting/title",
          "value": "UIBandSelectionInteractionStateSelecting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum~1selecting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionStateSelecting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum/title",
          "value": "UIBandSelectionInteractionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum~1possible/title",
          "value": "UIBandSelectionInteractionStatePossible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum~1possible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionStatePossible"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibandselectioninteraction/state-swift.enum/ended"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uibandselectioninteraction/state-swift.enum/ended"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
