{
  "abstract": [
    {
      "text": "The user has an O– blood type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/oNegative"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKBloodType@HKBloodTypeONegative",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "oNegative"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKBloodTypeONegative"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKBloodType.oNegative"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "oNegative"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType": {
      "abstract": [
        {
          "text": "Constants indicating the user’s blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/aNegative": {
      "abstract": [
        {
          "text": "The user has an A– blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aNegative"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/aNegative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeANegative"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.aNegative",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/anegative"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/aPositive": {
      "abstract": [
        {
          "text": "The user has an A+ blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aPositive"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/aPositive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeAPositive"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.aPositive",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/apositive"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/abNegative": {
      "abstract": [
        {
          "text": "The user has an AB– blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "abNegative"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/abNegative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeABNegative"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.abNegative",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/abnegative"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/abPositive": {
      "abstract": [
        {
          "text": "The user has an AB+ blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "abPositive"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/abPositive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeABPositive"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.abPositive",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/abpositive"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/bNegative": {
      "abstract": [
        {
          "text": "The user has an B– blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bNegative"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/bNegative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeBNegative"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.bNegative",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/bnegative"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/bPositive": {
      "abstract": [
        {
          "text": "The user has an B+ blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bPositive"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/bPositive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeBPositive"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.bPositive",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/bpositive"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/notSet": {
      "abstract": [
        {
          "text": "Either the user’s blood type is not set, or the user has not granted your app permission to read the blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSet"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/notSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeNotSet"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.notSet",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/notset"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/oNegative": {
      "abstract": [
        {
          "text": "The user has an O– blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oNegative"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/oNegative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeONegative"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.oNegative",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/onegative"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/oPositive": {
      "abstract": [
        {
          "text": "The user has an O+ blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oPositive"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/oPositive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeOPositive"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType.oPositive",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype/opositive"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/notSet",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/aPositive",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/aNegative",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/bPositive",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/bNegative",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/abPositive",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/abNegative",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/oPositive"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKBloodTypeONegative"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeONegative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/notSet",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/aPositive",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/aNegative",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/bPositive",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/bNegative",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/abPositive",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/abNegative",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType/oPositive"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKBloodTypeONegative"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1oPositive/title",
          "value": "HKBloodTypeOPositive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1oPositive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeOPositive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1bNegative/title",
          "value": "HKBloodTypeBNegative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1bNegative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeBNegative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1aNegative/title",
          "value": "HKBloodTypeANegative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1aNegative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeANegative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1abNegative/title",
          "value": "HKBloodTypeABNegative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1abNegative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeABNegative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1aPositive/title",
          "value": "HKBloodTypeAPositive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1aPositive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeAPositive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1bPositive/title",
          "value": "HKBloodTypeBPositive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1bPositive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeBPositive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1notSet/title",
          "value": "HKBloodTypeNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1notSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1abPositive/title",
          "value": "HKBloodTypeABPositive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1abPositive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeABPositive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1oNegative/title",
          "value": "HKBloodTypeONegative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType~1oNegative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeONegative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/title",
          "value": "HKBloodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkbloodtype/onegative"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkbloodtype/onegative"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
