{
  "abstract": [
    {
      "text": "A value that represents selection by character.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/character"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextSelectionGranularity@NSTextSelectionGranularityCharacter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "character"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextSelectionGranularityCharacter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTextSelection.Granularity.character"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "character"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection": {
      "abstract": [
        {
          "text": "A class that represents a single logical selection context that corresponds to an insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelection"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum": {
      "abstract": [
        {
          "text": "Values that describe the different granularities available to make a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Granularity"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Granularity"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/character": {
      "abstract": [
        {
          "text": "A value that represents selection by character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "character"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/character",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularityCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.character",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/character"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/line": {
      "abstract": [
        {
          "text": "A value that represents selection by line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularityLine"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.line",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/line"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/paragraph": {
      "abstract": [
        {
          "text": "A value that represents selection by paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraph"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/paragraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularityParagraph"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.paragraph",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/paragraph"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/sentence": {
      "abstract": [
        {
          "text": "A value that represents selection by sentence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentence"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/sentence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularitySentence"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.sentence",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/sentence"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/word": {
      "abstract": [
        {
          "text": "A value that represents selection by word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "word"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/word",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionGranularityWord"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity.word",
      "type": "topic",
      "url": "/documentation/uikit/nstextselection/granularity-swift.enum/word"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Degrees-of-granularity",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/word",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/paragraph",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/line",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/sentence"
      ],
      "title": "Degrees of granularity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextSelectionGranularityCharacter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Degrees-of-granularity",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/word",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/paragraph",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/line",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelection/Granularity-swift.enum/sentence"
              ],
              "title": "Degrees of granularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextSelectionGranularityCharacter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1line/title",
          "value": "NSTextSelectionGranularityLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1character/title",
          "value": "NSTextSelectionGranularityCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1character/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum/title",
          "value": "NSTextSelectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection/title",
          "value": "NSTextSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1sentence/title",
          "value": "NSTextSelectionGranularitySentence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1sentence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularitySentence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1paragraph/title",
          "value": "NSTextSelectionGranularityParagraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1paragraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityParagraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1word/title",
          "value": "NSTextSelectionGranularityWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelection~1Granularity-swift.enum~1word/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularityWord"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextselection/granularity-swift.enum/character"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextselection/granularity-swift.enum/character"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
