{
  "abstract": [
    {
      "text": "The minimize button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/miniaturizeButton"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWindowButton@NSWindowMiniaturizeButton",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "miniaturizeButton"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWindowMiniaturizeButton"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSWindow.ButtonType.miniaturizeButton"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "miniaturizeButton"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType": {
      "abstract": [
        {
          "text": "Constants that provide a way to access standard title bar buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ButtonType",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/closeButton": {
      "abstract": [
        {
          "text": "The close button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closeButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/closeButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCloseButton"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ButtonType.closeButton",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype/closebutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/documentIconButton": {
      "abstract": [
        {
          "text": "The document icon button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentIconButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/documentIconButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowDocumentIconButton"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ButtonType.documentIconButton",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype/documenticonbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/documentVersionsButton": {
      "abstract": [
        {
          "text": "The document versions button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentVersionsButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/documentVersionsButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowDocumentVersionsButton"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ButtonType.documentVersionsButton",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype/documentversionsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/fullScreenButton": {
      "abstract": [
        {
          "text": "The fullscreen icon button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowButton",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/fullScreenButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowFullScreenButton"
        }
      ],
      "role": "symbol",
      "title": "fullScreenButton",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype/fullscreenbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/miniaturizeButton": {
      "abstract": [
        {
          "text": "The minimize button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miniaturizeButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/miniaturizeButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowMiniaturizeButton"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ButtonType.miniaturizeButton",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype/miniaturizebutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/toolbarButton": {
      "abstract": [
        {
          "text": "The toolbar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/toolbarButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowToolbarButton"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ButtonType.toolbarButton",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype/toolbarbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/zoomButton": {
      "abstract": [
        {
          "text": "The zoom button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/zoomButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowZoomButton"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ButtonType.zoomButton",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype/zoombutton"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/closeButton",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/zoomButton",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/toolbarButton",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/documentIconButton",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/documentVersionsButton",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/fullScreenButton"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWindowMiniaturizeButton"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowMiniaturizeButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/closeButton",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/zoomButton",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/toolbarButton",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/documentIconButton",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/documentVersionsButton",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType/fullScreenButton"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWindowMiniaturizeButton"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/title",
          "value": "NSWindowButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1documentVersionsButton/title",
          "value": "NSWindowDocumentVersionsButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1documentVersionsButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowDocumentVersionsButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1fullScreenButton/title",
          "value": "NSWindowFullScreenButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1fullScreenButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowFullScreenButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1closeButton/title",
          "value": "NSWindowCloseButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1closeButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCloseButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1documentIconButton/title",
          "value": "NSWindowDocumentIconButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1documentIconButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowDocumentIconButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1miniaturizeButton/title",
          "value": "NSWindowMiniaturizeButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1miniaturizeButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowMiniaturizeButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1toolbarButton/title",
          "value": "NSWindowToolbarButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1toolbarButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1zoomButton/title",
          "value": "NSWindowZoomButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType~1zoomButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowZoomButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow/buttontype/miniaturizebutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow/buttontype/miniaturizebutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
