{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/autocorrectionType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTextInputTraits(py)autocorrectionType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "autocorrectionType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTextInputTraitType",
        "text": "NSTextInputTraitType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "autocorrectionType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "autocorrectionType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "autocorrectionType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraitType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTextInputTraitType",
              "text": "NSTextInputTraitType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraitType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraitType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputTraitType"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputTraitType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraittype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputTraits"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputTraits",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/autocorrectionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autocorrectionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/autocorrectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autocorrectionType"
        }
      ],
      "role": "symbol",
      "title": "autocorrectionType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/autocorrectiontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/dataDetectionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataDetectionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/dataDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataDetectionType"
        }
      ],
      "role": "symbol",
      "title": "dataDetectionType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/datadetectiontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/grammarCheckingType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grammarCheckingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/grammarCheckingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "grammarCheckingType"
        }
      ],
      "role": "symbol",
      "title": "grammarCheckingType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/grammarcheckingtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/inlinePredictionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inlinePredictionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/inlinePredictionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inlinePredictionType"
        }
      ],
      "role": "symbol",
      "title": "inlinePredictionType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/inlinepredictiontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/linkDetectionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkDetectionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/linkDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkDetectionType"
        }
      ],
      "role": "symbol",
      "title": "linkDetectionType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/linkdetectiontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartDashesType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartDashesType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartDashesType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smartDashesType"
        }
      ],
      "role": "symbol",
      "title": "smartDashesType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/smartdashestype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartInsertDeleteType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartInsertDeleteType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartInsertDeleteType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smartInsertDeleteType"
        }
      ],
      "role": "symbol",
      "title": "smartInsertDeleteType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/smartinsertdeletetype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartQuotesType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartQuotesType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartQuotesType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smartQuotesType"
        }
      ],
      "role": "symbol",
      "title": "smartQuotesType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/smartquotestype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/spellCheckingType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spellCheckingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/spellCheckingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spellCheckingType"
        }
      ],
      "role": "symbol",
      "title": "spellCheckingType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/spellcheckingtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/textCompletionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textCompletionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/textCompletionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textCompletionType"
        }
      ],
      "role": "symbol",
      "title": "textCompletionType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/textcompletiontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/textReplacementType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textReplacementType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInputTraitType",
          "text": "NSTextInputTraitType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/textReplacementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textReplacementType"
        }
      ],
      "role": "symbol",
      "title": "textReplacementType",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/textreplacementtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/dataDetectionType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/grammarCheckingType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/inlinePredictionType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/linkDetectionType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartDashesType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartInsertDeleteType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartQuotesType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/spellCheckingType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/textCompletionType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/textReplacementType"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "autocorrectionType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autocorrectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/dataDetectionType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/grammarCheckingType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/inlinePredictionType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/linkDetectionType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartDashesType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartInsertDeleteType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/smartQuotesType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/spellCheckingType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/textCompletionType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/textReplacementType"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraitType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSTextInputTraitType",
                    "text": "NSTextInputTraitType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "autocorrectionType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1dataDetectionType/title",
          "value": "dataDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1dataDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1linkDetectionType/title",
          "value": "linkDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1linkDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits/title",
          "value": "NSTextInputTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1textCompletionType/title",
          "value": "textCompletionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1textCompletionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textCompletionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1autocorrectionType/title",
          "value": "autocorrectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1autocorrectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autocorrectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1grammarCheckingType/title",
          "value": "grammarCheckingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1grammarCheckingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "grammarCheckingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1smartDashesType/title",
          "value": "smartDashesType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1smartDashesType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "smartDashesType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1spellCheckingType/title",
          "value": "spellCheckingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1spellCheckingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spellCheckingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1inlinePredictionType/title",
          "value": "inlinePredictionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1inlinePredictionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inlinePredictionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1smartQuotesType/title",
          "value": "smartQuotesType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1smartQuotesType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "smartQuotesType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1textReplacementType/title",
          "value": "textReplacementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1textReplacementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textReplacementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1smartInsertDeleteType/title",
          "value": "smartInsertDeleteType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1smartInsertDeleteType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "smartInsertDeleteType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraitType/title",
          "value": "NSTextInputTraitType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraitType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputTraitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraitType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputTraitType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextinputtraits/autocorrectiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextinputtraits/autocorrectiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
