{
  "abstract": [
    {
      "text": "An object that represents the geometry preferences for a window scene in an iOS app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UIWindowSceneGeometryPreferencesIOS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "iOS"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "iOS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIWindowScene.GeometryPreferences.iOS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "iOS"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to express iOS-specific geometry preferences when you call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIProposedSceneSizeNoPreference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIProposedSceneSizeNoPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIProposedSceneSizeNoPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIProposedSceneSizeNoPreference"
        }
      ],
      "role": "symbol",
      "title": "UIProposedSceneSizeNoPreference",
      "type": "topic",
      "url": "/documentation/uikit/uiproposedscenesizenopreference"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene": {
      "abstract": [
        {
          "text": "A scene that manages one or more windows for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/Geometry": {
      "abstract": [
        {
          "text": "An object that provides geometry information about the window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Geometry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/Geometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Geometry"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.Geometry",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences": {
      "abstract": [
        {
          "text": "An abstract superclass for representing window scene geometry preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GeometryPreferences"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GeometryPreferences"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Mac": {
      "abstract": [
        {
          "text": "An object that represents the geometry preferences for a window scene in an app built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mac"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Mac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mac"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences.Mac",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/mac"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Vision"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Vision"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences.Vision",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/vision"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS": {
      "abstract": [
        {
          "text": "An object that represents the geometry preferences for a window scene in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iOS"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences.iOS",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/ios"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/init()": {
      "abstract": [
        {
          "text": "Initializes a new window scene geometry preferences object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/ios/init()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/init(interfaceOrientations:)": {
      "abstract": [
        {
          "text": "Initializes a new window scene geometry preferences object with the specified interface orientations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "interfaceOrientations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientationMask",
          "text": "UIInterfaceOrientationMask"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/init(interfaceOrientations:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithInterfaceOrientations:"
        }
      ],
      "role": "symbol",
      "title": "init(interfaceOrientations:)",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/ios/init(interfaceorientations:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/interfaceOrientations": {
      "abstract": [
        {
          "text": "The preferred interface orientations for the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceOrientations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientationMask",
          "text": "UIInterfaceOrientationMask"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/interfaceOrientations",
      "kind": "symbol",
      "role": "symbol",
      "title": "interfaceOrientations",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/ios/interfaceorientations"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry": {
      "abstract": [
        {
          "text": "The current values for the window scene’s geometry in system space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveGeometry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowSceneGeometry",
          "text": "Geometry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectiveGeometry"
        }
      ],
      "role": "symbol",
      "title": "effectiveGeometry",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/effectivegeometry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)": {
      "abstract": [
        {
          "text": "Requests an update to the window scene’s geometry using the specified geometry preferences object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestGeometryUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowSceneGeometryPreferences",
          "text": "GeometryPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "errorHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestGeometryUpdateWithPreferences:errorHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestGeometryUpdate(_:errorHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/requestgeometryupdate(_:errorhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneGeometryPreferencesIOS/interfaceOrientations": {
      "abstract": [
        {
          "text": "The preferred interface orientations for the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "interfaceOrientations"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneGeometryPreferencesIOS/interfaceOrientations",
      "kind": "symbol",
      "role": "symbol",
      "title": "interfaceOrientations",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscenegeometrypreferencesios/interfaceorientations"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Working-with-window-geometry",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/Geometry",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Mac",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision",
        "doc://com.apple.uikit/documentation/UIKit/UIProposedSceneSizeNoPreference"
      ],
      "title": "Working with window geometry"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-geometry-preferences-object",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/init(interfaceOrientations:)",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/init()"
      ],
      "title": "Creating a geometry preferences object"
    },
    {
      "anchor": "Requesting-preferred-interface-orientations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/interfaceOrientations"
      ],
      "title": "Requesting preferred interface orientations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIWindowSceneGeometryPreferencesIOS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesIOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesIOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-geometry-preferences-object",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/init(interfaceOrientations:)",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS/init()"
              ],
              "title": "Creating a geometry preferences object"
            },
            {
              "anchor": "Requesting-preferred-interface-orientations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneGeometryPreferencesIOS/interfaceOrientations"
              ],
              "title": "Requesting preferred interface orientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowSceneGeometryPreferencesIOS/interfaceOrientations"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Working-with-window-geometry",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/Geometry",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Mac",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision",
                "doc://com.apple.uikit/documentation/UIKit/UIProposedSceneSizeNoPreference"
              ],
              "title": "Working with window geometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIWindowSceneGeometryPreferencesIOS"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIWindowSceneGeometryPreferences",
                    "text": "UIWindowSceneGeometryPreferences"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1requestGeometryUpdate(_:errorHandler:)/title",
          "value": "requestGeometryUpdateWithPreferences:errorHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1requestGeometryUpdate(_:errorHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestGeometryUpdateWithPreferences:errorHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS/title",
          "value": "UIWindowSceneGeometryPreferencesIOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesIOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesIOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Mac/title",
          "value": "UIWindowSceneGeometryPreferencesMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Mac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Mac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS~1init(interfaceOrientations:)/title",
          "value": "initWithInterfaceOrientations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS~1init(interfaceOrientations:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithInterfaceOrientations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIProposedSceneSizeNoPreference/title",
          "value": "UIProposedSceneSizeNoPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIProposedSceneSizeNoPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIProposedSceneSizeNoPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/title",
          "value": "UIWindowScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1effectiveGeometry/title",
          "value": "effectiveGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1effectiveGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectiveGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/title",
          "value": "UIWindowSceneGeometryPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/title",
          "value": "UIWindowSceneGeometryPreferencesVision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1Geometry/title",
          "value": "UIWindowSceneGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1Geometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1Geometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometry"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/geometrypreferences/ios"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwindowscene/geometrypreferences/ios"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
