{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior"]]},"abstract":[{"type":"text","text":"The anchor point for the attachment behavior, if any."}],"seeAlsoSections":[{"generated":true,"anchor":"Configuring-an-attachment-behavior","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange"],"title":"Configuring an attachment behavior"}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"UIKit"}],"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"7.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"7.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorPoint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"navigatorTitle":[{"text":"anchorPoint","kind":"identifier"}],"title":"anchorPoint","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)UIAttachmentBehavior(py)anchorPoint"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiattachmentbehavior/anchorpoint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiattachmentbehavior/anchorpoint"]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorPoint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","identifier":"doc://com.externally.resolved.symbol/c:@S@CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The anchor point is relative to the coordinate system for the behavior’s associated dynamic animator. For attachment types without an anchor point, the value in this property is "},{"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgpointzero","type":"reference","isActive":true},{"type":"text","text":". For more information about the coordinate system of the reference view, see "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator","type":"reference","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:@S@CGPoint":{"role":"symbol","abstract":[{"type":"text","text":"A structure that contains a point in a two-dimensional coordinate system."}],"type":"topic","url":"/documentation/corefoundation/cgpoint","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@S@CGPoint","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGPoint"}],"title":"CGPoint"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange":{"abstract":[{"type":"text","text":"The range of motion for the attachment behavior."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange","kind":"symbol","title":"attachmentRange","navigatorTitle":[{"kind":"identifier","text":"attachmentRange"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@UIFloatRange","text":"UIFloatRange"}],"url":"/documentation/uikit/uiattachmentbehavior/attachmentrange"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency":{"abstract":[{"type":"text","text":"The frequency of oscillation for the attachment behavior."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","kind":"symbol","title":"frequency","navigatorTitle":[{"kind":"identifier","text":"frequency"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"/documentation/uikit/uiattachmentbehavior/frequency"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque":{"abstract":[{"type":"text","text":"The amount of force needed to overcome rotational forces around an anchor point."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque","kind":"symbol","title":"frictionTorque","navigatorTitle":[{"kind":"identifier","text":"frictionTorque"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frictionTorque"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"/documentation/uikit/uiattachmentbehavior/frictiontorque"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping":{"kind":"symbol","url":"/documentation/uikit/uiattachmentbehavior/damping","navigatorTitle":[{"kind":"identifier","text":"damping"}],"abstract":[{"text":"The amount of damping to apply to the attachment behavior.","type":"text"}],"title":"damping","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"damping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator":{"title":"UIDynamicAnimator","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIDynamicAnimator"}],"abstract":[{"type":"text","text":"An object that provides physics-related capabilities and animations for its dynamic items, and provides the context for those animations."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIDynamicAnimator"}],"kind":"symbol","url":"/documentation/uikit/uidynamicanimator"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType":{"abstract":[{"type":"text","text":"The type of the attachment behavior."}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachedBehaviorType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAttachmentBehavior","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIAttachmentBehavior"},{"text":".","kind":"text"},{"text":"AttachmentType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIAttachmentBehaviorType"}],"navigatorTitle":[{"text":"attachedBehaviorType","kind":"identifier"}],"title":"attachedBehaviorType","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","url":"/documentation/uikit/uiattachmentbehavior/attachedbehaviortype"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"length"}],"title":"length","type":"topic","url":"/documentation/uikit/uiattachmentbehavior/length","role":"symbol","abstract":[{"type":"text","text":"The distance, in points, between the two attachment points of the attachment behavior."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length"},"doc://com.apple.documentation/documentation/coregraphics/cgpointzero":{"title":"CGPointZero","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgpointzero","url":"/documentation/coregraphics/cgpointzero","kind":"symbol","abstract":[{"text":"A point constant with location `(0,0)`. The zero point is equivalent to `CGPointMake(0,0)`.","type":"text"}],"fragments":[{"kind":"text","text":"let "},{"kind":"identifier","text":"CGPointZero"},{"kind":"text","text":": CGPoint"}],"role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint","abstract":[{"type":"text","text":"The anchor point for the attachment behavior, if any."}],"navigatorTitle":[{"text":"anchorPoint","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorPoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"type":"topic","role":"symbol","title":"anchorPoint","url":"/documentation/uikit/uiattachmentbehavior/anchorpoint"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior","kind":"symbol","navigatorTitle":[{"text":"UIAttachmentBehavior","kind":"identifier"}],"type":"topic","title":"UIAttachmentBehavior","url":"/documentation/uikit/uiattachmentbehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIAttachmentBehavior","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A relationship between two dynamic items, or between a dynamic item and an anchor point."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"anchorPoint","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"anchorPoint"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Configuring-an-attachment-behavior","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange"],"generated":true,"title":"Configuring an attachment behavior"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":" ","kind":"text"},{"text":"anchorPoint","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachmentRange/title","op":"replace","value":"attachmentRange"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachmentRange/fragments","op":"replace","value":[{"text":"attachmentRange","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frequency/title","op":"replace","value":"frequency"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frequency/fragments","op":"replace","value":[{"text":"frequency","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frictionTorque/title","op":"replace","value":"frictionTorque"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frictionTorque/fragments","op":"replace","value":[{"kind":"identifier","text":"frictionTorque"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1damping/title","op":"replace","value":"damping"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1damping/fragments","op":"replace","value":[{"text":"damping","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/title","op":"replace","value":"UIDynamicAnimator"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/fragments","op":"replace","value":[{"text":"UIDynamicAnimator","kind":"identifier"}]},{"op":"replace","value":[{"text":"UIDynamicAnimator","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/navigatorTitle"},{"op":"replace","value":"attachedBehaviorType","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachedBehaviorType/title"},{"op":"replace","value":[{"text":"attachedBehaviorType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachedBehaviorType/fragments"},{"op":"replace","value":"length","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1length/title"},{"op":"replace","value":[{"text":"length","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1length/fragments"},{"op":"replace","value":"anchorPoint","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1anchorPoint/title"},{"op":"replace","value":[{"text":"anchorPoint","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1anchorPoint/fragments"},{"op":"replace","value":"UIAttachmentBehavior","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIAttachmentBehavior"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/fragments"},{"op":"replace","value":[{"text":"UIAttachmentBehavior","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}