{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiattachmentbehavior/frictiontorque"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiattachmentbehavior/frictiontorque"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frictionTorque","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"For attachments where each item rotates around an anchor point, use this property to specify the resistance to that rotation. The default value of this property is ","type":"text"},{"type":"codeVoice","code":"0.0"},{"text":", which causes items to rotate freely with even very small impulses. Higher torque values increase the amount of force needed to cause rotation.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property has no formal units, so you need to experiment with values to get the behavior that you want."}]}]}],"sections":[],"abstract":[{"text":"The amount of force needed to overcome rotational forces around an anchor point.","type":"text"}],"metadata":{"symbolKind":"property","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)UIAttachmentBehavior(py)frictionTorque","modules":[{"name":"UIKit"}],"role":"symbol","title":"frictionTorque","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frictionTorque","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"text":"frictionTorque","kind":"identifier"}]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange"],"generated":true,"title":"Configuring an attachment behavior","anchor":"Configuring-an-attachment-behavior"}],"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType":{"abstract":[{"type":"text","text":"The type of the attachment behavior."}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachedBehaviorType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAttachmentBehavior","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIAttachmentBehavior"},{"text":".","kind":"text"},{"text":"AttachmentType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIAttachmentBehaviorType"}],"navigatorTitle":[{"text":"attachedBehaviorType","kind":"identifier"}],"title":"attachedBehaviorType","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","url":"/documentation/uikit/uiattachmentbehavior/attachedbehaviortype"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping":{"kind":"symbol","url":"/documentation/uikit/uiattachmentbehavior/damping","navigatorTitle":[{"kind":"identifier","text":"damping"}],"abstract":[{"text":"The amount of damping to apply to the attachment behavior.","type":"text"}],"title":"damping","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"damping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque":{"abstract":[{"type":"text","text":"The amount of force needed to overcome rotational forces around an anchor point."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque","kind":"symbol","title":"frictionTorque","navigatorTitle":[{"kind":"identifier","text":"frictionTorque"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frictionTorque"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"/documentation/uikit/uiattachmentbehavior/frictiontorque"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency":{"abstract":[{"type":"text","text":"The frequency of oscillation for the attachment behavior."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","kind":"symbol","title":"frequency","navigatorTitle":[{"kind":"identifier","text":"frequency"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"/documentation/uikit/uiattachmentbehavior/frequency"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"length"}],"title":"length","type":"topic","url":"/documentation/uikit/uiattachmentbehavior/length","role":"symbol","abstract":[{"type":"text","text":"The distance, in points, between the two attachment points of the attachment behavior."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange":{"abstract":[{"type":"text","text":"The range of motion for the attachment behavior."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange","kind":"symbol","title":"attachmentRange","navigatorTitle":[{"kind":"identifier","text":"attachmentRange"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@UIFloatRange","text":"UIFloatRange"}],"url":"/documentation/uikit/uiattachmentbehavior/attachmentrange"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"kind":"symbol","role":"symbol","title":"CGFloat","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGFloat"}],"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for floating-point scalar values in Core Graphics and related frameworks."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"abstract":[{"type":"text","text":"The basic type for all floating-point values."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","role":"symbol","url":"/documentation/corefoundation/cgfloat","kind":"symbol","type":"topic","title":"CGFloat"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint","abstract":[{"type":"text","text":"The anchor point for the attachment behavior, if any."}],"navigatorTitle":[{"text":"anchorPoint","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorPoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"type":"topic","role":"symbol","title":"anchorPoint","url":"/documentation/uikit/uiattachmentbehavior/anchorpoint"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior","kind":"symbol","navigatorTitle":[{"text":"UIAttachmentBehavior","kind":"identifier"}],"type":"topic","title":"UIAttachmentBehavior","url":"/documentation/uikit/uiattachmentbehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIAttachmentBehavior","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A relationship between two dynamic items, or between a dynamic item and an anchor point."}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"9.0"},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"9.0"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.1"},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"9.0"},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"frictionTorque"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"frictionTorque"}]},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Configuring an attachment behavior","anchor":"Configuring-an-attachment-behavior","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange"]}],"op":"replace"},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"frictionTorque"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachedBehaviorType/title","value":"attachedBehaviorType","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachedBehaviorType/fragments","value":[{"text":"attachedBehaviorType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1damping/title","value":"damping","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1damping/fragments","value":[{"kind":"identifier","text":"damping"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frictionTorque/title","value":"frictionTorque","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frictionTorque/fragments","value":[{"text":"frictionTorque","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frequency/title","value":"frequency","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frequency/fragments","value":[{"text":"frequency","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1length/title","value":"length","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1length/fragments","value":[{"text":"length","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachmentRange/title","value":"attachmentRange","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachmentRange/fragments","value":[{"text":"attachmentRange","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1anchorPoint/title","value":"anchorPoint","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1anchorPoint/fragments","value":[{"text":"anchorPoint","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/title","value":"UIAttachmentBehavior","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/fragments","value":[{"kind":"identifier","text":"UIAttachmentBehavior"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/navigatorTitle","value":[{"text":"UIAttachmentBehavior","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}