{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["/documentation/uikit/uiattachmentbehavior/init(item:attachedto:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiattachmentbehavior/init(item:attachedto:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"item","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item1","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDynamicItem","preciseIdentifier":"c:objc(pl)UIDynamicItem","text":"UIDynamicItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"attachedTo","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item2","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDynamicItem","preciseIdentifier":"c:objc(pl)UIDynamicItem","text":"UIDynamicItem","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"item1","content":[{"type":"paragraph","inlineContent":[{"text":"The first of two dynamic items connected by the attachment behavior.","type":"text"}]}]},{"name":"item2","content":[{"inlineContent":[{"type":"text","text":"The second of two dynamic items connected by the attachment behavior."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The initialized attachment behavior, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if there was a problem initializing the object"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The behavior created by this method acts like a solid rod connecting the two items at their center points. Forces applied to one item push or pull the other item accordingly. The items are free to rotate around each other but always remain the same distance apart.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The attachment object returned by this method is of type ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/AttachmentType/items","type":"reference"},{"text":".","type":"text"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Initializes a behavior where the centers of two dynamic items are attached to each other."}],"seeAlsoSections":[{"generated":true,"anchor":"Creating-and-initializing-attachment-behavior-objects","title":"Creating and initializing attachment behavior objects","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/slidingAttachment(with:attachmentAnchor:axisOfTranslation:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/slidingAttachment(with:attachedTo:attachmentAnchor:axisOfTranslation:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/fixedAttachment(with:attachedTo:attachmentAnchor:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/limitAttachment(with:offsetFromCenter:attachedTo:offsetFromCenter:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/pinAttachment(with:attachedTo:attachmentAnchor:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:attachedToAnchor:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:offsetFromCenter:attachedToAnchor:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:offsetFromCenter:attachedTo:offsetFromCenter:)"]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:attachedTo:)","interfaceLanguage":"swift"},"metadata":{"title":"init(item:attachedTo:)","externalID":"c:objc(cs)UIAttachmentBehavior(im)initWithItem:attachedToItem:","role":"symbol","symbolKind":"init","modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDynamicItem","text":"UIDynamicItem"},{"text":", ","kind":"text"},{"text":"attachedTo","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDynamicItem","preciseIdentifier":"c:objc(pl)UIDynamicItem","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","platforms":[{"name":"iOS","introducedAt":"7.0","deprecated":false,"unavailable":false,"beta":false},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"7.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}],"navigatorTitle":[{"text":"initWithItem:attachedToItem:","kind":"identifier"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/fixedAttachment(with:attachedTo:attachmentAnchor:)":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/fixedAttachment(with:attachedTo:attachmentAnchor:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedAttachment"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDynamicItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDynamicItem"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attachedTo"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UIDynamicItem","preciseIdentifier":"c:objc(pl)UIDynamicItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attachmentAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"text":"Creates and returns an attachment behavior where the two items are fixed together through the specified anchor point.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fixedAttachmentWithItem:attachedToItem:attachmentAnchor:"}],"title":"fixedAttachment(with:attachedTo:attachmentAnchor:)","url":"/documentation/uikit/uiattachmentbehavior/fixedattachment(with:attachedto:attachmentanchor:)"},"doc://com.apple.uikit/documentation/UIKit/UIDynamicItem":{"url":"/documentation/uikit/uidynamicitem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDynamicItem","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that can make a custom object eligible to participate in UIKit Dynamics."}],"kind":"symbol","navigatorTitle":[{"text":"UIDynamicItem","kind":"identifier"}],"type":"topic","role":"symbol","title":"UIDynamicItem","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDynamicItem"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/AttachmentType/items":{"role":"symbol","url":"/documentation/uikit/uiattachmentbehavior/attachmenttype/items","title":"UIAttachmentBehavior.AttachmentType.items","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/AttachmentType/items","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"}],"abstract":[{"text":"Designates an attachment behavior that connects a dynamic item to another dynamic item.","type":"text"}],"navigatorTitle":[{"text":"UIAttachmentBehaviorTypeItems","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/slidingAttachment(with:attachmentAnchor:axisOfTranslation:)":{"kind":"symbol","title":"slidingAttachment(with:attachmentAnchor:axisOfTranslation:)","type":"topic","role":"symbol","url":"/documentation/uikit/uiattachmentbehavior/slidingattachment(with:attachmentanchor:axisoftranslation:)","abstract":[{"text":"Creates and returns an attachment behavior where one item slides along the specified axis.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"slidingAttachmentWithItem:attachmentAnchor:axisOfTranslation:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/slidingAttachment(with:attachmentAnchor:axisOfTranslation:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slidingAttachment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDynamicItem","kind":"typeIdentifier","text":"UIDynamicItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attachmentAnchor"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"axisOfTranslation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGVector","preciseIdentifier":"c:@S@CGVector"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior","kind":"symbol","navigatorTitle":[{"text":"UIAttachmentBehavior","kind":"identifier"}],"type":"topic","title":"UIAttachmentBehavior","url":"/documentation/uikit/uiattachmentbehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIAttachmentBehavior","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A relationship between two dynamic items, or between a dynamic item and an anchor point."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/limitAttachment(with:offsetFromCenter:attachedTo:offsetFromCenter:)":{"kind":"symbol","title":"limitAttachment(with:offsetFromCenter:attachedTo:offsetFromCenter:)","type":"topic","role":"symbol","url":"/documentation/uikit/uiattachmentbehavior/limitattachment(with:offsetfromcenter:attachedto:offsetfromcenter:)","abstract":[{"text":"Creates and returns an attachment behavior object where two items are constrained by a maximum distance from one another.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"limitAttachmentWithItem:offsetFromCenter:attachedToItem:offsetFromCenter:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/limitAttachment(with:offsetFromCenter:attachedTo:offsetFromCenter:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitAttachment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDynamicItem","kind":"typeIdentifier","text":"UIDynamicItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offsetFromCenter"},{"kind":"text","text":": "},{"text":"UIOffset","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIOffset"},{"text":", ","kind":"text"},{"text":"attachedTo","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDynamicItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDynamicItem"},{"text":", ","kind":"text"},{"text":"offsetFromCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIOffset","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIOffset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:offsetFromCenter:attachedToAnchor:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithItem:offsetFromCenter:attachedToAnchor:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:offsetFromCenter:attachedToAnchor:)","title":"init(item:offsetFromCenter:attachedToAnchor:)","abstract":[{"type":"text","text":"Initializes a behavior where the specified point in a dynamic item is attached to an anchor point."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDynamicItem","kind":"typeIdentifier","text":"UIDynamicItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offsetFromCenter"},{"text":": ","kind":"text"},{"text":"UIOffset","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIOffset"},{"text":", ","kind":"text"},{"text":"attachedToAnchor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"type":"topic","url":"/documentation/uikit/uiattachmentbehavior/init(item:offsetfromcenter:attachedtoanchor:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:offsetFromCenter:attachedTo:offsetFromCenter:)":{"kind":"symbol","title":"init(item:offsetFromCenter:attachedTo:offsetFromCenter:)","type":"topic","role":"symbol","url":"/documentation/uikit/uiattachmentbehavior/init(item:offsetfromcenter:attachedto:offsetfromcenter:)","abstract":[{"text":"Initializes an attachment behavior that connects a specified point in one dynamic item to a specified point in another dynamic item.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithItem:offsetFromCenter:attachedToItem:offsetFromCenter:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:offsetFromCenter:attachedTo:offsetFromCenter:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"item","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDynamicItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDynamicItem"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"offsetFromCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOffset","preciseIdentifier":"c:@S@UIOffset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attachedTo"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDynamicItem","kind":"typeIdentifier","text":"UIDynamicItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offsetFromCenter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIOffset","kind":"typeIdentifier","text":"UIOffset"},{"kind":"text","text":")"}]},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:attachedTo:)":{"kind":"symbol","title":"init(item:attachedTo:)","type":"topic","role":"symbol","url":"/documentation/uikit/uiattachmentbehavior/init(item:attachedto:)","abstract":[{"text":"Initializes a behavior where the centers of two dynamic items are attached to each other.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithItem:attachedToItem:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:attachedTo:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UIDynamicItem","preciseIdentifier":"c:objc(pl)UIDynamicItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attachedTo"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UIDynamicItem","preciseIdentifier":"c:objc(pl)UIDynamicItem"},{"kind":"text","text":")"}]},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/pinAttachment(with:attachedTo:attachmentAnchor:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pinAttachment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDynamicItem","preciseIdentifier":"c:objc(pl)UIDynamicItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"attachedTo","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDynamicItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDynamicItem"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attachmentAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pinAttachmentWithItem:attachedToItem:attachmentAnchor:"}],"title":"pinAttachment(with:attachedTo:attachmentAnchor:)","type":"topic","url":"/documentation/uikit/uiattachmentbehavior/pinattachment(with:attachedto:attachmentanchor:)","role":"symbol","abstract":[{"type":"text","text":"Creates and returns an attachment behavior where the two items are pinned to, and move around, an anchor point"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/pinAttachment(with:attachedTo:attachmentAnchor:)"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:attachedToAnchor:)":{"kind":"symbol","title":"init(item:attachedToAnchor:)","type":"topic","role":"symbol","url":"/documentation/uikit/uiattachmentbehavior/init(item:attachedtoanchor:)","abstract":[{"text":"Initializes a behavior where the center of a dynamic item is attached to the specified anchor point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithItem:attachedToAnchor:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:attachedToAnchor:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"item","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDynamicItem","kind":"typeIdentifier","text":"UIDynamicItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attachedToAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}]},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/slidingAttachment(with:attachedTo:attachmentAnchor:axisOfTranslation:)":{"kind":"symbol","title":"slidingAttachment(with:attachedTo:attachmentAnchor:axisOfTranslation:)","type":"topic","role":"symbol","url":"/documentation/uikit/uiattachmentbehavior/slidingattachment(with:attachedto:attachmentanchor:axisoftranslation:)","abstract":[{"text":"Creates and returns an attachment behavior where two items are fixed to points that slide along the specified axis.","type":"text"}],"navigatorTitle":[{"text":"slidingAttachmentWithItem:attachedToItem:attachmentAnchor:axisOfTranslation:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/slidingAttachment(with:attachedTo:attachmentAnchor:axisOfTranslation:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"slidingAttachment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDynamicItem","kind":"typeIdentifier","text":"UIDynamicItem"},{"kind":"text","text":", "},{"text":"attachedTo","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDynamicItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDynamicItem"},{"text":", ","kind":"text"},{"text":"attachmentAnchor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"axisOfTranslation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGVector","kind":"typeIdentifier","text":"CGVector"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"7.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"7.0","name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"initWithItem:attachedToItem:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithItem:attachedToItem:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Creating-and-initializing-attachment-behavior-objects","title":"Creating and initializing attachment behavior objects","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/slidingAttachment(with:attachmentAnchor:axisOfTranslation:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/slidingAttachment(with:attachedTo:attachmentAnchor:axisOfTranslation:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/fixedAttachment(with:attachedTo:attachmentAnchor:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/limitAttachment(with:offsetFromCenter:attachedTo:offsetFromCenter:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/pinAttachment(with:attachedTo:attachmentAnchor:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:attachedToAnchor:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:offsetFromCenter:attachedToAnchor:)","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/init(item:offsetFromCenter:attachedTo:offsetFromCenter:)"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIDynamicItem","text":"id<UIDynamicItem>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"item1"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachedToItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIDynamicItem","text":"id<UIDynamicItem>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"item2"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"parameters":[{"name":"item1","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The first of two dynamic items connected by the attachment behavior."}]}]},{"name":"item2","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The second of two dynamic items connected by the attachment behavior."}]}]}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"The initialized attachment behavior, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if there was a problem initializing the object","type":"text"}],"type":"paragraph"}]},"path":"/primaryContentSections/2","op":"replace"},{"value":"fixedAttachmentWithItem:attachedToItem:attachmentAnchor:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1fixedAttachment(with:attachedTo:attachmentAnchor:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fixedAttachmentWithItem:attachedToItem:attachmentAnchor:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1fixedAttachment(with:attachedTo:attachmentAnchor:)/fragments"},{"value":"UIDynamicItem","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/title"},{"value":[{"kind":"identifier","text":"UIDynamicItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/fragments"},{"value":[{"kind":"identifier","text":"UIDynamicItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/navigatorTitle"},{"value":"UIAttachmentBehaviorTypeItems","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1AttachmentType~1items/title"},{"value":[{"kind":"identifier","text":"UIAttachmentBehaviorTypeItems"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1AttachmentType~1items/fragments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1slidingAttachment(with:attachmentAnchor:axisOfTranslation:)/title","op":"replace","value":"slidingAttachmentWithItem:attachmentAnchor:axisOfTranslation:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1slidingAttachment(with:attachmentAnchor:axisOfTranslation:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"slidingAttachmentWithItem:attachmentAnchor:axisOfTranslation:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/title","op":"replace","value":"UIAttachmentBehavior"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/fragments","op":"replace","value":[{"text":"UIAttachmentBehavior","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/navigatorTitle","op":"replace","value":[{"text":"UIAttachmentBehavior","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1limitAttachment(with:offsetFromCenter:attachedTo:offsetFromCenter:)/title","op":"replace","value":"limitAttachmentWithItem:offsetFromCenter:attachedToItem:offsetFromCenter:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1limitAttachment(with:offsetFromCenter:attachedTo:offsetFromCenter:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"limitAttachmentWithItem:offsetFromCenter:attachedToItem:offsetFromCenter:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1init(item:offsetFromCenter:attachedToAnchor:)/title","op":"replace","value":"initWithItem:offsetFromCenter:attachedToAnchor:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1init(item:offsetFromCenter:attachedToAnchor:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithItem:offsetFromCenter:attachedToAnchor:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1init(item:offsetFromCenter:attachedTo:offsetFromCenter:)/title","op":"replace","value":"initWithItem:offsetFromCenter:attachedToItem:offsetFromCenter:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1init(item:offsetFromCenter:attachedTo:offsetFromCenter:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithItem:offsetFromCenter:attachedToItem:offsetFromCenter:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1init(item:attachedTo:)/title","op":"replace","value":"initWithItem:attachedToItem:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1init(item:attachedTo:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithItem:attachedToItem:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1pinAttachment(with:attachedTo:attachmentAnchor:)/title","op":"replace","value":"pinAttachmentWithItem:attachedToItem:attachmentAnchor:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1pinAttachment(with:attachedTo:attachmentAnchor:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pinAttachmentWithItem:attachedToItem:attachmentAnchor:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1init(item:attachedToAnchor:)/title","op":"replace","value":"initWithItem:attachedToAnchor:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1init(item:attachedToAnchor:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithItem:attachedToAnchor:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1slidingAttachment(with:attachedTo:attachmentAnchor:axisOfTranslation:)/title","op":"replace","value":"slidingAttachmentWithItem:attachedToItem:attachmentAnchor:axisOfTranslation:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1slidingAttachment(with:attachedTo:attachmentAnchor:axisOfTranslation:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"slidingAttachmentWithItem:attachedToItem:attachmentAnchor:axisOfTranslation:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}