{"variants":[{"paths":["/documentation/uikit/uiattachmentbehavior/length"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiattachmentbehavior/length"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior"]]},"seeAlsoSections":[{"anchor":"Configuring-an-attachment-behavior","title":"Configuring an attachment behavior","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange"],"generated":true}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"length"}],"title":"length","externalID":"c:objc(cs)UIAttachmentBehavior(py)length","symbolKind":"property","platforms":[{"beta":false,"name":"iOS","introducedAt":"7.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"7.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false}],"roleHeading":"Instance Property"},"abstract":[{"text":"The distance, in points, between the two attachment points of the attachment behavior.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Use this property to adjust the attachment length, if you want to, ","type":"text"},{"inlineContent":[{"text":"after","type":"text"}],"type":"emphasis"},{"text":" creating an attachment. The system sets initial length automatically based on how you initialize the attachment.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"kind":"symbol","role":"symbol","title":"CGFloat","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGFloat"}],"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for floating-point scalar values in Core Graphics and related frameworks."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"abstract":[{"type":"text","text":"The basic type for all floating-point values."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","role":"symbol","url":"/documentation/corefoundation/cgfloat","kind":"symbol","type":"topic","title":"CGFloat"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint","abstract":[{"type":"text","text":"The anchor point for the attachment behavior, if any."}],"navigatorTitle":[{"text":"anchorPoint","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorPoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"type":"topic","role":"symbol","title":"anchorPoint","url":"/documentation/uikit/uiattachmentbehavior/anchorpoint"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange":{"abstract":[{"type":"text","text":"The range of motion for the attachment behavior."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange","kind":"symbol","title":"attachmentRange","navigatorTitle":[{"kind":"identifier","text":"attachmentRange"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@UIFloatRange","text":"UIFloatRange"}],"url":"/documentation/uikit/uiattachmentbehavior/attachmentrange"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping":{"kind":"symbol","url":"/documentation/uikit/uiattachmentbehavior/damping","navigatorTitle":[{"kind":"identifier","text":"damping"}],"abstract":[{"text":"The amount of damping to apply to the attachment behavior.","type":"text"}],"title":"damping","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"damping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"length"}],"title":"length","type":"topic","url":"/documentation/uikit/uiattachmentbehavior/length","role":"symbol","abstract":[{"type":"text","text":"The distance, in points, between the two attachment points of the attachment behavior."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/length"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency":{"abstract":[{"type":"text","text":"The frequency of oscillation for the attachment behavior."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","kind":"symbol","title":"frequency","navigatorTitle":[{"kind":"identifier","text":"frequency"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"/documentation/uikit/uiattachmentbehavior/frequency"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType":{"abstract":[{"type":"text","text":"The type of the attachment behavior."}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachedBehaviorType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAttachmentBehavior","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIAttachmentBehavior"},{"text":".","kind":"text"},{"text":"AttachmentType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIAttachmentBehaviorType"}],"navigatorTitle":[{"text":"attachedBehaviorType","kind":"identifier"}],"title":"attachedBehaviorType","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","url":"/documentation/uikit/uiattachmentbehavior/attachedbehaviortype"},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior","kind":"symbol","navigatorTitle":[{"text":"UIAttachmentBehavior","kind":"identifier"}],"type":"topic","title":"UIAttachmentBehavior","url":"/documentation/uikit/uiattachmentbehavior","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIAttachmentBehavior","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A relationship between two dynamic items, or between a dynamic item and an anchor point."}]},"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque":{"abstract":[{"type":"text","text":"The amount of force needed to overcome rotational forces around an anchor point."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque","kind":"symbol","title":"frictionTorque","navigatorTitle":[{"kind":"identifier","text":"frictionTorque"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frictionTorque"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"/documentation/uikit/uiattachmentbehavior/frictiontorque"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","introducedAt":"7.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"7.0","beta":false,"deprecated":false,"unavailable":false},{"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"op":"replace","value":"length","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"length","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Configuring an attachment behavior","anchor":"Configuring-an-attachment-behavior","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/anchorPoint","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachedBehaviorType","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/damping","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frequency","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/frictionTorque","doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior/attachmentRange"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"text":" ","kind":"text"},{"text":"length","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"anchorPoint","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1anchorPoint/title"},{"op":"replace","value":[{"text":"anchorPoint","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1anchorPoint/fragments"},{"op":"replace","value":"attachmentRange","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachmentRange/title"},{"op":"replace","value":[{"text":"attachmentRange","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachmentRange/fragments"},{"op":"replace","value":"damping","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1damping/title"},{"op":"replace","value":[{"kind":"identifier","text":"damping"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1damping/fragments"},{"op":"replace","value":"length","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1length/title"},{"op":"replace","value":[{"kind":"identifier","text":"length"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1length/fragments"},{"op":"replace","value":"frequency","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frequency/title"},{"op":"replace","value":[{"kind":"identifier","text":"frequency"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frequency/fragments"},{"op":"replace","value":"attachedBehaviorType","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachedBehaviorType/title"},{"op":"replace","value":[{"text":"attachedBehaviorType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1attachedBehaviorType/fragments"},{"op":"replace","value":"UIAttachmentBehavior","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/title"},{"op":"replace","value":[{"text":"UIAttachmentBehavior","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIAttachmentBehavior"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/navigatorTitle"},{"op":"replace","value":"frictionTorque","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frictionTorque/title"},{"op":"replace","value":[{"text":"frictionTorque","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior~1frictionTorque/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}