{
  "abstract": [
    {
      "text": "There is no specified response code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/unspecified"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSendRideFeedbackIntentResponseCode@INSendRideFeedbackIntentResponseCodeUnspecified",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unspecified"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSendRideFeedbackIntentResponseCodeUnspecified"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INSendRideFeedbackIntentResponseCode.unspecified"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unspecified"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specifying this code during the confirmation or handling phases results in an error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to record the feedback for the ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You are ready to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/success": {
      "abstract": [
        {
          "text": "You successfully recorded the feedback for the ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "There is no specified response code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/failure"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSendRideFeedbackIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponseCode/failure"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INSendRideFeedbackIntentResponseCodeUnspecified"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode~1ready/title",
          "value": "INSendRideFeedbackIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode~1unspecified/title",
          "value": "INSendRideFeedbackIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode~1success/title",
          "value": "INSendRideFeedbackIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode~1failure/title",
          "value": "INSendRideFeedbackIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode/title",
          "value": "INSendRideFeedbackIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponseCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insendridefeedbackintentresponsecode/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insendridefeedbackintentresponsecode/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
