{
  "abstract": [
    {
      "text": "Content insets use a reference point in relation to the safe area.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/safeArea"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIContentInsetsReference@UIContentInsetsReferenceSafeArea",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "safeArea"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIContentInsetsReferenceSafeArea"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIContentInsetsReference.safeArea"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "safeArea"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference": {
      "abstract": [
        {
          "text": "Constants that describe the reference point of the content insets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentInsetsReference"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentInsetsReference"
        }
      ],
      "role": "symbol",
      "title": "UIContentInsetsReference",
      "type": "topic",
      "url": "/documentation/uikit/uicontentinsetsreference"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/automatic": {
      "abstract": [
        {
          "text": "Content insets use the system default reference point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentInsetsReferenceAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UIContentInsetsReference.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uicontentinsetsreference/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/layoutMargins": {
      "abstract": [
        {
          "text": "Content insets use a reference point in relation to the layout margins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutMargins"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/layoutMargins",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentInsetsReferenceLayoutMargins"
        }
      ],
      "role": "symbol",
      "title": "UIContentInsetsReference.layoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uicontentinsetsreference/layoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/none": {
      "abstract": [
        {
          "text": "Content insets don’t have a reference point in relation to other insets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentInsetsReferenceNone"
        }
      ],
      "role": "symbol",
      "title": "UIContentInsetsReference.none",
      "type": "topic",
      "url": "/documentation/uikit/uicontentinsetsreference/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/readableContent": {
      "abstract": [
        {
          "text": "Content insets use a reference point in relation to the readable content guide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readableContent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/readableContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentInsetsReferenceReadableContent"
        }
      ],
      "role": "symbol",
      "title": "UIContentInsetsReference.readableContent",
      "type": "topic",
      "url": "/documentation/uikit/uicontentinsetsreference/readablecontent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/safeArea": {
      "abstract": [
        {
          "text": "Content insets use a reference point in relation to the safe area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "safeArea"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/safeArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentInsetsReferenceSafeArea"
        }
      ],
      "role": "symbol",
      "title": "UIContentInsetsReference.safeArea",
      "type": "topic",
      "url": "/documentation/uikit/uicontentinsetsreference/safearea"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/none",
        "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/layoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/readableContent"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIContentInsetsReferenceSafeArea"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentInsetsReferenceSafeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/none",
                "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/layoutMargins",
                "doc://com.apple.uikit/documentation/UIKit/UIContentInsetsReference/readableContent"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIContentInsetsReferenceSafeArea"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1automatic/title",
          "value": "UIContentInsetsReferenceAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentInsetsReferenceAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1layoutMargins/title",
          "value": "UIContentInsetsReferenceLayoutMargins"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1layoutMargins/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentInsetsReferenceLayoutMargins"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1readableContent/title",
          "value": "UIContentInsetsReferenceReadableContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1readableContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentInsetsReferenceReadableContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1none/title",
          "value": "UIContentInsetsReferenceNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentInsetsReferenceNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1safeArea/title",
          "value": "UIContentInsetsReferenceSafeArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference~1safeArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentInsetsReferenceSafeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference/title",
          "value": "UIContentInsetsReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentInsetsReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentInsetsReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentInsetsReference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontentinsetsreference/safearea"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicontentinsetsreference/safearea"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
