{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod/options"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod/options/gmres"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@SparseIterativeMethod@U@Solve.h@167014@FI@gmres",
    "fragments": [
      {
        "kind": "identifier",
        "text": "gmres"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gmres"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "gmres"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGMRESOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseGMRESOptions",
              "text": "SparseGMRESOptions"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gmres"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [],
          "name": "message"
        },
        {
          "content": [],
          "name": "message"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use (F/DQ)GMRES to solve Ax=b when A is symmetric indefinite or unsymmetric.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For symmetric positive-definite systems, use CG instead.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For rectangular or singular systems, use LSMR instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "More information about GMRES can be found on wikipedia:",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "https://en.wikipedia.org/wiki/Generalized_minimal_residual_method",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A more detailed description of GMRES and its variants is available in the book:",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "[1] Y. Saad (2003), “Iterative Methods for Sparse Linear Systems”, 2nd Edition,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Published by SIAM.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "@callback reportError Function to use to report parameter errors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If NULL, errors are logged via <os/log.h> and execution is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "halted via __builtin_trap().  If non-NULL, the provided function is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "called with a human-readable string describing the error condition.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If the callback returns, control will be returned to the caller with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "any outputs in a safe but undefined state (i.e. they may hold partial",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "results or garbage, but all sizes and pointers are valid).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "\\field variant",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Variant of GMRES to use. See definition of SparseGMRESVariant_t for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "further information on the available variants.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "\\field nvec",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Number of orthagonal vectors maintained. For GMRES and FGMRES variants,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "this is the number of iterations between restarts. For DQGMRES it is the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "number of historical vectors maintained in memory.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If nvec<=0, the default value of 16 is used.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "\\field maxIterations",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Maximum number of iterations to perform. If 0, the default value of 100",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "is used.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "\\field atol",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Absolute convergence tolerance. Iterate is considered to have converged if",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "|| b-Ax ||_2 < rtol * || b-Ax_0 ||_2 + atol.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "\\field rtol",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Relative convergence tolerance. Iterate is considered to have converged if",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "|| b-Ax ||_2 < rtol * || b-Ax_0 ||_2 + atol.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If rtol = 0.0, default value of sqrt(epsilon) is used.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If negative, rtol is treated as 0.0 (default is not used).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "@callback reportStatus Function to use to report status (iteration count",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and residual of first right-hand side) every few iterations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If NULL, status is not reported.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGMRESOptions": {
      "abstract": [
        {
          "text": "Options for creating a generalized minimal residual (GMRES) method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGMRESOptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGMRESOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGMRESOptions"
        }
      ],
      "role": "symbol",
      "title": "SparseGMRESOptions",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegmresoptions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod": {
      "abstract": [
        {
          "text": "The base type for all iterative methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseIterativeMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseIterativeMethod"
        }
      ],
      "role": "symbol",
      "title": "SparseIterativeMethod",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterativemethod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod/options": {
      "abstract": [
        {
          "text": "The options for the method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union_options"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod/options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "options"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterativemethod/options"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod/options/gmres": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "gmres"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod/options/gmres",
      "kind": "symbol",
      "role": "symbol",
      "title": "gmres",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterativemethod/options/gmres"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeMethod~1options/title",
          "value": "options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeMethod~1options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGMRESOptions/title",
          "value": "SparseGMRESOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGMRESOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGMRESOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGMRESOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGMRESOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeMethod/title",
          "value": "SparseIterativeMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterativeMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterativeMethod"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparseiterativemethod/options/gmres"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
