{
  "abstract": [
    {
      "text": "Add additional accessibility information to the view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SwiftUI/documentation/SwiftUI",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-9s1t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SwiftUI",
    "externalID": "s:7SwiftUI4ViewPAAE26accessibilityCustomContent__10importanceAA08ModifiedF0VyxAA31AccessibilityAttachmentModifierVGAA18LocalizedStringKeyV_ALSo08AXCustomF10ImportanceVtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityCustomContent"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
        "text": "LocalizedStringKey"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
        "text": "LocalizedStringKey"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "importance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AXCustomContent",
        "text": "AXCustomContent"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AXCustomContentImportance",
        "text": "Importance"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
        "text": "ModifiedContent"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "Self"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
        "text": "AccessibilityAttachmentModifier"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "SwiftUI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityCustomContent(_:_:importance:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "otherDeclarations": {
            "declarations": [
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-4r2qu",
                "tokens": [
                  {
                    "kind": "attribute",
                    "text": "nonisolated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityCustomContentKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
                    "text": "AccessibilityCustomContentKey"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI4TextV",
                    "text": "Text"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": "?"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "importance"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AXCustomContent",
                    "text": "AXCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "."
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AXCustomContentImportance",
                    "text": "Importance"
                  },
                  {
                    "kind": "text",
                    "text": " = .default) -> "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
                    "text": "ModifiedContent"
                  },
                  {
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "kind": "typeIdentifier",
                    "text": "Self"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
                    "text": "AccessibilityAttachmentModifier"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-2km9f",
                "tokens": [
                  {
                    "kind": "attribute",
                    "text": "nonisolated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityCustomContentKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
                    "text": "AccessibilityCustomContentKey"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "valueKey"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
                    "text": "LocalizedStringKey"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "importance"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AXCustomContent",
                    "text": "AXCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "."
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AXCustomContentImportance",
                    "text": "Importance"
                  },
                  {
                    "kind": "text",
                    "text": " = .default) -> "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
                    "text": "ModifiedContent"
                  },
                  {
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "kind": "typeIdentifier",
                    "text": "Self"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
                    "text": "AccessibilityAttachmentModifier"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-90n8p",
                "tokens": [
                  {
                    "kind": "attribute",
                    "text": "nonisolated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "label"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI4TextV",
                    "text": "Text"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI4TextV",
                    "text": "Text"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "importance"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AXCustomContent",
                    "text": "AXCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "."
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AXCustomContentImportance",
                    "text": "Importance"
                  },
                  {
                    "kind": "text",
                    "text": " = .default) -> "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
                    "text": "ModifiedContent"
                  },
                  {
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "kind": "typeIdentifier",
                    "text": "Self"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
                    "text": "AccessibilityAttachmentModifier"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-59tdk",
                "tokens": [
                  {
                    "kind": "attribute",
                    "text": "nonisolated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "labelKey"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
                    "text": "LocalizedStringKey"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI4TextV",
                    "text": "Text"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "importance"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AXCustomContent",
                    "text": "AXCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "."
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AXCustomContentImportance",
                    "text": "Importance"
                  },
                  {
                    "kind": "text",
                    "text": " = .default) -> "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
                    "text": "ModifiedContent"
                  },
                  {
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "kind": "typeIdentifier",
                    "text": "Self"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
                    "text": "AccessibilityAttachmentModifier"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-hcgc",
                "tokens": [
                  {
                    "kind": "attribute",
                    "text": "nonisolated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityCustomContent"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "highlight": "changed",
                    "kind": "genericParameter",
                    "text": "V"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": ">"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityCustomContentKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
                    "text": "AccessibilityCustomContentKey"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "kind": "typeIdentifier",
                    "text": "V"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "importance"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AXCustomContent",
                    "text": "AXCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "."
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AXCustomContentImportance",
                    "text": "Importance"
                  },
                  {
                    "kind": "text",
                    "text": " = .default) -> "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
                    "text": "ModifiedContent"
                  },
                  {
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "kind": "typeIdentifier",
                    "text": "Self"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
                    "text": "AccessibilityAttachmentModifier"
                  },
                  {
                    "kind": "text",
                    "text": "> "
                  },
                  {
                    "highlight": "changed",
                    "kind": "keyword",
                    "text": "where"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "typeIdentifier",
                    "text": "V"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/s:Sy",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:Sy",
                    "text": "StringProtocol"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-8uva9",
                "tokens": [
                  {
                    "kind": "attribute",
                    "text": "nonisolated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityCustomContent"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "highlight": "changed",
                    "kind": "genericParameter",
                    "text": "V"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": ">"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "labelKey"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
                    "text": "LocalizedStringKey"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "kind": "typeIdentifier",
                    "text": "V"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "importance"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AXCustomContent",
                    "text": "AXCustomContent"
                  },
                  {
                    "kind": "text",
                    "text": "."
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AXCustomContentImportance",
                    "text": "Importance"
                  },
                  {
                    "kind": "text",
                    "text": " = .default) -> "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
                    "text": "ModifiedContent"
                  },
                  {
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "kind": "typeIdentifier",
                    "text": "Self"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
                    "text": "AccessibilityAttachmentModifier"
                  },
                  {
                    "kind": "text",
                    "text": "> "
                  },
                  {
                    "highlight": "changed",
                    "kind": "keyword",
                    "text": "where"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "typeIdentifier",
                    "text": "V"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/s:Sy",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:Sy",
                    "text": "StringProtocol"
                  }
                ]
              }
            ],
            "displayIndex": 4
          },
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityCustomContent"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "highlight": "changed",
              "kind": "internalParam",
              "text": "labelKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "highlight": "changed",
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
              "text": "LocalizedStringKey"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "highlight": "changed",
              "kind": "internalParam",
              "text": "valueKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "highlight": "changed",
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
              "text": "LocalizedStringKey"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "importance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AXCustomContent",
              "text": "AXCustomContent"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AXCustomContentImportance",
              "text": "Importance"
            },
            {
              "kind": "text",
              "text": " = .default) -> "
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
              "text": "ModifiedContent"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
              "text": "AccessibilityAttachmentModifier"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Localized text describing to the user what",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "is contained in this additional information entry. For example:",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "“orientation”.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "labelKey"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Importance of the accessibility information.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "High-importance information gets read out immediately, while",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "default-importance information must be explicitly asked for by the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "importance"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to add information you want accessibility users to be",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "able to access about this element, beyond the basics of label, value,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and hint. For example, ",
              "type": "text"
            },
            {
              "code": "accessibilityCustomContent",
              "type": "codeVoice"
            },
            {
              "text": " can be used to add",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information about the orientation of a photograph, or the number of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "people found in the picture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Repeated calls of ",
                  "type": "text"
                },
                {
                  "code": "accessibilityCustomContent",
                  "type": "codeVoice"
                },
                {
                  "text": " with different",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "labels will create new entries of additional information. Calling",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "accessibilityAdditionalContent",
                  "type": "codeVoice"
                },
                {
                  "text": " repeatedly with the same label will",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "instead replace the previous value and importance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier": {
      "abstract": [
        {
          "text": "A view modifier that adds accessibility properties to the view",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityAttachmentModifier"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityAttachmentModifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessibilityAttachmentModifier"
        }
      ],
      "role": "symbol",
      "title": "AccessibilityAttachmentModifier",
      "type": "topic",
      "url": "/documentation/swiftui/accessibilityattachmentmodifier"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityCustomContentKey": {
      "abstract": [
        {
          "text": "Key used to specify the identifier and label associated with",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "an entry of additional accessibility information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityCustomContentKey"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/AccessibilityCustomContentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessibilityCustomContentKey"
        }
      ],
      "role": "symbol",
      "title": "AccessibilityCustomContentKey",
      "type": "topic",
      "url": "/documentation/swiftui/accessibilitycustomcontentkey"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey": {
      "abstract": [
        {
          "text": "The key used to look up an entry in a strings file or strings dictionary",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalizedStringKey"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalizedStringKey"
        }
      ],
      "role": "symbol",
      "title": "LocalizedStringKey",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent": {
      "abstract": [
        {
          "text": "A value with a modifier applied to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModifiedContent"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ModifiedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ModifiedContent"
        }
      ],
      "role": "symbol",
      "title": "ModifiedContent",
      "type": "topic",
      "url": "/documentation/swiftui/modifiedcontent"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of read-only text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "role": "symbol",
      "title": "Text",
      "type": "topic",
      "url": "/documentation/swiftui/text"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View": {
      "abstract": [
        {
          "text": "A type that represents part of your app’s user interface and provides",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "modifiers that you use to configure views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "role": "symbol",
      "title": "View",
      "type": "topic",
      "url": "/documentation/swiftui/view"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-2km9f": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
          "text": "AccessibilityCustomContentKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
          "text": "LocalizedStringKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-2km9f",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/accessibilitycustomcontent(_:_:importance:)-2km9f"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-4r2qu": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
          "text": "AccessibilityCustomContentKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-4r2qu",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/accessibilitycustomcontent(_:_:importance:)-4r2qu"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-59tdk": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
          "text": "LocalizedStringKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-59tdk",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/accessibilitycustomcontent(_:_:importance:)-59tdk"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-8uva9": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
          "text": "LocalizedStringKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-8uva9",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/accessibilitycustomcontent(_:_:importance:)-8uva9"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-90n8p": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-90n8p",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/accessibilitycustomcontent(_:_:importance:)-90n8p"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-9s1t": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
          "text": "LocalizedStringKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
          "text": "LocalizedStringKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-9s1t",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/accessibilitycustomcontent(_:_:importance:)-9s1t"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-hcgc": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
          "text": "AccessibilityCustomContentKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/accessibilityCustomContent(_:_:importance:)-hcgc",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/accessibilitycustomcontent(_:_:importance:)-hcgc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance": {
      "abstract": [
        {
          "text": "Objects that control the timing of content output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Importance"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXCustomContent.Importance",
      "type": "topic",
      "url": "/documentation/Accessibility/AXCustomContent/Importance-swift.enum"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent": {
      "abstract": [
        {
          "text": "Objects that define custom content and the timing of its output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomContent"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXCustomContent",
      "type": "topic",
      "url": "/documentation/Accessibility/AXCustomContent"
    },
    "doc://com.externally.resolved.symbol/s:Sy": {
      "abstract": [
        {
          "text": "A type that can represent a string as a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StringProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SL",
          "text": "Comparable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s32ExpressibleByStringInterpolationP",
          "text": "ExpressibleByStringInterpolation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25LosslessStringConvertibleP",
          "text": "LosslessStringConvertible"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s16TextOutputStreamP",
          "text": "TextOutputStream"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s20TextOutputStreamableP",
          "text": "TextOutputStreamable"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SJ",
          "text": "Character"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl5IndexQa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS5IndexV",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s32ExpressibleByStringInterpolationP0cD0Qa",
          "text": "StringInterpolation"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s26DefaultStringInterpolationV",
          "text": "DefaultStringInterpolation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sy",
          "text": "StringProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sy",
      "kind": "symbol",
      "role": "symbol",
      "title": "StringProtocol",
      "type": "topic",
      "url": "/documentation/Swift/StringProtocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AXCustomContentImportance/title",
          "value": "AXCustomContentImportance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AXCustomContentImportance/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXCustomContentImportance"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)AXCustomContent/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXCustomContent"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/swiftui/view/accessibilitycustomcontent(_:_:importance:)-9s1t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
