{
  "abstract": [
    {
      "text": "Sets the text content type for this view, which the system uses to",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "offer suggestions while the user enters text on macOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SwiftUI/documentation/SwiftUI",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-6fic1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SwiftUI",
    "externalID": "s:7SwiftUI4ViewPAAE15textContentTypeyQrSo06NSTexteF0aSgF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "textContentType"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTextContentType",
        "text": "NSTextContentType"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "keyword",
        "text": "some"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI4ViewP",
        "text": "View"
      }
    ],
    "modules": [
      {
        "name": "SwiftUI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "textContentType(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "otherDeclarations": {
            "declarations": [
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-ufdv",
                "tokens": [
                  {
                    "kind": "attribute",
                    "text": "nonisolated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "textContentType"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "textContentType"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@UITextContentType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UITextContentType",
                    "text": "UITextContentType"
                  },
                  {
                    "kind": "text",
                    "text": "?) -> "
                  },
                  {
                    "kind": "keyword",
                    "text": "some"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI4ViewP",
                    "text": "View"
                  },
                  {
                    "kind": "text",
                    "text": "\n"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-4dqqb",
                "tokens": [
                  {
                    "kind": "attribute",
                    "text": "nonisolated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "textContentType"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "textContentType"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@WKTextContentType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@WKTextContentType",
                    "text": "WKTextContentType"
                  },
                  {
                    "kind": "text",
                    "text": "?) -> "
                  },
                  {
                    "kind": "keyword",
                    "text": "some"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI4ViewP",
                    "text": "View"
                  },
                  {
                    "kind": "text",
                    "text": "\n"
                  }
                ]
              }
            ],
            "displayIndex": 0
          },
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "textContentType"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "textContentType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "highlight": "changed",
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTextContentType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTextContentType",
              "text": "NSTextContentType"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "kind": "keyword",
              "text": "some"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI4ViewP",
              "text": "View"
            },
            {
              "kind": "text",
              "text": "\n"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "One of the content types available in the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTextContentType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "structure that identify the semantic meaning expected for a text-entry",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "area.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "textContentType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to set the content type for input text.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, you can configure a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/TextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the entry of a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "username:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "TextField(\"Enter your username\", text: $username)",
            "    .textContentType(.username)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/EnvironmentValues/autocorrectionDisabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the view hierarchy has",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "auto-correction enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autocorrectionDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/EnvironmentValues/autocorrectionDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "autocorrectionDisabled",
      "type": "topic",
      "url": "/documentation/swiftui/environmentvalues/autocorrectiondisabled"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/TextField": {
      "abstract": [
        {
          "text": "A control that displays an editable text interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextField"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/TextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextField"
        }
      ],
      "role": "symbol",
      "title": "TextField",
      "type": "topic",
      "url": "/documentation/swiftui/textfield"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/TextInputAutocapitalization": {
      "abstract": [
        {
          "text": "The kind of autocapitalization behavior applied during text input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextInputAutocapitalization"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/TextInputAutocapitalization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextInputAutocapitalization"
        }
      ],
      "role": "symbol",
      "title": "TextInputAutocapitalization",
      "type": "topic",
      "url": "/documentation/swiftui/textinputautocapitalization"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View": {
      "abstract": [
        {
          "text": "A type that represents part of your app’s user interface and provides",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "modifiers that you use to configure views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "role": "symbol",
      "title": "View",
      "type": "topic",
      "url": "/documentation/swiftui/view"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/autocorrectionDisabled(_:)": {
      "abstract": [
        {
          "text": "Sets whether to disable autocorrection for this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autocorrectionDisabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/autocorrectionDisabled(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "autocorrectionDisabled(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/autocorrectiondisabled(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/keyboardType(_:)": {
      "abstract": [
        {
          "text": "Sets the keyboard type for this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIKeyboardType",
          "text": "UIKeyboardType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/keyboardType(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "keyboardType(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/keyboardtype(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/scrollDismissesKeyboard(_:)": {
      "abstract": [
        {
          "text": "Configures the behavior in which scrollable content interacts with",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the software keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollDismissesKeyboard"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI27ScrollDismissesKeyboardModeV",
          "text": "ScrollDismissesKeyboardMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/scrollDismissesKeyboard(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "scrollDismissesKeyboard(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/scrolldismisseskeyboard(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)": {
      "abstract": [
        {
          "text": "Sets the text content type for this view, which the system uses to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "offer suggestions while the user enters text on macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": ":)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "textContentType(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textcontenttype(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-4dqqb": {
      "abstract": [
        {
          "text": "Sets the text content type for this view, which the system uses to offer",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "suggestions while the user enters text on a watchOS device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-4dqqb",
      "kind": "symbol",
      "role": "symbol",
      "title": "textContentType(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textcontenttype(_:)-4dqqb"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-6fic1": {
      "abstract": [
        {
          "text": "Sets the text content type for this view, which the system uses to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "offer suggestions while the user enters text on macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-6fic1",
      "kind": "symbol",
      "role": "symbol",
      "title": "textContentType(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textcontenttype(_:)-6fic1"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-ufdv": {
      "abstract": [
        {
          "text": "Sets the text content type for this view, which the system uses to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "offer suggestions while the user enters text on an iOS or tvOS device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextContentType",
          "text": "UITextContentType"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-ufdv",
      "kind": "symbol",
      "role": "symbol",
      "title": "textContentType(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textcontenttype(_:)-ufdv"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputAutocapitalization(_:)": {
      "abstract": [
        {
          "text": "Sets how often the shift key in the keyboard is automatically enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputAutocapitalization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI27TextInputAutocapitalizationV",
          "text": "TextInputAutocapitalization"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputAutocapitalization(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "textInputAutocapitalization(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textinputautocapitalization(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputCompletion(_:)": {
      "abstract": [
        {
          "text": "Associates a fully formed string with the value of this view when used",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "as a text input suggestion",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputCompletion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputCompletion(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "textInputCompletion(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textinputcompletion(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:)": {
      "abstract": [
        {
          "text": "Configures the text input suggestions for this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputSuggestions"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ">(() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "textInputSuggestions(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textinputsuggestions(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:content:)": {
      "abstract": [
        {
          "text": "Configures the text input suggestions for this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputSuggestions"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "content"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:content:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "textInputSuggestions(_:content:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textinputsuggestions(_:content:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:id:content:)": {
      "abstract": [
        {
          "text": "Configures the text input suggestions for this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputSuggestions"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7KeyPathC",
          "text": "KeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "content"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:id:content:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "textInputSuggestions(_:id:content:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/textinputsuggestions(_:id:content:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTextContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextContentType",
      "type": "topic",
      "url": "/documentation/AppKit/NSTextContentType"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTextContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextContentType",
      "type": "topic",
      "url": "/documentation/AppKit/NSTextContentType"
    },
    "doc://com.externally.resolved.symbol/c:@T@UITextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextContentType"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@UITextContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextContentType",
      "type": "topic",
      "url": "/documentation/UIKit/UITextContentType"
    },
    "doc://com.externally.resolved.symbol/c:@T@WKTextContentType": {
      "abstract": [
        {
          "text": "Constants that specify a text field’s semantic meaning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@WKTextContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKTextContentType",
      "type": "topic",
      "url": "/documentation/WatchKit/WKTextContentType"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-text-entry",
      "generated": true,
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/autocorrectionDisabled(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/EnvironmentValues/autocorrectionDisabled",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/keyboardType(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/scrollDismissesKeyboard(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputAutocapitalization(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/TextInputAutocapitalization",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputCompletion(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:content:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textInputSuggestions(_:id:content:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-4dqqb",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View/textContentType(_:)-ufdv"
      ],
      "title": "Managing text entry"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTextContentType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@UITextContentType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "UITextContentType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContentType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@WKTextContentType/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/swiftui/view/textcontenttype(_:)-6fic1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
