{
  "abstract": [
    {
      "text": "Returns a Boolean value that indicates whether to accept a new connection from the guest operating system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListenerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListenerDelegate/listener(_:shouldAcceptNewConnection:from:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)VZVirtioSocketListenerDelegate(im)listener:shouldAcceptNewConnection:fromSocketDevice:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "listener"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VZVirtioSocketListener",
        "text": "VZVirtioSocketListener"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "shouldAcceptNewConnection"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VZVirtioSocketConnection",
        "text": "VZVirtioSocketConnection"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VZVirtioSocketDevice",
        "text": "VZVirtioSocketDevice"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "listener:shouldAcceptNewConnection:fromSocketDevice:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "listener(_:shouldAcceptNewConnection:from:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "listener"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "listener"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListener",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VZVirtioSocketListener",
              "text": "VZVirtioSocketListener"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "shouldAcceptNewConnection"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketConnection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VZVirtioSocketConnection",
              "text": "VZVirtioSocketConnection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "socketDevice"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VZVirtioSocketDevice",
              "text": "VZVirtioSocketDevice"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The listener object that monitors the associated port.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "listener"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The object that contains information about the proposed connection. Use this object to fetch port information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "connection"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Virtio socket device that requested the connection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "socketDevice"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to establish the connection, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to reject it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use your method’s implementation to quickly determine whether to accept or reject connection attempts. A typical implementation verifies that a connection between the specified ports is permissible. Return a result as quickly as possible, and don’t perform any long-running operations in this method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t implement this method, the virtual machine refuses all connection requests as if this method returned ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketConnection": {
      "abstract": [
        {
          "text": "A port-based connection between the guest operating system and the host computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSocketConnection"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSocketConnection"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSocketConnection",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketconnection"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice": {
      "abstract": [
        {
          "text": "A device that manages port-based connections between the guest system and the host computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSocketDevice"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSocketDevice"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSocketDevice",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketdevice"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListener": {
      "abstract": [
        {
          "text": "An object that listens for port-based connection requests from the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSocketListener"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSocketListener"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSocketListener",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketlistener"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListenerDelegate": {
      "abstract": [
        {
          "text": "An interface you use to manage connections between the guest operating system and host computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSocketListenerDelegate"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListenerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSocketListenerDelegate"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSocketListenerDelegate",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketlistenerdelegate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListenerDelegate/listener(_:shouldAcceptNewConnection:from:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether to accept a new connection from the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZVirtioSocketListener",
          "text": "VZVirtioSocketListener"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldAcceptNewConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZVirtioSocketConnection",
          "text": "VZVirtioSocketConnection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZVirtioSocketDevice",
          "text": "VZVirtioSocketDevice"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListenerDelegate/listener(_:shouldAcceptNewConnection:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "listener:shouldAcceptNewConnection:fromSocketDevice:"
        }
      ],
      "role": "symbol",
      "title": "listener(_:shouldAcceptNewConnection:from:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketlistenerdelegate/listener(_:shouldacceptnewconnection:from:)"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "listener:shouldAcceptNewConnection:fromSocketDevice:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "listener:shouldAcceptNewConnection:fromSocketDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListenerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "listener:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListener",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZVirtioSocketListener",
                    "text": "VZVirtioSocketListener"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "listener"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "shouldAcceptNewConnection:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketConnection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZVirtioSocketConnection",
                    "text": "VZVirtioSocketConnection"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "connection"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "fromSocketDevice:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZVirtioSocketDevice",
                    "text": "VZVirtioSocketDevice"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "socketDevice"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The listener object that monitors the associated port.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "listener"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The object that contains information about the proposed connection. Use this object to fetch port information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "connection"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The Virtio socket device that requested the connection.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "socketDevice"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " to establish the connection, or ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " to reject it.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListenerDelegate~1listener(_:shouldAcceptNewConnection:from:)/title",
          "value": "listener:shouldAcceptNewConnection:fromSocketDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListenerDelegate~1listener(_:shouldAcceptNewConnection:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "listener:shouldAcceptNewConnection:fromSocketDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListenerDelegate/title",
          "value": "VZVirtioSocketListenerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListenerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketListenerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListenerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketListenerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/title",
          "value": "VZVirtioSocketDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketConnection/title",
          "value": "VZVirtioSocketConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListener/title",
          "value": "VZVirtioSocketListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketListener"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzvirtiosocketlistenerdelegate/listener(_:shouldacceptnewconnection:from:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzvirtiosocketlistenerdelegate/listener(_:shouldacceptnewconnection:from:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
