{
  "abstract": [
    {
      "text": "Patterns that define the universal links an app can open.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ul:applinks.Details.Components",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "applinks.Details.Components"
      }
    ],
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applinks.Details.Components"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Object",
    "symbolKind": "dictionary",
    "title": "applinks.Details.Components"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "13.0.0",
          "name": "#",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "13.0.0",
          "name": "/",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "allowedTypes",
              "values": [
                [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ],
                [
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "ul:applinks.Details.Components.Query",
                    "text": "applinks.Details.Components.Query"
                  }
                ]
              ]
            }
          ],
          "content": [],
          "introducedVersion": "13.0.0",
          "name": "?",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "(string | "
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query",
              "kind": "typeIdentifier",
              "preciseIdentifier": "ul:applinks.Details.Components.Query",
              "text": "applinks.Details.Components.Query"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ],
          "typeDetails": [
            {
              "baseType": "string"
            },
            {
              "baseType": "dictionary"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "13.0.0",
          "name": "caseSensitive",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "13.0.0",
          "name": "comment",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "13.0.0",
          "name": "exclude",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "13.0.0",
          "name": "percentEncoded",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this object to define whether an associated app can open specific URLs in this domain as universal links.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The object optionally contains any of these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The pattern to match with the URL path component. The default is ",
                        "type": "text"
                      },
                      {
                        "code": "*",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", which matches everything.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "/",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The pattern or dictionary to match with the URL query component. The default is ",
                        "type": "text"
                      },
                      {
                        "code": "*",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", which matches everything.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "?",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The pattern to match with the URL fragment component. The default is ",
                        "type": "text"
                      },
                      {
                        "code": "*",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", which matches everything.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "#",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Boolean value that indicates whether to stop pattern matching and prevent the universal link from opening if the URL matches the associated pattern. The default is ",
                        "type": "text"
                      },
                      {
                        "code": "false",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "exclude",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Text that the system ignores. Use this to provide information about the URLs a pattern matches.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "comment",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Boolean value that indicates whether pattern matching is case-sensitive. The default is ",
                        "type": "text"
                      },
                      {
                        "code": "true",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "caseSensitive",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Boolean value that indicates whether URLs are percent-encoded. The default is ",
                        "type": "text"
                      },
                      {
                        "code": "true",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "percentEncoded",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "The order that you use to specify the patterns in the array determines the order the system follows when looking for a match.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The first match wins, allowing you to designate one app to handle specified URLs in your website, and another app to handle the rest.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use the following wildcards in your URL pattern-matching definitions:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "*",
              "type": "codeVoice"
            },
            {
              "text": " — Matches zero or more characters. This performs a greedy match and matches as many characters as possible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "?",
              "type": "codeVoice"
            },
            {
              "text": " — Matches any single character.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition, you can use ",
              "type": "text"
            },
            {
              "code": "?*",
              "type": "codeVoice"
            },
            {
              "text": " to match one or more characters (that is, at least one character).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A match occurs when a URL matches ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "all",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " the components that a ",
              "type": "text"
            },
            {
              "code": "components",
              "type": "codeVoice"
            },
            {
              "text": " object specifies.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The following example code matches all URLs with a path of ",
              "type": "text"
            },
            {
              "code": "abc",
              "type": "codeVoice"
            },
            {
              "text": " and a query of ",
              "type": "text"
            },
            {
              "code": "def",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"/\": \"abc\",",
            "  \"?\": \"def\",",
            "  \"#\": \"*\"",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The URL ",
              "type": "text"
            },
            {
              "code": "https://www.example.com/abc?def",
              "type": "codeVoice"
            },
            {
              "text": " matches with the above code, but ",
              "type": "text"
            },
            {
              "code": "https://www.example.com/abc",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "https://www.example.com?def",
              "type": "codeVoice"
            },
            {
              "text": " don’t.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The fragment part of the code matches everything, so the system ignores it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This example code shows another components object in an association file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"/\": \"/help/website/*\",",
            "  \"exclude\": true,",
            "  \"comment\": \"Matches any URL whose path starts with /help/website/ and instructs the system not to open it as a universal link\"",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks": {
      "abstract": [
        {
          "text": "The root object for a universal links service definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "role": "symbol",
      "title": "applinks",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary": {
      "abstract": [
        {
          "text": "A list of apps and the universal links they handle for a domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary": {
      "abstract": [
        {
          "text": "Patterns that define the universal links an app can open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details.Components"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details.Components"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details.Components",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query": {
      "abstract": [
        {
          "text": "A dictionary of names and values to match with query items in a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details.Components.Query"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details.Components.Query"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details.Components.Query",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary/query"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Query-dictionaries",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query"
      ],
      "title": "Query dictionaries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Object"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applinks.Details.Components"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Query-dictionaries",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query"
              ],
              "title": "Query dictionaries"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "object "
                  },
                  {
                    "kind": "identifier",
                    "text": "applinks.Details.Components"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "items": [
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "13.0.0",
                "name": "#",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "13.0.0",
                "name": "/",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              },
              {
                "attributes": [
                  {
                    "kind": "allowedTypes",
                    "values": [
                      [
                        {
                          "kind": "text",
                          "text": "string"
                        }
                      ],
                      [
                        {
                          "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query",
                          "kind": "typeIdentifier",
                          "preciseIdentifier": "ul:applinks.Details.Components.Query",
                          "text": "applinks.Details.Components.Query"
                        }
                      ]
                    ]
                  }
                ],
                "content": [],
                "introducedVersion": "13.0.0",
                "name": "?",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "(string | "
                  },
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "ul:applinks.Details.Components.Query",
                    "text": "applinks.Details.Components.Query"
                  },
                  {
                    "kind": "text",
                    "text": ")"
                  }
                ],
                "typeDetails": [
                  {
                    "baseType": "string"
                  },
                  {
                    "baseType": "dictionary"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "13.0.0",
                "name": "caseSensitive",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "boolean"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "13.0.0",
                "name": "comment",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "13.0.0",
                "name": "exclude",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "boolean"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "13.0.0",
                "name": "percentEncoded",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "boolean"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/title",
          "value": "applinks.Details"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/title",
          "value": "applinks.Details.Components"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary~1Query/title",
          "value": "applinks.Details.Components.Query"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary~1Query/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components.Query"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary~1Query/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details.Components.Query"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/title",
          "value": "applinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
