{
  "abstract": [
    {
      "text": "This function commands the device to “destroy” a currently downloaded effect. The effect ID and any data that is associated with the effect are freed and available for reallocation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/destroyeffect"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "DestroyEffect"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "code": [
            "HRESULT ( *DestroyEffect)(",
            "   void *self,",
            "   FFEffectDownloadID downloadID );"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "anchor": "Parameters",
          "level": 3,
          "text": "Parameters",
          "type": "heading"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Pointer to the FFPlugInDriver implementation instance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "self",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Indicates the effect ID that was obtained from the device when the effect was downloaded.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "downloadID",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Return-Value",
          "level": 3,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns FF_OK if successful, or an error value otherwise:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "FFERR_INVALIDDOWNLOADID",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "FFERR_GENERIC",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "FFERR_INTERNAL",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/downloadeffect": {
      "abstract": [
        {
          "text": "This function sends an effect to the device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/downloadeffect",
      "kind": "article",
      "role": "article",
      "title": "DownloadEffect",
      "type": "topic",
      "url": "/documentation/forcefeedback/downloadeffect"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/escape": {
      "abstract": [
        {
          "text": "This function escapes to the driver. This method is called in response to an application invoking the FFEffectEscape or FFDeviceEscape methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/escape",
      "kind": "article",
      "role": "article",
      "title": "Escape",
      "type": "topic",
      "url": "/documentation/forcefeedback/escape"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackgetversion": {
      "abstract": [
        {
          "text": "This function is used to determine driver and API version information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackgetversion",
      "kind": "article",
      "role": "article",
      "title": "ForceFeedbackGetVersion",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackgetversion"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/geteffectstatus": {
      "abstract": [
        {
          "text": "This function returns the device effect’s status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/geteffectstatus",
      "kind": "article",
      "role": "article",
      "title": "GetEffectStatus",
      "type": "topic",
      "url": "/documentation/forcefeedback/geteffectstatus"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/getforcefeedbackcapabilities": {
      "abstract": [
        {
          "text": "This function escapes to the driver. This method is called in response to an application invoking the FFEffectEscape or FFDevicEscape methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/getforcefeedbackcapabilities",
      "kind": "article",
      "role": "article",
      "title": "GetForceFeedbackCapabilities",
      "type": "topic",
      "url": "/documentation/forcefeedback/getforcefeedbackcapabilities"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/getforcefeedbackstate": {
      "abstract": [
        {
          "text": "This function returns the state of the device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/getforcefeedbackstate",
      "kind": "article",
      "role": "article",
      "title": "GetForceFeedbackState",
      "type": "topic",
      "url": "/documentation/forcefeedback/getforcefeedbackstate"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/initializeterminate": {
      "abstract": [
        {
          "text": "This function is used to “create and destroy” particular device instances. It provides the FF plug-in driver with all the necessary start-up parameters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/initializeterminate",
      "kind": "article",
      "role": "article",
      "title": "InitializeTerminate",
      "type": "topic",
      "url": "/documentation/forcefeedback/initializeterminate"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h": {
      "abstract": [
        {
          "text": "Public Interfaces and constants used to develop Force Feedback plugIns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOForceFeedbackLib.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/ioforcefeedbacklib-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/sendforcefeedbackcommand": {
      "abstract": [
        {
          "text": "This function sends a command to the device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/sendforcefeedbackcommand",
      "kind": "article",
      "role": "article",
      "title": "SendForceFeedbackCommand",
      "type": "topic",
      "url": "/documentation/forcefeedback/sendforcefeedbackcommand"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/setproperty": {
      "abstract": [
        {
          "text": "This function sets properties that define the device behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/setproperty",
      "kind": "article",
      "role": "article",
      "title": "SetProperty",
      "type": "topic",
      "url": "/documentation/forcefeedback/setproperty"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/starteffect": {
      "abstract": [
        {
          "text": "This function commands the device to play back an effect that was previously loaded.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/starteffect",
      "kind": "article",
      "role": "article",
      "title": "StartEffect",
      "type": "topic",
      "url": "/documentation/forcefeedback/starteffect"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/stopeffect": {
      "abstract": [
        {
          "text": "This function commands the device to stop an effect that was previously started.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/stopeffect",
      "kind": "article",
      "role": "article",
      "title": "StopEffect",
      "type": "topic",
      "url": "/documentation/forcefeedback/stopeffect"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/downloadeffect",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/escape",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackgetversion",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/geteffectstatus",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/getforcefeedbackcapabilities",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/getforcefeedbackstate",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/initializeterminate",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/sendforcefeedbackcommand",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/setproperty",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/starteffect",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/stopeffect"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/downloadeffect",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/escape",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackgetversion",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/geteffectstatus",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/getforcefeedbackcapabilities",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/getforcefeedbackstate",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/initializeterminate",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/sendforcefeedbackcommand",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/setproperty",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/starteffect",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/stopeffect"
              ],
              "title": "Miscellaneous"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/destroyeffect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/destroyeffect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
