{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@FFCAP_ET_CONSTANTFORCE@FFCAP_ET_INERTIA",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFCAP_ET_INERTIA"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFCAP_ET_INERTIA"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "FFCAP_ET_INERTIA"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFCAP_ET_INERTIA"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The effect represents a inertia force effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CONSTANTFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CONSTANTFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_CONSTANTFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_constantforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CUSTOMFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CUSTOMFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_CUSTOMFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_customforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_DAMPER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_DAMPER"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_DAMPER",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_damper"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_FRICTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_FRICTION"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_FRICTION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_friction"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_INERTIA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_INERTIA"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_INERTIA",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_inertia"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_RAMPFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_RAMPFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_RAMPFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_rampforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHDOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHDOWN"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SAWTOOTHDOWN",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sawtoothdown"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHUP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHUP"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SAWTOOTHUP",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sawtoothup"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SINE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SINE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SINE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sine"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SPRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SPRING"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SPRING",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_spring"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SQUARE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SQUARE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SQUARE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_square"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_TRIANGLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_TRIANGLE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_TRIANGLE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_triangle"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFCAP_ET_INERTIA"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_INERTIA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "FFCAP_ET_INERTIA"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SQUARE/title",
          "value": "FFCAP_ET_SQUARE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SQUARE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SQUARE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SPRING/title",
          "value": "FFCAP_ET_SPRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SPRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SPRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_DAMPER/title",
          "value": "FFCAP_ET_DAMPER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_DAMPER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_DAMPER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CUSTOMFORCE/title",
          "value": "FFCAP_ET_CUSTOMFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CUSTOMFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_CUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CONSTANTFORCE/title",
          "value": "FFCAP_ET_CONSTANTFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CONSTANTFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_CONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_FRICTION/title",
          "value": "FFCAP_ET_FRICTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_FRICTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_FRICTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHUP/title",
          "value": "FFCAP_ET_SAWTOOTHUP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHUP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SAWTOOTHUP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHDOWN/title",
          "value": "FFCAP_ET_SAWTOOTHDOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHDOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SAWTOOTHDOWN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_INERTIA/title",
          "value": "FFCAP_ET_INERTIA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_INERTIA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_INERTIA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SINE/title",
          "value": "FFCAP_ET_SINE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SINE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SINE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_TRIANGLE/title",
          "value": "FFCAP_ET_TRIANGLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_TRIANGLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_TRIANGLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_RAMPFORCE/title",
          "value": "FFCAP_ET_RAMPFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_RAMPFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_RAMPFORCE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffcap_et_inertia"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffcap_et_inertia"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
