{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@FFCapabilitiesEffectType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFCapabilitiesEffectType"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFCapabilitiesEffectType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "FFCapabilitiesEffectType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Types used in the emulatedEffects or supportedEffects members of the FFCAPABILITIES structure. Used to describe whether the particular effect type is supported or emulated by the device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CONSTANTFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CONSTANTFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_CONSTANTFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_constantforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CUSTOMFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CUSTOMFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_CUSTOMFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_customforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_DAMPER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_DAMPER"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_DAMPER",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_damper"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_FRICTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_FRICTION"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_FRICTION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_friction"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_INERTIA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_INERTIA"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_INERTIA",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_inertia"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_RAMPFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_RAMPFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_RAMPFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_rampforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHDOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHDOWN"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SAWTOOTHDOWN",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sawtoothdown"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHUP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHUP"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SAWTOOTHUP",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sawtoothup"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SINE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SINE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SINE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sine"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SPRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SPRING"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SPRING",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_spring"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SQUARE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SQUARE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SQUARE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_square"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_TRIANGLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_TRIANGLE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_TRIANGLE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_triangle"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectSubType"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectSubType"
        }
      ],
      "role": "symbol",
      "title": "FFCapabilitiesEffectSubType",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilitieseffectsubtype"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectType"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectType"
        }
      ],
      "role": "symbol",
      "title": "FFCapabilitiesEffectType",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilitieseffecttype"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCommandFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCommandFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCommandFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcommandflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCooperativeLevelFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCooperativeLevelFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCooperativeLevelFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcooperativelevelflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCoordinateSystemFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCoordinateSystemFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCoordinateSystemFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcoordinatesystemflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectParameterFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectParameterFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectParameterFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectparameterflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStartFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStartFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStartFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstartflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStatusFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStatusFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStatusFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstatusflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFProperty"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFProperty"
        }
      ],
      "role": "symbol",
      "title": "FFProperty",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffproperty"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFState"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFState"
        }
      ],
      "role": "symbol",
      "title": "FFState",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffstate"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Miscellaneous Defines",
      "type": "topic",
      "url": "/documentation/forcefeedback/miscellaneous-defines"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFCapabilitiesEffectType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FFCapabilitiesEffectType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/title",
          "value": "FFProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/title",
          "value": "FFEffectStatusFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStatusFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStatusFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_DAMPER/title",
          "value": "FFCAP_ET_DAMPER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_DAMPER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_DAMPER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/title",
          "value": "FFCommandFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCommandFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCommandFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/title",
          "value": "FFCapabilitiesEffectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/title",
          "value": "FFCoordinateSystemFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCoordinateSystemFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCoordinateSystemFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHUP/title",
          "value": "FFCAP_ET_SAWTOOTHUP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHUP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SAWTOOTHUP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/title",
          "value": "FFCooperativeLevelFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCooperativeLevelFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCooperativeLevelFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SPRING/title",
          "value": "FFCAP_ET_SPRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SPRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SPRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SQUARE/title",
          "value": "FFCAP_ET_SQUARE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SQUARE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SQUARE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CONSTANTFORCE/title",
          "value": "FFCAP_ET_CONSTANTFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CONSTANTFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_CONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHDOWN/title",
          "value": "FFCAP_ET_SAWTOOTHDOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHDOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SAWTOOTHDOWN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/title",
          "value": "FFCapabilitiesEffectSubType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/title",
          "value": "FFState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_TRIANGLE/title",
          "value": "FFCAP_ET_TRIANGLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_TRIANGLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_TRIANGLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SINE/title",
          "value": "FFCAP_ET_SINE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SINE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SINE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/title",
          "value": "FFEffectParameterFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectParameterFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectParameterFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_INERTIA/title",
          "value": "FFCAP_ET_INERTIA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_INERTIA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_INERTIA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_FRICTION/title",
          "value": "FFCAP_ET_FRICTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_FRICTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_FRICTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_RAMPFORCE/title",
          "value": "FFCAP_ET_RAMPFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_RAMPFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_RAMPFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/title",
          "value": "FFEffectStartFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStartFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStartFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CUSTOMFORCE/title",
          "value": "FFCAP_ET_CUSTOMFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CUSTOMFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_CUSTOMFORCE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffcapabilitieseffecttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffcapabilitieseffecttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
