{
  "abstract": [
    {
      "text": "A structure containing type-specific information for certain effects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@FFCONDITION",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFCONDITION"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFCONDITION"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "FFCONDITION"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Used with the SPRING, DAMPER, INERTIA, and FRICTION effects.A pointer to an array of FFCONDITION structures for an effect is passed in the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lpvTypeSpecificParams",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " member of the FFEFFECT structure. The number of elements in the array must be either one, or equal to the number of axes associated with the effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Different types of conditions interpret the parameters differently, but the basic idea is that force resulting from a condition is equal to ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "A(q - q0)",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " where ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "A",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is a scaling coefficient, ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "q",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is some metric, and ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "q0",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is the neutral value for that metric.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The preceding simplified formula must be adjusted if a nonzero deadband is provided. If the metric is less than ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lOffset - lDeadBand",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ", the resulting force is given by the following formula:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "force",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " = ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lNegativeCoefficient",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " * (",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "q",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " - (",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lOffset - lDeadBand",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": "))",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Similarly, if the metric is greater than ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lOffset + lDeadBand",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ", the resulting force is given by the following formula:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "force",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " = ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lPositiveCoefficient",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " * (",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "q",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " - (",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lOffset + lDeadBand",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": "))",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A spring condition uses axis position as the metric.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A damper condition uses axis velocity as the metric.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An inertia condition uses axis acceleration as the metric.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the number of FFCONDITION structures in the array is equal to the number of axes for the effect, the first structure applies to the first axis, the second applies to the second axis, and so on. For example, a two-axis spring condition with ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lOffset",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " set to 0 in both FFCONDITION structures would have the same effect as the joystick self-centering spring. When a condition is defined for each axis in this way, the effect must not be rotated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If there is a single FFCONDITION structure for an effect with more than one axis, the direction along which the parameters of the FFCONDITION structure are in effect is determined by the direction parameters passed in the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "rglDirection",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " field of the FFEFFECT structure. For example, a friction condition rotated 45 degrees (in polar coordinates) would resist joystick motion in the northeast-southwest direction but would have no effect on joystick motion in the northwest-southeast direction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES": {
      "abstract": [
        {
          "text": "Used by the FFDeviceGetForceFeedbackCapabilities method to retrieve device force-feedback capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAPABILITIES"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAPABILITIES"
        }
      ],
      "role": "symbol",
      "title": "FFCAPABILITIES",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilities"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION": {
      "abstract": [
        {
          "text": "A structure containing type-specific information for certain effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCONDITION"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCONDITION"
        }
      ],
      "role": "symbol",
      "title": "FFCONDITION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwNegativeSaturation": {
      "abstract": [
        {
          "text": "Maximum force output on the negative side of the offset, in the range from 0 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwNegativeSaturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwNegativeSaturation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwNegativeSaturation"
        }
      ],
      "role": "symbol",
      "title": "dwNegativeSaturation",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/dwnegativesaturation"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwPositiveSaturation": {
      "abstract": [
        {
          "text": "Maximum force output on the positive side of the offset, in the range from 0 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwPositiveSaturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwPositiveSaturation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwPositiveSaturation"
        }
      ],
      "role": "symbol",
      "title": "dwPositiveSaturation",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/dwpositivesaturation"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/init()"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/init(lOffset:lPositiveCoefficient:lNegativeCoefficient:dwPositiveSaturation:dwNegativeSaturation:lDeadBand:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "lOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "lPositiveCoefficient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "lNegativeCoefficient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dwPositiveSaturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dwNegativeSaturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "lDeadBand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/init(lOffset:lPositiveCoefficient:lNegativeCoefficient:dwPositiveSaturation:dwNegativeSaturation:lDeadBand:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(lOffset:lPositiveCoefficient:lNegativeCoefficient:dwPositiveSaturation:dwNegativeSaturation:lDeadBand:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/init(loffset:lpositivecoefficient:lnegativecoefficient:dwpositivesaturation:dwnegativesaturation:ldeadband:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lDeadBand": {
      "abstract": [
        {
          "text": "Region around ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " in which the condition is not active, in the range from 0 through 10,000. In other words, the condition is not active between ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " minus ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lDeadBand",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " plus ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lDeadBand",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lDeadBand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lDeadBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lDeadBand"
        }
      ],
      "role": "symbol",
      "title": "lDeadBand",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/ldeadband"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lNegativeCoefficient": {
      "abstract": [
        {
          "text": "Coefficient constant on the negative side of the offset, in the range from -10,000 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lNegativeCoefficient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lNegativeCoefficient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lNegativeCoefficient"
        }
      ],
      "role": "symbol",
      "title": "lNegativeCoefficient",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/lnegativecoefficient"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lOffset": {
      "abstract": [
        {
          "text": "Offset for the condition, in the range from -10,000 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lOffset"
        }
      ],
      "role": "symbol",
      "title": "lOffset",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/loffset"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lPositiveCoefficient": {
      "abstract": [
        {
          "text": "Coefficient constant on the positive side of the offset, in the range from -10,000 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lPositiveCoefficient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lPositiveCoefficient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lPositiveCoefficient"
        }
      ],
      "role": "symbol",
      "title": "lPositiveCoefficient",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/lpositivecoefficient"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the CONSTANTFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCONSTANTFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCONSTANTFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCONSTANTFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffconstantforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the CUSTOMFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCUSTOMFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCUSTOMFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCUSTOMFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT": {
      "abstract": [
        {
          "text": "UsUsed by the FFDeviceCreateEffect method to initialize a new effect object. It is also used by the FFEffectSetParameters and FFEffectGetParameters functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFFECT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFFECT"
        }
      ],
      "role": "symbol",
      "title": "FFEFFECT",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE": {
      "abstract": [
        {
          "text": "The FFEFFESCAPE structure passes hardware-specific data directly to the Force Feedback plugIn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFFESCAPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFFESCAPE"
        }
      ],
      "role": "symbol",
      "title": "FFEFFESCAPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE": {
      "abstract": [
        {
          "text": "Used by the FFEFFECT structure to specify the optional envelope parameters for an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFENVELOPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFENVELOPE"
        }
      ],
      "role": "symbol",
      "title": "FFENVELOPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffenvelope"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC": {
      "abstract": [
        {
          "text": "A structure containing type-specific information for certain effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFPERIODIC"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFPERIODIC"
        }
      ],
      "role": "symbol",
      "title": "FFPERIODIC",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffperiodic"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the RAMPFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFRAMPFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFRAMPFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFRAMPFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/fframpforce"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/init()",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/init(lOffset:lPositiveCoefficient:lNegativeCoefficient:dwPositiveSaturation:dwNegativeSaturation:lDeadBand:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwNegativeSaturation",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwPositiveSaturation",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lDeadBand",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lNegativeCoefficient",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lOffset",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lPositiveCoefficient"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFCONDITION"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwNegativeSaturation",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwPositiveSaturation",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lDeadBand",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lNegativeCoefficient",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lOffset",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lPositiveCoefficient"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FFCONDITION"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lPositiveCoefficient/title",
          "value": "lPositiveCoefficient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lPositiveCoefficient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lPositiveCoefficient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/title",
          "value": "FFEFFECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1dwNegativeSaturation/title",
          "value": "dwNegativeSaturation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1dwNegativeSaturation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwNegativeSaturation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/title",
          "value": "FFCONSTANTFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/title",
          "value": "FFCONDITION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/title",
          "value": "FFENVELOPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lOffset/title",
          "value": "lOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/title",
          "value": "FFPERIODIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFPERIODIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFPERIODIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lNegativeCoefficient/title",
          "value": "lNegativeCoefficient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lNegativeCoefficient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lNegativeCoefficient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1dwPositiveSaturation/title",
          "value": "dwPositiveSaturation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1dwPositiveSaturation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwPositiveSaturation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/title",
          "value": "FFCAPABILITIES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAPABILITIES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAPABILITIES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/title",
          "value": "FFRAMPFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFRAMPFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFRAMPFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/title",
          "value": "FFEFFESCAPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/title",
          "value": "FFCUSTOMFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lDeadBand/title",
          "value": "lDeadBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lDeadBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lDeadBand"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffcondition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffcondition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
