{
  "abstract": [
    {
      "text": "Contains type-specific information for the CUSTOMFORCE effect.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@FFCUSTOMFORCE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFCUSTOMFORCE"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFCUSTOMFORCE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "FFCUSTOMFORCE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A pointer to a single FFCUSTOMFORCE structure for an effect is passed in the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "lpvTypeSpecificParams",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " member of the FFEFFECT structure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The structure describes a custom or user-defined force.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES": {
      "abstract": [
        {
          "text": "Used by the FFDeviceGetForceFeedbackCapabilities method to retrieve device force-feedback capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAPABILITIES"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAPABILITIES"
        }
      ],
      "role": "symbol",
      "title": "FFCAPABILITIES",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilities"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION": {
      "abstract": [
        {
          "text": "A structure containing type-specific information for certain effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCONDITION"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCONDITION"
        }
      ],
      "role": "symbol",
      "title": "FFCONDITION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the CONSTANTFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCONSTANTFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCONSTANTFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCONSTANTFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffconstantforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the CUSTOMFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCUSTOMFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCUSTOMFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCUSTOMFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/cChannels": {
      "abstract": [
        {
          "text": "Number of channels (axes) affected by this force.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/cChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cChannels"
        }
      ],
      "role": "symbol",
      "title": "cChannels",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce/cchannels"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/cSamples": {
      "abstract": [
        {
          "text": "Total number of samples in the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "rglForceData",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ". It must be an integral multiple of the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "cChannels",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cSamples"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/cSamples",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cSamples"
        }
      ],
      "role": "symbol",
      "title": "cSamples",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce/csamples"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/dwSamplePeriod": {
      "abstract": [
        {
          "text": "Sample period, in microseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwSamplePeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/dwSamplePeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwSamplePeriod"
        }
      ],
      "role": "symbol",
      "title": "dwSamplePeriod",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce/dwsampleperiod"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce/init()"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/init(cChannels:dwSamplePeriod:cSamples:rglForceData:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "cChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dwSamplePeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cSamples"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rglForceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LPLONG",
          "text": "LPLONG"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/init(cChannels:dwSamplePeriod:cSamples:rglForceData:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(cChannels:dwSamplePeriod:cSamples:rglForceData:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce/init(cchannels:dwsampleperiod:csamples:rglforcedata:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/rglForceData": {
      "abstract": [
        {
          "text": "Pointer to an array of force values representing the custom force. If multiple channels are provided, the values are interleaved. For example, if ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "cChannels",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " is 3, the first element of the array belongs to the first channel, the second to the second, and the third to the third.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rglForceData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LPLONG",
          "text": "LPLONG"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/rglForceData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rglForceData"
        }
      ],
      "role": "symbol",
      "title": "rglForceData",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce/rglforcedata"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT": {
      "abstract": [
        {
          "text": "UsUsed by the FFDeviceCreateEffect method to initialize a new effect object. It is also used by the FFEffectSetParameters and FFEffectGetParameters functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFFECT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFFECT"
        }
      ],
      "role": "symbol",
      "title": "FFEFFECT",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE": {
      "abstract": [
        {
          "text": "The FFEFFESCAPE structure passes hardware-specific data directly to the Force Feedback plugIn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFFESCAPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFFESCAPE"
        }
      ],
      "role": "symbol",
      "title": "FFEFFESCAPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE": {
      "abstract": [
        {
          "text": "Used by the FFEFFECT structure to specify the optional envelope parameters for an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFENVELOPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFENVELOPE"
        }
      ],
      "role": "symbol",
      "title": "FFENVELOPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffenvelope"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC": {
      "abstract": [
        {
          "text": "A structure containing type-specific information for certain effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFPERIODIC"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFPERIODIC"
        }
      ],
      "role": "symbol",
      "title": "FFPERIODIC",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffperiodic"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the RAMPFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFRAMPFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFRAMPFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFRAMPFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/fframpforce"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/init()",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/init(cChannels:dwSamplePeriod:cSamples:rglForceData:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/cChannels",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/cSamples",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/dwSamplePeriod",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/rglForceData"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFCUSTOMFORCE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/cChannels",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/cSamples",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/dwSamplePeriod",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE/rglForceData"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FFCUSTOMFORCE"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/title",
          "value": "FFCAPABILITIES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAPABILITIES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAPABILITIES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/title",
          "value": "FFENVELOPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE~1cSamples/title",
          "value": "cSamples"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE~1cSamples/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cSamples"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE~1dwSamplePeriod/title",
          "value": "dwSamplePeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE~1dwSamplePeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwSamplePeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/title",
          "value": "FFCONDITION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/title",
          "value": "FFCONSTANTFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/title",
          "value": "FFEFFECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/title",
          "value": "FFEFFESCAPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/title",
          "value": "FFRAMPFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFRAMPFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFRAMPFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/title",
          "value": "FFPERIODIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFPERIODIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFPERIODIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE~1rglForceData/title",
          "value": "rglForceData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE~1rglForceData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rglForceData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE~1cChannels/title",
          "value": "cChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE~1cChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/title",
          "value": "FFCUSTOMFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffcustomforce"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffcustomforce"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
