{
  "abstract": [
    {
      "text": "Sends a command to the device’s force feedback system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSendForceFeedbackCommand(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@FFDeviceSendForceFeedbackCommand",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFDeviceSendForceFeedbackCommand"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@FFDeviceObjectReference",
        "text": "FFDeviceObjectReference"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@FFCommandFlag",
        "text": "FFCommandFlag"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HRESULT",
        "text": "HRESULT"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFDeviceSendForceFeedbackCommand"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "FFDeviceSendForceFeedbackCommand(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFDeviceSendForceFeedbackCommand"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "deviceReference"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceObjectReference",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@FFDeviceObjectReference",
              "text": "FFDeviceObjectReference"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@FFCommandFlag",
              "text": "FFCommandFlag"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HRESULT",
              "text": "HRESULT"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An opaque reference handle to the device object that is be disposed of. This handle is obtained from a previous call to FFCreateDevice.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "deviceReference"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Single value indicating the desired change in state. The value can be one of the following:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "FFSFFC_CONTINUE",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Paused playback of all active effects is to be continued. It is an error to send this command when the device is not in a paused state.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "FFSFFC_PAUSE",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Playback of all active effects is to be paused. This command also stops the clock-on effects so that they continue playing to their full duration when restarted.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "While the device is paused, new effects cannot be started, and existing ones cannot be modified. Doing so can cause the subsequent FFSFFC_CONTINUE command to fail to perform properly.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "To abandon a pause and stop all effects, use the FFSFFC_STOPALL or FFSFCC_RESET commands.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "FFSFFC_RESET",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The device’s force feedback system is to be put in its startup state. All effects are removed from the device, are no longer valid, and must be recreated if they are to be used again. The device’s actuators are disabled.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "FFSFFC_SETACTUATORSOFF",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The device’s force feedback actuators are to be disabled. While the actuators are off, effects continue to play but are ignored by the device. Using the analogy of a sound playback device, they are muted, rather than paused.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "FFSFFC_SETACTUATORSON",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The device’s force feedback actuators are to be enabled.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "FFSFFC_STOPALL",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Playback of any active effects is to be stopped. All active effects are reset, but are still being maintained by the device and are still valid. If the device is in a paused state, that state is lost.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This command is equivalent to calling the FFEffect_Stop method for each effect playing.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the method succeeds, the return value is FF_OK. If the method fails, the return value can be one of the following error values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "FFERR_INVALIDPARAM",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "FFERR_INTERNAL",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCommandFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCommandFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCommandFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcommandflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCreateDevice(_:_:)": {
      "abstract": [
        {
          "text": "Creates a new API device object from an OS object in preparation to use the device for force feedback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCreateDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@io_service_t",
          "text": "io_service_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCreateDevice(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCreateDevice"
        }
      ],
      "role": "symbol",
      "title": "FFCreateDevice(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcreatedevice(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceCreateEffect(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates and initializes an instance of an effect identified by the effect UUID on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceCreateEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFUUIDRef",
          "text": "CFUUID"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFECT",
          "text": "FFEFFECT"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceCreateEffect(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceCreateEffect"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceCreateEffect(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicecreateeffect(_:_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceEscape(_:_:)": {
      "abstract": [
        {
          "text": "Sends a hardware-specific command to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceEscape"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFESCAPE",
          "text": "FFEFFESCAPE"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceEscape(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceEscape"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceEscape(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdeviceescape(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackCapabilities(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the device’s force feedback capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackCapabilities"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFCAPABILITIES",
          "text": "FFCAPABILITIES"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackCapabilities(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackCapabilities"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceGetForceFeedbackCapabilities(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicegetforcefeedbackcapabilities(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets properties that define the device behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFProperty",
          "text": "FFProperty"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOByteCount",
          "text": "IOByteCount"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackProperty"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceGetForceFeedbackProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicegetforcefeedbackproperty(_:_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackState(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the state of the device’s force feedback system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFState",
          "text": "FFState"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackState(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackState"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceGetForceFeedbackState(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicegetforcefeedbackstate(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceObjectReference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceObjectReference"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceObjectReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceObjectReference"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceObjectReference",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdeviceobjectreference"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceReleaseEffect(_:_:)": {
      "abstract": [
        {
          "text": "Disposes of an API effect object created with FFDeviceCreateEffect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceReleaseEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceReleaseEffect(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceReleaseEffect"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceReleaseEffect(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicereleaseeffect(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSendForceFeedbackCommand(_:_:)": {
      "abstract": [
        {
          "text": "Sends a command to the device’s force feedback system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceSendForceFeedbackCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFCommandFlag",
          "text": "FFCommandFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSendForceFeedbackCommand(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceSendForceFeedbackCommand"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceSendForceFeedbackCommand(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicesendforcefeedbackcommand(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetCooperativeLevel(_:_:_:)": {
      "abstract": [
        {
          "text": "Function is unimplemented in version 1.0 of this API",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceSetCooperativeLevel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFCooperativeLevelFlag",
          "text": "FFCooperativeLevelFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetCooperativeLevel(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceSetCooperativeLevel"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceSetCooperativeLevel(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicesetcooperativelevel(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetForceFeedbackProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the device’s force feedback capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceSetForceFeedbackProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFProperty",
          "text": "FFProperty"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetForceFeedbackProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceSetForceFeedbackProperty"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceSetForceFeedbackProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicesetforcefeedbackproperty(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectDownload(_:)": {
      "abstract": [
        {
          "text": "Places the effect on the device. If the effect is already on the device, the existing effect is updated to match the values set by the FFEffectSetParameters method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectDownload"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectDownload(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectDownload"
        }
      ],
      "role": "symbol",
      "title": "FFEffectDownload(_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectdownload(_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectEscape(_:_:)": {
      "abstract": [
        {
          "text": "Sends a hardware-specific command to the driver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectEscape"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFESCAPE",
          "text": "FFEFFESCAPE"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectEscape(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectEscape"
        }
      ],
      "role": "symbol",
      "title": "FFEffectEscape(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectescape(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetEffectStatus(_:_:)": {
      "abstract": [
        {
          "text": "Sends a hardware-specific command to the driver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectGetEffectStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectStatusFlag",
          "text": "FFEffectStatusFlag"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetEffectStatus(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectGetEffectStatus"
        }
      ],
      "role": "symbol",
      "title": "FFEffectGetEffectStatus(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectgeteffectstatus(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetParameters(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves information about an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectGetParameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFECT",
          "text": "FFEFFECT"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectParameterFlag",
          "text": "FFEffectParameterFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetParameters(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectGetParameters"
        }
      ],
      "role": "symbol",
      "title": "FFEffectGetParameters(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectgetparameters(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectSetParameters(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the characteristics of an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectSetParameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFECT",
          "text": "FFEFFECT"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectParameterFlag",
          "text": "FFEffectParameterFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectSetParameters(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectSetParameters"
        }
      ],
      "role": "symbol",
      "title": "FFEffectSetParameters(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectsetparameters(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStart(_:_:_:)": {
      "abstract": [
        {
          "text": "Begins playing an effect. If the effect is already playing, it is restarted from the beginning. If the effect has not been downloaded or has been modified since its last download, it is downloaded before being started. This default behavior can be suppressed by passing the FFES_NODOWNLOAD flag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectStartFlag",
          "text": "FFEffectStartFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStart(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStart"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStart(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstart(_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCreateDevice(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceCreateEffect(_:_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceEscape(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackCapabilities(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackProperty(_:_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackState(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceReleaseEffect(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetCooperativeLevel(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetForceFeedbackProperty(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectDownload(_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectEscape(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetEffectStatus(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetParameters(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectSetParameters(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStart(_:_:_:)"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFDeviceSendForceFeedbackCommand"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceSendForceFeedbackCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCreateDevice(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceCreateEffect(_:_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceEscape(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackCapabilities(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackProperty(_:_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackState(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceReleaseEffect(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetCooperativeLevel(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetForceFeedbackProperty(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectDownload(_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectEscape(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetEffectStatus(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetParameters(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectSetParameters(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStart(_:_:_:)"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@HRESULT",
                    "text": "HRESULT"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FFDeviceSendForceFeedbackCommand"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceObjectReference",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FFDeviceObjectReference",
                    "text": "FFDeviceObjectReference"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "deviceReference"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FFCommandFlag",
                    "text": "FFCommandFlag"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An opaque reference handle to the device object that is be disposed of. This handle is obtained from a previous call to FFCreateDevice.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "deviceReference"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Single value indicating the desired change in state. The value can be one of the following:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "FFSFFC_CONTINUE",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Paused playback of all active effects is to be continued. It is an error to send this command when the device is not in a paused state.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "FFSFFC_PAUSE",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Playback of all active effects is to be paused. This command also stops the clock-on effects so that they continue playing to their full duration when restarted.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "While the device is paused, new effects cannot be started, and existing ones cannot be modified. Doing so can cause the subsequent FFSFFC_CONTINUE command to fail to perform properly.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "To abandon a pause and stop all effects, use the FFSFFC_STOPALL or FFSFCC_RESET commands.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "FFSFFC_RESET",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The device’s force feedback system is to be put in its startup state. All effects are removed from the device, are no longer valid, and must be recreated if they are to be used again. The device’s actuators are disabled.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "FFSFFC_SETACTUATORSOFF",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The device’s force feedback actuators are to be disabled. While the actuators are off, effects continue to play but are ignored by the device. Using the analogy of a sound playback device, they are muted, rather than paused.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "FFSFFC_SETACTUATORSON",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The device’s force feedback actuators are to be enabled.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "FFSFFC_STOPALL",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Playback of any active effects is to be stopped. All active effects are reset, but are still being maintained by the device and are still valid. If the device is in a paused state, that state is lost.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "This command is equivalent to calling the FFEffect_Stop method for each effect playing.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "flags"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "If the method succeeds, the return value is FF_OK. If the method fails, the return value can be one of the following error values:",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceObjectReference/title",
          "value": "FFDeviceObjectReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceObjectReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceObjectReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceObjectReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceObjectReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceCreateEffect(_:_:_:_:)/title",
          "value": "FFDeviceCreateEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceCreateEffect(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceCreateEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceEscape(_:_:)/title",
          "value": "FFDeviceEscape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceEscape(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceEscape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSendForceFeedbackCommand(_:_:)/title",
          "value": "FFDeviceSendForceFeedbackCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSendForceFeedbackCommand(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceSendForceFeedbackCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectEscape(_:_:)/title",
          "value": "FFEffectEscape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectEscape(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectEscape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectGetEffectStatus(_:_:)/title",
          "value": "FFEffectGetEffectStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectGetEffectStatus(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectGetEffectStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackCapabilities(_:_:)/title",
          "value": "FFDeviceGetForceFeedbackCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackCapabilities(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceGetForceFeedbackCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCreateDevice(_:_:)/title",
          "value": "FFCreateDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCreateDevice(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCreateDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectGetParameters(_:_:_:)/title",
          "value": "FFEffectGetParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectGetParameters(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectGetParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackProperty(_:_:_:_:)/title",
          "value": "FFDeviceGetForceFeedbackProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceGetForceFeedbackProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackState(_:_:)/title",
          "value": "FFDeviceGetForceFeedbackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackState(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceGetForceFeedbackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectSetParameters(_:_:_:)/title",
          "value": "FFEffectSetParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectSetParameters(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectSetParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/title",
          "value": "FFCommandFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCommandFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCommandFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSetForceFeedbackProperty(_:_:_:)/title",
          "value": "FFDeviceSetForceFeedbackProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSetForceFeedbackProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceSetForceFeedbackProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectDownload(_:)/title",
          "value": "FFEffectDownload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectDownload(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectDownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStart(_:_:_:)/title",
          "value": "FFEffectStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStart(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceReleaseEffect(_:_:)/title",
          "value": "FFDeviceReleaseEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceReleaseEffect(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceReleaseEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSetCooperativeLevel(_:_:_:)/title",
          "value": "FFDeviceSetCooperativeLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSetCooperativeLevel(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceSetCooperativeLevel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffdevicesendforcefeedbackcommand(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffdevicesendforcefeedbackcommand(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
