{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_START"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@FFEP_DURATION@FFEP_START",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFEP_START"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFEP_START"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "FFEP_START"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFEP_START"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEB_NOTRIGGER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEB_NOTRIGGER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEB_NOTRIGGER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEB_NOTRIGGER"
        }
      ],
      "role": "symbol",
      "title": "FFEB_NOTRIGGER",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeb_notrigger"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_ALLPARAMS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_ALLPARAMS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_ALLPARAMS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_ALLPARAMS"
        }
      ],
      "role": "symbol",
      "title": "FFEP_ALLPARAMS",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_allparams"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_AXES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_AXES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_AXES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_AXES"
        }
      ],
      "role": "symbol",
      "title": "FFEP_AXES",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_axes"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_DIRECTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_DIRECTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_DIRECTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_DIRECTION"
        }
      ],
      "role": "symbol",
      "title": "FFEP_DIRECTION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_direction"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_DURATION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_DURATION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_DURATION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_DURATION"
        }
      ],
      "role": "symbol",
      "title": "FFEP_DURATION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_duration"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_ENVELOPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_ENVELOPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_ENVELOPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_ENVELOPE"
        }
      ],
      "role": "symbol",
      "title": "FFEP_ENVELOPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_envelope"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_GAIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_GAIN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_GAIN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_GAIN"
        }
      ],
      "role": "symbol",
      "title": "FFEP_GAIN",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_gain"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_NODOWNLOAD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_NODOWNLOAD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_NODOWNLOAD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_NODOWNLOAD"
        }
      ],
      "role": "symbol",
      "title": "FFEP_NODOWNLOAD",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_nodownload"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_NORESTART": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_NORESTART"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_NORESTART",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_NORESTART"
        }
      ],
      "role": "symbol",
      "title": "FFEP_NORESTART",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_norestart"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_SAMPLEPERIOD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_SAMPLEPERIOD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_SAMPLEPERIOD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_SAMPLEPERIOD"
        }
      ],
      "role": "symbol",
      "title": "FFEP_SAMPLEPERIOD",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_sampleperiod"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_START": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_START"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_START",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_START"
        }
      ],
      "role": "symbol",
      "title": "FFEP_START",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_start"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_STARTDELAY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_STARTDELAY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_STARTDELAY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_STARTDELAY"
        }
      ],
      "role": "symbol",
      "title": "FFEP_STARTDELAY",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_startdelay"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TRIGGERBUTTON": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_TRIGGERBUTTON"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TRIGGERBUTTON",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_TRIGGERBUTTON"
        }
      ],
      "role": "symbol",
      "title": "FFEP_TRIGGERBUTTON",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_triggerbutton"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TRIGGERREPEATINTERVAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_TRIGGERREPEATINTERVAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TRIGGERREPEATINTERVAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_TRIGGERREPEATINTERVAL"
        }
      ],
      "role": "symbol",
      "title": "FFEP_TRIGGERREPEATINTERVAL",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_triggerrepeatinterval"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TYPESPECIFICPARAMS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEP_TYPESPECIFICPARAMS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TYPESPECIFICPARAMS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEP_TYPESPECIFICPARAMS"
        }
      ],
      "role": "symbol",
      "title": "FFEP_TYPESPECIFICPARAMS",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffep_typespecificparams"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEB_NOTRIGGER",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_ALLPARAMS",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_AXES",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_DIRECTION",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_DURATION",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_ENVELOPE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_GAIN",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_NODOWNLOAD",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_NORESTART",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_SAMPLEPERIOD",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_STARTDELAY",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TRIGGERBUTTON",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TRIGGERREPEATINTERVAL",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TYPESPECIFICPARAMS"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFEP_START"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_START"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEB_NOTRIGGER",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_ALLPARAMS",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_AXES",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_DIRECTION",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_DURATION",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_ENVELOPE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_GAIN",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_NODOWNLOAD",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_NORESTART",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_SAMPLEPERIOD",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_STARTDELAY",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TRIGGERBUTTON",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TRIGGERREPEATINTERVAL",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEP_TYPESPECIFICPARAMS"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "FFEP_START"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_DIRECTION/title",
          "value": "FFEP_DIRECTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_DIRECTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_DIRECTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_TRIGGERBUTTON/title",
          "value": "FFEP_TRIGGERBUTTON"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_TRIGGERBUTTON/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_TRIGGERBUTTON"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_AXES/title",
          "value": "FFEP_AXES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_AXES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_AXES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_ENVELOPE/title",
          "value": "FFEP_ENVELOPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_ENVELOPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_ENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_STARTDELAY/title",
          "value": "FFEP_STARTDELAY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_STARTDELAY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_STARTDELAY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_GAIN/title",
          "value": "FFEP_GAIN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_GAIN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_GAIN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_DURATION/title",
          "value": "FFEP_DURATION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_DURATION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_DURATION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_ALLPARAMS/title",
          "value": "FFEP_ALLPARAMS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_ALLPARAMS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_ALLPARAMS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_NORESTART/title",
          "value": "FFEP_NORESTART"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_NORESTART/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_NORESTART"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_START/title",
          "value": "FFEP_START"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_START/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_START"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_TYPESPECIFICPARAMS/title",
          "value": "FFEP_TYPESPECIFICPARAMS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_TYPESPECIFICPARAMS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_TYPESPECIFICPARAMS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_SAMPLEPERIOD/title",
          "value": "FFEP_SAMPLEPERIOD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_SAMPLEPERIOD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_SAMPLEPERIOD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEB_NOTRIGGER/title",
          "value": "FFEB_NOTRIGGER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEB_NOTRIGGER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEB_NOTRIGGER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_TRIGGERREPEATINTERVAL/title",
          "value": "FFEP_TRIGGERREPEATINTERVAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_TRIGGERREPEATINTERVAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_TRIGGERREPEATINTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_NODOWNLOAD/title",
          "value": "FFEP_NODOWNLOAD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEP_NODOWNLOAD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEP_NODOWNLOAD"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffep_start"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffep_start"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
