{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTED"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@FFERR_UNSUPPORTED",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFERR_UNSUPPORTED"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HRESULT",
        "text": "HRESULT"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFERR_UNSUPPORTED"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "FFERR_UNSUPPORTED"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFERR_UNSUPPORTED"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HRESULT",
              "text": "HRESULT"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The function called is not supported at this time",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/E_PENDING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "E_PENDING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/E_PENDING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "E_PENDING"
        }
      ],
      "role": "symbol",
      "title": "E_PENDING",
      "type": "topic",
      "url": "/documentation/forcefeedback/e_pending"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_OBJECTOFFSETS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFF_OBJECTOFFSETS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_OBJECTOFFSETS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFF_OBJECTOFFSETS"
        }
      ],
      "role": "symbol",
      "title": "FFEFF_OBJECTOFFSETS",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeff_objectoffsets"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEFULL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_DEVICEFULL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEFULL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_DEVICEFULL"
        }
      ],
      "role": "symbol",
      "title": "FFERR_DEVICEFULL",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_devicefull"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICENOTREG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFERR_DEVICENOTREG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICENOTREG",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFERR_DEVICENOTREG",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_devicenotreg"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEPAUSED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_DEVICEPAUSED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEPAUSED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_DEVICEPAUSED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_DEVICEPAUSED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_devicepaused"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICERELEASED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_DEVICERELEASED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICERELEASED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_DEVICERELEASED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_DEVICERELEASED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_devicereleased"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_UNSUPPORTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_UNSUPPORTED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_UNSUPPORTED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_unsupported"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DEGREES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_DEGREES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DEGREES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_DEGREES"
        }
      ],
      "role": "symbol",
      "title": "FF_DEGREES",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_degrees"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DOWNLOADSKIPPED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_DOWNLOADSKIPPED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DOWNLOADSKIPPED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_DOWNLOADSKIPPED"
        }
      ],
      "role": "symbol",
      "title": "FF_DOWNLOADSKIPPED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_downloadskipped"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_EFFECTRESTARTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_EFFECTRESTARTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_EFFECTRESTARTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_EFFECTRESTARTED"
        }
      ],
      "role": "symbol",
      "title": "FF_EFFECTRESTARTED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_effectrestarted"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FALSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_FALSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FALSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_FALSE"
        }
      ],
      "role": "symbol",
      "title": "FF_FALSE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_false"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FFNOMINALMAX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_FFNOMINALMAX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FFNOMINALMAX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_FFNOMINALMAX"
        }
      ],
      "role": "symbol",
      "title": "FF_FFNOMINALMAX",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_ffnominalmax"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_INFINITE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_INFINITE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_INFINITE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_INFINITE"
        }
      ],
      "role": "symbol",
      "title": "FF_INFINITE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_infinite"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_OK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_OK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_OK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_OK"
        }
      ],
      "role": "symbol",
      "title": "FF_OK",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_ok"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_SECONDS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_SECONDS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_SECONDS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_SECONDS"
        }
      ],
      "role": "symbol",
      "title": "FF_SECONDS",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_seconds"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_TRUNCATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_TRUNCATED"
        }
      ],
      "role": "symbol",
      "title": "FF_TRUNCATED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_truncated"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATEDANDRESTARTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_TRUNCATEDANDRESTARTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATEDANDRESTARTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_TRUNCATEDANDRESTARTED"
        }
      ],
      "role": "symbol",
      "title": "FF_TRUNCATEDANDRESTARTED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_truncatedandrestarted"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/E_PENDING",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DEGREES",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DOWNLOADSKIPPED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_EFFECTRESTARTED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FALSE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FFNOMINALMAX",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_INFINITE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_OK",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_SECONDS",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATEDANDRESTARTED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_OBJECTOFFSETS",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEFULL",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEPAUSED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICERELEASED"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFERR_UNSUPPORTED"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_UNSUPPORTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/E_PENDING",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DEGREES",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DOWNLOADSKIPPED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_EFFECTRESTARTED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FALSE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FFNOMINALMAX",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_INFINITE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_OK",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_SECONDS",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATEDANDRESTARTED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_OBJECTOFFSETS",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEFULL",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICENOTREG",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEPAUSED"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FFERR_UNSUPPORTED"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_SECONDS/title",
          "value": "FF_SECONDS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_SECONDS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_SECONDS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_TRUNCATEDANDRESTARTED/title",
          "value": "FF_TRUNCATEDANDRESTARTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_TRUNCATEDANDRESTARTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_TRUNCATEDANDRESTARTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_TRUNCATED/title",
          "value": "FF_TRUNCATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_TRUNCATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_TRUNCATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_DOWNLOADSKIPPED/title",
          "value": "FF_DOWNLOADSKIPPED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_DOWNLOADSKIPPED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_DOWNLOADSKIPPED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1E_PENDING/title",
          "value": "E_PENDING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1E_PENDING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "E_PENDING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_OBJECTOFFSETS/title",
          "value": "FFEFF_OBJECTOFFSETS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_OBJECTOFFSETS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFF_OBJECTOFFSETS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_EFFECTRESTARTED/title",
          "value": "FF_EFFECTRESTARTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_EFFECTRESTARTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_EFFECTRESTARTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_FALSE/title",
          "value": "FF_FALSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_FALSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_FALSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICEFULL/title",
          "value": "FFERR_DEVICEFULL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICEFULL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_DEVICEFULL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_FFNOMINALMAX/title",
          "value": "FF_FFNOMINALMAX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_FFNOMINALMAX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_FFNOMINALMAX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_OK/title",
          "value": "FF_OK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_OK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_OK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICERELEASED/title",
          "value": "FFERR_DEVICERELEASED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICERELEASED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_DEVICERELEASED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_INFINITE/title",
          "value": "FF_INFINITE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_INFINITE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_INFINITE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_DEGREES/title",
          "value": "FF_DEGREES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_DEGREES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_DEGREES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_UNSUPPORTED/title",
          "value": "FFERR_UNSUPPORTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_UNSUPPORTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_UNSUPPORTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICEPAUSED/title",
          "value": "FFERR_DEVICEPAUSED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICEPAUSED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_DEVICEPAUSED"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/fferr_unsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/fferr_unsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
