{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_SAFETYSWITCHON"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@FFGFFS_EMPTY@FFGFFS_SAFETYSWITCHON",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFGFFS_SAFETYSWITCHON"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFGFFS_SAFETYSWITCHON"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "FFGFFS_SAFETYSWITCHON"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFGFFS_SAFETYSWITCHON"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_ACTUATORSOFF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_ACTUATORSOFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_ACTUATORSOFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_ACTUATORSOFF"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_ACTUATORSOFF",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_actuatorsoff"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_ACTUATORSON": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_ACTUATORSON"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_ACTUATORSON",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_ACTUATORSON"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_ACTUATORSON",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_actuatorson"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_DEVICELOST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_DEVICELOST"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_DEVICELOST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_DEVICELOST"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_DEVICELOST",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_devicelost"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_EMPTY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_EMPTY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_EMPTY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_EMPTY"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_EMPTY",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_empty"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_PAUSED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_PAUSED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_PAUSED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_PAUSED"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_PAUSED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_paused"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_POWEROFF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_POWEROFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_POWEROFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_POWEROFF"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_POWEROFF",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_poweroff"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_POWERON": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_POWERON"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_POWERON",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_POWERON"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_POWERON",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_poweron"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_SAFETYSWITCHOFF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_SAFETYSWITCHOFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_SAFETYSWITCHOFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_SAFETYSWITCHOFF"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_SAFETYSWITCHOFF",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_safetyswitchoff"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_SAFETYSWITCHON": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_SAFETYSWITCHON"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_SAFETYSWITCHON",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_SAFETYSWITCHON"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_SAFETYSWITCHON",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_safetyswitchon"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_STOPPED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_STOPPED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_STOPPED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_STOPPED"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_STOPPED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_stopped"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_USERFFSWITCHOFF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_USERFFSWITCHOFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_USERFFSWITCHOFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_USERFFSWITCHOFF"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_USERFFSWITCHOFF",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_userffswitchoff"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_USERFFSWITCHON": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFGFFS_USERFFSWITCHON"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_USERFFSWITCHON",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFGFFS_USERFFSWITCHON"
        }
      ],
      "role": "symbol",
      "title": "FFGFFS_USERFFSWITCHON",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffgffs_userffswitchon"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_ACTUATORSOFF",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_ACTUATORSON",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_DEVICELOST",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_EMPTY",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_PAUSED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_POWEROFF",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_POWERON",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_SAFETYSWITCHOFF",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_STOPPED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_USERFFSWITCHOFF",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_USERFFSWITCHON"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFGFFS_SAFETYSWITCHON"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_SAFETYSWITCHON"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_ACTUATORSOFF",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_ACTUATORSON",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_DEVICELOST",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_EMPTY",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_PAUSED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_POWEROFF",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_POWERON",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_SAFETYSWITCHOFF",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_STOPPED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_USERFFSWITCHOFF",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFGFFS_USERFFSWITCHON"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "FFGFFS_SAFETYSWITCHON"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_POWEROFF/title",
          "value": "FFGFFS_POWEROFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_POWEROFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_POWEROFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_STOPPED/title",
          "value": "FFGFFS_STOPPED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_STOPPED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_STOPPED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_SAFETYSWITCHON/title",
          "value": "FFGFFS_SAFETYSWITCHON"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_SAFETYSWITCHON/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_SAFETYSWITCHON"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_USERFFSWITCHOFF/title",
          "value": "FFGFFS_USERFFSWITCHOFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_USERFFSWITCHOFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_USERFFSWITCHOFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_USERFFSWITCHON/title",
          "value": "FFGFFS_USERFFSWITCHON"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_USERFFSWITCHON/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_USERFFSWITCHON"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_ACTUATORSOFF/title",
          "value": "FFGFFS_ACTUATORSOFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_ACTUATORSOFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_ACTUATORSOFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_PAUSED/title",
          "value": "FFGFFS_PAUSED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_PAUSED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_PAUSED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_EMPTY/title",
          "value": "FFGFFS_EMPTY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_EMPTY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_EMPTY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_POWERON/title",
          "value": "FFGFFS_POWERON"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_POWERON/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_POWERON"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_SAFETYSWITCHOFF/title",
          "value": "FFGFFS_SAFETYSWITCHOFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_SAFETYSWITCHOFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_SAFETYSWITCHOFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_ACTUATORSON/title",
          "value": "FFGFFS_ACTUATORSON"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_ACTUATORSON/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_ACTUATORSON"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_DEVICELOST/title",
          "value": "FFGFFS_DEVICELOST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFGFFS_DEVICELOST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFGFFS_DEVICELOST"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffgffs_safetyswitchon"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffgffs_safetyswitchon"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
