{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "collectionGroup",
    "title": "ForceFeedback Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Constants",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-constants"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Data Types",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-data-types"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524447-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524471-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524506-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524522-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524526-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524537-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524546-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524560-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524566-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524584-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h": {
      "abstract": [
        {
          "text": "Public Interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Structures",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-structures"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h": {
      "abstract": [
        {
          "text": "Constants used in the public interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedbackConstants.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackconstants-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h": {
      "abstract": [
        {
          "text": "Public Interfaces and constants used to develop Force Feedback plugIns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOForceFeedbackLib.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/ioforcefeedbacklib-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedback-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedback-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
