{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_CONTINUE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFSFFC_CONTINUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_CONTINUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFSFFC_CONTINUE"
        }
      ],
      "role": "symbol",
      "title": "FFSFFC_CONTINUE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffsffc_continue"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_PAUSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFSFFC_PAUSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_PAUSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFSFFC_PAUSE"
        }
      ],
      "role": "symbol",
      "title": "FFSFFC_PAUSE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffsffc_pause"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_RESET": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFSFFC_RESET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_RESET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFSFFC_RESET"
        }
      ],
      "role": "symbol",
      "title": "FFSFFC_RESET",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffsffc_reset"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_SETACTUATORSOFF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFSFFC_SETACTUATORSOFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_SETACTUATORSOFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFSFFC_SETACTUATORSOFF"
        }
      ],
      "role": "symbol",
      "title": "FFSFFC_SETACTUATORSOFF",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffsffc_setactuatorsoff"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_SETACTUATORSON": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFSFFC_SETACTUATORSON"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_SETACTUATORSON",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFSFFC_SETACTUATORSON"
        }
      ],
      "role": "symbol",
      "title": "FFSFFC_SETACTUATORSON",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffsffc_setactuatorson"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_STOPALL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFSFFC_STOPALL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_STOPALL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFSFFC_STOPALL"
        }
      ],
      "role": "symbol",
      "title": "FFSFFC_STOPALL",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffsffc_stopall"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Enumerations",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524447-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524471-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524522-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524526-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524537-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524546-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524560-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524566-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524584-anonymous"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_CONTINUE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_PAUSE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_RESET",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_SETACTUATORSOFF",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_SETACTUATORSON",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFSFFC_STOPALL"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_RESET/title",
          "value": "FFSFFC_RESET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_RESET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFSFFC_RESET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_STOPALL/title",
          "value": "FFSFFC_STOPALL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_STOPALL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFSFFC_STOPALL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_CONTINUE/title",
          "value": "FFSFFC_CONTINUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_CONTINUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFSFFC_CONTINUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_PAUSE/title",
          "value": "FFSFFC_PAUSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_PAUSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFSFFC_PAUSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_SETACTUATORSOFF/title",
          "value": "FFSFFC_SETACTUATORSOFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_SETACTUATORSOFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFSFFC_SETACTUATORSOFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_SETACTUATORSON/title",
          "value": "FFSFFC_SETACTUATORSON"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFSFFC_SETACTUATORSON/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFSFFC_SETACTUATORSON"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedback-enumerations-1524506-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
