{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_CARTESIAN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFF_CARTESIAN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_CARTESIAN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFF_CARTESIAN"
        }
      ],
      "role": "symbol",
      "title": "FFEFF_CARTESIAN",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeff_cartesian"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_POLAR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFF_POLAR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_POLAR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFF_POLAR"
        }
      ],
      "role": "symbol",
      "title": "FFEFF_POLAR",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeff_polar"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_SPHERICAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFF_SPHERICAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_SPHERICAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFF_SPHERICAL"
        }
      ],
      "role": "symbol",
      "title": "FFEFF_SPHERICAL",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeff_spherical"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Enumerations",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524447-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524471-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524506-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524522-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524526-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524537-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524546-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524560-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524566-anonymous"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_CARTESIAN",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_POLAR",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_SPHERICAL"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_SPHERICAL/title",
          "value": "FFEFF_SPHERICAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_SPHERICAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFF_SPHERICAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_CARTESIAN/title",
          "value": "FFEFF_CARTESIAN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_CARTESIAN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFF_CARTESIAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_POLAR/title",
          "value": "FFEFF_POLAR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_POLAR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFF_POLAR"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedback-enumerations-1524584-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
