{
  "abstract": [
    {
      "text": "Constants used in the public interfaces to the Force Feedback implementation in macOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ForceFeedbackConstants.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This header file contains the Effect type UUIDs, type definitions used in the API, force feedback constants and error values used by the API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectSubType"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectSubType"
        }
      ],
      "role": "symbol",
      "title": "FFCapabilitiesEffectSubType",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilitieseffectsubtype"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectType"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectType"
        }
      ],
      "role": "symbol",
      "title": "FFCapabilitiesEffectType",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilitieseffecttype"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCommandFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCommandFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCommandFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcommandflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCooperativeLevelFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCooperativeLevelFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCooperativeLevelFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcooperativelevelflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCoordinateSystemFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCoordinateSystemFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCoordinateSystemFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcoordinatesystemflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectParameterFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectParameterFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectParameterFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectparameterflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStartFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStartFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStartFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstartflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStatusFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStatusFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStatusFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstatusflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFProperty"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFProperty"
        }
      ],
      "role": "symbol",
      "title": "FFProperty",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffproperty"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFState"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFState"
        }
      ],
      "role": "symbol",
      "title": "FFState",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffstate"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Constants",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-constants"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Data Types",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-data-types"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Enumerations",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h": {
      "abstract": [
        {
          "text": "Public Interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Structures",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-structures"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h": {
      "abstract": [
        {
          "text": "Public Interfaces and constants used to develop Force Feedback plugIns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOForceFeedbackLib.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/ioforcefeedbacklib-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Miscellaneous Defines",
      "type": "topic",
      "url": "/documentation/forcefeedback/miscellaneous-defines"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "See the Overview section above for header-level documentation.",
                  "type": "text"
                }
              ],
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/title",
          "value": "FFProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/title",
          "value": "FFCommandFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCommandFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCommandFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/title",
          "value": "FFCooperativeLevelFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCooperativeLevelFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCooperativeLevelFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/title",
          "value": "FFCapabilitiesEffectSubType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/title",
          "value": "FFEffectStartFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStartFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStartFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/title",
          "value": "FFEffectStatusFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStatusFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStatusFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/title",
          "value": "FFCoordinateSystemFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCoordinateSystemFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCoordinateSystemFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/title",
          "value": "FFEffectParameterFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectParameterFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectParameterFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/title",
          "value": "FFState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/title",
          "value": "FFCapabilitiesEffectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedbackconstants-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedbackconstants-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
