{
  "abstract": [
    {
      "text": "Public Interfaces to the Force Feedback implementation in macOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ForceFeedback.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Force Feedback API allows developers to control Force Feedback devices attached to the system. It is a distilled version of the Force Feedback functionality found in Microsoft’s DirectInput API. Developers familiar with that API should find this API to be similar.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Included-Headers",
          "level": 3,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<CoreFoundation/CoreFoundation.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<CoreFoundation/CFPlugInCOM.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<MacTypes.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<IOKit/IOTypes.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<ForceFeedback/ForceFeedbackConstants.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES": {
      "abstract": [
        {
          "text": "Used by the FFDeviceGetForceFeedbackCapabilities method to retrieve device force-feedback capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAPABILITIES"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAPABILITIES"
        }
      ],
      "role": "symbol",
      "title": "FFCAPABILITIES",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilities"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION": {
      "abstract": [
        {
          "text": "A structure containing type-specific information for certain effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCONDITION"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCONDITION"
        }
      ],
      "role": "symbol",
      "title": "FFCONDITION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the CONSTANTFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCONSTANTFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCONSTANTFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCONSTANTFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffconstantforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the CUSTOMFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCUSTOMFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCUSTOMFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCUSTOMFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcustomforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCreateDevice(_:_:)": {
      "abstract": [
        {
          "text": "Creates a new API device object from an OS object in preparation to use the device for force feedback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCreateDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@io_service_t",
          "text": "io_service_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCreateDevice(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCreateDevice"
        }
      ],
      "role": "symbol",
      "title": "FFCreateDevice(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcreatedevice(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceCreateEffect(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates and initializes an instance of an effect identified by the effect UUID on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceCreateEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFUUIDRef",
          "text": "CFUUID"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFECT",
          "text": "FFEFFECT"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceCreateEffect(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceCreateEffect"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceCreateEffect(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicecreateeffect(_:_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceEscape(_:_:)": {
      "abstract": [
        {
          "text": "Sends a hardware-specific command to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceEscape"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFESCAPE",
          "text": "FFEFFESCAPE"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceEscape(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceEscape"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceEscape(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdeviceescape(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackCapabilities(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the device’s force feedback capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackCapabilities"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFCAPABILITIES",
          "text": "FFCAPABILITIES"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackCapabilities(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackCapabilities"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceGetForceFeedbackCapabilities(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicegetforcefeedbackcapabilities(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Gets properties that define the device behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFProperty",
          "text": "FFProperty"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOByteCount",
          "text": "IOByteCount"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackProperty"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceGetForceFeedbackProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicegetforcefeedbackproperty(_:_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackState(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the state of the device’s force feedback system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFState",
          "text": "FFState"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackState(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceGetForceFeedbackState"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceGetForceFeedbackState(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicegetforcefeedbackstate(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceReleaseEffect(_:_:)": {
      "abstract": [
        {
          "text": "Disposes of an API effect object created with FFDeviceCreateEffect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceReleaseEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceReleaseEffect(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceReleaseEffect"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceReleaseEffect(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicereleaseeffect(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSendForceFeedbackCommand(_:_:)": {
      "abstract": [
        {
          "text": "Sends a command to the device’s force feedback system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceSendForceFeedbackCommand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFCommandFlag",
          "text": "FFCommandFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSendForceFeedbackCommand(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceSendForceFeedbackCommand"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceSendForceFeedbackCommand(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicesendforcefeedbackcommand(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetCooperativeLevel(_:_:_:)": {
      "abstract": [
        {
          "text": "Function is unimplemented in version 1.0 of this API",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceSetCooperativeLevel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFCooperativeLevelFlag",
          "text": "FFCooperativeLevelFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetCooperativeLevel(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceSetCooperativeLevel"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceSetCooperativeLevel(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicesetcooperativelevel(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetForceFeedbackProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the device’s force feedback capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceSetForceFeedbackProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFProperty",
          "text": "FFProperty"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetForceFeedbackProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceSetForceFeedbackProperty"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceSetForceFeedbackProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicesetforcefeedbackproperty(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT": {
      "abstract": [
        {
          "text": "UsUsed by the FFDeviceCreateEffect method to initialize a new effect object. It is also used by the FFEffectSetParameters and FFEffectGetParameters functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFFECT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFFECT"
        }
      ],
      "role": "symbol",
      "title": "FFEFFECT",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffect"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE": {
      "abstract": [
        {
          "text": "The FFEFFESCAPE structure passes hardware-specific data directly to the Force Feedback plugIn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFFESCAPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFFESCAPE"
        }
      ],
      "role": "symbol",
      "title": "FFEFFESCAPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffescape"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE": {
      "abstract": [
        {
          "text": "Used by the FFEFFECT structure to specify the optional envelope parameters for an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFENVELOPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFENVELOPE"
        }
      ],
      "role": "symbol",
      "title": "FFENVELOPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffenvelope"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectDownload(_:)": {
      "abstract": [
        {
          "text": "Places the effect on the device. If the effect is already on the device, the existing effect is updated to match the values set by the FFEffectSetParameters method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectDownload"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectDownload(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectDownload"
        }
      ],
      "role": "symbol",
      "title": "FFEffectDownload(_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectdownload(_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectEscape(_:_:)": {
      "abstract": [
        {
          "text": "Sends a hardware-specific command to the driver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectEscape"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFESCAPE",
          "text": "FFEFFESCAPE"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectEscape(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectEscape"
        }
      ],
      "role": "symbol",
      "title": "FFEffectEscape(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectescape(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetEffectStatus(_:_:)": {
      "abstract": [
        {
          "text": "Sends a hardware-specific command to the driver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectGetEffectStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectStatusFlag",
          "text": "FFEffectStatusFlag"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetEffectStatus(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectGetEffectStatus"
        }
      ],
      "role": "symbol",
      "title": "FFEffectGetEffectStatus(_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectgeteffectstatus(_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetParameters(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves information about an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectGetParameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFECT",
          "text": "FFEFFECT"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectParameterFlag",
          "text": "FFEffectParameterFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetParameters(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectGetParameters"
        }
      ],
      "role": "symbol",
      "title": "FFEffectGetParameters(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectgetparameters(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectSetParameters(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the characteristics of an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectSetParameters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@FFEFFECT",
          "text": "FFEFFECT"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectParameterFlag",
          "text": "FFEffectParameterFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectSetParameters(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectSetParameters"
        }
      ],
      "role": "symbol",
      "title": "FFEffectSetParameters(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectsetparameters(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStart(_:_:_:)": {
      "abstract": [
        {
          "text": "Begins playing an effect. If the effect is already playing, it is restarted from the beginning. If the effect has not been downloaded or has been modified since its last download, it is downloaded before being started. This default behavior can be suppressed by passing the FFES_NODOWNLOAD flag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectStartFlag",
          "text": "FFEffectStartFlag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStart(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStart"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStart(_:_:_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstart(_:_:_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStop(_:)": {
      "abstract": [
        {
          "text": "Stops playing an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStop"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStop(_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstop(_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectUnload(_:)": {
      "abstract": [
        {
          "text": "Removes the effect from the device. If the effect is playing, it is automatically stopped before it is unloaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectUnload"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFEffectObjectReference",
          "text": "FFEffectObjectReference"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectUnload(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectUnload"
        }
      ],
      "role": "symbol",
      "title": "FFEffectUnload(_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectunload(_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFIsForceFeedback(_:)": {
      "abstract": [
        {
          "text": "Used to determine if a particular device provided by HID Manager is a force feedback device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFIsForceFeedback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@io_service_t",
          "text": "io_service_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFIsForceFeedback(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFIsForceFeedback"
        }
      ],
      "role": "symbol",
      "title": "FFIsForceFeedback(_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffisforcefeedback(_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC": {
      "abstract": [
        {
          "text": "A structure containing type-specific information for certain effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFPERIODIC"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFPERIODIC"
        }
      ],
      "role": "symbol",
      "title": "FFPERIODIC",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffperiodic"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE": {
      "abstract": [
        {
          "text": "Contains type-specific information for the RAMPFORCE effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFRAMPFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFRAMPFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFRAMPFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/fframpforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFReleaseDevice(_:)": {
      "abstract": [
        {
          "text": "Disposes of an API device object created with FFCreateDevice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFReleaseDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FFDeviceObjectReference",
          "text": "FFDeviceObjectReference"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFReleaseDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFReleaseDevice"
        }
      ],
      "role": "symbol",
      "title": "FFReleaseDevice(_:)",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffreleasedevice(_:)"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Constants",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-constants"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Data Types",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-data-types"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Enumerations",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Structures",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-structures"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h": {
      "abstract": [
        {
          "text": "Constants used in the public interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedbackConstants.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackconstants-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h": {
      "abstract": [
        {
          "text": "Public Interfaces and constants used to develop Force Feedback plugIns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOForceFeedbackLib.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/ioforcefeedbacklib-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCreateDevice(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceCreateEffect(_:_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceEscape(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackCapabilities(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackProperty(_:_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackState(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceReleaseEffect(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSendForceFeedbackCommand(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetCooperativeLevel(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetForceFeedbackProperty(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectDownload(_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectEscape(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetEffectStatus(_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetParameters(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectSetParameters(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStart(_:_:_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStop(_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectUnload(_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFIsForceFeedback(_:)",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFReleaseDevice(_:)"
      ],
      "title": "Miscellaneous"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCreateDevice(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceCreateEffect(_:_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceEscape(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackCapabilities(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackProperty(_:_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceGetForceFeedbackState(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceReleaseEffect(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSendForceFeedbackCommand(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetCooperativeLevel(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceSetForceFeedbackProperty(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectDownload(_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectEscape(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetEffectStatus(_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectGetParameters(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectSetParameters(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStart(_:_:_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStop(_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectUnload(_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFIsForceFeedback(_:)",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFReleaseDevice(_:)"
              ],
              "title": "Miscellaneous"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAPABILITIES",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONSTANTFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCUSTOMFORCE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFECT",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFFESCAPE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFENVELOPE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFRAMPFORCE"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/ioforcefeedbacklib-h",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-structures",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFReleaseDevice(_:)/title",
          "value": "FFReleaseDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFReleaseDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFReleaseDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceEscape(_:_:)/title",
          "value": "FFDeviceEscape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceEscape(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceEscape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSetForceFeedbackProperty(_:_:_:)/title",
          "value": "FFDeviceSetForceFeedbackProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSetForceFeedbackProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceSetForceFeedbackProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/title",
          "value": "FFENVELOPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFENVELOPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/title",
          "value": "FFCONDITION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/title",
          "value": "FFEFFECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFECT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSendForceFeedbackCommand(_:_:)/title",
          "value": "FFDeviceSendForceFeedbackCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSendForceFeedbackCommand(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceSendForceFeedbackCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectUnload(_:)/title",
          "value": "FFEffectUnload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectUnload(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectUnload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectSetParameters(_:_:_:)/title",
          "value": "FFEffectSetParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectSetParameters(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectSetParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceCreateEffect(_:_:_:_:)/title",
          "value": "FFDeviceCreateEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceCreateEffect(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceCreateEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFIsForceFeedback(_:)/title",
          "value": "FFIsForceFeedback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFIsForceFeedback(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFIsForceFeedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/title",
          "value": "FFPERIODIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFPERIODIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFPERIODIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackCapabilities(_:_:)/title",
          "value": "FFDeviceGetForceFeedbackCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackCapabilities(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceGetForceFeedbackCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/title",
          "value": "FFCAPABILITIES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAPABILITIES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAPABILITIES/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAPABILITIES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectGetEffectStatus(_:_:)/title",
          "value": "FFEffectGetEffectStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectGetEffectStatus(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectGetEffectStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceReleaseEffect(_:_:)/title",
          "value": "FFDeviceReleaseEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceReleaseEffect(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceReleaseEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectGetParameters(_:_:_:)/title",
          "value": "FFEffectGetParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectGetParameters(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectGetParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/title",
          "value": "FFCONSTANTFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONSTANTFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectDownload(_:)/title",
          "value": "FFEffectDownload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectDownload(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectDownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectEscape(_:_:)/title",
          "value": "FFEffectEscape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectEscape(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectEscape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/title",
          "value": "FFCUSTOMFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCUSTOMFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSetCooperativeLevel(_:_:_:)/title",
          "value": "FFDeviceSetCooperativeLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceSetCooperativeLevel(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceSetCooperativeLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStart(_:_:_:)/title",
          "value": "FFEffectStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStart(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStop(_:)/title",
          "value": "FFEffectStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStop(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/title",
          "value": "FFEFFESCAPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFFESCAPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackState(_:_:)/title",
          "value": "FFDeviceGetForceFeedbackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackState(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceGetForceFeedbackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCreateDevice(_:_:)/title",
          "value": "FFCreateDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCreateDevice(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCreateDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/title",
          "value": "FFRAMPFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFRAMPFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFRAMPFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFRAMPFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackProperty(_:_:_:_:)/title",
          "value": "FFDeviceGetForceFeedbackProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceGetForceFeedbackProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceGetForceFeedbackProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedback-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedback-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
