{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackVersionPtr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ForceFeedbackVersionPtr",
    "fragments": [
      {
        "kind": "identifier",
        "text": "ForceFeedbackVersionPtr"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ForceFeedbackVersionPtr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "ForceFeedbackVersionPtr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackVersion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@ForceFeedbackVersion",
              "text": "ForceFeedbackVersion"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "ForceFeedbackVersionPtr"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DWORD"
        }
      ],
      "role": "symbol",
      "title": "DWORD",
      "type": "topic",
      "url": "/documentation/forcefeedback/dword"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceObjectReference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFDeviceObjectReference"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceObjectReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFDeviceObjectReference"
        }
      ],
      "role": "symbol",
      "title": "FFDeviceObjectReference",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdeviceobjectreference"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectObjectReference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectObjectReference"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectObjectReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectObjectReference"
        }
      ],
      "role": "symbol",
      "title": "FFEffectObjectReference",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectobjectreference"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackDeviceStatePtr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ForceFeedbackDeviceStatePtr"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackDeviceStatePtr",
      "kind": "symbol",
      "role": "symbol",
      "title": "ForceFeedbackDeviceStatePtr",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackdevicestateptr"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackVersion": {
      "abstract": [
        {
          "text": "Used to return plugIn version information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ForceFeedbackVersion"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ForceFeedbackVersion",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackversion"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackVersionPtr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ForceFeedbackVersionPtr"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackVersionPtr",
      "kind": "symbol",
      "role": "symbol",
      "title": "ForceFeedbackVersionPtr",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackversionptr"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/IOForceFeedbackDeviceInterfacePtr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOForceFeedbackDeviceInterfacePtr"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/IOForceFeedbackDeviceInterfacePtr",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOForceFeedbackDeviceInterfacePtr",
      "type": "topic",
      "url": "/documentation/forcefeedback/ioforcefeedbackdeviceinterfaceptr"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/LONG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/LONG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LONG"
        }
      ],
      "role": "symbol",
      "title": "LONG",
      "type": "topic",
      "url": "/documentation/forcefeedback/long"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/LPDWORD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPDWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/LPDWORD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPDWORD"
        }
      ],
      "role": "symbol",
      "title": "LPDWORD",
      "type": "topic",
      "url": "/documentation/forcefeedback/lpdword"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/LPLONG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPLONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/LPLONG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPLONG"
        }
      ],
      "role": "symbol",
      "title": "LPLONG",
      "type": "topic",
      "url": "/documentation/forcefeedback/lplong"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCAPABILITIES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PFFCAPABILITIES"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCAPABILITIES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PFFCAPABILITIES"
        }
      ],
      "role": "symbol",
      "title": "PFFCAPABILITIES",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffcapabilities"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCONDITION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PFFCONDITION"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCONDITION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PFFCONDITION"
        }
      ],
      "role": "symbol",
      "title": "PFFCONDITION",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffcondition"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCONSTANTFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PFFCONSTANTFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCONSTANTFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PFFCONSTANTFORCE"
        }
      ],
      "role": "symbol",
      "title": "PFFCONSTANTFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffconstantforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCUSTOMFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PFFCUSTOMFORCE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCUSTOMFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PFFCUSTOMFORCE"
        }
      ],
      "role": "symbol",
      "title": "PFFCUSTOMFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffcustomforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFEFFECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PFFEFFECT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFEFFECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PFFEFFECT"
        }
      ],
      "role": "symbol",
      "title": "PFFEFFECT",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffeffect"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFEFFESCAPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PFFEFFESCAPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFEFFESCAPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PFFEFFESCAPE"
        }
      ],
      "role": "symbol",
      "title": "PFFEFFESCAPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffeffescape"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFENVELOPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PFFENVELOPE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFENVELOPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PFFENVELOPE"
        }
      ],
      "role": "symbol",
      "title": "PFFENVELOPE",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffenvelope"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDeviceObjectReference",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectObjectReference",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/ForceFeedbackDeviceStatePtr",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/IOForceFeedbackDeviceInterfacePtr",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/LONG",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/LPDWORD",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/LPLONG",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCAPABILITIES",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCONDITION",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCONSTANTFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFCUSTOMFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFEFFECT",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFEFFESCAPE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFENVELOPE"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceObjectReference/title",
          "value": "FFDeviceObjectReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceObjectReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceObjectReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFDeviceObjectReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFDeviceObjectReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LPDWORD/title",
          "value": "LPDWORD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LPDWORD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPDWORD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LPDWORD/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LPDWORD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCUSTOMFORCE/title",
          "value": "PFFCUSTOMFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCUSTOMFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCUSTOMFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFCUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFENVELOPE/title",
          "value": "PFFENVELOPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFENVELOPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFENVELOPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFENVELOPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LONG/title",
          "value": "LONG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LONG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LONG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LONG/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LONG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCAPABILITIES/title",
          "value": "PFFCAPABILITIES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCAPABILITIES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFCAPABILITIES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCAPABILITIES/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFCAPABILITIES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LPLONG/title",
          "value": "LPLONG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LPLONG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPLONG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LPLONG/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LPLONG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFEFFECT/title",
          "value": "PFFEFFECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFEFFECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFEFFECT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectObjectReference/title",
          "value": "FFEffectObjectReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectObjectReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectObjectReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectObjectReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectObjectReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFEFFESCAPE/title",
          "value": "PFFEFFESCAPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFEFFESCAPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFEFFESCAPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFEFFESCAPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCONSTANTFORCE/title",
          "value": "PFFCONSTANTFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCONSTANTFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFCONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCONSTANTFORCE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFCONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCONDITION/title",
          "value": "PFFCONDITION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCONDITION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1PFFCONDITION/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PFFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/title",
          "value": "DWORD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DWORD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DWORD"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedbackversionptr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
