{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ForceFeedback Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDEVICESTATE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFDEVICESTATE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDEVICESTATE",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFDEVICESTATE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffdevicestate"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON0"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON0",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON0",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button0"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON1"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON1",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON1",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button1"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON10": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON10"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON10",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON10",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button10"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON11": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON11"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON11",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON11",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button11"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON12": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON12"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON12",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON12",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button12"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON13": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON13"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON13",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON13",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button13"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON14": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON14"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON14",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON14",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button14"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON15": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON15"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON15",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON15",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button15"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON16"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON16",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON16",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button16"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON17": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON17"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON17",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON17",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button17"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON18": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON18"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON18",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON18",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button18"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON19": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON19"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON19",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON19",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button19"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON2"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON2",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON2",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button2"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON20": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON20"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON20",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON20",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button20"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON21": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON21"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON21",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON21",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button21"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON22": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON22"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON22",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON22",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button22"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON23": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON23"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON23",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON23",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button23"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON24"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON24",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON24",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button24"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON25": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON25"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON25",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON25",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button25"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON26": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON26"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON26",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON26",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button26"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON27": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON27"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON27",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON27",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button27"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON28": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON28"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON28",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON28",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button28"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON29": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON29"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON29",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON29",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button29"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON3"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON3",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON3",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button3"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON30": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON30"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON30",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON30",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button30"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON31": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON31"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON31",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON31",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button31"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON4"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON4",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON4",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button4"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON5"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON5",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON5",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button5"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON6"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON6",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON6",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button6"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON7"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON7",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON7",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button7"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON8"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON8",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON8",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button8"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON9": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_BUTTON9"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON9",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_BUTTON9",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_button9"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_POV": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_POV"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_POV",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_POV",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_pov"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFJOFS_RX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFJOFS_RX"
        }
      ],
      "role": "symbol",
      "title": "FFJOFS_RX",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_rx"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFJOFS_RY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFJOFS_RY"
        }
      ],
      "role": "symbol",
      "title": "FFJOFS_RY",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_ry"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RZ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFJOFS_RZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFJOFS_RZ"
        }
      ],
      "role": "symbol",
      "title": "FFJOFS_RZ",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_rz"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_SLIDER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFJOFS_SLIDER"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_SLIDER",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFJOFS_SLIDER",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_slider"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_Y": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFJOFS_Y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_Y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFJOFS_Y"
        }
      ],
      "role": "symbol",
      "title": "FFJOFS_Y",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_y"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_Z": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFJOFS_Z"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_Z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFJOFS_Z"
        }
      ],
      "role": "symbol",
      "title": "FFJOFS_Z",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_z"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/IOFORCEFEEDBACKDEVICE_FUNCS_100": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOFORCEFEEDBACKDEVICE_FUNCS_100"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/IOFORCEFEEDBACKDEVICE_FUNCS_100",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOFORCEFEEDBACKDEVICE_FUNCS_100",
      "type": "topic",
      "url": "/documentation/forcefeedback/ioforcefeedbackdevice_funcs_100"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFDEVICESTATE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PFFDEVICESTATE"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFDEVICESTATE",
      "kind": "symbol",
      "role": "symbol",
      "title": "PFFDEVICESTATE",
      "type": "topic",
      "url": "/documentation/forcefeedback/pffdevicestate"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Data Types",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-data-types"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Enumerations",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h": {
      "abstract": [
        {
          "text": "Public Interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h": {
      "abstract": [
        {
          "text": "Constants used in the public interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedbackConstants.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackconstants-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kIOForceFeedbackDeviceInterfaceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kIOForceFeedbackDeviceInterfaceID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kIOForceFeedbackDeviceInterfaceID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOForceFeedbackDeviceInterfaceID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kioforcefeedbackdeviceinterfaceid"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kIOForceFeedbackLibTypeID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kIOForceFeedbackLibTypeID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kIOForceFeedbackLibTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOForceFeedbackLibTypeID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kioforcefeedbacklibtypeid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RX",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RY",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_RZ",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_Y",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_Z"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFDEVICESTATE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON0",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON1",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON10",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON11",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON12",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON13",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON14",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON15",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON16",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON17",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON18",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON19",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON2",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON20",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON21",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON22",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON23",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON24",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON25",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON26",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON27",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON28",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON29",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON3",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON30",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON31",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON4",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON5",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON6",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON7",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON8",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_BUTTON9",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_POV",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_SLIDER",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/IOFORCEFEEDBACKDEVICE_FUNCS_100",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/PFFDEVICESTATE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/kIOForceFeedbackDeviceInterfaceID",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/kIOForceFeedbackLibTypeID"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_RY/title",
          "value": "FFJOFS_RY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_RY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFJOFS_RY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_RZ/title",
          "value": "FFJOFS_RZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_RZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFJOFS_RZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_Y/title",
          "value": "FFJOFS_Y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_Y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFJOFS_Y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_Z/title",
          "value": "FFJOFS_Z"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_Z/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFJOFS_Z"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_RX/title",
          "value": "FFJOFS_RX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_RX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFJOFS_RX"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedback-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
