{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524537-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CONSTANTFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CONSTANTFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_CONSTANTFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_constantforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CUSTOMFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_CUSTOMFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_CUSTOMFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_customforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_DAMPER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_DAMPER"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_DAMPER",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_damper"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_FRICTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_FRICTION"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_FRICTION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_friction"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_INERTIA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_INERTIA"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_INERTIA",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_inertia"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_RAMPFORCE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_RAMPFORCE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_RAMPFORCE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_rampforce"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHDOWN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHDOWN"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SAWTOOTHDOWN",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sawtoothdown"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHUP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SAWTOOTHUP"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SAWTOOTHUP",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sawtoothup"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SINE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SINE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SINE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_sine"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SPRING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SPRING"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SPRING",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_spring"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SQUARE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_SQUARE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_SQUARE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_square"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCAP_ET_TRIANGLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCAP_ET_TRIANGLE"
        }
      ],
      "role": "symbol",
      "title": "FFCAP_ET_TRIANGLE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcap_et_triangle"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedback Enumerations",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524447-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524471-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524506-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524522-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524526-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524546-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524560-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524566-anonymous"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedback-enumerations-1524584-anonymous"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524471-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524584-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524526-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524546-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524506-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524522-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524566-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524447-anonymous",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedback-enumerations-1524560-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CONSTANTFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_CUSTOMFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_DAMPER",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_FRICTION",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_INERTIA",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_RAMPFORCE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHDOWN",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SAWTOOTHUP",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SINE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SPRING",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_SQUARE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCAP_ET_TRIANGLE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CUSTOMFORCE/title",
          "value": "FFCAP_ET_CUSTOMFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CUSTOMFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_CUSTOMFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CONSTANTFORCE/title",
          "value": "FFCAP_ET_CONSTANTFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_CONSTANTFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_CONSTANTFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_RAMPFORCE/title",
          "value": "FFCAP_ET_RAMPFORCE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_RAMPFORCE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_RAMPFORCE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHUP/title",
          "value": "FFCAP_ET_SAWTOOTHUP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHUP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SAWTOOTHUP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SQUARE/title",
          "value": "FFCAP_ET_SQUARE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SQUARE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SQUARE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_DAMPER/title",
          "value": "FFCAP_ET_DAMPER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_DAMPER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_DAMPER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_TRIANGLE/title",
          "value": "FFCAP_ET_TRIANGLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_TRIANGLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_TRIANGLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_FRICTION/title",
          "value": "FFCAP_ET_FRICTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_FRICTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_FRICTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_INERTIA/title",
          "value": "FFCAP_ET_INERTIA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_INERTIA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_INERTIA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SINE/title",
          "value": "FFCAP_ET_SINE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SINE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SINE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SPRING/title",
          "value": "FFCAP_ET_SPRING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SPRING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SPRING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHDOWN/title",
          "value": "FFCAP_ET_SAWTOOTHDOWN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCAP_ET_SAWTOOTHDOWN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCAP_ET_SAWTOOTHDOWN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/forcefeedback-enumerations-1524537-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
