{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/miscellaneous-defines"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Miscellaneous Defines"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/E_PENDING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "E_PENDING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/E_PENDING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "E_PENDING"
        }
      ],
      "role": "symbol",
      "title": "E_PENDING",
      "type": "topic",
      "url": "/documentation/forcefeedback/e_pending"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectSubType"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectSubType"
        }
      ],
      "role": "symbol",
      "title": "FFCapabilitiesEffectSubType",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilitieseffectsubtype"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectType"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCapabilitiesEffectType"
        }
      ],
      "role": "symbol",
      "title": "FFCapabilitiesEffectType",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcapabilitieseffecttype"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCommandFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCommandFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCommandFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcommandflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCooperativeLevelFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCooperativeLevelFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCooperativeLevelFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcooperativelevelflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCoordinateSystemFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCoordinateSystemFlag"
        }
      ],
      "role": "symbol",
      "title": "FFCoordinateSystemFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcoordinatesystemflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_OBJECTOFFSETS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEFF_OBJECTOFFSETS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_OBJECTOFFSETS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEFF_OBJECTOFFSETS"
        }
      ],
      "role": "symbol",
      "title": "FFEFF_OBJECTOFFSETS",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeff_objectoffsets"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEFULL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_DEVICEFULL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEFULL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_DEVICEFULL"
        }
      ],
      "role": "symbol",
      "title": "FFERR_DEVICEFULL",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_devicefull"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICENOTREG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FFERR_DEVICENOTREG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICENOTREG",
      "kind": "symbol",
      "role": "symbol",
      "title": "FFERR_DEVICENOTREG",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_devicenotreg"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEPAUSED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_DEVICEPAUSED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEPAUSED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_DEVICEPAUSED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_DEVICEPAUSED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_devicepaused"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICERELEASED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_DEVICERELEASED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICERELEASED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_DEVICERELEASED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_DEVICERELEASED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_devicereleased"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTPLAYING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_EFFECTPLAYING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTPLAYING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_EFFECTPLAYING"
        }
      ],
      "role": "symbol",
      "title": "FFERR_EFFECTPLAYING",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_effectplaying"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTTYPEMISMATCH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_EFFECTTYPEMISMATCH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTTYPEMISMATCH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_EFFECTTYPEMISMATCH"
        }
      ],
      "role": "symbol",
      "title": "FFERR_EFFECTTYPEMISMATCH",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_effecttypemismatch"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTTYPENOTSUPPORTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_EFFECTTYPENOTSUPPORTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTTYPENOTSUPPORTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_EFFECTTYPENOTSUPPORTED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_EFFECTTYPENOTSUPPORTED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_effecttypenotsupported"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_GENERIC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_GENERIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_GENERIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_GENERIC"
        }
      ],
      "role": "symbol",
      "title": "FFERR_GENERIC",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_generic"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_HASEFFECTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_HASEFFECTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_HASEFFECTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_HASEFFECTS"
        }
      ],
      "role": "symbol",
      "title": "FFERR_HASEFFECTS",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_haseffects"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INCOMPLETEEFFECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_INCOMPLETEEFFECT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INCOMPLETEEFFECT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_INCOMPLETEEFFECT"
        }
      ],
      "role": "symbol",
      "title": "FFERR_INCOMPLETEEFFECT",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_incompleteeffect"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INTERNAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_INTERNAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INTERNAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_INTERNAL"
        }
      ],
      "role": "symbol",
      "title": "FFERR_INTERNAL",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_internal"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INVALIDDOWNLOADID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_INVALIDDOWNLOADID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INVALIDDOWNLOADID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_INVALIDDOWNLOADID"
        }
      ],
      "role": "symbol",
      "title": "FFERR_INVALIDDOWNLOADID",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_invaliddownloadid"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INVALIDPARAM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_INVALIDPARAM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INVALIDPARAM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_INVALIDPARAM"
        }
      ],
      "role": "symbol",
      "title": "FFERR_INVALIDPARAM",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_invalidparam"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_MOREDATA": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_MOREDATA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_MOREDATA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_MOREDATA"
        }
      ],
      "role": "symbol",
      "title": "FFERR_MOREDATA",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_moredata"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOINTERFACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_NOINTERFACE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOINTERFACE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_NOINTERFACE"
        }
      ],
      "role": "symbol",
      "title": "FFERR_NOINTERFACE",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_nointerface"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOTDOWNLOADED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_NOTDOWNLOADED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOTDOWNLOADED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_NOTDOWNLOADED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_NOTDOWNLOADED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_notdownloaded"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOTINITIALIZED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_NOTINITIALIZED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOTINITIALIZED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_NOTINITIALIZED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_NOTINITIALIZED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_notinitialized"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_OUTOFMEMORY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_OUTOFMEMORY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_OUTOFMEMORY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_OUTOFMEMORY"
        }
      ],
      "role": "symbol",
      "title": "FFERR_OUTOFMEMORY",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_outofmemory"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNPLUGGED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_UNPLUGGED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNPLUGGED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_UNPLUGGED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_UNPLUGGED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_unplugged"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_UNSUPPORTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_UNSUPPORTED"
        }
      ],
      "role": "symbol",
      "title": "FFERR_UNSUPPORTED",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_unsupported"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTEDAXIS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFERR_UNSUPPORTEDAXIS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTEDAXIS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFERR_UNSUPPORTEDAXIS"
        }
      ],
      "role": "symbol",
      "title": "FFERR_UNSUPPORTEDAXIS",
      "type": "topic",
      "url": "/documentation/forcefeedback/fferr_unsupportedaxis"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectParameterFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectParameterFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectParameterFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectparameterflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStartFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStartFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStartFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstartflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFEffectStatusFlag"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFEffectStatusFlag"
        }
      ],
      "role": "symbol",
      "title": "FFEffectStatusFlag",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffeffectstatusflag"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFJOFS_X"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_X",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFJOFS_X"
        }
      ],
      "role": "symbol",
      "title": "FFJOFS_X",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_x"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFProperty"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFProperty"
        }
      ],
      "role": "symbol",
      "title": "FFProperty",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffproperty"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFState"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFState"
        }
      ],
      "role": "symbol",
      "title": "FFState",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffstate"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DEGREES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_DEGREES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DEGREES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_DEGREES"
        }
      ],
      "role": "symbol",
      "title": "FF_DEGREES",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_degrees"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DOWNLOADSKIPPED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_DOWNLOADSKIPPED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DOWNLOADSKIPPED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_DOWNLOADSKIPPED"
        }
      ],
      "role": "symbol",
      "title": "FF_DOWNLOADSKIPPED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_downloadskipped"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_EFFECTRESTARTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_EFFECTRESTARTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_EFFECTRESTARTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_EFFECTRESTARTED"
        }
      ],
      "role": "symbol",
      "title": "FF_EFFECTRESTARTED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_effectrestarted"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FALSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_FALSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FALSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_FALSE"
        }
      ],
      "role": "symbol",
      "title": "FF_FALSE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_false"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FFNOMINALMAX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_FFNOMINALMAX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FFNOMINALMAX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_FFNOMINALMAX"
        }
      ],
      "role": "symbol",
      "title": "FF_FFNOMINALMAX",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_ffnominalmax"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_INFINITE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_INFINITE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_INFINITE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_INFINITE"
        }
      ],
      "role": "symbol",
      "title": "FF_INFINITE",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_infinite"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_OK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_OK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_OK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_OK"
        }
      ],
      "role": "symbol",
      "title": "FF_OK",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_ok"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_SECONDS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_SECONDS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_SECONDS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_SECONDS"
        }
      ],
      "role": "symbol",
      "title": "FF_SECONDS",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_seconds"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_TRUNCATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_TRUNCATED"
        }
      ],
      "role": "symbol",
      "title": "FF_TRUNCATED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_truncated"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATEDANDRESTARTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FF_TRUNCATEDANDRESTARTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATEDANDRESTARTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FF_TRUNCATEDANDRESTARTED"
        }
      ],
      "role": "symbol",
      "title": "FF_TRUNCATEDANDRESTARTED",
      "type": "topic",
      "url": "/documentation/forcefeedback/ff_truncatedandrestarted"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/ffjofs_i_i_i": {
      "abstract": [],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/ffjofs_i_i_i",
      "kind": "article",
      "role": "article",
      "title": "FFJOFS_<i>i</i>",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffjofs_i_i_i"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h": {
      "abstract": [
        {
          "text": "Constants used in the public interfaces to the Force Feedback implementation in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/forcefeedbackconstants-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ForceFeedbackConstants.h",
      "type": "topic",
      "url": "/documentation/forcefeedback/forcefeedbackconstants-h"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_ConstantForce_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_ConstantForce_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_ConstantForce_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_ConstantForce_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_constantforce_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_CustomForce_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_CustomForce_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_CustomForce_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_CustomForce_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_customforce_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Damper_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_Damper_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Damper_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_Damper_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_damper_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Friction_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_Friction_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Friction_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_Friction_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_friction_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Inertia_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_Inertia_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Inertia_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_Inertia_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_inertia_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_RampForce_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_RampForce_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_RampForce_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_RampForce_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_rampforce_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_SawtoothDown_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_SawtoothDown_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_SawtoothDown_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_SawtoothDown_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_sawtoothdown_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_SawtoothUp_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_SawtoothUp_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_SawtoothUp_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_SawtoothUp_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_sawtoothup_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Sine_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_Sine_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Sine_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_Sine_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_sine_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Spring_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_Spring_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Spring_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_Spring_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_spring_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Square_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_Square_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Square_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_Square_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_square_id"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Triangle_ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFFEffectType_Triangle_ID"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Triangle_ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFFEffectType_Triangle_ID",
      "type": "topic",
      "url": "/documentation/forcefeedback/kffeffecttype_triangle_id"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/E_PENDING",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DEGREES",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DOWNLOADSKIPPED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_EFFECTRESTARTED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FALSE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FFNOMINALMAX",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_INFINITE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_OK",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_SECONDS",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATEDANDRESTARTED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_OBJECTOFFSETS",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEFULL",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEPAUSED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICERELEASED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTPLAYING",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTTYPEMISMATCH",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTTYPENOTSUPPORTED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_GENERIC",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_HASEFFECTS",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INCOMPLETEEFFECT",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INTERNAL",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INVALIDDOWNLOADID",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INVALIDPARAM",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_MOREDATA",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOINTERFACE",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOTDOWNLOADED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOTINITIALIZED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_OUTOFMEMORY",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNPLUGGED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTED",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTEDAXIS",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/ffjofs_i_i_i",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_X"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/E_PENDING",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DEGREES",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_DOWNLOADSKIPPED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_EFFECTRESTARTED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FALSE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_FFNOMINALMAX",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_INFINITE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_OK",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_SECONDS",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FF_TRUNCATEDANDRESTARTED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEFF_OBJECTOFFSETS",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEFULL",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICENOTREG",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICEPAUSED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_DEVICERELEASED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTPLAYING",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTTYPEMISMATCH",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_EFFECTTYPENOTSUPPORTED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_GENERIC",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_HASEFFECTS",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INCOMPLETEEFFECT",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INTERNAL",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INVALIDDOWNLOADID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_INVALIDPARAM",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_MOREDATA",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOINTERFACE",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOTDOWNLOADED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_NOTINITIALIZED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_OUTOFMEMORY",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNPLUGGED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTED",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFERR_UNSUPPORTEDAXIS",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/ffjofs_i_i_i",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFJOFS_X",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_ConstantForce_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_CustomForce_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Damper_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Friction_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Inertia_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_RampForce_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_SawtoothDown_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_SawtoothUp_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Sine_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Spring_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Square_ID",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/kFFEffectType_Triangle_ID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectSubType",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCapabilitiesEffectType",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCommandFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCooperativeLevelFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCoordinateSystemFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectParameterFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStartFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFEffectStatusFlag",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFProperty",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFState"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_OBJECTOFFSETS/title",
          "value": "FFEFF_OBJECTOFFSETS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEFF_OBJECTOFFSETS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEFF_OBJECTOFFSETS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_EFFECTPLAYING/title",
          "value": "FFERR_EFFECTPLAYING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_EFFECTPLAYING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_EFFECTPLAYING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_GENERIC/title",
          "value": "FFERR_GENERIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_GENERIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_GENERIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_NOINTERFACE/title",
          "value": "FFERR_NOINTERFACE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_NOINTERFACE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_NOINTERFACE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICERELEASED/title",
          "value": "FFERR_DEVICERELEASED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICERELEASED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_DEVICERELEASED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_MOREDATA/title",
          "value": "FFERR_MOREDATA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_MOREDATA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_MOREDATA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_UNSUPPORTED/title",
          "value": "FFERR_UNSUPPORTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_UNSUPPORTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_UNSUPPORTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_NOTDOWNLOADED/title",
          "value": "FFERR_NOTDOWNLOADED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_NOTDOWNLOADED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_NOTDOWNLOADED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/title",
          "value": "FFEffectStatusFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStatusFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStatusFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStatusFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/title",
          "value": "FFCommandFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCommandFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCommandFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCommandFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_TRUNCATEDANDRESTARTED/title",
          "value": "FF_TRUNCATEDANDRESTARTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_TRUNCATEDANDRESTARTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_TRUNCATEDANDRESTARTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1E_PENDING/title",
          "value": "E_PENDING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1E_PENDING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "E_PENDING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/title",
          "value": "FFProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_EFFECTTYPENOTSUPPORTED/title",
          "value": "FFERR_EFFECTTYPENOTSUPPORTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_EFFECTTYPENOTSUPPORTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_EFFECTTYPENOTSUPPORTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_UNSUPPORTEDAXIS/title",
          "value": "FFERR_UNSUPPORTEDAXIS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_UNSUPPORTEDAXIS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_UNSUPPORTEDAXIS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICEFULL/title",
          "value": "FFERR_DEVICEFULL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICEFULL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_DEVICEFULL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_DOWNLOADSKIPPED/title",
          "value": "FF_DOWNLOADSKIPPED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_DOWNLOADSKIPPED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_DOWNLOADSKIPPED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/title",
          "value": "FFEffectStartFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStartFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectStartFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectStartFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_INCOMPLETEEFFECT/title",
          "value": "FFERR_INCOMPLETEEFFECT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_INCOMPLETEEFFECT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_INCOMPLETEEFFECT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_INTERNAL/title",
          "value": "FFERR_INTERNAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_INTERNAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_INTERNAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_NOTINITIALIZED/title",
          "value": "FFERR_NOTINITIALIZED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_NOTINITIALIZED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_NOTINITIALIZED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_FALSE/title",
          "value": "FF_FALSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_FALSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_FALSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_INVALIDPARAM/title",
          "value": "FFERR_INVALIDPARAM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_INVALIDPARAM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_INVALIDPARAM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_X/title",
          "value": "FFJOFS_X"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFJOFS_X/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFJOFS_X"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/title",
          "value": "FFCooperativeLevelFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCooperativeLevelFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCooperativeLevelFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCooperativeLevelFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_OUTOFMEMORY/title",
          "value": "FFERR_OUTOFMEMORY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_OUTOFMEMORY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_OUTOFMEMORY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_OK/title",
          "value": "FF_OK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_OK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_OK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_EFFECTTYPEMISMATCH/title",
          "value": "FFERR_EFFECTTYPEMISMATCH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_EFFECTTYPEMISMATCH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_EFFECTTYPEMISMATCH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICEPAUSED/title",
          "value": "FFERR_DEVICEPAUSED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_DEVICEPAUSED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_DEVICEPAUSED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_INVALIDDOWNLOADID/title",
          "value": "FFERR_INVALIDDOWNLOADID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_INVALIDDOWNLOADID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_INVALIDDOWNLOADID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/title",
          "value": "FFCapabilitiesEffectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/title",
          "value": "FFCapabilitiesEffectSubType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCapabilitiesEffectSubType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCapabilitiesEffectSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_FFNOMINALMAX/title",
          "value": "FF_FFNOMINALMAX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_FFNOMINALMAX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_FFNOMINALMAX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_TRUNCATED/title",
          "value": "FF_TRUNCATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_TRUNCATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_TRUNCATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_SECONDS/title",
          "value": "FF_SECONDS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_SECONDS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_SECONDS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_UNPLUGGED/title",
          "value": "FFERR_UNPLUGGED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_UNPLUGGED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_UNPLUGGED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/title",
          "value": "FFCoordinateSystemFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCoordinateSystemFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCoordinateSystemFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCoordinateSystemFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_INFINITE/title",
          "value": "FF_INFINITE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_INFINITE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_INFINITE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_HASEFFECTS/title",
          "value": "FFERR_HASEFFECTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFERR_HASEFFECTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFERR_HASEFFECTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/title",
          "value": "FFEffectParameterFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectParameterFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFEffectParameterFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFEffectParameterFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/title",
          "value": "FFState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_DEGREES/title",
          "value": "FF_DEGREES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_DEGREES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_DEGREES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_EFFECTRESTARTED/title",
          "value": "FF_EFFECTRESTARTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FF_EFFECTRESTARTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FF_EFFECTRESTARTED"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/miscellaneous-defines"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/miscellaneous-defines"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
