{
  "abstract": [
    {
      "text": "Network EAP type is ",
      "type": "text"
    },
    {
      "code": "EAPTLS",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPTLS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEHotspotConfigurationEAPType@NEHotspotConfigurationEAPTypeEAPTLS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EAPTLS"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEHotspotConfigurationEAPTypeEAPTLS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEHotspotEAPSettings.EAPType.EAPTLS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EAPTLS"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings": {
      "abstract": [
        {
          "text": "Extensible Authentication Protocol settings for configuring WPA and WPA2 enterprise Wi-Fi networks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotEAPSettings"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotEAPSettings"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType": {
      "abstract": [
        {
          "text": "The EAP types that may be specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/supportedEAPTypes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAPType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAPType"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.EAPType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/eaptype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPFAST": {
      "abstract": [
        {
          "text": "Network EAP type is ",
          "type": "text"
        },
        {
          "code": "EAPFAST",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAPFAST"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPFAST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTypeEAPFAST"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.EAPType.EAPFAST",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/eaptype/eapfast"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPPEAP": {
      "abstract": [
        {
          "text": "Network EAP type is ",
          "type": "text"
        },
        {
          "code": "EAPPEAP",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAPPEAP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPPEAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTypeEAPPEAP"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.EAPType.EAPPEAP",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/eaptype/eappeap"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPTLS": {
      "abstract": [
        {
          "text": "Network EAP type is ",
          "type": "text"
        },
        {
          "code": "EAPTLS",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAPTLS"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPTLS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTypeEAPTLS"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.EAPType.EAPTLS",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/eaptype/eaptls"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPTTLS": {
      "abstract": [
        {
          "text": "Network EAP type is ",
          "type": "text"
        },
        {
          "code": "EAPTTLS",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAPTTLS"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPTTLS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationEAPTypeEAPTTLS"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.EAPType.EAPTTLS",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/eaptype/eapttls"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/supportedEAPTypes": {
      "abstract": [
        {
          "text": "An array of supported EAP types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedEAPTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/supportedEAPTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedEAPTypes"
        }
      ],
      "role": "symbol",
      "title": "supportedEAPTypes",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/supportedeaptypes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPTTLS",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPPEAP",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPFAST"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEHotspotConfigurationEAPTypeEAPTLS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTypeEAPTLS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPTTLS",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPPEAP",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType/EAPFAST"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEHotspotConfigurationEAPTypeEAPTLS"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType~1EAPFAST/title",
          "value": "NEHotspotConfigurationEAPTypeEAPFAST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType~1EAPFAST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTypeEAPFAST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType~1EAPTLS/title",
          "value": "NEHotspotConfigurationEAPTypeEAPTLS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType~1EAPTLS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTypeEAPTLS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType~1EAPTTLS/title",
          "value": "NEHotspotConfigurationEAPTypeEAPTTLS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType~1EAPTTLS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTypeEAPTTLS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/title",
          "value": "NEHotspotEAPSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotEAPSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotEAPSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType/title",
          "value": "NEHotspotConfigurationEAPType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType~1EAPPEAP/title",
          "value": "NEHotspotConfigurationEAPTypeEAPPEAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType~1EAPPEAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTypeEAPPEAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1supportedEAPTypes/title",
          "value": "supportedEAPTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1supportedEAPTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedEAPTypes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspoteapsettings/eaptype/eaptls"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspoteapsettings/eaptype/eaptls"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
