{
  "abstract": [
    {
      "text": "The different types of thumbnails that you can create.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "QuickLookThumbnailing",
    "externalID": "c:@E@QLThumbnailRepresentationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RepresentationType"
      }
    ],
    "modules": [
      {
        "name": "Quick Look Thumbnailing"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RepresentationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "QLThumbnailRepresentation.RepresentationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RepresentationType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/providing-thumbnails-of-your-custom-file-types"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing": {
      "abstract": [
        {
          "text": "Generate thumbnails for common file types and add a Thumbnail Extension to your app to enable others to create thumbnails of your custom files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look Thumbnailing",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation": {
      "abstract": [
        {
          "text": "Information about the thumbnail that the thumbnail generator returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailRepresentation"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailRepresentation"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailRepresentation",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType": {
      "abstract": [
        {
          "text": "The different types of thumbnails that you can create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RepresentationType"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RepresentationType"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailRepresentation.RepresentationType",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/representationtype"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/icon": {
      "abstract": [
        {
          "text": "A file icon representation of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icon"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/icon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailRepresentationTypeIcon"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailRepresentation.RepresentationType.icon",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/representationtype/icon"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/representationtype/init(rawvalue:)"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/lowQualityThumbnail": {
      "abstract": [
        {
          "text": "A cached thumbnail representation of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowQualityThumbnail"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/lowQualityThumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailRepresentationTypeLowQualityThumbnail"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailRepresentation.RepresentationType.lowQualityThumbnail",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/representationtype/lowqualitythumbnail"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/thumbnail": {
      "abstract": [
        {
          "text": "A thumbnail representation of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbnail"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/thumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailRepresentationTypeThumbnail"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailRepresentation.RepresentationType.thumbnail",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/representationtype/thumbnail"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/cgImage": {
      "abstract": [
        {
          "text": "A thumbnail in the form of a Core Graphics image object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cgImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/cgImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImage"
        }
      ],
      "role": "symbol",
      "title": "cgImage",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/cgimage"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/contentRect": {
      "abstract": [
        {
          "text": "The rectangle within the thumbnail image of the document that represents its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/contentRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentRect"
        }
      ],
      "role": "symbol",
      "title": "contentRect",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/contentrect"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/nsImage": {
      "abstract": [
        {
          "text": "A thumbnail in the form of an AppKit image object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nsImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/nsImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "nsImage",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/nsimage"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/type": {
      "abstract": [
        {
          "text": "The type of thumbnail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailRepresentation",
          "text": "QLThumbnailRepresentation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLThumbnailRepresentationType",
          "text": "RepresentationType"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/type"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/uiImage": {
      "abstract": [
        {
          "text": "A thumbnail in the form of a UIKit image object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uiImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/uiImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "uiImage",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/uiimage"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/providing-thumbnails-of-your-custom-file-types": {
      "abstract": [
        {
          "text": "Implement a Thumbnail Extension to allow the operating system and other apps to display thumbnails of your custom files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/providing-thumbnails-of-your-custom-file-types",
      "kind": "article",
      "role": "article",
      "title": "Providing Thumbnails of Your Custom File Types",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/providing-thumbnails-of-your-custom-file-types"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Thumbnail-Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/cgImage",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/nsImage",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/uiImage",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/type",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/contentRect"
      ],
      "title": "Thumbnail Images"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/icon",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/lowQualityThumbnail",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/thumbnail"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLThumbnailRepresentationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/icon",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/lowQualityThumbnail",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/RepresentationType/thumbnail"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Thumbnail-Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/cgImage",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/nsImage",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/uiImage",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/type",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailRepresentation/contentRect"
              ],
              "title": "Thumbnail Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLThumbnailRepresentationType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1uiImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1uiImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1cgImage/title",
          "value": "CGImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1cgImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1contentRect/title",
          "value": "contentRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1contentRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType~1lowQualityThumbnail/title",
          "value": "QLThumbnailRepresentationTypeLowQualityThumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType~1lowQualityThumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentationTypeLowQualityThumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1nsImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1nsImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType~1icon/title",
          "value": "QLThumbnailRepresentationTypeIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType~1icon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentationTypeIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation/title",
          "value": "QLThumbnailRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType/title",
          "value": "QLThumbnailRepresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType~1thumbnail/title",
          "value": "QLThumbnailRepresentationTypeThumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailRepresentation~1RepresentationType~1thumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRepresentationTypeThumbnail"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/representationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookthumbnailing/qlthumbnailrepresentation/representationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
