{
  "abstract": [
    {
      "text": "The layer’s OpenGL context.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use CAMetalLayer instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer/openGLContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSOpenGLLayer(py)openGLContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "openGLContext"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
        "text": "NSOpenGLContext"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "openGLContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.6",
        "message": "Please use CAMetalLayer instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "openGLContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "openGLContext"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
              "text": "NSOpenGLContext"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Provides access to the layer’s associated ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".  Subclasses shouldn’t invoke ",
              "type": "text"
            },
            {
              "code": "setOpenGLContext:",
              "type": "codeVoice"
            },
            {
              "text": ", but can override it if desired to intercept assignment of the layer’s context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext": {
      "abstract": [
        {
          "text": "An object that represents an OpenGL graphics context, into which all OpenGL calls are rendered.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLContext"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLContext",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer": {
      "abstract": [
        {
          "text": "A subclass of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that is suitable for rendering OpenGL into layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLLayer"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsopengllayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer/openGLContext": {
      "abstract": [
        {
          "text": "The layer’s OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openGLContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
          "text": "NSOpenGLContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer/openGLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openGLContext"
        }
      ],
      "role": "symbol",
      "title": "openGLContext",
      "type": "topic",
      "url": "/documentation/appkit/nsopengllayer/openglcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer/openGLContext(for:)": {
      "abstract": [
        {
          "text": "Returns the OpenGL context to use for the requested pixel format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openGLContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLPixelFormat",
          "text": "NSOpenGLPixelFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
          "text": "NSOpenGLContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer/openGLContext(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openGLContextForPixelFormat:"
        }
      ],
      "role": "symbol",
      "title": "openGLContext(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopengllayer/openglcontext(for:)"
    },
    "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer": {
      "abstract": [
        {
          "text": "A layer that provides a layer suitable for rendering OpenGL content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAOpenGLLayer",
      "type": "topic",
      "url": "/documentation/QuartzCore/CAOpenGLLayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Rendering-Context",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer/openGLContext(for:)"
      ],
      "title": "Managing the Rendering Context"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "openGLContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "openGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Rendering-Context",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer/openGLContext(for:)"
              ],
              "title": "Managing the Rendering Context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
                    "text": "NSOpenGLContext"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "openGLContext"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use CAMetalLayer instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer~1openGLContext(for:)/title",
          "value": "openGLContextForPixelFormat:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer~1openGLContext(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openGLContextForPixelFormat:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer~1openGLContext/title",
          "value": "openGLContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer~1openGLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "openGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/title",
          "value": "NSOpenGLContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1QuartzCore~1CAOpenGLLayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAOpenGLLayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CALayer",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/title",
          "value": "NSOpenGLLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsopengllayer/openglcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsopengllayer/openglcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
