{
  "abstract": [
    {
      "text": "The property value’s status is unknown.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty/Status/notYetLoaded",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVKeyValueStatus@AVKeyValueStatusUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVKeyValueStatusUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "4.0",
        "message": "Use AVAsyncProperty.Status instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "4.0",
        "message": "Use AVAsyncProperty.Status instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "13.1",
        "message": "Use AVAsyncProperty.Status instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.7",
        "message": "Use AVAsyncProperty.Status instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "9.0",
        "message": "Use AVAsyncProperty.Status instead",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use AVAsyncProperty.Status instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "1.0",
        "message": "Use AVAsyncProperty.Status instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVKeyValueStatus.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty/Status/notYetLoaded": {
      "abstract": [
        {
          "text": "The system hasn’t loaded a property value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notYetLoaded"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty/Status/notYetLoaded",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAsyncProperty.Status.notYetLoaded",
      "type": "topic",
      "url": "/documentation/avfoundation/avasyncproperty/status/notyetloaded"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus": {
      "abstract": [
        {
          "text": "Values that indicate the loaded status of a property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKeyValueStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKeyValueStatus"
        }
      ],
      "role": "symbol",
      "title": "AVKeyValueStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avkeyvaluestatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/cancelled": {
      "abstract": [
        {
          "text": "You canceled loading a property value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKeyValueStatusCancelled"
        }
      ],
      "role": "symbol",
      "title": "AVKeyValueStatus.cancelled",
      "type": "topic",
      "url": "/documentation/avfoundation/avkeyvaluestatus/cancelled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/failed": {
      "abstract": [
        {
          "text": "The system is unable to load the propery value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKeyValueStatusFailed"
        }
      ],
      "role": "symbol",
      "title": "AVKeyValueStatus.failed",
      "type": "topic",
      "url": "/documentation/avfoundation/avkeyvaluestatus/failed"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/loaded": {
      "abstract": [
        {
          "text": "The property value is ready to use.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loaded"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/loaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKeyValueStatusLoaded"
        }
      ],
      "role": "symbol",
      "title": "AVKeyValueStatus.loaded",
      "type": "topic",
      "url": "/documentation/avfoundation/avkeyvaluestatus/loaded"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/loading": {
      "abstract": [
        {
          "text": "The system is loading the property value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loading"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/loading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKeyValueStatusLoading"
        }
      ],
      "role": "symbol",
      "title": "AVKeyValueStatus.loading",
      "type": "topic",
      "url": "/documentation/avfoundation/avkeyvaluestatus/loading"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/unknown": {
      "abstract": [
        {
          "text": "The property value’s status is unknown.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKeyValueStatusUnknown"
        }
      ],
      "role": "symbol",
      "title": "AVKeyValueStatus.unknown",
      "type": "topic",
      "url": "/documentation/avfoundation/avkeyvaluestatus/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Status-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/loading",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/loaded",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/failed",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/cancelled"
      ],
      "title": "Status Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVKeyValueStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKeyValueStatusUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Status-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/loading",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/loaded",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/failed",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVKeyValueStatus/cancelled"
              ],
              "title": "Status Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVKeyValueStatusUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1loaded/title",
          "value": "AVKeyValueStatusLoaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1loaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKeyValueStatusLoaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus/title",
          "value": "AVKeyValueStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKeyValueStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKeyValueStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1cancelled/title",
          "value": "AVKeyValueStatusCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKeyValueStatusCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1failed/title",
          "value": "AVKeyValueStatusFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKeyValueStatusFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1loading/title",
          "value": "AVKeyValueStatusLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1loading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKeyValueStatusLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1unknown/title",
          "value": "AVKeyValueStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVKeyValueStatus~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKeyValueStatusUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avkeyvaluestatus/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avkeyvaluestatus/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
