{"variants":[{"paths":["/documentation/metal/mtlbinding/isused"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metal/mtlbinding/isused"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isUsed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.metal/documentation/Metal/MTLBinding/isUsed"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isUsed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"property","required":true,"roleHeading":"Instance Property","navigatorTitle":[{"text":"used","kind":"identifier"}],"modules":[{"name":"Metal"}],"externalID":"c:objc(pl)MTLBinding(py)used","role":"symbol","title":"isUsed","platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"16.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"16.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"16.0"},{"name":"macOS","deprecated":false,"introducedAt":"13.0","beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"introducedAt":"16.0","beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLBinding"]]},"references":{"doc://com.apple.metal/documentation/Metal/MTLBinding":{"navigatorTitle":[{"text":"MTLBinding","kind":"identifier"}],"url":"/documentation/metal/mtlbinding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MTLBinding"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLBinding","kind":"symbol","abstract":[],"title":"MTLBinding"},"doc://com.externally.resolved.symbol/s:Sb":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"identifier":"doc://com.externally.resolved.symbol/s:Sb","url":"/documentation/Swift/Bool","title":"Bool"},"doc://com.apple.metal/documentation/Metal":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal","title":"Metal","abstract":[{"text":"Render advanced 3D graphics and compute data in parallel with graphics processors.","type":"text"}],"url":"/documentation/metal"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.metal/documentation/Metal/MTLBinding/isUsed":{"role":"symbol","kind":"symbol","required":true,"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"used"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLBinding/isUsed","title":"isUsed","url":"/documentation/metal/mtlbinding/isused","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isUsed","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"16.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"16.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"16.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"name":"macOS","deprecated":false,"introducedAt":"13.0","beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"introducedAt":"16.0","beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"used","path":"/metadata/title","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"used","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLBinding"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"kind":"identifier","text":"isUsed"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"used"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"MTLBinding","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/title"},{"value":[{"kind":"identifier","text":"MTLBinding"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/fragments"},{"value":[{"text":"MTLBinding","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/navigatorTitle"},{"value":"used","op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding~1isUsed/title"},{"value":[{"kind":"identifier","text":"used"}],"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding~1isUsed/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}