{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(pl)MTLBinding(py)name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":[{"introducedAt":"16.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"introducedAt":"16.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"16.0","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"introducedAt":"13.0","unavailable":false,"name":"macOS","beta":false,"deprecated":false},{"introducedAt":"16.0","unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false,"deprecated":false}],"symbolKind":"property","title":"name","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"name"}],"required":true,"modules":[{"name":"Metal"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLBinding"]]},"identifier":{"url":"doc://com.apple.metal/documentation/Metal/MTLBinding/name","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/metal/mtlbinding/name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metal/mtlbinding/name"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.apple.metal/documentation/Metal/MTLBinding":{"navigatorTitle":[{"text":"MTLBinding","kind":"identifier"}],"url":"/documentation/metal/mtlbinding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MTLBinding"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLBinding","kind":"symbol","abstract":[],"title":"MTLBinding"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.metal/documentation/Metal":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal","title":"Metal","abstract":[{"text":"Render advanced 3D graphics and compute data in parallel with graphics processors.","type":"text"}],"url":"/documentation/metal"},"doc://com.externally.resolved.symbol/s:SS":{"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"kind":"symbol","url":"/documentation/Swift/String","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"role":"symbol","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"kind":"symbol","title":"NSString","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","url":"/documentation/foundation/nsstring"},"doc://com.apple.metal/documentation/Metal/MTLBinding/name":{"identifier":"doc://com.apple.metal/documentation/Metal/MTLBinding/name","url":"/documentation/metal/mtlbinding/name","type":"topic","kind":"symbol","title":"name","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"name"}],"required":true,"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","deprecated":false,"introducedAt":"16.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"16.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"16.0","unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"16.0","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"name"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLBinding"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"name"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/title","value":"MTLBinding"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/fragments","value":[{"kind":"identifier","text":"MTLBinding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/navigatorTitle","value":[{"text":"MTLBinding","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding~1name/title","value":"name"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding~1name/fragments","value":[{"kind":"identifier","text":"name"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}