{
  "abstract": [
    {
      "text": "Writes the display order of the media sources to the accessory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/writeOrder(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7HomeKit32HMMediaSourceDisplayOrderProfileC05writeF0yySaySiGYaKF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "writeOrder"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": "]) "
      },
      {
        "kind": "keyword",
        "text": "async"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "writeOrder(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "writeOrder"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "order"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": "]) "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The new display order for the media sources. Provides an ordered list of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentifier",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " values for ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeInputSource",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " services associated with the profile.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "order"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An error is thrown if the source ordering fails to be written to the accessory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentifier": {
      "abstract": [
        {
          "text": "The identifier for an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeIdentifier",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeidentifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile": {
      "abstract": [
        {
          "text": "An interface from which to read and, if allowed by the accessory, update the ordering of input sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMMediaSourceDisplayOrderProfile"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMMediaSourceDisplayOrderProfile"
        }
      ],
      "role": "symbol",
      "title": "HMMediaSourceDisplayOrderProfile",
      "type": "topic",
      "url": "/documentation/homekit/hmmediasourcedisplayorderprofile"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/Delegate-swift.protocol": {
      "abstract": [
        {
          "text": "The protocol through which a delegate receives updates on the order of input media sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Delegate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/Delegate-swift.protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Delegate"
        }
      ],
      "role": "symbol",
      "title": "HMMediaSourceDisplayOrderProfile.Delegate",
      "type": "topic",
      "url": "/documentation/homekit/hmmediasourcedisplayorderprofile/delegate-swift.protocol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/canModifyOrder": {
      "abstract": [
        {
          "text": "A Boolean that indicates if the display order of the input media sources can be modified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canModifyOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/canModifyOrder",
      "kind": "symbol",
      "role": "symbol",
      "title": "canModifyOrder",
      "type": "topic",
      "url": "/documentation/homekit/hmmediasourcedisplayorderprofile/canmodifyorder"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/delegate-swift.property": {
      "abstract": [
        {
          "text": "The property that handles updates to the display order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@HomeKit@objc(cs)HMMediaSourceDisplayOrderProfile",
          "text": "HMMediaSourceDisplayOrderProfile"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7HomeKit32HMMediaSourceDisplayOrderProfileC8DelegateP",
          "text": "Delegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/delegate-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/homekit/hmmediasourcedisplayorderprofile/delegate-swift.property"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/order": {
      "abstract": [
        {
          "text": "The display order of input media sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "order"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/order",
      "kind": "symbol",
      "role": "symbol",
      "title": "order",
      "type": "topic",
      "url": "/documentation/homekit/hmmediasourcedisplayorderprofile/order"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/writeOrder(_:)": {
      "abstract": [
        {
          "text": "Writes the display order of the media sources to the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeOrder"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/writeOrder(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "writeOrder(_:)",
      "type": "topic",
      "url": "/documentation/homekit/hmmediasourcedisplayorderprofile/writeorder(_:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeInputSource": {
      "abstract": [
        {
          "text": "An accessory input source service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMServiceTypeInputSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeInputSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMServiceTypeInputSource"
        }
      ],
      "role": "symbol",
      "title": "HMServiceTypeInputSource",
      "type": "topic",
      "url": "/documentation/homekit/hmservicetypeinputsource"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-input-source-order",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/delegate-swift.property",
        "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/order",
        "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/canModifyOrder",
        "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile/Delegate-swift.protocol"
      ],
      "title": "Managing input source order"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMServiceTypeInputSource/title",
          "value": "HMServiceTypeInputSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMServiceTypeInputSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMServiceTypeInputSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeIdentifier/title",
          "value": "HMCharacteristicTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmmediasourcedisplayorderprofile/writeorder(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
