{
  "abstract": [
    {
      "text": "Incorporate the system text cursor into your custom text UI in AppKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/text-display"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Adopting the system text cursor in custom text views"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "People can enter text into your app in a variety of ways, such as typing, copy and paste, or dictation. macOS 14 introduces enhancements to the system UI for the text cursor to provide a more seamless text experience.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app handles text input through standard AppKit views such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", your app automatically uses the system UI for the text cursor. This system UI includes the following elements:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The text cursor that indicates the insertion point of the text",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Text cursor accessories that indicate state, such as current input source language, dictation, and Caps Lock",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Animation effects that surround the text cursor during dictation",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you have a highly customized UI for displaying text, you can adopt this system UI in your AppKit app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-the-system-text-cursor-to-a-custom-text-view",
          "level": 3,
          "text": "Add the system text cursor to a custom text view",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your app handles text input through a custom view that builds on ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can display the system text cursor manually. Create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " view and add it on top of the view that displays text in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Set up the text cursor.",
            "let textCursor = NSTextInsertionIndicator(frame: .zero)",
            "documentView.addSubview(textCursor)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When your custom text view becomes active or becomes first responder, update the display mode of the text cursor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Show the text cursor when the text view becomes active.",
            "func didBecomeActive() {",
            "    textCursor.displayMode = .automatic",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Configure-the-text-cursor-animations",
          "level": 3,
          "text": "Configure the text cursor animations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Depending on the behavior you need at a particular point in time, you can determine how the text cursor handles animations by selecting one of these display modes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Automatic. Set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/automatic",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " display mode to stop and start animations for the text cursor automatically. These animations include a blinking effect that applies to the text cursor during typing and dictation, animated transitions between dictation states, and automatic hiding of the text cursor during tracking loops. This display mode is appropriate in the majority of cases when your custom text view is accepting text input.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Always visible. Set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/visible",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " display mode to always show the text cursor and disable animations. This display mode is appropriate when the text cursor needs to appear without blinking — for example, to indicate a drop destination as part of a drag and drop interaction.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you use the automatic display mode, you can further customize the animation options depending on the needs of your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "By default, the text cursor hides automatically during tracking loops. Include the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct/showWhileTracking",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " option in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/automaticModeOptions-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to show the text cursor during tracking instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "By default, the text cursor shows an animated effect during dictation. To completely hide the view that draws the animated effect, remove ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct/showEffectsView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " from ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/automaticModeOptions-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". To customize the placement of this view in your view hierarchy, specify ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/effectsViewInserter",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how to customize the placement of the animated effects view to place it directly below the text cursor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Specify custom view hierarchy placement for the animated effects view.",
            "textCursor.effectsViewInserter = { view in",
            "    documentView.addSubview(view, positioned: .below, relativeTo: textCursor)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Update-the-text-cursor-position",
          "level": 3,
          "text": "Update the text cursor position",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your custom text view is responsible for updating the position of the text cursor when a person inputs text, but the system provides the appropriate animated effect. For example, the following image shows the system animation effect that applies to the text cursor during dictation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4213258",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As a person types or inserts text during dictation, update the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/frame",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " view. The view automatically changes its appearance in response to that movement, matching the system UI for the corresponding type of input (typing or dictation).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-placements-of-text-cursor-accessories",
          "level": 3,
          "text": "Configure the placements of text cursor accessories",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system text cursor displays accessories that indicate state, such as current input source language, dictation, and Caps Lock. For example, the following image shows the text cursor with the dictation indicator and the current input language set to English.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4277103",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a person changes the input language, the accessory expands to show the language selection UI in the language switcher accessory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4277104",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " draws these accessories automatically, but you can specify where in relation to the text cursor to draw them. In your custom text view, you can override the placement of these accessories by specifying ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/preferredTextAccessoryPlacement()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your implementation of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When the system renders the text cursor in your custom view, it uses the return value of this method to determine where to draw the accessories.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Indicate-the-offscreen-text-cursor-position-during-dictation",
          "level": 3,
          "text": "Indicate the offscreen text cursor position during dictation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system text cursor shows a dictation indicator accessory during an active dictation session. When a person scrolls the text cursor offscreen during dictation, the system also draws a scroll-away indicator to indicate the position of the cursor. For example, the following image shows a scroll-away indicator that points downwards, indicating that the text cursor is out of view below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4277102",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For the system to show the scroll-away indicator on a custom text view, you need to complete the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Adopt ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and implement ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/unionRectInVisibleSelectedRange",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/documentVisibleRect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". These properties provide the system with the coordinate information it needs to draw the scroll-away indicator in the appropriate position.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Notify the system when a person starts or stops scrolling, so the system can display the indicator at the appropriate time. Call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientWillStartScrollingOrZooming()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " when scrolling starts, and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidEndScrollingOrZooming()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " when scrolling ends.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Hide-the-system-text-cursor",
          "level": 3,
          "text": "Hide the system text cursor",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your custom text view resigns first responder status, update the display mode of the text cursor to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/hidden",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Hide the text cursor when the text view becomes inactive.",
            "func didBecomeInactive() {",
            "    textCursor.displayMode = .hidden",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you implement custom text UI in a UIKit app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Session 10058: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc2023/10058/",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Related sessions from WWDC23",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives": {
      "abstract": [
        {
          "text": "A list of alternative strings for a piece of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlternatives"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlternatives"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlternatives",
      "type": "topic",
      "url": "/documentation/appkit/nstextalternatives"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContent": {
      "abstract": [
        {
          "text": "A protocol that describes specific kinds of input content types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContent"
        }
      ],
      "role": "symbol",
      "title": "NSTextContent",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextField": {
      "abstract": [
        {
          "text": "Text the user can select or edit to send an action message to a target when the user presses the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "role": "symbol",
      "title": "NSTextField",
      "type": "topic",
      "url": "/documentation/appkit/nstextfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient": {
      "abstract": [
        {
          "text": "A set of methods that text views need to implement to interact properly with the text input management system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputClient"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputClient"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputClient",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputclient"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/documentVisibleRect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentVisibleRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/documentVisibleRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentVisibleRect"
        }
      ],
      "role": "symbol",
      "title": "documentVisibleRect",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputclient/documentvisiblerect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/preferredTextAccessoryPlacement()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTextAccessoryPlacement"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextCursorAccessoryPlacement",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/preferredTextAccessoryPlacement()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredTextAccessoryPlacement"
        }
      ],
      "role": "symbol",
      "title": "preferredTextAccessoryPlacement()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputclient/preferredtextaccessoryplacement()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/unionRectInVisibleSelectedRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unionRectInVisibleSelectedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient/unionRectInVisibleSelectedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unionRectInVisibleSelectedRange"
        }
      ],
      "role": "symbol",
      "title": "unionRectInVisibleSelectedRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputclient/unionrectinvisibleselectedrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext": {
      "abstract": [
        {
          "text": "An object that represents the Cocoa text input system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputContext"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputContext",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidEndScrollingOrZooming()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputClientDidEndScrollingOrZooming"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidEndScrollingOrZooming()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInputClientDidEndScrollingOrZooming"
        }
      ],
      "role": "symbol",
      "title": "textInputClientDidEndScrollingOrZooming()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/textinputclientdidendscrollingorzooming()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientWillStartScrollingOrZooming()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputClientWillStartScrollingOrZooming"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientWillStartScrollingOrZooming()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInputClientWillStartScrollingOrZooming"
        }
      ],
      "role": "symbol",
      "title": "textInputClientWillStartScrollingOrZooming()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/textinputclientwillstartscrollingorzooming()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator": {
      "abstract": [
        {
          "text": "A view that represents the insertion indicator in text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicator"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct": {
      "abstract": [
        {
          "text": "Options that affect the automatic display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutomaticModeOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutomaticModeOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.AutomaticModeOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/automaticmodeoptions-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct/showEffectsView": {
      "abstract": [
        {
          "text": "Specifies whether a trailing glow displays during dictation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showEffectsView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextInsertionIndicator",
          "text": "NSTextInsertionIndicator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInsertionIndicatorAutomaticModeOptions",
          "text": "AutomaticModeOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct/showEffectsView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicatorAutomaticModeOptionsShowEffectsView"
        }
      ],
      "role": "symbol",
      "title": "showEffectsView",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/automaticmodeoptions-swift.struct/showeffectsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct/showWhileTracking": {
      "abstract": [
        {
          "text": "Specifies whether the insertion indicator shows during a tracking loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showWhileTracking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextInsertionIndicator",
          "text": "NSTextInsertionIndicator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInsertionIndicatorAutomaticModeOptions",
          "text": "AutomaticModeOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct/showWhileTracking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicatorAutomaticModeOptionsShowWhileTracking"
        }
      ],
      "role": "symbol",
      "title": "showWhileTracking",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/automaticmodeoptions-swift.struct/showwhiletracking"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that determine how to display the system text cursor in a custom text UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/automatic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicatorDisplayModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode.automatic",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum/automatic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/hidden": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/hidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicatorDisplayModeHidden"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode.hidden",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum/hidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/visible": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum/visible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicatorDisplayModeVisible"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode.visible",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum/visible"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/automaticModeOptions-swift.property": {
      "abstract": [
        {
          "text": "Options that affect the automatic display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticModeOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextInsertionIndicator",
          "text": "NSTextInsertionIndicator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextInsertionIndicatorAutomaticModeOptions",
          "text": "AutomaticModeOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/automaticModeOptions-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticModeOptions"
        }
      ],
      "role": "symbol",
      "title": "automaticModeOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/automaticmodeoptions-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/effectsViewInserter": {
      "abstract": [
        {
          "text": "An optional closure the system calls during dictation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectsViewInserter"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/effectsViewInserter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectsViewInserter"
        }
      ],
      "role": "symbol",
      "title": "effectsViewInserter",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/effectsviewinserter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/frame": {
      "abstract": [
        {
          "text": "The view’s frame rectangle, which defines its position and size in its superview’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/appkit/nsview/frame"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-display": {
      "abstract": [
        {
          "text": "Display text and check spelling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Display",
      "type": "topic",
      "url": "/documentation/appkit/text-display"
    },
    "doc://com.apple.documentation/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views": {
      "abstract": [
        {
          "text": "Incorporate the system text-selection experience into your custom text UI in UIKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views",
      "kind": "article",
      "role": "article",
      "title": "Adopting system selection UI in custom text views",
      "type": "topic",
      "url": "/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/videos/play/wwdc2023/10058/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2023/10058/",
      "title": "What’s new with text and text interactions",
      "titleInlineContent": [
        {
          "text": "What’s new with text and text interactions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10058/"
    },
    "media-4213258": {
      "alt": "Screenshot of text that says “The quick brown fox jumps over the” with the text cursor at the end of the text. The text cursor shows a blue glowing effect that trails through the text behind it, gradually dimming in opacity as it reaches the word “over.”",
      "identifier": "media-4213258",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9e3cf9b424c226b3116f31f758c76a8d/media-4213258@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1d61d22ed9045619eda4cc838bd3ad30/media-4213258~dark@2x.png"
        }
      ]
    },
    "media-4277102": {
      "alt": "Screenshot of text in a text input field with an active dictation session. A scroll-away indicator points downwards, indicating that the text cursor is out of view below.",
      "identifier": "media-4277102",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a115c25ef1f35d3210de878287a3418b/media-4277102@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f89bdd98e9a3a73958c3c54ea128a76f/media-4277102~dark@2x.png"
        }
      ]
    },
    "media-4277103": {
      "alt": "Screenshot of text that says “The quick brown fox jumps over the” with the text cursor at the end of the text. The text cursor shows a dictation indicator accessory and a language indicator accessory that reads EN to represent the English language.",
      "identifier": "media-4277103",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cb559fac35d45dd0f5304fa3db3cdf2e/media-4277103@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/780684a182a3e49aa09bd0fbb66deda9/media-4277103~dark@2x.png"
        }
      ]
    },
    "media-4277104": {
      "alt": "Screenshot of the text cursor in a text input field. The text cursor shows the language switcher accessory with three possible input languages: English, Russian, Arabic, and Japanese.",
      "identifier": "media-4277104",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ffaaab086b99f0c1cc7f2c001045e760/media-4277104@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9ccd5480e3ba1d2f82282ddf61b68d85/media-4277104~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-input",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
        "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct"
      ],
      "title": "Text input"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-input",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
                "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct"
              ],
              "title": "Text input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/title",
          "value": "NSTextInputContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1effectsViewInserter/title",
          "value": "effectsViewInserter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1effectsViewInserter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectsViewInserter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/title",
          "value": "NSTextInsertionIndicatorDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1unionRectInVisibleSelectedRange/title",
          "value": "unionRectInVisibleSelectedRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1unionRectInVisibleSelectedRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unionRectInVisibleSelectedRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1hidden/title",
          "value": "NSTextInsertionIndicatorDisplayModeHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1hidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayModeHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct~1showEffectsView/title",
          "value": "NSTextInsertionIndicatorAutomaticModeOptionsShowEffectsView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct~1showEffectsView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptionsShowEffectsView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/title",
          "value": "NSTextContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1preferredTextAccessoryPlacement()/title",
          "value": "preferredTextAccessoryPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1preferredTextAccessoryPlacement()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "preferredTextAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/title",
          "value": "NSTextInsertionIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1documentVisibleRect/title",
          "value": "documentVisibleRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient~1documentVisibleRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentVisibleRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientWillStartScrollingOrZooming()/title",
          "value": "textInputClientWillStartScrollingOrZooming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientWillStartScrollingOrZooming()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textInputClientWillStartScrollingOrZooming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1automaticModeOptions-swift.property/title",
          "value": "automaticModeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1automaticModeOptions-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/title",
          "value": "NSTextInputClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1automatic/title",
          "value": "NSTextInsertionIndicatorDisplayModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct~1showWhileTracking/title",
          "value": "NSTextInsertionIndicatorAutomaticModeOptionsShowWhileTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct~1showWhileTracking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptionsShowWhileTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientDidEndScrollingOrZooming()/title",
          "value": "textInputClientDidEndScrollingOrZooming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientDidEndScrollingOrZooming()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textInputClientDidEndScrollingOrZooming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title",
          "value": "NSTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1visible/title",
          "value": "NSTextInsertionIndicatorDisplayModeVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum~1visible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayModeVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/title",
          "value": "NSTextAlternatives"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/title",
          "value": "NSTextInsertionIndicatorAutomaticModeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/adopting-the-system-text-cursor-in-custom-text-views"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/adopting-the-system-text-cursor-in-custom-text-views"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
