{
  "abstract": [
    {
      "text": "Attributes that are specific to the app object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
        "doc://com.apple.appkit/documentation/AppKit/nsaccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "App-Specific Attributes"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/extrasMenuBar": {
      "abstract": [
        {
          "text": "The app extras menu bar (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extrasMenuBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/extrasMenuBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityExtrasMenuBarAttribute"
        }
      ],
      "role": "symbol",
      "title": "extrasMenuBar",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/extrasmenubar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/focusedUIElement": {
      "abstract": [
        {
          "text": "The element with the current focus (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedUIElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/focusedUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFocusedUIElementAttribute"
        }
      ],
      "role": "symbol",
      "title": "focusedUIElement",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/focuseduielement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/focusedWindow": {
      "abstract": [
        {
          "text": "The app’s window that has current focus (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/focusedWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFocusedWindowAttribute"
        }
      ],
      "role": "symbol",
      "title": "focusedWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/focusedwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/frontmost": {
      "abstract": [
        {
          "text": "A flag that indicates whether the app is frontmost (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontmost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/frontmost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFrontmostAttribute"
        }
      ],
      "role": "symbol",
      "title": "frontmost",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/frontmost"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/hidden": {
      "abstract": [
        {
          "text": "A flag that indicates whether the app is hidden (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/hidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityHiddenAttribute"
        }
      ],
      "role": "symbol",
      "title": "hidden",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/hidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/mainWindow": {
      "abstract": [
        {
          "text": "The app’s main window (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mainWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/mainWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMainWindowAttribute"
        }
      ],
      "role": "symbol",
      "title": "mainWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/mainwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/menuBar": {
      "abstract": [
        {
          "text": "The app’s menu bar (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/menuBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMenuBarAttribute"
        }
      ],
      "role": "symbol",
      "title": "menuBar",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/menubar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/windows": {
      "abstract": [
        {
          "text": "The app’s windows (",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/windows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityWindowsAttribute"
        }
      ],
      "role": "symbol",
      "title": "windows",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/windows"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to individual table cells.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used with grid views, such as thumbnails and media browsers that present a grid of items. The children of a grid are ordered.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Grid View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/grid-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the items in a layout area.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Item Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-item-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsaccessibility": {
      "abstract": [
        {
          "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used in outline views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/slider-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to sliders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/slider-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Slider Attributes",
      "type": "topic",
      "url": "/documentation/appkit/slider-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/standard-attributes": {
      "abstract": [
        {
          "text": "Standard attributes that can be adopted by any accessibility object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Attributes",
      "type": "topic",
      "url": "/documentation/appkit/standard-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to tables and outlines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Table View and Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/table-view-and-outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants": {
      "abstract": [
        {
          "text": "Attributes and key constants used with attributed strings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Attributed-String Attributes and Constants",
      "type": "topic",
      "url": "/documentation/appkit/text-attributed-string-attributes-and-constants"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes specific to windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Window-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/window-specific-attributes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
        "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
        "doc://com.apple.appkit/documentation/AppKit/slider-attributes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/focusedUIElement",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/focusedWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/frontmost",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/hidden",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/mainWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/menuBar",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/windows",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/extrasMenuBar"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/focusedUIElement",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/focusedWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/frontmost",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/hidden",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/mainWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/menuBar",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/windows",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/extrasMenuBar"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
                "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
                "doc://com.apple.appkit/documentation/AppKit/slider-attributes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1windows/title",
          "value": "NSAccessibilityWindowsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1windows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityWindowsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1focusedUIElement/title",
          "value": "NSAccessibilityFocusedUIElementAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1focusedUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFocusedUIElementAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1focusedWindow/title",
          "value": "NSAccessibilityFocusedWindowAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1focusedWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFocusedWindowAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1hidden/title",
          "value": "NSAccessibilityHiddenAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1hidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityHiddenAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1frontmost/title",
          "value": "NSAccessibilityFrontmostAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1frontmost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFrontmostAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1extrasMenuBar/title",
          "value": "NSAccessibilityExtrasMenuBarAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1extrasMenuBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityExtrasMenuBarAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1mainWindow/title",
          "value": "NSAccessibilityMainWindowAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1mainWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMainWindowAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1menuBar/title",
          "value": "NSAccessibilityMenuBarAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1menuBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMenuBarAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/app-specific-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/app-specific-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
