{
  "abstract": [
    {
      "text": "Show, hide, minimize, arrange, and update your app’s windows.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/app-windows"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "App Windows"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/OcclusionState-swift.struct": {
      "abstract": [
        {
          "text": "This constant indicates whether at least part of any window owned by this app is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OcclusionState"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/OcclusionState-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OcclusionState"
        }
      ],
      "role": "symbol",
      "title": "NSApplication.OcclusionState",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/occlusionstate-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/WindowListOptions": {
      "abstract": [
        {
          "text": "This constant indicates a window ordering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WindowListOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/WindowListOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WindowListOptions"
        }
      ],
      "role": "symbol",
      "title": "NSApplication.WindowListOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/windowlistoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/arrangeInFront(_:)": {
      "abstract": [
        {
          "text": "Arranges windows listed in the Window menu in front of all other windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrangeInFront"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/arrangeInFront(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrangeInFront:"
        }
      ],
      "role": "symbol",
      "title": "arrangeInFront(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/arrangeinfront(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/completeStateRestoration()": {
      "abstract": [
        {
          "text": "Completes the extended state restoration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeStateRestoration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/completeStateRestoration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completeStateRestoration"
        }
      ],
      "role": "symbol",
      "title": "completeStateRestoration()",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/completestaterestoration()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/context": {
      "abstract": [
        {
          "text": "The graphics context associated with the app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGraphicsContext",
          "text": "NSGraphicsContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "context"
        }
      ],
      "role": "symbol",
      "title": "context",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/context"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/displayWindowRunLoopOrdering": {
      "abstract": [
        {
          "text": "The priority at which windows are displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayWindowRunLoopOrdering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/displayWindowRunLoopOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisplayWindowRunLoopOrdering"
        }
      ],
      "role": "symbol",
      "title": "displayWindowRunLoopOrdering",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/displaywindowrunloopordering"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/enumerateWindows(options:using:)": {
      "abstract": [
        {
          "text": "Executes a block for each of the app’s windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateWindows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowListOptions",
          "text": "WindowListOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/enumerateWindows(options:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateWindowsWithOptions:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateWindows(options:using:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/enumeratewindows(options:using:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/extendStateRestoration()": {
      "abstract": [
        {
          "text": "Allows an app to extend its state restoration period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendStateRestoration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/extendStateRestoration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendStateRestoration"
        }
      ],
      "role": "symbol",
      "title": "extendStateRestoration()",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/extendstaterestoration()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/hide(_:)": {
      "abstract": [
        {
          "text": "Hides all the receiver’s windows, and the next app in line is activated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/hide(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hide:"
        }
      ],
      "role": "symbol",
      "title": "hide(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/hide(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/isHidden": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/ishidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/isProtectedDataAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isProtectedDataAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/isProtectedDataAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "protectedDataAvailable"
        }
      ],
      "role": "symbol",
      "title": "isProtectedDataAvailable",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/isprotecteddataavailable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/keyWindow": {
      "abstract": [
        {
          "text": "The window that currently receives keyboard events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/keyWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyWindow"
        }
      ],
      "role": "symbol",
      "title": "keyWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/keywindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/mainWindow": {
      "abstract": [
        {
          "text": "The app’s main window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mainWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/mainWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mainWindow"
        }
      ],
      "role": "symbol",
      "title": "mainWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/mainwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/makeWindowsPerform(_:inOrder:)": {
      "abstract": [
        {
          "text": "Sends the specified message to each of the app’s window objects until one returns a non-",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeWindowsPerform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/makeWindowsPerform(_:inOrder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeWindowsPerform:inOrder:"
        }
      ],
      "role": "symbol",
      "title": "makeWindowsPerform(_:inOrder:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/makewindowsperform(_:inorder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/miniaturizeAll(_:)": {
      "abstract": [
        {
          "text": "Miniaturizes all the receiver’s windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miniaturizeAll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/miniaturizeAll(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "miniaturizeAll:"
        }
      ],
      "role": "symbol",
      "title": "miniaturizeAll(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/miniaturizeall(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/occlusionState-swift.property": {
      "abstract": [
        {
          "text": "The occlusion state of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "occlusionState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationOcclusionState",
          "text": "OcclusionState"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/occlusionState-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "occlusionState"
        }
      ],
      "role": "symbol",
      "title": "occlusionState",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/occlusionstate-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/preventWindowOrdering()": {
      "abstract": [
        {
          "text": "Suppresses the usual window ordering in handling the most recent mouse-down event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preventWindowOrdering"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/preventWindowOrdering()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preventWindowOrdering"
        }
      ],
      "role": "symbol",
      "title": "preventWindowOrdering()",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/preventwindowordering()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/resetCursorRectsRunLoopOrdering": {
      "abstract": [
        {
          "text": "The priority at which cursor rects are reset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetCursorRectsRunLoopOrdering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/resetCursorRectsRunLoopOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSResetCursorRectsRunLoopOrdering"
        }
      ],
      "role": "symbol",
      "title": "resetCursorRectsRunLoopOrdering",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/resetcursorrectsrunloopordering"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/restoreWindow(withIdentifier:state:completionHandler:)": {
      "abstract": [
        {
          "text": "Invoked to request that a window be restored.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreWindow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSUserInterfaceItemIdentifier",
          "text": "NSUserInterfaceItemIdentifier"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/restoreWindow(withIdentifier:state:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "restoreWindowWithIdentifier:state:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "restoreWindow(withIdentifier:state:completionHandler:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/restorewindow(withidentifier:state:completionhandler:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/setWindowsNeedUpdate(_:)": {
      "abstract": [
        {
          "text": "Sets whether the receiver’s windows need updating when the receiver has finished processing the current event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setWindowsNeedUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/setWindowsNeedUpdate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setWindowsNeedUpdate:"
        }
      ],
      "role": "symbol",
      "title": "setWindowsNeedUpdate(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/setwindowsneedupdate(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/unhide(_:)": {
      "abstract": [
        {
          "text": "Restores hidden windows to the screen and makes the receiver active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unhide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/unhide(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unhide:"
        }
      ],
      "role": "symbol",
      "title": "unhide(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/unhide(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/unhideWithoutActivation()": {
      "abstract": [
        {
          "text": "Restores hidden windows without activating their owner (the receiver).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unhideWithoutActivation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/unhideWithoutActivation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unhideWithoutActivation"
        }
      ],
      "role": "symbol",
      "title": "unhideWithoutActivation()",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/unhidewithoutactivation()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindows()": {
      "abstract": [
        {
          "text": "Sends an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/update()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message to each onscreen window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateWindows"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindows()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateWindows"
        }
      ],
      "role": "symbol",
      "title": "updateWindows()",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/updatewindows()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/window(withWindowNumber:)": {
      "abstract": [
        {
          "text": "Returns the window corresponding to the specified window number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "window"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withWindowNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/window(withWindowNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowWithWindowNumber:"
        }
      ],
      "role": "symbol",
      "title": "window(withWindowNumber:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/window(withwindownumber:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/windows": {
      "abstract": [
        {
          "text": "An array of the app’s window objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/windows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windows"
        }
      ],
      "role": "symbol",
      "title": "windows",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/windows"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/update()": {
      "abstract": [
        {
          "text": "Updates the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/update()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "update"
        }
      ],
      "role": "symbol",
      "title": "update()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/update()"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-and-environment": {
      "abstract": [
        {
          "text": "Learn about the objects that you use to interact with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and Environment",
      "type": "topic",
      "url": "/documentation/appkit/app-and-environment"
    },
    "doc://com.apple.appkit/documentation/AppKit/menus": {
      "abstract": [
        {
          "text": "Access the app’s main menu items and update the window and services menus.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/menus",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Menus",
      "type": "topic",
      "url": "/documentation/appkit/menus"
    },
    "doc://com.apple.appkit/documentation/AppKit/modal-windows-and-panels": {
      "abstract": [
        {
          "text": "Display a modal window or show one of the standard app panels, such as the app’s About panel.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/modal-windows-and-panels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modal Windows and Panels",
      "type": "topic",
      "url": "/documentation/appkit/modal-windows-and-panels"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsupdatewindowsrunloopordering": {
      "abstract": [
        {
          "text": "This constant is used by the ",
          "type": "text"
        },
        {
          "code": "NSRunLoop",
          "type": "codeVoice"
        },
        {
          "text": " method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/runloop/1409310-perform",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsupdatewindowsrunloopordering",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSUpdateWindowsRunLoopOrdering",
      "type": "topic",
      "url": "/documentation/appkit/nsupdatewindowsrunloopordering"
    },
    "doc://com.apple.documentation/documentation/foundation/runloop/1409310-perform": {
      "abstract": [
        {
          "text": "Schedules the sending of a message on the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "(Selector, "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": Any, "
        },
        {
          "kind": "identifier",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": Any?, "
        },
        {
          "kind": "identifier",
          "text": "order"
        },
        {
          "kind": "text",
          "text": ": Int, "
        },
        {
          "kind": "identifier",
          "text": "modes"
        },
        {
          "kind": "text",
          "text": ": [RunLoop.Mode])"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/runloop/1409310-perform",
      "kind": "symbol",
      "role": "symbol",
      "title": "perform(_:target:argument:order:modes:)",
      "type": "topic",
      "url": "/documentation/foundation/runloop/1409310-perform"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Windows-Panels-and-Menus",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/modal-windows-and-panels",
        "doc://com.apple.appkit/documentation/AppKit/menus"
      ],
      "title": "Managing Windows, Panels, and Menus"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-App-Windows",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/keyWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/mainWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/window(withWindowNumber:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/windows",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/makeWindowsPerform(_:inOrder:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/enumerateWindows(options:using:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/WindowListOptions"
      ],
      "title": "Managing App Windows"
    },
    {
      "anchor": "Minimizing-Windows",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/miniaturizeAll(_:)"
      ],
      "title": "Minimizing Windows"
    },
    {
      "anchor": "Hiding-Windows",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/isHidden",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/hide(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/unhide(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/unhideWithoutActivation()"
      ],
      "title": "Hiding Windows"
    },
    {
      "anchor": "Updating-Windows",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindows()",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/setWindowsNeedUpdate(_:)"
      ],
      "title": "Updating Windows"
    },
    {
      "anchor": "Managing-Window-Layers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/preventWindowOrdering()",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/arrangeInFront(_:)"
      ],
      "title": "Managing Window Layers"
    },
    {
      "anchor": "Drawing-Windows",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/context"
      ],
      "title": "Drawing Windows"
    },
    {
      "anchor": "Getting-the-Occlusion-State",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/occlusionState-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/OcclusionState-swift.struct"
      ],
      "title": "Getting the Occlusion State"
    },
    {
      "anchor": "Restoring-App-Windows-at-Launch",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/isProtectedDataAvailable",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/extendStateRestoration()",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/completeStateRestoration()",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/restoreWindow(withIdentifier:state:completionHandler:)"
      ],
      "title": "Restoring App Windows at Launch"
    },
    {
      "anchor": "Managing-Run-Loops",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/displayWindowRunLoopOrdering",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/resetCursorRectsRunLoopOrdering",
        "doc://com.apple.appkit/documentation/AppKit/nsupdatewindowsrunloopordering"
      ],
      "title": "Managing Run Loops"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-App-Windows",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/keyWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/mainWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/window(withWindowNumber:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/windows",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/makeWindowsPerform(_:inOrder:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/enumerateWindows(options:using:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/WindowListOptions"
              ],
              "title": "Managing App Windows"
            },
            {
              "anchor": "Minimizing-Windows",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/miniaturizeAll(_:)"
              ],
              "title": "Minimizing Windows"
            },
            {
              "anchor": "Hiding-Windows",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/isHidden",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/hide(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/unhide(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/unhideWithoutActivation()"
              ],
              "title": "Hiding Windows"
            },
            {
              "anchor": "Updating-Windows",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindows()",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/setWindowsNeedUpdate(_:)"
              ],
              "title": "Updating Windows"
            },
            {
              "anchor": "Managing-Window-Layers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/preventWindowOrdering()",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/arrangeInFront(_:)"
              ],
              "title": "Managing Window Layers"
            },
            {
              "anchor": "Drawing-Windows",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/context"
              ],
              "title": "Drawing Windows"
            },
            {
              "anchor": "Getting-the-Occlusion-State",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/occlusionState-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/OcclusionState-swift.struct"
              ],
              "title": "Getting the Occlusion State"
            },
            {
              "anchor": "Restoring-App-Windows-at-Launch",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/isProtectedDataAvailable",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/extendStateRestoration()",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/completeStateRestoration()",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/restoreWindow(withIdentifier:state:completionHandler:)"
              ],
              "title": "Restoring App Windows at Launch"
            },
            {
              "anchor": "Managing-Run-Loops",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/displayWindowRunLoopOrdering",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/resetCursorRectsRunLoopOrdering",
                "doc://com.apple.appkit/documentation/AppKit/nsupdatewindowsrunloopordering"
              ],
              "title": "Managing Run Loops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Windows-Panels-and-Menus",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/modal-windows-and-panels",
                "doc://com.apple.appkit/documentation/AppKit/menus"
              ],
              "title": "Managing Windows, Panels, and Menus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1displayWindowRunLoopOrdering/title",
          "value": "NSDisplayWindowRunLoopOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1displayWindowRunLoopOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayWindowRunLoopOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1keyWindow/title",
          "value": "keyWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1keyWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1context/title",
          "value": "context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1occlusionState-swift.property/title",
          "value": "occlusionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1occlusionState-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "occlusionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1update()/title",
          "value": "update"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1update()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "update"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1runloop~11409310-perform/title",
          "value": "performSelector:target:argument:order:modes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1completeStateRestoration()/title",
          "value": "completeStateRestoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1completeStateRestoration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "completeStateRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1enumerateWindows(options:using:)/title",
          "value": "enumerateWindowsWithOptions:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1enumerateWindows(options:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateWindowsWithOptions:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1WindowListOptions/title",
          "value": "NSWindowListOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1WindowListOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowListOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1WindowListOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowListOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1arrangeInFront(_:)/title",
          "value": "arrangeInFront:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1arrangeInFront(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "arrangeInFront:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1OcclusionState-swift.struct/title",
          "value": "NSApplicationOcclusionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1OcclusionState-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationOcclusionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1OcclusionState-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationOcclusionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1window(withWindowNumber:)/title",
          "value": "windowWithWindowNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1window(withWindowNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "windowWithWindowNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1restoreWindow(withIdentifier:state:completionHandler:)/title",
          "value": "restoreWindowWithIdentifier:state:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1restoreWindow(withIdentifier:state:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "restoreWindowWithIdentifier:state:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1resetCursorRectsRunLoopOrdering/title",
          "value": "NSResetCursorRectsRunLoopOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1resetCursorRectsRunLoopOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSResetCursorRectsRunLoopOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1miniaturizeAll(_:)/title",
          "value": "miniaturizeAll:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1miniaturizeAll(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "miniaturizeAll:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1unhide(_:)/title",
          "value": "unhide:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1unhide(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unhide:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1setWindowsNeedUpdate(_:)/title",
          "value": "setWindowsNeedUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1setWindowsNeedUpdate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setWindowsNeedUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1extendStateRestoration()/title",
          "value": "extendStateRestoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1extendStateRestoration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "extendStateRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1hide(_:)/title",
          "value": "hide:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1hide(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hide:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1updateWindows()/title",
          "value": "updateWindows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1updateWindows()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateWindows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1unhideWithoutActivation()/title",
          "value": "unhideWithoutActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1unhideWithoutActivation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unhideWithoutActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1preventWindowOrdering()/title",
          "value": "preventWindowOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1preventWindowOrdering()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "preventWindowOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1makeWindowsPerform(_:inOrder:)/title",
          "value": "makeWindowsPerform:inOrder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1makeWindowsPerform(_:inOrder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeWindowsPerform:inOrder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1mainWindow/title",
          "value": "mainWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1mainWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mainWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1isProtectedDataAvailable/title",
          "value": "protectedDataAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1isProtectedDataAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "protectedDataAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1windows/title",
          "value": "windows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1windows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windows"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/app-windows"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/app-windows"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
