{
  "abstract": [
    {
      "text": "Extend your app’s basic functionality to other parts of the system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/app-extensions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "App Extensions"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierAddressText": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTypeIdentifierAddressText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierAddressText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypeIdentifierAddressText"
        }
      ],
      "role": "symbol",
      "title": "NSTypeIdentifierAddressText",
      "type": "topic",
      "url": "/documentation/appkit/nstypeidentifieraddresstext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierDateText": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTypeIdentifierDateText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierDateText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypeIdentifierDateText"
        }
      ],
      "role": "symbol",
      "title": "NSTypeIdentifierDateText",
      "type": "topic",
      "url": "/documentation/appkit/nstypeidentifierdatetext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierPhoneNumberText": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTypeIdentifierPhoneNumberText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierPhoneNumberText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypeIdentifierPhoneNumberText"
        }
      ],
      "role": "symbol",
      "title": "NSTypeIdentifierPhoneNumberText",
      "type": "topic",
      "url": "/documentation/appkit/nstypeidentifierphonenumbertext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierTransitInformationText": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTypeIdentifierTransitInformationText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierTransitInformationText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypeIdentifierTransitInformationText"
        }
      ],
      "role": "symbol",
      "title": "NSTypeIdentifierTransitInformationText",
      "type": "topic",
      "url": "/documentation/appkit/nstypeidentifiertransitinformationtext"
    },
    "doc://com.apple.appkit/documentation/AppKit/add-functionality-to-finder-with-action-extensions": {
      "abstract": [
        {
          "text": "Implement Action Extensions to provide quick access to commonly used features of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/add-functionality-to-finder-with-action-extensions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Add Functionality to Finder with Action Extensions",
      "type": "topic",
      "url": "/documentation/appkit/add-functionality-to-finder-with-action-extensions"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-and-environment": {
      "abstract": [
        {
          "text": "Learn about the objects that you use to interact with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and Environment",
      "type": "topic",
      "url": "/documentation/appkit/app-and-environment"
    },
    "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings": {
      "abstract": [
        {
          "text": "Automatically synchronize your data model with your app’s interface using Cocoa Bindings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cocoa Bindings",
      "type": "topic",
      "url": "/documentation/appkit/cocoa-bindings"
    },
    "doc://com.apple.appkit/documentation/AppKit/documents-data-and-pasteboard": {
      "abstract": [
        {
          "text": "Organize your app’s data and preferences, and share that data on the pasteboard or in iCloud.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/documents-data-and-pasteboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Documents, Data, and Pasteboard",
      "type": "topic",
      "url": "/documentation/appkit/documents-data-and-pasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/resource-management": {
      "abstract": [
        {
          "text": "Manage the storyboards and nib files containing your app’s user interface, and learn how to load data that is stored in resource files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/resource-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource Management",
      "type": "topic",
      "url": "/documentation/appkit/resource-management"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the extension appears in the Finder Preview pane and Quick Actions menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionServiceAllowsFinderPreviewItem",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the extension appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionServiceAllowsTouchBarItem",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName": {
      "abstract": [
        {
          "text": "The name of an icon for display when the extension appears in the Finder Preview pane and Quick Actions menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionServiceFinderPreviewIconName",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel": {
      "abstract": [
        {
          "text": "A name for display when the extension appears in the Finder Preview pane and Quick Actions menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionServiceFinderPreviewLabel",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName": {
      "abstract": [
        {
          "text": "The color to use for the bezel around the extension when it appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarBezelColorName",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName": {
      "abstract": [
        {
          "text": "The name of an icon for display when the extension appears as a Quick Action in the Touch Bar",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarIconName",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel": {
      "abstract": [
        {
          "text": "A name for display when the extension appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarLabel",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel"
    },
    "doc://com.apple.documentation/documentation/MailKit/build-mail-app-extensions": {
      "abstract": [
        {
          "text": "Create app extensions that block content, perform message and composing actions, and help message security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MailKit/build-mail-app-extensions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Build Mail App Extensions",
      "type": "topic",
      "url": "/documentation/MailKit/build-mail-app-extensions"
    },
    "doc://com.apple.documentation/documentation/foundation/nsextensioncontext": {
      "abstract": [
        {
          "text": "The host app context from which an app extension is invoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsextensioncontext",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionContext",
      "type": "topic",
      "url": "/documentation/foundation/nsextensioncontext"
    },
    "doc://com.apple.documentation/documentation/foundation/nsextensionrequesthandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsextensionrequesthandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-Structure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
        "doc://com.apple.appkit/documentation/AppKit/documents-data-and-pasteboard",
        "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
        "doc://com.apple.appkit/documentation/AppKit/resource-management"
      ],
      "title": "App Structure"
    }
  ],
  "topicSections": [
    {
      "anchor": "Extension-Support",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsextensioncontext",
        "doc://com.apple.documentation/documentation/foundation/nsextensionrequesthandling"
      ],
      "title": "Extension Support"
    },
    {
      "abstract": [
        {
          "text": "Quick Actions allow your app extension to appear in the Finder Preview pane, Quick Actions menu, and Touch Bar.",
          "type": "text"
        }
      ],
      "anchor": "Quick-Actions",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/add-functionality-to-finder-with-action-extensions",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName"
      ],
      "title": "Quick Actions"
    },
    {
      "anchor": "Mail-Extensions",
      "identifiers": [
        "doc://com.apple.documentation/documentation/MailKit/build-mail-app-extensions"
      ],
      "title": "Mail Extensions"
    },
    {
      "anchor": "UTI-Subtypes-for-Data-Detector-Types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierAddressText",
        "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierDateText",
        "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierPhoneNumberText",
        "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierTransitInformationText"
      ],
      "title": "UTI Subtypes for Data Detector Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Extension-Support",
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/nsextensioncontext",
                "doc://com.apple.documentation/documentation/foundation/nsextensionrequesthandling"
              ],
              "title": "Extension Support"
            },
            {
              "abstract": [
                {
                  "text": "Quick Actions allow your app extension to appear in the Finder Preview pane, Quick Actions menu, and Touch Bar.",
                  "type": "text"
                }
              ],
              "anchor": "Quick-Actions",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/add-functionality-to-finder-with-action-extensions",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName"
              ],
              "title": "Quick Actions"
            },
            {
              "anchor": "Mail-Extensions",
              "identifiers": [
                "doc://com.apple.documentation/documentation/MailKit/build-mail-app-extensions"
              ],
              "title": "Mail Extensions"
            },
            {
              "anchor": "UTI-Subtypes-for-Data-Detector-Types",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierAddressText",
                "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierDateText",
                "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierPhoneNumberText",
                "doc://com.apple.appkit/documentation/AppKit/NSTypeIdentifierTransitInformationText"
              ],
              "title": "UTI Subtypes for Data Detector Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-Structure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
                "doc://com.apple.appkit/documentation/AppKit/documents-data-and-pasteboard",
                "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
                "doc://com.apple.appkit/documentation/AppKit/resource-management"
              ],
              "title": "App Structure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypeIdentifierAddressText/title",
          "value": "NSTypeIdentifierAddressText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypeIdentifierAddressText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypeIdentifierAddressText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypeIdentifierDateText/title",
          "value": "NSTypeIdentifierDateText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypeIdentifierDateText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypeIdentifierDateText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypeIdentifierPhoneNumberText/title",
          "value": "NSTypeIdentifierPhoneNumberText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypeIdentifierPhoneNumberText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypeIdentifierPhoneNumberText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypeIdentifierTransitInformationText/title",
          "value": "NSTypeIdentifierTransitInformationText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypeIdentifierTransitInformationText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypeIdentifierTransitInformationText"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/app-extensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/app-extensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
