{
  "abstract": [
    {
      "text": "Add Dark Mode support to your app, and use appearance proxies to modify your UI.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/appearance-customization"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Appearance Customization"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppearance": {
      "abstract": [
        {
          "text": "An object that manages standard appearance attributes for UI elements in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearance"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppearance"
        }
      ],
      "role": "symbol",
      "title": "NSAppearance",
      "type": "topic",
      "url": "/documentation/appkit/nsappearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization": {
      "abstract": [
        {
          "text": "A set of methods for getting and setting the appearance attributes of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        }
      ],
      "role": "symbol",
      "title": "NSAppearanceCustomization",
      "type": "topic",
      "url": "/documentation/appkit/nsappearancecustomization"
    },
    "doc://com.apple.appkit/documentation/AppKit/animation": {
      "abstract": [
        {
          "text": "Animate your views and other content to create a more engaging experience for users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/animation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation",
      "type": "topic",
      "url": "/documentation/appkit/animation"
    },
    "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics": {
      "abstract": [
        {
          "text": "Play sounds and haptic feedback, and incorporate speech recognition and synthesis into your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sound, Speech, and Haptics",
      "type": "topic",
      "url": "/documentation/appkit/sound-speech-and-haptics"
    },
    "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app": {
      "abstract": [
        {
          "text": "Incorporate scanned documents and pictures from a user’s iPhone, iPad, or iPod touch into your Mac app using Continuity Camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting Continuity Camera in Your Mac App",
      "type": "topic",
      "url": "/documentation/appkit/supporting-continuity-camera-in-your-mac-app"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-layout": {
      "abstract": [
        {
          "text": "Position and size views using a stack view or Auto Layout constraints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-layout",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Layout",
      "type": "topic",
      "url": "/documentation/appkit/view-layout"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-management": {
      "abstract": [
        {
          "text": "Manage your user interface, including the size and position of views in a window.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Management",
      "type": "topic",
      "url": "/documentation/appkit/view-management"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens": {
      "abstract": [
        {
          "text": "Organize your view hierarchies and facilitate their display onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows, Panels, and Screens",
      "type": "topic",
      "url": "/documentation/appkit/windows-panels-and-screens"
    },
    "doc://com.apple.documentation/documentation/UIKit/supporting-dark-mode-in-your-interface": {
      "abstract": [
        {
          "text": "Update colors, images, and behaviors so that your app adapts automatically when Dark Mode is active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/supporting-dark-mode-in-your-interface",
      "kind": "article",
      "role": "article",
      "title": "Supporting Dark Mode in Your Interface",
      "type": "topic",
      "url": "/documentation/UIKit/supporting-dark-mode-in-your-interface"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/view-management",
        "doc://com.apple.appkit/documentation/AppKit/view-layout",
        "doc://com.apple.appkit/documentation/AppKit/animation",
        "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
        "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics",
        "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app"
      ],
      "title": "User Interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dark-Mode",
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/supporting-dark-mode-in-your-interface"
      ],
      "title": "Dark Mode"
    },
    {
      "abstract": [
        {
          "text": "Apply standard themes to the views in your interface.",
          "type": "text"
        }
      ],
      "anchor": "Appearance-System",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAppearance",
        "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization"
      ],
      "title": "Appearance System"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dark-Mode",
              "identifiers": [
                "doc://com.apple.documentation/documentation/UIKit/supporting-dark-mode-in-your-interface"
              ],
              "title": "Dark Mode"
            },
            {
              "abstract": [
                {
                  "text": "Apply standard themes to the views in your interface.",
                  "type": "text"
                }
              ],
              "anchor": "Appearance-System",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAppearance",
                "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization"
              ],
              "title": "Appearance System"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
                "doc://com.apple.appkit/documentation/AppKit/view-management",
                "doc://com.apple.appkit/documentation/AppKit/view-layout",
                "doc://com.apple.appkit/documentation/AppKit/animation",
                "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
                "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics",
                "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app"
              ],
              "title": "User Interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearance/title",
          "value": "NSAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/title",
          "value": "NSAppearanceCustomization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/appearance-customization"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/appearance-customization"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
