{
  "abstract": [
    {
      "text": "The version of the AppKit framework containing a specific bug fix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/appkit-versions-for-nscursor-bug-fixes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AppKit Versions for NSCursor Bug Fixes"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCursorSizeSupport": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework that introduced support for cursors larger than 16 x 16 pixels in size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithCursorSizeSupport"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCursorSizeSupport",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithCursorSizeSupport",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithcursorsizesupport"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor": {
      "abstract": [
        {
          "text": "A pointer (also called a cursor).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCursor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursor"
        }
      ],
      "role": "symbol",
      "title": "NSCursor",
      "type": "topic",
      "url": "/documentation/appkit/nscursor"
    },
    "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock": {
      "abstract": [
        {
          "text": "Implement menus and cursors to facilitate interactions with your app, and use your app’s Dock tile to convey updated information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Menus, Cursors, and the Dock",
      "type": "topic",
      "url": "/documentation/appkit/menus-cursors-and-the-dock"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCursorSizeSupport"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title",
          "value": "NSCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/appkit-versions-for-nscursor-bug-fixes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/appkit-versions-for-nscursor-bug-fixes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
