{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/NSButton",
        "doc://com.apple.appkit/documentation/AppKit/NSButtonCell",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/bezelstyle-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton": {
      "abstract": [
        {
          "text": "A control that defines an area on the screen that a user clicks to trigger an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum": {
      "abstract": [
        {
          "text": "The set of bezel styles to style buttons in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/inline": {
      "abstract": [
        {
          "text": "A button that has a solid round-rectangle border background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/inline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleInline"
        }
      ],
      "role": "symbol",
      "title": "inline",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/inline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/recessed": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use in scope bars and title bar accessories, similar to the bookmarks bar in Safari.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recessed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/recessed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRecessed"
        }
      ],
      "role": "symbol",
      "title": "recessed",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/recessed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/regularSquare": {
      "abstract": [
        {
          "text": "A rectangular button with a two-point border, designed for icons.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularSquare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/regularSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRegularSquare"
        }
      ],
      "role": "symbol",
      "title": "regularSquare",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/regularsquare"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundRect": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use as an action or auxiliary button in scope bars and title bar accessories.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roundRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRoundRect"
        }
      ],
      "role": "symbol",
      "title": "roundRect",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/roundrect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/rounded": {
      "abstract": [
        {
          "text": "A rounded rectangle button, designed for text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rounded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/rounded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRounded"
        }
      ],
      "role": "symbol",
      "title": "rounded",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/rounded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundedDisclosure": {
      "abstract": [
        {
          "text": "A bezel style for use with a vertically expanding and collapsing disclosure button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roundedDisclosure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundedDisclosure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRoundedDisclosure"
        }
      ],
      "role": "symbol",
      "title": "roundedDisclosure",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/roundeddisclosure"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/shadowlessSquare": {
      "abstract": [
        {
          "text": "A rectangular button with no shadow, so it can abut the cells without overlapping shadows.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowlessSquare"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/shadowlessSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleShadowlessSquare"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.shadowlessSquare",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/shadowlesssquare"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedRounded": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use in the toolbar or title bar regions of a window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texturedRounded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedRounded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleTexturedRounded"
        }
      ],
      "role": "symbol",
      "title": "texturedRounded",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/texturedrounded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedSquare": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use with textured (metal) windows.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texturedSquare"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleTexturedSquare"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.texturedSquare",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/texturedsquare"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell": {
      "abstract": [
        {
          "text": "An object that defines the user interface of a button or other clickable region of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButtonCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonCell"
        }
      ],
      "role": "symbol",
      "title": "NSButtonCell",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCircularBezelStyle": {
      "abstract": [
        {
          "text": "A round button with room for a small icon or a single character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCircularBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCircularBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCircularBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nscircularbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDisclosureBezelStyle": {
      "abstract": [
        {
          "text": "A bezel style for use with a disclosure triangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDisclosureBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDisclosureBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDisclosureBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsdisclosurebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHelpButtonBezelStyle": {
      "abstract": [
        {
          "text": "A round button with a question mark providing the standard help button look.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHelpButtonBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHelpButtonBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHelpButtonBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nshelpbuttonbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInlineBezelStyle": {
      "abstract": [
        {
          "text": "The inline bezel style contains a solid round-rect border background. It can be used to create an “unread” indicator in an outline view, or another inline button in a tableview, such as a stop progress button in a download panel. Use text for an unread indicator, and a template image for other buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInlineBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInlineBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInlineBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsinlinebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRecessedBezelStyle": {
      "abstract": [
        {
          "text": "A bezel style that matches the recessed buttons in Mail, Finder and Safari.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRecessedBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRecessedBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRecessedBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsrecessedbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRegularSquareBezelStyle": {
      "abstract": [
        {
          "text": "A rectangular button with a two-point border, designed for icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRegularSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRegularSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRegularSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsregularsquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundRectBezelStyle": {
      "abstract": [
        {
          "text": "A bezel style that matches the search buttons in Finder and Mail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundRectBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundRectBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundRectBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundrectbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundedBezelStyle": {
      "abstract": [
        {
          "text": "A rounded rectangle button, designed for text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundedBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundedBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundedBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundedbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundedDisclosureBezelStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundedDisclosureBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundedDisclosureBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundedDisclosureBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundeddisclosurebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSShadowlessSquareBezelStyle": {
      "abstract": [
        {
          "text": "Similar to ",
          "type": "text"
        },
        {
          "code": "NSRegularSquareBezelStyle",
          "type": "codeVoice"
        },
        {
          "text": ", but has no shadow, so you can abut the cells without overlapping shadows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSShadowlessSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSShadowlessSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSShadowlessSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsshadowlesssquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSmallIconButtonBezelStyle": {
      "abstract": [
        {
          "text": "This bezel style is obsolete and should not be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSmallIconButtonBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSmallIconButtonBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSmallIconButtonBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nssmalliconbuttonbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSmallSquareBezelStyle": {
      "abstract": [
        {
          "text": "A simple square bezel style. Buttons using this style can be scaled to any size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSmallSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSmallSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSmallSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nssmallsquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTexturedRoundedBezelStyle": {
      "abstract": [
        {
          "text": "A textured (metal) bezel style similar in appearance to the Finder’s action (gear) button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTexturedRoundedBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTexturedRoundedBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTexturedRoundedBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstexturedroundedbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTexturedSquareBezelStyle": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use with textured (metal) windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTexturedSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTexturedSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTexturedSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstexturedsquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSThickSquareBezelStyle": {
      "abstract": [
        {
          "text": "A rectangular button with a three-point border, designed for icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSThickSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSThickSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSThickSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsthicksquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSThickerSquareBezelStyle": {
      "abstract": [
        {
          "text": "A rectangular button with a four-point border, designed for icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSThickerSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSThickerSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSThickerSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsthickersquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/inline",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/recessed",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/regularSquare",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/rounded",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundedDisclosure",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundRect",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedRounded"
      ],
      "title": "Properties"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/shadowlessSquare",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedSquare"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/inline",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/recessed",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/regularSquare",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/rounded",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundedDisclosure",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundRect",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedRounded"
              ],
              "title": "Properties"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/shadowlessSquare",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedSquare",
                "doc://com.apple.appkit/documentation/AppKit/NSCircularBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSDisclosureBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSHelpButtonBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSInlineBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSRecessedBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSRegularSquareBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSRoundedBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSRoundedDisclosureBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSRoundRectBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSShadowlessSquareBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSSmallIconButtonBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSSmallSquareBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSThickerSquareBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSThickSquareBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTexturedRoundedBezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTexturedSquareBezelStyle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1regularSquare/title",
          "value": "NSBezelStyleRegularSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1regularSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRegularSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1shadowlessSquare/title",
          "value": "NSBezelStyleShadowlessSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1shadowlessSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleShadowlessSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1rounded/title",
          "value": "NSBezelStyleRounded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1rounded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRounded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1roundRect/title",
          "value": "NSBezelStyleRoundRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1roundRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRoundRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1texturedSquare/title",
          "value": "NSBezelStyleTexturedSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1texturedSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleTexturedSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1inline/title",
          "value": "NSBezelStyleInline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1inline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title",
          "value": "NSButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1roundedDisclosure/title",
          "value": "NSBezelStyleRoundedDisclosure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1roundedDisclosure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRoundedDisclosure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/title",
          "value": "NSBezelStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1recessed/title",
          "value": "NSBezelStyleRecessed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1recessed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRecessed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell/title",
          "value": "NSButtonCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1texturedRounded/title",
          "value": "NSBezelStyleTexturedRounded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1texturedRounded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleTexturedRounded"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/bezelstyle-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/bezelstyle-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
