{
  "abstract": [
    {
      "text": "These constants define keys in the binding information dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Binding dictionary keys"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingInfoKey"
        }
      ],
      "role": "symbol",
      "title": "NSBindingInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nsbindinginfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/observedKeyPath": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the key path of the binding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedKeyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingInfoKey",
          "text": "NSBindingInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/observedKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSObservedKeyPathKey"
        }
      ],
      "role": "symbol",
      "title": "observedKeyPath",
      "type": "topic",
      "url": "/documentation/appkit/nsbindinginfokey/observedkeypath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/observedObject": {
      "abstract": [
        {
          "text": "The object that is the observable controller of the binding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingInfoKey",
          "text": "NSBindingInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/observedObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSObservedObjectKey"
        }
      ],
      "role": "symbol",
      "title": "observedObject",
      "type": "topic",
      "url": "/documentation/appkit/nsbindinginfokey/observedobject"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/options": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": " object containing key value pairs as specified in the options",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "dictionary when the binding was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingInfoKey",
          "text": "NSBindingInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOptionsKey"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/appkit/nsbindinginfokey/options"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingName": {
      "abstract": [
        {
          "text": "Values that specify a binding for certain methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingName"
        }
      ],
      "role": "symbol",
      "title": "NSBindingName",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingOption"
        }
      ],
      "role": "symbol",
      "title": "NSBindingOption",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController": {
      "abstract": [
        {
          "text": "A bindings-compatible controller that manages the display and editing of a dictionary of key-value pairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDictionaryController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDictionaryController"
        }
      ],
      "role": "symbol",
      "title": "NSDictionaryController",
      "type": "topic",
      "url": "/documentation/appkit/nsdictionarycontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair": {
      "abstract": [
        {
          "text": "A set of methods implemented by arranged objects to give access to information about those objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDictionaryControllerKeyValuePair"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDictionaryControllerKeyValuePair"
        }
      ],
      "role": "symbol",
      "title": "NSDictionaryControllerKeyValuePair",
      "type": "topic",
      "url": "/documentation/appkit/nsdictionarycontrollerkeyvaluepair"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)": {
      "abstract": [
        {
          "text": "Tests whether a given object is special marker object used for indicating the state of a selection in relation to a key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIsControllerMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIsControllerMarker"
        }
      ],
      "role": "symbol",
      "title": "NSIsControllerMarker(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsiscontrollermarker(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings": {
      "abstract": [
        {
          "text": "Automatically synchronize your data model with your app’s interface using Cocoa Bindings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cocoa Bindings",
      "type": "topic",
      "url": "/documentation/appkit/cocoa-bindings"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation": {
      "abstract": [
        {
          "text": "A set of methods that you can use to create and remove bindings between view objects and controllers, or between controllers and model objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation",
      "kind": "article",
      "role": "article",
      "title": "NSKeyValueBindingCreation",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/nskeyvaluebindingcreation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Key-Value-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
        "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
        "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation"
      ],
      "title": "Key-Value Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/observedObject",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/observedKeyPath",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/options"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/observedObject",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/observedKeyPath",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/options"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Key-Value-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
                "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
                "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation"
              ],
              "title": "Key-Value Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/title",
          "value": "NSBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey~1options/title",
          "value": "NSOptionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey~1options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOptionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey~1observedKeyPath/title",
          "value": "NSObservedKeyPathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey~1observedKeyPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSObservedKeyPathKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/title",
          "value": "NSBindingName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey~1observedObject/title",
          "value": "NSObservedObjectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey~1observedObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSObservedObjectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIsControllerMarker(_:)/title",
          "value": "NSIsControllerMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIsControllerMarker(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIsControllerMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/title",
          "value": "NSBindingInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/title",
          "value": "NSDictionaryControllerKeyValuePair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryControllerKeyValuePair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryControllerKeyValuePair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/title",
          "value": "NSDictionaryController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/binding-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/binding-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
