{
  "abstract": [
    {
      "text": "Provide a column-based interface for viewing and navigating hierarchical information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/browser-view"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Browser View"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowser": {
      "abstract": [
        {
          "text": "An interface that displays a hierarchically organized list of data items that can be navigated and selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBrowser"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBrowser"
        }
      ],
      "role": "symbol",
      "title": "NSBrowser",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowser"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowserCell": {
      "abstract": [
        {
          "text": "The user interface of a browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBrowserCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowserCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBrowserCell"
        }
      ],
      "role": "symbol",
      "title": "NSBrowserCell",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowsercell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBrowserDelegate": {
      "abstract": [
        {
          "text": "A set of methods that a browser delegate implements to manage selection, scrolling, sizing, and other behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBrowserDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBrowserDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBrowserDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSBrowserDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsbrowserdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/collection-view": {
      "abstract": [
        {
          "text": "Display one or more subviews in a highly configurable arrangement.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/collection-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Collection View",
      "type": "topic",
      "url": "/documentation/appkit/collection-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/outline-view": {
      "abstract": [
        {
          "text": "Display a list-based interface for hierarchical data, where each level of hierarchy is indented from the previous one.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/outline-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Outline View",
      "type": "topic",
      "url": "/documentation/appkit/outline-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/table-view": {
      "abstract": [
        {
          "text": "Display custom data in rows and columns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/table-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Table View",
      "type": "topic",
      "url": "/documentation/appkit/table-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-Views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/collection-view",
        "doc://com.apple.appkit/documentation/AppKit/outline-view",
        "doc://com.apple.appkit/documentation/AppKit/table-view",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ],
      "title": "Content Views"
    }
  ],
  "topicSections": [
    {
      "anchor": "View",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBrowser"
      ],
      "title": "View"
    },
    {
      "anchor": "Management",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBrowserDelegate"
      ],
      "title": "Management"
    },
    {
      "anchor": "Cell",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBrowserCell"
      ],
      "title": "Cell"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "View",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBrowser"
              ],
              "title": "View"
            },
            {
              "anchor": "Management",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBrowserDelegate"
              ],
              "title": "Management"
            },
            {
              "anchor": "Cell",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBrowserCell"
              ],
              "title": "Cell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-Views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/collection-view",
                "doc://com.apple.appkit/documentation/AppKit/outline-view",
                "doc://com.apple.appkit/documentation/AppKit/table-view",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ],
              "title": "Content Views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowserDelegate/title",
          "value": "NSBrowserDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowserDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowserDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowserDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowserDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/title",
          "value": "NSBrowser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowserCell/title",
          "value": "NSBrowserCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowserCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowserCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBrowserCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBrowserCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/browser-view"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/browser-view"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
