{
  "abstract": [
    {
      "text": "Load colors from asset catalogs, and create colors from raw component values, such as those used by grayscale, RGB, HSB, and CMYK colors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/color",
        "doc://com.apple.appkit/documentation/AppKit/NSColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/color-creation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Color Creation"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/Name": {
      "abstract": [
        {
          "text": "The name of a color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/Name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSColor.Name",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/name"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init()": {
      "abstract": [
        {
          "text": "Initializes the color object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(CIColor:)": {
      "abstract": [
        {
          "text": "Creates a color object from the specified Core Image color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "CIColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIColor",
          "text": "CIColor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(CIColor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithCIColor:"
        }
      ],
      "role": "symbol",
      "title": "init(CIColor:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(cicolor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI5ColorV",
          "text": "Color"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedHue:saturation:brightness:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object using the given opacity and HSB color space components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "calibratedHue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "saturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "brightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedHue:saturation:brightness:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithCalibratedHue:saturation:brightness:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(calibratedHue:saturation:brightness:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(calibratedhue:saturation:brightness:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedRed:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object using the given opacity and RGB components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "calibratedRed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedRed:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithCalibratedRed:green:blue:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(calibratedRed:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(calibratedred:green:blue:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedWhite:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object using the given opacity and grayscale values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "calibratedWhite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedWhite:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithCalibratedWhite:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(calibratedWhite:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(calibratedwhite:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(catalogName:colorName:)": {
      "abstract": [
        {
          "text": "Creates a color object using the specified asset catalog and color names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "catalogName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorList",
          "text": "NSColorList"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorListName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "colorName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(catalogName:colorName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithCatalogName:colorName:"
        }
      ],
      "role": "symbol",
      "title": "init(catalogName:colorName:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(catalogname:colorname:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(cgColor:)": {
      "abstract": [
        {
          "text": "Creates a color object using the specified Core Graphics color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "cgColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(cgColor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithCGColor:"
        }
      ],
      "role": "symbol",
      "title": "init(cgColor:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(cgcolor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a color object from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(coder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:components:count:)": {
      "abstract": [
        {
          "text": "Creates a color object from the specified components of the given color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "components"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:components:count:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithColorSpace:components:count:"
        }
      ],
      "role": "symbol",
      "title": "init(colorSpace:components:count:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(colorspace:components:count:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:hue:saturation:brightness:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object with the specified color space, hue, saturation, brightness, and alpha channel values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "hue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "saturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "brightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:hue:saturation:brightness:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithColorSpace:hue:saturation:brightness:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(colorSpace:hue:saturation:brightness:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(colorspace:hue:saturation:brightness:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceCyan:magenta:yellow:black:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object using the given opacity value and CMYK components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "deviceCyan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "magenta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "yellow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "black"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceCyan:magenta:yellow:black:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithDeviceCyan:magenta:yellow:black:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(deviceCyan:magenta:yellow:black:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(devicecyan:magenta:yellow:black:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceHue:saturation:brightness:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object using the given opacity value and HSB color space components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "deviceHue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "saturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "brightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceHue:saturation:brightness:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithDeviceHue:saturation:brightness:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(deviceHue:saturation:brightness:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(devicehue:saturation:brightness:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceRed:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object using the given opacity value and RGB components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "deviceRed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceRed:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithDeviceRed:green:blue:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(deviceRed:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(devicered:green:blue:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceWhite:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object using the given opacity and grayscale values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "deviceWhite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceWhite:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithDeviceWhite:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(deviceWhite:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(devicewhite:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(displayP3Red:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object from the specified components in the Display P3 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayP3Red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(displayP3Red:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithDisplayP3Red:green:blue:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(displayP3Red:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(displayp3red:green:blue:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(for:)": {
      "abstract": [
        {
          "text": "Returns the color object specified by the given control tint.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlTint",
          "text": "NSControlTint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorForControlTint:"
        }
      ],
      "role": "symbol",
      "title": "init(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(genericGamma22White:alpha:)": {
      "abstract": [
        {
          "text": "Returns a color object with the specified white and alpha values in the GenericGamma22 colorspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "genericGamma22White"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(genericGamma22White:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithGenericGamma22White:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(genericGamma22White:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(genericgamma22white:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(hue:saturation:brightness:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object with the specified hue, saturation, brightness, and alpha channel values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "hue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "saturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "brightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(hue:saturation:brightness:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithHue:saturation:brightness:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(hue:saturation:brightness:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(hue:saturation:brightness:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(name:dynamicProvider:)": {
      "abstract": [
        {
          "text": "Creates a dynamic catalog color with a provider that’s used to resolve the exact color value, calculated on first use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "dynamicProvider"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAppearance",
          "text": "NSAppearance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(name:dynamicProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithName:dynamicProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(name:dynamicProvider:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(name:dynamicprovider:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(named:)": {
      "abstract": [
        {
          "text": "Creates a color object from the provided name, which corresponds to a color in the default asset catalog of the app’s main bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(named:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorNamed:"
        }
      ],
      "role": "symbol",
      "title": "init(named:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(named:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(named:bundle:)": {
      "abstract": [
        {
          "text": "Creates a color object from the provided name, which corresponds to a color in the default asset catalog of the specified bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bundle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(named:bundle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorNamed:bundle:"
        }
      ],
      "role": "symbol",
      "title": "init(named:bundle:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(named:bundle:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(patternImage:)": {
      "abstract": [
        {
          "text": "Creates a color object that uses the specified image pattern to paint the target area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "patternImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(patternImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithPatternImage:"
        }
      ],
      "role": "symbol",
      "title": "init(patternImage:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(patternimage:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(red:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object with the specified red, green, blue, and alpha channel values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(red:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithRed:green:blue:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(red:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(red:green:blue:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(resource:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport13ColorResourceV",
          "text": "ColorResource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(resource:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(resource:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(resource:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(srgbRed:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object from the specified components in the sRGB colorspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "srgbRed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(srgbRed:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithSRGBRed:green:blue:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(srgbRed:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(srgbred:green:blue:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(white:alpha:)": {
      "abstract": [
        {
          "text": "Creates a color object with the specified brightness and alpha channel values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "white"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(white:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithWhite:alpha:"
        }
      ],
      "role": "symbol",
      "title": "init(white:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(white:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/patternImage": {
      "abstract": [
        {
          "text": "The pattern image used to paint the target area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/patternImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "patternImage"
        }
      ],
      "role": "symbol",
      "title": "patternImage",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/patternimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControlTint": {
      "abstract": [
        {
          "text": "Constants for specifying a cell’s tint color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlTint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControlTint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlTint"
        }
      ],
      "role": "symbol",
      "title": "NSControlTint",
      "type": "topic",
      "url": "/documentation/appkit/nscontroltint"
    },
    "doc://com.apple.appkit/documentation/AppKit/color": {
      "abstract": [
        {
          "text": "Represent colors using built-in or custom formats, and give users options for selecting and applying colors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/appkit/color"
    },
    "doc://com.apple.appkit/documentation/AppKit/standard-colors": {
      "abstract": [
        {
          "text": "Retrieve the standard color objects for common colors like red, blue, green, black, white, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/standard-colors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Colors",
      "type": "topic",
      "url": "/documentation/appkit/standard-colors"
    },
    "doc://com.apple.appkit/documentation/AppKit/ui-element-colors": {
      "abstract": [
        {
          "text": "Retrieve standard color objects for use with windows, controls, labels, text, selections and other content in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/ui-element-colors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UI Element Colors",
      "type": "topic",
      "url": "/documentation/appkit/ui-element-colors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-and-Creating-Colors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/ui-element-colors",
        "doc://com.apple.appkit/documentation/AppKit/standard-colors"
      ],
      "title": "Getting and Creating Colors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Loading-Color-Objects-from-Asset-Catalogs",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(named:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(named:bundle:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(catalogName:colorName:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/Name"
      ],
      "title": "Loading Color Objects from Asset Catalogs"
    },
    {
      "anchor": "Creating-a-Color-Using-RGB-Components",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(srgbRed:green:blue:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(displayP3Red:green:blue:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(red:green:blue:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedRed:green:blue:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceRed:green:blue:alpha:)"
      ],
      "title": "Creating a Color Using RGB Components"
    },
    {
      "anchor": "Creating-a-Color-Using-HSB-Components",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedHue:saturation:brightness:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceHue:saturation:brightness:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(hue:saturation:brightness:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:hue:saturation:brightness:alpha:)"
      ],
      "title": "Creating a Color Using HSB Components"
    },
    {
      "anchor": "Creating-a-Color-Using-CMYK-Components",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceCyan:magenta:yellow:black:alpha:)"
      ],
      "title": "Creating a Color Using CMYK Components"
    },
    {
      "anchor": "Creating-a-Color-Using-White-Components",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(white:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedWhite:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceWhite:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(genericGamma22White:alpha:)"
      ],
      "title": "Creating a Color Using White Components"
    },
    {
      "anchor": "Creating-a-Pattern-Based-Color",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(patternImage:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/patternImage"
      ],
      "title": "Creating a Pattern-Based Color"
    },
    {
      "anchor": "Creating-a-Color-Dynamically",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(name:dynamicProvider:)"
      ],
      "title": "Creating a Color Dynamically"
    },
    {
      "anchor": "Creating-a-Color-in-an-Arbitrary-Color-Space",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:components:count:)"
      ],
      "title": "Creating a Color in an Arbitrary Color Space"
    },
    {
      "anchor": "Creating-a-System-Tint-Color",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSControlTint"
      ],
      "title": "Creating a System Tint Color"
    },
    {
      "anchor": "Converting-Other-Types-of-Color-Objects",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(cgColor:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(CIColor:)"
      ],
      "title": "Converting Other Types of Color Objects"
    },
    {
      "anchor": "Creating-Color-Objects",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init()",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(coder:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/init(resource:)"
      ],
      "title": "Creating Color Objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Loading-Color-Objects-from-Asset-Catalogs",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(named:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(named:bundle:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(catalogName:colorName:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/Name"
              ],
              "title": "Loading Color Objects from Asset Catalogs"
            },
            {
              "anchor": "Creating-a-Color-Using-RGB-Components",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(srgbRed:green:blue:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(displayP3Red:green:blue:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(red:green:blue:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedRed:green:blue:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceRed:green:blue:alpha:)"
              ],
              "title": "Creating a Color Using RGB Components"
            },
            {
              "anchor": "Creating-a-Color-Using-HSB-Components",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedHue:saturation:brightness:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceHue:saturation:brightness:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(hue:saturation:brightness:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:hue:saturation:brightness:alpha:)"
              ],
              "title": "Creating a Color Using HSB Components"
            },
            {
              "anchor": "Creating-a-Color-Using-CMYK-Components",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceCyan:magenta:yellow:black:alpha:)"
              ],
              "title": "Creating a Color Using CMYK Components"
            },
            {
              "anchor": "Creating-a-Color-Using-White-Components",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(white:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(calibratedWhite:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(deviceWhite:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(genericGamma22White:alpha:)"
              ],
              "title": "Creating a Color Using White Components"
            },
            {
              "anchor": "Creating-a-Pattern-Based-Color",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(patternImage:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/patternImage"
              ],
              "title": "Creating a Pattern-Based Color"
            },
            {
              "anchor": "Creating-a-Color-Dynamically",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(name:dynamicProvider:)"
              ],
              "title": "Creating a Color Dynamically"
            },
            {
              "anchor": "Creating-a-Color-in-an-Arbitrary-Color-Space",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:components:count:)"
              ],
              "title": "Creating a Color in an Arbitrary Color Space"
            },
            {
              "anchor": "Creating-a-System-Tint-Color",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSControlTint"
              ],
              "title": "Creating a System Tint Color"
            },
            {
              "anchor": "Converting-Other-Types-of-Color-Objects",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(cgColor:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(CIColor:)"
              ],
              "title": "Converting Other Types of Color Objects"
            },
            {
              "anchor": "Creating-Color-Objects",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init()",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/init(coder:)"
              ],
              "title": "Creating Color Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-and-Creating-Colors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/ui-element-colors",
                "doc://com.apple.appkit/documentation/AppKit/standard-colors"
              ],
              "title": "Getting and Creating Colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(deviceWhite:alpha:)/title",
          "value": "colorWithDeviceWhite:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(deviceWhite:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithDeviceWhite:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(named:)/title",
          "value": "colorNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(named:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(catalogName:colorName:)/title",
          "value": "colorWithCatalogName:colorName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(catalogName:colorName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithCatalogName:colorName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(for:)/title",
          "value": "colorForControlTint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorForControlTint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(named:bundle:)/title",
          "value": "colorNamed:bundle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(named:bundle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorNamed:bundle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(red:green:blue:alpha:)/title",
          "value": "colorWithRed:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(red:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithRed:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(deviceCyan:magenta:yellow:black:alpha:)/title",
          "value": "colorWithDeviceCyan:magenta:yellow:black:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(deviceCyan:magenta:yellow:black:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithDeviceCyan:magenta:yellow:black:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(displayP3Red:green:blue:alpha:)/title",
          "value": "colorWithDisplayP3Red:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(displayP3Red:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithDisplayP3Red:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(CIColor:)/title",
          "value": "colorWithCIColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(CIColor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithCIColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(calibratedHue:saturation:brightness:alpha:)/title",
          "value": "colorWithCalibratedHue:saturation:brightness:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(calibratedHue:saturation:brightness:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithCalibratedHue:saturation:brightness:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(colorSpace:hue:saturation:brightness:alpha:)/title",
          "value": "colorWithColorSpace:hue:saturation:brightness:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(colorSpace:hue:saturation:brightness:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithColorSpace:hue:saturation:brightness:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1patternImage/title",
          "value": "patternImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1patternImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "patternImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(deviceHue:saturation:brightness:alpha:)/title",
          "value": "colorWithDeviceHue:saturation:brightness:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(deviceHue:saturation:brightness:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithDeviceHue:saturation:brightness:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(calibratedWhite:alpha:)/title",
          "value": "colorWithCalibratedWhite:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(calibratedWhite:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithCalibratedWhite:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTint/title",
          "value": "NSControlTint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(patternImage:)/title",
          "value": "colorWithPatternImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(patternImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithPatternImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(srgbRed:green:blue:alpha:)/title",
          "value": "colorWithSRGBRed:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(srgbRed:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithSRGBRed:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1Name/title",
          "value": "NSColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1Name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1Name/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(calibratedRed:green:blue:alpha:)/title",
          "value": "colorWithCalibratedRed:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(calibratedRed:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithCalibratedRed:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(colorSpace:components:count:)/title",
          "value": "colorWithColorSpace:components:count:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(colorSpace:components:count:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithColorSpace:components:count:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(white:alpha:)/title",
          "value": "colorWithWhite:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(white:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithWhite:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(genericGamma22White:alpha:)/title",
          "value": "colorWithGenericGamma22White:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(genericGamma22White:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithGenericGamma22White:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(deviceRed:green:blue:alpha:)/title",
          "value": "colorWithDeviceRed:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(deviceRed:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithDeviceRed:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(hue:saturation:brightness:alpha:)/title",
          "value": "colorWithHue:saturation:brightness:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(hue:saturation:brightness:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithHue:saturation:brightness:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(cgColor:)/title",
          "value": "colorWithCGColor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(cgColor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithCGColor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(name:dynamicProvider:)/title",
          "value": "colorWithName:dynamicProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(name:dynamicProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithName:dynamicProvider:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/color-creation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/color-creation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
