{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/text-display",
        "doc://com.apple.appkit/documentation/AppKit/NSText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/common-unicode-characters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Common Unicode Characters"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBackTabCharacter": {
      "abstract": [
        {
          "text": "The back tab character: ",
          "type": "text"
        },
        {
          "code": "0x0019",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBackTabCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBackTabCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBackTabCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSBackTabCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsbacktabcharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBackspaceCharacter": {
      "abstract": [
        {
          "text": "The backspace character: ",
          "type": "text"
        },
        {
          "code": "0x0008",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBackspaceCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBackspaceCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBackspaceCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSBackspaceCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsbackspacecharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCarriageReturnCharacter": {
      "abstract": [
        {
          "text": "The carriage return character: ",
          "type": "text"
        },
        {
          "code": "0x000d",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCarriageReturnCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCarriageReturnCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCarriageReturnCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSCarriageReturnCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nscarriagereturncharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeleteCharacter": {
      "abstract": [
        {
          "text": "The delete character: ",
          "type": "text"
        },
        {
          "code": "0x007f",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeleteCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeleteCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeleteCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSDeleteCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsdeletecharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEnterCharacter": {
      "abstract": [
        {
          "text": "The enter character: ",
          "type": "text"
        },
        {
          "code": "0x0003",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEnterCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEnterCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEnterCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSEnterCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsentercharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormFeedCharacter": {
      "abstract": [
        {
          "text": "The form feed character: ",
          "type": "text"
        },
        {
          "code": "0x000c",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFormFeedCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormFeedCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFormFeedCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSFormFeedCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsformfeedcharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineSeparatorCharacter": {
      "abstract": [
        {
          "text": "The line separator character: ",
          "type": "text"
        },
        {
          "code": "0x2028",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLineSeparatorCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineSeparatorCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineSeparatorCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSLineSeparatorCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nslineseparatorcharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNewlineCharacter": {
      "abstract": [
        {
          "text": "The newline character: ",
          "type": "text"
        },
        {
          "code": "0x000a",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSNewlineCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNewlineCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNewlineCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSNewlineCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsnewlinecharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphSeparatorCharacter": {
      "abstract": [
        {
          "text": "The paragraph separator character: ",
          "type": "text"
        },
        {
          "code": "0x2029",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSParagraphSeparatorCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphSeparatorCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSParagraphSeparatorCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphSeparatorCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphseparatorcharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabCharacter": {
      "abstract": [
        {
          "text": "The tab character: ",
          "type": "text"
        },
        {
          "code": "0x0009",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTabCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabCharacter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabCharacter"
        }
      ],
      "role": "symbol",
      "title": "NSTabCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nstabcharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSText": {
      "abstract": [
        {
          "text": "The most general programmatic interface for objects that manage text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSText"
        }
      ],
      "role": "symbol",
      "title": "NSText",
      "type": "topic",
      "url": "/documentation/appkit/nstext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection": {
      "abstract": [
        {
          "text": "Constants that specify the writing direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/movement-codes": {
      "abstract": [
        {
          "text": "The reason for a change of editing focus among text fields.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/movement-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Movement Codes",
      "type": "topic",
      "url": "/documentation/appkit/movement-codes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-display": {
      "abstract": [
        {
          "text": "Display text and check spelling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Display",
      "type": "topic",
      "url": "/documentation/appkit/text-display"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection",
        "doc://com.apple.appkit/documentation/AppKit/movement-codes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEnterCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSBackspaceCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSTabCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSNewlineCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSFormFeedCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSCarriageReturnCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSBackTabCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSDeleteCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSLineSeparatorCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphSeparatorCharacter"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEnterCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSBackspaceCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSTabCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSNewlineCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSFormFeedCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSCarriageReturnCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSBackTabCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSDeleteCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSLineSeparatorCharacter",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphSeparatorCharacter"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection",
                "doc://com.apple.appkit/documentation/AppKit/movement-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBackTabCharacter/title",
          "value": "NSBackTabCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBackTabCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBackTabCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCarriageReturnCharacter/title",
          "value": "NSCarriageReturnCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCarriageReturnCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCarriageReturnCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphSeparatorCharacter/title",
          "value": "NSParagraphSeparatorCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphSeparatorCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphSeparatorCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/title",
          "value": "NSTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/title",
          "value": "NSText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormFeedCharacter/title",
          "value": "NSFormFeedCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormFeedCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormFeedCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEnterCharacter/title",
          "value": "NSEnterCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEnterCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEnterCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineSeparatorCharacter/title",
          "value": "NSLineSeparatorCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineSeparatorCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineSeparatorCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBackspaceCharacter/title",
          "value": "NSBackspaceCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBackspaceCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBackspaceCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeleteCharacter/title",
          "value": "NSDeleteCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeleteCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeleteCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabCharacter/title",
          "value": "NSTabCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNewlineCharacter/title",
          "value": "NSNewlineCharacter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNewlineCharacter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNewlineCharacter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/title",
          "value": "NSWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/common-unicode-characters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/common-unicode-characters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
