{
  "abstract": [
    {
      "text": "Constants for use with multiple classes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Constants"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIMAGE_UNAVAILABLE_MACCATALYST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIMAGE_UNAVAILABLE_MACCATALYST"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIMAGE_UNAVAILABLE_MACCATALYST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIMAGE_UNAVAILABLE_MACCATALYST"
        }
      ],
      "role": "symbol",
      "title": "NSIMAGE_UNAVAILABLE_MACCATALYST",
      "type": "topic",
      "url": "/documentation/appkit/nsimage_unavailable_maccatalyst"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS_USER_ACTIVITY_SUPPORTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NS_USER_ACTIVITY_SUPPORTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS_USER_ACTIVITY_SUPPORTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NS_USER_ACTIVITY_SUPPORTED"
        }
      ],
      "role": "symbol",
      "title": "NS_USER_ACTIVITY_SUPPORTED",
      "type": "topic",
      "url": "/documentation/appkit/ns_user_activity_supported"
    },
    "doc://com.apple.appkit/documentation/AppKit/data-types": {
      "abstract": [
        {
          "text": "Data types for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types",
      "type": "topic",
      "url": "/documentation/appkit/data-types"
    },
    "doc://com.apple.appkit/documentation/AppKit/enumerations": {
      "abstract": [
        {
          "text": "Enumerations for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Enumerations",
      "type": "topic",
      "url": "/documentation/appkit/enumerations"
    },
    "doc://com.apple.appkit/documentation/AppKit/exceptions": {
      "abstract": [
        {
          "text": "Constants AppKit uses to name exceptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/exceptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Exceptions",
      "type": "topic",
      "url": "/documentation/appkit/exceptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/macros": {
      "abstract": [
        {
          "text": "Macros for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/appkit/macros"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/enumerations",
        "doc://com.apple.appkit/documentation/AppKit/data-types",
        "doc://com.apple.appkit/documentation/AppKit/macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSIMAGE_UNAVAILABLE_MACCATALYST",
        "doc://com.apple.appkit/documentation/AppKit/NS_USER_ACTIVITY_SUPPORTED"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSIMAGE_UNAVAILABLE_MACCATALYST",
                "doc://com.apple.appkit/documentation/AppKit/NS_USER_ACTIVITY_SUPPORTED"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Exceptions",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/exceptions"
              ],
              "title": "Exceptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/enumerations",
                "doc://com.apple.appkit/documentation/AppKit/data-types",
                "doc://com.apple.appkit/documentation/AppKit/macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NS_USER_ACTIVITY_SUPPORTED/title",
          "value": "NS_USER_ACTIVITY_SUPPORTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NS_USER_ACTIVITY_SUPPORTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NS_USER_ACTIVITY_SUPPORTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIMAGE_UNAVAILABLE_MACCATALYST/title",
          "value": "NSIMAGE_UNAVAILABLE_MACCATALYST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIMAGE_UNAVAILABLE_MACCATALYST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIMAGE_UNAVAILABLE_MACCATALYST"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
