{
  "abstract": [
    {
      "text": "Draw rectangles and other primitive shapes using these convenience functions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/drawing"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/convenience-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Convenience Functions"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath": {
      "abstract": [
        {
          "text": "An object that can create paths using PostScript-style commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawButton(_:_:)": {
      "abstract": [
        {
          "text": "Draws a gray-filled rectangle representing a user-interface button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawButton"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawButton(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawButton"
        }
      ],
      "role": "symbol",
      "title": "NSDrawButton(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawbutton(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawDarkBezel(_:_:)": {
      "abstract": [
        {
          "text": "Draws a dark gray-filled rectangle with a bezel border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawDarkBezel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawDarkBezel(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawDarkBezel"
        }
      ],
      "role": "symbol",
      "title": "NSDrawDarkBezel(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawdarkbezel(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawGrayBezel(_:_:)": {
      "abstract": [
        {
          "text": "Draws a gray-filled rectangle with a bezel border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawGrayBezel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawGrayBezel(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawGrayBezel"
        }
      ],
      "role": "symbol",
      "title": "NSDrawGrayBezel(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawgraybezel(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawGroove(_:_:)": {
      "abstract": [
        {
          "text": "Draws a gray-filled rectangle with a groove border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawGroove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawGroove(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawGroove"
        }
      ],
      "role": "symbol",
      "title": "NSDrawGroove(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawgroove(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawLightBezel(_:_:)": {
      "abstract": [
        {
          "text": "Draws a white-filled rectangle with a bezel border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawLightBezel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawLightBezel(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawLightBezel"
        }
      ],
      "role": "symbol",
      "title": "NSDrawLightBezel(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawlightbezel(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawNinePartImage(_:_:_:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Draws a nine-part tiled image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawNinePartImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCompositingOperation",
          "text": "NSCompositingOperation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawNinePartImage(_:_:_:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawNinePartImage"
        }
      ],
      "role": "symbol",
      "title": "NSDrawNinePartImage(_:_:_:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawninepartimage(_:_:_:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawThreePartImage(_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Draws a three-part tiled image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawThreePartImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCompositingOperation",
          "text": "NSCompositingOperation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawThreePartImage(_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawThreePartImage"
        }
      ],
      "role": "symbol",
      "title": "NSDrawThreePartImage(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawthreepartimage(_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawTiledRects(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Draws rectangles with borders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawTiledRects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSRectEdge",
          "text": "NSRectEdge"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawTiledRects(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawTiledRects"
        }
      ],
      "role": "symbol",
      "title": "NSDrawTiledRects(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawtiledrects(_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawWhiteBezel(_:_:)": {
      "abstract": [
        {
          "text": "Draws a white-filled rectangle with a bezel border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawWhiteBezel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawWhiteBezel(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawWhiteBezel"
        }
      ],
      "role": "symbol",
      "title": "NSDrawWhiteBezel(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawwhitebezel(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawWindowBackground(_:)": {
      "abstract": [
        {
          "text": "Draws the window’s default background pattern into the specified rectangle of the currently focused view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawWindowBackground"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawWindowBackground(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawWindowBackground"
        }
      ],
      "role": "symbol",
      "title": "NSDrawWindowBackground(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawwindowbackground(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEraseRect(_:)": {
      "abstract": [
        {
          "text": "Erases the specified rect by filling it with white.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEraseRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEraseRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEraseRect"
        }
      ],
      "role": "symbol",
      "title": "NSEraseRect(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nseraserect(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFocusRingPlacement": {
      "abstract": [
        {
          "text": "Constants that indicate how the system draws the focus ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFocusRingPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFocusRingPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSFocusRingPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsfocusringplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFocusRingPlacement/set()": {
      "abstract": [
        {
          "text": "Specifies how the system draws the focus ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "set"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingPlacement/set()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSetFocusRingStyle"
        }
      ],
      "role": "symbol",
      "title": "set()",
      "type": "topic",
      "url": "/documentation/appkit/nsfocusringplacement/set()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType": {
      "abstract": [
        {
          "text": "Constants that describe the style of the focus ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFocusRingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFocusRingType"
        }
      ],
      "role": "symbol",
      "title": "NSFocusRingType",
      "type": "topic",
      "url": "/documentation/appkit/nsfocusringtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFrameRect": {
      "abstract": [
        {
          "text": "Draws a bordered rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFrameRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFrameRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFrameRect",
      "type": "topic",
      "url": "/documentation/appkit/nsframerect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidth": {
      "abstract": [
        {
          "text": "Draws a bordered rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFrameRectWithWidth"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidth",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFrameRectWithWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsframerectwithwidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidthUsingOperation": {
      "abstract": [
        {
          "text": "Draws a bordered rectangle using the specified compositing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFrameRectWithWidthUsingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidthUsingOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFrameRectWithWidthUsingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsframerectwithwidthusingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHighlightRect": {
      "abstract": [
        {
          "text": "Highlights the specified rect by filling it with white.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHighlightRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHighlightRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHighlightRect",
      "type": "topic",
      "url": "/documentation/appkit/nshighlightrect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectClip": {
      "abstract": [
        {
          "text": "Modifies the current clipping path by intersecting it with the passed rect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectClip"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectClip",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectClip",
      "type": "topic",
      "url": "/documentation/appkit/nsrectclip"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectClipList": {
      "abstract": [
        {
          "text": "Modifies the current clipping path by intersecting it with the passed rect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectClipList"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectClipList",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectClipList",
      "type": "topic",
      "url": "/documentation/appkit/nsrectcliplist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFill": {
      "abstract": [
        {
          "text": "Fills the passed rectangle with the current color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFill"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFill",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFill",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfill"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillList": {
      "abstract": [
        {
          "text": "Fills the rectangles in the passed list with the current fill color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillList"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillList",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillList",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillListUsingOperation": {
      "abstract": [
        {
          "text": "Fills the rectangles in a list using the current fill color and specified compositing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillListUsingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillListUsingOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillListUsingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllistusingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColors": {
      "abstract": [
        {
          "text": "Fills the rectangles in the passed list with the passed list of colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillListWithColors"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColors",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillListWithColors",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllistwithcolors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColorsUsingOperation": {
      "abstract": [
        {
          "text": "Fills the rectangles in a list using the specified colors and compositing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillListWithColorsUsingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColorsUsingOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillListWithColorsUsingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllistwithcolorsusingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithGrays": {
      "abstract": [
        {
          "text": "Fills the rectangles in the passed list with the passed list of grays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillListWithGrays"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithGrays",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillListWithGrays",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllistwithgrays"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillUsingOperation": {
      "abstract": [
        {
          "text": "Fills a rectangle using the current fill color and the specified compositing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillUsingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillUsingOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillUsingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfillusingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/drawing": {
      "abstract": [
        {
          "text": "Draw shapes, images, and other content on the screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/drawing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawing",
      "type": "topic",
      "url": "/documentation/appkit/drawing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shapes-and-Paths",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath"
      ],
      "title": "Shapes and Paths"
    }
  ],
  "topicSections": [
    {
      "anchor": "Drawing-Rectangles",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEraseRect(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawTiledRects(_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawGroove(_:_:)"
      ],
      "title": "Drawing Rectangles"
    },
    {
      "anchor": "Drawing-Bezels",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDrawDarkBezel(_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawGrayBezel(_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawLightBezel(_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawWhiteBezel(_:_:)"
      ],
      "title": "Drawing Bezels"
    },
    {
      "anchor": "Drawing-Backgrounds",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDrawButton(_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawWindowBackground(_:)"
      ],
      "title": "Drawing Backgrounds"
    },
    {
      "anchor": "Drawing-Multipart-Images",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDrawNinePartImage(_:_:_:_:_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawThreePartImage(_:_:_:_:_:_:_:_:)"
      ],
      "title": "Drawing Multipart Images"
    },
    {
      "anchor": "Drawing-Focus-Rings",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFocusRingPlacement/set()",
        "doc://com.apple.appkit/documentation/AppKit/NSFocusRingPlacement",
        "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType"
      ],
      "title": "Drawing Focus Rings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Drawing-Rectangles",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFrameRect",
                "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidth",
                "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidthUsingOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSEraseRect(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSRectFill",
                "doc://com.apple.appkit/documentation/AppKit/NSRectFillList",
                "doc://com.apple.appkit/documentation/AppKit/NSRectFillListUsingOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColors",
                "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColorsUsingOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithGrays",
                "doc://com.apple.appkit/documentation/AppKit/NSRectFillUsingOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawTiledRects(_:_:_:_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawGroove(_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSHighlightRect"
              ],
              "title": "Drawing Rectangles"
            },
            {
              "anchor": "Drawing-Bezels",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDrawDarkBezel(_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawGrayBezel(_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawLightBezel(_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawWhiteBezel(_:_:)"
              ],
              "title": "Drawing Bezels"
            },
            {
              "anchor": "Drawing-Backgrounds",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDrawButton(_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawWindowBackground(_:)"
              ],
              "title": "Drawing Backgrounds"
            },
            {
              "anchor": "Drawing-Multipart-Images",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDrawNinePartImage(_:_:_:_:_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawThreePartImage(_:_:_:_:_:_:_:_:)"
              ],
              "title": "Drawing Multipart Images"
            },
            {
              "anchor": "Clipping-Rectangles",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSRectClip",
                "doc://com.apple.appkit/documentation/AppKit/NSRectClipList"
              ],
              "title": "Clipping Rectangles"
            },
            {
              "anchor": "Drawing-Focus-Rings",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFocusRingPlacement/set()",
                "doc://com.apple.appkit/documentation/AppKit/NSFocusRingPlacement",
                "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType"
              ],
              "title": "Drawing Focus Rings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shapes-and-Paths",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath"
              ],
              "title": "Shapes and Paths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEraseRect(_:)/title",
          "value": "NSEraseRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEraseRect(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEraseRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title",
          "value": "NSBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingPlacement/title",
          "value": "NSFocusRingPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFocusRingPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingPlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFocusRingPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawThreePartImage(_:_:_:_:_:_:_:_:)/title",
          "value": "NSDrawThreePartImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawThreePartImage(_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawThreePartImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawWindowBackground(_:)/title",
          "value": "NSDrawWindowBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawWindowBackground(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawWindowBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawLightBezel(_:_:)/title",
          "value": "NSDrawLightBezel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawLightBezel(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawLightBezel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawButton(_:_:)/title",
          "value": "NSDrawButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawButton(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawGroove(_:_:)/title",
          "value": "NSDrawGroove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawGroove(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawGroove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawDarkBezel(_:_:)/title",
          "value": "NSDrawDarkBezel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawDarkBezel(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawDarkBezel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawNinePartImage(_:_:_:_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "NSDrawNinePartImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawNinePartImage(_:_:_:_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawNinePartImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawTiledRects(_:_:_:_:_:)/title",
          "value": "NSDrawTiledRects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawTiledRects(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawTiledRects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawGrayBezel(_:_:)/title",
          "value": "NSDrawGrayBezel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawGrayBezel(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawGrayBezel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingType/title",
          "value": "NSFocusRingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFocusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFocusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingPlacement~1set()/title",
          "value": "NSSetFocusRingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingPlacement~1set()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSetFocusRingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawWhiteBezel(_:_:)/title",
          "value": "NSDrawWhiteBezel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawWhiteBezel(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawWhiteBezel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/convenience-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/convenience-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
