{
  "abstract": [
    {
      "text": "Manage the layer object that provides the view’s visual representation and accelerates drawing operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/core-animation-support"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Animation Support"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum": {
      "abstract": [
        {
          "text": "These constants specify the location of the layer content when the content is not rerendered in response to view resizing. For more information, see the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerContentsPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerContentsPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify how layer resizing is handled when a view is layer-backed or layer-hosting. For more information, see the  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsRedrawPolicy",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/alphaValue": {
      "abstract": [
        {
          "text": "The opacity of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/alphaValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alphaValue"
        }
      ],
      "role": "symbol",
      "title": "alphaValue",
      "type": "topic",
      "url": "/documentation/appkit/nsview/alphavalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/backgroundFilters": {
      "abstract": [
        {
          "text": "An array of Core Image filters to apply to the view’s background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundFilters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIFilter",
          "text": "CIFilter"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/backgroundFilters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundFilters"
        }
      ],
      "role": "symbol",
      "title": "backgroundFilters",
      "type": "topic",
      "url": "/documentation/appkit/nsview/backgroundfilters"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/canDrawSubviewsIntoLayer": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view incorporates content from its subviews into its own layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canDrawSubviewsIntoLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/canDrawSubviewsIntoLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canDrawSubviewsIntoLayer"
        }
      ],
      "role": "symbol",
      "title": "canDrawSubviewsIntoLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsview/candrawsubviewsintolayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/compositingFilter": {
      "abstract": [
        {
          "text": "The Core Image filter used to composite the view’s contents with its background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositingFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIFilter",
          "text": "CIFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/compositingFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compositingFilter"
        }
      ],
      "role": "symbol",
      "title": "compositingFilter",
      "type": "topic",
      "url": "/documentation/appkit/nsview/compositingfilter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/contentFilters": {
      "abstract": [
        {
          "text": "An array of Core Image filters to apply to the contents of the view and its sublayers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentFilters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIFilter",
          "text": "CIFilter"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/contentFilters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentFilters"
        }
      ],
      "role": "symbol",
      "title": "contentFilters",
      "type": "topic",
      "url": "/documentation/appkit/nsview/contentfilters"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/frameCenterRotation": {
      "abstract": [
        {
          "text": "The rotation angle of the view around the center of its layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameCenterRotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/frameCenterRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameCenterRotation"
        }
      ],
      "role": "symbol",
      "title": "frameCenterRotation",
      "type": "topic",
      "url": "/documentation/appkit/nsview/framecenterrotation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layer": {
      "abstract": [
        {
          "text": "The Core Animation layer that the view uses as its backing store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layer"
        }
      ],
      "role": "symbol",
      "title": "layer",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property": {
      "abstract": [
        {
          "text": "The current layer contents placement policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerContentsPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSViewLayerContentsPlacement",
          "text": "LayerContentsPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerContentsPlacement"
        }
      ],
      "role": "symbol",
      "title": "layerContentsPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property": {
      "abstract": [
        {
          "text": "The contents redraw policy for the view’s layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerContentsRedrawPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSViewLayerContentsRedrawPolicy",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerContentsRedrawPolicy"
        }
      ],
      "role": "symbol",
      "title": "layerContentsRedrawPolicy",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layerUsesCoreImageFilters": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view’s layer uses Core Image filters and needs in-process rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerUsesCoreImageFilters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerUsesCoreImageFilters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerUsesCoreImageFilters"
        }
      ],
      "role": "symbol",
      "title": "layerUsesCoreImageFilters",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layerusescoreimagefilters"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/makeBackingLayer()": {
      "abstract": [
        {
          "text": "Creates the view’s backing layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeBackingLayer"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/makeBackingLayer()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeBackingLayer"
        }
      ],
      "role": "symbol",
      "title": "makeBackingLayer()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/makebackinglayer()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/shadow": {
      "abstract": [
        {
          "text": "The shadow displayed underneath the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSShadow",
          "text": "NSShadow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/shadow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadow"
        }
      ],
      "role": "symbol",
      "title": "shadow",
      "type": "topic",
      "url": "/documentation/appkit/nsview/shadow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/wantsLayer": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view uses a layer as its backing store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/wantsLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsLayer"
        }
      ],
      "role": "symbol",
      "title": "wantsLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsview/wantslayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/wantsUpdateLayer": {
      "abstract": [
        {
          "text": "A Boolean value indicating which drawing path the view takes when updating its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsUpdateLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/wantsUpdateLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsUpdateLayer"
        }
      ],
      "role": "symbol",
      "title": "wantsUpdateLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsview/wantsupdatelayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewLayerContentScaleDelegate": {
      "abstract": [
        {
          "text": "An optional layer delegate method for handling resolution changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewLayerContentScaleDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewLayerContentScaleDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentScaleDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSViewLayerContentScaleDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsviewlayercontentscaledelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsview-appearance": {
      "abstract": [
        {
          "text": "Change the view’s visibility, vibrancy, and focus ring and respond to appearance-related changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance",
      "type": "topic",
      "url": "/documentation/appkit/nsview-appearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/related-ui": {
      "abstract": [
        {
          "text": "Manage contextual menus, cursors, tool tips, and other system-provided windows and content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/related-ui",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Related UI",
      "type": "topic",
      "url": "/documentation/appkit/related-ui"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-coordinates": {
      "abstract": [
        {
          "text": "Manage the frame and bounds rectangles that determine the size and position of the view in the view hierarchy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Coordinates",
      "type": "topic",
      "url": "/documentation/appkit/view-coordinates"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-hierarchy": {
      "abstract": [
        {
          "text": "Manage the subviews, superview, and window of a view and respond to notifications when the view hierarchy changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Hierarchy",
      "type": "topic",
      "url": "/documentation/appkit/view-hierarchy"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
        "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
        "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
        "doc://com.apple.appkit/documentation/AppKit/related-ui"
      ],
      "title": "Configuring the view"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-the-Views-Layer",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/wantsLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSView/wantsUpdateLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSView/layer",
        "doc://com.apple.appkit/documentation/AppKit/NSView/makeBackingLayer()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSView/canDrawSubviewsIntoLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSView/layerUsesCoreImageFilters",
        "doc://com.apple.appkit/documentation/AppKit/NSViewLayerContentScaleDelegate"
      ],
      "title": "Managing the View’s Layer"
    },
    {
      "anchor": "Managing-Layer-Related-Properties",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/alphaValue",
        "doc://com.apple.appkit/documentation/AppKit/NSView/frameCenterRotation",
        "doc://com.apple.appkit/documentation/AppKit/NSView/backgroundFilters",
        "doc://com.apple.appkit/documentation/AppKit/NSView/compositingFilter",
        "doc://com.apple.appkit/documentation/AppKit/NSView/contentFilters",
        "doc://com.apple.appkit/documentation/AppKit/NSView/shadow"
      ],
      "title": "Managing Layer-Related Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-the-Views-Layer",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/wantsLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSView/wantsUpdateLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSView/layer",
                "doc://com.apple.appkit/documentation/AppKit/NSView/makeBackingLayer()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSView/canDrawSubviewsIntoLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSView/layerUsesCoreImageFilters",
                "doc://com.apple.appkit/documentation/AppKit/NSViewLayerContentScaleDelegate"
              ],
              "title": "Managing the View’s Layer"
            },
            {
              "anchor": "Managing-Layer-Related-Properties",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/alphaValue",
                "doc://com.apple.appkit/documentation/AppKit/NSView/frameCenterRotation",
                "doc://com.apple.appkit/documentation/AppKit/NSView/backgroundFilters",
                "doc://com.apple.appkit/documentation/AppKit/NSView/compositingFilter",
                "doc://com.apple.appkit/documentation/AppKit/NSView/contentFilters",
                "doc://com.apple.appkit/documentation/AppKit/NSView/shadow"
              ],
              "title": "Managing Layer-Related Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-view",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
                "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
                "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
                "doc://com.apple.appkit/documentation/AppKit/related-ui"
              ],
              "title": "Configuring the view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1backgroundFilters/title",
          "value": "backgroundFilters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1backgroundFilters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundFilters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewLayerContentScaleDelegate/title",
          "value": "NSViewLayerContentScaleDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewLayerContentScaleDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentScaleDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewLayerContentScaleDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentScaleDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layer/title",
          "value": "layer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsPlacement-swift.property/title",
          "value": "layerContentsPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsPlacement-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1alphaValue/title",
          "value": "alphaValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1alphaValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alphaValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frameCenterRotation/title",
          "value": "frameCenterRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frameCenterRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frameCenterRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1wantsLayer/title",
          "value": "wantsLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1wantsLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1shadow/title",
          "value": "shadow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1shadow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1canDrawSubviewsIntoLayer/title",
          "value": "canDrawSubviewsIntoLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1canDrawSubviewsIntoLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canDrawSubviewsIntoLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1compositingFilter/title",
          "value": "compositingFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1compositingFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compositingFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1wantsUpdateLayer/title",
          "value": "wantsUpdateLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1wantsUpdateLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsUpdateLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerUsesCoreImageFilters/title",
          "value": "layerUsesCoreImageFilters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerUsesCoreImageFilters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerUsesCoreImageFilters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/title",
          "value": "NSViewLayerContentsPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/title",
          "value": "NSViewLayerContentsRedrawPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsRedrawPolicy-swift.property/title",
          "value": "layerContentsRedrawPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsRedrawPolicy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1makeBackingLayer()/title",
          "value": "makeBackingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1makeBackingLayer()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeBackingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1contentFilters/title",
          "value": "contentFilters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1contentFilters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentFilters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/core-animation-support"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/core-animation-support"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
