{
  "abstract": [
    {
      "text": "Modify the behavior of Writing Tools in standard macOS text views,",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "and adjust your app’s behavior while the feature is active.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/writing-tools"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/customizing-writing-tools-behavior-for-system-views"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Customizing Writing Tools behavior for AppKit views"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes have built-in support for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Writing Tools, but you can customize how the feature works for your interface.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You might choose to change how someone experiences Writing Tools in your app,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or disable the feature for specific types of content. For example, you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "might disable Writing Tools in a view that you use to display code listings.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can also customize the type of content Writing Tools generates for your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "text view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If you create a custom text view, instead of using the standard system",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "views, use the available APIs to add Writing Tools support to your view. For more",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Specifying-the-Writing-Tools-UI-experience-you-want",
          "level": 3,
          "text": "Specifying the Writing Tools UI experience you want",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Writing Tools supports both limited and complete versions of the Writing Tools",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "experience. The limited experience keeps changes in the Writing Tools",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interface until the person approves them. The limited experience displays the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "changes inline with the rest of your view’s content. Both experiences give people",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ability to accept or reject changes, but the complete experience offers a more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interactive way to view those changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To specify the experience you want, change the value in your view’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/writingToolsBehavior",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. The system applies the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "best available experience to views by default, but you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "can specify the experience you prefer in your views. You can also disable the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "feature if you don’t want Writing Tools to be active in your view.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To disable the feature, set the value of this property to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Modify-your-apps-behavior-when-Writing-Tools-is-active",
          "level": 3,
          "text": "Modify your app’s behavior when Writing Tools is active",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "It takes time for the large language models (LLMs) of Writing Tools to suggest",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "changes. It also takes time for someone to review the changes and approve them.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "While those things happen, Writing Tools might make temporary changes to your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view’s content. During that time, disable any app-specific features that might",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interfere with the Writing Tools operation. For example, you might choose to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "disable cloud-based updates of your text while Writing Tools is active.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " you can determine when Writing Tools is active using your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "delegate object. The system calls the delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textViewWritingToolsWillBegin(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method before Writing Tools makes any modifications, and it calls the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textViewWritingToolsDidEnd(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method after incorporating",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "any final changes. Use those methods to turn off any features that might interfere",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with Writing Tools while it’s active.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Specify-ranges-of-text-for-Writing-Tools-to-ignore",
          "level": 3,
          "text": "Specify ranges of text for Writing Tools to ignore",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t want Writing Tools to modify portions of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textView(_:writingToolsIgnoredRangesInEnclosingRange:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method in your delegate. Writing Tools calls that method for each operation, providing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you with the range of text it’s considering. Use your implementation of the method to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "specify any subranges of text you want Writing Tools to ignore. You might use this method",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to prevent Writing Tools from changing code listings, proper names, or direct",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "quotes embedded in the text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextField": {
      "abstract": [
        {
          "text": "Text the user can select or edit to send an action message to a target when the user presses the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "role": "symbol",
      "title": "NSTextField",
      "type": "topic",
      "url": "/documentation/appkit/nstextfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/writingToolsBehavior": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writingToolsBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWritingToolsBehavior",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputTraits/writingToolsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writingToolsBehavior"
        }
      ],
      "role": "symbol",
      "title": "writingToolsBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputtraits/writingtoolsbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textView(_:writingToolsIgnoredRangesInEnclosingRange:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextView",
          "text": "NSTextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "writingToolsIgnoredRangesInEnclosingRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textView(_:writingToolsIgnoredRangesInEnclosingRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:writingToolsIgnoredRangesInEnclosingRange:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:writingToolsIgnoredRangesInEnclosingRange:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextviewdelegate/textview(_:writingtoolsignoredrangesinenclosingrange:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textViewWritingToolsDidEnd(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewWritingToolsDidEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextView",
          "text": "NSTextView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textViewWritingToolsDidEnd(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewWritingToolsDidEnd:"
        }
      ],
      "role": "symbol",
      "title": "textViewWritingToolsDidEnd(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextviewdelegate/textviewwritingtoolsdidend(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textViewWritingToolsWillBegin(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewWritingToolsWillBegin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextView",
          "text": "NSTextView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate/textViewWritingToolsWillBegin(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewWritingToolsWillBegin:"
        }
      ],
      "role": "symbol",
      "title": "textViewWritingToolsWillBegin(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextviewdelegate/textviewwritingtoolswillbegin(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior": {
      "abstract": [
        {
          "text": "Constants that specify the Writing Tools experience for the underlying view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/none": {
      "abstract": [
        {
          "text": "An option to prevent Writing Tools from modifying the text in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehaviorNone"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior.none",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions": {
      "abstract": [
        {
          "text": "Constants to specify what type of content to allow in Writing Tools",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "suggestions or rewrites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsResultOptions",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsresultoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview": {
      "abstract": [
        {
          "text": "Integrate Writing Tools support, including support for inline replacement",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "animations, to your custom text views on macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview",
      "kind": "article",
      "role": "article",
      "title": "Adding Writing Tools support to a custom AppKit view",
      "type": "topic",
      "url": "/documentation/appkit/adding-writing-tools-support-to-a-custom-nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/writing-tools": {
      "abstract": [
        {
          "text": "Add support for Writing Tools to your app’s text views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/writing-tools",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Writing Tools",
      "type": "topic",
      "url": "/documentation/appkit/writing-tools"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
      ],
      "title": "Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
              ],
              "title": "Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate~1textViewWritingToolsDidEnd(_:)/title",
          "value": "textViewWritingToolsDidEnd:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate~1textViewWritingToolsDidEnd(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewWritingToolsDidEnd:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/title",
          "value": "NSWritingToolsResultOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1none/title",
          "value": "NSWritingToolsBehaviorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehaviorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate~1textViewWritingToolsWillBegin(_:)/title",
          "value": "textViewWritingToolsWillBegin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate~1textViewWritingToolsWillBegin(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewWritingToolsWillBegin:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/title",
          "value": "NSWritingToolsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title",
          "value": "NSTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate~1textView(_:writingToolsIgnoredRangesInEnclosingRange:)/title",
          "value": "textView:writingToolsIgnoredRangesInEnclosingRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate~1textView(_:writingToolsIgnoredRangesInEnclosingRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:writingToolsIgnoredRangesInEnclosingRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1writingToolsBehavior/title",
          "value": "writingToolsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputTraits~1writingToolsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "writingToolsBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/customizing-writing-tools-behavior-for-system-views"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/customizing-writing-tools-behavior-for-system-views"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
