{
  "abstract": [
    {
      "text": "A constant that is used by image representations to denote an attribute whose value changes to match the display device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/device-specific-value"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Device-Specific Value"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep": {
      "abstract": [
        {
          "text": "A semiabstract superclass that provides subclasses that you use to draw an image from a particular type of source data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep/bitsPerSample": {
      "abstract": [
        {
          "text": "The number of bits per sample in the object (if the object is a planar image, this property contains the number of bits per sample per plane).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitsPerSample"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/bitsPerSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bitsPerSample"
        }
      ],
      "role": "symbol",
      "title": "bitsPerSample",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep/bitspersample"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep/colorSpaceName": {
      "abstract": [
        {
          "text": "The name of the color space used by the image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpaceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/colorSpaceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSpaceName"
        }
      ],
      "role": "symbol",
      "title": "colorSpaceName",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep/colorspacename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep/hasAlpha": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image data has an alpha channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/hasAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alpha"
        }
      ],
      "role": "symbol",
      "title": "hasAlpha",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep/hasalpha"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep/isOpaque": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image is opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isOpaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/isOpaque",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opaque"
        }
      ],
      "role": "symbol",
      "title": "isOpaque",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep/isopaque"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep/layoutDirection": {
      "abstract": [
        {
          "text": "The layout direction for the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSImageLayoutDirection",
          "text": "LayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/layoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutDirection"
        }
      ],
      "role": "symbol",
      "title": "layoutDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep/layoutdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep/pixelsHigh": {
      "abstract": [
        {
          "text": "The height of the image, measured in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelsHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/pixelsHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelsHigh"
        }
      ],
      "role": "symbol",
      "title": "pixelsHigh",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep/pixelshigh"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep/pixelsWide": {
      "abstract": [
        {
          "text": "The width of the image, measured in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelsWide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/pixelsWide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelsWide"
        }
      ],
      "role": "symbol",
      "title": "pixelsWide",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep/pixelswide"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRepMatchesDevice": {
      "abstract": [
        {
          "text": "A constant indicating that the value of certain attributes, such as the number of colors or bits per sample, will change to match the display device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageRepMatchesDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRepMatchesDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageRepMatchesDevice"
        }
      ],
      "role": "symbol",
      "title": "NSImageRepMatchesDevice",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerepmatchesdevice"
    },
    "doc://com.apple.appkit/documentation/AppKit/images-and-pdf": {
      "abstract": [
        {
          "text": "Create and manage images, in bitmap, PDF, and other formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Images and PDF",
      "type": "topic",
      "url": "/documentation/appkit/images-and-pdf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Information-About-the-Representation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep/bitsPerSample",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep/colorSpaceName",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep/hasAlpha",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep/isOpaque",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep/pixelsHigh",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep/pixelsWide",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep/layoutDirection"
      ],
      "title": "Specifying Information About the Representation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageRepMatchesDevice"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImageRepMatchesDevice"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Information-About-the-Representation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep/bitsPerSample",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep/colorSpaceName",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep/hasAlpha",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep/isOpaque",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep/pixelsHigh",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep/pixelsWide",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep/layoutDirection"
              ],
              "title": "Specifying Information About the Representation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1layoutDirection/title",
          "value": "layoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1layoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1pixelsWide/title",
          "value": "pixelsWide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1pixelsWide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelsWide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1isOpaque/title",
          "value": "opaque"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1isOpaque/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opaque"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1colorSpaceName/title",
          "value": "colorSpaceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1colorSpaceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSpaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1bitsPerSample/title",
          "value": "bitsPerSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1bitsPerSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bitsPerSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/title",
          "value": "NSImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1hasAlpha/title",
          "value": "alpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1hasAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRepMatchesDevice/title",
          "value": "NSImageRepMatchesDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRepMatchesDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRepMatchesDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1pixelsHigh/title",
          "value": "pixelsHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1pixelsHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelsHigh"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/device-specific-value"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/device-specific-value"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
