{
  "abstract": [
    {
      "text": "Keys for constructing an attributed string from data on disk.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/textkit",
        "doc://com.apple.appkit/documentation/AppKit/textkit-string-attributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Document reading option keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these keys when you need to specify a key of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentReadingOptionKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentReadingOptionKey": {
      "abstract": [
        {
          "text": "Options for constructing an attributed string from data you read from disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentReadingOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentReadingOptionKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentReadingOptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumentreadingoptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType": {
      "abstract": [
        {
          "text": "Constants for the document type document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBaseURLDocumentOption": {
      "abstract": [
        {
          "text": "The base URL for HTML documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBaseURLDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBaseURLDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBaseURLDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nsbaseurldocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCharacterEncodingDocumentOption": {
      "abstract": [
        {
          "text": "The string encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCharacterEncodingDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCharacterEncodingDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCharacterEncodingDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nscharacterencodingdocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDefaultAttributesDocumentOption": {
      "abstract": [
        {
          "text": "The default attributes to apply to plain files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultAttributesDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDefaultAttributesDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultAttributesDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nsdefaultattributesdocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentOption": {
      "abstract": [
        {
          "text": "The document type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDocumentTypeDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDocumentTypeDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumenttypedocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFileTypeDocumentOption": {
      "abstract": [
        {
          "text": "The file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFileTypeDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFileTypeDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileTypeDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nsfiletypedocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentOption": {
      "abstract": [
        {
          "text": "The text-scaling mode to associate with the document’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSourceTextScalingDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSourceTextScalingDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nssourcetextscalingdocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTargetTextScalingDocumentOption": {
      "abstract": [
        {
          "text": "The text scaling mode to use after reading the text from disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTargetTextScalingDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTargetTextScalingDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTargetTextScalingDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nstargettextscalingdocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextEncodingNameDocumentOption": {
      "abstract": [
        {
          "text": "The text encoding to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEncodingNameDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextEncodingNameDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEncodingNameDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nstextencodingnamedocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextKit1ListMarkerFormatDocumentOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextKit1ListMarkerFormatDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextKit1ListMarkerFormatDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextKit1ListMarkerFormatDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nstextkit1listmarkerformatdocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey": {
      "abstract": [
        {
          "text": "Constants for the text layout sections document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionKey",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType": {
      "abstract": [
        {
          "text": "Constants that specify the text scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "role": "symbol",
      "title": "NSTextScalingType",
      "type": "topic",
      "url": "/documentation/appkit/nstextscalingtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSizeMultiplierDocumentOption": {
      "abstract": [
        {
          "text": "The scale factor for font sizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextSizeMultiplierDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSizeMultiplierDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextSizeMultiplierDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nstextsizemultiplierdocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTimeoutDocumentOption": {
      "abstract": [
        {
          "text": "The time, in seconds, to wait for a document to finish loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTimeoutDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTimeoutDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTimeoutDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nstimeoutdocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWebPreferencesDocumentOption": {
      "abstract": [
        {
          "text": "A WebPreferences object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWebPreferencesDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWebPreferencesDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWebPreferencesDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nswebpreferencesdocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWebResourceLoadDelegateDocumentOption": {
      "abstract": [
        {
          "text": "An object to serve as the web resource loading delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWebResourceLoadDelegateDocumentOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWebResourceLoadDelegateDocumentOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWebResourceLoadDelegateDocumentOption",
      "type": "topic",
      "url": "/documentation/appkit/nswebresourceloaddelegatedocumentoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/appkit/textkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit-string-attributes": {
      "abstract": [
        {
          "text": "AppKit-specific keys and values for displaying text and managing documents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit-string-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit string attributes",
      "type": "topic",
      "url": "/documentation/appkit/textkit-string-attributes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-document-wide-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
        "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType"
      ],
      "title": "Getting document-wide attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-document-options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBaseURLDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSCharacterEncodingDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSDefaultAttributesDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSFileTypeDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSTextEncodingNameDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSizeMultiplierDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSTimeoutDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSWebPreferencesDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSWebResourceLoadDelegateDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSTextKit1ListMarkerFormatDocumentOption"
      ],
      "title": "Getting the document options"
    },
    {
      "anchor": "Getting-the-font-scaling-options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentOption",
        "doc://com.apple.appkit/documentation/AppKit/NSTargetTextScalingDocumentOption"
      ],
      "title": "Getting the font-scaling options"
    },
    {
      "anchor": "Getting-the-key-type",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentReadingOptionKey"
      ],
      "title": "Getting the key type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/title",
          "value": "NSTextScalingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/document-reading-option-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
