{
  "abstract": [
    {
      "text": "Draw shapes, images, and other content on the screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/drawing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Drawing"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath": {
      "abstract": [
        {
          "text": "An object that can create paths using PostScript-style commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGradient": {
      "abstract": [
        {
          "text": "An object that can draw gradient fill colors",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGradient"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGradient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGradient"
        }
      ],
      "role": "symbol",
      "title": "NSGradient",
      "type": "topic",
      "url": "/documentation/appkit/nsgradient"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext": {
      "abstract": [
        {
          "text": "An object that represents a graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGraphicsContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGraphicsContext"
        }
      ],
      "role": "symbol",
      "title": "NSGraphicsContext",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSShadow": {
      "abstract": [
        {
          "text": "An object you use to specify attributes to create and style a drop shadow during drawing operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSShadow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSShadow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSShadow"
        }
      ],
      "role": "symbol",
      "title": "NSShadow",
      "type": "topic",
      "url": "/documentation/appkit/nsshadow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingContext": {
      "abstract": [
        {
          "text": "An object that manages metrics for drawing attributed strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "role": "symbol",
      "title": "NSStringDrawingContext",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions": {
      "abstract": [
        {
          "text": "Constants that specify the rendering options for drawing a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/color": {
      "abstract": [
        {
          "text": "Represent colors using built-in or custom formats, and give users options for selecting and applying colors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/appkit/color"
    },
    "doc://com.apple.appkit/documentation/AppKit/convenience-functions": {
      "abstract": [
        {
          "text": "Draw rectangles and other primitive shapes using these convenience functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/convenience-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Convenience Functions",
      "type": "topic",
      "url": "/documentation/appkit/convenience-functions"
    },
    "doc://com.apple.appkit/documentation/AppKit/images-and-pdf": {
      "abstract": [
        {
          "text": "Create and manage images, in bitmap, PDF, and other formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Images and PDF",
      "type": "topic",
      "url": "/documentation/appkit/images-and-pdf"
    },
    "doc://com.apple.appkit/documentation/AppKit/printing": {
      "abstract": [
        {
          "text": "Display the system print panels and manage the printing process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/printing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Printing",
      "type": "topic",
      "url": "/documentation/appkit/printing"
    },
    "doc://com.apple.documentation/documentation/UIKit/NSStringDrawingOptions": {
      "abstract": [
        {
          "text": "Constants that specify the rendering options for drawing a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/NSStringDrawingOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingOptions",
      "type": "topic",
      "url": "/documentation/UIKit/NSStringDrawingOptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphics-Drawing-Color-and-Printing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
        "doc://com.apple.appkit/documentation/AppKit/color",
        "doc://com.apple.appkit/documentation/AppKit/printing"
      ],
      "title": "Graphics, Drawing, Color, and Printing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Drawing-Contexts",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"
      ],
      "title": "Drawing Contexts"
    },
    {
      "anchor": "Shapes-and-Paths",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
        "doc://com.apple.appkit/documentation/AppKit/convenience-functions"
      ],
      "title": "Shapes and Paths"
    },
    {
      "anchor": "Strings",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingContext",
        "doc://com.apple.documentation/documentation/UIKit/NSStringDrawingOptions"
      ],
      "title": "Strings"
    },
    {
      "anchor": "Gradients",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGradient"
      ],
      "title": "Gradients"
    },
    {
      "anchor": "Shadows",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSShadow"
      ],
      "title": "Shadows"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Drawing-Contexts",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext"
              ],
              "title": "Drawing Contexts"
            },
            {
              "anchor": "Shapes-and-Paths",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
                "doc://com.apple.appkit/documentation/AppKit/convenience-functions"
              ],
              "title": "Shapes and Paths"
            },
            {
              "anchor": "Strings",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingContext",
                "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions"
              ],
              "title": "Strings"
            },
            {
              "anchor": "Gradients",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGradient"
              ],
              "title": "Gradients"
            },
            {
              "anchor": "Shadows",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSShadow"
              ],
              "title": "Shadows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphics-Drawing-Color-and-Printing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
                "doc://com.apple.appkit/documentation/AppKit/color",
                "doc://com.apple.appkit/documentation/AppKit/printing"
              ],
              "title": "Graphics, Drawing, Color, and Printing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGradient/title",
          "value": "NSGradient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGradient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGradient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/title",
          "value": "NSGraphicsContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGraphicsContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGraphicsContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title",
          "value": "NSBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStringDrawingContext/title",
          "value": "NSStringDrawingContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStringDrawingContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStringDrawingContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1NSStringDrawingOptions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSStringDrawingOptions"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSShadow/title",
          "value": "NSShadow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSShadow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSShadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSShadow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSShadow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/drawing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/drawing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
