{
  "abstract": [
    {
      "text": "Enumerations for use with multiple classes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Enumerations"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition": {
      "abstract": [
        {
          "text": "The position along the perimeter of a rectangular frame (its edges and corners) from which it’s resized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FrameResizePosition"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections": {
      "abstract": [
        {
          "text": "The directions in which a rectangular frame can be resized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizeDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorFrameResizeDirections",
      "type": "topic",
      "url": "/documentation/appkit/nscursorframeresizedirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection": {
      "abstract": [
        {
          "text": "An absolute direction on the horizontal axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHorizontalDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHorizontalDirection"
        }
      ],
      "role": "symbol",
      "title": "NSHorizontalDirection",
      "type": "topic",
      "url": "/documentation/appkit/nshorizontaldirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections": {
      "abstract": [
        {
          "text": "The absolute directions on the horizontal axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHorizontalDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHorizontalDirections",
      "type": "topic",
      "url": "/documentation/appkit/nshorizontaldirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange": {
      "abstract": [
        {
          "text": "Describes how High Dynamic Range (HDR) image content displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DynamicRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DynamicRange"
        }
      ],
      "role": "symbol",
      "title": "NSImage.DynamicRange",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dynamicrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode": {
      "abstract": [
        {
          "text": "Represents the types of sharing (collaborating on an item vs. sending a copy of the item)",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "The share picker supports up to two modes, each of which corresponds to one of these types",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingCollaborationMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingCollaborationMode"
        }
      ],
      "role": "symbol",
      "title": "NSSharingCollaborationMode",
      "type": "topic",
      "url": "/documentation/appkit/nssharingcollaborationmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection": {
      "abstract": [
        {
          "text": "A direction on the vertical axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSVerticalDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVerticalDirection"
        }
      ],
      "role": "symbol",
      "title": "NSVerticalDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsverticaldirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections": {
      "abstract": [
        {
          "text": "The directions on the vertical axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSVerticalDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSVerticalDirections",
      "type": "topic",
      "url": "/documentation/appkit/nsverticaldirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior": {
      "abstract": [
        {
          "text": "Constants that specify the Writing Tools experience for the underlying view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions": {
      "abstract": [
        {
          "text": "Constants to specify what type of content to allow in Writing Tools",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "suggestions or rewrites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsResultOptions",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsresultoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/constants": {
      "abstract": [
        {
          "text": "Constants for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Constants",
      "type": "topic",
      "url": "/documentation/appkit/constants"
    },
    "doc://com.apple.appkit/documentation/AppKit/data-types": {
      "abstract": [
        {
          "text": "Data types for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types",
      "type": "topic",
      "url": "/documentation/appkit/data-types"
    },
    "doc://com.apple.appkit/documentation/AppKit/macros": {
      "abstract": [
        {
          "text": "Macros for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Macros",
      "type": "topic",
      "url": "/documentation/appkit/macros"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/constants",
        "doc://com.apple.appkit/documentation/AppKit/data-types",
        "doc://com.apple.appkit/documentation/AppKit/macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition",
        "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
        "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition",
                "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
                "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/constants",
                "doc://com.apple.appkit/documentation/AppKit/data-types",
                "doc://com.apple.appkit/documentation/AppKit/macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/title",
          "value": "NSWritingToolsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/title",
          "value": "NSImageDynamicRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/title",
          "value": "NSSharingCollaborationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/title",
          "value": "NSCursorFrameResizePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/title",
          "value": "NSTextCursorAccessoryPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/title",
          "value": "NSWritingToolsResultOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
