{
  "abstract": [
    {
      "text": "In addition to communicating search strings via the find pasteboard, the standard Find panel for ",
      "type": "text"
    },
    {
      "code": "NSTextView",
      "type": "codeVoice"
    },
    {
      "text": " also communicates search option metadata, including case sensitivity and substring matching options. This metadata is stored in a property list as the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " value on the global find pasteboard. As such, third party applications may store additional keys in this property list to communicate additional metadata as desired to support the various search options common to many third-party applications’ Find panels.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/text-display",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/find-panel-search-metadata"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Find Panel Search Metadata"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFindPanelAction": {
      "abstract": [
        {
          "text": "These constants define the tags for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/performFindPanelAction(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFindPanelAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFindPanelAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFindPanelAction"
        }
      ],
      "role": "symbol",
      "title": "NSFindPanelAction",
      "type": "topic",
      "url": "/documentation/appkit/nsfindpanelaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFindPanelSubstringMatchType": {
      "abstract": [
        {
          "text": "The type of substring matching used by the Find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFindPanelSubstringMatchType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFindPanelSubstringMatchType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFindPanelSubstringMatchType"
        }
      ],
      "role": "symbol",
      "title": "NSFindPanelSubstringMatchType",
      "type": "topic",
      "url": "/documentation/appkit/nsfindpanelsubstringmatchtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/FindPanelSearchOptionKey/findPanelCaseInsensitiveSearch": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the search is case-insensitive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findPanelCaseInsensitiveSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardTypeFindPanelSearchOptionKey",
          "text": "FindPanelSearchOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/FindPanelSearchOptionKey/findPanelCaseInsensitiveSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFindPanelCaseInsensitiveSearch"
        }
      ],
      "role": "symbol",
      "title": "findPanelCaseInsensitiveSearch",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/findpanelsearchoptionkey/findpanelcaseinsensitivesearch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/FindPanelSearchOptionKey/findPanelSubstringMatch": {
      "abstract": [
        {
          "text": "A number object containing the match type to use in the find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findPanelSubstringMatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardTypeFindPanelSearchOptionKey",
          "text": "FindPanelSearchOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/FindPanelSearchOptionKey/findPanelSubstringMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFindPanelSubstringMatch"
        }
      ],
      "role": "symbol",
      "title": "findPanelSubstringMatch",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/findpanelsearchoptionkey/findpanelsubstringmatch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions": {
      "abstract": [
        {
          "text": "Type for the find panel metadata property list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findPanelSearchOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFindPanelSearchOptionsPboardType"
        }
      ],
      "role": "symbol",
      "title": "findPanelSearchOptions",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/findpanelsearchoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSelectionAffinity": {
      "abstract": [
        {
          "text": "These constants specify the preferred direction of selection. They’re used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionAffinity",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/setSelectedRange(_:affinity:stillSelecting:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSelectionAffinity"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSelectionAffinity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSelectionAffinity"
        }
      ],
      "role": "symbol",
      "title": "NSSelectionAffinity",
      "type": "topic",
      "url": "/documentation/appkit/nsselectionaffinity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSelectionGranularity": {
      "abstract": [
        {
          "text": "These constants specify how much the text view extends the selection when the user drags the mouse. They’re used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionGranularity",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionRange(forProposedRange:granularity:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ":",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSelectionGranularity"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSelectionGranularity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSelectionGranularity"
        }
      ],
      "role": "symbol",
      "title": "NSSelectionGranularity",
      "type": "topic",
      "url": "/documentation/appkit/nsselectiongranularity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/performFindPanelAction(_:)": {
      "abstract": [
        {
          "text": "Performs a find panel action specified by the sender’s tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performFindPanelAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/performFindPanelAction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performFindPanelAction:"
        }
      ],
      "role": "symbol",
      "title": "performFindPanelAction(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/performfindpanelaction(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionAffinity": {
      "abstract": [
        {
          "text": "The preferred direction of selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionAffinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSelectionAffinity",
          "text": "NSSelectionAffinity"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionAffinity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionAffinity"
        }
      ],
      "role": "symbol",
      "title": "selectionAffinity",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/selectionaffinity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionGranularity": {
      "abstract": [
        {
          "text": "The selection granularity for subsequent extension of a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionGranularity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSelectionGranularity",
          "text": "NSSelectionGranularity"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionGranularity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionGranularity"
        }
      ],
      "role": "symbol",
      "title": "selectionGranularity",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/selectiongranularity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionRange(forProposedRange:granularity:)": {
      "abstract": [
        {
          "text": "Returns an adjusted selected range based on the selection granularity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProposedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "granularity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSelectionGranularity",
          "text": "NSSelectionGranularity"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/selectionRange(forProposedRange:granularity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionRangeForProposedRange:granularity:"
        }
      ],
      "role": "symbol",
      "title": "selectionRange(forProposedRange:granularity:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/selectionrange(forproposedrange:granularity:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView/setSelectedRange(_:affinity:stillSelecting:)": {
      "abstract": [
        {
          "text": "Sets the selection to a range of characters in response to user action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSelectedRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "affinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSelectionAffinity",
          "text": "NSSelectionAffinity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "stillSelecting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView/setSelectedRange(_:affinity:stillSelecting:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSelectedRange:affinity:stillSelecting:"
        }
      ],
      "role": "symbol",
      "title": "setSelectedRange(_:affinity:stillSelecting:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextview/setselectedrange(_:affinity:stillselecting:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/input-sources-locale-identifiers": {
      "abstract": [
        {
          "text": "Locale identifiers represent the input sources available.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/input-sources-locale-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input Sources Locale Identifiers",
      "type": "topic",
      "url": "/documentation/appkit/input-sources-locale-identifiers"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-display": {
      "abstract": [
        {
          "text": "Display text and check spelling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Display",
      "type": "topic",
      "url": "/documentation/appkit/text-display"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSelectionGranularity",
        "doc://com.apple.appkit/documentation/AppKit/NSSelectionAffinity",
        "doc://com.apple.appkit/documentation/AppKit/NSFindPanelAction",
        "doc://com.apple.appkit/documentation/AppKit/input-sources-locale-identifiers",
        "doc://com.apple.appkit/documentation/AppKit/NSFindPanelSubstringMatchType"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/FindPanelSearchOptionKey/findPanelCaseInsensitiveSearch",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/FindPanelSearchOptionKey/findPanelSubstringMatch"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/findPanelSearchOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/FindPanelSearchOptionKey/findPanelCaseInsensitiveSearch",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/FindPanelSearchOptionKey/findPanelSubstringMatch"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSelectionGranularity",
                "doc://com.apple.appkit/documentation/AppKit/NSSelectionAffinity",
                "doc://com.apple.appkit/documentation/AppKit/NSFindPanelAction",
                "doc://com.apple.appkit/documentation/AppKit/input-sources-locale-identifiers",
                "doc://com.apple.appkit/documentation/AppKit/NSFindPanelSubstringMatchType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1FindPanelSearchOptionKey~1findPanelSubstringMatch/title",
          "value": "NSFindPanelSubstringMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1FindPanelSearchOptionKey~1findPanelSubstringMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFindPanelSubstringMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1performFindPanelAction(_:)/title",
          "value": "performFindPanelAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1performFindPanelAction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performFindPanelAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1selectionRange(forProposedRange:granularity:)/title",
          "value": "selectionRangeForProposedRange:granularity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1selectionRange(forProposedRange:granularity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectionRangeForProposedRange:granularity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1selectionGranularity/title",
          "value": "selectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1selectionGranularity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1findPanelSearchOptions/title",
          "value": "NSFindPanelSearchOptionsPboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1findPanelSearchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFindPanelSearchOptionsPboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1selectionAffinity/title",
          "value": "selectionAffinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1selectionAffinity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionAffinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1FindPanelSearchOptionKey~1findPanelCaseInsensitiveSearch/title",
          "value": "NSFindPanelCaseInsensitiveSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1FindPanelSearchOptionKey~1findPanelCaseInsensitiveSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFindPanelCaseInsensitiveSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setSelectedRange(_:affinity:stillSelecting:)/title",
          "value": "setSelectedRange:affinity:stillSelecting:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView~1setSelectedRange(_:affinity:stillSelecting:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setSelectedRange:affinity:stillSelecting:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSelectionGranularity/title",
          "value": "NSSelectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSelectionGranularity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSelectionGranularity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFindPanelSubstringMatchType/title",
          "value": "NSFindPanelSubstringMatchType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFindPanelSubstringMatchType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFindPanelSubstringMatchType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFindPanelSubstringMatchType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFindPanelSubstringMatchType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSelectionAffinity/title",
          "value": "NSSelectionAffinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSelectionAffinity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSelectionAffinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSelectionAffinity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSelectionAffinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFindPanelAction/title",
          "value": "NSFindPanelAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFindPanelAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFindPanelAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFindPanelAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFindPanelAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/find-panel-search-metadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/find-panel-search-metadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
