{
  "abstract": [
    {
      "text": "Manage the fonts used to display text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/fonts"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Fonts"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes encapsulate and manage font families, sizes, and variations. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class defines a single object for each distinct font; for efficiency, these objects, which can be rather large, are shared by all the objects in your app. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class defines the font specification panel that’s presented to the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont": {
      "abstract": [
        {
          "text": "The representation of a font in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "role": "symbol",
      "title": "NSFont",
      "type": "topic",
      "url": "/documentation/appkit/nsfont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontAssetRequest"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAssetRequest"
        }
      ],
      "role": "symbol",
      "title": "NSFontAssetRequest",
      "type": "topic",
      "url": "/documentation/appkit/nsfontassetrequest"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection": {
      "abstract": [
        {
          "text": "A font collection, which is a group of font descriptors taken together as a single object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontCollection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCollection"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollection",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionOptions": {
      "abstract": [
        {
          "text": "Constants that support font collection management.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontCollectionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCollectionOptions"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollectionOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollectionoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor": {
      "abstract": [
        {
          "text": "A dictionary of attributes that describe a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct": {
      "abstract": [
        {
          "text": "A symbolic description of the stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.SymbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass": {
      "abstract": [
        {
          "text": "Constants that classify certain stylistic qualities of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontFamilyClass"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFamilyClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontFamilyClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontfamilyclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontManager": {
      "abstract": [
        {
          "text": "The center of activity for the font-conversion system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontManager"
        }
      ],
      "role": "symbol",
      "title": "NSFontManager",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel": {
      "abstract": [
        {
          "text": "The Font panel—a user interface object that displays a list of available fonts, letting the user preview them and change the font used to display text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanel"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits": {
      "abstract": [
        {
          "text": "A symbolic description of stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "NSFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontsymbolictraits"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask": {
      "abstract": [
        {
          "text": "Constants for isolating specific traits of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontTraitMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection": {
      "abstract": [
        {
          "text": "A mutable collection of font descriptors taken together as a single object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMutableFontCollection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMutableFontCollection"
        }
      ],
      "role": "symbol",
      "title": "NSMutableFontCollection",
      "type": "topic",
      "url": "/documentation/appkit/nsmutablefontcollection"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-display": {
      "abstract": [
        {
          "text": "Display text and check spelling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Display",
      "type": "topic",
      "url": "/documentation/appkit/text-display"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/appkit/textkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/writing-tools": {
      "abstract": [
        {
          "text": "Add support for Writing Tools to your app’s text views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/writing-tools",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Writing Tools",
      "type": "topic",
      "url": "/documentation/appkit/writing-tools"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/text-display",
        "doc://com.apple.appkit/documentation/AppKit/textkit",
        "doc://com.apple.appkit/documentation/AppKit/writing-tools"
      ],
      "title": "Text"
    }
  ],
  "topicSections": [
    {
      "anchor": "Font-Data",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits"
      ],
      "title": "Font Data"
    },
    {
      "anchor": "Management",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontManager",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionOptions"
      ],
      "title": "Management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Font-Data",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFont",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits"
              ],
              "title": "Font Data"
            },
            {
              "anchor": "Management",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontManager",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionOptions"
              ],
              "title": "Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/text-display",
                "doc://com.apple.appkit/documentation/AppKit/textkit",
                "doc://com.apple.appkit/documentation/AppKit/writing-tools"
              ],
              "title": "Text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/title",
          "value": "NSFontAssetRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAssetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAssetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection/title",
          "value": "NSFontCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager/title",
          "value": "NSFontManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionOptions/title",
          "value": "NSFontCollectionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableFontCollection/title",
          "value": "NSMutableFontCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableFontCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableFontCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/title",
          "value": "NSFontDescriptorSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title",
          "value": "NSFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/title",
          "value": "NSFontFamilyClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/title",
          "value": "NSFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/title",
          "value": "NSFontPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/title",
          "value": "NSFontTraitMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/title",
          "value": "NSFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTraits"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/fonts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/fonts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
