{
  "abstract": [
    {
      "text": "Encapsulate your app’s event-handling logic in gesture recognizers so that you can reuse that code throughout your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/gestures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Gestures"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSClickGestureRecognizer": {
      "abstract": [
        {
          "text": "A discrete gesture recognizer that tracks a specified number of mouse clicks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSClickGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSClickGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSClickGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "NSClickGestureRecognizer",
      "type": "topic",
      "url": "/documentation/appkit/nsclickgesturerecognizer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGestureRecognizer": {
      "abstract": [
        {
          "text": "An object that monitors events and calls its action method when a predefined sequence of events occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "NSGestureRecognizer",
      "type": "topic",
      "url": "/documentation/appkit/nsgesturerecognizer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGestureRecognizerDelegate": {
      "abstract": [
        {
          "text": "A set of methods for fine-tuning a gesture recognizer’s behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGestureRecognizerDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGestureRecognizerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGestureRecognizerDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSGestureRecognizerDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsgesturerecognizerdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMagnificationGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that tracks a pinch gesture that magnifies content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMagnificationGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMagnificationGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMagnificationGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "NSMagnificationGestureRecognizer",
      "type": "topic",
      "url": "/documentation/appkit/nsmagnificationgesturerecognizer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPanGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer for panning gestures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPanGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPanGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPanGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "NSPanGestureRecognizer",
      "type": "topic",
      "url": "/documentation/appkit/nspangesturerecognizer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPressGestureRecognizer": {
      "abstract": [
        {
          "text": "A discrete gesture recognizer that tracks whether the user holds down a mouse button for a minimum amount of time before releasing it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPressGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPressGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPressGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "NSPressGestureRecognizer",
      "type": "topic",
      "url": "/documentation/appkit/nspressgesturerecognizer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRotationGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that tracks two trackpad touches moving opposite each other in a circular motion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRotationGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRotationGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRotationGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "NSRotationGestureRecognizer",
      "type": "topic",
      "url": "/documentation/appkit/nsrotationgesturerecognizer"
    },
    "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit": {
      "abstract": [
        {
          "text": "Make your AppKit apps accessible to everyone who uses macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for AppKit",
      "type": "topic",
      "url": "/documentation/appkit/accessibility-for-appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/drag-and-drop": {
      "abstract": [
        {
          "text": "Support the direct manipulation of your app’s content using drag and drop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag and Drop",
      "type": "topic",
      "url": "/documentation/appkit/drag-and-drop"
    },
    "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock": {
      "abstract": [
        {
          "text": "Implement menus and cursors to facilitate interactions with your app, and use your app’s Dock tile to convey updated information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Menus, Cursors, and the Dock",
      "type": "topic",
      "url": "/documentation/appkit/menus-cursors-and-the-dock"
    },
    "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad": {
      "abstract": [
        {
          "text": "Handle events related to mouse, keyboard, and trackpad input.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mouse, Keyboard, and Trackpad",
      "type": "topic",
      "url": "/documentation/appkit/mouse-keyboard-and-trackpad"
    },
    "doc://com.apple.appkit/documentation/AppKit/touch-bar": {
      "abstract": [
        {
          "text": "Display interactive content and controls in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/touch-bar",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Touch Bar",
      "type": "topic",
      "url": "/documentation/appkit/touch-bar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-Interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
        "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
        "doc://com.apple.appkit/documentation/AppKit/touch-bar",
        "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
        "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit"
      ],
      "title": "User Interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Standard-Gestures",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSClickGestureRecognizer",
        "doc://com.apple.appkit/documentation/AppKit/NSPressGestureRecognizer",
        "doc://com.apple.appkit/documentation/AppKit/NSPanGestureRecognizer",
        "doc://com.apple.appkit/documentation/AppKit/NSRotationGestureRecognizer",
        "doc://com.apple.appkit/documentation/AppKit/NSMagnificationGestureRecognizer"
      ],
      "title": "Standard Gestures"
    },
    {
      "anchor": "Custom-Gestures",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGestureRecognizer",
        "doc://com.apple.appkit/documentation/AppKit/NSGestureRecognizerDelegate"
      ],
      "title": "Custom Gestures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Standard-Gestures",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSClickGestureRecognizer",
                "doc://com.apple.appkit/documentation/AppKit/NSPressGestureRecognizer",
                "doc://com.apple.appkit/documentation/AppKit/NSPanGestureRecognizer",
                "doc://com.apple.appkit/documentation/AppKit/NSRotationGestureRecognizer",
                "doc://com.apple.appkit/documentation/AppKit/NSMagnificationGestureRecognizer"
              ],
              "title": "Standard Gestures"
            },
            {
              "anchor": "Custom-Gestures",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGestureRecognizer",
                "doc://com.apple.appkit/documentation/AppKit/NSGestureRecognizerDelegate"
              ],
              "title": "Custom Gestures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-Interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
                "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
                "doc://com.apple.appkit/documentation/AppKit/touch-bar",
                "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
                "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit"
              ],
              "title": "User Interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRotationGestureRecognizer/title",
          "value": "NSRotationGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRotationGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRotationGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRotationGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRotationGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGestureRecognizerDelegate/title",
          "value": "NSGestureRecognizerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGestureRecognizerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGestureRecognizerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGestureRecognizerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGestureRecognizerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSClickGestureRecognizer/title",
          "value": "NSClickGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSClickGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSClickGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSClickGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSClickGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPressGestureRecognizer/title",
          "value": "NSPressGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPressGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPressGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPressGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanGestureRecognizer/title",
          "value": "NSPanGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMagnificationGestureRecognizer/title",
          "value": "NSMagnificationGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMagnificationGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMagnificationGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMagnificationGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMagnificationGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGestureRecognizer/title",
          "value": "NSGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGestureRecognizer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/gestures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/gestures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
