{
  "abstract": [
    {
      "text": "Create and manage images, in bitmap, PDF, and other formats.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/images-and-pdf"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Images and PDF"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep": {
      "abstract": [
        {
          "text": "An object that renders an image from bitmap data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBitmapImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSBitmapImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCIImageRep": {
      "abstract": [
        {
          "text": "An object that can render an image from a Core Image object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCIImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCIImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCIImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSCIImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsciimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCustomImageRep": {
      "abstract": [
        {
          "text": "An object that uses a delegate object to render an image from a custom format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCustomImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCustomImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCustomImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSCustomImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nscustomimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEPSImageRep": {
      "abstract": [
        {
          "text": "An object that can render an image from encapsulated PostScript (EPS) code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEPSImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEPSImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEPSImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSEPSImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsepsimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that you can use to respond to drawing failures and manage incremental loads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSImageDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep": {
      "abstract": [
        {
          "text": "A semiabstract superclass that provides subclasses that you use to draw an image from a particular type of source data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPDFImageRep": {
      "abstract": [
        {
          "text": "An object that can render an image from a PDF format data stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPDFImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPDFImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPDFImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSPDFImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nspdfimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPDFInfo": {
      "abstract": [
        {
          "text": "An object that stores information associated with the creation of a PDF file, such as its URL, tag names, page orientation, and paper size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPDFInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPDFInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPDFInfo"
        }
      ],
      "role": "symbol",
      "title": "NSPDFInfo",
      "type": "topic",
      "url": "/documentation/appkit/nspdfinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPICTImageRep": {
      "abstract": [
        {
          "text": "An object that renders an image from a PICT format data stream of version 1, version 2, and extended version 2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPICTImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPICTImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPICTImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSPICTImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nspictimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/applying-apple-hdr-effect-to-your-photos": {
      "abstract": [
        {
          "text": "You can decode and apply Apple’s HDR gain map to your own images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/applying-apple-hdr-effect-to-your-photos",
      "kind": "article",
      "role": "article",
      "title": "Applying Apple HDR effect to your photos",
      "type": "topic",
      "url": "/documentation/appkit/applying-apple-hdr-effect-to-your-photos"
    },
    "doc://com.apple.appkit/documentation/AppKit/color": {
      "abstract": [
        {
          "text": "Represent colors using built-in or custom formats, and give users options for selecting and applying colors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/appkit/color"
    },
    "doc://com.apple.appkit/documentation/AppKit/drawing": {
      "abstract": [
        {
          "text": "Draw shapes, images, and other content on the screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/drawing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawing",
      "type": "topic",
      "url": "/documentation/appkit/drawing"
    },
    "doc://com.apple.appkit/documentation/AppKit/printing": {
      "abstract": [
        {
          "text": "Display the system print panels and manage the printing process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/printing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Printing",
      "type": "topic",
      "url": "/documentation/appkit/printing"
    },
    "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app": {
      "abstract": [
        {
          "text": "Incorporate scanned documents and pictures from a user’s iPhone, iPad, or iPod touch into your Mac app using Continuity Camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting Continuity Camera in Your Mac App",
      "type": "topic",
      "url": "/documentation/appkit/supporting-continuity-camera-in-your-mac-app"
    },
    "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances": {
      "abstract": [
        {
          "text": "Supply image resources appropriate for light and dark appearances and for high-contrast environments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances",
      "kind": "article",
      "role": "article",
      "title": "Providing images for different appearances",
      "type": "topic",
      "url": "/documentation/UIKit/providing-images-for-different-appearances"
    },
    "doc://com.apple.documentation/documentation/UIKit/supporting-hdr-images-in-your-app": {
      "abstract": [
        {
          "text": "​ Load, display, edit, and save HDR images using SwiftUI and Core Image. ​",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/supporting-hdr-images-in-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting HDR images in your app",
      "type": "topic",
      "url": "/documentation/UIKit/supporting-hdr-images-in-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphics-Drawing-Color-and-Printing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/drawing",
        "doc://com.apple.appkit/documentation/AppKit/color",
        "doc://com.apple.appkit/documentation/AppKit/printing"
      ],
      "title": "Graphics, Drawing, Color, and Printing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Images",
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances",
        "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app",
        "doc://com.apple.documentation/documentation/UIKit/supporting-hdr-images-in-your-app",
        "doc://com.apple.appkit/documentation/AppKit/applying-apple-hdr-effect-to-your-photos",
        "doc://com.apple.appkit/documentation/AppKit/NSImage",
        "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep"
      ],
      "title": "Images"
    },
    {
      "anchor": "Bitmap-Formats",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
        "doc://com.apple.appkit/documentation/AppKit/NSCIImageRep",
        "doc://com.apple.appkit/documentation/AppKit/NSPICTImageRep"
      ],
      "title": "Bitmap Formats"
    },
    {
      "anchor": "Vector-Formats",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPDFImageRep",
        "doc://com.apple.appkit/documentation/AppKit/NSPDFInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSEPSImageRep"
      ],
      "title": "Vector Formats"
    },
    {
      "anchor": "Custom-Formats",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCustomImageRep"
      ],
      "title": "Custom Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Images",
              "identifiers": [
                "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances",
                "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app",
                "doc://com.apple.documentation/documentation/UIKit/supporting-hdr-images-in-your-app",
                "doc://com.apple.appkit/documentation/AppKit/applying-apple-hdr-effect-to-your-photos",
                "doc://com.apple.appkit/documentation/AppKit/NSImage",
                "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep"
              ],
              "title": "Images"
            },
            {
              "anchor": "Bitmap-Formats",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
                "doc://com.apple.appkit/documentation/AppKit/NSCIImageRep",
                "doc://com.apple.appkit/documentation/AppKit/NSPICTImageRep"
              ],
              "title": "Bitmap Formats"
            },
            {
              "anchor": "Vector-Formats",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPDFImageRep",
                "doc://com.apple.appkit/documentation/AppKit/NSPDFInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSEPSImageRep"
              ],
              "title": "Vector Formats"
            },
            {
              "anchor": "Custom-Formats",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCustomImageRep"
              ],
              "title": "Custom Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphics-Drawing-Color-and-Printing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/drawing",
                "doc://com.apple.appkit/documentation/AppKit/color",
                "doc://com.apple.appkit/documentation/AppKit/printing"
              ],
              "title": "Graphics, Drawing, Color, and Printing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPICTImageRep/title",
          "value": "NSPICTImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPICTImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPICTImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPICTImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPICTImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFInfo/title",
          "value": "NSPDFInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPDFInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPDFInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFImageRep/title",
          "value": "NSPDFImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPDFImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPDFImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/title",
          "value": "NSImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/title",
          "value": "NSImageDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomImageRep/title",
          "value": "NSCustomImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEPSImageRep/title",
          "value": "NSEPSImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEPSImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEPSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEPSImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEPSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/title",
          "value": "NSBitmapImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCIImageRep/title",
          "value": "NSCIImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCIImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCIImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCIImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCIImageRep"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/images-and-pdf"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/images-and-pdf"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
