{
  "abstract": [
    {
      "text": "Parameterized attributes that are specific to layout areas.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
        "doc://com.apple.appkit/documentation/AppKit/nsaccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Layout Area Parameterized Attributes"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutPointForScreenPoint": {
      "abstract": [
        {
          "text": "The point in the layout area (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ") corresponding to the specified point on the screen (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutPointForScreenPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutPointForScreenPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLayoutPointForScreenPointParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "layoutPointForScreenPoint",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/layoutpointforscreenpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutSizeForScreenSize": {
      "abstract": [
        {
          "text": "The size of the layout area in points (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ") corresponding to the specified screen size (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutSizeForScreenSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutSizeForScreenSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLayoutSizeForScreenSizeParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "layoutSizeForScreenSize",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/layoutsizeforscreensize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenPointForLayoutPoint": {
      "abstract": [
        {
          "text": "The screen point (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ") corresponding to the specified point in the layout area (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenPointForLayoutPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenPointForLayoutPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityScreenPointForLayoutPointParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "screenPointForLayoutPoint",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/screenpointforlayoutpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenSizeForLayoutSize": {
      "abstract": [
        {
          "text": "The size of the screen in points (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ") corresponding to the specified size of the layout area (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenSizeForLayoutSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenSizeForLayoutSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityScreenSizeForLayoutSizeParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "screenSizeForLayoutSize",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/screensizeforlayoutsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the app object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/app-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to individual table cells.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used with grid views, such as thumbnails and media browsers that present a grid of items. The children of a grid are ordered.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Grid View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/grid-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the items in a layout area.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Item Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-item-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsaccessibility": {
      "abstract": [
        {
          "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used in outline views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/slider-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to sliders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/slider-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Slider Attributes",
      "type": "topic",
      "url": "/documentation/appkit/slider-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/standard-attributes": {
      "abstract": [
        {
          "text": "Standard attributes that can be adopted by any accessibility object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Attributes",
      "type": "topic",
      "url": "/documentation/appkit/standard-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to tables and outlines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Table View and Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/table-view-and-outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants": {
      "abstract": [
        {
          "text": "Attributes and key constants used with attributed strings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Attributed-String Attributes and Constants",
      "type": "topic",
      "url": "/documentation/appkit/text-attributed-string-attributes-and-constants"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes specific to windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Window-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/window-specific-attributes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
        "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
        "doc://com.apple.appkit/documentation/AppKit/slider-attributes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutPointForScreenPoint",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutSizeForScreenSize",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenPointForLayoutPoint",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenSizeForLayoutSize"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutPointForScreenPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutSizeForScreenSize",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenPointForLayoutPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenSizeForLayoutSize"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
                "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
                "doc://com.apple.appkit/documentation/AppKit/slider-attributes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1layoutPointForScreenPoint/title",
          "value": "NSAccessibilityLayoutPointForScreenPointParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1layoutPointForScreenPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityLayoutPointForScreenPointParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1layoutSizeForScreenSize/title",
          "value": "NSAccessibilityLayoutSizeForScreenSizeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1layoutSizeForScreenSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityLayoutSizeForScreenSizeParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1screenSizeForLayoutSize/title",
          "value": "NSAccessibilityScreenSizeForLayoutSizeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1screenSizeForLayoutSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityScreenSizeForLayoutSizeParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1screenPointForLayoutPoint/title",
          "value": "NSAccessibilityScreenPointForLayoutPointParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1screenPointForLayoutPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityScreenPointForLayoutPointParameterizedAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/layout-area-parameterized-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/layout-area-parameterized-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
