{
  "abstract": [
    {
      "text": "Macros for use with multiple classes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Macros"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/APPKIT_API_UNAVAILABLE_BEGIN_MACCATALYST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "APPKIT_API_UNAVAILABLE_BEGIN_MACCATALYST"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/APPKIT_API_UNAVAILABLE_BEGIN_MACCATALYST",
      "kind": "symbol",
      "role": "symbol",
      "title": "APPKIT_API_UNAVAILABLE_BEGIN_MACCATALYST",
      "type": "topic",
      "url": "/documentation/appkit/appkit_api_unavailable_begin_maccatalyst"
    },
    "doc://com.apple.appkit/documentation/AppKit/APPKIT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "APPKIT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/APPKIT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "APPKIT_EXTERN",
      "type": "topic",
      "url": "/documentation/appkit/appkit_extern"
    },
    "doc://com.apple.appkit/documentation/AppKit/APPKIT_IVAR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "APPKIT_IVAR"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/APPKIT_IVAR",
      "kind": "symbol",
      "role": "symbol",
      "title": "APPKIT_IVAR",
      "type": "topic",
      "url": "/documentation/appkit/appkit_ivar"
    },
    "doc://com.apple.appkit/documentation/AppKit/APPKIT_PRIVATE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "APPKIT_PRIVATE"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/APPKIT_PRIVATE",
      "kind": "symbol",
      "role": "symbol",
      "title": "APPKIT_PRIVATE",
      "type": "topic",
      "url": "/documentation/appkit/appkit_private"
    },
    "doc://com.apple.appkit/documentation/AppKit/APPKIT_PRIVATE_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "APPKIT_PRIVATE_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/APPKIT_PRIVATE_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "APPKIT_PRIVATE_EXTERN",
      "type": "topic",
      "url": "/documentation/appkit/appkit_private_extern"
    },
    "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_0"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_0",
      "type": "topic",
      "url": "/documentation/appkit/available_mac_os_x_version_10_0_and_later_but_deprecated_in_mac_os_x_version_10_0"
    },
    "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_1_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_10_1_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_1"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_1_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_10_1_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_1",
      "type": "topic",
      "url": "/documentation/appkit/available_mac_os_x_version_10_1_and_later_but_deprecated_in_mac_os_x_version_10_1"
    },
    "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_2_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_10_2_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_2"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_2_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_2",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_10_2_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_2",
      "type": "topic",
      "url": "/documentation/appkit/available_mac_os_x_version_10_2_and_later_but_deprecated_in_mac_os_x_version_10_2"
    },
    "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_3_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_10_3_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_3"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_3_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_3",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_10_3_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_3",
      "type": "topic",
      "url": "/documentation/appkit/available_mac_os_x_version_10_3_and_later_but_deprecated_in_mac_os_x_version_10_3"
    },
    "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_4"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_4",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_4",
      "type": "topic",
      "url": "/documentation/appkit/available_mac_os_x_version_10_4_and_later_but_deprecated_in_mac_os_x_version_10_4"
    },
    "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_5_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_10_5_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_5"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_5_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_5",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_10_5_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_5",
      "type": "topic",
      "url": "/documentation/appkit/available_mac_os_x_version_10_5_and_later_but_deprecated_in_mac_os_x_version_10_5"
    },
    "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_6"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_6",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_6",
      "type": "topic",
      "url": "/documentation/appkit/available_mac_os_x_version_10_6_and_later_but_deprecated_in_mac_os_x_version_10_6"
    },
    "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_7_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_10_7_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_7"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_7_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_7",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_10_7_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_7",
      "type": "topic",
      "url": "/documentation/appkit/available_mac_os_x_version_10_7_and_later_but_deprecated_in_mac_os_x_version_10_7"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDictionaryOfVariableBindings": {
      "abstract": [
        {
          "text": "Creates a dictionary wherein the keys are string representations of the corresponding values’ variable names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDictionaryOfVariableBindings"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDictionaryOfVariableBindings",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDictionaryOfVariableBindings",
      "type": "topic",
      "url": "/documentation/appkit/nsdictionaryofvariablebindings"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIMAGE_UNAVAILABLE_MACCATALYST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIMAGE_UNAVAILABLE_MACCATALYST"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIMAGE_UNAVAILABLE_MACCATALYST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIMAGE_UNAVAILABLE_MACCATALYST"
        }
      ],
      "role": "symbol",
      "title": "NSIMAGE_UNAVAILABLE_MACCATALYST",
      "type": "topic",
      "url": "/documentation/appkit/nsimage_unavailable_maccatalyst"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRepRegistryChangedNotification": {
      "abstract": [
        {
          "text": "Posted whenever the image representation class registry changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSImageRepRegistryChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRepRegistryChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSImageRepRegistryChangedNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerepregistrychangednotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLAYOUTANCHOR_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLAYOUTANCHOR_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLAYOUTANCHOR_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLAYOUTANCHOR_EXTERN",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutanchor_extern"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLAYOUTCONSTRAINT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLAYOUTCONSTRAINT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLAYOUTCONSTRAINT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLAYOUTCONSTRAINT_EXTERN",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint_extern"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_CLASS_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS_OPENGL_CLASS_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_CLASS_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS_OPENGL_CLASS_DEPRECATED",
      "type": "topic",
      "url": "/documentation/appkit/ns_opengl_class_deprecated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS_OPENGL_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS_OPENGL_DEPRECATED",
      "type": "topic",
      "url": "/documentation/appkit/ns_opengl_deprecated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_ENUM_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS_OPENGL_ENUM_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_ENUM_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS_OPENGL_ENUM_DEPRECATED",
      "type": "topic",
      "url": "/documentation/appkit/ns_opengl_enum_deprecated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS_USER_ACTIVITY_SUPPORTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NS_USER_ACTIVITY_SUPPORTED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS_USER_ACTIVITY_SUPPORTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NS_USER_ACTIVITY_SUPPORTED"
        }
      ],
      "role": "symbol",
      "title": "NS_USER_ACTIVITY_SUPPORTED",
      "type": "topic",
      "url": "/documentation/appkit/ns_user_activity_supported"
    },
    "doc://com.apple.appkit/documentation/AppKit/constants": {
      "abstract": [
        {
          "text": "Constants for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Constants",
      "type": "topic",
      "url": "/documentation/appkit/constants"
    },
    "doc://com.apple.appkit/documentation/AppKit/data-types": {
      "abstract": [
        {
          "text": "Data types for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types",
      "type": "topic",
      "url": "/documentation/appkit/data-types"
    },
    "doc://com.apple.appkit/documentation/AppKit/enumerations": {
      "abstract": [
        {
          "text": "Enumerations for use with multiple classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Enumerations",
      "type": "topic",
      "url": "/documentation/appkit/enumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/enumerations",
        "doc://com.apple.appkit/documentation/AppKit/constants",
        "doc://com.apple.appkit/documentation/AppKit/data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSIMAGE_UNAVAILABLE_MACCATALYST",
        "doc://com.apple.appkit/documentation/AppKit/NS_USER_ACTIVITY_SUPPORTED"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/APPKIT_API_UNAVAILABLE_BEGIN_MACCATALYST",
                "doc://com.apple.appkit/documentation/AppKit/APPKIT_EXTERN",
                "doc://com.apple.appkit/documentation/AppKit/APPKIT_IVAR",
                "doc://com.apple.appkit/documentation/AppKit/APPKIT_PRIVATE",
                "doc://com.apple.appkit/documentation/AppKit/APPKIT_PRIVATE_EXTERN",
                "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_0",
                "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_1_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_1",
                "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_2_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_2",
                "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_3_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_3",
                "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_4",
                "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_5_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_5",
                "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_6",
                "doc://com.apple.appkit/documentation/AppKit/AVAILABLE_MAC_OS_X_VERSION_10_7_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_7",
                "doc://com.apple.appkit/documentation/AppKit/NSDictionaryOfVariableBindings",
                "doc://com.apple.appkit/documentation/AppKit/NSIMAGE_UNAVAILABLE_MACCATALYST",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRepRegistryChangedNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSLAYOUTANCHOR_EXTERN",
                "doc://com.apple.appkit/documentation/AppKit/NSLAYOUTCONSTRAINT_EXTERN",
                "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_CLASS_DEPRECATED",
                "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_DEPRECATED",
                "doc://com.apple.appkit/documentation/AppKit/NS_OPENGL_ENUM_DEPRECATED",
                "doc://com.apple.appkit/documentation/AppKit/NS_USER_ACTIVITY_SUPPORTED"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/enumerations",
                "doc://com.apple.appkit/documentation/AppKit/constants",
                "doc://com.apple.appkit/documentation/AppKit/data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIMAGE_UNAVAILABLE_MACCATALYST/title",
          "value": "NSIMAGE_UNAVAILABLE_MACCATALYST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIMAGE_UNAVAILABLE_MACCATALYST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIMAGE_UNAVAILABLE_MACCATALYST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NS_USER_ACTIVITY_SUPPORTED/title",
          "value": "NS_USER_ACTIVITY_SUPPORTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NS_USER_ACTIVITY_SUPPORTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NS_USER_ACTIVITY_SUPPORTED"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
