{
  "abstract": [
    {
      "text": "Implement menus and cursors to facilitate interactions with your app, and use your app’s Dock tile to convey updated information.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Menus, Cursors, and the Dock"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor": {
      "abstract": [
        {
          "text": "A pointer (also called a cursor).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCursor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursor"
        }
      ],
      "role": "symbol",
      "title": "NSCursor",
      "type": "topic",
      "url": "/documentation/appkit/nscursor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDockTile": {
      "abstract": [
        {
          "text": "The visual representation of your app’s miniaturized windows and app icon as they appear in the Dock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDockTile"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDockTile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDockTile"
        }
      ],
      "role": "symbol",
      "title": "NSDockTile",
      "type": "topic",
      "url": "/documentation/appkit/nsdocktile"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDockTilePlugIn": {
      "abstract": [
        {
          "text": "A set of methods implemented by plug-ins that allow an app’s Dock tile to be customized while the app is not running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDockTilePlugIn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDockTilePlugIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDockTilePlugIn"
        }
      ],
      "role": "symbol",
      "title": "NSDockTilePlugIn",
      "type": "topic",
      "url": "/documentation/appkit/nsdocktileplugin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenu": {
      "abstract": [
        {
          "text": "An object that manages an app’s menus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenu"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenu"
        }
      ],
      "role": "symbol",
      "title": "NSMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuDelegate": {
      "abstract": [
        {
          "text": "The optional methods implemented by delegates of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenu",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects to manage menu display and handle some events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSMenuDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsmenudelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItem": {
      "abstract": [
        {
          "text": "A command item in an app menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItem"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItem",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge": {
      "abstract": [
        {
          "text": "A control that provides additional quantitative information specific to a menu item, such as the number of available updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItemBadge"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItemBadge"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItemBadge",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitembadge"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemValidation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItemValidation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItemValidation"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItemValidation",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemvalidation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusBar": {
      "abstract": [
        {
          "text": "An object that manages a collection of status items displayed within the system-wide menu bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStatusBar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStatusBar"
        }
      ],
      "role": "symbol",
      "title": "NSStatusBar",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton": {
      "abstract": [
        {
          "text": "The appearance and behavior of an item in the systemwide menu bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStatusBarButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStatusBarButton"
        }
      ],
      "role": "symbol",
      "title": "NSStatusBarButton",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusbarbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusItem": {
      "abstract": [
        {
          "text": "An individual element displayed in the system menu bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStatusItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStatusItem"
        }
      ],
      "role": "symbol",
      "title": "NSStatusItem",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTrackingArea": {
      "abstract": [
        {
          "text": "A region of a view that generates mouse-tracking and cursor-update events when the pointer is over that region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTrackingArea"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTrackingArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTrackingArea"
        }
      ],
      "role": "symbol",
      "title": "NSTrackingArea",
      "type": "topic",
      "url": "/documentation/appkit/nstrackingarea"
    },
    "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit": {
      "abstract": [
        {
          "text": "Make your AppKit apps accessible to everyone who uses macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for AppKit",
      "type": "topic",
      "url": "/documentation/appkit/accessibility-for-appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/drag-and-drop": {
      "abstract": [
        {
          "text": "Support the direct manipulation of your app’s content using drag and drop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag and Drop",
      "type": "topic",
      "url": "/documentation/appkit/drag-and-drop"
    },
    "doc://com.apple.appkit/documentation/AppKit/gestures": {
      "abstract": [
        {
          "text": "Encapsulate your app’s event-handling logic in gesture recognizers so that you can reuse that code throughout your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/gestures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Gestures",
      "type": "topic",
      "url": "/documentation/appkit/gestures"
    },
    "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad": {
      "abstract": [
        {
          "text": "Handle events related to mouse, keyboard, and trackpad input.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mouse, Keyboard, and Trackpad",
      "type": "topic",
      "url": "/documentation/appkit/mouse-keyboard-and-trackpad"
    },
    "doc://com.apple.appkit/documentation/AppKit/touch-bar": {
      "abstract": [
        {
          "text": "Display interactive content and controls in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/touch-bar",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Touch Bar",
      "type": "topic",
      "url": "/documentation/appkit/touch-bar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-Interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
        "doc://com.apple.appkit/documentation/AppKit/gestures",
        "doc://com.apple.appkit/documentation/AppKit/touch-bar",
        "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
        "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit"
      ],
      "title": "User Interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Menus",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItem",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuDelegate"
      ],
      "title": "Menus"
    },
    {
      "anchor": "Menu-Validation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemValidation"
      ],
      "title": "Menu Validation"
    },
    {
      "anchor": "Menu-Bar-Items",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSStatusBar",
        "doc://com.apple.appkit/documentation/AppKit/NSStatusItem",
        "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton"
      ],
      "title": "Menu Bar Items"
    },
    {
      "anchor": "Cursors",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursor",
        "doc://com.apple.appkit/documentation/AppKit/NSTrackingArea"
      ],
      "title": "Cursors"
    },
    {
      "anchor": "The-Dock",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDockTile",
        "doc://com.apple.appkit/documentation/AppKit/NSDockTilePlugIn"
      ],
      "title": "The Dock"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Menus",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItem",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuDelegate"
              ],
              "title": "Menus"
            },
            {
              "anchor": "Menu-Validation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemValidation"
              ],
              "title": "Menu Validation"
            },
            {
              "anchor": "Menu-Bar-Items",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSStatusBar",
                "doc://com.apple.appkit/documentation/AppKit/NSStatusItem",
                "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton"
              ],
              "title": "Menu Bar Items"
            },
            {
              "anchor": "Cursors",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCursor",
                "doc://com.apple.appkit/documentation/AppKit/NSTrackingArea"
              ],
              "title": "Cursors"
            },
            {
              "anchor": "The-Dock",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDockTile",
                "doc://com.apple.appkit/documentation/AppKit/NSDockTilePlugIn"
              ],
              "title": "The Dock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-Interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
                "doc://com.apple.appkit/documentation/AppKit/gestures",
                "doc://com.apple.appkit/documentation/AppKit/touch-bar",
                "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
                "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit"
              ],
              "title": "User Interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/title",
          "value": "NSStatusBarButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title",
          "value": "NSCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDockTile/title",
          "value": "NSDockTile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDockTile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDockTile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDockTile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDockTile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/title",
          "value": "NSMenuItemBadge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemBadge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemBadge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDockTilePlugIn/title",
          "value": "NSDockTilePlugIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDockTilePlugIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDockTilePlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDockTilePlugIn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDockTilePlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuDelegate/title",
          "value": "NSMenuDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBar/title",
          "value": "NSStatusBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingArea/title",
          "value": "NSTrackingArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTrackingArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingArea/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTrackingArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem/title",
          "value": "NSStatusItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/title",
          "value": "NSMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/title",
          "value": "NSMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemValidation/title",
          "value": "NSMenuItemValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemValidation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemValidation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/menus-cursors-and-the-dock"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/menus-cursors-and-the-dock"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
