{
  "abstract": [
    {
      "text": "Access the app’s main menu items and update the window and services menus.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/menus"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Menus"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/addWindowsItem(_:title:filename:)": {
      "abstract": [
        {
          "text": "Adds an item to the Window menu for a given window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addWindowsItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "filename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/addWindowsItem(_:title:filename:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addWindowsItem:title:filename:"
        }
      ],
      "role": "symbol",
      "title": "addWindowsItem(_:title:filename:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/addwindowsitem(_:title:filename:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/changeWindowsItem(_:title:filename:)": {
      "abstract": [
        {
          "text": "Changes the item for a given window in the Window menu to a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeWindowsItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "filename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/changeWindowsItem(_:title:filename:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeWindowsItem:title:filename:"
        }
      ],
      "role": "symbol",
      "title": "changeWindowsItem(_:title:filename:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/changewindowsitem(_:title:filename:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/isAutomaticCustomizeTouchBarMenuItemEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the main menu contains an item for customizing the contents of the Touch Bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutomaticCustomizeTouchBarMenuItemEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/isAutomaticCustomizeTouchBarMenuItemEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticCustomizeTouchBarMenuItemEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutomaticCustomizeTouchBarMenuItemEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/isautomaticcustomizetouchbarmenuitemenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/mainMenu": {
      "abstract": [
        {
          "text": "The app’s main menu bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mainMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/mainMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mainMenu"
        }
      ],
      "role": "symbol",
      "title": "mainMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/mainmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/registerServicesMenuSendTypes(_:returnTypes:)": {
      "abstract": [
        {
          "text": "Registers the pasteboard types the receiver can send and receive in response to service requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerServicesMenuSendTypes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "returnTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/registerServicesMenuSendTypes(_:returnTypes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerServicesMenuSendTypes:returnTypes:"
        }
      ],
      "role": "symbol",
      "title": "registerServicesMenuSendTypes(_:returnTypes:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/registerservicesmenusendtypes(_:returntypes:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/removeWindowsItem(_:)": {
      "abstract": [
        {
          "text": "Removes the Window menu item for a given window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeWindowsItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/removeWindowsItem(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeWindowsItem:"
        }
      ],
      "role": "symbol",
      "title": "removeWindowsItem(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/removewindowsitem(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/servicesMenu": {
      "abstract": [
        {
          "text": "The app’s Services menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "servicesMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/servicesMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "servicesMenu"
        }
      ],
      "role": "symbol",
      "title": "servicesMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/servicesmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindowsItem(_:)": {
      "abstract": [
        {
          "text": "Updates the Window menu item for a given window to reflect the edited status of that window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateWindowsItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindowsItem(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateWindowsItem:"
        }
      ],
      "role": "symbol",
      "title": "updateWindowsItem(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/updatewindowsitem(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/windowsMenu": {
      "abstract": [
        {
          "text": "The Window menu of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowsMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/windowsMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowsMenu"
        }
      ],
      "role": "symbol",
      "title": "windowsMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/windowsmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-and-environment": {
      "abstract": [
        {
          "text": "Learn about the objects that you use to interact with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and Environment",
      "type": "topic",
      "url": "/documentation/appkit/app-and-environment"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-windows": {
      "abstract": [
        {
          "text": "Show, hide, minimize, arrange, and update your app’s windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-windows",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App Windows",
      "type": "topic",
      "url": "/documentation/appkit/app-windows"
    },
    "doc://com.apple.appkit/documentation/AppKit/modal-windows-and-panels": {
      "abstract": [
        {
          "text": "Display a modal window or show one of the standard app panels, such as the app’s About panel.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/modal-windows-and-panels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modal Windows and Panels",
      "type": "topic",
      "url": "/documentation/appkit/modal-windows-and-panels"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Windows-Panels-and-Menus",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/app-windows",
        "doc://com.apple.appkit/documentation/AppKit/modal-windows-and-panels"
      ],
      "title": "Managing Windows, Panels, and Menus"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Main-Menu",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/mainMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/isAutomaticCustomizeTouchBarMenuItemEnabled"
      ],
      "title": "Accessing the Main Menu"
    },
    {
      "anchor": "Managing-the-Window-Menu",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/windowsMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/addWindowsItem(_:title:filename:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/changeWindowsItem(_:title:filename:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/removeWindowsItem(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindowsItem(_:)"
      ],
      "title": "Managing the Window Menu"
    },
    {
      "anchor": "Managing-the-Services-Menu",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/registerServicesMenuSendTypes(_:returnTypes:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/servicesMenu"
      ],
      "title": "Managing the Services Menu"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Main-Menu",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/mainMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/isAutomaticCustomizeTouchBarMenuItemEnabled"
              ],
              "title": "Accessing the Main Menu"
            },
            {
              "anchor": "Managing-the-Window-Menu",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/windowsMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/addWindowsItem(_:title:filename:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/changeWindowsItem(_:title:filename:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/removeWindowsItem(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindowsItem(_:)"
              ],
              "title": "Managing the Window Menu"
            },
            {
              "anchor": "Managing-the-Services-Menu",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/registerServicesMenuSendTypes(_:returnTypes:)",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/servicesMenu"
              ],
              "title": "Managing the Services Menu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Windows-Panels-and-Menus",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/app-windows",
                "doc://com.apple.appkit/documentation/AppKit/modal-windows-and-panels"
              ],
              "title": "Managing Windows, Panels, and Menus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1changeWindowsItem(_:title:filename:)/title",
          "value": "changeWindowsItem:title:filename:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1changeWindowsItem(_:title:filename:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changeWindowsItem:title:filename:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1updateWindowsItem(_:)/title",
          "value": "updateWindowsItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1updateWindowsItem(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateWindowsItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1addWindowsItem(_:title:filename:)/title",
          "value": "addWindowsItem:title:filename:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1addWindowsItem(_:title:filename:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addWindowsItem:title:filename:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1servicesMenu/title",
          "value": "servicesMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1servicesMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "servicesMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1isAutomaticCustomizeTouchBarMenuItemEnabled/title",
          "value": "automaticCustomizeTouchBarMenuItemEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1isAutomaticCustomizeTouchBarMenuItemEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticCustomizeTouchBarMenuItemEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1removeWindowsItem(_:)/title",
          "value": "removeWindowsItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1removeWindowsItem(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeWindowsItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1registerServicesMenuSendTypes(_:returnTypes:)/title",
          "value": "registerServicesMenuSendTypes:returnTypes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1registerServicesMenuSendTypes(_:returnTypes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerServicesMenuSendTypes:returnTypes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1windowsMenu/title",
          "value": "windowsMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1windowsMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windowsMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1mainMenu/title",
          "value": "mainMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1mainMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mainMenu"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/menus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/menus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
