{
  "abstract": [
    {
      "text": "Miscellaneous attributes that can apply to various types of elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
        "doc://com.apple.appkit/documentation/AppKit/nsaccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/miscellaneous-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Miscellaneous Attributes"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/clearButton": {
      "abstract": [
        {
          "text": "The element that represents the clear button in a search field (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/clearButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityClearButtonAttribute"
        }
      ],
      "role": "symbol",
      "title": "clearButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/clearbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/columnTitles": {
      "abstract": [
        {
          "text": "The elements that represent the column titles (",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnTitles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/columnTitles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityColumnTitlesAttribute"
        }
      ],
      "role": "symbol",
      "title": "columnTitles",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/columntitles"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/containsProtectedContent": {
      "abstract": [
        {
          "text": "A flag that indicates whether the object contains protected content (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "), or not (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/false",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as ",
          "type": "text"
        },
        {
          "code": "boolValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsProtectedContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/containsProtectedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityContainsProtectedContentAttribute"
        }
      ],
      "role": "symbol",
      "title": "containsProtectedContent",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/containsprotectedcontent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/criticalValue": {
      "abstract": [
        {
          "text": "The critical value in a level indicator (typically, ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "criticalValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/criticalValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCriticalValueAttribute"
        }
      ],
      "role": "symbol",
      "title": "criticalValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/criticalvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/decrementButton": {
      "abstract": [
        {
          "text": "The element that represents a stepper’s decrement button (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/decrementButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDecrementButtonAttribute"
        }
      ],
      "role": "symbol",
      "title": "decrementButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/decrementbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/document": {
      "abstract": [
        {
          "text": "The URL for the file represented by the element (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "document"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/document",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDocumentAttribute"
        }
      ],
      "role": "symbol",
      "title": "document",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/document"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/edited": {
      "abstract": [
        {
          "text": "A flag that indicates whether the element has been modified (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/edited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityEditedAttribute"
        }
      ],
      "role": "symbol",
      "title": "edited",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/edited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/expanded": {
      "abstract": [
        {
          "text": "A flag that indicates whether the element is expanded (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expanded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/expanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityExpandedAttribute"
        }
      ],
      "role": "symbol",
      "title": "expanded",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/expanded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/filename": {
      "abstract": [
        {
          "text": "The filename associated with the element (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/filename",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFilenameAttribute"
        }
      ],
      "role": "symbol",
      "title": "filename",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/filename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/header": {
      "abstract": [
        {
          "text": "The element that represents a table view’s header (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "header"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/header",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityHeaderAttribute"
        }
      ],
      "role": "symbol",
      "title": "header",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/header"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/horizontalScrollBar": {
      "abstract": [
        {
          "text": "The element that represents a scroll view’s horizontal scroll bar (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalScrollBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/horizontalScrollBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityHorizontalScrollBarAttribute"
        }
      ],
      "role": "symbol",
      "title": "horizontalScrollBar",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/horizontalscrollbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/identifier": {
      "abstract": [
        {
          "text": "The identity of the element (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityIdentifierAttribute"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/identifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/incrementButton": {
      "abstract": [
        {
          "text": "The element that represents a stepper’s increment button (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incrementButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/incrementButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityIncrementButtonAttribute"
        }
      ],
      "role": "symbol",
      "title": "incrementButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/incrementbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/index": {
      "abstract": [
        {
          "text": "The index of the row or column represented by the element (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/index",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityIndexAttribute"
        }
      ],
      "role": "symbol",
      "title": "index",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/index"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/nextContents": {
      "abstract": [
        {
          "text": "The elements representing the contents that follow the current divider element, such as a subview adjacent to a split view’s splitter element (",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextContents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/nextContents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityNextContentsAttribute"
        }
      ],
      "role": "symbol",
      "title": "nextContents",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/nextcontents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/orientation": {
      "abstract": [
        {
          "text": "The element’s orientation, which can have the value ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/horizontal",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/vertical",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/orientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityOrientationAttribute"
        }
      ],
      "role": "symbol",
      "title": "orientation",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/orientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/overflowButton": {
      "abstract": [
        {
          "text": "The element that represents a toolbar’s overflow button (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overflowButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/overflowButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityOverflowButtonAttribute"
        }
      ],
      "role": "symbol",
      "title": "overflowButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/overflowbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/placeholderValue": {
      "abstract": [
        {
          "text": "The placeholder value for a control, such as a text field (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/placeholderValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityPlaceholderValueAttribute"
        }
      ],
      "role": "symbol",
      "title": "placeholderValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/placeholdervalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/previousContents": {
      "abstract": [
        {
          "text": "The elements representing the contents that precede the current divider element, such as a subview adjacent to a split view’s splitter bar element (",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previousContents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/previousContents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityPreviousContentsAttribute"
        }
      ],
      "role": "symbol",
      "title": "previousContents",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/previouscontents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/searchButton": {
      "abstract": [
        {
          "text": "The element that represents the search button in a search field (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/searchButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySearchButtonAttribute"
        }
      ],
      "role": "symbol",
      "title": "searchButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/searchbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/searchMenu": {
      "abstract": [
        {
          "text": "The element that represents the menu in a search field (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/searchMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySearchMenuAttribute"
        }
      ],
      "role": "symbol",
      "title": "searchMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/searchmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/selected": {
      "abstract": [
        {
          "text": "A flag that indicates whether the element is selected (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/selected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySelectedAttribute"
        }
      ],
      "role": "symbol",
      "title": "selected",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/selected"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/splitters": {
      "abstract": [
        {
          "text": "The views and splitter bar in a split view (",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/splitters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySplittersAttribute"
        }
      ],
      "role": "symbol",
      "title": "splitters",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/splitters"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/tabs": {
      "abstract": [
        {
          "text": "The tab elements in a tab view (",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/tabs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityTabsAttribute"
        }
      ],
      "role": "symbol",
      "title": "tabs",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/tabs"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/url": {
      "abstract": [
        {
          "text": "The URL associated with the element (",
          "type": "text"
        },
        {
          "code": "NSURL",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityURLAttribute"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/url"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/verticalScrollBar": {
      "abstract": [
        {
          "text": "The element that represents the vertical scroll bar in a scroll view (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalScrollBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/verticalScrollBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityVerticalScrollBarAttribute"
        }
      ],
      "role": "symbol",
      "title": "verticalScrollBar",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/verticalscrollbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/warningValue": {
      "abstract": [
        {
          "text": "The warning value in a level indicator (typically, ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "warningValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/warningValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityWarningValueAttribute"
        }
      ],
      "role": "symbol",
      "title": "warningValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/warningvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/horizontal": {
      "abstract": [
        {
          "text": "The element is oriented horizontally.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityOrientationValue",
          "text": "OrientationValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/horizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityHorizontalOrientationValue"
        }
      ],
      "role": "symbol",
      "title": "horizontal",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue/horizontal"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/vertical": {
      "abstract": [
        {
          "text": "The element is oriented vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityOrientationValue",
          "text": "OrientationValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/vertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityVerticalOrientationValue"
        }
      ],
      "role": "symbol",
      "title": "vertical",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue/vertical"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the app object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/app-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to individual table cells.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used with grid views, such as thumbnails and media browsers that present a grid of items. The children of a grid are ordered.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Grid View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/grid-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the items in a layout area.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Item Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-item-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsaccessibility": {
      "abstract": [
        {
          "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used in outline views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/standard-attributes": {
      "abstract": [
        {
          "text": "Standard attributes that can be adopted by any accessibility object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Attributes",
      "type": "topic",
      "url": "/documentation/appkit/standard-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to tables and outlines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Table View and Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/table-view-and-outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants": {
      "abstract": [
        {
          "text": "Attributes and key constants used with attributed strings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Attributed-String Attributes and Constants",
      "type": "topic",
      "url": "/documentation/appkit/text-attributed-string-attributes-and-constants"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes specific to windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Window-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/window-specific-attributes"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
        "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/clearButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/columnTitles",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/decrementButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/document",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/edited",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/expanded",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/filename",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/header",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/horizontalScrollBar",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/incrementButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/index",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/nextContents",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/orientation",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/overflowButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/previousContents",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/searchButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/searchMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/selected",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/splitters",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/tabs",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/url",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/verticalScrollBar",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/warningValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/criticalValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/placeholderValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/containsProtectedContent",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/identifier"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/clearButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/columnTitles",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/decrementButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/document",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/edited",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/expanded",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/filename",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/header",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/horizontalScrollBar",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/incrementButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/index",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/nextContents",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/orientation",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/overflowButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/previousContents",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/searchButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/searchMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/selected",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/splitters",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/tabs",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/url",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/verticalScrollBar",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/warningValue",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/criticalValue",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/placeholderValue",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/containsProtectedContent",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/identifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
                "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1tabs/title",
          "value": "NSAccessibilityTabsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1tabs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityTabsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1decrementButton/title",
          "value": "NSAccessibilityDecrementButtonAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1decrementButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDecrementButtonAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1previousContents/title",
          "value": "NSAccessibilityPreviousContentsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1previousContents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityPreviousContentsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1horizontalScrollBar/title",
          "value": "NSAccessibilityHorizontalScrollBarAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1horizontalScrollBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityHorizontalScrollBarAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1index/title",
          "value": "NSAccessibilityIndexAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1index/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityIndexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1clearButton/title",
          "value": "NSAccessibilityClearButtonAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1clearButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityClearButtonAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1vertical/title",
          "value": "NSAccessibilityVerticalOrientationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1vertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityVerticalOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1splitters/title",
          "value": "NSAccessibilitySplittersAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1splitters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySplittersAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1containsProtectedContent/title",
          "value": "NSAccessibilityContainsProtectedContentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1containsProtectedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityContainsProtectedContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1searchMenu/title",
          "value": "NSAccessibilitySearchMenuAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1searchMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySearchMenuAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1criticalValue/title",
          "value": "NSAccessibilityCriticalValueAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1criticalValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCriticalValueAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1searchButton/title",
          "value": "NSAccessibilitySearchButtonAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1searchButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySearchButtonAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1verticalScrollBar/title",
          "value": "NSAccessibilityVerticalScrollBarAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1verticalScrollBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityVerticalScrollBarAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1horizontal/title",
          "value": "NSAccessibilityHorizontalOrientationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1horizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityHorizontalOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1orientation/title",
          "value": "NSAccessibilityOrientationAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1orientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientationAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1document/title",
          "value": "NSAccessibilityDocumentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1document/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDocumentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1header/title",
          "value": "NSAccessibilityHeaderAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1header/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityHeaderAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1selected/title",
          "value": "NSAccessibilitySelectedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1selected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySelectedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1edited/title",
          "value": "NSAccessibilityEditedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1edited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityEditedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1overflowButton/title",
          "value": "NSAccessibilityOverflowButtonAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1overflowButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOverflowButtonAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1filename/title",
          "value": "NSAccessibilityFilenameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1filename/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFilenameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1columnTitles/title",
          "value": "NSAccessibilityColumnTitlesAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1columnTitles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityColumnTitlesAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1incrementButton/title",
          "value": "NSAccessibilityIncrementButtonAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1incrementButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityIncrementButtonAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1nextContents/title",
          "value": "NSAccessibilityNextContentsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1nextContents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNextContentsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1identifier/title",
          "value": "NSAccessibilityIdentifierAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityIdentifierAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1expanded/title",
          "value": "NSAccessibilityExpandedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1expanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityExpandedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1warningValue/title",
          "value": "NSAccessibilityWarningValueAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1warningValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityWarningValueAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1url/title",
          "value": "NSAccessibilityURLAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityURLAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1placeholderValue/title",
          "value": "NSAccessibilityPlaceholderValueAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1placeholderValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityPlaceholderValueAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/miscellaneous-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/miscellaneous-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
