{
  "abstract": [
    {
      "text": "The following constants correspond to the available font panel mode masks returned by ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1534415-validmodesforfontpanel",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
        "doc://com.apple.appkit/documentation/AppKit/nsfontpanelvalidation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/mode-masks"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Mode Masks"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelAllEffectsModeMask": {
      "abstract": [
        {
          "text": "Display all the effects user interface items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelAllEffectsModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelAllEffectsModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelAllEffectsModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelAllEffectsModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelalleffectsmodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelAllModesMask": {
      "abstract": [
        {
          "text": "Display all the available adornments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelAllModesMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelAllModesMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelAllModesMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelAllModesMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelallmodesmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelCollectionModeMask": {
      "abstract": [
        {
          "text": "Display the font collections column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelCollectionModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelCollectionModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelCollectionModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelCollectionModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelcollectionmodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelDocumentColorEffectModeMask": {
      "abstract": [
        {
          "text": "Display the document color button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelDocumentColorEffectModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelDocumentColorEffectModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelDocumentColorEffectModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelDocumentColorEffectModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpaneldocumentcoloreffectmodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelFaceModeMask": {
      "abstract": [
        {
          "text": "Display the typeface column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelFaceModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelFaceModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelFaceModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelFaceModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelfacemodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelShadowEffectModeMask": {
      "abstract": [
        {
          "text": "Display the shadow effects button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelShadowEffectModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelShadowEffectModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelShadowEffectModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelShadowEffectModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelshadoweffectmodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelSizeModeMask": {
      "abstract": [
        {
          "text": "Display the font size column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelSizeModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelSizeModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelSizeModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelSizeModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelsizemodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelStandardModesMask": {
      "abstract": [
        {
          "text": "Display the standard default font panel—that is, including the collections, typeface, and size columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelStandardModesMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelStandardModesMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelStandardModesMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelStandardModesMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelstandardmodesmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelStrikethroughEffectModeMask": {
      "abstract": [
        {
          "text": "Display the strike-through popup menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelStrikethroughEffectModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelStrikethroughEffectModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelStrikethroughEffectModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelStrikethroughEffectModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelstrikethrougheffectmodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelTextColorEffectModeMask": {
      "abstract": [
        {
          "text": "Display the text color button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelTextColorEffectModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelTextColorEffectModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelTextColorEffectModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelTextColorEffectModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpaneltextcoloreffectmodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanelUnderlineEffectModeMask": {
      "abstract": [
        {
          "text": "Display the underline popup menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanelUnderlineEffectModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanelUnderlineEffectModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelUnderlineEffectModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanelUnderlineEffectModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelunderlineeffectmodemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsfontpanelvalidation": {
      "abstract": [
        {
          "text": "A set of methods you use to tell the Font panel to display some or all of its elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsfontpanelvalidation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSFontPanelValidation",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanelvalidation"
    },
    "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens": {
      "abstract": [
        {
          "text": "Organize your view hierarchies and facilitate their display onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows, Panels, and Screens",
      "type": "topic",
      "url": "/documentation/appkit/windows-panels-and-screens"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1534415-validmodesforfontpanel": {
      "abstract": [
        {
          "text": "Returns the mode mask corresponding to the expected font panel mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1534415-validmodesforfontpanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "validModesForFontPanel:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1534415-validmodesforfontpanel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelFaceModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelSizeModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelCollectionModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelUnderlineEffectModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelStrikethroughEffectModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelTextColorEffectModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelDocumentColorEffectModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelShadowEffectModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelAllEffectsModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelStandardModesMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanelAllModesMask"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelFaceModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelSizeModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelCollectionModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelUnderlineEffectModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelStrikethroughEffectModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelTextColorEffectModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelDocumentColorEffectModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelShadowEffectModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelAllEffectsModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelStandardModesMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanelAllModesMask"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelAllModesMask/title",
          "value": "NSFontPanelAllModesMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelAllModesMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelAllModesMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelCollectionModeMask/title",
          "value": "NSFontPanelCollectionModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelCollectionModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelCollectionModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelDocumentColorEffectModeMask/title",
          "value": "NSFontPanelDocumentColorEffectModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelDocumentColorEffectModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelDocumentColorEffectModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelSizeModeMask/title",
          "value": "NSFontPanelSizeModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelSizeModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelSizeModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelUnderlineEffectModeMask/title",
          "value": "NSFontPanelUnderlineEffectModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelUnderlineEffectModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelUnderlineEffectModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelFaceModeMask/title",
          "value": "NSFontPanelFaceModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelFaceModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelFaceModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelTextColorEffectModeMask/title",
          "value": "NSFontPanelTextColorEffectModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelTextColorEffectModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelTextColorEffectModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelAllEffectsModeMask/title",
          "value": "NSFontPanelAllEffectsModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelAllEffectsModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelAllEffectsModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelStrikethroughEffectModeMask/title",
          "value": "NSFontPanelStrikethroughEffectModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelStrikethroughEffectModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelStrikethroughEffectModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelStandardModesMask/title",
          "value": "NSFontPanelStandardModesMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelStandardModesMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelStandardModesMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelShadowEffectModeMask/title",
          "value": "NSFontPanelShadowEffectModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanelShadowEffectModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelShadowEffectModeMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/mode-masks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/mode-masks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
