{
  "abstract": [
    {
      "text": "The reason for a change of editing focus among text fields.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/text-display",
        "doc://com.apple.appkit/documentation/AppKit/NSText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/movement-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Movement Codes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are the possible values for the ",
              "type": "text"
            },
            {
              "code": "NSTextMovement",
              "type": "codeVoice"
            },
            {
              "text": " key of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText/didEndEditingNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary. The field editor makes sure that these are the values sent when the user presses the Tab, Backtab, or Return key while editing, in essence describing why the user is leaving the field. The control then uses this information to decide where to send focus next.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBacktabTextMovement": {
      "abstract": [
        {
          "text": "The Backtab (Shift-Tab) key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBacktabTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBacktabTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBacktabTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSBacktabTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsbacktabtextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCancelTextMovement": {
      "abstract": [
        {
          "text": "The user cancelled the completion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCancelTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCancelTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCancelTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSCancelTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nscanceltextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDownTextMovement": {
      "abstract": [
        {
          "text": "The down arrow key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDownTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDownTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDownTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSDownTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsdowntextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIllegalTextMovement": {
      "abstract": [
        {
          "text": "Currently unused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIllegalTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIllegalTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIllegalTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSIllegalTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsillegaltextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftTextMovement": {
      "abstract": [
        {
          "text": "The left arrow key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLeftTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLeftTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSLeftTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nslefttextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherTextMovement": {
      "abstract": [
        {
          "text": "The user performed some undefined action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOtherTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOtherTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSOtherTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsothertextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReturnTextMovement": {
      "abstract": [
        {
          "text": "The Return key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReturnTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReturnTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReturnTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSReturnTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsreturntextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightTextMovement": {
      "abstract": [
        {
          "text": "The right arrow key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRightTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRightTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSRightTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsrighttextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabTextMovement": {
      "abstract": [
        {
          "text": "The Tab key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTabTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSTabTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nstabtextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSText": {
      "abstract": [
        {
          "text": "The most general programmatic interface for objects that manage text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSText"
        }
      ],
      "role": "symbol",
      "title": "NSText",
      "type": "topic",
      "url": "/documentation/appkit/nstext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSText/didEndEditingNotification": {
      "abstract": [
        {
          "text": "Posted when focus leaves an ",
          "type": "text"
        },
        {
          "code": "NSText",
          "type": "codeVoice"
        },
        {
          "text": " object, whether or not any operation has changed characters or formatting attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didEndEditingNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText/didEndEditingNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextDidEndEditingNotification"
        }
      ],
      "role": "symbol",
      "title": "didEndEditingNotification",
      "type": "topic",
      "url": "/documentation/appkit/nstext/didendeditingnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUpTextMovement": {
      "abstract": [
        {
          "text": "The up arrow key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUpTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUpTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSUpTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsuptextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection": {
      "abstract": [
        {
          "text": "Constants that specify the writing direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/common-unicode-characters": {
      "abstract": [],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/common-unicode-characters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Common Unicode Characters",
      "type": "topic",
      "url": "/documentation/appkit/common-unicode-characters"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-display": {
      "abstract": [
        {
          "text": "Display text and check spelling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Display",
      "type": "topic",
      "url": "/documentation/appkit/text-display"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection",
        "doc://com.apple.appkit/documentation/AppKit/common-unicode-characters"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSIllegalTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSReturnTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSTabTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSBacktabTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSRightTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSUpTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSDownTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSCancelTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSOtherTextMovement"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSIllegalTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSReturnTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSTabTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSBacktabTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSLeftTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSRightTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSUpTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSDownTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSCancelTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSOtherTextMovement"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection",
                "doc://com.apple.appkit/documentation/AppKit/common-unicode-characters"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRightTextMovement/title",
          "value": "NSRightTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRightTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRightTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBacktabTextMovement/title",
          "value": "NSBacktabTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBacktabTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBacktabTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1didEndEditingNotification/title",
          "value": "NSTextDidEndEditingNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1didEndEditingNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextDidEndEditingNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOtherTextMovement/title",
          "value": "NSOtherTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOtherTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOtherTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/title",
          "value": "NSText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/title",
          "value": "NSWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReturnTextMovement/title",
          "value": "NSReturnTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReturnTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReturnTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabTextMovement/title",
          "value": "NSTabTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLeftTextMovement/title",
          "value": "NSLeftTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLeftTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLeftTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCancelTextMovement/title",
          "value": "NSCancelTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCancelTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCancelTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDownTextMovement/title",
          "value": "NSDownTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDownTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDownTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/title",
          "value": "NSTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUpTextMovement/title",
          "value": "NSUpTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUpTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIllegalTextMovement/title",
          "value": "NSIllegalTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIllegalTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIllegalTextMovement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/movement-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/movement-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
