{"topicSections":[{"title":"Supporting Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton/accessibilityValue()"],"anchor":"Supporting-Accessibility"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Buttons","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton","doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox"],"anchor":"Buttons"}],"variants":[{"paths":["/documentation/appkit/nsaccessibilityradiobutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsaccessibilityradiobutton"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"metadata":{"roleHeading":"Protocol","externalID":"c:objc(pl)NSAccessibilityRadioButton","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"role":"symbol","symbolKind":"protocol","platforms":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"modules":[{"name":"AppKit"}],"title":"NSAccessibilityRadioButton"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityRadioButton"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSAccessibilityButton","text":"NSAccessibilityButton","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton"}],"platforms":["macOS"]}]},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol when you want a user interface element to behave like a radio button—a control for constraining a selection to a single element from several elements—in the accessibility hierarchy.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can further enhance the adopting element by implementing any of the information properties or action methods that the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","isActive":true,"type":"reference"},{"text":" protocol declares.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Any class that adopts this protocol must implement all of its methods, and the required methods of any protocol it inherits from. The compiler may require you to override some methods that your ancestors have already implemented. Simply follow the compiler’s warnings, and reimplement these methods as necessary.","type":"text"}]}],"name":"Explicit Implementation Required","type":"aside","style":"note"}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a radio button."}],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton":{"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"type":"topic","title":"NSAccessibilityRadioButton","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a radio button."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton","url":"/documentation/appkit/nsaccessibilityradiobutton"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton/accessibilityValue()":{"url":"/documentation/appkit/nsaccessibilityradiobutton/accessibilityvalue()","abstract":[{"text":"Returns the radio button’s value.","type":"text"}],"role":"symbol","required":true,"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessibilityValue"}],"title":"accessibilityValue()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton/accessibilityValue()"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol":{"title":"NSAccessibilityElementProtocol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to interact with an assistive app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityelementprotocol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox":{"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityCheckBox"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityCheckBox"}],"type":"topic","title":"NSAccessibilityCheckBox","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a checkbox."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox","url":"/documentation/appkit/nsaccessibilitycheckbox"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilitySwitch","kind":"identifier"}],"navigatorTitle":[{"text":"NSAccessibilitySwitch","kind":"identifier"}],"role":"symbol","title":"NSAccessibilitySwitch","type":"topic","kind":"symbol","url":"/documentation/appkit/nsaccessibilityswitch","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a switch."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityButton","kind":"identifier"}],"navigatorTitle":[{"text":"NSAccessibilityButton","kind":"identifier"}],"role":"symbol","title":"NSAccessibilityButton","type":"topic","kind":"symbol","url":"/documentation/appkit/nsaccessibilitybutton","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a button."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Protocol","op":"replace","path":"/metadata/roleHeading"},{"value":"NSAccessibilityRadioButton","op":"replace","path":"/metadata/title"},{"value":"protocol","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"NSAccessibilityRadioButton","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace","path":"/hierarchy"},{"value":[{"anchor":"Supporting-Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton/accessibilityValue()"],"title":"Supporting Accessibility"}],"op":"replace","path":"/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton"],"title":"Inherits From","kind":"relationships"}],"op":"replace","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton","doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox"],"generated":true,"anchor":"Buttons","title":"Buttons"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityRadioButton","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton","text":"NSAccessibilityButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSAccessibilityButton"},{"text":">","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/title","value":"NSAccessibilityRadioButton"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/fragments","value":[{"kind":"identifier","text":"NSAccessibilityRadioButton"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityRadioButton"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","value":"NSAccessibility"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","value":[{"kind":"identifier","text":"NSAccessibility"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","value":[{"text":"NSAccessibility","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton~1accessibilityValue()/title","value":"accessibilityValue"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton~1accessibilityValue()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityValue"}]},{"value":"NSAccessibilityElement","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title","op":"replace"},{"value":[{"text":"NSAccessibilityElement","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSAccessibilityElement"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle","op":"replace"},{"value":"NSAccessibilityCheckBox","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCheckBox/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSAccessibilityCheckBox"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCheckBox/fragments","op":"replace"},{"value":[{"text":"NSAccessibilityCheckBox","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCheckBox/navigatorTitle","op":"replace"},{"value":"NSAccessibilitySwitch","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySwitch/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSAccessibilitySwitch"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySwitch/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSAccessibilitySwitch"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySwitch/navigatorTitle","op":"replace"},{"value":"NSAccessibilityButton","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSAccessibilityButton"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSAccessibilityButton"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}