{"variants":[{"paths":["/documentation/appkit/nsaccessibilitystatictext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsaccessibilitystatictext"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityStaticText"},{"kind":"text","text":" : "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","preciseIdentifier":"c:objc(pl)NSAccessibilityElement","kind":"typeIdentifier","text":"NSAccessibilityElementProtocol"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol when you want to represent short pieces of text, such as headers or labels. For longer blocks of text, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText"},{"text":" protocol.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can further enhance the adopting element by implementing any of the information properties or action methods that the "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","type":"reference"},{"type":"text","text":" protocol declares."}]},{"style":"note","name":"Explicit Implementation Required","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Any class that adopts this protocol must implement all of its methods, and the required methods of any protocol it inherits from. The compiler may require you to override some methods that your ancestors have already implemented. Simply follow the compiler’s warnings, and reimplement these methods as necessary."}],"type":"paragraph"}]}]}],"metadata":{"roleHeading":"Protocol","title":"NSAccessibilityStaticText","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityStaticText"}],"platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"role":"symbol","symbolKind":"protocol","modules":[{"name":"AppKit"}],"externalID":"c:objc(pl)NSAccessibilityStaticText","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityStaticText"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as static text.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Text","anchor":"Text","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText"],"kind":"relationships"},{"title":"Conforming Types","type":"conformingTypes","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSComboBox","doc://com.apple.appkit/documentation/AppKit/NSSearchField","doc://com.apple.appkit/documentation/AppKit/NSSecureTextField","doc://com.apple.appkit/documentation/AppKit/NSTextField","doc://com.apple.appkit/documentation/AppKit/NSTextView","doc://com.apple.appkit/documentation/AppKit/NSTokenField"],"kind":"relationships"}],"topicSections":[{"title":"Supporting Accessibility","anchor":"Supporting-Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.apple.appkit/documentation/AppKit/NSSearchField":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSearchField","abstract":[{"text":"A text field optimized for performing text-based searches.","type":"text"}],"navigatorTitle":[{"text":"NSSearchField","kind":"identifier"}],"url":"/documentation/appkit/nssearchfield","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSearchField","kind":"identifier"}],"type":"topic","title":"NSSearchField"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()":{"required":true,"title":"accessibilityValue()","url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityvalue()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Returns the text that the accessibility element displays."}],"navigatorTitle":[{"text":"accessibilityValue","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTextView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSTextView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextView","abstract":[{"text":"A view that draws text and handles user interactions with that text.","type":"text"}],"type":"topic","title":"NSTextView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSTextView"}],"url":"/documentation/appkit/nstextview","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol":{"title":"NSAccessibilityElementProtocol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to interact with an assistive app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityelementprotocol"},"doc://com.apple.appkit/documentation/AppKit/NSComboBox":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboBox","navigatorTitle":[{"text":"NSComboBox","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NSComboBox","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A view that displays a list of values in a pop-up menu where the user selects a value or types in a custom value."}],"type":"topic","title":"NSComboBox","role":"symbol","url":"/documentation/appkit/nscombobox"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText","navigatorTitle":[{"text":"NSAccessibilityStaticText","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityStaticText","kind":"identifier"}],"title":"NSAccessibilityStaticText","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as static text."}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsaccessibilitystatictext"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)":{"title":"accessibilityAttributedString(for:)","navigatorTitle":[{"text":"accessibilityAttributedStringForRange:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","role":"symbol","url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityattributedstring(for:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityAttributedString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Returns the attributed substring for the specified range of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText":{"url":"/documentation/appkit/nsaccessibilitynavigablestatictext","title":"NSAccessibilityNavigableStaticText","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityNavigableStaticText"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityNavigableStaticText"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as navigable static text."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField":{"abstract":[{"type":"text","text":"A text field that hides the typed text."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextField","kind":"identifier"}],"url":"/documentation/appkit/nssecuretextfield","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField","role":"symbol","navigatorTitle":[{"text":"NSSecureTextField","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NSSecureTextField"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()":{"url":"/documentation/appkit/nsaccessibilitystatictext/accessibilityvisiblecharacterrange()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityVisibleCharacterRange"}],"role":"symbol","type":"topic","title":"accessibilityVisibleCharacterRange()","abstract":[{"text":"Returns the range of visible characters in the document.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityVisibleCharacterRange"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSRange"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"},"doc://com.apple.appkit/documentation/AppKit/NSTokenField":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSTokenField","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenField","url":"/documentation/appkit/nstokenfield","title":"NSTokenField","role":"symbol","abstract":[{"text":"A text field that converts text into visually distinct tokens.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTokenField","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTextField":{"title":"NSTextField","navigatorTitle":[{"text":"NSTextField","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField","role":"symbol","url":"/documentation/appkit/nstextfield","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextField","kind":"identifier"}],"abstract":[{"text":"Text the user can select or edit to send an action message to a target when the user presses the Return key.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Protocol","path":"/metadata/roleHeading","op":"replace"},{"value":"NSAccessibilityStaticText","path":"/metadata/title","op":"replace"},{"value":"protocol","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NSAccessibilityStaticText"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSAccessibilityStaticText"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"anchor":"Supporting-Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityAttributedString(for:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityValue()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText/accessibilityVisibleCharacterRange()"],"title":"Supporting Accessibility"}],"op":"replace","path":"/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText"],"title":"Inherited By","kind":"relationships"}],"op":"replace","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText"],"anchor":"Text","title":"Text","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityStaticText","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSAccessibilityElement","text":"NSAccessibilityElement","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","value":"NSAccessibility","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","value":[{"text":"NSAccessibility","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","value":[{"text":"NSAccessibility","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/title","value":"NSSearchField","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/fragments","value":[{"kind":"identifier","text":"NSSearchField"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/navigatorTitle","value":[{"text":"NSSearchField","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityValue()/title","value":"accessibilityValue","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityValue()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityValue"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title","value":"NSTextView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments","value":[{"kind":"identifier","text":"NSTextView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle","value":[{"kind":"identifier","text":"NSTextView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title","value":"NSAccessibilityElement","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments","value":[{"text":"NSAccessibilityElement","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityElement"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBox/title","value":"NSComboBox","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBox/fragments","value":[{"kind":"identifier","text":"NSComboBox"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBox/navigatorTitle","value":[{"text":"NSComboBox","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/title","value":"NSAccessibilityStaticText","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/fragments","value":[{"text":"NSAccessibilityStaticText","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityStaticText"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityAttributedString(for:)/title","value":"accessibilityAttributedStringForRange:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityAttributedString(for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityAttributedStringForRange:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/title","value":"NSAccessibilityNavigableStaticText","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/fragments","value":[{"text":"NSAccessibilityNavigableStaticText","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/navigatorTitle","value":[{"text":"NSAccessibilityNavigableStaticText","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/title","value":"NSSecureTextField","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/fragments","value":[{"text":"NSSecureTextField","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/navigatorTitle","value":[{"kind":"identifier","text":"NSSecureTextField"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityVisibleCharacterRange()/title","value":"accessibilityVisibleCharacterRange","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText~1accessibilityVisibleCharacterRange()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityVisibleCharacterRange","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/title","value":"NSTokenField","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/fragments","value":[{"text":"NSTokenField","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/navigatorTitle","value":[{"text":"NSTokenField","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title","value":"NSTextField","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments","value":[{"kind":"identifier","text":"NSTextField"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle","value":[{"kind":"identifier","text":"NSTextField"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}