{
  "abstract": [
    {
      "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "title": "NSAccessibility"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "NSAccessibility",
              "type": "codeVoice"
            },
            {
              "text": " informal protocol defines an old, key-based API. For the most part, Apple doesn’t recommend using this API. Use the method-based API in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead. However, there are a few methods and properties that are still relevant. You can combine the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1526136-accessibilityhittest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLayoutArea/accessibilityFocusedUIElement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1534050-accessibilitynotifieswhendestroy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties with the new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLayoutArea/accessibilityFocusedUIElement": {
      "abstract": [
        {
          "text": "The child accessibility element with the current focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityFocusedUIElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLayoutArea/accessibilityFocusedUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityFocusedUIElement"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityFocusedUIElement",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitylayoutarea/accessibilityfocuseduielement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate": {
      "abstract": [
        {
          "text": "A set of methods that drawer delegates implement to open, close, and resize the drawer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawerDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawerDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSDrawerDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration": {
      "abstract": [
        {
          "text": "A set of methods that controllers can implement to enable an editor view to inform the controller when it has uncommitted changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEditorRegistration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEditorRegistration"
        }
      ],
      "role": "symbol",
      "title": "NSEditorRegistration",
      "type": "topic",
      "url": "/documentation/appkit/nseditorregistration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInputServerMouseTracker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInputServerMouseTracker"
        }
      ],
      "role": "symbol",
      "title": "NSInputServerMouseTracker",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInputServiceProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInputServiceProvider"
        }
      ],
      "role": "symbol",
      "title": "NSInputServiceProvider",
      "type": "topic",
      "url": "/documentation/appkit/nsinputserviceprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/actions": {
      "abstract": [
        {
          "text": "Standard actions that accessibility objects can perform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/actions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Actions",
      "type": "topic",
      "url": "/documentation/appkit/actions"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the app object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/app-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to individual table cells.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/column-sort-direction": {
      "abstract": [
        {
          "text": "Values that indicate the sort direction of a column (used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/column-sort-direction",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Column Sort Direction",
      "type": "topic",
      "url": "/documentation/appkit/column-sort-direction"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used with grid views, such as thumbnails and media browsers that present a grid of items. The children of a grid are ordered.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Grid View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/grid-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the items in a layout area.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Item Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-item-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/linkage-elements": {
      "abstract": [
        {
          "text": "Constants that specify links between accessibility elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/linkage-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Linkage Elements",
      "type": "topic",
      "url": "/documentation/appkit/linkage-elements"
    },
    "doc://com.apple.appkit/documentation/AppKit/measurement-unit-attributes": {
      "abstract": [
        {
          "text": "Values that indicate the unit values of a ruler or layout area (used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/measurement-unit-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Measurement Unit Attributes",
      "type": "topic",
      "url": "/documentation/appkit/measurement-unit-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/miscellaneous-attributes": {
      "abstract": [
        {
          "text": "Miscellaneous attributes that can apply to various types of elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/miscellaneous-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Miscellaneous Attributes",
      "type": "topic",
      "url": "/documentation/appkit/miscellaneous-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsaccessibility": {
      "abstract": [
        {
          "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols": {
      "abstract": [
        {
          "text": "A set of methods that controllers and UI elements can implement to manage editing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSEditor",
      "type": "topic",
      "url": "/documentation/appkit/nseditor-deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/orientations": {
      "abstract": [
        {
          "text": "Values that indicate the orientation of elements, such as scroll bars and split views. Use these values with an accessibility element’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/orientations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Orientations",
      "type": "topic",
      "url": "/documentation/appkit/orientations"
    },
    "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used in outline views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/ruler-marker-type-values": {
      "abstract": [
        {
          "text": "Values that indicate the marker type of an element. Use these values with an accessibility element’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/ruler-marker-type-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ruler Marker Type Values",
      "type": "topic",
      "url": "/documentation/appkit/ruler-marker-type-values"
    },
    "doc://com.apple.appkit/documentation/AppKit/ruler-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to ruler views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/ruler-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ruler View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/ruler-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/screen-matte-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to screen mattes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/screen-matte-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Screen Matte Attributes",
      "type": "topic",
      "url": "/documentation/appkit/screen-matte-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/slider-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to sliders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/slider-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Slider Attributes",
      "type": "topic",
      "url": "/documentation/appkit/slider-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/standard-attributes": {
      "abstract": [
        {
          "text": "Standard attributes that can be adopted by any accessibility object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Attributes",
      "type": "topic",
      "url": "/documentation/appkit/standard-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to tables and outlines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Table View and Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/table-view-and-outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants": {
      "abstract": [
        {
          "text": "Attributes and key constants used with attributed strings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Attributed-String Attributes and Constants",
      "type": "topic",
      "url": "/documentation/appkit/text-attributed-string-attributes-and-constants"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes specific to windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Window-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/window-specific-attributes"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1524809-accessibilityattributevalue": {
      "abstract": [
        {
          "text": "Returns the value of the receiver's parameterized attribute corresponding to the specified attribute name and parameter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributeValue"
        },
        {
          "kind": "text",
          "text": "(NSAccessibility.ParameterizedAttribute, "
        },
        {
          "kind": "identifier",
          "text": "forParameter"
        },
        {
          "kind": "text",
          "text": ": Any?) -> Any?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1524809-accessibilityattributevalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributeValue(_:forParameter:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1524809-accessibilityattributevalue"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1525181-accessibilityattributenames": {
      "abstract": [
        {
          "text": "Returns an array of attribute names supported by the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributeNames"
        },
        {
          "kind": "text",
          "text": "() -> [NSAccessibility.Attribute]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1525181-accessibilityattributenames",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributeNames()",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1525181-accessibilityattributenames"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1525455-accessibilityparameterizedattrib": {
      "abstract": [
        {
          "text": "Returns a list of parameterized attribute names supported by the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityParameterizedAttributeNames"
        },
        {
          "kind": "text",
          "text": "() -> [NSAccessibility.ParameterizedAttribute]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1525455-accessibilityparameterizedattrib",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityParameterizedAttributeNames()",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1525455-accessibilityparameterizedattrib"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1526100-accessibilityfocuseduielement": {
      "abstract": [
        {
          "text": "The deepest descendant of the accessibility hierarchy that has the focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityFocusedUIElement"
        },
        {
          "kind": "text",
          "text": ": Any?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1526100-accessibilityfocuseduielement",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityFocusedUIElement",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1526100-accessibilityfocuseduielement"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1526136-accessibilityhittest": {
      "abstract": [
        {
          "text": "Returns the deepest descendant of the accessibility hierarchy that contains the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityHitTest"
        },
        {
          "kind": "text",
          "text": "(NSPoint) -> Any?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1526136-accessibilityhittest",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHitTest(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1526136-accessibilityhittest"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1526439-accessibilityisignored": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the receiver should be ignored in the parent-child accessibility hierarchy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityIsIgnored"
        },
        {
          "kind": "text",
          "text": "() -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1526439-accessibilityisignored",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityIsIgnored()",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1526439-accessibilityisignored"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1527138-accessibilityarrayattributecount": {
      "abstract": [
        {
          "text": "Returns the count of the specified accessibility array attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityArrayAttributeCount"
        },
        {
          "kind": "text",
          "text": "(NSAccessibility.Attribute) -> Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1527138-accessibilityarrayattributecount",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityArrayAttributeCount(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1527138-accessibilityarrayattributecount"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1527905-accessibilityactionnames": {
      "abstract": [
        {
          "text": "Returns an array of action names supported by the accessibility element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityActionNames"
        },
        {
          "kind": "text",
          "text": "() -> [NSAccessibility.Action]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1527905-accessibilityactionnames",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityActionNames()",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1527905-accessibilityactionnames"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1528477-accessibilitysetvalue": {
      "abstract": [
        {
          "text": "Sets the value of the specified attribute in the receiver to the specified value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySetValue"
        },
        {
          "kind": "text",
          "text": "(Any?, "
        },
        {
          "kind": "identifier",
          "text": "forAttribute"
        },
        {
          "kind": "text",
          "text": ": NSAccessibility.Attribute)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1528477-accessibilitysetvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySetValue(_:forAttribute:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1528477-accessibilitysetvalue"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1529207-accessibilityisattributesettable": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the value for the specified attribute in the receiver can be set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityIsAttributeSettable"
        },
        {
          "kind": "text",
          "text": "(NSAccessibility.Attribute) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1529207-accessibilityisattributesettable",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityIsAttributeSettable(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1529207-accessibilityisattributesettable"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1532465-accessibilityattributevalue": {
      "abstract": [
        {
          "text": "Returns the value of the specified attribute in the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributeValue"
        },
        {
          "kind": "text",
          "text": "(NSAccessibility.Attribute) -> Any?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1532465-accessibilityattributevalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributeValue(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1532465-accessibilityattributevalue"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1533500-accessibilityactiondescription": {
      "abstract": [
        {
          "text": "Returns a localized description of the specified action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityActionDescription"
        },
        {
          "kind": "text",
          "text": "(NSAccessibility.Action) -> String?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1533500-accessibilityactiondescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityActionDescription(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1533500-accessibilityactiondescription"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1533528-accessibilityperformaction": {
      "abstract": [
        {
          "text": "Performs the action associated with the specified action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityPerformAction"
        },
        {
          "kind": "text",
          "text": "(NSAccessibility.Action)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1533528-accessibilityperformaction",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityPerformAction(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1533528-accessibilityperformaction"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1533558-accessibilityindex": {
      "abstract": [
        {
          "text": "Returns the index of the specified accessibility child in the parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "ofChild"
        },
        {
          "kind": "text",
          "text": ": Any) -> Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1533558-accessibilityindex",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityIndex(ofChild:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1533558-accessibilityindex"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1534050-accessibilitynotifieswhendestroy": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a custom accessibility object sends a notification when its corresponding UI element is destroyed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityNotifiesWhenDestroyed"
        },
        {
          "kind": "text",
          "text": ": Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1534050-accessibilitynotifieswhendestroy",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityNotifiesWhenDestroyed",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1534050-accessibilitynotifieswhendestroy"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1535843-accessibilitysetoverridevalue": {
      "abstract": [
        {
          "text": "Overrides the specified attribute in the receiver or adds it if it does not exist, and sets its value to the specified value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySetOverrideValue"
        },
        {
          "kind": "text",
          "text": "(Any?, "
        },
        {
          "kind": "identifier",
          "text": "forAttribute"
        },
        {
          "kind": "text",
          "text": ": NSAccessibility.Attribute) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1535843-accessibilitysetoverridevalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySetOverrideValue(_:forAttribute:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1535843-accessibilitysetoverridevalue"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1535909-accessibilityarrayattributevalue": {
      "abstract": [
        {
          "text": "Returns a subarray of values of an accessibility array attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityArrayAttributeValues"
        },
        {
          "kind": "text",
          "text": "(NSAccessibility.Attribute, "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": Int, "
        },
        {
          "kind": "identifier",
          "text": "maxCount"
        },
        {
          "kind": "text",
          "text": ": Int) -> [Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1535909-accessibilityarrayattributevalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityArrayAttributeValues(_:index:maxCount:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1535909-accessibilityarrayattributevalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
        "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
        "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
        "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Available-Methods-and-Properties",
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1526100-accessibilityfocuseduielement",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1526136-accessibilityhittest",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1534050-accessibilitynotifieswhendestroy"
      ],
      "title": "Available Methods and Properties"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
        "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
        "doc://com.apple.appkit/documentation/AppKit/slider-attributes",
        "doc://com.apple.appkit/documentation/AppKit/screen-matte-attributes",
        "doc://com.apple.appkit/documentation/AppKit/ruler-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/linkage-elements",
        "doc://com.apple.appkit/documentation/AppKit/miscellaneous-attributes",
        "doc://com.apple.appkit/documentation/AppKit/column-sort-direction",
        "doc://com.apple.appkit/documentation/AppKit/measurement-unit-attributes",
        "doc://com.apple.appkit/documentation/AppKit/orientations",
        "doc://com.apple.appkit/documentation/AppKit/ruler-marker-type-values",
        "doc://com.apple.appkit/documentation/AppKit/actions"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1533500-accessibilityactiondescription",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1527905-accessibilityactionnames",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1527138-accessibilityarrayattributecount",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1535909-accessibilityarrayattributevalue",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1525181-accessibilityattributenames",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1532465-accessibilityattributevalue",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1524809-accessibilityattributevalue",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1533558-accessibilityindex",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1529207-accessibilityisattributesettable",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1526439-accessibilityisignored",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1525455-accessibilityparameterizedattrib",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1533528-accessibilityperformaction",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1535843-accessibilitysetoverridevalue",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1528477-accessibilitysetvalue"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Available-Methods-and-Properties",
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1526100-accessibilityfocuseduielement",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1526136-accessibilityhittest",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1534050-accessibilitynotifieswhendestroy"
              ],
              "title": "Available Methods and Properties"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
                "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
                "doc://com.apple.appkit/documentation/AppKit/slider-attributes",
                "doc://com.apple.appkit/documentation/AppKit/screen-matte-attributes",
                "doc://com.apple.appkit/documentation/AppKit/ruler-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/linkage-elements",
                "doc://com.apple.appkit/documentation/AppKit/miscellaneous-attributes",
                "doc://com.apple.appkit/documentation/AppKit/column-sort-direction",
                "doc://com.apple.appkit/documentation/AppKit/measurement-unit-attributes",
                "doc://com.apple.appkit/documentation/AppKit/orientations",
                "doc://com.apple.appkit/documentation/AppKit/ruler-marker-type-values",
                "doc://com.apple.appkit/documentation/AppKit/actions"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1533500-accessibilityactiondescription",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1527905-accessibilityactionnames",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1527138-accessibilityarrayattributecount",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1535909-accessibilityarrayattributevalue",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1525181-accessibilityattributenames",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1532465-accessibilityattributevalue",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1524809-accessibilityattributevalue",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1533558-accessibilityindex",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1529207-accessibilityisattributesettable",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1526439-accessibilityisignored",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1525455-accessibilityparameterizedattrib",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1533528-accessibilityperformaction",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1535843-accessibilitysetoverridevalue",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1528477-accessibilitysetvalue"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
                "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11535909-accessibilityarrayattributevalue/title",
          "value": "accessibilityArrayAttributeValues:index:maxCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/title",
          "value": "NSDrawerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/title",
          "value": "NSInputServiceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServiceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServiceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11533558-accessibilityindex/title",
          "value": "accessibilityIndexOfChild:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11533528-accessibilityperformaction/title",
          "value": "accessibilityPerformAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11532465-accessibilityattributevalue/title",
          "value": "accessibilityAttributeValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11526439-accessibilityisignored/title",
          "value": "accessibilityIsIgnored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11533500-accessibilityactiondescription/title",
          "value": "accessibilityActionDescription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11525181-accessibilityattributenames/title",
          "value": "accessibilityAttributeNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/title",
          "value": "NSEditorRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditorRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditorRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/title",
          "value": "NSInputServerMouseTracker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11535843-accessibilitysetoverridevalue/title",
          "value": "accessibilitySetOverrideValue:forAttribute:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11528477-accessibilitysetvalue/title",
          "value": "accessibilitySetValue:forAttribute:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11527138-accessibilityarrayattributecount/title",
          "value": "accessibilityArrayAttributeCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11527905-accessibilityactionnames/title",
          "value": "accessibilityActionNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11525455-accessibilityparameterizedattrib/title",
          "value": "accessibilityParameterizedAttributeNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11524809-accessibilityattributevalue/title",
          "value": "accessibilityAttributeValue:forParameter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityLayoutArea~1accessibilityFocusedUIElement/title",
          "value": "accessibilityFocusedUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityLayoutArea~1accessibilityFocusedUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityFocusedUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11529207-accessibilityisattributesettable/title",
          "value": "accessibilityIsAttributeSettable:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11526136-accessibilityhittest/title",
          "value": "accessibilityHitTest:"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
