{"sections":[],"abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as an outline view."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityOutline"},{"kind":"text","text":" : "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","preciseIdentifier":"c:objc(pl)NSAccessibilityTable","kind":"typeIdentifier","text":"NSAccessibilityTable"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"Use this protocol when you want a user interface element to behave like an outline—a view that uses a row-and-column format to display hierarchical data that can expand and collapse—in the accessibility hierarchy.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You can further enhance the adopting element by implementing any of the information properties or action methods that the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","type":"reference","isActive":true},{"text":" protocol declares.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Any class that adopts this protocol must implement all of its methods, and the required methods of any protocol it inherits from. The compiler may require you to override some methods that your ancestors have already implemented. Simply follow the compiler’s warnings, and reimplement these methods as necessary.","type":"text"}],"type":"paragraph"}],"name":"Explicit Implementation Required","type":"aside","style":"note"},{"inlineContent":[{"text":"Although the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline"},{"text":" protocol doesn’t declare any methods, it does conform to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable"},{"text":" protocol. You may need to explicitly implement methods from any of the protocols that ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline"},{"text":" conforms to.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"relationshipsSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSOutlineView"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityOutline"}],"platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"externalID":"c:objc(pl)NSAccessibilityOutline","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityOutline"}],"role":"symbol","title":"NSAccessibilityOutline","symbolKind":"protocol","modules":[{"name":"AppKit"}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"variants":[{"paths":["/documentation/appkit/nsaccessibilityoutline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsaccessibilityoutline"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRow"],"anchor":"Lists","title":"Lists","generated":true}],"references":{"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRow":{"abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a row for a table, list, or outline view."}],"url":"/documentation/appkit/nsaccessibilityrow","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityRow"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRow","title":"NSAccessibilityRow","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityRow"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline","url":"/documentation/appkit/nsaccessibilityoutline","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NSAccessibilityOutline","kind":"identifier"}],"title":"NSAccessibilityOutline","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as an outline view."}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityOutline","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol":{"title":"NSAccessibilityElementProtocol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to interact with an assistive app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityelementprotocol"},"doc://com.apple.appkit/documentation/AppKit/NSOutlineView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NSOutlineView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A view that uses a row-and-column format to display hierarchical data like directories and files that can be expanded and collapsed."}],"url":"/documentation/appkit/nsoutlineview","navigatorTitle":[{"kind":"identifier","text":"NSOutlineView"}],"title":"NSOutlineView","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOutlineView"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList","url":"/documentation/appkit/nsaccessibilitylist","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"NSAccessibilityList","kind":"identifier"}],"title":"NSAccessibilityList","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a list view."}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityList","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable":{"abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a table view."}],"type":"topic","title":"NSAccessibilityTable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityTable"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","role":"symbol","url":"/documentation/appkit/nsaccessibilitytable","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityTable"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup":{"url":"/documentation/appkit/nsaccessibilitygroup","title":"NSAccessibilityGroup","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityGroup","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSAccessibilityGroup","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup","abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to act as a container for other user interface elements.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Protocol","op":"replace"},{"value":"NSAccessibilityOutline","op":"replace","path":"/metadata/title"},{"value":"protocol","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"NSAccessibilityOutline"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"NSAccessibilityOutline","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSOutlineView"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"op":"replace","path":"/relationshipsSections"},{"value":[{"title":"Lists","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRow"],"anchor":"Lists"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityOutline"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","preciseIdentifier":"c:objc(pl)NSAccessibilityTable","text":"NSAccessibilityTable"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"NSAccessibilityRow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRow/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSAccessibilityRow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRow/fragments"},{"op":"replace","value":[{"text":"NSAccessibilityRow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRow/navigatorTitle"},{"op":"replace","value":"NSAccessibilityOutline","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOutline/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSAccessibilityOutline"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOutline/fragments"},{"value":[{"kind":"identifier","text":"NSAccessibilityOutline"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOutline/navigatorTitle"},{"value":"NSAccessibilityElement","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title"},{"value":[{"kind":"identifier","text":"NSAccessibilityElement"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle","value":[{"text":"NSAccessibilityElement","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/title","value":"NSOutlineView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/fragments","value":[{"text":"NSOutlineView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/navigatorTitle","value":[{"text":"NSOutlineView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","value":"NSAccessibility","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","value":[{"text":"NSAccessibility","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","value":[{"text":"NSAccessibility","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityList/title","value":"NSAccessibilityList","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityList/fragments","value":[{"kind":"identifier","text":"NSAccessibilityList"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityList/navigatorTitle","value":[{"text":"NSAccessibilityList","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/title","value":"NSAccessibilityTable","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/fragments","value":[{"text":"NSAccessibilityTable","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityTable"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityGroup/title","value":"NSAccessibilityGroup","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityGroup/fragments","value":[{"text":"NSAccessibilityGroup","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityGroup/navigatorTitle","value":[{"text":"NSAccessibilityGroup","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}