{
  "abstract": [
    {
      "text": "A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibilityButton",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSAccessibilityButton"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityButton"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSAccessibilityButton"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibilityButton"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSAccessibilityElement",
              "text": "NSAccessibilityElementProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this protocol when you want a user interface element to behave like a button—a control that triggers an action when the user clicks it—in the accessibility hierarchy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can further enhance the adopting element by implementing any of the information properties or action methods that the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol declares.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Any class that adopts this protocol must implement all of its methods, and the required methods of any protocol it inherits from. The compiler may require you to override some methods that your ancestors have already implemented. Simply follow the compiler’s warnings, and reimplement these methods as necessary.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Explicit Implementation Required",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityButton"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitybutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton/accessibilityLabel()": {
      "abstract": [
        {
          "text": "Returns a short description of the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLabel"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton/accessibilityLabel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLabel"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLabel()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitybutton/accessibilitylabel()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton/accessibilityPerformPress()": {
      "abstract": [
        {
          "text": "Simulates clicking the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityPerformPress"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton/accessibilityPerformPress()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityPerformPress"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityPerformPress()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitybutton/accessibilityperformpress()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a checkbox.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityCheckBox"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCheckBox"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCheckBox",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycheckbox"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityelementprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a radio button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityRadioButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRadioButton"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRadioButton",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityradiobutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilitySwitch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySwitch"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilitySwitch",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityswitch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton": {
      "abstract": [
        {
          "text": "A control that defines an area on the screen that a user clicks to trigger an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButton": {
      "abstract": [
        {
          "text": "A control for selecting an item from a list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPopUpButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopUpButton"
        }
      ],
      "role": "symbol",
      "title": "NSPopUpButton",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton": {
      "abstract": [
        {
          "text": "The appearance and behavior of an item in the systemwide menu bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStatusBarButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStatusBarButton"
        }
      ],
      "role": "symbol",
      "title": "NSStatusBarButton",
      "type": "topic",
      "url": "/documentation/appkit/nsstatusbarbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSwitch": {
      "abstract": [
        {
          "text": "A control that offers a binary choice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSwitch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSwitch"
        }
      ],
      "role": "symbol",
      "title": "NSSwitch",
      "type": "topic",
      "url": "/documentation/appkit/nsswitch"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButton",
        "doc://com.apple.appkit/documentation/AppKit/NSStatusBarButton",
        "doc://com.apple.appkit/documentation/AppKit/NSSwitch"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox"
      ],
      "title": "Buttons"
    }
  ],
  "topicSections": [
    {
      "anchor": "Supporting-Accessibility",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton/accessibilityLabel()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton/accessibilityPerformPress()"
      ],
      "title": "Supporting Accessibility"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityButton"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Supporting-Accessibility",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton/accessibilityLabel()",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityButton/accessibilityPerformPress()"
              ],
              "title": "Supporting Accessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Buttons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySwitch",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCheckBox"
              ],
              "title": "Buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityButton"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSAccessibilityElement",
                    "text": "NSAccessibilityElement"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButton/title",
          "value": "NSPopUpButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton/title",
          "value": "NSAccessibilityButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/title",
          "value": "NSStatusBarButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStatusBarButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStatusBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCheckBox/title",
          "value": "NSAccessibilityCheckBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCheckBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCheckBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCheckBox/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCheckBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySwitch/title",
          "value": "NSAccessibilitySwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySwitch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSwitch/title",
          "value": "NSSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSwitch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/title",
          "value": "NSAccessibilityRadioButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRadioButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRadioButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton~1accessibilityPerformPress()/title",
          "value": "accessibilityPerformPress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton~1accessibilityPerformPress()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityPerformPress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title",
          "value": "NSButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton~1accessibilityLabel()/title",
          "value": "accessibilityLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityButton~1accessibilityLabel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilitybutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibilitybutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
