{
  "abstract": [
    {
      "text": "A delegate for a custom rotor that finds the next item result after performing a search with the specified search parameters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSAccessibilityCustomRotorItemSearchDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityCustomRotorItemSearchDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSAccessibilityCustomRotorItemSearchDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/SearchParameters": {
      "abstract": [
        {
          "text": "Search parameters for a custom rotor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SearchParameters"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/SearchParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SearchParameters"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCustomRotor.SearchParameters",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/searchparameters"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemSearchDelegate": {
      "abstract": [
        {
          "text": "The delegate for finding the next item result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemSearchDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemSearchDelegate"
        }
      ],
      "role": "symbol",
      "title": "itemSearchDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/itemsearchdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate": {
      "abstract": [
        {
          "text": "A delegate for a custom rotor that finds the next item result after performing a search with the specified search parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCustomRotorItemSearchDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotoritemsearchdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate/rotor(_:resultFor:)": {
      "abstract": [
        {
          "text": "Performs a search with the specified search parameters and returns the item result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
          "text": "NSAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resultFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
          "text": "NSAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotorSearchParameters",
          "text": "SearchParameters"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
          "text": "NSAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotorItemResult",
          "text": "ItemResult"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate/rotor(_:resultFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotor:resultForSearchParameters:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "rotor(_:resultFor:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotoritemsearchdelegate/rotor(_:resultfor:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigating-to-the-Next-Item",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemSearchDelegate"
      ],
      "title": "Navigating to the Next Item"
    }
  ],
  "topicSections": [
    {
      "anchor": "Finding-the-Next-Item",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate/rotor(_:resultFor:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/SearchParameters"
      ],
      "title": "Finding the Next Item"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Finding-the-Next-Item",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate/rotor(_:resultFor:)",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/SearchParameters"
              ],
              "title": "Finding the Next Item"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigating-to-the-Next-Item",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemSearchDelegate"
              ],
              "title": "Navigating to the Next Item"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityCustomRotorItemSearchDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/title",
          "value": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1SearchParameters/title",
          "value": "NSAccessibilityCustomRotorSearchParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1SearchParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorSearchParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1SearchParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorSearchParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1itemSearchDelegate/title",
          "value": "itemSearchDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1itemSearchDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate~1rotor(_:resultFor:)/title",
          "value": "rotor:resultForSearchParameters:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate~1rotor(_:resultFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rotor:resultForSearchParameters:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilitycustomrotoritemsearchdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibilitycustomrotoritemsearchdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
