{
  "abstract": [
    {
      "text": "A context-sensitive function that helps VoiceOver users find the next instance of a related accessibility element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSAccessibilityCustomRotor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSAccessibilityCustomRotor"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityCustomRotor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSAccessibilityCustomRotor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Assistive apps, like VoiceOver, provide interfaces to quickly search apps for content of a specific type. For example, in a web browser, a user can quickly explore a list of navigational links or buttons using VoiceOver’s content menus.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides a way for apps to vend their own content menus. For example, Pages can create a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Headings",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " custom rotor that allows assistive apps to search the Pages document for all headings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityCustomRotors": {
      "abstract": [
        {
          "text": "The custom rotors of the current accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityCustomRotors"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityCustomRotors",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomRotors",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-c.protocol/accessibilitycustomrotors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor": {
      "abstract": [
        {
          "text": "A context-sensitive function that helps VoiceOver users find the next instance of a related accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotor"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCustomRotor",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/RotorType": {
      "abstract": [
        {
          "text": "Constants that indicate the type of content that the rotor represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RotorType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/RotorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RotorType"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCustomRotor.RotorType",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/rotortype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(label:itemSearchDelegate:)": {
      "abstract": [
        {
          "text": "Creates a custom rotor with the specified label and item search delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(label:itemSearchDelegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLabel:itemSearchDelegate:"
        }
      ],
      "role": "symbol",
      "title": "init(label:itemSearchDelegate:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/init(label:itemsearchdelegate:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(rotorType:itemSearchDelegate:)": {
      "abstract": [
        {
          "text": "Creates a custom rotor with the specified rotor type and item search delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rotorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
          "text": "NSAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAccessibilityCustomRotorType",
          "text": "RotorType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(rotorType:itemSearchDelegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRotorType:itemSearchDelegate:"
        }
      ],
      "role": "symbol",
      "title": "init(rotorType:itemSearchDelegate:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/init(rotortype:itemsearchdelegate:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemLoadingDelegate": {
      "abstract": [
        {
          "text": "The delegate for loading item results that don’t have a backing UI element at loading time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemLoadingDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityElementLoading",
          "text": "NSAccessibilityElementLoading"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemLoadingDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemLoadingDelegate"
        }
      ],
      "role": "symbol",
      "title": "itemLoadingDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/itemloadingdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemSearchDelegate": {
      "abstract": [
        {
          "text": "The delegate for finding the next item result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemSearchDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemSearchDelegate"
        }
      ],
      "role": "symbol",
      "title": "itemSearchDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/itemsearchdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/label": {
      "abstract": [
        {
          "text": "The localized label that assistive apps use to describe the custom rotor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/label"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/type": {
      "abstract": [
        {
          "text": "The type of content that the rotor represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
          "text": "NSAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAccessibilityCustomRotorType",
          "text": "RotorType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/type"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate": {
      "abstract": [
        {
          "text": "A delegate for a custom rotor that finds the next item result after performing a search with the specified search parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCustomRotorItemSearchDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotoritemsearchdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementLoading": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary for an accessibility element to support loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementLoading"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementLoading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementLoading"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityElementLoading",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityelementloading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityCustomRotors()": {
      "abstract": [
        {
          "text": "Returns the custom rotors of the current accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomRotors"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
          "text": "NSAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityCustomRotors()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "accessibilityCustomRotors()",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/accessibilitycustomrotors()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityCustomRotors(_:)": {
      "abstract": [
        {
          "text": "Sets the custom rotors of the current accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessibilityCustomRotors"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
          "text": "NSAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityCustomRotors(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "setAccessibilityCustomRotors(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol/setaccessibilitycustomrotors(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assigning-Rotors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/accessibilityCustomRotors()",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol/setAccessibilityCustomRotors(_:)"
      ],
      "title": "Assigning Rotors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Rotor",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(label:itemSearchDelegate:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(rotorType:itemSearchDelegate:)"
      ],
      "title": "Creating a Rotor"
    },
    {
      "anchor": "Navigating-to-the-Next-Item",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemSearchDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate"
      ],
      "title": "Navigating to the Next Item"
    },
    {
      "anchor": "Loading-the-Item",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemLoadingDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementLoading"
      ],
      "title": "Loading the Item"
    },
    {
      "anchor": "Getting-the-Rotor-Type",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/type",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/RotorType"
      ],
      "title": "Getting the Rotor Type"
    },
    {
      "anchor": "Identifying-the-Rotor",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/label"
      ],
      "title": "Identifying the Rotor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityCustomRotor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Rotor",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(label:itemSearchDelegate:)",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(rotorType:itemSearchDelegate:)"
              ],
              "title": "Creating a Rotor"
            },
            {
              "anchor": "Navigating-to-the-Next-Item",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemSearchDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate"
              ],
              "title": "Navigating to the Next Item"
            },
            {
              "anchor": "Loading-the-Item",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/itemLoadingDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementLoading"
              ],
              "title": "Loading the Item"
            },
            {
              "anchor": "Getting-the-Rotor-Type",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/type",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/RotorType"
              ],
              "title": "Getting the Rotor Type"
            },
            {
              "anchor": "Identifying-the-Rotor",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/label"
              ],
              "title": "Identifying the Rotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assigning-Rotors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityCustomRotors"
              ],
              "title": "Assigning Rotors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityCustomRotor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/title",
          "value": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1init(label:itemSearchDelegate:)/title",
          "value": "initWithLabel:itemSearchDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1init(label:itemSearchDelegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLabel:itemSearchDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1label/title",
          "value": "label"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "label"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1init(rotorType:itemSearchDelegate:)/title",
          "value": "initWithRotorType:itemSearchDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1init(rotorType:itemSearchDelegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRotorType:itemSearchDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1itemLoadingDelegate/title",
          "value": "itemLoadingDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1itemLoadingDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemLoadingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementLoading/title",
          "value": "NSAccessibilityElementLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementLoading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElementLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementLoading/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElementLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1RotorType/title",
          "value": "NSAccessibilityCustomRotorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1RotorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1RotorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1itemSearchDelegate/title",
          "value": "itemSearchDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1itemSearchDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor/title",
          "value": "NSAccessibilityCustomRotor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilitycustomrotor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibilitycustomrotor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
