{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityTable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSAccessibilityGroup","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup","text":"NSAccessibilityGroup"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"text":"Use this protocol when you want a user interface element to behave like a table—a view that uses a row-and-column format to display a set of related records and their attributes—in the accessibility hierarchy.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You can further enhance the adopting element by implementing any of the information properties or action methods that the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"},{"text":" protocol declares.","type":"text"}],"type":"paragraph"},{"name":"Explicit Implementation Required","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Any class that adopts this protocol must implement all of its methods, and the required methods of any protocol it inherits from. The compiler may require you to override some methods that your ancestors have already implemented. Simply follow the compiler’s warnings, and reimplement these methods as necessary."}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRow"],"anchor":"Lists","generated":true,"title":"Lists"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsaccessibilitytable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsaccessibilitytable"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:objc(pl)NSAccessibilityTable","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityTable"}],"modules":[{"name":"AppKit"}],"symbolKind":"protocol","title":"NSAccessibilityTable","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityTable"}]},"relationshipsSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSOutlineView","doc://com.apple.appkit/documentation/AppKit/NSTableView"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a table view.","type":"text"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumnHeaderUIElements()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityLabel()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRowHeaderUIElements()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedCells()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleCells()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/setAccessibilitySelectedRows(_:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityHeaderGroup()"],"anchor":"Supporting-Accessibility","title":"Supporting Accessibility"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleColumns()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleColumns()","abstract":[{"text":"Returns the visible columns for the table.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"accessibilityVisibleColumns","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityVisibleColumns","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"title":"accessibilityVisibleColumns()","kind":"symbol","url":"/documentation/appkit/nsaccessibilitytable/accessibilityvisiblecolumns()","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleRows()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleRows()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityVisibleRows","kind":"identifier"},{"text":"() -> [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSAccessibilityRow","text":"NSAccessibilityRow","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"type":"topic","abstract":[{"text":"Returns the visible rows for the table.","type":"text"}],"url":"/documentation/appkit/nsaccessibilitytable/accessibilityvisiblerows()","title":"accessibilityVisibleRows()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"accessibilityVisibleRows","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedColumns()":{"abstract":[{"text":"Returns the currently selected columns for the table.","type":"text"}],"navigatorTitle":[{"text":"accessibilitySelectedColumns","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedColumns()","url":"/documentation/appkit/nsaccessibilitytable/accessibilityselectedcolumns()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilitySelectedColumns","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"role":"symbol","title":"accessibilitySelectedColumns()"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup":{"url":"/documentation/appkit/nsaccessibilitygroup","title":"NSAccessibilityGroup","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityGroup","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSAccessibilityGroup","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup","abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to act as a container for other user interface elements.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleCells()":{"abstract":[{"text":"Returns the visible cells for the table.","type":"text"}],"type":"topic","title":"accessibilityVisibleCells()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityVisibleCells","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleCells()","role":"symbol","url":"/documentation/appkit/nsaccessibilitytable/accessibilityvisiblecells()","navigatorTitle":[{"text":"accessibilityVisibleCells","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList","url":"/documentation/appkit/nsaccessibilitylist","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"NSAccessibilityList","kind":"identifier"}],"title":"NSAccessibilityList","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a list view."}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityList","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumnHeaderUIElements()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumnHeaderUIElements()","abstract":[{"type":"text","text":"Returns the column header accessibility elements for the table."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityColumnHeaderUIElements"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityColumnHeaderUIElements"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"accessibilityColumnHeaderUIElements()","kind":"symbol","url":"/documentation/appkit/nsaccessibilitytable/accessibilitycolumnheaderuielements()","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityLabel()":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityLabel"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"accessibilityLabel()","url":"/documentation/appkit/nsaccessibilitytable/accessibilitylabel()","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityLabel()","type":"topic","abstract":[{"text":"Returns a short description of the table.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityLabel"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable":{"abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a table view."}],"type":"topic","title":"NSAccessibilityTable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityTable"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","role":"symbol","url":"/documentation/appkit/nsaccessibilitytable","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityTable"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRow":{"abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a row for a table, list, or outline view."}],"url":"/documentation/appkit/nsaccessibilityrow","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityRow"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRow","title":"NSAccessibilityRow","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityRow"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedRows()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilitySelectedRows","kind":"identifier"},{"text":"() -> [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSAccessibilityRow","text":"NSAccessibilityRow","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedRows()","abstract":[{"text":"Returns the currently selected rows for the table.","type":"text"}],"type":"topic","title":"accessibilitySelectedRows()","kind":"symbol","navigatorTitle":[{"text":"accessibilitySelectedRows","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilitytable/accessibilityselectedrows()","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRowHeaderUIElements()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRowHeaderUIElements()","abstract":[{"text":"Returns the row header accessibility elements for the table.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityRowHeaderUIElements","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"title":"accessibilityRowHeaderUIElements()","url":"/documentation/appkit/nsaccessibilitytable/accessibilityrowheaderuielements()","type":"topic","navigatorTitle":[{"text":"accessibilityRowHeaderUIElements","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityHeaderGroup()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityHeaderGroup","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"accessibilityHeaderGroup()","url":"/documentation/appkit/nsaccessibilitytable/accessibilityheadergroup()","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityHeaderGroup()","type":"topic","abstract":[{"text":"Returns the header group for the table.","type":"text"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"accessibilityHeaderGroup","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/setAccessibilitySelectedRows(_:)":{"abstract":[{"text":"Sets the table’s currently selected rows.","type":"text"}],"type":"topic","title":"setAccessibilitySelectedRows(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAccessibilitySelectedRows","kind":"identifier"},{"text":"([any ","kind":"text"},{"text":"NSAccessibilityRow","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSAccessibilityRow"},{"text":"])","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/setAccessibilitySelectedRows(_:)","role":"symbol","url":"/documentation/appkit/nsaccessibilitytable/setaccessibilityselectedrows(_:)","navigatorTitle":[{"text":"setAccessibilitySelectedRows:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSOutlineView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NSOutlineView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A view that uses a row-and-column format to display hierarchical data like directories and files that can be expanded and collapsed."}],"url":"/documentation/appkit/nsoutlineview","navigatorTitle":[{"kind":"identifier","text":"NSOutlineView"}],"title":"NSOutlineView","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOutlineView"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumns()":{"abstract":[{"text":"Returns the column accessibility elements for the table.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityColumns"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumns()","url":"/documentation/appkit/nsaccessibilitytable/accessibilitycolumns()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityColumns"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"role":"symbol","title":"accessibilityColumns()"},"doc://com.apple.appkit/documentation/AppKit/NSTableView":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSTableView","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records."}],"url":"/documentation/appkit/nstableview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView","title":"NSTableView"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline","url":"/documentation/appkit/nsaccessibilityoutline","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NSAccessibilityOutline","kind":"identifier"}],"title":"NSAccessibilityOutline","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as an outline view."}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityOutline","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedCells()":{"abstract":[{"text":"The currently selected cells for the table.","type":"text"}],"navigatorTitle":[{"text":"accessibilitySelectedCells","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedCells()","url":"/documentation/appkit/nsaccessibilitytable/accessibilityselectedcells()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilitySelectedCells","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"role":"symbol","title":"accessibilitySelectedCells()"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRows()":{"url":"/documentation/appkit/nsaccessibilitytable/accessibilityrows()","title":"accessibilityRows()","kind":"symbol","required":true,"abstract":[{"text":"Returns the row accessibility elements for the table.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRows()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accessibilityRows","kind":"identifier"},{"kind":"text","text":"() -> [any "},{"preciseIdentifier":"c:objc(pl)NSAccessibilityRow","text":"NSAccessibilityRow","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityRows"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol":{"title":"NSAccessibilityElementProtocol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to interact with an assistive app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityelementprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Protocol"},{"path":"/metadata/title","op":"replace","value":"NSAccessibilityTable"},{"op":"replace","path":"/metadata/symbolKind","value":"protocol"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSAccessibilityTable"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"text":"NSAccessibilityTable","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"op":"replace","path":"/topicSections","value":[{"title":"Supporting Accessibility","anchor":"Supporting-Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumnHeaderUIElements()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityLabel()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRowHeaderUIElements()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedCells()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleCells()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/setAccessibilitySelectedRows(_:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityHeaderGroup()"]}]},{"op":"replace","path":"/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline"],"title":"Inherited By","type":"inheritedBy"},{"kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableView"],"title":"Conforming Types","type":"conformingTypes"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityList","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOutline","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRow"],"title":"Lists","generated":true,"anchor":"Lists"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityTable","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSAccessibilityGroup","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSAccessibilityGroup","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityGroup"},{"text":">","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleColumns()/title","value":"accessibilityVisibleColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleColumns()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityVisibleColumns","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleRows()/title","value":"accessibilityVisibleRows"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleRows()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityVisibleRows","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedColumns()/title","value":"accessibilitySelectedColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedColumns()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilitySelectedColumns","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityGroup/title","value":"NSAccessibilityGroup"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityGroup/fragments","value":[{"kind":"identifier","text":"NSAccessibilityGroup"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityGroup/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityGroup"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleCells()/title","value":"accessibilityVisibleCells"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleCells()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityVisibleCells","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityList/title","value":"NSAccessibilityList"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityList/fragments","value":[{"kind":"identifier","text":"NSAccessibilityList"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityList/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityList"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityColumnHeaderUIElements()/title","value":"accessibilityColumnHeaderUIElements"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityColumnHeaderUIElements()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityColumnHeaderUIElements"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityLabel()/title","value":"accessibilityLabel"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityLabel()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityLabel","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/title","value":"NSAccessibilityTable"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/fragments","value":[{"kind":"identifier","text":"NSAccessibilityTable"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityTable"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRow/title","value":"NSAccessibilityRow"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRow/fragments","value":[{"kind":"identifier","text":"NSAccessibilityRow"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRow/navigatorTitle","value":[{"text":"NSAccessibilityRow","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","value":"NSAccessibility"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","value":[{"text":"NSAccessibility","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","value":[{"text":"NSAccessibility","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedRows()/title","value":"accessibilitySelectedRows"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedRows()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilitySelectedRows","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityRowHeaderUIElements()/title","value":"accessibilityRowHeaderUIElements"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityRowHeaderUIElements()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityRowHeaderUIElements","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityHeaderGroup()/title","value":"accessibilityHeaderGroup"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityHeaderGroup()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityHeaderGroup","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1setAccessibilitySelectedRows(_:)/title","value":"setAccessibilitySelectedRows:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1setAccessibilitySelectedRows(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAccessibilitySelectedRows:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/title","value":"NSOutlineView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/fragments","value":[{"text":"NSOutlineView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/navigatorTitle","value":[{"kind":"identifier","text":"NSOutlineView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityColumns()/title","value":"accessibilityColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityColumns()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityColumns"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title","value":"NSTableView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments","value":[{"kind":"identifier","text":"NSTableView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle","value":[{"text":"NSTableView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOutline/title","value":"NSAccessibilityOutline"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOutline/fragments","value":[{"text":"NSAccessibilityOutline","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOutline/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityOutline"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedCells()/title","value":"accessibilitySelectedCells"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedCells()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilitySelectedCells"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityRows()/title","value":"accessibilityRows"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityRows()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityRows","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title","value":"NSAccessibilityElement"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments","value":[{"kind":"identifier","text":"NSAccessibilityElement"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle","value":[{"text":"NSAccessibilityElement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}