{"seeAlsoSections":[{"anchor":"Value-Controls","title":"Value Controls","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySlider"],"generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"topicSections":[{"anchor":"Supporting-Accessibility","title":"Supporting Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityLabel()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformDecrement()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformIncrement()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityValue()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityStepper"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityStepper"}],"role":"symbol","modules":[{"name":"AppKit"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"roleHeading":"Protocol","title":"NSAccessibilityStepper","externalID":"c:objc(pl)NSAccessibilityStepper"},"kind":"symbol","abstract":[{"text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a stepper.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityStepper","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSAccessibilityElementProtocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSAccessibilityElement"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol when you want a user interface element to behave like a stepper—a control with up and down arrow buttons for incrementing or decrementing a value—in the accessibility hierarchy."}]},{"type":"paragraph","inlineContent":[{"text":"You can further enhance the adopting element by implementing any of the information properties or action methods that the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","type":"reference","isActive":true},{"text":" protocol declares.","type":"text"}]},{"type":"aside","name":"Explicit Implementation Required","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Any class that adopts this protocol must implement all of its methods, and the required methods of any protocol it inherits from. The compiler may require you to override some methods that your ancestors have already implemented. Simply follow the compiler’s warnings, and reimplement these methods as necessary."}]}]}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStepper"],"type":"conformingTypes"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsaccessibilitystepper"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsaccessibilitystepper"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityLabel()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityLabel()","title":"accessibilityLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityLabel"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"/documentation/appkit/nsaccessibilitystepper/accessibilitylabel()","kind":"symbol","type":"topic","role":"symbol","required":true,"abstract":[{"type":"text","text":"Returns a short description of the stepper."}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityLabel"}]},"doc://com.apple.appkit/documentation/AppKit/NSStepper":{"abstract":[{"type":"text","text":"An interface with up and down arrow buttons for incrementing or decrementing a value."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSStepper"}],"url":"/documentation/appkit/nsstepper","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStepper","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSStepper"}],"type":"topic","kind":"symbol","title":"NSStepper"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityValue()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityValue()","title":"accessibilityValue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"url":"/documentation/appkit/nsaccessibilitystepper/accessibilityvalue()","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Returns the stepper’s value."}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityValue"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper","title":"NSAccessibilityStepper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityStepper"}],"url":"/documentation/appkit/nsaccessibilitystepper","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a stepper."}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityStepper"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformDecrement()":{"type":"topic","abstract":[{"text":"Decrements the stepper’s value.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityPerformDecrement","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformDecrement"}],"url":"/documentation/appkit/nsaccessibilitystepper/accessibilityperformdecrement()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformDecrement()","title":"accessibilityPerformDecrement()","required":true},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySlider":{"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a slider.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"NSAccessibilitySlider","kind":"identifier"}],"title":"NSAccessibilitySlider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"NSAccessibilitySlider","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySlider","url":"/documentation/appkit/nsaccessibilityslider","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol":{"title":"NSAccessibilityElementProtocol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to interact with an assistive app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityelementprotocol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformIncrement()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformIncrement()","title":"accessibilityPerformIncrement()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformIncrement"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/appkit/nsaccessibilitystepper/accessibilityperformincrement()","kind":"symbol","type":"topic","role":"symbol","required":true,"abstract":[{"type":"text","text":"Increments the stepper’s value."}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformIncrement"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Protocol","path":"/metadata/roleHeading"},{"op":"replace","value":"NSAccessibilityStepper","path":"/metadata/title"},{"op":"replace","value":"protocol","path":"/metadata/symbolKind"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSAccessibilityStepper"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibilityStepper"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"title":"Supporting Accessibility","anchor":"Supporting-Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityLabel()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformDecrement()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformIncrement()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityValue()"]}],"op":"replace"},{"path":"/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformingTypes","title":"Conforming Types","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStepper"],"kind":"relationships"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Value-Controls","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySlider"],"title":"Value Controls"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityStepper","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSAccessibilityElement","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSAccessibilityElement","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol"},{"text":">","kind":"text"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityLabel()/title","value":"accessibilityLabel","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityLabel()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityLabel","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepper/title","op":"replace","value":"NSStepper"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepper/fragments","op":"replace","value":[{"text":"NSStepper","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepper/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSStepper"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityValue()/title","op":"replace","value":"accessibilityValue"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityValue()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"accessibilityValue","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper/title","op":"replace","value":"NSAccessibilityStepper"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper/fragments","op":"replace","value":[{"text":"NSAccessibilityStepper","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSAccessibilityStepper"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityPerformDecrement()/title","op":"replace","value":"accessibilityPerformDecrement"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityPerformDecrement()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityPerformDecrement"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySlider/title","op":"replace","value":"NSAccessibilitySlider"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySlider/fragments","op":"replace","value":[{"text":"NSAccessibilitySlider","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySlider/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSAccessibilitySlider"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","op":"replace","value":"NSAccessibility"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","op":"replace","value":[{"kind":"identifier","text":"NSAccessibility"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSAccessibility"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title","op":"replace","value":"NSAccessibilityElement"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments","op":"replace","value":[{"kind":"identifier","text":"NSAccessibilityElement"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSAccessibilityElement"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityPerformIncrement()/title","op":"replace","value":"accessibilityPerformIncrement"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityPerformIncrement()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityPerformIncrement"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}