{
  "abstract": [
    {
      "text": "A namespace for accessibility symbols for AppKit apps.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@NSAccessibility",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSAccessibility"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSAccessibility"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct": {
      "abstract": [
        {
          "text": "A namespace for accessibility symbols for AppKit apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Action": {
      "abstract": [
        {
          "text": "Constants that describe types of actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Action",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/action"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/AnnotationAttributeKey": {
      "abstract": [
        {
          "text": "Keys for annotation attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnnotationAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/AnnotationAttributeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnnotationAttributeKey"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.AnnotationAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/annotationattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute": {
      "abstract": [
        {
          "text": "Constants that describe attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Attribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ErrorCodeExceptionInfo": {
      "abstract": [
        {
          "text": "An integer error code for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorCodeExceptionInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ErrorCodeExceptionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityErrorCodeExceptionInfo"
        }
      ],
      "role": "symbol",
      "title": "ErrorCodeExceptionInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/errorcodeexceptioninfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey": {
      "abstract": [
        {
          "text": "Keys for font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontAttributeKey"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.FontAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/fontattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification": {
      "abstract": [
        {
          "text": "The name of the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Notification"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Notification",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey": {
      "abstract": [
        {
          "text": "The key in the user info dictionary for a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationUserInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.NotificationUserInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notificationuserinfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue": {
      "abstract": [
        {
          "text": "Values that indicate the orientation of user interface elements, such as scroll bars and split views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OrientationValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OrientationValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.OrientationValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute": {
      "abstract": [
        {
          "text": "Values that describe parameterized attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.ParameterizedAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Role": {
      "abstract": [
        {
          "text": "Values that describe types of objects that accessibility elements represent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Role"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Role",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Role"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Role",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/role"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue": {
      "abstract": [
        {
          "text": "Values that describe ruler marker types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.RulerMarkerTypeValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerUnitValue": {
      "abstract": [
        {
          "text": "Values that indicate the unit values of a ruler or layout area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RulerUnitValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerUnitValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RulerUnitValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.RulerUnitValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulerunitvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/SortDirectionValue": {
      "abstract": [
        {
          "text": "Values that indicate the sort direction of a column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SortDirectionValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/SortDirectionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SortDirectionValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.SortDirectionValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/sortdirectionvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole": {
      "abstract": [
        {
          "text": "Values that describe specialized object subtypes that accessibility elements represent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Subrole"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Subrole",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)": {
      "abstract": [
        {
          "text": "Sends a notification to any observing assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "post"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "element"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "notification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityPostNotification"
        }
      ],
      "role": "symbol",
      "title": "post(element:notification:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/post(element:notification:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:userInfo:)": {
      "abstract": [
        {
          "text": "Sends a notification and an optional user info dictionary to any observing assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "post"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "element"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "notification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationUserInfoKey",
          "text": "NotificationUserInfoKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:userInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityPostNotificationWithUserInfo"
        }
      ],
      "role": "symbol",
      "title": "post(element:notification:userInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/post(element:notification:userinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)": {
      "abstract": [
        {
          "text": "Raises an error if the parameter is the wrong type or has an illegal value",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raiseBadArgumentException"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRaiseBadArgumentException"
        }
      ],
      "role": "symbol",
      "title": "raiseBadArgumentException(_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/raisebadargumentexception(_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/screenPoint(fromView:point:)": {
      "abstract": [
        {
          "text": "Returns the point in screen coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "point"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/screenPoint(fromView:point:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityPointInView"
        }
      ],
      "role": "symbol",
      "title": "screenPoint(fromView:point:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/screenpoint(fromview:point:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/screenRect(fromView:rect:)": {
      "abstract": [
        {
          "text": "Returns the frame in screen coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/screenRect(fromView:rect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFrameInView"
        }
      ],
      "role": "symbol",
      "title": "screenRect(fromView:rect:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/screenrect(fromview:rect:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/setMayContainProtectedContent(_:)": {
      "abstract": [
        {
          "text": "Sets whether the app may have protected content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMayContainProtectedContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/setMayContainProtectedContent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySetMayContainProtectedContent"
        }
      ],
      "role": "symbol",
      "title": "setMayContainProtectedContent(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/setmaycontainprotectedcontent(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredAncestor(of:)": {
      "abstract": [
        {
          "text": "Returns an unignored accessibility object, ascending the hierarchy, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unignoredAncestor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredAncestor(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnignoredAncestor"
        }
      ],
      "role": "symbol",
      "title": "unignoredAncestor(of:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/unignoredancestor(of:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredChildren(from:)": {
      "abstract": [
        {
          "text": "Returns a list of unignored accessibility objects, descending the hierarchy, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unignoredChildren"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredChildren(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnignoredChildren"
        }
      ],
      "role": "symbol",
      "title": "unignoredChildren(from:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/unignoredchildren(from:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredChildrenForOnlyChild(from:)": {
      "abstract": [
        {
          "text": "Returns a list of unignored accessibility objects, descending the hierarchy, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unignoredChildrenForOnlyChild"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredChildrenForOnlyChild(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnignoredChildrenForOnlyChild"
        }
      ],
      "role": "symbol",
      "title": "unignoredChildrenForOnlyChild(from:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/unignoredchildrenforonlychild(from:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredDescendant(of:)": {
      "abstract": [
        {
          "text": "Returns an unignored accessibility object, descending the hierarchy, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unignoredDescendant"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredDescendant(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnignoredDescendant"
        }
      ],
      "role": "symbol",
      "title": "unignoredDescendant(of:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/unignoreddescendant(of:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "AppKit-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol"
      ],
      "title": "AppKit Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Posting-Notifications",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:userInfo:)"
      ],
      "title": "Posting Notifications"
    },
    {
      "anchor": "Getting-Accessibility-Objects",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredAncestor(of:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredChildren(from:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredChildrenForOnlyChild(from:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/unignoredDescendant(of:)"
      ],
      "title": "Getting Accessibility Objects"
    },
    {
      "anchor": "Getting-Screen-Coordinates",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/screenPoint(fromView:point:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/screenRect(fromView:rect:)"
      ],
      "title": "Getting Screen Coordinates"
    },
    {
      "anchor": "Specifying-Protected-Content",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/setMayContainProtectedContent(_:)"
      ],
      "title": "Specifying Protected Content"
    },
    {
      "anchor": "Handling-Errors",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ErrorCodeExceptionInfo"
      ],
      "title": "Handling Errors"
    },
    {
      "anchor": "Using-Accessibility-Types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Action",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/AnnotationAttributeKey",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Role",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerUnitValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/SortDirectionValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole"
      ],
      "title": "Using Accessibility Types"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey/title",
          "value": "NSAccessibilityFontAttributeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey/title",
          "value": "NSAccessibilityNotificationUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNotificationUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNotificationUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/title",
          "value": "NSAccessibilityRulerMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:)/title",
          "value": "NSAccessibilityPostNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityPostNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1AnnotationAttributeKey/title",
          "value": "NSAccessibilityAnnotationAttributeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1AnnotationAttributeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAnnotationAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1AnnotationAttributeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAnnotationAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1unignoredDescendant(of:)/title",
          "value": "NSAccessibilityUnignoredDescendant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1unignoredDescendant(of:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnignoredDescendant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/title",
          "value": "NSAccessibilityRaiseBadArgumentException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRaiseBadArgumentException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1screenRect(fromView:rect:)/title",
          "value": "NSAccessibilityFrameInView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1screenRect(fromView:rect:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFrameInView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Role/title",
          "value": "NSAccessibilityRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Role/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Role/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1setMayContainProtectedContent(_:)/title",
          "value": "NSAccessibilitySetMayContainProtectedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1setMayContainProtectedContent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySetMayContainProtectedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Action/title",
          "value": "NSAccessibilityActionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityActionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Action/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityActionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute/title",
          "value": "NSAccessibilityAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1unignoredAncestor(of:)/title",
          "value": "NSAccessibilityUnignoredAncestor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1unignoredAncestor(of:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnignoredAncestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1unignoredChildrenForOnlyChild(from:)/title",
          "value": "NSAccessibilityUnignoredChildrenForOnlyChild"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1unignoredChildrenForOnlyChild(from:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnignoredChildrenForOnlyChild"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/title",
          "value": "NSAccessibilitySubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerUnitValue/title",
          "value": "NSAccessibilityRulerUnitValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerUnitValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerUnitValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerUnitValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerUnitValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1SortDirectionValue/title",
          "value": "NSAccessibilitySortDirectionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1SortDirectionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySortDirectionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1SortDirectionValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySortDirectionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue/title",
          "value": "NSAccessibilityOrientationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1screenPoint(fromView:point:)/title",
          "value": "NSAccessibilityPointInView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1screenPoint(fromView:point:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityPointInView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:userInfo:)/title",
          "value": "NSAccessibilityPostNotificationWithUserInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:userInfo:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityPostNotificationWithUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification/title",
          "value": "NSAccessibilityNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1unignoredChildren(from:)/title",
          "value": "NSAccessibilityUnignoredChildren"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1unignoredChildren(from:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnignoredChildren"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/title",
          "value": "NSAccessibilityParameterizedAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityParameterizedAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityParameterizedAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ErrorCodeExceptionInfo/title",
          "value": "NSAccessibilityErrorCodeExceptionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ErrorCodeExceptionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityErrorCodeExceptionInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
