{
  "abstract": [
    {
      "text": "Text underline color (",
      "type": "text"
    },
    {
      "code": "CGColorRef",
      "type": "codeVoice"
    },
    {
      "text": ").",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSAccessibilityUnderlineColorTextAttribute",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityUnderlineColorTextAttribute"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityUnderlineColorTextAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSAccessibilityUnderlineColorTextAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringKey",
              "text": "NSAttributedStringKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnderlineColorTextAttribute"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontFamily": {
      "abstract": [
        {
          "text": "An optional key for a font family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontFamily"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityFontAttributeKey",
          "text": "FontAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFontFamilyKey"
        }
      ],
      "role": "symbol",
      "title": "fontFamily",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/fontattributekey/fontfamily"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontName": {
      "abstract": [
        {
          "text": "A required key for a font name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityFontAttributeKey",
          "text": "FontAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFontNameKey"
        }
      ],
      "role": "symbol",
      "title": "fontName",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/fontattributekey/fontname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute": {
      "abstract": [
        {
          "text": "Text attachment (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAttachmentTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityAttachmentTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityattachmenttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute": {
      "abstract": [
        {
          "text": "Autocorrected text (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAutocorrectedTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityAutocorrectedTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityautocorrectedtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute": {
      "abstract": [
        {
          "text": "Text background color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityBackgroundColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityBackgroundColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitybackgroundcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute": {
      "abstract": [
        {
          "text": "Font keys (",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFontTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityFontTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityfonttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute": {
      "abstract": [
        {
          "text": "Text foreground color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityForegroundColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityForegroundColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityforegroundcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute": {
      "abstract": [
        {
          "text": "Text link (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLinkTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityLinkTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitylinktextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute": {
      "abstract": [
        {
          "text": "Misspelled text that is visibly marked as misspelled (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value). If you’re implementing a custom text-editing app, use ",
          "type": "text"
        },
        {
          "code": "NSAccessibilityMarkedMisspelledTextAttribute",
          "type": "codeVoice"
        },
        {
          "text": " to ensure that VoiceOver properly identifies misspelled text to users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMarkedMisspelledTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityMarkedMisspelledTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitymarkedmisspelledtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute": {
      "abstract": [
        {
          "text": "Misspelled text that isn’t necessarily visibly marked as misspelled (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " as a Boolean value). Beginning in macOS 10.9, VoiceOver no longer checks for this attribute; instead, VoiceOver uses ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMisspelledTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityMisspelledTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitymisspelledtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute": {
      "abstract": [
        {
          "text": "Text shadow (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityShadowTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityShadowTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityshadowtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute": {
      "abstract": [
        {
          "text": "Text strikethrough color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStrikethroughColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityStrikethroughColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitystrikethroughcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute": {
      "abstract": [
        {
          "text": "Text strikethrough (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStrikethroughTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityStrikethroughTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitystrikethroughtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute": {
      "abstract": [
        {
          "text": "Text superscript style (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": "). Values > 0 are superscript; values < 0 are subscript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySuperscriptTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilitySuperscriptTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitysuperscripttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute": {
      "abstract": [
        {
          "text": "Text underline color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnderlineColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityUnderlineColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityunderlinecolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute": {
      "abstract": [
        {
          "text": "Text underline style (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnderlineTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityUnderlineTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityunderlinetextattribute"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey": {
      "abstract": [
        {
          "text": "The attributes you apply to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString.Key",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontName",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontFamily"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSAttributedStringKey/title",
          "value": "NSAttributedStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontFamily/title",
          "value": "NSAccessibilityFontFamilyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontFamilyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontName/title",
          "value": "NSAccessibilityFontNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontNameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilityunderlinecolortextattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
