{
  "abstract": [
    {
      "text": "A format where alpha values are not premultiplied.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAlphaNonpremultipliedBitmapFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSAlphaNonpremultipliedBitmapFormat",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSAlphaNonpremultipliedBitmapFormat"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAlphaNonpremultipliedBitmapFormat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSAlphaNonpremultipliedBitmapFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSBitmapFormat",
              "text": "NSBitmapFormat"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAlphaNonpremultipliedBitmapFormat"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If this option is not specified, alpha values are premultiplied.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS16BitBigEndianBitmapFormat": {
      "abstract": [
        {
          "text": "A 16-bit, big endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS16BitBigEndianBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS16BitBigEndianBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS16BitBigEndianBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/ns16bitbigendianbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS16BitLittleEndianBitmapFormat": {
      "abstract": [
        {
          "text": "A 16-bit, little endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS16BitLittleEndianBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS16BitLittleEndianBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS16BitLittleEndianBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/ns16bitlittleendianbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS32BitBigEndianBitmapFormat": {
      "abstract": [
        {
          "text": "A 32-bit, big endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS32BitBigEndianBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS32BitBigEndianBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS32BitBigEndianBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/ns32bitbigendianbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS32BitLittleEndianBitmapFormat": {
      "abstract": [
        {
          "text": "A 32-bit, little endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS32BitLittleEndianBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS32BitLittleEndianBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS32BitLittleEndianBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/ns32bitlittleendianbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlphaFirstBitmapFormat": {
      "abstract": [
        {
          "text": "A format where the alpha value comes first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAlphaFirstBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlphaFirstBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAlphaFirstBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsalphafirstbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlphaNonpremultipliedBitmapFormat": {
      "abstract": [
        {
          "text": "A format where alpha values are not premultiplied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAlphaNonpremultipliedBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlphaNonpremultipliedBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAlphaNonpremultipliedBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsalphanonpremultipliedbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format": {
      "abstract": [
        {
          "text": "Constants that represent bitmap component formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "role": "symbol",
      "title": "NSBitmapImageRep.Format",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFloatingPointSamplesBitmapFormat": {
      "abstract": [
        {
          "text": "A format where samples are specified using floating-point numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFloatingPointSamplesBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFloatingPointSamplesBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFloatingPointSamplesBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsfloatingpointsamplesbitmapformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAlphaFirstBitmapFormat",
        "doc://com.apple.appkit/documentation/AppKit/NSFloatingPointSamplesBitmapFormat",
        "doc://com.apple.appkit/documentation/AppKit/NS16BitLittleEndianBitmapFormat",
        "doc://com.apple.appkit/documentation/AppKit/NS32BitLittleEndianBitmapFormat",
        "doc://com.apple.appkit/documentation/AppKit/NS16BitBigEndianBitmapFormat",
        "doc://com.apple.appkit/documentation/AppKit/NS32BitBigEndianBitmapFormat"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/title",
          "value": "NSBitmapFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsalphanonpremultipliedbitmapformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
