{
  "abstract": [
    {
      "text": "This constant is returned in the userInfo dictionary of the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/progressMarkNotification",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " notification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/animation",
        "doc://com.apple.appkit/documentation/AppKit/NSAnimation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsanimationprogressmark-notification-key"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "NSAnimationProgressMark Notification Key"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation": {
      "abstract": [
        {
          "text": "An object that manages the timing and progress of animations in the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAnimation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAnimation"
        }
      ],
      "role": "symbol",
      "title": "NSAnimation",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation/BlockingMode": {
      "abstract": [
        {
          "text": "These constants indicate the blocking mode of an ",
          "type": "text"
        },
        {
          "code": "NSAnimation",
          "type": "codeVoice"
        },
        {
          "text": " object when it is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BlockingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/BlockingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BlockingMode"
        }
      ],
      "role": "symbol",
      "title": "NSAnimation.BlockingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation/blockingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Curve": {
      "abstract": [
        {
          "text": "These constants describe the curve of an animation—that is, the relative speed of an animation from start to finish.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Curve"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Curve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Curve"
        }
      ],
      "role": "symbol",
      "title": "NSAnimation.Curve",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation/curve"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Progress": {
      "abstract": [
        {
          "text": "The animation progress, as a floating-point number between ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Progress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "role": "symbol",
      "title": "NSAnimation.Progress",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation/progress"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation/progressMarkNotification": {
      "abstract": [
        {
          "text": "Posted when the current progress of a running animation reaches one of its progress marks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progressMarkNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/progressMarkNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAnimationProgressMarkNotification"
        }
      ],
      "role": "symbol",
      "title": "progressMarkNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation/progressmarknotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimation/progressMarkUserInfoKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progressMarkUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimation/progressMarkUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAnimationProgressMark"
        }
      ],
      "role": "symbol",
      "title": "progressMarkUserInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nsanimation/progressmarkuserinfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/animation": {
      "abstract": [
        {
          "text": "Animate your views and other content to create a more engaging experience for users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/animation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation",
      "type": "topic",
      "url": "/documentation/appkit/animation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Curve",
        "doc://com.apple.appkit/documentation/AppKit/NSAnimation/BlockingMode",
        "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Progress"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAnimation/progressMarkUserInfoKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAnimation/progressMarkUserInfoKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Curve",
                "doc://com.apple.appkit/documentation/AppKit/NSAnimation/BlockingMode",
                "doc://com.apple.appkit/documentation/AppKit/NSAnimation/Progress"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Curve/title",
          "value": "NSAnimationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Curve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Curve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Progress/title",
          "value": "NSAnimationProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Progress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1Progress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1BlockingMode/title",
          "value": "NSAnimationBlockingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1BlockingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationBlockingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1BlockingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationBlockingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1progressMarkUserInfoKey/title",
          "value": "NSAnimationProgressMark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1progressMarkUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationProgressMark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation/title",
          "value": "NSAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1progressMarkNotification/title",
          "value": "NSAnimationProgressMarkNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimation~1progressMarkNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimationProgressMarkNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsanimationprogressmark-notification-key"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsanimationprogressmark-notification-key"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
