{
  "abstract": [
    {
      "text": "The specific version of the AppKit framework that introduced support for directional tab items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDirectionalTabs"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSAppKitVersionNumberWithDirectionalTabs",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSAppKitVersionNumberWithDirectionalTabs"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAppKitVersionNumberWithDirectionalTabs"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSAppKitVersionNumberWithDirectionalTabs"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAppKitVersion",
              "text": "NSAppKitVersion"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumberWithDirectionalTabs"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion": {
      "abstract": [
        {
          "text": "Constants for determining which version of AppKit is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersion"
        }
      ],
      "role": "symbol",
      "title": "NSAppKitVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithColumnResizingBrowser": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework that introduced support for resizing individual browser columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithColumnResizingBrowser"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithColumnResizingBrowser",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithColumnResizingBrowser",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithcolumnresizingbrowser"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithContinuousScrollingBrowser": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework that introduced support the continuous scrolling in a browser view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithContinuousScrollingBrowser"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithContinuousScrollingBrowser",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithContinuousScrollingBrowser",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithcontinuousscrollingbrowser"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCursorSizeSupport": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework that introduced support for cursors larger than 16 x 16 pixels in size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithCursorSizeSupport"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCursorSizeSupport",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithCursorSizeSupport",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithcursorsizesupport"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCustomSheetPosition": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework that introduced custom sheet positioning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithCustomSheetPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCustomSheetPosition",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithCustomSheetPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithcustomsheetposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDeferredWindowDisplaySupport": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework that introduced support for deferred window display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithDeferredWindowDisplaySupport"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDeferredWindowDisplaySupport",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithDeferredWindowDisplaySupport",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithdeferredwindowdisplaysupport"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDirectionalTabs": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework that introduced support for directional tab items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithDirectionalTabs"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDirectionalTabs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithDirectionalTabs",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithdirectionaltabs"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDockTilePlugInSupport": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework that introduced support for dock tile plug-ins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithDockTilePlugInSupport"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDockTilePlugInSupport",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithDockTilePlugInSupport",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithdocktilepluginsupport"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithPatternColorLeakFix": {
      "abstract": [
        {
          "text": "The specific version of the AppKit framework from OS X 10.1 that correctly autoreleases color objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumberWithPatternColorLeakFix"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithPatternColorLeakFix",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppKitVersionNumberWithPatternColorLeakFix",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversionnumberwithpatterncolorleakfix"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Feature-Introductions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithColumnResizingBrowser",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithContinuousScrollingBrowser",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCursorSizeSupport",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithCustomSheetPosition",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDeferredWindowDisplaySupport",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithDockTilePlugInSupport",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersionNumberWithPatternColorLeakFix"
      ],
      "title": "Feature Introductions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/title",
          "value": "NSAppKitVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsappkitversionnumberwithdirectionaltabs"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
