{
  "abstract": [
    {
      "text": "Constants for the document type document attribute key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSAttributedStringDocumentType",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSAttributedStringDocumentType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAttributedStringDocumentType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSAttributedStringDocumentType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSAttributedStringDocumentType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants as values for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentAttribute",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in the document attributes dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType": {
      "abstract": [
        {
          "text": "Constants for the document type document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocFormatTextDocumentType": {
      "abstract": [
        {
          "text": "Microsoft Word document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDocFormatTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocFormatTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDocFormatTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsdocformattextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentAttribute": {
      "abstract": [
        {
          "text": "The document type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDocumentTypeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDocumentTypeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumenttypedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHTMLTextDocumentType": {
      "abstract": [
        {
          "text": "Hypertext markup language (HTML) document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHTMLTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHTMLTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHTMLTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nshtmltextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMacSimpleTextDocumentType": {
      "abstract": [
        {
          "text": "Macintosh SimpleText document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMacSimpleTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMacSimpleTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMacSimpleTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsmacsimpletextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOfficeOpenXMLTextDocumentType": {
      "abstract": [
        {
          "text": "ECMA Office Open XML text document format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOfficeOpenXMLTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOfficeOpenXMLTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOfficeOpenXMLTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsofficeopenxmltextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenDocumentTextDocumentType": {
      "abstract": [
        {
          "text": "OASIS Open Document text document format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenDocumentTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenDocumentTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenDocumentTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsopendocumenttextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPlainTextDocumentType": {
      "abstract": [
        {
          "text": "Plain text document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPlainTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPlainTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPlainTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsplaintextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRTFDTextDocumentType": {
      "abstract": [
        {
          "text": "Rich text format with attachments document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRTFDTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRTFDTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRTFDTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsrtfdtextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRTFTextDocumentType": {
      "abstract": [
        {
          "text": "Rich text format document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRTFTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRTFTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRTFTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsrtftextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey": {
      "abstract": [
        {
          "text": "Constants for the text layout sections document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionKey",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType": {
      "abstract": [
        {
          "text": "Constants that specify the text scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "role": "symbol",
      "title": "NSTextScalingType",
      "type": "topic",
      "url": "/documentation/appkit/nstextscalingtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWebArchiveTextDocumentType": {
      "abstract": [
        {
          "text": "WebKit WebArchive document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWebArchiveTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWebArchiveTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWebArchiveTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nswebarchivetextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWordMLTextDocumentType": {
      "abstract": [
        {
          "text": "Microsoft Word XML (WordML schema) document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWordMLTextDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWordMLTextDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWordMLTextDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nswordmltextdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys": {
      "abstract": [
        {
          "text": "Keys for constructing an attributed string from data on disk.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document reading option keys",
      "type": "topic",
      "url": "/documentation/appkit/document-reading-option-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-document-wide-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
        "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType"
      ],
      "title": "Getting document-wide attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-keys-for-document-types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocFormatTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSHTMLTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSMacSimpleTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSOfficeOpenXMLTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenDocumentTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSPlainTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSRTFTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSRTFDTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSWebArchiveTextDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSWordMLTextDocumentType"
      ],
      "title": "Getting keys for document types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/title",
          "value": "NSTextScalingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsattributedstringdocumenttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
