{
  "abstract": [
    {
      "text": "The attributes you apply to an entire document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSAttributedStringDocumentAttributeKey",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSAttributedStringDocumentAttributeKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAttributedStringDocumentAttributeKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSAttributedStringDocumentAttributeKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSAttributedStringDocumentAttributeKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type defines attributes that apply to an entire attributed string, and not to specific ranges of characters. You specify these attributes when writing an attributed string to disk, or reading text from a file on disk. Use these attributes to specify metadata about the overall document, including its author or title, page margin details, font-scaling options for cross-platform interchange, and more.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppearanceDocumentAttribute": {
      "abstract": [
        {
          "text": "The appearance of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppearanceDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppearanceDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppearanceDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsappearancedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType": {
      "abstract": [
        {
          "text": "Constants for the document type document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAuthorDocumentAttribute": {
      "abstract": [
        {
          "text": "The author of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAuthorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAuthorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAuthorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsauthordocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorDocumentAttribute": {
      "abstract": [
        {
          "text": "The background color of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBackgroundColorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBackgroundColorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsbackgroundcolordocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBottomMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The bottom margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBottomMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBottomMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBottomMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsbottommargindocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCategoryDocumentAttribute": {
      "abstract": [
        {
          "text": "The document’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCategoryDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCategoryDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCategoryDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nscategorydocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCharacterEncodingDocumentAttribute": {
      "abstract": [
        {
          "text": "The string encoding for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCharacterEncodingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCharacterEncodingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCharacterEncodingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nscharacterencodingdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCocoaVersionDocumentAttribute": {
      "abstract": [
        {
          "text": "The version of Cocoa that created the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCocoaVersionDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCocoaVersionDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCocoaVersionDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nscocoaversiondocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCommentDocumentAttribute": {
      "abstract": [
        {
          "text": "The document comments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCommentDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCommentDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCommentDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nscommentdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompanyDocumentAttribute": {
      "abstract": [
        {
          "text": "The company or organization name associated with the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompanyDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompanyDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompanyDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nscompanydocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSConvertedDocumentAttribute": {
      "abstract": [
        {
          "text": "A value that indicates whether a filter service converted the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSConvertedDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSConvertedDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSConvertedDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsconverteddocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCopyrightDocumentAttribute": {
      "abstract": [
        {
          "text": "The document’s copyright information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCopyrightDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCopyrightDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopyrightDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nscopyrightdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCreationTimeDocumentAttribute": {
      "abstract": [
        {
          "text": "The creation date of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCreationTimeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCreationTimeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCreationTimeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nscreationtimedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDefaultAttributesDocumentAttribute": {
      "abstract": [
        {
          "text": "The default document attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultAttributesDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDefaultAttributesDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultAttributesDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsdefaultattributesdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDefaultFontExcludedDocumentAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultFontExcludedDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDefaultFontExcludedDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultFontExcludedDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsdefaultfontexcludeddocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDefaultTabIntervalDocumentAttribute": {
      "abstract": [
        {
          "text": "The default tab stop interval for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultTabIntervalDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDefaultTabIntervalDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultTabIntervalDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsdefaulttabintervaldocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentAttribute": {
      "abstract": [
        {
          "text": "The document type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDocumentTypeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDocumentTypeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumenttypedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditorDocumentAttribute": {
      "abstract": [
        {
          "text": "The name of person who last edited the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSEditorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEditorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nseditordocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSExcludedElementsDocumentAttribute": {
      "abstract": [
        {
          "text": "The HTML elements to exclude in generated HTML.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSExcludedElementsDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSExcludedElementsDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExcludedElementsDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsexcludedelementsdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFileTypeDocumentAttribute": {
      "abstract": [
        {
          "text": "The document type for interpreting the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFileTypeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFileTypeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileTypeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsfiletypedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHyphenationFactorDocumentAttribute": {
      "abstract": [
        {
          "text": "The hyphenation factor of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHyphenationFactorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHyphenationFactorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHyphenationFactorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nshyphenationfactordocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKeywordsDocumentAttribute": {
      "abstract": [
        {
          "text": "The document keywords.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKeywordsDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKeywordsDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKeywordsDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nskeywordsdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The left margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmargindocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSManagerDocumentAttribute": {
      "abstract": [
        {
          "text": "The name of the author’s manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSManagerDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSManagerDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagerDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsmanagerdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSModificationTimeDocumentAttribute": {
      "abstract": [
        {
          "text": "The modification date of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSModificationTimeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSModificationTimeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSModificationTimeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsmodificationtimedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPaperSizeDocumentAttribute": {
      "abstract": [
        {
          "text": "The paper size for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPaperSizeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPaperSizeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPaperSizeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nspapersizedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrefixSpacesDocumentAttribute": {
      "abstract": [
        {
          "text": "The number of spaces for indenting nested HTML elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPrefixSpacesDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrefixSpacesDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrefixSpacesDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsprefixspacesdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReadOnlyDocumentAttribute": {
      "abstract": [
        {
          "text": "An indication of whether the document is read-only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSReadOnlyDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReadOnlyDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSReadOnlyDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsreadonlydocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The right margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmargindocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentAttribute": {
      "abstract": [
        {
          "text": "The text-scaling mode you used when creating the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSourceTextScalingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSourceTextScalingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nssourcetextscalingdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSubjectDocumentAttribute": {
      "abstract": [
        {
          "text": "The subject of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSubjectDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSubjectDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSubjectDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nssubjectdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextEncodingNameDocumentAttribute": {
      "abstract": [
        {
          "text": "The name of the text encoding to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEncodingNameDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextEncodingNameDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEncodingNameDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstextencodingnamedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey": {
      "abstract": [
        {
          "text": "Constants for the text layout sections document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionKey",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute": {
      "abstract": [
        {
          "text": "The layout orientations for each section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionsAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionsAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionsattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextScalingDocumentAttribute": {
      "abstract": [
        {
          "text": "The text-scaling mode to use when displaying the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextScalingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextScalingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextScalingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstextscalingdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType": {
      "abstract": [
        {
          "text": "Constants that specify the text scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "role": "symbol",
      "title": "NSTextScalingType",
      "type": "topic",
      "url": "/documentation/appkit/nstextscalingtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTitleDocumentAttribute": {
      "abstract": [
        {
          "text": "The document title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTitleDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTitleDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTitleDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstitledocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTopMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The top margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTopMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTopMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTopMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstopmargindocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewModeDocumentAttribute": {
      "abstract": [
        {
          "text": "The view mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewModeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewModeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewModeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsviewmodedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewSizeDocumentAttribute": {
      "abstract": [
        {
          "text": "The view size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewSizeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewSizeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewSizeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsviewsizedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewZoomDocumentAttribute": {
      "abstract": [
        {
          "text": "The view zoom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewZoomDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewZoomDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewZoomDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsviewzoomdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys": {
      "abstract": [
        {
          "text": "Keys for constructing an attributed string from data on disk.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document reading option keys",
      "type": "topic",
      "url": "/documentation/appkit/document-reading-option-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-document-wide-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys",
        "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType"
      ],
      "title": "Getting document-wide attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-document-type-keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentTypeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSFileTypeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSTextEncodingNameDocumentAttribute"
      ],
      "title": "Getting document type keys"
    },
    {
      "anchor": "Getting-document-metadata-keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAuthorDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSCategoryDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSCharacterEncodingDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSCocoaVersionDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSCommentDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSCompanyDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSConvertedDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSCopyrightDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSCreationTimeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSEditorDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSKeywordsDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSManagerDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSModificationTimeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSReadOnlyDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSSubjectDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSTitleDocumentAttribute"
      ],
      "title": "Getting document metadata keys"
    },
    {
      "anchor": "Getting-document-appearance-keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAppearanceDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSBottomMarginDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSDefaultFontExcludedDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSDefaultTabIntervalDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSExcludedElementsDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSHyphenationFactorDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftMarginDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSPaperSizeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSPrefixSpacesDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSRightMarginDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSTopMarginDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSViewModeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSViewSizeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSViewZoomDocumentAttribute"
      ],
      "title": "Getting document appearance keys"
    },
    {
      "anchor": "Getting-the-font-scaling-options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSTextScalingDocumentAttribute"
      ],
      "title": "Getting the font-scaling options"
    },
    {
      "anchor": "Getting-the-default-attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDefaultAttributesDocumentAttribute"
      ],
      "title": "Getting the default attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/title",
          "value": "NSTextScalingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsattributedstringdocumentattributekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
