{
  "abstract": [
    {
      "text": "An event type used to support Java applications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAWTEventType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSAWTEventType",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSAWTEventType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAWTEventType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSAWTEventType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSEventSubtype",
              "text": "NSEventSubtype"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAWTEventType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAWTEventType": {
      "abstract": [
        {
          "text": "An event type used to support Java applications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAWTEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAWTEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAWTEventType",
      "type": "topic",
      "url": "/documentation/appkit/nsawteventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationActivatedEventType": {
      "abstract": [
        {
          "text": "The application has been activated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationActivatedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationActivatedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationActivatedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationactivatedeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationDeactivatedEventType": {
      "abstract": [
        {
          "text": "The application has been deactivated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationDeactivatedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationDeactivatedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationDeactivatedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationdeactivatedeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype": {
      "abstract": [
        {
          "text": "Subtypes for various types of events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseEventSubtype": {
      "abstract": [
        {
          "text": "Indicates a purely mouse event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseEventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseEventSubtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseEventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nsmouseeventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPowerOffEventType": {
      "abstract": [
        {
          "text": "Specifies that the user is turning off the computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPowerOffEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPowerOffEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPowerOffEventType",
      "type": "topic",
      "url": "/documentation/appkit/nspoweroffeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreenChangedEventType": {
      "abstract": [
        {
          "text": "An NSWindow has changed screens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSScreenChangedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreenChangedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSScreenChangedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nsscreenchangedeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabletPointEventSubtype": {
      "abstract": [
        {
          "text": "Indicates a tablet-pointer event; see description of ",
          "type": "text"
        },
        {
          "code": "NSTabletPoint",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTabletPointEventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabletPointEventSubtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTabletPointEventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nstabletpointeventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabletProximityEventSubtype": {
      "abstract": [
        {
          "text": "Indicates a tablet-proximity event; see description of ",
          "type": "text"
        },
        {
          "code": "NSTabletProximity",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTabletProximityEventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabletProximityEventSubtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTabletProximityEventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nstabletproximityeventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchEventSubtype": {
      "abstract": [
        {
          "text": "Indicates a touch event subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTouchEventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchEventSubtype",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchEventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nstoucheventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowExposedEventType": {
      "abstract": [
        {
          "text": "A non-retained NSWindow has been exposed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWindowExposedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowExposedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindowExposedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nswindowexposedeventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowMovedEventType": {
      "abstract": [
        {
          "text": "An NSWindow has moved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWindowMovedEventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowMovedEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindowMovedEventType",
      "type": "topic",
      "url": "/documentation/appkit/nswindowmovedeventtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplicationActivatedEventType",
        "doc://com.apple.appkit/documentation/AppKit/NSApplicationDeactivatedEventType",
        "doc://com.apple.appkit/documentation/AppKit/NSMouseEventSubtype",
        "doc://com.apple.appkit/documentation/AppKit/NSPowerOffEventType",
        "doc://com.apple.appkit/documentation/AppKit/NSScreenChangedEventType",
        "doc://com.apple.appkit/documentation/AppKit/NSTabletPointEventSubtype",
        "doc://com.apple.appkit/documentation/AppKit/NSTabletProximityEventSubtype",
        "doc://com.apple.appkit/documentation/AppKit/NSTouchEventSubtype",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowExposedEventType",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowMovedEventType"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/title",
          "value": "NSEventSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsawteventtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
