{
  "abstract": [
    {
      "text": "Creates and runs a critical alert sheet.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlert",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@NSBeginCriticalAlertSheet",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSBeginCriticalAlertSheet"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSBeginCriticalAlertSheet"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.10",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "NSBeginCriticalAlertSheet"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSBeginCriticalAlertSheet"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "title"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "defaultButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "alternateButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "otherButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWindow",
              "text": "NSWindow"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "docWindow"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "modalDelegate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SEL",
              "text": "SEL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "didEndSelector"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SEL",
              "text": "SEL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "didDismissSelector"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "contextInfo"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "msgFormat"
            },
            {
              "kind": "text",
              "text": ", ...);"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Creates and runs a critical alert sheet on ",
              "type": "text"
            },
            {
              "code": "docWindow",
              "type": "codeVoice"
            },
            {
              "text": ", with the title of ",
              "type": "text"
            },
            {
              "code": "title",
              "type": "codeVoice"
            },
            {
              "text": ", the text of ",
              "type": "text"
            },
            {
              "code": "msg",
              "type": "codeVoice"
            },
            {
              "text": ", and buttons with titles of ",
              "type": "text"
            },
            {
              "code": "defaultButton",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "alternateButton",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "otherButton",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "See the description of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for information on layout, default parameters, and the selectors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sheet presented to the user is badged with a caution icon. Critical alerts should be used only as specified in the “Alerts” section of the UI Element Guidelines: Windows chapter of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/OSXHIGuidelines/index.html#//apple_ref/doc/uid/20000957",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)": {
      "abstract": [
        {
          "text": "Raises an error if the parameter is the wrong type or has an illegal value",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raiseBadArgumentException"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRaiseBadArgumentException"
        }
      ],
      "role": "symbol",
      "title": "raiseBadArgumentException(_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/raisebadargumentexception(_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlert": {
      "abstract": [
        {
          "text": "A modal dialog or sheet attached to a document window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAlert"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlert"
        }
      ],
      "role": "symbol",
      "title": "NSAlert",
      "type": "topic",
      "url": "/documentation/appkit/nsalert"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbeginalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginCriticalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginCriticalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegincriticalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginInformationalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginInformationalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegininformationalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Prepares a set of glyphs for processing by character-based routines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSGlyph",
          "text": "NSGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMultibyteGlyphPacking",
          "text": "NSMultibyteGlyphPacking"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        }
      ],
      "role": "symbol",
      "title": "NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsconvertglyphstopackedglyphs(_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display a critical message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetcriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display an informational message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetinformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption": {
      "abstract": [
        {
          "text": "Returns global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion": {
      "abstract": [
        {
          "text": "Returns the NSOpenGL version numbers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption": {
      "abstract": [
        {
          "text": "Sets global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLSetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLSetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglsetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)": {
      "abstract": [
        {
          "text": "Disposes of an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        }
      ],
      "role": "symbol",
      "title": "NSReleaseAlertPanel(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsreleasealertpanel(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel": {
      "abstract": [
        {
          "text": "Creates an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsrunalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunAlertPanelRelativeToWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunAlertPanelRelativeToWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsrunalertpanelrelativetowindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruncriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruninformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@SEL": {
      "abstract": [
        {
          "text": "Defines an opaque type that represents a method selector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
      "kind": "symbol",
      "role": "symbol",
      "title": "SEL",
      "type": "topic",
      "url": "/documentation/objectivec/sel"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/OSXHIGuidelines/index.html#//apple_ref/doc/uid/20000957": {
      "identifier": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/OSXHIGuidelines/index.html#//apple_ref/doc/uid/20000957",
      "title": "macOS Human Interface Guidelines",
      "titleInlineContent": [
        {
          "text": "macOS Human Interface Guidelines",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/OSXHIGuidelines/index.html#//apple_ref/doc/uid/20000957"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/title",
          "value": "NSReleaseAlertPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReleaseAlertPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/title",
          "value": "NSAccessibilityRaiseBadArgumentException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRaiseBadArgumentException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/title",
          "value": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConvertGlyphsToPackedGlyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/title",
          "value": "NSAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlert"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbegincriticalalertsheet"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
