{
  "abstract": [
    {
      "text": "Creates and runs an alert sheet.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlert",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@NSBeginAlertSheet",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSBeginAlertSheet"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSBeginAlertSheet"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.10",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "NSBeginAlertSheet"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSBeginAlertSheet"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "title"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "defaultButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "alternateButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "otherButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWindow",
              "text": "NSWindow"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "docWindow"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "modalDelegate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SEL",
              "text": "SEL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "didEndSelector"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SEL",
              "text": "SEL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "didDismissSelector"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "contextInfo"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "msgFormat"
            },
            {
              "kind": "text",
              "text": ", ...);"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Creates and runs an alert sheet on ",
              "type": "text"
            },
            {
              "code": "docWindow",
              "type": "codeVoice"
            },
            {
              "text": ", with the title of ",
              "type": "text"
            },
            {
              "code": "title",
              "type": "codeVoice"
            },
            {
              "text": ", the text of ",
              "type": "text"
            },
            {
              "code": "msg",
              "type": "codeVoice"
            },
            {
              "text": ", and buttons with titles of ",
              "type": "text"
            },
            {
              "code": "defaultButton",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "alternateButton",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "otherButton",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The buttons are laid out on the lower-right corner of the sheet, with ",
              "type": "text"
            },
            {
              "code": "defaultButton",
              "type": "codeVoice"
            },
            {
              "text": " on the right, ",
              "type": "text"
            },
            {
              "code": "alternateButton",
              "type": "codeVoice"
            },
            {
              "text": " on the left, and ",
              "type": "text"
            },
            {
              "code": "otherButton",
              "type": "codeVoice"
            },
            {
              "text": " in the middle. If ",
              "type": "text"
            },
            {
              "code": "title",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " or an empty string, a default localized title is used (“Alert” in English). If ",
              "type": "text"
            },
            {
              "code": "defaultButton",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " or an empty string, a default localized button title (“OK” in English) is used. For the remaining buttons, this function creates them only if their corresponding button title is non-",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A Command-D key equivalent for the “Don’t Save” button is provided, if one is found. The button titles are searched for the localized value for “Don’t Save.” If a match is found, that button is assigned a Command-D key equivalent, provided it is not the default button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you create a modal panel using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can assign the key equivalent yourself, using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalentModifierMask",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "msg",
              "type": "codeVoice"
            },
            {
              "text": " argument is the message that’s displayed in the panel. It can use printf-style formatting characters; any necessary arguments should be listed at the end of the function’s argument list (after the ",
              "type": "text"
            },
            {
              "code": "msg",
              "type": "codeVoice"
            },
            {
              "text": " argument). For more information on formatting characters, see the man page for ",
              "type": "text"
            },
            {
              "code": "printf",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the modal session is ended, and before the sheet is dismissed, the ",
              "type": "text"
            },
            {
              "code": "didEndSelector",
              "type": "codeVoice"
            },
            {
              "text": " is invoked on the ",
              "type": "text"
            },
            {
              "code": "modalDelegate",
              "type": "codeVoice"
            },
            {
              "text": ". passing ",
              "type": "text"
            },
            {
              "code": "contextInfo",
              "type": "codeVoice"
            },
            {
              "text": ". After the sheet is dismissed, the ",
              "type": "text"
            },
            {
              "code": "didDismissSelector",
              "type": "codeVoice"
            },
            {
              "text": " is invoked on the ",
              "type": "text"
            },
            {
              "code": "modalDelegate",
              "type": "codeVoice"
            },
            {
              "text": ", passing ",
              "type": "text"
            },
            {
              "code": "contextInfo",
              "type": "codeVoice"
            },
            {
              "text": ". Typically, you will want to implement the ",
              "type": "text"
            },
            {
              "code": "didEndSelector",
              "type": "codeVoice"
            },
            {
              "text": " but you may pass ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " for the ",
              "type": "text"
            },
            {
              "code": "didDismissSelector",
              "type": "codeVoice"
            },
            {
              "text": ". The two selectors should be defined as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "sheetDidEnd:(NSWindow *)sheet returnCode:(int)returnCode contextInfo:(void  *)contextInfo;",
            "sheetDidDismiss:(NSWindow *)sheet returnCode:(int)returnCode contextInfo:(void  *)contextInfo;"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "where ",
              "type": "text"
            },
            {
              "code": "sheet",
              "type": "codeVoice"
            },
            {
              "text": " is the alert sheet, ",
              "type": "text"
            },
            {
              "code": "returnCode",
              "type": "codeVoice"
            },
            {
              "text": " specifies which button the user pressed, and ",
              "type": "text"
            },
            {
              "code": "contextInfo",
              "type": "codeVoice"
            },
            {
              "text": " is the same ",
              "type": "text"
            },
            {
              "code": "contextInfo",
              "type": "codeVoice"
            },
            {
              "text": " passed into ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". ",
              "type": "text"
            },
            {
              "code": "returnCode",
              "type": "codeVoice"
            },
            {
              "text": " can be one of the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlertDefaultReturn",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " means the user pressed the default button.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlertAlternateReturn",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " means the user pressed the alternate button.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlertOtherReturn",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " means the user pressed the other button.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlertErrorReturn",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " means an error occurred while running the alert panel.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)": {
      "abstract": [
        {
          "text": "Raises an error if the parameter is the wrong type or has an illegal value",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raiseBadArgumentException"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRaiseBadArgumentException"
        }
      ],
      "role": "symbol",
      "title": "raiseBadArgumentException(_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/raisebadargumentexception(_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlert": {
      "abstract": [
        {
          "text": "A modal dialog or sheet attached to a document window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAlert"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlert"
        }
      ],
      "role": "symbol",
      "title": "NSAlert",
      "type": "topic",
      "url": "/documentation/appkit/nsalert"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlertAlternateReturn": {
      "abstract": [
        {
          "text": "The user pressed the alternate button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAlertAlternateReturn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlertAlternateReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlertAlternateReturn"
        }
      ],
      "role": "symbol",
      "title": "NSAlertAlternateReturn",
      "type": "topic",
      "url": "/documentation/appkit/nsalertalternatereturn"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlertDefaultReturn": {
      "abstract": [
        {
          "text": "The user pressed the default button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAlertDefaultReturn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlertDefaultReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlertDefaultReturn"
        }
      ],
      "role": "symbol",
      "title": "NSAlertDefaultReturn",
      "type": "topic",
      "url": "/documentation/appkit/nsalertdefaultreturn"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlertErrorReturn": {
      "abstract": [
        {
          "text": "The alert cannot identify the reason it was closed; it may have been closed by an external source or by a button other than those listed above.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAlertErrorReturn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlertErrorReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlertErrorReturn"
        }
      ],
      "role": "symbol",
      "title": "NSAlertErrorReturn",
      "type": "topic",
      "url": "/documentation/appkit/nsalerterrorreturn"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlertOtherReturn": {
      "abstract": [
        {
          "text": "The user pressed a second alternate button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAlertOtherReturn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlertOtherReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlertOtherReturn"
        }
      ],
      "role": "symbol",
      "title": "NSAlertOtherReturn",
      "type": "topic",
      "url": "/documentation/appkit/nsalertotherreturn"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)": {
      "abstract": [
        {
          "text": "Starts a document modal session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSheet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modalFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modalDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/beginsheet(_:modalfor:modaldelegate:didend:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)": {
      "abstract": [
        {
          "text": "Starts a modal event loop for the specified window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalResponse",
          "text": "ModalResponse"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalForWindow:"
        }
      ],
      "role": "symbol",
      "title": "runModal(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/runmodal(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbeginalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginCriticalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginCriticalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegincriticalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginInformationalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginInformationalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegininformationalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalent": {
      "abstract": [
        {
          "text": "The key-equivalent character of the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyEquivalent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyEquivalent"
        }
      ],
      "role": "symbol",
      "title": "keyEquivalent",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/keyequivalent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalentModifierMask": {
      "abstract": [
        {
          "text": "The mask specifying the modifier keys for the button’s key equivalent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyEquivalentModifierMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventModifierFlags",
          "text": "ModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalentModifierMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyEquivalentModifierMask"
        }
      ],
      "role": "symbol",
      "title": "keyEquivalentModifierMask",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/keyequivalentmodifiermask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Prepares a set of glyphs for processing by character-based routines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSGlyph",
          "text": "NSGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMultibyteGlyphPacking",
          "text": "NSMultibyteGlyphPacking"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        }
      ],
      "role": "symbol",
      "title": "NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsconvertglyphstopackedglyphs(_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display a critical message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetcriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display an informational message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetinformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption": {
      "abstract": [
        {
          "text": "Returns global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion": {
      "abstract": [
        {
          "text": "Returns the NSOpenGL version numbers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption": {
      "abstract": [
        {
          "text": "Sets global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLSetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLSetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglsetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)": {
      "abstract": [
        {
          "text": "Disposes of an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        }
      ],
      "role": "symbol",
      "title": "NSReleaseAlertPanel(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsreleasealertpanel(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel": {
      "abstract": [
        {
          "text": "Creates an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsrunalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunAlertPanelRelativeToWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunAlertPanelRelativeToWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsrunalertpanelrelativetowindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruncriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruninformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@SEL": {
      "abstract": [
        {
          "text": "Defines an opaque type that represents a method selector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
      "kind": "symbol",
      "role": "symbol",
      "title": "SEL",
      "type": "topic",
      "url": "/documentation/objectivec/sel"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlertAlternateReturn/title",
          "value": "NSAlertAlternateReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlertAlternateReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlertAlternateReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/title",
          "value": "NSAccessibilityRaiseBadArgumentException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRaiseBadArgumentException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/title",
          "value": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConvertGlyphsToPackedGlyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlertOtherReturn/title",
          "value": "NSAlertOtherReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlertOtherReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlertOtherReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModal(for:)/title",
          "value": "runModalForWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModal(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalForWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1keyEquivalentModifierMask/title",
          "value": "keyEquivalentModifierMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1keyEquivalentModifierMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyEquivalentModifierMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/title",
          "value": "NSReleaseAlertPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReleaseAlertPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlertErrorReturn/title",
          "value": "NSAlertErrorReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlertErrorReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlertErrorReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlertDefaultReturn/title",
          "value": "NSAlertDefaultReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlertDefaultReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlertDefaultReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1keyEquivalent/title",
          "value": "keyEquivalent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1keyEquivalent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyEquivalent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)/title",
          "value": "beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/title",
          "value": "NSAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlert"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbeginalertsheet"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
