{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSBindingOption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSBindingOption"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSBindingOption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSBindingOption"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Values that are used as keys in the options dictionary passed to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1458185-bind",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "These keys are also used in the dictionary returned as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/options",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1458122-infoforbinding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". See the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Reference/CocoaBindingsRef/CocoaBindingsRef.html#//apple_ref/doc/uid/10000189i",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingInfoKey"
        }
      ],
      "role": "symbol",
      "title": "NSBindingInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nsbindinginfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/options": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": " object containing key value pairs as specified in the options",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "dictionary when the binding was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingInfoKey",
          "text": "NSBindingInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey/options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOptionsKey"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/appkit/nsbindinginfokey/options"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingName": {
      "abstract": [
        {
          "text": "Values that specify a binding for certain methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingName"
        }
      ],
      "role": "symbol",
      "title": "NSBindingName",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingOption"
        }
      ],
      "role": "symbol",
      "title": "NSBindingOption",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsEditingMultipleValuesSelection": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the binding allows editing when the value represents a multiple selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsEditingMultipleValuesSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsEditingMultipleValuesSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAllowsEditingMultipleValuesSelectionBindingOption"
        }
      ],
      "role": "symbol",
      "title": "allowsEditingMultipleValuesSelection",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/allowseditingmultiplevaluesselection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsNullArgument": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the argument bindings allows passing argument values of ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsNullArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsNullArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAllowsNullArgumentBindingOption"
        }
      ],
      "role": "symbol",
      "title": "allowsNullArgument",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/allowsnullargument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/alwaysPresentsApplicationModalAlerts": {
      "abstract": [
        {
          "text": "A number containing a Boolean value that determines if validation and error alert panels displayed as a result of this binding are displayed as application modal alerts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alwaysPresentsApplicationModalAlerts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/alwaysPresentsApplicationModalAlerts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlwaysPresentsApplicationModalAlertsBindingOption"
        }
      ],
      "role": "symbol",
      "title": "alwaysPresentsApplicationModalAlerts",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/alwayspresentsapplicationmodalalerts"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEditable": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the editable state of the user interface item is automatically configured based on the controller’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionallySetsEditable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEditable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConditionallySetsEditableBindingOption"
        }
      ],
      "role": "symbol",
      "title": "conditionallySetsEditable",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/conditionallysetseditable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEnabled": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the enabled state of the user interface item is automatically configured based on the controller’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionallySetsEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConditionallySetsEnabledBindingOption"
        }
      ],
      "role": "symbol",
      "title": "conditionallySetsEnabled",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/conditionallysetsenabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsHidden": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the hidden state of the user interface item is automatically configured based on the controller’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionallySetsHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConditionallySetsHiddenBindingOption"
        }
      ],
      "role": "symbol",
      "title": "conditionallySetsHidden",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/conditionallysetshidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/contentPlacementTag": {
      "abstract": [
        {
          "text": "A number that specifies the tag id of the popup menu item to replace with the content of the array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentPlacementTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/contentPlacementTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSContentPlacementTagBindingOption"
        }
      ],
      "role": "symbol",
      "title": "contentPlacementTag",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/contentplacementtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/continuouslyUpdatesValue": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines whether the value of the binding is updated as edits are made to the user interface item or is updated only when the user interface item resigns as the responder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuouslyUpdatesValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/continuouslyUpdatesValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSContinuouslyUpdatesValueBindingOption"
        }
      ],
      "role": "symbol",
      "title": "continuouslyUpdatesValue",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/continuouslyupdatesvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/createsSortDescriptor": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if a sort descriptor is created for a table column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createsSortDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/createsSortDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCreatesSortDescriptorBindingOption"
        }
      ],
      "role": "symbol",
      "title": "createsSortDescriptor",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/createssortdescriptor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/deletesObjectsOnRemove": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if an object is deleted from the managed context immediately upon being removed from a relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletesObjectsOnRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/deletesObjectsOnRemove",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeletesObjectsOnRemoveBindingsOption"
        }
      ],
      "role": "symbol",
      "title": "deletesObjectsOnRemove",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/deletesobjectsonremove"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayName": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object containing a human readable string to be displayed for a predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisplayNameBindingOption"
        }
      ],
      "role": "symbol",
      "title": "displayName",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/displayname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayPattern": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies a format string used to construct the final value of a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayPattern"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisplayPatternBindingOption"
        }
      ],
      "role": "symbol",
      "title": "displayPattern",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/displaypattern"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/handlesContentAsCompoundValue": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the content is treated as a compound value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handlesContentAsCompoundValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/handlesContentAsCompoundValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHandlesContentAsCompoundValueBindingOption"
        }
      ],
      "role": "symbol",
      "title": "handlesContentAsCompoundValue",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/handlescontentascompoundvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/insertsNullPlaceholder": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if an additional item which represents ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " is inserted into a matrix or pop-up menu before the items in the content array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertsNullPlaceholder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/insertsNullPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInsertsNullPlaceholderBindingOption"
        }
      ],
      "role": "symbol",
      "title": "insertsNullPlaceholder",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/insertsnullplaceholder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/invokesSeparatelyWithArrayObjects": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines whether the specified selector is invoked with the array as the argument or is invoked repeatedly with each array item as an argument.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invokesSeparatelyWithArrayObjects"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/invokesSeparatelyWithArrayObjects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInvokesSeparatelyWithArrayObjectsBindingOption"
        }
      ],
      "role": "symbol",
      "title": "invokesSeparatelyWithArrayObjects",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/invokesseparatelywitharrayobjects"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/multipleValuesPlaceholder": {
      "abstract": [
        {
          "text": "An object that is used as a placeholder when the key path of the bound controller returns the ",
          "type": "text"
        },
        {
          "code": "NSMultipleValuesMarker",
          "type": "codeVoice"
        },
        {
          "text": " marker for a binding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multipleValuesPlaceholder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/multipleValuesPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMultipleValuesPlaceholderBindingOption"
        }
      ],
      "role": "symbol",
      "title": "multipleValuesPlaceholder",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/multiplevaluesplaceholder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/noSelectionPlaceholder": {
      "abstract": [
        {
          "text": "An object that is used as a placeholder when the key path of the bound controller returns the ",
          "type": "text"
        },
        {
          "code": "NSNoSelectionMarker",
          "type": "codeVoice"
        },
        {
          "text": " marker for a binding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSelectionPlaceholder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/noSelectionPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoSelectionPlaceholderBindingOption"
        }
      ],
      "role": "symbol",
      "title": "noSelectionPlaceholder",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/noselectionplaceholder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/notApplicablePlaceholder": {
      "abstract": [
        {
          "text": "An object that is used as a placeholder when the key path of the bound controller returns the ",
          "type": "text"
        },
        {
          "code": "NSNotApplicableMarker",
          "type": "codeVoice"
        },
        {
          "text": " marker for a binding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notApplicablePlaceholder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/notApplicablePlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNotApplicablePlaceholderBindingOption"
        }
      ],
      "role": "symbol",
      "title": "notApplicablePlaceholder",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/notapplicableplaceholder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/nullPlaceholder": {
      "abstract": [
        {
          "text": "An object that is used as a placeholder when the key path of the bound controller returns ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " for a binding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullPlaceholder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/nullPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNullPlaceholderBindingOption"
        }
      ],
      "role": "symbol",
      "title": "nullPlaceholder",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/nullplaceholder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/predicateFormat": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the predicate pattern string for the predicate bindings. Use ",
          "type": "text"
        },
        {
          "code": "$value",
          "type": "codeVoice"
        },
        {
          "text": " to refer to the value in the search field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/predicateFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPredicateFormatBindingOption"
        }
      ],
      "role": "symbol",
      "title": "predicateFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/predicateformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/raisesForNotApplicableKeys": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that specifies if an exception is raised when the binding is bound to a key that is not applicable—for example when an object is not key-value coding compliant for a key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raisesForNotApplicableKeys"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/raisesForNotApplicableKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRaisesForNotApplicableKeysBindingOption"
        }
      ],
      "role": "symbol",
      "title": "raisesForNotApplicableKeys",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/raisesfornotapplicablekeys"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/selectorName": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies the method selector invoked by the target binding when the user interface item is clicked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectorName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/selectorName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSelectorNameBindingOption"
        }
      ],
      "role": "symbol",
      "title": "selectorName",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/selectorname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/selectsAllWhenSettingContent": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that specifies if all the items in the array controller are selected when the content is set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectsAllWhenSettingContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/selectsAllWhenSettingContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSelectsAllWhenSettingContentBindingOption"
        }
      ],
      "role": "symbol",
      "title": "selectsAllWhenSettingContent",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/selectsallwhensettingcontent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/validatesImmediately": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing a Boolean value that determines if the contents of the binding are validated immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validatesImmediately"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/validatesImmediately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSValidatesImmediatelyBindingOption"
        }
      ],
      "role": "symbol",
      "title": "validatesImmediately",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/validatesimmediately"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformer": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSValueTransformer",
          "type": "codeVoice"
        },
        {
          "text": " instance that is applied to the bound value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSValueTransformerBindingOption"
        }
      ],
      "role": "symbol",
      "title": "valueTransformer",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/valuetransformer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformerName": {
      "abstract": [
        {
          "text": "The value for this key is an identifier of a registered ",
          "type": "text"
        },
        {
          "code": "NSValueTransformer",
          "type": "codeVoice"
        },
        {
          "text": " instance that is applied to the bound value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueTransformerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBindingOption",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSValueTransformerNameBindingOption"
        }
      ],
      "role": "symbol",
      "title": "valueTransformerName",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption/valuetransformername"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController": {
      "abstract": [
        {
          "text": "A bindings-compatible controller that manages the display and editing of a dictionary of key-value pairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDictionaryController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDictionaryController"
        }
      ],
      "role": "symbol",
      "title": "NSDictionaryController",
      "type": "topic",
      "url": "/documentation/appkit/nsdictionarycontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair": {
      "abstract": [
        {
          "text": "A set of methods implemented by arranged objects to give access to information about those objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDictionaryControllerKeyValuePair"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDictionaryControllerKeyValuePair"
        }
      ],
      "role": "symbol",
      "title": "NSDictionaryControllerKeyValuePair",
      "type": "topic",
      "url": "/documentation/appkit/nsdictionarycontrollerkeyvaluepair"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)": {
      "abstract": [
        {
          "text": "Tests whether a given object is special marker object used for indicating the state of a selection in relation to a key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIsControllerMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIsControllerMarker"
        }
      ],
      "role": "symbol",
      "title": "NSIsControllerMarker(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsiscontrollermarker(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys": {
      "abstract": [
        {
          "text": "These constants define keys in the binding information dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Binding dictionary keys",
      "type": "topic",
      "url": "/documentation/appkit/binding-dictionary-keys"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1458122-infoforbinding": {
      "abstract": [
        {
          "text": "Returns a dictionary describing the receiver’s `binding`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "infoForBinding"
        },
        {
          "kind": "text",
          "text": "(NSBindingName) -> [NSBindingInfoKey : Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1458122-infoforbinding",
      "kind": "symbol",
      "role": "symbol",
      "title": "infoForBinding(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1458122-infoforbinding"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1458185-bind": {
      "abstract": [
        {
          "text": "Establishes a binding between a given property of the receiver and the property of a given object specified by a given key path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "bind"
        },
        {
          "kind": "text",
          "text": "(NSBindingName, "
        },
        {
          "kind": "identifier",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": Any, "
        },
        {
          "kind": "identifier",
          "text": "withKeyPath"
        },
        {
          "kind": "text",
          "text": ": String, "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": [NSBindingOption : Any]?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1458185-bind",
      "kind": "symbol",
      "role": "symbol",
      "title": "bind(_:to:withKeyPath:options:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1458185-bind"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation": {
      "abstract": [
        {
          "text": "A set of methods that you can use to create and remove bindings between view objects and controllers, or between controllers and model objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation",
      "kind": "article",
      "role": "article",
      "title": "NSKeyValueBindingCreation",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/nskeyvaluebindingcreation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Reference/CocoaBindingsRef/CocoaBindingsRef.html#//apple_ref/doc/uid/10000189i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Reference/CocoaBindingsRef/CocoaBindingsRef.html#//apple_ref/doc/uid/10000189i",
      "title": "Cocoa Bindings Reference",
      "titleInlineContent": [
        {
          "text": "Cocoa Bindings Reference",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Reference/CocoaBindingsRef/CocoaBindingsRef.html#//apple_ref/doc/uid/10000189i"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Key-Value-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
        "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
        "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation",
        "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys"
      ],
      "title": "Key-Value Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Binding-Options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsEditingMultipleValuesSelection",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsNullArgument",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/alwaysPresentsApplicationModalAlerts",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEditable",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEnabled",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsHidden",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/contentPlacementTag",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/continuouslyUpdatesValue",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/createsSortDescriptor",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/deletesObjectsOnRemove",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayName",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayPattern",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/handlesContentAsCompoundValue",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/insertsNullPlaceholder",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/invokesSeparatelyWithArrayObjects",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/multipleValuesPlaceholder",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/noSelectionPlaceholder",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/notApplicablePlaceholder",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/nullPlaceholder",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/predicateFormat",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/raisesForNotApplicableKeys",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/selectorName",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/selectsAllWhenSettingContent",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/validatesImmediately",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformer",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformerName"
      ],
      "title": "Binding Options"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBindingOption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Binding-Options",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsEditingMultipleValuesSelection",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/allowsNullArgument",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/alwaysPresentsApplicationModalAlerts",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEditable",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsEnabled",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/conditionallySetsHidden",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/contentPlacementTag",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/continuouslyUpdatesValue",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/createsSortDescriptor",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/deletesObjectsOnRemove",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayName",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/displayPattern",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/handlesContentAsCompoundValue",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/insertsNullPlaceholder",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/invokesSeparatelyWithArrayObjects",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/multipleValuesPlaceholder",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/noSelectionPlaceholder",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/notApplicablePlaceholder",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/nullPlaceholder",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/predicateFormat",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/raisesForNotApplicableKeys",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/selectorName",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/selectsAllWhenSettingContent",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/validatesImmediately",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformer",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption/valueTransformerName"
              ],
              "title": "Binding Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Key-Value-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
                "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
                "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation",
                "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys"
              ],
              "title": "Key-Value Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSBindingOption"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/title",
          "value": "NSDictionaryControllerKeyValuePair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryControllerKeyValuePair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryControllerKeyValuePair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/title",
          "value": "NSBindingInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11458185-bind/title",
          "value": "bind:toObject:withKeyPath:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1createsSortDescriptor/title",
          "value": "NSCreatesSortDescriptorBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1createsSortDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCreatesSortDescriptorBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsEditable/title",
          "value": "NSConditionallySetsEditableBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsEditable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConditionallySetsEditableBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1allowsNullArgument/title",
          "value": "NSAllowsNullArgumentBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1allowsNullArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAllowsNullArgumentBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1handlesContentAsCompoundValue/title",
          "value": "NSHandlesContentAsCompoundValueBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1handlesContentAsCompoundValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHandlesContentAsCompoundValueBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1validatesImmediately/title",
          "value": "NSValidatesImmediatelyBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1validatesImmediately/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValidatesImmediatelyBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1displayName/title",
          "value": "NSDisplayNameBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1displayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayNameBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1raisesForNotApplicableKeys/title",
          "value": "NSRaisesForNotApplicableKeysBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1raisesForNotApplicableKeys/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRaisesForNotApplicableKeysBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsEnabled/title",
          "value": "NSConditionallySetsEnabledBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConditionallySetsEnabledBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/title",
          "value": "NSBindingName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey~1options/title",
          "value": "NSOptionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey~1options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOptionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1nullPlaceholder/title",
          "value": "NSNullPlaceholderBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1nullPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNullPlaceholderBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1predicateFormat/title",
          "value": "NSPredicateFormatBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1predicateFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPredicateFormatBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIsControllerMarker(_:)/title",
          "value": "NSIsControllerMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIsControllerMarker(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIsControllerMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1noSelectionPlaceholder/title",
          "value": "NSNoSelectionPlaceholderBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1noSelectionPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoSelectionPlaceholderBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1continuouslyUpdatesValue/title",
          "value": "NSContinuouslyUpdatesValueBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1continuouslyUpdatesValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSContinuouslyUpdatesValueBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1selectorName/title",
          "value": "NSSelectorNameBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1selectorName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSelectorNameBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1alwaysPresentsApplicationModalAlerts/title",
          "value": "NSAlwaysPresentsApplicationModalAlertsBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1alwaysPresentsApplicationModalAlerts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlwaysPresentsApplicationModalAlertsBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1invokesSeparatelyWithArrayObjects/title",
          "value": "NSInvokesSeparatelyWithArrayObjectsBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1invokesSeparatelyWithArrayObjects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInvokesSeparatelyWithArrayObjectsBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1deletesObjectsOnRemove/title",
          "value": "NSDeletesObjectsOnRemoveBindingsOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1deletesObjectsOnRemove/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeletesObjectsOnRemoveBindingsOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1valueTransformer/title",
          "value": "NSValueTransformerBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1valueTransformer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValueTransformerBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1valueTransformerName/title",
          "value": "NSValueTransformerNameBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1valueTransformerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValueTransformerNameBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1selectsAllWhenSettingContent/title",
          "value": "NSSelectsAllWhenSettingContentBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1selectsAllWhenSettingContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSelectsAllWhenSettingContentBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/title",
          "value": "NSBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsHidden/title",
          "value": "NSConditionallySetsHiddenBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1conditionallySetsHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConditionallySetsHiddenBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1contentPlacementTag/title",
          "value": "NSContentPlacementTagBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1contentPlacementTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSContentPlacementTagBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11458122-infoforbinding/title",
          "value": "infoForBinding:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1multipleValuesPlaceholder/title",
          "value": "NSMultipleValuesPlaceholderBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1multipleValuesPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultipleValuesPlaceholderBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1displayPattern/title",
          "value": "NSDisplayPatternBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1displayPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayPatternBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1insertsNullPlaceholder/title",
          "value": "NSInsertsNullPlaceholderBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1insertsNullPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertsNullPlaceholderBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/title",
          "value": "NSDictionaryController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1notApplicablePlaceholder/title",
          "value": "NSNotApplicablePlaceholderBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1notApplicablePlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNotApplicablePlaceholderBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1allowsEditingMultipleValuesSelection/title",
          "value": "NSAllowsEditingMultipleValuesSelectionBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption~1allowsEditingMultipleValuesSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAllowsEditingMultipleValuesSelectionBindingOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbindingoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbindingoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
