{
  "abstract": [
    {
      "text": "A set of methods that a candidate list item delegate uses to enable selection state and list visibility.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSCandidateListTouchBarItemDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCandidateListTouchBarItemDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCandidateListTouchBarItemDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSCandidateListTouchBarItemDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItemDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem/client": {
      "abstract": [
        {
          "text": "The client object for the candidate list item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "client"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextInputClient",
          "text": "NSTextInputClient"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem/client",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "client"
        }
      ],
      "role": "symbol",
      "title": "client",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritem/client"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem/delegate": {
      "abstract": [
        {
          "text": "The delegate of the candidate list item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCandidateListTouchBarItemDelegate",
          "text": "NSCandidateListTouchBarItemDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritem/delegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate": {
      "abstract": [
        {
          "text": "A set of methods that a candidate list item delegate uses to enable selection state and list visibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCandidateListTouchBarItemDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCandidateListTouchBarItemDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSCandidateListTouchBarItemDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritemdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:beginSelectingCandidateAt:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has started touching one of the candidates in the candidate list item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "candidateListTouchBarItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCandidateListTouchBarItem",
          "text": "NSCandidateListTouchBarItem"
        },
        {
          "kind": "text",
          "text": "<AnyObject>, "
        },
        {
          "kind": "externalParam",
          "text": "beginSelectingCandidateAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:beginSelectingCandidateAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "candidateListTouchBarItem:beginSelectingCandidateAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "candidateListTouchBarItem(_:beginSelectingCandidateAt:)",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritemdelegate/candidatelisttouchbaritem(_:beginselectingcandidateat:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:changeSelectionFromCandidateAt:to:)": {
      "abstract": [
        {
          "text": "Tells the delegate that user has moved from touching one candidate in the candidate list item to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "candidateListTouchBarItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCandidateListTouchBarItem",
          "text": "NSCandidateListTouchBarItem"
        },
        {
          "kind": "text",
          "text": "<AnyObject>, "
        },
        {
          "kind": "externalParam",
          "text": "changeSelectionFromCandidateAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:changeSelectionFromCandidateAt:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "candidateListTouchBarItem:changeSelectionFromCandidateAtIndex:toIndex:"
        }
      ],
      "role": "symbol",
      "title": "candidateListTouchBarItem(_:changeSelectionFromCandidateAt:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritemdelegate/candidatelisttouchbaritem(_:changeselectionfromcandidateat:to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:changedCandidateListVisibility:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the visibility of the candidate list has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "candidateListTouchBarItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCandidateListTouchBarItem",
          "text": "NSCandidateListTouchBarItem"
        },
        {
          "kind": "text",
          "text": "<AnyObject>, "
        },
        {
          "kind": "externalParam",
          "text": "changedCandidateListVisibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:changedCandidateListVisibility:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "candidateListTouchBarItem:changedCandidateListVisibility:"
        }
      ],
      "role": "symbol",
      "title": "candidateListTouchBarItem(_:changedCandidateListVisibility:)",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritemdelegate/candidatelisttouchbaritem(_:changedcandidatelistvisibility:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:endSelectingCandidateAt:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a user has stopped touching candidates in the candidate list item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "candidateListTouchBarItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCandidateListTouchBarItem",
          "text": "NSCandidateListTouchBarItem"
        },
        {
          "kind": "text",
          "text": "<AnyObject>, "
        },
        {
          "kind": "externalParam",
          "text": "endSelectingCandidateAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:endSelectingCandidateAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "candidateListTouchBarItem:endSelectingCandidateAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "candidateListTouchBarItem(_:endSelectingCandidateAt:)",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritemdelegate/candidatelisttouchbaritem(_:endselectingcandidateat:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-a-client-and-a-delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem/client",
        "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem/delegate"
      ],
      "title": "Providing a client and a delegate"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-selection-changes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:beginSelectingCandidateAt:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:changeSelectionFromCandidateAt:to:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:endSelectingCandidateAt:)"
      ],
      "title": "Handling selection changes"
    },
    {
      "anchor": "Handling-visibility-changes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:changedCandidateListVisibility:)"
      ],
      "title": "Handling visibility changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCandidateListTouchBarItemDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItemDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItemDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-selection-changes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:beginSelectingCandidateAt:)",
                "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:changeSelectionFromCandidateAt:to:)",
                "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:endSelectingCandidateAt:)"
              ],
              "title": "Handling selection changes"
            },
            {
              "anchor": "Handling-visibility-changes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItemDelegate/candidateListTouchBarItem(_:changedCandidateListVisibility:)"
              ],
              "title": "Handling visibility changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-a-client-and-a-delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem/client",
                "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem/delegate"
              ],
              "title": "Providing a client and a delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCandidateListTouchBarItemDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate/title",
          "value": "NSCandidateListTouchBarItemDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItemDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItemDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate~1candidateListTouchBarItem(_:beginSelectingCandidateAt:)/title",
          "value": "candidateListTouchBarItem:beginSelectingCandidateAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate~1candidateListTouchBarItem(_:beginSelectingCandidateAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "candidateListTouchBarItem:beginSelectingCandidateAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate~1candidateListTouchBarItem(_:changedCandidateListVisibility:)/title",
          "value": "candidateListTouchBarItem:changedCandidateListVisibility:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate~1candidateListTouchBarItem(_:changedCandidateListVisibility:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "candidateListTouchBarItem:changedCandidateListVisibility:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem~1client/title",
          "value": "client"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem~1client/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "client"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate~1candidateListTouchBarItem(_:changeSelectionFromCandidateAt:to:)/title",
          "value": "candidateListTouchBarItem:changeSelectionFromCandidateAtIndex:toIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate~1candidateListTouchBarItem(_:changeSelectionFromCandidateAt:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "candidateListTouchBarItem:changeSelectionFromCandidateAtIndex:toIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate~1candidateListTouchBarItem(_:endSelectingCandidateAt:)/title",
          "value": "candidateListTouchBarItem:endSelectingCandidateAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItemDelegate~1candidateListTouchBarItem(_:endSelectingCandidateAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "candidateListTouchBarItem:endSelectingCandidateAtIndex:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscandidatelisttouchbaritemdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscandidatelisttouchbaritemdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
