{
  "abstract": [
    {
      "text": "The user cancelled the completion.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCancelTextMovement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSIllegalTextMovement@NSCancelTextMovement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCancelTextMovement"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCancelTextMovement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSCancelTextMovement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCancelTextMovement"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBacktabTextMovement": {
      "abstract": [
        {
          "text": "The Backtab (Shift-Tab) key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBacktabTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBacktabTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBacktabTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSBacktabTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsbacktabtextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCancelTextMovement": {
      "abstract": [
        {
          "text": "The user cancelled the completion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCancelTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCancelTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCancelTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSCancelTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nscanceltextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDownTextMovement": {
      "abstract": [
        {
          "text": "The down arrow key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDownTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDownTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDownTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSDownTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsdowntextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIllegalTextMovement": {
      "abstract": [
        {
          "text": "Currently unused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIllegalTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIllegalTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIllegalTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSIllegalTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsillegaltextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftTextMovement": {
      "abstract": [
        {
          "text": "The left arrow key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLeftTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLeftTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSLeftTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nslefttextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherTextMovement": {
      "abstract": [
        {
          "text": "The user performed some undefined action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOtherTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOtherTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSOtherTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsothertextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReturnTextMovement": {
      "abstract": [
        {
          "text": "The Return key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReturnTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReturnTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReturnTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSReturnTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsreturntextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightTextMovement": {
      "abstract": [
        {
          "text": "The right arrow key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRightTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRightTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSRightTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsrighttextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabTextMovement": {
      "abstract": [
        {
          "text": "The Tab key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTabTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSTabTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nstabtextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUpTextMovement": {
      "abstract": [
        {
          "text": "The up arrow key was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUpTextMovement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUpTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSUpTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nsuptextmovement"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSIllegalTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSReturnTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSTabTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSBacktabTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSRightTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSUpTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSDownTextMovement",
        "doc://com.apple.appkit/documentation/AppKit/NSOtherTextMovement"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCancelTextMovement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCancelTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSIllegalTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSReturnTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSTabTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSBacktabTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSLeftTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSRightTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSUpTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSDownTextMovement",
                "doc://com.apple.appkit/documentation/AppKit/NSOtherTextMovement"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSCancelTextMovement"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLeftTextMovement/title",
          "value": "NSLeftTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLeftTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLeftTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDownTextMovement/title",
          "value": "NSDownTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDownTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDownTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIllegalTextMovement/title",
          "value": "NSIllegalTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIllegalTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIllegalTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBacktabTextMovement/title",
          "value": "NSBacktabTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBacktabTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBacktabTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOtherTextMovement/title",
          "value": "NSOtherTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOtherTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOtherTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCancelTextMovement/title",
          "value": "NSCancelTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCancelTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCancelTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReturnTextMovement/title",
          "value": "NSReturnTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReturnTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReturnTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRightTextMovement/title",
          "value": "NSRightTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRightTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRightTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabTextMovement/title",
          "value": "NSTabTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUpTextMovement/title",
          "value": "NSUpTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUpTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpTextMovement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscanceltextmovement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscanceltextmovement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
