{
  "abstract": [
    {
      "text": "The image is clipped to produce one column or row of pages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSClipPagination"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSClipPagination",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSClipPagination"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSClipPagination"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSClipPagination"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/PaginationMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSPrintingPaginationMode",
              "text": "NSPrintingPaginationMode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSClipPagination"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAutoPagination": {
      "abstract": [
        {
          "text": "The image is divided into equal-sized rectangles and placed in one column of pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAutoPagination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAutoPagination",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAutoPagination",
      "type": "topic",
      "url": "/documentation/appkit/nsautopagination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSClipPagination": {
      "abstract": [
        {
          "text": "The image is clipped to produce one column or row of pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSClipPagination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSClipPagination",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSClipPagination",
      "type": "topic",
      "url": "/documentation/appkit/nsclippagination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFitPagination": {
      "abstract": [
        {
          "text": "The image is scaled to produce one column or one row of pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFitPagination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFitPagination",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFitPagination",
      "type": "topic",
      "url": "/documentation/appkit/nsfitpagination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/PaginationMode": {
      "abstract": [
        {
          "text": "Constants that specify the different ways in which an image is divided into pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaginationMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/PaginationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PaginationMode"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo.PaginationMode",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/paginationmode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAutoPagination",
        "doc://com.apple.appkit/documentation/AppKit/NSFitPagination"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1PaginationMode/title",
          "value": "NSPrintingPaginationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1PaginationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintingPaginationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1PaginationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintingPaginationMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsclippagination"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
