{"topicSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/init(leading:top:trailing:bottom:)"],"anchor":"Creating-edge-spacing","title":"Creating edge spacing"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/leading","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/top","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/trailing","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/bottom"],"anchor":"Getting-the-edge-spacing","title":"Getting the edge spacing"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"You use edge spacing to create additional spacing around the edges of an item to adjust the position of the item in relation to its container and other items."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The leading and trailing spaces within edge spacing differ in left-to-right versus right-to-left environments. In a left-to-right environment, the leading space is on the left, and the trailing space is on the right. In a right-to-left environment, the leading space is on the right, and the trailing space is on the left. This difference ensures that your collection view layout is built with support for right-to-left languages."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The following diagram shows the difference between adding 2 points of trailing edge spacing in a left-to-right versus a right-to-left environment."}],"type":"paragraph"},{"inlineContent":[{"identifier":"media-3570381","type":"image"}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutDimension","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSize","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSpacing","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutContainer"],"generated":true,"anchor":"Size-and-spacing","title":"Size and spacing"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"modules":[{"name":"AppKit"}],"roleHeading":"Class","externalID":"c:objc(cs)NSCollectionLayoutEdgeSpacing","title":"NSCollectionLayoutEdgeSpacing","platforms":[{"introducedAt":"10.15","beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}],"symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}]},"variants":[{"paths":["/documentation/appkit/nscollectionlayoutedgespacing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscollectionlayoutedgespacing"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"kind":"symbol","abstract":[{"text":"An object that defines the space around the edges of items in a collection view.","type":"text"}],"references":{"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"kind":"symbol","url":"/documentation/Swift/CustomStringConvertible","role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutContainer":{"title":"NSCollectionLayoutContainer","navigatorTitle":[{"text":"NSCollectionLayoutContainer","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutContainer","role":"symbol","url":"/documentation/appkit/nscollectionlayoutcontainer","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutContainer","kind":"identifier"}],"abstract":[{"text":"A protocol used to provide information about the size and content insets of a layout’s container.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/leading":{"abstract":[{"text":"The leading edge spacing value.","type":"text"}],"navigatorTitle":[{"text":"leading","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/leading","url":"/documentation/appkit/nscollectionlayoutedgespacing/leading","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leading","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"leading"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutDimension":{"url":"/documentation/appkit/nscollectionlayoutdimension","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutDimension"}],"role":"symbol","type":"topic","title":"NSCollectionLayoutDimension","abstract":[{"type":"text","text":"An individual dimension representing an item’s width or height in a collection view."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutDimension"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutDimension"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSpacing":{"abstract":[{"type":"text","text":"An object that defines the space between or around items in a collection view."}],"url":"/documentation/appkit/nscollectionlayoutspacing","kind":"symbol","role":"symbol","title":"NSCollectionLayoutSpacing","navigatorTitle":[{"text":"NSCollectionLayoutSpacing","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSpacing","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutSpacing","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","title":"CVarArg","kind":"symbol","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"role":"symbol","type":"topic","title":"NSCopying","url":"/documentation/foundation/nscopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","kind":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"kind":"identifier","text":"NSCopying"}],"abstract":[{"type":"text","text":"A protocol that objects adopt to provide functional copies of themselves."}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"type":"text","text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects."}],"url":"/documentation/objectivec/nsobject","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","role":"symbol","type":"topic","title":"NSObject"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing":{"title":"NSCollectionLayoutEdgeSpacing","navigatorTitle":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing","role":"symbol","url":"/documentation/appkit/nscollectionlayoutedgespacing","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that defines the space around the edges of items in a collection view."}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSize":{"type":"topic","role":"symbol","title":"NSCollectionLayoutSize","url":"/documentation/appkit/nscollectionlayoutsize","navigatorTitle":[{"text":"NSCollectionLayoutSize","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSize","kind":"symbol","abstract":[{"text":"The width and the height of an item in a collection view.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutSize","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/top":{"abstract":[{"text":"The top edge spacing value.","type":"text"}],"navigatorTitle":[{"text":"top","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/top","url":"/documentation/appkit/nscollectionlayoutedgespacing/top","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"top"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/trailing":{"kind":"symbol","url":"/documentation/appkit/nscollectionlayoutedgespacing/trailing","title":"trailing","navigatorTitle":[{"text":"trailing","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"The trailing edge spacing value.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/trailing","role":"symbol"},"media-3570381":{"identifier":"media-3570381","alt":"Two diagrams that compare edge spacing in a left-to-right and a right-to-left environment. Both diagrams show a group of three square items in a row. The first diagram, labeled trailing in left-to-right environment, shows trailing space on the right of each item, implying that leading space is on the left. The second diagram, labeled trailing in right-to-left environment, shows trailing space on the left of each item, implying that leading space is on the right.","variants":[{"url":"https://docs-assets.developer.apple.com/published/a315a0a064f715f044a87ad23b139457/media-3570381@2x.png","traits":["2x","light"]},{"url":"https://docs-assets.developer.apple.com/published/0eb1dca0c8e3363af7104445aa047c88/media-3570381~dark@2x.png","traits":["2x","dark"]}],"type":"image"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/init(leading:top:trailing:bottom:)":{"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"leading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCollectionLayoutSpacing","preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCollectionLayoutSpacing","preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"trailing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCollectionLayoutSpacing","preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing"},{"kind":"text","text":"?, "},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCollectionLayoutSpacing","preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Creates an edge spacing object with the specified leading, top, trailing, and bottom spacing."}],"url":"/documentation/appkit/nscollectionlayoutedgespacing/init(leading:top:trailing:bottom:)","title":"init(leading:top:trailing:bottom:)","role":"symbol","navigatorTitle":[{"text":"spacingForLeading:top:trailing:bottom:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/init(leading:top:trailing:bottom:)"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/bottom":{"type":"topic","role":"symbol","title":"bottom","url":"/documentation/appkit/nscollectionlayoutedgespacing/bottom","navigatorTitle":[{"text":"bottom","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/bottom","kind":"symbol","abstract":[{"text":"The bottom edge spacing value.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSpacing","text":"NSCollectionLayoutSpacing","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","role":"symbol","type":"topic","title":"CustomDebugStringConvertible"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.15","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Class","path":"/metadata/roleHeading","op":"replace"},{"value":"NSCollectionLayoutEdgeSpacing","path":"/metadata/title","op":"replace"},{"value":"class","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NSCollectionLayoutEdgeSpacing"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"path":"/topicSections","op":"replace","value":[{"title":"Creating edge spacing","anchor":"Creating-edge-spacing","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/init(leading:top:trailing:bottom:)"]},{"title":"Getting the edge spacing","anchor":"Getting-the-edge-spacing","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/leading","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/top","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/trailing","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEdgeSpacing/bottom"]}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"]}],"op":"replace","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutDimension","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSize","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSpacing","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutContainer"],"anchor":"Size-and-spacing","generated":true,"title":"Size and spacing"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutEdgeSpacing"},{"kind":"text","text":" : "},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"NSCollectionLayoutContainer","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutContainer/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutContainer/fragments","op":"replace","value":[{"text":"NSCollectionLayoutContainer","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutContainer/navigatorTitle","op":"replace","value":[{"text":"NSCollectionLayoutContainer","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1leading/title","op":"replace","value":"leading"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1leading/fragments","op":"replace","value":[{"kind":"identifier","text":"leading"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutDimension/title","op":"replace","value":"NSCollectionLayoutDimension"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutDimension/fragments","op":"replace","value":[{"text":"NSCollectionLayoutDimension","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutDimension/navigatorTitle","op":"replace","value":[{"text":"NSCollectionLayoutDimension","kind":"identifier"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSpacing/title","op":"replace","value":"NSCollectionLayoutSpacing"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSpacing/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSpacing"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSpacing/navigatorTitle","op":"replace","value":[{"text":"NSCollectionLayoutSpacing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing/title","op":"replace","value":"NSCollectionLayoutEdgeSpacing"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing/fragments","op":"replace","value":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing/navigatorTitle","op":"replace","value":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSize/title","op":"replace","value":"NSCollectionLayoutSize"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSize/fragments","op":"replace","value":[{"text":"NSCollectionLayoutSize","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSize/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSize"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1top/title","op":"replace","value":"top"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1top/fragments","op":"replace","value":[{"kind":"identifier","text":"top"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1trailing/title","op":"replace","value":"trailing"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1trailing/fragments","op":"replace","value":[{"text":"trailing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1init(leading:top:trailing:bottom:)/title","op":"replace","value":"spacingForLeading:top:trailing:bottom:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1init(leading:top:trailing:bottom:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"spacingForLeading:top:trailing:bottom:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1bottom/title","op":"replace","value":"bottom"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEdgeSpacing~1bottom/fragments","op":"replace","value":[{"text":"bottom","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}