{
  "abstract": [
    {
      "text": "An object that represents a custom color space.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSColorSpace",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSColorSpace"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSColorSpace"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSColorSpace"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can make custom color spaces from ColorSync profiles or from ICC profiles. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " also has factory methods that return objects representing the system color spaces.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:components:count:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to create color objects using custom ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. You can also send the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/usingColorSpace(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " message to an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to convert it between two color spaces, either of which may be a custom color space.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:components:count:)": {
      "abstract": [
        {
          "text": "Creates a color object from the specified components of the given color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "components"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/init(colorSpace:components:count:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithColorSpace:components:count:"
        }
      ],
      "role": "symbol",
      "title": "init(colorSpace:components:count:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/init(colorspace:components:count:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/usingColorSpace(_:)": {
      "abstract": [
        {
          "text": "Creates a new color object representing the color of the current color object in the specified color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usingColorSpace"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/usingColorSpace(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorUsingColorSpace:"
        }
      ],
      "role": "symbol",
      "title": "usingColorSpace(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/usingcolorspace(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorList": {
      "abstract": [
        {
          "text": "An ordered list of color objects, identified by keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorList"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorList"
        }
      ],
      "role": "symbol",
      "title": "NSColorList",
      "type": "topic",
      "url": "/documentation/appkit/nscolorlist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace": {
      "abstract": [
        {
          "text": "An object that represents a custom color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model": {
      "abstract": [
        {
          "text": "Constants that describe the abstract model on which color space objects are based.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Model"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Model"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/adobeRGB1998": {
      "abstract": [
        {
          "text": "A color space object that represents an Adobe RGB (1998) color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeRGB1998"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/adobeRGB1998",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adobeRGB1998ColorSpace"
        }
      ],
      "role": "symbol",
      "title": "adobeRGB1998",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/adobergb1998"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/availableColorSpaces(with:)": {
      "abstract": [
        {
          "text": "Returns the list of color spaces available on the system that are displayed in the color panel, in the order they are displayed in the color panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableColorSpaces"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSColorSpaceModel",
          "text": "Model"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/availableColorSpaces(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableColorSpacesWithModel:"
        }
      ],
      "role": "symbol",
      "title": "availableColorSpaces(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/availablecolorspaces(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/cgColorSpace": {
      "abstract": [
        {
          "text": "The Core Graphics color-space object that represents a color space equivalent to the color space’s.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cgColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/cgColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGColorSpace"
        }
      ],
      "role": "symbol",
      "title": "cgColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/cgcolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSpaceModel": {
      "abstract": [
        {
          "text": "The model on which the color space is based.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpaceModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSColorSpaceModel",
          "text": "Model"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSpaceModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSpaceModel"
        }
      ],
      "role": "symbol",
      "title": "colorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/colorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSyncProfile": {
      "abstract": [
        {
          "text": "The ColorSync profile from which the color space was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSyncProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSyncProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSyncProfile"
        }
      ],
      "role": "symbol",
      "title": "colorSyncProfile",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/colorsyncprofile"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceCMYK": {
      "abstract": [
        {
          "text": "A color space object that represents a calibrated or device-dependent CMYK color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCMYK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceCMYK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceCMYKColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceCMYK",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/devicecmyk"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceGray": {
      "abstract": [
        {
          "text": "A color space object that represents a calibrated or device-dependent gray color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceGray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceGray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceGrayColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceGray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/devicegray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceRGB": {
      "abstract": [
        {
          "text": "A color space object that represents a calibrated or device-dependent RGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/devicergb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/displayP3": {
      "abstract": [
        {
          "text": "A color space object that represents a P3 Display color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayP3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/displayP3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayP3ColorSpace"
        }
      ],
      "role": "symbol",
      "title": "displayP3",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/displayp3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedGenericGamma22Gray": {
      "abstract": [
        {
          "text": "A color space object that represents an extended gray color space with a gamma value of 2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedGenericGamma22Gray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedGenericGamma22Gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedGenericGamma22GrayColorSpace"
        }
      ],
      "role": "symbol",
      "title": "extendedGenericGamma22Gray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/extendedgenericgamma22gray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedSRGB": {
      "abstract": [
        {
          "text": "A color space object that represents an extended sRGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedSRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedSRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedSRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "extendedSRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/extendedsrgb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericCMYK": {
      "abstract": [
        {
          "text": "A color space object that represents a device-independent CMYK color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericCMYK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericCMYK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genericCMYKColorSpace"
        }
      ],
      "role": "symbol",
      "title": "genericCMYK",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/genericcmyk"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGamma22Gray": {
      "abstract": [
        {
          "text": "A color space object that represents a gray color space with a gamma value of 2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericGamma22Gray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGamma22Gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genericGamma22GrayColorSpace"
        }
      ],
      "role": "symbol",
      "title": "genericGamma22Gray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/genericgamma22gray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGray": {
      "abstract": [
        {
          "text": "A color space object that represents a device-independent gray color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericGray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genericGrayColorSpace"
        }
      ],
      "role": "symbol",
      "title": "genericGray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/genericgray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericRGB": {
      "abstract": [
        {
          "text": "A color space object that represents a device-independent RGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genericRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "genericRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/genericrgb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/iccProfileData": {
      "abstract": [
        {
          "text": "The ICC profile data from which the color space was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iccProfileData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/iccProfileData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCProfileData"
        }
      ],
      "role": "symbol",
      "title": "iccProfileData",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/iccprofiledata"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(cgColorSpace:)": {
      "abstract": [
        {
          "text": "Initializes and returns a color space object initialized from a Core Graphics color-space object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "cgColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(cgColorSpace:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCGColorSpace:"
        }
      ],
      "role": "symbol",
      "title": "init(cgColorSpace:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/init(cgcolorspace:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(colorSyncProfile:)": {
      "abstract": [
        {
          "text": "Initializes and returns a color space object from the specified ColorSync profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "colorSyncProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(colorSyncProfile:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithColorSyncProfile:"
        }
      ],
      "role": "symbol",
      "title": "init(colorSyncProfile:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/init(colorsyncprofile:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(iccProfileData:)": {
      "abstract": [
        {
          "text": "Initializes and returns a color space object from the specified ICC profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "iccProfileData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(iccProfileData:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithICCProfileData:"
        }
      ],
      "role": "symbol",
      "title": "init(iccProfileData:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/init(iccprofiledata:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/localizedName": {
      "abstract": [
        {
          "text": "The localized name of the color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/localizedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedName"
        }
      ],
      "role": "symbol",
      "title": "localizedName",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/localizedname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/numberOfColorComponents": {
      "abstract": [
        {
          "text": "The number of components, excluding alpha, the color space supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfColorComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/numberOfColorComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfColorComponents"
        }
      ],
      "role": "symbol",
      "title": "numberOfColorComponents",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/numberofcolorcomponents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/sRGB": {
      "abstract": [
        {
          "text": "A color space object that represents an sRGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/sRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "sRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/srgb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Colors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColorList"
      ],
      "title": "Colors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-a-Named-Color-Space",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceCMYK",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericCMYK",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceGray",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGray",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/sRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedSRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/displayP3",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGamma22Gray",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedGenericGamma22Gray",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/adobeRGB1998"
      ],
      "title": "Getting a Named Color Space"
    },
    {
      "anchor": "Getting-the-Color-Spaces-Available-On-the-System",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/availableColorSpaces(with:)"
      ],
      "title": "Getting the Color Spaces Available On the System"
    },
    {
      "anchor": "Initializing-a-Custom-Color-Space-Object",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(cgColorSpace:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(colorSyncProfile:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(iccProfileData:)"
      ],
      "title": "Initializing a Custom Color Space Object"
    },
    {
      "anchor": "Accessing-Color-Space-Data-and-Attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/cgColorSpace",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSpaceModel",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSyncProfile",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/iccProfileData",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/localizedName",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/numberOfColorComponents"
      ],
      "title": "Accessing Color Space Data and Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSColorSpace"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-a-Named-Color-Space",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceCMYK",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericCMYK",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceGray",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGray",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/sRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedSRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/displayP3",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGamma22Gray",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedGenericGamma22Gray",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/adobeRGB1998"
              ],
              "title": "Getting a Named Color Space"
            },
            {
              "anchor": "Getting-the-Color-Spaces-Available-On-the-System",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/availableColorSpaces(with:)"
              ],
              "title": "Getting the Color Spaces Available On the System"
            },
            {
              "anchor": "Initializing-a-Custom-Color-Space-Object",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(cgColorSpace:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(colorSyncProfile:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/init(iccProfileData:)"
              ],
              "title": "Initializing a Custom Color Space Object"
            },
            {
              "anchor": "Accessing-Color-Space-Data-and-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/cgColorSpace",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSyncProfile",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/iccProfileData",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/localizedName",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/numberOfColorComponents"
              ],
              "title": "Accessing Color Space Data and Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Colors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor",
                "doc://com.apple.appkit/documentation/AppKit/NSColorList"
              ],
              "title": "Colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSColorSpace"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1numberOfColorComponents/title",
          "value": "numberOfColorComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1numberOfColorComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfColorComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericCMYK/title",
          "value": "genericCMYKColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericCMYK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericCMYKColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1init(colorSyncProfile:)/title",
          "value": "initWithColorSyncProfile:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1init(colorSyncProfile:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithColorSyncProfile:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceCMYK/title",
          "value": "deviceCMYKColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceCMYK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceCMYKColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1colorSpaceModel/title",
          "value": "colorSpaceModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1colorSpaceModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericRGB/title",
          "value": "genericRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1iccProfileData/title",
          "value": "ICCProfileData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1iccProfileData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCProfileData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1availableColorSpaces(with:)/title",
          "value": "availableColorSpacesWithModel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1availableColorSpaces(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "availableColorSpacesWithModel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1displayP3/title",
          "value": "displayP3ColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1displayP3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayP3ColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1sRGB/title",
          "value": "sRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1sRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericGray/title",
          "value": "genericGrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericGray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericGrayColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1extendedGenericGamma22Gray/title",
          "value": "extendedGenericGamma22GrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1extendedGenericGamma22Gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedGenericGamma22GrayColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceGray/title",
          "value": "deviceGrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceGray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceGrayColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1localizedName/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1localizedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList/title",
          "value": "NSColorList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1init(iccProfileData:)/title",
          "value": "initWithICCProfileData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1init(iccProfileData:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithICCProfileData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(colorSpace:components:count:)/title",
          "value": "colorWithColorSpace:components:count:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1init(colorSpace:components:count:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "colorWithColorSpace:components:count:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/title",
          "value": "NSColorSpaceModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1adobeRGB1998/title",
          "value": "adobeRGB1998ColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1adobeRGB1998/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adobeRGB1998ColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericGamma22Gray/title",
          "value": "genericGamma22GrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericGamma22Gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericGamma22GrayColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1colorSyncProfile/title",
          "value": "colorSyncProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1colorSyncProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSyncProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1extendedSRGB/title",
          "value": "extendedSRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1extendedSRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedSRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceRGB/title",
          "value": "deviceRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1cgColorSpace/title",
          "value": "CGColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1cgColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1init(cgColorSpace:)/title",
          "value": "initWithCGColorSpace:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1init(cgColorSpace:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCGColorSpace:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/title",
          "value": "NSColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1usingColorSpace(_:)/title",
          "value": "colorUsingColorSpace:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1usingColorSpace(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "colorUsingColorSpace:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolorspace"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolorspace"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
