{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscollectionlayoutanchor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscollectionlayoutanchor"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutAnchor","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"You use an anchor to attach a supplementary item to a specific item. An anchor contains information about where on the item your supplementary item is attached, including:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An edge or set of edges. You can attach a supplementary item to a single edge, or to a corner by specifying two adjacent edges.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An offset from the item. By default, the supplementary item is anchored within the specified edges of the item it’s attached to. You can change this location by providing a custom offset when you create an anchor."}]}]}]},{"anchor":"Edges","type":"heading","text":"Edges","level":3},{"inlineContent":[{"text":"The leading and trailing edges for anchors differ in left-to-right versus right-to-left environments. In a left-to-right environment, the leading edge is on the left, and the trailing edge is on the right. In a right-to-left environment, the leading edge is on the right, and the trailing edge is on the left. This difference ensures that your collection view layout is built with support for right-to-left languages.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The following diagram shows anchor placement for the specified edges in a left-to-right environment.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"image","identifier":"media-3570665"}],"type":"paragraph"},{"anchor":"Offset","type":"heading","text":"Offset","level":3},{"inlineContent":[{"text":"You can express anchor offset in these ways:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Absolute value. The offset is calculated as a point value. For example, an absolute x offset of ","type":"text"},{"type":"codeVoice","code":"30.0"},{"text":" means that the origin of the supplementary item is offset by 30 points in the positive x direction.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Fractional value. The offset is calculated as a fraction of the supplementary item’s dimensions. For example, a fractional x offset of "},{"type":"codeVoice","code":"0.3"},{"type":"text","text":" means that the origin of the supplementary item is offset by 30% of the supplementary item’s width in the positive x direction."}],"type":"paragraph"}]}]},{"inlineContent":[{"text":"The following code creates a basic badge and attaches it to an item’s top trailing corner.","type":"text"}],"type":"paragraph"},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"syntax":"swift","type":"codeListing","code":["let itemSize = NSCollectionLayoutSize(widthDimension: .absolute(44),","                                     heightDimension: .absolute(44))","    ","let badgeAnchor = NSCollectionLayoutAnchor(edges: [.top, .trailing],","                                fractionalOffset: CGPoint(x: 0.3, y: -0.3))","    ","let badgeSize = NSCollectionLayoutSize(widthDimension: .absolute(20),","                                      heightDimension: .absolute(20))","    ","let badge = NSCollectionLayoutSupplementaryItem(layoutSize: badgeSize,","                                               elementKind: \"badge\",","                                           containerAnchor: badgeAnchor)","    ","let item = NSCollectionLayoutItem(layoutSize: itemSize,","                          supplementaryItems: [badge])",""]}]},{"title":"Objective-C","content":[{"code":["NSCollectionLayoutSize *itemSize = [NSCollectionLayoutSize sizeWithWidthDimension:[NSCollectionLayoutDimension absoluteDimension:44.0] heightDimension:[NSCollectionLayoutDimension absoluteDimension:44.0]];","","NSCollectionLayoutAnchor *badgeAnchor = [NSCollectionLayoutAnchor layoutAnchorWithEdges: NSDirectionalRectEdgeTop|NSDirectionalRectEdgeTrailing fractionalOffset:CGPointMake(0.3, -0.3)];","","NSCollectionLayoutSize *badgeSize = [NSCollectionLayoutSize sizeWithWidthDimension:[NSCollectionLayoutDimension absoluteDimension:20.0] heightDimension:[NSCollectionLayoutDimension absoluteDimension:20.0]];","","NSCollectionLayoutSupplementaryItem *badge = [NSCollectionLayoutSupplementaryItem supplementaryItemWithLayoutSize:badgeSize elementKind:ELEMENT_KIND_BADGE containerAnchor:badgeAnchor];","","NSCollectionLayoutItem *item = [NSCollectionLayoutItem itemWithLayoutSize:itemSize supplementaryItems:@[badge]];"],"type":"codeListing","syntax":"objc"}]}]}]}],"abstract":[{"text":"An object that defines how to attach a supplementary item to an item in a collection view.","type":"text"}],"topicSections":[{"anchor":"Creating-an-anchor","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:absoluteOffset:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:fractionalOffset:)"],"title":"Creating an anchor"},{"anchor":"Getting-the-edges","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/edges"],"title":"Getting the edges"},{"anchor":"Getting-the-offset","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/offset","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isAbsoluteOffset","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isFractionalOffset"],"title":"Getting the offset"}],"kind":"symbol","metadata":{"symbolKind":"class","modules":[{"name":"AppKit"}],"title":"NSCollectionLayoutAnchor","platforms":[{"deprecated":false,"beta":false,"introducedAt":"10.15","unavailable":false,"name":"macOS"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutAnchor"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutAnchor"}],"externalID":"c:objc(cs)NSCollectionLayoutAnchor"},"sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Appearance","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutBoundarySupplementaryItem","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSupplementaryItem","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutDecorationItem"],"title":"Appearance"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","role":"symbol","type":"topic","title":"CustomDebugStringConvertible"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutBoundarySupplementaryItem":{"type":"topic","role":"symbol","title":"NSCollectionLayoutBoundarySupplementaryItem","url":"/documentation/appkit/nscollectionlayoutboundarysupplementaryitem","navigatorTitle":[{"text":"NSCollectionLayoutBoundarySupplementaryItem","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutBoundarySupplementaryItem","kind":"symbol","abstract":[{"text":"An object used to add headers or footers to a collection view.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutBoundarySupplementaryItem","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/offset":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/offset","url":"/documentation/appkit/nscollectionlayoutanchor/offset","title":"offset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"offset"}],"abstract":[{"type":"text","text":"The floating-point value of the anchor’s offset from the item it’s attached to."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"offset"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSupplementaryItem":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutSupplementaryItem","kind":"identifier"}],"url":"/documentation/appkit/nscollectionlayoutsupplementaryitem","title":"NSCollectionLayoutSupplementaryItem","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSupplementaryItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutSupplementaryItem","kind":"identifier"}],"abstract":[{"type":"text","text":"An object used to add an extra visual decoration to an item in a collection view."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor":{"url":"/documentation/appkit/nscollectionlayoutanchor","kind":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSCollectionLayoutAnchor","abstract":[{"type":"text","text":"An object that defines how to attach a supplementary item to an item in a collection view."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:absoluteOffset:)":{"role":"symbol","title":"init(edges:absoluteOffset:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates an anchor with the specified edges to attach to, offset by the provided absolute value."}],"url":"/documentation/appkit/nscollectionlayoutanchor/init(edges:absoluteoffset:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:absoluteOffset:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"absoluteOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"layoutAnchorWithEdges:absoluteOffset:"}]},"media-3570665":{"alt":"Diagram showing anchor positions. Top, bottom, leading, and trailing anchors are on the halfway point on their respective edges. The anchors defined by the edge combinations top and leading, top and trailing, bottom and leading, and bottom and trailing are in the corners between each of those sets of edges.","identifier":"media-3570665","type":"image","variants":[{"url":"https://docs-assets.developer.apple.com/published/b7e68b458cab77379003c0ce5e2ef3e9/media-3570665@2x.png","traits":["2x","light"]},{"url":"https://docs-assets.developer.apple.com/published/90a0677fdd2f803d9388e6a44dca75c3/media-3570665~dark@2x.png","traits":["2x","dark"]}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"role":"symbol","type":"topic","title":"NSCopying","url":"/documentation/foundation/nscopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","kind":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"kind":"identifier","text":"NSCopying"}],"abstract":[{"type":"text","text":"A protocol that objects adopt to provide functional copies of themselves."}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isFractionalOffset":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isFractionalOffset","url":"/documentation/appkit/nscollectionlayoutanchor/isfractionaloffset","title":"isFractionalOffset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFractionalOffset"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the anchor’s offset is expressed as a fraction of its supplementary item’s dimension."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFractionalOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:)":{"title":"init(edges:)","abstract":[{"type":"text","text":"Creates an anchor with the specified edges to attach to."}],"role":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nscollectionlayoutanchor/init(edges:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:)","navigatorTitle":[{"kind":"identifier","text":"layoutAnchorWithEdges:"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutDecorationItem":{"title":"NSCollectionLayoutDecorationItem","navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutDecorationItem"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutDecorationItem","role":"symbol","url":"/documentation/appkit/nscollectionlayoutdecorationitem","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutDecorationItem"}],"abstract":[{"text":"An object used to add a background to a section of a collection view.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/edges":{"title":"edges","abstract":[{"type":"text","text":"The edges of the item an anchor is attached to."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"edges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"}],"kind":"symbol","url":"/documentation/appkit/nscollectionlayoutanchor/edges","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/edges","navigatorTitle":[{"kind":"identifier","text":"edges"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"kind":"symbol","url":"/documentation/Swift/CustomStringConvertible","role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isAbsoluteOffset":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isAbsoluteOffset","url":"/documentation/appkit/nscollectionlayoutanchor/isabsoluteoffset","title":"isAbsoluteOffset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isAbsoluteOffset"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the anchor’s offset is expressed as an absolute value."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAbsoluteOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","title":"CVarArg","kind":"symbol","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"type":"text","text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects."}],"url":"/documentation/objectivec/nsobject","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","role":"symbol","type":"topic","title":"NSObject"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:fractionalOffset:)":{"title":"init(edges:fractionalOffset:)","abstract":[{"type":"text","text":"Creates an anchor with the specified edges to attach to, offset by the provided fractional value."}],"role":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"edges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fractionalOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nscollectionlayoutanchor/init(edges:fractionaloffset:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:fractionalOffset:)","navigatorTitle":[{"kind":"identifier","text":"layoutAnchorWithEdges:fractionalOffset:"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"10.15"}],"op":"replace","path":"/metadata/platforms"},{"value":"Class","op":"replace","path":"/metadata/roleHeading"},{"value":"NSCollectionLayoutAnchor","op":"replace","path":"/metadata/title"},{"value":"class","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"anchor":"Creating-an-anchor","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:absoluteOffset:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/init(edges:fractionalOffset:)"],"title":"Creating an anchor"},{"anchor":"Getting-the-edges","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/edges"],"title":"Getting the edges"},{"anchor":"Getting-the-offset","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/offset","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isAbsoluteOffset","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutAnchor/isFractionalOffset"],"title":"Getting the offset"}],"op":"replace"},{"path":"/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"title":"Appearance","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutBoundarySupplementaryItem","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSupplementaryItem","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutDecorationItem"],"anchor":"Appearance"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutAnchor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutBoundarySupplementaryItem/title","value":"NSCollectionLayoutBoundarySupplementaryItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutBoundarySupplementaryItem/fragments","value":[{"kind":"identifier","text":"NSCollectionLayoutBoundarySupplementaryItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutBoundarySupplementaryItem/navigatorTitle","value":[{"kind":"identifier","text":"NSCollectionLayoutBoundarySupplementaryItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1offset/title","value":"offset","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1offset/fragments","value":[{"kind":"identifier","text":"offset"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSupplementaryItem/title","value":"NSCollectionLayoutSupplementaryItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSupplementaryItem/fragments","value":[{"kind":"identifier","text":"NSCollectionLayoutSupplementaryItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSupplementaryItem/navigatorTitle","value":[{"text":"NSCollectionLayoutSupplementaryItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/title","value":"NSCollectionLayoutAnchor","op":"replace"},{"op":"replace","value":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/fragments"},{"op":"replace","value":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor/navigatorTitle"},{"op":"replace","value":"layoutAnchorWithEdges:absoluteOffset:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:absoluteOffset:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"layoutAnchorWithEdges:absoluteOffset:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:absoluteOffset:)/fragments"},{"op":"replace","value":"isFractionalOffset","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1isFractionalOffset/title"},{"op":"replace","value":[{"text":"isFractionalOffset","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1isFractionalOffset/fragments"},{"op":"replace","value":"layoutAnchorWithEdges:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"layoutAnchorWithEdges:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:)/fragments"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"NSCollectionLayoutDecorationItem","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutDecorationItem/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutDecorationItem"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutDecorationItem/fragments"},{"op":"replace","value":[{"text":"NSCollectionLayoutDecorationItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutDecorationItem/navigatorTitle"},{"op":"replace","value":"edges","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1edges/title"},{"op":"replace","value":[{"kind":"identifier","text":"edges"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1edges/fragments"},{"op":"replace","value":"isAbsoluteOffset","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1isAbsoluteOffset/title"},{"op":"replace","value":[{"kind":"identifier","text":"isAbsoluteOffset"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1isAbsoluteOffset/fragments"},{"op":"replace","value":"layoutAnchorWithEdges:fractionalOffset:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:fractionalOffset:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"layoutAnchorWithEdges:fractionalOffset:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutAnchor~1init(edges:fractionalOffset:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}