{
  "abstract": [
    {
      "text": "Subtracts the darker value from the lighter value.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/difference",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCompositeDifference"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSCompositeDifference",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSCompositeDifference"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCompositeDifference"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSCompositeDifference"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSCompositingOperation",
              "text": "NSCompositingOperation"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCompositeDifference"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeClear": {
      "abstract": [
        {
          "text": "Transparent. (",
          "type": "text"
        },
        {
          "code": "R = 0",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeClear"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeClear",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeClear",
      "type": "topic",
      "url": "/documentation/appkit/nscompositeclear"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeCopy": {
      "abstract": [
        {
          "text": "Source image. (",
          "type": "text"
        },
        {
          "code": "R = S",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeCopy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeCopy",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeCopy",
      "type": "topic",
      "url": "/documentation/appkit/nscompositecopy"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationAtop": {
      "abstract": [
        {
          "text": "Destination image wherever both images are opaque, source image wherever source image is opaque but destination image is transparent, and transparent elsewhere. (",
          "type": "text"
        },
        {
          "code": "R = S*(1 - Da) + D*Sa",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeDestinationAtop"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationAtop",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeDestinationAtop",
      "type": "topic",
      "url": "/documentation/appkit/nscompositedestinationatop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationIn": {
      "abstract": [
        {
          "text": "Destination image wherever both images are opaque, and transparent elsewhere. (",
          "type": "text"
        },
        {
          "code": "R = D*Sa",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeDestinationIn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationIn",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeDestinationIn",
      "type": "topic",
      "url": "/documentation/appkit/nscompositedestinationin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationOut": {
      "abstract": [
        {
          "text": "Destination image wherever destination image is opaque but source image is transparent, and transparent elsewhere. (",
          "type": "text"
        },
        {
          "code": "R = D*(1 - Sa)",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeDestinationOut"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeDestinationOut",
      "type": "topic",
      "url": "/documentation/appkit/nscompositedestinationout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationOver": {
      "abstract": [
        {
          "text": "Destination image wherever destination image is opaque, and source image elsewhere. (",
          "type": "text"
        },
        {
          "code": "R = S*(1 - Da) + D",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeDestinationOver"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationOver",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeDestinationOver",
      "type": "topic",
      "url": "/documentation/appkit/nscompositedestinationover"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeDifference": {
      "abstract": [
        {
          "text": "Subtracts the darker value from the lighter value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeDifference"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeDifference",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeDifference",
      "type": "topic",
      "url": "/documentation/appkit/nscompositedifference"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeMultiply": {
      "abstract": [
        {
          "text": "The source color is multiplied by the destination color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeMultiply"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeMultiply",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeMultiply",
      "type": "topic",
      "url": "/documentation/appkit/nscompositemultiply"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositePlusDarker": {
      "abstract": [
        {
          "text": "Sum of source and destination images, with color values approaching 0 as a limit. (",
          "type": "text"
        },
        {
          "code": "R = MAX(0, (1 - D) + (1 - S))",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositePlusDarker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositePlusDarker",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositePlusDarker",
      "type": "topic",
      "url": "/documentation/appkit/nscompositeplusdarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositePlusLighter": {
      "abstract": [
        {
          "text": "Sum of source and destination images, with color values approaching 1 as a limit. (",
          "type": "text"
        },
        {
          "code": "R = MIN(1, S + D)",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositePlusLighter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositePlusLighter",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositePlusLighter",
      "type": "topic",
      "url": "/documentation/appkit/nscompositepluslighter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeScreen": {
      "abstract": [
        {
          "text": "Multiplies the complement of the destination and source color values, and then complements the result.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeScreen"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeScreen",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeScreen",
      "type": "topic",
      "url": "/documentation/appkit/nscompositescreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceAtop": {
      "abstract": [
        {
          "text": "Source image wherever both images are opaque, destination image wherever destination image is opaque but source image is transparent, and transparent elsewhere. (",
          "type": "text"
        },
        {
          "code": "R = S*Da + D*(1 - Sa)",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeSourceAtop"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceAtop",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeSourceAtop",
      "type": "topic",
      "url": "/documentation/appkit/nscompositesourceatop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceIn": {
      "abstract": [
        {
          "text": "Source image wherever both images are opaque, and transparent elsewhere. (",
          "type": "text"
        },
        {
          "code": "R = S*Da",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeSourceIn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceIn",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeSourceIn",
      "type": "topic",
      "url": "/documentation/appkit/nscompositesourcein"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceOut": {
      "abstract": [
        {
          "text": "Source image wherever source image is opaque but destination image is transparent, and transparent elsewhere. (",
          "type": "text"
        },
        {
          "code": "R = S*(1 - Da)",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeSourceOut"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeSourceOut",
      "type": "topic",
      "url": "/documentation/appkit/nscompositesourceout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceOver": {
      "abstract": [
        {
          "text": "Source image wherever source image is opaque, and destination image elsewhere. (",
          "type": "text"
        },
        {
          "code": "R = S + D*(1 - Sa)",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeSourceOver"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceOver",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeSourceOver",
      "type": "topic",
      "url": "/documentation/appkit/nscompositesourceover"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositeXOR": {
      "abstract": [
        {
          "text": "Exclusive OR of source and destination images. (",
          "type": "text"
        },
        {
          "code": "R = S*(1 - Da) + D*(1 - Sa)",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCompositeXOR"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositeXOR",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompositeXOR",
      "type": "topic",
      "url": "/documentation/appkit/nscompositexor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation": {
      "abstract": [
        {
          "text": "Constants that describe compositing operators in terms of source and destination images, each having an opaque and transparent region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/difference": {
      "abstract": [
        {
          "text": "Subtracts the darker value from the lighter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "difference"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation/difference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperationDifference"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation.difference",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation/difference"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Compositing-Modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeClear",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeCopy",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceOver",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceIn",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceOut",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeSourceAtop",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationOver",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationIn",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationOut",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeDestinationAtop",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeXOR",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositePlusDarker",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositePlusLighter",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeMultiply",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositeScreen"
      ],
      "title": "Deprecated Compositing Modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1difference/title",
          "value": "NSCompositingOperationDifference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation~1difference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperationDifference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/title",
          "value": "NSCompositingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscompositedifference"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
