{"sections":[],"seeAlsoSections":[{"anchor":"Advanced-layouts","generated":true,"title":"Advanced layouts","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroupCustomItem"]}],"abstract":[{"text":"A closure that creates and returns each of the custom group’s items.","type":"text"}],"metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItemProvider"}],"symbolKind":"typealias","roleHeading":"Type Alias","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"externalID":"c:@T@NSCollectionLayoutGroupCustomItemProvider","navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItemProvider"}],"role":"symbol","title":"NSCollectionLayoutGroupCustomItemProvider","modules":[{"name":"AppKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroupCustomItemProvider"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscollectionlayoutgroupcustomitemprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscollectionlayoutgroupcustomitemprovider"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItemProvider"},{"kind":"text","text":" = (any "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEnvironment","text":"NSCollectionLayoutEnvironment","preciseIdentifier":"c:objc(pl)NSCollectionLayoutEnvironment"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroupCustomItem","text":"NSCollectionLayoutGroupCustomItem","preciseIdentifier":"c:objc(cs)NSCollectionLayoutGroupCustomItem"},{"kind":"text","text":"]"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use a custom item provider to supply the item arrangement when creating a group using the "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroup/custom(layoutSize:itemProvider:)","type":"reference","isActive":true},{"type":"text","text":" initializer."}]}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroupCustomItem":{"kind":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutGroupCustomItem","kind":"identifier"}],"role":"symbol","title":"NSCollectionLayoutGroupCustomItem","abstract":[{"text":"An item used in a group with a custom layout arrangement.","type":"text"}],"url":"/documentation/appkit/nscollectionlayoutgroupcustomitem","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSCollectionLayoutGroupCustomItem","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroupCustomItem"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroupCustomItemProvider":{"abstract":[{"type":"text","text":"A closure that creates and returns each of the custom group’s items."}],"url":"/documentation/appkit/nscollectionlayoutgroupcustomitemprovider","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutGroupCustomItemProvider","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutGroupCustomItemProvider","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroupCustomItemProvider","role":"symbol","type":"topic","title":"NSCollectionLayoutGroupCustomItemProvider"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroup/custom(layoutSize:itemProvider:)":{"role":"symbol","title":"custom(layoutSize:itemProvider:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroup/custom(layoutSize:itemProvider:)","url":"/documentation/appkit/nscollectionlayoutgroup/custom(layoutsize:itemprovider:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"customGroupWithLayoutSize:itemProvider:"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"layoutSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCollectionLayoutSize","text":"NSCollectionLayoutSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"itemProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCollectionLayoutGroupCustomItemProvider","preciseIdentifier":"c:@T@NSCollectionLayoutGroupCustomItemProvider","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"text":"Creates a group of the specified size, with an item provider that creates a custom arrangement for those items.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEnvironment":{"type":"topic","role":"symbol","title":"NSCollectionLayoutEnvironment","url":"/documentation/appkit/nscollectionlayoutenvironment","navigatorTitle":[{"text":"NSCollectionLayoutEnvironment","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutEnvironment","kind":"symbol","abstract":[{"text":"A protocol used to provide information about the layout’s container and environment traits, such as size classes and display scale factor.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutEnvironment","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Alias","path":"/metadata/roleHeading","op":"replace"},{"value":"NSCollectionLayoutGroupCustomItemProvider","path":"/metadata/title","op":"replace"},{"value":"typealias","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItemProvider"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"NSCollectionLayoutGroupCustomItemProvider","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutGroupCustomItem"],"generated":true,"anchor":"Advanced-layouts","title":"Advanced layouts"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BF*Q$objc(cs)NSArray(#*Qoobjc(pl)NSCollectionLayoutEnvironment)","text":"NSArray<NSCollectionLayoutGroupCustomItem *> *(^)(id<NSCollectionLayoutEnvironment>)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutGroupCustomItemProvider","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"NSCollectionLayoutGroupCustomItem","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutGroupCustomItem/title","op":"replace"},{"op":"replace","value":[{"text":"NSCollectionLayoutGroupCustomItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutGroupCustomItem/fragments"},{"op":"replace","value":[{"text":"NSCollectionLayoutGroupCustomItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutGroupCustomItem/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutGroupCustomItemProvider","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutGroupCustomItemProvider/title"},{"op":"replace","value":[{"text":"NSCollectionLayoutGroupCustomItemProvider","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutGroupCustomItemProvider/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItemProvider"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutGroupCustomItemProvider/navigatorTitle"},{"op":"replace","value":"customGroupWithLayoutSize:itemProvider:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutGroup~1custom(layoutSize:itemProvider:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"customGroupWithLayoutSize:itemProvider:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutGroup~1custom(layoutSize:itemProvider:)/fragments"},{"op":"replace","value":"NSCollectionLayoutEnvironment","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEnvironment/title"},{"op":"replace","value":[{"text":"NSCollectionLayoutEnvironment","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEnvironment/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutEnvironment"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutEnvironment/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}