{"abstract":[{"text":"An object that implements custom behaviors when changing from one layout to another in a collection view.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior"],"generated":true,"anchor":"Layouts","title":"Layouts"}],"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"paths":["/documentation/appkit/nscollectionviewtransitionlayout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscollectionviewtransitionlayout"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"NSCollectionViewTransitionLayout","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewTransitionLayout"}],"externalID":"c:objc(cs)NSCollectionViewTransitionLayout","modules":[{"name":"AppKit"}],"platforms":[{"introducedAt":"10.11","beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewTransitionLayout"}],"roleHeading":"Class","role":"symbol","symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewTransitionLayout","kind":"identifier"}],"platforms":["macOS"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Transition layout objects are commonly used to implement interactive transitions between layouts, where the transition itself is driven by a gesture recognizer.","type":"text"}]},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"In macOS 10.11, collection views do not provide built-in support for driving layout transitions.","type":"text"}]}],"type":"aside"}]}],"topicSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/init(currentLayout:nextLayout:)"],"anchor":"Initializing-the-Transition-Layout-Object","title":"Initializing the Transition Layout Object"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/transitionProgress","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/updateValue(_:forAnimatedKey:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/value(forAnimatedKey:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/AnimatedKey"],"anchor":"Updating-the-Transition-Information","title":"Updating the Transition Information"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/currentLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/nextLayout"],"anchor":"Accessing-the-Layout-Objects","title":"Accessing the Layout Objects"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout":{"abstract":[{"type":"text","text":"A layout object that lets you combine items in highly adaptive and flexible visual arrangements."}],"url":"/documentation/appkit/nscollectionviewcompositionallayout","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewCompositionalLayout","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NSCollectionViewCompositionalLayout","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout","role":"symbol","type":"topic","title":"NSCollectionViewCompositionalLayout"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","title":"CVarArg","kind":"symbol","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/init(currentLayout:nextLayout:)":{"navigatorTitle":[{"text":"initWithCurrentLayout:nextLayout:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Initializes and returns the transition layout object.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"currentLayout"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCollectionViewLayout","kind":"typeIdentifier","text":"NSCollectionViewLayout"},{"text":", ","kind":"text"},{"text":"nextLayout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCollectionViewLayout","preciseIdentifier":"c:objc(cs)NSCollectionViewLayout","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(currentLayout:nextLayout:)","url":"/documentation/appkit/nscollectionviewtransitionlayout/init(currentlayout:nextlayout:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/init(currentLayout:nextLayout:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/nextLayout":{"title":"nextLayout","url":"/documentation/appkit/nscollectionviewtransitionlayout/nextlayout","abstract":[{"type":"text","text":"The collection view’s new layout object."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/nextLayout","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nextLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCollectionViewLayout","preciseIdentifier":"c:objc(cs)NSCollectionViewLayout","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"nextLayout","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout":{"abstract":[{"text":"A layout that organizes items into a flexible and configurable arrangement.","type":"text"}],"url":"/documentation/appkit/nscollectionviewflowlayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewFlowLayout"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewFlowLayout"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout","role":"symbol","type":"topic","title":"NSCollectionViewFlowLayout"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/transitionProgress":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"text":"The completion percentage of the transition.","type":"text"}],"title":"transitionProgress","navigatorTitle":[{"kind":"identifier","text":"transitionProgress"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nscollectionviewtransitionlayout/transitionprogress","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/transitionProgress","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider":{"abstract":[{"type":"text","text":"A closure that creates and returns each of the layout’s sections."}],"url":"/documentation/appkit/nscollectionviewcompositionallayoutsectionprovider","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewCompositionalLayoutSectionProvider"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewCompositionalLayoutSectionProvider"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider","role":"symbol","type":"topic","title":"NSCollectionViewCompositionalLayoutSectionProvider"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/updateValue(_:forAnimatedKey:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAnimatedKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCollectionViewTransitionLayout","text":"NSCollectionViewTransitionLayout"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSCollectionViewTransitionLayoutAnimatedKey","text":"AnimatedKey"},{"kind":"text","text":")"}],"abstract":[{"text":"Sets the value of a key whose value you use during the animation.","type":"text"}],"title":"updateValue(_:forAnimatedKey:)","navigatorTitle":[{"kind":"identifier","text":"updateValue:forAnimatedKey:"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nscollectionviewtransitionlayout/updatevalue(_:foranimatedkey:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/updateValue(_:forAnimatedKey:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout":{"url":"/documentation/appkit/nscollectionviewgridlayout","kind":"symbol","navigatorTitle":[{"text":"NSCollectionViewGridLayout","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSCollectionViewGridLayout","abstract":[{"type":"text","text":"A layout that displays a single section of items in a row and column grid."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewGridLayout","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/value(forAnimatedKey:)":{"abstract":[{"type":"text","text":"Returns the most recently set value for the specified key."}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAnimatedKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCollectionViewTransitionLayout","text":"NSCollectionViewTransitionLayout"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSCollectionViewTransitionLayoutAnimatedKey","text":"AnimatedKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"/documentation/appkit/nscollectionviewtransitionlayout/value(foranimatedkey:)","navigatorTitle":[{"kind":"identifier","text":"valueForAnimatedKey:"}],"title":"value(forAnimatedKey:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/value(forAnimatedKey:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout":{"kind":"symbol","navigatorTitle":[{"text":"NSCollectionViewLayout","kind":"identifier"}],"role":"symbol","title":"NSCollectionViewLayout","abstract":[{"type":"text","text":"An abstract base class that you subclass and use to generate layout information for a collection view."}],"url":"/documentation/appkit/nscollectionviewlayout","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewLayout","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior":{"abstract":[{"type":"text","text":"The scrolling behavior of the layout’s sections in relation to the main layout axis."}],"url":"/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior","kind":"symbol","role":"symbol","title":"NSCollectionLayoutSectionOrthogonalScrollingBehavior","navigatorTitle":[{"text":"NSCollectionLayoutSectionOrthogonalScrollingBehavior","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutSectionOrthogonalScrollingBehavior","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewDelegateFlowLayout"}],"url":"/documentation/appkit/nscollectionviewdelegateflowlayout","title":"NSCollectionViewDelegateFlowLayout","abstract":[{"type":"text","text":"A set of methods that a delegate implements to provide layout information to a flow layout object in a collection view."}],"navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewDelegateFlowLayout"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/AnimatedKey":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"AnimatedKey","kind":"identifier"}],"abstract":[],"title":"NSCollectionViewTransitionLayout.AnimatedKey","navigatorTitle":[{"text":"AnimatedKey","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nscollectionviewtransitionlayout/animatedkey","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/AnimatedKey","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout":{"abstract":[{"text":"An object that implements custom behaviors when changing from one layout to another in a collection view.","type":"text"}],"url":"/documentation/appkit/nscollectionviewtransitionlayout","kind":"symbol","role":"symbol","title":"NSCollectionViewTransitionLayout","navigatorTitle":[{"text":"NSCollectionViewTransitionLayout","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewTransitionLayout","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes":{"abstract":[{"text":"An object that contains layout-related attributes for an element in a collection view.","type":"text"}],"url":"/documentation/appkit/nscollectionviewlayoutattributes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewLayoutAttributes"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewLayoutAttributes"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes","role":"symbol","type":"topic","title":"NSCollectionViewLayoutAttributes"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","role":"symbol","type":"topic","title":"CustomDebugStringConvertible"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/currentLayout":{"navigatorTitle":[{"text":"currentLayout","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCollectionViewLayout","preciseIdentifier":"c:objc(cs)NSCollectionViewLayout","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/currentLayout","type":"topic","title":"currentLayout","kind":"symbol","abstract":[{"text":"The collection view’s current layout object.","type":"text"}],"url":"/documentation/appkit/nscollectionviewtransitionlayout/currentlayout","role":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"kind":"symbol","url":"/documentation/Swift/CustomStringConvertible","role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSCollectionViewCompositionalLayoutConfiguration","kind":"identifier"}],"url":"/documentation/appkit/nscollectionviewcompositionallayoutconfiguration","title":"NSCollectionViewCompositionalLayoutConfiguration","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewCompositionalLayoutConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that defines scroll direction, section spacing, and headers or footers for the layout."}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"title":"NSCoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"role":"symbol","url":"/documentation/foundation/nscoding","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views":{"abstract":[{"text":"Bring compositional layouts to your app and simplify updating your user interface with diffable data sources.","type":"text"}],"url":"/documentation/UIKit/implementing-modern-collection-views","kind":"article","identifier":"doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views","role":"sampleCode","type":"topic","title":"Implementing modern collection views"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"10.11","name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Class","path":"/metadata/roleHeading"},{"op":"replace","value":"NSCollectionViewTransitionLayout","path":"/metadata/title"},{"op":"replace","value":"class","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewTransitionLayout"}],"path":"/metadata/fragments"},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"text":"NSCollectionViewTransitionLayout","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"op":"replace","path":"/topicSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/init(currentLayout:nextLayout:)"],"title":"Initializing the Transition Layout Object","anchor":"Initializing-the-Transition-Layout-Object"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/transitionProgress","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/updateValue(_:forAnimatedKey:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/value(forAnimatedKey:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/AnimatedKey"],"title":"Updating the Transition Information","anchor":"Updating-the-Transition-Information"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/currentLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout/nextLayout"],"title":"Accessing the Layout Objects","anchor":"Accessing-the-Layout-Objects"}]},{"op":"replace","path":"/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider","doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior"],"title":"Layouts","generated":true,"anchor":"Layouts"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewTransitionLayout","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout","text":"NSCollectionViewLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCollectionViewLayout"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/title","value":"NSCollectionViewCompositionalLayout"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/fragments","value":[{"text":"NSCollectionViewCompositionalLayout","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/navigatorTitle","value":[{"kind":"identifier","text":"NSCollectionViewCompositionalLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1init(currentLayout:nextLayout:)/title","op":"replace","value":"initWithCurrentLayout:nextLayout:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1init(currentLayout:nextLayout:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCurrentLayout:nextLayout:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1nextLayout/title","op":"replace","value":"nextLayout"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1nextLayout/fragments","op":"replace","value":[{"text":"nextLayout","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/title","op":"replace","value":"NSCollectionViewFlowLayout"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/fragments","op":"replace","value":[{"text":"NSCollectionViewFlowLayout","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewFlowLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1transitionProgress/title","op":"replace","value":"transitionProgress"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1transitionProgress/fragments","op":"replace","value":[{"text":"transitionProgress","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/title","op":"replace","value":"NSCollectionViewCompositionalLayoutSectionProvider"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewCompositionalLayoutSectionProvider"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/navigatorTitle","op":"replace","value":[{"text":"NSCollectionViewCompositionalLayoutSectionProvider","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1updateValue(_:forAnimatedKey:)/title","op":"replace","value":"updateValue:forAnimatedKey:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1updateValue(_:forAnimatedKey:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateValue:forAnimatedKey:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/title","op":"replace","value":"NSCollectionViewGridLayout"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewGridLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewGridLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1value(forAnimatedKey:)/title","op":"replace","value":"valueForAnimatedKey:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1value(forAnimatedKey:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"valueForAnimatedKey:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/title","op":"replace","value":"NSCollectionViewLayout"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/navigatorTitle","op":"replace","value":[{"text":"NSCollectionViewLayout","kind":"identifier"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/title","op":"replace","value":"NSCollectionLayoutSectionOrthogonalScrollingBehavior"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/fragments","op":"replace","value":[{"text":"NSCollectionLayoutSectionOrthogonalScrollingBehavior","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSectionOrthogonalScrollingBehavior"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/title","op":"replace","value":"NSCollectionViewDelegateFlowLayout"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/fragments","op":"replace","value":[{"text":"NSCollectionViewDelegateFlowLayout","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewDelegateFlowLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1AnimatedKey/title","op":"replace","value":"NSCollectionViewTransitionLayoutAnimatedKey"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1AnimatedKey/fragments","op":"replace","value":[{"text":"NSCollectionViewTransitionLayoutAnimatedKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1AnimatedKey/navigatorTitle","op":"replace","value":[{"text":"NSCollectionViewTransitionLayoutAnimatedKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/title","op":"replace","value":"NSCollectionViewTransitionLayout"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewTransitionLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewTransitionLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/title","op":"replace","value":"NSCollectionViewLayoutAttributes"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/fragments","op":"replace","value":[{"text":"NSCollectionViewLayoutAttributes","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewLayoutAttributes"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1currentLayout/title","op":"replace","value":"currentLayout"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout~1currentLayout/fragments","op":"replace","value":[{"kind":"identifier","text":"currentLayout"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/title","op":"replace","value":"NSCollectionViewCompositionalLayoutConfiguration"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/fragments","op":"replace","value":[{"text":"NSCollectionViewCompositionalLayoutConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/navigatorTitle","op":"replace","value":[{"text":"NSCollectionViewCompositionalLayoutConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}