{"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDataSource","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegate","doc://com.apple.appkit/documentation/AppKit/NSDiffableDataSourceSnapshot-swift.struct"],"anchor":"Data","title":"Data","generated":true}],"topicSections":[{"anchor":"Creating-a-Diffable-Data-Source","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/init(collectionView:itemProvider:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/ItemProvider"],"title":"Creating a Diffable Data Source"},{"anchor":"Creating-Supplementary-Views","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/supplementaryViewProvider-swift.property","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/SupplementaryViewProvider-swift.typealias"],"title":"Creating Supplementary Views"},{"anchor":"Identifying-Items","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/itemIdentifier(for:)","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/indexPath(for:)"],"title":"Identifying Items"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/snapshot()","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/apply(_:animatingDifferences:completion:)"],"title":"Updating Data","anchor":"Updating-Data"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/protocol-implementations"],"title":"Supporting Protocol Requirements","anchor":"Supporting-Protocol-Requirements"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/description()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewDiffableDataSource","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"SectionIdentifierType"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"ItemIdentifierType"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SectionIdentifierType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SH","text":"Hashable","preciseIdentifier":"s:SH"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ItemIdentifierType"},{"kind":"text","text":" : "},{"text":"Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","kind":"typeIdentifier","preciseIdentifier":"s:SH"}]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"A ","type":"text"},{"inlineContent":[{"type":"text","text":"diffable data source"}],"type":"emphasis"},{"text":" object is a specialized type of data source that works together with your collection view object. It provides the behavior you need to manage updates to your collection view’s data and UI in a simple, efficient way. It also conforms to the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDataSource","type":"reference"},{"text":" protocol and provides implementations for all of the protocol’s methods.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"To fill a collection view with data:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Connect a diffable data source to your collection view."}]}]},{"content":[{"inlineContent":[{"text":"Implement an item provider to configure your collection view’s items.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Generate the current state of the data."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Display the data in the UI."}],"type":"paragraph"}]}],"type":"orderedList"},{"inlineContent":[{"text":"To connect a diffable data source to a collection view, you create the diffable data source using its ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/init(collectionView:itemProvider:)","type":"reference"},{"text":" initializer, passing in the collection view you want to associate with that data source. You also pass in an item provider, where you configure each of your items to determine how to display your data in the UI.","type":"text"}],"type":"paragraph"},{"code":["dataSource = NSCollectionViewDiffableDataSource<Int, UUID>(collectionView: collectionView) {","    (collectionView: NSCollectionView, indexPath: IndexPath, itemIdentifier: UUID) -> NSCollectionViewItem? in","    // configure and return item","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"Then, you generate the current state of the data and display the data in the UI by constructing and applying a snapshot. For more information, see "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDiffableDataSourceSnapshot-swift.struct","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDataSource","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"title":"Conforms To","type":"conformsTo"}],"abstract":[{"text":"The object you use to manage data and provide items for a collection view.","type":"text"}],"metadata":{"modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","introducedAt":"10.15.1","unavailable":false,"beta":false,"deprecated":false}],"roleHeading":"Class","externalID":"s:6AppKit34NSCollectionViewDiffableDataSourceC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewDiffableDataSource","kind":"identifier"}],"title":"NSCollectionViewDiffableDataSource","symbolKind":"class","navigatorTitle":[{"text":"NSCollectionViewDiffableDataSource","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscollectionviewdiffabledatasource-axww"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"type":"text","text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects."}],"url":"/documentation/objectivec/nsobject","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","role":"symbol","type":"topic","title":"NSObject"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/indexPath(for:)":{"url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/indexpath(for:)","title":"indexPath(for:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPath"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ItemIdentifierType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/indexPath(for:)","abstract":[{"type":"text","text":"Returns an index path for the item with the specified identifier in the collection view."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/SupplementaryViewProvider-swift.typealias":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupplementaryViewProvider"}],"url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/supplementaryviewprovider-swift.typealias","role":"symbol","navigatorTitle":[{"text":"SupplementaryViewProvider","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/SupplementaryViewProvider-swift.typealias","title":"NSCollectionViewDiffableDataSource.SupplementaryViewProvider","abstract":[{"text":"A closure that configures and returns a collection view’s supplementary view, such as a header or footer, from a diffable data source.","type":"text"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"kind":"symbol","url":"/documentation/Swift/CustomStringConvertible","role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDataSource":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDataSource","role":"symbol","type":"topic","url":"/documentation/appkit/nscollectionviewdatasource","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewDataSource"}],"abstract":[{"type":"text","text":"A set of methods that a data source object implements to provide the information and view objects that a collection view requires to present content."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewDataSource"}],"title":"NSCollectionViewDataSource","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","role":"symbol","type":"topic","title":"CustomDebugStringConvertible"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/init(collectionView:itemProvider:)":{"url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/init(collectionview:itemprovider:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"collectionView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCollectionView","preciseIdentifier":"c:objc(cs)NSCollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"itemProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCollectionViewDiffableDataSource","preciseIdentifier":"s:6AppKit34NSCollectionViewDiffableDataSourceC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SectionIdentifierType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ItemIdentifierType","kind":"typeIdentifier"},{"text":">.","kind":"text"},{"preciseIdentifier":"s:6AppKit34NSCollectionViewDiffableDataSourceC12ItemProvidera","kind":"typeIdentifier","text":"ItemProvider"},{"kind":"text","text":")"}],"title":"init(collectionView:itemProvider:)","type":"topic","abstract":[{"type":"text","text":"Creates a diffable data source with the specified item provider, and connects it to the specified collection view."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/init(collectionView:itemProvider:)"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/snapshot()":{"role":"symbol","kind":"symbol","type":"topic","title":"snapshot()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"snapshot","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"NSDiffableDataSourceSnapshot","preciseIdentifier":"s:6AppKit28NSDiffableDataSourceSnapshotV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SectionIdentifierType"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ItemIdentifierType"},{"kind":"text","text":">"}],"url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/snapshot()","abstract":[{"type":"text","text":"Returns a representation of the current state of the data in the collection view."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/snapshot()"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/ItemProvider":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/ItemProvider","url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/itemprovider","role":"symbol","navigatorTitle":[{"text":"ItemProvider","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ItemProvider","kind":"identifier"}],"title":"NSCollectionViewDiffableDataSource.ItemProvider","abstract":[{"type":"text","text":"A closure that configures and returns an item for a collection view from its diffable data source."}]},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/itemIdentifier(for:)":{"title":"itemIdentifier(for:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemIdentifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ItemIdentifierType"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns an identifier for the item at the specified index path in the collection view."}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/itemIdentifier(for:)","url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/itemidentifier(for:)"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/apply(_:animatingDifferences:completion:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Updates the UI to reflect the state of the data in the specified snapshot, optionally animating the UI changes and executing a completion handler."}],"role":"symbol","title":"apply(_:animatingDifferences:completion:)","url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/apply(_:animatingdifferences:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"text":"NSDiffableDataSourceSnapshot","kind":"typeIdentifier","preciseIdentifier":"s:6AppKit28NSDiffableDataSourceSnapshotV"},{"text":"<","kind":"text"},{"text":"SectionIdentifierType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ItemIdentifierType","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"animatingDifferences","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/apply(_:animatingDifferences:completion:)"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegate":{"kind":"symbol","url":"/documentation/appkit/nscollectionviewdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewDelegate"}],"abstract":[{"type":"text","text":"A set of methods that you use to manage the behavior of a collection view."}],"title":"NSCollectionViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewDelegate"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegate","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/protocol-implementations":{"kind":"article","url":"/documentation/appkit/protocol-implementations","role":"collectionGroup","type":"topic","title":"Protocol Implementations","identifier":"doc://com.apple.appkit/documentation/AppKit/protocol-implementations","abstract":[{"type":"text","text":"Access the diffable data source’s implementations of protocol methods."}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDiffableDataSourceSnapshot-swift.struct":{"kind":"symbol","url":"/documentation/appkit/nsdiffabledatasourcesnapshot-swift.struct","title":"NSDiffableDataSourceSnapshot","navigatorTitle":[{"kind":"identifier","text":"NSDiffableDataSourceSnapshot"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDiffableDataSourceSnapshot","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A representation of the state of the data in a view at a specific point in time."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDiffableDataSourceSnapshot-swift.struct","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/supplementaryViewProvider-swift.property":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supplementaryViewProvider"},{"kind":"text","text":": "},{"text":"NSCollectionViewDiffableDataSource","kind":"typeIdentifier","preciseIdentifier":"s:6AppKit34NSCollectionViewDiffableDataSourceC"},{"text":"<","kind":"text"},{"text":"SectionIdentifierType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"ItemIdentifierType"},{"kind":"text","text":">."},{"kind":"typeIdentifier","text":"SupplementaryViewProvider","preciseIdentifier":"s:6AppKit34NSCollectionViewDiffableDataSourceC013SupplementaryD8Providera"},{"kind":"text","text":"?"}],"kind":"symbol","url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/supplementaryviewprovider-swift.property","role":"symbol","type":"topic","title":"supplementaryViewProvider","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/supplementaryViewProvider-swift.property","abstract":[{"type":"text","text":"The closure that configures and returns the collection view’s supplementary views, such as headers and footers, from the diffable data source."}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewDiffableDataSource"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewDiffableDataSource"}],"url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww","title":"NSCollectionViewDiffableDataSource","abstract":[{"text":"The object you use to manage data and provide items for a collection view.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","title":"CVarArg","kind":"symbol","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/description()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","url":"/documentation/appkit/nscollectionviewdiffabledatasource-axww/description()","role":"symbol","type":"topic","title":"description()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSource-axww/description()","abstract":[{"text":"Returns a string with a description of the diffable data source.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDataSource/title","value":"NSCollectionViewDataSource"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDataSource/fragments","value":[{"kind":"identifier","text":"NSCollectionViewDataSource"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDataSource/navigatorTitle","value":[{"text":"NSCollectionViewDataSource","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegate/title","value":"NSCollectionViewDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegate/fragments","value":[{"text":"NSCollectionViewDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegate/navigatorTitle","value":[{"text":"NSCollectionViewDelegate","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}