{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscontroltexteditingdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscontroltexteditingdelegate"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Management","generated":true,"anchor":"Management","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate"]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"protocol","roleHeading":"Protocol","title":"NSControlTextEditingDelegate","navigatorTitle":[{"text":"NSControlTextEditingDelegate","kind":"identifier"}],"externalID":"c:objc(pl)NSControlTextEditingDelegate","modules":[{"name":"AppKit"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSControlTextEditingDelegate","kind":"identifier"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A set of optional methods implemented by delegates of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","type":"reference"},{"type":"text","text":" subclasses to respond to editing actions."}],"topicSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:isValidObject:)","doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:didFailToValidatePartialString:errorDescription:)"],"anchor":"Validating-a-Controls-Value","title":"Validating a Control’s Value"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:didFailToFormatString:errorDescription:)"],"anchor":"Responding-to-Text-Formatting","title":"Responding to Text Formatting"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textShouldBeginEditing:)","doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textShouldEndEditing:)"],"anchor":"Responding-to-Text-Editing","title":"Responding to Text Editing"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textView:completions:forPartialWordRange:indexOfSelectedItem:)"],"anchor":"Working-with-Text-Completion","title":"Working with Text Completion"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textView:doCommandBy:)"],"anchor":"Working-with-Key-Bindings","title":"Working with Key Bindings"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidBeginEditing(_:)","doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidChange(_:)","doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidEndEditing(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate","doc://com.apple.appkit/documentation/AppKit/NSMatrixDelegate","doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDelegate","doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate","doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate","doc://com.apple.appkit/documentation/AppKit/NSTokenFieldDelegate"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSControlTextEditingDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate":{"kind":"symbol","url":"/documentation/appkit/nscontroltexteditingdelegate","type":"topic","role":"symbol","navigatorTitle":[{"text":"NSControlTextEditingDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of optional methods implemented by delegates of "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","isActive":true,"type":"reference"},{"text":" subclasses to respond to editing actions.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSControlTextEditingDelegate","kind":"identifier"}],"title":"NSControlTextEditingDelegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate"},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:didFailToFormatString:errorDescription:)":{"abstract":[{"text":"Invoked when the formatter for the cell belonging to the specified control cannot convert a string to an underlying object.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"control"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSControl","text":"NSControl"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToFormatString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"control(_:didFailToFormatString:errorDescription:)","role":"symbol","url":"/documentation/appkit/nscontroltexteditingdelegate/control(_:didfailtoformatstring:errordescription:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:didFailToFormatString:errorDescription:)","navigatorTitle":[{"text":"control:didFailToFormatString:errorDescription:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textShouldBeginEditing:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textShouldBeginEditing:)","role":"symbol","url":"/documentation/appkit/nscontroltexteditingdelegate/control(_:textshouldbeginediting:)","type":"topic","navigatorTitle":[{"text":"control:textShouldBeginEditing:","kind":"identifier"}],"abstract":[{"text":"Invoked when the user tries to enter a character in a cell of a control that allows editing of text (such as a text field or form field).","type":"text"}],"title":"control(_:textShouldBeginEditing:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"control","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSControl","text":"NSControl","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textShouldBeginEditing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSText","text":"NSText","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSControl":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","navigatorTitle":[{"kind":"identifier","text":"NSControl"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSControl"}],"title":"NSControl","role":"symbol","abstract":[{"text":"A specialized view, such as a button or text field, that notifies your app of relevant events using the target-action design pattern.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscontrol"},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidEndEditing(_:)":{"url":"/documentation/appkit/nscontroltexteditingdelegate/controltextdidendediting(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidEndEditing(_:)","abstract":[{"text":"Tells the delegate that the control finished editing its text content and committed the changes.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlTextDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"controlTextDidEndEditing(_:)","navigatorTitle":[{"text":"controlTextDidEndEditing:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:didFailToValidatePartialString:errorDescription:)":{"title":"control(_:didFailToValidatePartialString:errorDescription:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"control","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSControl","preciseIdentifier":"c:objc(cs)NSControl"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToValidatePartialString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"url":"/documentation/appkit/nscontroltexteditingdelegate/control(_:didfailtovalidatepartialstring:errordescription:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:didFailToValidatePartialString:errorDescription:)","navigatorTitle":[{"kind":"identifier","text":"control:didFailToValidatePartialString:errorDescription:"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Invoked when the formatter for the cell belonging to ","type":"text"},{"type":"codeVoice","code":"control"},{"text":" (or selected cell) rejects a partial string a user is typing into the cell.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate","role":"symbol","kind":"symbol","type":"topic","url":"/documentation/appkit/nssearchfielddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSearchFieldDelegate"}],"abstract":[{"type":"text","text":"A protocol that a search field delegate can use to determine when a search started or ended."}],"title":"NSSearchFieldDelegate","navigatorTitle":[{"kind":"identifier","text":"NSSearchFieldDelegate"}]},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textView:completions:forPartialWordRange:indexOfSelectedItem:)":{"abstract":[{"text":"Invoked to allow you to control the list of proposed text completions generated by text fields and other controls.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"control:textView:completions:forPartialWordRange:indexOfSelectedItem:","kind":"identifier"}],"url":"/documentation/appkit/nscontroltexteditingdelegate/control(_:textview:completions:forpartialwordrange:indexofselecteditem:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"control","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSControl"},{"text":", ","kind":"text"},{"text":"textView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextView"},{"text":", ","kind":"text"},{"text":"completions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"forPartialWordRange","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexOfSelectedItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textView:completions:forPartialWordRange:indexOfSelectedItem:)","title":"control(_:textView:completions:forPartialWordRange:indexOfSelectedItem:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDelegate":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSOutlineViewDelegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDelegate","navigatorTitle":[{"text":"NSOutlineViewDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of optional methods implemented by delegates of "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOutlineView"},{"type":"text","text":" objects."}],"type":"topic","title":"NSOutlineViewDelegate","url":"/documentation/appkit/nsoutlineviewdelegate"},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:isValidObject:)":{"title":"control(_:isValidObject:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"control","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSControl"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isValidObject"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nscontroltexteditingdelegate/control(_:isvalidobject:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:isValidObject:)","navigatorTitle":[{"kind":"identifier","text":"control:isValidObject:"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Invoked when the insertion point leaves a cell belonging to the specified control, but before the value of the cell’s object is displayed.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSMatrixDelegate":{"type":"topic","url":"/documentation/appkit/nsmatrixdelegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMatrixDelegate","kind":"symbol","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"NSMatrixDelegate"},{"text":" protocol defines the optional methods implemented by delegates of ","type":"text"},{"type":"codeVoice","code":"NSMatrix"},{"text":" objects.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSMatrixDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"NSMatrixDelegate","kind":"identifier"}],"title":"NSMatrixDelegate"},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textShouldEndEditing:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"control","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSControl"},{"text":", ","kind":"text"},{"text":"textShouldEndEditing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSText","text":"NSText","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textShouldEndEditing:)","kind":"symbol","type":"topic","url":"/documentation/appkit/nscontroltexteditingdelegate/control(_:textshouldendediting:)","abstract":[{"text":"Invoked when the insertion point tries to leave a cell of the control that has been edited.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"control:textShouldEndEditing:","kind":"identifier"}],"title":"control(_:textShouldEndEditing:)"},"doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate","navigatorTitle":[{"kind":"identifier","text":"NSTextFieldDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSTextFieldDelegate"}],"kind":"symbol","abstract":[{"text":"A protocol that a text field delegate can use to control its field editor action menu.","type":"text"}],"type":"topic","title":"NSTextFieldDelegate","role":"symbol","url":"/documentation/appkit/nstextfielddelegate"},"doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate":{"role":"symbol","type":"topic","title":"NSComboBoxDelegate","url":"/documentation/appkit/nscomboboxdelegate","navigatorTitle":[{"text":"NSComboBoxDelegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSComboBoxDelegate","kind":"identifier"}],"abstract":[{"text":"A set of optional methods implemented by delegates of combo box objects.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidChange(_:)":{"title":"controlTextDidChange(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlTextDidChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"controlTextDidChange:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidChange(_:)","abstract":[{"text":"Tells the delegate that the control made changes to its text content.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nscontroltexteditingdelegate/controltextdidchange(_:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSOutlineView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NSOutlineView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A view that uses a row-and-column format to display hierarchical data like directories and files that can be expanded and collapsed."}],"url":"/documentation/appkit/nsoutlineview","navigatorTitle":[{"kind":"identifier","text":"NSOutlineView"}],"title":"NSOutlineView","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOutlineView"},"doc://com.apple.appkit/documentation/AppKit/NSTokenField":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSTokenField","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenField","url":"/documentation/appkit/nstokenfield","title":"NSTokenField","role":"symbol","abstract":[{"text":"A text field that converts text into visually distinct tokens.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTokenField","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textView:doCommandBy:)":{"title":"control(_:textView:doCommandBy:)","navigatorTitle":[{"kind":"identifier","text":"control:textView:doCommandBySelector:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textView:doCommandBy:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"control"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSControl","kind":"typeIdentifier","text":"NSControl"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSTextView","kind":"typeIdentifier","text":"NSTextView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"doCommandBy"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier","text":"Selector"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/appkit/nscontroltexteditingdelegate/control(_:textview:docommandby:)","abstract":[{"text":"Invoked when users press keys with predefined bindings in a cell of the specified control.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidBeginEditing(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidBeginEditing(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlTextDidBeginEditing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Tells the delegate that the control started editing its text content.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"controlTextDidBeginEditing:"}],"title":"controlTextDidBeginEditing(_:)","role":"symbol","url":"/documentation/appkit/nscontroltexteditingdelegate/controltextdidbeginediting(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSTokenFieldDelegate":{"title":"NSTokenFieldDelegate","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenFieldDelegate","url":"/documentation/appkit/nstokenfielddelegate","navigatorTitle":[{"kind":"identifier","text":"NSTokenFieldDelegate"}],"abstract":[{"text":"A set of optional methods implemented by delegates of ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenField","type":"reference","isActive":true},{"text":" objects.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSTokenFieldDelegate"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate":{"kind":"symbol","url":"/documentation/appkit/nstableviewdelegate","title":"NSTableViewDelegate","navigatorTitle":[{"text":"NSTableViewDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NSTableViewDelegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"A set of optional methods you implement in a table view delegate to customize the behavior of the table view.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Protocol","path":"/metadata/roleHeading","op":"replace"},{"value":"NSControlTextEditingDelegate","path":"/metadata/title","op":"replace"},{"value":"protocol","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NSControlTextEditingDelegate"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"NSControlTextEditingDelegate","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"anchor":"Validating-a-Controls-Value","title":"Validating a Control’s Value","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:isValidObject:)","doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:didFailToValidatePartialString:errorDescription:)"]},{"anchor":"Responding-to-Text-Formatting","title":"Responding to Text Formatting","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:didFailToFormatString:errorDescription:)"]},{"anchor":"Responding-to-Text-Editing","title":"Responding to Text Editing","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textShouldBeginEditing:)","doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textShouldEndEditing:)"]},{"anchor":"Working-with-Text-Completion","title":"Working with Text Completion","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textView:completions:forPartialWordRange:indexOfSelectedItem:)"]},{"anchor":"Working-with-Key-Bindings","title":"Working with Key Bindings","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/control(_:textView:doCommandBy:)"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidBeginEditing(_:)","doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidChange(_:)","doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate/controlTextDidEndEditing(_:)"]}],"path":"/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"title":"Inherits From"},{"type":"inheritedBy","kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMatrixDelegate","doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDelegate","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate","doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate"],"title":"Inherited By"}],"path":"/relationshipsSections","op":"replace"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate"],"title":"Management","anchor":"Management"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSControlTextEditingDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"NSControlTextEditingDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSControlTextEditingDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/fragments"},{"op":"replace","value":[{"text":"NSControlTextEditingDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/navigatorTitle"},{"op":"replace","value":"control:didFailToFormatString:errorDescription:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:didFailToFormatString:errorDescription:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"control:didFailToFormatString:errorDescription:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:didFailToFormatString:errorDescription:)/fragments"},{"op":"replace","value":"control:textShouldBeginEditing:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:textShouldBeginEditing:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"control:textShouldBeginEditing:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:textShouldBeginEditing:)/fragments"},{"op":"replace","value":"NSControl","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/title"},{"op":"replace","value":[{"text":"NSControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/navigatorTitle","value":[{"kind":"identifier","text":"NSControl"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1controlTextDidEndEditing(_:)/title","value":"controlTextDidEndEditing:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1controlTextDidEndEditing(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"controlTextDidEndEditing:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:didFailToValidatePartialString:errorDescription:)/title","value":"control:didFailToValidatePartialString:errorDescription:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:didFailToValidatePartialString:errorDescription:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"control:didFailToValidatePartialString:errorDescription:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/title","value":"NSSearchFieldDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/fragments","value":[{"kind":"identifier","text":"NSSearchFieldDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/navigatorTitle","value":[{"kind":"identifier","text":"NSSearchFieldDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:textView:completions:forPartialWordRange:indexOfSelectedItem:)/title","value":"control:textView:completions:forPartialWordRange:indexOfSelectedItem:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:textView:completions:forPartialWordRange:indexOfSelectedItem:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"control:textView:completions:forPartialWordRange:indexOfSelectedItem:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDelegate/title","value":"NSOutlineViewDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDelegate/fragments","value":[{"text":"NSOutlineViewDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDelegate/navigatorTitle","value":[{"text":"NSOutlineViewDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:isValidObject:)/title","value":"control:isValidObject:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:isValidObject:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"control:isValidObject:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrixDelegate/title","value":"NSMatrixDelegate"},{"op":"replace","value":[{"text":"NSMatrixDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrixDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSMatrixDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrixDelegate/navigatorTitle"},{"op":"replace","value":"control:textShouldEndEditing:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:textShouldEndEditing:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"control:textShouldEndEditing:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:textShouldEndEditing:)/fragments"},{"op":"replace","value":"NSTextFieldDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSTextFieldDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/fragments"},{"op":"replace","value":[{"text":"NSTextFieldDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/navigatorTitle"},{"op":"replace","value":"NSComboBoxDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate/title"},{"op":"replace","value":[{"text":"NSComboBoxDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate/fragments"},{"op":"replace","value":[{"text":"NSComboBoxDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate/navigatorTitle"},{"op":"replace","value":"controlTextDidChange:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1controlTextDidChange(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"controlTextDidChange:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1controlTextDidChange(_:)/fragments"},{"op":"replace","value":"NSOutlineView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/title"},{"op":"replace","value":[{"text":"NSOutlineView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSOutlineView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/navigatorTitle"},{"op":"replace","value":"NSTokenField","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSTokenField"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/fragments"},{"op":"replace","value":[{"text":"NSTokenField","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/navigatorTitle"},{"op":"replace","value":"control:textView:doCommandBySelector:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:textView:doCommandBy:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"control:textView:doCommandBySelector:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1control(_:textView:doCommandBy:)/fragments"},{"op":"replace","value":"controlTextDidBeginEditing:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1controlTextDidBeginEditing(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"controlTextDidBeginEditing:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate~1controlTextDidBeginEditing(_:)/fragments"},{"op":"replace","value":"NSTokenFieldDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSTokenFieldDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldDelegate/fragments"},{"op":"replace","value":[{"text":"NSTokenFieldDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldDelegate/navigatorTitle"},{"op":"replace","value":"NSTableViewDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSTableViewDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/fragments"},{"op":"replace","value":[{"text":"NSTableViewDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/navigatorTitle"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}