{
  "abstract": [
    {
      "text": "A layout object that lets you combine items in highly adaptive and flexible visual arrangements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSCollectionViewCompositionalLayout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCollectionViewCompositionalLayout"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCollectionViewCompositionalLayout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSCollectionViewCompositionalLayout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayout"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A compositional layout is a type of collection view layout. It’s designed to be composable, flexible, and fast, letting you build any kind of visual arrangement for your content by combining—or compositing—each smaller component into a full layout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A compositional layout is composed of one or more sections that break up the layout into distinct visual groupings. Each section is composed of groups of individual items, the smallest unit of data you want to present. A group might lay out its items in a horizontal row, a vertical column, or a custom arrangement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You combine the components by building up from items into a group, from groups into a section, and finally into a full layout, like in this example of a basic list layout:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func createBasicListLayout() -> NSCollectionViewLayout {",
            "    let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),",
            "                                         heightDimension: .fractionalHeight(1.0))",
            "    let item = NSCollectionLayoutItem(layoutSize: itemSize)",
            "  ",
            "    let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),",
            "                                          heightDimension: .absolute(44))",
            "    let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize,",
            "                                                     subitems: [item])",
            "  ",
            "    let section = NSCollectionLayoutSection(group: group)",
            "",
            "    let layout = NSCollectionViewCompositionalLayout(section: section)",
            "    return layout",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior": {
      "abstract": [
        {
          "text": "The scrolling behavior of the layout’s sections in relation to the main layout axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout": {
      "abstract": [
        {
          "text": "A layout object that lets you combine items in highly adaptive and flexible visual arrangements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewCompositionalLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/configuration": {
      "abstract": [
        {
          "text": "The layout’s configuration, such as its scroll direction and section spacing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionViewCompositionalLayoutConfiguration",
          "text": "NSCollectionViewCompositionalLayoutConfiguration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayout/configuration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(section:)": {
      "abstract": [
        {
          "text": "Creates a compositional layout object with a single section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "section"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionLayoutSection",
          "text": "NSCollectionLayoutSection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(section:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSection:"
        }
      ],
      "role": "symbol",
      "title": "init(section:)",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayout/init(section:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(section:configuration:)": {
      "abstract": [
        {
          "text": "Creates a compositional layout object with a single section and an additional configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "section"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionLayoutSection",
          "text": "NSCollectionLayoutSection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionViewCompositionalLayoutConfiguration",
          "text": "NSCollectionViewCompositionalLayoutConfiguration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(section:configuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSection:configuration:"
        }
      ],
      "role": "symbol",
      "title": "init(section:configuration:)",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayout/init(section:configuration:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(sectionProvider:)": {
      "abstract": [
        {
          "text": "Creates a compositional layout object with a section provider to supply the layout’s sections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sectionProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSCollectionViewCompositionalLayoutSectionProvider",
          "text": "NSCollectionViewCompositionalLayoutSectionProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(sectionProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSectionProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(sectionProvider:)",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayout/init(sectionprovider:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(sectionProvider:configuration:)": {
      "abstract": [
        {
          "text": "Creates a compositional layout object with a section provider and an additional configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sectionProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSCollectionViewCompositionalLayoutSectionProvider",
          "text": "NSCollectionViewCompositionalLayoutSectionProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionViewCompositionalLayoutConfiguration",
          "text": "NSCollectionViewCompositionalLayoutConfiguration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(sectionProvider:configuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSectionProvider:configuration:"
        }
      ],
      "role": "symbol",
      "title": "init(sectionProvider:configuration:)",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayout/init(sectionprovider:configuration:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration": {
      "abstract": [
        {
          "text": "An object that defines scroll direction, section spacing, and headers or footers for the layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayoutConfiguration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayoutConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewCompositionalLayoutConfiguration",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayoutconfiguration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider": {
      "abstract": [
        {
          "text": "A closure that creates and returns each of the layout’s sections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayoutSectionProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayoutSectionProvider"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewCompositionalLayoutSectionProvider",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayoutsectionprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout": {
      "abstract": [
        {
          "text": "A set of methods that a delegate implements to provide layout information to a flow layout object in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewDelegateFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewDelegateFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewDelegateFlowLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewdelegateflowlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout": {
      "abstract": [
        {
          "text": "A layout that organizes items into a flexible and configurable arrangement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewFlowLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewflowlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout": {
      "abstract": [
        {
          "text": "A layout that displays a single section of items in a row and column grid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewGridLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewGridLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewGridLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewgridlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout": {
      "abstract": [
        {
          "text": "An abstract base class that you subclass and use to generate layout information for a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes": {
      "abstract": [
        {
          "text": "An object that contains layout-related attributes for an element in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewLayoutAttributes",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewlayoutattributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout": {
      "abstract": [
        {
          "text": "An object that implements custom behaviors when changing from one layout to another in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewTransitionLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewTransitionLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewTransitionLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewtransitionlayout"
    },
    "doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views": {
      "abstract": [
        {
          "text": "Bring compositional layouts to your app and simplify updating your user interface with diffable data sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing modern collection views",
      "type": "topic",
      "url": "/documentation/UIKit/implementing-modern-collection-views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Layouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior"
      ],
      "title": "Layouts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Layout",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(section:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(section:configuration:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(sectionProvider:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(sectionProvider:configuration:)"
      ],
      "title": "Creating a Layout"
    },
    {
      "anchor": "Configuring-the-Layout",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/configuration"
      ],
      "title": "Configuring the Layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCollectionViewCompositionalLayout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Layout",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(section:)",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(section:configuration:)",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(sectionProvider:)",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/init(sectionProvider:configuration:)"
              ],
              "title": "Creating a Layout"
            },
            {
              "anchor": "Configuring-the-Layout",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout/configuration"
              ],
              "title": "Configuring the Layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Layouts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior"
              ],
              "title": "Layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCollectionViewCompositionalLayout"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSCollectionViewLayout",
                    "text": "NSCollectionViewLayout"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/title",
          "value": "NSCollectionViewTransitionLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewTransitionLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewTransitionLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1init(sectionProvider:)/title",
          "value": "initWithSectionProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1init(sectionProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSectionProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/title",
          "value": "NSCollectionViewCompositionalLayoutConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayoutConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayoutConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/title",
          "value": "NSCollectionViewLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/title",
          "value": "NSCollectionViewCompositionalLayoutSectionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayoutSectionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayoutSectionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/title",
          "value": "NSCollectionViewFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1init(sectionProvider:configuration:)/title",
          "value": "initWithSectionProvider:configuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1init(sectionProvider:configuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSectionProvider:configuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/title",
          "value": "NSCollectionViewLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/title",
          "value": "NSCollectionViewGridLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewGridLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewGridLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/title",
          "value": "NSCollectionViewCompositionalLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/title",
          "value": "NSCollectionViewDelegateFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDelegateFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDelegateFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1init(section:)/title",
          "value": "initWithSection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1init(section:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1init(section:configuration:)/title",
          "value": "initWithSection:configuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1init(section:configuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSection:configuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1configuration/title",
          "value": "configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout~1configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscollectionviewcompositionallayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscollectionviewcompositionallayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
