{
  "abstract": [
    {
      "text": "A set of methods that provides basic behavior for a color picker.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSColorPickingDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSColorPickingDefault"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSColorPickingDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSColorPickingDefault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSColorPickingDefault"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol, together with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingCustom",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol (which provides implementation-specific behavior), provides an interface for adding color pickers to an app’s color panel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPanel": {
      "abstract": [
        {
          "text": "A standard user interface for selecting color in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorPanel"
        }
      ],
      "role": "symbol",
      "title": "NSColorPanel",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPicker": {
      "abstract": [
        {
          "text": "An abstract superclass that implements the default color picking protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorPicker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorPicker"
        }
      ],
      "role": "symbol",
      "title": "NSColorPicker",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpicker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingCustom": {
      "abstract": [
        {
          "text": "A set of methods that provides a way to add color pickers—custom user interfaces for color selection—to an app’s color panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorPickingCustom"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingCustom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorPickingCustom"
        }
      ],
      "role": "symbol",
      "title": "NSColorPickingCustom",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingcustom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault": {
      "abstract": [
        {
          "text": "A set of methods that provides basic behavior for a color picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorPickingDefault"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorPickingDefault"
        }
      ],
      "role": "symbol",
      "title": "NSColorPickingDefault",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/alphaControlAddedOrRemoved(_:)": {
      "abstract": [
        {
          "text": "Sent when the color panel’s opacity controls have been hidden or displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaControlAddedOrRemoved"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/alphaControlAddedOrRemoved(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alphaControlAddedOrRemoved:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "alphaControlAddedOrRemoved(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/alphacontroladdedorremoved(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/attachColorList(_:)": {
      "abstract": [
        {
          "text": "Tells the receiver to attach the given color list, if it isn’t already displaying the list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachColorList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorList",
          "text": "NSColorList"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/attachColorList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attachColorList:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "attachColorList(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/attachcolorlist(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/buttonToolTip()": {
      "abstract": [
        {
          "text": "Provides the toolbar button help tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonToolTip"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/buttonToolTip()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonToolTip"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "buttonToolTip()",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/buttontooltip()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/detachColorList(_:)": {
      "abstract": [
        {
          "text": "Tells the receiver to detach the given color list, unless the receiver isn’t displaying the list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detachColorList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorList",
          "text": "NSColorList"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/detachColorList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detachColorList:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "detachColorList(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/detachcolorlist(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/init(pickerMask:colorPanel:)": {
      "abstract": [
        {
          "text": "Initializes the receiver with a given color panel and its mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "pickerMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "colorPanel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorPanel",
          "text": "NSColorPanel"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/init(pickerMask:colorPanel:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPickerMask:colorPanel:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "init(pickerMask:colorPanel:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/init(pickermask:colorpanel:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/insertNewButtonImage(_:in:)": {
      "abstract": [
        {
          "text": "Sets the image of a given button cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertNewButtonImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButtonCell",
          "text": "NSButtonCell"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/insertNewButtonImage(_:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertNewButtonImage:in:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "insertNewButtonImage(_:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/insertnewbuttonimage(_:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/minContentSize()": {
      "abstract": [
        {
          "text": "Indicates the receiver’s minimum content size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minContentSize"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/minContentSize()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minContentSize"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "minContentSize()",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/mincontentsize()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/provideNewButtonImage()": {
      "abstract": [
        {
          "text": "Provides the image of the button used to select the receiver in the color panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provideNewButtonImage"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/provideNewButtonImage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provideNewButtonImage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "provideNewButtonImage()",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/providenewbuttonimage()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/setMode(_:)": {
      "abstract": [
        {
          "text": "Specifies the receiver’s mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorPanel",
          "text": "NSColorPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSColorPanelMode",
          "text": "Mode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/setMode(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMode:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setMode(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/setmode(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/viewSizeChanged(_:)": {
      "abstract": [
        {
          "text": "Tells the recever when the color panel’s view size changes in a way that might affect the color picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewSizeChanged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/viewSizeChanged(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewSizeChanged:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "viewSizeChanged(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickingdefault/viewsizechanged(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingCustom"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorPicker"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Color-Panels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingCustom",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPicker"
      ],
      "title": "Color Panels"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Color-Pickers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/init(pickerMask:colorPanel:)"
      ],
      "title": "Creating Color Pickers"
    },
    {
      "anchor": "Configuring-Color-Pickers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/setMode(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/insertNewButtonImage(_:in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/provideNewButtonImage()",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/minContentSize()",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/buttonToolTip()"
      ],
      "title": "Configuring Color Pickers"
    },
    {
      "anchor": "Handling-Events",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/alphaControlAddedOrRemoved(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/viewSizeChanged(_:)"
      ],
      "title": "Handling Events"
    },
    {
      "anchor": "Managing-Color-Lists",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/attachColorList(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/detachColorList(_:)"
      ],
      "title": "Managing Color Lists"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSColorPickingDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickingDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickingDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Color-Pickers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/init(pickerMask:colorPanel:)"
              ],
              "title": "Creating Color Pickers"
            },
            {
              "anchor": "Configuring-Color-Pickers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/setMode(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/insertNewButtonImage(_:in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/provideNewButtonImage()",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/minContentSize()",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/buttonToolTip()"
              ],
              "title": "Configuring Color Pickers"
            },
            {
              "anchor": "Handling-Events",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/alphaControlAddedOrRemoved(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/viewSizeChanged(_:)"
              ],
              "title": "Handling Events"
            },
            {
              "anchor": "Managing-Color-Lists",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/attachColorList(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingDefault/detachColorList(_:)"
              ],
              "title": "Managing Color Lists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingCustom"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorPicker"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Color-Panels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickingCustom",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPicker"
              ],
              "title": "Color Panels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSColorPickingDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1attachColorList(_:)/title",
          "value": "attachColorList:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1attachColorList(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attachColorList:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1alphaControlAddedOrRemoved(_:)/title",
          "value": "alphaControlAddedOrRemoved:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1alphaControlAddedOrRemoved(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "alphaControlAddedOrRemoved:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1init(pickerMask:colorPanel:)/title",
          "value": "initWithPickerMask:colorPanel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1init(pickerMask:colorPanel:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPickerMask:colorPanel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingCustom/title",
          "value": "NSColorPickingCustom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingCustom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickingCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingCustom/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickingCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPanel/title",
          "value": "NSColorPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1insertNewButtonImage(_:in:)/title",
          "value": "insertNewButtonImage:in:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1insertNewButtonImage(_:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertNewButtonImage:in:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1minContentSize()/title",
          "value": "minContentSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1minContentSize()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "minContentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1provideNewButtonImage()/title",
          "value": "provideNewButtonImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1provideNewButtonImage()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provideNewButtonImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1setMode(_:)/title",
          "value": "setMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1setMode(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPicker/title",
          "value": "NSColorPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1buttonToolTip()/title",
          "value": "buttonToolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1buttonToolTip()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "buttonToolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault/title",
          "value": "NSColorPickingDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickingDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickingDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1viewSizeChanged(_:)/title",
          "value": "viewSizeChanged:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1viewSizeChanged(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewSizeChanged:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1detachColorList(_:)/title",
          "value": "detachColorList:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickingDefault~1detachColorList(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "detachColorList:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolorpickingdefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolorpickingdefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
