{
  "abstract": [
    {
      "text": "A closure that configures and returns an item for a collection view from its diffable data source.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSCollectionViewDiffableDataSourceItemProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCollectionView",
              "text": "NSCollectionView"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation9IndexPathV",
              "text": "IndexPath"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCollectionViewItem",
              "text": "NSCollectionViewItem"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The collection view to configure this item for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "collectionView"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The index path that specifies the location of the item in the collection view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "indexPath"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier of the data item for this item.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "itemIdentifier"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A non-",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " configured item object. The item provider must return a valid item object to the collection view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView": {
      "abstract": [
        {
          "text": "An ordered collection of data items displayed in a customizable layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionView"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionView",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference/init(collectionView:itemProvider:)": {
      "abstract": [
        {
          "text": "Creates a diffable data source with the specified item provider, and connects it to the specified collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSCollectionViewDiffableDataSourceItemProvider",
          "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference/init(collectionView:itemProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCollectionView:itemProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(collectionView:itemProvider:)",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewdiffabledatasourcereference/init(collectionview:itemprovider:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider": {
      "abstract": [
        {
          "text": "A closure that configures and returns an item for a collection view from its diffable data source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewDiffableDataSourceReferenceItemProvider",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewdiffabledatasourcereferenceitemprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewItem": {
      "abstract": [
        {
          "text": "The visual representation for a single data element in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewItem"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewItem",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewitem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV": {
      "abstract": [
        {
          "text": "A list of indexes that together represent the path to a specific location in a tree of nested arrays. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "IndexPath"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV",
      "kind": "symbol",
      "role": "symbol",
      "title": "IndexPath",
      "type": "topic",
      "url": "/documentation/foundation/indexpath"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Diffable-Data-Source",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference/init(collectionView:itemProvider:)"
      ],
      "title": "Creating a Diffable Data Source"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCollectionViewDiffableDataSourceItemProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSourceItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSourceItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Diffable-Data-Source",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference/init(collectionView:itemProvider:)"
              ],
              "title": "Creating a Diffable Data Source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BF*$objc(cs)NSCollectionViewItem(#*$objc(cs)NSCollectionView#*$objc(cs)NSIndexPath#*Qo)",
                    "text": "NSCollectionViewItem *(^)(NSCollectionView *, NSIndexPath *, id)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCollectionViewDiffableDataSourceItemProvider"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/title",
          "value": "NSCollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewItem/title",
          "value": "NSCollectionViewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReference~1init(collectionView:itemProvider:)/title",
          "value": "initWithCollectionView:itemProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReference~1init(collectionView:itemProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCollectionView:itemProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReferenceItemProvider/title",
          "value": "NSCollectionViewDiffableDataSourceItemProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReferenceItemProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSourceItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReferenceItemProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSourceItemProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscollectionviewdiffabledatasourcereferenceitemprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscollectionviewdiffabledatasourcereferenceitemprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
