{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"seeAlsoSections":[{"title":"View","anchor":"View","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionView"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView","interfaceLanguage":"swift"},"abstract":[{"text":"A protocol that defines a button to control the collapse of a collection view’s section.","type":"text"}],"relationshipsSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewElement","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewSectionHeaderView"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSCollectionViewElement","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewElement","text":"NSCollectionViewElement","kind":"typeIdentifier"}],"platforms":["macOS"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A collection view can support a section that can collapse into a single horizontally scrollable row, similar to the groupings in the icon view in Finder. To ensure that the collection view can communicate with the button that controls the collapsing of a section, the section header view object should conform to this protocol and connect the button’s outlet to ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView/sectionCollapseButton"},{"text":".","type":"text"}]}]}],"metadata":{"title":"NSCollectionViewSectionHeaderView","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewSectionHeaderView"}],"roleHeading":"Protocol","modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewSectionHeaderView"}],"symbolKind":"protocol","externalID":"c:objc(pl)NSCollectionViewSectionHeaderView","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}]},"topicSections":[{"title":"Providing a Collapse Button","anchor":"Providing-a-Collapse-Button","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView/sectionCollapseButton"]}],"variants":[{"paths":["/documentation/appkit/nscollectionviewsectionheaderview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscollectionviewsectionheaderview"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}],"type":"topic","abstract":[{"text":"A set of methods used to associate a unique identifier with objects in your user interface.","type":"text"}],"url":"/documentation/appkit/nsuserinterfaceitemidentification","title":"NSUserInterfaceItemIdentification","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionView":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView","navigatorTitle":[{"text":"NSCollectionView","kind":"identifier"}],"abstract":[{"type":"text","text":"An ordered collection of data items displayed in a customizable layout."}],"type":"topic","title":"NSCollectionView","url":"/documentation/appkit/nscollectionview"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView/sectionCollapseButton":{"url":"/documentation/appkit/nscollectionviewsectionheaderview/sectioncollapsebutton","navigatorTitle":[{"kind":"identifier","text":"sectionCollapseButton"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sectionCollapseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSButton","preciseIdentifier":"c:objc(cs)NSButton","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"sectionCollapseButton","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView/sectionCollapseButton","abstract":[{"text":"A control that lets users collapse and open a collection view section.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView":{"abstract":[{"text":"A protocol that defines a button to control the collapse of a collection view’s section.","type":"text"}],"url":"/documentation/appkit/nscollectionviewsectionheaderview","kind":"symbol","role":"symbol","title":"NSCollectionViewSectionHeaderView","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewSectionHeaderView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSCollectionViewSectionHeaderView"}]},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewElement":{"abstract":[{"type":"text","text":"A set of methods that you use to manage the content in a collection view."}],"url":"/documentation/appkit/nscollectionviewelement","kind":"symbol","role":"symbol","title":"NSCollectionViewElement","navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewElement"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewElement","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewElement"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"name":"macOS","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Protocol","op":"replace"},{"path":"/metadata/title","value":"NSCollectionViewSectionHeaderView","op":"replace"},{"path":"/metadata/symbolKind","value":"protocol","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"NSCollectionViewSectionHeaderView","kind":"identifier"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"text":"NSCollectionViewSectionHeaderView","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"anchor":"Providing-a-Collapse-Button","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewSectionHeaderView/sectionCollapseButton"],"title":"Providing a Collapse Button"}],"op":"replace"},{"path":"/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewElement"],"type":"inheritsFrom"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"title":"View","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionView"],"generated":true,"anchor":"View"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionViewSectionHeaderView","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSCollectionViewElement","preciseIdentifier":"c:objc(pl)NSCollectionViewElement","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewElement","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"op":"replace"},{"value":"NSUserInterfaceItemIdentification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSUserInterfaceItemIdentification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSUserInterfaceItemIdentification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle","op":"replace"},{"value":"NSCollectionView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSCollectionView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSCollectionView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/navigatorTitle","op":"replace"},{"value":"sectionCollapseButton","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView~1sectionCollapseButton/title","op":"replace"},{"op":"replace","value":[{"text":"sectionCollapseButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView~1sectionCollapseButton/fragments"},{"op":"replace","value":"NSCollectionViewSectionHeaderView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView/title"},{"op":"replace","value":[{"text":"NSCollectionViewSectionHeaderView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView/fragments"},{"op":"replace","value":[{"text":"NSCollectionViewSectionHeaderView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewSectionHeaderView/navigatorTitle"},{"op":"replace","value":"NSCollectionViewElement","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewElement/title"},{"op":"replace","value":[{"text":"NSCollectionViewElement","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewElement/fragments"},{"op":"replace","value":[{"text":"NSCollectionViewElement","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewElement/navigatorTitle"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}