{
  "abstract": [
    {
      "text": "The scrolling behavior of the layout’s sections in relation to the main layout axis.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSCollectionLayoutSectionOrthogonalScrollingBehavior",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, each section lays out its content along the main axis of its layout, defined by the layout configuration’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration/scrollDirection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. You can change this behavior for a particular section by setting its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSection/orthogonalScrollingBehavior",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to a different value than its default ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Setting any other value for this property makes the section lay out its content orthogonally to the main layout axis.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSection/orthogonalScrollingBehavior": {
      "abstract": [
        {
          "text": "The section’s scrolling behavior in relation to the main layout axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orthogonalScrollingBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionLayoutSectionOrthogonalScrollingBehavior",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSection/orthogonalScrollingBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orthogonalScrollingBehavior"
        }
      ],
      "role": "symbol",
      "title": "orthogonalScrollingBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsection/orthogonalscrollingbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior": {
      "abstract": [
        {
          "text": "The scrolling behavior of the layout’s sections in relation to the main layout axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuous": {
      "abstract": [
        {
          "text": "The section allows users to scroll its content orthogonally with continuous scrolling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuous"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.continuous",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/continuous"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary": {
      "abstract": [
        {
          "text": "The section allows users to scroll its content orthogonally, coming to a natural stop at the leading boundary of the visible group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuousGroupLeadingBoundary"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.continuousGroupLeadingBoundary",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/continuousgroupleadingboundary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally one group at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupPaging"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.groupPaging",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/grouppaging"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally one group at a time, centering each group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupPagingCentered"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.groupPagingCentered",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/grouppagingcentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none": {
      "abstract": [
        {
          "text": "The section does not allow users to scroll its content orthogonally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorNone"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.none",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/paging": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paging"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/paging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSectionOrthogonalScrollingBehavior.paging",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior/paging"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout": {
      "abstract": [
        {
          "text": "A layout object that lets you combine items in highly adaptive and flexible visual arrangements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewCompositionalLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration": {
      "abstract": [
        {
          "text": "An object that defines scroll direction, section spacing, and headers or footers for the layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayoutConfiguration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayoutConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewCompositionalLayoutConfiguration",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayoutconfiguration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration/scrollDirection": {
      "abstract": [
        {
          "text": "The axis that the content in the collection view layout scrolls along.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCollectionViewScrollDirection",
          "text": "ScrollDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration/scrollDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollDirection"
        }
      ],
      "role": "symbol",
      "title": "scrollDirection",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayoutconfiguration/scrolldirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider": {
      "abstract": [
        {
          "text": "A closure that creates and returns each of the layout’s sections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayoutSectionProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewCompositionalLayoutSectionProvider"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewCompositionalLayoutSectionProvider",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewcompositionallayoutsectionprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout": {
      "abstract": [
        {
          "text": "A set of methods that a delegate implements to provide layout information to a flow layout object in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewDelegateFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewDelegateFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewDelegateFlowLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewdelegateflowlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout": {
      "abstract": [
        {
          "text": "A layout that organizes items into a flexible and configurable arrangement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewFlowLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewflowlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout": {
      "abstract": [
        {
          "text": "A layout that displays a single section of items in a row and column grid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewGridLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewGridLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewGridLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewgridlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout": {
      "abstract": [
        {
          "text": "An abstract base class that you subclass and use to generate layout information for a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes": {
      "abstract": [
        {
          "text": "An object that contains layout-related attributes for an element in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewLayoutAttributes",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewlayoutattributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout": {
      "abstract": [
        {
          "text": "An object that implements custom behaviors when changing from one layout to another in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewTransitionLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewTransitionLayout"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewTransitionLayout",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewtransitionlayout"
    },
    "doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views": {
      "abstract": [
        {
          "text": "Bring compositional layouts to your app and simplify updating your user interface with diffable data sources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing modern collection views",
      "type": "topic",
      "url": "/documentation/UIKit/implementing-modern-collection-views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Layouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider"
      ],
      "title": "Layouts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/paging",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/none",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/paging",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Layouts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/UIKit/implementing-modern-collection-views",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewFlowLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDelegateFlowLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewGridLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewTransitionLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayoutAttributes",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutConfiguration",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewCompositionalLayoutSectionProvider"
              ],
              "title": "Layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1groupPagingCentered/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1groupPagingCentered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/title",
          "value": "NSCollectionViewFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1continuous/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1continuous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1groupPaging/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1groupPaging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration~1scrollDirection/title",
          "value": "scrollDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration~1scrollDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrollDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/title",
          "value": "NSCollectionViewDelegateFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDelegateFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDelegateFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDelegateFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSection~1orthogonalScrollingBehavior/title",
          "value": "orthogonalScrollingBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSection~1orthogonalScrollingBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1none/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/title",
          "value": "NSCollectionViewCompositionalLayoutSectionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayoutSectionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutSectionProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayoutSectionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/title",
          "value": "NSCollectionViewGridLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewGridLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewGridLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewGridLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/title",
          "value": "NSCollectionViewTransitionLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewTransitionLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewTransitionLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewTransitionLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/title",
          "value": "NSCollectionViewLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1continuousGroupLeadingBoundary/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1continuousGroupLeadingBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/title",
          "value": "NSCollectionViewCompositionalLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/title",
          "value": "NSCollectionViewCompositionalLayoutConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayoutConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewCompositionalLayoutConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewCompositionalLayoutConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/title",
          "value": "NSCollectionViewLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1paging/title",
          "value": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionLayoutSectionOrthogonalScrollingBehavior~1paging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscollectionlayoutsectionorthogonalscrollingbehavior"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
