{
  "abstract": [
    {
      "text": "The inset distances for views, taking the user interface layout direction into account.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@NSDirectionalEdgeInsets",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSDirectionalEdgeInsets"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDirectionalEdgeInsets"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSDirectionalEdgeInsets"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalEdgeInsets",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsets"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/bottom": {
      "abstract": [
        {
          "text": "The bottom edge inset value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "role": "symbol",
      "title": "bottom",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsets/bottom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init()": {
      "abstract": [
        {
          "text": "Creates a directional edge insets structure that contains default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsets/init()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init(_:)": {
      "abstract": [
        {
          "text": "Create edge insets from the equivalent EdgeInsets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI10EdgeInsetsV",
          "text": "EdgeInsets"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsets/init(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init(top:leading:bottom:trailing:)": {
      "abstract": [
        {
          "text": "Creates a directional edge insets structure that contains the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trailing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init(top:leading:bottom:trailing:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(top:leading:bottom:trailing:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsets/init(top:leading:bottom:trailing:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/leading": {
      "abstract": [
        {
          "text": "The leading edge inset value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "role": "symbol",
      "title": "leading",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsets/leading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/top": {
      "abstract": [
        {
          "text": "The top edge inset value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "role": "symbol",
      "title": "top",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsets/top"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/trailing": {
      "abstract": [
        {
          "text": "The trailing edge inset value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "role": "symbol",
      "title": "trailing",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsets/trailing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsetsMake": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsetsMake"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsetsMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDirectionalEdgeInsetsMake",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsetsmake"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsetsZero": {
      "abstract": [
        {
          "text": "A directional edge insets structure whose top, leading, bottom, and trailing fields all have a value of ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsetsZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsetsZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsetsZero"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalEdgeInsetsZero",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionaledgeinsetszero"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDirectionalRectEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDirectionalRectEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalRectEdge",
      "type": "topic",
      "url": "/documentation/appkit/nsdirectionalrectedge"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectAlignment": {
      "abstract": [
        {
          "text": "Constants that specify alignment to an edge or a set of edges depending on the user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRectAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nsrectalignment"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/2865946-string": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a directional edge insets structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": NSDirectionalEdgeInsets) -> String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/2865946-string",
      "kind": "symbol",
      "role": "symbol",
      "title": "string(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/2865946-string"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/2865991-nsdirectionaledgeinsets": {
      "abstract": [
        {
          "text": "Returns a directional edge insets structure based on data in the specified string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "nsDirectionalEdgeInsets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": String) -> NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/2865991-nsdirectionaledgeinsets",
      "kind": "symbol",
      "role": "symbol",
      "title": "nsDirectionalEdgeInsets(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/2865991-nsdirectionaledgeinsets"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSRectAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalRectEdge"
      ],
      "title": "Related types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-directional-edge-insets",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init()",
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init(top:leading:bottom:trailing:)"
      ],
      "title": "Creating directional edge insets"
    },
    {
      "anchor": "Getting-the-edge-values",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/bottom",
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/leading",
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/top",
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/trailing"
      ],
      "title": "Getting the edge values"
    },
    {
      "anchor": "Converting-to-and-from-strings",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nscoder/2865946-string",
        "doc://com.apple.documentation/documentation/foundation/nscoder/2865991-nsdirectionaledgeinsets"
      ],
      "title": "Converting to and from strings"
    },
    {
      "anchor": "Getting-the-empty-edge-insets",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsetsZero"
      ],
      "title": "Getting the empty edge insets"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/init(_:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDirectionalEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-directional-edge-insets",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsetsMake"
              ],
              "title": "Creating directional edge insets"
            },
            {
              "anchor": "Getting-the-edge-values",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/bottom",
                "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/leading",
                "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/top",
                "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsets/trailing"
              ],
              "title": "Getting the edge values"
            },
            {
              "anchor": "Converting-to-and-from-strings",
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/nscoder/2865946-string",
                "doc://com.apple.documentation/documentation/foundation/nscoder/2865991-nsdirectionaledgeinsets"
              ],
              "title": "Converting to and from strings"
            },
            {
              "anchor": "Getting-the-empty-edge-insets",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDirectionalEdgeInsetsZero"
              ],
              "title": "Getting the empty edge insets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSRectAlignment",
                "doc://com.apple.appkit/documentation/AppKit/NSDirectionalRectEdge"
              ],
              "title": "Related types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDirectionalEdgeInsets"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDirectionalEdgeInsets"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets/title",
          "value": "NSDirectionalEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets~1trailing/title",
          "value": "trailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalRectEdge/title",
          "value": "NSDirectionalRectEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalRectEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalRectEdge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets~1leading/title",
          "value": "leading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets~1bottom/title",
          "value": "bottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets~1top/title",
          "value": "top"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsets~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "top"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsetsZero/title",
          "value": "NSDirectionalEdgeInsetsZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDirectionalEdgeInsetsZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsetsZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment/title",
          "value": "NSRectAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdirectionaledgeinsets"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdirectionaledgeinsets"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
