{
  "abstract": [
    {
      "text": "Disables screen updates.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "As of 10.11 it is not generally necessary to take explicit action to achieve visual atomicity. +[NSAnimationContext runAnimationGroup:] and other similar methods can be used when a stronger than normal need for visual atomicity is required. The NSAnimationContext methods do not suffer from the same performance problems as NSDisableScreenUpdates.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDisableScreenUpdates()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@NSDisableScreenUpdates",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSDisableScreenUpdates"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDisableScreenUpdates"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.11",
        "introducedAt": "10.0",
        "message": "As of 10.11 it is not generally necessary to take explicit action to achieve visual atomicity. +[NSAnimationContext runAnimationGroup:] and other similar methods can be used when a stronger than normal need for visual atomicity is required. The NSAnimationContext methods do not suffer from the same performance problems as NSDisableScreenUpdates.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "NSDisableScreenUpdates()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDisableScreenUpdates"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Prevents drawing operations from being flushed to the screen for all windows belonging to the calling process. When you re-enable screen updates (with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEnableScreenUpdates()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") screen flushing for all windows belonging to the calling process appears to be simultaneous. You typically call this function so that operations on multiple windows appear atomic to the user. This is a technique particularly useful for synchronizing parent and child windows. Make sure that the period after calling this function and before reenabling updates is short; the system only allow updating to be disabled for a limited time (currently one second) before automatically reenabling updates. Successive calls to this function are placed on a stack and must be popped off that stack by matching ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEnableScreenUpdates()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " calls.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)": {
      "abstract": [
        {
          "text": "Raises an error if the parameter is the wrong type or has an illegal value",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raiseBadArgumentException"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRaiseBadArgumentException"
        }
      ],
      "role": "symbol",
      "title": "raiseBadArgumentException(_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/raisebadargumentexception(_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbeginalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginCriticalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginCriticalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegincriticalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginInformationalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginInformationalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegininformationalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Prepares a set of glyphs for processing by character-based routines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSGlyph",
          "text": "NSGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMultibyteGlyphPacking",
          "text": "NSMultibyteGlyphPacking"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        }
      ],
      "role": "symbol",
      "title": "NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsconvertglyphstopackedglyphs(_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCopyBits(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies a bitmap image to the location specified by a destination point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCopyBits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCopyBits(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCopyBits"
        }
      ],
      "role": "symbol",
      "title": "NSCopyBits(_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscopybits(_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDisableScreenUpdates()": {
      "abstract": [
        {
          "text": "Disables screen updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDisableScreenUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDisableScreenUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisableScreenUpdates"
        }
      ],
      "role": "symbol",
      "title": "NSDisableScreenUpdates()",
      "type": "topic",
      "url": "/documentation/appkit/nsdisablescreenupdates()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDottedFrameRect(_:)": {
      "abstract": [
        {
          "text": "Draws a bordered rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDottedFrameRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDottedFrameRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDottedFrameRect"
        }
      ],
      "role": "symbol",
      "title": "NSDottedFrameRect(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdottedframerect(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawColorTiledRects(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Draws a single-color, bordered rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawColorTiledRects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSRectEdge",
          "text": "NSRectEdge"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawColorTiledRects(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawColorTiledRects"
        }
      ],
      "role": "symbol",
      "title": "NSDrawColorTiledRects(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawcolortiledrects(_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEnableScreenUpdates()": {
      "abstract": [
        {
          "text": "Enables screen updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEnableScreenUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEnableScreenUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEnableScreenUpdates"
        }
      ],
      "role": "symbol",
      "title": "NSEnableScreenUpdates()",
      "type": "topic",
      "url": "/documentation/appkit/nsenablescreenupdates()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display a critical message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetcriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display an informational message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetinformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetWindowServerMemory(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the amount of memory being used by a context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGetWindowServerMemory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetWindowServerMemory(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGetWindowServerMemory"
        }
      ],
      "role": "symbol",
      "title": "NSGetWindowServerMemory(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgetwindowservermemory(_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption": {
      "abstract": [
        {
          "text": "Returns global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion": {
      "abstract": [
        {
          "text": "Returns the NSOpenGL version numbers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption": {
      "abstract": [
        {
          "text": "Sets global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLSetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLSetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglsetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContentsType(forPathExtension:)": {
      "abstract": [
        {
          "text": "Returns a pasteboard type based on the passed file type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileContentsType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forPathExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContentsType(forPathExtension:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCreateFileContentsPboardType"
        }
      ],
      "role": "symbol",
      "title": "fileContentsType(forPathExtension:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/filecontentstype(forpathextension:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileNameType(forPathExtension:)": {
      "abstract": [
        {
          "text": "Returns a pasteboard type based on the passed file type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNameType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forPathExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileNameType(forPathExtension:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCreateFilenamePboardType"
        }
      ],
      "role": "symbol",
      "title": "fileNameType(forPathExtension:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/filenametype(forpathextension:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtension": {
      "abstract": [
        {
          "text": "A file type based on the passed pasteboard type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "representedPathExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGetFileType"
        }
      ],
      "role": "symbol",
      "title": "representedPathExtension",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/representedpathextension"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtensions(from:)": {
      "abstract": [
        {
          "text": "Returns an array of file types based on the passed pasteboard types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "representedPathExtensions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtensions(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGetFileTypes"
        }
      ],
      "role": "symbol",
      "title": "representedPathExtensions(from:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/representedpathextensions(from:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReadPixel(_:)": {
      "abstract": [
        {
          "text": "Reads the color of the pixel at the specified location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReadPixel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReadPixel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReadPixel"
        }
      ],
      "role": "symbol",
      "title": "NSReadPixel(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsreadpixel(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)": {
      "abstract": [
        {
          "text": "Disposes of an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        }
      ],
      "role": "symbol",
      "title": "NSReleaseAlertPanel(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsreleasealertpanel(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel": {
      "abstract": [
        {
          "text": "Creates an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsrunalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruncriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruninformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSetShowsServicesMenuItem(_:_:)": {
      "abstract": [
        {
          "text": "Specifies whether an item should be included in Services menus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSetShowsServicesMenuItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSetShowsServicesMenuItem(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSetShowsServicesMenuItem"
        }
      ],
      "role": "symbol",
      "title": "NSSetShowsServicesMenuItem(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nssetshowsservicesmenuitem(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSShowsServicesMenuItem(_:)": {
      "abstract": [
        {
          "text": "Specifies whether a Services menu item is currently enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSShowsServicesMenuItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSShowsServicesMenuItem(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSShowsServicesMenuItem"
        }
      ],
      "role": "symbol",
      "title": "NSShowsServicesMenuItem(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsshowsservicesmenuitem(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSEnableScreenUpdates()",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawColorTiledRects(_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSetShowsServicesMenuItem(_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCopyBits(_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSShowsServicesMenuItem(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDottedFrameRect(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSReadPixel(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGetWindowServerMemory(_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContentsType(forPathExtension:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileNameType(forPathExtension:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtension",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtensions(from:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.11",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDisableScreenUpdates"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisableScreenUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
                "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
                "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
                "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDisableScreenUpdates"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "As of 10.11 it is not generally necessary to take explicit action to achieve visual atomicity. +[NSAnimationContext runAnimationGroup:] and other similar methods can be used when a stronger than normal need for visual atomicity is required. The NSAnimationContext methods do not suffer from the same performance problems as NSDisableScreenUpdates.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSShowsServicesMenuItem(_:)/title",
          "value": "NSShowsServicesMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSShowsServicesMenuItem(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSShowsServicesMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1representedPathExtension/title",
          "value": "NSGetFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1representedPathExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGetFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDottedFrameRect(_:)/title",
          "value": "NSDottedFrameRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDottedFrameRect(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDottedFrameRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSetShowsServicesMenuItem(_:_:)/title",
          "value": "NSSetShowsServicesMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSetShowsServicesMenuItem(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSetShowsServicesMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileContentsType(forPathExtension:)/title",
          "value": "NSCreateFileContentsPboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileContentsType(forPathExtension:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCreateFileContentsPboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/title",
          "value": "NSReleaseAlertPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReleaseAlertPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEnableScreenUpdates()/title",
          "value": "NSEnableScreenUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEnableScreenUpdates()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEnableScreenUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGetWindowServerMemory(_:_:_:_:)/title",
          "value": "NSGetWindowServerMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGetWindowServerMemory(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGetWindowServerMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCopyBits(_:_:_:)/title",
          "value": "NSCopyBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCopyBits(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCopyBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReadPixel(_:)/title",
          "value": "NSReadPixel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReadPixel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReadPixel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileNameType(forPathExtension:)/title",
          "value": "NSCreateFilenamePboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileNameType(forPathExtension:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCreateFilenamePboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/title",
          "value": "NSAccessibilityRaiseBadArgumentException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRaiseBadArgumentException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawColorTiledRects(_:_:_:_:_:)/title",
          "value": "NSDrawColorTiledRects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawColorTiledRects(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawColorTiledRects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDisableScreenUpdates()/title",
          "value": "NSDisableScreenUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDisableScreenUpdates()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisableScreenUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1representedPathExtensions(from:)/title",
          "value": "NSGetFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1representedPathExtensions(from:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGetFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/title",
          "value": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConvertGlyphsToPackedGlyphs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdisablescreenupdates()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdisablescreenupdates()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
