{
  "abstract": [
    {
      "text": "The panel is created as a modal sheet.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocModalWindowMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSDocModalWindowMask",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSDocModalWindowMask"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDocModalWindowMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSDocModalWindowMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSWindowStyleMask",
              "text": "NSWindowStyleMask"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDocModalWindowMask"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocModalWindowMask": {
      "abstract": [
        {
          "text": "The panel is created as a modal sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDocModalWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocModalWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDocModalWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsdocmodalwindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHUDWindowMask": {
      "abstract": [
        {
          "text": "The panel is created as a transparent panel (sometimes called a “heads-up display”).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHUDWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHUDWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHUDWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nshudwindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNonactivatingPanelMask": {
      "abstract": [
        {
          "text": "The panel can receive keyboard input without activating the owning app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNonactivatingPanelMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNonactivatingPanelMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNonactivatingPanelMask",
      "type": "topic",
      "url": "/documentation/appkit/nsnonactivatingpanelmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUtilityWindowMask": {
      "abstract": [
        {
          "text": "The panel is created as a floating window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUtilityWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUtilityWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUtilityWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsutilitywindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify the style of a window, and that you can combine with the C bitwise OR operator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StyleMask"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.StyleMask",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSUtilityWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSNonactivatingPanelMask",
        "doc://com.apple.appkit/documentation/AppKit/NSHUDWindowMask"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/title",
          "value": "NSWindowStyleMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocmodalwindowmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
