{
  "abstract": [
    {
      "text": "A set of methods that drawer delegates implement to open, close, and resize the drawer.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Drawers are deprecated and should not be used in modern macOS apps.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSDrawerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSDrawerDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDrawerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSDrawerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate": {
      "abstract": [
        {
          "text": "A set of methods that drawer delegates implement to open, close, and resize the drawer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawerDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawerDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSDrawerDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerDidClose(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate that the drawer has closed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawerDidClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerDidClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawerDidClose:"
        }
      ],
      "role": "symbol",
      "title": "drawerDidClose(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate/drawerdidclose(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerDidOpen(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate that the drawer has opened.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawerDidOpen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerDidOpen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawerDidOpen:"
        }
      ],
      "role": "symbol",
      "title": "drawerDidOpen(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate/drawerdidopen(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerShouldClose(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate if the specified drawer should close.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawerShouldClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDrawer",
          "text": "NSDrawer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerShouldClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawerShouldClose:"
        }
      ],
      "role": "symbol",
      "title": "drawerShouldClose(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate/drawershouldclose(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerShouldOpen(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate if the specified drawer should open.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawerShouldOpen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDrawer",
          "text": "NSDrawer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerShouldOpen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawerShouldOpen:"
        }
      ],
      "role": "symbol",
      "title": "drawerShouldOpen(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate/drawershouldopen(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillClose(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate the drawer will close.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawerWillClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawerWillClose:"
        }
      ],
      "role": "symbol",
      "title": "drawerWillClose(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate/drawerwillclose(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillOpen(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate that the drawer will open.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawerWillOpen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillOpen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawerWillOpen:"
        }
      ],
      "role": "symbol",
      "title": "drawerWillOpen(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate/drawerwillopen(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillResizeContents(_:to:)": {
      "abstract": [
        {
          "text": "Invoked when the user resizes the drawer or parent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawerWillResizeContents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDrawer",
          "text": "NSDrawer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillResizeContents(_:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawerWillResizeContents:toSize:"
        }
      ],
      "role": "symbol",
      "title": "drawerWillResizeContents(_:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate/drawerwillresizecontents(_:to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration": {
      "abstract": [
        {
          "text": "A set of methods that controllers can implement to enable an editor view to inform the controller when it has uncommitted changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEditorRegistration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEditorRegistration"
        }
      ],
      "role": "symbol",
      "title": "NSEditorRegistration",
      "type": "topic",
      "url": "/documentation/appkit/nseditorregistration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInputServerMouseTracker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInputServerMouseTracker"
        }
      ],
      "role": "symbol",
      "title": "NSInputServerMouseTracker",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInputServiceProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInputServiceProvider"
        }
      ],
      "role": "symbol",
      "title": "NSInputServiceProvider",
      "type": "topic",
      "url": "/documentation/appkit/nsinputserviceprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsaccessibility": {
      "abstract": [
        {
          "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols": {
      "abstract": [
        {
          "text": "A set of methods that controllers and UI elements can implement to manage editing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSEditor",
      "type": "topic",
      "url": "/documentation/appkit/nseditor-deprecated-symbols"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
        "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
        "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
        "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
        "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Opening-and-Closing-Drawers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerShouldOpen(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillOpen(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerDidOpen(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerShouldClose(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillClose(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerDidClose(_:)"
      ],
      "title": "Opening and Closing Drawers"
    },
    {
      "anchor": "Managing-Drawer-Size",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillResizeContents(_:to:)"
      ],
      "title": "Managing Drawer Size"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDrawerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Opening-and-Closing-Drawers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerShouldOpen(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillOpen(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerDidOpen(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerShouldClose(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillClose(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerDidClose(_:)"
              ],
              "title": "Opening and Closing Drawers"
            },
            {
              "anchor": "Managing-Drawer-Size",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate/drawerWillResizeContents(_:to:)"
              ],
              "title": "Managing Drawer Size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
                "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
                "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDrawerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Drawers are deprecated and should not be used in modern macOS apps.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerWillClose(_:)/title",
          "value": "drawerWillClose:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerWillClose(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawerWillClose:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerDidClose(_:)/title",
          "value": "drawerDidClose:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerDidClose(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawerDidClose:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/title",
          "value": "NSInputServerMouseTracker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/title",
          "value": "NSInputServiceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServiceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServiceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerDidOpen(_:)/title",
          "value": "drawerDidOpen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerDidOpen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawerDidOpen:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerShouldOpen(_:)/title",
          "value": "drawerShouldOpen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerShouldOpen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawerShouldOpen:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/title",
          "value": "NSEditorRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditorRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditorRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerShouldClose(_:)/title",
          "value": "drawerShouldClose:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerShouldClose(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawerShouldClose:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/title",
          "value": "NSDrawerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerWillResizeContents(_:to:)/title",
          "value": "drawerWillResizeContents:toSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerWillResizeContents(_:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawerWillResizeContents:toSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerWillOpen(_:)/title",
          "value": "drawerWillOpen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate~1drawerWillOpen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawerWillOpen:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdrawerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdrawerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
