{
  "abstract": [
    {
      "text": "A set of methods that supply information about a dragging session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSDraggingInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSDraggingInfo"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDraggingInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSDraggingInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You invoke the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol methods from within a class’s implementation of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods. AppKit automatically passes an object that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol as the argument to each of the methods that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " defines. Send ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " messages to this object. You never need to create a class that implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDragOperation": {
      "abstract": [
        {
          "text": "A group of constants that represent which operations the dragging source can perform on dragging items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDragOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDragOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDragOperation"
        }
      ],
      "role": "symbol",
      "title": "NSDragOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsdragoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingContext": {
      "abstract": [
        {
          "text": "Constants that specify whether a drag terminates within or outside the application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingContext"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingContext",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination": {
      "abstract": [
        {
          "text": "A set of methods that the destination object (or recipient) of a dragged image must implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingDestination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingDestination"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingDestination",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingdestination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation": {
      "abstract": [
        {
          "text": "Constants that control the visual format of multiple dragging items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingFormation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingFormation"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingFormation",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingformation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo": {
      "abstract": [
        {
          "text": "A set of methods that supply information about a dragging session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingInfo"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/animatesToDestination": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the dragging formation animates while the drag is over the destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animatesToDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/animatesToDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animatesToDestination"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "animatesToDestination",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/animatestodestination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggedImage": {
      "abstract": [
        {
          "text": "The image that represents the dragging item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggedImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggedImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggedImage"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggedImage",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/draggedimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggedImageLocation": {
      "abstract": [
        {
          "text": "The current location of the dragged image’s origin, in the base coordinate system of the destination object’s window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggedImageLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggedImageLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggedImageLocation"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggedImageLocation",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/draggedimagelocation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingDestinationWindow": {
      "abstract": [
        {
          "text": "The destination window for the dragging operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingDestinationWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingDestinationWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingDestinationWindow"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggingDestinationWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/draggingdestinationwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingFormation": {
      "abstract": [
        {
          "text": "The formation of the dragging items while the drag is over the destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingFormation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDraggingFormation",
          "text": "NSDraggingFormation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingFormation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingFormation"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggingFormation",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/draggingformation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingLocation": {
      "abstract": [
        {
          "text": "The current location of the mouse pointer in the base coordinate system of the destination object’s window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingLocation"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggingLocation",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/dragginglocation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingPasteboard": {
      "abstract": [
        {
          "text": "The pasteboard object that holds the dragged data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingPasteboard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingPasteboard"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggingPasteboard",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/draggingpasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSequenceNumber": {
      "abstract": [
        {
          "text": "A number that uniquely identifies the dragging session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingSequenceNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSequenceNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingSequenceNumber"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggingSequenceNumber",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/draggingsequencenumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSource": {
      "abstract": [
        {
          "text": "The source, or owner, of the dragged data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingSource"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggingSource",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/draggingsource"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSourceOperationMask": {
      "abstract": [
        {
          "text": "Information about the dragging operation and the data it contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingSourceOperationMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDragOperation",
          "text": "NSDragOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSourceOperationMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingSourceOperationMask"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggingSourceOperationMask",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/draggingsourceoperationmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/enumerateDraggingItems(options:for:classes:searchOptions:using:)": {
      "abstract": [
        {
          "text": "Enumerates through each dragging item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateDraggingItems"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDraggingItemEnumerationOptions",
          "text": "NSDraggingItemEnumerationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "classes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "searchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
          "text": "ReadingOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingItem",
          "text": "NSDraggingItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/enumerateDraggingItems(options:for:classes:searchOptions:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "enumerateDraggingItems(options:for:classes:searchOptions:using:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/enumeratedraggingitems(options:for:classes:searchoptions:using:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/namesOfPromisedFilesDropped(atDestination:)": {
      "abstract": [
        {
          "text": "Sets the drop location for promised files and returns the names of the files that the receiver promises to create there.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "namesOfPromisedFilesDropped"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/namesOfPromisedFilesDropped(atDestination:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "namesOfPromisedFilesDroppedAtDestination:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "namesOfPromisedFilesDropped(atDestination:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/namesofpromisedfilesdropped(atdestination:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/numberOfValidItemsForDrop": {
      "abstract": [
        {
          "text": "The number of valid items for a drop operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfValidItemsForDrop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/numberOfValidItemsForDrop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfValidItemsForDrop"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "numberOfValidItemsForDrop",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/numberofvaliditemsfordrop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/resetSpringLoading()": {
      "abstract": [
        {
          "text": "Resets a spring-loading operation to its initial state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetSpringLoading"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/resetSpringLoading()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetSpringLoading"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "resetSpringLoading()",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/resetspringloading()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/slideDraggedImage(to:)": {
      "abstract": [
        {
          "text": "Slides the image to a specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slideDraggedImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/slideDraggedImage(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "slideDraggedImageTo:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "slideDraggedImage(to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/slidedraggedimage(to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/springLoadingHighlight": {
      "abstract": [
        {
          "text": "A highlighting style for your app’s user interface to display during a spring-loading operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "springLoadingHighlight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSpringLoadingHighlight",
          "text": "NSSpringLoadingHighlight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/springLoadingHighlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springLoadingHighlight"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "springLoadingHighlight",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo/springloadinghighlight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions": {
      "abstract": [
        {
          "text": "A group of constants that specify options to use when enumerating dragging items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingItemEnumerationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingItemEnumerationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingItemEnumerationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingitemenumerationoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination": {
      "abstract": [
        {
          "text": "A set of methods that the destination object (or recipient) of a dragged object can implement to support spring-loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSpringLoadingDestination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpringLoadingDestination"
        }
      ],
      "role": "symbol",
      "title": "NSSpringLoadingDestination",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingdestination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingHighlight": {
      "abstract": [
        {
          "text": "A group of constants that indicate a highlighting style for your app’s user interface to display during a spring-loading operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSpringLoadingHighlight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingHighlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpringLoadingHighlight"
        }
      ],
      "role": "symbol",
      "title": "NSSpringLoadingHighlight",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadinghighlight"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drop-Targets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination"
      ],
      "title": "Drop Targets"
    }
  ],
  "topicSections": [
    {
      "anchor": "Obtaining-information-about-the-dragging-session",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingPasteboard",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSequenceNumber",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSource",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSourceOperationMask",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingLocation",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingDestinationWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/numberOfValidItemsForDrop",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/namesOfPromisedFilesDropped(atDestination:)"
      ],
      "title": "Obtaining information about the dragging session"
    },
    {
      "anchor": "Getting-image-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggedImageLocation",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggedImage"
      ],
      "title": "Getting image information"
    },
    {
      "anchor": "Sliding-the-image",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/slideDraggedImage(to:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/animatesToDestination",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingFormation"
      ],
      "title": "Sliding the image"
    },
    {
      "anchor": "Enumerate-dragged-items",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/enumerateDraggingItems(options:for:classes:searchOptions:using:)"
      ],
      "title": "Enumerate dragged items"
    },
    {
      "anchor": "Implementing-spring-loading-support",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/springLoadingHighlight",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/resetSpringLoading()"
      ],
      "title": "Implementing spring-loading support"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDragOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingHighlight",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingContext"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDraggingInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Obtaining-information-about-the-dragging-session",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingPasteboard",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSequenceNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSource",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingSourceOperationMask",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingLocation",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingDestinationWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/numberOfValidItemsForDrop",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/namesOfPromisedFilesDropped(atDestination:)"
              ],
              "title": "Obtaining information about the dragging session"
            },
            {
              "anchor": "Getting-image-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggedImageLocation",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggedImage"
              ],
              "title": "Getting image information"
            },
            {
              "anchor": "Sliding-the-image",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/slideDraggedImage(to:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/animatesToDestination",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/draggingFormation"
              ],
              "title": "Sliding the image"
            },
            {
              "anchor": "Enumerate-dragged-items",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/enumerateDraggingItems(options:for:classes:searchOptions:using:)"
              ],
              "title": "Enumerate dragged items"
            },
            {
              "anchor": "Implementing-spring-loading-support",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/springLoadingHighlight",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/resetSpringLoading()"
              ],
              "title": "Implementing spring-loading support"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDragOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingItemEnumerationOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingHighlight",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingContext"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Drop-Targets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination"
              ],
              "title": "Drop Targets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDraggingInfo"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1namesOfPromisedFilesDropped(atDestination:)/title",
          "value": "namesOfPromisedFilesDroppedAtDestination:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1namesOfPromisedFilesDropped(atDestination:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "namesOfPromisedFilesDroppedAtDestination:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination/title",
          "value": "NSSpringLoadingDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpringLoadingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpringLoadingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/title",
          "value": "NSDraggingDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingFormation/title",
          "value": "draggingFormation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingFormation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggingFormation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingSource/title",
          "value": "draggingSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggingSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItemEnumerationOptions/title",
          "value": "NSDraggingItemEnumerationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItemEnumerationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingItemEnumerationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItemEnumerationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingItemEnumerationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1springLoadingHighlight/title",
          "value": "springLoadingHighlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1springLoadingHighlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "springLoadingHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingSequenceNumber/title",
          "value": "draggingSequenceNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingSequenceNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggingSequenceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1enumerateDraggingItems(options:for:classes:searchOptions:using:)/title",
          "value": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1enumerateDraggingItems(options:for:classes:searchOptions:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingHighlight/title",
          "value": "NSSpringLoadingHighlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingHighlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpringLoadingHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingHighlight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpringLoadingHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation/title",
          "value": "NSDraggingFormation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingPasteboard/title",
          "value": "draggingPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggingPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1numberOfValidItemsForDrop/title",
          "value": "numberOfValidItemsForDrop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1numberOfValidItemsForDrop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfValidItemsForDrop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingSourceOperationMask/title",
          "value": "draggingSourceOperationMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingSourceOperationMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggingSourceOperationMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1slideDraggedImage(to:)/title",
          "value": "slideDraggedImageTo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1slideDraggedImage(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "slideDraggedImageTo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDragOperation/title",
          "value": "NSDragOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDragOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDragOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDragOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDragOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingLocation/title",
          "value": "draggingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggingLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingContext/title",
          "value": "NSDraggingContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggedImageLocation/title",
          "value": "draggedImageLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggedImageLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggedImageLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingDestinationWindow/title",
          "value": "draggingDestinationWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggingDestinationWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggingDestinationWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1animatesToDestination/title",
          "value": "animatesToDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1animatesToDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "animatesToDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggedImage/title",
          "value": "draggedImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1draggedImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "draggedImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1resetSpringLoading()/title",
          "value": "resetSpringLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1resetSpringLoading()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resetSpringLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/title",
          "value": "NSDraggingInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdragginginfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdragginginfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
