{
  "abstract": [
    {
      "text": "A set of methods that are implemented by the source object in a dragging session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSDraggingSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSDraggingSource"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDraggingSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSDraggingSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDraggingSource"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS 10.7 and later ",
              "type": "text"
            },
            {
              "code": "NSDraggingSource",
              "type": "codeVoice"
            },
            {
              "text": " is now a formal protocol and has an updated interface. The OS X v10.6 behavior has been retained, but will be dropped in a future version of the operating system. The methods that are to be deprecated are marked as such.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView": {
      "abstract": [
        {
          "text": "An ordered collection of data items displayed in a customizable layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionView"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionView",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent": {
      "abstract": [
        {
          "text": "A single object in a dragging item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingImageComponent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingImageComponent"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingImageComponent",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingimagecomponent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem": {
      "abstract": [
        {
          "text": "A single dragged item within a dragging session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingItem"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingItem",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession": {
      "abstract": [
        {
          "text": "The encapsulation of a drag-and-drop action that supports modification of the drag while in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingSession"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingSession"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingSession",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsession"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource": {
      "abstract": [
        {
          "text": "A set of methods that are implemented by the source object in a dragging session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingSource"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingSource"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingSource",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsource"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:endedAt:operation:)": {
      "abstract": [
        {
          "text": "Invoked when the dragging session has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingSession",
          "text": "NSDraggingSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endedAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "operation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDragOperation",
          "text": "NSDragOperation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:endedAt:operation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingSession:endedAtPoint:operation:"
        }
      ],
      "role": "symbol",
      "title": "draggingSession(_:endedAt:operation:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsource/draggingsession(_:endedat:operation:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:movedTo:)": {
      "abstract": [
        {
          "text": "Invoked when the drag moves on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingSession",
          "text": "NSDraggingSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "movedTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:movedTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingSession:movedToPoint:"
        }
      ],
      "role": "symbol",
      "title": "draggingSession(_:movedTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsource/draggingsession(_:movedto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:sourceOperationMaskFor:)": {
      "abstract": [
        {
          "text": "Declares the types of operations the source allows to be performed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingSession",
          "text": "NSDraggingSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceOperationMaskFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDraggingContext",
          "text": "NSDraggingContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDragOperation",
          "text": "NSDragOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:sourceOperationMaskFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingSession:sourceOperationMaskForDraggingContext:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draggingSession(_:sourceOperationMaskFor:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsource/draggingsession(_:sourceoperationmaskfor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:willBeginAt:)": {
      "abstract": [
        {
          "text": "Invoked when the drag will begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingSession",
          "text": "NSDraggingSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willBeginAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:willBeginAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingSession:willBeginAtPoint:"
        }
      ],
      "role": "symbol",
      "title": "draggingSession(_:willBeginAt:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsource/draggingsession(_:willbeginat:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/ignoreModifierKeys(for:)": {
      "abstract": [
        {
          "text": "Returns whether the modifier keys will be ignored for this dragging session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoreModifierKeys"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDraggingSession",
          "text": "NSDraggingSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/ignoreModifierKeys(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ignoreModifierKeysForDraggingSession:"
        }
      ],
      "role": "symbol",
      "title": "ignoreModifierKeys(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingsource/ignoremodifierkeys(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOutlineView": {
      "abstract": [
        {
          "text": "A view that uses a row-and-column format to display hierarchical data like directories and files that can be expanded and collapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOutlineView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOutlineView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOutlineView"
        }
      ],
      "role": "symbol",
      "title": "NSOutlineView",
      "type": "topic",
      "url": "/documentation/appkit/nsoutlineview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1416082-namesofpromisedfilesdropped": {
      "abstract": [
        {
          "text": "Returns the names of the files that the receiver promises to create at a specified location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "namesOfPromisedFilesDropped"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "atDestination"
        },
        {
          "kind": "text",
          "text": ": URL) -> [String]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1416082-namesofpromisedfilesdropped",
      "kind": "symbol",
      "role": "symbol",
      "title": "namesOfPromisedFilesDropped(atDestination:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1416082-namesofpromisedfilesdropped"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DragandDrop/DragandDrop.html#//apple_ref/doc/uid/10000069i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DragandDrop/DragandDrop.html#//apple_ref/doc/uid/10000069i",
      "title": "Drag and Drop Programming Topics",
      "titleInlineContent": [
        {
          "text": "Drag and Drop Programming Topics",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DragandDrop/DragandDrop.html#//apple_ref/doc/uid/10000069i"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
        "doc://com.apple.appkit/documentation/AppKit/NSOutlineView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DragandDrop/DragandDrop.html#//apple_ref/doc/uid/10000069i"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Drag-Sources",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent"
      ],
      "title": "Drag Sources"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dragging-Session-Operation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:sourceOperationMaskFor:)"
      ],
      "title": "Dragging Session Operation"
    },
    {
      "anchor": "Dragging-Session-Locations",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:willBeginAt:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:movedTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:endedAt:operation:)"
      ],
      "title": "Dragging Session Locations"
    },
    {
      "anchor": "Dragging-Session-Modifier-Keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/ignoreModifierKeys(for:)"
      ],
      "title": "Dragging Session Modifier Keys"
    },
    {
      "anchor": "Dragging-Options",
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1416082-namesofpromisedfilesdropped"
      ],
      "title": "Dragging Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDraggingSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dragging-Session-Operation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:sourceOperationMaskFor:)"
              ],
              "title": "Dragging Session Operation"
            },
            {
              "anchor": "Dragging-Session-Locations",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:willBeginAt:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:movedTo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/draggingSession(_:endedAt:operation:)"
              ],
              "title": "Dragging Session Locations"
            },
            {
              "anchor": "Dragging-Session-Modifier-Keys",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingSource/ignoreModifierKeys(for:)"
              ],
              "title": "Dragging Session Modifier Keys"
            },
            {
              "anchor": "Dragging-Options",
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1416082-namesofpromisedfilesdropped"
              ],
              "title": "Dragging Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DragandDrop/DragandDrop.html#//apple_ref/doc/uid/10000069i"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Drag-Sources",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingItem",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingSession",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingImageComponent"
              ],
              "title": "Drag Sources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDraggingSource"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/title",
          "value": "NSDraggingSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource/title",
          "value": "NSDraggingSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingImageComponent/title",
          "value": "NSDraggingImageComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingImageComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingImageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingImageComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingImageComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/title",
          "value": "NSCollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11416082-namesofpromisedfilesdropped/title",
          "value": "namesOfPromisedFilesDroppedAtDestination:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1draggingSession(_:movedTo:)/title",
          "value": "draggingSession:movedToPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1draggingSession(_:movedTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "draggingSession:movedToPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1draggingSession(_:endedAt:operation:)/title",
          "value": "draggingSession:endedAtPoint:operation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1draggingSession(_:endedAt:operation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "draggingSession:endedAtPoint:operation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1ignoreModifierKeys(for:)/title",
          "value": "ignoreModifierKeysForDraggingSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1ignoreModifierKeys(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "ignoreModifierKeysForDraggingSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1draggingSession(_:willBeginAt:)/title",
          "value": "draggingSession:willBeginAtPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1draggingSession(_:willBeginAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "draggingSession:willBeginAtPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1draggingSession(_:sourceOperationMaskFor:)/title",
          "value": "draggingSession:sourceOperationMaskForDraggingContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingSource~1draggingSession(_:sourceOperationMaskFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "draggingSession:sourceOperationMaskForDraggingContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/title",
          "value": "NSOutlineView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/title",
          "value": "NSDraggingItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdraggingsource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdraggingsource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
