{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEditor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSEditor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSEditor"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEditor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSEditor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSEditor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSArrayController": {
      "abstract": [
        {
          "text": "A bindings-compatible controller that manages a collection of objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSArrayController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSArrayController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSArrayController"
        }
      ],
      "role": "symbol",
      "title": "NSArrayController",
      "type": "topic",
      "url": "/documentation/appkit/nsarraycontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewItem": {
      "abstract": [
        {
          "text": "The visual representation for a single data element in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewItem"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewItem",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSController": {
      "abstract": [
        {
          "text": "An abstract class that implements the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " informal protocols required for controller classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSController"
        }
      ],
      "role": "symbol",
      "title": "NSController",
      "type": "topic",
      "url": "/documentation/appkit/nscontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController": {
      "abstract": [
        {
          "text": "A bindings-compatible controller that manages the display and editing of a dictionary of key-value pairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDictionaryController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDictionaryController"
        }
      ],
      "role": "symbol",
      "title": "NSDictionaryController",
      "type": "topic",
      "url": "/documentation/appkit/nsdictionarycontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEditor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEditor"
        }
      ],
      "role": "symbol",
      "title": "NSEditor",
      "type": "topic",
      "url": "/documentation/appkit/nseditor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditing()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commitEditing"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commitEditing"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "commitEditing()",
      "type": "topic",
      "url": "/documentation/appkit/nseditor/commitediting()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditing(withDelegate:didCommit:contextInfo:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commitEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditing(withDelegate:didCommit:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commitEditingWithDelegate:didCommitSelector:contextInfo:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "commitEditing(withDelegate:didCommit:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nseditor/commitediting(withdelegate:didcommit:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditingWithoutPresentingError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commitEditingWithoutPresentingError"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditingWithoutPresentingError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commitEditingAndReturnError:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "commitEditingWithoutPresentingError()",
      "type": "topic",
      "url": "/documentation/appkit/nseditor/commiteditingwithoutpresentingerror()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditor/discardEditing()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discardEditing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditor/discardEditing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discardEditing"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "discardEditing()",
      "type": "topic",
      "url": "/documentation/appkit/nseditor/discardediting()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration": {
      "abstract": [
        {
          "text": "A set of methods that controllers can implement to enable an editor view to inform the controller when it has uncommitted changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEditorRegistration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEditorRegistration"
        }
      ],
      "role": "symbol",
      "title": "NSEditorRegistration",
      "type": "topic",
      "url": "/documentation/appkit/nseditorregistration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSObjectController": {
      "abstract": [
        {
          "text": "A controller that can manage an object’s properties referenced by key-value paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSObjectController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSObjectController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSObjectController"
        }
      ],
      "role": "symbol",
      "title": "NSObjectController",
      "type": "topic",
      "url": "/documentation/appkit/nsobjectcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageController": {
      "abstract": [
        {
          "text": "An object that controls swipe navigation and animations between views or view content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageController"
        }
      ],
      "role": "symbol",
      "title": "NSPageController",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitViewController": {
      "abstract": [
        {
          "text": "An object that manages an array of adjacent child views, and has a split view object for managing dividers between those views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSplitViewController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewController"
        }
      ],
      "role": "symbol",
      "title": "NSSplitViewController",
      "type": "topic",
      "url": "/documentation/appkit/nssplitviewcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabViewController": {
      "abstract": [
        {
          "text": "A container view controller that manages a tab view interface, which organizes multiple pages of content but displays only one page at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTabViewController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabViewController"
        }
      ],
      "role": "symbol",
      "title": "NSTabViewController",
      "type": "topic",
      "url": "/documentation/appkit/nstabviewcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController": {
      "abstract": [
        {
          "text": "An object that manages a custom view—known as an accessory view—in the title bar–toolbar area of a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTitlebarAccessoryViewController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTitlebarAccessoryViewController"
        }
      ],
      "role": "symbol",
      "title": "NSTitlebarAccessoryViewController",
      "type": "topic",
      "url": "/documentation/appkit/nstitlebaraccessoryviewcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTreeController": {
      "abstract": [
        {
          "text": "A bindings-compatible controller that manages a tree of objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTreeController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTreeController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTreeController"
        }
      ],
      "role": "symbol",
      "title": "NSTreeController",
      "type": "topic",
      "url": "/documentation/appkit/nstreecontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController": {
      "abstract": [
        {
          "text": "A controller that accesses user preference information for your app from the user’s defaults database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserDefaultsController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserDefaultsController"
        }
      ],
      "role": "symbol",
      "title": "NSUserDefaultsController",
      "type": "topic",
      "url": "/documentation/appkit/nsuserdefaultscontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewController": {
      "abstract": [
        {
          "text": "A controller that manages a view, typically loaded from a nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewController"
        }
      ],
      "role": "symbol",
      "title": "NSViewController",
      "type": "topic",
      "url": "/documentation/appkit/nsviewcontroller"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSArrayController",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewItem",
        "doc://com.apple.appkit/documentation/AppKit/NSController",
        "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
        "doc://com.apple.appkit/documentation/AppKit/NSObjectController",
        "doc://com.apple.appkit/documentation/AppKit/NSPageController",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitViewController",
        "doc://com.apple.appkit/documentation/AppKit/NSTabViewController",
        "doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController",
        "doc://com.apple.appkit/documentation/AppKit/NSTreeController",
        "doc://com.apple.appkit/documentation/AppKit/NSUserDefaultsController",
        "doc://com.apple.appkit/documentation/AppKit/NSViewController"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Object-Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration"
      ],
      "title": "Object Editing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditing()",
        "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditing(withDelegate:didCommit:contextInfo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditingWithoutPresentingError()",
        "doc://com.apple.appkit/documentation/AppKit/NSEditor/discardEditing()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEditor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditing()",
                "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditing(withDelegate:didCommit:contextInfo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSEditor/commitEditingWithoutPresentingError()",
                "doc://com.apple.appkit/documentation/AppKit/NSEditor/discardEditing()"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSController",
                "doc://com.apple.appkit/documentation/AppKit/NSViewController"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Object-Editing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration"
              ],
              "title": "Object Editing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSEditor"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController/title",
          "value": "NSPageController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSController/title",
          "value": "NSController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTreeController/title",
          "value": "NSTreeController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTreeController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTreeController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTreeController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTreeController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/title",
          "value": "NSArrayController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSArrayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSArrayController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSArrayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor~1discardEditing()/title",
          "value": "discardEditing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor~1discardEditing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "discardEditing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/title",
          "value": "NSEditorRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditorRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditorRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabViewController/title",
          "value": "NSTabViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewController/title",
          "value": "NSSplitViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController/title",
          "value": "NSUserDefaultsController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserDefaultsController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserDefaultsController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserDefaultsController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewController/title",
          "value": "NSViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/title",
          "value": "NSDictionaryController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewItem/title",
          "value": "NSCollectionViewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor~1commitEditing()/title",
          "value": "commitEditing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor~1commitEditing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "commitEditing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor/title",
          "value": "NSEditor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSObjectController/title",
          "value": "NSObjectController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSObjectController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSObjectController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSObjectController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSObjectController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController/title",
          "value": "NSTitlebarAccessoryViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarAccessoryViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTitlebarAccessoryViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor~1commitEditingWithoutPresentingError()/title",
          "value": "commitEditingAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor~1commitEditingWithoutPresentingError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "commitEditingAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor~1commitEditing(withDelegate:didCommit:contextInfo:)/title",
          "value": "commitEditingWithDelegate:didCommitSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditor~1commitEditing(withDelegate:didCommit:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "commitEditingWithDelegate:didCommitSelector:contextInfo:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nseditor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nseditor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
