{
  "abstract": [
    {
      "text": "Represents the eraser end of a stylus-like pointing device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEraserPointingDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSEraserPointingDevice",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSEraserPointingDevice"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEraserPointingDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSEraserPointingDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSPointingDeviceType",
              "text": "NSPointingDeviceType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSEraserPointingDevice"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorPointingDevice": {
      "abstract": [
        {
          "text": "Represents a cursor (or puck-like) pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorPointingDevice"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorPointingDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorPointingDevice",
      "type": "topic",
      "url": "/documentation/appkit/nscursorpointingdevice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEraserPointingDevice": {
      "abstract": [
        {
          "text": "Represents the eraser end of a stylus-like pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSEraserPointingDevice"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEraserPointingDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEraserPointingDevice",
      "type": "topic",
      "url": "/documentation/appkit/nseraserpointingdevice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum": {
      "abstract": [
        {
          "text": "The pointing-device types for tablet-proximity events or mouse events with a proximity event subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PointingDeviceType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/PointingDeviceType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PointingDeviceType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.PointingDeviceType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/pointingdevicetype-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPenPointingDevice": {
      "abstract": [
        {
          "text": "Represents the tip end of a stylus-like pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPenPointingDevice"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPenPointingDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPenPointingDevice",
      "type": "topic",
      "url": "/documentation/appkit/nspenpointingdevice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnknownPointingDevice": {
      "abstract": [
        {
          "text": "Represents an unknown type of pointing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnknownPointingDevice"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnknownPointingDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnknownPointingDevice",
      "type": "topic",
      "url": "/documentation/appkit/nsunknownpointingdevice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursorPointingDevice",
        "doc://com.apple.appkit/documentation/AppKit/NSPenPointingDevice",
        "doc://com.apple.appkit/documentation/AppKit/NSUnknownPointingDevice"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/title",
          "value": "NSPointingDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1PointingDeviceType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPointingDeviceType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nseraserpointingdevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
