{
  "abstract": [
    {
      "text": "The mode set when tracking events modally, such as a mouse-dragging loop.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEventTrackingRunLoopMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSEventTrackingRunLoopMode",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSEventTrackingRunLoopMode"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEventTrackingRunLoopMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSEventTrackingRunLoopMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRunLoopMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRunLoopMode",
              "text": "NSRunLoopMode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSEventTrackingRunLoopMode"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentEvent": {
      "abstract": [
        {
          "text": "The last event object that the app retrieved from the event queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentEvent"
        }
      ],
      "role": "symbol",
      "title": "currentEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/currentevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/discardEvents(matching:before:)": {
      "abstract": [
        {
          "text": "Removes all events matching the given mask and generated before the specified event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discardEvents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventMask",
          "text": "EventTypeMask"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "before"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/discardEvents(matching:before:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discardEventsMatchingMask:beforeEvent:"
        }
      ],
      "role": "symbol",
      "title": "discardEvents(matching:before:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/discardevents(matching:before:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/finishLaunching()": {
      "abstract": [
        {
          "text": "Activates the app, opens any files specified by the ",
          "type": "text"
        },
        {
          "code": "NSOpen",
          "type": "codeVoice"
        },
        {
          "text": " user default, and unhighlights the app’s icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishLaunching"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/finishLaunching()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishLaunching"
        }
      ],
      "role": "symbol",
      "title": "finishLaunching()",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/finishlaunching()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/isRunning": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the main event loop is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/isRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "running"
        }
      ],
      "role": "symbol",
      "title": "isRunning",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/isrunning"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/nextEvent(matching:until:inMode:dequeue:)": {
      "abstract": [
        {
          "text": "Returns the next event matching a given mask, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if no such event is found before a specified expiration date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventMask",
          "text": "EventTypeMask"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "until"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "inMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRunLoop",
          "text": "RunLoop"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRunLoopMode",
          "text": "Mode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dequeue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/nextEvent(matching:until:inMode:dequeue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextEventMatchingMask:untilDate:inMode:dequeue:"
        }
      ],
      "role": "symbol",
      "title": "nextEvent(matching:until:inMode:dequeue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/nextevent(matching:until:inmode:dequeue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/postEvent(_:atStart:)": {
      "abstract": [
        {
          "text": "Adds a given event to the receiver’s event queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/postEvent(_:atStart:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postEvent:atStart:"
        }
      ],
      "role": "symbol",
      "title": "postEvent(_:atStart:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/postevent(_:atstart:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/run()": {
      "abstract": [
        {
          "text": "Starts the main event loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "run"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/run()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "run"
        }
      ],
      "role": "symbol",
      "title": "run()",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/run()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/sendEvent(_:)": {
      "abstract": [
        {
          "text": "Dispatches an event to other objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/sendEvent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendEvent:"
        }
      ],
      "role": "symbol",
      "title": "sendEvent(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/sendevent(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/stop(_:)": {
      "abstract": [
        {
          "text": "Stops the main event loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/stop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stop:"
        }
      ],
      "role": "symbol",
      "title": "stop(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/stop(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEventTrackingRunLoopMode": {
      "abstract": [
        {
          "text": "The mode set when tracking events modally, such as a mouse-dragging loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSEventTrackingRunLoopMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEventTrackingRunLoopMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEventTrackingRunLoopMode",
      "type": "topic",
      "url": "/documentation/appkit/nseventtrackingrunloopmode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRunLoopMode": {
      "abstract": [
        {
          "text": "Modes that a run loop operates in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "RunLoop.Mode"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRunLoopMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "RunLoop.Mode",
      "type": "topic",
      "url": "/documentation/foundation/runloop/mode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Event-Loop",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/nextEvent(matching:until:inMode:dequeue:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/discardEvents(matching:before:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/isRunning",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/run()",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/finishLaunching()",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/stop(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/sendEvent(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/postEvent(_:atStart:)"
      ],
      "title": "Managing the Event Loop"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1stop(_:)/title",
          "value": "stop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1stop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1finishLaunching()/title",
          "value": "finishLaunching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1finishLaunching()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLaunching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1postEvent(_:atStart:)/title",
          "value": "postEvent:atStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1postEvent(_:atStart:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "postEvent:atStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSRunLoopMode/title",
          "value": "NSRunLoopMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1isRunning/title",
          "value": "running"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1isRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "running"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1discardEvents(matching:before:)/title",
          "value": "discardEventsMatchingMask:beforeEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1discardEvents(matching:before:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "discardEventsMatchingMask:beforeEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1sendEvent(_:)/title",
          "value": "sendEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1sendEvent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1nextEvent(matching:until:inMode:dequeue:)/title",
          "value": "nextEventMatchingMask:untilDate:inMode:dequeue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1nextEvent(matching:until:inMode:dequeue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "nextEventMatchingMask:untilDate:inMode:dequeue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1run()/title",
          "value": "run"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1run()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "run"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1currentEvent/title",
          "value": "currentEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1currentEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nseventtrackingrunloopmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
