{
  "abstract": [
    {
      "text": "Specifies the even-odd winding rule.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum/evenOdd",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvenOddWindingRule"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSEvenOddWindingRule",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSEvenOddWindingRule"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEvenOddWindingRule"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSEvenOddWindingRule"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSWindingRule",
              "text": "NSWindingRule"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSEvenOddWindingRule"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Count the total number of path crossings. If the number of crossings is even, the point is outside the path. If the number of crossings is odd, the point is inside the path and the region that contains it is filled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the winding rule a Bézier path uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WindingRule"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WindingRule"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.WindingRule",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/windingrule-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum/evenOdd": {
      "abstract": [
        {
          "text": "Specifies the even-odd winding rule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evenOdd"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum/evenOdd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindingRuleEvenOdd"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.WindingRule.evenOdd",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/windingrule-swift.enum/evenodd"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvenOddWindingRule": {
      "abstract": [
        {
          "text": "Specifies the even-odd winding rule.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSEvenOddWindingRule"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvenOddWindingRule",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEvenOddWindingRule",
      "type": "topic",
      "url": "/documentation/appkit/nsevenoddwindingrule"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNonZeroWindingRule": {
      "abstract": [
        {
          "text": "Specifies the non-zero winding rule.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNonZeroWindingRule"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNonZeroWindingRule",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNonZeroWindingRule",
      "type": "topic",
      "url": "/documentation/appkit/nsnonzerowindingrule"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSNonZeroWindingRule"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum~1evenOdd/title",
          "value": "NSWindingRuleEvenOdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum~1evenOdd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindingRuleEvenOdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/title",
          "value": "NSWindingRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindingRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindingRule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevenoddwindingrule"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
