{
  "abstract": [
    {
      "text": "The F30 key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSF30FunctionKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSUpArrowFunctionKey@NSF30FunctionKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSF30FunctionKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSF30FunctionKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSF30FunctionKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSF30FunctionKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is unavailable on most Macintosh keyboards.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF10FunctionKey": {
      "abstract": [
        {
          "text": "The F10 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF10FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF10FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF10FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF10FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf10functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF11FunctionKey": {
      "abstract": [
        {
          "text": "The F11 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF11FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF11FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF11FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF11FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf11functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF12FunctionKey": {
      "abstract": [
        {
          "text": "The F12 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF12FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF12FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF12FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF12FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf12functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF13FunctionKey": {
      "abstract": [
        {
          "text": "The F13 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF13FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF13FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF13FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF13FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf13functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF14FunctionKey": {
      "abstract": [
        {
          "text": "The F14 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF14FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF14FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF14FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF14FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf14functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF15FunctionKey": {
      "abstract": [
        {
          "text": "The F15 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF15FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF15FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF15FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF15FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf15functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF1FunctionKey": {
      "abstract": [
        {
          "text": "The F1 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF1FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF1FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF1FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF1FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf1functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF2FunctionKey": {
      "abstract": [
        {
          "text": "The F2 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF2FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF2FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF2FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF2FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf2functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF30FunctionKey": {
      "abstract": [
        {
          "text": "The F30 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF30FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF30FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF30FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF30FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf30functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF3FunctionKey": {
      "abstract": [
        {
          "text": "The F3 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF3FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF3FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF3FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF3FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf3functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF4FunctionKey": {
      "abstract": [
        {
          "text": "The F4 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF4FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF4FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF4FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF4FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf4functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF5FunctionKey": {
      "abstract": [
        {
          "text": "The F5 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF5FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF5FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF5FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF5FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf5functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF6FunctionKey": {
      "abstract": [
        {
          "text": "The F6 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF6FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF6FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF6FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF6FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf6functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF7FunctionKey": {
      "abstract": [
        {
          "text": "The F7 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF7FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF7FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF7FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF7FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf7functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF8FunctionKey": {
      "abstract": [
        {
          "text": "The F8 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF8FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF8FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF8FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF8FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf8functionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSF9FunctionKey": {
      "abstract": [
        {
          "text": "The F9 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSF9FunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSF9FunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSF9FunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSF9FunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsf9functionkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Function-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSF1FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF2FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF3FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF4FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF5FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF6FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF7FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF8FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF9FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF10FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF11FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF12FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF13FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF14FunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSF15FunctionKey"
      ],
      "title": "Getting the Function Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSF30FunctionKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF30FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Function-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSF1FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF2FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF3FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF4FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF5FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF6FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF7FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF8FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF9FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF10FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF11FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF12FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF13FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF14FunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSF15FunctionKey"
              ],
              "title": "Getting the Function Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSF30FunctionKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF3FunctionKey/title",
          "value": "NSF3FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF3FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF3FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF11FunctionKey/title",
          "value": "NSF11FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF11FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF11FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF4FunctionKey/title",
          "value": "NSF4FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF4FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF4FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF8FunctionKey/title",
          "value": "NSF8FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF8FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF8FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF1FunctionKey/title",
          "value": "NSF1FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF1FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF1FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF10FunctionKey/title",
          "value": "NSF10FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF10FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF10FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF13FunctionKey/title",
          "value": "NSF13FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF13FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF13FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF30FunctionKey/title",
          "value": "NSF30FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF30FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF30FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF2FunctionKey/title",
          "value": "NSF2FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF2FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF2FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF6FunctionKey/title",
          "value": "NSF6FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF6FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF6FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF14FunctionKey/title",
          "value": "NSF14FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF14FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF14FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF9FunctionKey/title",
          "value": "NSF9FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF9FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF9FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF5FunctionKey/title",
          "value": "NSF5FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF5FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF5FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF7FunctionKey/title",
          "value": "NSF7FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF7FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF7FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF12FunctionKey/title",
          "value": "NSF12FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF12FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF12FunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF15FunctionKey/title",
          "value": "NSF15FunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSF15FunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSF15FunctionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsf30functionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsf30functionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
