{
  "abstract": [
    {
      "text": "A set of methods that provides the name of the promised file and writes the file to the destination directory when the file promise is fulfilled.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSFilePromiseProviderDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFilePromiseProviderDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFilePromiseProviderDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSFilePromiseProviderDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFilePromiseProviderDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProvider": {
      "abstract": [
        {
          "text": "An object that provides a promise for the pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFilePromiseProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFilePromiseProvider"
        }
      ],
      "role": "symbol",
      "title": "NSFilePromiseProvider",
      "type": "topic",
      "url": "/documentation/appkit/nsfilepromiseprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate": {
      "abstract": [
        {
          "text": "A set of methods that provides the name of the promised file and writes the file to the destination directory when the file promise is fulfilled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFilePromiseProviderDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFilePromiseProviderDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSFilePromiseProviderDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsfilepromiseproviderdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/filePromiseProvider(_:fileNameForType:)": {
      "abstract": [
        {
          "text": "Provides the drag destination file’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filePromiseProvider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFilePromiseProvider",
          "text": "NSFilePromiseProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fileNameForType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/filePromiseProvider(_:fileNameForType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filePromiseProvider:fileNameForType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "filePromiseProvider(_:fileNameForType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfilepromiseproviderdelegate/filepromiseprovider(_:filenamefortype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/filePromiseProvider(_:writePromiseTo:completionHandler:)": {
      "abstract": [
        {
          "text": "Writes the contents of a promise to the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filePromiseProvider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFilePromiseProvider",
          "text": "NSFilePromiseProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "writePromiseTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/filePromiseProvider(_:writePromiseTo:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filePromiseProvider:writePromiseToURL:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "filePromiseProvider(_:writePromiseTo:completionHandler:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfilepromiseproviderdelegate/filepromiseprovider(_:writepromiseto:completionhandler:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/operationQueue(for:)": {
      "abstract": [
        {
          "text": "Returns the operation queue from which to issue the write request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFilePromiseProvider",
          "text": "NSFilePromiseProvider"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOperationQueue",
          "text": "OperationQueue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/operationQueue(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "operationQueueForFilePromiseProvider:"
        }
      ],
      "role": "symbol",
      "title": "operationQueue(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfilepromiseproviderdelegate/operationqueue(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseReceiver": {
      "abstract": [
        {
          "text": "An object that receives a file promise from the pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFilePromiseReceiver"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseReceiver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFilePromiseReceiver"
        }
      ],
      "role": "symbol",
      "title": "NSFilePromiseReceiver",
      "type": "topic",
      "url": "/documentation/appkit/nsfilepromisereceiver"
    },
    "doc://com.apple.appkit/documentation/AppKit/supporting-collection-view-drag-and-drop-through-file-promises": {
      "abstract": [
        {
          "text": "Share data between macOS apps during drag and drop by using an item provider.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/supporting-collection-view-drag-and-drop-through-file-promises",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Collection View Drag and Drop Through File Promises",
      "type": "topic",
      "url": "/documentation/appkit/supporting-collection-view-drag-and-drop-through-file-promises"
    },
    "doc://com.apple.appkit/documentation/AppKit/supporting-drag-and-drop-through-file-promises": {
      "abstract": [
        {
          "text": "Receive and provide file promises to support dragged app files and pasteboard operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/supporting-drag-and-drop-through-file-promises",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Drag and Drop Through File Promises",
      "type": "topic",
      "url": "/documentation/appkit/supporting-drag-and-drop-through-file-promises"
    },
    "doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises": {
      "abstract": [
        {
          "text": "Share data between macOS apps during drag and drop by using an item provider.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Table View Drag and Drop Through File Promises",
      "type": "topic",
      "url": "/documentation/appkit/supporting-table-view-drag-and-drop-through-file-promises"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-Promises",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/supporting-drag-and-drop-through-file-promises",
        "doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises",
        "doc://com.apple.appkit/documentation/AppKit/supporting-collection-view-drag-and-drop-through-file-promises",
        "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProvider",
        "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseReceiver"
      ],
      "title": "File Promises"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-File-Promises",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/filePromiseProvider(_:fileNameForType:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/filePromiseProvider(_:writePromiseTo:completionHandler:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/operationQueue(for:)"
      ],
      "title": "Handling File Promises"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFilePromiseProviderDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilePromiseProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilePromiseProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-File-Promises",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/filePromiseProvider(_:fileNameForType:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/filePromiseProvider(_:writePromiseTo:completionHandler:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProviderDelegate/operationQueue(for:)"
              ],
              "title": "Handling File Promises"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-Promises",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/supporting-drag-and-drop-through-file-promises",
                "doc://com.apple.appkit/documentation/AppKit/supporting-table-view-drag-and-drop-through-file-promises",
                "doc://com.apple.appkit/documentation/AppKit/supporting-collection-view-drag-and-drop-through-file-promises",
                "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseProvider",
                "doc://com.apple.appkit/documentation/AppKit/NSFilePromiseReceiver"
              ],
              "title": "File Promises"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFilePromiseProviderDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate~1filePromiseProvider(_:fileNameForType:)/title",
          "value": "filePromiseProvider:fileNameForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate~1filePromiseProvider(_:fileNameForType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "filePromiseProvider:fileNameForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate~1operationQueue(for:)/title",
          "value": "operationQueueForFilePromiseProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate~1operationQueue(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "operationQueueForFilePromiseProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseReceiver/title",
          "value": "NSFilePromiseReceiver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseReceiver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilePromiseReceiver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseReceiver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilePromiseReceiver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProvider/title",
          "value": "NSFilePromiseProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilePromiseProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilePromiseProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate/title",
          "value": "NSFilePromiseProviderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilePromiseProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilePromiseProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate~1filePromiseProvider(_:writePromiseTo:completionHandler:)/title",
          "value": "filePromiseProvider:writePromiseToURL:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFilePromiseProviderDelegate~1filePromiseProvider(_:writePromiseTo:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "filePromiseProvider:writePromiseToURL:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfilepromiseproviderdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfilepromiseproviderdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
