{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "code": "NSFormCell",
      "type": "codeVoice"
    },
    {
      "text": " class is used to implement text entry fields in a form. The left part of an ",
      "type": "text"
    },
    {
      "code": "NSFormCell",
      "type": "codeVoice"
    },
    {
      "text": " object contains a title. The right part contains an editable text entry field.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFormCell"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSFormCell",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFormCell"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFormCell"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSFormCell"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "NSFormCell",
              "type": "codeVoice"
            },
            {
              "text": " object implements the user interface of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSForm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityelementprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSActionCell": {
      "abstract": [
        {
          "text": "An active area inside a control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSActionCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSActionCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSActionCell"
        }
      ],
      "role": "symbol",
      "title": "NSActionCell",
      "type": "topic",
      "url": "/documentation/appkit/nsactioncell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep": {
      "abstract": [
        {
          "text": "An object that stores image data in a form that can be readily transferred to the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCachedImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCachedImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nscachedimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawer": {
      "abstract": [
        {
          "text": "A user interface element that contains and displays text, scroll, and browser views, in addition to other view subclasses.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawer"
        }
      ],
      "role": "symbol",
      "title": "NSDrawer",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSForm": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSForm",
          "type": "codeVoice"
        },
        {
          "text": " object is a vertical matrix of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects to implement the fields.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSForm"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSForm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSForm"
        }
      ],
      "role": "symbol",
      "title": "NSForm",
      "type": "topic",
      "url": "/documentation/appkit/nsform"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSFormCell",
          "type": "codeVoice"
        },
        {
          "text": " class is used to implement text entry fields in a form. The left part of an ",
          "type": "text"
        },
        {
          "code": "NSFormCell",
          "type": "codeVoice"
        },
        {
          "text": " object contains a title. The right part contains an editable text entry field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFormCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFormCell"
        }
      ],
      "role": "symbol",
      "title": "NSFormCell",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/attributedTitle": {
      "abstract": [
        {
          "text": "The title of the cell as an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/attributedTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedTitle"
        }
      ],
      "role": "symbol",
      "title": "attributedTitle",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/attributedtitle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/init(coder:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/init(coder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/init(textCell:)": {
      "abstract": [
        {
          "text": "Returns an ",
          "type": "text"
        },
        {
          "code": "NSFormCell",
          "type": "codeVoice"
        },
        {
          "text": " object initialized with the specified title string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "textCell"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/init(textCell:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initTextCell:"
        }
      ],
      "role": "symbol",
      "title": "init(textCell:)",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/init(textcell:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/isOpaque": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the title is empty and an opaque bezel is set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isOpaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/isOpaque",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opaque"
        }
      ],
      "role": "symbol",
      "title": "isOpaque",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/isopaque"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/placeholderAttributedString": {
      "abstract": [
        {
          "text": "The cell’s attributed placeholder string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderAttributedString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/placeholderAttributedString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderAttributedString"
        }
      ],
      "role": "symbol",
      "title": "placeholderAttributedString",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/placeholderattributedstring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/placeholderString": {
      "abstract": [
        {
          "text": "The cell’s plain text placeholder string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/placeholderString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderString"
        }
      ],
      "role": "symbol",
      "title": "placeholderString",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/placeholderstring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/preferredTextFieldWidth": {
      "abstract": [
        {
          "text": "The preferred text field width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTextFieldWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/preferredTextFieldWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredTextFieldWidth"
        }
      ],
      "role": "symbol",
      "title": "preferredTextFieldWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/preferredtextfieldwidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/setTitleWithMnemonic:": {
      "abstract": [
        {
          "text": "Sets the cell title and mnemonic character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleWithMnemonic:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/setTitleWithMnemonic:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleWithMnemonic:"
        }
      ],
      "role": "symbol",
      "title": "setTitleWithMnemonic:",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/settitlewithmnemonic:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/title": {
      "abstract": [
        {
          "text": "The cell’s title text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/title"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleAlignment": {
      "abstract": [
        {
          "text": "The alignment of the title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextAlignment",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleAlignment"
        }
      ],
      "role": "symbol",
      "title": "titleAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/titlealignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleBaseWritingDirection": {
      "abstract": [
        {
          "text": "The default writing direction used to render the form cell’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleBaseWritingDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWritingDirection",
          "text": "NSWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleBaseWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleBaseWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "titleBaseWritingDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/titlebasewritingdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleFont": {
      "abstract": [
        {
          "text": "The font used to draw cell’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleFont"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleFont"
        }
      ],
      "role": "symbol",
      "title": "titleFont",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/titlefont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleWidth": {
      "abstract": [
        {
          "text": "The width of the title field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleWidth"
        }
      ],
      "role": "symbol",
      "title": "titleWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/titlewidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleWidth(_:)": {
      "abstract": [
        {
          "text": "Returns the width of the title field constrained to the specified size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleWidth(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleWidth:"
        }
      ],
      "role": "symbol",
      "title": "titleWidth(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell/titlewidth(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInputManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInputManager",
      "type": "topic",
      "url": "/documentation/appkit/nsinputmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInputServer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInputServer",
      "type": "topic",
      "url": "/documentation/appkit/nsinputserver"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell": {
      "abstract": [
        {
          "text": "An object that handles the measurement and display of a single menu item in its encompassing frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItemCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItemCell"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItemCell",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMovie": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMovie"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMovie",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMovie",
      "type": "topic",
      "url": "/documentation/appkit/nsmovie"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext": {
      "abstract": [
        {
          "text": "An object that represents an OpenGL graphics context, into which all OpenGL calls are rendered.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLContext"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLContext",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer": {
      "abstract": [
        {
          "text": "A subclass of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that is suitable for rendering OpenGL into layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLLayer"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsopengllayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer": {
      "abstract": [
        {
          "text": "An object that provides access to accelerated offscreen rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLPixelBuffer",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelbuffer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat": {
      "abstract": [
        {
          "text": "An object that specifies the types of buffers and other attributes of the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLPixelFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView": {
      "abstract": [
        {
          "text": "A view that displays OpenGL content in a view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLView"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLView",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfaceitemidentification"
    },
    "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer": {
      "abstract": [
        {
          "text": "A layer that provides a layer suitable for rendering OpenGL content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAOpenGLLayer",
      "type": "topic",
      "url": "/documentation/QuartzCore/CAOpenGLLayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSActionCell"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
        "doc://com.apple.appkit/documentation/AppKit/NSForm",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/init(coder:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Initializing-an-NSFormCell",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/init(textCell:)"
      ],
      "title": "Initializing an NSFormCell"
    },
    {
      "anchor": "Asking-About-a-Cells-Appearance",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/isOpaque"
      ],
      "title": "Asking About a Cell’s Appearance"
    },
    {
      "anchor": "Accessing-a-Cells-Title",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/attributedTitle",
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/title",
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleBaseWritingDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleFont",
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleWidth"
      ],
      "title": "Accessing a Cell’s Title"
    },
    {
      "anchor": "Asking-About-Placeholder-Values",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/placeholderAttributedString",
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/placeholderString"
      ],
      "title": "Asking About Placeholder Values"
    },
    {
      "anchor": "Sizing-for-Auto-Layout",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/preferredTextFieldWidth"
      ],
      "title": "Sizing for Auto Layout"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleWidth(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFormCell"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/init(coder:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Initializing-an-NSFormCell",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/init(textCell:)"
              ],
              "title": "Initializing an NSFormCell"
            },
            {
              "anchor": "Asking-About-a-Cells-Appearance",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/isOpaque"
              ],
              "title": "Asking About a Cell’s Appearance"
            },
            {
              "anchor": "Accessing-a-Cells-Title",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/attributedTitle",
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/title",
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleAlignment",
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleBaseWritingDirection",
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleFont",
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleWidth"
              ],
              "title": "Accessing a Cell’s Title"
            },
            {
              "anchor": "Setting-a-Keyboard-Equivalent",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/setTitleWithMnemonic:"
              ],
              "title": "Setting a Keyboard Equivalent"
            },
            {
              "anchor": "Asking-About-Placeholder-Values",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/placeholderAttributedString",
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/placeholderString"
              ],
              "title": "Asking About Placeholder Values"
            },
            {
              "anchor": "Sizing-for-Auto-Layout",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/preferredTextFieldWidth"
              ],
              "title": "Sizing for Auto Layout"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell/titleWidth(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSActionCell"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
                "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
                "doc://com.apple.appkit/documentation/AppKit/NSForm",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell",
                "doc://com.apple.appkit/documentation/AppKit/NSInputManager",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServer",
                "doc://com.apple.appkit/documentation/AppKit/NSMovie"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFormCell"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSActionCell",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSActionCell",
                    "text": "NSActionCell"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/title",
          "value": "NSMenuItemCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/title",
          "value": "NSOpenGLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleAlignment/title",
          "value": "titleAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/title",
          "value": "NSForm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleFont/title",
          "value": "titleFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1attributedTitle/title",
          "value": "attributedTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1attributedTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributedTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/title",
          "value": "NSDrawer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1preferredTextFieldWidth/title",
          "value": "preferredTextFieldWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1preferredTextFieldWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredTextFieldWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/title",
          "value": "NSOpenGLView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/title",
          "value": "NSActionCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSActionCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSActionCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1QuartzCore~1CAOpenGLLayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAOpenGLLayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CALayer",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1isOpaque/title",
          "value": "opaque"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1isOpaque/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opaque"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1placeholderAttributedString/title",
          "value": "placeholderAttributedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1placeholderAttributedString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderAttributedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/title",
          "value": "NSFormCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleWidth(_:)/title",
          "value": "titleWidth:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleWidth(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "titleWidth:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/title",
          "value": "NSOpenGLContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleBaseWritingDirection/title",
          "value": "titleBaseWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleBaseWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleBaseWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/title",
          "value": "NSOpenGLLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleWidth/title",
          "value": "titleWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1titleWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1init(textCell:)/title",
          "value": "initTextCell:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1init(textCell:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initTextCell:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title",
          "value": "NSUserInterfaceItemIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1placeholderString/title",
          "value": "placeholderString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell~1placeholderString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsformcell"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsformcell"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
