{
  "abstract": [
    {
      "text": "The font rendering mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFontRenderingMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFontRenderingMode"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontRenderingMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSFontRenderingMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode": {
      "abstract": [
        {
          "text": "The font rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedIntegerAdvancementsRenderingMode": {
      "abstract": [
        {
          "text": "Specifies antialiased, integer advancements rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "antialiasedIntegerAdvancementsRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedIntegerAdvancementsRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAntialiasedIntegerAdvancementsRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode.antialiasedIntegerAdvancementsRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/antialiasedintegeradvancementsrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedRenderingMode": {
      "abstract": [
        {
          "text": "Specifies antialiased, floating-point advancements rendering mode (synonymous with printerFont).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "antialiasedRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAntialiasedRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode.antialiasedRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/antialiasedrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/defaultRenderingMode": {
      "abstract": [
        {
          "text": "Determines the actual mode based on the user preference settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/defaultRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDefaultRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode.defaultRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/defaultrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/integerAdvancementsRenderingMode": {
      "abstract": [
        {
          "text": "Specifies integer advancements rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integerAdvancementsRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/integerAdvancementsRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontIntegerAdvancementsRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode.integerAdvancementsRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/integeradvancementsrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyph": {
      "abstract": [
        {
          "text": "The type used to specify glyphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyph"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyph"
        }
      ],
      "role": "symbol",
      "title": "NSGlyph",
      "type": "topic",
      "url": "/documentation/appkit/nsglyph"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator": {
      "abstract": [
        {
          "text": "An object that performs the initial, nominal glyph generation phase in the layout process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphGenerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphGenerator"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphGenerator",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphgenerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo": {
      "abstract": [
        {
          "text": "A glyph attribute in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphInfo"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage": {
      "abstract": [
        {
          "text": "A set of methods that a glyph storage object must implement to interact properly with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphStorage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphStorage"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphStorage",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphstorage"
    },
    "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes": {
      "abstract": [
        {
          "text": "These constants define reserved glyph codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Glyph Codes",
      "type": "topic",
      "url": "/documentation/appkit/reserved-glyph-codes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Glyphs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGlyph",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
        "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes"
      ],
      "title": "Glyphs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/defaultRenderingMode",
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedRenderingMode",
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/integerAdvancementsRenderingMode",
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedIntegerAdvancementsRenderingMode"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontRenderingMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/defaultRenderingMode",
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedRenderingMode",
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/integerAdvancementsRenderingMode",
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedIntegerAdvancementsRenderingMode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Glyphs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGlyph",
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage",
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
                "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes"
              ],
              "title": "Glyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontRenderingMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1integerAdvancementsRenderingMode/title",
          "value": "NSFontIntegerAdvancementsRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1integerAdvancementsRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontIntegerAdvancementsRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/title",
          "value": "NSGlyph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/title",
          "value": "NSGlyphInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1antialiasedRenderingMode/title",
          "value": "NSFontAntialiasedRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1antialiasedRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAntialiasedRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1antialiasedIntegerAdvancementsRenderingMode/title",
          "value": "NSFontAntialiasedIntegerAdvancementsRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1antialiasedIntegerAdvancementsRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAntialiasedIntegerAdvancementsRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1defaultRenderingMode/title",
          "value": "NSFontDefaultRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1defaultRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDefaultRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/title",
          "value": "NSFontRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/title",
          "value": "NSGlyphStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/title",
          "value": "NSGlyphGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphGenerator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontrenderingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontrenderingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
