{
  "abstract": [
    {
      "text": "A set of methods you use to tell the Font panel to display some or all of its elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsfontpanelvalidation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "title": "NSFontPanelValidation"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontChanging": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontChanging"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontChanging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontChanging"
        }
      ],
      "role": "symbol",
      "title": "NSFontChanging",
      "type": "topic",
      "url": "/documentation/appkit/nsfontchanging"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel": {
      "abstract": [
        {
          "text": "The Font panel—a user interface object that displays a list of available fonts, letting the user preview them and change the font used to display text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanel"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanel.ModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/mode-masks": {
      "abstract": [
        {
          "text": "The following constants correspond to the available font panel mode masks returned by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1534415-validmodesforfontpanel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/mode-masks",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mode Masks",
      "type": "topic",
      "url": "/documentation/appkit/mode-masks"
    },
    "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens": {
      "abstract": [
        {
          "text": "Organize your view hierarchies and facilitate their display onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows, Panels, and Screens",
      "type": "topic",
      "url": "/documentation/appkit/windows-panels-and-screens"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1534415-validmodesforfontpanel": {
      "abstract": [
        {
          "text": "Returns the mode mask corresponding to the expected font panel mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1534415-validmodesforfontpanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "validModesForFontPanel:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1534415-validmodesforfontpanel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009459": {
      "identifier": "https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009459",
      "title": "Cocoa Text Architecture Guide",
      "titleInlineContent": [
        {
          "text": "Cocoa Text Architecture Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009459"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009459"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Font-Panels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontChanging"
      ],
      "title": "Font Panels"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/mode-masks"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Validating-Modes-for-a-Font-Panel",
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1534415-validmodesforfontpanel"
              ],
              "title": "Validating Modes for a Font Panel"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/mode-masks"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009459"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Font-Panels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontChanging"
              ],
              "title": "Font Panels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontChanging/title",
          "value": "NSFontChanging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontChanging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontChanging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontChanging/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontChanging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask/title",
          "value": "NSFontPanelModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/title",
          "value": "NSFontPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontpanelvalidation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontpanelvalidation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
