{
  "abstract": [
    {
      "text": "A font where the style is among those typefaces designed to simulate handwriting.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontScriptsClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSFontUnknownClass@NSFontScriptsClass",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFontScriptsClass"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontScriptsClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSFontScriptsClass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFontScriptsClass"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontClarendonSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is a variation of the Oldstyle Serifs and the Transitional Serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontClarendonSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontClarendonSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontClarendonSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontClarendonSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontclarendonserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontFreeformSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style includes serifs, but it expresses a design freedom that does not generally fit within the other serif design classifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontFreeformSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFreeformSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFreeformSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontFreeformSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontfreeformserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontModernSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is based on the Latin printing style of the 20th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontModernSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontModernSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontModernSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontModernSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmodernserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontOldStyleSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is based on the Latin printing style of the 15th to 17th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontOldStyleSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontOldStyleSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontOldStyleSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontOldStyleSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontoldstyleserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontOrnamentalsClass": {
      "abstract": [
        {
          "text": "A font where the style includes highly decorated or stylized character shapes such as those typically used in headlines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontOrnamentalsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontOrnamentalsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontOrnamentalsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontOrnamentalsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontornamentalsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSansSerifClass": {
      "abstract": [
        {
          "text": "A font where the style includes most basic letter forms (excluding Scripts and Ornamentals) that do not have serifs on the strokes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSansSerifClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSansSerifClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSansSerifClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontSansSerifClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontsansserifclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontScriptsClass": {
      "abstract": [
        {
          "text": "A font where the style is among those typefaces designed to simulate handwriting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontScriptsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontScriptsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontScriptsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontScriptsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontscriptsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSlabSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is characterized by serifs with a square transition between the strokes and the serifs (no brackets).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSlabSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSlabSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSlabSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontSlabSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontslabserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicClass": {
      "abstract": [
        {
          "text": "A font where the style is generally design independent, making it suitable for special characters (icons, dingbats, technical symbols, and so on) that may be used equally well with any font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSymbolicClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSymbolicClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontSymbolicClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontsymbolicclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTransitionalSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is based on the Latin printing style of the 18th to 19th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontTransitionalSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTransitionalSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTransitionalSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontTransitionalSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttransitionalserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontUnknownClass": {
      "abstract": [
        {
          "text": "A font with no design classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontUnknownClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontUnknownClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontUnknownClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontUnknownClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontunknownclass"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontUnknownClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontOldStyleSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTransitionalSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontModernSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontClarendonSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSlabSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontFreeformSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSansSerifClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontOrnamentalsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicClass"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontScriptsClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontScriptsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontUnknownClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontOldStyleSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTransitionalSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontModernSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontClarendonSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSlabSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontFreeformSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSansSerifClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontOrnamentalsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicClass"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFontScriptsClass"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontUnknownClass/title",
          "value": "NSFontUnknownClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontUnknownClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontUnknownClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontOldStyleSerifsClass/title",
          "value": "NSFontOldStyleSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontOldStyleSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontOldStyleSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSansSerifClass/title",
          "value": "NSFontSansSerifClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSansSerifClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSansSerifClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicClass/title",
          "value": "NSFontSymbolicClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontScriptsClass/title",
          "value": "NSFontScriptsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontScriptsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontScriptsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontOrnamentalsClass/title",
          "value": "NSFontOrnamentalsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontOrnamentalsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontOrnamentalsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSlabSerifsClass/title",
          "value": "NSFontSlabSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSlabSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSlabSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTransitionalSerifsClass/title",
          "value": "NSFontTransitionalSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTransitionalSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTransitionalSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFreeformSerifsClass/title",
          "value": "NSFontFreeformSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFreeformSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFreeformSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontClarendonSerifsClass/title",
          "value": "NSFontClarendonSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontClarendonSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontClarendonSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontModernSerifsClass/title",
          "value": "NSFontModernSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontModernSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontModernSerifsClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontscriptsclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontscriptsclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
