{
  "abstract": [
    {
      "text": "A dictionary of attributes that describe a font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSFontDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFontDescriptor"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSFontDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A font descriptor can be used to create or modify an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The system provides a font matching capability, so that you can partially describe a font by creating a font descriptor with, for example, just a family name. You can then find all the available fonts on the system with a matching family name using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptors(withMandatoryKeys:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are several ways to create a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. You can use ",
              "type": "text"
            },
            {
              "code": "alloc",
              "type": "codeVoice"
            },
            {
              "text": " and  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(fontAttributes:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/fontDescriptorWithFontAttributes:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:matrix:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:size:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". to create a font descriptor based on either your custom attributes dictionary or on a specific font’s name and size. Alternatively you can use one of the ",
              "type": "text"
            },
            {
              "code": "fontDescriptor…",
              "type": "codeVoice"
            },
            {
              "text": " instance methods (such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFace(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") to create a modified version of an existing descriptor. The latter methods are useful if you have an existing descriptor and simply want to change one aspect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "All attributes in the attributes dictionary are optional.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont": {
      "abstract": [
        {
          "text": "The representation of a font in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "role": "symbol",
      "title": "NSFont",
      "type": "topic",
      "url": "/documentation/appkit/nsfont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontAssetRequest"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAssetRequest"
        }
      ],
      "role": "symbol",
      "title": "NSFontAssetRequest",
      "type": "topic",
      "url": "/documentation/appkit/nsfontassetrequest"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor": {
      "abstract": [
        {
          "text": "A dictionary of attributes that describe a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName": {
      "abstract": [
        {
          "text": "Constants for the names of font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttributeName"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.AttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/attributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/FeatureKey": {
      "abstract": [
        {
          "text": "Constants to use as keys to retrieve information about a font descriptor from its feature dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FeatureKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/FeatureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FeatureKey"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.FeatureKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/featurekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct": {
      "abstract": [
        {
          "text": "A symbolic description of the stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.SymbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SystemDesign": {
      "abstract": [
        {
          "text": "Constants for font designs, such as monospace, rounded, and serif.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemDesign"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SystemDesign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemDesign"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.SystemDesign",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/systemdesign"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey": {
      "abstract": [
        {
          "text": "Constants that can be used as keys to retrieve information about a font descriptor from its trait dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TraitKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TraitKey"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.TraitKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/traitkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/VariationKey": {
      "abstract": [
        {
          "text": "Constants that can be used as keys to retrieve information about a font descriptor from its variation axis dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VariationKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/VariationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VariationKey"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.VariationKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/variationkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/addingAttributes(_:)": {
      "abstract": [
        {
          "text": "Returns a new font descriptor based on the current object, but with the specified attributes taking precedence over the existing ones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addingAttributes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/addingAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorByAddingAttributes:"
        }
      ],
      "role": "symbol",
      "title": "addingAttributes(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/addingattributes(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/fontAttributes": {
      "abstract": [
        {
          "text": "The receiver’s dictionary of attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/fontAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontAttributes"
        }
      ],
      "role": "symbol",
      "title": "fontAttributes",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/fontattributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/fontDescriptorWithFontAttributes:": {
      "abstract": [
        {
          "text": "Returns a font descriptor with a dictionary of attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fontDescriptorWithFontAttributes:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/fontDescriptorWithFontAttributes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithFontAttributes:"
        }
      ],
      "role": "symbol",
      "title": "fontDescriptorWithFontAttributes:",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/fontdescriptorwithfontattributes:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(fontAttributes:)": {
      "abstract": [
        {
          "text": "Initializes and returns a new font descriptor with the specified attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fontAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(fontAttributes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFontAttributes:"
        }
      ],
      "role": "symbol",
      "title": "init(fontAttributes:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/init(fontattributes:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:matrix:)": {
      "abstract": [
        {
          "text": "Returns a font descriptor with the name and matrix attributes set to the given values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "matrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation15AffineTransformV",
          "text": "AffineTransform"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:matrix:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithName:matrix:"
        }
      ],
      "role": "symbol",
      "title": "init(name:matrix:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/init(name:matrix:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:size:)": {
      "abstract": [
        {
          "text": "Returns a font descriptor with the name and size attributes set to the given values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:size:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithName:size:"
        }
      ],
      "role": "symbol",
      "title": "init(name:size:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/init(name:size:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptor(withMandatoryKeys:)": {
      "abstract": [
        {
          "text": "Returns a normalized font descriptor whose specified attributes match those of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingFontDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMandatoryKeys"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptor(withMandatoryKeys:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchingFontDescriptorWithMandatoryKeys:"
        }
      ],
      "role": "symbol",
      "title": "matchingFontDescriptor(withMandatoryKeys:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/matchingfontdescriptor(withmandatorykeys:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptors(withMandatoryKeys:)": {
      "abstract": [
        {
          "text": "Returns all the fonts available on the system whose specified attributes match those of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingFontDescriptors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMandatoryKeys"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        },
        {
          "kind": "text",
          "text": ">?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptors(withMandatoryKeys:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchingFontDescriptorsWithMandatoryKeys:"
        }
      ],
      "role": "symbol",
      "title": "matchingFontDescriptors(withMandatoryKeys:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/matchingfontdescriptors(withmandatorykeys:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matrix": {
      "abstract": [
        {
          "text": "The current transform matrix of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation15AffineTransformV",
          "text": "AffineTransform"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matrix"
        }
      ],
      "role": "symbol",
      "title": "matrix",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/matrix"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/object(forKey:)": {
      "abstract": [
        {
          "text": "Returns the font attribute specified by the given key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorAttributeName",
          "text": "AttributeName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/object(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKey:"
        }
      ],
      "role": "symbol",
      "title": "object(forKey:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/object(forkey:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/pointSize": {
      "abstract": [
        {
          "text": "The point size of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/pointSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointSize"
        }
      ],
      "role": "symbol",
      "title": "pointSize",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/pointsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/postscriptName": {
      "abstract": [
        {
          "text": "The PostScript name of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postscriptName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/postscriptName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postscriptName"
        }
      ],
      "role": "symbol",
      "title": "postscriptName",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/postscriptname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/preferredFontDescriptor(forTextStyle:options:)": {
      "abstract": [
        {
          "text": "Returns a font descriptor that contains the text style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFontDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTextStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyleOptionKey",
          "text": "TextStyleOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/preferredFontDescriptor(forTextStyle:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredFontDescriptorForTextStyle:options:"
        }
      ],
      "role": "symbol",
      "title": "preferredFontDescriptor(forTextStyle:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/preferredfontdescriptor(fortextstyle:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/requiresFontAssetRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresFontAssetRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/requiresFontAssetRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresFontAssetRequest"
        }
      ],
      "role": "symbol",
      "title": "requiresFontAssetRequest",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/requiresfontassetrequest"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/symbolicTraits-swift.property": {
      "abstract": [
        {
          "text": "A bit mask that describes the traits of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolicTraits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/symbolicTraits-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "symbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withDesign(_:)": {
      "abstract": [
        {
          "text": "Returns a new font descriptor based on the current object, but with the specified design style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withDesign"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorSystemDesign",
          "text": "SystemDesign"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withDesign(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithDesign:"
        }
      ],
      "role": "symbol",
      "title": "withDesign(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/withdesign(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFace(_:)": {
      "abstract": [
        {
          "text": "Returns a new font descriptor based on the current object, but with the specified face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withFace"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFace(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithFace:"
        }
      ],
      "role": "symbol",
      "title": "withFace(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/withface(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFamily(_:)": {
      "abstract": [
        {
          "text": "Returns a new font descriptor based on the current object, but with the specified font family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withFamily"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFamily(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithFamily:"
        }
      ],
      "role": "symbol",
      "title": "withFamily(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/withfamily(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withMatrix(_:)": {
      "abstract": [
        {
          "text": "Returns a new font descriptor based on the current object, but with the specified font matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withMatrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation15AffineTransformV",
          "text": "AffineTransform"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withMatrix(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithMatrix:"
        }
      ],
      "role": "symbol",
      "title": "withMatrix(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/withmatrix(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withSize(_:)": {
      "abstract": [
        {
          "text": "Returns a new font descriptor based on the current object, but with the specified point size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithSize:"
        }
      ],
      "role": "symbol",
      "title": "withSize(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/withsize(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withSymbolicTraits(_:)": {
      "abstract": [
        {
          "text": "Returns a new font descriptor based on the current object, but with the specified symbolic traits taking precedence over the existing ones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withSymbolicTraits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withSymbolicTraits(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontDescriptorWithSymbolicTraits:"
        }
      ],
      "role": "symbol",
      "title": "withSymbolicTraits(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/withsymbolictraits(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass": {
      "abstract": [
        {
          "text": "Constants that classify certain stylistic qualities of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontFamilyClass"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFamilyClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontFamilyClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontfamilyclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClassMask": {
      "abstract": [
        {
          "text": "Constant you use to access ",
          "type": "text"
        },
        {
          "code": "NSFontFamilyClass",
          "type": "codeVoice"
        },
        {
          "text": " values in the upper four bits of ",
          "type": "text"
        },
        {
          "code": "NSFontSymbolicTraits",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontFamilyClassMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClassMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFamilyClassMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontFamilyClassMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontfamilyclassmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits": {
      "abstract": [
        {
          "text": "A symbolic description of stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "NSFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontsymbolictraits"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask": {
      "abstract": [
        {
          "text": "Constants for isolating specific traits of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontTraitMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/typeface-information": {
      "abstract": [
        {
          "text": "Constants for type faces such as italic or bold.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/typeface-information",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Typeface Information",
      "type": "topic",
      "url": "/documentation/appkit/typeface-information"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Font-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits"
      ],
      "title": "Font Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Font-Descriptor",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/preferredFontDescriptor(forTextStyle:options:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:matrix:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:size:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(fontAttributes:)"
      ],
      "title": "Creating a Font Descriptor"
    },
    {
      "anchor": "Modifying-an-Existing-Font-Descriptor",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/addingAttributes(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFace(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFamily(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withMatrix(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withSize(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withSymbolicTraits(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withDesign(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SystemDesign"
      ],
      "title": "Modifying an Existing Font Descriptor"
    },
    {
      "anchor": "Finding-Fonts",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptors(withMandatoryKeys:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptor(withMandatoryKeys:)"
      ],
      "title": "Finding Fonts"
    },
    {
      "anchor": "Getting-the-Font-Attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/fontAttributes",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/object(forKey:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matrix",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/pointSize",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/postscriptName",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/FeatureKey",
        "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClassMask",
        "doc://com.apple.appkit/documentation/AppKit/typeface-information",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/VariationKey"
      ],
      "title": "Getting the Font Attributes"
    },
    {
      "anchor": "Getting-the-Font-Traits",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/symbolicTraits-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey"
      ],
      "title": "Getting the Font Traits"
    },
    {
      "anchor": "Requiring-Font-Assets",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/requiresFontAssetRequest"
      ],
      "title": "Requiring Font Assets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Font-Descriptor",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/preferredFontDescriptor(forTextStyle:options:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/fontDescriptorWithFontAttributes:",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:matrix:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(name:size:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/init(fontAttributes:)"
              ],
              "title": "Creating a Font Descriptor"
            },
            {
              "anchor": "Modifying-an-Existing-Font-Descriptor",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/addingAttributes(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFace(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withFamily(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withMatrix(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withSize(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withSymbolicTraits(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/withDesign(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SystemDesign"
              ],
              "title": "Modifying an Existing Font Descriptor"
            },
            {
              "anchor": "Finding-Fonts",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptors(withMandatoryKeys:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matchingFontDescriptor(withMandatoryKeys:)"
              ],
              "title": "Finding Fonts"
            },
            {
              "anchor": "Getting-the-Font-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/fontAttributes",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/object(forKey:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/AttributeName",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/matrix",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/pointSize",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/postscriptName",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/FeatureKey",
                "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClassMask",
                "doc://com.apple.appkit/documentation/AppKit/typeface-information",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/VariationKey"
              ],
              "title": "Getting the Font Attributes"
            },
            {
              "anchor": "Getting-the-Font-Traits",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/symbolicTraits-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey"
              ],
              "title": "Getting the Font Traits"
            },
            {
              "anchor": "Requiring-Font-Assets",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/requiresFontAssetRequest"
              ],
              "title": "Requiring Font Assets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Font-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFont",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits"
              ],
              "title": "Font Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1postscriptName/title",
          "value": "postscriptName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1postscriptName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postscriptName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1object(forKey:)/title",
          "value": "objectForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1object(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1symbolicTraits-swift.property/title",
          "value": "symbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1symbolicTraits-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1preferredFontDescriptor(forTextStyle:options:)/title",
          "value": "preferredFontDescriptorForTextStyle:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1preferredFontDescriptor(forTextStyle:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "preferredFontDescriptorForTextStyle:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1matrix/title",
          "value": "matrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1matrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1init(name:size:)/title",
          "value": "fontDescriptorWithName:size:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1init(name:size:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorWithName:size:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/title",
          "value": "NSFontFamilyClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1addingAttributes(_:)/title",
          "value": "fontDescriptorByAddingAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1addingAttributes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorByAddingAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withSize(_:)/title",
          "value": "fontDescriptorWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withSize(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorWithSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withMatrix(_:)/title",
          "value": "fontDescriptorWithMatrix:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withMatrix(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorWithMatrix:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/title",
          "value": "NSFontDescriptorSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withFace(_:)/title",
          "value": "fontDescriptorWithFace:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withFace(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorWithFace:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title",
          "value": "NSFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName/title",
          "value": "NSFontDescriptorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1AttributeName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1fontAttributes/title",
          "value": "fontAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1fontAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fontAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/title",
          "value": "NSFontAssetRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAssetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAssetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/title",
          "value": "NSFontTraitMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1matchingFontDescriptor(withMandatoryKeys:)/title",
          "value": "matchingFontDescriptorWithMandatoryKeys:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1matchingFontDescriptor(withMandatoryKeys:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchingFontDescriptorWithMandatoryKeys:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1matchingFontDescriptors(withMandatoryKeys:)/title",
          "value": "matchingFontDescriptorsWithMandatoryKeys:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1matchingFontDescriptors(withMandatoryKeys:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchingFontDescriptorsWithMandatoryKeys:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey/title",
          "value": "NSFontDescriptorTraitKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SystemDesign/title",
          "value": "NSFontDescriptorSystemDesign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SystemDesign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSystemDesign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SystemDesign/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSystemDesign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1VariationKey/title",
          "value": "NSFontDescriptorVariationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1VariationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorVariationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1VariationKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorVariationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1FeatureKey/title",
          "value": "NSFontDescriptorFeatureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1FeatureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorFeatureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1FeatureKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorFeatureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withFamily(_:)/title",
          "value": "fontDescriptorWithFamily:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withFamily(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorWithFamily:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/title",
          "value": "NSFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1init(fontAttributes:)/title",
          "value": "initWithFontAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1init(fontAttributes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFontAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withDesign(_:)/title",
          "value": "fontDescriptorWithDesign:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withDesign(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorWithDesign:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/title",
          "value": "NSFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1init(name:matrix:)/title",
          "value": "fontDescriptorWithName:matrix:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1init(name:matrix:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorWithName:matrix:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1pointSize/title",
          "value": "pointSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1pointSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClassMask/title",
          "value": "NSFontFamilyClassMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClassMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClassMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withSymbolicTraits(_:)/title",
          "value": "fontDescriptorWithSymbolicTraits:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1withSymbolicTraits(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontDescriptorWithSymbolicTraits:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1requiresFontAssetRequest/title",
          "value": "requiresFontAssetRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1requiresFontAssetRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresFontAssetRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
