{
  "abstract": [
    {
      "text": "A font collection, which is a group of font descriptors taken together as a single object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSFontCollection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFontCollection"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontCollection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSFontCollection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFontCollection"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can publicize the font collection as a named collection and it is presented through the System user interface such as the font panel and Font Book. The queries can be modified using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection": {
      "abstract": [
        {
          "text": "A font collection, which is a group of font descriptors taken together as a single object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontCollection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCollection"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollection",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/ActionTypeKey": {
      "abstract": [
        {
          "text": "The following actions are possible values of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/actionUserInfoKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/didChangeNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActionTypeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/ActionTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActionTypeKey"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollection.ActionTypeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/actiontypekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/Name": {
      "abstract": [
        {
          "text": "The constants represent the standard mutable collection names—these names are included in the list of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/allFontCollectionNames",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "–they have special meaning to the Cocoa font system and should not be hidden or renamed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/Name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollection.Name",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/name"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/UserInfoKey": {
      "abstract": [
        {
          "text": "These constants are used as keys in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/didChangeNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary to indicate the changes that have taken place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UserInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/UserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollection.UserInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/userinfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/Visibility": {
      "abstract": [
        {
          "text": "Constants that specify the visibility of font collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Visibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/Visibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Visibility"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollection.Visibility",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/visibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/actionUserInfoKey": {
      "abstract": [
        {
          "text": "An action was taken. See ",
          "type": "text"
        },
        {
          "code": "NSFontCollectionAction Key Values",
          "type": "codeVoice"
        },
        {
          "text": " for the possible values. An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionUserInfoKey",
          "text": "UserInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/actionUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCollectionActionKey"
        }
      ],
      "role": "symbol",
      "title": "actionUserInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/actionuserinfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/allFontCollectionNames": {
      "abstract": [
        {
          "text": "Returns all named collections visible to this process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allFontCollectionNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/allFontCollectionNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allFontCollectionNames"
        }
      ],
      "role": "symbol",
      "title": "allFontCollectionNames",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/allfontcollectionnames"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/didChangeNotification": {
      "abstract": [
        {
          "text": "Posted whenever a font collection is changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/didChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCollectionDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/didchangenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/exclusionDescriptors": {
      "abstract": [
        {
          "text": "A list of query font descriptors whose matching results are excluded from the list of matching descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exclusionDescriptors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/exclusionDescriptors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exclusionDescriptors"
        }
      ],
      "role": "symbol",
      "title": "exclusionDescriptors",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/exclusiondescriptors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/hide(withName:visibility:)": {
      "abstract": [
        {
          "text": "Remove from view the named font collection with the specified visibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "visibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontCollectionVisibility",
          "text": "Visibility"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/hide(withName:visibility:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hideFontCollectionWithName:visibility:error:"
        }
      ],
      "role": "symbol",
      "title": "hide(withName:visibility:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/hide(withname:visibility:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(descriptors:)": {
      "abstract": [
        {
          "text": "Returns a font collection matching the given descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(descriptors:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontCollectionWithDescriptors:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptors:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/init(descriptors:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(locale:)": {
      "abstract": [
        {
          "text": "Returns a collection of fonts matching the given locale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "locale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(locale:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontCollectionWithLocale:"
        }
      ],
      "role": "symbol",
      "title": "init(locale:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/init(locale:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(name:)": {
      "abstract": [
        {
          "text": "Creates a named font collection object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontCollectionWithName:"
        }
      ],
      "role": "symbol",
      "title": "init(name:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/init(name:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(name:visibility:)": {
      "abstract": [
        {
          "text": "Creates a font collection with the specified name and font visibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "visibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontCollectionVisibility",
          "text": "Visibility"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(name:visibility:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontCollectionWithName:visibility:"
        }
      ],
      "role": "symbol",
      "title": "init(name:visibility:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/init(name:visibility:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors": {
      "abstract": [
        {
          "text": "An array of font descriptors matching the logical descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingDescriptors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchingDescriptors"
        }
      ],
      "role": "symbol",
      "title": "matchingDescriptors",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/matchingdescriptors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:)": {
      "abstract": [
        {
          "text": "Returns an array of font descriptors matching the logical descriptors for the given font family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingDescriptors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFamily"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchingDescriptorsForFamily:"
        }
      ],
      "role": "symbol",
      "title": "matchingDescriptors(forFamily:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/matchingdescriptors(forfamily:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:options:)": {
      "abstract": [
        {
          "text": "Returns an array of font descriptors matching the logical descriptors for the given font family and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingDescriptors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFamily"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionMatchingOptionKey",
          "text": "NSFontCollectionMatchingOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchingDescriptorsForFamily:options:"
        }
      ],
      "role": "symbol",
      "title": "matchingDescriptors(forFamily:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/matchingdescriptors(forfamily:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(options:)": {
      "abstract": [
        {
          "text": "Returns an array of font descriptors matching the logical descriptors with the given options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchingDescriptors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionMatchingOptionKey",
          "text": "NSFontCollectionMatchingOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchingDescriptorsWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "matchingDescriptors(options:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/matchingdescriptors(options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/queryDescriptors": {
      "abstract": [
        {
          "text": "An array of font descriptors whose matching results produce the collection’s matching descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryDescriptors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/queryDescriptors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryDescriptors"
        }
      ],
      "role": "symbol",
      "title": "queryDescriptors",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/querydescriptors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/rename(fromName:visibility:toName:)": {
      "abstract": [
        {
          "text": "Renames the font collection with the specified name and visibility to the second name specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rename"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "visibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontCollectionVisibility",
          "text": "Visibility"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/rename(fromName:visibility:toName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renameFontCollectionWithName:visibility:toName:error:"
        }
      ],
      "role": "symbol",
      "title": "rename(fromName:visibility:toName:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/rename(fromname:visibility:toname:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/show(_:withName:visibility:)": {
      "abstract": [
        {
          "text": "Make the given font collection visible by giving it a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "show"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontCollectionName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "visibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontCollectionVisibility",
          "text": "Visibility"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/show(_:withName:visibility:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showFontCollection:withName:visibility:error:"
        }
      ],
      "role": "symbol",
      "title": "show(_:withName:visibility:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/show(_:withname:visibility:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/withAllAvailableDescriptors": {
      "abstract": [
        {
          "text": "The font collection that matches all registered fonts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withAllAvailableDescriptors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontCollection",
          "text": "NSFontCollection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/withAllAvailableDescriptors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontCollectionWithAllAvailableDescriptors"
        }
      ],
      "role": "symbol",
      "title": "withAllAvailableDescriptors",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollection/withallavailabledescriptors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionMatchingOptionKey": {
      "abstract": [
        {
          "text": "These constants are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " options dictionary parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontCollectionMatchingOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionMatchingOptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCollectionMatchingOptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollectionMatchingOptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollectionmatchingoptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionOptions": {
      "abstract": [
        {
          "text": "Constants that support font collection management.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontCollectionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCollectionOptions"
        }
      ],
      "role": "symbol",
      "title": "NSFontCollectionOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcollectionoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontManager": {
      "abstract": [
        {
          "text": "The center of activity for the font-conversion system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontManager"
        }
      ],
      "role": "symbol",
      "title": "NSFontManager",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection": {
      "abstract": [
        {
          "text": "A mutable collection of font descriptors taken together as a single object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMutableFontCollection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMutableFontCollection"
        }
      ],
      "role": "symbol",
      "title": "NSMutableFontCollection",
      "type": "topic",
      "url": "/documentation/appkit/nsmutablefontcollection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying": {
      "abstract": [
        {
          "text": "A protocol that mutable objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSMutableCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableCopying",
      "type": "topic",
      "url": "/documentation/foundation/nsmutablecopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontManager",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionOptions"
      ],
      "title": "Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Font-Collections",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(descriptors:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(locale:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(name:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(name:visibility:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/withAllAvailableDescriptors"
      ],
      "title": "Creating Font Collections"
    },
    {
      "anchor": "Naming-the-Font-Collection",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/rename(fromName:visibility:toName:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/show(_:withName:visibility:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/hide(withName:visibility:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/allFontCollectionNames",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/Name",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/Visibility"
      ],
      "title": "Naming the Font Collection"
    },
    {
      "anchor": "Getting-the-Font-Descriptors",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:options:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(options:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionMatchingOptionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/queryDescriptors",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/exclusionDescriptors"
      ],
      "title": "Getting the Font Descriptors"
    },
    {
      "anchor": "Responding-to-Changes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/didChangeNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/UserInfoKey",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/ActionTypeKey"
      ],
      "title": "Responding to Changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontCollection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Font-Collections",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(descriptors:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(locale:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(name:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/init(name:visibility:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/withAllAvailableDescriptors"
              ],
              "title": "Creating Font Collections"
            },
            {
              "anchor": "Naming-the-Font-Collection",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/rename(fromName:visibility:toName:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/show(_:withName:visibility:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/hide(withName:visibility:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/allFontCollectionNames",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/Name",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/Visibility"
              ],
              "title": "Naming the Font Collection"
            },
            {
              "anchor": "Getting-the-Font-Descriptors",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(forFamily:options:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/matchingDescriptors(options:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionMatchingOptionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/queryDescriptors",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/exclusionDescriptors"
              ],
              "title": "Getting the Font Descriptors"
            },
            {
              "anchor": "Responding-to-Changes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/didChangeNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/UserInfoKey",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollection/ActionTypeKey"
              ],
              "title": "Responding to Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontManager",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableFontCollection",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCollectionOptions"
              ],
              "title": "Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontCollection"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionMatchingOptionKey/title",
          "value": "NSFontCollectionMatchingOptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionMatchingOptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionMatchingOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionMatchingOptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionMatchingOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1exclusionDescriptors/title",
          "value": "exclusionDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1exclusionDescriptors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exclusionDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableFontCollection/title",
          "value": "NSMutableFontCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableFontCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableFontCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1Visibility/title",
          "value": "NSFontCollectionVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1Visibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1Visibility/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1UserInfoKey/title",
          "value": "NSFontCollectionUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1UserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1UserInfoKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1matchingDescriptors(forFamily:)/title",
          "value": "matchingDescriptorsForFamily:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1matchingDescriptors(forFamily:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchingDescriptorsForFamily:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1didChangeNotification/title",
          "value": "NSFontCollectionDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1didChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1actionUserInfoKey/title",
          "value": "NSFontCollectionActionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1actionUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionActionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1init(descriptors:)/title",
          "value": "fontCollectionWithDescriptors:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1init(descriptors:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontCollectionWithDescriptors:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection/title",
          "value": "NSFontCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1show(_:withName:visibility:)/title",
          "value": "showFontCollection:withName:visibility:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1show(_:withName:visibility:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "showFontCollection:withName:visibility:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1init(name:visibility:)/title",
          "value": "fontCollectionWithName:visibility:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1init(name:visibility:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontCollectionWithName:visibility:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1Name/title",
          "value": "NSFontCollectionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1Name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1Name/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1matchingDescriptors(forFamily:options:)/title",
          "value": "matchingDescriptorsForFamily:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1matchingDescriptors(forFamily:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchingDescriptorsForFamily:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1ActionTypeKey/title",
          "value": "NSFontCollectionActionTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1ActionTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionActionTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1ActionTypeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionActionTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionOptions/title",
          "value": "NSFontCollectionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollectionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCollectionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1init(name:)/title",
          "value": "fontCollectionWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1init(name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontCollectionWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1init(locale:)/title",
          "value": "fontCollectionWithLocale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1init(locale:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fontCollectionWithLocale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1matchingDescriptors(options:)/title",
          "value": "matchingDescriptorsWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1matchingDescriptors(options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchingDescriptorsWithOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1withAllAvailableDescriptors/title",
          "value": "fontCollectionWithAllAvailableDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1withAllAvailableDescriptors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fontCollectionWithAllAvailableDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1rename(fromName:visibility:toName:)/title",
          "value": "renameFontCollectionWithName:visibility:toName:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1rename(fromName:visibility:toName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "renameFontCollectionWithName:visibility:toName:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1matchingDescriptors/title",
          "value": "matchingDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1matchingDescriptors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchingDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager/title",
          "value": "NSFontManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1queryDescriptors/title",
          "value": "queryDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1queryDescriptors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queryDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1allFontCollectionNames/title",
          "value": "allFontCollectionNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1allFontCollectionNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allFontCollectionNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1hide(withName:visibility:)/title",
          "value": "hideFontCollectionWithName:visibility:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCollection~1hide(withName:visibility:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "hideFontCollectionWithName:visibility:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontcollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontcollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
