{
  "abstract": [
    {
      "text": "Constants that classify certain stylistic qualities of the font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSFontFamilyClass",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFontFamilyClass"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontFamilyClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSFontFamilyClass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These values correspond closely to the font class values in the OpenType OS/2 table. The class values are bundled in the upper four bits of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and can be accessed via ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClassMask",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information about the specific meaning of each identifier, refer to the OpenType specification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont": {
      "abstract": [
        {
          "text": "The representation of a font in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "role": "symbol",
      "title": "NSFont",
      "type": "topic",
      "url": "/documentation/appkit/nsfont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontAssetRequest"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAssetRequest"
        }
      ],
      "role": "symbol",
      "title": "NSFontAssetRequest",
      "type": "topic",
      "url": "/documentation/appkit/nsfontassetrequest"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontClarendonSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is a variation of the Oldstyle Serifs and the Transitional Serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontClarendonSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontClarendonSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontClarendonSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontClarendonSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontclarendonserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor": {
      "abstract": [
        {
          "text": "A dictionary of attributes that describe a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct": {
      "abstract": [
        {
          "text": "A symbolic description of the stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.SymbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass": {
      "abstract": [
        {
          "text": "Constants that classify certain stylistic qualities of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontFamilyClass"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFamilyClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontFamilyClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontfamilyclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClassMask": {
      "abstract": [
        {
          "text": "Constant you use to access ",
          "type": "text"
        },
        {
          "code": "NSFontFamilyClass",
          "type": "codeVoice"
        },
        {
          "text": " values in the upper four bits of ",
          "type": "text"
        },
        {
          "code": "NSFontSymbolicTraits",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontFamilyClassMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClassMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFamilyClassMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontFamilyClassMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontfamilyclassmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontFreeformSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style includes serifs, but it expresses a design freedom that does not generally fit within the other serif design classifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontFreeformSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFreeformSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFreeformSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontFreeformSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontfreeformserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontModernSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is based on the Latin printing style of the 20th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontModernSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontModernSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontModernSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontModernSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmodernserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontOldStyleSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is based on the Latin printing style of the 15th to 17th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontOldStyleSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontOldStyleSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontOldStyleSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontOldStyleSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontoldstyleserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontOrnamentalsClass": {
      "abstract": [
        {
          "text": "A font where the style includes highly decorated or stylized character shapes such as those typically used in headlines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontOrnamentalsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontOrnamentalsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontOrnamentalsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontOrnamentalsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontornamentalsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSansSerifClass": {
      "abstract": [
        {
          "text": "A font where the style includes most basic letter forms (excluding Scripts and Ornamentals) that do not have serifs on the strokes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSansSerifClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSansSerifClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSansSerifClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontSansSerifClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontsansserifclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontScriptsClass": {
      "abstract": [
        {
          "text": "A font where the style is among those typefaces designed to simulate handwriting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontScriptsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontScriptsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontScriptsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontScriptsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontscriptsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSlabSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is characterized by serifs with a square transition between the strokes and the serifs (no brackets).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSlabSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSlabSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSlabSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontSlabSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontslabserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicClass": {
      "abstract": [
        {
          "text": "A font where the style is generally design independent, making it suitable for special characters (icons, dingbats, technical symbols, and so on) that may be used equally well with any font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSymbolicClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSymbolicClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontSymbolicClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontsymbolicclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits": {
      "abstract": [
        {
          "text": "A symbolic description of stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "NSFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontsymbolictraits"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask": {
      "abstract": [
        {
          "text": "Constants for isolating specific traits of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontTraitMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTransitionalSerifsClass": {
      "abstract": [
        {
          "text": "A font where the style is based on the Latin printing style of the 18th to 19th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontTransitionalSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTransitionalSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTransitionalSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontTransitionalSerifsClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttransitionalserifsclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontUnknownClass": {
      "abstract": [
        {
          "text": "A font with no design classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontUnknownClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontUnknownClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontUnknownClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontUnknownClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontunknownclass"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Font-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits"
      ],
      "title": "Font Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontUnknownClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontOldStyleSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTransitionalSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontModernSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontClarendonSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSlabSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontFreeformSerifsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSansSerifClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontOrnamentalsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontScriptsClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicClass"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontFamilyClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontUnknownClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontOldStyleSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTransitionalSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontModernSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontClarendonSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSlabSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontFreeformSerifsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSansSerifClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontOrnamentalsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontScriptsClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicClass"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Font-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFont",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits"
              ],
              "title": "Font Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontFamilyClass"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFreeformSerifsClass/title",
          "value": "NSFontFreeformSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFreeformSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFreeformSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/title",
          "value": "NSFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/title",
          "value": "NSFontDescriptorSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontOldStyleSerifsClass/title",
          "value": "NSFontOldStyleSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontOldStyleSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontOldStyleSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/title",
          "value": "NSFontAssetRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAssetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAssetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontOrnamentalsClass/title",
          "value": "NSFontOrnamentalsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontOrnamentalsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontOrnamentalsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSansSerifClass/title",
          "value": "NSFontSansSerifClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSansSerifClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSansSerifClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontUnknownClass/title",
          "value": "NSFontUnknownClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontUnknownClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontUnknownClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTransitionalSerifsClass/title",
          "value": "NSFontTransitionalSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTransitionalSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTransitionalSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/title",
          "value": "NSFontTraitMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSlabSerifsClass/title",
          "value": "NSFontSlabSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSlabSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSlabSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontModernSerifsClass/title",
          "value": "NSFontModernSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontModernSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontModernSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title",
          "value": "NSFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/title",
          "value": "NSFontFamilyClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontScriptsClass/title",
          "value": "NSFontScriptsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontScriptsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontScriptsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClassMask/title",
          "value": "NSFontFamilyClassMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClassMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClassMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontClarendonSerifsClass/title",
          "value": "NSFontClarendonSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontClarendonSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontClarendonSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/title",
          "value": "NSFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicClass/title",
          "value": "NSFontSymbolicClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontfamilyclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontfamilyclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
