{
  "abstract": [
    {
      "text": "The font synthesizes appropriate attributes for user interface rendering, such as control titles, if necessary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontUIOptimizedTrait"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSFontItalicTrait@NSFontUIOptimizedTrait",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFontUIOptimizedTrait"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontUIOptimizedTrait"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSFontUIOptimizedTrait"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFontUIOptimizedTrait"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontBoldTrait": {
      "abstract": [
        {
          "text": "The font’s typestyle is boldface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontBoldTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontBoldTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontBoldTrait"
        }
      ],
      "role": "symbol",
      "title": "NSFontBoldTrait",
      "type": "topic",
      "url": "/documentation/appkit/nsfontboldtrait"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontCondensedTrait": {
      "abstract": [
        {
          "text": "The font’s typestyle is condensed. Expanded and condensed traits are mutually exclusive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontCondensedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontCondensedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontCondensedTrait"
        }
      ],
      "role": "symbol",
      "title": "NSFontCondensedTrait",
      "type": "topic",
      "url": "/documentation/appkit/nsfontcondensedtrait"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontExpandedTrait": {
      "abstract": [
        {
          "text": "The font’s typestyle is expanded. Expanded and condensed traits are mutually exclusive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontExpandedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontExpandedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontExpandedTrait"
        }
      ],
      "role": "symbol",
      "title": "NSFontExpandedTrait",
      "type": "topic",
      "url": "/documentation/appkit/nsfontexpandedtrait"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontItalicTrait": {
      "abstract": [
        {
          "text": "The font’s typestyle is italic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontItalicTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontItalicTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontItalicTrait"
        }
      ],
      "role": "symbol",
      "title": "NSFontItalicTrait",
      "type": "topic",
      "url": "/documentation/appkit/nsfontitalictrait"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontMonoSpaceTrait": {
      "abstract": [
        {
          "text": "The font uses fixed-pitch glyphs if available. The font may have multiple glyph advances (many CJK glyphs contain two spaces).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontMonoSpaceTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontMonoSpaceTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontMonoSpaceTrait"
        }
      ],
      "role": "symbol",
      "title": "NSFontMonoSpaceTrait",
      "type": "topic",
      "url": "/documentation/appkit/nsfontmonospacetrait"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontUIOptimizedTrait": {
      "abstract": [
        {
          "text": "The font synthesizes appropriate attributes for user interface rendering, such as control titles, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontUIOptimizedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontUIOptimizedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontUIOptimizedTrait"
        }
      ],
      "role": "symbol",
      "title": "NSFontUIOptimizedTrait",
      "type": "topic",
      "url": "/documentation/appkit/nsfontuioptimizedtrait"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontVerticalTrait": {
      "abstract": [
        {
          "text": "The font uses vertical glyph variants and metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontVerticalTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontVerticalTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontVerticalTrait"
        }
      ],
      "role": "symbol",
      "title": "NSFontVerticalTrait",
      "type": "topic",
      "url": "/documentation/appkit/nsfontverticaltrait"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontItalicTrait",
        "doc://com.apple.appkit/documentation/AppKit/NSFontBoldTrait",
        "doc://com.apple.appkit/documentation/AppKit/NSFontExpandedTrait",
        "doc://com.apple.appkit/documentation/AppKit/NSFontCondensedTrait",
        "doc://com.apple.appkit/documentation/AppKit/NSFontMonoSpaceTrait",
        "doc://com.apple.appkit/documentation/AppKit/NSFontVerticalTrait"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontUIOptimizedTrait"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontUIOptimizedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontItalicTrait",
                "doc://com.apple.appkit/documentation/AppKit/NSFontBoldTrait",
                "doc://com.apple.appkit/documentation/AppKit/NSFontExpandedTrait",
                "doc://com.apple.appkit/documentation/AppKit/NSFontCondensedTrait",
                "doc://com.apple.appkit/documentation/AppKit/NSFontMonoSpaceTrait",
                "doc://com.apple.appkit/documentation/AppKit/NSFontVerticalTrait"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFontUIOptimizedTrait"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCondensedTrait/title",
          "value": "NSFontCondensedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontCondensedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontCondensedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontUIOptimizedTrait/title",
          "value": "NSFontUIOptimizedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontUIOptimizedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontUIOptimizedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontBoldTrait/title",
          "value": "NSFontBoldTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontBoldTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontBoldTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontItalicTrait/title",
          "value": "NSFontItalicTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontItalicTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontItalicTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontExpandedTrait/title",
          "value": "NSFontExpandedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontExpandedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontExpandedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontVerticalTrait/title",
          "value": "NSFontVerticalTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontVerticalTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontVerticalTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontMonoSpaceTrait/title",
          "value": "NSFontMonoSpaceTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontMonoSpaceTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontMonoSpaceTrait"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontuioptimizedtrait"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontuioptimizedtrait"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
