{
  "abstract": [
    {
      "text": "Draws a bordered rectangle using the specified compositing operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidthUsingOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@NSFrameRectWithWidthUsingOperation",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSFrameRectWithWidthUsingOperation"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFrameRectWithWidthUsingOperation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "NSFrameRectWithWidthUsingOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFrameRectWithWidthUsingOperation"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "frameWidth"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSCompositingOperation",
              "text": "NSCompositingOperation"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "op"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The bounding rectangle (in the current coordinate system) in which to draw.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The width of the frame, specified in points.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "frameWidth"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The compositing operation to use when drawing the frame.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "op"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Draws a frame around the inside of ",
              "type": "text"
            },
            {
              "code": "aRect",
              "type": "codeVoice"
            },
            {
              "text": " in the current color, using the compositing operation ",
              "type": "text"
            },
            {
              "code": "op",
              "type": "codeVoice"
            },
            {
              "text": ". The width is equal to ",
              "type": "text"
            },
            {
              "code": "frameWidth",
              "type": "codeVoice"
            },
            {
              "text": " in the current coordinate system. Since the frame is drawn inside the rectangle, it will be visible even if drawing is clipped to the rectangle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because this function does not draw directly on the line, but rather inside it, it uses the current fill color (not stroke color) when drawing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For a list of compositing operations and how you use them, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation": {
      "abstract": [
        {
          "text": "Constants that describe compositing operators in terms of source and destination images, each having an opaque and transparent region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawGroove(_:_:)": {
      "abstract": [
        {
          "text": "Draws a gray-filled rectangle with a groove border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawGroove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawGroove(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawGroove"
        }
      ],
      "role": "symbol",
      "title": "NSDrawGroove(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawgroove(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawTiledRects(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Draws rectangles with borders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawTiledRects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSRectEdge",
          "text": "NSRectEdge"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawTiledRects(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawTiledRects"
        }
      ],
      "role": "symbol",
      "title": "NSDrawTiledRects(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawtiledrects(_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEraseRect(_:)": {
      "abstract": [
        {
          "text": "Erases the specified rect by filling it with white.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEraseRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEraseRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEraseRect"
        }
      ],
      "role": "symbol",
      "title": "NSEraseRect(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nseraserect(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFrameRect": {
      "abstract": [
        {
          "text": "Draws a bordered rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFrameRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFrameRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFrameRect",
      "type": "topic",
      "url": "/documentation/appkit/nsframerect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidth": {
      "abstract": [
        {
          "text": "Draws a bordered rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFrameRectWithWidth"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidth",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFrameRectWithWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsframerectwithwidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidthUsingOperation": {
      "abstract": [
        {
          "text": "Draws a bordered rectangle using the specified compositing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFrameRectWithWidthUsingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidthUsingOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFrameRectWithWidthUsingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsframerectwithwidthusingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHighlightRect": {
      "abstract": [
        {
          "text": "Highlights the specified rect by filling it with white.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHighlightRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHighlightRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHighlightRect",
      "type": "topic",
      "url": "/documentation/appkit/nshighlightrect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFill": {
      "abstract": [
        {
          "text": "Fills the passed rectangle with the current color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFill"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFill",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFill",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfill"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillList": {
      "abstract": [
        {
          "text": "Fills the rectangles in the passed list with the current fill color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillList"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillList",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillList",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillListUsingOperation": {
      "abstract": [
        {
          "text": "Fills the rectangles in a list using the current fill color and specified compositing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillListUsingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillListUsingOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillListUsingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllistusingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColors": {
      "abstract": [
        {
          "text": "Fills the rectangles in the passed list with the passed list of colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillListWithColors"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColors",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillListWithColors",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllistwithcolors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColorsUsingOperation": {
      "abstract": [
        {
          "text": "Fills the rectangles in a list using the specified colors and compositing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillListWithColorsUsingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColorsUsingOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillListWithColorsUsingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllistwithcolorsusingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithGrays": {
      "abstract": [
        {
          "text": "Fills the rectangles in the passed list with the passed list of grays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillListWithGrays"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithGrays",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillListWithGrays",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfilllistwithgrays"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRectFillUsingOperation": {
      "abstract": [
        {
          "text": "Fills a rectangle using the current fill color and the specified compositing operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRectFillUsingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRectFillUsingOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRectFillUsingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsrectfillusingoperation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRect": {
      "abstract": [
        {
          "text": "A rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRect",
      "type": "topic",
      "url": "/documentation/foundation/nsrect"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290",
      "title": "Cocoa Drawing Guide",
      "titleInlineContent": [
        {
          "text": "Cocoa Drawing Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drawing-Rectangles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFrameRect",
        "doc://com.apple.appkit/documentation/AppKit/NSFrameRectWithWidth",
        "doc://com.apple.appkit/documentation/AppKit/NSEraseRect(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSRectFill",
        "doc://com.apple.appkit/documentation/AppKit/NSRectFillList",
        "doc://com.apple.appkit/documentation/AppKit/NSRectFillListUsingOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColors",
        "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithColorsUsingOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSRectFillListWithGrays",
        "doc://com.apple.appkit/documentation/AppKit/NSRectFillUsingOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawTiledRects(_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawGroove(_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSHighlightRect"
      ],
      "title": "Drawing Rectangles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEraseRect(_:)/title",
          "value": "NSEraseRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEraseRect(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEraseRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/title",
          "value": "NSCompositingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawTiledRects(_:_:_:_:_:)/title",
          "value": "NSDrawTiledRects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawTiledRects(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawTiledRects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawGroove(_:_:)/title",
          "value": "NSDrawGroove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawGroove(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawGroove"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsframerectwithwidthusingoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
