{
  "abstract": [
    {
      "text": "Constants that specify how a glyph is laid out relative to the previous glyph.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/GlyphProperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSGlyphInscription",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSGlyphInscription"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSGlyphInscription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.11",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSGlyphInscription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSGlyphInscription"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The glyph inscription constants are possible values for the glyph attribute ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphAttributeInscribe",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "; glyph inscriptions are set during glyph generation. The only constants that the text system currently uses are ",
              "type": "text"
            },
            {
              "code": "NSGlyphInscribeBase",
              "type": "codeVoice"
            },
            {
              "text": " (for most glyphs) and ",
              "type": "text"
            },
            {
              "code": "NSGlyphInscribeOverstrike",
              "type": "codeVoice"
            },
            {
              "text": " (for nonbase glyphs). Nonbase glyphs occur when diacritical marks are applied to a base character, and the font does not have a single glyph to represent the combination.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, if a font did not contain a single glyph for ü, but did contain separate glyphs for u and ¨, then it could be rendered with a base glyph u followed by a nonbase glyph ¨. In that case the nonbase glyph would have the value ",
              "type": "text"
            },
            {
              "code": "NSGlyphInscribeOverstrike",
              "type": "codeVoice"
            },
            {
              "text": " for the inscribe attribute.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphAttributeInscribe": {
      "abstract": [
        {
          "text": "The glyph inscription attribute.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphAttributeInscribe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphAttributeInscribe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphAttributeInscribe"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphAttributeInscribe",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphattributeinscribe"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription": {
      "abstract": [
        {
          "text": "Constants that specify how a glyph is laid out relative to the previous glyph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGlyphInscription"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGlyphInscription",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinscription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeAbove": {
      "abstract": [
        {
          "text": "A glyph is rendered above the previous glyph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGlyphInscribeAbove"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeAbove",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGlyphInscribeAbove",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinscription/nsglyphinscribeabove"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeBase": {
      "abstract": [
        {
          "text": "A base glyph; a character that the font can represent with a single glyph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGlyphInscribeBase"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeBase",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGlyphInscribeBase",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinscription/nsglyphinscribebase"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeBelow": {
      "abstract": [
        {
          "text": "A glyph is rendered below the previous glyph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGlyphInscribeBelow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeBelow",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGlyphInscribeBelow",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinscription/nsglyphinscribebelow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeOverBelow": {
      "abstract": [
        {
          "text": "A glyph is rendered on top and below the previous glyph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGlyphInscribeOverBelow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeOverBelow",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGlyphInscribeOverBelow",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinscription/nsglyphinscribeoverbelow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeOverstrike": {
      "abstract": [
        {
          "text": "A glyph is rendered on top of the previous glyph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGlyphInscribeOverstrike"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeOverstrike",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGlyphInscribeOverstrike",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinscription/nsglyphinscribeoverstrike"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/GlyphProperty": {
      "abstract": [
        {
          "text": "Glyph properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GlyphProperty"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/GlyphProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GlyphProperty"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.GlyphProperty",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/glyphproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeBase",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeBelow",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeAbove",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeOverstrike",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInscription/NSGlyphInscribeOverBelow"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1GlyphProperty/title",
          "value": "NSGlyphProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1GlyphProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1GlyphProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphAttributeInscribe/title",
          "value": "NSGlyphAttributeInscribe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphAttributeInscribe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphAttributeInscribe"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsglyphinscription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
