{
  "abstract": [
    {
      "text": "A set of methods that a glyph storage object must implement to interact properly with ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSGlyphStorage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSGlyphStorage"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSGlyphStorage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSGlyphStorage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An example of a class that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode": {
      "abstract": [
        {
          "text": "The font rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyph": {
      "abstract": [
        {
          "text": "The type used to specify glyphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyph"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyph"
        }
      ],
      "role": "symbol",
      "title": "NSGlyph",
      "type": "topic",
      "url": "/documentation/appkit/nsglyph"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator": {
      "abstract": [
        {
          "text": "An object that performs the initial, nominal glyph generation phase in the layout process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphGenerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphGenerator"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphGenerator",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphgenerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo": {
      "abstract": [
        {
          "text": "A glyph attribute in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphInfo"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage": {
      "abstract": [
        {
          "text": "A set of methods that a glyph storage object must implement to interact properly with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphStorage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphStorage"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphStorage",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphstorage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/attributedString()": {
      "abstract": [
        {
          "text": "Returns the text storage object from which the ",
          "type": "text"
        },
        {
          "code": "NSGlyphGenerator",
          "type": "codeVoice"
        },
        {
          "text": " object procures characters for glyph generation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedString"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/attributedString()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedString"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "attributedString()",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphstorage/attributedstring()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/insertGlyphs(_:length:forStartingGlyphAt:characterIndex:)": {
      "abstract": [
        {
          "text": "Inserts the given glyphs into the glyph cache and maps them to the specified characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertGlyphs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSGlyph",
          "text": "NSGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forStartingGlyphAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "characterIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/insertGlyphs(_:length:forStartingGlyphAt:characterIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertGlyphs:length:forStartingGlyphAtIndex:characterIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "insertGlyphs(_:length:forStartingGlyphAt:characterIndex:)",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphstorage/insertglyphs(_:length:forstartingglyphat:characterindex:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/layoutOptions()": {
      "abstract": [
        {
          "text": "Returns the current layout options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutOptions"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/layoutOptions()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutOptions"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "layoutOptions()",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphstorage/layoutoptions()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/setIntAttribute(_:value:forGlyphAt:)": {
      "abstract": [
        {
          "text": "Sets a custom attribute value for a given glyph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIntAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forGlyphAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/setIntAttribute(_:value:forGlyphAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIntAttribute:value:forGlyphAtIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setIntAttribute(_:value:forGlyphAt:)",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphstorage/setintattribute(_:value:forglyphat:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager": {
      "abstract": [
        {
          "text": "An object that coordinates the layout and display of text characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-options": {
      "abstract": [
        {
          "text": "Layout options returned as a bit mask by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/layoutOptions()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Options",
      "type": "topic",
      "url": "/documentation/appkit/layout-options"
    },
    "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes": {
      "abstract": [
        {
          "text": "These constants define reserved glyph codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Glyph Codes",
      "type": "topic",
      "url": "/documentation/appkit/reserved-glyph-codes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Glyphs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGlyph",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
        "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes",
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode"
      ],
      "title": "Glyphs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Returning-text-storage",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/attributedString()"
      ],
      "title": "Returning text storage"
    },
    {
      "anchor": "Returning-glyph-display-options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/layoutOptions()"
      ],
      "title": "Returning glyph display options"
    },
    {
      "anchor": "Modifying-the-glyph-cache",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/insertGlyphs(_:length:forStartingGlyphAt:characterIndex:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/setIntAttribute(_:value:forGlyphAt:)"
      ],
      "title": "Modifying the glyph cache"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/layout-options"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSGlyphStorage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Returning-text-storage",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/attributedString()"
              ],
              "title": "Returning text storage"
            },
            {
              "anchor": "Returning-glyph-display-options",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/layoutOptions()"
              ],
              "title": "Returning glyph display options"
            },
            {
              "anchor": "Modifying-the-glyph-cache",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/insertGlyphs(_:length:forStartingGlyphAt:characterIndex:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage/setIntAttribute(_:value:forGlyphAt:)"
              ],
              "title": "Modifying the glyph cache"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/layout-options"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Glyphs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGlyph",
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
                "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes",
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode"
              ],
              "title": "Glyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSGlyphStorage"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/title",
          "value": "NSGlyphInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage~1attributedString()/title",
          "value": "attributedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage~1attributedString()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/title",
          "value": "NSGlyphStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage~1insertGlyphs(_:length:forStartingGlyphAt:characterIndex:)/title",
          "value": "insertGlyphs:length:forStartingGlyphAtIndex:characterIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage~1insertGlyphs(_:length:forStartingGlyphAt:characterIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertGlyphs:length:forStartingGlyphAtIndex:characterIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/title",
          "value": "NSGlyphGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/title",
          "value": "NSGlyph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/title",
          "value": "NSLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage~1layoutOptions()/title",
          "value": "layoutOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage~1layoutOptions()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage~1setIntAttribute(_:value:forGlyphAt:)/title",
          "value": "setIntAttribute:value:forGlyphAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage~1setIntAttribute(_:value:forGlyphAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIntAttribute:value:forGlyphAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/title",
          "value": "NSFontRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsglyphstorage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsglyphstorage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
