{
  "abstract": [
    {
      "text": "The type used to specify glyphs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGlyph"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSGlyph",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSGlyph"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSGlyph"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSGlyph"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSGlyph"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode": {
      "abstract": [
        {
          "text": "The font rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyph": {
      "abstract": [
        {
          "text": "The type used to specify glyphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyph"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyph"
        }
      ],
      "role": "symbol",
      "title": "NSGlyph",
      "type": "topic",
      "url": "/documentation/appkit/nsglyph"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator": {
      "abstract": [
        {
          "text": "An object that performs the initial, nominal glyph generation phase in the layout process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphGenerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphGenerator"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphGenerator",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphgenerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo": {
      "abstract": [
        {
          "text": "A glyph attribute in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphInfo"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage": {
      "abstract": [
        {
          "text": "A set of methods that a glyph storage object must implement to interact properly with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGlyphStorage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGlyphStorage"
        }
      ],
      "role": "symbol",
      "title": "NSGlyphStorage",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphstorage"
    },
    "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes": {
      "abstract": [
        {
          "text": "These constants define reserved glyph codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Glyph Codes",
      "type": "topic",
      "url": "/documentation/appkit/reserved-glyph-codes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Glyphs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
        "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes",
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode"
      ],
      "title": "Glyphs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSGlyph"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Glyphs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphStorage",
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphGenerator",
                "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfo",
                "doc://com.apple.appkit/documentation/AppKit/reserved-glyph-codes",
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode"
              ],
              "title": "Glyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSGlyph"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/title",
          "value": "NSGlyphInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/title",
          "value": "NSFontRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/title",
          "value": "NSGlyph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/title",
          "value": "NSGlyphStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/title",
          "value": "NSGlyphGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyphGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGlyphGenerator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsglyph"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsglyph"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
