{
  "abstract": [
    {
      "text": "A container that aligns views in a flexible grid of rows and columns.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGridView"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSGridView",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSGridView"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSGridView"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSGridView"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSGridView"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A grid view helps you lay out content, such as photos or thumbnails, in a row-column arrangement similar to a spreadsheet. Within a grid view, an item that occupies a single row-column intersection is represented by an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityelementprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer": {
      "abstract": [
        {
          "text": "A set of methods that defines a way to add animation to an existing class with a minimum of API impact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAnimatablePropertyContainer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAnimatablePropertyContainer"
        }
      ],
      "role": "symbol",
      "title": "NSAnimatablePropertyContainer",
      "type": "topic",
      "url": "/documentation/appkit/nsanimatablepropertycontainer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization": {
      "abstract": [
        {
          "text": "A set of methods for getting and setting the appearance attributes of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        }
      ],
      "role": "symbol",
      "title": "NSAppearanceCustomization",
      "type": "topic",
      "url": "/documentation/appkit/nsappearancecustomization"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination": {
      "abstract": [
        {
          "text": "A set of methods that the destination object (or recipient) of a dragged image must implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingDestination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingDestination"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingDestination",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingdestination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell": {
      "abstract": [
        {
          "text": "An individual content area within a grid view, typically at the intersection of a row and a column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGridCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCell"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView": {
      "abstract": [
        {
          "text": "A container that aligns views in a flexible grid of rows and columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGridView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridView"
        }
      ],
      "role": "symbol",
      "title": "NSGridView",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/addColumn(with:)": {
      "abstract": [
        {
          "text": "Adds a new column containing the array of views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridColumn",
          "text": "NSGridColumn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/addColumn(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addColumnWithViews:"
        }
      ],
      "role": "symbol",
      "title": "addColumn(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/addcolumn(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/addRow(with:)": {
      "abstract": [
        {
          "text": "Adds an array of views to a new row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridRow",
          "text": "NSGridRow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/addRow(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addRowWithViews:"
        }
      ],
      "role": "symbol",
      "title": "addRow(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/addrow(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/cell(atColumnIndex:rowIndex:)": {
      "abstract": [
        {
          "text": "Returns the grid cell object at the specified column and row index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atColumnIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rowIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/cell(atColumnIndex:rowIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cellAtColumnIndex:rowIndex:"
        }
      ],
      "role": "symbol",
      "title": "cell(atColumnIndex:rowIndex:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/cell(atcolumnindex:rowindex:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/cell(for:)": {
      "abstract": [
        {
          "text": "Returns the grid cell object that contains the given view or one of its ancestors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/cell(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cellForView:"
        }
      ],
      "role": "symbol",
      "title": "cell(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/cell(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/column(at:)": {
      "abstract": [
        {
          "text": "Returns the grid column object at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "column"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridColumn",
          "text": "NSGridColumn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/column(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "column(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/column(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/columnSpacing": {
      "abstract": [
        {
          "text": "The column spacing for the grid view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/columnSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnSpacing"
        }
      ],
      "role": "symbol",
      "title": "columnSpacing",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/columnspacing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/index(of:)-32sdd": {
      "abstract": [
        {
          "text": "Returns the index of the specified grid column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridColumn",
          "text": "NSGridColumn"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/index(of:)-32sdd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfColumn:"
        }
      ],
      "role": "symbol",
      "title": "index(of:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/index(of:)-32sdd"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/index(of:)-6zs2o": {
      "abstract": [
        {
          "text": "Returns the index of the specified grid row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridRow",
          "text": "NSGridRow"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/index(of:)-6zs2o",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfRow:"
        }
      ],
      "role": "symbol",
      "title": "index(of:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/index(of:)-6zs2o"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a newly allocated grid view object from the coder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/init(coder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(frame:)": {
      "abstract": [
        {
          "text": "Creates a newly allocated grid view object with the specified frame rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(frame:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/init(frame:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(numberOfColumns:rows:)": {
      "abstract": [
        {
          "text": "Creates a newly allocated grid view object with the specified number of columns and rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "numberOfColumns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(numberOfColumns:rows:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gridViewWithNumberOfColumns:rows:"
        }
      ],
      "role": "symbol",
      "title": "init(numberOfColumns:rows:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/init(numberofcolumns:rows:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(views:)": {
      "abstract": [
        {
          "text": "Creates a newly allocated grid view object with the specified array of arrays of views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "views"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "]])"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(views:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gridViewWithViews:"
        }
      ],
      "role": "symbol",
      "title": "init(views:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/init(views:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/insertColumn(at:with:)": {
      "abstract": [
        {
          "text": "Inserts the array of view objects at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridColumn",
          "text": "NSGridColumn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/insertColumn(at:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertColumnAtIndex:withViews:"
        }
      ],
      "role": "symbol",
      "title": "insertColumn(at:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/insertcolumn(at:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/insertRow(at:with:)": {
      "abstract": [
        {
          "text": "Inserts the array of view objects into the grid view at the index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridRow",
          "text": "NSGridRow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/insertRow(at:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertRowAtIndex:withViews:"
        }
      ],
      "role": "symbol",
      "title": "insertRow(at:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/insertrow(at:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/mergeCells(inHorizontalRange:verticalRange:)": {
      "abstract": [
        {
          "text": "Expands the cell at the top-leading corner of the horizontal and vertical range to cover the entire area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeCells"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inHorizontalRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "verticalRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/mergeCells(inHorizontalRange:verticalRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergeCellsInHorizontalRange:verticalRange:"
        }
      ],
      "role": "symbol",
      "title": "mergeCells(inHorizontalRange:verticalRange:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/mergecells(inhorizontalrange:verticalrange:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/moveColumn(at:to:)": {
      "abstract": [
        {
          "text": "Moves the specified column to a new column location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/moveColumn(at:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveColumnAtIndex:toIndex:"
        }
      ],
      "role": "symbol",
      "title": "moveColumn(at:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/movecolumn(at:to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/moveRow(at:to:)": {
      "abstract": [
        {
          "text": "Moves the specified row to the new row location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/moveRow(at:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveRowAtIndex:toIndex:"
        }
      ],
      "role": "symbol",
      "title": "moveRow(at:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/moverow(at:to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/numberOfColumns": {
      "abstract": [
        {
          "text": "The number of columns in the grid view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfColumns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/numberOfColumns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfColumns"
        }
      ],
      "role": "symbol",
      "title": "numberOfColumns",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/numberofcolumns"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/numberOfRows": {
      "abstract": [
        {
          "text": "The number of rows in the grid view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfRows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/numberOfRows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfRows"
        }
      ],
      "role": "symbol",
      "title": "numberOfRows",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/numberofrows"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/removeColumn(at:)": {
      "abstract": [
        {
          "text": "Removes the column from the grid view at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeColumn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/removeColumn(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeColumnAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "removeColumn(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/removecolumn(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/removeRow(at:)": {
      "abstract": [
        {
          "text": "Removes the row from the grid view at the index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/removeRow(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeRowAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "removeRow(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/removerow(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/row(at:)": {
      "abstract": [
        {
          "text": "Returns the grid row object at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "row"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridRow",
          "text": "NSGridRow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/row(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "row(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/row(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/rowAlignment": {
      "abstract": [
        {
          "text": "The row alignment for the grid view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridRow",
          "text": "NSGridRow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridRowAlignment",
          "text": "Alignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/rowAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowAlignment"
        }
      ],
      "role": "symbol",
      "title": "rowAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/rowalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/rowSpacing": {
      "abstract": [
        {
          "text": "The row spacing for the grid view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/rowSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowSpacing"
        }
      ],
      "role": "symbol",
      "title": "rowSpacing",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/rowspacing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/sizedForContent": {
      "abstract": [
        {
          "text": "The default value for row and column sizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizedForContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/sizedForContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridViewSizeForContent"
        }
      ],
      "role": "symbol",
      "title": "sizedForContent",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/sizedforcontent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/xPlacement": {
      "abstract": [
        {
          "text": "The placement of the cell within the grid column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/xPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xPlacement"
        }
      ],
      "role": "symbol",
      "title": "xPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/xplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridView/yPlacement": {
      "abstract": [
        {
          "text": "The placement of the cell within the grid row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridView/yPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yPlacement"
        }
      ],
      "role": "symbol",
      "title": "yPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridview/yplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding": {
      "abstract": [
        {
          "text": "Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        }
      ],
      "role": "symbol",
      "title": "NSStandardKeyBindingResponding",
      "type": "topic",
      "url": "/documentation/appkit/nsstandardkeybindingresponding"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbarprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring": {
      "abstract": [
        {
          "text": "A protocol that marks classes to restore the state of your app to continue a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        }
      ],
      "role": "symbol",
      "title": "NSUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/appkit/nsuseractivityrestoring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfaceitemidentification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
        "doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer",
        "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding",
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider",
        "doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-Grid-View",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(numberOfColumns:rows:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(views:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(frame:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(coder:)"
      ],
      "title": "Creating a Grid View"
    },
    {
      "anchor": "Getting-Information-About-the-Grid",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/numberOfRows",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/numberOfColumns",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/index(of:)-32sdd",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/row(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/column(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/index(of:)-6zs2o"
      ],
      "title": "Getting Information About the Grid"
    },
    {
      "anchor": "Adding-Removing-and-Moving-Rows",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/addRow(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/insertRow(at:with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/removeRow(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/moveRow(at:to:)"
      ],
      "title": "Adding, Removing, and Moving Rows"
    },
    {
      "anchor": "Adding-Removing-and-Moving-Columns",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/addColumn(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/insertColumn(at:with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/removeColumn(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/moveColumn(at:to:)"
      ],
      "title": "Adding, Removing, and Moving Columns"
    },
    {
      "anchor": "Managing-Grid-Spacing-and-Alignment",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/sizedForContent",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/columnSpacing",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/rowSpacing",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/rowAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/xPlacement",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/yPlacement"
      ],
      "title": "Managing Grid Spacing and Alignment"
    },
    {
      "anchor": "Creating-and-Merging-Cells",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/cell(atColumnIndex:rowIndex:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/cell(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSGridView/mergeCells(inHorizontalRange:verticalRange:)"
      ],
      "title": "Creating and Merging Cells"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSGridView"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Grid-View",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(numberOfColumns:rows:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(views:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(frame:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/init(coder:)"
              ],
              "title": "Creating a Grid View"
            },
            {
              "anchor": "Getting-Information-About-the-Grid",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/numberOfRows",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/numberOfColumns",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/index(of:)-32sdd",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/row(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/column(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/index(of:)-6zs2o"
              ],
              "title": "Getting Information About the Grid"
            },
            {
              "anchor": "Adding-Removing-and-Moving-Rows",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/addRow(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/insertRow(at:with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/removeRow(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/moveRow(at:to:)"
              ],
              "title": "Adding, Removing, and Moving Rows"
            },
            {
              "anchor": "Adding-Removing-and-Moving-Columns",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/addColumn(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/insertColumn(at:with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/removeColumn(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/moveColumn(at:to:)"
              ],
              "title": "Adding, Removing, and Moving Columns"
            },
            {
              "anchor": "Managing-Grid-Spacing-and-Alignment",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/sizedForContent",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/columnSpacing",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/rowSpacing",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/rowAlignment",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/xPlacement",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/yPlacement"
              ],
              "title": "Managing Grid Spacing and Alignment"
            },
            {
              "anchor": "Creating-and-Merging-Cells",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/cell(atColumnIndex:rowIndex:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/cell(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSGridView/mergeCells(inHorizontalRange:verticalRange:)"
              ],
              "title": "Creating and Merging Cells"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSGridView"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSView",
                    "text": "NSView"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1column(at:)/title",
          "value": "columnAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1column(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "columnAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1addRow(with:)/title",
          "value": "addRowWithViews:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1addRow(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addRowWithViews:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1xPlacement/title",
          "value": "xPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1xPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1row(at:)/title",
          "value": "rowAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1row(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rowAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView/title",
          "value": "NSGridView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1addColumn(with:)/title",
          "value": "addColumnWithViews:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1addColumn(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addColumnWithViews:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/title",
          "value": "NSAppearanceCustomization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1numberOfRows/title",
          "value": "numberOfRows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1numberOfRows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfRows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/title",
          "value": "NSDraggingDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1insertRow(at:with:)/title",
          "value": "insertRowAtIndex:withViews:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1insertRow(at:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertRowAtIndex:withViews:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title",
          "value": "NSStandardKeyBindingResponding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1index(of:)-32sdd/title",
          "value": "indexOfColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1index(of:)-32sdd/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/title",
          "value": "NSGridCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1removeColumn(at:)/title",
          "value": "removeColumnAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1removeColumn(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeColumnAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1columnSpacing/title",
          "value": "columnSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1columnSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columnSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1cell(atColumnIndex:rowIndex:)/title",
          "value": "cellAtColumnIndex:rowIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1cell(atColumnIndex:rowIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cellAtColumnIndex:rowIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1moveRow(at:to:)/title",
          "value": "moveRowAtIndex:toIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1moveRow(at:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveRowAtIndex:toIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1yPlacement/title",
          "value": "yPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1yPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title",
          "value": "NSUserInterfaceItemIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1rowSpacing/title",
          "value": "rowSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1rowSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1rowAlignment/title",
          "value": "rowAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1rowAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1numberOfColumns/title",
          "value": "numberOfColumns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1numberOfColumns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfColumns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1sizedForContent/title",
          "value": "NSGridViewSizeForContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1sizedForContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridViewSizeForContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1mergeCells(inHorizontalRange:verticalRange:)/title",
          "value": "mergeCellsInHorizontalRange:verticalRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1mergeCells(inHorizontalRange:verticalRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mergeCellsInHorizontalRange:verticalRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1moveColumn(at:to:)/title",
          "value": "moveColumnAtIndex:toIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1moveColumn(at:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveColumnAtIndex:toIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/title",
          "value": "NSAnimatablePropertyContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimatablePropertyContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimatablePropertyContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/title",
          "value": "NSTouchBarProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1cell(for:)/title",
          "value": "cellForView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1cell(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cellForView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1init(numberOfColumns:rows:)/title",
          "value": "gridViewWithNumberOfColumns:rows:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1init(numberOfColumns:rows:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "gridViewWithNumberOfColumns:rows:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1init(frame:)/title",
          "value": "initWithFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1init(frame:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1insertColumn(at:with:)/title",
          "value": "insertColumnAtIndex:withViews:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1insertColumn(at:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertColumnAtIndex:withViews:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1init(views:)/title",
          "value": "gridViewWithViews:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1init(views:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "gridViewWithViews:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1removeRow(at:)/title",
          "value": "removeRowAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1removeRow(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeRowAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1index(of:)-6zs2o/title",
          "value": "indexOfRow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridView~1index(of:)-6zs2o/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfRow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/title",
          "value": "NSUserActivityRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsgridview"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsgridview"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
