{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"NSGridColumn"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSGridColumn"}],"role":"symbol","modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.12"}],"title":"NSGridColumn","externalID":"c:objc(cs)NSGridColumn","roleHeading":"Class"},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridRow"],"generated":true,"title":"Rows and Columns","anchor":"Rows-and-Columns"}],"topicSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement"],"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridColumn/cell(at:)","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/mergeCells(in:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A column within a grid view.","type":"text"}],"kind":"symbol","variants":[{"paths":["/documentation/appkit/nsgridcolumn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsgridcolumn"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSGridColumn","kind":"identifier"}],"platforms":["macOS"]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding":{"url":"/documentation/appkit/nsgridcolumn/leadingpadding","abstract":[],"role":"symbol","title":"leadingPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"leadingPadding"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nsgridcolumn/ishidden","navigatorTitle":[{"kind":"identifier","text":"hidden"}],"title":"isHidden","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/mergeCells(in:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mergeCells","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mergeCellsInRange:","kind":"identifier"}],"abstract":[],"title":"mergeCells(in:)","role":"symbol","url":"/documentation/appkit/nsgridcolumn/mergecells(in:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/mergeCells(in:)"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","role":"symbol","type":"topic","title":"CustomDebugStringConvertible"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","title":"CVarArg","kind":"symbol","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGridRow":{"url":"/documentation/appkit/nsgridrow","title":"NSGridRow","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSGridRow","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSGridRow","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridRow","abstract":[{"type":"text","text":"A row within a grid view."}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailingPadding","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nsgridcolumn/trailingpadding","navigatorTitle":[{"text":"trailingPadding","kind":"identifier"}],"title":"trailingPadding","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn":{"abstract":[{"text":"A column within a grid view.","type":"text"}],"navigatorTitle":[{"text":"NSGridColumn","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn","url":"/documentation/appkit/nsgridcolumn","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSGridColumn","kind":"identifier"}],"role":"symbol","title":"NSGridColumn"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gridView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGridView","text":"NSGridView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/appkit/nsgridcolumn/gridview","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"gridView","kind":"identifier"}],"title":"gridView"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"title":"NSCoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"role":"symbol","url":"/documentation/foundation/nscoding","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"type":"text","text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects."}],"url":"/documentation/objectivec/nsobject","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","role":"symbol","type":"topic","title":"NSObject"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/cell(at:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSGridCell","kind":"typeIdentifier","text":"NSGridCell"}],"navigatorTitle":[{"kind":"identifier","text":"cellAtIndex:"}],"abstract":[],"title":"cell(at:)","role":"symbol","url":"/documentation/appkit/nsgridcolumn/cell(at:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/cell(at:)"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfCells","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/numberofcells","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"numberOfCells","kind":"identifier"}],"title":"numberOfCells"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xPlacement","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSGridCell","text":"NSGridCell","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSGridCellPlacement","text":"Placement","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/xplacement","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"xPlacement","kind":"identifier"}],"title":"xPlacement"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"kind":"symbol","url":"/documentation/Swift/CustomStringConvertible","role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsgridcolumn/width","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"width","kind":"identifier"}],"title":"width"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"10.12","unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Class","op":"replace"},{"path":"/metadata/title","value":"NSGridColumn","op":"replace"},{"path":"/metadata/symbolKind","value":"class","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"NSGridColumn","kind":"identifier"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"NSGridColumn"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridColumn/gridView","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/isHidden","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/leadingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/numberOfCells","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/trailingPadding","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/width","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/xPlacement"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridColumn/cell(at:)","doc://com.apple.appkit/documentation/AppKit/NSGridColumn/mergeCells(in:)"]}],"op":"replace"},{"path":"/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCoding"],"title":"Conforms To"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGridRow"],"generated":true,"anchor":"Rows-and-Columns","title":"Rows and Columns"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSGridColumn"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","text":"NSObject"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1leadingPadding/title","value":"leadingPadding","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1leadingPadding/fragments","value":[{"kind":"identifier","text":"leadingPadding"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1isHidden/title","value":"hidden","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1isHidden/fragments","value":[{"text":"hidden","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1mergeCells(in:)/title","value":"mergeCellsInRange:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1mergeCells(in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"mergeCellsInRange:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow/title","value":"NSGridRow","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow/fragments","value":[{"kind":"identifier","text":"NSGridRow"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridRow/navigatorTitle","value":[{"kind":"identifier","text":"NSGridRow"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1trailingPadding/title","value":"trailingPadding","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1trailingPadding/fragments","value":[{"kind":"identifier","text":"trailingPadding"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/title","value":"NSGridColumn","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/fragments","value":[{"kind":"identifier","text":"NSGridColumn"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn/navigatorTitle","value":[{"kind":"identifier","text":"NSGridColumn"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1gridView/title","value":"gridView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1gridView/fragments","value":[{"kind":"identifier","text":"gridView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1cell(at:)/title","value":"cellAtIndex:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1cell(at:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"cellAtIndex:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1numberOfCells/title","value":"numberOfCells","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1numberOfCells/fragments","value":[{"kind":"identifier","text":"numberOfCells"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1xPlacement/title","value":"xPlacement","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1xPlacement/fragments","value":[{"kind":"identifier","text":"xPlacement"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1width/title","value":"width","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridColumn~1width/fragments","value":[{"kind":"identifier","text":"width"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}