{
  "abstract": [
    {
      "text": "A set of optional methods that you can use to respond to drawing failures and manage incremental loads.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSImageDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSImageDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSImageDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSImageDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/LoadStatus": {
      "abstract": [
        {
          "text": "Status values for incremental image loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LoadStatus"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/LoadStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LoadStatus"
        }
      ],
      "role": "symbol",
      "title": "NSImage.LoadStatus",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/loadstatus"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that you can use to respond to drawing failures and manage incremental loads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSImageDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadPartOfRepresentation:withValidRows:": {
      "abstract": [
        {
          "text": "Tells the delegate that part of the incrementally loaded image data is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image:didLoadPartOfRepresentation:withValidRows:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadPartOfRepresentation:withValidRows:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image:didLoadPartOfRepresentation:withValidRows:"
        }
      ],
      "role": "symbol",
      "title": "image:didLoadPartOfRepresentation:withValidRows:",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/image:didloadpartofrepresentation:withvalidrows:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentation:withStatus:": {
      "abstract": [
        {
          "text": "Tells the delegate that an incrementally loaded image has been loaded and decompressed as completely as is possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image:didLoadRepresentation:withStatus:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentation:withStatus:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image:didLoadRepresentation:withStatus:"
        }
      ],
      "role": "symbol",
      "title": "image:didLoadRepresentation:withStatus:",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/image:didloadrepresentation:withstatus:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentationHeader:": {
      "abstract": [
        {
          "text": "Tells the delegate that enough data has been read to determine the size of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image:didLoadRepresentationHeader:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentationHeader:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image:didLoadRepresentationHeader:"
        }
      ],
      "role": "symbol",
      "title": "image:didLoadRepresentationHeader:",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/image:didloadrepresentationheader:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:willLoadRepresentation:": {
      "abstract": [
        {
          "text": "Tells the delegate that the image object is about to access its underlying bitmap data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image:willLoadRepresentation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:willLoadRepresentation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image:willLoadRepresentation:"
        }
      ],
      "role": "symbol",
      "title": "image:willLoadRepresentation:",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/image:willloadrepresentation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/imageDidNotDraw(_:in:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the image object is unable, for whatever reason, to lock focus on its image or draw in the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageDidNotDraw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/imageDidNotDraw(_:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageDidNotDraw:inRect:"
        }
      ],
      "role": "symbol",
      "title": "imageDidNotDraw(_:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/imagedidnotdraw(_:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep": {
      "abstract": [
        {
          "text": "A semiabstract superclass that provides subclasses that you use to draw an image from a particular type of source data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/applying-apple-hdr-effect-to-your-photos": {
      "abstract": [
        {
          "text": "You can decode and apply Apple’s HDR gain map to your own images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/applying-apple-hdr-effect-to-your-photos",
      "kind": "article",
      "role": "article",
      "title": "Applying Apple HDR effect to your photos",
      "type": "topic",
      "url": "/documentation/appkit/applying-apple-hdr-effect-to-your-photos"
    },
    "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app": {
      "abstract": [
        {
          "text": "Incorporate scanned documents and pictures from a user’s iPhone, iPad, or iPod touch into your Mac app using Continuity Camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting Continuity Camera in Your Mac App",
      "type": "topic",
      "url": "/documentation/appkit/supporting-continuity-camera-in-your-mac-app"
    },
    "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances": {
      "abstract": [
        {
          "text": "Supply image resources appropriate for light and dark appearances and for high-contrast environments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances",
      "kind": "article",
      "role": "article",
      "title": "Providing images for different appearances",
      "type": "topic",
      "url": "/documentation/UIKit/providing-images-for-different-appearances"
    },
    "doc://com.apple.documentation/documentation/UIKit/supporting-hdr-images-in-your-app": {
      "abstract": [
        {
          "text": "​ Load, display, edit, and save HDR images using SwiftUI and Core Image. ​",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/supporting-hdr-images-in-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting HDR images in your app",
      "type": "topic",
      "url": "/documentation/UIKit/supporting-hdr-images-in-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances",
        "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app",
        "doc://com.apple.documentation/documentation/UIKit/supporting-hdr-images-in-your-app",
        "doc://com.apple.appkit/documentation/AppKit/applying-apple-hdr-effect-to-your-photos",
        "doc://com.apple.appkit/documentation/AppKit/NSImage",
        "doc://com.apple.appkit/documentation/AppKit/NSImageRep"
      ],
      "title": "Images"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-Drawing-Failure",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/imageDidNotDraw(_:in:)"
      ],
      "title": "Responding to Drawing Failure"
    },
    {
      "anchor": "Managing-Incremental-Loads",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImage/LoadStatus"
      ],
      "title": "Managing Incremental Loads"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSImageDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-Drawing-Failure",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/imageDidNotDraw(_:in:)"
              ],
              "title": "Responding to Drawing Failure"
            },
            {
              "anchor": "Managing-Incremental-Loads",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadPartOfRepresentation:withValidRows:",
                "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentation:withStatus:",
                "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentationHeader:",
                "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:willLoadRepresentation:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/LoadStatus"
              ],
              "title": "Managing Incremental Loads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances",
                "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app",
                "doc://com.apple.documentation/documentation/UIKit/supporting-hdr-images-in-your-app",
                "doc://com.apple.appkit/documentation/AppKit/applying-apple-hdr-effect-to-your-photos",
                "doc://com.apple.appkit/documentation/AppKit/NSImage",
                "doc://com.apple.appkit/documentation/AppKit/NSImageRep"
              ],
              "title": "Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSImageDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/title",
          "value": "NSImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/title",
          "value": "NSImageDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1LoadStatus/title",
          "value": "NSImageLoadStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1LoadStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageLoadStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1LoadStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageLoadStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate~1imageDidNotDraw(_:in:)/title",
          "value": "imageDidNotDraw:inRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate~1imageDidNotDraw(_:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageDidNotDraw:inRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimagedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimagedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
