{
  "abstract": [
    {
      "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
        "doc://com.apple.appkit/documentation/AppKit/NSImage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsimage-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/bestRepresentationForDevice:": {
      "abstract": [
        {
          "text": "Returns the best representation for the device with the specified characteristics.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "bestRepresentationForDevice:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/bestRepresentationForDevice:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bestRepresentationForDevice:"
        }
      ],
      "role": "symbol",
      "title": "bestRepresentationForDevice:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/bestrepresentationfordevice:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/cacheDepthMatchesImageDepth": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether an image’s offscreen window caches use the same bit depth as the image data itself.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "cacheDepthMatchesImageDepth"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/cacheDepthMatchesImageDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cacheDepthMatchesImageDepth"
        }
      ],
      "role": "symbol",
      "title": "cacheDepthMatchesImageDepth",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/cachedepthmatchesimagedepth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:fromRect:operation:": {
      "abstract": [
        {
          "text": "Composites a portion of the image to the specified point in the current coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "compositeToPoint:fromRect:operation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:fromRect:operation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compositeToPoint:fromRect:operation:"
        }
      ],
      "role": "symbol",
      "title": "compositeToPoint:fromRect:operation:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/compositetopoint:fromrect:operation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:fromRect:operation:fraction:": {
      "abstract": [
        {
          "text": "Composites a portion of the image at the specified opacity to the current coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "compositeToPoint:fromRect:operation:fraction:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:fromRect:operation:fraction:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compositeToPoint:fromRect:operation:fraction:"
        }
      ],
      "role": "symbol",
      "title": "compositeToPoint:fromRect:operation:fraction:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/compositetopoint:fromrect:operation:fraction:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:operation:": {
      "abstract": [
        {
          "text": "Composites the entire image to the specified point in the current coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "compositeToPoint:operation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:operation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compositeToPoint:operation:"
        }
      ],
      "role": "symbol",
      "title": "compositeToPoint:operation:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/compositetopoint:operation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:operation:fraction:": {
      "abstract": [
        {
          "text": "Composites the entire image at the specified opacity in the current coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "compositeToPoint:operation:fraction:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:operation:fraction:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compositeToPoint:operation:fraction:"
        }
      ],
      "role": "symbol",
      "title": "compositeToPoint:operation:fraction:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/compositetopoint:operation:fraction:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/dissolveToPoint:fraction:": {
      "abstract": [
        {
          "text": "Composites the entire image to the specified location using the source-over operator.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dissolveToPoint:fraction:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/dissolveToPoint:fraction:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dissolveToPoint:fraction:"
        }
      ],
      "role": "symbol",
      "title": "dissolveToPoint:fraction:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dissolvetopoint:fraction:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/dissolveToPoint:fromRect:fraction:": {
      "abstract": [
        {
          "text": "Composites a portion of the image to the specified location using the source-over operator.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dissolveToPoint:fromRect:fraction:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/dissolveToPoint:fromRect:fraction:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dissolveToPoint:fromRect:fraction:"
        }
      ],
      "role": "symbol",
      "title": "dissolveToPoint:fromRect:fraction:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dissolvetopoint:fromrect:fraction:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()": {
      "abstract": [
        {
          "text": "Returns an array of strings identifying the image types supported by the registered image representation objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageFileTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageFileTypes"
        }
      ],
      "role": "symbol",
      "title": "imageFileTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/imagefiletypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/imagePasteboardTypes()": {
      "abstract": [
        {
          "text": "Returns an array of strings identifying the pasteboard types supported directly by the registered image representation objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imagePasteboardTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/imagePasteboardTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imagePasteboardTypes"
        }
      ],
      "role": "symbol",
      "title": "imagePasteboardTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/imagepasteboardtypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredFileTypes()": {
      "abstract": [
        {
          "text": "Returns an array of strings identifying the file types supported directly by the registered image representation objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageUnfilteredFileTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredFileTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageUnfilteredFileTypes"
        }
      ],
      "role": "symbol",
      "title": "imageUnfilteredFileTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/imageunfilteredfiletypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredPasteboardTypes()": {
      "abstract": [
        {
          "text": "Returns an array of strings identifying the pasteboard types supported directly by the registered image representation objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageUnfilteredPasteboardTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredPasteboardTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageUnfilteredPasteboardTypes"
        }
      ],
      "role": "symbol",
      "title": "imageUnfilteredPasteboardTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/imageunfilteredpasteboardtypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/init(iconRef:)": {
      "abstract": [
        {
          "text": "Initializes the image object with a Carbon-style icon resource.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "iconRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IconRef",
          "text": "IconRef"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/init(iconRef:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIconRef:"
        }
      ],
      "role": "symbol",
      "title": "init(iconRef:)",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/init(iconref:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/isCachedSeparately": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether each image representation caches its contents in a separate offscreen window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isCachedSeparately"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/isCachedSeparately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isCachedSeparately"
        }
      ],
      "role": "symbol",
      "title": "isCachedSeparately",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/iscachedseparately"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/isDataRetained": {
      "abstract": [
        {
          "text": "Returns a Boolean value that incidates whether the image retains its source image data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isDataRetained"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/isDataRetained",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isDataRetained"
        }
      ],
      "role": "symbol",
      "title": "isDataRetained",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/isdataretained"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/isFlipped": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the image uses a flipped coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isFlipped"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/isFlipped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isFlipped"
        }
      ],
      "role": "symbol",
      "title": "isFlipped",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/isflipped"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocus()": {
      "abstract": [
        {
          "text": "Prepares the image to receive drawing commands.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockFocus"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lockFocus"
        }
      ],
      "role": "symbol",
      "title": "lockFocus()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/lockfocus()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocusFlipped(_:)": {
      "abstract": [
        {
          "text": "Prepares the image to receive drawing commands using the specified flipped state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockFocusFlipped"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocusFlipped(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lockFocusFlipped:"
        }
      ],
      "role": "symbol",
      "title": "lockFocusFlipped(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/lockfocusflipped(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocusOnRepresentation:": {
      "abstract": [
        {
          "text": "Prepares the specified image representation to receive drawing commands.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "lockFocusOnRepresentation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocusOnRepresentation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lockFocusOnRepresentation:"
        }
      ],
      "role": "symbol",
      "title": "lockFocusOnRepresentation:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/lockfocusonrepresentation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/scalesWhenResized": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether to scale image representations to fit the image’s size.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "scalesWhenResized"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/scalesWhenResized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scalesWhenResized"
        }
      ],
      "role": "symbol",
      "title": "scalesWhenResized",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/scaleswhenresized"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/setCacheDepthMatchesImageDepth:": {
      "abstract": [
        {
          "text": "Sets whether the image’s offscreen window caches use the same bit depth as the image data itself.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setCacheDepthMatchesImageDepth:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/setCacheDepthMatchesImageDepth:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCacheDepthMatchesImageDepth:"
        }
      ],
      "role": "symbol",
      "title": "setCacheDepthMatchesImageDepth:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/setcachedepthmatchesimagedepth:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/setCachedSeparately:": {
      "abstract": [
        {
          "text": "Sets whether each image representation uses a separate offscreen window to cache its contents.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setCachedSeparately:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/setCachedSeparately:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCachedSeparately:"
        }
      ],
      "role": "symbol",
      "title": "setCachedSeparately:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/setcachedseparately:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/setDataRetained:": {
      "abstract": [
        {
          "text": "Sets whether the image retains its source image data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setDataRetained:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/setDataRetained:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDataRetained:"
        }
      ],
      "role": "symbol",
      "title": "setDataRetained:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/setdataretained:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/setFlipped:": {
      "abstract": [
        {
          "text": "Sets whether the polarity of the y axis is inverted when drawing an image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFlipped:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/setFlipped:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFlipped:"
        }
      ],
      "role": "symbol",
      "title": "setFlipped:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/setflipped:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/setScalesWhenResized:": {
      "abstract": [
        {
          "text": "Sets whether to scale different-sized image representations to fit the image’s size.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setScalesWhenResized:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/setScalesWhenResized:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setScalesWhenResized:"
        }
      ],
      "role": "symbol",
      "title": "setScalesWhenResized:",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/setscaleswhenresized:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/unlockFocus()": {
      "abstract": [
        {
          "text": "Removes the focus from the image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlockFocus"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/unlockFocus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlockFocus"
        }
      ],
      "role": "symbol",
      "title": "unlockFocus()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/unlockfocus()"
    },
    "doc://com.apple.appkit/documentation/AppKit/images-and-pdf": {
      "abstract": [
        {
          "text": "Create and manage images, in bitmap, PDF, and other formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Images and PDF",
      "type": "topic",
      "url": "/documentation/appkit/images-and-pdf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Class-Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredFileTypes()",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/imagePasteboardTypes()",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredPasteboardTypes()"
      ],
      "title": "Class Methods"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocus()",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocusFlipped(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/unlockFocus()",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/init(iconRef:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Class-Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredFileTypes()",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/imagePasteboardTypes()",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredPasteboardTypes()"
              ],
              "title": "Class Methods"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocus()",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocusFlipped(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/unlockFocus()",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/init(iconRef:)",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/lockFocusOnRepresentation:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/bestRepresentationForDevice:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:operation:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:fromRect:operation:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:fromRect:operation:fraction:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/compositeToPoint:operation:fraction:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/dissolveToPoint:fraction:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/dissolveToPoint:fromRect:fraction:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/setScalesWhenResized:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/scalesWhenResized",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/setDataRetained:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/isDataRetained",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/setCachedSeparately:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/isCachedSeparately",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/setCacheDepthMatchesImageDepth:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/cacheDepthMatchesImageDepth",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/setFlipped:",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/isFlipped"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1unlockFocus()/title",
          "value": "unlockFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1unlockFocus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unlockFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageFileTypes()/title",
          "value": "imageFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageFileTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imagePasteboardTypes()/title",
          "value": "imagePasteboardTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imagePasteboardTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imagePasteboardTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageUnfilteredFileTypes()/title",
          "value": "imageUnfilteredFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageUnfilteredFileTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageUnfilteredFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1lockFocusFlipped(_:)/title",
          "value": "lockFocusFlipped:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1lockFocusFlipped(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lockFocusFlipped:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageUnfilteredPasteboardTypes()/title",
          "value": "imageUnfilteredPasteboardTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageUnfilteredPasteboardTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageUnfilteredPasteboardTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1lockFocus()/title",
          "value": "lockFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1lockFocus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lockFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(iconRef:)/title",
          "value": "initWithIconRef:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(iconRef:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIconRef:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimage-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimage-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
