{
  "abstract": [
    {
      "text": "Constants that specify the interpolation, or image smoothing, behavior used by the image interpolation property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSImageInterpolation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSImageInterpolation"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSImageInterpolation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSImageInterpolation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation": {
      "abstract": [
        {
          "text": "Constants that describe compositing operators in terms of source and destination images, each having an opaque and transparent region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositingOperation"
        }
      ],
      "role": "symbol",
      "title": "NSCompositingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nscompositingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/compositingOperation": {
      "abstract": [
        {
          "text": "The graphics context’s global compositing operation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositingOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCompositingOperation",
          "text": "NSCompositingOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/compositingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compositingOperation"
        }
      ],
      "role": "symbol",
      "title": "compositingOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext/compositingoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation": {
      "abstract": [
        {
          "text": "A constant that specifies the graphics context’s interpolation, or image smoothing, behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageInterpolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSImageInterpolation",
          "text": "NSImageInterpolation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageInterpolation"
        }
      ],
      "role": "symbol",
      "title": "imageInterpolation",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext/imageinterpolation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/patternPhase": {
      "abstract": [
        {
          "text": "The amount to offset the pattern color when filling the graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/patternPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "patternPhase"
        }
      ],
      "role": "symbol",
      "title": "patternPhase",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext/patternphase"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/shouldAntialias": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the graphics context uses antialiasing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldAntialias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/shouldAntialias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldAntialias"
        }
      ],
      "role": "symbol",
      "title": "shouldAntialias",
      "type": "topic",
      "url": "/documentation/appkit/nsgraphicscontext/shouldantialias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation": {
      "abstract": [
        {
          "text": "Constants that specify the interpolation, or image smoothing, behavior used by the image interpolation property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageInterpolation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolation"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/default": {
      "abstract": [
        {
          "text": "Use the context’s default interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationDefault"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.default",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/high": {
      "abstract": [
        {
          "text": "Highest quality, slower than the medium interpolation option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationHigh"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.high",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/high"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/low": {
      "abstract": [
        {
          "text": "Fast, low-quality interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationLow"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.low",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/low"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/medium": {
      "abstract": [
        {
          "text": "Medium quality, slower than the low interpolation option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationMedium"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.medium",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/medium"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/none": {
      "abstract": [
        {
          "text": "No interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterpolationNone"
        }
      ],
      "role": "symbol",
      "title": "NSImageInterpolation.none",
      "type": "topic",
      "url": "/documentation/appkit/nsimageinterpolation/none"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Rendering-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/compositingOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation",
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/shouldAntialias",
        "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/patternPhase"
      ],
      "title": "Configuring Rendering Options"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/default",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/none",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/low",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/medium",
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/high"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSImageInterpolation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/default",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/none",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/low",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/medium",
                "doc://com.apple.appkit/documentation/AppKit/NSImageInterpolation/high"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Rendering-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/compositingOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSCompositingOperation",
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/imageInterpolation",
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/shouldAntialias",
                "doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/patternPhase"
              ],
              "title": "Configuring Rendering Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSImageInterpolation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1none/title",
          "value": "NSImageInterpolationNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1compositingOperation/title",
          "value": "compositingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1compositingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1shouldAntialias/title",
          "value": "shouldAntialias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1shouldAntialias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldAntialias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1default/title",
          "value": "NSImageInterpolationDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1low/title",
          "value": "NSImageInterpolationLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/title",
          "value": "NSCompositingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCompositingOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1high/title",
          "value": "NSImageInterpolationHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/title",
          "value": "NSImageInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1imageInterpolation/title",
          "value": "imageInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1imageInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1medium/title",
          "value": "NSImageInterpolationMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageInterpolation~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterpolationMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1patternPhase/title",
          "value": "patternPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1patternPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "patternPhase"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimageinterpolation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimageinterpolation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
