{
  "abstract": [
    {
      "text": "Returns an interface style value for the specified key and responder.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyleForKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@NSInterfaceStyleForKey",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSInterfaceStyleForKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSInterfaceStyleForKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.8",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "NSInterfaceStyleForKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInterfaceStyle",
              "text": "NSInterfaceStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSInterfaceStyleForKey"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "responder"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Used to determine an interface style based on a key and a responder, either of which may be ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value specifies the style in which an interface item, such as a button or a scroll bar, should be drawn. For example, a value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMacintoshInterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " indicates an item should be drawn in the Macintosh style. The values defined for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNoInterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNextStepInterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindows95InterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMacintoshInterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Note that this function never returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNoInterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The interface style value returned by this function depends on several factors. If responder is not ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " and if responder specifies an interface style other than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNoInterfaceStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", this function returns the responder’s style, and ",
              "type": "text"
            },
            {
              "code": "key",
              "type": "codeVoice"
            },
            {
              "text": " is ignored.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Otherwise, if ",
              "type": "text"
            },
            {
              "code": "key",
              "type": "codeVoice"
            },
            {
              "text": " is not ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " and there is an interface style for ",
              "type": "text"
            },
            {
              "code": "key",
              "type": "codeVoice"
            },
            {
              "text": " specified by the defaults system, this function returns the interface style for ",
              "type": "text"
            },
            {
              "code": "key",
              "type": "codeVoice"
            },
            {
              "text": " from the defaults system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, if ",
              "type": "text"
            },
            {
              "code": "key",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", or if there is no interface style for ",
              "type": "text"
            },
            {
              "code": "key",
              "type": "codeVoice"
            },
            {
              "text": " specified by the defaults system, this function returns the global interface style specified by the defaults system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The defaults system allows an application to customize its behavior to match a user’s preferences. You can read about the defaults system in the documentation for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/userdefaults",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)": {
      "abstract": [
        {
          "text": "Raises an error if the parameter is the wrong type or has an illegal value",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raiseBadArgumentException"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRaiseBadArgumentException"
        }
      ],
      "role": "symbol",
      "title": "raiseBadArgumentException(_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/raisebadargumentexception(_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbeginalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginCriticalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginCriticalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegincriticalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginInformationalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginInformationalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegininformationalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Prepares a set of glyphs for processing by character-based routines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSGlyph",
          "text": "NSGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMultibyteGlyphPacking",
          "text": "NSMultibyteGlyphPacking"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        }
      ],
      "role": "symbol",
      "title": "NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsconvertglyphstopackedglyphs(_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display a critical message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetcriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display an informational message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetinformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle": {
      "abstract": [
        {
          "text": "These constants are used in ",
          "type": "text"
        },
        {
          "code": "NSResponder",
          "type": "codeVoice"
        },
        {
          "text": "’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInterfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsinterfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyleForKey": {
      "abstract": [
        {
          "text": "Returns an interface style value for the specified key and responder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInterfaceStyleForKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyleForKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInterfaceStyleForKey",
      "type": "topic",
      "url": "/documentation/appkit/nsinterfacestyleforkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMacintoshInterfaceStyle": {
      "abstract": [
        {
          "text": "The Macintosh interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMacintoshInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMacintoshInterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMacintoshInterfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsmacintoshinterfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNextStepInterfaceStyle": {
      "abstract": [
        {
          "text": "The NextStep interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNextStepInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNextStepInterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNextStepInterfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsnextstepinterfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNoInterfaceStyle": {
      "abstract": [
        {
          "text": "The default interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNoInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNoInterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNoInterfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsnointerfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption": {
      "abstract": [
        {
          "text": "Returns global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion": {
      "abstract": [
        {
          "text": "Returns the NSOpenGL version numbers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption": {
      "abstract": [
        {
          "text": "Sets global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLSetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLSetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglsetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)": {
      "abstract": [
        {
          "text": "Disposes of an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        }
      ],
      "role": "symbol",
      "title": "NSReleaseAlertPanel(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsreleasealertpanel(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder": {
      "abstract": [
        {
          "text": "An abstract class that forms the basis of event and command processing in AppKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSResponder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSResponder"
        }
      ],
      "role": "symbol",
      "title": "NSResponder",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle": {
      "abstract": [
        {
          "text": "Returns the receiver’s interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "interfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "interfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/interfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel": {
      "abstract": [
        {
          "text": "Creates an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsrunalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruncriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruninformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindows95InterfaceStyle": {
      "abstract": [
        {
          "text": "The Windows 95 interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWindows95InterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindows95InterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindows95InterfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nswindows95interfacestyle"
    },
    "doc://com.apple.documentation/documentation/foundation/userdefaults": {
      "abstract": [
        {
          "text": "An interface to the user’s defaults database, where you store key-value pairs persistently across launches of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "UserDefaults"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/userdefaults",
      "kind": "symbol",
      "role": "symbol",
      "title": "UserDefaults",
      "type": "topic",
      "url": "/documentation/foundation/userdefaults"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/title",
          "value": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConvertGlyphsToPackedGlyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title",
          "value": "NSResponder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1userdefaults/title",
          "value": "NSUserDefaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/title",
          "value": "NSAccessibilityRaiseBadArgumentException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRaiseBadArgumentException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/title",
          "value": "NSReleaseAlertPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReleaseAlertPanel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsinterfacestyleforkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
