{
  "abstract": [
    {
      "text": "The insert line key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSInsertLineFunctionKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSUpArrowFunctionKey@NSInsertLineFunctionKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSInsertLineFunctionKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSInsertLineFunctionKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSInsertLineFunctionKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSInsertLineFunctionKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is unavailable on most Macintosh keyboards.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginFunctionKey": {
      "abstract": [
        {
          "text": "The begin key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBeginFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBeginFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSBeginFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsbeginfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBreakFunctionKey": {
      "abstract": [
        {
          "text": "The break key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBreakFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBreakFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBreakFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSBreakFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsbreakfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSClearDisplayFunctionKey": {
      "abstract": [
        {
          "text": "The clear display key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSClearDisplayFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSClearDisplayFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSClearDisplayFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSClearDisplayFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nscleardisplayfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSClearLineFunctionKey": {
      "abstract": [
        {
          "text": "The clear or num lock key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSClearLineFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSClearLineFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSClearLineFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSClearLineFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsclearlinefunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeleteCharFunctionKey": {
      "abstract": [
        {
          "text": "The delete character key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeleteCharFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeleteCharFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeleteCharFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSDeleteCharFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsdeletecharfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeleteLineFunctionKey": {
      "abstract": [
        {
          "text": "The delete line key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeleteLineFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeleteLineFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeleteLineFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSDeleteLineFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsdeletelinefunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSExecuteFunctionKey": {
      "abstract": [
        {
          "text": "The execute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExecuteFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSExecuteFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExecuteFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSExecuteFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsexecutefunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFindFunctionKey": {
      "abstract": [
        {
          "text": "The find key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFindFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFindFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFindFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSFindFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfindfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHelpFunctionKey": {
      "abstract": [
        {
          "text": "The help key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHelpFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHelpFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHelpFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSHelpFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nshelpfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInsertCharFunctionKey": {
      "abstract": [
        {
          "text": "The insert character key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInsertCharFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInsertCharFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInsertCharFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSInsertCharFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsinsertcharfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInsertFunctionKey": {
      "abstract": [
        {
          "text": "The insert key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInsertFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInsertFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInsertFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSInsertFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsinsertfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInsertLineFunctionKey": {
      "abstract": [
        {
          "text": "The insert line key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInsertLineFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInsertLineFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInsertLineFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSInsertLineFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsinsertlinefunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuFunctionKey": {
      "abstract": [
        {
          "text": "The menu key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSMenuFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsmenufunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSModeSwitchFunctionKey": {
      "abstract": [
        {
          "text": "The mode switch key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSModeSwitchFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSModeSwitchFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSModeSwitchFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSModeSwitchFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsmodeswitchfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPauseFunctionKey": {
      "abstract": [
        {
          "text": "The pause key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPauseFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPauseFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPauseFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPauseFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nspausefunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintFunctionKey": {
      "abstract": [
        {
          "text": "The print key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPrintFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfunctionkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Special-Behavior-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBeginFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSBreakFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSClearDisplayFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSClearLineFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSDeleteCharFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSDeleteLineFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSExecuteFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSFindFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSHelpFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSInsertFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSInsertCharFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSModeSwitchFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSPauseFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintFunctionKey"
      ],
      "title": "Getting Special Behavior Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSInsertLineFunctionKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertLineFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Special-Behavior-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBeginFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSBreakFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSClearDisplayFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSClearLineFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSDeleteCharFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSDeleteLineFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSExecuteFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSFindFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSHelpFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSInsertFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSInsertCharFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSModeSwitchFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSPauseFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintFunctionKey"
              ],
              "title": "Getting Special Behavior Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSInsertLineFunctionKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSExecuteFunctionKey/title",
          "value": "NSExecuteFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSExecuteFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExecuteFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeleteCharFunctionKey/title",
          "value": "NSDeleteCharFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeleteCharFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeleteCharFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInsertFunctionKey/title",
          "value": "NSInsertFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInsertFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeleteLineFunctionKey/title",
          "value": "NSDeleteLineFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeleteLineFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeleteLineFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHelpFunctionKey/title",
          "value": "NSHelpFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHelpFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHelpFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSModeSwitchFunctionKey/title",
          "value": "NSModeSwitchFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSModeSwitchFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSModeSwitchFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBreakFunctionKey/title",
          "value": "NSBreakFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBreakFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBreakFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSClearDisplayFunctionKey/title",
          "value": "NSClearDisplayFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSClearDisplayFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSClearDisplayFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInsertCharFunctionKey/title",
          "value": "NSInsertCharFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInsertCharFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertCharFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintFunctionKey/title",
          "value": "NSPrintFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInsertLineFunctionKey/title",
          "value": "NSInsertLineFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInsertLineFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertLineFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFindFunctionKey/title",
          "value": "NSFindFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFindFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFindFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSClearLineFunctionKey/title",
          "value": "NSClearLineFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSClearLineFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSClearLineFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuFunctionKey/title",
          "value": "NSMenuFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPauseFunctionKey/title",
          "value": "NSPauseFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPauseFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPauseFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBeginFunctionKey/title",
          "value": "NSBeginFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBeginFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBeginFunctionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsinsertlinefunctionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsinsertlinefunctionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
