{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSInputServerMouseTracker",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSInputServerMouseTracker"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSInputServerMouseTracker"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSInputServerMouseTracker"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate": {
      "abstract": [
        {
          "text": "A set of methods that drawer delegates implement to open, close, and resize the drawer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawerDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawerDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSDrawerDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawerdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration": {
      "abstract": [
        {
          "text": "A set of methods that controllers can implement to enable an editor view to inform the controller when it has uncommitted changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEditorRegistration"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEditorRegistration"
        }
      ],
      "role": "symbol",
      "title": "NSEditorRegistration",
      "type": "topic",
      "url": "/documentation/appkit/nseditorregistration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInputServer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInputServer",
      "type": "topic",
      "url": "/documentation/appkit/nsinputserver"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInputServerMouseTracker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInputServerMouseTracker"
        }
      ],
      "role": "symbol",
      "title": "NSInputServerMouseTracker",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDownOnCharacterIndex:atCoordinate:withModifier:client:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDownOnCharacterIndex:atCoordinate:withModifier:client:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "role": "symbol",
      "title": "mouseDownOnCharacterIndex:atCoordinate:withModifier:client:",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker/mousedownoncharacterindex:atcoordinate:withmodifier:client:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "role": "symbol",
      "title": "mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker/mousedraggedoncharacterindex:atcoordinate:withmodifier:client:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseUpOnCharacterIndex:atCoordinate:withModifier:client:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mouseUpOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseUpOnCharacterIndex:atCoordinate:withModifier:client:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseUpOnCharacterIndex:atCoordinate:withModifier:client:"
        }
      ],
      "role": "symbol",
      "title": "mouseUpOnCharacterIndex:atCoordinate:withModifier:client:",
      "type": "topic",
      "url": "/documentation/appkit/nsinputservermousetracker/mouseuponcharacterindex:atcoordinate:withmodifier:client:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInputServiceProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInputServiceProvider"
        }
      ],
      "role": "symbol",
      "title": "NSInputServiceProvider",
      "type": "topic",
      "url": "/documentation/appkit/nsinputserviceprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsaccessibility": {
      "abstract": [
        {
          "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols": {
      "abstract": [
        {
          "text": "A set of methods that controllers and UI elements can implement to manage editing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSEditor",
      "type": "topic",
      "url": "/documentation/appkit/nseditor-deprecated-symbols"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
        "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
        "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
        "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate"
      ],
      "title": "Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSInputServerMouseTracker"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDownOnCharacterIndex:atCoordinate:withModifier:client:",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseDraggedOnCharacterIndex:atCoordinate:withModifier:client:",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServerMouseTracker/mouseUpOnCharacterIndex:atCoordinate:withModifier:client:"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSInputServer"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
                "doc://com.apple.appkit/documentation/AppKit/nseditor-deprecated-symbols",
                "doc://com.apple.appkit/documentation/AppKit/NSEditorRegistration",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServiceProvider",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawerDelegate"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSInputServerMouseTracker"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/title",
          "value": "NSEditorRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditorRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEditorRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEditorRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/title",
          "value": "NSInputServerMouseTracker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServerMouseTracker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServerMouseTracker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/title",
          "value": "NSInputServiceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServiceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSInputServiceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInputServiceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/title",
          "value": "NSDrawerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsinputservermousetracker"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsinputservermousetracker"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
