{
  "abstract": [
    {
      "text": "Tests whether a given object is special marker object used for indicating the state of a selection in relation to a key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@NSIsControllerMarker",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSIsControllerMarker"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSIsControllerMarker"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "NSIsControllerMarker(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSIsControllerMarker"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "object"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Specify the object you want to check. This parameter can be ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "object"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the object is one of the designated controller markers or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if it is not.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function helps you to create bindings between user interface elements and controller objects. The Application Kit predefines several special marker objects used as values for indicating selection state; currently these are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultipleValuesMarker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNoSelectionMarker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNotApplicableMarker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". These markers are typed as ",
              "type": "text"
            },
            {
              "code": "id",
              "type": "codeVoice"
            },
            {
              "text": " and only exist for the purpose of indicating a state; they are never archived and cannot be used as object values in controls. You use this function to test whether a given object value is a marker, in which case it is not directly assignable to the object that is bound. This check is important, especially since additional markers may be added in the future.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "See the ",
              "type": "text"
            },
            {
              "code": "NSKeyValueBinding.h",
              "type": "codeVoice"
            },
            {
              "text": " header file for further details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingInfoKey"
        }
      ],
      "role": "symbol",
      "title": "NSBindingInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nsbindinginfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingName": {
      "abstract": [
        {
          "text": "Values that specify a binding for certain methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingName"
        }
      ],
      "role": "symbol",
      "title": "NSBindingName",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingOption"
        }
      ],
      "role": "symbol",
      "title": "NSBindingOption",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController": {
      "abstract": [
        {
          "text": "A bindings-compatible controller that manages the display and editing of a dictionary of key-value pairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDictionaryController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDictionaryController"
        }
      ],
      "role": "symbol",
      "title": "NSDictionaryController",
      "type": "topic",
      "url": "/documentation/appkit/nsdictionarycontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair": {
      "abstract": [
        {
          "text": "A set of methods implemented by arranged objects to give access to information about those objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDictionaryControllerKeyValuePair"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDictionaryControllerKeyValuePair"
        }
      ],
      "role": "symbol",
      "title": "NSDictionaryControllerKeyValuePair",
      "type": "topic",
      "url": "/documentation/appkit/nsdictionarycontrollerkeyvaluepair"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)": {
      "abstract": [
        {
          "text": "Tests whether a given object is special marker object used for indicating the state of a selection in relation to a key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIsControllerMarker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIsControllerMarker(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIsControllerMarker"
        }
      ],
      "role": "symbol",
      "title": "NSIsControllerMarker(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsiscontrollermarker(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultipleValuesMarker": {
      "abstract": [
        {
          "text": "This marker indicates that a key’s value contains multiple values that differ.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMultipleValuesMarker"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultipleValuesMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMultipleValuesMarker"
        }
      ],
      "role": "symbol",
      "title": "NSMultipleValuesMarker",
      "type": "topic",
      "url": "/documentation/appkit/nsmultiplevaluesmarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNoSelectionMarker": {
      "abstract": [
        {
          "text": "This marker indicates that the controller’s selection is currently empty.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSNoSelectionMarker"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNoSelectionMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoSelectionMarker"
        }
      ],
      "role": "symbol",
      "title": "NSNoSelectionMarker",
      "type": "topic",
      "url": "/documentation/appkit/nsnoselectionmarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNotApplicableMarker": {
      "abstract": [
        {
          "text": "This marker indicates that an object is not key-value coding compliant for the requested key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSNotApplicableMarker"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNotApplicableMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNotApplicableMarker"
        }
      ],
      "role": "symbol",
      "title": "NSNotApplicableMarker",
      "type": "topic",
      "url": "/documentation/appkit/nsnotapplicablemarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys": {
      "abstract": [
        {
          "text": "These constants define keys in the binding information dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Binding dictionary keys",
      "type": "topic",
      "url": "/documentation/appkit/binding-dictionary-keys"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation": {
      "abstract": [
        {
          "text": "A set of methods that you can use to create and remove bindings between view objects and controllers, or between controllers and model objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation",
      "kind": "article",
      "role": "article",
      "title": "NSKeyValueBindingCreation",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/nskeyvaluebindingcreation"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Key-Value-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
        "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
        "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation",
        "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys"
      ],
      "title": "Key-Value Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSIsControllerMarker"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIsControllerMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Key-Value-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDictionaryController",
                "doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingName",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingOption",
                "doc://com.apple.appkit/documentation/AppKit/NSBindingInfoKey",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/nskeyvaluebindingcreation",
                "doc://com.apple.appkit/documentation/AppKit/binding-dictionary-keys"
              ],
              "title": "Key-Value Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSIsControllerMarker"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "object"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specify the object you want to check. This parameter can be ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "object"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the object is one of the designated controller markers or ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if it is not.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/title",
          "value": "NSBindingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIsControllerMarker(_:)/title",
          "value": "NSIsControllerMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSIsControllerMarker(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIsControllerMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultipleValuesMarker/title",
          "value": "NSMultipleValuesMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultipleValuesMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultipleValuesMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/title",
          "value": "NSDictionaryController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/title",
          "value": "NSBindingInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingInfoKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/title",
          "value": "NSBindingName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/title",
          "value": "NSDictionaryControllerKeyValuePair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryControllerKeyValuePair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDictionaryControllerKeyValuePair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNotApplicableMarker/title",
          "value": "NSNotApplicableMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNotApplicableMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNotApplicableMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNoSelectionMarker/title",
          "value": "NSNoSelectionMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNoSelectionMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoSelectionMarker"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsiscontrollermarker(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsiscontrollermarker(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
