{
  "abstract": [
    {
      "text": "Text is justified.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/justified",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSJustifiedTextAlignment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSJustifiedTextAlignment",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSJustifiedTextAlignment"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSJustifiedTextAlignment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSJustifiedTextAlignment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTextAlignment",
              "text": "NSTextAlignment"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSJustifiedTextAlignment"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCenterTextAlignment": {
      "abstract": [
        {
          "text": "Text is visually center-aligned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCenterTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCenterTextAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCenterTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nscentertextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSJustifiedTextAlignment": {
      "abstract": [
        {
          "text": "Text is justified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSJustifiedTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSJustifiedTextAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSJustifiedTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nsjustifiedtextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftTextAlignment": {
      "abstract": [
        {
          "text": "Text is visually left-aligned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftTextAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nslefttextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNaturalTextAlignment": {
      "abstract": [
        {
          "text": "Text uses the default alignment for the current localization of the app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNaturalTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNaturalTextAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNaturalTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nsnaturaltextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightTextAlignment": {
      "abstract": [
        {
          "text": "Text is visually right-aligned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightTextAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nsrighttextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/justified": {
      "abstract": [
        {
          "text": "Text is justified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "justified"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment/justified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignmentJustified"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment.justified",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment/justified"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLeftTextAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSRightTextAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSCenterTextAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSNaturalTextAlignment"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/title",
          "value": "NSTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1justified/title",
          "value": "NSTextAlignmentJustified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment~1justified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignmentJustified"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsjustifiedtextalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
