{
  "abstract": [
    {
      "text": "A rectangular area that can interact with Auto Layout.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSLayoutGuide",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSLayoutGuide"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLayoutGuide"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSLayoutGuide"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSLayoutGuide"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use layout guides to replace the placeholder views you may have created to represent inter-view spaces or encapsulation in your user interface. Traditionally, there were a number of Auto Layout techniques that required placeholder views. A placeholder view is an empty view that does not have any visual elements of its own and serves only to define a rectangular region in the view hierarchy. For example, if you wanted to use constraints to define the size or location of an empty space between views, you needed to use a placeholder view to represent that space. If you wanted to center a group of objects, you needed a placeholder view to contain those objects. Similarly, placeholder views could be used to contain and encapsulate part of your user interface. Placeholder views let you break up a large, complex user interface into self-contained, modular chunks. When used properly, they could greatly simplify your Auto Layout constraint logic.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are a number of costs associated with adding placeholder views to your view hierarchy. First, there is the cost of creating and maintaining the view itself. Second, the placeholder view is a full member of the view hierarchy, which means that it adds overhead to every task the hierarchy performs. Worst of all, the invisible placeholder view can intercept messages that are intended for other views, causing problems that are very difficult to find.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class is designed to perform all the tasks previously performed by placeholder views, but to do it in a safer, more efficient manner. Layout guides are not views. They do not use as much memory, and they do not participate in the view hierarchy. Instead, they simply define a rectangular region in their owning view’s coordinate system that can interact with Auto Layout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Creating-Layout-Guides",
          "level": 3,
          "text": "Creating Layout Guides",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To create a layout guide, perform the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instantiate a new layout guide.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the layout guide to a view by calling the view’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/addLayoutGuide(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method .",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Define the position and size of the layout guide using Auto Layout.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can use these guides to define the space between elements in your layout. The following example shows how to use layout guides to define an equal spacing between a series of views.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let space1 = NSLayoutGuide()",
                    "view.addLayoutGuide(space1)",
                    " ",
                    "let space2 = NSLayoutGuide()",
                    "view.addLayoutGuide(space2)",
                    " ",
                    "space1.widthAnchor.constraintEqualToAnchor(space2.widthAnchor).active = true",
                    "saveButton.trailingAnchor.constraintEqualToAnchor(space1.leadingAnchor).active = true",
                    "cancelButton.leadingAnchor.constraintEqualToAnchor(space1.trailingAnchor).active = true",
                    "cancelButton.trailingAnchor.constraintEqualToAnchor(space2.leadingAnchor).active = true",
                    "clearButton.leadingAnchor.constraintEqualToAnchor(space2.trailingAnchor).active = true"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSLayoutGuide *space1 = [[NSLayoutGuide alloc]init];",
                    "[self.view addLayoutGuide:space1];",
                    " ",
                    "NSLayoutGuide *space2 = [[NSLayoutGuide alloc] init];",
                    "[self.view addLayoutGuide:space2];",
                    " ",
                    "[space1.widthAnchor constraintEqualToAnchor:space2.widthAnchor].active = YES;",
                    "[self.saveButton.trailingAnchor constraintEqualToAnchor:space1.leadingAnchor].active = YES;",
                    "[self.cancelButton.leadingAnchor constraintEqualToAnchor:space1.trailingAnchor].active = YES;",
                    "[self.cancelButton.trailingAnchor constraintEqualToAnchor:space2.leadingAnchor].active = YES;",
                    "[self.clearButton.leadingAnchor constraintEqualToAnchor:space2.trailingAnchor].active = YES;"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "A layout guide can also act as an opaque box that contains other views and controls, letting you encapsulate parts of your view and break up your layout into modular chunks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let container = NSLayoutGuide()",
                    "view.addLayoutGuide(container)",
                    " ",
                    "// Layout the contents of the container",
                    "button.lastBaselineAnchor.constraintEqualToAnchor(textField.lastBaselineAnchor).active = true",
                    "button.leadingAnchor.constraintEqualToAnchor(container.leadingAnchor).active = true",
                    "textField.leadingAnchor.constraintEqualToAnchor(button.trailingAnchor, constant: 8.0).active = true",
                    "textField.trailingAnchor.constraintEqualToAnchor(container.trailingAnchor).active = true",
                    "textField.topAnchor.constraintEqualToAnchor(container.topAnchor).active = true",
                    "textField.bottomAnchor.constraintEqualToAnchor(container.bottomAnchor).active = true",
                    " ",
                    "// Set exterior constraints.",
                    "container.leadingAnchor.constraintEqualToAnchor(margins.leadingAnchor).active = true",
                    "container.trailingAnchor.constraintEqualToAnchor(margins.trailingAnchor).asctive = true",
                    "container.topAnchor.constraintEqualToAnchor(margins.topAnchor).active = true"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSLayoutGuide *container = [[NSLayoutGuide alloc] init];",
                    "[self.view addLayoutGuide:container];",
                    " ",
                    "// Layout the contents of the container",
                    "[self.button.lastBaselineAnchor constraintEqualToAnchor:self.textField.lastBaselineAnchor].active = YES;",
                    "[self.textField.leadingAnchor constraintEqualToAnchor:self.button.trailingAnchor constant:8.0].active = YES;",
                    "[self.textField.trailingAnchor constraintEqualToAnchor:container.trailingAnchor].active = YES;",
                    "[self.textField.topAnchor constraintEqualToAnchor:container.topAnchor].active = YES;",
                    "[self.textField.bottomAnchor constraintEqualToAnchor:container.bottomAnchor].active = YES;",
                    " ",
                    "// Set exterior constraints.",
                    " ",
                    "[container.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor constant:20.0].active = YES;",
                    "[container.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor constant:20.0].active = YES;",
                    "[container.topAnchor constraintEqualToAnchor:self.view.topAnchor constant:20.0].active = YES;"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Layout constraints do not fully encapsulate their contents. The system still compares the priority of optional constraints inside the layout guide with the priority of optional constraints outside the guide.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutDimension": {
      "abstract": [
        {
          "text": "A factory class for creating size-based layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutDimension"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutDimension",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutdimension"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide": {
      "abstract": [
        {
          "text": "A rectangular area that can interact with Auto Layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutGuide"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutGuide",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/bottomAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the bottom edge of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/bottomAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bottomAnchor"
        }
      ],
      "role": "symbol",
      "title": "bottomAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/bottomanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/centerXAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the horizontal center of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerXAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/centerXAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerXAnchor"
        }
      ],
      "role": "symbol",
      "title": "centerXAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/centerxanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/centerYAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the vertical center of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerYAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/centerYAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerYAnchor"
        }
      ],
      "role": "symbol",
      "title": "centerYAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/centeryanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/constraintsAffectingLayout(for:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraintsAffectingLayout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutConstraintOrientation",
          "text": "Orientation"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/constraintsAffectingLayout(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintsAffectingLayoutForOrientation:"
        }
      ],
      "role": "symbol",
      "title": "constraintsAffectingLayout(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/constraintsaffectinglayout(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/frame": {
      "abstract": [
        {
          "text": "The layout guide’s frame in its owning view’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/frame"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/hasAmbiguousLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasAmbiguousLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/hasAmbiguousLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasAmbiguousLayout"
        }
      ],
      "role": "symbol",
      "title": "hasAmbiguousLayout",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/hasambiguouslayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/heightAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the height of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heightAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutDimension",
          "text": "NSLayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/heightAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "heightAnchor"
        }
      ],
      "role": "symbol",
      "title": "heightAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/heightanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/identifier": {
      "abstract": [
        {
          "text": "A string used to identify the layout guide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSUserInterfaceItemIdentifier",
          "text": "NSUserInterfaceItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/identifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/leadingAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the leading edge of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leadingAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/leadingAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leadingAnchor"
        }
      ],
      "role": "symbol",
      "title": "leadingAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/leadinganchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/leftAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the left edge of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/leftAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftAnchor"
        }
      ],
      "role": "symbol",
      "title": "leftAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/leftanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/owningView": {
      "abstract": [
        {
          "text": "The view that owns this layout guide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "owningView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/owningView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "owningView"
        }
      ],
      "role": "symbol",
      "title": "owningView",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/owningview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/rightAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the right edge of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/rightAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightAnchor"
        }
      ],
      "role": "symbol",
      "title": "rightAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/rightanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/topAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the top edge of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/topAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "topAnchor"
        }
      ],
      "role": "symbol",
      "title": "topAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/topanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/trailingAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the trailing edge of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/trailingAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingAnchor"
        }
      ],
      "role": "symbol",
      "title": "trailingAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/trailinganchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/widthAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the width of the layout guide’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widthAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutDimension",
          "text": "NSLayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/widthAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widthAnchor"
        }
      ],
      "role": "symbol",
      "title": "widthAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide/widthanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfaceitemidentification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/addLayoutGuide(_:)": {
      "abstract": [
        {
          "text": "Adds the provided layout guide to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addLayoutGuide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutGuide",
          "text": "NSLayoutGuide"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/addLayoutGuide(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addLayoutGuide:"
        }
      ],
      "role": "symbol",
      "title": "addLayoutGuide(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/addlayoutguide(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Layout-Guides",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutDimension"
      ],
      "title": "Layout Guides"
    }
  ],
  "topicSections": [
    {
      "anchor": "Working-With-Layout-Guides",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/identifier",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/frame",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/owningView"
      ],
      "title": "Working With Layout Guides"
    },
    {
      "anchor": "Creating-Constraints-Using-Layout-Anchors",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/bottomAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/centerXAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/centerYAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/heightAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/leadingAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/leftAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/rightAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/topAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/trailingAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/widthAnchor"
      ],
      "title": "Creating Constraints Using Layout Anchors"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/hasAmbiguousLayout"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/constraintsAffectingLayout(for:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Working-With-Layout-Guides",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/identifier",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/frame",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/owningView"
              ],
              "title": "Working With Layout Guides"
            },
            {
              "anchor": "Creating-Constraints-Using-Layout-Anchors",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/bottomAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/centerXAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/centerYAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/heightAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/leadingAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/leftAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/rightAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/topAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/trailingAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/widthAnchor"
              ],
              "title": "Creating Constraints Using Layout Anchors"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/hasAmbiguousLayout"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide/constraintsAffectingLayout(for:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Layout-Guides",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutDimension"
              ],
              "title": "Layout Guides"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSLayoutGuide"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1bottomAnchor/title",
          "value": "bottomAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1bottomAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bottomAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1constraintsAffectingLayout(for:)/title",
          "value": "constraintsAffectingLayoutForOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1constraintsAffectingLayout(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "constraintsAffectingLayoutForOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1topAnchor/title",
          "value": "topAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1topAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "topAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1hasAmbiguousLayout/title",
          "value": "hasAmbiguousLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1hasAmbiguousLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasAmbiguousLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1leftAnchor/title",
          "value": "leftAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1leftAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1widthAnchor/title",
          "value": "widthAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1widthAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widthAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1heightAnchor/title",
          "value": "heightAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1heightAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "heightAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide/title",
          "value": "NSLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1trailingAnchor/title",
          "value": "trailingAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1trailingAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1centerYAnchor/title",
          "value": "centerYAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1centerYAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerYAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1centerXAnchor/title",
          "value": "centerXAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1centerXAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerXAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutDimension/title",
          "value": "NSLayoutDimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutDimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutDimension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1rightAnchor/title",
          "value": "rightAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1rightAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1owningView/title",
          "value": "owningView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1owningView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "owningView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title",
          "value": "NSUserInterfaceItemIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addLayoutGuide(_:)/title",
          "value": "addLayoutGuide:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addLayoutGuide(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addLayoutGuide:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1leadingAnchor/title",
          "value": "leadingAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide~1leadingAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leadingAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslayoutguide"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nslayoutguide"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
