{
  "abstract": [
    {
      "text": "Values that describe the progression of text on a page.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSLineSweepDirection",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSLineSweepDirection"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLineSweepDirection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSLineSweepDirection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSLineSweepDirection"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The typesetter decides which way text should flow and passes these values as arguments to the text container, which uses them to calculate the next line rectangle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Line sweep is the direction text progresses within a line. See ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/TextStorageLayer/TextStorageLayer.html#//apple_ref/doc/uid/10000087i",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The only values currently used by the supplied typesetters are ",
              "type": "text"
            },
            {
              "code": "NSLineSweepRight",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "NSLineMovesDown",
              "type": "codeVoice"
            },
            {
              "text": ". An ",
              "type": "text"
            },
            {
              "code": "NSTextContainer",
              "type": "codeVoice"
            },
            {
              "text": " subclass should be able to deal with any value, and an ",
              "type": "text"
            },
            {
              "code": "NSTypesetter",
              "type": "codeVoice"
            },
            {
              "text": " subclass should be able to use any of them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSATSTypesetter": {
      "abstract": [
        {
          "text": "A concrete typesetter object that places glyphs during the text layout process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSATSTypesetter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSATSTypesetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSATSTypesetter"
        }
      ],
      "role": "symbol",
      "title": "NSATSTypesetter",
      "type": "topic",
      "url": "/documentation/appkit/nsatstypesetter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager": {
      "abstract": [
        {
          "text": "An object that coordinates the layout and display of text characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineMovementDirection": {
      "abstract": [
        {
          "text": "The direction in which a line moves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineMovementDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineMovementDirection",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineMovementDirection",
      "type": "topic",
      "url": "/documentation/appkit/nslinemovementdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection": {
      "abstract": [
        {
          "text": "Values that describe the progression of text on a page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineSweepDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineSweepDirection",
      "type": "topic",
      "url": "/documentation/appkit/nslinesweepdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepDown": {
      "abstract": [
        {
          "text": "Characters move from top to bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineSweepDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineSweepDown",
      "type": "topic",
      "url": "/documentation/appkit/nslinesweepdirection/nslinesweepdown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepLeft": {
      "abstract": [
        {
          "text": "Characters move from right to left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineSweepLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepLeft",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineSweepLeft",
      "type": "topic",
      "url": "/documentation/appkit/nslinesweepdirection/nslinesweepleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepRight": {
      "abstract": [
        {
          "text": "Characters move from left to right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineSweepRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepRight",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineSweepRight",
      "type": "topic",
      "url": "/documentation/appkit/nslinesweepdirection/nslinesweepright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepUp": {
      "abstract": [
        {
          "text": "Characters move from bottom to top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineSweepUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineSweepUp",
      "type": "topic",
      "url": "/documentation/appkit/nslinesweepdirection/nslinesweepup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextStorage": {
      "abstract": [
        {
          "text": "The fundamental storage mechanism of TextKit that contains the text managed by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextStorage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextStorage"
        }
      ],
      "role": "symbol",
      "title": "NSTextStorage",
      "type": "topic",
      "url": "/documentation/appkit/nstextstorage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTypesetter": {
      "abstract": [
        {
          "text": "An abstract class that performs various type layout tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTypesetter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTypesetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTypesetter"
        }
      ],
      "role": "symbol",
      "title": "NSTypesetter",
      "type": "topic",
      "url": "/documentation/appkit/nstypesetter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/TextStorageLayer/TextStorageLayer.html#//apple_ref/doc/uid/10000087i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/TextStorageLayer/TextStorageLayer.html#//apple_ref/doc/uid/10000087i",
      "title": "Text System Storage Layer Overview",
      "titleInlineContent": [
        {
          "text": "Text System Storage Layer Overview",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/TextStorageLayer/TextStorageLayer.html#//apple_ref/doc/uid/10000087i"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "TextKit-1",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextStorage",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager",
        "doc://com.apple.appkit/documentation/AppKit/NSATSTypesetter",
        "doc://com.apple.appkit/documentation/AppKit/NSTypesetter",
        "doc://com.apple.appkit/documentation/AppKit/NSLineMovementDirection"
      ],
      "title": "TextKit 1"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepLeft",
        "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepRight",
        "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepDown",
        "doc://com.apple.appkit/documentation/AppKit/NSLineSweepDirection/NSLineSweepUp"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextStorage/title",
          "value": "NSTextStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/title",
          "value": "NSLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSATSTypesetter/title",
          "value": "NSATSTypesetter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSATSTypesetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSATSTypesetter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSATSTypesetter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSATSTypesetter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypesetter/title",
          "value": "NSTypesetter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypesetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTypesetter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTypesetter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslinesweepdirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
