{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum/linear",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLinearSlider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSLinearSlider",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSLinearSlider"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLinearSlider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSLinearSlider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSSliderType",
              "text": "NSSliderType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSLinearSlider"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A bar representing a range, and a knob indicating the currently selected value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCircularSlider": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCircularSlider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCircularSlider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCircularSlider",
      "type": "topic",
      "url": "/documentation/appkit/nscircularslider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLinearSlider": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLinearSlider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLinearSlider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLinearSlider",
      "type": "topic",
      "url": "/documentation/appkit/nslinearslider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum": {
      "abstract": [
        {
          "text": "The types of sliders, used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SliderType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SliderType"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.SliderType",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/slidertype-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum/circular": {
      "abstract": [
        {
          "text": "A dial representing an angular range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circular"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum/circular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSliderTypeCircular"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.SliderType.circular",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/slidertype-swift.enum/circular"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum/linear": {
      "abstract": [
        {
          "text": "A bar representing a range, and a knob indicating the currently selected value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSliderTypeLinear"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.SliderType.linear",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/slidertype-swift.enum/linear"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType": {
      "abstract": [
        {
          "text": "The slider type, either linear or circular.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sliderType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSliderType",
          "text": "SliderType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sliderType"
        }
      ],
      "role": "symbol",
      "title": "sliderType",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/slidertype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum/circular",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum/linear",
        "doc://com.apple.appkit/documentation/AppKit/NSCircularSlider"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1sliderType/title",
          "value": "sliderType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1sliderType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sliderType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum~1circular/title",
          "value": "NSSliderTypeCircular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum~1circular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderTypeCircular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum~1linear/title",
          "value": "NSSliderTypeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderTypeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/title",
          "value": "NSSliderType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslinearslider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
