{
  "abstract": [
    {
      "text": "Constants that specify what happens when a line is too long for a container.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSLineBreakMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSLineBreakMode"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLineBreakMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSLineBreakMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode": {
      "abstract": [
        {
          "text": "Constants that specify what happens when a line is too long for a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byCharWrapping": {
      "abstract": [
        {
          "text": "The value that indicates wrapping occurs before the first character that doesn’t fit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byCharWrapping"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byCharWrapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakByCharWrapping"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode.byCharWrapping",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode/bycharwrapping"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byClipping": {
      "abstract": [
        {
          "text": "The value that indicates lines don’t extend past the edge of the text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byClipping"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakByClipping"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode.byClipping",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode/byclipping"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingHead": {
      "abstract": [
        {
          "text": "The value that indicates that a line displays so that the end fits in the container and an ellipsis glyph indicates the missing text at the beginning of the line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byTruncatingHead"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakByTruncatingHead"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode.byTruncatingHead",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode/bytruncatinghead"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingMiddle": {
      "abstract": [
        {
          "text": "The value that indicates that a line displays so that the beginning and end fit in the container and an ellipsis glyph indicates the missing text in the middle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byTruncatingMiddle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingMiddle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakByTruncatingMiddle"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode.byTruncatingMiddle",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode/bytruncatingmiddle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingTail": {
      "abstract": [
        {
          "text": "The value that indicates a line displays so that the beginning fits in the container and an ellipsis glyph indicates the missing text at the end of the line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byTruncatingTail"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingTail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakByTruncatingTail"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode.byTruncatingTail",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode/bytruncatingtail"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byWordWrapping": {
      "abstract": [
        {
          "text": "The value that indicates wrapping occurs at word boundaries, unless the word doesn’t fit on a single line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byWordWrapping"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byWordWrapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakByWordWrapping"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode.byWordWrapping",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode/bywordwrapping"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/LineBreakStrategy-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify how the text system breaks lines while laying out paragraphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineBreakStrategy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineBreakStrategy"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.LineBreakStrategy",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/linebreakstrategy-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/allowsDefaultTighteningForTruncation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system tightens character spacing before truncating text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDefaultTighteningForTruncation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/allowsDefaultTighteningForTruncation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsDefaultTighteningForTruncation"
        }
      ],
      "role": "symbol",
      "title": "allowsDefaultTighteningForTruncation",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/allowsdefaulttighteningfortruncation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/hyphenationFactor": {
      "abstract": [
        {
          "text": "The paragraph’s threshold for hyphenation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hyphenationFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/hyphenationFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hyphenationFactor"
        }
      ],
      "role": "symbol",
      "title": "hyphenationFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/hyphenationfactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode for breaking lines in the paragraph that don’t fit within a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/linebreakmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakStrategy-swift.property": {
      "abstract": [
        {
          "text": "The strategy for breaking lines while laying out paragraphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakStrategy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
          "text": "NSParagraphStyle"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakStrategy",
          "text": "LineBreakStrategy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakStrategy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakStrategy"
        }
      ],
      "role": "symbol",
      "title": "lineBreakStrategy",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/linebreakstrategy-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tighteningFactorForTruncation": {
      "abstract": [
        {
          "text": "The threshold for using tightening as an alternative to truncation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tighteningFactorForTruncation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tighteningFactorForTruncation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tighteningFactorForTruncation"
        }
      ],
      "role": "symbol",
      "title": "tighteningFactorForTruncation",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/tighteningfactorfortruncation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/usesDefaultHyphenation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the paragraph style uses the system hyphenation settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesDefaultHyphenation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/usesDefaultHyphenation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesDefaultHyphenation"
        }
      ],
      "role": "symbol",
      "title": "usesDefaultHyphenation",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/usesdefaulthyphenation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-line-break-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakMode",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakStrategy-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/hyphenationFactor",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/usesDefaultHyphenation",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tighteningFactorForTruncation",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/allowsDefaultTighteningForTruncation"
      ],
      "title": "Getting line-break information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byWordWrapping",
        "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byCharWrapping",
        "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byClipping",
        "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingHead",
        "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingTail",
        "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingMiddle"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byWordWrapping",
                "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byCharWrapping",
                "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byClipping",
                "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingHead",
                "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingTail",
                "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode/byTruncatingMiddle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-line-break-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakMode",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakStrategy-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/hyphenationFactor",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/usesDefaultHyphenation",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tighteningFactorForTruncation",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/allowsDefaultTighteningForTruncation"
              ],
              "title": "Getting line-break information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSLineBreakMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineBreakMode/title",
          "value": "lineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byCharWrapping/title",
          "value": "NSLineBreakByCharWrapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byCharWrapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakByCharWrapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1hyphenationFactor/title",
          "value": "hyphenationFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1hyphenationFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hyphenationFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byTruncatingHead/title",
          "value": "NSLineBreakByTruncatingHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byTruncatingHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakByTruncatingHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tighteningFactorForTruncation/title",
          "value": "tighteningFactorForTruncation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tighteningFactorForTruncation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tighteningFactorForTruncation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byWordWrapping/title",
          "value": "NSLineBreakByWordWrapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byWordWrapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakByWordWrapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1usesDefaultHyphenation/title",
          "value": "usesDefaultHyphenation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1usesDefaultHyphenation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesDefaultHyphenation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byTruncatingMiddle/title",
          "value": "NSLineBreakByTruncatingMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byTruncatingMiddle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakByTruncatingMiddle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1allowsDefaultTighteningForTruncation/title",
          "value": "allowsDefaultTighteningForTruncation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1allowsDefaultTighteningForTruncation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsDefaultTighteningForTruncation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byTruncatingTail/title",
          "value": "NSLineBreakByTruncatingTail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byTruncatingTail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakByTruncatingTail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineBreakStrategy-swift.property/title",
          "value": "lineBreakStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineBreakStrategy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode/title",
          "value": "NSLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/title",
          "value": "NSLineBreakStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byClipping/title",
          "value": "NSLineBreakByClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode~1byClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakByClipping"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslinebreakmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nslinebreakmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
