{
  "abstract": [
    {
      "text": "An object that handles the measurement and display of a single menu item in its encompassing frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSMenuItemCell",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSMenuItemCell"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMenuItemCell"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSMenuItemCell"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "NSMenuItemCell",
                  "type": "codeVoice"
                },
                {
                  "text": " is no longer used to draw menus. Using it does not affect the appearance of your menus.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityelementprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell": {
      "abstract": [
        {
          "text": "An object that defines the user interface of a button or other clickable region of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButtonCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonCell"
        }
      ],
      "role": "symbol",
      "title": "NSButtonCell",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep": {
      "abstract": [
        {
          "text": "An object that stores image data in a form that can be readily transferred to the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCachedImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCachedImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nscachedimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawer": {
      "abstract": [
        {
          "text": "A user interface element that contains and displays text, scroll, and browser views, in addition to other view subclasses.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawer"
        }
      ],
      "role": "symbol",
      "title": "NSDrawer",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSForm": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSForm",
          "type": "codeVoice"
        },
        {
          "text": " object is a vertical matrix of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects to implement the fields.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSForm"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSForm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSForm"
        }
      ],
      "role": "symbol",
      "title": "NSForm",
      "type": "topic",
      "url": "/documentation/appkit/nsform"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSFormCell",
          "type": "codeVoice"
        },
        {
          "text": " class is used to implement text entry fields in a form. The left part of an ",
          "type": "text"
        },
        {
          "code": "NSFormCell",
          "type": "codeVoice"
        },
        {
          "text": " object contains a title. The right part contains an editable text entry field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFormCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFormCell"
        }
      ],
      "role": "symbol",
      "title": "NSFormCell",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInputManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInputManager",
      "type": "topic",
      "url": "/documentation/appkit/nsinputmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInputServer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInputServer",
      "type": "topic",
      "url": "/documentation/appkit/nsinputserver"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell": {
      "abstract": [
        {
          "text": "An object that handles the measurement and display of a single menu item in its encompassing frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItemCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItemCell"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItemCell",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/calcSize()": {
      "abstract": [
        {
          "text": "Calculates the minimum required width and height of the receiver’s menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calcSize"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/calcSize()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calcSize"
        }
      ],
      "role": "symbol",
      "title": "calcSize()",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/calcsize()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawBorderAndBackground(withFrame:in:)": {
      "abstract": [
        {
          "text": "Draws the borders and background associated with the receiver’s menu item (if any).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawBorderAndBackground"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawBorderAndBackground(withFrame:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawBorderAndBackgroundWithFrame:inView:"
        }
      ],
      "role": "symbol",
      "title": "drawBorderAndBackground(withFrame:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/drawborderandbackground(withframe:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawImage(withFrame:in:)": {
      "abstract": [
        {
          "text": "Draws the image associated with the menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawImage(withFrame:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawImageWithFrame:inView:"
        }
      ],
      "role": "symbol",
      "title": "drawImage(withFrame:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/drawimage(withframe:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawKeyEquivalent(withFrame:in:)": {
      "abstract": [
        {
          "text": "Draws the key equivalent associated with the menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawKeyEquivalent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawKeyEquivalent(withFrame:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawKeyEquivalentWithFrame:inView:"
        }
      ],
      "role": "symbol",
      "title": "drawKeyEquivalent(withFrame:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/drawkeyequivalent(withframe:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawSeparatorItem(withFrame:in:)": {
      "abstract": [
        {
          "text": "Draws a menu item separator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawSeparatorItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawSeparatorItem(withFrame:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawSeparatorItemWithFrame:inView:"
        }
      ],
      "role": "symbol",
      "title": "drawSeparatorItem(withFrame:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/drawseparatoritem(withframe:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawStateImage(withFrame:in:)": {
      "abstract": [
        {
          "text": "Draws the state image associated with the menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawStateImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawStateImage(withFrame:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawStateImageWithFrame:inView:"
        }
      ],
      "role": "symbol",
      "title": "drawStateImage(withFrame:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/drawstateimage(withframe:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawTitle(withFrame:in:)": {
      "abstract": [
        {
          "text": "Draws the title associated with the menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawTitle(withFrame:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawTitleWithFrame:inView:"
        }
      ],
      "role": "symbol",
      "title": "drawTitle(withFrame:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/drawtitle(withframe:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/imageWidth": {
      "abstract": [
        {
          "text": "The width of the image associated with the menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/imageWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWidth"
        }
      ],
      "role": "symbol",
      "title": "imageWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/imagewidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/init(coder:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/init(coder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/init(textCell:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "textCell"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/init(textCell:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initTextCell:"
        }
      ],
      "role": "symbol",
      "title": "init(textCell:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/init(textcell:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/keyEquivalentRect(forBounds:)": {
      "abstract": [
        {
          "text": "Returns the rectangle into which the menu item’s key equivalent should be drawn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyEquivalentRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/keyEquivalentRect(forBounds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyEquivalentRectForBounds:"
        }
      ],
      "role": "symbol",
      "title": "keyEquivalentRect(forBounds:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/keyequivalentrect(forbounds:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/keyEquivalentWidth": {
      "abstract": [
        {
          "text": "The width of the menu item’s key equivalent string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyEquivalentWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/keyEquivalentWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyEquivalentWidth"
        }
      ],
      "role": "symbol",
      "title": "keyEquivalentWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/keyequivalentwidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/menuItem": {
      "abstract": [
        {
          "text": "The menu item object associated with the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenuItem",
          "text": "NSMenuItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/menuItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuItem"
        }
      ],
      "role": "symbol",
      "title": "menuItem",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/menuitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/needsDisplay": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the menu item needs to be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needsDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/needsDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "needsDisplay"
        }
      ],
      "role": "symbol",
      "title": "needsDisplay",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/needsdisplay"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/needsSizing": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the size of the menu needs to be calculated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needsSizing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/needsSizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "needsSizing"
        }
      ],
      "role": "symbol",
      "title": "needsSizing",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/needssizing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/stateImageRect(forBounds:)": {
      "abstract": [
        {
          "text": "Returns the rectangle into which the menu item’s state image should be drawn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateImageRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/stateImageRect(forBounds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stateImageRectForBounds:"
        }
      ],
      "role": "symbol",
      "title": "stateImageRect(forBounds:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/stateimagerect(forbounds:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/stateImageWidth": {
      "abstract": [
        {
          "text": "The width of the image used to indicate the state of the menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateImageWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/stateImageWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stateImageWidth"
        }
      ],
      "role": "symbol",
      "title": "stateImageWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/stateimagewidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/tag": {
      "abstract": [
        {
          "text": "The integer tag of the selected menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/tag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tag"
        }
      ],
      "role": "symbol",
      "title": "tag",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/tag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/titleRect(forBounds:)": {
      "abstract": [
        {
          "text": "Returns the rectangle into which the menu item’s title should be drawn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/titleRect(forBounds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleRectForBounds:"
        }
      ],
      "role": "symbol",
      "title": "titleRect(forBounds:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/titlerect(forbounds:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/titleWidth": {
      "abstract": [
        {
          "text": "The width of the menu item’s text, measured in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/titleWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleWidth"
        }
      ],
      "role": "symbol",
      "title": "titleWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell/titlewidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMovie": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMovie"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMovie",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMovie",
      "type": "topic",
      "url": "/documentation/appkit/nsmovie"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext": {
      "abstract": [
        {
          "text": "An object that represents an OpenGL graphics context, into which all OpenGL calls are rendered.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLContext"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLContext",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer": {
      "abstract": [
        {
          "text": "A subclass of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that is suitable for rendering OpenGL into layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLLayer"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsopengllayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer": {
      "abstract": [
        {
          "text": "An object that provides access to accelerated offscreen rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLPixelBuffer",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelbuffer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat": {
      "abstract": [
        {
          "text": "An object that specifies the types of buffers and other attributes of the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLPixelFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView": {
      "abstract": [
        {
          "text": "A view that displays OpenGL content in a view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLView"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLView",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSPopUpButtonCell",
          "type": "codeVoice"
        },
        {
          "text": " class defines the visual appearance of pop-up buttons that display pop-up or pull-down menus. Pop-up menus present the user with a set of choices, much the way radio buttons do, but using much less space. Pull-down menus also provide a set of choices but present the information in a slightly different way, usually to provide a set of commands from which the user can choose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPopUpButtonCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopUpButtonCell"
        }
      ],
      "role": "symbol",
      "title": "NSPopUpButtonCell",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbuttoncell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfaceitemidentification"
    },
    "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer": {
      "abstract": [
        {
          "text": "A layer that provides a layer suitable for rendering OpenGL content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAOpenGLLayer",
      "type": "topic",
      "url": "/documentation/QuartzCore/CAOpenGLLayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButtonCell"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
        "doc://com.apple.appkit/documentation/AppKit/NSForm",
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/init(coder:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/init(textCell:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Configuring-Menu-Item-Attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/menuItem"
      ],
      "title": "Configuring Menu-Item Attributes"
    },
    {
      "anchor": "Calculating-the-Size-of-a-Menu-Item",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/calcSize()",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/needsSizing",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/imageWidth",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/titleWidth",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/keyEquivalentWidth",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/stateImageWidth"
      ],
      "title": "Calculating the Size of a Menu Item"
    },
    {
      "anchor": "Getting-the-Menu-Items-Drawing-Rectangle",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/keyEquivalentRect(forBounds:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/stateImageRect(forBounds:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/titleRect(forBounds:)"
      ],
      "title": "Getting the Menu Item’s Drawing Rectangle"
    },
    {
      "anchor": "Drawing-the-Menu-Item",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawBorderAndBackground(withFrame:in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawImage(withFrame:in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawKeyEquivalent(withFrame:in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawSeparatorItem(withFrame:in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawStateImage(withFrame:in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawTitle(withFrame:in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/needsDisplay"
      ],
      "title": "Drawing the Menu Item"
    },
    {
      "anchor": "Assigning-a-Tag",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/tag"
      ],
      "title": "Assigning a Tag"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSMenuItemCell"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/init(coder:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/init(textCell:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Configuring-Menu-Item-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/menuItem"
              ],
              "title": "Configuring Menu-Item Attributes"
            },
            {
              "anchor": "Calculating-the-Size-of-a-Menu-Item",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/calcSize()",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/needsSizing",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/imageWidth",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/titleWidth",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/keyEquivalentWidth",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/stateImageWidth"
              ],
              "title": "Calculating the Size of a Menu Item"
            },
            {
              "anchor": "Getting-the-Menu-Items-Drawing-Rectangle",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/keyEquivalentRect(forBounds:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/stateImageRect(forBounds:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/titleRect(forBounds:)"
              ],
              "title": "Getting the Menu Item’s Drawing Rectangle"
            },
            {
              "anchor": "Drawing-the-Menu-Item",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawBorderAndBackground(withFrame:in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawImage(withFrame:in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawKeyEquivalent(withFrame:in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawSeparatorItem(withFrame:in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawStateImage(withFrame:in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/drawTitle(withFrame:in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/needsDisplay"
              ],
              "title": "Drawing the Menu Item"
            },
            {
              "anchor": "Assigning-a-Tag",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell/tag"
              ],
              "title": "Assigning a Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButtonCell"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButtonCell"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
                "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
                "doc://com.apple.appkit/documentation/AppKit/NSForm",
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
                "doc://com.apple.appkit/documentation/AppKit/NSInputManager",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServer",
                "doc://com.apple.appkit/documentation/AppKit/NSMovie"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSMenuItemCell"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSButtonCell",
                    "text": "NSButtonCell"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawBorderAndBackground(withFrame:in:)/title",
          "value": "drawBorderAndBackgroundWithFrame:inView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawBorderAndBackground(withFrame:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawBorderAndBackgroundWithFrame:inView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1stateImageRect(forBounds:)/title",
          "value": "stateImageRectForBounds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1stateImageRect(forBounds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stateImageRectForBounds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1titleRect(forBounds:)/title",
          "value": "titleRectForBounds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1titleRect(forBounds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "titleRectForBounds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/title",
          "value": "NSOpenGLContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1keyEquivalentRect(forBounds:)/title",
          "value": "keyEquivalentRectForBounds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1keyEquivalentRect(forBounds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "keyEquivalentRectForBounds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawTitle(withFrame:in:)/title",
          "value": "drawTitleWithFrame:inView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawTitle(withFrame:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawTitleWithFrame:inView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title",
          "value": "NSUserInterfaceItemIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1calcSize()/title",
          "value": "calcSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1calcSize()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "calcSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1titleWidth/title",
          "value": "titleWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1titleWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/title",
          "value": "NSFormCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/title",
          "value": "NSMenuItemCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/title",
          "value": "NSOpenGLView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell/title",
          "value": "NSPopUpButtonCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpButtonCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButtonCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpButtonCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawKeyEquivalent(withFrame:in:)/title",
          "value": "drawKeyEquivalentWithFrame:inView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawKeyEquivalent(withFrame:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawKeyEquivalentWithFrame:inView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawSeparatorItem(withFrame:in:)/title",
          "value": "drawSeparatorItemWithFrame:inView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawSeparatorItem(withFrame:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawSeparatorItemWithFrame:inView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell/title",
          "value": "NSButtonCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1stateImageWidth/title",
          "value": "stateImageWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1stateImageWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stateImageWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1needsDisplay/title",
          "value": "needsDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1needsDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "needsDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/title",
          "value": "NSOpenGLLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawStateImage(withFrame:in:)/title",
          "value": "drawStateImageWithFrame:inView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawStateImage(withFrame:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawStateImageWithFrame:inView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1keyEquivalentWidth/title",
          "value": "keyEquivalentWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1keyEquivalentWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyEquivalentWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1needsSizing/title",
          "value": "needsSizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1needsSizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "needsSizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1QuartzCore~1CAOpenGLLayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAOpenGLLayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CALayer",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1tag/title",
          "value": "tag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1tag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/title",
          "value": "NSOpenGLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1menuItem/title",
          "value": "menuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1menuItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "menuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/title",
          "value": "NSForm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawImage(withFrame:in:)/title",
          "value": "drawImageWithFrame:inView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1drawImage(withFrame:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawImageWithFrame:inView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/title",
          "value": "NSDrawer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1imageWidth/title",
          "value": "imageWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1imageWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1init(textCell:)/title",
          "value": "initTextCell:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell~1init(textCell:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initTextCell:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmenuitemcell"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsmenuitemcell"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
