{
  "abstract": [
    {
      "text": "An object that configures and displays a Media Library Browser panel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSMediaLibraryBrowserController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSMediaLibraryBrowserController"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMediaLibraryBrowserController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSMediaLibraryBrowserController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMediaLibraryBrowserController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "From this panel a user can drag media  into views in their app. The class provides a standard interface to the MediaLibrary framework content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The Media Library Browser panel is not an ",
                  "type": "text"
                },
                {
                  "code": "NSPanel",
                  "type": "codeVoice"
                },
                {
                  "text": " instance.  It has panel like methods to remotely control the Media Library Browser.  Clients have no direct programmatic access to the panel displaying the Media Library Browser.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For more information see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaSource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaObject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Pasteboard-Types",
          "level": 3,
          "text": "Pasteboard Types",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Media Library Browser defines two pasteboard types for decoding the dragged content and retrieving the media content that is appropriate, one for mediagroup content and one for individual media items",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "com.apple.MediaLibrary.PboardType.MediaGroupIdentifiersPlist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " pasteboard type describes media group content and is published when the user drags items from the upper media-group-organized pane of the Media Library Browser.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "com.apple.MediaLibrary.PboardType.MediaObjectIdentifiersPlist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " pasteboard type describes individual media items and is published when the user drags media items such as images, movies, or sounds from the media item pane of the Media Library Browser.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "There is a third, less specialized, type of media library pasteboard. When the user initiates a drag the pasteboard will contain an array with one more more  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilenamesPboardType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " pasteboard items, one for each of the files within the group dragged from the media-group-organized pane, and one or more items when a media item or items are dragged from the media item pane.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you do not need access to the associated Media Library metadata, using the ",
              "type": "text"
            },
            {
              "code": "NSFilenamesPboardType",
              "type": "codeVoice"
            },
            {
              "text": " pasteboard data is the simplest means of retrieving the dragged content, although accessing the media in this manner when your app is sandboxed requires that you use the ",
              "type": "text"
            },
            {
              "code": "NSURL",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "The-Media-Group-Pasteboard-Type",
          "level": 4,
          "text": "The Media Group Pasteboard Type",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "\"com.apple.MediaLibrary.PboardType.MediaGroupIdentifiersPlist\"",
              "type": "codeVoice"
            },
            {
              "text": " pasteboard type is published when the user drags items from the upper media-group-organized pane of the Media Library Browser.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It consists of an ",
              "type": "text"
            },
            {
              "code": "NSDictionary",
              "type": "codeVoice"
            },
            {
              "text": " plist that contains",
              "type": "text"
            },
            {
              "code": "keys",
              "type": "codeVoice"
            },
            {
              "text": " with the media source identifiers and corresponding ",
              "type": "text"
            },
            {
              "code": "value",
              "type": "codeVoice"
            },
            {
              "text": " that are arrays of media group identifiers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To decode the pasteboard data and get ",
              "type": "text"
            },
            {
              "code": "MLMediaGroup",
              "type": "codeVoice"
            },
            {
              "text": " instances, assuming you have an ",
              "type": "text"
            },
            {
              "code": "MLMediaLibrary",
              "type": "codeVoice"
            },
            {
              "text": " instance, use the techniques illustrated in the code listing below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Retrieving MLMediaGroup instances from the pasteboard",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "NSDictionary *mediaGroupsDict = [dragPasteboard propertyListForType:@\"com.apple.MediaLibrary.PBoardType.MediaGroupIdentifiersPlist\"];",
            "    if ( mediaGroupsDict )",
            "    {",
            "        [s appendFormat:@\"Media Groups Dictionary: %@\\n\", mediaGroupsDict];",
            "        [s appendString:@\"Media Groups:\\n\"];",
            "        for ( NSString *sourceIdentifier in [mediaGroupsDict allKeys] )",
            "        {",
            "            MLTAppDelegate *appDelegate = (MLTAppDelegate *)[[NSApplication sharedApplication] delegate];",
            "            MLMediaLibrary *mediaLibrary = appDelegate.mediaLibrary;",
            "            MLMediaSource *mediaSource = [mediaLibrary.mediaSources objectForKey:sourceIdentifier];",
            "            if ( mediaSource )",
            "            {",
            "                NSArray *groupIdentifiers = [mediaGroupsDict objectForKey:sourceIdentifier];",
            "                for ( NSString *groupIdentifier in groupIdentifiers )",
            "                {",
            "                    MLMediaGroup *mediaGroup = [mediaSource mediaGroupForIdentifier:groupIdentifier];",
            "                    [s appendFormat:@\"%@\\n\", mediaGroup];",
            "                }",
            "            }",
            "        }",
            "    }"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "anchor": "The-Media-Object-Pasteboard-Type",
          "level": 4,
          "text": "The Media Object Pasteboard Type",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "\"com.apple.MediaLibrary.PboardType.MediaObjectIdentifiersPlist\"",
              "type": "codeVoice"
            },
            {
              "text": " pasteboard type is published when the user drags an item from the media item pane of the Media Library Browser.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It consists of an ",
              "type": "text"
            },
            {
              "code": "NSDictionary",
              "type": "codeVoice"
            },
            {
              "text": " plist that contains",
              "type": "text"
            },
            {
              "code": "keys",
              "type": "codeVoice"
            },
            {
              "text": " with the media source identifiers and corresponding ",
              "type": "text"
            },
            {
              "code": "value",
              "type": "codeVoice"
            },
            {
              "text": " that are arrays of media object identifiers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To decode the pasteboard data and get ",
              "type": "text"
            },
            {
              "code": "MLMediaObject",
              "type": "codeVoice"
            },
            {
              "text": " instances, assuming that you have an MLMediaLibrary instance, use the techniques illustrated in the code listing below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 2. Retrieving MLMediaObject instances from the pasteboard",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            " NSDictionary *mediaObjectsDict = [dragPasteboard propertyListForType:@\"com.apple.MediaLibrary.PBoardType.MediaObjectIdentifiersPlist\"];",
            "    if ( mediaObjectsDict )",
            "    {",
            "        [s appendFormat:@\"Media Objects Dictionary: %@\\n\", mediaObjectsDict];",
            "        [s appendString:@\"Media Objects:\\n\"];",
            "        for ( NSString *sourceIdentifier in [mediaObjectsDict allKeys] )",
            "        {",
            "            MLTAppDelegate *appDelegate = (MLTAppDelegate *)[[NSApplication sharedApplication] delegate];",
            "            MLMediaLibrary *mediaLibrary = appDelegate.mediaLibrary;",
            "            MLMediaSource *mediaSource = [mediaLibrary.mediaSources objectForKey:sourceIdentifier];",
            "            if ( mediaSource )",
            "            {",
            "                NSArray *objectIdentifiers = [mediaObjectsDict objectForKey:sourceIdentifier];",
            "                for ( NSString *objectIdentifier in objectIdentifiers )",
            "                {",
            "                    MLMediaObject *mediaObject = [mediaSource mediaObjectForIdentifier:objectIdentifier];",
            "                    [s appendFormat:@\"%@\\n\", mediaObject];",
            "                }",
            "            }",
            "        }",
            "    }"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFilenamesPboardType": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " objects designating one or more filenames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFilenamesPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilenamesPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFilenamesPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nsfilenamespboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController": {
      "abstract": [
        {
          "text": "An object that configures and displays a Media Library Browser panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMediaLibraryBrowserController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMediaLibraryBrowserController"
        }
      ],
      "role": "symbol",
      "title": "NSMediaLibraryBrowserController",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library": {
      "abstract": [
        {
          "text": "These constants are masks used to configure a Media Library Browser to display specific types of media. Combined masks are not yet supported.  In other words, only one nonzero mask value is supported at a time.  If masks are combined, the lowest mask value is used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Library"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Library"
        }
      ],
      "role": "symbol",
      "title": "NSMediaLibraryBrowserController.Library",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/library"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/frame": {
      "abstract": [
        {
          "text": "The frame, in global coordinates, used to display the Media Library Browser panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/frame"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/isVisible": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the Media Library Browser panel is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/isVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "role": "symbol",
      "title": "isVisible",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/isvisible"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/mediaLibraries": {
      "abstract": [
        {
          "text": "The media library that is in use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaLibraries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMediaLibraryBrowserController",
          "text": "NSMediaLibraryBrowserController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMediaLibrary",
          "text": "Library"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/mediaLibraries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaLibraries"
        }
      ],
      "role": "symbol",
      "title": "mediaLibraries",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/medialibraries"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/shared": {
      "abstract": [
        {
          "text": "Returns the shared Media Library Browser instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMediaLibraryBrowserController",
          "text": "NSMediaLibraryBrowserController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedMediaLibraryBrowserController"
        }
      ],
      "role": "symbol",
      "title": "shared",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/shared"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/togglePanel(_:)": {
      "abstract": [
        {
          "text": "Toggles the visibility of the Media Library Browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "togglePanel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/togglePanel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "togglePanel:"
        }
      ],
      "role": "symbol",
      "title": "togglePanel(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/togglepanel(_:)"
    },
    "doc://com.apple.documentation/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/MediaLibrary"
    },
    "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaGroup": {
      "abstract": [
        {
          "text": "The `MLMediaGroup` class provides groupings for media objects from a single source of media, such as iTunes or Aperture. The media objects—individual files containing a piece of media such as a photo, song, or movie—are referenced by one or more groups within each media source. These groupings serve as filters, providing hierarchical structure to the collection of objects in each source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaGroup"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLMediaGroup",
      "type": "topic",
      "url": "/documentation/MediaLibrary/MLMediaGroup"
    },
    "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaLibrary": {
      "abstract": [
        {
          "text": "The `MLMediaLibrary` class provides an interface for accessing a collection of media objects from various sources. It serves as the initial access point of the Media Library framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLibrary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaLibrary",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLMediaLibrary",
      "type": "topic",
      "url": "/documentation/MediaLibrary/MLMediaLibrary"
    },
    "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaObject": {
      "abstract": [
        {
          "text": "The `MLMediaObject` class describes a single media file, such as a photo, song, or movie. Each media object contains basic metadata including a name, media type, URL, and so on. Additional information about each object is stored in its list of attributes. For a list of possible object attribute keys, see [Media Object Attribute Keys](doc://com.apple.medialibrary/documentation/MediaLibrary/media-object-attribute-keys).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObject"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLMediaObject",
      "type": "topic",
      "url": "/documentation/MediaLibrary/MLMediaObject"
    },
    "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaSource": {
      "abstract": [
        {
          "text": "The `MLMediaSource` class identifies a specific provider of media. Conceptually, a media source respresents a single app, such as iTunes or Aperture. Each media source contains multiple groups of media objects—individual files containing a piece of media such as a photo, song, or movie.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSource"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaLibrary/MLMediaSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLMediaSource",
      "type": "topic",
      "url": "/documentation/MediaLibrary/MLMediaSource"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou": {
      "abstract": [
        {
          "text": "In an app that adopts App Sandbox, revokes access to the resource pointed to by a security-scoped URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "stopAccessingSecurityScopedResource"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou",
      "kind": "symbol",
      "role": "symbol",
      "title": "stopAccessingSecurityScopedResource()",
      "type": "topic",
      "url": "/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso": {
      "abstract": [
        {
          "text": "In an app that has adopted App Sandbox, makes the resource pointed to by a security-scoped URL available to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "startAccessingSecurityScopedResource"
        },
        {
          "kind": "text",
          "text": "() -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso",
      "kind": "symbol",
      "role": "symbol",
      "title": "startAccessingSecurityScopedResource()",
      "type": "topic",
      "url": "/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-Media-Library-Browser-Panel",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/shared"
      ],
      "title": "Creating a Media Library Browser Panel"
    },
    {
      "anchor": "Displaying-the-Media-Library-Browser-Panel",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/frame",
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/togglePanel(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/isVisible"
      ],
      "title": "Displaying the Media Library Browser Panel"
    },
    {
      "anchor": "Displayed-Media-Library-Types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/mediaLibraries"
      ],
      "title": "Displayed Media Library Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSMediaLibraryBrowserController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Media-Library-Browser-Panel",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/shared"
              ],
              "title": "Creating a Media Library Browser Panel"
            },
            {
              "anchor": "Displaying-the-Media-Library-Browser-Panel",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/frame",
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/togglePanel(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/isVisible"
              ],
              "title": "Displaying the Media Library Browser Panel"
            },
            {
              "anchor": "Displayed-Media-Library-Types",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/mediaLibraries"
              ],
              "title": "Displayed Media Library Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSMediaLibraryBrowserController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library/title",
          "value": "NSMediaLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MediaLibrary~1MLMediaSource/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLMediaSource"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MediaLibrary~1MLMediaObject/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLMediaObject"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1mediaLibraries/title",
          "value": "mediaLibraries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1mediaLibraries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaLibraries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1togglePanel(_:)/title",
          "value": "togglePanel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1togglePanel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "togglePanel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MediaLibrary~1MLMediaLibrary/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLMediaLibrary"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl~11413736-stopaccessingsecurityscopedresou/title",
          "value": "stopAccessingSecurityScopedResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1shared/title",
          "value": "sharedMediaLibraryBrowserController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedMediaLibraryBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1isVisible/title",
          "value": "visible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1isVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MediaLibrary~1MLMediaGroup/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLMediaGroup"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl~11417051-startaccessingsecurityscopedreso/title",
          "value": "startAccessingSecurityScopedResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController/title",
          "value": "NSMediaLibraryBrowserController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmedialibrarybrowsercontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsmedialibrarybrowsercontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
