{
  "abstract": [
    {
      "text": "The window displays a minimize button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMiniaturizableWindowMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSMiniaturizableWindowMask",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSMiniaturizableWindowMask"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMiniaturizableWindowMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSMiniaturizableWindowMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSWindowStyleMask",
              "text": "NSWindowStyleMask"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMiniaturizableWindowMask"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBorderlessWindowMask": {
      "abstract": [
        {
          "text": "The window displays none of the usual peripheral elements. Useful only for display or caching purposes. A window that uses ",
          "type": "text"
        },
        {
          "code": "NSBorderlessWindowMask",
          "type": "codeVoice"
        },
        {
          "text": " can’t become key or main, unless the value of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeMain",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". Note that you can set a window’s or panel’s style mask to ",
          "type": "text"
        },
        {
          "code": "NSBorderlessWindowMask",
          "type": "codeVoice"
        },
        {
          "text": " in Interface Builder by deselecting Title Bar in the Appearance section of the Attributes inspector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBorderlessWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBorderlessWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBorderlessWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsborderlesswindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSClosableWindowMask": {
      "abstract": [
        {
          "text": "The window displays a close button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSClosableWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSClosableWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSClosableWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsclosablewindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFullScreenWindowMask": {
      "abstract": [
        {
          "text": "The window can appear full screen. A fullscreen window does not draw its title bar, and may have special handling for its toolbar. This mask is automatically toggled when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is called.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFullScreenWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFullScreenWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFullScreenWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfullscreenwindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFullSizeContentViewWindowMask": {
      "abstract": [
        {
          "text": "When set, the content view consumes the full size of the window; it can be combined with other window style masks, but is only respected for windows with a title bar. Using this mask opts in to layer backing. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutRect",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutGuide",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to lay out views underneath the title bar-toolbar area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFullSizeContentViewWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFullSizeContentViewWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFullSizeContentViewWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfullsizecontentviewwindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMiniaturizableWindowMask": {
      "abstract": [
        {
          "text": "The window displays a minimize button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMiniaturizableWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMiniaturizableWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMiniaturizableWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsminiaturizablewindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResizableWindowMask": {
      "abstract": [
        {
          "text": "The window displays a resize control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSResizableWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResizableWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSResizableWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsresizablewindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTexturedBackgroundWindowMask": {
      "abstract": [
        {
          "text": "The window displays with a metal-textured background. Additionally, the window may be moved by clicking and dragging anywhere in the window background. A bordered window with this mask gets rounded bottom corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTexturedBackgroundWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTexturedBackgroundWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTexturedBackgroundWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nstexturedbackgroundwindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTitledWindowMask": {
      "abstract": [
        {
          "text": "The window displays a title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTitledWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTitledWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTitledWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nstitledwindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnifiedTitleAndToolbarWindowMask": {
      "abstract": [
        {
          "text": "The window’s title bar and toolbar have a unified look—that is, a continuous background. A horizontal separator line appears under the title bar and toolbar .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnifiedTitleAndToolbarWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnifiedTitleAndToolbarWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnifiedTitleAndToolbarWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsunifiedtitleandtoolbarwindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnscaledWindowMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnscaledWindowMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnscaledWindowMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnscaledWindowMask",
      "type": "topic",
      "url": "/documentation/appkit/nsunscaledwindowmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify the style of a window, and that you can combine with the C bitwise OR operator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StyleMask"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.StyleMask",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window can become the key window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canBecomeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canBecomeKeyWindow"
        }
      ],
      "role": "symbol",
      "title": "canBecomeKey",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/canbecomekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeMain": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window can become the application’s main window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canBecomeMain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeMain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canBecomeMainWindow"
        }
      ],
      "role": "symbol",
      "title": "canBecomeMain",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/canbecomemain"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutGuide": {
      "abstract": [
        {
          "text": "A value used by Auto Layout constraints to automatically bind to the value of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutRect",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentLayoutGuide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentLayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "contentLayoutGuide",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/contentlayoutguide"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutRect": {
      "abstract": [
        {
          "text": "The area inside the window that is for non-obscured content, in window coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentLayoutRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentLayoutRect"
        }
      ],
      "role": "symbol",
      "title": "contentLayoutRect",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/contentlayoutrect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)": {
      "abstract": [
        {
          "text": "Takes the window into or out of fullscreen mode,",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleFullScreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleFullScreen:"
        }
      ],
      "role": "symbol",
      "title": "toggleFullScreen(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/togglefullscreen(_:)"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBorderlessWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSTitledWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSClosableWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSResizableWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSTexturedBackgroundWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSUnifiedTitleAndToolbarWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFullScreenWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFullSizeContentViewWindowMask",
        "doc://com.apple.appkit/documentation/AppKit/NSUnscaledWindowMask"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeKey/title",
          "value": "canBecomeKeyWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canBecomeKeyWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentLayoutRect/title",
          "value": "contentLayoutRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentLayoutRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentLayoutRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentLayoutGuide/title",
          "value": "contentLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentLayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeMain/title",
          "value": "canBecomeMainWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeMain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canBecomeMainWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/title",
          "value": "NSWindowStyleMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/title",
          "value": "toggleFullScreen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleFullScreen:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsminiaturizablewindowmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
