{
  "abstract": [
    {
      "text": "Specifies a miter line shape of the joints between connected segments of a stroked path.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/miter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMiterLineJoinStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSMiterLineJoinStyle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSMiterLineJoinStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMiterLineJoinStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSMiterLineJoinStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLineJoinStyle",
              "text": "NSLineJoinStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMiterLineJoinStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Here is an example of the appearance of this style:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2934725",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBevelLineJoinStyle": {
      "abstract": [
        {
          "text": "Specifies a bevel line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBevelLineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBevelLineJoinStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBevelLineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbevellinejoinstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the shape of the joins between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineJoinStyle"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/miter": {
      "abstract": [
        {
          "text": "Specifies a miter line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/miter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineJoinStyleMiter"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineJoinStyle.miter",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum/miter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMiterLineJoinStyle": {
      "abstract": [
        {
          "text": "Specifies a miter line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMiterLineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMiterLineJoinStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMiterLineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsmiterlinejoinstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundLineJoinStyle": {
      "abstract": [
        {
          "text": "Specifies a round line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundLineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundLineJoinStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundLineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundlinejoinstyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-2934725": {
      "alt": "Diagram that shows the miter line join style.",
      "identifier": "media-2934725",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/24a8040812f1885bb21312a7ca550f6c/media-2934725@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSRoundLineJoinStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSBevelLineJoinStyle"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/title",
          "value": "NSLineJoinStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum~1miter/title",
          "value": "NSLineJoinStyleMiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum~1miter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyleMiter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmiterlinejoinstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
