{
  "abstract": [
    {
      "text": "When the user clicks the button (on state), the button appears illuminated.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushInButton"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSMomentaryPushInButton",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSMomentaryPushInButton"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMomentaryPushInButton"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSMomentaryPushInButton"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSButtonType",
              "text": "NSButtonType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMomentaryPushInButton"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This type of button is best for simply triggering actions, as it doesn’t show its state; it always displays its normal image or title. This option is called Momentary Push In in Interface Builder’s Button inspector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Most buttons in macOS, such as Cancel button in many dialogs, are momentary light buttons. If you click one, it highlights briefly, triggers an action, and returns to its original state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This button type is the default.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton": {
      "abstract": [
        {
          "text": "A button that sends an action when the user first clicks the button and continues sending actions until the user releases pressure entirely.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAcceleratorButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAcceleratorButton",
      "type": "topic",
      "url": "/documentation/appkit/nsacceleratorbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType": {
      "abstract": [
        {
          "text": "Button types that you can specify using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn": {
      "abstract": [
        {
          "text": "A button that illuminates when the user clicks it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryPushIn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMomentaryPushIn"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.momentaryPushIn",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/momentarypushin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)": {
      "abstract": [
        {
          "text": "Sets how the button highlights while pressed and how it shows its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setButtonType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSButtonType",
          "text": "ButtonType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setButtonType:"
        }
      ],
      "role": "symbol",
      "title": "setButtonType(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell/setbuttontype(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryChangeButton": {
      "abstract": [
        {
          "text": "When the button is clicked, the alternate (on state) image and alternate title are displayed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryChangeButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryChangeButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryChangeButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarychangebutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLight": {
      "abstract": [
        {
          "text": "When the button is clicked (on state), it appears illuminated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryLight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLight",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryLight",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarylight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLightButton": {
      "abstract": [
        {
          "text": "When the button is clicked (on state), it appears illuminated. If the button has borders, it may also appear recessed. When the button is released, it returns to its normal (off) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryLightButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLightButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryLightButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarylightbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushButton": {
      "abstract": [
        {
          "text": "When the button is clicked (on state), it appears illuminated. If the button has a bordered, it may also appear recessed. When the button is released, it returns to its normal (off) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryPushButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryPushButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarypushbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushInButton": {
      "abstract": [
        {
          "text": "When the user clicks the button (on state), the button appears illuminated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryPushInButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushInButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryPushInButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarypushinbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton": {
      "abstract": [
        {
          "text": "A multilevel accelerator button is a variation of a normal accelerator button that allows for a configurable number of stepped pressure levels. As each one is reached, the user receives light tactile feedback and an action is sent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMultiLevelAcceleratorButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMultiLevelAcceleratorButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmultilevelacceleratorbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOnOffButton": {
      "abstract": [
        {
          "text": "The first click highlights the button; a second click returns it to the normal (unhighlighted) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOnOffButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOnOffButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOnOffButton",
      "type": "topic",
      "url": "/documentation/appkit/nsonoffbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPushOnPushOffButton": {
      "abstract": [
        {
          "text": "When the button is clicked (on state), it appears illuminated. If the button has borders, it may also appear recessed. A second click returns it to its normal (off) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPushOnPushOffButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPushOnPushOffButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPushOnPushOffButton",
      "type": "topic",
      "url": "/documentation/appkit/nspushonpushoffbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRadioButton": {
      "abstract": [
        {
          "text": "This style is similar to ",
          "type": "text"
        },
        {
          "code": "NSSwitchButton",
          "type": "codeVoice"
        },
        {
          "text": ", but it is used to constrain a selection to a single element from several elements.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRadioButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRadioButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRadioButton",
      "type": "topic",
      "url": "/documentation/appkit/nsradiobutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSwitchButton": {
      "abstract": [
        {
          "text": "This style is a variant of ",
          "type": "text"
        },
        {
          "code": "NSToggleButton",
          "type": "codeVoice"
        },
        {
          "text": " that has no border and is typically used to represent a checkbox.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSwitchButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSwitchButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSwitchButton",
      "type": "topic",
      "url": "/documentation/appkit/nsswitchbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToggleButton": {
      "abstract": [
        {
          "text": "After the first click, the button displays its alternate image or title (on state); a second click returns the button to its normal (off) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSToggleButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToggleButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToggleButton",
      "type": "topic",
      "url": "/documentation/appkit/nstogglebutton"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Button-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLightButton",
        "doc://com.apple.appkit/documentation/AppKit/NSPushOnPushOffButton",
        "doc://com.apple.appkit/documentation/AppKit/NSToggleButton",
        "doc://com.apple.appkit/documentation/AppKit/NSSwitchButton",
        "doc://com.apple.appkit/documentation/AppKit/NSRadioButton",
        "doc://com.apple.appkit/documentation/AppKit/NSMomentaryChangeButton",
        "doc://com.apple.appkit/documentation/AppKit/NSOnOffButton",
        "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton",
        "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton",
        "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushButton",
        "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLight"
      ],
      "title": "Deprecated Button Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1setButtonType(_:)/title",
          "value": "setButtonType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1setButtonType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setButtonType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/title",
          "value": "NSButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryPushIn/title",
          "value": "NSButtonTypeMomentaryPushIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryPushIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMomentaryPushIn"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmomentarypushinbutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
