{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.appkit/documentation/AppKit/NSMouseEntered"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@E@NSEventType","text":"NSEventType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"NSMouseEntered","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown","doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp","doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown","doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp","doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown","doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp","doc://com.apple.appkit/documentation/AppKit/NSMouseMoved","doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged","doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged","doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged","doc://com.apple.appkit/documentation/AppKit/NSMouseExited","doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate","doc://com.apple.appkit/documentation/AppKit/NSKeyDown","doc://com.apple.appkit/documentation/AppKit/NSKeyUp","doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged"],"generated":true,"title":"Deprecated","anchor":"Deprecated"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered","isActive":true,"type":"reference"},{"type":"text","text":" instead."}],"type":"paragraph"}],"variants":[{"paths":["/documentation/appkit/nsmouseentered"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"A mouse-entered event.","type":"text"}],"metadata":{"platforms":[{"name":"macOS","deprecated":false,"deprecatedAt":"10.12","beta":false,"unavailable":false,"introducedAt":"10.0"}],"title":"NSMouseEntered","roleHeading":"Global Variable","navigatorTitle":[{"kind":"identifier","text":"NSMouseEntered"}],"modules":[{"name":"AppKit"}],"externalID":"c:@NSMouseEntered","role":"symbol","symbolKind":"var","fragments":[{"kind":"identifier","text":"NSMouseEntered"}]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged","abstract":[{"text":"A left mouse-dragged event.","type":"text"}],"deprecated":true,"url":"/documentation/appkit/nsleftmousedragged","role":"symbol","fragments":[{"text":"NSLeftMouseDragged","kind":"identifier"}],"type":"topic","title":"NSLeftMouseDragged"},"doc://com.apple.appkit/documentation/AppKit/NSMouseExited":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMouseExited","abstract":[{"text":"A mouse-exited event.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"NSMouseExited"}],"title":"NSMouseExited","deprecated":true,"url":"/documentation/appkit/nsmouseexited","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSKeyDown":{"role":"symbol","fragments":[{"text":"NSKeyDown","kind":"identifier"}],"url":"/documentation/appkit/nskeydown","type":"topic","deprecated":true,"kind":"symbol","title":"NSKeyDown","abstract":[{"type":"text","text":"A key-down event."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSKeyDown"},"doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate","kind":"symbol","role":"symbol","type":"topic","title":"NSCursorUpdate","fragments":[{"text":"NSCursorUpdate","kind":"identifier"}],"abstract":[{"text":"A cursor-update event.","type":"text"}],"url":"/documentation/appkit/nscursorupdate","deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp","fragments":[{"text":"NSOtherMouseUp","kind":"identifier"}],"title":"NSOtherMouseUp","role":"symbol","url":"/documentation/appkit/nsothermouseup","abstract":[{"type":"text","text":"An other mouse-up event."}],"type":"topic","deprecated":true,"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown":{"title":"NSLeftMouseDown","deprecated":true,"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown","role":"symbol","url":"/documentation/appkit/nsleftmousedown","kind":"symbol","fragments":[{"text":"NSLeftMouseDown","kind":"identifier"}],"abstract":[{"type":"text","text":"A left mouse-down event."}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType":{"url":"/documentation/appkit/nsevent/eventtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventType","kind":"identifier"}],"title":"NSEvent.EventType","kind":"symbol","abstract":[{"text":"Constants for the types of events that responder objects can handle.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType","role":"symbol","type":"topic","navigatorTitle":[{"text":"EventType","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown":{"role":"symbol","type":"topic","deprecated":true,"abstract":[{"type":"text","text":"An other mouse-down event."}],"url":"/documentation/appkit/nsothermousedown","kind":"symbol","fragments":[{"kind":"identifier","text":"NSOtherMouseDown"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown","title":"NSOtherMouseDown"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged":{"title":"NSOtherMouseDragged","deprecated":true,"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged","role":"symbol","url":"/documentation/appkit/nsothermousedragged","kind":"symbol","fragments":[{"text":"NSOtherMouseDragged","kind":"identifier"}],"abstract":[{"text":"An other mouse-dragged event.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSMouseMoved":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMouseMoved","type":"topic","fragments":[{"text":"NSMouseMoved","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"/documentation/appkit/nsmousemoved","deprecated":true,"abstract":[{"text":"A mouse-moved event.","type":"text"}],"title":"NSMouseMoved"},"doc://com.apple.appkit/documentation/AppKit/NSKeyUp":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSKeyUp","fragments":[{"text":"NSKeyUp","kind":"identifier"}],"title":"NSKeyUp","role":"symbol","url":"/documentation/appkit/nskeyup","abstract":[{"type":"text","text":"A key-up event."}],"type":"topic","deprecated":true,"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMouseEntered":{"abstract":[{"type":"text","text":"A mouse-entered event."}],"deprecated":true,"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMouseEntered","url":"/documentation/appkit/nsmouseentered","kind":"symbol","fragments":[{"kind":"identifier","text":"NSMouseEntered"}],"role":"symbol","title":"NSMouseEntered"},"doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown":{"title":"NSRightMouseDown","deprecated":true,"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown","role":"symbol","url":"/documentation/appkit/nsrightmousedown","kind":"symbol","fragments":[{"text":"NSRightMouseDown","kind":"identifier"}],"abstract":[{"text":"A right mouse-down event.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/mouseEntered","title":"NSEvent.EventType.mouseEntered","type":"topic","url":"/documentation/appkit/nsevent/eventtype/mouseentered","navigatorTitle":[{"kind":"identifier","text":"NSEventTypeMouseEntered"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mouseEntered"}],"abstract":[{"type":"text","text":"The cursor entered a well-defined area, such as a view."}]},"doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged":{"title":"NSRightMouseDragged","deprecated":true,"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged","role":"symbol","url":"/documentation/appkit/nsrightmousedragged","kind":"symbol","fragments":[{"text":"NSRightMouseDragged","kind":"identifier"}],"abstract":[{"type":"text","text":"A right mouse-dragged event."}]},"doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp":{"kind":"symbol","url":"/documentation/appkit/nsrightmouseup","deprecated":true,"title":"NSRightMouseUp","fragments":[{"kind":"identifier","text":"NSRightMouseUp"}],"type":"topic","abstract":[{"text":"A right mouse-up event.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp","url":"/documentation/appkit/nsleftmouseup","fragments":[{"kind":"identifier","text":"NSLeftMouseUp"}],"type":"topic","title":"NSLeftMouseUp","deprecated":true,"role":"symbol","abstract":[{"text":"A left mouse-up event.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged":{"title":"NSFlagsChanged","deprecated":true,"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged","role":"symbol","url":"/documentation/appkit/nsflagschanged","kind":"symbol","fragments":[{"kind":"identifier","text":"NSFlagsChanged"}],"abstract":[{"text":"A flags-changed event.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title","value":"NSEventType","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments","value":[{"text":"NSEventType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle","value":[{"kind":"identifier","text":"NSEventType"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseEntered/title","value":"NSEventTypeMouseEntered","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1mouseEntered/fragments","value":[{"text":"NSEventTypeMouseEntered","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}