{
  "abstract": [
    {
      "text": "Moves the path object’s current drawing point to the specified point.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMoveToBezierPathElement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSMoveToBezierPathElement",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSMoveToBezierPathElement"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMoveToBezierPathElement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSMoveToBezierPathElement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSBezierPathElement",
              "text": "NSBezierPathElement"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMoveToBezierPathElement"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This path element does not result in any drawing. Using this command in the middle of a path results in a disconnected line segment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Contains 1 point.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType": {
      "abstract": [
        {
          "text": "Constants that specify basic path element commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo": {
      "abstract": [
        {
          "text": "Moves the path object’s current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementMoveTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.moveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/moveto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSClosePathBezierPathElement": {
      "abstract": [
        {
          "text": "Marks the end of the current subpath at the specified point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSClosePathBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSClosePathBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSClosePathBezierPathElement",
      "type": "topic",
      "url": "/documentation/appkit/nsclosepathbezierpathelement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCurveToBezierPathElement": {
      "abstract": [
        {
          "text": "Creates a curved line segment from the current point to the specified endpoint using two control points to define the curve.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCurveToBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCurveToBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCurveToBezierPathElement",
      "type": "topic",
      "url": "/documentation/appkit/nscurvetobezierpathelement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineToBezierPathElement": {
      "abstract": [
        {
          "text": "Creates a straight line from the current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineToBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineToBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineToBezierPathElement",
      "type": "topic",
      "url": "/documentation/appkit/nslinetobezierpathelement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMoveToBezierPathElement": {
      "abstract": [
        {
          "text": "Moves the path object’s current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMoveToBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMoveToBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMoveToBezierPathElement",
      "type": "topic",
      "url": "/documentation/appkit/nsmovetobezierpathelement"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLineToBezierPathElement",
        "doc://com.apple.appkit/documentation/AppKit/NSCurveToBezierPathElement",
        "doc://com.apple.appkit/documentation/AppKit/NSClosePathBezierPathElement"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1moveTo/title",
          "value": "NSBezierPathElementMoveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1moveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementMoveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/title",
          "value": "NSBezierPathElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmovetobezierpathelement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
