{
  "abstract": [
    {
      "text": "A constant for glyph packing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSMultibyteGlyphPacking",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSMultibyteGlyphPacking"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMultibyteGlyphPacking"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.13",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSMultibyteGlyphPacking"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMultibyteGlyphPacking"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Cocoa stores all text data as Unicode. The text system converts Unicode into glyph IDs and places them in 1-, 2-, or 4-byte storage depending on the context. To render text, you must convert the storage into a format the text engine understands. The following constants describe the glyph packing schemes the text rendering engine can use. They are used to extract glyphs from a font for making a multibyte (or single-byte) array of glyphs for passing to an interpreter, such as the window server, which expects a big-endian multibyte stream (that is, “packed glyphs”) instead of a pure ",
              "type": "text"
            },
            {
              "code": "NSGlyph",
              "type": "codeVoice"
            },
            {
              "text": " stream. They’re used by ",
              "type": "text"
            },
            {
              "code": "glyphPacking",
              "type": "codeVoice"
            },
            {
              "text": ". With Quartz, the engine always expects the format to be in 2-byte short array, so ",
              "type": "text"
            },
            {
              "code": "NSNativeShortGlyphPacking",
              "type": "codeVoice"
            },
            {
              "text": " is the only format currently in use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)": {
      "abstract": [
        {
          "text": "Starts a modal event loop for the specified window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalResponse",
          "text": "ModalResponse"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalForWindow:"
        }
      ],
      "role": "symbol",
      "title": "runModal(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/runmodal(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModalSession(_:)": {
      "abstract": [
        {
          "text": "Runs a given modal session, as defined in a previous invocation of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/beginModalSession(for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModalSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalSession",
          "text": "ModalSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalResponse",
          "text": "ModalResponse"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModalSession(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalSession:"
        }
      ],
      "role": "symbol",
      "title": "runModalSession(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/runmodalsession(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle": {
      "abstract": [
        {
          "text": "These constants are used in ",
          "type": "text"
        },
        {
          "code": "NSResponder",
          "type": "codeVoice"
        },
        {
          "text": "’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInterfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsinterfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking": {
      "abstract": [
        {
          "text": "A constant for glyph packing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMultibyteGlyphPacking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMultibyteGlyphPacking"
        }
      ],
      "role": "symbol",
      "title": "NSMultibyteGlyphPacking",
      "type": "topic",
      "url": "/documentation/appkit/nsmultibyteglyphpacking"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmultibyteglyphpacking/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking/nativeShortGlyphPacking": {
      "abstract": [
        {
          "text": "The native format for macOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nativeShortGlyphPacking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking/nativeShortGlyphPacking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNativeShortGlyphPacking"
        }
      ],
      "role": "symbol",
      "title": "NSMultibyteGlyphPacking.nativeShortGlyphPacking",
      "type": "topic",
      "url": "/documentation/appkit/nsmultibyteglyphpacking/nativeshortglyphpacking"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption": {
      "abstract": [
        {
          "text": "Constants that specify OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLGlobalOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGlobalOption"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLGlobalOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglglobaloption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle": {
      "abstract": [
        {
          "text": "Returns the receiver’s interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "interfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "interfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/interfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight": {
      "abstract": [
        {
          "text": "The writing direction is left to right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftToRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection.leftToRight",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection/lefttoright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft": {
      "abstract": [
        {
          "text": "The writing direction is right to left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightToLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection.rightToLeft",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection/righttoleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/additional-writing-directions": {
      "abstract": [
        {
          "text": "Additional values to be added to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", when used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1524497-writingdirection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/additional-writing-directions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Additional Writing Directions",
      "type": "topic",
      "url": "/documentation/appkit/additional-writing-directions"
    },
    "doc://com.apple.appkit/documentation/AppKit/data-entry-types": {
      "abstract": [
        {
          "text": "These constants specify how a cell formats numeric data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/data-entry-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Entry Types",
      "type": "topic",
      "url": "/documentation/appkit/data-entry-types"
    },
    "doc://com.apple.appkit/documentation/AppKit/glyph-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used only inside the glyph generation machinery, but must also be shared between components.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/glyph-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Glyph Attributes",
      "type": "topic",
      "url": "/documentation/appkit/glyph-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsbuttontypes-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsbuttontypes-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttontypes-anonymous"
    },
    "doc://com.apple.appkit/documentation/AppKit/return-values-for-modal-operations": {
      "abstract": [
        {
          "text": "Historical return values for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModalSession(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/return-values-for-modal-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Return values for modal operations",
      "type": "topic",
      "url": "/documentation/appkit/return-values-for-modal-operations"
    },
    "doc://com.apple.appkit/documentation/AppKit/tags-of-views-in-the-fontpanel": {
      "abstract": [
        {
          "text": "These constants are obsolete and should not be used.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/tags-of-views-in-the-fontpanel",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Tags of Views in the FontPanel",
      "type": "topic",
      "url": "/documentation/appkit/tags-of-views-in-the-fontpanel"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1524497-writingdirection": {
      "abstract": [
        {
          "text": "The writing direction of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "writingDirection"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1524497-writingdirection",
      "kind": "symbol",
      "role": "symbol",
      "title": "writingDirection",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1524497-writingdirection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/glyph-attributes",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption",
        "doc://com.apple.appkit/documentation/AppKit/data-entry-types",
        "doc://com.apple.appkit/documentation/AppKit/nsbuttontypes-anonymous",
        "doc://com.apple.appkit/documentation/AppKit/additional-writing-directions",
        "doc://com.apple.appkit/documentation/AppKit/return-values-for-modal-operations",
        "doc://com.apple.appkit/documentation/AppKit/tags-of-views-in-the-fontpanel"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Packing-Options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking/nativeShortGlyphPacking"
      ],
      "title": "Packing Options"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.13",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSMultibyteGlyphPacking"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultibyteGlyphPacking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultibyteGlyphPacking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Packing-Options",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking/nativeShortGlyphPacking"
              ],
              "title": "Packing Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/glyph-attributes",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption",
                "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle",
                "doc://com.apple.appkit/documentation/AppKit/data-entry-types",
                "doc://com.apple.appkit/documentation/AppKit/nsbuttontypes-anonymous",
                "doc://com.apple.appkit/documentation/AppKit/additional-writing-directions",
                "doc://com.apple.appkit/documentation/AppKit/return-values-for-modal-operations",
                "doc://com.apple.appkit/documentation/AppKit/tags-of-views-in-the-fontpanel"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSMultibyteGlyphPacking"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultibyteGlyphPacking~1nativeShortGlyphPacking/title",
          "value": "NSNativeShortGlyphPacking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultibyteGlyphPacking~1nativeShortGlyphPacking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNativeShortGlyphPacking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1rightToLeft/title",
          "value": "NSWritingDirectionRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1rightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionRightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1leftToRight/title",
          "value": "NSWritingDirectionLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModalSession(_:)/title",
          "value": "runModalSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModalSession(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/title",
          "value": "NSOpenGLGlobalOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLGlobalOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLGlobalOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModal(for:)/title",
          "value": "runModalForWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModal(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalForWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultibyteGlyphPacking/title",
          "value": "NSMultibyteGlyphPacking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultibyteGlyphPacking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultibyteGlyphPacking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultibyteGlyphPacking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultibyteGlyphPacking"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmultibyteglyphpacking"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsmultibyteglyphpacking"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
