{
  "abstract": [
    {
      "text": "An object for changing the values of the subattributes in a paragraph style attribute.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSMutableParagraphStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSMutableParagraphStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMutableParagraphStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSMutableParagraphStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class adds methods to its superclass, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", for changing the values of the subattributes in a paragraph style attribute. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Don’t mutate a paragraph style object after adding it to an attributed string. Doing so can cause your app to crash.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle": {
      "abstract": [
        {
          "text": "An object for changing the values of the subattributes in a paragraph style attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMutableParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMutableParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "NSMutableParagraphStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/addTabStop(_:)": {
      "abstract": [
        {
          "text": "Adds the specified tab stop to the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTabStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextTab",
          "text": "NSTextTab"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/addTabStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addTabStop:"
        }
      ],
      "role": "symbol",
      "title": "addTabStop(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/addtabstop(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/alignment": {
      "abstract": [
        {
          "text": "The text alignment of the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextAlignment",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/alignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alignment"
        }
      ],
      "role": "symbol",
      "title": "alignment",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/alignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/allowsDefaultTighteningForTruncation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system tightens intercharacter spacing before truncating text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDefaultTighteningForTruncation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/allowsDefaultTighteningForTruncation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsDefaultTighteningForTruncation"
        }
      ],
      "role": "symbol",
      "title": "allowsDefaultTighteningForTruncation",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/allowsdefaulttighteningfortruncation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/baseWritingDirection": {
      "abstract": [
        {
          "text": "The base writing direction for the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseWritingDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWritingDirection",
          "text": "NSWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/baseWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "baseWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "baseWritingDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/basewritingdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/defaultTabInterval": {
      "abstract": [
        {
          "text": "A number used as the document’s default tab spacing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultTabInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/defaultTabInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultTabInterval"
        }
      ],
      "role": "symbol",
      "title": "defaultTabInterval",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/defaulttabinterval"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/firstLineHeadIndent": {
      "abstract": [
        {
          "text": "The indentation of the first line of the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstLineHeadIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/firstLineHeadIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "firstLineHeadIndent"
        }
      ],
      "role": "symbol",
      "title": "firstLineHeadIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/firstlineheadindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/headIndent": {
      "abstract": [
        {
          "text": "The indentation of the paragraph’s lines other than the first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/headIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headIndent"
        }
      ],
      "role": "symbol",
      "title": "headIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/headindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/headerLevel": {
      "abstract": [
        {
          "text": "The paragraph’s header level for HTML generation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/headerLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headerLevel"
        }
      ],
      "role": "symbol",
      "title": "headerLevel",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/headerlevel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/hyphenationFactor": {
      "abstract": [
        {
          "text": "The paragraph’s threshold for hyphenation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hyphenationFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/hyphenationFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hyphenationFactor"
        }
      ],
      "role": "symbol",
      "title": "hyphenationFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/hyphenationfactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode for breaking lines in the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/linebreakmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineBreakStrategy": {
      "abstract": [
        {
          "text": "The strategies that the text system may use to break lines while laying out the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakStrategy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
          "text": "NSParagraphStyle"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakStrategy",
          "text": "LineBreakStrategy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineBreakStrategy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakStrategy"
        }
      ],
      "role": "symbol",
      "title": "lineBreakStrategy",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/linebreakstrategy"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineHeightMultiple": {
      "abstract": [
        {
          "text": "The line height multiple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineHeightMultiple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineHeightMultiple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineHeightMultiple"
        }
      ],
      "role": "symbol",
      "title": "lineHeightMultiple",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/lineheightmultiple"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineSpacing": {
      "abstract": [
        {
          "text": "The distance in points between the bottom of one line fragment and the top of the next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineSpacing"
        }
      ],
      "role": "symbol",
      "title": "lineSpacing",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/linespacing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/maximumLineHeight": {
      "abstract": [
        {
          "text": "The paragraph’s maximum line height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumLineHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/maximumLineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumLineHeight"
        }
      ],
      "role": "symbol",
      "title": "maximumLineHeight",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/maximumlineheight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/minimumLineHeight": {
      "abstract": [
        {
          "text": "The paragraph’s minimum line height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumLineHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/minimumLineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumLineHeight"
        }
      ],
      "role": "symbol",
      "title": "minimumLineHeight",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/minimumlineheight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/paragraphSpacing": {
      "abstract": [
        {
          "text": "The space after the end of the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/paragraphSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paragraphSpacing"
        }
      ],
      "role": "symbol",
      "title": "paragraphSpacing",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/paragraphspacing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/paragraphSpacingBefore": {
      "abstract": [
        {
          "text": "The distance between the paragraph’s top and the beginning of its text content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphSpacingBefore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/paragraphSpacingBefore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paragraphSpacingBefore"
        }
      ],
      "role": "symbol",
      "title": "paragraphSpacingBefore",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/paragraphspacingbefore"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/removeTabStop(_:)": {
      "abstract": [
        {
          "text": "Removes the first text tab with a location and type equal to the specified tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTabStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextTab",
          "text": "NSTextTab"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/removeTabStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTabStop:"
        }
      ],
      "role": "symbol",
      "title": "removeTabStop(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/removetabstop(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/setParagraphStyle(_:)": {
      "abstract": [
        {
          "text": "Replaces the subattributes of the paragraph with those in the specified paragraph style object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setParagraphStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
          "text": "NSParagraphStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/setParagraphStyle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setParagraphStyle:"
        }
      ],
      "role": "symbol",
      "title": "setParagraphStyle(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/setparagraphstyle(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tabStops": {
      "abstract": [
        {
          "text": "The text tab objects that represent the paragraph’s tab stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStops"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextTab",
          "text": "NSTextTab"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tabStops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabStops"
        }
      ],
      "role": "symbol",
      "title": "tabStops",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/tabstops"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tailIndent": {
      "abstract": [
        {
          "text": "The trailing indentation of the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tailIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tailIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tailIndent"
        }
      ],
      "role": "symbol",
      "title": "tailIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/tailindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/textBlocks": {
      "abstract": [
        {
          "text": "The text blocks that contain the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textBlocks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextBlock",
          "text": "NSTextBlock"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/textBlocks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textBlocks"
        }
      ],
      "role": "symbol",
      "title": "textBlocks",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/textblocks"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/textLists": {
      "abstract": [
        {
          "text": "The text lists that contain the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLists"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextList",
          "text": "NSTextList"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/textLists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLists"
        }
      ],
      "role": "symbol",
      "title": "textLists",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/textlists"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation": {
      "abstract": [
        {
          "text": "The threshold for using tightening as an alternative to truncation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tighteningFactorForTruncation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tighteningFactorForTruncation"
        }
      ],
      "role": "symbol",
      "title": "tighteningFactorForTruncation",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/tighteningfactorfortruncation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/usesDefaultHyphenation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesDefaultHyphenation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/usesDefaultHyphenation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesDefaultHyphenation"
        }
      ],
      "role": "symbol",
      "title": "usesDefaultHyphenation",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle/usesdefaulthyphenation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle": {
      "abstract": [
        {
          "text": "The paragraph or ruler attributes for an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextBlock": {
      "abstract": [
        {
          "text": "A block of text laid out in a subregion of the text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextBlock"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextBlock"
        }
      ],
      "role": "symbol",
      "title": "NSTextBlock",
      "type": "topic",
      "url": "/documentation/appkit/nstextblock"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextList": {
      "abstract": [
        {
          "text": "A section of text that forms a single list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextList"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextList"
        }
      ],
      "role": "symbol",
      "title": "NSTextList",
      "type": "topic",
      "url": "/documentation/appkit/nstextlist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTab": {
      "abstract": [
        {
          "text": "A tab in a paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTab"
        }
      ],
      "role": "symbol",
      "title": "NSTextTab",
      "type": "topic",
      "url": "/documentation/appkit/nstexttab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTable": {
      "abstract": [
        {
          "text": "An object that represents a text table as a whole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTable"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTable"
        }
      ],
      "role": "symbol",
      "title": "NSTextTable",
      "type": "topic",
      "url": "/documentation/appkit/nstexttable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock": {
      "abstract": [
        {
          "text": "A text block that appears as a cell in a text table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTableBlock"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTableBlock"
        }
      ],
      "role": "symbol",
      "title": "NSTextTableBlock",
      "type": "topic",
      "url": "/documentation/appkit/nstexttableblock"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying": {
      "abstract": [
        {
          "text": "A protocol that mutable objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSMutableCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableCopying",
      "type": "topic",
      "url": "/documentation/foundation/nsmutablecopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formatting-and-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
        "doc://com.apple.appkit/documentation/AppKit/NSTextList",
        "doc://com.apple.appkit/documentation/AppKit/NSTextTable",
        "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
        "doc://com.apple.appkit/documentation/AppKit/NSTextBlock"
      ],
      "title": "Formatting and attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-style-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/setParagraphStyle(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/alignment",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/firstLineHeadIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/headIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tailIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineHeightMultiple",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/maximumLineHeight",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/minimumLineHeight",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineSpacing",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/paragraphSpacing",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/paragraphSpacingBefore",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/baseWritingDirection"
      ],
      "title": "Setting style information"
    },
    {
      "anchor": "Specifying-tab-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/addTabStop(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/removeTabStop(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tabStops",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/defaultTabInterval"
      ],
      "title": "Specifying tab information"
    },
    {
      "anchor": "Setting-text-blocks-and-lists",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/textBlocks",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/textLists"
      ],
      "title": "Setting text blocks and lists"
    },
    {
      "anchor": "Setting-line-break-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineBreakMode",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineBreakStrategy",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/hyphenationFactor",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/usesDefaultHyphenation",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation",
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/allowsDefaultTighteningForTruncation"
      ],
      "title": "Setting line-break information"
    },
    {
      "anchor": "Setting-HTML-header-level",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/headerLevel"
      ],
      "title": "Setting HTML header level"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSMutableParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-style-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/setParagraphStyle(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/alignment",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/firstLineHeadIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/headIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tailIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineHeightMultiple",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/maximumLineHeight",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/minimumLineHeight",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineSpacing",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/paragraphSpacing",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/paragraphSpacingBefore",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/baseWritingDirection"
              ],
              "title": "Setting style information"
            },
            {
              "anchor": "Specifying-tab-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/addTabStop(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/removeTabStop(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tabStops",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/defaultTabInterval"
              ],
              "title": "Specifying tab information"
            },
            {
              "anchor": "Setting-text-blocks-and-lists",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/textBlocks",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/textLists"
              ],
              "title": "Setting text blocks and lists"
            },
            {
              "anchor": "Setting-line-break-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineBreakMode",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/lineBreakStrategy",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/hyphenationFactor",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/usesDefaultHyphenation",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/tighteningFactorForTruncation",
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/allowsDefaultTighteningForTruncation"
              ],
              "title": "Setting line-break information"
            },
            {
              "anchor": "Setting-HTML-header-level",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle/headerLevel"
              ],
              "title": "Setting HTML header level"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formatting-and-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
                "doc://com.apple.appkit/documentation/AppKit/NSTextList",
                "doc://com.apple.appkit/documentation/AppKit/NSTextTable",
                "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
                "doc://com.apple.appkit/documentation/AppKit/NSTextBlock"
              ],
              "title": "Formatting and attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSMutableParagraphStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
                    "text": "NSParagraphStyle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/title",
          "value": "NSTextTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1headIndent/title",
          "value": "headIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1headIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1paragraphSpacing/title",
          "value": "paragraphSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1paragraphSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paragraphSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1removeTabStop(_:)/title",
          "value": "removeTabStop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1removeTabStop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeTabStop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1paragraphSpacingBefore/title",
          "value": "paragraphSpacingBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1paragraphSpacingBefore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paragraphSpacingBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1baseWritingDirection/title",
          "value": "baseWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1baseWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "baseWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1headerLevel/title",
          "value": "headerLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1headerLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headerLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/title",
          "value": "NSParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1lineBreakStrategy/title",
          "value": "lineBreakStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1lineBreakStrategy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1textBlocks/title",
          "value": "textBlocks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1textBlocks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textBlocks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle/title",
          "value": "NSMutableParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/title",
          "value": "NSTextTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1lineSpacing/title",
          "value": "lineSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1lineSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextList/title",
          "value": "NSTextList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1alignment/title",
          "value": "alignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1alignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1minimumLineHeight/title",
          "value": "minimumLineHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1minimumLineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumLineHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1setParagraphStyle(_:)/title",
          "value": "setParagraphStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1setParagraphStyle(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setParagraphStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1usesDefaultHyphenation/title",
          "value": "usesDefaultHyphenation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1usesDefaultHyphenation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesDefaultHyphenation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1allowsDefaultTighteningForTruncation/title",
          "value": "allowsDefaultTighteningForTruncation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1allowsDefaultTighteningForTruncation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsDefaultTighteningForTruncation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/title",
          "value": "NSTextTableBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTableBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTableBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1lineBreakMode/title",
          "value": "lineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1lineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextBlock/title",
          "value": "NSTextBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1hyphenationFactor/title",
          "value": "hyphenationFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1hyphenationFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hyphenationFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1addTabStop(_:)/title",
          "value": "addTabStop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1addTabStop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addTabStop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1maximumLineHeight/title",
          "value": "maximumLineHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1maximumLineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumLineHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1textLists/title",
          "value": "textLists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1textLists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textLists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1tabStops/title",
          "value": "tabStops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1tabStops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabStops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1tighteningFactorForTruncation/title",
          "value": "tighteningFactorForTruncation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1tighteningFactorForTruncation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tighteningFactorForTruncation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1defaultTabInterval/title",
          "value": "defaultTabInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1defaultTabInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultTabInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1lineHeightMultiple/title",
          "value": "lineHeightMultiple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1lineHeightMultiple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineHeightMultiple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1tailIndent/title",
          "value": "tailIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1tailIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tailIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1firstLineHeadIndent/title",
          "value": "firstLineHeadIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle~1firstLineHeadIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "firstLineHeadIndent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmutableparagraphstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsmutableparagraphstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
