{
  "abstract": [
    {
      "text": "An outlet connection between Interface Builder objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSNibOutletConnector"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSNibOutletConnector",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSNibOutletConnector"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSNibOutletConnector"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSNibOutletConnector"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSNibOutletConnector"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNibConnector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNibConnector",
              "text": "NSNibConnector"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNib": {
      "abstract": [
        {
          "text": "An object wrapper, or container, for an Interface Builder nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSNib"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNib",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNib"
        }
      ],
      "role": "symbol",
      "title": "NSNib",
      "type": "topic",
      "url": "/documentation/appkit/nsnib"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNibConnector": {
      "abstract": [
        {
          "text": "A connection between two nibs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNibConnector"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNibConnector",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNibConnector",
      "type": "topic",
      "url": "/documentation/appkit/nsnibconnector"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNibControlConnector": {
      "abstract": [
        {
          "text": "A control connection between two Interface Builder objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNibControlConnector"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNibControlConnector",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNibControlConnector",
      "type": "topic",
      "url": "/documentation/appkit/nsnibcontrolconnector"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNibOutletConnector": {
      "abstract": [
        {
          "text": "An outlet connection between Interface Builder objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSNibOutletConnector"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNibOutletConnector",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNibOutletConnector",
      "type": "topic",
      "url": "/documentation/appkit/nsniboutletconnector"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNibOutletConnector/establishConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "establishConnection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNibOutletConnector/establishConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "establishConnection"
        }
      ],
      "role": "symbol",
      "title": "establishConnection",
      "type": "topic",
      "url": "/documentation/appkit/nsniboutletconnector/establishconnection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSNibConnector"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Nib-Files",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSNib",
        "doc://com.apple.appkit/documentation/AppKit/NSNibConnector",
        "doc://com.apple.appkit/documentation/AppKit/NSNibControlConnector"
      ],
      "title": "Nib Files"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSNibOutletConnector/establishConnection"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNib/title",
          "value": "NSNib"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNib/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNib"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNib/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNib"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsniboutletconnector"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
