{
  "abstract": [
    {
      "text": "An object that represents an OpenGL graphics context, into which all OpenGL calls are rendered.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "The OpenGL API is deprecated. Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Metal",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/MetalKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSOpenGLContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSOpenGLContext"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSOpenGLContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "message": "Please use Metal or MetalKit.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSOpenGLContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An OpenGL context is created using an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "object that specifies the context’s buffer types and other attributes. A context can be full-screen, offscreen, or associated with an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. A context draws into its ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "drawable object",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", which is the frame buffer that is the target of OpenGL drawing operations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Every ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object wraps a low-level, platform-specific Core OpenGL (CGL) context. Your application can retrieve the CGL context by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/cglContextObj",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. For more information on the underling CGL context, see ",
              "type": "text"
            },
            {
              "code": "CGL",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep": {
      "abstract": [
        {
          "text": "An object that stores image data in a form that can be readily transferred to the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCachedImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCachedImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nscachedimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDrawer": {
      "abstract": [
        {
          "text": "A user interface element that contains and displays text, scroll, and browser views, in addition to other view subclasses.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDrawer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDrawer"
        }
      ],
      "role": "symbol",
      "title": "NSDrawer",
      "type": "topic",
      "url": "/documentation/appkit/nsdrawer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSForm": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSForm",
          "type": "codeVoice"
        },
        {
          "text": " object is a vertical matrix of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects to implement the fields.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSForm"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSForm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSForm"
        }
      ],
      "role": "symbol",
      "title": "NSForm",
      "type": "topic",
      "url": "/documentation/appkit/nsform"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFormCell": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSFormCell",
          "type": "codeVoice"
        },
        {
          "text": " class is used to implement text entry fields in a form. The left part of an ",
          "type": "text"
        },
        {
          "code": "NSFormCell",
          "type": "codeVoice"
        },
        {
          "text": " object contains a title. The right part contains an editable text entry field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFormCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFormCell"
        }
      ],
      "role": "symbol",
      "title": "NSFormCell",
      "type": "topic",
      "url": "/documentation/appkit/nsformcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInputManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInputManager",
      "type": "topic",
      "url": "/documentation/appkit/nsinputmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputServer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInputServer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputServer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInputServer",
      "type": "topic",
      "url": "/documentation/appkit/nsinputserver"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell": {
      "abstract": [
        {
          "text": "An object that handles the measurement and display of a single menu item in its encompassing frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItemCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItemCell"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItemCell",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMovie": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMovie"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMovie",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMovie",
      "type": "topic",
      "url": "/documentation/appkit/nsmovie"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext": {
      "abstract": [
        {
          "text": "An object that represents an OpenGL graphics context, into which all OpenGL calls are rendered.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLContext"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLContext",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/Parameter": {
      "abstract": [
        {
          "text": "Constants that specify context parameters.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Parameter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/Parameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Parameter"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLContext.Parameter",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/parameter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/cglContextObj": {
      "abstract": [
        {
          "text": "Returns the low-level, platform-specific Core OpenGL (CGL) context object represented by the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cglContextObj"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLContextObj",
          "text": "CGLContextObj"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/cglContextObj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGLContextObj"
        }
      ],
      "role": "symbol",
      "title": "cglContextObj",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/cglcontextobj"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/clearCurrentContext()": {
      "abstract": [
        {
          "text": "Clears the current context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearCurrentContext"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/clearCurrentContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "clearCurrentContext()",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/clearcurrentcontext()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/clearDrawable()": {
      "abstract": [
        {
          "text": "Disassociates the OpenGL context from its viewport.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearDrawable"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/clearDrawable()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearDrawable"
        }
      ],
      "role": "symbol",
      "title": "clearDrawable()",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/cleardrawable()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/copyAttributesFromContext:withMask:": {
      "abstract": [
        {
          "text": "Copies selected groups of state variables to the OpenGL context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "copyAttributesFromContext:withMask:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/copyAttributesFromContext:withMask:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyAttributesFromContext:withMask:"
        }
      ],
      "role": "symbol",
      "title": "copyAttributesFromContext:withMask:",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/copyattributesfromcontext:withmask:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/createTexture:fromView:internalFormat:": {
      "abstract": [
        {
          "text": "Creates a new texture from the contents of the specified view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "createTexture:fromView:internalFormat:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/createTexture:fromView:internalFormat:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createTexture:fromView:internalFormat:"
        }
      ],
      "role": "symbol",
      "title": "createTexture:fromView:internalFormat:",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/createtexture:fromview:internalformat:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/current": {
      "abstract": [
        {
          "text": "Returns the current OpenGL graphics context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "current"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
          "text": "NSOpenGLContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/current",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentContext"
        }
      ],
      "role": "symbol",
      "title": "current",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/current"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/currentVirtualScreen": {
      "abstract": [
        {
          "text": "Returns the current virtual screen for the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentVirtualScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/currentVirtualScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentVirtualScreen"
        }
      ],
      "role": "symbol",
      "title": "currentVirtualScreen",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/currentvirtualscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/flushBuffer()": {
      "abstract": [
        {
          "text": "Copies the back buffer to the front buffer of the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flushBuffer"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/flushBuffer()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flushBuffer"
        }
      ],
      "role": "symbol",
      "title": "flushBuffer()",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/flushbuffer()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/getValues(_:for:)": {
      "abstract": [
        {
          "text": "Returns the value of the requested parameter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
          "text": "NSOpenGLContext"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSOpenGLContextParameter",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/getValues(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getValues:forParameter:"
        }
      ],
      "role": "symbol",
      "title": "getValues(_:for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/getvalues(_:for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/init(cglContextObj:)": {
      "abstract": [
        {
          "text": "Initializes and returns an OpenGL context object using an existing CGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "cglContextObj"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGLContextObj",
          "text": "CGLContextObj"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/init(cglContextObj:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCGLContextObj:"
        }
      ],
      "role": "symbol",
      "title": "init(cglContextObj:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/init(cglcontextobj:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/init(format:share:)": {
      "abstract": [
        {
          "text": "Returns an OpenGL context object initialized with the specified pixel format information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLPixelFormat",
          "text": "NSOpenGLPixelFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "share"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
          "text": "NSOpenGLContext"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/init(format:share:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFormat:shareContext:"
        }
      ],
      "role": "symbol",
      "title": "init(format:share:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/init(format:share:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/makeCurrentContext()": {
      "abstract": [
        {
          "text": "Sets the context as the current OpenGL context object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeCurrentContext"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/makeCurrentContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "makeCurrentContext()",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/makecurrentcontext()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/openGLVersion": {
      "abstract": [
        {
          "text": "The version of OpenGL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openGLVersion"
        },
        {
          "kind": "text",
          "text": ": (major"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ", minor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/openGLVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "openGLVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/openglversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBuffer": {
      "abstract": [
        {
          "text": "Returns the pixel-buffer object attached to the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "pixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "pixelBuffer",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/pixelbuffer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBufferCubeMapFace": {
      "abstract": [
        {
          "text": "Returns the cube map face of the pixel buffer attached to the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "pixelBufferCubeMapFace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBufferCubeMapFace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelBufferCubeMapFace"
        }
      ],
      "role": "symbol",
      "title": "pixelBufferCubeMapFace",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/pixelbuffercubemapface"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBufferMipMapLevel": {
      "abstract": [
        {
          "text": "Returns the mipmap level of the pixel buffer attached to the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "pixelBufferMipMapLevel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBufferMipMapLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelBufferMipMapLevel"
        }
      ],
      "role": "symbol",
      "title": "pixelBufferMipMapLevel",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/pixelbuffermipmaplevel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelFormat": {
      "abstract": [
        {
          "text": "The pixel format of the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLPixelFormat",
          "text": "NSOpenGLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelFormat"
        }
      ],
      "role": "symbol",
      "title": "pixelFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/pixelformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setFullScreen": {
      "abstract": [
        {
          "text": "Sets the OpenGL context to full-screen mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFullScreen"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setFullScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFullScreen"
        }
      ],
      "role": "symbol",
      "title": "setFullScreen",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/setfullscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setOffScreen:width:height:rowbytes:": {
      "abstract": [
        {
          "text": "Instructs the OpenGL context to render into an offscreen buffer with the specified attributes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setOffScreen:width:height:rowbytes:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setOffScreen:width:height:rowbytes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setOffScreen:width:height:rowbytes:"
        }
      ],
      "role": "symbol",
      "title": "setOffScreen:width:height:rowbytes:",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/setoffscreen:width:height:rowbytes:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setPixelBuffer:cubeMapFace:mipMapLevel:currentVirtualScreen:": {
      "abstract": [
        {
          "text": "Attaches the specified pixel buffer to the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setPixelBuffer:cubeMapFace:mipMapLevel:currentVirtualScreen:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setPixelBuffer:cubeMapFace:mipMapLevel:currentVirtualScreen:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPixelBuffer:cubeMapFace:mipMapLevel:currentVirtualScreen:"
        }
      ],
      "role": "symbol",
      "title": "setPixelBuffer:cubeMapFace:mipMapLevel:currentVirtualScreen:",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/setpixelbuffer:cubemapface:mipmaplevel:currentvirtualscreen:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setTextureImageToPixelBuffer:colorBuffer:": {
      "abstract": [
        {
          "text": "Attaches the image data in the specified pixel buffer to the texture object currently bound by the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTextureImageToPixelBuffer:colorBuffer:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setTextureImageToPixelBuffer:colorBuffer:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTextureImageToPixelBuffer:colorBuffer:"
        }
      ],
      "role": "symbol",
      "title": "setTextureImageToPixelBuffer:colorBuffer:",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/settextureimagetopixelbuffer:colorbuffer:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setValues(_:for:)": {
      "abstract": [
        {
          "text": "Sets the value of the specified parameter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GLint",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenGLContext",
          "text": "NSOpenGLContext"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSOpenGLContextParameter",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setValues(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValues:forParameter:"
        }
      ],
      "role": "symbol",
      "title": "setValues(_:for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/setvalues(_:for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/update()": {
      "abstract": [
        {
          "text": "Updates the OpenGL context’s drawable object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/update()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "update"
        }
      ],
      "role": "symbol",
      "title": "update()",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/update()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/view": {
      "abstract": [
        {
          "text": "Returns the OpenGL context’s view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "view"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/view",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "view"
        }
      ],
      "role": "symbol",
      "title": "view",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglcontext/view"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer": {
      "abstract": [
        {
          "text": "A subclass of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that is suitable for rendering OpenGL into layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLLayer"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsopengllayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer": {
      "abstract": [
        {
          "text": "An object that provides access to accelerated offscreen rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLPixelBuffer",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelbuffer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat": {
      "abstract": [
        {
          "text": "An object that specifies the types of buffers and other attributes of the OpenGL context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLPixelFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView": {
      "abstract": [
        {
          "text": "A view that displays OpenGL content in a view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLView"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLView",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/Metal"
    },
    "doc://com.apple.documentation/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/MetalKit"
    },
    "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer": {
      "abstract": [
        {
          "text": "A layer that provides a layer suitable for rendering OpenGL content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAOpenGLLayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAOpenGLLayer",
      "type": "topic",
      "url": "/documentation/QuartzCore/CAOpenGLLayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSLocking": {
      "abstract": [
        {
          "text": "The elementary methods adopted by classes that define lock objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSLocking"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSLocking",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLocking",
      "type": "topic",
      "url": "/documentation/foundation/nslocking"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSLocking",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
        "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
        "doc://com.apple.appkit/documentation/AppKit/NSForm",
        "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Contexts",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/init(format:share:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/init(cglContextObj:)"
      ],
      "title": "Creating Contexts"
    },
    {
      "anchor": "Managing-the-Current-Context",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/clearCurrentContext()",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/current",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/makeCurrentContext()"
      ],
      "title": "Managing the Current Context"
    },
    {
      "anchor": "Managing-the-Drawable-Object",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/view",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/clearDrawable()",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/update()"
      ],
      "title": "Managing the Drawable Object"
    },
    {
      "anchor": "Flushing-the-Drawing-Buffer",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/flushBuffer()"
      ],
      "title": "Flushing the Drawing Buffer"
    },
    {
      "anchor": "Context-Parameter-Handling",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setValues(_:for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/getValues(_:for:)"
      ],
      "title": "Context Parameter Handling"
    },
    {
      "anchor": "Working-with-Virtual-Screens",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/currentVirtualScreen"
      ],
      "title": "Working with Virtual Screens"
    },
    {
      "anchor": "Getting-the-CGL-Context-Object",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/cglContextObj"
      ],
      "title": "Getting the CGL Context Object"
    },
    {
      "anchor": "Getting-the-Pixel-Format",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelFormat"
      ],
      "title": "Getting the Pixel Format"
    },
    {
      "anchor": "Getting-the-OpenGL-Version",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/openGLVersion"
      ],
      "title": "Getting the OpenGL Version"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/Parameter"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSOpenGLContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Contexts",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/init(format:share:)",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/init(cglContextObj:)"
              ],
              "title": "Creating Contexts"
            },
            {
              "anchor": "Managing-the-Current-Context",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/clearCurrentContext()",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/current",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/makeCurrentContext()"
              ],
              "title": "Managing the Current Context"
            },
            {
              "anchor": "Managing-the-Drawable-Object",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/view",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setFullScreen",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setOffScreen:width:height:rowbytes:",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/clearDrawable()",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/update()"
              ],
              "title": "Managing the Drawable Object"
            },
            {
              "anchor": "Flushing-the-Drawing-Buffer",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/flushBuffer()"
              ],
              "title": "Flushing the Drawing Buffer"
            },
            {
              "anchor": "Copying-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/copyAttributesFromContext:withMask:"
              ],
              "title": "Copying Attributes"
            },
            {
              "anchor": "Context-Parameter-Handling",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setValues(_:for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/getValues(_:for:)"
              ],
              "title": "Context Parameter Handling"
            },
            {
              "anchor": "Working-with-Virtual-Screens",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/currentVirtualScreen"
              ],
              "title": "Working with Virtual Screens"
            },
            {
              "anchor": "Creating-Textures",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/createTexture:fromView:internalFormat:"
              ],
              "title": "Creating Textures"
            },
            {
              "anchor": "Getting-the-CGL-Context-Object",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/cglContextObj"
              ],
              "title": "Getting the CGL Context Object"
            },
            {
              "anchor": "Working-with-Pixel-Buffers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setPixelBuffer:cubeMapFace:mipMapLevel:currentVirtualScreen:",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBuffer",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBufferCubeMapFace",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelBufferMipMapLevel",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/setTextureImageToPixelBuffer:colorBuffer:"
              ],
              "title": "Working with Pixel Buffers"
            },
            {
              "anchor": "Getting-the-Pixel-Format",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/pixelFormat"
              ],
              "title": "Getting the Pixel Format"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLContext/Parameter"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSLocking"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLView",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelFormat",
                "doc://com.apple.appkit/documentation/AppKit/NSCachedImageRep",
                "doc://com.apple.appkit/documentation/AppKit/NSDrawer",
                "doc://com.apple.appkit/documentation/AppKit/NSForm",
                "doc://com.apple.appkit/documentation/AppKit/NSFormCell",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuItemCell",
                "doc://com.apple.appkit/documentation/AppKit/NSInputManager",
                "doc://com.apple.appkit/documentation/AppKit/NSInputServer",
                "doc://com.apple.appkit/documentation/AppKit/NSMovie"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSOpenGLContext"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "The OpenGL API is deprecated. Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Metal",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/MetalKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/title",
          "value": "NSOpenGLView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1QuartzCore~1CAOpenGLLayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAOpenGLLayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CALayer",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/title",
          "value": "NSFormCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFormCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFormCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1clearDrawable()/title",
          "value": "clearDrawable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1clearDrawable()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/title",
          "value": "NSForm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSForm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSForm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1flushBuffer()/title",
          "value": "flushBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1flushBuffer()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "flushBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1clearCurrentContext()/title",
          "value": "clearCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1clearCurrentContext()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "clearCurrentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1pixelFormat/title",
          "value": "pixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1pixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/title",
          "value": "NSOpenGLContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1init(cglContextObj:)/title",
          "value": "initWithCGLContextObj:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1init(cglContextObj:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCGLContextObj:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1current/title",
          "value": "currentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1current/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/title",
          "value": "NSOpenGLPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLPixelFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1init(format:share:)/title",
          "value": "initWithFormat:shareContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1init(format:share:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFormat:shareContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/title",
          "value": "NSOpenGLLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/title",
          "value": "NSDrawer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDrawer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1cglContextObj/title",
          "value": "CGLContextObj"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1cglContextObj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGLContextObj"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1view/title",
          "value": "view"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1view/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1makeCurrentContext()/title",
          "value": "makeCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1makeCurrentContext()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeCurrentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1update()/title",
          "value": "update"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1update()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "update"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1Parameter/title",
          "value": "NSOpenGLContextParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1Parameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContextParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1Parameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLContextParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1currentVirtualScreen/title",
          "value": "currentVirtualScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1currentVirtualScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentVirtualScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1getValues(_:for:)/title",
          "value": "getValues:forParameter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1getValues(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getValues:forParameter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/title",
          "value": "NSMenuItemCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1setValues(_:for:)/title",
          "value": "setValues:forParameter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLContext~1setValues(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setValues:forParameter:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsopenglcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsopenglcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
