{
  "abstract": [
    {
      "text": "A set of methods for managing interactions with an open or save panel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSOpenSavePanelDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSOpenSavePanelDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSOpenSavePanelDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSOpenSavePanelDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSOpenSavePanelDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel": {
      "abstract": [
        {
          "text": "A panel that prompts the user to select a file to open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenPanel"
        }
      ],
      "role": "symbol",
      "title": "NSOpenPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsopenpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate": {
      "abstract": [
        {
          "text": "A set of methods for managing interactions with an open or save panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenSavePanelDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenSavePanelDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSOpenSavePanelDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didChangeToDirectoryURL:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user changed the selected directory to the directory located at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didChangeToDirectoryURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didChangeToDirectoryURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panel:didChangeToDirectoryURL:"
        }
      ],
      "role": "symbol",
      "title": "panel(_:didChangeToDirectoryURL:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate/panel(_:didchangetodirectoryurl:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didSelect:)": {
      "abstract": [
        {
          "code": "NSSavePanel",
          "type": "codeVoice"
        },
        {
          "text": ": Optional — Sent when the user changes the current type.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "code": "NSOpenPanel",
          "type": "codeVoice"
        },
        {
          "text": ": Not sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didSelect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panel:didSelectType:"
        }
      ],
      "role": "symbol",
      "title": "panel(_:didSelect:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate/panel(_:didselect:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:displayNameFor:)": {
      "abstract": [
        {
          "code": "NSSavePanel",
          "type": "codeVoice"
        },
        {
          "text": ": Optional — Sent when the content type popup is displayed and the save panel needs the display name for a type. If ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " is returned, the save panel will display type’s ",
          "type": "text"
        },
        {
          "code": "localizedDescription",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "code": "NSOpenPanel",
          "type": "codeVoice"
        },
        {
          "text": ": Not sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayNameFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:displayNameFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panel:displayNameForType:"
        }
      ],
      "role": "symbol",
      "title": "panel(_:displayNameFor:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate/panel(_:displaynamefor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:shouldEnable:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether the specified URL should be enabled in the Open panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:shouldEnable:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panel:shouldEnableURL:"
        }
      ],
      "role": "symbol",
      "title": "panel(_:shouldEnable:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate/panel(_:shouldenable:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:userEnteredFilename:confirmed:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user confirmed a filename choice by clicking Save in a Save panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userEnteredFilename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "confirmed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:userEnteredFilename:confirmed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panel:userEnteredFilename:confirmed:"
        }
      ],
      "role": "symbol",
      "title": "panel(_:userEnteredFilename:confirmed:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate/panel(_:userenteredfilename:confirmed:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:validate:)": {
      "abstract": [
        {
          "text": "Asks the delegate to validate the URL for a file that the user selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "validate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:validate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panel:validateURL:error:"
        }
      ],
      "role": "symbol",
      "title": "panel(_:validate:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate/panel(_:validate:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:willExpand:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the Save panel is about to expand or collapse because the user clicked the disclosure triangle that displays or hides the file browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willExpand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:willExpand:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panel:willExpand:"
        }
      ],
      "role": "symbol",
      "title": "panel(_:willExpand:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate/panel(_:willexpand:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panelSelectionDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user changed the selection in the specified Save panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panelSelectionDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panelSelectionDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panelSelectionDidChange:"
        }
      ],
      "role": "symbol",
      "title": "panelSelectionDidChange(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsopensavepaneldelegate/panelselectiondidchange(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathCell": {
      "abstract": [
        {
          "text": "The user interface of a path control object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathCell"
        }
      ],
      "role": "symbol",
      "title": "NSPathCell",
      "type": "topic",
      "url": "/documentation/appkit/nspathcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel": {
      "abstract": [
        {
          "text": "A panel that prompts the user for information about where to save a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSavePanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSavePanel"
        }
      ],
      "role": "symbol",
      "title": "NSSavePanel",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPathCell"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Open-and-Save-Panels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel"
      ],
      "title": "Open and Save Panels"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-the-Users-Selection",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:userEnteredFilename:confirmed:)"
      ],
      "title": "Responding to the User’s Selection"
    },
    {
      "anchor": "Responding-to-Panel-Changes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panelSelectionDidChange(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didChangeToDirectoryURL:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:willExpand:)"
      ],
      "title": "Responding to Panel Changes"
    },
    {
      "anchor": "Validating-the-Panel-Content",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:shouldEnable:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:validate:)"
      ],
      "title": "Validating the Panel Content"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didSelect:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:displayNameFor:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSOpenSavePanelDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenSavePanelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenSavePanelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-the-Users-Selection",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:userEnteredFilename:confirmed:)"
              ],
              "title": "Responding to the User’s Selection"
            },
            {
              "anchor": "Responding-to-Panel-Changes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panelSelectionDidChange(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didChangeToDirectoryURL:)",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:willExpand:)"
              ],
              "title": "Responding to Panel Changes"
            },
            {
              "anchor": "Validating-the-Panel-Content",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:shouldEnable:)",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:validate:)"
              ],
              "title": "Validating the Panel Content"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:didSelect:)",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenSavePanelDelegate/panel(_:displayNameFor:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPathCell"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Open-and-Save-Panels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel"
              ],
              "title": "Open and Save Panels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSOpenSavePanelDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:shouldEnable:)/title",
          "value": "panel:shouldEnableURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:shouldEnable:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "panel:shouldEnableURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/title",
          "value": "NSSavePanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSavePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSavePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:didChangeToDirectoryURL:)/title",
          "value": "panel:didChangeToDirectoryURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:didChangeToDirectoryURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "panel:didChangeToDirectoryURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate/title",
          "value": "NSOpenSavePanelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenSavePanelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenSavePanelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:userEnteredFilename:confirmed:)/title",
          "value": "panel:userEnteredFilename:confirmed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:userEnteredFilename:confirmed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "panel:userEnteredFilename:confirmed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:didSelect:)/title",
          "value": "panel:didSelectType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:didSelect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "panel:didSelectType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:displayNameFor:)/title",
          "value": "panel:displayNameForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:displayNameFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "panel:displayNameForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panelSelectionDidChange(_:)/title",
          "value": "panelSelectionDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panelSelectionDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "panelSelectionDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/title",
          "value": "NSOpenPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:willExpand:)/title",
          "value": "panel:willExpand:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:willExpand:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "panel:willExpand:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCell/title",
          "value": "NSPathCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:validate:)/title",
          "value": "panel:validateURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenSavePanelDelegate~1panel(_:validate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "panel:validateURL:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsopensavepaneldelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsopensavepaneldelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
