{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/nsopenpanel-deprecated-symbols","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsopenpanel-deprecated-symbols"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsopenpanel-deprecated-symbols"]}],"kind":"article","abstract":[{"type":"text","text":"Review symbols that are no longer supported, and find the replacements to use instead."}],"metadata":{"modules":[{"name":"AppKit"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Deprecated Symbols"},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/runModalForTypes:":{"url":"/documentation/appkit/nsopenpanel/runmodalfortypes:","title":"runModalForTypes:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"runModalForTypes:"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"runModalForTypes:"}],"deprecated":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/runModalForTypes:","abstract":[{"type":"text","text":"Displays the panel and begins a modal event loop that is terminated when the user clicks either OK or Cancel."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/beginSheetForDirectory:file:types:modalForWindow:modalDelegate:didEndSelector:contextInfo:":{"url":"/documentation/appkit/nsopenpanel/beginsheetfordirectory:file:types:modalforwindow:modaldelegate:didendselector:contextinfo:","title":"beginSheetForDirectory:file:types:modalForWindow:modalDelegate:didEndSelector:contextInfo:","fragments":[{"text":"- ","kind":"text"},{"text":"beginSheetForDirectory:file:types:modalForWindow:modalDelegate:didEndSelector:contextInfo:","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"beginSheetForDirectory:file:types:modalForWindow:modalDelegate:didEndSelector:contextInfo:","kind":"identifier"}],"deprecated":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/beginSheetForDirectory:file:types:modalForWindow:modalDelegate:didEndSelector:contextInfo:","abstract":[{"text":"Presents an Open panel as a sheet with the directory specified by ","type":"text"},{"code":"absoluteDirectoryPath","type":"codeVoice"},{"text":" and optionally the file specified by ","type":"text"},{"type":"codeVoice","code":"filename"},{"text":" selected.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens":{"identifier":"doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens","type":"topic","abstract":[{"type":"text","text":"Organize your view hierarchies and facilitate their display onscreen."}],"url":"/documentation/appkit/windows-panels-and-screens","title":"Windows, Panels, and Screens","kind":"article","role":"collectionGroup"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel":{"url":"/documentation/appkit/nsopenpanel","title":"NSOpenPanel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSOpenPanel"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSOpenPanel"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel","abstract":[{"text":"A panel that prompts the user to select a file to open.","type":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/beginForDirectory:file:types:modelessDelegate:didEndSelector:contextInfo:":{"title":"beginForDirectory:file:types:modelessDelegate:didEndSelector:contextInfo:","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/beginForDirectory:file:types:modelessDelegate:didEndSelector:contextInfo:","deprecated":true,"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"beginForDirectory:file:types:modelessDelegate:didEndSelector:contextInfo:","kind":"identifier"}],"abstract":[{"text":"Presents a modeless Open panel.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"beginForDirectory:file:types:modelessDelegate:didEndSelector:contextInfo:","kind":"identifier"}],"url":"/documentation/appkit/nsopenpanel/beginfordirectory:file:types:modelessdelegate:didendselector:contextinfo:"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/filenames":{"type":"topic","kind":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"filenames"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/filenames","url":"/documentation/appkit/nsopenpanel/filenames","title":"filenames","role":"symbol","abstract":[{"text":"Returns an array containing the absolute paths (as NSString objects) of the selected files and directories.","type":"text"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"filenames"}]},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/runModalForDirectory:file:types:":{"deprecated":true,"url":"/documentation/appkit/nsopenpanel/runmodalfordirectory:file:types:","title":"runModalForDirectory:file:types:","kind":"symbol","abstract":[{"text":"Displays the panel and begins a modal event loop that is terminated when the user clicks either OK or Cancel.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/runModalForDirectory:file:types:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"runModalForDirectory:file:types:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"runModalForDirectory:file:types:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/filenames","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/beginForDirectory:file:types:modelessDelegate:didEndSelector:contextInfo:","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/beginSheetForDirectory:file:types:modalForWindow:modalDelegate:didEndSelector:contextInfo:","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/runModalForDirectory:file:types:","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/runModalForTypes:"],"anchor":"Methods","title":"Methods"}],"path":"/topicSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":"NSOpenPanel","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/title","op":"replace"},{"value":[{"text":"NSOpenPanel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/fragments","op":"replace"},{"value":[{"text":"NSOpenPanel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}