{
  "abstract": [
    {
      "text": "An other mouse-dragged event.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSOtherMouseDragged",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSOtherMouseDragged"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSOtherMouseDragged"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSOtherMouseDragged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSEventType",
              "text": "NSEventType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSOtherMouseDragged"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate": {
      "abstract": [
        {
          "text": "A cursor-update event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorUpdate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorUpdate",
      "type": "topic",
      "url": "/documentation/appkit/nscursorupdate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType": {
      "abstract": [
        {
          "text": "Constants for the types of events that responder objects can handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged": {
      "abstract": [
        {
          "text": "The user moved the mouse while holding down a tertiary mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventType/otherMouseDragged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventTypeOtherMouseDragged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventType.otherMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtype/othermousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged": {
      "abstract": [
        {
          "text": "A flags-changed event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFlagsChanged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFlagsChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsflagschanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKeyDown": {
      "abstract": [
        {
          "text": "A key-down event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKeyDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKeyDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKeyDown",
      "type": "topic",
      "url": "/documentation/appkit/nskeydown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKeyUp": {
      "abstract": [
        {
          "text": "A key-up event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKeyUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKeyUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKeyUp",
      "type": "topic",
      "url": "/documentation/appkit/nskeyup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown": {
      "abstract": [
        {
          "text": "A left mouse-down event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged": {
      "abstract": [
        {
          "text": "A left mouse-dragged event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp": {
      "abstract": [
        {
          "text": "A left mouse-up event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseEntered": {
      "abstract": [
        {
          "text": "A mouse-entered event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseEntered"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseEntered",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseEntered",
      "type": "topic",
      "url": "/documentation/appkit/nsmouseentered"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseExited": {
      "abstract": [
        {
          "text": "A mouse-exited event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseExited"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseExited",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseExited",
      "type": "topic",
      "url": "/documentation/appkit/nsmouseexited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseMoved": {
      "abstract": [
        {
          "text": "A mouse-moved event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseMoved"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseMoved",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseMoved",
      "type": "topic",
      "url": "/documentation/appkit/nsmousemoved"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown": {
      "abstract": [
        {
          "text": "An other mouse-down event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsothermousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged": {
      "abstract": [
        {
          "text": "An other mouse-dragged event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDragged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsothermousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp": {
      "abstract": [
        {
          "text": "An other mouse-up event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsothermouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown": {
      "abstract": [
        {
          "text": "A right mouse-down event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseDown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseDown",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmousedown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged": {
      "abstract": [
        {
          "text": "A right mouse-dragged event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseDragged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseDragged",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmousedragged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp": {
      "abstract": [
        {
          "text": "A right mouse-up event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmouseup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDown",
        "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSMouseMoved",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDragged",
        "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDragged",
        "doc://com.apple.appkit/documentation/AppKit/NSMouseEntered",
        "doc://com.apple.appkit/documentation/AppKit/NSMouseExited",
        "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate",
        "doc://com.apple.appkit/documentation/AppKit/NSKeyDown",
        "doc://com.apple.appkit/documentation/AppKit/NSKeyUp",
        "doc://com.apple.appkit/documentation/AppKit/NSFlagsChanged"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDragged/title",
          "value": "NSEventTypeOtherMouseDragged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType~1otherMouseDragged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventTypeOtherMouseDragged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/title",
          "value": "NSEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsothermousedragged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
